# -*- coding: utf-8 -*-
# B1 "conversation with a friend" dialogues. Each language: [line you hear, fitting reply, wrong, wrong, wrong]
TIER = 'B1'
TOPICS = {
    'talk-catching-up': 'Catching Up with a Friend',
    'talk-making-plans': 'Making Plans & Sorting Things Out',
}
DIALOGUES = [
    {"id": "d-b1-01", "topic": "talk-catching-up", "setup": "A friend you haven’t seen in months asks what’s new.",
     "note": "“What have you been up to?” — share recent news, not a fact about the weather.",
     "es": ["¡Cuánto tiempo! ¿Qué has estado haciendo?", "Pues cambié de trabajo hace dos meses y estoy encantado.", "El tren sale a las nueve.", "Prefiero el té al café.", "Está a dos cuadras de aquí."],
     "fr": ["Ça fait un bail ! Qu’est-ce que tu deviens ?", "J’ai changé de boulot il y a deux mois et j’adore.", "Le train part à neuf heures.", "Je préfère le thé au café.", "C’est à deux rues d’ici."],
     "it": ["Da quanto tempo! Che hai fatto di bello?", "Ho cambiato lavoro due mesi fa e sono contentissimo.", "Il treno parte alle nove.", "Preferisco il tè al caffè.", "È a due isolati da qui."],
     "pt": ["Quanto tempo! O que você tem feito?", "Mudei de emprego há dois meses e estou adorando.", "O trem sai às nove.", "Prefiro chá a café.", "Fica a duas quadras daqui."],
     "ja": ["{久|ひさ}しぶり！{最近|さいきん}どうしてた？", "{二|に}か{月前|げつまえ}に{転職|てんしょく}して、すごく{気|き}に{入|い}ってるよ。", "{電車|でんしゃ}は{九時|くじ}に{出|で}ます。", "コーヒーよりお{茶|ちゃ}が{好|す}き。", "ここから{二|に}ブロック{先|さき}だよ。"],
     "zh": ["好久不见！最近在忙什么？", "两个月前换了工作，我很喜欢。", "火车九点出发。", "比起咖啡我更喜欢茶。", "从这儿走两个街区。"]},
    {"id": "d-b1-02", "topic": "talk-catching-up", "setup": "Your friend says they’ve been feeling stressed lately.",
     "note": "Respond to a friend’s stress with empathy, not with an unrelated plan.",
     "es": ["Últimamente estoy muy estresado con el trabajo.", "Lo siento mucho. ¿Quieres hablar de ello?", "Yo compré una bici nueva.", "La película empieza a las ocho.", "Mi hermana vive en Roma."],
     "fr": ["Ces derniers temps, je suis très stressé au boulot.", "Je suis désolé. Tu veux en parler ?", "Moi, j’ai acheté un nouveau vélo.", "Le film commence à huit heures.", "Ma sœur vit à Rome."],
     "it": ["Ultimamente sono stressatissimo per il lavoro.", "Mi dispiace tanto. Vuoi parlarne?", "Io ho comprato una bici nuova.", "Il film inizia alle otto.", "Mia sorella vive a Roma."],
     "pt": ["Ultimamente estou muito estressado com o trabalho.", "Sinto muito. Quer conversar sobre isso?", "Eu comprei uma bicicleta nova.", "O filme começa às oito.", "Minha irmã mora em Roma."],
     "ja": ["{最近|さいきん}、{仕事|しごと}でストレスがすごいんだ。", "それは{大変|たいへん}だね。{話|はな}したい？", "{僕|ぼく}は{新|あたら}しい{自転車|じてんしゃ}を{買|か}ったよ。", "{映画|えいが}は{八時|はちじ}に{始|はじ}まる。", "{妹|いもうと}はローマに{住|す}んでる。"],
     "zh": ["最近工作压力好大。", "真不好受。想聊聊吗？", "我买了辆新自行车。", "电影八点开始。", "我姐姐住在罗马。"]},
    {"id": "d-b1-03", "topic": "talk-catching-up", "setup": "A friend asks how your trip went.",
     "note": "“How was the trip?” — describe the experience.",
     "es": ["¿Qué tal el viaje? ¡Cuéntamelo todo!", "Increíble. La comida, la gente… ya quiero volver.", "Necesito comprar leche.", "Trabajo de nueve a cinco.", "Hace frío en enero."],
     "fr": ["Alors, ce voyage ? Raconte-moi tout !", "Incroyable. La bouffe, les gens… j’ai déjà envie d’y retourner.", "Je dois acheter du lait.", "Je travaille de neuf à cinq.", "Il fait froid en janvier."],
     "it": ["Com’è andato il viaggio? Raccontami tutto!", "Incredibile. Il cibo, la gente… voglio già tornarci.", "Devo comprare il latte.", "Lavoro dalle nove alle cinque.", "Fa freddo a gennaio."],
     "pt": ["E a viagem? Me conta tudo!", "Incrível. A comida, as pessoas… já quero voltar.", "Preciso comprar leite.", "Trabalho das nove às cinco.", "Faz frio em janeiro."],
     "ja": ["{旅行|りょこう}どうだった？{全部|ぜんぶ}{聞|き}かせて！", "{最高|さいこう}だった。{料理|りょうり}も{人|ひと}も…もう{戻|もど}りたいよ。", "{牛乳|ぎゅうにゅう}を{買|か}わないと。", "{九時|くじ}から{五時|ごじ}まで{働|はたら}いてる。", "{一月|いちがつ}は{寒|さむ}い。"],
     "zh": ["旅行怎么样？都跟我讲讲！", "太棒了。吃的、人……我已经想再去了。", "我得买牛奶。", "我朝九晚五上班。", "一月很冷。"]},
    {"id": "d-b1-04", "topic": "talk-catching-up", "setup": "A friend mentions they broke up with their partner.",
     "note": "Break-up news calls for support, not congratulations or logistics.",
     "es": ["Lucía y yo rompimos la semana pasada.", "Vaya, no lo sabía. ¿Cómo estás llevándolo?", "¡Felicidades! Qué buena noticia.", "¿A qué hora quedamos?", "El museo cierra los lunes."],
     "fr": ["Lucie et moi, on a rompu la semaine dernière.", "Oh, je ne savais pas. Tu tiens le coup ?", "Félicitations ! Quelle bonne nouvelle.", "On se retrouve à quelle heure ?", "Le musée ferme le lundi."],
     "it": ["Io e Lucia ci siamo lasciati la settimana scorsa.", "Oh, non lo sapevo. Come la stai prendendo?", "Congratulazioni! Che bella notizia.", "A che ora ci vediamo?", "Il museo chiude il lunedì."],
     "pt": ["Eu e a Lúcia terminamos semana passada.", "Nossa, eu não sabia. Como você está lidando com isso?", "Parabéns! Que ótima notícia.", "A que horas a gente se encontra?", "O museu fecha na segunda."],
     "ja": ["ルシアと{先週|せんしゅう}{別|わか}れたんだ。", "そうだったの、{知|し}らなかった。{大丈夫|だいじょうぶ}？", "おめでとう！いいニュースだね。", "{何時|なんじ}に{会|あ}う？", "{博物館|はくぶつかん}は{月曜|げつよう}{休|やす}みだよ。"],
     "zh": ["我和露西亚上周分手了。", "啊，我不知道。你还好吗？", "恭喜！真是好消息。", "我们几点见？", "博物馆周一闭馆。"]},
    {"id": "d-b1-05", "topic": "talk-catching-up", "setup": "A friend asks whether you’re still going to the gym.",
     "note": "“Are you still…?” — answer about the habit, honestly.",
     "es": ["¿Sigues yendo al gimnasio?", "La verdad, lo dejé. Ahora salgo a correr por las mañanas.", "Sí, el pan está muy rico.", "Vivo en el quinto piso.", "Mañana es martes."],
     "fr": ["Tu vas toujours à la salle ?", "Franchement, j’ai arrêté. Maintenant je cours le matin.", "Oui, le pain est très bon.", "J’habite au cinquième.", "Demain c’est mardi."],
     "it": ["Vai ancora in palestra?", "Sinceramente ho smesso. Adesso corro la mattina.", "Sì, il pane è molto buono.", "Abito al quinto piano.", "Domani è martedì."],
     "pt": ["Você ainda vai à academia?", "Pra ser sincero, parei. Agora corro de manhã.", "Sim, o pão está muito bom.", "Moro no quinto andar.", "Amanhã é terça."],
     "ja": ["まだジムに{通|かよ}ってる？", "{正直|しょうじき}、やめちゃった。{今|いま}は{朝|あさ}{走|はし}ってるよ。", "うん、パンがすごくおいしい。", "{五階|ごかい}に{住|す}んでる。", "{明日|あした}は{火曜日|かようび}。"],
     "zh": ["你还去健身房吗？", "说实话，不去了。现在早上跑步。", "是的，面包很好吃。", "我住五楼。", "明天是星期二。"]},
    {"id": "d-b1-06", "topic": "talk-catching-up", "setup": "Your friend asks your opinion on a show they recommended.",
     "note": "Give an opinion with a reason — that’s what a friend is asking for.",
     "es": ["¿Ya viste la serie que te recomendé? ¿Qué te pareció?", "Me enganchó desde el primer capítulo, aunque el final me decepcionó un poco.", "Cuesta veinte euros.", "Tengo dos gatos.", "El baño está al fondo."],
     "fr": ["T’as vu la série que je t’ai conseillée ? T’en as pensé quoi ?", "Accro dès le premier épisode, même si la fin m’a un peu déçu.", "Ça coûte vingt euros.", "J’ai deux chats.", "Les toilettes sont au fond."],
     "it": ["Hai visto la serie che ti ho consigliato? Che ne pensi?", "Mi ha preso dal primo episodio, anche se il finale mi ha un po’ deluso.", "Costa venti euro.", "Ho due gatti.", "Il bagno è in fondo."],
     "pt": ["Já viu a série que te recomendei? O que achou?", "Me prendeu desde o primeiro episódio, embora o final tenha me decepcionado um pouco.", "Custa vinte euros.", "Tenho dois gatos.", "O banheiro fica no fundo."],
     "ja": ["おすすめしたドラマ{見|み}た？どうだった？", "{一話|いちわ}からハマったよ。{最終回|さいしゅうかい}はちょっとがっかりだったけど。", "{二十|にじゅう}ユーロです。", "{猫|ねこ}を{二匹|にひき}{飼|か}ってる。", "トイレは{奥|おく}だよ。"],
     "zh": ["我推荐的那部剧你看了吗？觉得怎么样？", "第一集就上头了，不过结局有点让我失望。", "二十欧元。", "我养了两只猫。", "洗手间在最里面。"]},

    {"id": "d-b1-07", "topic": "talk-making-plans", "setup": "A friend proposes a hike this weekend but you already have plans.",
     "note": "Decline politely and offer an alternative — that’s how plans get sorted.",
     "es": ["¿Vamos de senderismo el sábado?", "El sábado no puedo, tengo una boda. ¿Te va bien el domingo?", "Sí, me llamo Alex.", "El semáforo está en rojo.", "Este vino es de Chile."],
     "fr": ["On va faire une rando samedi ?", "Samedi je ne peux pas, j’ai un mariage. Dimanche, ça t’irait ?", "Oui, je m’appelle Alex.", "Le feu est rouge.", "Ce vin vient du Chili."],
     "it": ["Andiamo a fare trekking sabato?", "Sabato non posso, ho un matrimonio. Domenica ti va?", "Sì, mi chiamo Alex.", "Il semaforo è rosso.", "Questo vino è cileno."],
     "pt": ["Vamos fazer uma trilha no sábado?", "Sábado não dá, tenho um casamento. Domingo pode ser?", "Sim, meu nome é Alex.", "O sinal está vermelho.", "Esse vinho é do Chile."],
     "ja": ["{土曜日|どようび}にハイキング{行|い}かない？", "{土曜|どよう}は{結婚式|けっこんしき}があって{無理|むり}なんだ。{日曜|にちよう}はどう？", "はい、アレックスです。", "{信号|しんごう}は{赤|あか}だよ。", "このワインはチリ{産|さん}だよ。"],
     "zh": ["周六去徒步吗？", "周六不行，我要参加婚礼。周日可以吗？", "是的，我叫艾利克斯。", "红灯了。", "这酒是智利的。"]},
    {"id": "d-b1-08", "topic": "talk-making-plans", "setup": "A friend is running late and texts you.",
     "note": "Respond to “I’m running late” by adjusting the plan.",
     "es": ["Perdona, voy a llegar quince minutos tarde.", "Tranquilo, te espero en la cafetería de la esquina.", "Me gusta el color azul.", "Hoy hace mucho viento.", "Mi cumpleaños es en mayo."],
     "fr": ["Désolé, je vais avoir quinze minutes de retard.", "Pas de souci, je t’attends au café du coin.", "J’aime bien le bleu.", "Il y a beaucoup de vent aujourd’hui.", "Mon anniversaire est en mai."],
     "it": ["Scusa, arrivo con quindici minuti di ritardo.", "Tranquillo, ti aspetto al bar all’angolo.", "Mi piace il blu.", "Oggi c’è molto vento.", "Il mio compleanno è a maggio."],
     "pt": ["Desculpa, vou chegar quinze minutos atrasado.", "Tranquilo, te espero no café da esquina.", "Eu gosto da cor azul.", "Hoje está ventando muito.", "Meu aniversário é em maio."],
     "ja": ["ごめん、{十五分|じゅうごふん}くらい{遅|おく}れる。", "{大丈夫|だいじょうぶ}、{角|かど}のカフェで{待|ま}ってるよ。", "{青色|あおいろ}が{好|す}き。", "{今日|きょう}は{風|かぜ}が{強|つよ}い。", "{誕生日|たんじょうび}は{五月|ごがつ}だよ。"],
     "zh": ["抱歉，我要晚到十五分钟。", "没事，我在街角的咖啡店等你。", "我喜欢蓝色。", "今天风很大。", "我的生日在五月。"]},
    {"id": "d-b1-09", "topic": "talk-making-plans", "setup": "You’re splitting a restaurant bill with a friend.",
     "note": "Deciding how to pay is part of the plan — pick the reply about the bill.",
     "es": ["¿Dividimos la cuenta o pago yo esta vez?", "Dividamos, pero la próxima invito yo.", "Está lloviendo otra vez.", "Nací en Chicago.", "El autobús pasa cada diez minutos."],
     "fr": ["On partage l’addition ou c’est moi qui paie cette fois ?", "On partage, mais la prochaine c’est pour moi.", "Il pleut encore.", "Je suis né à Chicago.", "Le bus passe toutes les dix minutes."],
     "it": ["Dividiamo il conto o pago io stavolta?", "Dividiamo, ma la prossima offro io.", "Sta piovendo di nuovo.", "Sono nato a Chicago.", "L’autobus passa ogni dieci minuti."],
     "pt": ["A gente racha a conta ou eu pago dessa vez?", "Vamos rachar, mas na próxima eu pago.", "Está chovendo de novo.", "Nasci em Chicago.", "O ônibus passa a cada dez minutos."],
     "ja": ["{割|わ}り{勘|かん}にする？{今回|こんかい}は{僕|ぼく}が{払|はら}う？", "{割|わ}り{勘|かん}にしよう。でも{次|つぎ}は{私|わたし}がおごるね。", "また{雨|あめ}が{降|ふ}ってる。", "シカゴで{生|う}まれました。", "バスは{十分|じゅっぷん}おきに{来|く}る。"],
     "zh": ["我们平摊还是这次我请？", "平摊吧，下次我请你。", "又下雨了。", "我在芝加哥出生。", "公交车每十分钟一趟。"]},
    {"id": "d-b1-10", "topic": "talk-making-plans", "setup": "A friend asks you to help them move next week.",
     "note": "A request for help gets a yes/no with conditions — not a random fact.",
     "es": ["¿Me ayudas con la mudanza el jueves?", "Claro, cuenta conmigo. Salgo del trabajo a las seis, ¿te sirve?", "El queso está en la nevera.", "Aprendo japonés desde hace un año.", "La playa está lejos."],
     "fr": ["Tu peux m’aider à déménager jeudi ?", "Bien sûr, compte sur moi. Je finis à six heures, ça te va ?", "Le fromage est dans le frigo.", "J’apprends le japonais depuis un an.", "La plage est loin."],
     "it": ["Mi dai una mano col trasloco giovedì?", "Certo, contaci. Finisco alle sei, ti va bene?", "Il formaggio è in frigo.", "Studio giapponese da un anno.", "La spiaggia è lontana."],
     "pt": ["Você me ajuda na mudança na quinta?", "Claro, conta comigo. Saio do trabalho às seis, serve?", "O queijo está na geladeira.", "Estudo japonês há um ano.", "A praia é longe."],
     "ja": ["{木曜日|もくようび}、{引|ひ}っ{越|こ}し{手伝|てつだ}ってくれる？", "もちろん。{仕事|しごと}は{六時|ろくじ}に{終|お}わるけど、それで{間|ま}に{合|あ}う？", "チーズは{冷蔵庫|れいぞうこ}にあるよ。", "{一年前|いちねんまえ}から{日本語|にほんご}を{勉強|べんきょう}してる。", "{海|うみ}は{遠|とお}いよ。"],
     "zh": ["周四能帮我搬家吗？", "当然，算我一个。我六点下班，来得及吗？", "奶酪在冰箱里。", "我学日语一年了。", "海滩很远。"]},
    {"id": "d-b1-11", "topic": "talk-making-plans", "setup": "A friend suggests a restaurant but you have a food restriction.",
     "note": "Mention the restriction and steer the plan — the natural move.",
     "es": ["¿Cenamos en el asador nuevo?", "Es que soy vegetariano. ¿Conoces algún sitio con más opciones?", "Los lunes tengo clase de piano.", "La calle está cortada.", "Mi padre es médico."],
     "fr": ["On dîne au nouveau grill ?", "C’est que je suis végétarien. Tu connais un endroit avec plus de choix ?", "Le lundi, j’ai cours de piano.", "La rue est fermée.", "Mon père est médecin."],
     "it": ["Ceniamo alla nuova griglieria?", "Il fatto è che sono vegetariano. Conosci un posto con più scelta?", "Il lunedì ho lezione di piano.", "La strada è chiusa.", "Mio padre è medico."],
     "pt": ["Vamos jantar na churrascaria nova?", "É que eu sou vegetariano. Conhece algum lugar com mais opções?", "Segunda tenho aula de piano.", "A rua está fechada.", "Meu pai é médico."],
     "ja": ["{新|あたら}しい{焼肉屋|やきにくや}で{夕食|ゆうしょく}どう？", "{実|じつ}はベジタリアンなんだ。もっと{選択肢|せんたくし}がある{店|みせ}{知|し}らない？", "{月曜|げつよう}はピアノのレッスンがある。", "その{道|みち}は{通行止|つうこうど}めだよ。", "{父|ちち}は{医者|いしゃ}です。"],
     "zh": ["去新开的烤肉店吃晚饭吗？", "我其实是素食者。你知道选择多一点的地方吗？", "周一我有钢琴课。", "那条街封了。", "我爸爸是医生。"]},
    {"id": "d-b1-12", "topic": "talk-making-plans", "setup": "A friend asks if you can lend them some money until Friday.",
     "note": "Handle a money request directly and kindly.",
     "es": ["¿Me puedes prestar cincuenta euros hasta el viernes?", "Sí, sin problema. Te los paso ahora por transferencia.", "Prefiero la ventana al pasillo.", "Hace sol en la playa.", "Mi abuela tiene ochenta años."],
     "fr": ["Tu peux me prêter cinquante euros jusqu’à vendredi ?", "Oui, pas de problème. Je te fais un virement tout de suite.", "Je préfère la fenêtre au couloir.", "Il fait beau à la plage.", "Ma grand-mère a quatre-vingts ans."],
     "it": ["Mi presti cinquanta euro fino a venerdì?", "Sì, nessun problema. Ti faccio subito un bonifico.", "Preferisco il finestrino al corridoio.", "C’è il sole in spiaggia.", "Mia nonna ha ottant’anni."],
     "pt": ["Pode me emprestar cinquenta euros até sexta?", "Claro, sem problema. Já te faço uma transferência.", "Prefiro a janela ao corredor.", "Está sol na praia.", "Minha avó tem oitenta anos."],
     "ja": ["{金曜|きんよう}まで{五十|ごじゅう}ユーロ{貸|か}してくれる？", "いいよ、{問題|もんだい}ない。{今|いま}すぐ{振|ふ}り{込|こ}むね。", "{通路側|つうろがわ}より{窓側|まどがわ}がいい。", "ビーチは{晴|は}れてる。", "{祖母|そぼ}は{八十歳|はちじゅっさい}です。"],
     "zh": ["能借我五十欧元到周五吗？", "行，没问题。我现在就转给你。", "比起过道我更喜欢靠窗。", "海滩上阳光很好。", "我奶奶八十岁了。"]},
]
