# -*- coding: utf-8 -*-
# Traditional tales of the Japanese-speaking world, retold and graded for the Ship's Library
LANG = 'ja'
FOLK = [
    {
        'id': 'fk-ja-01', 'tier': 'B1', 'title': '{桃太郎|ももたろう}', 'title_en': "Momotaro, the Peach Boy",
        'origin': "Japanese folk tale, Japan",
        'paras': [
            '{昔々|むかしむかし}、おじいさんとおばあさんが{住|す}んでいました。おじいさんは{山|やま}へ{柴刈|しばか}りに、おばあさんは{川|かわ}へ{洗濯|せんたく}に{行|い}きました。おばあさんが{川|かわ}で{洗濯|せんたく}をしていると、{大|おお}きな{桃|もも}が{流|なが}れてきました。',
            'おばあさんはその{桃|もも}を{家|いえ}に{持|も}ち{帰|かえ}りました。おじいさんと{桃|もも}を{切|き}ろうとすると、{中|なか}から{元気|げんき}な{男|おとこ}の{子|こ}が{生|う}まれました。{二人|ふたり}はその{子|こ}を{桃太郎|ももたろう}と{名付|なづ}けました。',
            '{桃太郎|ももたろう}はすくすく{育|そだ}ち、{強|つよ}い{若者|わかもの}になりました。ある{日|ひ}、{桃太郎|ももたろう}は{鬼退治|おにたいじ}に{行|い}くと{言|い}いました。おばあさんはきびだんごを{作|つく}ってあげました。',
            '{桃太郎|ももたろう}は{旅|たび}の{途中|とちゅう}で{犬|いぬ}に{会|あ}いました。{犬|いぬ}はきびだんごをもらって、{家来|けらい}になりました。{同|おな}じように、{猿|さる}と{雉|きじ}も{家来|けらい}になりました。',
            '{桃太郎|ももたろう}と{三匹|さんびき}の{家来|けらい}は{船|ふね}で{鬼|おに}が{島|しま}へ{渡|わた}りました。{島|しま}には{恐|おそ}ろしい{鬼|おに}たちが{住|す}んでいて、{村|むら}から{宝物|たからもの}を{奪|うば}っていました。{桃太郎|ももたろう}たちは{力|ちから}を{合|あ}わせて{鬼|おに}と{戦|たたか}いました。',
            '{犬|いぬ}は{鬼|おに}に{噛|か}みつき、{猿|さる}は{引|ひ}っかき、{雉|きじ}は{目|め}をつつきました。{桃太郎|ももたろう}は{鬼|おに}の{大将|たいしょう}と{戦|たたか}い、ついに{勝|か}ちました。{鬼|おに}たちは{謝|あやま}って、{奪|うば}った{宝物|たからもの}を{返|かえ}しました。',
            '{桃太郎|ももたろう}と{家来|けらい}たちは{宝物|たからもの}を{積|つ}んで{村|むら}へ{帰|かえ}りました。おじいさんとおばあさんはとても{喜|よろこ}びました。それから{村|むら}はいつまでも{平和|へいわ}に{暮|く}らしました。',
        ],
        'paras_en': [
            "Long, long ago, an old man and an old woman lived together. The old man went to the mountain to gather firewood, and the old woman went to the river to do washing. While the old woman was washing clothes in the river, a big peach came floating along.",
            "The old woman brought the peach home. When she and the old man tried to cut it open, a lively baby boy was born from inside. The two of them named the child Momotaro.",
            "Momotaro grew up quickly and became a strong young man. One day, Momotaro said he would go to defeat the ogres. The old woman made him millet dumplings for the journey.",
            "On his journey, Momotaro met a dog. The dog received a millet dumpling and became his follower. In the same way, a monkey and a pheasant also became his followers.",
            "Momotaro and his three followers crossed the sea by boat to Ogre Island. On the island lived fearsome ogres who had been stealing treasure from villages. Momotaro and his friends joined forces and fought the ogres.",
            "The dog bit the ogres, the monkey scratched them, and the pheasant pecked at their eyes. Momotaro fought the chief ogre and finally won. The ogres apologized and returned the treasure they had stolen.",
            "Momotaro and his followers loaded the treasure and returned to the village. The old man and the old woman were overjoyed. After that, the village lived peacefully ever after.",
        ],
        'questions': [
            {'after': 1, 'q': "What did the old woman find while washing clothes in the river?", 'options': ["A big peach", "A small fish", "A wooden box", "A golden coin"], 'correct': 0},
            {'after': 3, 'q': "Which animals had joined Momotaro as followers by this point in the story?", 'options': ["A dog, a cat, and a bird", "A tiger, a monkey, and a crane", "A dog, a monkey, and a pheasant", "A dog, a bear, and a fox"], 'correct': 2},
            {'after': 5, 'q': "How did Momotaro defeat the ogres?", 'options': ["He tricked the ogres into leaving the island", "He fought the chief ogre with his three animal followers and won", "He bought the treasure back from the ogres", "He asked the villagers to fight for him"], 'correct': 1},
            {'after': 6, 'q': "What happened at the end of the story?", 'options': ["The ogres captured Momotaro", "The peach turned into gold", "Momotaro stayed on the island forever", "Momotaro and his followers brought the treasure home and the village lived peacefully"], 'correct': 3},
        ],
    },
    {
        'id': 'fk-ja-02', 'tier': 'B1', 'title': '{浦島太郎|うらしまたろう}', 'title_en': "Urashima Taro",
        'origin': "Japanese folk tale, Japan",
        'paras': [
            'ある{村|むら}に、{浦島太郎|うらしまたろう}という{漁師|りょうし}が{住|す}んでいました。ある{日|ひ}、{太郎|たろう}は{浜辺|はまべ}で{子供|こども}たちが{亀|かめ}をいじめているのを{見|み}つけました。{太郎|たろう}は{亀|かめ}を{助|たす}けて、{海|うみ}に{逃|に}がしてあげました。',
            '{数日後|すうじつご}、{海|うみ}の{上|うえ}であの{亀|かめ}が{現|あらわ}れました。{亀|かめ}は「{助|たす}けてくれたお{礼|れい}に、{竜宮城|りゅうぐうじょう}へお{連|つ}れします」と{言|い}いました。{太郎|たろう}は{亀|かめ}の{背中|せなか}に{乗|の}って、{海|うみ}の{底|そこ}へ{向|む}かいました。',
            '{竜宮城|りゅうぐうじょう}はとても{美|うつく}しい{場所|ばしょ}で、{乙姫|おとひめ}という{姫|ひめ}が{太郎|たろう}を{歓迎|かんげい}しました。{太郎|たろう}はごちそうを{食|た}べたり、{魚|さかな}たちの{踊|おど}りを{見|み}たりして、{楽|たの}しい{時間|じかん}を{過|す}ごしました。',
            'しかし、しばらくすると{太郎|たろう}は{村|むら}のことが{恋|こい}しくなりました。{太郎|たろう}は{乙姫|おとひめ}に{帰|かえ}りたいと{言|い}いました。{乙姫|おとひめ}は「これは{玉手箱|たまてばこ}です。{決|けっ}して{開|あ}けないでください」と{言|い}って、{箱|はこ}を{渡|わた}しました。',
            '{太郎|たろう}は{亀|かめ}に{乗|の}って{村|むら}へ{戻|もど}りました。ところが{村|むら}の{様子|ようす}はすっかり{変|か}わっていて、{知|し}っている{人|ひと}は{誰|だれ}もいませんでした。{太郎|たろう}は{驚|おどろ}いて、あちこち{尋|たず}ねて{回|まわ}りました。',
            '{村人|むらびと}に{聞|き}くと、{浦島太郎|うらしまたろう}という{人|ひと}は{何百年|なんびゃくねん}も{前|まえ}に{海|うみ}へ{出|で}て、それきり{戻|もど}らなかったと{言|い}われました。{竜宮城|りゅうぐうじょう}での{数日|すうじつ}は、{実|じつ}は{地上|ちじょう}の{長|なが}い{年月|としつき}だったのです。',
            '{悲|かな}しくなった{太郎|たろう}は、{約束|やくそく}を{忘|わす}れて{玉手箱|たまてばこ}を{開|あ}けてしまいました。{中|なか}から{白|しろ}い{煙|けむり}が{出|で}てきて、{太郎|たろう}はたちまち{白髪|しらが}のおじいさんになりました。こうして{太郎|たろう}は、{時|とき}の{重|おも}みを{知|し}りました。',
        ],
        'paras_en': [
            "In a certain village lived a fisherman named Urashima Taro. One day, Taro found some children bullying a turtle on the beach. Taro saved the turtle and let it go free in the sea.",
            "A few days later, that same turtle appeared on the surface of the sea. The turtle said, \"As thanks for saving me, I will take you to the Dragon Palace.\" Taro climbed onto the turtle's back and headed down to the bottom of the sea.",
            "The Dragon Palace was a very beautiful place, and a princess named Otohime welcomed Taro. Taro ate a feast and watched the fish dance, spending a happy time there.",
            "But after a while, Taro began to miss his village. He told Otohime he wanted to go home. Otohime said, \"This is a jeweled box. Please never open it,\" and handed him the box.",
            "Taro rode the turtle back to his village. But the village had completely changed, and there was no one he recognized. Taro was startled and went around asking people about it.",
            "When he asked the villagers, he was told that a man named Urashima Taro had gone out to sea hundreds of years ago and never returned. The few days he had spent at the Dragon Palace had actually been a long stretch of years on land.",
            "Saddened, Taro forgot his promise and opened the jeweled box. White smoke poured out, and Taro instantly became a white-haired old man. In this way, Taro learned the weight of time.",
        ],
        'questions': [
            {'after': 1, 'q': "Why did the turtle take Taro to the Dragon Palace?", 'options': ["To punish him for fishing too much", "To thank him for saving its life", "Because it was lost and needed help", "To trade him for treasure"], 'correct': 1},
            {'after': 3, 'q': "What did Otohime give Taro when he decided to leave?", 'options': ["A jeweled box he must never open", "A magic fishing net", "A map back to the village", "A pearl necklace"], 'correct': 0},
            {'after': 5, 'q': "What had really happened during the days Taro spent at the Dragon Palace?", 'options': ["His family had moved away", "The village had been destroyed by a storm", "Nothing had changed at all", "Hundreds of years had passed in his home village"], 'correct': 3},
            {'after': 6, 'q': "What happened when Taro opened the box?", 'options': ["Gold coins spilled out", "The turtle appeared again", "White smoke came out and he instantly turned into an old man", "Nothing happened at all"], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ja-03', 'tier': 'B2', 'title': '{かぐや姫|かぐやひめ}', 'title_en': "Princess Kaguya",
        'origin': "The Tale of the Bamboo Cutter (Taketori Monogatari), Japan, 10th century",
        'paras': [
            '{昔|むかし}、{竹|たけ}を{取|と}って{暮|く}らしを{立|た}てていた{翁|おきな}がいました。ある{日|ひ}、{光|ひか}る{竹|たけ}を{見|み}つけて{中|なか}を{開|あ}けてみると、{小|ちい}さくて{美|うつく}しい{女|おんな}の{子|こ}が{座|すわ}っていました。{翁|おきな}とその{妻|つま}は、この{子|こ}を{我|わ}が{子|こ}として{育|そだ}てることにしました。',
            'それから{竹|たけ}を{取|と}るたびに、{節|ふし}の{中|なか}から{黄金|おうごん}が{見|み}つかるようになり、{夫婦|ふうふ}はしだいに{裕福|ゆうふく}になっていきました。{女|おんな}の{子|こ}は「かぐや{姫|ひめ}」と{名付|なづ}けられ、{驚|おどろ}くほどの{速|はや}さで{育|そだ}ち、この{世|よ}のものとは{思|おも}えないほど{美|うつく}しい{娘|むすめ}になりました。',
            'かぐや{姫|ひめ}の{美|うつく}しさの{噂|うわさ}は{都|みやこ}じゅうに{広|ひろ}まり、{多|おお}くの{貴族|きぞく}たちが{求婚|きゅうこん}にやって{来|き}ました。かぐや{姫|ひめ}は、もし{結婚|けっこん}するとしたら、それぞれに{手|て}に{入|はい}れることが{不可能|ふかのう}に{近|ちか}い{宝物|たからもの}を{持|も}ってくるようにと{条件|じょうけん}を{出|だ}しました。',
            '{求婚者|きゅうこんしゃ}たちは{次々|つぎつぎ}に{挑戦|ちょうせん}しましたが、{誰|だれ}一人として{条件|じょうけん}を{満|み}たすことができませんでした。{中|なか}には{偽物|にせもの}の{宝物|たからもの}を{持|も}ってきて、かぐや{姫|ひめ}を{騙|だま}そうとする{者|もの}さえいました。{最終的|さいしゅうてき}に、{帝|みかど}さえもかぐや{姫|ひめ}に{心|こころ}を{奪|うば}われましたが、{姫|ひめ}はその{求婚|きゅうこん}も{断|ことわ}りました。',
            '{年月|としつき}が{経|た}つにつれ、かぐや{姫|ひめ}は{月|つき}を{見|み}ては{涙|なみだ}を{流|なが}すようになりました。{心配|しんぱい}した{両親|りょうしん}が{理由|りゆう}を{尋|たず}ねると、かぐや{姫|ひめ}はついに、{自分|じぶん}が{本当|ほんとう}は{月|つき}の{都|みやこ}の{人|ひと}であり、もうすぐ{月|つき}へ{帰|かえ}らなければならないと{打|う}ち{明|あ}けました。',
            '{帝|みかど}はかぐや{姫|ひめ}を{月|つき}へ{帰|かえ}したくないと{考|かんが}え、{兵士|へいし}たちに{家|いえ}を{守|まも}らせました。しかし{満月|まんげつ}の{夜|よる}、{月|つき}から{迎|むか}えの{使者|ししゃ}たちが{降|お}りてくると、{兵士|へいし}たちの{力|ちから}はまったく{及|およ}ばず、かぐや{姫|ひめ}は{天|てん}の{羽衣|はごろも}をまとい、この{世|よ}の{記憶|きおく}を{失|うしな}いながら{月|つき}へ{昇|のぼ}っていきました。',
            'かぐや{姫|ひめ}は{去|さ}る{前|まえ}に、{両親|りょうしん}と{帝|みかど}に{不老不死|ふろうふし}の{薬|くすり}を{残|のこ}していきました。しかし{帝|みかど}はかぐや{姫|ひめ}のいないこの{世|よ}で{永遠|えいえん}に{生|い}きることに{意味|いみ}を{感|かん}じられず、その{薬|くすり}を{日本|にほん}で{一番|いちばん}{高|たか}い{山|やま}の{頂上|ちょうじょう}で{燃|も}やすよう{命|めい}じました。それ{以来|いらい}、その{山|やま}は「{不死|ふし}の{山|やま}」、すなわち{富士山|ふじさん}と{呼|よ}ばれるようになったと{伝|つた}えられています。',
        ],
        'paras_en': [
            "Long ago, there was an old bamboo cutter who made his living from bamboo. One day he found a glowing stalk of bamboo, and when he opened it up, a small, beautiful baby girl was sitting inside. The old man and his wife decided to raise the child as their own.",
            "After that, every time he cut bamboo, gold was found inside the stalks, and the couple gradually became wealthy. The girl was named Kaguya-hime, and she grew at an astonishing speed, becoming a young woman so beautiful she seemed not of this world.",
            "Word of Kaguya-hime's beauty spread throughout the capital, and many nobles came to court her. Kaguya-hime set a condition: if she were to marry, each suitor would have to bring her a treasure that was nearly impossible to obtain.",
            "The suitors attempted the challenge one after another, but not a single one could fulfill the condition. Some even tried to deceive Kaguya-hime by bringing fake treasures. In the end, even the Emperor himself fell in love with her, but she refused his proposal too.",
            "As the years passed, Kaguya-hime began to weep whenever she looked at the moon. When her worried parents asked her the reason, she finally confessed that she was truly from the capital of the moon and would soon have to return there.",
            "The Emperor, not wanting to let Kaguya-hime return to the moon, had soldiers guard the house. But on the night of the full moon, when messengers descended from the moon to fetch her, the soldiers' strength was completely useless, and Kaguya-hime, wrapped in a robe of feathers, ascended to the moon, losing all memory of this world.",
            "Before leaving, Kaguya-hime left her parents and the Emperor a potion of eternal life. But the Emperor felt no meaning in living forever in a world without Kaguya-hime, and he ordered the potion to be burned atop the tallest mountain in Japan. It is said that ever since, that mountain has been called the \"Mountain of Immortality\" — Mount Fuji.",
        ],
        'questions': [
            {'after': 1, 'q': "What began happening every time the old man cut bamboo after finding the girl?", 'options': ["The bamboo turned to silver", "The stalks began to glow", "Gold was found inside the stalks", "Nothing unusual happened"], 'correct': 2},
            {'after': 3, 'q': "What condition did Kaguya-hime set for any suitor who wished to marry her?", 'options': ["He had to defeat her in a contest of poetry", "He had to be approved by the Emperor", "He had to wait ten years", "He had to bring her a treasure nearly impossible to obtain"], 'correct': 3},
            {'after': 5, 'q': "What did Kaguya-hime finally confess to her worried parents?", 'options': ["That she was from the moon and would soon have to return there", "That she was secretly in love with the Emperor", "That she wished to marry a suitor after all", "That she was ill and dying"], 'correct': 0},
            {'after': 6, 'q': "According to the tale, why is Mount Fuji said to have gotten its name?", 'options': ["Because Kaguya-hime was born there", "Because the Emperor had the elixir of immortality burned on its summit", "Because the bamboo cutter lived on the mountain", "Because the moon messengers landed there"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ja-04', 'tier': 'B2', 'title': '{鶴|つる}の{恩返|おんがえ}し', 'title_en': "The Crane's Gratitude",
        'origin': "Japanese folk tale, Japan",
        'paras': [
            '{貧|まず}しいけれど{心|こころ}の{優|やさ}しい{男|おとこ}が、{雪|ゆき}の{降|ふ}る{日|ひ}に{罠|わな}にかかった{一羽|いちわ}の{鶴|つる}を{見|み}つけました。{男|おとこ}は{鶴|つる}を{可哀想|かわいそう}に{思|おも}い、{罠|わな}を{外|はず}して{空|そら}へ{逃|に}がしてやりました。',
            'その{夜|よる}、{男|おとこ}の{家|いえ}に{一人|ひとり}の{美|うつく}しい{女性|じょせい}が{訪|おとず}れ、{道|みち}に{迷|まよ}ったので{泊|とめ}めてほしいと{頼|たの}みました。{男|おとこ}が{承知|しょうち}すると、その{女性|じょせい}はやがて{男|おとこ}の{妻|つま}になりました。',
            '{貧|まず}しい{暮|く}らしが{続|つづ}く{中|なか}、{妻|つま}はある{日|ひ}、「{機|はた}を{織|お}りますので、{織|お}っている{間|あいだ}は{決|けっ}して{部屋|へや}を{覗|のぞ}かないでください」と{言|い}いました。{妻|つま}が{織|お}り{上|あ}げた{布|ぬの}はとても{美|うつく}しく、{高|たか}い{値段|ねだん}で{売|う}れました。',
            '{布|ぬの}が{評判|ひょうばん}になると、{村人|むらびと}たちはもっと{織|お}ってほしいと{頼|たの}みました。{妻|つま}は{何度|なんど}も{機|はた}を{織|お}り{続|つづ}けましたが、そのたびに{体|からだ}がやせ{細|ほそ}っていきました。それでも{妻|つま}は{約束|やくそく}を{守|まも}るようにと{夫|おっと}に{頼|たの}みました。',
            'ある{日|ひ}、{好奇心|こうきしん}に{負|ま}けた{男|おとこ}はとうとう{約束|やくそく}を{破|やぶ}って{部屋|へや}を{覗|のぞ}いてしまいました。{中|なか}を{見|み}ると、{一羽|いちわ}の{鶴|つる}が{自分|じぶん}の{羽|はね}を{一本|いっぽん}ずつ{抜|ぬ}いて、それを{糸|いと}にして{布|ぬの}を{織|お}っていました。',
            '{正体|しょうたい}を{見|み}られた{鶴|つる}は、もう{一緒|いっしょ}にはいられないと{男|おとこ}に{告|つ}げました。あの{罠|わな}から{助|たす}けてもらった{鶴|つる}が{恩|おん}を{返|かえ}すために{人間|にんげん}の{姿|すがた}になり、{妻|つま}として{暮|く}らしていたのだと{明|あ}かしました。',
            '{鶴|つる}は{悲|かな}しそうに{男|おとこ}を{見|み}つめたあと、{窓|まど}から{飛|と}び{立|た}ち、{空|そら}の{彼方|かなた}へ{消|き}えていきました。{男|おとこ}は{一人|ひとり}きりになり、{恩|おん}に{報|むく}いようとする{気持|きも}ちを{疑|うたが}うことなく、ただ{信|しん}じて{見守|みまも}ることの{大切|たいせつ}さを、{苦|にが}い{思|おも}いとともに{学|まな}びました。',
        ],
        'paras_en': [
            "A poor but kind-hearted man found a crane caught in a trap on a snowy day. Feeling pity for the crane, the man freed it from the trap and let it fly away into the sky.",
            "That night, a beautiful woman visited the man's house, saying she had lost her way and asking to be allowed to stay. When the man agreed, the woman eventually became his wife.",
            "As their poor life continued, the wife said one day, \"I will weave cloth on the loom, but while I am weaving, please never look into the room.\" The cloth she wove was so beautiful that it sold for a high price.",
            "Once the cloth became well known, the villagers asked for more of it. The wife kept weaving again and again, but each time she grew thinner and more frail. Even so, she asked her husband to keep his promise not to look.",
            "One day, overcome by curiosity, the man finally broke his promise and peeked into the room. Inside, he saw a crane plucking out its own feathers one by one and weaving them into thread to make the cloth.",
            "Having had her true form seen, the crane told the man she could no longer stay with him. She revealed that she was the crane he had once saved from the trap, and that she had taken human form and lived as his wife in order to repay his kindness.",
            "The crane gazed at the man sorrowfully, then flew out the window and vanished into the distant sky. Left alone, the man learned, with bitter regret, how important it is to trust and watch over someone's gratitude without doubting it.",
        ],
        'questions': [
            {'after': 1, 'q': "What did the mysterious woman ask of the man on the night she arrived?", 'options': ["To marry her immediately", "To give her food and money", "To help her find the crane", "To let her stay because she had lost her way"], 'correct': 3},
            {'after': 3, 'q': "What condition did the wife set before she began weaving?", 'options': ["That he must buy her a new loom", "That he must never look into the room while she wove", "That he must never tell anyone about the cloth", "That he must help her weave"], 'correct': 1},
            {'after': 5, 'q': "What did the man discover the wife's true identity to be?", 'options': ["A fox spirit in disguise", "A neighboring village's weaver", "The crane he had once saved from the trap", "A ghost of his late mother"], 'correct': 2},
            {'after': 6, 'q': "How does the story end?", 'options': ["The crane flies away and the man is left alone with regret", "The man and the crane live happily together forever", "The man turns into a crane too", "The villagers punish the man"], 'correct': 0},
        ],
    },
    {
        'id': 'fk-ja-05', 'tier': 'C1', 'title': '{金太郎|きんたろう}', 'title_en': "Kintaro, the Golden Boy",
        'origin': "Japanese folk legend, based on the historical figure Sakata no Kintoki, Japan",
        'paras': [
            '{足柄山|あしがらやま}の{奥深|おくふか}くに、{人並|ひとな}み{外|はず}れた{怪力|かいりき}を{持|も}つ{金太郎|きんたろう}という{少年|しょうねん}が{暮|く}らしていました。{赤|あか}い{腹掛|はらが}けをまとい、{斧|おの}を{肩|かた}に{担|かつ}いで{山中|さんちゅう}を{駆|か}け{回|まわ}るその{姿|すがた}は、{里|さと}の{人々|ひとびと}の{間|あいだ}で{語|かた}り{草|ぐさ}になっていました。',
            '{金太郎|きんたろう}の{遊|あそ}び{相手|あいて}は、{熊|くま}や{猿|さる}、{鹿|しか}といった{山|やま}の{動物|どうぶつ}たちでした。{中|なか}でも{熊|くま}とは{相撲|すもう}を{取|と}るのが{日課|にっか}で、{力自慢|ちからじまん}の{熊|くま}でさえ、{金太郎|きんたろう}に{歯|は}が{立|た}たないことがほとんどでした。',
            'ある{日|ひ}、{都|みやこ}から{一人|ひとり}の{武将|ぶしょう}——{源頼光|みなもとのよりみつ}——が{足柄山|あしがらやま}を{通|とお}りかかり、{金太郎|きんたろう}の{並外|なみはず}れた{力|ちから}と{正直|しょうじき}な{人柄|ひとがら}に{目|め}を{留|と}めました。{頼光|よりみつ}は、これほどの{逸材|いつざい}を{山|やま}に{埋|うず}もれさせておくのは{惜|お}しいと{考|かんが}えました。',
            '{頼光|よりみつ}は{金太郎|きんたろう}の{母|はは}に、{息子|むすこ}を{家来|けらい}として{都|みやこ}へ{連|つ}れて{行|い}きたいと{申|もう}し{出|で}ました。{母|はは}は{一抹|いちまつ}の{寂|さび}しさを{覚|おぼ}えながらも、{息子|むすこ}の{将来|しょうらい}を{思|おも}い、その{申|もう}し{出|で}を{快|こころよ}く{受|う}け{入|い}れました。',
            'こうして{金太郎|きんたろう}は{元服|げんぷく}し、{坂田金時|さかたのきんとき}と{名乗|なの}るようになりました。{都|みやこ}に{上|のぼ}った{金時|きんとき}は{頼光|よりみつ}に{仕|つか}え、{四天王|してんのう}と{呼|よ}ばれる{最強|さいきょう}の{家来|けらい}たちの{一人|ひとり}に{数|かぞ}えられるまでになりました。',
            '{金時|きんとき}が{最|もっと}も{名|な}を{馳|は}せたのは、{京都|きょうと}の{大江山|おおえやま}に{巣食|すく}う{鬼|おに}、{酒呑童子|しゅてんどうじ}{討伐|とうばつ}の{逸話|いつわ}です。{頼光|よりみつ}たちは{酒呑童子|しゅてんどうじ}を{油断|ゆだん}させるために{酒|さけ}を{振|ふ}る{舞|ま}い、{酔|よ}いつぶれたところを{討|う}ち{取|と}ったと{伝|つた}えられています。',
            '{幼少期|ようしょうき}に{山中|さんちゅう}で{培|つちか}った{類|たぐ}い{稀|まれ}な{力|ちから}と、{動物|どうぶつ}たちとの{触|ふ}れ{合|あ}いを{通|とお}して{身|み}につけた{優|やさ}しさは、{都|みやこ}へ{出|で}てからも{金時|きんとき}の{中|なか}で{色褪|いろあ}せることはありませんでした。{今日|きょう}でも、{端午|たんご}の{節句|せっく}には{金太郎|きんたろう}の{人形|にんぎょう}が{飾|かざ}られ、{健|すこ}やかな{成長|せいちょう}を{願|ねが}う{男児|だんじ}たちの{象徴|しょうちょう}とされています。',
        ],
        'paras_en': [
            "Deep in the mountains of Ashigara lived a boy of extraordinary strength named Kintaro. Wearing a red apron and carrying an axe over his shoulder as he ran wild through the mountains, he became something of a legend among the people of the villages below.",
            "Kintaro's playmates were the animals of the mountain — bears, monkeys, and deer. Among them, wrestling with bears was practically a daily routine, and even bears proud of their strength were usually no match for him.",
            "One day, a warrior from the capital — Minamoto no Yorimitsu — happened to pass through Mount Ashigara and took notice of Kintaro's extraordinary strength and honest character. Yorimitsu thought it would be a waste to leave such a talent buried away in the mountains.",
            "Yorimitsu proposed to Kintaro's mother that he take her son to the capital as one of his retainers. Though she felt a pang of loneliness, the mother, thinking of her son's future, gladly accepted the offer.",
            "Thus Kintaro came of age and took the name Sakata no Kintoki. Once in the capital, Kintoki served Yorimitsu and came to be counted among the \"Four Guardian Kings,\" the strongest of his retainers.",
            "Kintoki's greatest claim to fame is the tale of the defeat of Shuten-doji, an ogre lurking on Mount Oe near Kyoto. It is said that Yorimitsu and his men plied the ogre with sake to lower his guard, then struck him down once he was thoroughly drunk.",
            "The rare strength he cultivated in the mountains during childhood, and the gentleness he developed through his bond with animals, never faded within Kintoki even after he went to the capital. Even today, dolls of Kintaro are displayed for the Boys' Festival, serving as a symbol for the healthy growth of young boys.",
        ],
        'questions': [
            {'after': 1, 'q': "What was Kintaro's daily routine with the bears?", 'options': ["Wrestling with them", "Racing them up the mountain", "Feeding them fish", "Teaching them tricks"], 'correct': 0},
            {'after': 3, 'q': "Why did Yorimitsu approach Kintaro's mother?", 'options': ["To buy the family's land", "To warn her that Kintaro was too dangerous", "To offer her a job in the capital", "To ask if he could take her son to the capital as a retainer"], 'correct': 3},
            {'after': 5, 'q': "How did Yorimitsu's men defeat the ogre Shuten-doji, according to the legend?", 'options': ["They challenged him to single combat", "They got him drunk on sake and struck him down while he was defenseless", "They trapped him in a cave", "They tricked him with a magic mirror"], 'correct': 1},
            {'after': 6, 'q': "What does Kintaro symbolize in Japan today?", 'options': ["Good fortune in business", "Protection from ogres", "Healthy growth for young boys, honored with dolls at the Boys' Festival", "Success in archery"], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ja-06', 'tier': 'C2', 'title': '{一寸法師|いっすんぼうし}', 'title_en': "One-Inch Boy",
        'origin': "Japanese folk tale, recorded in the Otogizoshi collection, Japan",
        'paras': [
            '{子|こ}のない{老夫婦|ろうふうふ}が{神仏|しんぶつ}に{祈|いの}り{続|つづ}けたすえ、ついに{授|さず}かったのは、なんとも{奇妙|きみょう}なことに、{指|ゆび}{一本|いっぽん}ほどの{大|おお}きさしかない{男|おとこ}の{子|こ}でした。{夫婦|ふうふ}はそれでもこの{子|こ}を{慈|いつく}しみ、「{一寸法師|いっすんぼうし}」と{名付|なづ}けて{大切|たいせつ}に{育|そだ}てました。',
            'しかし{何年|なんねん}が{過|す}ぎても、{一寸法師|いっすんぼうし}の{背丈|せたけ}は{一寸|いっすん}——{約|やく}三{センチ|せんち}——のまま、いっこうに{伸|の}びる{気配|けはい}がありませんでした。{周囲|しゅうい}の{嘲|あざけ}りをよそに、{一寸法師|いっすんぼうし}は{志|こころざし}だけは{人一倍|ひといちばい}{大|おお}きく、いつか{都|みやこ}で{名|な}を{上|あ}げたいという{野心|やしん}を{胸|むね}に{秘|ひ}めていました。',
            'ある{日|ひ}、{一寸法師|いっすんぼうし}は{両親|りょうしん}に{暇乞|いとまご}いをし、お{椀|わん}を{舟|ふね}に、{箸|はし}を{櫂|かい}に、{針|はり}を{刀|かたな}の{代|か}わりにして、{川|かわ}を{下|くだ}り{都|みやこ}を{目指|めざ}しました。その{出|い}で{立|た}ちの{滑稽|こっけい}さとは{裏腹|うらはら}に、{瞳|ひとみ}には{確|たし}かな{覚悟|かくご}が{宿|やど}っていたといいます。',
            '{都|みやこ}に{辿|たど}り{着|つ}いた{一寸法師|いっすんぼうし}は、ある{公卿|くぎょう}の{屋敷|やしき}に{仕|つか}えることとなり、やがてその{家|いえ}の{姫君|ひめぎみ}に{供|とも}として{付|つ}き{従|したが}うようになりました。{小柄|こがら}な{身|み}でありながら{機転|きてん}が{利|き}き、{立|た}ち{居振|いふる}る{舞|ま}いにも{品|ひん}があったため、{姫君|ひめぎみ}はしだいに{一寸法師|いっすんぼうし}を{信頼|しんらい}するようになりました。',
            '{姫君|ひめぎみ}とともに{寺参|てらまい}りに{出|で}かけたある{日|ひ}、{行|ゆ}く{手|て}を{阻|はば}むように{二匹|にひき}の{鬼|おに}が{現|あらわ}れました。{一寸法師|いっすんぼうし}は{怯|ひる}むことなく{針|はり}の{刀|かたな}を{抜|ぬ}き、{鬼|おに}の{喉元|のどもと}や{目|め}を{狙|ねら}って{果敢|かかん}に{斬|き}りかかりました。',
            '{手|て}を{焼|や}いた{鬼|おに}の{一匹|いっぴき}は、しまいに{一寸法師|いっすんぼうし}を{丸|まる}ごと{飲|の}み{込|こ}んでしまいましたが、{一寸法師|いっすんぼうし}は{鬼|おに}の{腹|はら}の{中|なか}を{針|はり}で{突|つ}き{回|まわ}り、{苦|くる}しみに{耐|た}えかねた{鬼|おに}はとうとう{彼|かれ}を{吐|は}き{出|だ}して{逃|に}げ{去|さ}りました。{慌|あわ}てふためいた{鬼|おに}たちは、その{場|ば}に「{打|う}ち{出|で}の{小槌|こづち}」という{宝物|たからもの}を{置|お}き{忘|わす}れていきました。',
            '{姫君|ひめぎみ}がその{小槌|こづち}を{振|ふ}るたびに、{一寸法師|いっすんぼうし}の{体|からだ}は{見|み}る{見|み}るうちに{人並|ひとな}みの{背丈|せたけ}へと{変|へん}じていきました。{小|ちい}さな{体|からだ}に{見合|みあ}わぬ{大志|たいし}を{抱|いだ}き{続|つづ}けた{一寸法師|いっすんぼうし}は、こうしてついにその{志|こころざし}にふさわしい{姿|すがた}を{手|て}に{入|い}れ、のちに{姫君|ひめぎみ}と{夫婦|ふうふ}の{契|ちぎ}りを{結|むす}んだと{語|かた}り{継|つ}がれています。',
        ],
        'paras_en': [
            "An elderly, childless couple prayed to the gods and buddhas for so long that at last a child was granted to them — though, strangely enough, it was a baby boy no bigger than a single finger. Even so, the couple cherished the child, naming him \"Issun-boshi,\" the One-Inch Boy, and raising him with great care.",
            "Yet years passed, and Issun-boshi's height remained fixed at one inch — about three centimeters — with no sign of growth whatsoever. Undeterred by the mockery of those around him, Issun-boshi harbored an ambition greater than anyone's: a secret longing to one day make a name for himself in the capital.",
            "One day, Issun-boshi took leave of his parents, and using a rice bowl as a boat, chopsticks as oars, and a sewing needle in place of a sword, he set off down the river toward the capital. Despite the comic absurdity of his outfit, it is said that a genuine resolve dwelled in his eyes.",
            "Upon reaching the capital, Issun-boshi came to serve in the mansion of a court noble, and eventually became an attendant to that household's young lady. Small though he was, he proved quick-witted, and his bearing carried such refinement that the lady gradually came to trust him.",
            "One day, while accompanying the lady on a pilgrimage to a temple, two ogres appeared as if to block their path. Without flinching, Issun-boshi drew his needle-sword and boldly struck at the ogres' throats and eyes.",
            "One of the ogres, finding him troublesome, finally swallowed Issun-boshi whole — but Issun-boshi jabbed about inside the ogre's belly with his needle, and unable to bear the pain any longer, the ogre at last spit him out and fled. In their panic, the ogres left behind a treasure called the \"lucky mallet.\"",
            "Each time the lady swung the mallet, Issun-boshi's body visibly transformed, growing before her eyes into an ordinary human height. Issun-boshi, who had clung to ambitions far too great for his tiny body, thus finally obtained a form worthy of his aspirations, and it is told that he later married the lady and lived as her husband.",
        ],
        'questions': [
            {'after': 1, 'q': "What ambition did Issun-boshi secretly hold despite the mockery of others?", 'options': ["A wish to grow taller by magic", "A longing to one day make a name for himself in the capital", "A desire to become a farmer", "A hope to find his birth parents"], 'correct': 1},
            {'after': 3, 'q': "What role did Issun-boshi come to hold in the noble's household?", 'options': ["The head of the household's guards", "A cook in the kitchen", "An attendant trusted by the young lady of the house", "A messenger between villages"], 'correct': 2},
            {'after': 5, 'q': "How did Issun-boshi escape after being swallowed by the ogre?", 'options': ["He jabbed inside the ogre's belly with his needle until it spat him out", "He cut his way out with a sword", "He shrank himself and slipped out", "He was rescued by the lady"], 'correct': 0},
            {'after': 6, 'q': "What did the lucky mallet do for Issun-boshi?", 'options': ["It turned him invisible", "It gave him great wealth", "It transformed him into an ogre", "It made his body grow to an ordinary human height"], 'correct': 3},
        ],
    },
]
