# -*- coding: utf-8 -*-
# Traditional tales of the Polish-speaking world, retold and graded for the Ship's Library
LANG = 'pl'
FOLK = [
    {
        'id': 'fk-pl-01', 'tier': 'B1', 'title': 'Smok Wawelski', 'title_en': 'The Wawel Dragon',
        'origin': 'Polish legend, medieval Krakow',
        'paras': [
            'Dawno temu, w Krakowie, nad rzeką Wisłą, mieszkał straszny smok. Smok mieszkał w jaskini pod wzgórzem Wawel. Codziennie smok wychodził z jaskini i szukał jedzenia.',
            'Smok bardzo lubił jeść owce. Czasem jadł też krowy i konie. Ludzie w Krakowie bali się smoka i chowali zwierzęta.',
            'Król Krak rządził miastem. Król miał dwie córki. Król chciał zabić smoka, ale to było trudne.',
            'Wielu rycerzy próbowało zabić smoka. Smok zabijał rycerzy ogniem. Nikt nie mógł pokonać smoka.',
            'Pewnego dnia przyszedł młody szewc. Szewc nazywał się Skuba. Skuba miał prosty, ale mądry plan.',
            'Skuba wziął owcę i włożył do niej siarkę. Zostawił owcę przed jaskinią smoka. Smok zjadł owcę i poczuł straszne pragnienie.',
            'Smok pił wodę z Wisły bardzo długo. Brzuch smoka pękł i smok zginął. Skuba ożenił się z córką króla i wszyscy żyli szczęśliwie.',
        ],
        'paras_en': [
            "Long ago, in Krakow, by the Vistula river, there lived a terrible dragon. The dragon lived in a cave under Wawel hill. Every day the dragon came out of the cave and looked for food.",
            "The dragon loved to eat sheep. Sometimes he also ate cows and horses. The people of Krakow were afraid of the dragon and hid their animals.",
            "King Krak ruled the city. The king had two daughters. The king wanted to kill the dragon, but it was difficult.",
            "Many knights tried to kill the dragon. The dragon killed the knights with fire. No one could defeat the dragon.",
            "One day a young shoemaker arrived. The shoemaker's name was Skuba. Skuba had a simple but clever plan.",
            "Skuba took a sheep and put sulfur inside it. He left the sheep in front of the dragon's cave. The dragon ate the sheep and felt a terrible thirst.",
            "The dragon drank water from the Vistula for a very long time. The dragon's belly burst and the dragon died. Skuba married the king's daughter and they all lived happily.",
        ],
        'questions': [
            {'after': 1, 'q': 'Where did the dragon live?', 'options': ['In a cave under Wawel hill', 'In the royal castle', 'In a forest', 'In the river itself'], 'correct': 0},
            {'after': 3, 'q': 'Who ruled the city of Krakow?', 'options': ['A council of knights', 'King Krak', 'The shoemaker Skuba', 'A bishop'], 'correct': 1},
            {'after': 5, 'q': 'What was Skuba\'s plan?', 'options': ['Fight the dragon with a sword', 'Trap the dragon in a net', 'Fill a sheep with sulfur for the dragon to eat', 'Poison the river water'], 'correct': 2},
            {'after': 6, 'q': 'How did the dragon die?', 'options': ['A knight killed it with fire', 'It drank so much water that its belly burst', 'The king poisoned it', 'It fell from Wawel hill'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-pl-02', 'tier': 'B1', 'title': 'Złota Kaczka', 'title_en': 'The Golden Duck',
        'origin': 'Warsaw urban legend',
        'paras': [
            'W Warszawie, na Starym Mieście, jest stara kamienica. Pod kamienicą jest głęboka piwnica. W piwnicy mieszka złota kaczka.',
            'Dawno temu żył młody czeladnik ślusarski. Czeladnik chciał zostać mistrzem. Mistrzowie ślusarscy mieli tajne zebrania w nocy.',
            'Pewnej nocy czeladnik ukrył się i patrzył na zebranie. Zobaczył, jak mistrzowie wzywają złe duchy. To była wielka tajemnica.',
            'Mistrzowie zauważyli czeladnika i bardzo się rozgniewali. Rzucili na niego klątwę. Czeladnik zamienił się w złotą kaczkę.',
            'Złota kaczka musiała pilnować skarbu w piwnicy. Skarb składał się ze złota i drogich kamieni. Kaczka czekała na kogoś odważnego.',
            'Wielu ludzi próbowało znaleźć skarb i zdjąć klątwę. Trzeba było przejść trzy trudne próby. Nikomu się to nie udało.',
            'Legenda mówi, że złota kaczka wciąż czeka w piwnicy. Może pewnego dnia ktoś zdejmie klątwę. Wtedy czeladnik znowu stanie się człowiekiem.',
        ],
        'paras_en': [
            "In Warsaw, in the Old Town, there is an old tenement house. Under the house is a deep cellar. In the cellar lives a golden duck.",
            "Long ago there lived a young locksmith's apprentice. The apprentice wanted to become a master. The locksmith masters held secret meetings at night.",
            "One night the apprentice hid and watched the meeting. He saw the masters summoning evil spirits. It was a great secret.",
            "The masters noticed the apprentice and became very angry. They cast a curse on him. The apprentice turned into a golden duck.",
            "The golden duck had to guard a treasure in the cellar. The treasure was made of gold and precious stones. The duck waited for someone brave.",
            "Many people tried to find the treasure and lift the curse. One had to pass three difficult trials. No one succeeded.",
            "Legend says the golden duck still waits in the cellar. Maybe one day someone will lift the curse. Then the apprentice will become a human again.",
        ],
        'questions': [
            {'after': 1, 'q': 'Where does the golden duck live?', 'options': ['In a well outside town', 'In a deep cellar under an old house', 'In a church tower', 'In a forest cave'], 'correct': 1},
            {'after': 3, 'q': 'What did the apprentice see the masters doing at night?', 'options': ['Baking bread', 'Summoning evil spirits', 'Selling treasure', 'Building a house'], 'correct': 1},
            {'after': 5, 'q': 'What must the duck guard?', 'options': ['A collection of old books', 'A treasure of gold and precious stones', 'A magic sword', 'A royal crown'], 'correct': 1},
            {'after': 6, 'q': 'How many difficult trials must be passed to find the treasure?', 'options': ['Two', 'Three', 'Five', 'One'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-pl-03', 'tier': 'B2', 'title': 'Syrenka Warszawska', 'title_en': 'The Warsaw Mermaid',
        'origin': 'Warsaw legend',
        'paras': [
            'Dawno, dawno temu, w falach Wisły pływała piękna syrenka. Przypłynęła z dalekiego Bałtyku i zakochała się w tej rzece. Postanowiła zostać tu na zawsze.',
            'Rybacy, którzy łowili ryby w Wiśle, często słyszeli jej piękny śpiew. Gdyby ktoś usłyszał ten śpiew nocą, poczułby dziwny spokój. Syrenka pomagała rybakom, uwalniając ich sieci z wodorostów.',
            'Pewnego dnia bogaty kupiec zobaczył syrenkę na brzegu rzeki. Zachwycił się jej urodą i złotym głosem. Postanowił schwytać ją i pokazywać za pieniądze.',
            'Kupiec zapłacił rybakom, żeby złapali syrenkę w sieci. Gdyby syrenka nie była tak ufna, nigdy by się nie dała złapać. Zamknęli ją w drewnianej szopie nad brzegiem rzeki.',
            'Syn właściciela szopy usłyszał płacz syrenki. Współczuł jej i wypuścił ją, gdy nikt nie patrzył. W podzięce syrenka obiecała zawsze bronić miasta.',
            'Syrenka wróciła do Wisły, ale nie zapomniała o swojej obietnicy. Kiedy miastu groziło niebezpieczeństwo, wypływała z wodą, trzymając miecz i tarczę. Mieszkańcy Warszawy zaczęli czcić ją jako opiekunkę.',
            'Do dziś syrenka jest symbolem Warszawy. Jej wizerunek z mieczem i tarczą można zobaczyć na herbie miasta. Ludzie wierzą, że nadal strzeże miasta pod powierzchnią rzeki.',
        ],
        'paras_en': [
            "Long, long ago, a beautiful mermaid swam in the waves of the Vistula. She had swum in from the distant Baltic Sea and fallen in love with the river. She decided to stay there forever.",
            "Fishermen who fished in the Vistula often heard her beautiful singing. If someone heard that singing at night, they would feel a strange calm. The mermaid helped the fishermen by freeing their nets from seaweed.",
            "One day a rich merchant saw the mermaid on the riverbank. He was captivated by her beauty and golden voice. He decided to capture her and put her on display for money.",
            "The merchant paid the fishermen to catch the mermaid in a net. If the mermaid had not been so trusting, she would never have been caught. They locked her in a wooden shed by the riverbank.",
            "The shed owner's son heard the mermaid crying. He felt sorry for her and set her free when no one was watching. In gratitude, the mermaid promised to always defend the city.",
            "The mermaid returned to the Vistula, but she did not forget her promise. Whenever the city was in danger, she would rise from the water holding a sword and a shield. The people of Warsaw began to honor her as their protector.",
            "To this day the mermaid is a symbol of Warsaw. Her image with a sword and shield can be seen on the city's coat of arms. People believe she still guards the city beneath the surface of the river.",
        ],
        'questions': [
            {'after': 1, 'q': 'Where did the mermaid come from?', 'options': ['The Baltic Sea', 'The Black Sea', 'A mountain lake', 'The ocean'], 'correct': 0},
            {'after': 3, 'q': "What did the merchant want to do with the mermaid?", 'options': ['Free her immediately', 'Capture her and show her for money', 'Marry her', 'Give her a gift'], 'correct': 1},
            {'after': 5, 'q': 'Who freed the mermaid?', 'options': ['A fisherman', 'The merchant himself', "The shed owner's son", 'A soldier'], 'correct': 2},
            {'after': 6, 'q': 'What does the mermaid carry when defending the city?', 'options': ['A sword and shield', 'A crown and scepter', 'A net and hook', 'A harp and flute'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-pl-04', 'tier': 'B2', 'title': 'Lech, Czech i Rus', 'title_en': 'Lech, Czech and Rus',
        'origin': 'Slavic founding legend',
        'paras': [
            'Legenda głosi, że dawno temu trzej bracia, Lech, Czech i Rus, wędrowali razem w poszukiwaniu nowej ziemi. Chcieli założyć własne państwa dla swoich ludów. Podróżowali wiele dni przez lasy i pola.',
            'Gdy dotarli do rozstaju dróg, bracia postanowili się rozdzielić. Czech skierował się na południe, gdzie znalazł piękną górę i osiedlił się u jej podnóża. Jego lud nazwano później Czechami.',
            'Rus poszedł na wschód, w stronę rozległych stepów i wielkich rzek. Tam założył swoje państwo, które z czasem stało się ojczyzną narodu ruskiego. Gdyby wybrał inny kierunek, historia Europy Wschodniej mogłaby wyglądać inaczej.',
            'Lech wędrował dalej na północ, aż pewnego wieczoru zobaczył wysoki dąb. Na dębie znajdowało się gniazdo orła, oświetlone promieniami zachodzącego słońca. Widok tak go zachwycił, że postanowił się tu zatrzymać.',
            'Lech uznał białego orła za dobry znak od bogów. Postanowił, że w tym miejscu założy swoją siedzibę i nazwie ją Gniezdnem, od słowa "gniazdo". Jego lud zaczęto nazywać Polanami.',
            'Biały orzeł stał się symbolem nowego państwa Lecha. Gdyby nie ten znak, Polska mogłaby mieć zupełnie inny herb. Do dziś biały orzeł widnieje na polskiej fladze i godle.',
            'Trzej bracia rzadko się już spotykali, ale ich ludy zachowały pamięć o wspólnym pochodzeniu. Polacy, Czesi i Rusini do dziś wspominają tę opowieść jako symbol dawnego braterstwa Słowian. Legenda przypomina, że mimo różnych dróg, korzenie pozostają wspólne.',
        ],
        'paras_en': [
            "Legend has it that long ago three brothers, Lech, Czech and Rus, traveled together in search of new land. They wanted to found their own states for their peoples. They journeyed for many days through forests and fields.",
            "When they reached a crossroads, the brothers decided to part ways. Czech headed south, where he found a beautiful mountain and settled at its foot. His people were later named the Czechs.",
            "Rus went east, toward the vast steppes and great rivers. There he founded his state, which in time became the homeland of the Rus' people. Had he chosen a different direction, the history of Eastern Europe might look quite different.",
            "Lech continued wandering north, until one evening he saw a tall oak tree. In the oak was an eagle's nest, lit by the rays of the setting sun. The sight amazed him so much that he decided to stop there.",
            'Lech took the white eagle as a good sign from the gods. He decided that he would found his settlement here and name it Gniezno, from the word "gniazdo" (nest). His people came to be called the Polans.',
            "The white eagle became the symbol of Lech's new state. If not for this sign, Poland might have a completely different coat of arms. To this day the white eagle appears on the Polish flag and emblem.",
            "The three brothers rarely met again, but their peoples kept the memory of their shared origin. Poles, Czechs and Rusyns still recall this story today as a symbol of ancient Slavic brotherhood. The legend reminds us that, despite different paths, the roots remain shared.",
        ],
        'questions': [
            {'after': 1, 'q': 'Why were the three brothers traveling?', 'options': ['To find new land and found their own states', 'To escape a dragon', 'To find treasure', 'To visit a king'], 'correct': 0},
            {'after': 3, 'q': 'Which direction did Rus travel?', 'options': ['West', 'East', 'South', 'North'], 'correct': 1},
            {'after': 5, 'q': "What did Lech name his settlement, and after what word?", 'options': ['Gniezno, after "gniazdo" (nest)', 'Kraków, after "kruk" (raven)', 'Warszawa, after "wars"', 'Poznań, after "poznać" (to know)'], 'correct': 0},
            {'after': 6, 'q': 'What did the white eagle become?', 'options': ["The symbol of Lech's new state, later Poland's emblem", "A symbol of Czech's mountain", "A symbol of Rus's rivers", 'A symbol of bad luck'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-pl-05', 'tier': 'C1', 'title': 'Pan Twardowski', 'title_en': 'Mister Twardowski',
        'origin': 'Polish legend, 16th-century Krakow (Polish counterpart to the Faust legend)',
        'paras': [
            'Pan Twardowski był szlachcicem i czarnoksiężnikiem, który żył podobno za panowania króla Zygmunta Augusta, w szesnastym wieku. Fascynowały go zakazane nauki, alchemia i czarna magia, którym oddawał się z iście renesansową pasją. Krążyły o nim plotki, że potrafi wskrzeszać zmarłych i przepowiadać przyszłość.',
            'Aby zdobyć jeszcze większą moc, Twardowski zawarł pakt z diabłem imieniem Mefistofeles - postać znaną też z niemieckiej legendy o Fauście, choć polska wersja ma swój własny, przewrotny koniec. W zamian za wiedzę i bogactwo miał oddać diabłu swoją duszę. Umowę spisano jednak z pewnym istotnym zastrzeżeniem.',
            'W umowie zapisano, że diabeł będzie mógł zabrać duszę Twardowskiego dopiero w Rzymie. Twardowski, przebiegły jak zawsze, postanowił nigdy w życiu nie postawić stopy w tym mieście. Przez wiele lat żył spokojnie, korzystając ze swojej magicznej wiedzy i unikając Wiecznego Miasta.',
            'Pewnego razu jednak Twardowski zatrzymał się w podkrakowskiej karczmie, która - jak się okazało - nosiła nazwę "Rzym". Diabeł, korzystając z tej sprytnej sztuczki losu, natychmiast się zjawił, aby upomnieć się o zapłatę. Twardowski zrozumiał, że przechytrzył sam siebie.',
            'Gdy diabeł porywał go w powietrze, Twardowski zaczął się modlić i wzywać imienia Matki Boskiej. Moc modlitwy przerwała lot diabła, który w popłochu upuścił czarnoksiężnika. Twardowski zawisł jednak nie na ziemi, lecz na Księżycu.',
            'Od tamtej pory, jak głosi legenda, Pan Twardowski mieszka na Księżycu razem ze swoim wiernym pająkiem. Nazywa się go "polskim człowiekiem na Księżycu", a jego historię przywołuje się, gdy mowa o kimś, kto przechytrzył los, choć nie do końca. Ludowe podanie zyskało też trwały ślad w języku polskim.',
            'Do dziś funkcjonuje powiedzenie "zniknąć jak Twardowski na Księżycu", używane, gdy ktoś nagle i tajemniczo znika. Legenda o Twardowskim inspirowała pisarzy, malarzy i twórców ludowych przez stulecia. Pozostaje jedną z najbardziej znanych polskich opowieści o sprycie, pysze i cenie, jaką się za nie płaci.',
        ],
        'paras_en': [
            "Mister Twardowski was a nobleman and sorcerer who supposedly lived during the reign of King Sigismund Augustus, in the sixteenth century. He was fascinated by forbidden sciences, alchemy and black magic, which he pursued with a truly Renaissance passion. Rumors circulated that he could raise the dead and foretell the future.",
            "To gain even greater power, Twardowski made a pact with a devil named Mephistopheles - a figure also known from the German legend of Faust, though the Polish version has its own, wry ending. In exchange for knowledge and wealth, he was to give the devil his soul. The contract, however, was written with one crucial condition.",
            "The contract stated that the devil could only claim Twardowski's soul in Rome. Twardowski, cunning as ever, resolved never in his life to set foot in that city. For many years he lived peacefully, making use of his magical knowledge and avoiding the Eternal City.",
            'One day, however, Twardowski stopped at an inn near Krakow which, as it turned out, was named "Rome". The devil, seizing on this clever twist of fate, appeared at once to demand payment. Twardowski realized he had outwitted himself.',
            "As the devil carried him up into the air, Twardowski began to pray and call upon the name of the Mother of God. The power of the prayer stopped the devil's flight, who in his panic dropped the sorcerer. Twardowski did not land on the ground, though, but on the Moon.",
            'From that time on, so the legend says, Mister Twardowski lives on the Moon together with his faithful spider. He is called "the Polish man on the Moon", and his story is invoked whenever someone outwits fate, though not entirely. The folk tale also left a lasting mark on the Polish language.',
            'To this day there is a saying, "to vanish like Twardowski on the Moon," used when someone disappears suddenly and mysteriously. The legend of Twardowski has inspired writers, painters and folk artists for centuries. It remains one of the best-known Polish tales about cleverness, pride, and the price paid for them.',
        ],
        'questions': [
            {'after': 1, 'q': 'What was Pan Twardowski said to be able to do?', 'options': ['Fly to other countries', 'Raise the dead and predict the future', 'Turn lead into gold only', 'Speak with animals'], 'correct': 1},
            {'after': 3, 'q': "Under what condition could the devil take Twardowski's soul?", 'options': ['Only in Rome', 'Only at midnight', 'Only if Twardowski married', 'Only in Krakow'], 'correct': 0},
            {'after': 5, 'q': 'Where did Twardowski end up after praying?', 'options': ['Back home safely', 'On the Moon', 'In Rome', 'In the tavern'], 'correct': 1},
            {'after': 6, 'q': 'What Polish expression comes from this legend?', 'options': ['"To vanish like Twardowski on the Moon"', '"To dance like the devil"', '"To pray like a saint"', '"To trade like a merchant"'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-pl-06', 'tier': 'C2', 'title': 'Bazyliszek Warszawski', 'title_en': 'The Basilisk of Warsaw',
        'origin': 'Warsaw legend, Old Town cellars',
        'paras': [
            'W mrokach starej Warszawy, w piwnicach kamienic przy ulicy Krzywe Koło, miało niegdyś czaić się stworzenie tak potworne, że samo jego spojrzenie odbierało życie. Bazyliszek - pół gad, pół kogut, wylężony podobno z jaja zniesionego przez starego koguta - żywił się ciemnością i strachem mieszczan. Kroniki miejskie, na wpół legenda, na wpół przestroga, głoszą, że jego istnienie odkryto przypadkiem, gdy służąca zeszła do piwnicy po sól i już nigdy stamtąd nie wróciła.',
            'Wieść o milczącej śmierci roznosiła się po mieście lotem błyskawicy, siejąc grozę wśród kupców i rzemieślników Starego Miasta. Kolejni odważni - a może tylko nierozważni - mieszkańcy schodzili do piwnicy, by zbadać sprawę, i żaden z nich nie wracał żywy. Rajcy miejscy, zaniepokojeni malejącą liczbą obywateli, ogłosili wysoką nagrodę temu, kto pokona bestię.',
            'Zgłosił się pewien więzień, skazany na śmierć za drobną kradzież, gotów zaryzykować wszystko w zamian za ułaskawienie. Doradzono mu starą, ludową mądrość: bazyliszek zabija spojrzeniem, lecz sam ginie, ujrzawszy własne odbicie. Uzbrojony jedynie w pochodnię i wypolerowane do połysku lustra, skazaniec zszedł w ciemność, niepewny, czy wyjdzie z niej żywy.',
            'W piwnicznym mroku, oświetlonym tylko drżącym płomieniem pochodni, więzień ustawił lustra naprzeciw miejsca, z którego dobiegało ciche, złowrogie syczenie. Bazyliszek, dostrzegłszy w tafli własne, potworne odbicie, wydał z siebie przeraźliwy skrzek, jakby świat sam się nad nim znęcał. Jego ciało skamieniało w mgnieniu oka, zastygając w groteskowej, na zawsze bezruchomej pozie.',
            'Więzień, choć drżący ze strachu, wyszedł z piwnicy o własnych siłach i doniósł rajcom o zwycięstwie. Ułaskawiono go zgodnie z obietnicą, a skamieniałego bazyliszka podobno przez długie lata przechowywano jako osobliwość i przestrogę. Miasto odetchnęło z ulgą, choć plotki o innych, głębszych piwnicach kryjących podobne stwory nigdy do końca nie ucichły.',
            'Historycy spierają się, ile w tej opowieści prawdy, a ile średniowiecznego lęku przed tym, co niewidzialne i podziemne - zarazą, ciemnością, nieznanym. Bazyliszek stał się jednak trwałym elementem warszawskiego folkloru, przywoływanym w kronikach obok smoka wawelskiego czy syrenki znad Wisły. Jego cień, jak twierdzą niektórzy, wciąż kładzie się na najstarszych piwnicach miasta.',
            'Do dziś ulica, przy której miało dojść do tych wydarzeń, nosi ślad tamtej legendy w lokalnej pamięci, choć samego bazyliszka nikt już oczywiście nie widział. Opowieść bywa odczytywana jako przypowieść o odwadze, sprycie i cenie, jaką płaci się za nieostrożną ciekawość. Pozostaje przestrogą - i jednocześnie zaproszeniem - by nie schodzić zbyt pochopnie w mroki, których nie rozumiemy.',
        ],
        'paras_en': [
            "In the shadows of old Warsaw, in the cellars of the houses on Krzywe Koło street, there was once said to lurk a creature so monstrous that its very gaze could take a life. The basilisk - half reptile, half rooster, supposedly hatched from an egg laid by an old rooster - fed on darkness and on the fear of the townsfolk. City chronicles, half legend, half warning, claim its existence was discovered by chance, when a servant girl went down to the cellar for salt and never returned.",
            "News of the silent deaths spread through the city like lightning, sowing dread among the merchants and craftsmen of the Old Town. One brave - or perhaps merely reckless - resident after another went down to the cellar to investigate, and none of them came back alive. The town councilors, alarmed at the shrinking number of citizens, announced a great reward for whoever could defeat the beast.",
            "A certain prisoner, condemned to death for a minor theft, came forward, willing to risk everything in exchange for a pardon. He was given an old piece of folk wisdom: the basilisk kills with its gaze, but dies itself upon seeing its own reflection. Armed only with a torch and mirrors polished to a shine, the condemned man descended into the darkness, unsure whether he would come out of it alive.",
            "In the cellar's gloom, lit only by the trembling flame of the torch, the prisoner set the mirrors up facing the spot from which a quiet, menacing hiss was coming. The basilisk, catching sight of its own monstrous reflection in the glass, let out a terrible shriek, as if the world itself were tormenting it. Its body turned to stone in the blink of an eye, freezing forever into a grotesque, motionless pose.",
            "The prisoner, though trembling with fear, walked out of the cellar under his own power and reported his victory to the councilors. He was pardoned as promised, and the petrified basilisk was reportedly kept for many years afterward as a curiosity and a warning. The city breathed a sigh of relief, though rumors of other, deeper cellars hiding similar creatures never entirely died away.",
            "Historians disagree over how much truth lies in this tale, and how much reflects a medieval fear of what is invisible and lies underground - plague, darkness, the unknown. Nonetheless the basilisk became a lasting fixture of Warsaw folklore, invoked in chronicles alongside the Wawel dragon or the mermaid of the Vistula. Its shadow, some claim, still falls upon the oldest cellars of the city.",
            "To this day the street where these events supposedly took place bears the trace of that legend in local memory, though no one, of course, has seen the basilisk itself since. The tale is sometimes read as a parable about courage, cunning, and the price paid for careless curiosity. It remains a warning - and, at the same time, an invitation - not to descend too rashly into the darknesses we do not understand.",
        ],
        'questions': [
            {'after': 1, 'q': 'What was the basilisk supposedly hatched from?', 'options': ['An egg laid by an old rooster', "A witch's curse", "A dragon's tooth", 'A cursed well'], 'correct': 0},
            {'after': 3, 'q': "What weakness did folk wisdom say the basilisk had?", 'options': ['It dies seeing its own reflection', 'It fears fire', 'It cannot cross water', 'It sleeps during the day'], 'correct': 0},
            {'after': 5, 'q': 'What happened to the prisoner after defeating the basilisk?', 'options': ['He was executed anyway', 'He was pardoned as promised', 'He became mayor', 'He fled the city'], 'correct': 1},
            {'after': 6, 'q': 'Alongside which other legends is the basilisk mentioned in chronicles?', 'options': ['The Wawel dragon and the Warsaw mermaid', 'Pan Twardowski and Janosik', 'Lech and Czech', 'The Golden Duck and Krak'], 'correct': 0},
        ],
    },
]
