# -*- coding: utf-8 -*-
# Traditional tales of the Indonesian-speaking world, retold and graded for the Ship's Library
LANG = 'ind'
FOLK = [
    {
        'id': 'fk-ind-01', 'tier': 'B1', 'title': 'Kancil dan Buaya', 'title_en': 'The Mouse-Deer and the Crocodiles',
        'origin': 'Kancil (mouse-deer) tales, oral tradition, Indonesia and the Malay Archipelago',
        'paras': [
            'Di tepi hutan, hidup seekor kancil yang cerdik. Ia ingin menyeberangi sungai untuk memakan buah di seberang. Sungai itu penuh dengan buaya yang lapar.',
            'Kancil lalu memikirkan sebuah akal. Ia berkata kepada buaya, "Raja hutan mengirim aku untuk menghitung jumlah kalian." Buaya-buaya itu senang karena merasa penting.',
            '"Berbarislah dari tepi sungai ini sampai ke seberang," kata kancil. Semua buaya pun berbaris rapi membentuk jembatan hidup. Kancil mulai melompat dari punggung satu buaya ke buaya lain sambil menghitung.',
            '"Satu, dua, tiga, empat..." kancil menghitung dengan keras. Buaya-buaya itu diam saja, menunggu giliran dihitung. Mereka tidak curiga sedikit pun.',
            'Ketika kancil sampai di buaya terakhir, ia melompat ke tepi sungai seberang. Ia tertawa dan berkata, "Terima kasih, aku hanya butuh jembatan!" Buaya-buaya itu marah karena tertipu.',
            'Namun kancil sudah aman di seberang sungai. Ia makan buah-buahan segar dengan tenang. Sejak hari itu, buaya-buaya selalu waspada terhadap kancil.',
            'Cerita kancil dan buaya diceritakan turun-temurun di banyak daerah Indonesia. Kancil menjadi lambang kecerdikan yang mengalahkan kekuatan. Anak-anak belajar bahwa akal bisa lebih kuat daripada otot.',
        ],
        'paras_en': [
            'At the edge of the forest lived a clever mouse-deer. It wanted to cross the river to eat fruit on the other side. The river was full of hungry crocodiles.',
            'The mouse-deer then thought of a trick. It said to the crocodiles, "The king of the forest sent me to count how many of you there are." The crocodiles were pleased because they felt important.',
            '"Line up from this riverbank all the way to the other side," said the mouse-deer. All the crocodiles lined up neatly, forming a living bridge. The mouse-deer began hopping from one crocodile\'s back to the next, counting as it went.',
            '"One, two, three, four..." the mouse-deer counted loudly. The crocodiles just stayed still, waiting their turn to be counted. They did not suspect a thing.',
            'When the mouse-deer reached the last crocodile, it leapt onto the far riverbank. It laughed and said, "Thank you, I only needed a bridge!" The crocodiles were furious at being tricked.',
            'But the mouse-deer was already safe on the other side of the river. It calmly ate the fresh fruit. From that day on, the crocodiles were always wary of the mouse-deer.',
            'The story of the mouse-deer and the crocodiles has been told for generations across many regions of Indonesia. The mouse-deer became a symbol of cleverness overcoming brute strength. Children learn that wit can be stronger than muscle.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did the mouse-deer want to cross the river?', 'options': ['To eat fruit on the other side', 'To visit relatives', 'To escape a storm', 'To find water to drink'], 'correct': 0},
            {'after': 3, 'q': 'What trick did the mouse-deer use to cross the river?', 'options': ['It swam quickly past the crocodiles', 'It asked the crocodiles to line up so it could count them', 'It built a wooden raft', 'It waited until the crocodiles fell asleep'], 'correct': 1},
            {'after': 5, 'q': 'How did the crocodiles feel when they realized they had been tricked?', 'options': ['Amused', 'Grateful', 'Furious', 'Indifferent'], 'correct': 2},
            {'after': 6, 'q': 'What does the mouse-deer come to symbolize in the story?', 'options': ['Physical strength', 'Cleverness overcoming strength', 'Cowardice', 'Cruelty'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ind-02', 'tier': 'B1', 'title': 'Timun Mas', 'title_en': 'Golden Cucumber',
        'origin': 'Javanese folk tale, Indonesia',
        'paras': [
            'Dahulu kala, hiduplah seorang janda bernama Mbok Sirni. Ia sangat ingin memiliki anak tetapi belum juga dikaruniai. Suatu hari, seorang raksasa memberinya biji mentimun ajaib.',
            'Raksasa itu berkata, "Tanamlah biji ini, dan kau akan mendapatkan seorang anak perempuan." Namun ada syaratnya: ketika anak itu berusia tujuh belas tahun, ia harus diserahkan kepada raksasa. Mbok Sirni menyetujui syarat itu karena sangat ingin punya anak.',
            'Biji itu tumbuh menjadi buah mentimun emas yang besar. Di dalamnya, Mbok Sirni menemukan bayi perempuan yang cantik. Ia menamainya Timun Mas dan membesarkannya dengan penuh kasih sayang.',
            'Timun Mas tumbuh menjadi gadis yang cerdas dan baik hati. Namun waktu terus berjalan, dan hari yang ditakutkan pun mendekat. Mbok Sirni sangat sedih memikirkan janji kepada raksasa.',
            'Seorang petapa memberi Mbok Sirni empat bungkusan ajaib untuk Timun Mas: biji timun, jarum, garam, dan terasi. "Lemparkan satu per satu saat raksasa mengejar," pesan petapa itu. Ketika raksasa datang menagih janji, Timun Mas pun lari sambil membawa bungkusan itu.',
            'Biji timun yang dilempar tumbuh menjadi ladang mentimun yang menghambat raksasa. Jarum berubah menjadi hutan bambu berduri. Garam menjadi lautan luas, dan terasi menjadi lumpur panas yang menenggelamkan raksasa itu.',
            'Timun Mas akhirnya selamat dan kembali ke pelukan ibunya. Mereka hidup bahagia tanpa rasa takut lagi. Kisah ini mengajarkan bahwa kecerdikan dan kesiapan bisa mengalahkan kejahatan.',
        ],
        'paras_en': [
            'Long ago, there lived a widow named Mbok Sirni. She longed to have a child but had not yet been blessed with one. One day, a giant gave her a magic cucumber seed.',
            'The giant said, "Plant this seed, and you will get a daughter." But there was a condition: when the child turned seventeen, she had to be handed over to the giant. Mbok Sirni agreed to the condition because she wanted a child so badly.',
            'The seed grew into a huge golden cucumber. Inside it, Mbok Sirni found a beautiful baby girl. She named her Timun Mas and raised her with great love.',
            "Timun Mas grew into a clever, kind-hearted girl. But time kept passing, and the dreaded day drew near. Mbok Sirni grew very sad thinking about her promise to the giant.",
            'A hermit gave Mbok Sirni four magic bundles for Timun Mas: cucumber seeds, a needle, salt, and shrimp paste. "Throw them one by one when the giant chases you," the hermit advised. When the giant came to collect his due, Timun Mas ran off carrying the bundles.',
            "The cucumber seeds she threw grew into a cucumber field that blocked the giant's path. The needle turned into a forest of thorny bamboo. The salt became a vast sea, and the shrimp paste became boiling mud that swallowed the giant.",
            "Timun Mas finally made it to safety and returned to her mother's arms. They lived happily without fear ever again. This tale teaches that cleverness and preparation can defeat evil.",
        ],
        'questions': [
            {'after': 1, 'q': 'What did the giant give Mbok Sirni?', 'options': ['A bag of gold', 'A magic cucumber seed', 'A pair of magic shoes', 'A talking bird'], 'correct': 1},
            {'after': 3, 'q': 'What did Mbok Sirni find inside the golden cucumber?', 'options': ['A baby boy', 'A chest of jewels', 'A baby girl', 'A magic sword'], 'correct': 2},
            {'after': 5, 'q': 'What did the hermit give Timun Mas to escape the giant?', 'options': ['Four magic bundles: cucumber seeds, a needle, salt, and shrimp paste', 'A magic cloak of invisibility', 'A flying horse', 'A map to a hidden cave'], 'correct': 0},
            {'after': 6, 'q': 'What happened to the giant in the end?', 'options': ["He became Timun Mas's friend", 'He was swallowed by boiling mud', 'He turned to stone', 'He fled to another kingdom'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ind-03', 'tier': 'B2', 'title': 'Malin Kundang', 'title_en': 'Malin Kundang',
        'origin': 'Minangkabau legend, West Sumatra, Indonesia',
        'paras': [
            'Malin Kundang adalah anak seorang nelayan miskin di pesisir Sumatra. Ia tumbuh bersama ibunya yang bekerja keras seorang diri, karena ayahnya telah lama meninggal di laut. Meskipun hidup serba kekurangan, ibunya selalu memastikan Malin tidak pernah kelaparan.',
            'Ketika dewasa, Malin memutuskan untuk merantau mencari peruntungan di kapal dagang. Ibunya melepasnya dengan berat hati sambil berpesan agar ia selalu mengingat asal-usulnya. Bertahun-tahun berlalu tanpa kabar apa pun dari Malin.',
            'Malin akhirnya menjadi saudagar kaya dan menikahi seorang wanita bangsawan. Suatu hari, kapalnya berlabuh di kampung halamannya sendiri. Berita kedatangan saudagar kaya itu segera tersebar hingga terdengar oleh ibunya yang sudah renta.',
            'Dengan hati yang penuh rindu, sang ibu bergegas menemui kapal itu. Namun ketika ia memeluk Malin di depan umum, Malin justru mendorongnya dan berpura-pura tidak mengenalinya. Ia malu karena istrinya melihat penampilan ibunya yang lusuh.',
            '"Perempuan tua ini bukan ibuku!" seru Malin dengan angkuh di hadapan semua orang. Hati sang ibu hancur mendengar penolakan anak yang telah dibesarkannya dengan susah payah. Dengan air mata bercampur amarah, ia pun berdoa memohon keadilan kepada Tuhan.',
            'Tidak lama setelah kapal Malin berlayar meninggalkan pantai, langit tiba-tiba menjadi gelap dan badai dahsyat datang. Petir menyambar kapal itu hingga hancur berkeping-keping. Malin perlahan berubah menjadi batu, sebagai kutukan atas kedurhakaannya.',
            'Batu berbentuk manusia yang menyerupai Malin masih dapat dilihat di pantai Air Manis, Padang, hingga sekarang. Masyarakat setempat menyebutnya "Batu Malin Kundang". Kisah ini menjadi peringatan turun-temurun tentang bahaya durhaka kepada orang tua.',
        ],
        'paras_en': [
            "Malin Kundang was the son of a poor fisherman on the coast of Sumatra. He grew up with his mother, who worked hard alone, since his father had died at sea long before. Although they lived in poverty, his mother always made sure Malin never went hungry.",
            "When he grew up, Malin decided to go abroad to seek his fortune on a trading ship. His mother saw him off with a heavy heart, telling him to always remember where he came from. Years passed without any news from Malin at all.",
            'Malin eventually became a wealthy merchant and married a noblewoman. One day, his ship docked in his own home village. News of the wealthy merchant\'s arrival soon spread and reached his now-elderly mother.',
            "With a heart full of longing, his mother hurried to the ship. But when she embraced Malin in public, he instead pushed her away and pretended not to recognize her. He was ashamed because his wife saw his mother's shabby appearance.",
            '"This old woman is not my mother!" Malin shouted arrogantly in front of everyone. His mother\'s heart was shattered by the rejection from the son she had raised with such difficulty. With tears mixed with anger, she prayed to God for justice.',
            "Soon after Malin's ship sailed away from the shore, the sky suddenly darkened and a fierce storm arrived. Lightning struck the ship until it broke into pieces. Malin slowly turned to stone, cursed for his disrespect toward his mother.",
            'A stone shaped like a human, resembling Malin, can still be seen on Air Manis beach in Padang today. Locals call it "Batu Malin Kundang," the Malin Kundang Stone. The tale has become a lasting warning about the danger of disrespecting one\'s parents.',
        ],
        'questions': [
            {'after': 1, 'q': "Why did Malin's mother have to work hard alone?", 'options': ['Malin refused to help her', 'His father had died at sea', 'She wanted to buy a house', 'She was saving for a trip'], 'correct': 1},
            {'after': 3, 'q': "What had Malin become by the time his ship returned to his village?", 'options': ['A poor fisherman like his father', 'A wealthy merchant married to a noblewoman', 'A ship\'s captain with no family', 'A famous storyteller'], 'correct': 1},
            {'after': 5, 'q': "How did Malin react when his mother came to embrace him?", 'options': ['He happily introduced her to his wife', 'He denied that she was his mother', 'He invited her aboard the ship', 'He wept with joy'], 'correct': 1},
            {'after': 6, 'q': "What happened to Malin as a result of his mother's curse?", 'options': ['He became rich beyond measure', 'He turned to stone in a storm', 'He was banished from the village', 'He lost his memory'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ind-04', 'tier': 'B2', 'title': 'Bawang Merah dan Bawang Putih', 'title_en': 'Shallot and Garlic',
        'origin': 'Indonesian/Malay folk tale (Cinderella-type), Indonesia',
        'paras': [
            'Bawang Putih adalah gadis yatim yang tinggal bersama ibu tiri dan saudara tirinya, Bawang Merah. Sejak ayahnya meninggal, Bawang Putih diperlakukan seperti pembantu di rumahnya sendiri. Sementara itu, Bawang Merah selalu dimanjakan dan tidak pernah diberi pekerjaan rumah.',
            'Suatu hari, ibu tiri menyuruh Bawang Putih mencuci pakaian di sungai yang jauh dari rumah. Malangnya, salah satu kain milik ibu tirinya hanyut terbawa arus. Karena takut dimarahi, Bawang Putih menyusuri sungai untuk mencarinya.',
            'Di tepi sungai, ia bertemu seorang nenek tua yang menyimpan kain itu. Nenek itu bersedia mengembalikannya dengan satu syarat: Bawang Putih harus membantunya mengurus rumah selama beberapa hari. Bawang Putih setuju dan bekerja dengan tulus tanpa mengeluh.',
            'Sebagai balasan, nenek itu memberikan Bawang Putih dua buah labu untuk dipilih, satu besar dan satu kecil. Dengan rendah hati, Bawang Putih memilih labu yang kecil. Ketika dibelah di rumah, labu kecil itu ternyata penuh berisi emas dan permata.',
            'Melihat kekayaan itu, ibu tiri dan Bawang Merah menjadi iri hati. Bawang Merah pun sengaja pergi ke sungai yang sama dan membuang kainnya sendiri ke air. Ia menemui nenek tua itu dan berpura-pura baik hati agar mendapat imbalan serupa.',
            'Namun sikap Bawang Merah kasar dan malas selama bekerja di rumah nenek itu. Ketika diberi pilihan labu, ia dengan serakah memilih labu yang paling besar. Sesampainya di rumah, labu besar itu justru dipenuhi ular dan binatang berbisa.',
            'Kisah ini mengajarkan bahwa ketulusan dan kerendahan hati akan membawa berkah, sementara keserakahan hanya mendatangkan celaka. Cerita Bawang Merah dan Bawang Putih tetap dikisahkan kepada anak-anak di seluruh Nusantara hingga kini.',
        ],
        'paras_en': [
            "Bawang Putih was an orphaned girl who lived with her stepmother and stepsister, Bawang Merah. After her father's death, Bawang Putih was treated like a servant in her own home. Meanwhile, Bawang Merah was always pampered and never given any housework.",
            "One day, the stepmother sent Bawang Putih to wash clothes in a river far from the house. Unfortunately, one of her stepmother's cloths was swept away by the current. Afraid of being scolded, Bawang Putih followed the river to search for it.",
            "On the riverbank, she met an old woman who had kept the cloth. The old woman agreed to return it on one condition: Bawang Putih had to help her with housework for several days. Bawang Putih agreed and worked sincerely without complaint.",
            "In return, the old woman offered Bawang Putih a choice between two pumpkins, one large and one small. Humbly, Bawang Putih chose the small one. When it was cut open at home, the small pumpkin turned out to be full of gold and jewels.",
            "Seeing this wealth, the stepmother and Bawang Merah grew jealous. Bawang Merah deliberately went to the same river and threw her own cloth into the water. She found the old woman and pretended to be kind in hopes of receiving the same reward.",
            "But Bawang Merah was rude and lazy while working in the old woman's house. When offered the choice of pumpkins, she greedily picked the largest one. Once home, the big pumpkin turned out to be filled with snakes and venomous creatures.",
            'This tale teaches that sincerity and humility bring blessings, while greed only brings disaster. The story of Bawang Merah and Bawang Putih is still told to children across the Indonesian archipelago today.',
        ],
        'questions': [
            {'after': 1, 'q': 'How was Bawang Putih treated in her own home?', 'options': ['Like a beloved only child', 'Like a servant', 'Like royalty', 'She was sent away to school'], 'correct': 1},
            {'after': 3, 'q': 'What condition did the old woman set for returning the cloth?', 'options': ['Bawang Putih had to find a lost ring', 'Bawang Putih had to help with housework for several days', 'Bawang Putih had to sing a song', 'Bawang Putih had to pay with gold'], 'correct': 1},
            {'after': 5, 'q': 'Why did Bawang Merah go to the same river?', 'options': ['To wash her own clothes', 'To find her sister', 'To imitate Bawang Putih and get a similar reward', 'To fetch drinking water'], 'correct': 2},
            {'after': 6, 'q': 'What was inside the large pumpkin Bawang Merah chose?', 'options': ['Gold and jewels', 'Fresh fruit', 'Snakes and venomous creatures', 'Nothing at all'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ind-05', 'tier': 'C1', 'title': 'Sangkuriang dan Tangkuban Perahu', 'title_en': 'Sangkuriang and the Overturned Boat',
        'origin': 'Sundanese legend, West Java, Indonesia',
        'paras': [
            'Menurut legenda tanah Sunda, hiduplah seorang putri bernama Dayang Sumbi yang memiliki anjing setia bernama Tumang. Tanpa disadarinya, Tumang sebenarnya adalah seorang dewa yang dikutuk menjelma menjadi anjing. Dari hubungan yang tak lazim itu, lahirlah seorang putra bernama Sangkuriang.',
            'Sangkuriang tumbuh menjadi pemuda pemberani dan gemar berburu ditemani Tumang. Suatu hari, karena kesal gagal berburu, ia membunuh Tumang tanpa mengetahui jati diri anjing itu. Ketika Dayang Sumbi mengetahui kebenarannya, ia murka dan memukul kepala Sangkuriang hingga terluka, lalu mengusirnya dari rumah.',
            'Bertahun-tahun kemudian, Sangkuriang kembali sebagai pengembara yang gagah setelah mengembara jauh dan berguru kesaktian. Ia tidak mengenali Dayang Sumbi, yang oleh kesaktiannya tetap awet muda, dan jatuh cinta padanya. Dayang Sumbi pun tidak menyadari bahwa pemuda tampan itu adalah anaknya sendiri, hingga keduanya sepakat untuk menikah.',
            'Menjelang pernikahan, Dayang Sumbi melihat bekas luka di kepala Sangkuriang dan akhirnya menyadari bahwa pemuda itu adalah putranya. Ia berusaha menggagalkan pernikahan itu tanpa membuat Sangkuriang marah. Maka ia mengajukan sebuah syarat yang mustahil: Sangkuriang harus membendung Sungai Citarum dan membangun perahu besar dalam waktu semalam.',
            'Dengan bantuan roh-roh gaib yang tunduk padanya, Sangkuriang bekerja dengan kecepatan luar biasa hingga hampir menyelesaikan tugas itu sebelum fajar. Ketakutan, Dayang Sumbi memohon bantuan penduduk untuk menyalakan obor di ufuk timur dan menumbuk padi, menciptakan suasana seolah pagi telah tiba. Ayam-ayam pun berkokok, dan roh-roh gaib yang membantu Sangkuriang ketakutan lalu melarikan diri sebelum pekerjaan selesai.',
            'Menyadari bahwa ia telah ditipu, Sangkuriang murka bukan kepalang. Dengan kekuatannya, ia menendang perahu besar yang belum selesai itu hingga terbalik dan melayang jauh. Perahu itu jatuh dan berubah menjadi sebuah gunung yang menyerupai perahu terbalik.',
            'Gunung itu kemudian dikenal masyarakat sebagai Gunung Tangkuban Perahu, yang hingga kini berdiri di dataran tinggi Bandung. Legenda ini bukan sekadar dongeng, melainkan juga cara masyarakat Sunda menjelaskan asal-usul bentang alam di sekitar mereka. Kisah cinta terlarang dan amarah yang membentuk gunung ini tetap menjadi salah satu legenda paling dikenal di Indonesia.',
        ],
        'paras_en': [
            'According to Sundanese legend, there lived a princess named Dayang Sumbi who had a loyal dog named Tumang. Unbeknownst to her, Tumang was actually a god who had been cursed to take the form of a dog. From this unusual union was born a son named Sangkuriang.',
            "Sangkuriang grew into a brave young man who loved hunting with Tumang by his side. One day, frustrated after a failed hunt, he killed Tumang without knowing the dog's true identity. When Dayang Sumbi learned the truth, she flew into a rage and struck Sangkuriang's head, wounding him, then banished him from the house.",
            "Years later, Sangkuriang returned as a dashing wanderer after journeying far and studying the mystical arts. He did not recognize Dayang Sumbi, who by her own powers had remained eternally youthful, and fell in love with her. Dayang Sumbi, in turn, did not realize the handsome young man was her own son, and the two agreed to marry.",
            "As the wedding approached, Dayang Sumbi noticed the old scar on Sangkuriang's head and finally realized the young man was her son. She tried to call off the marriage without provoking his anger. So she set an impossible condition: Sangkuriang had to dam the Citarum River and build a great boat, all in a single night.",
            "With the help of spirits who obeyed him, Sangkuriang worked at extraordinary speed and nearly finished the task before dawn. Terrified, Dayang Sumbi begged the villagers to light torches on the eastern horizon and pound rice, creating the illusion that morning had already come. The roosters crowed, and the spirits helping Sangkuriang, frightened, fled before the work was complete.",
            'Realizing he had been deceived, Sangkuriang flew into an uncontrollable rage. With his great strength, he kicked the unfinished boat, sending it flying and flipping over. It landed and turned into a mountain shaped like an overturned boat.',
            "That mountain became known to the people as Mount Tangkuban Perahu, which still stands in the highlands of Bandung today. The legend is not merely a fairy tale but also the Sundanese people's way of explaining the landscape around them. This tale of forbidden love and the fury that shaped a mountain remains one of the most well-known legends in Indonesia.",
        ],
        'questions': [
            {'after': 1, 'q': 'Who was Tumang, in truth?', 'options': ['An ordinary dog', 'A god cursed to take canine form', "Dayang Sumbi's brother", 'A neighboring king'], 'correct': 1},
            {'after': 3, 'q': 'Why did Sangkuriang and Dayang Sumbi agree to marry?', 'options': ['They both knew they were related and married for duty', "Sangkuriang recognized her but she didn't know him", 'Neither recognized the other as mother and son', 'A king arranged the marriage'], 'correct': 2},
            {'after': 5, 'q': 'How did Dayang Sumbi stop the spirits from finishing the boat?', 'options': ['She begged Sangkuriang directly to stop', 'She created a false dawn with torches and rice-pounding', 'She hid the boat overnight', 'She asked the gods to send rain'], 'correct': 1},
            {'after': 6, 'q': 'What did the overturned boat become?', 'options': ['A river', 'A cave', 'A mountain, Tangkuban Perahu', 'A lake'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ind-06', 'tier': 'C2', 'title': 'Roro Jonggrang', 'title_en': 'Roro Jonggrang',
        'origin': 'Javanese legend, Central Java, Indonesia',
        'paras': [
            'Di tanah Jawa yang subur, tersebutlah Kerajaan Prambanan yang diperintah oleh Prabu Baka, seorang raja sakti namun angkuh. Ketika Bandung Bondowoso, pangeran dari Kerajaan Pengging, menyerang dan menaklukkan Prambanan, Prabu Baka gugur di medan laga. Sang pangeran kemudian jatuh hati pada putri sang raja yang ditaklukkannya, Roro Jonggrang, seorang perempuan yang kecantikannya sepadan dengan kekerasan hatinya.',
            'Bandung Bondowoso melamar Roro Jonggrang dengan penuh keyakinan, tidak menduga bahwa hatinya menyimpan dendam mendalam atas kematian ayahnya. Roro Jonggrang, yang tak berani menolak secara terang-terangan seorang penakluk sakti, menempuh siasat yang lebih halus namun kejam. Ia mengajukan dua syarat yang tampak mustahil dipenuhi: sebuah sumur bernama Jalatunda, dan seribu candi yang harus rampung dalam satu malam.',
            'Syarat pertama justru menjadi jebakan maut. Ketika Bandung Bondowoso turun ke dalam sumur yang digalinya sendiri, para pengikut Roro Jonggrang menimbunnya hidup-hidup dengan tanah. Namun berkat kesaktiannya, sang pangeran berhasil meloloskan diri, dan alih-alih membalas dendam, ia justru tetap bertekad memenuhi syarat kedua demi memenangkan hati sang putri.',
            'Malam itu, Bandung Bondowoso memanggil bala tentara jin dan makhluk halus untuk membantunya. Dalam hitungan jam, candi demi candi menjulang dari tanah bagaikan disulap, dan menjelang tengah malam, sembilan ratus sembilan puluh sembilan candi telah berdiri megah. Kepanikan pun merayapi hati Roro Jonggrang, yang menyadari bahwa syaratnya, yang semula ia anggap mustahil, kini nyaris terpenuhi.',
            'Dengan kecerdikan yang lahir dari keputusasaan, Roro Jonggrang membangunkan para dayang untuk menumbuk lesung dan membakar jerami di sisi timur, menciptakan ilusi fajar yang belum sungguh tiba. Ayam-ayam jantan, tertipu oleh cahaya dan bunyi itu, mulai berkokok bersahutan. Para jin, yang terikat sumpah untuk tidak bekerja di siang hari, serta-merta menghentikan pekerjaan mereka dan lenyap ke dalam bumi, meninggalkan satu candi yang belum sempat rampung.',
            'Ketika kebenaran akhirnya terkuak, murka Bandung Bondowoso tak terbendung lagi. Dengan suara yang gemuruh oleh amarah dan luka, ia mengutuk Roro Jonggrang agar menjadi arca batu, pelengkap candi keseribu yang gagal ia dirikan dengan tangannya sendiri. Seketika itu pula, tubuh sang putri membeku menjadi patung, seolah kecantikannya yang dahulu memikat kini abadi dalam wujud batu yang dingin.',
            'Hingga hari ini, kompleks Candi Prambanan berdiri sebagai saksi bisu legenda tersebut, dan arca Durga di bilik utara candi utama masih dipercaya sebagian masyarakat sebagai perwujudan Roro Jonggrang. Kisah ini menenun bersama tema cinta yang bertepuk sebelah tangan, kelicikan yang berbalik menjadi petaka, dan warisan arsitektur yang nyata hingga kini. Lebih dari sekadar dongeng pengantar tidur, legenda Roro Jonggrang adalah cerita asal-usul yang menjelaskan keagungan salah satu candi Hindu terbesar di Asia Tenggara.',
        ],
        'paras_en': [
            'In the fertile land of Java, there was once the kingdom of Prambanan, ruled by Prabu Baka, a powerful but arrogant king. When Bandung Bondowoso, a prince from the kingdom of Pengging, attacked and conquered Prambanan, Prabu Baka fell in battle. The prince then fell in love with the daughter of the king he had defeated, Roro Jonggrang, a woman whose beauty was matched only by the hardness of her heart.',
            "Bandung Bondowoso proposed to Roro Jonggrang with full confidence, not suspecting that she harbored deep resentment over her father's death. Roro Jonggrang, who dared not openly refuse a mighty conqueror, resorted to a subtler but no less cruel scheme. She set two conditions that seemed impossible to fulfill: a well named Jalatunda, and a thousand temples to be completed in a single night.",
            "The first condition proved to be a deadly trap. When Bandung Bondowoso climbed down into the well he himself had dug, Roro Jonggrang's followers buried him alive with earth. Yet thanks to his supernatural power, the prince managed to escape, and rather than seek revenge, he remained determined to fulfill the second condition in order to win the princess's heart.",
            "That night, Bandung Bondowoso summoned an army of spirits and supernatural beings to assist him. Within hours, temple after temple rose from the earth as if conjured, and by nearly midnight, nine hundred and ninety-nine temples stood in magnificent array. Panic crept into Roro Jonggrang's heart as she realized that the condition she had once thought impossible was now nearly fulfilled.",
            'With a cunning born of desperation, Roro Jonggrang woke her maidservants to pound rice mortars and burn straw to the east, creating the illusion of a dawn that had not truly arrived. The roosters, deceived by the light and noise, began to crow one after another. The spirits, bound by an oath not to work past daybreak, immediately abandoned their labor and vanished into the earth, leaving one temple unfinished.',
            "When the truth finally came to light, Bandung Bondowoso's fury could no longer be contained. With a voice thundering with rage and heartbreak, he cursed Roro Jonggrang to become a stone statue, the missing thousandth temple he had failed to build with his own hands. In an instant, the princess's body froze into a statue, as though her once-captivating beauty was now made eternal in cold stone.",
            "To this day, the Prambanan temple complex stands as silent witness to this legend, and the statue of Durga in the northern chamber of the main temple is still believed by some to be the embodiment of Roro Jonggrang. The tale weaves together themes of unrequited love, cunning that backfires into tragedy, and an architectural legacy that endures to this day. More than just a bedtime story, the legend of Roro Jonggrang is an origin tale explaining the grandeur of one of the largest Hindu temples in Southeast Asia.",
        ],
        'questions': [
            {'after': 1, 'q': 'Why did Bandung Bondowoso fall in love with Roro Jonggrang?', 'options': ['She was the daughter of the king he had defeated, and famously beautiful', 'She helped him win the battle', 'She was a foreign princess visiting the court', 'They had been childhood friends'], 'correct': 0},
            {'after': 3, 'q': 'What happened when Bandung Bondowoso climbed into the well?', 'options': ['He found treasure', "Roro Jonggrang's followers buried him alive, but he escaped", 'He drowned instantly', 'He refused to go down'], 'correct': 1},
            {'after': 5, 'q': 'How did Roro Jonggrang trick the spirits into stopping their work?', 'options': ['She threatened them with a sword', 'She created a false dawn with rice-pounding and burning straw', 'She bribed them with gold', 'She asked Bandung Bondowoso to call them off'], 'correct': 1},
            {'after': 6, 'q': 'What ultimately happened to Roro Jonggrang?', 'options': ['She married Bandung Bondowoso happily', 'She was cursed into a stone statue', 'She fled to another kingdom', 'She became queen of Prambanan'], 'correct': 1},
        ],
    },
]
