# -*- coding: utf-8 -*-
# Traditional tales of the Classical Latin (no macrons)-speaking world, retold and graded for the Ship's Library
LANG = 'la'
FOLK = [
    {
        'id': 'fk-la-01', 'tier': 'B1', 'title': 'Romulus et Remus', 'title_en': 'Romulus and Remus',
        'origin': 'Roman foundation legend, told by Livy and other ancient historians',
        'paras': [
            'Olim in terra Italia duo fratres erant, Romulus et Remus. Mater eorum erat Rhea Silvia, filia regis. Sed rex malus, nomine Amulius, fratres timebat et eos in flumine Tiberi reliquit.',
            'Aqua pueros ad ripam portavit. Ibi lupa fera pueros invenit. Lupa eos non necavit, sed lac suum dedit. Pueri cum lupa multos dies vixerunt.',
            'Postea pastor, nomine Faustulus, pueros invenit. Faustulus et uxor eius pueros domum duxerunt. Fratres apud pastores creverunt et fortes viri facti sunt.',
            'Cum adulti erant, Romulus et Remus veritatem de familia sua cognoverunt. Regem malum Amulium vicerunt et avum verum in regno posuerunt.',
            'Fratres novam urbem aedificare voluerunt. Sed de loco urbis non consentiebant. Romulus unum collem elegit, Remus alterum collem elegit.',
            'Fratres inter se certabant. In ira, Romulus Remum necavit. Postea Romulus multum doluit, sed urbem solus aedificavit.',
            'Romulus urbem suo nomine Romam vocavit. Romulus primus rex Romae fuit. Hodie multi hanc fabulam de origine Romae narrant.',
        ],
        'paras_en': [
            'Long ago in the land of Italy there were two brothers, Romulus and Remus. Their mother was Rhea Silvia, the daughter of a king. But an evil king named Amulius feared the brothers and left them in the Tiber river.',
            'The water carried the boys to the riverbank. There a wild she-wolf found them. The wolf did not kill them, but gave them her own milk. The boys lived with the wolf for many days.',
            'Later a shepherd named Faustulus found the boys. Faustulus and his wife took the boys home. The brothers grew up among shepherds and became strong men.',
            'When they were grown, Romulus and Remus learned the truth about their family. They defeated the evil king Amulius and restored their true grandfather to the throne.',
            'The brothers wanted to build a new city. But they could not agree on the location of the city. Romulus chose one hill, Remus chose another hill.',
            'The brothers quarreled with each other. In anger, Romulus killed Remus. Afterward Romulus grieved deeply, but he built the city alone.',
            'Romulus named the city Rome after himself. Romulus was the first king of Rome. Today many people still tell this tale about the origin of Rome.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did Amulius leave the twin boys in the river?', 'options': ['Because he feared them', 'Because he loved them', 'Because a priest ordered it', 'Because the boys were sick'], 'correct': 0},
            {'after': 3, 'q': 'Who found and raised the boys after the wolf?', 'options': ['A shepherd named Faustulus', 'A king', 'A priest', 'A soldier'], 'correct': 0},
            {'after': 5, 'q': 'Why did the brothers argue before founding the city?', 'options': ['They disagreed about where to build it', 'They disagreed about who their mother was', 'They fought over the wolf', 'They argued about their grandfather'], 'correct': 0},
            {'after': 6, 'q': 'What happened between the brothers?', 'options': ['Romulus killed Remus in anger', 'Remus killed Romulus', 'They became joint kings', 'They left the city together'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-la-02', 'tier': 'B1', 'title': 'Androcles et Leo', 'title_en': 'Androcles and the Lion',
        'origin': 'Roman folk tale, recorded by Aulus Gellius',
        'paras': [
            'Olim servus, nomine Androcles, a domino suo fugit. Androcles in silvam magnam cucurrit et ibi in spelunca se occultavit.',
            'In spelunca leo magnus erat. Leo Androclem non oppugnavit; leo pedem suum ad servum extendit. Androcles vidit spinam magnam in pede leonis.',
            'Androcles, quamquam timebat, spinam ex pede leonis traxit. Leo statim melius se habuit. Deinde leo et Androcles multos dies in spelunca simul habitaverunt, quasi amici.',
            'Postea milites Androclem invenerunt et eum ceperunt. Androclem Romam duxerunt, quod servus fugitivus erat. Ibi Androcles poenam capitalem exspectabat.',
            'Romani Androclem in arenam miserunt, ubi leo ferus eum devorare debebat. Populus in circo spectabat. Leo magnus in arenam intravit.',
            'Sed leo, cum Androclem vidit, eum non oppugnavit. Erat enim idem leo cuius pedem Androcles olim curaverat. Leo amicum suum agnovit et pacifice iuxta eum stetit.',
            'Populus hoc miraculum vidit et stupuit. Imperator Androcli libertatem dedit. Androcles et leo deinde per vias Romae simul ambulabant, et omnes eos spectabant.',
        ],
        'paras_en': [
            'Once a slave named Androcles ran away from his master. Androcles ran into a great forest and hid there in a cave.',
            "In the cave there was a great lion. The lion did not attack Androcles; the lion stretched its paw toward the slave. Androcles saw a large thorn in the lion's paw.",
            "Although he was afraid, Androcles pulled the thorn out of the lion's paw. The lion immediately felt better. After that, the lion and Androcles lived together in the cave for many days, like friends.",
            'Later soldiers found Androcles and captured him. They took him to Rome, because he was a runaway slave. There Androcles awaited the death penalty.',
            'The Romans sent Androcles into the arena, where a fierce lion was supposed to devour him. The crowd watched in the circus. A great lion entered the arena.',
            'But when the lion saw Androcles, it did not attack him. For it was the same lion whose paw Androcles had once treated. The lion recognized its friend and stood peacefully beside him.',
            'The crowd saw this marvel and was amazed. The emperor granted Androcles his freedom. Androcles and the lion then walked together through the streets of Rome, and everyone watched them.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did Androcles hide in a cave?', 'options': ['He was running away from his master', 'He was hunting animals', 'He was lost in a storm', 'He was searching for treasure'], 'correct': 0},
            {'after': 3, 'q': 'What did Androcles do for the lion?', 'options': ['He removed a thorn from its paw', 'He gave it food', 'He built it a den', 'He taught it tricks'], 'correct': 0},
            {'after': 5, 'q': 'Why was Androcles sent into the arena?', 'options': ['To be devoured by a wild lion as punishment', 'To fight gladiators', 'To tame the lion for the crowd', 'To be freed by the emperor'], 'correct': 0},
            {'after': 6, 'q': "Why didn't the lion attack Androcles?", 'options': ['The lion recognized him as the friend who had once helped him', 'The lion was too old to attack', 'The lion was asleep', 'The trainers had calmed the lion'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-la-03', 'tier': 'B2', 'title': 'Vulpes et Corvus', 'title_en': 'The Fox and the Crow',
        'origin': 'Aesopic fable, retold in Latin verse by Phaedrus',
        'paras': [
            'Fabulam narrabo quam poeta Phaedrus olim scripsit, de vulpe astuta et corvo stulto. Corvus in alta arbore sedebat, caseum ore tenens, quem furto ceperat.',
            'Vulpes, quae caseum cupiebat, sub arbore constitit. Si corvum laudibus decepisset, caseus in terram caderet, et vulpes facile eum raperet.',
            '"O corve," inquit vulpes, "quam pulchrae sunt pennae tuae! Si vox tua tam dulcis esset quantum formosum est corpus tuum, omnium avium certe regina esses."',
            'Corvus, verbis vulpis motus, vocem suam ostendere voluit. Cum os aperuisset ut caneret, caseus statim in terram decidit.',
            'Vulpes, quae hoc exspectaverat, caseum celeriter arripuit et eum devoravit. Corvus stultus in arbore sine cibo mansit, dolens.',
            '"Noli umquam," inquit vulpes ridens, "adulatoribus credere; nam qui adulatur, semper aliquid a te vult." Corvus, sero sapiens factus, tacuit.',
            'Haec fabula homines docet ne adulationi credant, cum aliquis eos immodice laudat. Nam plerumque adulator non amicus est, sed is qui aliquid nostrum cupit.',
        ],
        'paras_en': [
            'I will tell a fable that the poet Phaedrus once wrote, about a clever fox and a foolish crow. A crow was sitting in a tall tree, holding in its beak a piece of cheese it had stolen.',
            'A fox, who wanted the cheese, stood beneath the tree. If she could trick the crow with flattery, the cheese would fall to the ground, and the fox could easily snatch it.',
            '"Oh crow," said the fox, "how beautiful your feathers are! If your voice were as sweet as your body is lovely, you would surely be the queen of all birds."',
            'The crow, moved by the fox\'s words, wanted to show off its voice. When it opened its beak to sing, the cheese immediately fell to the ground.',
            'The fox, who had expected this, quickly grabbed the cheese and devoured it. The foolish crow was left in the tree without food, grieving.',
            '"Never," said the fox, laughing, "trust flatterers; for whoever flatters you always wants something from you." The crow, wise too late, fell silent.',
            'This fable teaches people not to trust flattery when someone praises them excessively. For a flatterer is usually not a friend, but someone who wants something of ours.',
        ],
        'questions': [
            {'after': 1, 'q': 'What was the crow holding in its beak?', 'options': ['A piece of cheese it had stolen', 'A fish', 'A golden ring', 'A nest of eggs'], 'correct': 0},
            {'after': 3, 'q': 'What did the fox tell the crow?', 'options': ['That its singing voice was probably as beautiful as its feathers', 'That its feathers were ugly', 'That it should give her the cheese directly', 'That foxes and crows should be friends'], 'correct': 0},
            {'after': 5, 'q': 'What happened to the cheese?', 'options': ['The fox grabbed and ate it after the crow dropped it', 'The crow ate it before the fox arrived', 'The cheese was too high for the fox to reach', 'A dog stole it from both of them'], 'correct': 0},
            {'after': 6, 'q': 'What is the moral of the fable?', 'options': ['Do not trust flatterers, who usually want something from you', 'Birds should not sing near foxes', 'Cheese should always be hidden in trees', 'Foxes are always dangerous to crows'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-la-04', 'tier': 'B2', 'title': 'Horatius Cocles', 'title_en': 'Horatius at the Bridge',
        'origin': 'Roman legend of early Republic, told by Livy',
        'paras': [
            'Post reges ex urbe expulsos, Romani rem publicam liberam instituerunt. Sed Lars Porsena, rex Etruscorum, cum magno exercitu ad urbem venit, ut regem exsulem restitueret.',
            'Si hostes pontem Sublicium trans Tiberim transissent, urbs statim capta esset. Cives, terrore perculsi, ad pontem fugerunt, sperantes se intra moenia tutos fore.',
            'Horatius Cocles, miles fortissimus, apud pontem stetit. "Nisi pons celeriter rescinditur," clamavit, "hostes hodie in urbem intrabunt. Ego, cum duobus sociis, aditum tenebo dum vos pontem rescindatis."',
            'Horatius et duo socii in ponte contra totum exercitum hostium restiterunt. Cives interea post eos pontem securibus frangebant. Etrusci, tam paucos viros videntes, primo dubitabant an impetum facerent.',
            'Cum pons paene ruptus esset, Horatius socios suos ad partem tutam pontis redire iussit. Ipse solus in extrema parte pontis mansit, hostibus obstans, donec ultimum lignum pontis cecidit.',
            'Horatius, priusquam in flumen desiluit, Tiberim deum precatus est ut se armatum reciperet. Deinde, gravi armatura onustus, in aquam saltavit et, sagittis undique volantibus, ad ripam alteram natavit.',
            'Si Horatius illo die non tam fortis fuisset, Roma forsitan capta esset. Cives eum postea magnis honoribus ornaverunt, et fabula de ponte defenso per multa saecula narrata est.',
        ],
        'paras_en': [
            'After the kings had been expelled from the city, the Romans established a free republic. But Lars Porsena, king of the Etruscans, came to the city with a great army, in order to restore the exiled king.',
            'If the enemy had crossed the Sublician bridge over the Tiber, the city would have been captured at once. The citizens, struck with terror, fled to the bridge, hoping they would be safe within the walls.',
            'Horatius Cocles, a very brave soldier, stood at the bridge. "Unless the bridge is quickly cut down," he shouted, "the enemy will enter the city today. I, with two companions, will hold the approach while you cut down the bridge."',
            'Horatius and his two companions held the bridge against the entire enemy army. Meanwhile the citizens behind them were breaking the bridge apart with axes. The Etruscans, seeing so few men, at first hesitated to attack.',
            'When the bridge was nearly broken through, Horatius ordered his companions to retreat to the safe part of the bridge. He alone remained at the far end of the bridge, blocking the enemy, until the last timber of the bridge fell.',
            'Before he leapt into the river, Horatius prayed to the god Tiber to receive him safely, armor and all. Then, weighed down by heavy armor, he jumped into the water and, with arrows flying at him from every side, swam to the far bank.',
            'If Horatius had not been so brave that day, Rome might have been captured. The citizens later honored him greatly, and the story of the defended bridge was told for many centuries.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did Lars Porsena march on Rome?', 'options': ['To restore the exiled king to power', 'To conquer new farmland', 'To punish Horatius personally', 'To collect unpaid tribute'], 'correct': 0},
            {'after': 3, 'q': 'What did Horatius propose to do?', 'options': ['Hold the bridge with two companions while the Romans destroyed it', 'Surrender the city to save lives', 'Negotiate peace with Porsena', 'Burn the bridge down himself alone'], 'correct': 0},
            {'after': 5, 'q': 'What did Horatius do once the bridge was nearly destroyed?', 'options': ['He sent his companions back to safety and held the far end alone', 'He retreated immediately with his companions', 'He rebuilt the bridge himself', 'He called for reinforcements from the city'], 'correct': 0},
            {'after': 6, 'q': 'How did Horatius escape after the bridge collapsed?', 'options': ['He prayed to the river god and swam across in his armor', 'He was rescued by a passing boat', 'He ran along the riverbank to a ford', 'He surrendered to the Etruscans'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-la-05', 'tier': 'C1', 'title': 'Cincinnatus', 'title_en': 'Cincinnatus',
        'origin': 'Roman legend of civic virtue, told by Livy',
        'paras': [
            'Lucius Quinctius, cui cognomen erat Cincinnatus (id est "crispus," propter capillos eius crispos), parvum agrum trans Tiberim colebat, quamquam olim inter primores civitatis numeratus erat.',
            'Eo tempore Aequi, gens montana Romanis inimica, consulem Minucium cum exercitu in valle angusta circumsederant, ita ut Romani neque progredi neque effugere possent.',
            'Senatus, re desperata commotus, decrevit ut dictator crearetur, magistratus ille extraordinarius cui, tempore periculi, potestas paene regia in sex menses conceditur.',
            'Legati igitur ad Cincinnatum missi sunt, quem in agro suo, sudore perfusum, arantem invenerunt. Cincinnatus, ubi audivit se dictatorem factum esse, uxorem togam afferre iussit, quam, pulvere adhuc oblitus, induit.',
            'Romam profectus, Cincinnatus omnes cives iuniores statim ad arma vocavit; nemo huic viro, cuius auctoritas tam subito et tam mirabiliter aucta erat, contradicere ausus est.',
            'Una nocte exercitum ad locum ubi Minucius obsidebatur duxit, Aequos ipsos inter duo agmina Romana clausit, et hostes, prius obsessores, nunc obsessi, se dedere coacti sunt.',
            'Cincinnatus autem, gloria parta, potestatem dictatoriam, quam per sedecim tantum dies tenuerat, cum lex sex menses permitteret, sponte deposuit et ad aratrum suum rediit, exemplum posteris relinquens virtutis quae honores non quaerit.',
        ],
        'paras_en': [
            'Lucius Quinctius, whose surname was Cincinnatus (that is, "curly-haired," because of his curly hair), was farming a small plot of land across the Tiber, although he had once been counted among the leading men of the state.',
            'At that time the Aequi, a mountain people hostile to the Romans, had surrounded the consul Minucius and his army in a narrow valley, so that the Romans could neither advance nor escape.',
            'The Senate, alarmed by the desperate situation, decreed that a dictator be appointed, that extraordinary office to which, in a time of danger, near-royal power is granted for six months.',
            'Envoys were therefore sent to Cincinnatus, whom they found in his field, drenched in sweat, plowing. Cincinnatus, when he heard that he had been made dictator, told his wife to bring his toga, which, still covered in dust, he put on.',
            'Having set out for Rome, Cincinnatus immediately called all the younger citizens to arms; no one dared to oppose this man, whose authority had grown so suddenly and so remarkably.',
            'In a single night he led the army to the place where Minucius was besieged, trapped the Aequi themselves between two Roman columns, and the enemy, formerly besiegers, now besieged, were forced to surrender.',
            'Cincinnatus, however, having won this glory, voluntarily gave up his dictatorial power, which he had held for only sixteen days even though the law allowed six months, and returned to his plow, leaving to future generations an example of virtue that does not seek honors.',
        ],
        'questions': [
            {'after': 1, 'q': 'What does the name Cincinnatus mean, and what was he doing before he became famous?', 'options': ['It means "curly-haired," and he was farming a small plot of land', 'It means "the strong one," and he was leading the army', 'It means "the wise one," and he was serving in the senate', 'It means "the exile," and he was living abroad'], 'correct': 0},
            {'after': 3, 'q': 'Why did the Senate decide to appoint a dictator?', 'options': ['Because a consul and his army were trapped by the enemy and the situation seemed desperate', 'Because the consuls had been assassinated', 'Because a plague had struck the city', 'Because the common people were rebelling'], 'correct': 0},
            {'after': 5, 'q': 'What did Cincinnatus do as soon as he arrived in Rome?', 'options': ['He called all the younger citizens to arms at once', 'He held a triumphal parade', 'He executed the previous consul', 'He built new fortifications'], 'correct': 0},
            {'after': 6, 'q': 'What did Cincinnatus do after winning the war?', 'options': ['He voluntarily gave up his power, far earlier than the law allowed, and returned to his farm', 'He kept his power for the full six months and then ran for consul', 'He declared himself king of Rome', 'He exiled the defeated Aequi from Italy'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-la-06', 'tier': 'C2', 'title': 'Baucis et Philemon', 'title_en': 'Baucis and Philemon',
        'origin': "Ovid's Metamorphoses, ancient Rome",
        'paras': [
            'Fama est olim Iovem et Mercurium, forma mortali indutos, per Phrygiae collem incultum peregrinasse, hospitium quaerentes; sed mille domos pulsaverunt, et mille ianuae, dure seratae, clausae mansere.',
            'Tandem ad tugurium pervenerunt humile, stramine et culmis palustribus tectum, ubi Baucis anus et Philemon senex, olim iuvenes coniuncti, iam simul in illa ipsa casa consenuerant, paupertatem, levem si ferre didicisses, non erubescentes.',
            'Hi, quamquam hospites divites esse suspicari non poterant, quicquid habebant libentissime obtulerunt: ignem cineribus hesternis suscitaverunt, holera ex horto suo collecta lavaverunt, et unicum baconis frustum, fumo diu servatum, cultro secuerunt.',
            'Mensa, uno pede claudicans, testa subiecta stabilita est; vinum, quamvis vile, in poculis fictilibus, non auro, sed cura maiore quam ullum convivium regale, propinatum est.',
            'Subito senes animadverterunt crateram vino, quotiescumque hausta erat, sponte sua iterum atque iterum impleri, prodigium quod illis timorem sacrum, non stuporem meram, incussit; tum demum deos, sub humili tecto latentes, agnoverunt.',
            'Manibus ad caelum sublatis, veniam pro paupere convivio petiverunt; unicam anserem, custodem casae, mactare volebant, sed anser ipse, celerior quam senes, ad Iovis pedes tandem confugit, et deus, misericordia motus, eum servari iussit.',
            'Dii, casam relinquentes, senes ad montis verticem duxerunt; ibi, respicientes, viderunt agros vicinos gurgite mersos, unam domum, suam, in templum marmoreum mutatam, et Iuppiter, precibus eorum benigne auditis, Baucidem et Philemonem, cum tempus venit, non morte separavit, sed in duas arbores, iuxta natas, simul mutavit.',
        ],
        'paras_en': [
            'The story goes that once Jupiter and Mercury, disguised in mortal form, wandered over an untended hill in Phrygia, seeking lodging; but they knocked at a thousand houses, and a thousand doors, harshly bolted, remained shut.',
            'At last they came to a humble hut, roofed with straw and marsh reeds, where old Baucis and old Philemon, once joined as a young couple, had now grown old together in that very cottage, not ashamed of a poverty made light by their having learned to bear it.',
            'Though they could not suspect their guests were wealthy, this couple offered whatever they had most gladly: they stirred up a fire from the previous day\'s ashes, washed vegetables gathered from their garden, and cut with a knife a single piece of bacon that had long been kept in the smoke.',
            'The table, wobbling on one short leg, was steadied with a piece of broken pottery; wine, though cheap, was served in earthenware cups, not gold, but with greater care than any royal banquet.',
            'Suddenly the old couple noticed that the wine bowl, however much was drunk from it, kept filling itself again and again on its own, a marvel that struck them with sacred awe rather than mere astonishment; only then did they recognize the gods hidden beneath their humble roof.',
            'With hands raised to the sky, they begged forgiveness for their poor feast; they wanted to slaughter their one goose, the guardian of the cottage, but the goose itself, swifter than the old pair, finally took refuge at the feet of Jupiter, and the god, moved by pity, ordered that it be spared.',
            'The gods, leaving the cottage, led the old couple to the top of the mountain; there, looking back, they saw the neighboring fields submerged in a flood, their own single house changed into a marble temple, and Jupiter, having kindly heard their prayers, did not separate Baucis and Philemon by death when the time came, but transformed them together into two trees, growing side by side.',
        ],
        'questions': [
            {'after': 1, 'q': 'What were Jupiter and Mercury doing, disguised as mortals?', 'options': ['Searching for hospitality among the people of Phrygia, and being turned away everywhere', 'Testing the strength of local warriors', 'Looking for a lost temple', 'Collecting taxes from villagers'], 'correct': 0},
            {'after': 3, 'q': 'What did Baucis and Philemon do for their guests despite not knowing who they were?', 'options': ['They offered everything they had, cheerfully, though it was humble fare', 'They refused to let strangers inside their home', 'They sent them to a wealthier neighbor', 'They asked the strangers for payment first'], 'correct': 0},
            {'after': 5, 'q': 'What prodigy made the old couple realize their guests were gods?', 'options': ['The wine bowl kept refilling itself no matter how much was poured', 'The house suddenly became warm', 'Their goose began to speak to them', 'A bright star appeared over the roof'], 'correct': 0},
            {'after': 6, 'q': 'What ultimately happened to Baucis and Philemon?', 'options': ['When death finally came, they were transformed together into two trees rather than being separated', 'They were made immortal and lived forever in the marble temple', 'They were turned to stone by the flood', 'They were separated, one dying long before the other'], 'correct': 0},
        ],
    },
]
