# -*- coding: utf-8 -*-
# Traditional tales of the Korean-speaking world, retold and graded for the Ship's Library
LANG = 'ko'
FOLK = [
    {
        'id': 'fk-ko-01', 'tier': 'B1', 'title': '흥부와 놀부', 'title_en': "Heungbu and Nolbu",
        'origin': "Korean folk tale, traditional oral literature",
        'paras': [
            '옛날 어느 마을에 흥부와 놀부라는 형제가 살았습니다. 형 놀부는 욕심이 많고 마음이 나빴습니다. 동생 흥부는 마음이 착하고 가난했습니다.',
            '놀부는 부모님이 돌아가시자 재산을 혼자 다 차지했습니다. 그리고 흥부와 그의 가족을 집에서 쫓아냈습니다. 흥부는 아내와 많은 아이들과 함께 낡은 오두막에서 살았습니다. 먹을 것이 없어서 가족은 늘 배가 고팠습니다.',
            '어느 봄날, 제비 한 마리가 흥부의 집 처마 밑에 둥지를 지었습니다. 그런데 아기 제비 한 마리가 둥지에서 떨어져 다리가 부러졌습니다. 흥부는 제비의 다리를 천으로 조심스럽게 감아 주었습니다. 제비는 곧 건강해져서 남쪽 나라로 날아갔습니다.',
            '이듬해 봄, 그 제비가 다시 흥부의 집으로 돌아왔습니다. 제비는 입에 작은 씨앗 하나를 물고 있었습니다. 흥부는 그 씨앗을 마당에 심었습니다.',
            '씨앗은 무럭무럭 자라서 커다란 박이 되었습니다. 흥부와 아내는 박을 반으로 잘랐습니다. 그런데 박 속에서 금은보화가 쏟아져 나왔습니다. 흥부의 가족은 순식간에 큰 부자가 되었습니다.',
            '이 소식을 들은 놀부는 몹시 화가 났습니다. 놀부는 제비 둥지를 찾아서 일부러 아기 제비의 다리를 부러뜨렸습니다. 그리고 다시 다리를 고쳐 주고 남쪽으로 보냈습니다. 놀부는 자기도 부자가 되고 싶었습니다.',
            '이듬해 봄, 제비는 놀부에게도 씨앗을 가져다주었습니다. 놀부는 기뻐하며 그 씨앗을 심고 커다란 박을 얻었습니다. 그러나 박 속에서는 금은보화 대신 도깨비들이 나와 놀부를 혼내 주었습니다. 마음씨 착한 흥부는 모든 것을 잃은 형을 용서하고 재산을 나누어 주었습니다.',
        ],
        'paras_en': [
            "Long ago, in a certain village, there lived two brothers named Heungbu and Nolbu. The older brother, Nolbu, was greedy and unkind. The younger brother, Heungbu, was kind-hearted and poor.",
            "When their parents passed away, Nolbu took all the family's property for himself. He then threw Heungbu and his family out of the house. Heungbu lived in an old hut with his wife and many children. With nothing to eat, the family was always hungry.",
            "One spring day, a swallow built a nest under the eaves of Heungbu's house. But one baby swallow fell from the nest and broke its leg. Heungbu carefully wrapped the swallow's leg with cloth. The swallow soon grew healthy and flew off to the southern land.",
            "The following spring, that swallow came back to Heungbu's house. It was holding a small seed in its beak. Heungbu planted the seed in his yard.",
            "The seed grew and grew into a huge gourd. Heungbu and his wife cut the gourd in half. Gold, silver, and treasure poured out from inside it. Heungbu's family instantly became very rich.",
            "When Nolbu heard this news, he became furious. He found a swallow's nest and deliberately broke a baby swallow's leg. Then he fixed the leg again and sent it south. Nolbu wanted to become rich too.",
            "The next spring, the swallow brought a seed to Nolbu as well. Nolbu happily planted the seed and grew a huge gourd. But instead of gold and treasure, goblins came out of the gourd and punished Nolbu. Kind-hearted Heungbu forgave his brother, who had lost everything, and shared his wealth with him.",
        ],
        'questions': [
            {'after': 1, 'q': "What happened after the parents died?", 'options': ["Nolbu shared the property equally", "Nolbu took all the property and threw Heungbu out", "Heungbu became rich", "The brothers moved away together"], 'correct': 1},
            {'after': 3, 'q': "What did the swallow bring back to Heungbu the following spring?", 'options': ["A bag of rice", "A small seed", "A letter", "A basket of fruit"], 'correct': 1},
            {'after': 5, 'q': "What did Nolbu do after hearing that Heungbu became rich?", 'options': ["He congratulated Heungbu", "He deliberately broke a swallow's leg", "He moved to the south", "He gave his wealth to Heungbu"], 'correct': 1},
            {'after': 6, 'q': "What came out of Nolbu's gourd?", 'options': ["Gold and treasure", "Goblins who punished him", "More swallows", "Nothing at all"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ko-02', 'tier': 'B1', 'title': '해와 달이 된 오누이', 'title_en': "The Siblings Who Became the Sun and the Moon",
        'origin': "Korean folk tale, traditional oral literature",
        'paras': [
            '옛날 깊은 산속 마을에 홀어머니와 오누이가 살았습니다. 오빠와 여동생은 항상 사이가 좋았습니다. 어머니는 매일 시장에 가서 떡을 팔았습니다.',
            '어느 날 어머니는 떡을 팔고 늦게 산길로 집에 돌아오고 있었습니다. 그런데 커다란 호랑이가 나타나서 떡을 하나 달라고 말했습니다. 어머니는 무서워서 떡을 하나씩 주었습니다.',
            '호랑이는 떡을 다 먹고도 계속 어머니를 쫓아왔습니다. 결국 호랑이는 어머니를 잡아먹고 어머니의 옷을 입었습니다. 호랑이는 오누이가 사는 집으로 향했습니다.',
            '호랑이는 어머니인 척하며 문을 두드렸습니다. 오누이는 목소리가 이상하다고 생각해서 문을 열어 주지 않았습니다. 호랑이는 손을 문틈으로 내밀었지만, 손에 털이 많아서 오누이는 어머니가 아니라는 것을 알았습니다.',
            '오누이는 뒷문으로 몰래 도망쳐서 마당의 큰 나무 위로 올라갔습니다. 호랑이는 나무 밑에서 오누이를 발견하고 쫓아 올라오려고 했습니다. 오누이는 하늘을 향해 살려 달라고 빌었습니다.',
            '그러자 하늘에서 튼튼한 동아줄이 내려와서 오누이는 줄을 타고 하늘로 올라갔습니다. 호랑이도 하늘에 빌어서 동아줄을 받았지만, 그 줄은 썩은 줄이었습니다. 호랑이는 줄을 타다가 끊어져서 땅으로 떨어졌습니다.',
            '하늘로 올라간 오빠와 여동생은 각각 해와 달이 되었습니다. 여동생은 밤이 무서워서 오빠와 자리를 바꾸어 해가 되었습니다. 그래서 오빠는 달이 되고, 여동생은 해가 되었다고 전해집니다.',
        ],
        'paras_en': [
            "Long ago, in a village deep in the mountains, a widowed mother lived with her two children, an older brother and a younger sister. The brother and sister always got along well. Every day, the mother went to the market to sell rice cakes.",
            "One day, the mother was walking home late on a mountain path after selling her rice cakes. Suddenly a huge tiger appeared and asked her for a rice cake. Frightened, the mother gave the tiger her rice cakes one by one.",
            "Even after eating all the rice cakes, the tiger kept following the mother. In the end, the tiger ate the mother and put on her clothes. The tiger then headed to the house where the siblings lived.",
            "The tiger knocked on the door, pretending to be the mother. The siblings thought the voice sounded strange, so they did not open the door. The tiger stuck its paw through a gap in the door, but the paw was covered in fur, so the siblings knew it was not their mother.",
            "The siblings secretly escaped through the back door and climbed up a big tree in the yard. The tiger found them under the tree and tried to climb up after them. The siblings prayed to the sky, begging to be saved.",
            "A strong rope came down from the sky, and the siblings climbed it up to heaven. The tiger also prayed and received a rope, but it was a rotten one. As the tiger climbed, the rope snapped and it fell to the ground.",
            "The brother and sister who rose to the sky became the sun and the moon. The sister was afraid of the night, so she switched places with her brother and became the sun. And so, it is said, the brother became the moon and the sister became the sun.",
        ],
        'questions': [
            {'after': 1, 'q': "What did the tiger ask the mother for on the mountain path?", 'options': ["Her clothes", "A rice cake", "Directions home", "Money"], 'correct': 1},
            {'after': 3, 'q': "How did the siblings realize the visitor was not their mother?", 'options': ["They saw its tail", "Its hand was covered in fur", "It spoke a foreign language", "It smelled like a tiger"], 'correct': 1},
            {'after': 5, 'q': "What happened to the tiger's rope?", 'options': ["It was made of gold", "It was rotten and snapped", "It turned into a snake", "It was too short to reach"], 'correct': 1},
            {'after': 6, 'q': "What did the brother and sister become?", 'options': ["Stars", "The sun and the moon", "Birds", "Mountains"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ko-03', 'tier': 'B2', 'title': '콩쥐와 팥쥐', 'title_en': "Kongjwi and Patjwi",
        'origin': "Korean folk tale, traditional oral literature",
        'paras': [
            '옛날 어느 마을에 콩쥐라는 소녀가 살고 있었는데, 어머니가 일찍 세상을 떠나서 아버지와 단둘이 지내야 했습니다. 아버지는 재혼을 했고, 새어머니에게는 팥쥐라는 딸이 있었습니다. 새어머니와 팥쥐는 겉으로는 다정한 척했지만, 실제로는 콩쥐를 몹시 미워했습니다.',
            '아버지가 먼 길을 떠난 뒤, 새어머니는 본격적으로 콩쥐를 괴롭히기 시작했습니다. 새어머니는 콩쥐에게 밑 빠진 항아리에 물을 가득 채우라고 시켰고, 팥쥐에게는 쉬운 집안일만 맡겼습니다. 콩쥐가 아무리 물을 부어도 항아리는 채워지지 않았습니다.',
            '콩쥐가 항아리 앞에서 울고 있을 때, 커다란 두꺼비 한 마리가 나타났습니다. 두꺼비는 자신의 몸으로 항아리의 깨진 구멍을 막아 주었고, 덕분에 항아리에 물이 가득 찼습니다. 콩쥐는 두꺼비에게 진심으로 고마워했습니다.',
            '다음 날, 새어머니는 콩쥐에게 나무 호미 하나로 돌밭의 잡초를 모두 뽑으라고 명령했습니다. 나무 호미는 곧 부러졌고, 콩쥐는 어찌할 바를 몰랐습니다. 그때 하늘에서 검은 소 한 마리가 내려와 순식간에 밭을 다 갈아 주고는 콩쥐에게 예쁜 옷과 꽃신을 남겨 주었습니다.',
            '얼마 후, 마을에서 큰 잔치가 열렸는데 원님도 참석한다는 소문이 돌았습니다. 새어머니와 팥쥐는 잔치에 가면서 콩쥐에게는 불가능해 보이는 일들을 잔뜩 시켜 두었습니다. 하지만 선녀들이 다시 나타나 콩쥐를 도왔고, 콩쥐는 소가 준 옷과 꽃신을 신고 몰래 잔치에 갈 수 있었습니다.',
            '잔치로 가는 길에 시냇물을 건너던 콩쥐는 서두르다가 꽃신 한 짝을 물에 빠뜨리고 말았습니다. 마침 그곳을 지나가던 원님이 그 꽃신을 발견하고는, 이렇게 아름다운 신발의 주인을 반드시 찾아야겠다고 생각했습니다. 원님은 신발이 발에 꼭 맞는 여인을 신부로 삼겠다고 마을에 알렸습니다.',
            '많은 여인들이 신발을 신어 보았지만 아무에게도 맞지 않았습니다. 마지막으로 콩쥐가 신어 보자 꽃신은 마치 원래 그녀의 것이었던 것처럼 꼭 맞았습니다. 원님은 콩쥐의 착한 마음씨를 알아보고 그녀를 아내로 맞이했으며, 콩쥐는 오랫동안 행복하게 살았습니다.',
        ],
        'paras_en': [
            "Long ago, in a certain village, there lived a girl named Kongjwi, who had to live alone with her father after her mother passed away early. Her father remarried, and his new wife had a daughter named Patjwi. The stepmother and Patjwi pretended to be affectionate on the surface, but in truth they hated Kongjwi bitterly.",
            "After her father left on a long journey, the stepmother began to torment Kongjwi in earnest. She ordered Kongjwi to fill a jar with a hole in the bottom completely with water, while giving Patjwi only easy chores. No matter how much water Kongjwi poured in, the jar would never fill up.",
            "While Kongjwi was crying in front of the jar, a huge toad appeared. The toad blocked the broken hole in the jar with its own body, and thanks to that, the jar filled with water. Kongjwi thanked the toad from the bottom of her heart.",
            "The next day, the stepmother ordered Kongjwi to pull up all the weeds in a stony field using only a single wooden hoe. The wooden hoe soon broke, and Kongjwi did not know what to do. Just then, a black ox came down from the sky, plowed the whole field in an instant, and left Kongjwi a beautiful dress and a pair of flower shoes.",
            "Some time later, a great feast was held in the village, and word spread that the magistrate himself would attend. As the stepmother and Patjwi left for the feast, they piled on Kongjwi a mountain of tasks that seemed impossible to finish. But fairies appeared again to help her, and Kongjwi was able to secretly go to the feast wearing the dress and flower shoes the ox had given her.",
            "While crossing a stream on her way to the feast, Kongjwi hurried and accidentally dropped one of her flower shoes into the water. The magistrate, who happened to be passing by, found the shoe and decided he must find the owner of such a beautiful shoe. He announced to the village that he would take as his bride whichever woman the shoe fit perfectly.",
            "Many women tried on the shoe, but it fit no one. When Kongjwi finally tried it on, the flower shoe fit as though it had always been hers. The magistrate recognized Kongjwi's kind heart and took her as his wife, and Kongjwi lived happily for a long time after that.",
        ],
        'questions': [
            {'after': 1, 'q': "What impossible task did the stepmother give Kongjwi?", 'options': ["Sweep the entire village", "Fill a jar with a broken bottom with water", "Sew a hundred dresses", "Catch a wild ox"], 'correct': 1},
            {'after': 3, 'q': "Who helped Kongjwi weed the stony field?", 'options': ["A toad", "Her father", "A black ox from the sky", "Patjwi"], 'correct': 2},
            {'after': 5, 'q': "What did Kongjwi lose while crossing the stream?", 'options': ["Her dress", "One of her flower shoes", "A basket of rice cakes", "Her hairpin"], 'correct': 1},
            {'after': 6, 'q': "How did the magistrate choose his bride?", 'options': ["By holding a contest of strength", "By finding whose foot fit the lost shoe", "By asking the village elders", "By marrying the richest woman"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ko-04', 'tier': 'B2', 'title': '심청전', 'title_en': "The Tale of Shim Cheong",
        'origin': "Korean folk tale (pansori tradition), traditional oral literature",
        'paras': [
            '옛날 황해도 어느 마을에 심학규라는 눈먼 선비가 딸 심청과 함께 살고 있었습니다. 심청의 어머니는 심청을 낳은 지 얼마 되지 않아 세상을 떠났고, 눈먼 아버지는 동냥젖을 먹여 가며 딸을 힘겹게 키웠습니다. 심청은 자라면서 점점 더 효성이 지극한 딸이 되었습니다.',
            '심청은 어릴 때부터 이웃집 일을 도와주고 삯바느질을 하며 눈먼 아버지를 정성껏 모셨습니다. 아버지는 그런 딸을 보며 늘 미안하고 고마운 마음을 느꼈습니다. 어느 날 아버지는 개울에 빠졌다가 지나가던 스님의 도움으로 겨우 목숨을 건졌습니다.',
            '스님은 아버지에게 공양미 삼백 석을 부처님께 바치면 눈을 뜰 수 있을 것이라고 말했습니다. 앞뒤를 가리지 못한 아버지는 그 자리에서 삼백 석을 바치겠다고 약속하고 말았습니다. 집에 돌아온 뒤에야 아버지는 그런 큰돈을 마련할 길이 없다는 것을 깨닫고 깊이 한탄했습니다.',
            '이 소식을 들은 심청은 마침 사람을 제물로 구하던 뱃사람들을 찾아갔습니다. 뱃사람들은 인당수라는 험한 바다를 지날 때 바칠 처녀를 찾고 있었고, 그 대가로 공양미 삼백 석을 주기로 했습니다. 심청은 아버지의 눈을 뜨게 하기 위해 자신을 제물로 바치기로 결심했습니다.',
            '심청은 아버지에게 사실대로 말하지 않고, 절에 불공을 드리러 간다고 거짓말을 했습니다. 뱃사람들과 함께 배를 타고 인당수에 이른 심청은 성난 파도를 향해 몸을 던졌습니다. 아버지는 그때까지도 딸이 이미 죽음을 향해 떠났다는 것을 전혀 알지 못했습니다.',
            '심청이 바다에 몸을 던지자, 용왕이 그녀의 효심에 감동하여 심청을 용궁으로 데려가 정성껏 보살펴 주었습니다. 얼마 후 용왕은 심청을 커다란 연꽃 속에 넣어 다시 바다 위로 떠오르게 했습니다. 마침 그곳을 지나던 어부들이 연꽃을 발견하고 황제에게 바쳤습니다.',
            '연꽃 속에서 나온 심청은 아름다움과 지혜로 황제의 마음을 사로잡아 황후가 되었습니다. 황후가 된 심청은 전국의 눈먼 사람들을 모아 큰 잔치를 열어 아버지를 찾으려 했습니다. 마침내 잔치에서 딸을 만난 아버지는 너무 놀라고 기뻐한 나머지 번쩍 눈을 떴습니다.',
        ],
        'paras_en': [
            "Long ago, in a village in Hwanghae Province, a blind scholar named Shim Hak-gyu lived with his daughter, Shim Cheong. Shim Cheong's mother passed away not long after giving birth to her, and her blind father raised her with great difficulty, feeding her with milk begged from neighbors. As Shim Cheong grew up, she became an increasingly devoted daughter.",
            "From a young age, Shim Cheong helped with neighbors' chores and did needlework for hire to devotedly care for her blind father. Seeing his daughter work so hard, the father always felt both sorry and grateful. One day, the father fell into a stream and was barely saved by a passing monk.",
            "The monk told him that if he offered three hundred sacks of rice to Buddha, he would be able to see again. Without thinking it through, the father promised on the spot to offer the three hundred sacks. Only after returning home did he realize he had no way to gather such a large sum, and he lamented deeply.",
            "When Shim Cheong heard this, she went to find some sailors who happened to be looking for a human sacrifice. The sailors were seeking a young woman to offer to the rough sea called Indangsu, and in exchange they promised three hundred sacks of rice. Shim Cheong decided to offer herself as the sacrifice so that her father could see again.",
            "Shim Cheong did not tell her father the truth, and instead lied that she was going to a temple to pray. Sailing with the sailors, she reached Indangsu and threw herself into the raging waves. Up to that moment, her father had no idea at all that his daughter had already set off toward death.",
            "When Shim Cheong threw herself into the sea, the Dragon King was moved by her filial devotion and took her to his underwater palace, where he cared for her tenderly. Some time later, the Dragon King placed her inside a great lotus flower and sent it floating back up to the surface of the sea. Fishermen who happened to be passing by found the lotus flower and presented it to the emperor.",
            "Emerging from the lotus flower, Shim Cheong captured the emperor's heart with her beauty and wisdom and became empress. As empress, Shim Cheong gathered all the blind people in the country for a great feast, hoping to find her father. At last, when her father met his daughter at the feast, he was so astonished and overjoyed that his eyes suddenly opened.",
        ],
        'questions': [
            {'after': 1, 'q': "What happened to Shim Cheong's father before he met the monk?", 'options': ["He lost his job", "He fell into a stream", "He was robbed", "He got lost in the mountains"], 'correct': 1},
            {'after': 3, 'q': "Why did Shim Cheong seek out the sailors?", 'options': ["To ask them for a job", "To offer herself as a sacrifice in exchange for rice for her father", "To sell her needlework", "To find passage to another village"], 'correct': 1},
            {'after': 5, 'q': "What did the Dragon King do with Shim Cheong?", 'options': ["He kept her prisoner forever", "He sent her back up inside a lotus flower", "He turned her into a fish", "He punished her for lying"], 'correct': 1},
            {'after': 6, 'q': "How did Shim Cheong's father regain his sight?", 'options': ["A doctor cured him", "He drank a magic potion", "He was overjoyed upon finally meeting his daughter", "The Dragon King restored it"], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ko-05', 'tier': 'C1', 'title': '나무꾼과 선녀', 'title_en': "The Woodcutter and the Fairy",
        'origin': "Korean folk tale, traditional oral literature",
        'paras': [
            '깊은 산속에서 홀로 나무를 해다 파는 가난한 나무꾼이 살고 있었습니다. 어느 날 그는 사냥꾼에게 쫓기던 사슴 한 마리와 맞닥뜨렸는데, 사슴은 다급한 목소리로 자신을 숨겨 달라고 애원했습니다. 나무꾼은 측은한 마음이 들어 사슴을 장작더미 뒤에 숨겨 주었고, 사냥꾼들이 지나가자 사슴은 목숨을 구해 준 은혜를 결코 잊지 않겠다고 말했습니다.',
            '며칠 뒤, 사슴은 나무꾼을 찾아와 은혜를 갚겠다며 한 가지 비밀을 알려 주었습니다. 보름달이 뜨는 밤이면 하늘의 선녀들이 산속 연못에 내려와 목욕을 한다는 것이었습니다. 사슴은 나무꾼에게 선녀들이 벗어 둔 날개옷 한 벌을 몰래 감추라고 일러 주면서, 다만 아이 셋을 낳기 전에는 절대로 그 옷을 돌려주지 말라고 신신당부했습니다.',
            '나무꾼은 사슴의 말대로 연못가에 숨어 있다가 선녀 한 명의 날개옷을 몰래 훔쳤습니다. 목욕을 마친 다른 선녀들은 날개옷을 입고 하늘로 날아올랐지만, 옷을 잃어버린 선녀는 땅에 남겨져 어쩔 줄 몰랐습니다. 나무꾼은 그 선녀에게 다가가 자신의 집으로 데려갔고, 두 사람은 결국 부부의 연을 맺게 되었습니다.',
            '세월이 흘러 부부 사이에는 아이가 둘 태어났고, 나무꾼은 사슴의 당부를 까맣게 잊은 채 행복한 나날을 보냈습니다. 그러던 어느 날 선녀는 남편에게 그동안 숨겨 두었던 날개옷을 한 번만 보여 달라고 간절히 졸랐습니다. 마음이 약해진 나무꾼은 결국 아내의 부탁을 이기지 못하고 옷장 깊숙이 숨겨 두었던 날개옷을 꺼내 주고 말았습니다.',
            '날개옷을 손에 넣은 선녀는 양팔에 두 아이를 안고는 순식간에 하늘로 날아올라 사라져 버렸습니다. 홀로 남겨진 나무꾼은 땅을 치며 후회했지만, 이미 늦은 뒤였습니다. 얼마 뒤 다시 나타난 사슴은 딱한 나무꾼에게 마지막 방법 하나를 일러 주었습니다.',
            '사슴은 매달 보름날 밤이면 선녀들이 물을 긷기 위해 하늘에서 커다란 두레박을 내려보낸다고 알려 주었습니다. 나무꾼이 그 두레박을 타면 하늘로 올라가 아내와 아이들을 다시 만날 수 있다는 것이었습니다. 나무꾼은 사슴이 일러 준 대로 연못가에서 기다렸다가 두레박을 타고 마침내 그리운 하늘나라로 올라갔습니다.',
            '하늘나라에서 나무꾼은 아내와 두 아이를 다시 만나 꿈에도 그리던 재회를 이루었고, 그 뒤로 오랫동안 행복하게 살았다고 전해집니다. 다만 이 이야기에는 여러 갈래가 전해 내려오는데, 어떤 판본에서는 나무꾼이 땅에 남겨 둔 늙은 어머니를 그리워하다가 규칙을 어기는 바람에 다시는 하늘로 돌아가지 못했다고도 합니다.',
        ],
        'paras_en': [
            "Deep in the mountains lived a poor woodcutter who gathered and sold firewood alone. One day he came upon a deer being chased by hunters, and the deer begged him in an urgent voice to hide it. Moved with pity, the woodcutter hid the deer behind a pile of firewood, and once the hunters had passed, the deer said it would never forget the kindness that had saved its life.",
            "A few days later, the deer came to find the woodcutter and, wanting to repay his kindness, told him a secret. On nights when the full moon rose, it said, fairies from heaven would come down to bathe in a pond in the mountains. The deer told him to secretly hide one of the feathered robes -- called 날개옷 (nalgaeot), the garments that let the fairies fly -- that the fairies would leave beside the pond, but warned him urgently never to return the robe until she had borne three children.",
            "Following the deer's instructions, the woodcutter hid by the pond and secretly stole one fairy's feathered robe. The other fairies, having finished bathing, put on their robes and flew back to the sky, but the fairy who had lost her robe was left behind on the ground, not knowing what to do. The woodcutter approached her and took her to his home, and the two of them eventually became husband and wife.",
            "As the years passed, the couple had two children, and the woodcutter, having completely forgotten the deer's warning, lived happy days. Then one day, the fairy earnestly begged her husband to let her see the feathered robe he had kept hidden all this time, if only once. His resolve weakening, the woodcutter could not refuse his wife's request and finally brought out the robe he had hidden deep in a chest.",
            "The moment she had the feathered robe in her hands, the fairy scooped up her two children in her arms and vanished into the sky in an instant. Left alone, the woodcutter beat the ground in regret, but it was already too late. Some time later, the deer appeared again and told the pitiful woodcutter one last way to fix things.",
            "The deer explained that every full-moon night, the fairies lowered a great bucket down from heaven to draw water. If the woodcutter rode up in that bucket, it said, he could climb to heaven and see his wife and children again. Following the deer's instructions, the woodcutter waited by the pond, rode up in the bucket, and at last ascended to the heavenly kingdom he had longed for.",
            "In the heavenly kingdom, the woodcutter was reunited with his wife and two children, achieving the reunion he had dreamed of, and it is said they lived happily for many years after. However, several versions of this tale have been passed down, and in one variant, the woodcutter grows homesick for the elderly mother he left behind on earth, breaks a rule in trying to visit her, and is never able to return to heaven again.",
        ],
        'questions': [
            {'after': 1, 'q': "What condition did the deer set for returning the fairy's feathered robe?", 'options': ["Not to return it until they had married for ten years", "Not to return it until the fairy had borne three children", "Not to return it until winter came", "Not to return it until the deer said so directly"], 'correct': 1},
            {'after': 3, 'q': "Why did the fairy eventually get her feathered robe back?", 'options': ["She found it herself while cleaning", "The deer gave it back to her", "The woodcutter gave in to her pleading and showed it to her", "The children found it and gave it to her"], 'correct': 2},
            {'after': 5, 'q': "How did the woodcutter reach heaven?", 'options': ["He grew wings himself", "He rode up in a bucket the fairies used to draw water", "He climbed an enormous tree", "He asked the hunters for help"], 'correct': 1},
            {'after': 6, 'q': "According to the story, what happens in one version of the tale's ending?", 'options': ["The woodcutter stays in heaven forever without incident", "The woodcutter breaks a rule trying to visit his mother and cannot return to heaven", "The fairy returns to earth to live with him", "The deer becomes human"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ko-06', 'tier': 'C2', 'title': '춘향전', 'title_en': "The Tale of Chunhyang",
        'origin': "Korean folk tale (pansori tradition), traditional oral literature",
        'paras': [
            '전라도 남원 땅, 봄기운이 완연한 광한루 부근에서 사또의 아들 이몽룡은 그네를 타는 한 처녀의 자태에 그만 넋을 잃고 말았습니다. 그 처녀는 퇴기의 딸 춘향이었는데, 신분의 벽에도 불구하고 그 자태와 기품은 여느 양반집 규수 못지않았습니다. 두 사람은 첫눈에 서로에게 마음을 빼앗겼고, 그날 밤 몽룡은 춘향의 집을 찾아 백년가약을 맺었습니다.',
            '그러나 행복은 오래가지 못했습니다. 몽룡의 아버지가 한양으로 영전하게 되면서, 몽룡 역시 아버지를 따라 떠나야 하는 처지에 놓이고 만 것입니다. 몽룡은 눈물을 흘리는 춘향의 손을 부여잡고, 반드시 장원 급제하여 돌아와 그녀를 정실부인으로 맞이하겠노라 굳게 맹세했습니다.',
            '몽룡이 떠난 뒤, 남원에는 변학도라는 새로운 사또가 부임해 왔습니다. 변학도는 학정을 일삼는 탐관오리로, 부임하자마자 미모가 뛰어나다는 춘향을 관아로 불러들여 수청을 들라고 명령했습니다. 춘향은 이미 지아비를 섬기는 몸이라며 단호히 거절했고, 그 절개는 죽음 앞에서도 꺾이지 않았습니다.',
            '분노한 변학도는 춘향을 옥에 가두고 모진 매질을 가하며 마음을 돌리라 윽박질렀습니다. 그러나 춘향은 형벌의 고통 속에서도 지조를 굽히지 않았고, 오히려 사또의 폭정을 준엄하게 꾸짖었습니다. 옥중에서 춘향은 나날이 쇠약해져 갔지만, 몽룡을 향한 그리움만은 조금도 옅어지지 않았습니다.',
            '한편 한양으로 올라간 몽룡은 밤낮으로 학문에 정진한 끝에 마침내 장원 급제하여 암행어사라는 중책을 제수받았습니다. 암행어사는 임금의 밀명을 받아 각 고을의 부정을 은밀히 조사하는 벼슬이었습니다. 몽룡은 남루한 거지 행색으로 변장하고서 남원으로 향했으니, 이는 춘향의 절개를 시험함과 동시에 변학도의 학정을 낱낱이 파헤치려는 계책이었습니다.',
            '거지 차림의 몽룡은 옥에 갇힌 춘향을 찾아갔고, 춘향은 초라해진 그의 모습에도 아랑곳하지 않고 한결같은 사랑을 보여 주었습니다. 이튿날은 마침 변학도의 생일잔치가 크게 열리는 날이었는데, 몽룡은 거지 행색으로 잔치에 끼어들어 변학도와 아전들의 횡포를 낱낱이 지켜보았습니다. 이윽고 몽룡이 암행어사 출두를 외치자, 잔치판은 삽시간에 아수라장으로 변하고 말았습니다.',
            '암행어사의 위엄 앞에서 변학도는 그 자리에서 파직되어 끌려갔고, 춘향은 마침내 옥에서 풀려나 그토록 그리던 낭군과 재회했습니다. 임금은 춘향의 굳은 절개를 높이 사 그녀에게 정렬부인이라는 칭호를 내렸으며, 두 사람은 이후 오래도록 부귀영화를 누리며 행복하게 살았다고 전해집니다.',
        ],
        'paras_en': [
            "In Namwon, in Jeolla Province, in the full flush of spring near the Gwanghallu pavilion, the magistrate's son Yi Mong-ryong was utterly captivated by the sight of a young woman on a swing. That woman was Chunhyang, the daughter of a retired gisaeng, yet despite the barrier of her low status, her bearing and grace rivaled that of any noblewoman. The two fell for each other at first sight, and that very night Mong-ryong visited Chunhyang's home and pledged eternal devotion to her.",
            "But their happiness did not last long. When Mong-ryong's father was transferred to Hanyang (the old name for Seoul), Mong-ryong found himself forced to follow him there. Clasping the hand of a weeping Chunhyang, Mong-ryong swore a solemn oath that he would pass the state examination with top honors and return to make her his lawful wife.",
            "After Mong-ryong left, a new magistrate named Byun Hak-do arrived to govern Namwon. Byun was a corrupt official who abused his power, and as soon as he took office, he summoned Chunhyang, whose beauty was renowned, and ordered her to attend and serve him. Chunhyang firmly refused, declaring that she already belonged to a husband, and her resolve did not waver even in the face of death.",
            "Enraged, Byun Hak-do threw Chunhyang in prison and had her brutally beaten, trying to force her to change her mind. Yet even amid the agony of her punishment, Chunhyang did not bend her principles, and instead sternly rebuked the magistrate's tyranny. Day by day she grew weaker in prison, but her longing for Mong-ryong never faded in the slightest.",
            "Meanwhile, in Hanyang, Mong-ryong had devoted himself to his studies day and night and at last passed the state examination with the highest honors, earning the weighty post of secret royal inspector. A secret royal inspector was an official who, under the king's confidential orders, covertly investigated corruption in each region. Mong-ryong disguised himself in a beggar's ragged clothes and set out for Namwon, both to test Chunhyang's fidelity and to expose Byun Hak-do's misrule in full.",
            "Disguised as a beggar, Mong-ryong went to see Chunhyang in prison, and she, unbothered by his shabby appearance, showed him the same unwavering love as ever. The next day happened to be the day of Byun Hak-do's grand birthday banquet, and Mong-ryong slipped into the feast in his beggar's guise, observing in full the corruption of Byun and his underlings. Before long, Mong-ryong cried out that the secret royal inspector had arrived, and the banquet hall was instantly thrown into chaos.",
            "Before the authority of the royal inspector, Byun Hak-do was stripped of his post on the spot and dragged away, and Chunhyang was at last released from prison to reunite with the husband she had longed for. The king, honoring Chunhyang's unyielding fidelity, bestowed upon her the title of Lady of Chastity, and it is said that the two of them lived on afterward in wealth and happiness for many years.",
        ],
        'questions': [
            {'after': 1, 'q': "What did Mong-ryong promise Chunhyang before he left for Hanyang?", 'options': ["To send her money every month", "To pass the state exam and return to marry her properly", "To bring her to Hanyang immediately", "To forget about his studies"], 'correct': 1},
            {'after': 3, 'q': "How did Chunhyang respond to Byun Hak-do's demand that she serve him?", 'options': ["She agreed out of fear", "She fled Namwon", "She refused, saying she already belonged to a husband", "She bribed him to leave her alone"], 'correct': 2},
            {'after': 5, 'q': "What position did Mong-ryong earn after passing the state exam?", 'options': ["Local magistrate of Namwon", "A secret royal inspector", "A court poet", "A palace guard"], 'correct': 1},
            {'after': 6, 'q': "What title did the king give Chunhyang for her fidelity?", 'options': ["Queen of Namwon", "Lady of Chastity", "Royal Inspector", "Retired gisaeng"], 'correct': 1},
        ],
    },
]
