# -*- coding: utf-8 -*-
# Traditional tales of the Turkish-speaking world, retold and graded for the Ship's Library
LANG = 'tr'
FOLK = [
    {
        'id': 'fk-tr-01', 'tier': 'B1', 'title': "Kazan Doğurdu", 'title_en': "The Cauldron Gave Birth",
        'origin': "Nasreddin Hodja tales, Anatolia (Turkey), 13th century",
        'paras': [
            "Bir gün Nasreddin Hoca, komşusundan büyük bir kazan ödünç aldı. Komşusu kazanı çok seviyordu. Hoca kazanı eve götürdü ve yemek pişirdi.",
            "Birkaç gün sonra Hoca, kazanı komşusuna geri götürdü. Kazanın içinde küçük bir tencere vardı. Komşusu şaşırdı ve sordu: \"Bu tencere nedir?\"",
            "Hoca gülümsedi ve dedi ki: \"Senin kazanın bir bebek doğurdu. Bu küçük tencere onun çocuğu.\" Komşusu çok sevindi ve tencereyi aldı.",
            "Aradan bir hafta geçti. Hoca yine komşusuna gitti ve kazanı ödünç istedi. Komşusu memnuniyetle kazanı verdi, çünkü belki yine bir bebek doğurabilirdi.",
            "Ama bu sefer Hoca kazanı geri getirmedi. Günler geçti, haftalar geçti. Sonunda komşusu Hoca'nın evine gitti ve kazanını sordu.",
            "Hoca üzgün bir yüzle dedi ki: \"Çok kötü bir haberim var. Kazanın öldü.\" Komşusu çok kızdı ve bağırdı: \"Bir kazan nasıl ölür?\"",
            "Hoca sakin sakin cevap verdi: \"Sen kazanın doğurduğuna inandın, neden öldüğüne inanmıyorsun?\" Komşusu ne diyeceğini bilemedi ve eve döndü. Bu hikaye bugün hala Türkiye'de anlatılır.",
        ],
        'paras_en': [
            "One day, Nasreddin Hodja borrowed a big cauldron from his neighbor. His neighbor loved the cauldron very much. Hodja took the cauldron home and cooked food in it.",
            "A few days later, Hodja brought the cauldron back to his neighbor. Inside the cauldron there was a small pot. The neighbor was surprised and asked, \"What is this pot?\"",
            "Hodja smiled and said, \"Your cauldron gave birth to a baby. This small pot is its child.\" The neighbor was very happy and took the pot.",
            "A week passed. Hodja went to his neighbor again and asked to borrow the cauldron. The neighbor gladly gave it to him, because maybe it would give birth again.",
            "But this time Hodja did not bring the cauldron back. Days passed, weeks passed. Finally the neighbor went to Hodja's house and asked about his cauldron.",
            "Hodja said with a sad face, \"I have very bad news. The cauldron died.\" The neighbor got very angry and shouted, \"How can a cauldron die?\"",
            "Hodja calmly answered, \"You believed the cauldron gave birth, so why don't you believe it died?\" The neighbor did not know what to say and went home. This story is still told in Turkey today.",
        ],
        'questions': [
            {'after': 1, 'q': "What did the neighbor find inside the cauldron when Hodja returned it?", 'options': ["A letter", "A small pot", "Some coins", "A piece of cloth"], 'correct': 1},
            {'after': 3, 'q': "Why did the neighbor gladly lend the cauldron to Hodja a second time?", 'options': ["He wanted Hodja to fix it", "He thought it might give birth again", "He needed space in his house", "Hodja paid him money"], 'correct': 1},
            {'after': 5, 'q': "What news did Hodja give the neighbor about the cauldron?", 'options': ["That it was stolen", "That it broke", "That it died", "That he sold it"], 'correct': 2},
            {'after': 6, 'q': "What was Hodja's clever argument at the end of the story?", 'options': ["That cauldrons are expensive", "That the neighbor should buy a new cauldron", "That if the neighbor believed it gave birth, he should believe it died", "That the neighbor was too greedy"], 'correct': 2},
        ],
    },
    {
        'id': 'fk-tr-02', 'tier': 'B1', 'title': "Ye Kürküm Ye", 'title_en': "Eat, My Fur Coat, Eat",
        'origin': "Nasreddin Hodja tales, Anatolia (Turkey), 13th century",
        'paras': [
            "Bir gün Nasreddin Hoca, zengin bir komşusunun düğün yemeğine davet edildi. Hoca eski ve basit kıyafetlerini giydi ve yemeğe gitti.",
            "Kapıda hizmetçiler onu gördü ama içeri almadı. \"Bu adam çok fakir görünüyor,\" dediler ve onu kovdular. Hoca çok üzüldü ama hiçbir şey söylemedi.",
            "Hoca eve gitti ve en güzel kürkünü giydi. Sonra tekrar düğüne döndü. Bu sefer herkes ona saygıyla davrandı ve onu en iyi yere oturttular.",
            "Sofrada güzel yemekler vardı. Hoca yemeğini almadı, bunun yerine kürkünün kolunu yemeğe daldırdı. Herkes şaşkınlıkla ona baktı.",
            "Ev sahibi sordu: \"Hocam, ne yapıyorsunuz?\" Hoca ciddi bir sesle cevap verdi: \"Ben değil, kürküm yiyor. Çünkü beni değil, kürkümü davet ettiniz.\"",
            "Ev sahibi utandı ve özür diledi. O gün herkes anladı ki insana dışarıdan değil, kim olduğuna göre davranmak gerekir.",
            "Bu hikaye, Türk kültüründe saygının kıyafetle değil, insanın kendisiyle ilgili olduğunu anlatır. Bugün hala \"Ye kürküm ye\" sözü bu hikayeden gelir.",
        ],
        'paras_en': [
            "One day, Nasreddin Hodja was invited to a rich neighbor's wedding feast. Hodja put on his old, simple clothes and went to the meal.",
            "The servants at the door saw him but did not let him in. \"This man looks very poor,\" they said, and turned him away. Hodja was very sad but said nothing.",
            "Hodja went home and put on his finest fur coat. Then he returned to the wedding. This time everyone treated him with respect and seated him in the best place.",
            "There was fine food on the table. Hodja did not take any food; instead he dipped the sleeve of his fur coat into the food. Everyone stared at him in surprise.",
            "The host asked, \"Hodja, what are you doing?\" Hodja answered seriously, \"It is not me eating, it is my fur coat. Because you did not invite me, you invited my coat.\"",
            "The host felt ashamed and apologized. That day everyone understood that people should be treated according to who they are, not how they look on the outside.",
            "This story tells how, in Turkish culture, respect is about the person, not the clothing. Even today, the saying \"Eat, my fur coat, eat\" comes from this story.",
        ],
        'questions': [
            {'after': 1, 'q': "Why didn't the servants let Hodja into the wedding at first?", 'options': ["He arrived too late", "He looked too poor", "He wasn't invited", "He was a stranger to them"], 'correct': 1},
            {'after': 3, 'q': "How did people treat Hodja differently when he returned?", 'options': ["They ignored him completely", "They gave him worse food", "They treated him with respect and gave him the best seat", "They asked him to leave again"], 'correct': 2},
            {'after': 5, 'q': "What did Hodja do with his fur coat at the table?", 'options': ["He sold it", "He dipped its sleeve into the food", "He gave it to the host", "He took it off"], 'correct': 1},
            {'after': 6, 'q': "What is the meaning of the saying \"Eat, my fur coat, eat\"?", 'options': ["That fine clothes bring good luck", "That food should never be wasted", "That people should be respected for who they are, not their clothes", "That guests should always dress formally"], 'correct': 2},
        ],
    },
    {
        'id': 'fk-tr-03', 'tier': 'B2', 'title': "Keloğlan ile Dev", 'title_en': "Keloğlan and the Giant",
        'origin': "Turkish folk tales (Keloğlan cycle), Anatolia",
        'paras': [
            "Eskiden, Anadolu'nun bir köyünde, Keloğlan adında fakir ama zeki bir genç yaşarmış. Annesiyle küçük bir kulübede otururlarmış ve geçimlerini zor sağlarlarmış. Keloğlan, kel başına rağmen herkesten daha akıllı olduğunu her fırsatta gösterirmiş.",
            "Bir gün köye korkunç bir dev gelmiş ve köylülerin hayvanlarını, ürünlerini çalmaya başlamış. Köylüler çaresizlik içinde kalmışlar, çünkü devle savaşacak güçleri yokmuş. Eğer biri devi durduramazsa, köy tamamen yok olacakmış.",
            "Keloğlan, \"Ben bu devi durdururum,\" demiş ve köylülerin şaşkın bakışları arasında devin mağarasına doğru yola çıkmış. Yanına sadece bir torba un, bir bıçak ve keskin zekasını almış.",
            "Mağaraya vardığında dev onu görmüş ve gülmüş: \"Seni tek lokmada yerim, küçük çocuk!\" Ama Keloğlan korkmamış; eğer korksaydı, hemen kaçardı. Bunun yerine bir taş alıp elinde sıkmış gibi yaparak suyunu akıtmış, aslında torbasındaki peyniri sıkmış.",
            "\"Bak,\" demiş Keloğlan, \"ben taştan bile su çıkarabilirim. Sen benimle güreşmeye kalkarsan, seni un ufak ederim.\" Dev bu numaraya inanmış ve korkmaya başlamış. Zeki köylü çocuğunun gücünden şüphe etmemiş.",
            "Dev, Keloğlan'la asla karşı karşıya gelmemeye karar vermiş ve köyden sonsuza dek uzaklaşmış. Köylüler bu haberi duyunca büyük bir sevinç yaşamışlar ve Keloğlan'ı kahraman ilan etmişler.",
            "O günden sonra Keloğlan'a artık kimse kel diye gülmemiş; herkes onun zekasına hayran kalmış. Bu masal, Anadolu'da güç kadar aklın da önemli olduğunu anlatmak için nesilden nesile aktarılmış.",
        ],
        'paras_en': [
            "Long ago, in a village in Anatolia, there lived a poor but clever young man named Keloğlan. He lived with his mother in a small hut, and they earned their living with difficulty. Despite his bald head, Keloğlan showed at every opportunity that he was smarter than everyone else.",
            "One day a terrifying giant came to the village and began stealing the villagers' animals and crops. The villagers were left helpless, because they had no strength to fight the giant. If no one could stop the giant, the village would be completely destroyed.",
            "\"I will stop this giant,\" Keloğlan said, and set off toward the giant's cave under the villagers' astonished gazes. He took with him only a sack of flour, a knife, and his sharp wit.",
            "When he reached the cave, the giant saw him and laughed: \"I will eat you in one bite, little boy!\" But Keloğlan was not afraid; if he had been afraid, he would have run away at once. Instead, he picked up a stone and pretended to squeeze it in his hand, letting liquid drip out — in fact he was squeezing cheese from his sack.",
            "\"Look,\" Keloğlan said, \"I can even squeeze water out of stone. If you try to wrestle me, I will grind you to powder.\" The giant believed this trick and began to grow afraid. He no longer doubted the strength of the clever village boy.",
            "The giant decided never to face Keloğlan again and moved away from the village forever. When the villagers heard this news, they were filled with great joy and declared Keloğlan a hero.",
            "From that day on, no one laughed at Keloğlan for being bald anymore; everyone admired his cleverness instead. This tale has been passed down from generation to generation in Anatolia to show that wit matters as much as strength.",
        ],
        'questions': [
            {'after': 1, 'q': "Why were the villagers unable to deal with the giant themselves?", 'options': ["They had no leader", "They had no strength to fight him", "They had already left the village", "They did not believe he existed"], 'correct': 1},
            {'after': 3, 'q': "What trick did Keloğlan use to frighten the giant?", 'options': ["He threw fire at him", "He pretended to squeeze water out of a stone", "He called for help from soldiers", "He showed the giant a sword"], 'correct': 1},
            {'after': 5, 'q': "What did the giant decide to do after being tricked?", 'options': ["Fight Keloğlan anyway", "Move away from the village forever", "Ask Keloğlan to be his friend", "Steal more animals before leaving"], 'correct': 1},
            {'after': 6, 'q': "What lesson does this tale teach, according to the passage?", 'options': ["That strength always wins", "That wit matters as much as strength", "That giants are never real", "That villagers should never trust strangers"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-tr-04', 'tier': 'B2', 'title': "Karagöz ile Hacivat'ın Doğuşu", 'title_en': "The Birth of Karagöz and Hacivat",
        'origin': "Karagöz and Hacivat shadow-play legend, Ottoman Turkey (Bursa)",
        'paras': [
            "Söylenceye göre, Osmanlı döneminde Bursa'da bir cami inşa ediliyormuş. İnşaatta çalışan iki usta varmış: biri Karagöz, diğeri Hacivat adında.",
            "Karagöz ile Hacivat o kadar eğlenceli ve nükteli konuşurlarmış ki, diğer işçiler çalışmayı bırakıp onları dinlermiş. Bu yüzden inşaat çok yavaş ilerliyormuş ve padişah bu durumdan haberdar olmuş.",
            "Padişah çok kızmış ve iki ustanın idam edilmesini emretmiş. Eğer işçiler onları dinlemeye devam etselerdi, cami hiçbir zaman bitmeyecekmiş, diye düşünmüş padişah.",
            "Ama daha sonra padişah çok pişman olmuş, çünkü Karagöz ile Hacivat'ın konuşmalarını özlemiş. Saraydaki bir şair, padişahı teselli etmek için bir fikir bulmuş.",
            "Şair, deve derisinden iki kukla yapmış; birine Karagöz, diğerine Hacivat demiş. Bir perdenin arkasında bu kuklaları oynatarak ikisinin komik diyaloglarını yeniden canlandırmış.",
            "Padişah bu gösteriyi çok beğenmiş ve gülmüş. Böylece Karagöz ile Hacivat, ölümlerinden sonra bile bir gölge oyunu sanatı olarak yaşamaya devam etmişler.",
            "Bugün hala Türkiye'de Ramazan aylarında Karagöz-Hacivat gölge oyunları sergilenir. Bu gelenek, mizahın ve dostluğun ölümsüzlüğünü simgeler.",
        ],
        'paras_en': [
            "According to legend, during the Ottoman period a mosque was being built in Bursa. Two master craftsmen worked at the construction site: one named Karagöz, the other Hacivat.",
            "Karagöz and Hacivat spoke so amusingly and wittily that the other workers would stop working just to listen to them. Because of this, the construction progressed very slowly, and the sultan learned of the situation.",
            "The sultan became very angry and ordered the two craftsmen executed. He thought that if the workers kept listening to them, the mosque would never be finished.",
            "But later the sultan deeply regretted his decision, because he missed the conversations of Karagöz and Hacivat. A poet at the palace came up with an idea to console the sultan.",
            "The poet made two puppets out of camel hide, naming one Karagöz and the other Hacivat. Behind a screen, he moved these puppets and recreated the pair's funny dialogues.",
            "The sultan loved this performance and laughed. And so Karagöz and Hacivat continued to live on, even after their deaths, as an art form known as shadow theater.",
            "Even today, Karagöz-Hacivat shadow plays are performed in Turkey during the month of Ramadan. This tradition symbolizes the immortality of humor and friendship.",
        ],
        'questions': [
            {'after': 1, 'q': "Why did the mosque construction slow down?", 'options': ["There was not enough stone", "Workers stopped to listen to Karagöz and Hacivat talk", "The sultan ran out of money", "A storm damaged the site"], 'correct': 1},
            {'after': 3, 'q': "What did the sultan feel after ordering the execution?", 'options': ["Relief that the mosque would finish faster", "Regret, because he missed their conversations", "Anger at the workers", "Pride in his decision"], 'correct': 1},
            {'after': 5, 'q': "What material did the poet use to make the puppets?", 'options': ["Wood", "Paper", "Camel hide", "Cloth"], 'correct': 2},
            {'after': 6, 'q': "When are Karagöz-Hacivat shadow plays traditionally performed today?", 'options': ["During weddings", "During the month of Ramadan", "On New Year's Eve", "During harvest festivals"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-tr-05', 'tier': 'C1', 'title': "Basat'ın Tepegöz'ü Öldürmesi", 'title_en': "Basat Kills Tepegöz",
        'origin': "The Book of Dede Korkut, Oghuz Turkic epic tradition",
        'paras': [
            "Dede Korkut Kitabı'nda anlatılan hikayelerden biri, Oğuz beylerinin Tepegöz adlı devle mücadelesini konu alır. Tepegöz, bir çobanla bir peri kızının çocuğuymuş; tek gözü alnının ortasındaymış ve insan eti yiyormuş.",
            "Tepegöz, Oğuz ilinde dehşet saçmaya başlamış; her gün köyden gençleri kaçırıp yiyormuş. Beyler onu durdurmak için defalarca ordu göndermiş, fakat hiçbiri Tepegöz'ün demir gibi derisine zarar verememiş.",
            "Bu sırada, Aruz Koca'nın evlat edindiği Basat adlı yiğit, aslında bir aslan tarafından büyütülmüş olağanüstü bir kahramanmış. Oğuz beyleri, çaresizlik içinde Basat'a başvurmuş ve ondan Tepegöz'le hesaplaşmasını rica etmişler.",
            "Basat, Tepegöz'ün mağarasına gitmiş ve onunla amansız bir mücadeleye girişmiş. Ne var ki devin bedeni kılıç işlemez bir zırh gibiymiş; Basat'ın darbeleri boşa çıkmış.",
            "Basat, aklını kullanarak bir hile düşünmüş: Tepegöz'ü sarhoş edip tek gözünü kızgın bir şişle kör etmiş. Kör olan dev, öfkeyle mağaranın ağzına oturmuş ve dışarı çıkan koyunların sırtına dokunarak Basat'ı yakalamaya çalışmış.",
            "Basat, koyun postuna bürünerek devin elinden kurtulmuş; bu, Homeros'un Kyklops efsanesindeki Odysseus'un hilesini andırır bir sahnedir. Sonunda Basat, devin can damarını bulup onu öldürmüş ve Oğuz ilini bu beladan kurtarmış.",
            "Dede Korkut, bu destanı anlattıktan sonra Basat'a hayır dua etmiş ve onun adının kıyamete kadar anılmasını dilemiş. Bu hikaye, Türk destan geleneğinde akıl ve cesaretin gücün üstesinden gelebileceğini gösteren en eski örneklerden biridir.",
        ],
        'paras_en': [
            "One of the stories told in the Book of Dede Korkut concerns the struggle of the Oghuz lords against a giant named Tepegöz. Tepegöz was the child of a shepherd and a fairy maiden; he had a single eye in the middle of his forehead and ate human flesh.",
            "Tepegöz began spreading terror across the land of the Oghuz, kidnapping and devouring young men from the villages every day. The lords sent armies against him again and again, but none could harm his iron-like skin.",
            "Meanwhile, a young hero named Basat, adopted by Aruz Koca but actually raised by a lioness, was an extraordinary warrior. In their desperation, the Oghuz lords turned to Basat and asked him to settle the score with Tepegöz.",
            "Basat went to Tepegöz's cave and entered into a merciless struggle with him. However, the giant's body was like armor that no sword could pierce; Basat's blows were in vain.",
            "Using his wits, Basat devised a trick: he got Tepegöz drunk and blinded his single eye with a red-hot spit. The blinded giant sat furiously at the mouth of the cave, trying to catch Basat by feeling the backs of the sheep going out.",
            "Basat wrapped himself in a sheepskin and escaped from the giant's grasp — a scene that recalls Odysseus's trick in Homer's Cyclops legend. In the end, Basat found the giant's vital vein and killed him, freeing the Oghuz land from this menace.",
            "After telling this epic tale, Dede Korkut blessed Basat and wished that his name be remembered until the Day of Judgment. This story is one of the oldest examples in Turkic epic tradition showing that wit and courage can overcome brute strength.",
        ],
        'questions': [
            {'after': 1, 'q': "What made it impossible for the lords' armies to defeat Tepegöz?", 'options': ["He could fly away from them", "His skin was like iron and could not be harmed", "He hid in a place no one could find", "He had many other giants helping him"], 'correct': 1},
            {'after': 3, 'q': "Why did the Oghuz lords turn to Basat for help?", 'options': ["He was the oldest and wisest lord", "He was an extraordinary warrior raised by a lioness", "He was Tepegöz's brother", "He had defeated giants before"], 'correct': 1},
            {'after': 5, 'q': "How did Basat escape after blinding Tepegöz?", 'options': ["He fought his way past him with a sword", "He wrapped himself in a sheepskin and slipped past", "He tunneled under the cave", "He waited until the giant fell asleep"], 'correct': 1},
            {'after': 6, 'q': "What does the passage say this story demonstrates in Turkic epic tradition?", 'options': ["That giants always win in the end", "That wit and courage can overcome brute strength", "That shepherds are the bravest heroes", "That fairies protect the Oghuz people"], 'correct': 1},
        ],
    },
    {
        'id': 'fk-tr-06', 'tier': 'C2', 'title': "Ferhat ile Şirin", 'title_en': "Ferhat and Şirin",
        'origin': "Ferhat and Şirin, Persian-Anatolian romantic legend (via Nizami and Turkish oral tradition)",
        'paras': [
            "Efsaneye göre, Ferhat adında yetenekli bir nakkaş, Ermen ülkesinin hükümdarı Mehmene Banu'nun kızı Şirin'e aşık olmuş. Aşkları öylesine derinmiş ki saray, bu birlikteliğe asla izin vermemiş; zira bir zanaatkarın bir prensesle evlenmesi, o çağın katı töresine aykırıymış.",
            "Mehmene Banu, Ferhat'ı savuşturmak için imkânsız görünen bir şart öne sürmüş: Eğer Ferhat, Bisütun dağını delip ülkeye su getirirse, Şirin'i ona verecekmiş. Ferhat, bu teklifi duyar duymaz kazmasını kapmış ve dağa yürümüş; umudu, taştan bile sertmiş.",
            "Yıllarca, gece gündüz durmaksızın kazmış Ferhat; her darbesinde dağın bağrından kıvılcımlar sıçrarmış. Halk, onun bu inatçı emeğine hayranlıkla bakar, kimileri ise \"bu imkânsız bir iş\" diyerek başını sallarmış.",
            "Sonunda dağ delinmek üzereyken, Mehmene Banu telaşa kapılmış; sözünü tutmak istemediği için kurnaz bir yalana başvurmuş. Yaşlı bir kadın göndererek Ferhat'a \"Şirin öldü\" haberini fısıldatmış.",
            "Bu yalanı duyan Ferhat'ın elindeki kazma bir anda ağırlaşmış, göğsündeki umut sönmüş. Öfkeyle değil, derin bir çaresizlikle kazmasını kendi başına indirmiş ve orada can vermiş.",
            "Şirin, gerçeği öğrendiğinde yüreği paramparça olmuş; sevgilisinin mezarına gidip orada ağlaya ağlaya son nefesini vermiş. İki aşık, ancak ölümde birleşebilmiş.",
            "Bu trajik kıssa, yüzyıllardır Anadolu ve İran edebiyatında yeniden anlatılmış; sabrın, sadakatin ve yıkıcı yalanın bedelini hatırlatan bir ibret hikayesi olarak nesilden nesile aktarılmıştır.",
        ],
        'paras_en': [
            "According to legend, a gifted stonemason named Ferhat fell in love with Şirin, daughter of Mehmene Banu, ruler of the land of Armenia. Their love ran so deep that the court would never permit their union, for a craftsman marrying a princess defied the rigid custom of that age.",
            "To turn Ferhat away, Mehmene Banu set what seemed an impossible condition: if Ferhat could carve through Mount Bisütun and bring water to the land, she would give him Şirin. The moment he heard this offer, Ferhat seized his pickaxe and set off for the mountain, his hope harder than stone itself.",
            "For years, Ferhat dug without pause, day and night; sparks leapt from the mountain's flank with every blow. The people gazed at his stubborn labor with admiration, while some shook their heads, saying, \"This is an impossible task.\"",
            "At last, when the mountain was on the verge of being breached, Mehmene Banu grew alarmed; unwilling to honor her word, she resorted to a cunning lie. She sent an old woman to whisper to Ferhat the news that \"Şirin has died.\"",
            "On hearing this lie, the pickaxe in Ferhat's hand suddenly grew heavy, and the hope in his chest went out. Not in rage, but in profound despair, he brought the pickaxe down upon his own head and died on the spot.",
            "When Şirin learned the truth, her heart shattered; she went to her beloved's grave and, weeping without end, breathed her last breath there. The two lovers could only be united in death.",
            "This tragic tale has been retold for centuries in Anatolian and Persian literature; it has been passed down from generation to generation as a cautionary story reminding us of the cost of patience betrayed, loyalty, and a ruinous lie.",
        ],
        'questions': [
            {'after': 1, 'q': "What condition did Mehmene Banu set for Ferhat to win Şirin's hand?", 'options': ["He had to defeat a rival prince", "He had to carve through Mount Bisütun to bring water", "He had to become a nobleman", "He had to leave the kingdom forever"], 'correct': 1},
            {'after': 3, 'q': "What did Mehmene Banu do when the mountain was nearly breached?", 'options': ["She honored her promise immediately", "She sent an old woman to falsely tell Ferhat that Şirin had died", "She offered Ferhat gold instead", "She asked Şirin to marry someone else openly"], 'correct': 1},
            {'after': 5, 'q': "How did Şirin die?", 'options': ["She was killed by Mehmene Banu", "She died of old age", "She wept at Ferhat's grave until she breathed her last breath", "She fell from the mountain"], 'correct': 2},
            {'after': 6, 'q': "How does the passage describe the legacy of this tale?", 'options': ["As a comedy performed at festivals", "As a cautionary story about loyalty and the cost of a ruinous lie", "As a historical record of a real war", "As a children's lullaby"], 'correct': 1},
        ],
    },
]
