# -*- coding: utf-8 -*-
# Traditional tales of the Dutch-speaking world, retold and graded for the Ship's Library
LANG = "nl"
FOLK = [
    {
        "id": "fk-nl-01", "tier": "B1", "title": "De Vliegende Hollander", "title_en": "The Flying Dutchman",
        "origin": "Dutch maritime legend, 17th-18th century Netherlands",
        "paras": [
            "Er was eens een kapitein die Van der Decken heette. Hij voer met zijn schip rond Kaap de Goede Hoop. Het weer was heel slecht, met hoge golven en sterke wind.",
            "De kapitein wilde toch verder varen. Zijn mannen waren bang en zeiden dat het te gevaarlijk was. Maar de kapitein luisterde niet naar hen.",
            "Hij vloekte en zei dat hij rond de kaap zou varen, ook al zou het eeuwig duren. God hoorde zijn woorden. Vanaf dat moment kon het schip nooit meer een haven bereiken.",
            "Het schip van Van der Decken vaart nog steeds over de zee. Het heet de Vliegende Hollander. Andere zeelui zien het schip soms tijdens een storm.",
            "Wie het schip ziet, krijgt ongeluk, zeggen de zeelui. Sommigen zeggen dat de kapitein probeert brieven naar land te sturen. Niemand kan die brieven ooit aannemen.",
            "De legende van de Vliegende Hollander is heel oud. Zeelui vertelden het verhaal al eeuwen geleden aan elkaar. Het verhaal waarschuwt mensen om niet te trots te zijn.",
            "Vandaag kennen veel mensen het verhaal, ook buiten Nederland. Het is een van de bekendste spookverhalen van de zee. De Vliegende Hollander blijft voor altijd op zoek naar een veilige haven.",
        ],
        "paras_en": [
            "Once there was a captain named Van der Decken. He was sailing his ship around the Cape of Good Hope. The weather was very bad, with high waves and strong wind.",
            "The captain wanted to sail on anyway. His men were afraid and said it was too dangerous. But the captain did not listen to them.",
            "He cursed and said he would sail around the cape even if it took forever. God heard his words. From that moment on, the ship could never reach a harbor again.",
            "Van der Decken's ship still sails the sea today. It is called the Flying Dutchman. Other sailors sometimes see the ship during a storm.",
            "Whoever sees the ship gets bad luck, the sailors say. Some say the captain tries to send letters to land. No one can ever accept those letters.",
            "The legend of the Flying Dutchman is very old. Sailors already told each other this story centuries ago. The story warns people not to be too proud.",
            "Today many people know the story, even outside the Netherlands. It is one of the most famous ghost stories of the sea. The Flying Dutchman remains forever in search of a safe harbor.",
        ],
        "questions": [
            {"after": 1, "q": "What did the captain do even though his crew was afraid?", "options": ["He turned the ship around", "He continued sailing anyway", "He asked the crew to vote", "He anchored the ship"], "correct": 1},
            {"after": 3, "q": "What is the name of the captain's ship in the legend?", "options": ["The Golden Hind", "The Flying Dutchman", "The Silver Star", "The Sea Ghost"], "correct": 1},
            {"after": 5, "q": "What does the legend of the Flying Dutchman warn people about?", "options": ["Never sail near Africa", "Being too proud", "Trusting strangers", "Sailing at night"], "correct": 1},
            {"after": 6, "q": "According to the story, what is the Flying Dutchman always looking for?", "options": ["Treasure", "His lost crew", "A safe harbor", "A new captain"], "correct": 2},
        ],
    },
    {
        "id": "fk-nl-02", "tier": "B1", "title": "De Witte Wieven", "title_en": "The White Women",
        "origin": "Dutch and German folklore, ancient burial mounds of the Low Countries",
        "paras": [
            "In het oosten van Nederland liggen oude heuvels in de natuur. Mensen noemen ze grafheuvels. Lang geleden begroeven mensen daar hun doden.",
            "Volgens de legende wonen er geesten in deze heuvels. Mensen noemen hen de Witte Wieven. Het zijn de geesten van wijze vrouwen uit het verleden.",
            "Soms komen de Witte Wieven 's nachts uit de heuvel. Ze dragen witte kleren en dansen in de mist. Boeren zagen hen soms op het veld.",
            "De Witte Wieven konden de toekomst voorspellen. Mensen uit het dorp gingen naar de heuvel om raad te vragen. De vrouwen gaven antwoord, maar altijd op een geheimzinnige manier.",
            "Sommige verhalen zeggen dat de Witte Wieven ook gevaarlijk waren. Wie hen bespotte, kreeg ongeluk. Daarom hadden de dorpelingen groot respect voor hen.",
            "Vandaag bestaan de grafheuvels nog steeds. Je kunt ze bezoeken in provincies zoals Drenthe en Overijssel. Veel plaatsen dragen nog de naam Witte Wievenberg.",
            "De legende leeft voort in verhalen en in de naam van de heuvels. Kinderen horen het verhaal nog steeds van hun grootouders. Zo blijft de herinnering aan de Witte Wieven bewaard.",
        ],
        "paras_en": [
            "In the east of the Netherlands there are old hills in nature. People call them burial mounds. Long ago people buried their dead there.",
            "According to the legend, spirits live in these hills. People call them the White Women. They are the spirits of wise women from the past.",
            "Sometimes the White Women come out of the hill at night. They wear white clothes and dance in the mist. Farmers sometimes saw them in the field.",
            "The White Women could predict the future. People from the village went to the hill to ask for advice. The women gave answers, but always in a mysterious way.",
            "Some stories say the White Women were also dangerous. Whoever mocked them got bad luck. That is why the villagers had great respect for them.",
            "Today the burial mounds still exist. You can visit them in provinces such as Drenthe and Overijssel. Many places still carry the name Witte Wievenberg.",
            "The legend lives on in stories and in the name of the hills. Children still hear the story from their grandparents. That is how the memory of the White Women is preserved.",
        ],
        "questions": [
            {"after": 1, "q": "Who are the White Women, according to the legend?", "options": ["Spirits of wise women from the past", "Ghosts of lost sailors", "Fairies who guard treasure", "Spirits of farmers"], "correct": 0},
            {"after": 3, "q": "What could the White Women do?", "options": ["Heal the sick", "Predict the future", "Control the weather", "Turn into animals"], "correct": 1},
            {"after": 5, "q": "Where can you visit the burial mounds today?", "options": ["In provinces such as Drenthe and Overijssel", "Only in Amsterdam", "Only in Belgium", "They no longer exist"], "correct": 0},
            {"after": 6, "q": "How does the legend continue to live on today?", "options": ["Through school textbooks only", "Through stories grandparents tell children", "Through a yearly festival", "It has been forgotten"], "correct": 1},
        ],
    },
    {
        "id": "fk-nl-03", "tier": "B2", "title": "Het Vrouwtje van Stavoren", "title_en": "The Lady of Stavoren",
        "origin": "Dutch legend from the Frisian port town of Stavoren",
        "paras": [
            "Lang geleden was Stavoren een rijke havenstad aan de Zuiderzee. Er woonde een rijke koopmansvrouw die bekendstond om haar hebzucht. Niemand in de stad was zo rijk als zij, en toch wilde ze altijd meer.",
            "Op een dag riep ze een scheepskapitein bij zich. Ze zei dat hij naar verre landen moest varen en de kostbaarste lading moest meebrengen die hij kon vinden. De kapitein beloofde dat hij zijn best zou doen.",
            "Na maanden kwam het schip terug in de haven. In het ruim lag geen goud en geen zijde, maar zakken vol tarwe. De kapitein legde uit dat hij dacht dat brood belangrijker was dan rijkdom.",
            "De vrouw werd woedend. Ze zei dat ze nog nooit zo beledigd was geweest, en ze beval dat het tarwe in zee gegooid zou worden. De mensen van de stad smeekten haar om het graan aan de armen te geven, maar ze weigerde.",
            "Terwijl het graan de zee in zonk, riep een oude bedelaar dat ze ooit net zo arm zou worden als hij. De vrouw lachte hem uit en zei dat ze net zo makkelijk arm zou worden als de ring die ze droeg zou verdwijnen. Ze gooide haar ring in het water om haar woorden te bewijzen.",
            "Jaren later ving een visser een grote vis. Toen zijn vrouw de vis opensneed, vond ze de gouden ring van de koopmansvrouw in de buik van de vis. Kort daarna verloor de vrouw al haar schepen en haar geld in een grote storm.",
            "Van de vrouw die ooit de rijkste van Stavoren was, bleef niets over dan armoede. Volgens de legende ontstond op de plek waar het tarwe zonk een zandbank, de Vrouwenzand genoemd, die de haven van Stavoren voor altijd blokkeerde. Zo verklaart het verhaal waarom de eens machtige stad langzaam haar rijkdom verloor.",
        ],
        "paras_en": [
            "Long ago, Stavoren was a rich port town on the Zuiderzee. There lived a rich merchant's wife who was known for her greed. No one in the town was as rich as she was, and yet she always wanted more.",
            "One day she called a ship's captain to her. She said he had to sail to distant lands and bring back the most precious cargo he could find. The captain promised he would do his best.",
            "After months the ship returned to the harbor. In the hold lay no gold and no silk, but sacks full of wheat. The captain explained that he thought bread was more important than riches.",
            "The woman became furious. She said she had never been so insulted, and she ordered that the wheat be thrown into the sea. The people of the town begged her to give the grain to the poor, but she refused.",
            "While the grain sank into the sea, an old beggar called out that she would one day become as poor as he was. The woman laughed at him and said she would become poor as easily as the ring she wore would disappear. She threw her ring into the water to prove her words.",
            "Years later a fisherman caught a large fish. When his wife cut the fish open, she found the merchant woman's gold ring in the fish's belly. Soon after, the woman lost all her ships and her money in a great storm.",
            "Of the woman who was once the richest in Stavoren, nothing remained but poverty. According to the legend, a sandbank formed at the spot where the wheat sank, called the Vrouwenzand, which blocked the harbor of Stavoren forever. That is how the story explains why the once-powerful town slowly lost its wealth.",
        ],
        "questions": [
            {"after": 1, "q": "What did the woman order the captain to bring back?", "options": ["Gold and jewels", "The most precious cargo he could find", "A new ship", "Spices from the East"], "correct": 1},
            {"after": 3, "q": "What did the woman do with the wheat the captain brought?", "options": ["She sold it", "She gave it to the poor", "She had it thrown into the sea", "She stored it for winter"], "correct": 2},
            {"after": 5, "q": "What did the fisherman's wife find inside the fish?", "options": ["A map", "The merchant woman's gold ring", "A letter", "A pearl necklace"], "correct": 1},
            {"after": 6, "q": "What is said to have formed where the wheat sank?", "options": ["A new island", "A lighthouse", "A sandbank called the Vrouwenzand", "A whirlpool"], "correct": 2},
        ],
    },
    {
        "id": "fk-nl-04", "tier": "B2", "title": "Reinaert de Vos", "title_en": "Reynard the Fox",
        "origin": "Medieval Dutch fable, Van den vos Reynaerde, 13th century Low Countries",
        "paras": [
            "Aan het hof van koning Nobel de Leeuw kwamen steeds meer klachten binnen over Reinaert de Vos. Iedereen zei dat hij loog, bedroog en stal waar hij maar kon. Alleen Reinaert zelf kwam niet opdagen om zich te verdedigen.",
            "De koning stuurde Bruun de Beer om Reinaert naar het hof te halen. Bruun vond de vos bij zijn burcht en bracht de boodschap over. Reinaert deed vriendelijk en beloofde dat hij Bruun eerst iets lekkers zou laten proeven.",
            "Hij bracht Bruun naar een boomstam die een boer had opengespleten om honing te zoeken. Reinaert zei dat er binnenin de stam heerlijke honing verborgen zat. Zodra Bruun zijn kop en poten in de spleet stak, trok Reinaert de wiggen weg, zodat de stam dichtklapte.",
            "Bruun zat vast en begon vreselijk te brullen van pijn. De boeren uit het dorp hoorden het lawaai en kwamen met stokken aangelopen. Bruun moest zich met alle kracht losrukken en verloor daarbij het vel van zijn kop en poten.",
            "Gewond en vernederd strompelde Bruun terug naar het hof. Toen de koning hem zo zag, werd hij woedend op Reinaert. Hij stuurde meteen Tibeert de Kater om de vos alsnog te halen.",
            "Maar ook Tibeert liet zich door Reinaert om de tuin leiden. De vos beloofde hem muizen, maar stuurde hem in plaats daarvan in een val die een priester voor hem had gezet. Tibeert ontsnapte ternauwernood, net als Bruun eerder.",
            "Zo bewees Reinaert telkens weer dat hij slimmer was dan de sterkste dieren van het hof. Het verhaal leert dat listigheid vaak meer bereikt dan pure kracht. Tot op vandaag is Reinaert de Vos het symbool van de sluwe bedrieger in de Nederlandse taal.",
        ],
        "paras_en": [
            "At the court of King Nobel the Lion, more and more complaints came in about Reynard the Fox. Everyone said he lied, cheated, and stole wherever he could. Only Reynard himself did not show up to defend himself.",
            "The king sent Bruin the Bear to bring Reynard to the court. Bruin found the fox at his stronghold and delivered the message. Reynard acted friendly and promised he would first let Bruin taste something delicious.",
            "He took Bruin to a tree trunk that a farmer had split open to look for honey. Reynard said that delicious honey was hidden inside the trunk. As soon as Bruin stuck his head and paws into the gap, Reynard pulled the wedges away, so that the trunk snapped shut.",
            "Bruin was stuck and began to roar terribly with pain. The farmers from the village heard the noise and came running with sticks. Bruin had to tear himself loose with all his strength and lost the skin of his head and paws in the process.",
            "Wounded and humiliated, Bruin limped back to the court. When the king saw him like that, he became furious with Reynard. He immediately sent Tibert the Cat to fetch the fox anyway.",
            "But Tibert too let himself be deceived by Reynard. The fox promised him mice, but instead sent him into a trap that a priest had set for him. Tibert barely escaped, just like Bruin before him.",
            "In this way Reynard proved again and again that he was smarter than the strongest animals at the court. The story teaches that cunning often achieves more than raw strength. To this day, Reynard the Fox is the symbol of the sly trickster in the Dutch language.",
        ],
        "questions": [
            {"after": 1, "q": "What did the king send Bruin the Bear to do?", "options": ["Fight Reynard", "Bring Reynard to the court", "Guard Reynard's stronghold", "Punish the farmers"], "correct": 1},
            {"after": 3, "q": "What happened to Bruin when he tore himself loose from the tree trunk?", "options": ["He broke his leg", "He lost the skin of his head and paws", "He fell into a river", "He was captured by farmers"], "correct": 1},
            {"after": 5, "q": "What happened to Tibert the Cat?", "options": ["He caught many mice", "He was sent into a trap but barely escaped", "He refused to go", "He became friends with Reynard"], "correct": 1},
            {"after": 6, "q": "What does the story teach, according to the final paragraph?", "options": ["That strength always wins", "That kings should trust no one", "That cunning often achieves more than raw strength", "That animals cannot be trusted"], "correct": 2},
        ],
    },
    {
        "id": "fk-nl-05", "tier": "C1", "title": "De legende van Sinterklaas", "title_en": "The legend of Sinterklaas",
        "origin": "Dutch folk tradition, rooted in the life of Saint Nicholas of Myra, 4th century",
        "paras": [
            "Ieder jaar, halverwege november, meert er in een Nederlandse havenstad een stoomboot aan die naar verluidt helemaal uit Spanje komt. Aan boord bevindt zich Sinterklaas, een goedheiligman met een lange witte baard, gehuld in een rood gewaad en een bisschopsmijter. De legende rond deze figuur gaat terug tot de heilige Nicolaas van Myra, een bisschop die in de vierde eeuw leefde in wat nu Turkije is.",
            "Volgens de overlevering was Nicolaas buitengewoon vrijgevig. Toen hij hoorde dat een arme man zijn drie dochters vanwege geldgebrek niet kon uithuwelijken, gooide hij 's nachts stiekem gouden munten door het raam, zodat de meisjes toch een bruidsschat kregen. Dit heimelijke gebaar van vrijgevigheid vormt tot op de dag van vandaag de kern van het sinterklaasfeest.",
            "In de Lage Landen versmolt het verhaal van de heilige met plaatselijke wintergebruiken, waarbij cadeautjes, gedichten en pepernoten een vaste plek kregen. Sinterklaas reist naar men zegt op een schimmel over de daken en gooit snoepgoed door de schoorsteen voor kinderen die hun schoen hebben gezet. Wie stout is geweest, krijgt in plaats daarvan slechts een roede te zien, hoewel dat tegenwoordig vooral als grapje bedoeld is.",
            "Aan de zijde van Sinterklaas staan zijn helpers, van oudsher Zwarte Pieten genoemd, wier uiterlijk de laatste decennia sterk ter discussie staat en inmiddels in veel steden is aangepast. Zij dragen de grote boeken bij waarin staat opgetekend wie zich het afgelopen jaar goed of stout heeft gedragen. Samen bezorgen ze de cadeautjes en houden ze de stoet feestelijk op gang.",
            "Het hoogtepunt van het feest is pakjesavond, op 5 december, wanneer families samenkomen om cadeaus uit te wisselen die vergezeld gaan van speelse, soms plagerige gedichten. Deze gedichten bevatten doorgaans een vleugje humor over de eigenaardigheden van wie het cadeau ontvangt. De volgende ochtend, op 6 december, vertrekt Sinterklaas naar verluidt weer terug naar Spanje, tot het volgende jaar.",
            "Historici wijzen erop dat de figuur van Sinterklaas ook elementen bevat die aan oudere, voorchristelijke wintertradities doen denken, al blijft de precieze oorsprong onderwerp van discussie onder folkloristen. Wat vaststaat, is dat het beeld van de heilige bisschop zich eeuwenlang heeft vermengd met lokale gebruiken tot het feest zoals het nu gevierd wordt. Zelfs de Amerikaanse Santa Claus ontleent zijn naam rechtstreeks aan het Nederlandse woord Sinterklaas.",
            "Vandaag de dag blijft het sinterklaasfeest een van de meest gekoesterde tradities in Nederland en Vlaanderen, ondanks de maatschappelijke discussies die het inmiddels oproept. Voor kinderen blijft de spanning van pakjesavond onveranderd groot, en de kern van het verhaal, dat vrijgevigheid in het geheim de mooiste vorm van geven is, blijft onaangetast. Zo overleeft het verhaal van een vierde-eeuwse bisschop tot in de eenentwintigste eeuw.",
        ],
        "paras_en": [
            "Every year, in mid-November, a steamboat that is said to come all the way from Spain docks in a Dutch port city. On board is Sinterklaas, a kindly holy man with a long white beard, dressed in a red robe and a bishop's mitre. The legend surrounding this figure goes back to Saint Nicholas of Myra, a bishop who lived in the fourth century in what is now Turkey.",
            "According to tradition, Nicholas was extraordinarily generous. When he heard that a poor man could not marry off his three daughters for lack of money, he secretly threw gold coins through the window at night, so that the girls could still receive a dowry. This secret act of generosity still forms the core of the Sinterklaas celebration to this day.",
            "In the Low Countries, the saint's story merged with local winter customs, in which presents, poems, and spiced cookies found a permanent place. Sinterklaas is said to travel over the rooftops on a white horse and throw sweets down the chimney for children who have set out their shoe. Whoever has been naughty instead gets only a glimpse of a birch rod, though nowadays that is mostly meant as a joke.",
            "At Sinterklaas's side stand his helpers, traditionally called Zwarte Pieten, whose appearance has been the subject of strong debate in recent decades and has since been adjusted in many cities. They carry the large books in which it is recorded who has behaved well or badly over the past year. Together they deliver the presents and keep the procession festive.",
            "The highlight of the celebration is pakjesavond, on December 5th, when families gather to exchange gifts accompanied by playful, sometimes teasing poems. These poems usually contain a touch of humor about the quirks of whoever receives the gift. The next morning, on December 6th, Sinterklaas is said to depart again for Spain, until the following year.",
            "Historians point out that the figure of Sinterklaas also contains elements reminiscent of older, pre-Christian winter traditions, although the precise origin remains a subject of debate among folklorists. What is certain is that the image of the holy bishop has blended for centuries with local customs into the celebration as it is held now. Even the American Santa Claus derives his name directly from the Dutch word Sinterklaas.",
            "Today the Sinterklaas celebration remains one of the most cherished traditions in the Netherlands and Flanders, despite the social debates it now raises. For children, the excitement of pakjesavond remains just as great, and the core of the story, that generosity given in secret is the most beautiful form of giving, remains untouched. Thus the story of a fourth-century bishop survives into the twenty-first century.",
        ],
        "questions": [
            {"after": 1, "q": "What did Saint Nicholas secretly do for the poor man's daughters, according to tradition?", "options": ["He found them husbands himself", "He threw gold coins through the window at night", "He gave them a house", "He wrote to the king on their behalf"], "correct": 1},
            {"after": 3, "q": "What are Sinterklaas's helpers traditionally called?", "options": ["Zwarte Pieten", "De Wieven", "De Kabouters", "De Boeken"], "correct": 0},
            {"after": 5, "q": "Where does the name of the American Santa Claus come from, according to the text?", "options": ["An old German word", "The Dutch word Sinterklaas", "A Spanish legend", "A pre-Christian winter god"], "correct": 1},
            {"after": 6, "q": "What core idea of the story does the final paragraph say remains untouched?", "options": ["That children must always be obedient", "That generosity given in secret is the most beautiful form of giving", "That bishops should be rich", "That Spain and the Netherlands are connected"], "correct": 1},
        ],
    },
    {
        "id": "fk-nl-06", "tier": "C2", "title": "Lange Wapper", "title_en": "Lange Wapper",
        "origin": "Flemish urban legend from Antwerp, Low Countries folklore",
        "paras": [
            "In de nauwe, kronkelende steegjes van het oude Antwerpen, waar de gevels elkaar bijna raken boven de kasseien, waart naar men zegt sinds onheuglijke tijden een wezen rond dat de gedaante aanneemt van al wie het tegenkomt. De Antwerpenaren doopten deze schim Lange Wapper, een reus die zich naar believen kon uitrekken tot boven de daken, of juist ineenkrimpen tot een onschuldig hondje aan de voeten van een argeloze voorbijganger.",
            "Vooral dronkaards en leeglopers die zich na sluitingstijd nog door de stegen waagden, waren zijn favoriete prooi. Hij verscheen dan als een oude bekende, een vriend of een verleidelijke vrouw, om zijn slachtoffer vervolgens een modderpoel of een gracht in te lokken, waarna hij zich grinnikend en torenhoog boven het spartelende slachtoffer uitrekte.",
            "De overlevering wil dat Lange Wapper niet enkel dronkaards teisterde, maar zich evenzeer wreekte op wie de stad onrecht aandeed: hebzuchtige kooplui, oneerlijke ambtenaren en wie zijn gezin verwaarloosde, kregen een even onaangename ontmoeting te verduren. Op die manier fungeerde het schepsel bijna als een soort volkse zedenmeester, wiens dreiging ouders gretig aanwendden om hun kinderen tijdig binnen te roepen.",
            "Een van de bekendste verhalen vertelt hoe een groep stadswachten Lange Wapper eens meende te vangen door hem, verkleed als oude bedelaar, in de boeien te slaan. Nauwelijks hadden ze hem echter afgevoerd, of het wezen zwol aan tot een gedaante zo reusachtig dat de boeien knapten als draadjes, waarop het, schaterlachend om de onnozelheid van zijn belagers, over de daken verdween.",
            "Sommige verhalenvertellers plaatsen de oorsprong van Lange Wapper bij een verdronken reus uit de Scheldemonding, wiens rusteloze geest de stad die hem vergat, tot in eeuwigheid zou blijven achtervolgen. Anderen zien in hem eerder een gestalte geworden waarschuwing, verzonnen door bezorgde ouders en door de stad zelf gekoesterd, omdat een spookverhaal doeltreffender bleek dan enig verbod.",
            "Wat de herkomst ook is, de gestalte van Lange Wapper verweefde zich onlosmakelijk met het collectieve geheugen van Antwerpen, tot op de dag van vandaag zichtbaar in de reuzenfiguur die nog altijd door de straten van de stad paradeert tijdens feestelijke optochten. Kinderen worden er niet langer werkelijk bang van gemaakt, maar de naam roept nog steeds een huivering van herkenning op bij wie in de oude binnenstad is opgegroeid.",
            "Zo blijft Lange Wapper, tussen mythe en moraal, een gestalte die zich, net als weleer, naar de gedaante van zijn toehoorders voegt: voor de een een grappige stadslegende, voor de ander een duistere herinnering aan een tijd waarin de nacht nog werkelijk iets te verbergen had. En misschien is dat de ware aard van het wezen: het bestaat vooral in de verbeelding van wie er nog in gelooft.",
        ],
        "paras_en": [
            "In the narrow, winding alleys of old Antwerp, where the facades nearly touch each other above the cobblestones, a being is said to have wandered since time immemorial, one that takes on the shape of whoever it encounters. The people of Antwerp named this apparition Lange Wapper, a giant who could stretch himself at will to above the rooftops, or shrink down to an innocent little dog at the feet of an unsuspecting passerby.",
            "Drunkards and idlers in particular, who still ventured through the alleys after closing time, were his favorite prey. He would then appear as an old acquaintance, a friend, or a seductive woman, only to lure his victim into a mud puddle or a canal, after which he would stretch himself, grinning and tower-high, above his floundering victim.",
            "Tradition holds that Lange Wapper did not only torment drunkards, but also took revenge on those who wronged the city: greedy merchants, dishonest officials, and those who neglected their families all had an equally unpleasant encounter to endure. In this way the creature functioned almost as a kind of folk moral enforcer, whose threat parents eagerly used to call their children indoors in time.",
            "One of the best-known stories tells how a group of city watchmen once thought they had caught Lange Wapper by clapping him in irons, disguised as an old beggar. Yet they had scarcely led him away when the creature swelled to a shape so enormous that the irons snapped like threads, whereupon it vanished over the rooftops, roaring with laughter at the foolishness of its captors.",
            "Some storytellers place the origin of Lange Wapper with a drowned giant from the mouth of the Scheldt, whose restless spirit would haunt forever the city that forgot him. Others see in him rather a warning given shape, invented by worried parents and cherished by the city itself, because a ghost story proved more effective than any ban.",
            "Whatever the origin, the figure of Lange Wapper became inseparably woven into the collective memory of Antwerp, still visible today in the giant figure that still parades through the streets of the city during festive processions. Children are no longer truly frightened by it, but the name still evokes a shiver of recognition in those who grew up in the old inner city.",
            "So Lange Wapper remains, between myth and morality, a figure that, just as before, takes on the shape of its listeners: for one a funny city legend, for another a dark memory of a time when the night still truly had something to hide. And perhaps that is the true nature of the being: it exists above all in the imagination of those who still believe in it.",
        ],
        "questions": [
            {"after": 1, "q": "Who were Lange Wapper's favorite victims, according to the legend?", "options": ["Children playing outside", "Drunkards and idlers out after closing time", "Sailors returning to port", "Market vendors"], "correct": 1},
            {"after": 3, "q": "What happened when the watchmen tried to arrest Lange Wapper?", "options": ["He escaped by shrinking to the size of a mouse", "He swelled up, broke the irons, and vanished over the rooftops", "He bribed them with gold", "He turned into smoke"], "correct": 1},
            {"after": 5, "q": "How is Lange Wapper still present in Antwerp today?", "options": ["As a statue in the harbor", "As a giant figure that parades through the streets during festive processions", "As the name of a local beer only", "He is completely forgotten"], "correct": 1},
            {"after": 6, "q": "What does the final paragraph suggest about the true nature of the being?", "options": ["That it was purely invented by the church", "That it exists mainly in the imagination of those who still believe in it", "That it was a real historical criminal", "That it no longer has any meaning today"], "correct": 1},
        ],
    },
]
