# -*- coding: utf-8 -*-
# Traditional tales of the Russian-speaking world, retold and graded for the Ship's Library
LANG = 'ru'
FOLK = [
    {
        'id': 'fk-ru-01', 'tier': 'B1', 'title': 'Репка', 'title_en': 'The Turnip',
        'origin': 'Russian folk tale, cumulative tale from the Afanasyev collection',
        'paras': [
            'Дед посадил репку. Репка выросла большая-пребольшая. Дед пошёл тянуть репку из земли.',
            'Тянет-потянет, вытянуть не может. Дед позвал бабку. Бабка пришла на помощь.',
            'Бабка за дедку, дедка за репку. Тянут-потянут, вытянуть не могут. Бабка позвала внучку.',
            'Внучка пришла быстро. Внучка за бабку, бабка за дедку, дедка за репку. Тянут-потянут, вытянуть не могут.',
            'Внучка позвала Жучку. Жучка за внучку, внучка за бабку, бабка за дедку, дедка за репку. Тянут-потянут, вытянуть не могут.',
            'Жучка позвала кошку. Кошка за Жучку, Жучка за внучку, внучка за бабку, бабка за дедку, дедка за репку. Тянут-потянут, вытянуть не могут.',
            'Кошка позвала мышку. Мышка помогла всем. Вместе они вытянули репку!',
        ],
        'paras_en': [
            'Grandfather planted a turnip. The turnip grew very, very big. Grandfather went to pull the turnip out of the ground.',
            'He pulls and pulls, but he cannot pull it out. Grandfather called Grandmother. Grandmother came to help.',
            'Grandmother held Grandfather, Grandfather held the turnip. They pull and pull, but they cannot pull it out. Grandmother called the Granddaughter.',
            'The Granddaughter came quickly. The Granddaughter held Grandmother, Grandmother held Grandfather, Grandfather held the turnip. They pull and pull, but they cannot pull it out.',
            'The Granddaughter called the dog Zhuchka. Zhuchka held the Granddaughter, and so on down the line. They pull and pull, but they cannot pull it out.',
            'Zhuchka called the cat. The cat held Zhuchka, and so on down the whole chain. They pull and pull, but they cannot pull it out.',
            'The cat called the mouse. The mouse helped everyone. Together they pulled the turnip out!',
        ],
        'questions': [
            {'after': 1, 'q': 'Who does Grandfather call for help first?', 'options': ['The dog', 'Grandmother', 'The cat', 'The mouse'], 'correct': 1},
            {'after': 3, 'q': 'Who does the Granddaughter call for help?', 'options': ['The mouse', 'The cat', 'The dog Zhuchka', 'Grandfather'], 'correct': 2},
            {'after': 5, 'q': 'Who does Zhuchka call for help?', 'options': ['The cat', 'The mouse', 'Grandmother', 'The Granddaughter'], 'correct': 0},
            {'after': 6, 'q': 'Who finally makes it possible to pull out the turnip?', 'options': ['Grandfather alone', 'The cat', 'The mouse', 'Grandmother alone'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ru-02', 'tier': 'B1', 'title': 'Колобок', 'title_en': 'Kolobok (The Little Round Loaf)',
        'origin': 'Russian folk tale, cumulative tale from the Afanasyev collection',
        'paras': [
            'Жили-были старик со старухой. Старуха испекла колобок. Колобок был круглый и румяный.',
            'Колобок лежал на окне и остывал. Вдруг он спрыгнул с окна. Колобок покатился по дороге.',
            'Колобок встретил зайца. Заяц сказал: "Колобок, я тебя съем!" Колобок ответил: "Не ешь меня, я тебе песенку спою!"',
            'Колобок спел песенку и укатился от зайца. Потом он встретил волка. Волк тоже хотел его съесть, но колобок укатился.',
            'Колобок встретил медведя. Медведь был большой и страшный. Но колобок снова спел песенку и укатился.',
            'Колобок встретил хитрую лису. Лиса была умнее всех зверей. Она попросила его спеть песенку ещё раз, поближе.',
            'Колобок подкатился ближе. Лиса схватила его и съела. Так закончилась история колобка.',
        ],
        'paras_en': [
            'Once upon a time there lived an old man and an old woman. The old woman baked a kolobok, a little round loaf. The kolobok was round and golden-brown.',
            'The kolobok lay on the windowsill cooling down. Suddenly it jumped off the windowsill. The kolobok rolled off down the road.',
            'The kolobok met a hare. The hare said, "Kolobok, I will eat you!" The kolobok answered, "Do not eat me, I will sing you a little song!"',
            'The kolobok sang its song and rolled away from the hare. Then it met a wolf. The wolf also wanted to eat it, but the kolobok rolled away.',
            'The kolobok met a bear. The bear was big and frightening. But the kolobok sang its song again and rolled away.',
            'The kolobok met a cunning fox. The fox was cleverer than all the other animals. She asked it to sing its song one more time, a little closer.',
            'The kolobok rolled closer. The fox grabbed it and ate it. That is how the story of the kolobok ended.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did the kolobok start rolling down the road?', 'options': ['It jumped off the windowsill on its own', 'The old woman pushed it out', 'A wolf carried it away', 'It was blown by the wind'], 'correct': 0},
            {'after': 3, 'q': 'How does the kolobok escape the hare and the wolf?', 'options': ['It hides in a hole', 'It sings a song and rolls away', 'It calls for the bear', 'It bites them'], 'correct': 1},
            {'after': 5, 'q': 'What does the fox ask the kolobok to do?', 'options': ['Roll away quickly', 'Give her some bread', 'Sing its song again, closer to her', 'Meet the bear'], 'correct': 2},
            {'after': 6, 'q': 'What finally happens to the kolobok?', 'options': ['It escapes forever', 'The fox eats it', 'The bear eats it', 'It returns home'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ru-03', 'tier': 'B2', 'title': 'Морозко', 'title_en': 'Morozko (Grandfather Frost)',
        'origin': 'Russian folk tale, from the Afanasyev collection',
        'paras': [
            'В одной деревне жил старик с двумя дочерьми. Родная дочь была ленивой, а падчерица — доброй и трудолюбивой. Мачеха не любила падчерицу и заставляла её делать всю работу.',
            'Однажды мачеха приказала старику отвезти падчерицу в лес и оставить там одну. Старик не хотел этого делать, но не мог ослушаться жены. Он отвёз дочь в зимний лес и уехал, оставив её под елью.',
            'Девушка сидела под елью и дрожала от холода. Вдруг пришёл Морозко, дух зимнего мороза, и спросил, тепло ли ей. Хотя ей было очень холодно, она вежливо ответила: "Тепло, дедушка Морозко."',
            'Морозко трижды усиливал мороз и трижды спрашивал её. Девушка каждый раз отвечала вежливо, хотя едва могла говорить от холода. Морозко был тронут её терпением и добротой.',
            'За её вежливость Морозко подарил падчерице тёплую шубу и сундук с драгоценностями. Он отвёз её домой живой и невредимой. Старик очень обрадовался, увидев дочь живой и богатой.',
            'Мачеха, узнав об этом, отправила в лес свою родную дочь, надеясь на такие же подарки. Но её дочь была грубой и жаловалась на холод. Когда Морозко спросил, тепло ли ей, она ответила резко и грубо.',
            'Морозко рассердился и заморозил грубую девушку. Старик привёз домой только тело своей ленивой дочери. С тех пор мачеха стала добрее к падчерице, поняв свою ошибку.',
        ],
        'paras_en': [
            'In a certain village there lived an old man with two daughters. His own daughter was lazy, while his stepdaughter was kind and hardworking. The stepmother did not love the stepdaughter and made her do all the work.',
            'One day the stepmother ordered the old man to take the stepdaughter into the forest and leave her there alone. The old man did not want to do this, but he could not disobey his wife. He took his daughter into the winter forest and drove away, leaving her under a fir tree.',
            'The girl sat under the fir tree, shivering with cold. Suddenly Morozko, the spirit of winter frost, appeared and asked whether she was warm. Although she was very cold, she answered politely, "I am warm, Grandfather Frost."',
            'Morozko tightened the frost three times and asked her three times. Each time the girl answered politely, though she could barely speak from the cold. Morozko was moved by her patience and kindness.',
            'For her politeness Morozko gave the stepdaughter a warm fur coat and a chest full of jewels. He brought her home alive and unharmed. The old man rejoiced greatly to see his daughter alive and rich.',
            'When the stepmother heard of this, she sent her own daughter into the forest, hoping for the same gifts. But her daughter was rude and complained about the cold. When Morozko asked whether she was warm, she answered sharply and rudely.',
            'Morozko grew angry and froze the rude girl. The old man brought home only the body of his lazy daughter. From that time on, the stepmother became kinder to her stepdaughter, having understood her mistake.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why does the stepmother send the stepdaughter into the forest?', 'options': ['To gather firewood', 'To leave her there alone, out of dislike', 'To meet Morozko on purpose', 'To find her a husband'], 'correct': 1},
            {'after': 3, 'q': 'How does the stepdaughter respond when Morozko asks if she is warm?', 'options': ['She cries and begs for help', 'She runs away', 'She politely says she is warm', 'She refuses to answer'], 'correct': 2},
            {'after': 5, 'q': 'What reward does Morozko give the stepdaughter?', 'options': ['Nothing at all', 'A warm fur coat and a chest of jewels', 'A magic horse', 'A new house'], 'correct': 1},
            {'after': 6, 'q': 'What happens to the stepmother\'s own daughter in the forest?', 'options': ['She receives even greater riches', 'Morozko freezes her because she is rude', 'She marries Morozko', 'She gets lost and comes home safely'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ru-04', 'tier': 'B2', 'title': 'Иван-царевич и Серый Волк', 'title_en': 'Ivan Tsarevich and the Grey Wolf',
        'origin': 'Russian folk tale, from the Afanasyev collection',
        'paras': [
            'У царя было три сына, и в его саду росла яблоня с золотыми яблоками. Каждую ночь кто-то воровал золотые яблоки. Царь послал сыновей по очереди сторожить сад.',
            'Только младший сын, Иван-царевич, не заснул и увидел вора — это была Жар-птица с золотыми перьями. Иван поймал одно перо, но птица улетела. Царь захотел получить саму Жар-птицу и отправил сыновей на поиски.',
            'В пути Иван встретил Серого Волка, который съел его коня. Волк пожалел царевича и предложил свою помощь вместо коня. Так они вместе отправились за Жар-птицей.',
            'Волк помог Ивану добыть Жар-птицу, затем волшебного коня, а потом и прекрасную Елену Прекрасную, хотя каждый раз предупреждал не брать лишнего. Иван, однако, нарушал советы волка, и это приводило к новым трудностям. Волк каждый раз выручал его благодаря своей волшебной силе.',
            'На обратном пути братья Ивана убили его и забрали Жар-птицу, коня и Елену. Они сказали отцу, что сами всё добыли. Тело Ивана осталось лежать в степи.',
            'Серый Волк нашёл тело Ивана и с помощью живой и мёртвой воды оживил его. Иван вернулся домой уже другим человеком — мудрее и осторожнее. Он разоблачил обман старших братьев перед царём.',
            'Правда восторжествовала: обманщиков наказали, а Иван женился на Елене Прекрасной. Серый Волк попрощался с Иваном и ушёл в лес. С тех пор эту историю рассказывают как пример дружбы и верности.',
        ],
        'paras_en': [
            'A tsar had three sons, and in his garden grew an apple tree with golden apples. Every night someone stole the golden apples. The tsar sent his sons to guard the garden in turn.',
            'Only the youngest son, Ivan Tsarevich, stayed awake and saw the thief — it was the Firebird with golden feathers. Ivan caught one feather, but the bird flew away. The tsar wanted to obtain the Firebird itself and sent his sons out to search for it.',
            'On the way Ivan met the Grey Wolf, who ate his horse. The wolf felt sorry for the prince and offered his own help in place of the horse. So together they set off after the Firebird.',
            'The wolf helped Ivan obtain the Firebird, then a magic horse, and then the beautiful Elena the Fair, though each time he warned Ivan not to take more than needed. Ivan, however, broke the wolf\'s advice, which led to new troubles. The wolf rescued him each time thanks to his magical power.',
            'On the way home Ivan\'s brothers killed him and took the Firebird, the horse, and Elena. They told their father that they had obtained everything themselves. Ivan\'s body was left lying in the steppe.',
            'The Grey Wolf found Ivan\'s body and, using the water of life and the water of death, brought him back to life. Ivan returned home a changed man — wiser and more careful. He exposed his older brothers\' deception before the tsar.',
            'Truth triumphed: the deceivers were punished, and Ivan married Elena the Fair. The Grey Wolf said farewell to Ivan and went off into the forest. Ever since, this story has been told as an example of friendship and loyalty.',
        ],
        'questions': [
            {'after': 1, 'q': 'What was stealing the golden apples from the garden?', 'options': ['A bear', 'The Firebird', 'A wolf', 'The eldest brother'], 'correct': 1},
            {'after': 3, 'q': 'What did the Grey Wolf offer Ivan after eating his horse?', 'options': ['Nothing, he ran off', 'His own help in place of the horse', 'A golden feather', 'A magic sword'], 'correct': 1},
            {'after': 5, 'q': 'What did Ivan\'s brothers do to him on the way home?', 'options': ['They helped him carry the treasures', 'They killed him and took his prizes', 'They abandoned him but let him live', 'They married Elena themselves'], 'correct': 1},
            {'after': 6, 'q': 'How does the story end for Ivan and the Grey Wolf?', 'options': ['They both die in the steppe', 'Ivan marries Elena and the wolf returns to the forest', 'The wolf becomes tsar', 'Ivan never forgives his brothers'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-ru-05', 'tier': 'C1', 'title': 'Садко', 'title_en': 'Sadko',
        'origin': 'Russian bylina (epic song), Novgorod cycle',
        'paras': [
            'В древнем Новгороде жил гусляр по имени Садко. Он не был богат, но играл на гуслях так искусно, что его охотно звали на пиры. Однажды, не получив приглашения, он в одиночестве пошёл играть на берег озера Ильмень.',
            'Царь морской, заворожённый его игрой, вышел из воды и пообещал Садко несметное богатство в обмен на его искусство. Он посоветовал гусляру биться об заклад с новгородскими купцами, что в Ильмень-озере водится рыба с золотыми перьями. Садко так и сделал, и заклад принёс ему сказочное богатство.',
            'Разбогатев, Садко стал самым именитым купцом Новгорода. Он снарядил торговые корабли и отправился за море, чтобы приумножить своё состояние. Слава о его богатстве разнеслась по всем окрестным землям.',
            'Но однажды в открытом море корабли Садко внезапно остановились, будто их держала невидимая сила. Опытные моряки поняли: морской царь требует дань, ведь много лет плавали по его владениям, не платя ему должного. Жребий пал на самого Садко, и ему пришлось спуститься в подводное царство.',
            'В подводных палатах морской царь принял Садко с почётом и попросил сыграть на гуслях. Гусляр играл так вдохновенно, что царь пустился в пляс, а от его пляски в море поднялась страшная буря, топившая корабли. Тогда некая мудрая сила подсказала Садко оборвать струны, чтобы прекратить пляску.',
            'Морской царь предложил Садко жениться на одной из морских дев, суля вечную жизнь в подводном царстве. Но Садко выбрал скромную деву по имени Чернавушка, следуя тайному совету, и уснул на её берегу, а не на брачном ложе. Наутро он проснулся не под водой, а на берегу родной реки Чернавы близ Новгорода.',
            'Обрадованный чудесным спасением, Садко построил на берегу церковь в благодарность и с тех пор больше не выходил в море за счастьем. Он щедро делился богатством с бедняками Новгорода и до конца своих дней прославлял город песнями. Так гусляр Садко остался в памяти народа не только как богач, но и как мастер, покоривший самого морского царя.',
        ],
        'paras_en': [
            'In ancient Novgorod there lived a gusli-player named Sadko. He was not rich, but he played the gusli so skillfully that people gladly invited him to feasts. One day, not having been invited, he went alone to play on the shore of Lake Ilmen.',
            'The Sea King, enchanted by his playing, rose out of the water and promised Sadko untold riches in exchange for his skill. He advised the gusli-player to wager with the Novgorod merchants that golden-finned fish lived in Lake Ilmen. Sadko did so, and the wager brought him fabulous wealth.',
            'Having grown rich, Sadko became the most eminent merchant in Novgorod. He fitted out trading ships and set off across the sea to increase his fortune further. Word of his wealth spread through all the surrounding lands.',
            'But one day, out on the open sea, Sadko\'s ships suddenly stopped, as though held by an invisible force. The experienced sailors understood: the Sea King was demanding tribute, since they had sailed his waters for years without ever paying him his due. The lot fell upon Sadko himself, and he had to descend into the underwater kingdom.',
            'In the underwater halls the Sea King received Sadko with honor and asked him to play the gusli. The player played so inspiredly that the king broke into a dance, and his dancing raised a terrible storm at sea that sank ships. Then some wise counsel told Sadko to snap the strings in order to stop the dance.',
            'The Sea King offered Sadko marriage to one of the sea maidens, promising him eternal life in the underwater kingdom. But Sadko, following secret advice, chose a modest maiden named Chernavushka and fell asleep on her shore rather than on the marriage bed. In the morning he awoke not underwater, but on the bank of the river Chernava near Novgorod, his own homeland.',
            'Overjoyed at his miraculous rescue, Sadko built a church on the riverbank in gratitude and never again went to sea in search of fortune. He generously shared his wealth with the poor of Novgorod and glorified the city with songs to the end of his days. Thus the gusli-player Sadko remained in the people\'s memory not only as a rich man, but as a master who had won over the Sea King himself.',
        ],
        'questions': [
            {'after': 1, 'q': 'How did Sadko first gain the Sea King\'s favor?', 'options': ['He gave him gold', 'He fought a sea monster', 'He played the gusli so well it enchanted him', 'He built him a palace'], 'correct': 2},
            {'after': 3, 'q': 'Why did Sadko\'s ships suddenly stop at sea?', 'options': ['A storm wrecked them', 'The Sea King demanded a tribute that had never been paid', 'They ran out of wind', 'Pirates blocked the way'], 'correct': 1},
            {'after': 5, 'q': 'What did Sadko do to stop the destructive dancing in the sea?', 'options': ['He sang louder', 'He snapped the strings of his gusli', 'He dove into the water', 'He asked the sea maidens for help'], 'correct': 1},
            {'after': 6, 'q': 'How did Sadko finally leave the Sea King\'s underwater kingdom?', 'options': ['He fought his way out', 'He married a sea maiden and stayed forever', 'He fell asleep by Chernavushka and woke up on the riverbank at home', 'The Sea King banished him'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-ru-06', 'tier': 'C2', 'title': 'Снегурочка', 'title_en': 'Snegurochka, the Snow Maiden',
        'origin': 'Russian folk tale, later dramatized by Alexander Ostrovsky; the folk version predates his play',
        'paras': [
            'В стародавние времена жили в деревне бездетные старик со старухою, и в лютой тоске по ребёнку слепили они однажды снежную девочку, дав волю то ли отчаянию, то ли смутной надежде на чудо. К изумлению обоих, снежная фигурка вдруг ожила, обратившись в тихую, бледнолицую девочку, которую нарекли Снегурочкой.',
            'Росла она не по дням, а по часам, но нрав её оставался странен: чуждалась солнечного тепла, сторонилась летних игр и веселья, будто некая внутренняя стужа оберегала само её существование. Старики, впрочем, не чаяли в ней души и старались уберечь приёмную дочь от всякого зноя.',
            'С приходом весны девушки стали звать Снегурочку в лес, на гулянья вокруг костров, и, несмотря на смутную тревогу, та поддалась их уговорам. Юноши засматривались на её неземную красоту, а один из них, пастух Лель, пленил её своим пением настолько, что в сердце Снегурочки впервые шевельнулось незнакомое, тёплое чувство.',
            'Матушка-Весна, тайно наблюдавшая за дочерью, сжалилась над её холодностью и одарила Снегурочку способностью любить по-настоящему, предупредив, однако, что первая же встреча с жарким летним солнцем станет для неё роковой. Снегурочка приняла этот дар, не задумываясь о цене, ибо жажда живого чувства оказалась сильнее осторожности.',
            'Когда на празднике Ивана Купалы девушки разожгли костры и заводили хороводы, Снегурочка, охваченная новообретённой любовью, устремилась вместе со всеми навстречу восходящему солнцу. Лучи светила коснулись её, и на глазах у изумлённой толпы хрупкая фигура начала таять, истончаясь прямо в воздухе.',
            'Она не издала ни стона, ни жалобы — лишь тихая улыбка озарила её лицо, будто минутное счастье любви искупало саму краткость отпущенного ей срока. Там, где стояла Снегурочка, осталось лишь лёгкое облачко пара да влажный след на траве.',
            'Народ долго толковал об этом чуде, одни — со скорбью, другие — с философическим смирением, видя в судьбе снежной девушки извечную притчу о несовместимости хрупкой красоты с испепеляющим жаром бытия. С тех пор имя Снегурочки в русском предании стало синонимом чистоты, обречённой не выдержать соприкосновения с подлинной, обжигающей жизнью.',
        ],
        'paras_en': [
            'In olden times there lived in a village a childless old man and old woman, and in bitter longing for a child they once sculpted a girl out of snow, giving vent to something between despair and a dim hope for a miracle. To the astonishment of them both, the snowy figure suddenly came alive, turning into a quiet, pale-faced girl whom they named Snegurochka, the Snow Maiden.',
            'She grew not by the day but by the hour, yet her temperament remained strange: she shrank from the sun\'s warmth and avoided the games and merriment of summer, as though some inner chill safeguarded her very existence. The old couple, for their part, doted on her and tried to shield their adopted daughter from any heat.',
            'With the coming of spring, the village girls began calling Snegurochka into the forest, to the gatherings around bonfires, and despite a vague unease she gave in to their urging. Young men could not take their eyes off her otherworldly beauty, and one of them, the shepherd Lel, captivated her with his singing so completely that an unfamiliar, warm feeling stirred in Snegurochka\'s heart for the first time.',
            'Mother Spring, who had been secretly watching over her daughter, took pity on her coldness and granted Snegurochka the ability to love truly, warning her, however, that her very first encounter with the blazing summer sun would prove fatal. Snegurochka accepted the gift without weighing its cost, for the thirst for living feeling proved stronger than caution.',
            'When, at the festival of Ivan Kupala, the girls lit bonfires and led round dances, Snegurochka, overcome by her newfound love, rushed forward with everyone else to meet the rising sun. Its rays touched her, and before the astonished crowd her fragile form began to melt, thinning away directly into the air.',
            'She uttered neither a groan nor a complaint — only a quiet smile lit her face, as though the fleeting happiness of love redeemed the very brevity of the time allotted to her. Where Snegurochka had stood, there remained only a light wisp of vapor and a damp trace upon the grass.',
            'The people talked for a long time about this wonder, some with sorrow, others with philosophical resignation, seeing in the snow maiden\'s fate an eternal parable about the incompatibility of fragile beauty with the searing heat of existence. Ever since, the name Snegurochka in Russian tradition has become a synonym for a purity fated not to withstand contact with true, scorching life.',
        ],
        'questions': [
            {'after': 1, 'q': 'How did Snegurochka come into being?', 'options': ['She was found abandoned in the forest', 'An old childless couple sculpted her from snow and she came alive', 'She was born to the couple in the usual way', 'Mother Spring sent her as a gift from the start'], 'correct': 1},
            {'after': 3, 'q': 'What happened to Snegurochka after she met the shepherd Lel?', 'options': ['She fell ill immediately', 'A warm feeling stirred in her heart for the first time', 'She fled back to her parents', 'She refused to listen to his singing'], 'correct': 1},
            {'after': 5, 'q': 'What did Mother Spring\'s gift of true love ultimately cost Snegurochka?', 'options': ['Her memory', 'Nothing, it was a gift with no price', 'Her life, since encountering the summer sun proved fatal', 'Her beauty'], 'correct': 2},
            {'after': 6, 'q': 'How did the people interpret Snegurochka\'s fate afterward?', 'options': ['As proof that magic does not exist', 'As a parable about fragile beauty unable to withstand the heat of true life', 'As a warning against singing at festivals', 'As an unimportant local rumor'], 'correct': 1},
        ],
    },
]
