# -*- coding: utf-8 -*-
# Traditional tales of the German-speaking world, retold and graded for the Ship's Library
LANG = 'de'
FOLK = [
    {
        'id': 'fk-de-01', 'tier': 'B1', 'title': 'Rumpelstilzchen', 'title_en': 'Rumpelstiltskin',
        'origin': 'Brothers Grimm, Germany',
        'paras': [
            'Es war einmal ein armer Müller. Er hatte eine schöne Tochter. Eines Tages traf er den König und sagte: "Meine Tochter kann Stroh zu Gold spinnen." Das war eine große Lüge.',
            'Der König hörte das und wollte es sehen. Er brachte die Tochter in ein Zimmer voller Stroh. "Spinne das Stroh bis morgen zu Gold", sagte er, "sonst musst du sterben."',
            'Das Mädchen saß allein und weinte. Sie konnte kein Gold spinnen. Plötzlich stand ein kleines Männchen im Zimmer. "Was gibst du mir, wenn ich für dich spinne?", fragte es.',
            'Sie gab ihm ihre Halskette, und das Männchen spann das Stroh zu Gold. In der nächsten Nacht brauchte der König noch mehr Gold. Das Mädchen gab dem Männchen ihren Ring dafür.',
            'In der dritten Nacht hatte sie nichts mehr zu geben. Das Männchen sagte: "Dann versprich mir dein erstes Kind." Sie hatte keine andere Wahl und versprach es.',
            'Der König heiratete sie, und sie wurde Königin. Bald bekam sie ein Kind. Da kam das Männchen zurück und wollte das Kind holen. Die Königin weinte und bat ihn, es nicht zu tun.',
            'Das Männchen hatte Mitleid. "Ich gebe dir drei Tage Zeit", sagte es. "Wenn du meinen Namen errätst, darfst du das Kind behalten." Ein Bote hörte, wie das Männchen im Wald sang: "Rumpelstilzchen heiße ich!" Als die Königin den Namen sagte, war das Männchen so wütend, dass es verschwand und nie wieder zurückkam.',
        ],
        'paras_en': [
            'Once there was a poor miller. He had a beautiful daughter. One day he met the king and said, "My daughter can spin straw into gold." That was a big lie.',
            'The king heard this and wanted to see it. He brought the daughter into a room full of straw. "Spin this straw into gold by morning," he said, "or you must die."',
            'The girl sat alone and cried. She could not spin gold. Suddenly a little man stood in the room. "What will you give me if I spin for you?" he asked.',
            'She gave him her necklace, and the little man spun the straw into gold. The next night the king needed even more gold. The girl gave the little man her ring for it.',
            'On the third night she had nothing left to give. The little man said, "Then promise me your first child." She had no other choice and promised it.',
            'The king married her, and she became queen. Soon she had a child. Then the little man came back and wanted to take the child. The queen cried and begged him not to.',
            'The little man felt pity. "I will give you three days," he said. "If you guess my name, you may keep the child." A messenger heard the little man singing in the forest, "My name is Rumpelstiltskin!" When the queen said the name, the little man was so angry that he vanished and never came back.',
        ],
        'questions': [
            {'after': 1, 'q': 'What did the miller tell the king about his daughter?', 'options': ['That she could spin straw into gold', 'That she could bake magic bread', 'That she could sing beautifully', 'That she could weave silk cloth'], 'correct': 0},
            {'after': 3, 'q': 'What did the girl give the little man the first time he helped her?', 'options': ['A gold coin', 'Her necklace', 'Her shoes', 'A loaf of bread'], 'correct': 1},
            {'after': 5, 'q': 'What did the girl promise the little man on the third night?', 'options': ['Half of the kingdom', 'Her first child', 'To marry him', 'Her ring'], 'correct': 1},
            {'after': 6, 'q': 'How did the queen learn the little man\'s name?', 'options': ['He told her himself', 'She read it in a book', 'A messenger heard him singing it in the forest', 'The king guessed it'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-de-02', 'tier': 'B1', 'title': 'Der Wolf und die sieben Geißlein', 'title_en': 'The Wolf and the Seven Young Goats',
        'origin': 'Brothers Grimm, Germany',
        'paras': [
            'Eine alte Geiß hatte sieben kleine Geißlein. Eines Tages wollte sie in den Wald gehen. Sie sagte: "Macht die Tür zu und öffnet sie nicht für den bösen Wolf!"',
            'Bald klopfte jemand an die Tür. "Macht auf, liebe Kinder, eure Mutter ist da", sagte eine raue Stimme. Aber die Geißlein erkannten die Stimme des Wolfs und machten die Tür nicht auf.',
            'Der Wolf ging zum Bäcker und aß Kreide, damit seine Stimme weich wurde. Dann klopfte er wieder an die Tür. Diesmal glaubten die Geißlein ihm und öffneten die Tür.',
            'Der Wolf sprang ins Haus und fraß sechs Geißlein. Nur das jüngste Geißlein versteckte sich in der Uhr und blieb sicher. Der Wolf war müde und satt und legte sich unter einem Baum schlafen.',
            'Die Mutter kam nach Hause und fand das Haus leer. Sie weinte laut, bis das jüngste Geißlein aus der Uhr kam und ihr alles erzählte. Zusammen gingen sie in den Wald und fanden den schlafenden Wolf.',
            'Die Mutter schnitt vorsichtig den Bauch des Wolfs auf, und alle sechs Geißlein sprangen lebendig heraus. Sie füllten den Bauch mit schweren Steinen und nähten ihn wieder zu.',
            'Als der Wolf aufwachte, wollte er zum Brunnen gehen und trinken. Die schweren Steine zogen ihn ins Wasser, und er ertrank. Die Geiß und ihre sieben Kinder tanzten vor Freude um den Brunnen.',
        ],
        'paras_en': [
            'An old goat had seven little kids. One day she wanted to go into the forest. She said, "Close the door and do not open it for the wicked wolf!"',
            'Soon someone knocked at the door. "Open up, dear children, your mother is here," said a rough voice. But the kids recognized the wolf\'s voice and did not open the door.',
            'The wolf went to the baker and ate chalk so that his voice became soft. Then he knocked at the door again. This time the kids believed him and opened the door.',
            'The wolf jumped into the house and ate six of the kids. Only the youngest kid hid in the clock and stayed safe. The wolf was tired and full and lay down to sleep under a tree.',
            'The mother came home and found the house empty. She cried loudly until the youngest kid came out of the clock and told her everything. Together they went into the forest and found the sleeping wolf.',
            'The mother carefully cut open the wolf\'s belly, and all six kids jumped out alive. They filled the belly with heavy stones and sewed it shut again.',
            'When the wolf woke up, he wanted to go to the well and drink. The heavy stones pulled him into the water, and he drowned. The goat and her seven children danced for joy around the well.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did the mother goat warn her children?', 'options': ['Because of the wicked wolf', 'Because of a storm', 'Because of hunters', 'Because of a fire'], 'correct': 0},
            {'after': 3, 'q': 'What did the wolf do to make his voice sound soft?', 'options': ['He drank warm milk', 'He ate chalk', 'He sang a song', 'He whispered'], 'correct': 1},
            {'after': 5, 'q': 'How did the mother goat save the six kids?', 'options': ['She scared the wolf away', 'She cut open his belly and freed them', 'She tricked him into the well', 'She called a hunter'], 'correct': 1},
            {'after': 6, 'q': 'How did the wolf die in the end?', 'options': ['He was shot by a hunter', 'He fell from a tree', 'The stones in his belly pulled him into the well', 'He ran away and never returned'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-de-03', 'tier': 'B2', 'title': 'Der Rattenfänger von Hameln', 'title_en': 'The Pied Piper of Hamelin',
        'origin': 'German legend, town of Hamelin',
        'paras': [
            'Im Jahr 1284 wurde die Stadt Hameln von einer schrecklichen Rattenplage geplagt. Überall liefen Ratten durch die Gassen, fraßen das Getreide und störten den Schlaf der Bürger. Die Bewohner wussten sich keinen Rat mehr.',
            'Da erschien ein fremder Mann in bunter Kleidung, der versprach, die Ratten zu vertreiben, wenn man ihm eine bestimmte Summe Geld zahlen würde. Der Bürgermeister nahm das Angebot erleichtert an, ohne lange zu verhandeln.',
            'Der Mann holte eine Pfeife hervor und begann zu spielen. Wie verzaubert kamen alle Ratten der Stadt aus ihren Löchern und folgten ihm bis zur Weser, wo sie ins Wasser gingen und ertranken. Die Stadt war endlich von der Plage befreit.',
            'Doch als der Rattenfänger sein Geld verlangte, weigerte sich der Bürgermeister zu zahlen. Er meinte, die Ratten seien ohnehin schon fast verschwunden gewesen, und die volle Summe sei nicht gerechtfertigt. Der Rattenfänger verließ die Stadt zornig, doch er kehrte bald zurück.',
            'Am nächsten Fest, während die Erwachsenen in der Kirche waren, spielte der Mann erneut auf seiner Pfeife. Diesmal folgten ihm nicht die Ratten, sondern alle Kinder der Stadt, wie von einer unsichtbaren Kraft angezogen.',
            'Der Rattenfänger führte die Kinder aus der Stadt hinaus und in einen nahen Berg hinein, der sich hinter ihnen wieder schloss. Nur zwei Kinder, ein Blindes und ein Lahmes, kamen nicht rechtzeitig nach und blieben zurück, um später von diesem Ereignis zu berichten.',
            'Seit jenem Tag durfte in Hameln durch jene Straße, durch die der Zug der Kinder gegangen war, keine Musik mehr gespielt werden. Die Geschichte wird bis heute erzählt, als Mahnung, ein gegebenes Versprechen zu halten.',
        ],
        'paras_en': [
            'In the year 1284, the town of Hamelin was plagued by a terrible infestation of rats. Rats ran everywhere through the alleys, ate the grain, and disturbed the citizens\' sleep. The residents no longer knew what to do.',
            'Then a stranger appeared, dressed in colorful clothing, who promised to drive away the rats if he were paid a certain sum of money. The mayor accepted the offer with relief, without negotiating for long.',
            'The man took out a pipe and began to play. As if enchanted, all the rats in the town came out of their holes and followed him to the Weser river, where they went into the water and drowned. The town was finally free of the plague.',
            'But when the piper demanded his money, the mayor refused to pay. He argued that the rats had almost disappeared anyway, and that the full sum was not justified. The piper left the town in fury, but he soon returned.',
            'At the next festival, while the adults were in church, the man played his pipe again. This time it was not the rats who followed him, but all the children of the town, as if drawn by an invisible force.',
            'The piper led the children out of the town and into a nearby mountain, which closed again behind them. Only two children, one blind and one lame, did not catch up in time and were left behind to later tell of this event.',
            'From that day on, no music was allowed to be played in Hamelin on the street through which the procession of children had passed. The story is still told today as a warning to keep a promise once given.',
        ],
        'questions': [
            {'after': 1, 'q': 'What problem did the town of Hamelin have?', 'options': ['A rat infestation', 'A drought', 'A plague of illness', 'A flood'], 'correct': 0},
            {'after': 3, 'q': 'Why did the mayor refuse to pay the piper?', 'options': ['He had no money left', 'He thought the full sum was not justified', 'He did not believe the piper had done the work', 'He wanted to pay him later'], 'correct': 1},
            {'after': 5, 'q': 'What happened to most of the children of Hamelin?', 'options': ['They were led into a mountain and vanished', 'They ran away to another town', 'They were rescued by the mayor', 'They fell asleep in the church'], 'correct': 0},
            {'after': 6, 'q': 'What rule remained in Hamelin after that day?', 'options': ['No rats were allowed inside the town', 'No music was allowed on the street the children took', 'No festivals were held again', 'No strangers were allowed into the town'], 'correct': 1},
        ],
    },
    {
        'id': 'fk-de-04', 'tier': 'B2', 'title': 'Till Eulenspiegel und das Brot', 'title_en': 'Till Eulenspiegel and the Bread',
        'origin': 'German folk humor, medieval trickster tales',
        'paras': [
            'Till Eulenspiegel war ein berühmter Schalk, der durch die Lande zog und überall seine Streiche spielte. Er nahm gerne Anweisungen wörtlich, um die Menschen, die ihn beschäftigten, zu ärgern oder bloßzustellen. So auch in der Stadt Braunschweig, wo er bei einem Bäcker Arbeit fand.',
            'Der Bäcker war ein grober Mann, der Till von Anfang an schlecht behandelte und ihn beschimpfte. Eines Abends sagte er zu Till: "Back mir heute Nacht Eulen und Meerkatzen, denn ich habe genug von deinen dummen Mienen." Er meinte damit nur, Till solle sich ärgern.',
            'Till aber nahm den Befehl wörtlich. Er formte den ganzen Teig zu kleinen Figuren von Eulen und Affen und backte sie über Nacht. Am nächsten Morgen fand der Bäcker seinen Laden voller seltsamer Gebäckfiguren, aber kein einziges normales Brot.',
            'Der Bäcker geriet in Wut und wollte Till dafür bestrafen, ihn den Lohn zu kürzen. Till erwiderte ruhig, er habe doch nur getan, was ihm befohlen worden sei, und niemand könne ihm einen Fehler vorwerfen.',
            'Da der Bäcker seine eigenen Worte nicht leugnen konnte, musste er die seltsamen Gebäckfiguren notgedrungen verkaufen. Zur Überraschung aller kamen die Bürger von Braunschweig neugierig herbei und kauften die Eulen und Affen aus Teig, weil sie so etwas noch nie gesehen hatten.',
            'Der Bäcker verdiente an diesem Tag mehr Geld als sonst, doch er war weiterhin verärgert über Tills Unverschämtheit. Er verlangte, dass Till in Zukunft nur noch gewöhnliches Brot backen solle, ohne jede Spielerei.',
            'Till aber blieb nicht lange, denn er wusste, dass sein nächster Streich woanders wartete. Er zog weiter von Stadt zu Stadt und hinterließ überall Geschichten von Bäckern, Handwerkern und Adligen, die seine wörtliche Auslegung ihrer eigenen Worte zu spüren bekamen.',
        ],
        'paras_en': [
            'Till Eulenspiegel was a famous prankster who traveled through the land playing tricks everywhere. He liked to take instructions literally in order to annoy or embarrass the people who employed him. So it was in the town of Braunschweig, where he found work with a baker.',
            'The baker was a rough man who treated Till badly from the start and insulted him. One evening he said to Till, "Bake me owls and monkeys tonight, because I have had enough of your stupid faces." He only meant it to annoy Till.',
            'But Till took the order literally. He shaped all the dough into little figures of owls and monkeys and baked them overnight. The next morning the baker found his shop full of strange pastry figures, but not a single normal loaf of bread.',
            'The baker flew into a rage and wanted to punish Till for it by cutting his pay. Till calmly replied that he had only done what he had been ordered to do, and that no one could accuse him of a mistake.',
            'Since the baker could not deny his own words, he was forced to sell the strange pastry figures. To everyone\'s surprise, the citizens of Braunschweig came by curiously and bought the dough owls and monkeys, because they had never seen anything like it before.',
            'The baker earned more money that day than usual, but he remained annoyed at Till\'s cheekiness. He demanded that in the future Till should only bake ordinary bread, without any tricks.',
            'But Till did not stay long, for he knew his next prank was waiting elsewhere. He traveled on from town to town, leaving behind everywhere stories of bakers, craftsmen, and nobles who felt the effect of his literal interpretation of their own words.',
        ],
        'questions': [
            {'after': 1, 'q': 'What was Till Eulenspiegel known for?', 'options': ['Taking instructions literally to play tricks', 'Baking the best bread in Germany', 'Telling fortunes to travelers', 'Fighting in tournaments'], 'correct': 0},
            {'after': 3, 'q': 'What did Till bake instead of bread?', 'options': ['Nothing at all', 'Figures of owls and monkeys', 'Loaves shaped like animals of the farm', 'Burnt, inedible dough'], 'correct': 1},
            {'after': 5, 'q': 'How did the citizens of Braunschweig react to the strange pastries?', 'options': ['They refused to buy them', 'They complained to the mayor', 'They bought them out of curiosity', 'They demanded a refund'], 'correct': 2},
            {'after': 6, 'q': 'What did Till do after leaving the baker?', 'options': ['He settled permanently in Braunschweig', 'He apologized and stopped playing tricks', 'He traveled on, playing tricks in other towns', 'He became a baker himself'], 'correct': 2},
        ],
    },
    {
        'id': 'fk-de-05', 'tier': 'C1', 'title': 'Die Loreley', 'title_en': 'The Loreley',
        'origin': 'Rhineland legend, popularized by Clemens Brentano and Heinrich Heine',
        'paras': [
            'Am Rhein, dort wo der Fluss sich zwischen steilen Felsen besonders eng windet, erhebt sich ein hoher Felsen, der noch heute Loreley genannt wird. Schiffer fürchteten diese Stelle seit jeher, denn die Strömung ist dort tückisch, und so mancher Kahn ist an den verborgenen Riffen zerschellt.',
            'Der Sage nach lebte einst auf diesem Felsen eine wunderschöne Jungfrau mit goldenem Haar, die man Loreley nannte. In der Abenddämmerung saß sie oben auf dem Fels, kämmte ihr langes Haar und sang mit einer Stimme, die jeden, der sie hörte, wie verzaubert erscheinen ließ.',
            'Die Schiffer, die auf dem Rhein vorbeifuhren, konnten ihrem Gesang nicht widerstehen. Sie wandten den Blick nach oben, um die schöne Sängerin zu erblicken, und vergaßen dabei völlig, auf die gefährlichen Klippen vor ihnen zu achten.',
            'So mancher Kahn geriet dadurch ins Trudeln, prallte gegen die Felsen und versank in den Fluten, während der Steuermann wie gebannt zur Loreley emporstarrte. Man erzählte sich, dass die Jungfrau selbst nicht bösartig sei, sondern nur ihrem eigenen Schmerz Ausdruck verleihe, den ihr ein untreuer Geliebter einst zugefügt hatte.',
            'In einer Version der Sage befiehlt ein Pfalzgraf, dem die vielen Unglücke zu Ohren gekommen sind, die Jungfrau festzunehmen und vor Gericht zu bringen. Man will herausfinden, ob sie tatsächlich eine Zauberin sei, die absichtlich Schiffer ins Verderben lockt.',
            'Doch auf dem Weg zur Burg bittet die Loreley darum, noch ein letztes Mal auf den Felsen steigen zu dürfen, um den Rhein zu betrachten. Als sie oben angekommen ist, erblickt sie in der Ferne ein Boot, in dem sie ihren verlorenen Geliebten zu erkennen glaubt, und stürzt sich voller Sehnsucht in die Fluten.',
            'Seither, so heißt es, hört man an klaren Abenden manchmal noch ihre Stimme über dem Wasser, und der Felsen trägt bis heute ihren Namen. Heinrich Heines berühmtes Gedicht hat diese Sage im 19. Jahrhundert weit über die Grenzen des Rheinlandes hinaus bekannt gemacht.',
        ],
        'paras_en': [
            'On the Rhine, where the river winds especially narrowly between steep cliffs, there rises a tall rock that is still called the Loreley today. Boatmen have always feared this spot, for the current there is treacherous, and many a boat has been wrecked on the hidden reefs.',
            'According to legend, a beautiful maiden with golden hair once lived on this rock, whom people called Loreley. At dusk she sat atop the rock, combed her long hair, and sang with a voice that made anyone who heard it seem enchanted.',
            'The boatmen passing by on the Rhine could not resist her singing. They turned their gaze upward to catch sight of the beautiful singer, and in doing so completely forgot to watch the dangerous cliffs ahead of them.',
            'Many a boat thereby went into a spin, crashed against the rocks, and sank into the floods, while the helmsman stared up at the Loreley as if spellbound. It was said that the maiden herself was not malicious, but merely giving expression to her own pain, once inflicted on her by an unfaithful lover.',
            'In one version of the legend, a count palatine, who had heard of the many misfortunes, orders the maiden to be arrested and brought before a court. They want to find out whether she is in fact a sorceress who deliberately lures boatmen to their doom.',
            'But on the way to the castle, the Loreley asks to be allowed to climb the rock one last time to look at the Rhine. Once she has reached the top, she sees a boat in the distance in which she believes she recognizes her lost lover, and throws herself into the floods, full of longing.',
            'Since then, it is said, one can still sometimes hear her voice over the water on clear evenings, and the rock still bears her name today. Heinrich Heine\'s famous poem made this legend widely known far beyond the borders of the Rhineland in the 19th century.',
        ],
        'questions': [
            {'after': 1, 'q': 'Why did boatmen fear the Loreley rock?', 'options': ['Because of pirates hiding there', 'Because the current is treacherous and many boats wrecked there', 'Because it was said to be cursed by a king', 'Because it blocked the only path down the Rhine'], 'correct': 1},
            {'after': 3, 'q': 'Why did so many boats crash near the rock, according to the legend?', 'options': ['A storm always struck at dusk', 'The boatmen were distracted by the maiden\'s singing', 'The river was too narrow for large boats', 'The rock itself moved into the water'], 'correct': 1},
            {'after': 5, 'q': 'What did the Loreley do when she reached the top of the rock for the last time?', 'options': ['She sang one final song and disappeared into the forest', 'She saw her lost lover\'s boat and threw herself into the river', 'She was rescued by the count palatine\'s soldiers', 'She turned into a bird and flew away'], 'correct': 1},
            {'after': 6, 'q': 'Who made the Loreley legend famous far beyond the Rhineland?', 'options': ['Heinrich Heine, with his famous poem', 'A medieval chronicler', 'The Brothers Grimm', 'A local fisherman'], 'correct': 0},
        ],
    },
    {
        'id': 'fk-de-06', 'tier': 'C2', 'title': 'Barbarossa im Kyffhäuser', 'title_en': 'Barbarossa in the Kyffhäuser',
        'origin': 'German legend surrounding Emperor Frederick I Barbarossa',
        'paras': [
            'Tief im Innern des Kyffhäuserberges, so will es die Überlieferung, ruht Kaiser Friedrich Barbarossa seit Jahrhunderten in einem verborgenen, von Fackeln erleuchteten Saal, umgeben von den steinernen Zeugnissen seiner einstigen Herrschaft. Er sitzt an einem runden Tisch, den Kopf in die Hand gestützt, und sein rötlicher Bart, dem er seinen Beinamen verdankt, ist im Laufe der langen Jahre so sehr gewachsen, dass er sich mehrfach um die Tischplatte gewunden hat.',
            'Der Legende zufolge fiel der Kaiser nicht im Kampf, wie manche Chronisten behaupteten, sondern wurde von übernatürlichen Mächten in den Berg entrückt, um dort in einem Zustand zwischen Schlaf und Wachsein die Wiederkehr einer glorreichen, geeinten deutschen Zukunft abzuwarten. Diese Vorstellung eines schlafenden, doch keineswegs endgültig verlorenen Herrschers verlieh dem Mythos seine eigentümliche, tröstliche Zählebigkeit.',
            'Hirten und Wanderer, die sich zuweilen in die Nähe des Berges wagten, berichteten von seltsamen Erscheinungen: einem Raben, der unablässig um die Bergkuppe kreiste, und einem Zwerg, der gelegentlich hervortrat, um vorwitzige Besucher mit rätselhaften Prophezeiungen zu verunsichern und sie sogleich wieder fortzuschicken.',
            'Einer weitverbreiteten Erzählung nach soll einst ein Schäfer bis in den innersten Saal vorgedrungen sein. Der Kaiser habe ihn gefragt, ob die Raben noch immer um den Berg flögen; als der Schäfer dies bejahte, habe Barbarossa mit schwerer, resignierter Stimme geseufzt, er müsse demnach noch weitere hundert Jahre schlafen, ehe seine Zeit gekommen sei.',
            'Im Lauf der Jahrhunderte verschmolz die ursprüngliche Sage zusehends mit der Gestalt seines Enkels, Kaiser Friedrich II., dessen Herrschaft in der kollektiven Erinnerung ähnlich glanzvoll nachwirkte, sodass sich die Grenze zwischen historischer Person und mythischer Verklärung zunehmend verwischte und beide Kaiser in der Volksphantasie miteinander verschmolzen.',
            'Im neunzehnten Jahrhundert, als sich die deutschsprachigen Länder nach politischer Einheit sehnten, erfuhr der Barbarossa-Mythos eine bemerkenswerte Renaissance: Dichter griffen ihn auf, um dem Wunsch nach einem starken, einigenden Reich literarischen Ausdruck zu verleihen, und auf dem Kyffhäuser selbst wurde schließlich ein monumentales Denkmal errichtet, das den schlafenden Kaiser dauerhaft ins kollektive Gedächtnis einschrieb.',
            'Ob man den Mythos nun als reines Märchen betrachtet oder als Sinnbild eines tief verwurzelten Bedürfnisses nach nationaler Erlösung deutet, seine Wirkungsmacht ist unbestreitbar: Noch heute pilgern Besucher zum Kyffhäuser, gewissermaßen auf der Suche nach jenem schlafenden Kaiser, dessen Erwachen, so will es die Erzählung, dereinst eine neue, bessere Epoche einläuten soll.',
        ],
        'paras_en': [
            'Deep within the Kyffhäuser mountain, so tradition has it, Emperor Frederick Barbarossa has rested for centuries in a hidden, torch-lit hall, surrounded by the stone remnants of his former rule. He sits at a round table, his head resting on his hand, and his reddish beard, from which he gets his nickname, has grown so much over the long years that it has wound itself several times around the tabletop.',
            'According to the legend, the emperor did not fall in battle, as some chroniclers claimed, but was carried off by supernatural powers into the mountain, to await there, in a state between sleep and wakefulness, the return of a glorious, united German future. This notion of a sleeping but by no means finally lost ruler gave the myth its peculiar, comforting durability.',
            'Shepherds and wanderers who occasionally ventured near the mountain reported strange occurrences: a raven that circled endlessly around the summit, and a dwarf who sometimes stepped forward to unsettle overly curious visitors with cryptic prophecies before promptly sending them away again.',
            'According to a widespread tale, a shepherd is said to have once made his way into the innermost hall. The emperor reportedly asked him whether the ravens still still flew around the mountain; when the shepherd confirmed this, Barbarossa is said to have sighed, in a heavy, resigned voice, that he must therefore sleep for another hundred years before his time had come.',
            'Over the course of the centuries, the original legend increasingly merged with the figure of his grandson, Emperor Frederick II, whose reign lived on with a similarly splendid afterglow in collective memory, so that the boundary between historical person and mythic transfiguration grew ever more blurred, and the two emperors fused together in the popular imagination.',
            'In the nineteenth century, as the German-speaking lands longed for political unity, the Barbarossa myth experienced a remarkable renaissance: poets took it up to give literary expression to the desire for a strong, unifying empire, and on the Kyffhäuser itself a monumental memorial was eventually erected, permanently inscribing the sleeping emperor into collective memory.',
            'Whether one regards the myth as pure fairy tale or interprets it as a symbol of a deeply rooted longing for national redemption, its power is undeniable: even today visitors make pilgrimages to the Kyffhäuser, in a sense searching for that sleeping emperor whose awakening, so the tale would have it, is one day meant to usher in a new, better age.',
        ],
        'questions': [
            {'after': 1, 'q': 'What is said to have happened to Barbarossa instead of dying in battle?', 'options': ['He was carried into the mountain by supernatural powers to await a future return', 'He retired quietly to a monastery', 'He was betrayed and imprisoned by his own son', 'He sailed away and was never seen again'], 'correct': 0},
            {'after': 3, 'q': 'What did Barbarossa reportedly say when the shepherd confirmed the ravens still circled the mountain?', 'options': ['That he would awaken immediately', 'That he must sleep another hundred years before his time had come', 'That the ravens should be killed', 'That the shepherd should never return'], 'correct': 1},
            {'after': 5, 'q': 'How did the Barbarossa myth change in the nineteenth century?', 'options': ['It was forgotten entirely', 'It was dismissed as false by historians', 'It saw a renaissance tied to the longing for German political unity', 'It became associated with a different, unrelated legend'], 'correct': 2},
            {'after': 6, 'q': 'What do visitors to the Kyffhäuser today symbolically seek, according to the passage?', 'options': ['Buried treasure said to be hidden in the mountain', 'The sleeping emperor whose awakening would usher in a better age', 'A cure for illness at a sacred spring', 'The grave of the raven from the legend'], 'correct': 1},
        ],
    },
]
