# -*- coding: utf-8 -*-
# C2 skill layer — native-speed lines (build + listening), spoken-register nuance drills, banter & debate dialogues
TIER = 'C2'
TOPICS = {
    'build-native-lines': 'Native-Speed Lines',
    'nuance-spoken-register': 'Nuance: Street vs. Formal',
    'nuance-tone-shades': 'Nuance: Shades of Tone',
    'talk-banter': 'Banter with Friends',
    'talk-heated-debate': 'Heated Debate',
    'listen-c2-lines': 'Listening: Native Speed',
    'listen-c2-words': 'Listening: Rare Vocabulary',
}

SENTENCES = [
    {"id": "c2-s01", "topic": "build-native-lines", "en": "Honestly, I’d have thought twice before signing anything like that.",
     "note": "A conditional-perfect regret with a hedge (honestly) — the rhythm of real spoken advice.",
     "es": ["Sinceramente,", "me lo habría pensado", "dos veces", "antes de firmar", "algo así"],
     "fr": ["Franchement,", "j’y aurais réfléchi", "à deux fois", "avant de signer", "un truc pareil"],
     "it": ["Sinceramente,", "ci avrei pensato", "due volte", "prima di firmare", "una cosa del genere"],
     "pt": ["Sinceramente,", "eu teria pensado", "duas vezes", "antes de assinar", "algo assim"],
     "ja": ["{正直|しょうじき}、", "あんなものに", "サインする{前|まえ}に", "{二度|にど}は", "{考|かんが}えたと{思|おも}う"],
     "zh": ["说实话，", "签那种东西之前", "我会", "再三", "考虑的"]},
    {"id": "c2-s02", "topic": "build-native-lines", "en": "It’s not that I don’t care — it’s that I’ve got nothing left to give.",
     "note": "Contrastive “it’s not that… it’s that…” — the structure of a real emotional clarification.",
     "es": ["No es que", "no me importe,", "es que", "ya no me queda", "nada que dar"],
     "fr": ["C’est pas que", "je m’en fiche,", "c’est que", "je n’ai plus rien", "à donner"],
     "it": ["Non è che", "non mi importi,", "è che", "non mi è rimasto", "niente da dare"],
     "pt": ["Não é que", "eu não me importe,", "é que", "não me sobrou", "nada para dar"],
     "ja": ["どうでもいい", "わけじゃなくて、", "もう{何|なに}も", "{残|のこ}ってないだけ", "なんだ"],
     "zh": ["不是", "我不在乎，", "而是", "我已经", "没什么可给的了"]},
    {"id": "c2-s03", "topic": "build-native-lines", "en": "Whatever you do, don’t let him talk you into it.",
     "note": "Emphatic warning: “whatever you do” + a phrasal verb of persuasion.",
     "es": ["Hagas lo que hagas,", "no dejes", "que te convenza", "de hacerlo"],
     "fr": ["Quoi que tu fasses,", "ne le laisse pas", "te convaincre", "de le faire"],
     "it": ["Qualunque cosa tu faccia,", "non lasciare", "che ti convinca", "a farlo"],
     "pt": ["Faça o que fizer,", "não deixe", "que ele te convença", "a fazer isso"],
     "ja": ["{何|なに}があっても、", "{彼|かれ}に", "{丸|まる}め{込|こ}まれ", "ないでね"],
     "zh": ["不管怎样，", "别让他", "把你", "说服了"]},
    {"id": "c2-s04", "topic": "build-native-lines", "en": "Had I known it would drag on this long, I’d never have agreed.",
     "note": "Inverted conditional (“had I known”) — formal in writing, fast and natural in speech.",
     "es": ["De haber sabido", "que se alargaría tanto,", "nunca habría", "aceptado"],
     "fr": ["Si j’avais su", "que ça traînerait autant,", "je n’aurais jamais", "accepté"],
     "it": ["Se avessi saputo", "che sarebbe andata per le lunghe,", "non avrei mai", "accettato"],
     "pt": ["Se eu soubesse", "que ia se arrastar tanto,", "nunca teria", "aceitado"],
     "ja": ["こんなに", "{長引|ながび}くと", "{知|し}っていたら、", "{絶対|ぜったい}に{引|ひ}き{受|う}けなかった"],
     "zh": ["早知道", "会拖这么久，", "我绝对", "不会答应"]},
    {"id": "c2-s05", "topic": "build-native-lines", "en": "She brushed it off, but you could tell it had gotten to her.",
     "note": "Two idioms in one breath: brush off (dismiss) and get to someone (affect).",
     "es": ["Le quitó importancia,", "pero se notaba", "que le había", "afectado"],
     "fr": ["Elle a fait comme si de rien n’était,", "mais on voyait bien", "que ça l’avait", "touchée"],
     "it": ["Ha fatto finta di niente,", "ma si vedeva", "che l’aveva", "colpita"],
     "pt": ["Ela fingiu que não era nada,", "mas dava para ver", "que tinha", "mexido com ela"],
     "ja": ["{彼女|かのじょ}は", "{軽|かる}く{流|なが}したけど、", "{効|こ}いていたのは", "{見|み}え{見|み}えだった"],
     "zh": ["她装作", "不在意，", "但看得出", "她心里受了影响"]},
    {"id": "c2-s06", "topic": "build-native-lines", "en": "Say what you like about him, but he gets things done.",
     "note": "A concessive opener (“say what you like”) followed by grudging praise.",
     "es": ["Di lo que quieras", "de él,", "pero", "consigue que las cosas", "se hagan"],
     "fr": ["Dis ce que tu veux", "sur lui,", "mais", "il fait avancer", "les choses"],
     "it": ["Di’ quello che vuoi", "di lui,", "ma", "le cose", "le fa"],
     "pt": ["Diga o que quiser", "dele,", "mas", "ele faz", "as coisas acontecerem"],
     "ja": ["{彼|かれ}のことを", "どう{言|い}おうと、", "やることは", "ちゃんと", "やる{人|ひと}だ"],
     "zh": ["随你怎么", "说他，", "但他", "确实", "能把事办成"]},
    {"id": "c2-s07", "topic": "build-native-lines", "en": "I’m not about to apologise for something I didn’t even do.",
     "note": "“Not about to” = firm refusal; “didn’t even” adds indignation.",
     "es": ["No pienso", "disculparme", "por algo", "que ni siquiera", "hice"],
     "fr": ["Je ne vais pas", "m’excuser", "pour un truc", "que je n’ai même pas", "fait"],
     "it": ["Non ho intenzione", "di scusarmi", "per una cosa", "che non ho nemmeno", "fatto"],
     "pt": ["Não vou", "pedir desculpa", "por algo", "que eu nem", "fiz"],
     "ja": ["やってもいない", "ことで", "{謝|あやま}る", "つもりは", "ない"],
     "zh": ["我才不会", "为一件", "我根本没做的事", "道歉", "呢"]},
    {"id": "c2-s08", "topic": "build-native-lines", "en": "By the time they got round to fixing it, the damage was done.",
     "note": "“Get round to” (finally do) with a past-perfect time frame.",
     "es": ["Para cuando", "por fin se pusieron", "a arreglarlo,", "el daño", "ya estaba hecho"],
     "fr": ["Le temps qu’ils", "se décident", "à le réparer,", "le mal", "était fait"],
     "it": ["Quando finalmente", "si sono decisi", "a ripararlo,", "il danno", "era ormai fatto"],
     "pt": ["Quando finalmente", "resolveram", "consertar,", "o estrago", "já estava feito"],
     "ja": ["やっと", "{直|なお}す{気|き}になった", "{頃|ころ}には、", "もう{手遅|ておく}れ", "だった"],
     "zh": ["等他们", "终于想起", "去修的时候，", "损失", "已经造成了"]},
    {"id": "c2-s09", "topic": "build-native-lines", "en": "Between you and me, I don’t think the deal is going to go through.",
     "note": "Confidential framing (“between you and me”) + phrasal verb “go through” (be finalised).",
     "es": ["Entre tú y yo,", "no creo", "que el acuerdo", "vaya a", "salir adelante"],
     "fr": ["Entre nous,", "je ne pense pas", "que l’accord", "va", "se faire"],
     "it": ["Detto tra noi,", "non credo", "che l’accordo", "andrà", "in porto"],
     "pt": ["Cá entre nós,", "não acho", "que o acordo", "vá", "sair"],
     "ja": ["ここだけの{話|はなし}、", "あの{取引|とりひき}は", "まとまらないと", "{思|おも}う", "よ"],
     "zh": ["咱们私下说，", "我觉得", "这笔交易", "谈不", "成"]},
    {"id": "c2-s10", "topic": "build-native-lines", "en": "You’d think they’d have learned by now, wouldn’t you?",
     "note": "Sarcastic “you’d think…” with a tag question — pure native rhythm.",
     "es": ["Uno pensaría", "que a estas alturas", "ya habrían", "aprendido,", "¿no?"],
     "fr": ["On pourrait croire", "qu’ils auraient", "compris", "depuis le temps,", "non ?"],
     "it": ["Uno penserebbe", "che ormai", "avessero", "imparato,", "no?"],
     "pt": ["Você pensaria", "que a essa altura", "eles já teriam", "aprendido,", "né?"],
     "ja": ["いい{加減|かげん}", "{学|まな}んでても", "よさそうな", "ものだけど", "ね"],
     "zh": ["你以为", "他们到现在", "该学乖了", "吧，", "对不对？"]},
    {"id": "c2-s11", "topic": "build-native-lines", "en": "No sooner had we sat down than the fire alarm went off.",
     "note": "Literary inversion “no sooner… than” — you’ll hear it in narration and read it in novels.",
     "es": ["Apenas", "nos habíamos sentado", "cuando", "saltó", "la alarma de incendios"],
     "fr": ["À peine", "étions-nous assis", "que", "l’alarme incendie", "s’est déclenchée"],
     "it": ["Ci eravamo appena", "seduti", "quando", "è scattato", "l’allarme antincendio"],
     "pt": ["Mal", "tínhamos nos sentado", "quando", "o alarme de incêndio", "disparou"],
     "ja": ["{座|すわ}った", "{途端|とたん}に", "{火災報知器|かさいほうちき}が", "{鳴|な}り{出|だ}した", "んだ"],
     "zh": ["我们刚", "坐下，", "火警", "就", "响了"]},
    {"id": "c2-s12", "topic": "build-native-lines", "en": "If it’s all the same to you, I’d rather we kept this off the record.",
     "note": "Polite-but-firm request: “if it’s all the same to you” + “I’d rather we + past”.",
     "es": ["Si te da igual,", "preferiría", "que esto", "quedara", "extraoficial"],
     "fr": ["Si ça ne te dérange pas,", "je préférerais", "que ça reste", "entre nous", "(officieux)"],
     "it": ["Se per te è lo stesso,", "preferirei", "che questo", "restasse", "ufficioso"],
     "pt": ["Se para você tanto faz,", "eu preferiria", "que isso", "ficasse", "em off"],
     "ja": ["{差|さ}し{支|つか}えなければ、", "これは", "オフレコに", "して", "おきたい"],
     "zh": ["如果你不介意，", "我希望", "这件事", "不要", "公开记录"]},
]

NUANCE = [
    # ---- street vs formal (2 per language) ----
    {"id": "n-es5", "lang": "es", "topic": "nuance-spoken-register", "context": "Telling a close friend you loved a concert (casual Spain/LatAm register)",
     "correct": "Estuvo brutal", "options": ["Estuvo brutal", "Fue sumamente satisfactorio", "Resultó adecuado", "Me pareció correcto"],
     "note": "Brutal/genial/una pasada are the street words for “amazing”; the other options sound like a review form."},
    {"id": "n-es6", "lang": "es", "topic": "nuance-spoken-register", "context": "Writing to a government office to ask for a document",
     "correct": "Les agradecería que me remitieran", "options": ["Les agradecería que me remitieran", "Pásenme", "Mándenme ya", "A ver si me lo mandan"],
     "note": "Official Spanish stacks courtesy: agradecería + subjunctive + remitir. The others are spoken and pushy."},
    {"id": "n-fr5", "lang": "fr", "topic": "nuance-spoken-register", "context": "A friend asks how your exam went — it went badly (casual)",
     "correct": "J’ai foiré", "options": ["J’ai foiré", "J’ai échoué lamentablement", "Cela s’est mal déroulé", "Le résultat fut décevant"],
     "note": "Foirer / se planter are the everyday words; “cela s’est mal déroulé” is report language."},
    {"id": "n-fr6", "lang": "fr", "topic": "nuance-spoken-register", "context": "Ending a formal email to a professor",
     "correct": "Je vous prie d’agréer l’expression de mes salutations distinguées", "options": ["Je vous prie d’agréer l’expression de mes salutations distinguées", "À plus", "Bisous", "Ciao"],
     "note": "French formal sign-offs are famously long; anything shorter with a professor reads as careless."},
    {"id": "n-it5", "lang": "it", "topic": "nuance-spoken-register", "context": "Telling friends the party was great (casual)",
     "correct": "È stata una figata", "options": ["È stata una figata", "È stata assai gradevole", "Fu un evento riuscito", "Risultò soddisfacente"],
     "note": "Figata / spettacolo / da paura are the spoken superlatives; assai gradevole is what a critic writes."},
    {"id": "n-it6", "lang": "it", "topic": "nuance-spoken-register", "context": "Asking a bank formally to confirm a transfer",
     "correct": "Vi sarei grato se poteste confermare", "options": ["Vi sarei grato se poteste confermare", "Confermatemi", "Ditemi se è arrivato", "Fatemi sapere, dai"],
     "note": "Vi sarei grato + se poteste is the standard formal request frame; the rest are chat register."},
    {"id": "n-pt5", "lang": "pt", "topic": "nuance-spoken-register", "context": "Telling a friend something was really cool (Brazil, casual)",
     "correct": "Foi massa demais", "options": ["Foi massa demais", "Foi deveras agradável", "Foi apropriado", "Mostrou-se satisfatório"],
     "note": "Massa / top / maneiro are spoken Brazilian praise; deveras agradável sounds like a 19th-century novel."},
    {"id": "n-pt6", "lang": "pt", "topic": "nuance-spoken-register", "context": "Opening a formal letter to a company",
     "correct": "Prezados senhores", "options": ["Prezados senhores", "E aí, galera", "Oi, gente", "Fala, pessoal"],
     "note": "Prezados / Excelentíssimo are formal openers; the others are how you greet friends."},
    {"id": "n-ja5", "lang": "ja", "topic": "nuance-spoken-register", "context": "Telling a close friend a film was amazing (casual)",
     "correct": "めっちゃよかった", "options": ["めっちゃよかった", "{大変|たいへん}{素晴|すば}らしゅうございました", "{非常|ひじょう}に{良好|りょうこう}でした", "{好評|こうひょう}を{博|はく}しました"],
     "note": "めっちゃ / やばい / 最高 are the spoken intensifiers; the others are honorific or written-report style."},
    {"id": "n-ja6", "lang": "ja", "topic": "nuance-spoken-register", "context": "Asking a client company to send a document (business keigo)",
     "correct": "お{送|おく}りいただけますでしょうか", "options": ["お{送|おく}りいただけますでしょうか", "{送|おく}って", "{送|おく}ってくれる？", "{送|おく}れ"],
     "note": "お〜いただけますでしょうか is the softest business request; 送って is friends-only, 送れ is an order."},
    {"id": "n-zh5", "lang": "zh", "topic": "nuance-spoken-register", "context": "Telling a friend the food was incredible (casual)",
     "correct": "好吃到爆", "options": ["好吃到爆", "味道颇为可口", "口感尚属良好", "堪称佳肴"],
     "note": "到爆 / 绝了 / 太棒了 are spoken superlatives; 颇为 / 尚属 / 堪称 are written-register hedges."},
    {"id": "n-zh6", "lang": "zh", "topic": "nuance-spoken-register", "context": "Writing a formal request to a university office",
     "correct": "烦请贵处协助办理", "options": ["烦请贵处协助办理", "你们帮我弄一下", "赶紧给我办了", "搞定它吧"],
     "note": "烦请 / 贵处 / 协助办理 are formal-letter set phrases; the other three are how you’d text a roommate."},
    # ---- shades of tone (2 per language) ----
    {"id": "n-es7", "lang": "es", "topic": "nuance-tone-shades", "context": "Gently telling a colleague their idea has a flaw (softened, not blunt)",
     "correct": "Igual habría que darle una vuelta", "options": ["Igual habría que darle una vuelta", "Eso no funciona", "Está mal", "Es una tontería"],
     "note": "Igual + conditional + darle una vuelta softens criticism; the others are blunt to rude."},
    {"id": "n-es8", "lang": "es", "topic": "nuance-tone-shades", "context": "Sarcastically reacting to yet another delay",
     "correct": "Qué novedad", "options": ["Qué novedad", "Qué sorpresa tan agradable", "Muchas gracias", "Qué bien, me alegro"],
     "note": "Qué novedad (“what a surprise”) is the standard sarcastic groan; the others could be sincere."},
    {"id": "n-fr7", "lang": "fr", "topic": "nuance-tone-shades", "context": "Softly disagreeing with your boss in a meeting",
     "correct": "Je ne suis pas sûr que ce soit la meilleure option", "options": ["Je ne suis pas sûr que ce soit la meilleure option", "C’est nul", "Vous avez tort", "N’importe quoi"],
     "note": "Je ne suis pas sûr que + subjunctive is the diplomatic disagreement; the others end careers."},
    {"id": "n-fr8", "lang": "fr", "topic": "nuance-tone-shades", "context": "Ironically praising a friend who arrives an hour late",
     "correct": "Ah bah enfin, on n’attendait plus que toi", "options": ["Ah bah enfin, on n’attendait plus que toi", "Merci d’être venu si tôt", "Tu es très ponctuel", "Content de te voir"],
     "note": "“Enfin, on n’attendait plus que toi” is the classic sarcastic welcome; the others read as literal."},
    {"id": "n-it7", "lang": "it", "topic": "nuance-tone-shades", "context": "Declining an invitation without offending",
     "correct": "Mi piacerebbe tanto, ma proprio non ce la faccio", "options": ["Mi piacerebbe tanto, ma proprio non ce la faccio", "No", "Non mi va", "Non ho voglia"],
     "note": "Mi piacerebbe + ma + non ce la faccio is the warm refusal; non mi va / non ho voglia sound dismissive."},
    {"id": "n-it8", "lang": "it", "topic": "nuance-tone-shades", "context": "Teasing a friend who is always late (affectionate sarcasm)",
     "correct": "Eh, la puntualità non è il tuo forte", "options": ["Eh, la puntualità non è il tuo forte", "Sei sempre in ritardo e basta", "Non mi fido di te", "Sei irresponsabile"],
     "note": "“Non è il tuo forte” (not your strong point) is playful understatement; the others are real complaints."},
    {"id": "n-pt7", "lang": "pt", "topic": "nuance-tone-shades", "context": "Softly correcting a stranger’s mistake (Brazil)",
     "correct": "Acho que talvez seja o contrário", "options": ["Acho que talvez seja o contrário", "Você está errado", "Isso é mentira", "Não é assim"],
     "note": "Acho que + talvez + subjunctive triple-cushions the correction; the others are confrontational."},
    {"id": "n-pt8", "lang": "pt", "topic": "nuance-tone-shades", "context": "Sarcastically reacting to bad news you saw coming",
     "correct": "Quem diria", "options": ["Quem diria", "Que pena", "Sinto muito", "Que surpresa boa"],
     "note": "Quem diria (“who would have thought”) said flat is pure sarcasm; que pena / sinto muito are sincere."},
    {"id": "n-ja7", "lang": "ja", "topic": "nuance-tone-shades", "context": "Declining a request from a coworker without saying no",
     "correct": "ちょっと{難|むずか}しいかもしれません", "options": ["ちょっと{難|むずか}しいかもしれません", "{無理|むり}です", "できません", "やりたくないです"],
     "note": "ちょっと難しい is the Japanese no; 無理です / できません are blunt, やりたくない is childish."},
    {"id": "n-ja8", "lang": "ja", "topic": "nuance-tone-shades", "context": "A friend brags about a tiny achievement — you tease them",
     "correct": "はいはい、すごいすごい", "options": ["はいはい、すごいすごい", "{本当|ほんとう}に{素晴|すば}らしいですね", "{尊敬|そんけい}します", "おめでとうございます"],
     "note": "Doubling はいはい / すごいすごい signals playful sarcasm; the others are sincere and formal."},
    {"id": "n-zh7", "lang": "zh", "topic": "nuance-tone-shades", "context": "Politely pushing back on a client’s request",
     "correct": "这个恐怕不太好办", "options": ["这个恐怕不太好办", "不行", "办不了", "别想了"],
     "note": "恐怕 + 不太 softens the refusal; 不行 / 办不了 are flat, 别想了 is rude."},
    {"id": "n-zh8", "lang": "zh", "topic": "nuance-tone-shades", "context": "Sarcastic reply when a friend says they’ll “definitely” pay you back tomorrow",
     "correct": "行行行，我信你个鬼", "options": ["行行行，我信你个鬼", "太好了，谢谢", "我相信你", "没问题"],
     "note": "我信你个鬼 (“I believe your ghost”) is pure internet-era sarcasm; the others are sincere."},
]

DIALOGUES = [
    {"id": "d-c2-01", "topic": "talk-banter", "setup": "A friend mocks your terrible parking.",
     "note": "Banter means giving as good as you get — a quick comeback, not an apology.",
     "es": ["Menudo aparcamiento, ¿te has sacado el carnet en una tómbola?", "Al menos yo tengo coche, tú vienes en patinete.", "Lo siento mucho, no volverá a pasar.", "El coche es azul.", "Hoy hace mucho calor."],
     "fr": ["Sacré créneau, tu as eu ton permis dans une pochette-surprise ?", "Au moins j’ai une voiture, toi tu viens en trottinette.", "Je suis désolé, ça n’arrivera plus.", "La voiture est bleue.", "Il fait très chaud aujourd’hui."],
     "it": ["Bel parcheggio, la patente l’hai vinta alla lotteria?", "Almeno io ho la macchina, tu vieni in monopattino.", "Mi dispiace tanto, non succederà più.", "La macchina è blu.", "Oggi fa molto caldo."],
     "pt": ["Que estacionada, você tirou a carteira numa rifa?", "Pelo menos eu tenho carro, você vem de patinete.", "Desculpa, não vai acontecer de novo.", "O carro é azul.", "Hoje está muito calor."],
     "ja": ["すごい{駐車|ちゅうしゃ}だね、{免許|めんきょ}は{福引|ふくび}きで{当|あ}てたの？", "{少|すく}なくとも{車|くるま}はあるよ、{君|きみ}はキックボードでしょ。", "{本当|ほんとう}にすみません、{二度|にど}としません。", "{車|くるま}は{青|あお}です。", "{今日|きょう}はとても{暑|あつ}いです。"],
     "zh": ["停得真绝，你驾照是抽奖抽来的吧？", "至少我有车，你还骑滑板车呢。", "非常抱歉，下次不会了。", "这辆车是蓝色的。", "今天很热。"]},
    {"id": "d-c2-02", "topic": "talk-banter", "setup": "Your friend claims they could beat you at anything.",
     "note": "Playful challenge — call the bluff with a specific dare.",
     "es": ["Te gano en lo que quieras, elige.", "Vale: a ver quién aguanta más sin mirar el móvil.", "Tienes razón, eres mejor en todo.", "El partido empieza a las ocho.", "Mi hermana vive en Sevilla."],
     "fr": ["Je te bats à n’importe quoi, choisis.", "OK : on voit qui tient le plus longtemps sans regarder son téléphone.", "Tu as raison, tu es meilleur en tout.", "Le match commence à huit heures.", "Ma sœur habite à Lyon."],
     "it": ["Ti batto in qualsiasi cosa, scegli tu.", "Ok: vediamo chi resiste di più senza guardare il telefono.", "Hai ragione, sei più bravo in tutto.", "La partita inizia alle otto.", "Mia sorella vive a Torino."],
     "pt": ["Eu te ganho em qualquer coisa, escolhe.", "Beleza: vamos ver quem aguenta mais tempo sem olhar o celular.", "Você tem razão, é melhor em tudo.", "O jogo começa às oito.", "Minha irmã mora em Recife."],
     "ja": ["{何|なん}でも{勝|か}てるよ、{選|えら}んで。", "じゃあ、どっちが{長|なが}くスマホを{見|み}ないでいられるか{勝負|しょうぶ}。", "その{通|とお}り、{君|きみ}は{全部|ぜんぶ}{上手|じょうず}だよ。", "{試合|しあい}は{八時|はちじ}に{始|はじ}まる。", "{姉|あね}は{大阪|おおさか}に{住|す}んでいる。"],
     "zh": ["随便比什么我都能赢你，你挑。", "行：看谁能更久不看手机。", "你说得对，你什么都比我强。", "比赛八点开始。", "我姐姐住在成都。"]},
    {"id": "d-c2-03", "topic": "talk-banter", "setup": "A friend teases you for still using an ancient phone.",
     "note": "Self-deprecating humour beats defensiveness.",
     "es": ["¿Ese móvil todavía funciona? Es una pieza de museo.", "Oye, que lo mío es vintage, no viejo.", "Sí, debería comprar uno nuevo mañana mismo.", "El museo cierra los lunes.", "Necesito un cargador."],
     "fr": ["Il marche encore, ce téléphone ? C’est une pièce de musée.", "Hé, chez moi c’est vintage, pas vieux.", "Oui, je devrais en acheter un neuf dès demain.", "Le musée est fermé le lundi.", "J’ai besoin d’un chargeur."],
     "it": ["Funziona ancora quel telefono? È un pezzo da museo.", "Ehi, il mio è vintage, mica vecchio.", "Sì, dovrei comprarne uno nuovo domani stesso.", "Il museo è chiuso il lunedì.", "Mi serve un caricabatterie."],
     "pt": ["Esse celular ainda funciona? É peça de museu.", "Ô, o meu é vintage, não é velho.", "É, eu deveria comprar um novo amanhã mesmo.", "O museu fecha na segunda.", "Preciso de um carregador."],
     "ja": ["そのスマホまだ{動|うご}くの？{博物館|はくぶつかん}{級|きゅう}だね。", "ちょっと、{古|ふる}いんじゃなくてヴィンテージなの。", "そうだね、{明日|あした}にでも{新|あたら}しいのを{買|か}うべきだ。", "{博物館|はくぶつかん}は{月曜|げつよう}{休|やす}み。", "{充電器|じゅうでんき}が{必要|ひつよう}。"],
     "zh": ["那手机还能用？简直是博物馆藏品。", "喂，我这叫复古，不叫旧。", "是啊，我明天就该买个新的。", "博物馆周一闭馆。", "我需要一个充电器。"]},
    {"id": "d-c2-04", "topic": "talk-banter", "setup": "Your friend says your cooking “isn’t bad”.",
     "note": "Read the backhanded compliment and return it with a wink.",
     "es": ["Pues no está mal, para ser tú.", "Viniendo de alguien que quema el agua, me lo tomo como un elogio.", "Gracias, me alegro de que te guste.", "La sal está en la mesa.", "Cené a las nueve."],
     "fr": ["Bah, c’est pas mauvais, pour toi.", "Venant de quelqu’un qui fait brûler l’eau, je prends ça comme un compliment.", "Merci, je suis content que ça te plaise.", "Le sel est sur la table.", "J’ai dîné à neuf heures."],
     "it": ["Beh, non è male, per essere tuo.", "Detto da uno che brucia l’acqua, lo prendo come un complimento.", "Grazie, sono contento che ti piaccia.", "Il sale è sul tavolo.", "Ho cenato alle nove."],
     "pt": ["Olha, não está ruim, pra ser você.", "Vindo de quem queima água, vou tomar como elogio.", "Obrigado, que bom que gostou.", "O sal está na mesa.", "Jantei às nove."],
     "ja": ["まあ、{君|きみ}にしては{悪|わる}くないね。", "お{湯|ゆ}を{焦|こ}がす{人|ひと}に{言|い}われたら、{褒|ほ}め{言葉|ことば}として{受|う}け{取|と}っとくよ。", "ありがとう、{気|き}に{入|い}ってもらえて{嬉|うれ}しい。", "{塩|しお}はテーブルの{上|うえ}にあるよ。", "{九時|くじ}に{夕食|ゆうしょく}を{食|た}べた。"],
     "zh": ["嗯，以你的水平来说，还不错。", "从一个能把水烧糊的人嘴里说出来，我就当是夸我了。", "谢谢，你喜欢就好。", "盐在桌子上。", "我九点吃的晚饭。"]},
    {"id": "d-c2-05", "topic": "talk-heated-debate", "setup": "Someone insists social media has ruined public debate.",
     "note": "Concede a point, then counter with a sharper one — that’s how you hold your ground at native speed.",
     "es": ["Las redes han destrozado el debate público, punto.", "Tienen su parte de culpa, sí, pero antes el debate lo controlaban cuatro periódicos.", "Totalmente de acuerdo, no hay más que hablar.", "Mi cuenta tiene mil seguidores.", "El periódico llega por la mañana."],
     "fr": ["Les réseaux sociaux ont détruit le débat public, point final.", "Ils ont leur part de responsabilité, oui, mais avant le débat était contrôlé par trois journaux.", "Tout à fait d’accord, il n’y a rien à ajouter.", "Mon compte a mille abonnés.", "Le journal arrive le matin."],
     "it": ["I social hanno distrutto il dibattito pubblico, punto.", "Hanno le loro colpe, sì, ma prima il dibattito lo controllavano tre giornali.", "Sono d’accordo, non c’è altro da dire.", "Il mio profilo ha mille follower.", "Il giornale arriva la mattina."],
     "pt": ["As redes sociais destruíram o debate público, ponto final.", "Têm sua parcela de culpa, sim, mas antes o debate era controlado por três jornais.", "Concordo totalmente, não há mais o que dizer.", "Minha conta tem mil seguidores.", "O jornal chega de manhã."],
     "ja": ["SNSは{公共|こうきょう}の{議論|ぎろん}を{壊|こわ}した、{以上|いじょう}。", "{責任|せきにん}の{一端|いったん}はあるけど、{昔|むかし}は{議論|ぎろん}を{数社|すうしゃ}の{新聞|しんぶん}が{仕切|しき}ってたよね。", "{完全|かんぜん}に{同意|どうい}、{言|い}うことなし。", "{私|わたし}のアカウントはフォロワーが{千人|せんにん}いる。", "{新聞|しんぶん}は{朝|あさ}{届|とど}く。"],
     "zh": ["社交媒体毁了公共讨论，没得辩。", "它们确实有责任，但以前的讨论是被三四家报纸把控的。", "完全同意，没什么好说的了。", "我的账号有一千个粉丝。", "报纸早上送到。"]},
    {"id": "d-c2-06", "topic": "talk-heated-debate", "setup": "A relative says young people don’t want to work anymore.",
     "note": "Challenge the premise with evidence, not with anger.",
     "es": ["Los jóvenes de hoy no quieren trabajar, así de claro.", "¿O será que no quieren trabajar por sueldos que no pagan ni el alquiler?", "Es verdad, somos unos vagos.", "Yo trabajo en una oficina.", "El alquiler se paga el día uno."],
     "fr": ["Les jeunes d’aujourd’hui ne veulent plus travailler, c’est clair.", "Ou alors ils ne veulent pas travailler pour des salaires qui ne paient même pas le loyer ?", "C’est vrai, on est des fainéants.", "Je travaille dans un bureau.", "Le loyer se paie le premier du mois."],
     "it": ["I giovani di oggi non vogliono lavorare, chiaro e tondo.", "O forse non vogliono lavorare per stipendi che non pagano nemmeno l’affitto?", "È vero, siamo dei fannulloni.", "Io lavoro in un ufficio.", "L’affitto si paga il primo del mese."],
     "pt": ["Os jovens de hoje não querem trabalhar, simples assim.", "Ou será que não querem trabalhar por salários que não pagam nem o aluguel?", "É verdade, somos uns preguiçosos.", "Eu trabalho num escritório.", "O aluguel vence dia primeiro."],
     "ja": ["{今|いま}の{若者|わかもの}は{働|はたら}きたがらない、それだけのことだ。", "というより、{家賃|やちん}も{払|はら}えない{給料|きゅうりょう}で{働|はたら}きたくないだけじゃない？", "そうだね、{僕|ぼく}らは{怠|なま}け{者|もの}だ。", "{僕|ぼく}はオフィスで{働|はたら}いている。", "{家賃|やちん}は{一日|ついたち}に{払|はら}う。"],
     "zh": ["现在的年轻人就是不想工作，就这么简单。", "还是说，他们只是不想为连房租都付不起的工资工作？", "没错，我们就是懒。", "我在办公室工作。", "房租一号交。"]},
    {"id": "d-c2-07", "topic": "talk-heated-debate", "setup": "A colleague argues the city should ban all cars from the centre.",
     "note": "Find the middle ground while naming the real trade-off.",
     "es": ["Habría que prohibir los coches en todo el centro, sin excepciones.", "Sin excepciones no: ¿y las ambulancias, los repartos, la gente con movilidad reducida?", "Sí, prohibámoslo todo mañana.", "Mi coche es rojo.", "El centro tiene muchas tiendas."],
     "fr": ["Il faudrait interdire les voitures dans tout le centre, sans exception.", "Sans exception, non : et les ambulances, les livraisons, les personnes à mobilité réduite ?", "Oui, interdisons tout dès demain.", "Ma voiture est rouge.", "Le centre a beaucoup de magasins."],
     "it": ["Bisognerebbe vietare le auto in tutto il centro, senza eccezioni.", "Senza eccezioni no: e le ambulanze, le consegne, chi ha problemi di mobilità?", "Sì, vietiamo tutto da domani.", "La mia auto è rossa.", "Il centro ha tanti negozi."],
     "pt": ["Deveriam proibir carros em todo o centro, sem exceção.", "Sem exceção não: e as ambulâncias, as entregas, as pessoas com mobilidade reduzida?", "Sim, vamos proibir tudo amanhã.", "Meu carro é vermelho.", "O centro tem muitas lojas."],
     "ja": ["{中心部|ちゅうしんぶ}は{例外|れいがい}なく{車|くるま}を{禁止|きんし}すべきだ。", "{例外|れいがい}なくは{無理|むり}でしょ。{救急車|きゅうきゅうしゃ}や{配達|はいたつ}、{移動|いどう}が{難|むずか}しい{人|ひと}はどうするの？", "うん、{明日|あした}から{全部|ぜんぶ}{禁止|きんし}にしよう。", "{僕|ぼく}の{車|くるま}は{赤|あか}い。", "{中心部|ちゅうしんぶ}には{店|みせ}が{多|おお}い。"],
     "zh": ["市中心应该全面禁车，不设例外。", "不设例外可不行：救护车、送货、行动不便的人怎么办？", "对，明天就全禁了。", "我的车是红色的。", "市中心有很多商店。"]},
    {"id": "d-c2-08", "topic": "talk-heated-debate", "setup": "A friend says learning languages is pointless now that AI translates everything.",
     "note": "Answer the strongest version of their claim, then show what translation can’t carry.",
     "es": ["Aprender idiomas ya no tiene sentido, la IA lo traduce todo.", "Traduce palabras, sí; pero el chiste, el tono y la confianza de la otra persona no te los traduce nadie.", "Cierto, dejo el curso hoy mismo.", "La aplicación es gratis.", "Estudio español los martes."],
     "fr": ["Apprendre des langues ne sert plus à rien, l’IA traduit tout.", "Elle traduit les mots, oui ; mais la blague, le ton et la confiance de l’autre, personne ne te les traduit.", "C’est vrai, j’arrête le cours aujourd’hui.", "L’appli est gratuite.", "J’étudie le français le mardi."],
     "it": ["Imparare le lingue non ha più senso, l’IA traduce tutto.", "Traduce le parole, sì; ma la battuta, il tono e la fiducia dell’altro non te li traduce nessuno.", "Vero, mollo il corso oggi stesso.", "L’app è gratuita.", "Studio italiano il martedì."],
     "pt": ["Aprender idiomas não faz mais sentido, a IA traduz tudo.", "Traduz palavras, sim; mas a piada, o tom e a confiança da outra pessoa ninguém traduz pra você.", "Verdade, largo o curso hoje mesmo.", "O aplicativo é grátis.", "Estudo português às terças."],
     "ja": ["{語学|ごがく}なんてもう{無意味|むいみ}だよ、AIが{全部|ぜんぶ}{訳|やく}してくれる。", "{言葉|ことば}は{訳|やく}せてもね、{冗談|じょうだん}や{口調|くちょう}、{相手|あいて}の{信頼|しんらい}までは{誰|だれ}も{訳|やく}してくれないよ。", "その{通|とお}り、{今日|きょう}で{講座|こうざ}をやめる。", "アプリは{無料|むりょう}だ。", "{火曜日|かようび}に{日本語|にほんご}を{勉強|べんきょう}する。"],
     "zh": ["学语言已经没意义了，AI什么都能翻译。", "词是能翻，可笑话、语气、还有对方对你的信任，没人能替你翻译。", "有道理，我今天就退课。", "这个应用是免费的。", "我周二学中文。"]},
]

LISTEN = [
    {"key": "listen-c2-lines", "tier": "C2", "source": "sentences", "count": 12},
    {"key": "listen-c2-words", "tier": "C2", "source": "vocab", "count": 20},
]
