# -*- coding: utf-8 -*-
# C2 vocabulary batch 4 — proverbs, formal collocations, native-speed spoken chunks, rhetoric & communication
TIER = 'C2'
TOPICS = {
    'proverbs-sayings': 'Proverbs & Sayings', 'formal-collocations': 'Formal Collocations',
    'phrases-c2': 'Native-Speed Chunks', 'communication-rare': 'Rhetoric & Communication',
}
WORDS = [
    # ---- proverbs & sayings (equivalent proverb, not literal) ----
    ("Better late than never", "⏰", "proverbs-sayings", "Más vale tarde que nunca", "Mieux vaut tard que jamais", "Meglio tardi che mai", "Antes tarde do que nunca", "{遅|おそ}くともしないよりはまし", "迟做总比不做好", "chí zuò zǒng bǐ bú zuò hǎo"),
    ("Actions speak louder than words", "🔨", "proverbs-sayings", "Obras son amores y no buenas razones", "Les actes valent mieux que les paroles", "Contano i fatti, non le parole", "Ações falam mais alto que palavras", "{不言実行|ふげんじっこう}", "事实胜于雄辩", "shìshí shèng yú xióngbiàn"),
    ("The early bird catches the worm", "🐦", "proverbs-sayings", "A quien madruga, Dios le ayuda", "L’avenir appartient à ceux qui se lèvent tôt", "Chi dorme non piglia pesci", "Deus ajuda quem cedo madruga", "{早起|はやお}きは{三文|さんもん}の{徳|とく}", "早起的鸟儿有虫吃", "zǎoqǐ de niǎor yǒu chóng chī"),
    ("Don't count your chickens before they hatch", "🐣", "proverbs-sayings", "No vendas la piel del oso antes de cazarlo", "Il ne faut pas vendre la peau de l’ours avant de l’avoir tué", "Non dire gatto se non ce l’hai nel sacco", "Não conte com o ovo antes de a galinha botar", "{捕|と}らぬ{狸|たぬき}の{皮算用|かわざんよう}", "别高兴得太早", "bié gāoxìng dé tài zǎo"),
    ("Every cloud has a silver lining", "🌤️", "proverbs-sayings", "No hay mal que por bien no venga", "À quelque chose malheur est bon", "Non tutto il male vien per nuocere", "Há males que vêm para bem", "{苦|く}あれば{楽|らく}あり", "塞翁失马，焉知非福", "sàiwēng shīmǎ, yān zhī fēi fú"),
    ("Practice makes perfect", "🎹", "proverbs-sayings", "La práctica hace al maestro", "C’est en forgeant qu’on devient forgeron", "La pratica rende perfetti", "A prática leva à perfeição", "{習|なら}うより{慣|な}れろ", "熟能生巧", "shú néng shēng qiǎo"),
    ("When in Rome, do as the Romans do", "🏛️", "proverbs-sayings", "Donde fueres, haz lo que vieres", "À Rome, fais comme les Romains", "Paese che vai, usanza che trovi", "Em Roma, faça como os romanos", "{郷|ごう}に{入|い}っては{郷|ごう}に{従|したが}え", "入乡随俗", "rù xiāng suí sú"),
    ("Two heads are better than one", "🧠", "proverbs-sayings", "Cuatro ojos ven más que dos", "Deux avis valent mieux qu’un", "Due teste sono meglio di una", "Duas cabeças pensam melhor do que uma", "{三人寄|さんにんよ}れば{文殊|もんじゅ}の{知恵|ちえ}", "三个臭皮匠，顶个诸葛亮", "sān gè chòu píjiàng, dǐng gè Zhūgě Liàng"),
    ("The grass is always greener on the other side", "🌱", "proverbs-sayings", "La hierba siempre parece más verde al otro lado", "L’herbe est toujours plus verte ailleurs", "L’erba del vicino è sempre più verde", "A grama do vizinho é sempre mais verde", "{隣|となり}の{芝生|しばふ}は{青|あお}い", "这山望着那山高", "zhè shān wàngzhe nà shān gāo"),
    ("Don't judge a book by its cover", "📕", "proverbs-sayings", "Las apariencias engañan", "L’habit ne fait pas le moine", "L’abito non fa il monaco", "As aparências enganam", "{人|ひと}は{見|み}かけによらぬもの", "人不可貌相", "rén bù kě mào xiàng"),
    ("Birds of a feather flock together", "🦜", "proverbs-sayings", "Dios los cría y ellos se juntan", "Qui se ressemble s’assemble", "Chi si somiglia si piglia", "Diga-me com quem andas e te direi quem és", "{類|るい}は{友|とも}を{呼|よ}ぶ", "物以类聚", "wù yǐ lèi jù"),
    ("A bird in the hand is worth two in the bush", "🤲", "proverbs-sayings", "Más vale pájaro en mano que ciento volando", "Un tiens vaut mieux que deux tu l’auras", "Meglio un uovo oggi che una gallina domani", "Mais vale um pássaro na mão do que dois voando", "{明日|あす}の{百|ひゃく}より{今日|きょう}の{五十|ごじゅう}", "一鸟在手胜过双鸟在林", "yī niǎo zài shǒu shèng guò shuāng niǎo zài lín"),
    ("Where there's a will, there's a way", "🧗", "proverbs-sayings", "Querer es poder", "Vouloir, c’est pouvoir", "Volere è potere", "Querer é poder", "{精神一到|せいしんいっとう}{何事|なにごと}か{成|な}らざらん", "有志者事竟成", "yǒu zhì zhě shì jìng chéng"),
    ("Rome wasn't built in a day", "🧱", "proverbs-sayings", "Roma no se construyó en un día", "Rome ne s’est pas faite en un jour", "Roma non fu fatta in un giorno", "Roma não foi construída em um dia", "ローマは{一日|いちにち}にして{成|な}らず", "罗马不是一天建成的", "Luómǎ bú shì yì tiān jiànchéng de"),
    ("Too many cooks spoil the broth", "🍲", "proverbs-sayings", "Muchas manos en un plato hacen mucho garabato", "Trop de cuisiniers gâtent la sauce", "Troppi cuochi guastano la cucina", "Muitos cozinheiros estragam a sopa", "{船頭多|せんどうおお}くして{船山|ふねやま}に{上|のぼ}る", "人多手杂", "rén duō shǒu zá"),
    ("Out of sight, out of mind", "🙈", "proverbs-sayings", "Ojos que no ven, corazón que no siente", "Loin des yeux, loin du cœur", "Lontano dagli occhi, lontano dal cuore", "O que os olhos não veem, o coração não sente", "{去|さ}る{者|もの}は{日々|ひび}に{疎|うと}し", "眼不见，心不烦", "yǎn bú jiàn, xīn bù fán"),
    ("Look before you leap", "🪂", "proverbs-sayings", "Antes de que te cases, mira lo que haces", "Il faut réfléchir avant d’agir", "Prima di agire, pensa", "Pense antes de agir", "{転|ころ}ばぬ{先|さき}の{杖|つえ}", "三思而后行", "sān sī ér hòu xíng"),
    ("Necessity is the mother of invention", "💡", "proverbs-sayings", "La necesidad es la madre de la invención", "Nécessité est mère d’invention", "La necessità aguzza l’ingegno", "A necessidade é a mãe da invenção", "{必要|ひつよう}は{発明|はつめい}の{母|はは}", "需要是发明之母", "xūyào shì fāmíng zhī mǔ"),
    ("You can't have your cake and eat it too", "🎂", "proverbs-sayings", "No se puede estar en misa y repicando", "On ne peut pas avoir le beurre et l’argent du beurre", "Non si può avere la botte piena e la moglie ubriaca", "Não se pode ter tudo", "{二兎|にと}を{追|お}う{者|もの}は{一兎|いっと}をも{得|え}ず", "鱼与熊掌不可兼得", "yú yǔ xióngzhǎng bù kě jiān dé"),
    ("Honesty is the best policy", "🤝", "proverbs-sayings", "La honestidad es la mejor política", "L’honnêteté est la meilleure des politiques", "L’onestà è la miglior politica", "A honestidade é a melhor política", "{正直|しょうじき}は{最善|さいぜん}の{策|さく}", "诚实为上策", "chéngshí wéi shàng cè"),
    ("Still waters run deep", "🌊", "proverbs-sayings", "Del agua mansa líbreme Dios", "Il n’est pire eau que l’eau qui dort", "L’acqua cheta rovina i ponti", "Águas paradas são profundas", "{能|のう}ある{鷹|たか}は{爪|つめ}を{隠|かく}す", "静水流深", "jìng shuǐ liú shēn"),
    ("Blood is thicker than water", "🩸", "proverbs-sayings", "La sangre tira", "Les liens du sang sont les plus forts", "Il sangue non è acqua", "O sangue fala mais alto", "{血|ち}は{水|みず}よりも{濃|こ}い", "血浓于水", "xuè nóng yú shuǐ"),
    ("Absence makes the heart grow fonder", "💌", "proverbs-sayings", "La ausencia aviva el cariño", "L’absence renforce l’amour", "La lontananza rafforza l’amore", "A distância aumenta o afeto", "{会|あ}えない{時間|じかん}が{愛|あい}を{育|そだ}てる", "小别胜新婚", "xiǎo bié shèng xīn hūn"),
    ("Every dog has its day", "🐕", "proverbs-sayings", "A cada cerdo le llega su San Martín", "À chacun son heure de gloire", "Ognuno ha il suo momento", "Um dia é da caça, outro do caçador", "{犬|いぬ}も{歩|ある}けば{棒|ぼう}に{当|あ}たる", "人人都有得意日", "rénrén dōu yǒu déyì rì"),
    ("Haste makes waste", "🏃", "proverbs-sayings", "Vísteme despacio que tengo prisa", "Qui trop se hâte reste en chemin", "La gatta frettolosa fece i gattini ciechi", "A pressa é inimiga da perfeição", "{急|せ}いては{事|こと}を{仕損|しそん}じる", "欲速则不达", "yù sù zé bù dá"),
    ("Let sleeping dogs lie", "😴", "proverbs-sayings", "Mejor no meneallo", "Ne réveillez pas le chat qui dort", "Non svegliare il can che dorme", "Não cutuque a onça com vara curta", "{触|さわ}らぬ{神|かみ}に{祟|たた}りなし", "别惹是生非", "bié rě shì shēng fēi"),
    ("Strike while the iron is hot", "🔥", "proverbs-sayings", "Al hierro candente, batirlo de repente", "Il faut battre le fer tant qu’il est chaud", "Batti il ferro finché è caldo", "Malhe o ferro enquanto está quente", "{鉄|てつ}は{熱|あつ}いうちに{打|う}て", "趁热打铁", "chèn rè dǎ tiě"),
    ("The pen is mightier than the sword", "🖋️", "proverbs-sayings", "La pluma es más poderosa que la espada", "La plume est plus forte que l’épée", "La penna è più potente della spada", "A caneta é mais poderosa que a espada", "ペンは{剣|けん}よりも{強|つよ}し", "笔比剑更有力", "bǐ bǐ jiàn gèng yǒu lì"),
    ("Curiosity killed the cat", "🐈", "proverbs-sayings", "La curiosidad mató al gato", "La curiosité est un vilain défaut", "La curiosità uccise il gatto", "A curiosidade matou o gato", "{好奇心|こうきしん}は{猫|ねこ}をも{殺|ころ}す", "好奇害死猫", "hàoqí hài sǐ māo"),
    ("Beggars can't be choosers", "🥖", "proverbs-sayings", "A caballo regalado no le mires el diente", "À cheval donné on ne regarde pas les dents", "A caval donato non si guarda in bocca", "Cavalo dado não se olha os dentes", "{貰|もら}う{物|もの}は{夏|なつ}も{小袖|こそで}", "有总比没有好（不能挑三拣四）", "bù néng tiāo sān jiǎn sì"),
    # ---- formal collocations ----
    ("To draw a distinction", "↔️", "formal-collocations", "Hacer una distinción", "Établir une distinction", "Fare una distinzione", "Fazer uma distinção", "{区別|くべつ}をつける", "加以区分", "jiāyǐ qūfēn"),
    ("To reach a verdict", "⚖️", "formal-collocations", "Emitir un veredicto", "Rendre un verdict", "Emettere un verdetto", "Chegar a um veredicto", "{評決|ひょうけつ}を{下|くだ}す", "作出裁决", "zuòchū cáijué"),
    ("To pose a threat", "⚠️", "formal-collocations", "Suponer una amenaza", "Représenter une menace", "Costituire una minaccia", "Representar uma ameaça", "{脅威|きょうい}をもたらす", "构成威胁", "gòuchéng wēixié"),
    ("To bear the brunt", "🛡️", "formal-collocations", "Llevarse la peor parte", "Subir de plein fouet", "Subire il peso maggiore", "Arcar com o pior", "{矢面|やおもて}に{立|た}つ", "首当其冲", "shǒu dāng qí chōng"),
    ("To lend credence to", "✅", "formal-collocations", "Dar credibilidad a", "Donner du crédit à", "Dare credito a", "Dar credibilidade a", "〜に{信憑性|しんぴょうせい}を{与|あた}える", "使…可信", "shǐ… kěxìn"),
    ("To wield influence", "🎛️", "formal-collocations", "Ejercer influencia", "Exercer une influence", "Esercitare influenza", "Exercer influência", "{影響力|えいきょうりょく}を{振|ふ}るう", "施加影响力", "shījiā yǐngxiǎnglì"),
    ("To incur a cost", "💸", "formal-collocations", "Incurrir en un gasto", "Encourir un coût", "Sostenere un costo", "Incorrer em um custo", "{費用|ひよう}を{負担|ふたん}する", "承担费用", "chéngdān fèiyòng"),
    ("To uphold a principle", "🏛️", "formal-collocations", "Defender un principio", "Défendre un principe", "Sostenere un principio", "Defender um princípio", "{原則|げんそく}を{守|まも}る", "坚持原则", "jiānchí yuánzé"),
    ("To exert pressure", "🧲", "formal-collocations", "Ejercer presión", "Exercer une pression", "Esercitare pressione", "Exercer pressão", "{圧力|あつりょく}をかける", "施加压力", "shījiā yālì"),
    ("To fulfil an obligation", "📜", "formal-collocations", "Cumplir una obligación", "Remplir une obligation", "Adempiere a un obbligo", "Cumprir uma obrigação", "{義務|ぎむ}を{果|は}たす", "履行义务", "lǚxíng yìwù"),
    ("To cast doubt on", "🌫️", "formal-collocations", "Poner en duda", "Jeter le doute sur", "Mettere in dubbio", "Lançar dúvidas sobre", "〜に{疑問|ぎもん}を{投|な}げかける", "对…提出质疑", "duì… tíchū zhìyí"),
    ("To pay tribute to", "🎗️", "formal-collocations", "Rendir homenaje a", "Rendre hommage à", "Rendere omaggio a", "Prestar homenagem a", "〜に{敬意|けいい}を{表|ひょう}する", "向…致敬", "xiàng… zhìjìng"),
    ("To take precedence over", "🥇", "formal-collocations", "Tener prioridad sobre", "Avoir la priorité sur", "Avere la precedenza su", "Ter precedência sobre", "〜に{優先|ゆうせん}する", "优先于", "yōuxiān yú"),
    ("To run the risk of", "🎲", "formal-collocations", "Correr el riesgo de", "Courir le risque de", "Correre il rischio di", "Correr o risco de", "〜する{危険|きけん}を{冒|おか}す", "冒…的风险", "mào… de fēngxiǎn"),
    ("To strike a balance", "⚖️", "formal-collocations", "Encontrar un equilibrio", "Trouver un équilibre", "Trovare un equilibrio", "Encontrar um equilíbrio", "バランスを{取|と}る", "取得平衡", "qǔdé pínghéng"),
    ("To come to fruition", "🍎", "formal-collocations", "Llegar a buen puerto", "Se concrétiser (porter ses fruits)", "Giungere a compimento", "Concretizar-se", "{実現|じつげん}する（{実|み}を{結|むす}ぶ）", "取得成果", "qǔdé chéngguǒ"),
    ("To shed light on", "🔦", "formal-collocations", "Arrojar luz sobre", "Faire la lumière sur", "Fare luce su", "Lançar luz sobre", "〜を{明|あき}らかにする", "阐明", "chǎnmíng"),
    ("To set a precedent", "📌", "formal-collocations", "Sentar un precedente", "Créer un précédent", "Creare un precedente", "Abrir um precedente", "{前例|ぜんれい}を{作|つく}る", "开创先例", "kāichuàng xiānlì"),
    ("To give rise to", "🌱", "formal-collocations", "Dar lugar a", "Donner lieu à", "Dare origine a", "Dar origem a", "〜を{引|ひ}き{起|お}こす", "引起", "yǐnqǐ"),
    ("To take issue with", "🙅", "formal-collocations", "Discrepar de", "Contester (s’élever contre)", "Contestare", "Discordar de (contestar)", "〜に{異議|いぎ}を{唱|とな}える", "对…提出异议", "duì… tíchū yìyì"),
    ("Pursuant to", "📜", "formal-collocations", "De conformidad con (en virtud de)", "Conformément à (en application de)", "Ai sensi di (in conformità a)", "Nos termos de (em conformidade com)", "〜に{基|もと}づき", "根据（依照）", "gēnjù"),
    ("Heretofore", "⏮️", "formal-collocations", "Hasta ahora (anteriormente)", "Jusqu’ici (auparavant)", "Finora (in precedenza)", "Até então (anteriormente)", "これまでは", "在此之前", "zài cǐ zhīqián"),
    ("Inasmuch as", "📎", "formal-collocations", "En tanto que (dado que)", "Dans la mesure où (attendu que)", "In quanto (dal momento che)", "Na medida em que (visto que)", "〜である{以上|いじょう}", "由于（鉴于）", "jiànyú"),
    ("In conjunction with", "🤝", "formal-collocations", "Junto con (conjuntamente con)", "Conjointement avec", "Congiuntamente a", "Em conjunto com", "〜と{併|あわ}せて", "与…结合", "yǔ… jiéhé"),
    ("Hitherto", "⏪", "formal-collocations", "Hasta ahora (hasta la fecha)", "Jusqu’ici (jusqu’à présent)", "Finora (sinora)", "Até agora (até então)", "これまで", "迄今", "qìjīn"),
    ("Forthwith", "⚡", "formal-collocations", "De inmediato (sin demora)", "Sur-le-champ (sans délai)", "Immediatamente (senza indugio)", "Imediatamente (sem demora)", "{直|ただ}ちに", "立即", "lìjí"),
    ("Whilst", "⏳", "formal-collocations", "Mientras (si bien)", "Tandis que (alors que)", "Mentre (sebbene)", "Enquanto (embora)", "〜の{一方|いっぽう}で", "然而（同时）", "rán'ér"),
    ("Wherein", "📍", "formal-collocations", "En el cual (donde)", "Dans lequel (où)", "In cui (nel quale)", "No qual (em que)", "その{中|なか}で", "在其中", "zài qízhōng"),
    ("Vis-à-vis", "↔️", "formal-collocations", "Con respecto a (frente a)", "Vis-à-vis de", "Nei confronti di (rispetto a)", "Em relação a", "〜に{対|たい}して", "相对于", "xiāngduì yú"),
    ("As regards", "🎯", "formal-collocations", "En cuanto a", "En ce qui concerne (quant à)", "Per quanto concerne", "Quanto a", "〜については", "至于", "zhìyú"),
    ("For the sake of argument", "🤔", "formal-collocations", "Por poner un ejemplo (supongamos)", "Pour les besoins de la discussion", "Per ipotesi (per amor di discussione)", "A título de argumentação", "{議論|ぎろん}のために（{仮|かり}に）", "为了论证起见", "wèile lùnzhèng qǐjiàn"),
    ("Be that as it may", "🤷", "formal-collocations", "Sea como fuere", "Quoi qu’il en soit", "Comunque sia", "Seja como for", "それはそれとして", "尽管如此", "jǐnguǎn rúcǐ"),
    ("On balance", "⚖️", "formal-collocations", "En conjunto (bien mirado)", "Tout bien considéré", "Tutto sommato", "Pesando tudo", "{総合的|そうごうてき}に{見|み}て", "总的来看", "zǒng de lái kàn"),
    ("At the behest of", "📨", "formal-collocations", "A instancias de", "À la demande de", "Su richiesta di", "A pedido de", "〜の{要請|ようせい}で", "应…的要求", "yìng… de yāoqiú"),
    ("In the wake of", "🌊", "formal-collocations", "A raíz de", "À la suite de", "Sulla scia di", "Na esteira de", "〜の{直後|ちょくご}に", "紧随…之后", "jǐn suí… zhī hòu"),
    ("On the grounds that", "🧱", "formal-collocations", "Alegando que", "Au motif que", "Con la motivazione che", "Sob a alegação de que", "〜という{理由|りゆう}で", "以…为由", "yǐ… wéi yóu"),
    ("In accordance with", "📋", "formal-collocations", "De conformidad con", "Conformément à", "In conformità con", "Em conformidade com", "〜に{従|したが}って", "依照", "yīzhào"),
    ("Pending", "⏳", "formal-collocations", "A la espera de (pendiente de)", "En attendant (dans l’attente de)", "In attesa di", "Aguardando (pendente de)", "〜を{待|ま}って", "待…（有待）", "yǒudài"),
    ("Irrespective of", "🚫", "formal-collocations", "Independientemente de", "Indépendamment de", "A prescindere da", "Independentemente de", "〜に{関係|かんけい}なく", "不论", "búlùn"),
    ("Hereinafter", "📄", "formal-collocations", "En adelante (en lo sucesivo)", "Ci-après", "In seguito (qui di seguito)", "Doravante (a seguir)", "{以下|いか}", "以下（下文）", "yǐxià"),
    # ---- native-speed spoken chunks ----
    ("Beats me", "🤷", "phrases-c2", "Ni idea", "Aucune idée", "Boh, non ne ho idea", "Sei lá", "さあね", "我哪知道", "wǒ nǎ zhīdào"),
    ("Point taken", "👍", "phrases-c2", "Tomo nota (tienes razón)", "Message reçu (bien vu)", "Ricevuto (hai ragione)", "Entendido (ponto para você)", "なるほど、{確|たし}かに", "明白了（你说得对）", "míngbai le"),
    ("Suit yourself", "🙃", "phrases-c2", "Como quieras", "Comme tu veux", "Fa’ come ti pare", "Como quiser", "{好|す}きにしろ", "随你便", "suí nǐ biàn"),
    ("Go figure", "🤯", "phrases-c2", "Vete a saber", "Va comprendre", "Vai a capire", "Vai entender", "わけがわからない", "谁知道呢（真搞不懂）", "zhēn gǎo bù dǒng"),
    ("Don't get me started", "🙄", "phrases-c2", "Ni me hables", "Ne m’en parle pas", "Non farmi parlare", "Nem me fale", "その{話|はなし}はやめて", "别提了", "bié tí le"),
    ("Bottom line is", "📉", "phrases-c2", "En resumidas cuentas", "En fin de compte", "In conclusione (il punto è)", "Resumindo (o fato é que)", "{要|よう}するに", "归根结底", "guīgēn jiédǐ"),
    ("Off the top of my head", "🧠", "phrases-c2", "Así de primeras", "Comme ça, de tête", "Così su due piedi", "Assim de cabeça", "ぱっと{思|おも}いつくのは", "一时想到的", "yìshí xiǎngdào de"),
    ("I'll say", "💯", "phrases-c2", "Ya te digo", "Et comment", "Eccome", "Pode crer", "{本当|ほんとう}にね", "可不是嘛", "kě bú shì ma"),
    ("You've got to be kidding me", "😳", "phrases-c2", "No me fastidies", "Tu te fiches de moi", "Mi prendi in giro", "Só pode ser brincadeira", "{冗談|じょうだん}でしょ", "你开什么玩笑", "nǐ kāi shénme wánxiào"),
    ("No offense, but", "🫤", "phrases-c2", "Sin ánimo de ofender, pero", "Sans vouloir te vexer, mais", "Senza offesa, ma", "Sem ofensa, mas", "{悪気|わるぎ}はないんだけど", "无意冒犯，但是", "wúyì màofàn, dànshì"),
    ("I'm not gonna lie", "🤥", "phrases-c2", "No te voy a mentir", "Je vais pas te mentir", "Non ti dico bugie", "Não vou mentir", "{正直|しょうじき}に{言|い}うと", "说实话", "shuō shíhuà"),
    ("Speak of the devil", "😈", "phrases-c2", "Hablando del rey de Roma", "Quand on parle du loup", "Parli del diavolo", "Falando no diabo", "{噂|うわさ}をすれば", "说曹操，曹操到", "shuō Cáo Cāo, Cáo Cāo dào"),
    ("It's on the tip of my tongue", "👅", "phrases-c2", "Lo tengo en la punta de la lengua", "Je l’ai sur le bout de la langue", "Ce l’ho sulla punta della lingua", "Está na ponta da língua", "{喉|のど}まで{出|で}かかってる", "话到嘴边了", "huà dào zuǐ biān le"),
    ("Let's call it a day", "🌇", "phrases-c2", "Lo dejamos por hoy", "On arrête là pour aujourd’hui", "Per oggi basta così", "Por hoje chega", "{今日|きょう}はここまでにしよう", "今天就到这儿吧", "jīntiān jiù dào zhèr ba"),
    ("It's not rocket science", "🚀", "phrases-c2", "No es tan complicado", "C’est pas sorcier", "Non è mica fisica nucleare", "Não é nenhum bicho de sete cabeças", "そんなに{難|むずか}しくない", "又不是什么高深的东西", "yòu bú shì shénme gāoshēn de dōngxi"),
    ("That's the last straw", "🥤", "phrases-c2", "Es la gota que colma el vaso", "C’est la goutte qui fait déborder le vase", "È la goccia che fa traboccare il vaso", "É a gota d’água", "もう{我慢|がまん}の{限界|げんかい}", "忍无可忍了", "rěn wú kě rěn le"),
    ("I couldn't care less", "😑", "phrases-c2", "Me da exactamente igual", "Je m’en fiche complètement", "Non me ne può fregare di meno", "Não estou nem aí", "どうでもいい", "我根本不在乎", "wǒ gēnběn bú zàihu"),
    ("What are the odds", "🎰", "phrases-c2", "Qué casualidad", "Quelle coïncidence", "Che coincidenza", "Que coincidência", "なんて{偶然|ぐうぜん}", "太巧了吧", "tài qiǎo le ba"),
    ("Say no more", "🤐", "phrases-c2", "No digas más", "N’en dis pas plus", "Non dire altro", "Nem precisa dizer mais", "みなまで{言|い}うな", "不用多说了", "bú yòng duō shuō le"),
    ("Hang in there", "💪", "phrases-c2", "Aguanta", "Tiens bon", "Tieni duro", "Aguenta firme", "{頑張|がんば}って（{踏|ふ}ん{張|ば}って）", "撑住", "chēng zhù"),
    ("I'm all ears", "👂", "phrases-c2", "Soy todo oídos", "Je suis tout ouïe", "Sono tutt’orecchi", "Sou todo ouvidos", "{聞|き}かせて", "洗耳恭听", "xǐ ěr gōng tīng"),
    ("That's on me", "🙋", "phrases-c2", "Eso es culpa mía", "C’est ma faute", "È colpa mia", "A culpa é minha", "それは{僕|ぼく}の{責任|せきにん}", "这是我的责任", "zhè shì wǒ de zérèn"),
    ("No hard feelings", "🤝", "phrases-c2", "Sin rencores", "Sans rancune", "Senza rancore", "Sem ressentimentos", "{根|ね}に{持|も}たないで", "别往心里去", "bié wǎng xīnli qù"),
    ("Ditto", "🔁", "phrases-c2", "Ídem (lo mismo)", "Idem (pareil)", "Idem", "Idem", "{同|おな}じく（{右|みぎ}に{同|おな}じ）", "同上（我也是）", "tóngshàng"),
    ("Spill the beans", "🫘", "phrases-c2", "Suelta la sopa", "Crache le morceau", "Vuota il sacco", "Desembucha", "{白状|はくじょう}しろ", "快说吧（说出来）", "kuài shuō ba"),
    ("In one ear and out the other", "👂", "phrases-c2", "Por un oído le entra y por otro le sale", "Ça rentre par une oreille et ça sort par l’autre", "Entra da un orecchio ed esce dall’altro", "Entra por um ouvido e sai pelo outro", "{右|みぎ}の{耳|みみ}から{左|ひだり}の{耳|みみ}へ", "左耳进右耳出", "zuǒ ěr jìn yòu ěr chū"),
    ("Cut to the chase", "🎬", "phrases-c2", "Ve al grano", "Va droit au but", "Vai al sodo", "Vai direto ao ponto", "{単刀直入|たんとうちょくにゅう}に{言|い}って", "直奔主题", "zhí bèn zhǔtí"),
    ("You name it", "📝", "phrases-c2", "Lo que se te ocurra", "Tout ce que tu veux", "Quello che vuoi", "O que você quiser", "{何|なん}でも", "应有尽有", "yīng yǒu jìn yǒu"),
    ("Not in a million years", "🚫", "phrases-c2", "Ni de broma", "Jamais de la vie", "Neanche per sogno", "Nem morto", "{絶対|ぜったい}にない", "绝不可能", "jué bù kěnéng"),
    ("It is what it is", "🫠", "phrases-c2", "Es lo que hay", "C’est comme ça", "È così e basta", "É o que é", "しょうがない", "就这样吧", "jiù zhèyàng ba"),
    ("Give me a break", "😤", "phrases-c2", "Déjame en paz (venga ya)", "Lâche-moi un peu", "Ma dai, per favore", "Me dá um tempo", "いい{加減|かげん}にして", "饶了我吧", "ráo le wǒ ba"),
    ("Hold your horses", "🐴", "phrases-c2", "Para el carro", "Doucement, pas si vite", "Calma, frena", "Calma aí", "ちょっと{待|ま}った", "别急", "bié jí"),
    ("Bite the bullet", "🦷", "phrases-c2", "Hacer de tripas corazón", "Serrer les dents", "Stringere i denti", "Engolir o sapo", "{覚悟|かくご}を{決|き}める", "硬着头皮", "yìng zhe tóupí"),
    ("Take it with a grain of salt", "🧂", "phrases-c2", "Tómalo con pinzas", "Prends-le avec des pincettes", "Prendilo con le pinze", "Não leve muito a sério", "{話半分|はなしはんぶん}に{聞|き}く", "别全信", "bié quán xìn"),
    ("Better safe than sorry", "🪖", "phrases-c2", "Más vale prevenir que curar", "Mieux vaut prévenir que guérir", "Meglio prevenire che curare", "Melhor prevenir do que remediar", "{念|ねん}には{念|ねん}を", "小心驶得万年船", "xiǎoxīn shǐ dé wànnián chuán"),
    ("Let's play it by ear", "🎶", "phrases-c2", "Ya veremos sobre la marcha", "On verra sur le moment", "Vediamo come va", "Vamos ver no momento", "その{場|ば}で{決|き}めよう", "到时候再说", "dào shíhou zài shuō"),
    ("I'll take a rain check", "🌧️", "phrases-c2", "Lo dejamos para otro día", "Une autre fois, peut-être", "Facciamo un’altra volta", "Fica para a próxima", "また{今度|こんど}にする", "改天吧", "gǎi tiān ba"),
    ("For what it's worth", "🪙", "phrases-c2", "Por si sirve de algo", "Pour ce que ça vaut", "Per quel che vale", "Se serve de alguma coisa", "{参考|さんこう}までに", "不管有没有用", "bùguǎn yǒu méiyǒu yòng"),
    ("Back to square one", "🔁", "phrases-c2", "Vuelta a empezar", "Retour à la case départ", "Punto e a capo", "De volta à estaca zero", "{振|ふ}り{出|だ}しに{戻|もど}る", "回到原点", "huí dào yuándiǎn"),
    ("Touch wood", "🪵", "phrases-c2", "Toco madera", "Je touche du bois", "Tocco ferro", "Bato na madeira", "{縁起|えんぎ}を{担|かつ}いで", "但愿如此（老天保佑）", "lǎotiān bǎoyòu"),
    # ---- rhetoric & communication ----
    ("Allusion", "🪞", "communication-rare", "Alusión", "Allusion", "Allusione", "Alusão", "{暗示|あんじ}（{言及|げんきゅう}）", "典故（暗指）", "diǎngù"),
    ("Anecdote", "📖", "communication-rare", "Anécdota", "Anecdote", "Aneddoto", "Anedota (caso)", "{逸話|いつわ}", "轶事", "yìshì"),
    ("Antithesis", "⚡", "communication-rare", "Antítesis", "Antithèse", "Antitesi", "Antítese", "{対照|たいしょう}（{正反対|せいはんたい}）", "对立面", "duìlìmiàn"),
    ("Aphorism", "💬", "communication-rare", "Aforismo", "Aphorisme", "Aforisma", "Aforismo", "{格言|かくげん}", "格言", "géyán"),
    ("Banter", "😄", "communication-rare", "Bromas (pique amistoso)", "Plaisanteries (badinage)", "Battute scherzose", "Brincadeiras (zoeira)", "{軽口|かるくち}", "调侃", "tiáokǎn"),
    ("Circumlocution", "🌀", "communication-rare", "Circunloquio", "Circonlocution", "Circonlocuzione", "Circunlóquio", "{遠回|とおまわ}しな{言|い}い{方|かた}", "迂回说法", "yūhuí shuōfǎ"),
    ("Cliché", "♻️", "communication-rare", "Cliché", "Cliché", "Cliché (luogo comune)", "Clichê", "{決|き}まり{文句|もんく}", "陈词滥调（老套）", "lǎotào"),
    ("Connotation", "🎨", "communication-rare", "Connotación", "Connotation", "Connotazione", "Conotação", "{含意|がんい}", "内涵（言外之意）", "yán wài zhī yì"),
    ("Digression", "🛤️", "communication-rare", "Digresión", "Digression", "Digressione", "Digressão", "{脱線|だっせん}", "离题", "lítí"),
    ("Double entendre", "😏", "communication-rare", "Doble sentido", "Double sens (sous-entendu)", "Doppio senso", "Duplo sentido", "{二重|にじゅう}の{意味|いみ}", "双关语", "shuāngguānyǔ"),
    ("Eloquence", "🎤", "communication-rare", "Elocuencia", "Éloquence", "Eloquenza", "Eloquência", "{雄弁|ゆうべん}", "口才", "kǒucái"),
    ("Euphemism", "🫣", "communication-rare", "Eufemismo", "Euphémisme", "Eufemismo", "Eufemismo", "{婉曲表現|えんきょくひょうげん}", "委婉语", "wěiwǎnyǔ"),
    ("Gist", "🎯", "communication-rare", "Esencia (lo esencial)", "Essentiel (idée générale)", "Succo (nocciolo)", "Essência (ideia geral)", "{要点|ようてん}", "要点", "yàodiǎn"),
    ("Hyperbole", "📈", "communication-rare", "Hipérbole", "Hyperbole", "Iperbole", "Hipérbole", "{誇張法|こちょうほう}", "夸张", "kuāzhāng"),
    ("Irony", "🙃", "communication-rare", "Ironía", "Ironie", "Ironia", "Ironia", "{皮肉|ひにく}（アイロニー）", "反讽", "fǎnfěng"),
    ("Juxtaposition", "🔲", "communication-rare", "Yuxtaposición", "Juxtaposition", "Giustapposizione", "Justaposição", "{並置|へいち}", "并置", "bìngzhì"),
    ("Malapropism", "🤪", "communication-rare", "Malapropismo (lapsus)", "Impropriété (lapsus)", "Strafalcione", "Malapropismo (trocadilho involuntário)", "{言葉|ことば}の{誤用|ごよう}", "用词错误（可笑的）", "yòngcí cuòwù"),
    ("Oxymoron", "🔥❄️", "communication-rare", "Oxímoron", "Oxymore", "Ossimoro", "Oxímoro", "{撞着語法|どうちゃくごほう}", "矛盾修辞", "máodùn xiūcí"),
    ("Paraphrase", "🔄", "communication-rare", "Paráfrasis", "Paraphrase", "Parafrasi", "Paráfrase", "{言|い}い{換|か}え", "释义（改述）", "gǎishù"),
    ("Pun", "🎭", "communication-rare", "Juego de palabras", "Jeu de mots", "Gioco di parole", "Trocadilho", "{駄洒落|だじゃれ}", "双关（谐音梗）", "xiéyīn gěng"),
    ("Quip", "⚡", "communication-rare", "Ocurrencia (agudeza)", "Bon mot (trait d’esprit)", "Battuta arguta", "Tirada (piada rápida)", "{気|き}の{利|き}いた{一言|ひとこと}", "俏皮话", "qiàopíhuà"),
    ("Sarcasm", "😒", "communication-rare", "Sarcasmo", "Sarcasme", "Sarcasmo", "Sarcasmo", "{嫌味|いやみ}", "讽刺", "fěngcì"),
    ("Slur (insult)", "🚫", "communication-rare", "Insulto (calumnia)", "Insulte (injure)", "Insulto (offesa)", "Insulto (calúnia)", "{中傷|ちゅうしょう}", "污蔑（侮辱性字眼）", "wūmiè"),
    ("Repartee", "⚡", "communication-rare", "Réplica ingeniosa (agudeza)", "Répartie", "Botta e risposta", "Réplica ágil (repartee)", "{当意即妙|とういそくみょう}の{応答|おうとう}", "机智的应答", "jīzhì de yìngdá"),
    ("Soliloquy", "🎭", "communication-rare", "Soliloquio", "Soliloque", "Soliloquio", "Solilóquio", "{独白|どくはく}", "独白", "dúbái"),
    ("Subtext", "📑", "communication-rare", "Subtexto (trasfondo)", "Sous-texte (sous-entendu)", "Sottotesto", "Subtexto (entrelinhas)", "{裏|うら}の{意味|いみ}", "潜台词", "qiántáicí"),
    ("Tangent", "↗️", "communication-rare", "Tangente (desvío del tema)", "Digression (hors-sujet)", "Tangente (divagazione)", "Tangente (desvio)", "{横道|よこみち}", "跑题", "pǎotí"),
    ("Tirade", "📢", "communication-rare", "Diatriba", "Tirade (diatribe)", "Tirata (invettiva)", "Diatribe", "{長広舌|ちょうこうぜつ}", "长篇大论（抨击）", "chángpiān dàlùn"),
    ("Understatement", "🤏", "communication-rare", "Atenuación (quedarse corto)", "Litote (euphémisme)", "Eufemismo (dire poco)", "Eufemismo (dizer pouco)", "{控|ひか}えめな{表現|ひょうげん}", "轻描淡写", "qīng miáo dàn xiě"),
    ("Verbiage", "🗯️", "communication-rare", "Palabrería", "Verbiage", "Verbosità (sproloquio)", "Palavrório", "{冗語|じょうご}", "废话（冗词）", "rǒngcí"),
    ("To allude to", "👉", "communication-rare", "Aludir a", "Faire allusion à", "Alludere a", "Aludir a", "〜をほのめかす", "暗指", "ànzhǐ"),
    ("To enunciate", "🗣️", "communication-rare", "Vocalizar (pronunciar con claridad)", "Articuler (prononcer clairement)", "Scandire", "Pronunciar claramente", "はっきり{発音|はつおん}する", "清晰发音", "qīngxī fāyīn"),
    ("To belabor the point", "🔨", "communication-rare", "Insistir demasiado", "Insister lourdement", "Insistere troppo", "Bater na mesma tecla", "くどくど{言|い}う", "反复强调", "fǎnfù qiángdiào"),
    ("To digress", "🛤️", "communication-rare", "Divagar", "Faire une digression", "Divagare", "Divagar", "{脱線|だっせん}する", "离题", "lítí"),
    ("To expound", "📖", "communication-rare", "Exponer (explicar detalladamente)", "Exposer (développer)", "Esporre (illustrare)", "Expor (explanar)", "{詳述|しょうじゅつ}する", "详述（阐述）", "chǎnshù"),
    ("To insinuate", "😏", "communication-rare", "Insinuar", "Insinuer", "Insinuare", "Insinuar", "ほのめかす", "暗示（含沙射影）", "hán shā shè yǐng"),
    ("To interject", "✋", "communication-rare", "Interponer (intervenir)", "Intervenir (lancer)", "Intervenire (interloquire)", "Interpor (intervir)", "{口|くち}を{挟|はさ}む", "插话", "chāhuà"),
    ("To hammer home", "🔨", "communication-rare", "Machacar (insistir en)", "Enfoncer le clou", "Ribadire con forza", "Martelar (insistir em)", "{念|ねん}を{押|お}す", "反复强调（敲定）", "fǎnfù qiángdiào"),
    ("To retort", "↩️", "communication-rare", "Replicar", "Rétorquer", "Ribattere", "Retrucar", "{言|い}い{返|かえ}す", "反驳（回嘴）", "huízuǐ"),
    ("To waffle (be vague)", "🧇", "communication-rare", "Irse por las ramas", "Tergiverser", "Tergiversare", "Enrolar (ficar em cima do muro)", "{言葉|ことば}を{濁|にご}す", "含糊其辞", "hánhu qí cí"),
]
