# -*- coding: utf-8 -*-
# C2 vocabulary batch 3 — rare & abstract nouns I–IV + sensory (taste, smell, texture, sound)
TIER = 'C2'
TOPICS = {
    'rare-nouns-1': 'Rare Nouns I', 'rare-nouns-2': 'Rare Nouns II',
    'rare-nouns-3': 'Rare Nouns III', 'rare-nouns-4': 'Rare Nouns IV',
    'sensory': 'Taste, Smell & Texture',
}
WORDS = [
    # ---- rare nouns I (abstract qualities) ----
    ("Acumen", "🧠", "rare-nouns-1", "Perspicacia", "Perspicacité (flair)", "Acume", "Perspicácia (tino)", "{洞察力|どうさつりょく}", "敏锐（才智）", "mǐnruì"),
    ("Alacrity", "⚡", "rare-nouns-1", "Presteza (diligencia)", "Empressement", "Alacrità (prontezza)", "Presteza (prontidão)", "{快活|かいかつ}さ（{機敏|きびん}さ）", "欣然（敏捷）", "xīnrán"),
    ("Ambivalence", "⚖️", "rare-nouns-1", "Ambivalencia", "Ambivalence", "Ambivalenza", "Ambivalência", "{相反|あいはん}する{感情|かんじょう}", "矛盾心理", "máodùn xīnlǐ"),
    ("Apathy", "😐", "rare-nouns-1", "Apatía", "Apathie", "Apatia", "Apatia", "{無関心|むかんしん}", "冷漠", "lěngmò"),
    ("Aplomb", "🧘", "rare-nouns-1", "Aplomo", "Aplomb (sang-froid)", "Disinvoltura (aplomb)", "Aprumo (desenvoltura)", "{沈着|ちんちゃく}", "沉着", "chénzhuó"),
    ("Audacity", "🦅", "rare-nouns-1", "Audacia", "Audace", "Audacia", "Audácia", "{大胆|だいたん}さ", "大胆（放肆）", "fàngsì"),
    ("Candor", "🪞", "rare-nouns-1", "Franqueza", "Franchise (candeur)", "Franchezza", "Franqueza", "{率直|そっちょく}さ", "坦率", "tǎnshuài"),
    ("Smugness", "😏", "rare-nouns-1", "Suficiencia (autocomplacencia)", "Suffisance", "Compiacimento (sufficienza)", "Presunção (ar de superioridade)", "{独|ひと}りよがり", "自鸣得意", "zìmíng déyì"),
    ("Scorn", "🙄", "rare-nouns-1", "Desdén (menosprecio)", "Mépris (dédain)", "Disprezzo (scherno)", "Escárnio (desprezo)", "{嘲|あざけ}り", "鄙夷", "bǐyí"),
    ("Deference", "🙇", "rare-nouns-1", "Deferencia", "Déférence", "Deferenza", "Deferência", "{敬意|けいい}（{服従|ふくじゅう}）", "顺从（尊重）", "shùncóng"),
    ("Discretion", "🤫", "rare-nouns-1", "Discreción", "Discrétion", "Discrezione", "Discrição", "{思慮分別|しりょふんべつ}（{裁量|さいりょう}）", "谨慎（自行决定）", "jǐnshèn"),
    ("Disdain", "🙄", "rare-nouns-1", "Desdén", "Dédain", "Sdegno (disdegno)", "Desdém", "{侮蔑|ぶべつ}", "鄙视", "bǐshì"),
    ("Forbearance", "🧘", "rare-nouns-1", "Paciencia (indulgencia)", "Indulgence (patience)", "Indulgenza (pazienza)", "Paciência (indulgência)", "{忍耐|にんたい}（{寛容|かんよう}）", "宽容（忍耐）", "kuānróng"),
    ("Fortitude", "🏔️", "rare-nouns-1", "Fortaleza (entereza)", "Force d’âme (courage)", "Forza d’animo", "Fortaleza (firmeza)", "{不屈|ふくつ}の{精神|せいしん}", "坚韧", "jiānrèn"),
    ("Hubris", "🏛️", "rare-nouns-1", "Arrogancia (soberbia)", "Hubris (orgueil démesuré)", "Tracotanza (hybris)", "Arrogância (húbris)", "{傲慢|ごうまん}", "狂妄自大", "kuángwàng zìdà"),
    ("Meekness", "🐑", "rare-nouns-1", "Mansedumbre", "Douceur (humilité)", "Mitezza", "Mansidão", "{柔和|にゅうわ}さ", "温顺", "wēnshùn"),
    ("Umbrage", "😤", "rare-nouns-1", "Ofensa (resentimiento)", "Ombrage", "Offesa (risentimento)", "Ofensa (melindre)", "{立腹|りっぷく}", "不快（生气）", "bùkuài"),
    ("Ingenuity", "💡", "rare-nouns-1", "Ingenio (inventiva)", "Ingéniosité", "Ingegnosità", "Engenhosidade", "{独創性|どくそうせい}", "独创性（心灵手巧）", "dúchuàngxìng"),
    ("Rectitude", "📏", "rare-nouns-1", "Rectitud", "Rectitude (droiture)", "Rettitudine", "Retidão", "{清廉|せいれん}さ", "正直（品行端正）", "pǐnxíng duānzhèng"),
    ("Malice", "😈", "rare-nouns-1", "Malicia (maldad)", "Malveillance", "Malizia (cattiveria)", "Malícia (maldade)", "{悪意|あくい}", "恶意", "èyì"),
    ("Nostalgia", "📻", "rare-nouns-1", "Nostalgia", "Nostalgie", "Nostalgia", "Nostalgia", "{郷愁|きょうしゅう}", "怀旧", "huáijiù"),
    ("Perseverance", "🐢", "rare-nouns-1", "Perseverancia", "Persévérance", "Perseveranza", "Perseverança", "{忍耐|にんたい}（{粘|ねば}り）", "毅力", "yìlì"),
    ("Prudence", "🦉", "rare-nouns-1", "Prudencia", "Prudence", "Prudenza", "Prudência", "{慎重|しんちょう}さ", "审慎", "shěnshèn"),
    ("Grit", "🪨", "rare-nouns-1", "Coraje (determinación)", "Cran (ténacité)", "Grinta", "Garra", "{根性|こんじょう}", "毅力（韧劲）", "rènjìn"),
    ("Reticence", "🤐", "rare-nouns-1", "Reticencia", "Réticence (réserve)", "Reticenza", "Reticência", "{寡黙|かもく}（{遠慮|えんりょ}）", "沉默寡言", "chénmò guǎyán"),
    ("Equanimity", "⚖️", "rare-nouns-1", "Ecuanimidad", "Équanimité (sérénité)", "Equanimità", "Equanimidade", "{平常心|へいじょうしん}", "平静（沉着）", "píngjìng"),
    ("Tenacity", "🐕", "rare-nouns-1", "Tenacidad", "Ténacité", "Tenacia", "Tenacidade", "{粘|ねば}り{強|づよ}さ", "顽强", "wánqiáng"),
    ("Vanity", "🪞", "rare-nouns-1", "Vanidad", "Vanité", "Vanità", "Vaidade", "{虚栄心|きょえいしん}", "虚荣", "xūróng"),
    ("Vigilance", "👁️", "rare-nouns-1", "Vigilancia", "Vigilance", "Vigilanza", "Vigilância", "{警戒|けいかい}", "警惕", "jǐngtì"),
    ("Zeal", "🔥", "rare-nouns-1", "Fervor (celo)", "Zèle (ferveur)", "Zelo (fervore)", "Zelo (fervor)", "{熱意|ねつい}", "热忱", "rèchén"),
    # ---- rare nouns II (situations & phenomena) ----
    ("Anomaly", "🔍", "rare-nouns-2", "Anomalía", "Anomalie", "Anomalia", "Anomalia", "{異常|いじょう}", "异常", "yìcháng"),
    ("Catalyst", "⚗️", "rare-nouns-2", "Catalizador", "Catalyseur", "Catalizzatore", "Catalisador", "{触媒|しょくばい}（きっかけ）", "催化剂", "cuīhuàjì"),
    ("Conundrum", "🧩", "rare-nouns-2", "Enigma (dilema)", "Casse-tête (énigme)", "Rompicapo (dilemma)", "Enigma (dilema)", "{難題|なんだい}", "难题", "nántí"),
    ("Debacle", "💥", "rare-nouns-2", "Debacle (desastre)", "Débâcle (fiasco)", "Debacle (disfatta)", "Debacle (fiasco)", "{大失敗|だいしっぱい}", "惨败", "cǎnbài"),
    ("Deluge", "🌊", "rare-nouns-2", "Diluvio (avalancha)", "Déluge", "Diluvio", "Dilúvio (enxurrada)", "{洪水|こうずい}（{殺到|さっとう}）", "洪水（泛滥）", "hóngshuǐ"),
    ("Dearth", "🏜️", "rare-nouns-2", "Escasez (carencia)", "Pénurie (manque)", "Scarsità (penuria)", "Escassez (carência)", "{欠乏|けつぼう}", "缺乏", "quēfá"),
    ("Dichotomy", "↔️", "rare-nouns-2", "Dicotomía", "Dichotomie", "Dicotomia", "Dicotomia", "{二分法|にぶんほう}", "二分法（对立）", "èrfēnfǎ"),
    ("Epitome", "🏆", "rare-nouns-2", "Epítome (paradigma)", "Incarnation (archétype)", "Epitome (quintessenza)", "Epítome (símbolo)", "{典型|てんけい}", "典范", "diǎnfàn"),
    ("Exodus", "🚶‍♂️", "rare-nouns-2", "Éxodo", "Exode", "Esodo", "Êxodo", "{大量流出|たいりょうりゅうしゅつ}", "大批离去", "dàpī líqù"),
    ("Facade", "🎭", "rare-nouns-2", "Fachada (apariencia)", "Façade (apparence)", "Facciata (apparenza)", "Fachada (aparência)", "{見|み}せかけ", "表面（假象）", "jiǎxiàng"),
    ("Fallacy", "🌀", "rare-nouns-2", "Falacia", "Sophisme (idée fausse)", "Fallacia (errore)", "Falácia", "{誤謬|ごびゅう}", "谬误", "miùwù"),
    ("Hindsight", "🔙", "rare-nouns-2", "Retrospectiva", "Recul (a posteriori)", "Senno di poi", "Retrospectiva", "{後知恵|あとぢえ}", "事后诸葛亮", "shìhòu zhūgěliàng"),
    ("Impasse", "🚧", "rare-nouns-2", "Punto muerto", "Impasse", "Vicolo cieco (impasse)", "Impasse", "{行|い}き{詰|づ}まり", "僵局", "jiāngjú"),
    ("Impetus", "🚀", "rare-nouns-2", "Impulso (ímpetu)", "Impulsion (élan)", "Impulso (spinta)", "Impulso (ímpeto)", "{弾|はず}み（{推進力|すいしんりょく}）", "推动力", "tuīdònglì"),
    ("Juncture", "🛤️", "rare-nouns-2", "Coyuntura", "Conjoncture (moment)", "Frangente", "Conjuntura", "{時点|じてん}（{節目|ふしめ}）", "关头", "guāntóu"),
    ("Loophole", "🕳️", "rare-nouns-2", "Vacío legal (resquicio)", "Faille (vide juridique)", "Scappatoia", "Brecha (lacuna)", "{抜|ぬ}け{穴|あな}", "漏洞", "lòudòng"),
    ("Tipping point", "⚖️", "rare-nouns-2", "Punto de inflexión", "Point de bascule", "Punto di svolta", "Ponto de virada", "{転換点|てんかんてん}", "临界点", "línjièdiǎn"),
    ("Onslaught", "⚔️", "rare-nouns-2", "Embestida (avalancha)", "Assaut (déferlement)", "Assalto (ondata)", "Investida (avalanche)", "{猛攻|もうこう}", "猛攻", "měnggōng"),
    ("Vicious circle", "🔁", "rare-nouns-2", "Círculo vicioso", "Cercle vicieux", "Circolo vizioso", "Círculo vicioso", "{悪循環|あくじゅんかん}", "恶性循环", "èxìng xúnhuán"),
    ("Plight", "🆘", "rare-nouns-2", "Situación difícil (apuro)", "Détresse (sort)", "Situazione difficile", "Situação difícil (apuro)", "{苦境|くきょう}", "困境", "kùnjìng"),
    ("Precedent", "📜", "rare-nouns-2", "Precedente", "Précédent", "Precedente", "Precedente", "{前例|ぜんれい}", "先例", "xiānlì"),
    ("Quandary", "🤷", "rare-nouns-2", "Dilema (aprieto)", "Dilemme (embarras)", "Dilemma (imbarazzo)", "Dilema (embaraço)", "{板挟|いたばさ}み", "进退两难", "jìntuì liǎngnán"),
    ("Ramification", "🌳", "rare-nouns-2", "Ramificación (consecuencia)", "Ramification (conséquence)", "Ramificazione (conseguenza)", "Ramificação (desdobramento)", "{派生的|はせいてき}な{影響|えいきょう}", "衍生后果", "yǎnshēng hòuguǒ"),
    ("Respite", "🛑", "rare-nouns-2", "Respiro (tregua)", "Répit", "Tregua (respiro)", "Trégua (respiro)", "{小休止|しょうきゅうし}", "喘息（暂缓）", "chuǎnxī"),
    ("Setback", "📉", "rare-nouns-2", "Revés (contratiempo)", "Revers (contretemps)", "Battuta d’arresto", "Revés (contratempo)", "{挫折|ざせつ}", "挫折", "cuòzhé"),
    ("Stalemate", "♟️", "rare-nouns-2", "Tablas (punto muerto)", "Impasse (pat)", "Stallo", "Impasse (empate)", "{膠着状態|こうちゃくじょうたい}", "僵局（对峙）", "duìzhì"),
    ("Surge", "📈", "rare-nouns-2", "Oleada (aumento repentino)", "Poussée (flambée)", "Impennata (ondata)", "Surto (onda)", "{急増|きゅうぞう}", "激增", "jīzēng"),
    ("Turmoil", "🌪️", "rare-nouns-2", "Agitación (confusión)", "Tumulte (bouleversement)", "Tumulto (subbuglio)", "Tumulto (agitação)", "{混乱|こんらん}", "动荡", "dòngdàng"),
    ("Upheaval", "🌋", "rare-nouns-2", "Trastorno (convulsión)", "Bouleversement", "Sconvolgimento", "Reviravolta (convulsão)", "{大変動|だいへんどう}", "剧变", "jùbiàn"),
    ("Watershed", "🏞️", "rare-nouns-2", "Punto de inflexión", "Tournant (moment charnière)", "Spartiacque", "Divisor de águas", "{分岐点|ぶんきてん}", "分水岭", "fēnshuǐlǐng"),
    # ---- rare nouns III (people & roles) ----
    ("Accomplice", "🕵️", "rare-nouns-3", "Cómplice", "Complice", "Complice", "Cúmplice", "{共犯者|きょうはんしゃ}", "同谋", "tóngmóu"),
    ("Adversary", "🥊", "rare-nouns-3", "Adversario", "Adversaire", "Avversario", "Adversário", "{敵対者|てきたいしゃ}", "对手", "duìshǒu"),
    ("Advocate", "📣", "rare-nouns-3", "Defensor (partidario)", "Défenseur (partisan)", "Sostenitore (fautore)", "Defensor (partidário)", "{擁護者|ようごしゃ}", "拥护者", "yōnghùzhě"),
    ("Benefactor", "🎁", "rare-nouns-3", "Benefactor", "Bienfaiteur", "Benefattore", "Benfeitor", "{恩人|おんじん}", "恩人（捐助者）", "ēnrén"),
    ("Bystander", "🧍", "rare-nouns-3", "Espectador (transeúnte)", "Passant (témoin)", "Passante (spettatore)", "Espectador (transeunte)", "{傍観者|ぼうかんしゃ}", "旁观者", "pángguānzhě"),
    ("Charlatan", "🎩", "rare-nouns-3", "Charlatán", "Charlatan", "Ciarlatano", "Charlatão", "ペテン{師|し}", "江湖骗子", "jiānghú piànzi"),
    ("Connoisseur", "🍷", "rare-nouns-3", "Entendido (conocedor)", "Connaisseur", "Intenditore", "Conhecedor (entendido)", "{目利|めき}き", "行家（鉴赏家）", "hángjiā"),
    ("Culprit", "🚔", "rare-nouns-3", "Culpable", "Coupable", "Colpevole", "Culpado", "{犯人|はんにん}", "罪魁祸首", "zuìkuí huòshǒu"),
    ("Demagogue", "📢", "rare-nouns-3", "Demagogo", "Démagogue", "Demagogo", "Demagogo", "{扇動家|せんどうか}", "煽动者", "shāndòngzhě"),
    ("Dilettante", "🎨", "rare-nouns-3", "Diletante", "Dilettante", "Dilettante", "Diletante", "{道楽者|どうらくもの}", "半吊子（业余爱好者）", "bàndiàozi"),
    ("Envoy", "✉️", "rare-nouns-3", "Enviado", "Émissaire (envoyé)", "Inviato", "Enviado (emissário)", "{特使|とくし}", "特使", "tèshǐ"),
    ("Lackey", "🧍", "rare-nouns-3", "Lacayo", "Laquais (larbin)", "Lacchè", "Lacaio", "{追従者|ついしょうしゃ}", "走狗（跟班）", "zǒugǒu"),
    ("Understudy", "🎭", "rare-nouns-3", "Suplente", "Doublure", "Sostituto (rincalzo)", "Substituto (suplente)", "{代役|だいやく}", "替补演员", "tìbǔ yǎnyuán"),
    ("Hypocrite", "🎭", "rare-nouns-3", "Hipócrita", "Hypocrite", "Ipocrita", "Hipócrita", "{偽善者|ぎぜんしゃ}", "伪君子", "wěijūnzǐ"),
    ("Insurgent", "✊", "rare-nouns-3", "Insurgente", "Insurgé", "Insorto", "Insurgente", "{反乱者|はんらんしゃ}", "叛乱者", "pànluànzhě"),
    ("Layperson", "👤", "rare-nouns-3", "Lego (profano)", "Profane (non-spécialiste)", "Profano (non addetto)", "Leigo", "{素人|しろうと}", "外行", "wàiháng"),
    ("Maverick", "🐎", "rare-nouns-3", "Inconformista", "Franc-tireur (non-conformiste)", "Anticonformista", "Inconformista", "{一匹狼|いっぴきおおかみ}", "特立独行者", "tèlì dúxíng zhě"),
    ("Sidekick", "🦸", "rare-nouns-3", "Compinche (ayudante)", "Acolyte (comparse)", "Spalla (aiutante)", "Ajudante (parceiro)", "{相棒|あいぼう}（{助手|じょしゅ}）", "搭档（助手）", "dādàng"),
    ("Mercenary", "💰", "rare-nouns-3", "Mercenario", "Mercenaire", "Mercenario", "Mercenário", "{傭兵|ようへい}", "雇佣兵", "gùyōngbīng"),
    ("Novice", "🌱", "rare-nouns-3", "Novato", "Novice", "Novizio (principiante)", "Novato", "{初心者|しょしんしゃ}", "新手", "xīnshǒu"),
    ("Pariah", "🚷", "rare-nouns-3", "Paria", "Paria", "Paria", "Pária", "のけ{者|もの}", "被排斥者", "bèi páichì zhě"),
    ("Patron", "🎗️", "rare-nouns-3", "Mecenas", "Mécène", "Mecenate", "Mecenas", "{後援者|こうえんしゃ}", "赞助人", "zànzhùrén"),
    ("Perpetrator", "🔪", "rare-nouns-3", "Autor (del delito)", "Auteur (du crime)", "Autore (del reato)", "Autor (do crime)", "{加害者|かがいしゃ}", "犯罪者（作案者）", "zuò'àn zhě"),
    ("Prodigy", "🎹", "rare-nouns-3", "Prodigio", "Prodige", "Prodigio", "Prodígio", "{神童|しんどう}", "神童", "shéntóng"),
    ("Informant", "🕵️", "rare-nouns-3", "Informante (soplón)", "Indicateur (informateur)", "Informatore (confidente)", "Informante", "{情報提供者|じょうほうていきょうしゃ}", "线人", "xiànrén"),
    ("Recluse", "🏚️", "rare-nouns-3", "Ermitaño (solitario)", "Reclus (ermite)", "Recluso (eremita)", "Recluso (eremita)", "{隠遁者|いんとんしゃ}", "隐士", "yǐnshì"),
    ("Sage", "🧙", "rare-nouns-3", "Sabio", "Sage", "Saggio", "Sábio", "{賢者|けんじゃ}", "圣贤", "shèngxián"),
    ("Turncoat", "🔄", "rare-nouns-3", "Chaquetero (tránsfuga)", "Renégat (retourneur de veste)", "Voltagabbana", "Vira-casaca", "{裏切|うらぎ}り{者|もの}", "叛徒（变节者）", "pàntú"),
    ("Stalwart", "🏋️", "rare-nouns-3", "Incondicional (baluarte)", "Pilier (fidèle)", "Pilastro (sostenitore fedele)", "Baluarte (fiel)", "{忠実|ちゅうじつ}な{支持者|しじしゃ}", "中坚分子", "zhōngjiān fènzǐ"),
    ("Tycoon", "🏢", "rare-nouns-3", "Magnate", "Magnat", "Magnate", "Magnata", "{大物実業家|おおものじつぎょうか}", "大亨", "dàhēng"),
    # ---- rare nouns IV (concepts & discourse) ----
    ("Ambiguity", "❔", "rare-nouns-4", "Ambigüedad", "Ambiguïté", "Ambiguità", "Ambiguidade", "{曖昧|あいまい}さ", "模棱两可", "móléng liǎngkě"),
    ("Analogy", "🔗", "rare-nouns-4", "Analogía", "Analogie", "Analogia", "Analogia", "{類推|るいすい}", "类比", "lèibǐ"),
    ("Axiom", "📐", "rare-nouns-4", "Axioma", "Axiome", "Assioma", "Axioma", "{公理|こうり}", "公理", "gōnglǐ"),
    ("Caveat", "⚠️", "rare-nouns-4", "Salvedad (advertencia)", "Mise en garde (réserve)", "Avvertenza (riserva)", "Ressalva", "{但|ただ}し{書|が}き", "警告（但书）", "dànshū"),
    ("Consensus", "🤝", "rare-nouns-4", "Consenso", "Consensus", "Consenso", "Consenso", "{総意|そうい}", "共识", "gòngshí"),
    ("Corollary", "➡️", "rare-nouns-4", "Corolario", "Corollaire", "Corollario", "Corolário", "{必然的|ひつぜんてき}な{結果|けっか}", "必然结果（推论）", "tuīlùn"),
    ("Yardstick", "📏", "rare-nouns-4", "Vara de medir (baremo)", "Étalon (critère de mesure)", "Metro di giudizio", "Parâmetro (medida)", "{物差|ものさ}し", "衡量标准", "héngliáng biāozhǔn"),
    ("Narrative", "📖", "rare-nouns-4", "Narrativa (relato)", "Récit (narratif)", "Narrazione (narrativa)", "Narrativa", "{物語|ものがたり}（ナラティブ）", "叙事", "xùshì"),
    ("Doctrine", "📘", "rare-nouns-4", "Doctrina", "Doctrine", "Dottrina", "Doutrina", "{教義|きょうぎ}", "教义（学说）", "xuéshuō"),
    ("Dogma", "⛪", "rare-nouns-4", "Dogma", "Dogme", "Dogma", "Dogma", "{独断|どくだん}（ドグマ）", "教条", "jiàotiáo"),
    ("Epiphany", "💫", "rare-nouns-4", "Revelación (epifanía)", "Révélation (déclic)", "Rivelazione (epifania)", "Epifania (revelação)", "ひらめき（{悟|さと}り）", "顿悟", "dùnwù"),
    ("Ethos", "🏛️", "rare-nouns-4", "Ethos (espíritu)", "Éthos (esprit)", "Ethos (spirito)", "Ethos (espírito)", "{気風|きふう}", "精神特质", "jīngshén tèzhì"),
    ("Conjecture", "🤔", "rare-nouns-4", "Conjetura", "Conjecture", "Congettura", "Conjectura", "{推測|すいそく}", "推测", "tuīcè"),
    ("Idiosyncrasy", "🦄", "rare-nouns-4", "Idiosincrasia", "Idiosyncrasie (particularité)", "Idiosincrasia", "Idiossincrasia", "{特異性|とくいせい}", "个人特质（癖性）", "pǐxìng"),
    ("Deduction", "🔎", "rare-nouns-4", "Deducción", "Déduction", "Deduzione", "Dedução", "{演繹|えんえき}", "推理（演绎）", "tuīlǐ"),
    ("Innuendo", "😏", "rare-nouns-4", "Insinuación", "Insinuation (sous-entendu)", "Insinuazione", "Insinuação", "{当|あ}てこすり", "影射", "yǐngshè"),
    ("Buzzword", "📢", "rare-nouns-4", "Palabra de moda", "Mot à la mode", "Parola in voga", "Palavra da moda", "{流行語|りゅうこうご}", "流行语（时髦词）", "liúxíngyǔ"),
    ("Simile", "🟰", "rare-nouns-4", "Símil", "Comparaison (simile)", "Similitudine", "Símile", "{直喩|ちょくゆ}", "明喻", "míngyù"),
    ("Nuance", "🎚️", "rare-nouns-4", "Matiz", "Nuance", "Sfumatura", "Nuance (matiz)", "ニュアンス（{微妙|びみょう}な{違|ちが}い）", "细微差别", "xìwēi chābié"),
    ("Archetype", "🗿", "rare-nouns-4", "Arquetipo", "Archétype", "Archetipo", "Arquétipo", "{原型|げんけい}", "原型", "yuánxíng"),
    ("Platitude", "🥱", "rare-nouns-4", "Tópico (lugar común)", "Platitude (lieu commun)", "Banalità (luogo comune)", "Platitude (lugar-comum)", "{決|き}まり{文句|もんく}", "陈词滥调", "chéncí làndiào"),
    ("Postulate", "📐", "rare-nouns-4", "Postulado", "Postulat", "Postulato", "Postulado", "{公準|こうじゅん}", "公设（假定）", "gōngshè"),
    ("Pretext", "🎟️", "rare-nouns-4", "Pretexto", "Prétexte", "Pretesto", "Pretexto", "{口実|こうじつ}", "借口", "jièkǒu"),
    ("Rebuttal", "↩️", "rare-nouns-4", "Refutación (réplica)", "Réfutation (réplique)", "Confutazione (replica)", "Refutação (réplica)", "{反駁|はんばく}", "反驳", "fǎnbó"),
    ("Rhetoric", "🎙️", "rare-nouns-4", "Retórica", "Rhétorique", "Retorica", "Retórica", "{修辞|しゅうじ}（レトリック）", "修辞（花言巧语）", "xiūcí"),
    ("Semantics", "🔤", "rare-nouns-4", "Semántica", "Sémantique", "Semantica", "Semântica", "{意味論|いみろん}", "语义（咬文嚼字）", "yǔyì"),
    ("Stigma", "🏷️", "rare-nouns-4", "Estigma", "Stigmate", "Stigma", "Estigma", "{烙印|らくいん}（{汚名|おめい}）", "污名", "wūmíng"),
    ("Tenet", "📌", "rare-nouns-4", "Principio (dogma)", "Principe (précepte)", "Principio (dogma)", "Princípio (preceito)", "{信条|しんじょう}", "信条", "xìntiáo"),
    ("Trope", "🎬", "rare-nouns-4", "Tropo (cliché narrativo)", "Trope (figure convenue)", "Tropo (cliché narrativo)", "Tropo (clichê)", "お{決|き}まりの{表現|ひょうげん}", "套路（惯用手法）", "tàolù"),
    ("Zeitgeist", "🕰️", "rare-nouns-4", "Espíritu de la época", "Air du temps (Zeitgeist)", "Spirito del tempo", "Espírito da época", "{時代精神|じだいせいしん}", "时代精神", "shídài jīngshén"),
    # ---- sensory: taste, smell, texture, sound ----
    ("Acrid", "🌶️", "sensory", "Acre", "Âcre", "Acre", "Acre", "{刺|さ}すような（{辛辣|しんらつ}な）", "刺鼻的（辛辣）", "cìbí de"),
    ("Astringent", "🍋", "sensory", "Astringente", "Astringent", "Astringente", "Adstringente", "{渋|しぶ}い", "涩的", "sè de"),
    ("Bland (flavorless)", "🍚", "sensory", "Soso (insípido)", "Fade", "Insipido (scialbo)", "Insosso (sem graça)", "{味気|あじけ}ない", "淡而无味", "dàn ér wúwèi"),
    ("Brackish", "🌊", "sensory", "Salobre", "Saumâtre", "Salmastro", "Salobro", "{塩気|しおけ}のある", "微咸的", "wēi xián de"),
    ("Cloying", "🍯", "sensory", "Empalagoso", "Écœurant (sirupeux)", "Stucchevole", "Enjoativo", "{甘|あま}ったるい", "甜得发腻的", "tián dé fā nì de"),
    ("Coarse", "🪵", "sensory", "Áspero (basto)", "Grossier (rugueux)", "Grezzo (ruvido)", "Grosseiro (áspero)", "{粗|あら}い", "粗糙的", "cūcāo de"),
    ("Creamy", "🥛", "sensory", "Cremoso", "Onctueux (crémeux)", "Cremoso", "Cremoso", "クリーミーな（{滑|なめ}らかな）", "奶油般的", "nǎiyóu bān de"),
    ("Crunchy", "🥕", "sensory", "Crujiente", "Croquant", "Croccante", "Crocante", "カリカリした", "脆的", "cuì de"),
    ("Dank", "🧟", "sensory", "Húmedo (mohoso)", "Humide (moite)", "Umido (muffoso)", "Úmido (mofado)", "じめじめした", "阴湿的", "yīnshī de"),
    ("Earthy", "🌰", "sensory", "Terroso", "Terreux", "Terroso", "Terroso", "{土|つち}っぽい", "泥土味的", "nítǔ wèi de"),
    ("Fragrant", "🌸", "sensory", "Fragante", "Parfumé (odorant)", "Fragrante (profumato)", "Fragrante (perfumado)", "{香|かぐわ}しい", "芳香的", "fāngxiāng de"),
    ("Gooey", "🧀", "sensory", "Pegajoso (viscoso)", "Gluant (collant)", "Appiccicoso (colloso)", "Grudento (pegajoso)", "ねばねばした", "黏糊糊的", "nián hūhū de"),
    ("Grainy", "🏖️", "sensory", "Granuloso", "Granuleux", "Granuloso", "Granulado (arenoso)", "ざらざらした", "颗粒状的", "kēlì zhuàng de"),
    ("Unctuous", "🧈", "sensory", "Untuoso", "Onctueux (mielleux)", "Untuoso", "Untuoso", "{脂|あぶら}ぎった", "油腻的（谄媚）", "yóunì de"),
    ("Gravelly (voice)", "🪨", "sensory", "Grave y áspera (voz)", "Rocailleuse (voix)", "Roca e profonda (voce)", "Rouca e grave (voz)", "しゃがれた（{低|ひく}くざらついた）", "低沉沙哑的", "dīchén shāyǎ de"),
    ("Luscious", "🍑", "sensory", "Delicioso (suculento)", "Succulent (délicieux)", "Succulento (delizioso)", "Suculento (delicioso)", "{甘美|かんび}な", "甘美多汁的", "gānměi duōzhī de"),
    ("Mellow", "🍂", "sensory", "Suave (meloso)", "Moelleux (doux)", "Morbido (pastoso)", "Suave (macio)", "まろやかな", "醇厚的", "chúnhòu de"),
    ("Hushed", "🤫", "sensory", "Apagado (en voz baja)", "Feutré (étouffé)", "Sommesso (ovattato)", "Abafado (em voz baixa)", "ひそひそした", "低声的", "dīshēng de"),
    ("Musty", "📦", "sensory", "Rancio (a humedad)", "De renfermé (moisi)", "Di muffa (stantio)", "Mofado (bafiento)", "かび{臭|くさ}い", "霉味的", "méiwèi de"),
    ("Piercing", "🔔", "sensory", "Penetrante (agudo)", "Perçant", "Penetrante (acuto)", "Penetrante (agudo)", "{甲高|かんだか}い（{突|つ}き{刺|さ}すような）", "尖锐刺耳的", "jiānruì cì'ěr de"),
    ("Pungent", "🧄", "sensory", "Penetrante (acre)", "Piquant (âcre)", "Pungente", "Pungente (forte)", "{鼻|はな}をつく", "刺鼻的", "cìbí de"),
    ("Putrid", "🤢", "sensory", "Pútrido", "Putride", "Putrido", "Pútrido", "{腐敗|ふはい}した", "腐烂的（恶臭）", "fǔlàn de"),
    ("Rancid", "🧈", "sensory", "Rancio", "Rance", "Rancido", "Rançoso", "{酸|す}えた", "腐臭的（哈喇）", "hāla"),
    ("Bitter aftertaste", "☕", "sensory", "Regusto amargo", "Arrière-goût amer", "Retrogusto amaro", "Gosto amargo residual", "{苦|にが}い{後味|あとあじ}", "苦涩的回味", "kǔsè de huíwèi"),
    ("Grating (sound)", "🪚", "sensory", "Chirriante", "Grinçant", "Stridente", "Irritante (chiado)", "{耳障|みみざわ}りな", "刺耳的", "cì'ěr de"),
    ("Silky", "🎀", "sensory", "Sedoso", "Soyeux", "Setoso", "Sedoso", "{絹|きぬ}のような", "丝滑的", "sīhuá de"),
    ("Slimy", "🐌", "sensory", "Viscoso (baboso)", "Visqueux (gluant)", "Viscido", "Viscoso (escorregadio)", "ぬるぬるした", "黏滑的", "niánhuá de"),
    ("Soggy", "🥣", "sensory", "Empapado (blando)", "Détrempé (ramolli)", "Molle (inzuppato)", "Encharcado (mole)", "ふやけた", "湿软的", "shīruǎn de"),
    ("Tangy", "🍊", "sensory", "Ácido (con un toque fuerte)", "Acidulé", "Aspro (piccante)", "Picante (ácido)", "ピリッとした（{酸味|さんみ}のある）", "酸爽的", "suānshuǎng de"),
    ("Zesty", "🍋", "sensory", "Sabroso (con chispa)", "Relevé (piquant)", "Vivace (piccante)", "Picante (vibrante)", "{風味|ふうみ}の{利|き}いた", "风味浓郁的", "fēngwèi nóngyù de"),
]
