# -*- coding: utf-8 -*-
# C2 vocabulary batch 7 — emotion verbs, body & mind sensations, social dynamics, arts & literature
TIER = 'C2'
TOPICS = {
    'emotions-rare': 'Emotion Verbs', 'body-mind-rare': 'Body & Mind Sensations',
    'social-rare': 'Social Dynamics', 'arts-rare': 'Arts & Literature Register',
}
WORDS = [
    # ---- emotion verbs (what feelings DO) ----
    ("To seethe", "🌋", "emotions-rare", "Hervir de rabia", "Bouillir (de rage)", "Ribollire (di rabbia)", "Ferver (de raiva)", "{煮|に}えくり{返|かえ}る", "怒火中烧", "nùhuǒ zhōngshāo"),
    ("To sulk", "😾", "emotions-rare", "Enfurruñarse", "Bouder", "Tenere il broncio", "Ficar emburrado", "ふてくされる", "生闷气", "shēng mènqì"),
    ("To fret", "😟", "emotions-rare", "Inquietarse (angustiarse)", "Se tracasser", "Preoccuparsi (crucciarsi)", "Afligir-se", "やきもきする", "烦恼（焦虑）", "fánnǎo"),
    ("To brood", "🌧️", "emotions-rare", "Darle vueltas (rumiar)", "Ruminer (broyer du noir)", "Rimuginare", "Remoer", "くよくよ{考|かんが}える", "闷闷不乐地沉思", "mènmèn búlè de chénsī"),
    ("To wallow (in self-pity)", "🛁", "emotions-rare", "Regodearse (en la autocompasión)", "Se complaire (dans l’apitoiement)", "Crogiolarsi (nell’autocommiserazione)", "Chafurdar (na autopiedade)", "{自己憐憫|じこれんびん}に{浸|ひた}る", "沉溺于自怜", "chénnì yú zìlián"),
    ("To gloat over a rival", "😏", "emotions-rare", "Regodearse de un rival", "Jubiler aux dépens d’un rival", "Gongolare per un rivale", "Regozijar-se com um rival", "ライバルの{失敗|しっぱい}にほくそ{笑|え}む", "对对手幸灾乐祸", "duì duìshǒu xìngzāi lèhuò"),
    ("To savor (the moment)", "😋", "emotions-rare", "Saborear (el momento)", "Savourer (l’instant)", "Assaporare (il momento)", "Saborear (o momento)", "{味|あじ}わう", "细细品味", "xìxì pǐnwèi"),
    ("To revel in", "🥂", "emotions-rare", "Deleitarse en", "Se délecter de", "Godersi (crogiolarsi in)", "Deleitar-se com", "〜を{大|おお}いに{楽|たの}しむ", "陶醉于", "táozuì yú"),
    ("To marvel at", "🤩", "emotions-rare", "Maravillarse de", "S’émerveiller de", "Meravigliarsi di", "Maravilhar-se com", "〜に{驚嘆|きょうたん}する", "惊叹", "jīngtàn"),
    ("To cringe", "😬", "emotions-rare", "Morirse de vergüenza (encogerse)", "Grimacer (de gêne)", "Rabbrividire (per l’imbarazzo)", "Encolher-se (de vergonha)", "{身|み}がすくむ（ドン{引|び}きする）", "尴尬得畏缩", "gāngà dé wèisuō"),
    ("To wince", "😖", "emotions-rare", "Hacer una mueca de dolor", "Tressaillir (grimacer)", "Trasalire (fare una smorfia)", "Fazer uma careta (de dor)", "{顔|かお}をしかめる", "皱眉畏缩", "zhòuméi wèisuō"),
    ("To flinch", "🫨", "emotions-rare", "Estremecerse (retroceder)", "Sursauter (reculer)", "Sussultare (ritrarsi)", "Estremecer (recuar)", "ひるむ", "退缩（畏缩）", "tuìsuō"),
    ("To shudder", "🥶", "emotions-rare", "Estremecerse", "Frissonner", "Rabbrividire", "Estremecer (tremer)", "{身震|みぶる}いする", "战栗", "zhànlì"),
    ("To quiver", "🍃", "emotions-rare", "Temblar (estremecerse)", "Trembler (frémir)", "Tremare (fremere)", "Tremer (estremecer)", "{震|ふる}える", "颤抖", "chàndǒu"),
    ("To swoon", "😍", "emotions-rare", "Desmayarse (de emoción)", "Se pâmer", "Andare in estasi (svenire)", "Desmaiar (de emoção)", "うっとりする", "神魂颠倒（晕倒）", "shénhún diāndǎo"),
    ("To pine for", "🥀", "emotions-rare", "Suspirar por", "Se languir de", "Struggersi per", "Ansiar por (definhar de saudade)", "〜を{恋|こ}い{焦|こ}がれる", "苦苦思念", "kǔkǔ sīniàn"),
    ("To long for", "🌙", "emotions-rare", "Añorar (ansiar)", "Avoir la nostalgie de (aspirer à)", "Desiderare ardentemente", "Ansiar por (ter saudade de)", "{待|ま}ち{焦|こ}がれる", "渴望（思念）", "kěwàng"),
    ("To crave", "🍫", "emotions-rare", "Ansiar (tener antojo)", "Avoir très envie de", "Bramare (avere voglia di)", "Ter desejo de (ansiar)", "{無性|むしょう}に{欲|ほ}しがる", "渴求", "kěqiú"),
    ("To abominate", "🤮", "emotions-rare", "Abominar", "Abominer (exécrer)", "Aborrire (abominare)", "Abominar", "{忌|い}み{嫌|きら}う（{嫌悪|けんお}する）", "憎恶（痛恨）", "zēngwù"),
    ("To nurse a grievance", "🤕", "emotions-rare", "Alimentar un agravio", "Ruminer un grief", "Covare un rancore", "Alimentar uma mágoa", "{不満|ふまん}を{抱|いだ}き{続|つづ}ける", "怀有不满", "huáiyǒu bùmǎn"),
    ("To begrudge", "😒", "emotions-rare", "Escatimar (envidiar)", "Envier (donner à contrecœur)", "Invidiare (dare a malincuore)", "Invejar (dar de má vontade)", "{惜|お}しむ（ねたむ）", "嫉妒（吝惜）", "jídù"),
    ("To grovel", "🙇", "emotions-rare", "Humillarse (arrastrarse)", "Ramper (s’aplatir)", "Strisciare (umiliarsi)", "Rastejar (humilhar-se)", "{平身低頭|へいしんていとう}する", "卑躬屈膝", "bēigōng qūxī"),
    ("To fawn over", "🐶", "emotions-rare", "Adular", "Flatter (faire des courbettes)", "Adulare (sdilinquirsi)", "Bajular", "へつらう", "讨好", "tǎohǎo"),
    ("To dote on", "🥰", "emotions-rare", "Adorar (mimar)", "Adorer (choyer)", "Stravedere per", "Paparicar (adorar)", "{溺愛|できあい}する", "溺爱", "nì'ài"),
    ("To treasure", "💎", "emotions-rare", "Atesorar", "Chérir (tenir à)", "Tenere come un tesoro", "Guardar como um tesouro", "{宝物|たからもの}のように{大事|だいじ}にする", "珍视", "zhēnshì"),
    ("To put at ease", "😌", "emotions-rare", "Tranquilizar (poner a gusto)", "Mettre à l’aise", "Mettere a proprio agio", "Deixar à vontade", "{安心|あんしん}させる（くつろがせる）", "使放松", "shǐ fàngsōng"),
    ("To console", "🫂", "emotions-rare", "Consolar", "Consoler", "Consolare", "Consolar", "{慰|なぐさ}める", "安慰", "ānwèi"),
    ("To commiserate", "😔", "emotions-rare", "Compadecerse", "Compatir", "Commiserare (condolersi)", "Compadecer-se", "{同情|どうじょう}する", "同情（表示慰问）", "tóngqíng"),
    ("To exasperate", "😩", "emotions-rare", "Exasperar", "Exaspérer", "Esasperare", "Exasperar", "いらいらさせる", "使恼怒", "shǐ nǎonù"),
    ("To infuriate", "🤬", "emotions-rare", "Enfurecer", "Rendre furieux", "Far infuriare", "Enfurecer", "{激怒|げきど}させる", "激怒", "jīnù"),
    ("To unnerve", "😰", "emotions-rare", "Desconcertar (poner nervioso)", "Déstabiliser (troubler)", "Innervosire (turbare)", "Desconcertar (perturbar)", "{動揺|どうよう}させる", "使不安", "shǐ bù'ān"),
    ("To mortify", "😳", "emotions-rare", "Mortificar (avergonzar)", "Mortifier", "Mortificare", "Mortificar", "{恥|は}じ{入|い}らせる", "使羞愧", "shǐ xiūkuì"),
    ("To captivate", "🔮", "emotions-rare", "Cautivar", "Captiver", "Affascinare (incantare)", "Cativar (fascinar)", "{魅了|みりょう}する", "迷住", "mí zhù"),
    ("To enrapture", "🌠", "emotions-rare", "Extasiar", "Ravir (transporter)", "Estasiare", "Extasiar", "{有頂天|うちょうてん}にさせる", "使狂喜", "shǐ kuángxǐ"),
    ("To disillusion", "💔", "emotions-rare", "Desilusionar", "Désillusionner", "Disilludere", "Desiludir", "{幻滅|げんめつ}させる", "使幻灭", "shǐ huànmiè"),
    ("To mollify", "🕊️", "emotions-rare", "Apaciguar (calmar)", "Amadouer (calmer)", "Rabbonire", "Amansar (acalmar)", "{機嫌|きげん}を{取|と}る", "安抚（平息怒气）", "ānfǔ"),
    ("To embolden", "🦁", "emotions-rare", "Envalentonar", "Enhardir", "Incoraggiare (rendere audace)", "Encorajar (dar ousadia)", "{勇気|ゆうき}づける", "壮胆", "zhuàngdǎn"),
    ("To dishearten", "😞", "emotions-rare", "Desanimar (descorazonar)", "Décourager", "Scoraggiare", "Desanimar", "{落胆|らくたん}させる", "使气馁", "shǐ qìněi"),
    ("To rankle", "🐝", "emotions-rare", "Escocer (doler)", "Rester en travers de la gorge", "Bruciare (rodere)", "Doer (ficar entalado)", "しこりとして{残|のこ}る", "耿耿于怀", "gěnggěng yú huái"),
    ("To smolder", "🔥", "emotions-rare", "Arder (por dentro)", "Couver (bouillir intérieurement)", "Covare (ardere sotto la cenere)", "Arder (por dentro)", "くすぶる", "郁积（闷烧）", "yùjī"),
    # ---- body & mind sensations ----
    ("Numbness", "🧊", "body-mind-rare", "Entumecimiento", "Engourdissement", "Intorpidimento", "Dormência", "しびれ", "麻木", "mámù"),
    ("Tingling", "✨", "body-mind-rare", "Hormigueo", "Picotement (fourmillement)", "Formicolio", "Formigamento", "ちくちく（ぴりぴり）する{感|かん}じ", "刺痛感", "cìtònggǎn"),
    ("Cramp", "🦵", "body-mind-rare", "Calambre", "Crampe", "Crampo", "Cãibra", "こむら{返|がえ}り", "抽筋", "chōujīn"),
    ("Twinge", "⚡", "body-mind-rare", "Punzada", "Élancement", "Fitta", "Pontada", "{一瞬|いっしゅん}の{痛|いた}み", "一阵刺痛", "yí zhèn cìtòng"),
    ("Throbbing", "💓", "body-mind-rare", "Palpitante (punzante)", "Lancinant (pulsatile)", "Pulsante (martellante)", "Latejante", "ずきずきする", "跳痛（抽痛）", "tiàotòng"),
    ("Dizziness", "😵‍💫", "body-mind-rare", "Mareo", "Vertige (étourdissement)", "Capogiro (vertigine)", "Tontura", "めまい", "头晕", "tóuyūn"),
    ("Lightheaded", "🎈", "body-mind-rare", "Aturdido (mareado)", "Étourdi (tête qui tourne)", "Stordito", "Zonzo (com a cabeça leve)", "{頭|あたま}がふらふらする", "头昏眼花的", "tóuhūn yǎnhuā de"),
    ("Vertigo", "🌀", "body-mind-rare", "Vértigo", "Vertige", "Vertigine", "Vertigem", "{眩暈|げんうん}（{回転性|かいてんせい}めまい）", "眩晕", "xuànyūn"),
    ("Queasy", "🤮", "body-mind-rare", "Mareado (con náuseas)", "Nauséeux (barbouillé)", "Nauseato", "Enjoado", "むかむかする", "反胃的", "fǎnwèi de"),
    ("Lethargy", "🐌", "body-mind-rare", "Letargo (apatía)", "Léthargie", "Letargia", "Letargia", "{無気力|むきりょく}", "嗜睡（无精打采）", "shìshuì"),
    ("Fatigue", "😩", "body-mind-rare", "Fatiga", "Fatigue (épuisement)", "Fatica (spossatezza)", "Fadiga", "{疲労|ひろう}", "疲劳", "píláo"),
    ("Stamina", "🏃", "body-mind-rare", "Resistencia (aguante)", "Endurance", "Resistenza", "Resistência (fôlego)", "スタミナ（{持久力|じきゅうりょく}）", "耐力", "nàilì"),
    ("Reflex", "🦵", "body-mind-rare", "Reflejo", "Réflexe", "Riflesso", "Reflexo", "{反射|はんしゃ}", "反射", "fǎnshè"),
    ("Flinch (noun)", "😨", "body-mind-rare", "Sobresalto", "Sursaut (mouvement de recul)", "Sussulto", "Sobressalto", "ひるみ", "退缩（畏缩）", "tuìsuō"),
    ("Pins and needles", "📌", "body-mind-rare", "Hormigueo (calambre)", "Fourmis (dans les jambes)", "Formicolio (formiche)", "Formigamento (agulhadas)", "しびれ（ちくちく{感|かん}）", "发麻（针刺感）", "fāmá"),
    ("Shiver", "🥶", "body-mind-rare", "Escalofrío", "Frisson", "Brivido", "Calafrio", "{悪寒|おかん}（{震|ふる}え）", "寒颤", "hánzhàn"),
    ("Hot flush", "🥵", "body-mind-rare", "Sofoco", "Bouffée de chaleur", "Vampata di calore", "Fogacho (calorão)", "ほてり", "潮热", "cháorè"),
    ("Blush", "😊", "body-mind-rare", "Rubor", "Rougissement", "Rossore", "Rubor", "{赤面|せきめん}", "脸红", "liǎnhóng"),
    ("Yawn", "🥱", "body-mind-rare", "Bostezo", "Bâillement", "Sbadiglio", "Bocejo", "あくび", "打哈欠", "dǎ hāqian"),
    ("Hiccup", "🫧", "body-mind-rare", "Hipo", "Hoquet", "Singhiozzo", "Soluço", "しゃっくり", "打嗝", "dǎgé"),
    ("Sneeze", "🤧", "body-mind-rare", "Estornudo", "Éternuement", "Starnuto", "Espirro", "くしゃみ", "打喷嚏", "dǎ pēntì"),
    ("Itch", "🪳", "body-mind-rare", "Picor (picazón)", "Démangeaison", "Prurito", "Coceira", "かゆみ", "痒", "yǎng"),
    ("Bruise", "🟣", "body-mind-rare", "Moretón (hematoma)", "Bleu (ecchymose)", "Livido", "Hematoma (roxo)", "{打|う}ち{身|み}（あざ）", "瘀伤", "yūshāng"),
    ("Blister", "🩹", "body-mind-rare", "Ampolla", "Ampoule (cloque)", "Vescica (bolla)", "Bolha", "{水膨|みずぶく}れ", "水泡", "shuǐpào"),
    ("Pulled muscle", "🦵", "body-mind-rare", "Tirón muscular", "Claquage (élongation)", "Stiramento", "Distensão muscular", "{肉離|にくばな}れ", "肌肉拉伤", "jīròu lāshāng"),
    ("Stiffness", "🧱", "body-mind-rare", "Rigidez (agujetas)", "Raideur", "Rigidità (indolenzimento)", "Rigidez", "こわばり", "僵硬", "jiāngyìng"),
    ("Restlessness", "🌀", "body-mind-rare", "Inquietud (desasosiego)", "Agitation (nervosité)", "Irrequietezza", "Inquietação", "{落|お}ち{着|つ}きのなさ", "坐立不安", "zuòlì bù'ān"),
    ("Daydream", "☁️", "body-mind-rare", "Ensoñación", "Rêverie", "Fantasticheria", "Devaneio", "{白昼夢|はくちゅうむ}", "白日梦", "báirìmèng"),
    ("Déjà vu", "🔁", "body-mind-rare", "Déjà vu", "Déjà-vu", "Déjà vu", "Déjà-vu", "{既視感|きしかん}", "似曾相识", "sìcéng xiāngshí"),
    ("Hunch", "🤔", "body-mind-rare", "Corazonada", "Intuition (pressentiment)", "Presentimento (intuizione)", "Palpite (pressentimento)", "{直感|ちょっかん}（{勘|かん}）", "预感", "yùgǎn"),
    ("Gut feeling", "🫃", "body-mind-rare", "Instinto (intuición visceral)", "Instinct (sentiment viscéral)", "Istinto (sensazione di pancia)", "Intuição (sexto sentido)", "{直感|ちょっかん}", "直觉", "zhíjué"),
    ("Brain fog", "🌫️", "body-mind-rare", "Niebla mental", "Brouillard mental", "Nebbia mentale", "Névoa mental", "{頭|あたま}がぼんやりすること", "脑雾", "nǎowù"),
    ("Second wind", "💨", "body-mind-rare", "Segundo aire", "Second souffle", "Secondo fiato", "Segundo fôlego", "{元気|げんき}の{回復|かいふく}", "重振精神", "chóngzhèn jīngshén"),
    ("Adrenaline rush", "🎢", "body-mind-rare", "Subidón de adrenalina", "Montée d’adrénaline", "Scarica di adrenalina", "Descarga de adrenalina", "アドレナリンの{放出|ほうしゅつ}", "肾上腺素飙升", "shènshàngxiànsù biāoshēng"),
    ("Motion sickness", "🚗", "body-mind-rare", "Mareo (cinetosis)", "Mal des transports", "Mal d’auto (cinetosi)", "Enjoo (de movimento)", "{乗|の}り{物酔|ものよ}い", "晕车（晕动症）", "yùnchē"),
    # ---- social dynamics ----
    ("Camaraderie", "🍻", "social-rare", "Camaradería", "Camaraderie", "Cameratismo", "Camaradagem", "{仲間意識|なかまいしき}", "同志情谊", "tóngzhì qíngyì"),
    ("Affinity (between people)", "🧲", "social-rare", "Afinidad", "Affinité", "Affinità", "Afinidade", "{親近感|しんきんかん}", "亲和力（投缘）", "tóuyuán"),
    ("Clique", "👯", "social-rare", "Camarilla (grupito)", "Clique (bande)", "Cricca (combriccola)", "Panelinha", "{派閥|はばつ}（{仲良|なかよ}しグループ）", "小圈子", "xiǎo quānzi"),
    ("Entourage", "🚶‍♂️🚶‍♀️", "social-rare", "Séquito", "Entourage", "Entourage (seguito)", "Comitiva (séquito)", "{取|と}り{巻|ま}き", "随行人员", "suíxíng rényuán"),
    ("Etiquette", "🎩", "social-rare", "Etiqueta (protocolo)", "Étiquette (bienséance)", "Etichetta (galateo)", "Etiqueta", "エチケット（{礼儀作法|れいぎさほう}）", "礼仪", "lǐyí"),
    ("Faux pas", "🙈", "social-rare", "Metedura de pata", "Faux pas (impair)", "Gaffe", "Gafe", "{失態|しったい}", "失礼（失态）", "shīlǐ"),
    ("Gossip", "🗣️", "social-rare", "Chisme (cotilleo)", "Ragots (commérages)", "Pettegolezzo", "Fofoca", "{噂話|うわさばなし}", "八卦", "bāguà"),
    ("Grudge", "😠", "social-rare", "Rencor", "Rancune", "Rancore", "Rancor", "{恨|うら}み", "积怨", "jīyuàn"),
    ("Chain of command", "⛓️", "social-rare", "Cadena de mando", "Chaîne de commandement", "Catena di comando", "Cadeia de comando", "{指揮系統|しきけいとう}", "指挥链", "zhǐhuīliàn"),
    ("Nepotism", "👨‍👦", "social-rare", "Nepotismo (enchufismo)", "Népotisme (piston)", "Nepotismo", "Nepotismo", "{縁故主義|えんこしゅぎ}", "裙带关系", "qúndài guānxi"),
    ("Ostracism", "🚷", "social-rare", "Ostracismo", "Ostracisme", "Ostracismo", "Ostracismo", "{村八分|むらはちぶ}", "排斥", "páichì"),
    ("Groupthink", "🧠", "social-rare", "Pensamiento de grupo", "Pensée de groupe", "Pensiero di gruppo", "Pensamento de grupo", "{集団浅慮|しゅうだんせんりょ}", "群体思维", "qúntǐ sīwéi"),
    ("Pecking order", "🐔", "social-rare", "Orden jerárquico", "Ordre hiérarchique", "Ordine gerarchico", "Ordem hierárquica", "{序列|じょれつ}", "啄食顺序（等级）", "zhuóshí shùnxù"),
    ("Rivalry", "⚔️", "social-rare", "Rivalidad", "Rivalité", "Rivalità", "Rivalidade", "{対抗意識|たいこういしき}", "竞争（对立）", "jìngzhēng"),
    ("Solidarity", "✊", "social-rare", "Solidaridad", "Solidarité", "Solidarietà", "Solidariedade", "{連帯|れんたい}", "团结", "tuánjié"),
    ("Snub", "🙅", "social-rare", "Desaire", "Rebuffade (camouflet)", "Sgarbo (snobbata)", "Desfeita (esnobada)", "{冷遇|れいぐう}", "冷落", "lěngluò"),
    ("Taboo", "🚫", "social-rare", "Tabú", "Tabou", "Tabù", "Tabu", "タブー", "禁忌", "jìnjì"),
    ("Flattery", "🍯", "social-rare", "Adulación", "Flatterie", "Adulazione", "Bajulação", "お{世辞|せじ}", "奉承", "fèngcheng"),
    ("Backhanded compliment", "🔪", "social-rare", "Cumplido envenenado", "Compliment à double tranchant", "Complimento a doppio taglio", "Elogio dúbio", "{嫌味|いやみ}な{褒|ほ}め{言葉|ことば}", "明褒暗贬", "míng bāo àn biǎn"),
    ("Cold shoulder", "🧊", "social-rare", "Desplante (indiferencia)", "Froideur (bouder quelqu’un)", "Trattamento freddo", "Frieza (esnobar)", "{冷|つめ}たい{態度|たいど}", "冷淡对待", "lěngdàn duìdài"),
    ("Small circle (inner circle)", "🔵", "social-rare", "Círculo íntimo", "Cercle intime (premier cercle)", "Cerchia ristretta", "Círculo íntimo", "{側近|そっきん}", "核心圈子", "héxīn quānzi"),
    ("Interloper", "🚪", "social-rare", "Intruso", "Intrus", "Intruso", "Intruso", "{闖入者|ちんにゅうしゃ}", "闯入者", "chuǎngrùzhě"),
    ("Old hand", "🧓", "social-rare", "Veterano (experto)", "Vieux routier", "Veterano (esperto)", "Veterano (velho de guerra)", "ベテラン（{古株|ふるかぶ}）", "老手", "lǎoshǒu"),
    ("Wingman", "🕊️", "social-rare", "Compinche (apoyo)", "Acolyte (compère)", "Spalla", "Parceiro (escudeiro)", "{相棒|あいぼう}", "僚机（助攻者）", "zhùgōngzhě"),
    ("Freeloader", "🧲", "social-rare", "Gorrón", "Parasite (pique-assiette)", "Scroccone", "Folgado (aproveitador)", "たかり{屋|や}", "蹭吃蹭喝的人", "cèngchī cènghē de rén"),
    ("Busybody", "👀", "social-rare", "Entrometido", "Fouineur (mêle-tout)", "Ficcanaso", "Intrometido (xereta)", "おせっかい", "爱管闲事的人", "ài guǎn xiánshì de rén"),
    ("Killjoy", "🎈", "social-rare", "Aguafiestas", "Rabat-joie", "Guastafeste", "Estraga-prazeres", "{興|きょう}ざめさせる{人|ひと}", "扫兴的人", "sǎoxìng de rén"),
    ("Show-off", "🦚", "social-rare", "Fanfarrón (presumido)", "Frimeur (m’as-tu-vu)", "Sbruffone (esibizionista)", "Exibido", "{見栄|みえ}っ{張|ぱ}り", "爱炫耀的人", "ài xuànyào de rén"),
    ("Pushover", "🪶", "social-rare", "Blando (pusilánime)", "Poire (bonne pâte)", "Persona che si fa mettere i piedi in testa", "Molenga (bobo)", "{押|お}しに{弱|よわ}い{人|ひと}", "软柿子", "ruǎn shìzi"),
    ("Self-starter", "🚀", "social-rare", "Persona con iniciativa", "Personne autonome (qui a de l’initiative)", "Persona intraprendente (autonoma)", "Pessoa proativa (com iniciativa)", "{自発的|じはつてき}に{動|うご}く{人|ひと}", "主动性强的人", "zhǔdòngxìng qiáng de rén"),
    ("To mingle", "🥂", "social-rare", "Mezclarse (socializar)", "Se mêler (aux invités)", "Socializzare (mescolarsi)", "Circular (socializar)", "{歓談|かんだん}する", "交际（混在一起）", "jiāojì"),
    ("To schmooze", "🍸", "social-rare", "Hacer la pelota (socializar por interés)", "Faire de la lèche (réseauter)", "Fare pubbliche relazioni (chiacchierare per interesse)", "Puxar papo por interesse", "{取|と}り{入|い}る", "拉关系（套近乎）", "lā guānxi"),
    ("To shun", "🚫", "social-rare", "Rehuir (evitar)", "Fuir (éviter)", "Evitare (sfuggire)", "Evitar (fugir de)", "{避|さ}ける（{遠|とお}ざける）", "回避（躲开）", "huíbì"),
    ("To patronize", "🙄", "social-rare", "Tratar con condescendencia", "Prendre de haut", "Trattare con condiscendenza", "Tratar com condescendência", "{見下|みくだ}す", "以居高临下的态度对待", "yǐ jūgāo línxià de tàidù duìdài"),
    ("To reconcile", "🤝", "social-rare", "Reconciliarse", "Se réconcilier", "Riconciliarsi", "Reconciliar-se", "{仲直|なかなお}りする", "和解", "héjiě"),
    ("To estrange", "💔", "social-rare", "Distanciar (enajenar)", "Éloigner (brouiller)", "Allontanare (estraniare)", "Afastar (distanciar)", "{疎遠|そえん}にする", "使疏远", "shǐ shūyuǎn"),
    ("To confide in", "🤫", "social-rare", "Confiarse a", "Se confier à", "Confidarsi con", "Confiar em (abrir-se com)", "〜に{打|う}ち{明|あ}ける", "向…吐露心事", "xiàng… tǔlù xīnshì"),
    ("To hobnob", "🎩", "social-rare", "Codearse", "Frayer avec (fréquenter)", "Frequentare (i pezzi grossi)", "Conviver (com gente importante)", "{親|した}しく{交|まじ}わる", "亲密交往（攀附）", "qīnmì jiāowǎng"),
    ("To rub shoulders with", "🤵", "social-rare", "Codearse con", "Côtoyer", "Sfregare i gomiti con", "Cruzar com (conviver com)", "〜と{付|つ}き{合|あ}う", "与…交往", "yǔ… jiāowǎng"),
    ("To fall out with", "💥", "social-rare", "Pelearse con", "Se brouiller avec", "Litigare con (rompere con)", "Brigar com (romper com)", "〜と{仲違|なかたが}いする", "与…闹翻", "yǔ… nàofān"),
    # ---- arts & literature register ----
    ("Foil (character)", "🪞", "arts-rare", "Contrapunto (personaje)", "Faire-valoir", "Spalla (contraltare)", "Contraponto (personagem)", "{引|ひ}き{立|た}て{役|やく}", "陪衬人物", "péichèn rénwù"),
    ("Anti-hero", "🦹", "arts-rare", "Antihéroe", "Anti-héros", "Antieroe", "Anti-herói", "アンチヒーロー", "反英雄", "fǎn yīngxióng"),
    ("Narrator", "🎙️", "arts-rare", "Narrador", "Narrateur", "Narratore", "Narrador", "{語|かた}り{手|て}", "叙述者", "xùshùzhě"),
    ("MacGuffin", "🧳", "arts-rare", "MacGuffin (excusa argumental)", "MacGuffin", "MacGuffin", "MacGuffin", "マクガフィン", "麦高芬", "màigāofēn"),
    ("Red herring", "🐟", "arts-rare", "Pista falsa", "Fausse piste", "Falsa pista", "Pista falsa", "{偽|にせ}の{手|て}がかり", "转移注意力的线索", "zhuǎnyí zhùyìlì de xiànsuǒ"),
    ("Motif", "🔁", "arts-rare", "Motivo (leitmotiv)", "Motif (leitmotiv)", "Motivo (leitmotiv)", "Motivo (leitmotiv)", "モチーフ", "母题", "mǔtí"),
    ("Frame narrative", "🖼️", "arts-rare", "Relato enmarcado", "Récit-cadre", "Racconto cornice", "Narrativa moldura", "{枠物語|わくものがたり}", "框架叙事", "kuàngjià xùshì"),
    ("Denouement", "🎀", "arts-rare", "Desenlace", "Dénouement", "Scioglimento (epilogo)", "Desfecho", "{大団円|だいだんえん}", "结局", "jiéjú"),
    ("Satire", "🎭", "arts-rare", "Sátira", "Satire", "Satira", "Sátira", "{風刺|ふうし}", "讽刺作品", "fěngcì zuòpǐn"),
    ("Parody", "🤡", "arts-rare", "Parodia", "Parodie", "Parodia", "Paródia", "パロディ", "戏仿", "xìfǎng"),
    ("Allegory", "🗝️", "arts-rare", "Alegoría", "Allégorie", "Allegoria", "Alegoria", "{寓話|ぐうわ}", "寓言", "yùyán"),
    ("Memoir", "📓", "arts-rare", "Memorias", "Mémoires", "Memorie", "Memórias", "{回顧録|かいころく}", "回忆录", "huíyìlù"),
    ("Anthology", "📚", "arts-rare", "Antología", "Anthologie", "Antologia", "Antologia", "{選集|せんしゅう}", "选集", "xuǎnjí"),
    ("Manuscript", "📜", "arts-rare", "Manuscrito", "Manuscrit", "Manoscritto", "Manuscrito", "{原稿|げんこう}", "手稿", "shǒugǎo"),
    ("Prose", "📝", "arts-rare", "Prosa", "Prose", "Prosa", "Prosa", "{散文|さんぶん}", "散文", "sǎnwén"),
    ("Couplet", "✌️", "arts-rare", "Pareado", "Distique", "Distico", "Dístico", "{二行連|にぎょうれん}", "对句", "duìjù"),
    ("Stanza", "📐", "arts-rare", "Estrofa", "Strophe", "Strofa", "Estrofe", "{連|れん}（スタンザ）", "诗节", "shījié"),
    ("Sonnet", "💌", "arts-rare", "Soneto", "Sonnet", "Sonetto", "Soneto", "ソネット", "十四行诗", "shísì háng shī"),
    ("Alliteration", "🅰️", "arts-rare", "Aliteración", "Allitération", "Allitterazione", "Aliteração", "{頭韻|とういん}", "头韵", "tóuyùn"),
    ("Meter (poetry)", "🥁", "arts-rare", "Métrica", "Mètre (métrique)", "Metro (metrica)", "Métrica", "{韻律|いんりつ}", "格律", "gélǜ"),
    ("Aesthetic", "🎨", "arts-rare", "Estética", "Esthétique", "Estetica", "Estética", "{美学|びがく}", "美学（审美）", "shěnměi"),
    ("Avant-garde", "🚀", "arts-rare", "Vanguardia", "Avant-garde", "Avanguardia", "Vanguarda", "{前衛|ぜんえい}", "先锋派", "xiānfēngpài"),
    ("Baroque", "👑", "arts-rare", "Barroco", "Baroque", "Barocco", "Barroco", "バロック", "巴洛克", "bāluòkè"),
    ("Impressionism", "🖌️", "arts-rare", "Impresionismo", "Impressionnisme", "Impressionismo", "Impressionismo", "{印象派|いんしょうは}", "印象派", "yìnxiàngpài"),
    ("Surrealism", "🫠", "arts-rare", "Surrealismo", "Surréalisme", "Surrealismo", "Surrealismo", "シュルレアリスム", "超现实主义", "chāoxiànshí zhǔyì"),
    ("Still life", "🍎", "arts-rare", "Bodegón (naturaleza muerta)", "Nature morte", "Natura morta", "Natureza-morta", "{静物画|せいぶつが}", "静物画", "jìngwùhuà"),
    ("Charcoal drawing", "🖤", "arts-rare", "Dibujo al carboncillo", "Fusain", "Disegno a carboncino", "Desenho a carvão", "{木炭画|もくたんが}", "炭笔画", "tànbǐhuà"),
    ("Etching", "🪞", "arts-rare", "Aguafuerte (grabado)", "Eau-forte (gravure)", "Acquaforte (incisione)", "Água-forte (gravura)", "エッチング（{腐食銅版画|ふしょくどうばんが}）", "蚀刻版画", "shíkè bǎnhuà"),
    ("Bust (sculpture)", "🗿", "arts-rare", "Busto", "Buste", "Busto", "Busto", "{胸像|きょうぞう}", "半身像", "bànshēnxiàng"),
    ("Chisel", "🔨", "arts-rare", "Cincel", "Ciseau (burin)", "Scalpello", "Cinzel", "のみ", "凿子", "záozi"),
    ("Easel", "🖼️", "arts-rare", "Caballete", "Chevalet", "Cavalletto", "Cavalete", "イーゼル", "画架", "huàjià"),
    ("Palette", "🎨", "arts-rare", "Paleta", "Palette", "Tavolozza", "Paleta", "パレット", "调色板", "tiáosèbǎn"),
    ("Overture", "🎻", "arts-rare", "Obertura", "Ouverture", "Ouverture", "Abertura", "{序曲|じょきょく}", "序曲", "xùqǔ"),
    ("Aria", "🎤", "arts-rare", "Aria", "Aria (air)", "Aria", "Ária", "アリア", "咏叹调", "yǒngtàndiào"),
    ("Encore", "👏", "arts-rare", "Bis", "Rappel (bis)", "Bis", "Bis", "アンコール", "安可（再来一个）", "ānkě"),
]
