# -*- coding: utf-8 -*-
# C1 vocabulary batch 5 — finance, language & migration, technology III; plus the C1 skill layer:
# media sentences (build + subtitle-listening), extra idioms, listening modules
TIER = 'C1'
TOPICS = {
    'finance': 'Finance & Accounting', 'language-migration': 'Language & Migration', 'technology-3': 'Technology III',
    'build-media-lines': 'Lines from the News & Screen', 'idiom-media': 'Idioms You Hear on Screen',
    'listen-c1-media': 'Listening: Media with Subtitles', 'listen-c1-words': 'Listening: Advanced Vocabulary',
}
WORDS = [
    # ---- finance & accounting ----
    ("Asset", "🏦", "finance", "Activo", "Actif", "Attivo (bene)", "Ativo", "{資産|しさん}", "资产", "zīchǎn"),
    ("Liability (finance)", "📉", "finance", "Pasivo", "Passif", "Passività", "Passivo", "{負債|ふさい}", "负债", "fùzhài"),
    ("Equity", "📊", "finance", "Capital (patrimonio)", "Capitaux propres", "Patrimonio netto", "Patrimônio líquido", "{株主資本|かぶぬししほん}", "股权", "gǔquán"),
    ("Portfolio", "💼", "finance", "Cartera (inversiones)", "Portefeuille", "Portafoglio", "Carteira (investimentos)", "ポートフォリオ", "投资组合", "tóuzī zǔhé"),
    ("Dividend", "💵", "finance", "Dividendo", "Dividende", "Dividendo", "Dividendo", "{配当|はいとう}", "股息", "gǔxī"),
    ("Bond (finance)", "📜", "finance", "Bono", "Obligation", "Obbligazione", "Título (obrigação)", "{債券|さいけん}", "债券", "zhàiquàn"),
    ("Hedge", "🛡️", "finance", "Cobertura (financiera)", "Couverture", "Copertura", "Proteção (hedge)", "ヘッジ", "对冲", "duìchōng"),
    ("Liquidity", "💧", "finance", "Liquidez", "Liquidité", "Liquidità", "Liquidez", "{流動性|りゅうどうせい}", "流动性", "liúdòngxìng"),
    ("Collateral", "🏠", "finance", "Garantía (aval)", "Garantie (nantissement)", "Garanzia (collaterale)", "Garantia (colateral)", "{担保|たんぽ}", "抵押品", "dǐyāpǐn"),
    ("Default (loan)", "⚠️", "finance", "Impago", "Défaut de paiement", "Insolvenza", "Inadimplência", "{債務不履行|さいむふりこう}", "违约", "wéiyuē"),
    ("Foreclosure", "🔒", "finance", "Ejecución hipotecaria", "Saisie", "Pignoramento", "Execução hipotecária", "{差|さ}し{押|お}さえ", "止赎", "zhǐshú"),
    ("Appreciation (value)", "📈", "finance", "Revalorización", "Plus-value", "Rivalutazione", "Valorização", "{値上|ねあ}がり", "增值", "zēngzhí"),
    ("Depreciation", "📉", "finance", "Depreciación", "Dépréciation", "Ammortamento", "Depreciação", "{減価償却|げんかしょうきゃく}", "折旧", "zhéjiù"),
    ("Capital gains", "💹", "finance", "Ganancias de capital", "Plus-values", "Plusvalenze", "Ganhos de capital", "キャピタルゲイン", "资本利得", "zīběn lìdé"),
    ("Write-off", "🗑️", "finance", "Cancelación (deducción)", "Amortissement (radiation)", "Svalutazione (cancellazione)", "Baixa (dedução)", "{償却|しょうきゃく}", "核销", "héxiāo"),
    ("Overhead", "🏢", "finance", "Gastos generales", "Frais généraux", "Spese generali", "Despesas gerais", "{間接費|かんせつひ}", "管理费用", "guǎnlǐ fèiyòng"),
    ("Payroll", "💰", "finance", "Nómina", "Paie (masse salariale)", "Libro paga", "Folha de pagamento", "{給与|きゅうよ}{支払|しはらい}", "工资单", "gōngzīdān"),
    ("Gross (before deductions)", "📊", "finance", "Bruto", "Brut", "Lordo", "Bruto", "{総額|そうがく}の", "毛（总额）", "máo"),
    ("Net", "💵", "finance", "Neto", "Net", "Netto", "Líquido", "{正味|しょうみ}の", "净（净额）", "jìng"),
    ("Deductible", "🧾", "finance", "Deducible", "Déductible", "Deducibile", "Dedutível", "{控除|こうじょ}できる", "可抵扣的", "kě dǐkòu de"),
    ("Exemption", "🚫", "finance", "Exención", "Exonération", "Esenzione", "Isenção", "{免除|めんじょ}", "豁免", "huòmiǎn"),
    ("Audit", "🔍", "finance", "Auditoría", "Audit", "Revisione contabile", "Auditoria", "{監査|かんさ}", "审计", "shěnjì"),
    ("Ledger", "📒", "finance", "Libro mayor", "Grand livre", "Libro mastro", "Razão (livro)", "{元帳|もとちょう}", "总账", "zǒngzhàng"),
    ("Bookkeeping", "📚", "finance", "Contabilidad (teneduría)", "Comptabilité (tenue des livres)", "Contabilità (tenuta dei libri)", "Escrituração", "{帳簿|ちょうぼ}づけ", "记账", "jìzhàng"),
    ("Break-even", "⚖️", "finance", "Punto de equilibrio", "Seuil de rentabilité", "Punto di pareggio", "Ponto de equilíbrio", "{損益分岐点|そんえきぶんきてん}", "盈亏平衡", "yíngkuī pínghéng"),
    ("Turnover", "🔄", "finance", "Facturación (volumen)", "Chiffre d’affaires (roulement)", "Giro d’affari", "Faturamento", "{売上高|うりあげだか}", "营业额", "yíngyè'é"),
    ("Markup", "🏷️", "finance", "Margen (recargo)", "Marge (majoration)", "Ricarico", "Margem (acréscimo)", "{上乗|うわの}せ", "加价", "jiājià"),
    ("Cash reserve", "🏦", "finance", "Reserva de efectivo", "Réserve de trésorerie", "Riserva di liquidità", "Reserva de caixa", "{現金準備|げんきんじゅんび}", "现金储备", "xiànjīn chǔbèi"),
    ("Venture capital", "🚀", "finance", "Capital de riesgo", "Capital-risque", "Capitale di rischio", "Capital de risco", "ベンチャーキャピタル", "风险投资", "fēngxiǎn tóuzī"),
    ("Fiscal year", "📅", "finance", "Año fiscal", "Exercice fiscal", "Anno fiscale", "Ano fiscal", "{会計年度|かいけいねんど}", "财政年度", "cáizhèng niándù"),

    # ---- language & migration ----
    ("Expedition", "🧭", "language-migration", "Expedición", "Expédition", "Spedizione", "Expedição", "{遠征|えんせい}", "远征", "yuǎnzhēng"),
    ("Pilgrimage", "🛐", "language-migration", "Peregrinación", "Pèlerinage", "Pellegrinaggio", "Peregrinação", "{巡礼|じゅんれい}", "朝圣", "cháoshèng"),
    ("Getaway", "🏝️", "language-migration", "Escapada", "Escapade", "Fuga (vacanza breve)", "Escapada", "{小旅行|しょうりょこう}", "短途度假", "duǎntú dùjià"),
    ("Sabbatical", "📚", "language-migration", "Año sabático", "Congé sabbatique", "Anno sabbatico", "Ano sabático", "サバティカル", "学术休假", "xuéshù xiūjià"),
    ("Nomad", "🐪", "language-migration", "Nómada", "Nomade", "Nomade", "Nômade", "{遊牧民|ゆうぼくみん}", "游牧者", "yóumùzhě"),
    ("Expatriate", "🌍", "language-migration", "Expatriado", "Expatrié", "Espatriato", "Expatriado", "{海外駐在員|かいがいちゅうざいいん}", "外派人员", "wàipài rényuán"),
    ("Immigrant", "🛬", "language-migration", "Inmigrante", "Immigré", "Immigrato", "Imigrante", "{移民|いみん}（{入|はい}ってくる）", "移民（移入）", "yímín"),
    ("To relocate", "🚚", "language-migration", "Trasladarse", "Déménager (s’installer ailleurs)", "Trasferirsi (altrove)", "Mudar-se (realocar)", "{移転|いてん}する", "搬迁", "bānqiān"),
    ("To settle down", "🏡", "language-migration", "Establecerse", "S’installer", "Sistemarsi", "Estabelecer-se", "{落|お}ち{着|つ}く（{定住|ていじゅう}）", "安顿下来", "āndùn xiàlái"),
    ("Culture shock", "😵", "language-migration", "Choque cultural", "Choc culturel", "Shock culturale", "Choque cultural", "カルチャーショック", "文化冲击", "wénhuà chōngjī"),
    ("To assimilate", "🔄", "language-migration", "Asimilarse", "S’assimiler", "Assimilarsi", "Assimilar-se", "{同化|どうか}する", "同化", "tónghuà"),
    ("Bilingual", "🗣️", "language-migration", "Bilingüe", "Bilingue", "Bilingue", "Bilíngue", "バイリンガル", "双语的", "shuāngyǔ de"),
    ("Multilingual", "🌐", "language-migration", "Multilingüe", "Multilingue", "Multilingue", "Multilíngue", "マルチリンガル", "多语的", "duōyǔ de"),
    ("Mother tongue", "👶", "language-migration", "Lengua materna", "Langue maternelle", "Madrelingua", "Língua materna", "{母語|ぼご}", "母语", "mǔyǔ"),
    ("Dialect", "🗺️", "language-migration", "Dialecto", "Dialecte", "Dialetto", "Dialeto", "{方言|ほうげん}", "方言", "fāngyán"),
    ("Slang", "🧢", "language-migration", "Jerga (argot)", "Argot", "Slang", "Gíria", "スラング", "俚语", "lǐyǔ"),
    ("Jargon", "🧑‍💼", "language-migration", "Jerga (técnica)", "Jargon", "Gergo", "Jargão", "{専門用語|せんもんようご}", "行话", "hánghuà"),
    ("Register (language)", "🎚️", "language-migration", "Registro", "Registre", "Registro", "Registro", "{言葉|ことば}づかい（レジスター）", "语域", "yǔyù"),
    ("Colloquial", "💬", "language-migration", "Coloquial", "Familier", "Colloquiale", "Coloquial", "{口語|こうご}の", "口语的", "kǒuyǔ de"),
    ("Fluency", "🌊", "language-migration", "Fluidez", "Aisance", "Scioltezza", "Fluência", "{流暢|りゅうちょう}さ", "流利度", "liúlìdù"),
    ("Proficiency", "🏅", "language-migration", "Dominio (competencia)", "Maîtrise", "Padronanza", "Proficiência", "{熟達|じゅくたつ}", "熟练程度", "shúliàn chéngdù"),
    ("To master", "👑", "language-migration", "Dominar", "Maîtriser", "Padroneggiare", "Dominar", "{習得|しゅうとく}する", "掌握", "zhǎngwò"),
    ("Immersion", "🌊", "language-migration", "Inmersión", "Immersion", "Immersione", "Imersão", "{没入|ぼつにゅう}", "沉浸", "chénjìn"),
    ("Intonation", "🎵", "language-migration", "Entonación", "Intonation", "Intonazione", "Entonação", "イントネーション", "语调", "yǔdiào"),
    ("To mispronounce", "🗣️", "language-migration", "Pronunciar mal", "Mal prononcer", "Pronunciare male", "Pronunciar mal", "{発音|はつおん}を{間違|まちが}える", "发错音", "fā cuò yīn"),
    ("False friend", "🎭", "language-migration", "Falso amigo", "Faux ami", "Falso amico", "Falso cognato", "{空似言葉|そらにことば}", "假朋友（词）", "jiǎ péngyou"),
    ("Cognate", "🔗", "language-migration", "Cognado", "Mot apparenté", "Parola affine", "Cognato (palavra)", "{同源語|どうげんご}", "同源词", "tóngyuáncí"),
    ("Loanword", "📥", "language-migration", "Préstamo (lingüístico)", "Emprunt", "Prestito (linguistico)", "Empréstimo (linguístico)", "{外来語|がいらいご}", "外来词", "wàiláicí"),
    ("Literacy", "📖", "language-migration", "Alfabetización", "Alphabétisation", "Alfabetizzazione", "Alfabetização", "{識字|しきじ}", "识字能力", "shízì nénglì"),
    ("Interpreter", "🎧", "language-migration", "Intérprete", "Interprète", "Interprete", "Intérprete", "{通訳|つうやく}", "口译员", "kǒuyìyuán"),

    # ---- technology III ----
    ("Latency", "⏱️", "technology-3", "Latencia", "Latence", "Latenza", "Latência", "{遅延|ちえん}（レイテンシ）", "延迟", "yánchí"),
    ("Server", "🖥️", "technology-3", "Servidor", "Serveur", "Server", "Servidor", "サーバー", "服务器", "fúwùqì"),
    ("Cloud computing", "☁️", "technology-3", "Computación en la nube", "Informatique en nuage", "Cloud computing", "Computação em nuvem", "クラウド", "云计算", "yún jìsuàn"),
    ("Backup (data)", "💾", "technology-3", "Copia de seguridad", "Sauvegarde", "Backup", "Backup", "バックアップ", "备份", "bèifèn"),
    ("Firewall", "🧱", "technology-3", "Cortafuegos", "Pare-feu", "Firewall", "Firewall", "ファイアウォール", "防火墙", "fánghuǒqiáng"),
    ("Malware", "🦠", "technology-3", "Malware", "Logiciel malveillant", "Malware", "Malware", "マルウェア", "恶意软件", "èyì ruǎnjiàn"),
    ("Phishing", "🎣", "technology-3", "Suplantación (phishing)", "Hameçonnage", "Phishing", "Phishing", "フィッシング", "网络钓鱼", "wǎngluò diàoyú"),
    ("Two-factor authentication", "🔐", "technology-3", "Autenticación de dos factores", "Authentification à deux facteurs", "Autenticazione a due fattori", "Autenticação de dois fatores", "{二段階認証|にだんかいにんしょう}", "双重验证", "shuāngchóng yànzhèng"),
    ("Biometric", "👁️", "technology-3", "Biométrico", "Biométrique", "Biometrico", "Biométrico", "{生体認証|せいたいにんしょう}の", "生物识别的", "shēngwù shíbié de"),
    ("Open source", "🔓", "technology-3", "Código abierto", "Open source", "Open source", "Código aberto", "オープンソース", "开源", "kāiyuán"),
    ("Interface", "🖱️", "technology-3", "Interfaz", "Interface", "Interfaccia", "Interface", "インターフェース", "界面", "jièmiàn"),
    ("Plugin", "🔌", "technology-3", "Complemento", "Extension (plugin)", "Plugin", "Plugin", "プラグイン", "插件", "chājiàn"),
    ("Patch (software)", "🩹", "technology-3", "Parche", "Correctif", "Patch", "Patch (correção)", "パッチ", "补丁", "bǔdīng"),
    ("To deploy", "🚀", "technology-3", "Desplegar", "Déployer (mettre en production)", "Distribuire (rilasciare)", "Implantar", "デプロイする", "部署", "bùshǔ"),
    ("Release (version)", "📦", "technology-3", "Versión (lanzamiento)", "Version (sortie)", "Rilascio", "Versão (lançamento)", "リリース", "发布版本", "fābù bǎnběn"),
    ("Beta", "🧪", "technology-3", "Beta", "Bêta", "Beta", "Beta", "ベータ{版|ばん}", "测试版", "cèshìbǎn"),
    ("Blockchain", "⛓️", "technology-3", "Cadena de bloques", "Chaîne de blocs", "Blockchain", "Blockchain", "ブロックチェーン", "区块链", "qūkuàiliàn"),
    ("Cryptocurrency", "🪙", "technology-3", "Criptomoneda", "Cryptomonnaie", "Criptovaluta", "Criptomoeda", "{暗号資産|あんごうしさん}", "加密货币", "jiāmì huòbì"),
    ("Machine learning", "🧠", "technology-3", "Aprendizaje automático", "Apprentissage automatique", "Apprendimento automatico", "Aprendizado de máquina", "{機械学習|きかいがくしゅう}", "机器学习", "jīqì xuéxí"),
    ("Neural network", "🕸️", "technology-3", "Red neuronal", "Réseau de neurones", "Rete neurale", "Rede neural", "ニューラルネットワーク", "神经网络", "shénjīng wǎngluò"),
    ("Dataset", "📊", "technology-3", "Conjunto de datos", "Jeu de données", "Set di dati", "Conjunto de dados", "データセット", "数据集", "shùjùjí"),
    ("Drone", "🚁", "technology-3", "Dron", "Drone", "Drone", "Drone", "ドローン", "无人机", "wúrénjī"),
    ("Sensor", "📡", "technology-3", "Sensor", "Capteur", "Sensore", "Sensor", "センサー", "传感器", "chuángǎnqì"),
    ("Augmented reality", "🕶️", "technology-3", "Realidad aumentada", "Réalité augmentée", "Realtà aumentata", "Realidade aumentada", "{拡張現実|かくちょうげんじつ}", "增强现实", "zēngqiáng xiànshí"),
    ("Wearable", "⌚", "technology-3", "Dispositivo vestible", "Objet connecté (portable)", "Dispositivo indossabile", "Vestível (wearable)", "ウェアラブル", "可穿戴设备", "kě chuāndài shèbèi"),
    ("Smart home", "🏠", "technology-3", "Casa inteligente", "Maison connectée", "Casa intelligente", "Casa inteligente", "スマートホーム", "智能家居", "zhìnéng jiājū"),
    ("Bandwidth (network)", "📶", "technology-3", "Ancho de banda", "Bande passante", "Larghezza di banda", "Largura de banda", "{帯域幅|たいいきはば}", "带宽", "dàikuān"),
    ("Outage", "🔌", "technology-3", "Caída (del servicio)", "Panne (de service)", "Interruzione (del servizio)", "Queda (do serviço)", "{障害|しょうがい}（サービス{停止|ていし}）", "服务中断", "fúwù zhōngduàn"),
    ("Scalability", "📈", "technology-3", "Escalabilidad", "Évolutivité", "Scalabilità", "Escalabilidade", "スケーラビリティ", "可扩展性", "kě kuòzhǎn xìng"),
    ("Encryption key", "🔑", "technology-3", "Clave de cifrado", "Clé de chiffrement", "Chiave di cifratura", "Chave de criptografia", "{暗号鍵|あんごうかぎ}", "加密密钥", "jiāmì mìyào"),
]

# ---- C1 media sentences: news snippets and screen dialogue lines (build + listening source) ----
SENTENCES = [
    {"id": "c1-m01", "topic": "build-media-lines", "en": "The government announced new measures to reduce inflation.",
     "note": "A news-register sentence: formal verb (announce) + abstract noun (measures) + purpose clause.",
     "es": ["El gobierno", "anunció", "nuevas medidas", "para reducir", "la inflación"],
     "fr": ["Le gouvernement", "a annoncé", "de nouvelles mesures", "pour réduire", "l’inflation"],
     "it": ["Il governo", "ha annunciato", "nuove misure", "per ridurre", "l’inflazione"],
     "pt": ["O governo", "anunciou", "novas medidas", "para reduzir", "a inflação"],
     "ja": ["{政府|せいふ}は", "インフレを{抑|おさ}えるための", "{新|あたら}しい{対策|たいさく}を", "{発表|はっぴょう}しました"],
     "zh": ["政府", "宣布了", "降低通胀的", "新措施"]},
    {"id": "c1-m02", "topic": "build-media-lines", "en": "According to the report, unemployment fell for the third month in a row.",
     "note": "Attribution (“according to”) plus a time expression — pure news structure.",
     "es": ["Según el informe,", "el desempleo", "bajó", "por tercer mes", "consecutivo"],
     "fr": ["Selon le rapport,", "le chômage", "a baissé", "pour le troisième mois", "consécutif"],
     "it": ["Secondo il rapporto,", "la disoccupazione", "è calata", "per il terzo mese", "consecutivo"],
     "pt": ["Segundo o relatório,", "o desemprego", "caiu", "pelo terceiro mês", "consecutivo"],
     "ja": ["{報告書|ほうこくしょ}によると、", "{失業率|しつぎょうりつ}は", "{三|さん}か{月|げつ}{連続|れんぞく}で", "{低下|ていか}しました"],
     "zh": ["根据报告，", "失业率", "连续第三个月", "下降"]},
    {"id": "c1-m03", "topic": "build-media-lines", "en": "I never said I was leaving; I said I needed time.",
     "note": "A screen line: correcting a misunderstanding with contrast.",
     "es": ["Nunca dije", "que me iba;", "dije", "que necesitaba", "tiempo"],
     "fr": ["Je n’ai jamais dit", "que je partais ;", "j’ai dit", "que j’avais besoin", "de temps"],
     "it": ["Non ho mai detto", "che me ne andavo;", "ho detto", "che avevo bisogno", "di tempo"],
     "pt": ["Eu nunca disse", "que ia embora;", "eu disse", "que precisava", "de tempo"],
     "ja": ["{出|で}ていくなんて", "{一度|いちど}も{言|い}ってない。", "{時間|じかん}が{必要|ひつよう}だって", "{言|い}ったんだ"],
     "zh": ["我从没说过", "我要走；", "我说的是", "我需要时间"]},
    {"id": "c1-m04", "topic": "build-media-lines", "en": "Whatever happens tonight, don’t open that door.",
     "note": "Thriller dialogue: concessive “whatever” + negative imperative.",
     "es": ["Pase lo que pase", "esta noche,", "no abras", "esa puerta"],
     "fr": ["Quoi qu’il arrive", "ce soir,", "n’ouvre pas", "cette porte"],
     "it": ["Qualunque cosa succeda", "stanotte,", "non aprire", "quella porta"],
     "pt": ["Aconteça o que acontecer", "esta noite,", "não abra", "aquela porta"],
     "ja": ["{今夜|こんや}", "{何|なに}が{起|お}きても、", "そのドアを", "{開|あ}けるな"],
     "zh": ["今晚", "无论发生什么，", "都别开", "那扇门"]},
    {"id": "c1-m05", "topic": "build-media-lines", "en": "Scientists warn that the glacier could disappear within a decade.",
     "note": "Reporting verb (warn) + modal possibility (could) + time frame.",
     "es": ["Los científicos", "advierten", "que el glaciar", "podría desaparecer", "en una década"],
     "fr": ["Les scientifiques", "avertissent", "que le glacier", "pourrait disparaître", "d’ici dix ans"],
     "it": ["Gli scienziati", "avvertono", "che il ghiacciaio", "potrebbe sparire", "entro un decennio"],
     "pt": ["Os cientistas", "alertam", "que a geleira", "pode desaparecer", "em uma década"],
     "ja": ["{科学者|かがくしゃ}たちは", "{氷河|ひょうが}が", "{十年以内|じゅうねんいない}に{消|き}える{可能性|かのうせい}があると", "{警告|けいこく}しています"],
     "zh": ["科学家警告说", "这座冰川", "可能在十年内", "消失"]},
    {"id": "c1-m06", "topic": "build-media-lines", "en": "If you had told me the truth, none of this would have happened.",
     "note": "Third conditional — the signature structure of every dramatic argument.",
     "es": ["Si me hubieras dicho", "la verdad,", "nada de esto", "habría pasado"],
     "fr": ["Si tu m’avais dit", "la vérité,", "rien de tout ça", "ne serait arrivé"],
     "it": ["Se mi avessi detto", "la verità,", "niente di tutto questo", "sarebbe successo"],
     "pt": ["Se você tivesse me contado", "a verdade,", "nada disso", "teria acontecido"],
     "ja": ["{本当|ほんとう}のことを", "{言|い}ってくれていたら、", "こんなことには", "ならなかったのに"],
     "zh": ["如果你当时", "告诉我真相，", "这一切", "都不会发生"]},
    {"id": "c1-m07", "topic": "build-media-lines", "en": "The suspect was arrested shortly after the police received an anonymous tip.",
     "note": "Passive voice + “shortly after” — crime-report register.",
     "es": ["El sospechoso", "fue detenido", "poco después de que", "la policía recibiera", "un aviso anónimo"],
     "fr": ["Le suspect", "a été arrêté", "peu après que", "la police a reçu", "un signalement anonyme"],
     "it": ["Il sospettato", "è stato arrestato", "poco dopo che", "la polizia ha ricevuto", "una segnalazione anonima"],
     "pt": ["O suspeito", "foi preso", "pouco depois de", "a polícia receber", "uma denúncia anônima"],
     "ja": ["{容疑者|ようぎしゃ}は", "{警察|けいさつ}が{匿名|とくめい}の{通報|つうほう}を{受|う}けた", "{直後|ちょくご}に", "{逮捕|たいほ}されました"],
     "zh": ["嫌疑人", "在警方收到匿名举报后", "不久", "被逮捕"]},
    {"id": "c1-m08", "topic": "build-media-lines", "en": "Honestly, I think we’re both to blame for what happened.",
     "note": "Screen dialogue: hedged opinion + shared responsibility.",
     "es": ["Sinceramente,", "creo que", "los dos tenemos la culpa", "de lo que pasó"],
     "fr": ["Franchement,", "je pense que", "nous sommes tous les deux responsables", "de ce qui s’est passé"],
     "it": ["Sinceramente,", "penso che", "la colpa sia di entrambi", "per quello che è successo"],
     "pt": ["Sinceramente,", "acho que", "nós dois temos culpa", "pelo que aconteceu"],
     "ja": ["{正直|しょうじき}に{言|い}うと、", "{起|お}きたことについては", "{二人|ふたり}とも", "{責任|せきにん}があると{思|おも}う"],
     "zh": ["说实话，", "我觉得", "发生的事", "我们俩都有责任"]},
    {"id": "c1-m09", "topic": "build-media-lines", "en": "The company denied the allegations but declined to comment further.",
     "note": "Two reporting verbs in contrast (denied / declined) — standard corporate-news phrasing.",
     "es": ["La empresa", "negó", "las acusaciones", "pero se negó", "a hacer más comentarios"],
     "fr": ["L’entreprise", "a démenti", "les accusations", "mais a refusé", "de commenter davantage"],
     "it": ["L’azienda", "ha negato", "le accuse", "ma ha rifiutato", "di commentare oltre"],
     "pt": ["A empresa", "negou", "as acusações", "mas se recusou", "a comentar mais"],
     "ja": ["{同社|どうしゃ}は", "{疑惑|ぎわく}を{否定|ひてい}したが、", "それ{以上|いじょう}の", "コメントは{控|ひか}えた"],
     "zh": ["该公司", "否认了指控，", "但拒绝", "进一步置评"]},
    {"id": "c1-m10", "topic": "build-media-lines", "en": "You have no idea what I gave up to get here.",
     "note": "Emotional screen line with an embedded clause (“what I gave up”).",
     "es": ["No tienes ni idea", "de lo que renuncié", "para llegar", "hasta aquí"],
     "fr": ["Tu n’as aucune idée", "de ce à quoi j’ai renoncé", "pour arriver", "jusqu’ici"],
     "it": ["Non hai idea", "di quello a cui ho rinunciato", "per arrivare", "fin qui"],
     "pt": ["Você não faz ideia", "do que eu abri mão", "para chegar", "até aqui"],
     "ja": ["ここまで{来|く}るのに", "{私|わたし}が{何|なに}を{犠牲|ぎせい}にしたか、", "{君|きみ}には", "{分|わ}からないだろう"],
     "zh": ["你根本不知道", "为了走到这一步", "我放弃了", "什么"]},
    {"id": "c1-m11", "topic": "build-media-lines", "en": "Voters will head to the polls on Sunday amid growing uncertainty.",
     "note": "Future headline style: “head to the polls” + “amid” + abstract noun.",
     "es": ["Los votantes", "acudirán a las urnas", "el domingo", "en medio de", "una creciente incertidumbre"],
     "fr": ["Les électeurs", "se rendront aux urnes", "dimanche", "dans un climat", "d’incertitude croissante"],
     "it": ["Gli elettori", "andranno alle urne", "domenica", "in un clima", "di crescente incertezza"],
     "pt": ["Os eleitores", "irão às urnas", "no domingo", "em meio a", "uma incerteza crescente"],
     "ja": ["{有権者|ゆうけんしゃ}は", "{高|たか}まる{不透明感|ふとうめいかん}の{中|なか}、", "{日曜日|にちようび}に", "{投票|とうひょう}に{向|む}かいます"],
     "zh": ["选民们", "将在周日", "在日益加剧的不确定性中", "前往投票"]},
    {"id": "c1-m12", "topic": "build-media-lines", "en": "Let’s just say it didn’t go the way I planned.",
     "note": "Understatement — “let’s just say” — a very common spoken hedge.",
     "es": ["Digamos", "que no salió", "como", "lo había planeado"],
     "fr": ["Disons", "que ça ne s’est pas passé", "comme", "je l’avais prévu"],
     "it": ["Diciamo", "che non è andata", "come", "avevo previsto"],
     "pt": ["Digamos", "que não saiu", "como", "eu tinha planejado"],
     "ja": ["まあ、", "{計画|けいかく}どおりには", "いかなかった", "とだけ{言|い}っておくよ"],
     "zh": ["这么说吧，", "事情", "没有按我计划的", "那样发展"]},
]

# ---- extra C1 idioms heard on screen (2 per language) ----
IDIOMS = [
    {"id": "i-es5", "lang": "es", "topic": "idiom-media", "phrase": "Tirar la toalla", "correct": "To give up",
     "options": ["To give up", "To take a shower", "To start a fight", "To clean up a mess"], "note": "Literally “throw in the towel” — straight from boxing, same as English."},
    {"id": "i-es6", "lang": "es", "topic": "idiom-media", "phrase": "Estar en las nubes", "correct": "To be daydreaming, not paying attention",
     "options": ["To be daydreaming, not paying attention", "To be very happy", "To be traveling by plane", "To be very tall"], "note": "Literally “to be in the clouds” — head somewhere else entirely."},
    {"id": "i-fr5", "lang": "fr", "topic": "idiom-media", "phrase": "Mettre les pieds dans le plat", "correct": "To bring up something awkward bluntly",
     "options": ["To bring up something awkward bluntly", "To step in a puddle", "To eat too fast", "To cook a big meal"], "note": "Literally “put one’s feet in the dish” — a tactless blunder."},
    {"id": "i-fr6", "lang": "fr", "topic": "idiom-media", "phrase": "Ce n’est pas la mer à boire", "correct": "It’s not that hard",
     "options": ["It’s not that hard", "It’s not worth drinking", "The sea is dangerous", "It’s too expensive"], "note": "Literally “it’s not the sea to drink” — no big deal."},
    {"id": "i-it5", "lang": "it", "topic": "idiom-media", "phrase": "Acqua in bocca", "correct": "Keep it a secret",
     "options": ["Keep it a secret", "Drink some water", "Stop talking nonsense", "Be careful swimming"], "note": "Literally “water in the mouth” — you can’t talk with a mouthful."},
    {"id": "i-it6", "lang": "it", "topic": "idiom-media", "phrase": "Costare un occhio della testa", "correct": "To cost a fortune",
     "options": ["To cost a fortune", "To hurt one’s eye", "To lose focus", "To be very ugly"], "note": "Literally “cost an eye of the head” — the Italian cousin of the Spanish version."},
    {"id": "i-pt5", "lang": "pt", "topic": "idiom-media", "phrase": "Chutar o balde", "correct": "To lose one’s patience and give up on the rules",
     "options": ["To lose one’s patience and give up on the rules", "To play soccer badly", "To spill water everywhere", "To take a break"], "note": "Literally “kick the bucket” — in Portuguese it means snapping, not dying."},
    {"id": "i-pt6", "lang": "pt", "topic": "idiom-media", "phrase": "Engolir sapos", "correct": "To put up with unpleasant things silently",
     "options": ["To put up with unpleasant things silently", "To eat exotic food", "To tell a lie", "To speak very fast"], "note": "Literally “swallow frogs” — biting your tongue through insults."},
    {"id": "i-ja5", "lang": "ja", "topic": "idiom-media", "phrase": "{空気|くうき}を{読|よ}む", "romaji": "kūki wo yomu", "correct": "To read the room",
     "options": ["To read the room", "To breathe deeply", "To study the weather", "To read out loud"], "note": "Literally “read the air” — the core social skill in Japanese conversation."},
    {"id": "i-ja6", "lang": "ja", "topic": "idiom-media", "phrase": "{一石二鳥|いっせきにちょう}", "romaji": "isseki nichō", "correct": "To kill two birds with one stone",
     "options": ["To kill two birds with one stone", "To miss an easy chance", "To be very lucky", "To make a rare mistake"], "note": "A four-character idiom: “one stone, two birds.”"},
    {"id": "i-zh5", "lang": "zh", "topic": "idiom-media", "phrase": "加油", "romaji": "jiāyóu", "correct": "Come on, you can do it!",
     "options": ["Come on, you can do it!", "Fill up the gas tank", "Add more oil to the pan", "Slow down"], "note": "Literally “add fuel” — the universal Chinese cheer."},
    {"id": "i-zh6", "lang": "zh", "topic": "idiom-media", "phrase": "井底之蛙", "romaji": "jǐng dǐ zhī wā", "correct": "A narrow-minded person with limited experience",
     "options": ["A narrow-minded person with limited experience", "A very lucky person", "A skilled swimmer", "A person who talks too much"], "note": "Literally “the frog at the bottom of the well” — it thinks the sky is a small circle."},
]

LISTEN = [
    {"key": "listen-c1-media", "tier": "C1", "source": "sentences", "count": 12},
    {"key": "listen-c1-words", "tier": "C1", "source": "vocab", "count": 20},
]
