# -*- coding: utf-8 -*-
# B2 vocabulary batch 5 — time management, geography, anatomy, clothing & fabric, abstract concepts, degree adverbs, hobbies & making
TIER = 'B2'
TOPICS = {
    'time-management': 'Time Management', 'geography': 'Geography & Landscapes', 'anatomy': 'Anatomy',
    'clothing-fabric': 'Clothing & Fabric', 'abstract-concepts': 'Abstract Concepts', 'degree-adverbs': 'Degree & Manner Adverbs',
    'hobbies-making': 'Hobbies & Making',
}
WORDS = [
    # ---- time management ----
    ("Efficiency", "⚡", "time-management", "Eficiencia", "Efficacité", "Efficienza", "Eficiência", "{効率|こうりつ}", "效率", "xiàolǜ"),
    ("Productivity", "📈", "time-management", "Productividad", "Productivité", "Produttività", "Produtividade", "{生産性|せいさんせい}", "生产力", "shēngchǎnlì"),
    ("To-do list", "☑️", "time-management", "Lista de tareas", "Liste de choses à faire", "Lista delle cose da fare", "Lista de tarefas", "やることリスト", "待办清单", "dàibàn qīngdān"),
    ("Reminder", "🔔", "time-management", "Recordatorio", "Rappel", "Promemoria", "Lembrete", "リマインダー", "提醒", "tíxǐng"),
    ("To reschedule", "📅", "time-management", "Reprogramar", "Reprogrammer", "Riprogrammare", "Remarcar", "{予定|よてい}を{変更|へんこう}する", "改期", "gǎiqī"),
    ("Calendar", "🗓️", "time-management", "Calendario", "Calendrier", "Calendario", "Calendário", "カレンダー", "日历", "rìlì"),
    ("Time zone", "🌐", "time-management", "Zona horaria", "Fuseau horaire", "Fuso orario", "Fuso horário", "{時間帯|じかんたい}", "时区", "shíqū"),
    ("Daylight saving time", "🕰️", "time-management", "Horario de verano", "Heure d’été", "Ora legale", "Horário de verão", "サマータイム", "夏令时", "xiàlìngshí"),
    ("Punctuality", "⏰", "time-management", "Puntualidad", "Ponctualité", "Puntualità", "Pontualidade", "{時間厳守|じかんげんしゅ}", "守时", "shǒushí"),
    ("Ahead of schedule", "🏃", "time-management", "Adelantado", "En avance", "In anticipo", "Adiantado", "{予定|よてい}より{早|はや}く", "提前于计划", "tíqián yú jìhuà"),
    ("Behind schedule", "🐢", "time-management", "Retrasado (respecto al plan)", "En retard (sur le planning)", "In ritardo (sulla tabella)", "Atrasado (no cronograma)", "{予定|よてい}より{遅|おく}れて", "落后于计划", "luòhòu yú jìhuà"),
    ("In advance", "📆", "time-management", "Con antelación", "À l’avance", "In anticipo (prima)", "Com antecedência", "{前|まえ}もって", "提前", "tíqián"),
    ("Last minute", "⏱️", "time-management", "De última hora", "De dernière minute", "All’ultimo minuto", "De última hora", "{土壇場|どたんば}の", "最后一刻", "zuìhòu yíkè"),
    ("Overdue", "⚠️", "time-management", "Atrasado (vencido)", "En retard (échu)", "Scaduto", "Vencido", "{期限切|きげんぎ}れ", "逾期", "yúqī"),
    ("To squeeze in", "🤏", "time-management", "Hacer un hueco", "Caser", "Infilare (nel programma)", "Encaixar", "{無理|むり}に{入|い}れる", "挤出时间", "jǐchū shíjiān"),
    ("To multitask", "🤹", "time-management", "Hacer varias cosas a la vez", "Faire plusieurs choses à la fois", "Fare più cose insieme", "Fazer várias coisas ao mesmo tempo", "マルチタスクする", "多任务处理", "duō rènwu chǔlǐ"),
    ("To allocate", "📊", "time-management", "Asignar (tiempo)", "Allouer", "Allocare", "Alocar", "{配分|はいぶん}する", "分配（时间）", "fēnpèi"),
    ("Downtime", "🛋️", "time-management", "Tiempo muerto", "Temps mort", "Tempo morto", "Tempo de folga", "{休止時間|きゅうしじかん}", "空闲时间（停机）", "kòngxián shíjiān"),
    ("Spare time", "🕰️", "time-management", "Tiempo libre (sobrante)", "Temps libre (restant)", "Tempo libero (avanzato)", "Tempo vago", "{余|あま}った{時間|じかん}", "闲暇", "xiánxiá"),
    ("To kill time", "🎮", "time-management", "Matar el tiempo", "Tuer le temps", "Ammazzare il tempo", "Matar o tempo", "{時間|じかん}をつぶす", "消磨时间", "xiāomó shíjiān"),
    ("Pastime", "🎨", "time-management", "Pasatiempo (afición)", "Passe-temps (loisir)", "Passatempo (svago)", "Passatempo (lazer)", "{気晴|きば}らし", "消遣", "xiāoqiǎn"),
    ("Leisure", "🏖️", "time-management", "Ocio", "Loisirs", "Svago", "Lazer", "{余暇|よか}", "休闲", "xiūxián"),
    ("On the dot", "🎯", "time-management", "En punto", "Pile", "In punto", "Em ponto", "{時間|じかん}ぴったりに", "准点", "zhǔndiǎn"),
    ("Around the clock", "🕛", "time-management", "Las veinticuatro horas", "Vingt-quatre heures sur vingt-quatre", "Ventiquattr’ore su ventiquattro", "Vinte e quatro horas por dia", "{昼夜|ちゅうや}を{問|と}わず", "全天候", "quántiānhòu"),
    ("In the nick of time", "⏳", "time-management", "Justo a tiempo", "Juste à temps", "Appena in tempo", "Bem na hora", "ぎりぎりで", "在最后关头", "zài zuìhòu guāntóu"),
    ("Long-term", "🛤️", "time-management", "A largo plazo (adj.)", "À long terme (adj.)", "A lungo termine (agg.)", "De longo prazo", "{長期|ちょうき}の", "长期的", "chángqī de"),
    ("Short-term", "⏱️", "time-management", "A corto plazo", "À court terme", "A breve termine", "De curto prazo", "{短期|たんき}の", "短期的", "duǎnqī de"),
    ("Simultaneously", "⚖️", "time-management", "Simultáneamente", "Simultanément", "Simultaneamente", "Simultaneamente", "{同時|どうじ}に（{並行|へいこう}）", "同时地", "tóngshí de"),

    # ---- geography & landscapes ----
    ("Continent", "🌍", "geography", "Continente", "Continent", "Continente", "Continente", "{大陸|たいりく}", "大陆", "dàlù"),
    ("Hemisphere", "🌐", "geography", "Hemisferio", "Hémisphère", "Emisfero", "Hemisfério", "{半球|はんきゅう}", "半球", "bànqiú"),
    ("Equator", "➖", "geography", "Ecuador (línea)", "Équateur", "Equatore", "Equador (linha)", "{赤道|せきどう}", "赤道", "chìdào"),
    ("Latitude", "🧭", "geography", "Latitud", "Latitude", "Latitudine", "Latitude", "{緯度|いど}", "纬度", "wěidù"),
    ("Altitude", "🏔️", "geography", "Altitud", "Altitude", "Altitudine", "Altitude", "{標高|ひょうこう}", "海拔", "hǎibá"),
    ("Valley", "🏞️", "geography", "Valle", "Vallée", "Valle", "Vale", "{谷|たに}", "山谷", "shāngǔ"),
    ("Canyon", "🏜️", "geography", "Cañón", "Canyon", "Canyon", "Desfiladeiro", "{峡谷|きょうこく}", "峡谷", "xiágǔ"),
    ("Cliff", "🧗", "geography", "Acantilado", "Falaise", "Scogliera", "Penhasco", "{崖|がけ}", "悬崖", "xuányá"),
    ("Cave", "🕳️", "geography", "Cueva", "Grotte", "Grotta", "Caverna", "{洞窟|どうくつ}", "洞穴", "dòngxué"),
    ("Plateau", "🗻", "geography", "Meseta", "Plateau", "Altopiano", "Planalto", "{高原|こうげん}", "高原", "gāoyuán"),
    ("Peninsula", "🗺️", "geography", "Península", "Péninsule", "Penisola", "Península", "{半島|はんとう}", "半岛", "bàndǎo"),
    ("Bay", "⛵", "geography", "Bahía", "Baie", "Baia", "Baía", "{湾|わん}", "海湾", "hǎiwān"),
    ("Coast", "🏖️", "geography", "Costa", "Côte", "Costa", "Costa", "{海岸|かいがん}", "海岸", "hǎi'àn"),
    ("Shore", "🌊", "geography", "Orilla", "Rivage", "Riva", "Margem (praia)", "{岸|きし}", "岸边", "ànbiān"),
    ("Harbor", "⚓", "geography", "Puerto", "Port", "Porto", "Porto", "{港|みなと}", "港口", "gǎngkǒu"),
    ("Dune", "🏜️", "geography", "Duna", "Dune", "Duna", "Duna", "{砂丘|さきゅう}", "沙丘", "shāqiū"),
    ("Iceberg", "🧊", "geography", "Iceberg", "Iceberg", "Iceberg", "Iceberg", "{氷山|ひょうざん}", "冰山", "bīngshān"),
    ("Swamp", "🐊", "geography", "Pantano", "Marécage", "Palude", "Pântano", "{沼地|ぬまち}", "沼泽", "zhǎozé"),
    ("Jungle", "🌴", "geography", "Selva", "Jungle", "Giungla", "Selva", "ジャングル", "丛林", "cónglín"),
    ("Rainforest", "🌧️", "geography", "Selva tropical", "Forêt tropicale", "Foresta pluviale", "Floresta tropical", "{熱帯雨林|ねったいうりん}", "热带雨林", "rèdài yǔlín"),
    ("Savanna", "🦒", "geography", "Sabana", "Savane", "Savana", "Savana", "サバンナ", "热带草原", "rèdài cǎoyuán"),
    ("Tundra", "❄️", "geography", "Tundra", "Toundra", "Tundra", "Tundra", "ツンドラ", "苔原", "táiyuán"),
    ("Oasis", "🌴", "geography", "Oasis", "Oasis", "Oasi", "Oásis", "オアシス", "绿洲", "lǜzhōu"),
    ("Waterfall", "💦", "geography", "Cascada", "Cascade", "Cascata", "Cachoeira", "{滝|たき}", "瀑布", "pùbù"),
    ("Stream", "🏞️", "geography", "Arroyo", "Ruisseau", "Ruscello", "Riacho", "{小川|おがわ}", "溪流", "xīliú"),
    ("Spring (water)", "💧", "geography", "Manantial", "Source", "Sorgente", "Nascente", "{泉|いずみ}", "泉水", "quánshuǐ"),
    ("Reef", "🐠", "geography", "Arrecife", "Récif", "Barriera corallina", "Recife", "サンゴ{礁|しょう}", "珊瑚礁", "shānhújiāo"),
    ("Tide", "🌊", "geography", "Marea", "Marée", "Marea", "Maré", "{潮|しお}", "潮汐", "cháoxī"),
    ("Current (water)", "🌀", "geography", "Corriente", "Courant", "Corrente", "Correnteza", "{海流|かいりゅう}", "水流", "shuǐliú"),
    ("Horizon", "🌅", "geography", "Horizonte", "Horizon", "Orizzonte", "Horizonte", "{地平線|ちへいせん}", "地平线", "dìpíngxiàn"),

    # ---- anatomy ----
    ("Skeleton", "💀", "anatomy", "Esqueleto", "Squelette", "Scheletro", "Esqueleto", "{骨格|こっかく}", "骨骼", "gǔgé"),
    ("Bone", "🦴", "anatomy", "Hueso", "Os", "Osso", "Osso", "{骨|ほね}", "骨头", "gǔtou"),
    ("Skull", "💀", "anatomy", "Cráneo", "Crâne", "Cranio", "Crânio", "{頭蓋骨|ずがいこつ}", "头骨", "tóugǔ"),
    ("Spine", "🦴", "anatomy", "Columna vertebral", "Colonne vertébrale", "Colonna vertebrale", "Coluna", "{背骨|せぼね}", "脊柱", "jǐzhù"),
    ("Rib", "🦴", "anatomy", "Costilla", "Côte", "Costola", "Costela", "{肋骨|ろっこつ}", "肋骨", "lèigǔ"),
    ("Joint", "🦵", "anatomy", "Articulación", "Articulation", "Articolazione", "Articulação", "{関節|かんせつ}", "关节", "guānjié"),
    ("Tendon", "🧬", "anatomy", "Tendón", "Tendon", "Tendine", "Tendão", "{腱|けん}", "肌腱", "jījiàn"),
    ("Nerve", "⚡", "anatomy", "Nervio", "Nerf", "Nervo", "Nervo", "{神経|しんけい}", "神经", "shénjīng"),
    ("Brain", "🧠", "anatomy", "Cerebro", "Cerveau", "Cervello", "Cérebro", "{脳|のう}", "大脑", "dànǎo"),
    ("Lung", "🫁", "anatomy", "Pulmón", "Poumon", "Polmone", "Pulmão", "{肺|はい}", "肺", "fèi"),
    ("Liver", "🫀", "anatomy", "Hígado", "Foie", "Fegato", "Fígado", "{肝臓|かんぞう}", "肝脏", "gānzàng"),
    ("Kidney", "🫘", "anatomy", "Riñón", "Rein", "Rene", "Rim", "{腎臓|じんぞう}", "肾脏", "shènzàng"),
    ("Intestine", "🌀", "anatomy", "Intestino", "Intestin", "Intestino", "Intestino", "{腸|ちょう}", "肠", "cháng"),
    ("Artery", "❤️", "anatomy", "Arteria", "Artère", "Arteria", "Artéria", "{動脈|どうみゃく}", "动脉", "dòngmài"),
    ("Vein", "💙", "anatomy", "Vena", "Veine", "Vena", "Veia", "{静脈|じょうみゃく}", "静脉", "jìngmài"),
    ("Pulse", "💓", "anatomy", "Pulso", "Pouls", "Polso (battito)", "Pulso", "{脈|みゃく}", "脉搏", "màibó"),
    ("Wrist", "⌚", "anatomy", "Muñeca", "Poignet", "Polso", "Pulso (articulação)", "{手首|てくび}", "手腕", "shǒuwàn"),
    ("Ankle", "🦶", "anatomy", "Tobillo", "Cheville", "Caviglia", "Tornozelo", "{足首|あしくび}", "脚踝", "jiǎohuái"),
    ("Elbow", "💪", "anatomy", "Codo", "Coude", "Gomito", "Cotovelo", "{肘|ひじ}", "肘", "zhǒu"),
    ("Thigh", "🦵", "anatomy", "Muslo", "Cuisse", "Coscia", "Coxa", "{太|ふと}もも", "大腿", "dàtuǐ"),
    ("Heel", "👠", "anatomy", "Talón", "Talon", "Tallone", "Calcanhar", "かかと", "脚跟", "jiǎogēn"),
    ("Palm", "🖐️", "anatomy", "Palma", "Paume", "Palmo", "Palma", "{手|て}のひら", "手掌", "shǒuzhǎng"),
    ("Thumb", "👍", "anatomy", "Pulgar", "Pouce", "Pollice", "Polegar", "{親指|おやゆび}", "拇指", "mǔzhǐ"),
    ("Eyebrow", "🤨", "anatomy", "Ceja", "Sourcil", "Sopracciglio", "Sobrancelha", "{眉|まゆ}", "眉毛", "méimao"),
    ("Eyelash", "👁️", "anatomy", "Pestaña", "Cil", "Ciglio", "Cílio", "まつげ", "睫毛", "jiémáo"),
    ("Chin", "🧔", "anatomy", "Barbilla", "Menton", "Mento", "Queixo", "あご", "下巴", "xiàba"),
    ("Cheek", "😊", "anatomy", "Mejilla", "Joue", "Guancia", "Bochecha", "{頬|ほお}", "脸颊", "liǎnjiá"),
    ("Forehead", "🧠", "anatomy", "Frente", "Front", "Fronte", "Testa (fronte)", "{額|ひたい}", "额头", "étóu"),
    ("Jaw", "🦷", "anatomy", "Mandíbula", "Mâchoire", "Mascella", "Mandíbula", "{顎|あご}（{骨|ほね}）", "下颌", "xiàhé"),
    ("Throat", "🗣️", "anatomy", "Garganta", "Gorge", "Gola", "Garganta", "{喉|のど}", "喉咙", "hóulóng"),
    ("Tongue", "👅", "anatomy", "Lengua", "Langue (organe)", "Lingua (organo)", "Língua (órgão)", "{舌|した}", "舌头", "shétou"),
    ("Lip", "👄", "anatomy", "Labio", "Lèvre", "Labbro", "Lábio", "{唇|くちびる}", "嘴唇", "zuǐchún"),

    # ---- clothing & fabric ----
    ("Tailor", "🧵", "clothing-fabric", "Sastre", "Tailleur", "Sarto", "Alfaiate", "{仕立屋|したてや}", "裁缝", "cáiféng"),
    ("Fabric", "🧶", "clothing-fabric", "Tela", "Tissu", "Tessuto", "Tecido", "{布地|ぬのじ}", "布料", "bùliào"),
    ("Seam", "🪡", "clothing-fabric", "Costura", "Couture", "Cucitura", "Costura", "{縫|ぬ}い{目|め}", "接缝", "jiēfèng"),
    ("Zipper", "🤐", "clothing-fabric", "Cremallera", "Fermeture éclair", "Cerniera", "Zíper", "ファスナー", "拉链", "lāliàn"),
    ("Button", "🔘", "clothing-fabric", "Botón", "Bouton", "Bottone", "Botão", "ボタン", "纽扣", "niǔkòu"),
    ("Collar", "👔", "clothing-fabric", "Cuello (prenda)", "Col", "Colletto", "Colarinho", "{襟|えり}", "衣领", "yīlǐng"),
    ("Sleeve", "👕", "clothing-fabric", "Manga", "Manche", "Manica", "Manga", "{袖|そで}", "袖子", "xiùzi"),
    ("Hem", "📏", "clothing-fabric", "Dobladillo", "Ourlet", "Orlo", "Bainha", "{裾|すそ}", "褶边", "zhěbiān"),
    ("Pocket", "🧥", "clothing-fabric", "Bolsillo", "Poche", "Tasca", "Bolso", "ポケット", "口袋", "kǒudài"),
    ("Lining", "🧥", "clothing-fabric", "Forro", "Doublure", "Fodera", "Forro", "{裏地|うらじ}", "衬里", "chènlǐ"),
    ("To fasten", "🔗", "clothing-fabric", "Abrochar", "Attacher", "Allacciare", "Fechar (prender)", "{留|と}める", "系上", "jìshàng"),
    ("To unbutton", "🔓", "clothing-fabric", "Desabrochar", "Déboutonner", "Sbottonare", "Desabotoar", "ボタンを{外|はず}す", "解开纽扣", "jiěkāi niǔkòu"),
    ("To fold", "📄", "clothing-fabric", "Doblar (ropa)", "Plier (vêtements)", "Piegare (vestiti)", "Dobrar (roupa)", "たたむ", "折叠", "zhédié"),
    ("Wardrobe", "🚪", "clothing-fabric", "Armario", "Armoire", "Armadio", "Guarda-roupa", "クローゼット", "衣柜", "yīguì"),
    ("Hanger", "🧷", "clothing-fabric", "Percha", "Cintre", "Gruccia", "Cabide", "ハンガー", "衣架", "yījià"),
    ("Detergent", "🧴", "clothing-fabric", "Detergente", "Lessive", "Detersivo", "Detergente", "{洗剤|せんざい}", "洗衣液", "xǐyīyè"),
    ("Stain", "🟤", "clothing-fabric", "Mancha", "Tache", "Macchia", "Mancha", "しみ", "污渍", "wūzì"),
    ("To shrink", "📉", "clothing-fabric", "Encoger", "Rétrécir", "Restringersi", "Encolher", "{縮|ちぢ}む", "缩水", "suōshuǐ"),
    ("To fade", "🌫️", "clothing-fabric", "Desteñir", "Déteindre", "Sbiadire", "Desbotar", "{色|いろ}あせる", "褪色", "tuìsè"),
    ("Wrinkle", "〰️", "clothing-fabric", "Arruga", "Pli (froissure)", "Piega (grinza)", "Ruga (amassado)", "しわ", "褶皱", "zhězhòu"),
    ("Formal wear", "🤵", "clothing-fabric", "Ropa formal", "Tenue de soirée", "Abito formale", "Traje social", "{正装|せいそう}", "正装", "zhèngzhuāng"),
    ("Casual wear", "👕", "clothing-fabric", "Ropa informal", "Tenue décontractée", "Abbigliamento casual", "Roupa casual", "{普段着|ふだんぎ}", "休闲装", "xiūxiánzhuāng"),
    ("Uniform", "👮", "clothing-fabric", "Uniforme", "Uniforme", "Uniforme", "Uniforme", "{制服|せいふく}", "制服", "zhìfú"),
    ("Suit", "🤵", "clothing-fabric", "Traje", "Costume", "Completo", "Terno", "スーツ", "西装", "xīzhuāng"),
    ("Tie", "👔", "clothing-fabric", "Corbata", "Cravate", "Cravatta", "Gravata", "ネクタイ", "领带", "lǐngdài"),
    ("High heels", "👠", "clothing-fabric", "Tacones", "Talons hauts", "Tacchi alti", "Salto alto", "ハイヒール", "高跟鞋", "gāogēnxié"),
    ("Sneakers", "👟", "clothing-fabric", "Zapatillas", "Baskets", "Scarpe da ginnastica", "Tênis (calçado)", "スニーカー", "运动鞋", "yùndòngxié"),
    ("Boots", "🥾", "clothing-fabric", "Botas", "Bottes", "Stivali", "Botas", "ブーツ", "靴子", "xuēzi"),
    ("Sandals", "🩴", "clothing-fabric", "Sandalias", "Sandales", "Sandali", "Sandálias", "サンダル", "凉鞋", "liángxié"),
    ("Slippers", "🥿", "clothing-fabric", "Pantuflas", "Chaussons", "Pantofole", "Chinelos", "スリッパ", "拖鞋", "tuōxié"),
    ("Pajamas", "🛌", "clothing-fabric", "Pijama", "Pyjama", "Pigiama", "Pijama", "パジャマ", "睡衣", "shuìyī"),
    ("Underwear", "🩲", "clothing-fabric", "Ropa interior", "Sous-vêtements", "Biancheria intima", "Roupa íntima", "{下着|したぎ}", "内衣", "nèiyī"),
    ("Belt", "🧷", "clothing-fabric", "Cinturón", "Ceinture", "Cintura", "Cinto", "ベルト", "腰带", "yāodài"),

    # ---- abstract concepts ----
    ("Concept", "💡", "abstract-concepts", "Concepto", "Concept", "Concetto", "Conceito", "{概念|がいねん}", "概念", "gàiniàn"),
    ("Notion", "💭", "abstract-concepts", "Noción", "Notion", "Nozione", "Noção", "{観念|かんねん}", "观念", "guānniàn"),
    ("Aspect", "🔷", "abstract-concepts", "Aspecto", "Aspect", "Aspetto", "Aspecto", "{側面|そくめん}", "方面", "fāngmiàn"),
    ("Factor", "🧩", "abstract-concepts", "Factor", "Facteur", "Fattore", "Fator", "{要因|よういん}", "因素", "yīnsù"),
    ("Feature", "⭐", "abstract-concepts", "Característica", "Caractéristique", "Caratteristica", "Característica", "{特徴|とくちょう}（{機能|きのう}）", "特点", "tèdiǎn"),
    ("Element", "🔹", "abstract-concepts", "Elemento", "Élément", "Elemento", "Elemento", "{要素|ようそ}", "元素", "yuánsù"),
    ("Component", "⚙️", "abstract-concepts", "Componente", "Composant", "Componente", "Componente", "{構成要素|こうせいようそ}", "组成部分", "zǔchéng bùfen"),
    ("Structure", "🏗️", "abstract-concepts", "Estructura", "Structure", "Struttura", "Estrutura", "{構造|こうぞう}", "结构", "jiégòu"),
    ("Function", "🔧", "abstract-concepts", "Función", "Fonction", "Funzione", "Função", "{機能|きのう}", "功能", "gōngnéng"),
    ("Process", "🔄", "abstract-concepts", "Proceso", "Processus", "Processo", "Processo", "{過程|かてい}", "过程", "guòchéng"),
    ("Procedure", "📋", "abstract-concepts", "Procedimiento", "Procédure", "Procedura", "Procedimento", "{手順|てじゅん}", "程序（步骤）", "chéngxù"),
    ("Method", "🛠️", "abstract-concepts", "Método", "Méthode", "Metodo", "Método", "{方法|ほうほう}", "方法", "fāngfǎ"),
    ("Approach", "🧭", "abstract-concepts", "Enfoque", "Approche", "Approccio", "Abordagem", "アプローチ", "方式（途径）", "fāngshì"),
    ("Technique", "🎯", "abstract-concepts", "Técnica", "Technique", "Tecnica", "Técnica", "{技術|ぎじゅつ}（{技法|ぎほう}）", "技巧", "jìqiǎo"),
    ("Framework", "🖼️", "abstract-concepts", "Marco", "Cadre", "Quadro (schema)", "Estrutura (quadro)", "{枠組|わくぐ}み", "框架", "kuàngjià"),
    ("Criterion", "📏", "abstract-concepts", "Criterio", "Critère", "Criterio", "Critério", "{基準|きじゅん}（{判断|はんだん}）", "标准（准则）", "zhǔnzé"),
    ("Standard", "✅", "abstract-concepts", "Estándar", "Norme (standard)", "Standard", "Padrão", "{標準|ひょうじゅん}", "标准", "biāozhǔn"),
    ("Norm", "📐", "abstract-concepts", "Norma", "Norme", "Norma", "Norma", "{規範|きはん}", "规范", "guīfàn"),
    ("Exception", "❗", "abstract-concepts", "Excepción", "Exception", "Eccezione", "Exceção", "{例外|れいがい}", "例外", "lìwài"),
    ("Phase", "🌗", "abstract-concepts", "Fase", "Phase", "Fase", "Fase", "{段階|だんかい}", "阶段", "jiēduàn"),
    ("Sequence", "🔢", "abstract-concepts", "Secuencia", "Séquence", "Sequenza", "Sequência", "{順序|じゅんじょ}", "顺序", "shùnxù"),
    ("Outcome", "🏁", "abstract-concepts", "Resultado", "Résultat (issue)", "Esito", "Resultado", "{結果|けっか}（{成果|せいか}）", "结果（成果）", "chéngguǒ"),
    ("Consequence", "➡️", "abstract-concepts", "Consecuencia", "Conséquence", "Conseguenza", "Consequência", "{影響|えいきょう}（{結果|けっか}）", "后果", "hòuguǒ"),
    ("Impact", "💥", "abstract-concepts", "Impacto", "Impact", "Impatto", "Impacto", "{衝撃|しょうげき}（{影響|えいきょう}）", "影响（冲击）", "chōngjī"),
    ("Implication", "🔗", "abstract-concepts", "Implicación", "Implication", "Implicazione", "Implicação", "{含意|がんい}", "含义（影响）", "hányì"),
    ("Significance", "⭐", "abstract-concepts", "Importancia (significado)", "Signification (importance)", "Significato (rilevanza)", "Significado (importância)", "{意義|いぎ}", "意义", "yìyì"),
    ("Context", "🗺️", "abstract-concepts", "Contexto", "Contexte", "Contesto", "Contexto", "{文脈|ぶんみゃく}", "语境", "yǔjìng"),
    ("Scope", "🔭", "abstract-concepts", "Alcance", "Portée", "Portata", "Escopo", "{範囲|はんい}", "范围", "fànwéi"),
    ("Scale (magnitude)", "📊", "abstract-concepts", "Escala", "Échelle", "Scala", "Escala", "{規模|きぼ}", "规模", "guīmó"),
    ("Dimension", "📐", "abstract-concepts", "Dimensión", "Dimension", "Dimensione", "Dimensão", "{次元|じげん}", "维度", "wéidù"),
    ("Proportion", "🥧", "abstract-concepts", "Proporción", "Proportion", "Proporzione", "Proporção", "{割合|わりあい}", "比例", "bǐlì"),
    ("Ratio", "➗", "abstract-concepts", "Razón (proporción)", "Rapport (ratio)", "Rapporto (ratio)", "Razão (proporção)", "{比率|ひりつ}", "比率", "bǐlǜ"),

    # ---- degree & manner adverbs ----
    ("Barely", "🤏", "degree-adverbs", "Apenas", "À peine", "A malapena", "Mal", "かろうじて", "勉强", "miǎnqiǎng"),
    ("Hardly", "🔻", "degree-adverbs", "Casi no", "Presque pas", "Quasi per niente", "Quase não", "ほとんど〜ない", "几乎不", "jīhū bù"),
    ("Merely", "🔹", "degree-adverbs", "Meramente", "Simplement", "Semplicemente", "Meramente", "{単|たん}に", "仅仅", "jǐnjǐn"),
    ("Utterly", "💯", "degree-adverbs", "Totalmente", "Totalement", "Del tutto", "Totalmente", "{全|まった}く", "完全地", "wánquán de"),
    ("Thoroughly", "🔍", "degree-adverbs", "A fondo", "À fond", "A fondo", "A fundo", "{徹底的|てっていてき}に", "彻底地", "chèdǐ de"),
    ("Fairly", "👌", "degree-adverbs", "Bastante", "Assez", "Abbastanza (piuttosto)", "Razoavelmente", "かなり", "相当", "xiāngdāng"),
    ("Rather", "🤔", "degree-adverbs", "Más bien", "Plutôt", "Piuttosto", "Bastante (um tanto)", "むしろ（かなり）", "颇", "pō"),
    ("Somewhat", "〰️", "degree-adverbs", "Algo", "Quelque peu", "Un po’ (alquanto)", "Um pouco (de certo modo)", "いくぶん", "有点", "yǒudiǎn"),
    ("Slightly", "🤏", "degree-adverbs", "Ligeramente", "Légèrement", "Leggermente", "Ligeiramente", "わずかに", "稍微", "shāowēi"),
    ("Considerably", "📈", "degree-adverbs", "Considerablemente", "Considérablement", "Considerevolmente", "Consideravelmente", "かなり（{大幅|おおはば}に）", "相当大地", "xiāngdāng dà de"),
    ("Significantly", "📊", "degree-adverbs", "Significativamente", "Sensiblement", "Significativamente", "Significativamente", "{著|いちじる}しく", "显著地", "xiǎnzhù de"),
    ("Roughly", "📏", "degree-adverbs", "Aproximadamente", "Environ", "All’incirca", "Aproximadamente", "おおよそ", "大致", "dàzhì"),
    ("Precisely", "🎯", "degree-adverbs", "Precisamente", "Précisément", "Precisamente", "Precisamente", "{正確|せいかく}に", "精确地", "jīngquè de"),
    ("Virtually", "💻", "degree-adverbs", "Prácticamente", "Pratiquement", "Praticamente", "Praticamente", "{事実上|じじつじょう}", "实际上", "shíjì shàng"),
    ("Entirely", "🌐", "degree-adverbs", "Enteramente", "Entièrement", "Interamente", "Inteiramente", "{完全|かんぜん}に", "全然", "quánrán"),
    ("Partially", "🌗", "degree-adverbs", "Parcialmente", "Partiellement", "Parzialmente", "Parcialmente", "{部分的|ぶぶんてき}に", "部分地", "bùfen de"),
    ("Mostly", "📊", "degree-adverbs", "Mayormente", "Surtout (principalement)", "Perlopiù", "Principalmente", "{主|おも}に", "大多", "dàduō"),
    ("Increasingly", "📈", "degree-adverbs", "Cada vez más", "De plus en plus", "Sempre più", "Cada vez mais", "ますます", "越来越", "yuèláiyuè"),
    ("Gradually", "🐢", "degree-adverbs", "Gradualmente", "Progressivement", "Gradualmente", "Gradualmente", "{徐々|じょじょ}に", "逐渐", "zhújiàn"),
    ("Rapidly", "🐆", "degree-adverbs", "Rápidamente", "Rapidement", "Rapidamente", "Rapidamente", "{急速|きゅうそく}に", "迅速地", "xùnsù de"),
    ("Steadily", "📶", "degree-adverbs", "Constantemente", "Régulièrement", "Costantemente", "Constantemente", "{着実|ちゃくじつ}に", "稳步地", "wěnbù de"),
    ("Abruptly", "⚡", "degree-adverbs", "Abruptamente", "Brusquement", "Bruscamente", "Abruptamente", "{突然|とつぜん}（{唐突|とうとつ}に）", "突然地", "tūrán de"),
    ("Ultimately", "🏁", "degree-adverbs", "En última instancia", "En fin de compte", "In definitiva", "Em última análise", "{最終的|さいしゅうてき}に", "最终", "zuìzhōng"),
    ("Altogether", "🧮", "degree-adverbs", "En total", "Au total", "Complessivamente", "Ao todo", "{全部|ぜんぶ}で", "总共（完全）", "zǒnggòng"),
    ("Whatsoever", "🚫", "degree-adverbs", "En absoluto", "Que ce soit", "Di sorta", "Algum (nenhum)", "{全|まった}く（〜ない）", "丝毫", "sīháo"),
    ("Nonetheless", "🧱", "degree-adverbs", "Aun así", "Néanmoins (pourtant)", "Nondimeno", "Ainda assim", "それでもなお", "尽管如此（仍然）", "réngrán"),
    ("Deliberately", "🎯", "degree-adverbs", "Deliberadamente", "Délibérément", "Deliberatamente", "Deliberadamente", "{故意|こい}に", "故意地", "gùyì de"),
    ("Reluctantly", "😒", "degree-adverbs", "De mala gana", "À contrecœur", "Malvolentieri", "A contragosto", "しぶしぶ", "勉强地", "miǎnqiǎng de"),

    # ---- hobbies & making ----
    ("Knitting", "🧶", "hobbies-making", "Tejer (punto)", "Tricot", "Lavoro a maglia", "Tricô", "{編|あ}み{物|もの}", "编织", "biānzhī"),
    ("Sewing", "🪡", "hobbies-making", "Costura (coser)", "Couture (coudre)", "Cucito", "Costura (coser)", "{裁縫|さいほう}", "缝纫", "féngrèn"),
    ("Pottery", "🏺", "hobbies-making", "Cerámica", "Poterie", "Ceramica", "Cerâmica", "{陶芸|とうげい}", "陶艺", "táoyì"),
    ("Woodworking", "🪵", "hobbies-making", "Carpintería", "Menuiserie", "Falegnameria", "Marcenaria", "{木工|もっこう}", "木工", "mùgōng"),
    ("Gardening", "🌱", "hobbies-making", "Jardinería", "Jardinage", "Giardinaggio", "Jardinagem", "ガーデニング", "园艺", "yuányì"),
    ("Birdwatching", "🐦", "hobbies-making", "Observación de aves", "Observation des oiseaux", "Birdwatching", "Observação de aves", "バードウォッチング", "观鸟", "guānniǎo"),
    ("Kayaking", "🛶", "hobbies-making", "Kayak", "Kayak", "Kayak", "Caiaque", "カヤック", "皮划艇", "píhuátǐng"),
    ("Rock climbing", "🧗", "hobbies-making", "Escalada", "Escalade", "Arrampicata", "Escalada", "ロッククライミング", "攀岩", "pānyán"),
    ("Martial arts", "🥋", "hobbies-making", "Artes marciales", "Arts martiaux", "Arti marziali", "Artes marciais", "{武道|ぶどう}", "武术", "wǔshù"),
    ("Boxing", "🥊", "hobbies-making", "Boxeo", "Boxe", "Pugilato", "Boxe", "ボクシング", "拳击", "quánjī"),
    ("Archery", "🏹", "hobbies-making", "Tiro con arco", "Tir à l’arc", "Tiro con l’arco", "Arco e flecha", "アーチェリー", "射箭", "shèjiàn"),
    ("Bowling", "🎳", "hobbies-making", "Bolos", "Bowling", "Bowling", "Boliche", "ボウリング", "保龄球", "bǎolíngqiú"),
    ("Karaoke", "🎤", "hobbies-making", "Karaoke", "Karaoké", "Karaoke", "Karaokê", "カラオケ", "卡拉OK", "kǎlā OK"),
    ("Esports", "🎮", "hobbies-making", "Deportes electrónicos", "E-sport", "Esport", "Esportes eletrônicos", "eスポーツ", "电子竞技", "diànzǐ jìngjì"),
    ("Collectible", "🏆", "hobbies-making", "Objeto de colección", "Objet de collection", "Oggetto da collezione", "Item de coleção", "コレクターズアイテム", "收藏品", "shōucángpǐn"),
    ("Cosplay", "🦸", "hobbies-making", "Cosplay", "Cosplay", "Cosplay", "Cosplay", "コスプレ", "角色扮演", "juésè bànyǎn"),
    ("3D printing", "🖨️", "hobbies-making", "Impresión 3D", "Impression 3D", "Stampa 3D", "Impressão 3D", "3Dプリント", "3D打印", "3D dǎyìn"),
    ("Tabletop role-playing game", "🐉", "hobbies-making", "Juego de rol de mesa", "Jeu de rôle sur table", "Gioco di ruolo da tavolo", "RPG de mesa", "テーブルトークRPG", "桌面角色扮演游戏", "zhuōmiàn juésè bànyǎn yóuxì"),
    ("Miniature (figure)", "🧝", "hobbies-making", "Miniatura", "Figurine", "Miniatura", "Miniatura", "ミニチュア", "微缩模型", "wēisuō móxíng"),
    ("Dice", "🎲", "hobbies-making", "Dados", "Dés", "Dadi", "Dados", "サイコロ", "骰子", "tóuzi"),
    ("Campaign (game)", "🗺️", "hobbies-making", "Campaña (juego)", "Campagne (jeu)", "Campagna (gioco)", "Campanha (jogo)", "キャンペーン（ゲーム）", "战役（游戏）", "zhànyì"),
    ("Hobbyist", "🧑‍🎨", "hobbies-making", "Aficionado (hobby)", "Amateur (passionné)", "Hobbista", "Hobista", "{趣味人|しゅみじん}", "业余爱好者", "yèyú àihàozhě"),
    ("Craft", "✂️", "hobbies-making", "Artesanía", "Artisanat", "Artigianato", "Artesanato", "{工芸|こうげい}", "手工艺", "shǒugōngyì"),
    ("Workbench", "🛠️", "hobbies-making", "Banco de trabajo", "Établi", "Banco da lavoro", "Bancada", "{作業台|さぎょうだい}", "工作台", "gōngzuòtái"),
    ("Glue", "🧴", "hobbies-making", "Pegamento", "Colle", "Colla", "Cola", "{接着剤|せっちゃくざい}", "胶水", "jiāoshuǐ"),
    ("Sandpaper", "📄", "hobbies-making", "Papel de lija", "Papier de verre", "Carta vetrata", "Lixa", "{紙|かみ}やすり", "砂纸", "shāzhǐ"),
    ("Paintbrush", "🖌️", "hobbies-making", "Pincel", "Pinceau", "Pennello", "Pincel", "{絵筆|えふで}", "画笔", "huàbǐ"),
    ("Prototype", "🧪", "hobbies-making", "Prototipo", "Prototype", "Prototipo", "Protótipo", "{試作品|しさくひん}", "原型", "yuánxíng"),
]
