# -*- coding: utf-8 -*-
# C2 vocabulary batch 1 — rare & literary verbs I–V
TIER = 'C2'
TOPICS = {
    'rare-verbs-1': 'Rare Verbs I', 'rare-verbs-2': 'Rare Verbs II', 'rare-verbs-3': 'Rare Verbs III',
    'rare-verbs-4': 'Rare Verbs IV', 'rare-verbs-5': 'Rare Verbs V',
}
WORDS = [
    # ---- rare verbs I ----
    ("To abate", "📉", "rare-verbs-1", "Amainar", "S’apaiser (diminuer)", "Placarsi", "Amainar", "{和|やわ}らぐ", "减弱", "jiǎnruò"),
    ("To abhor", "🤮", "rare-verbs-1", "Aborrecer (detestar)", "Abhorrer", "Aborrire", "Abominar", "{忌|い}み{嫌|きら}う", "憎恶（痛恨）", "tònghèn"),
    ("To abstain", "🚫", "rare-verbs-1", "Abstenerse (de votar)", "S’abstenir (vote)", "Astenersi (voto)", "Abster-se (voto)", "{棄権|きけん}する", "弃权", "qìquán"),
    ("To accentuate", "❗", "rare-verbs-1", "Acentuar", "Accentuer", "Accentuare", "Acentuar", "{強調|きょうちょう}する（{際立|きわだ}たせる）", "突出（强调）", "tūchū"),
    ("To acquiesce", "🙇", "rare-verbs-1", "Consentir (ceder)", "Acquiescer", "Acconsentire", "Consentir (aquiescer)", "{黙|だま}って{従|したが}う", "默许", "mòxǔ"),
    ("To admonish", "☝️", "rare-verbs-1", "Amonestar", "Admonester", "Ammonire", "Admoestar", "{戒|いまし}める", "告诫", "gàojiè"),
    ("To alleviate", "🩹", "rare-verbs-1", "Aliviar", "Soulager (alléger)", "Alleviare", "Aliviar", "{軽減|けいげん}する", "减轻", "jiǎnqīng"),
    ("To amass", "💰", "rare-verbs-1", "Amasar (acumular)", "Amasser", "Ammassare", "Amealhar", "{蓄|たくわ}える", "积聚", "jījù"),
    ("To appease", "🕊️", "rare-verbs-1", "Apaciguar", "Apaiser", "Placare", "Apaziguar", "なだめる", "安抚", "ānfǔ"),
    ("To ascribe", "🏷️", "rare-verbs-1", "Atribuir", "Attribuer (imputer)", "Attribuire (ascrivere)", "Atribuir", "〜に{帰|き}する", "归因于", "guīyīn yú"),
    ("To augment", "➕", "rare-verbs-1", "Aumentar (incrementar)", "Augmenter (accroître)", "Aumentare (accrescere)", "Aumentar (ampliar)", "{増大|ぞうだい}させる", "增大", "zēngdà"),
    ("To avert", "🛡️", "rare-verbs-1", "Evitar (impedir)", "Éviter (conjurer)", "Scongiurare", "Evitar (impedir)", "{回避|かいひ}する（{防|ふせ}ぐ）", "避免（防止）", "bìmiǎn"),
    ("To beckon", "👋", "rare-verbs-1", "Hacer señas", "Faire signe (d’approcher)", "Fare cenno", "Acenar (chamar)", "{手招|てまね}きする", "招手示意", "zhāoshǒu shìyì"),
    ("To belittle", "👇", "rare-verbs-1", "Menospreciar", "Rabaisser", "Sminuire", "Menosprezar", "{見下|みくだ}す（けなす）", "贬低", "biǎndī"),
    ("To bequeath", "📜", "rare-verbs-1", "Legar", "Léguer", "Lasciare in eredità", "Legar", "{遺|のこ}す（{遺贈|いぞう}）", "遗赠", "yízèng"),
    ("To beseech", "🙏", "rare-verbs-1", "Suplicar (implorar)", "Implorer (supplier)", "Supplicare (implorare)", "Suplicar (implorar)", "{懇願|こんがん}する", "恳求（哀求）", "āiqiú"),
    ("To bewilder", "😵", "rare-verbs-1", "Desconcertar", "Déconcerter", "Sconcertare", "Desconcertar", "{当惑|とうわく}させる", "使迷惑", "shǐ míhuò"),
    ("To brandish", "🗡️", "rare-verbs-1", "Blandir", "Brandir", "Brandire", "Brandir", "{振|ふ}りかざす", "挥舞", "huīwǔ"),
    ("To castigate", "🔨", "rare-verbs-1", "Castigar (reprender)", "Fustiger", "Castigare", "Castigar (repreender)", "{厳|きび}しく{叱|しか}る", "严厉批评", "yánlì pīpíng"),
    ("To coalesce", "🔗", "rare-verbs-1", "Fusionarse", "Fusionner (se fondre)", "Fondersi", "Fundir-se", "{合体|がったい}する", "合并（联合）", "liánhé"),
    ("To commend", "🏅", "rare-verbs-1", "Elogiar (encomiar)", "Louer (féliciter)", "Elogiare (lodare)", "Elogiar (louvar)", "{称賛|しょうさん}する", "称赞（表扬）", "biǎoyáng"),
    ("To concede", "🏳️", "rare-verbs-1", "Conceder (admitir)", "Concéder", "Concedere (ammettere)", "Conceder (admitir)", "{譲歩|じょうほ}する", "让步（承认）", "ràngbù"),
    ("To concoct", "🧪", "rare-verbs-1", "Inventar (tramar)", "Concocter", "Escogitare (inventare)", "Inventar (tramar)", "でっち{上|あ}げる", "编造", "biānzào"),
    ("To confer", "🎓", "rare-verbs-1", "Conferir (otorgar)", "Conférer", "Conferire", "Conferir (outorgar)", "{授与|じゅよ}する", "授予", "shòuyǔ"),
    ("To contend", "🗣️", "rare-verbs-1", "Sostener (argumentar)", "Soutenir (affirmer)", "Sostenere (affermare)", "Sustentar (argumentar)", "{主張|しゅちょう}する（{論|ろん}じる）", "主张", "zhǔzhāng"),
    ("To corroborate", "✅", "rare-verbs-1", "Corroborar", "Corroborer", "Corroborare", "Corroborar", "{裏付|うらづ}ける", "证实（佐证）", "zuǒzhèng"),
    ("To aggravate", "🔥", "rare-verbs-1", "Agravar (empeorar)", "Aggraver (irriter)", "Aggravare (peggiorare)", "Agravar (piorar)", "{悪化|あっか}させる（{苛立|いらだ}たせる）", "使恶化", "shǐ èhuà"),
    ("To assail", "⚔️", "rare-verbs-1", "Asaltar (atacar)", "Assaillir", "Assalire", "Assaltar (atacar)", "{攻|せ}め{立|た}てる", "攻击（抨击）", "pēngjī"),
    ("To chastise", "🗯️", "rare-verbs-1", "Reprender (castigar)", "Châtier (réprimander)", "Rimproverare (punire)", "Repreender (castigar)", "{懲|こ}らしめる", "惩戒", "chéngjiè"),
    ("To condescend", "😒", "rare-verbs-1", "Condescender", "Condescendre", "Degnarsi", "Condescender", "{見下|みくだ}した{態度|たいど}をとる", "屈尊", "qūzūn"),

    # ---- rare verbs II ----
    ("To debunk", "🔍", "rare-verbs-2", "Desmentir", "Démystifier", "Sfatare", "Desmascarar", "{暴|あば}く（{誤|あやま}りを）", "揭穿", "jiēchuān"),
    ("To decipher", "🔐", "rare-verbs-2", "Descifrar", "Déchiffrer", "Decifrare", "Decifrar", "{解読|かいどく}する", "破译", "pòyì"),
    ("To decry", "📢", "rare-verbs-2", "Condenar (censurar)", "Dénoncer (décrier)", "Condannare (deplorare)", "Condenar (censurar)", "{公然|こうぜん}と{非難|ひなん}する", "谴责", "qiǎnzé"),
    ("To deem", "⚖️", "rare-verbs-2", "Considerar (juzgar)", "Juger (estimer)", "Ritenere", "Considerar (julgar)", "〜と{見|み}なす", "认为（视为）", "shìwéi"),
    ("To defer", "⏳", "rare-verbs-2", "Aplazar (diferir)", "Différer (reporter)", "Differire", "Adiar (diferir)", "{延期|えんき}する（{延|の}ばす）", "推迟（延期）", "tuīchí"),
    ("To delineate", "📐", "rare-verbs-2", "Delinear", "Délimiter", "Delineare", "Delinear", "{明確|めいかく}に{描|えが}く", "勾画", "gōuhuà"),
    ("To denounce", "🗣️", "rare-verbs-2", "Denunciar", "Dénoncer", "Denunciare", "Denunciar", "{糾弾|きゅうだん}する", "谴责（揭发）", "jiēfā"),
    ("To deplete", "🪫", "rare-verbs-2", "Agotar (mermar)", "Épuiser", "Esaurire", "Esgotar", "{枯渇|こかつ}させる", "耗尽", "hàojìn"),
    ("To deride", "😏", "rare-verbs-2", "Ridiculizar", "Tourner en dérision", "Deridere", "Ridicularizar", "{嘲笑|ちょうしょう}する", "嘲笑", "cháoxiào"),
    ("To despair", "🌑", "rare-verbs-2", "Desesperarse", "Désespérer", "Disperare", "Desesperar", "{絶望|ぜつぼう}する", "绝望（动词）", "juéwàng"),
    ("To detain", "🔒", "rare-verbs-2", "Detener (retener)", "Détenir (retenir)", "Trattenere (detenere)", "Deter", "{拘束|こうそく}する", "拘留（扣押）", "kòuyā"),
    ("To deviate", "↪️", "rare-verbs-2", "Desviarse", "Dévier", "Deviare", "Desviar-se", "{逸脱|いつだつ}する", "偏离", "piānlí"),
    ("To disdain", "😤", "rare-verbs-2", "Desdeñar", "Dédaigner", "Disdegnare", "Desdenhar", "{軽蔑|けいべつ}する（{見下|みくだ}す）", "鄙弃", "bǐqì"),
    ("To disperse", "💨", "rare-verbs-2", "Dispersar", "Disperser", "Disperdere", "Dispersar", "{分散|ぶんさん}させる", "驱散（分散）", "fēnsàn"),
    ("To dissuade", "🛑", "rare-verbs-2", "Disuadir (desaconsejar)", "Dissuader (déconseiller)", "Dissuadere (sconsigliare)", "Dissuadir (desaconselhar)", "{思|おも}いとどまらせる（{説得|せっとく}）", "劝阻", "quànzǔ"),
    ("To divulge", "📢", "rare-verbs-2", "Divulgar (revelar un secreto)", "Divulguer (révéler)", "Divulgare (rivelare)", "Divulgar (revelar)", "{漏|も}らす", "泄露（透露）", "tòulù"),
    ("To dwindle", "📉", "rare-verbs-2", "Menguar", "Diminuer (s’amenuiser)", "Diminuire (ridursi)", "Minguar", "{減|へ}っていく", "逐渐减少", "zhújiàn jiǎnshǎo"),
    ("To elude", "🏃", "rare-verbs-2", "Eludir (escapar)", "Échapper à", "Sfuggire a", "Escapar de", "〜を{逃|のが}れる", "躲避（难以理解）", "duǒbì"),
    ("To emanate", "✨", "rare-verbs-2", "Emanar", "Émaner", "Emanare", "Emanar", "{発|はっ}する", "散发", "sànfā"),
    ("To embellish", "🎀", "rare-verbs-2", "Embellecer (adornar)", "Enjoliver", "Abbellire", "Embelezar (enfeitar)", "{飾|かざ}り{立|た}てる", "润饰", "rùnshì"),
    ("To encompass", "🌐", "rare-verbs-2", "Abarcar", "Englober", "Comprendere (abbracciare)", "Abranger", "{包含|ほうがん}する", "涵盖", "hángài"),
    ("To engender", "🌱", "rare-verbs-2", "Engendrar", "Engendrer", "Generare (suscitare)", "Engendrar", "{生|しょう}じさせる", "引起（产生）", "yǐnqǐ"),
    ("To enlighten", "💡", "rare-verbs-2", "Iluminar (instruir)", "Éclairer (instruire)", "Illuminare (istruire)", "Esclarecer (instruir)", "{啓発|けいはつ}する", "启发", "qǐfā"),
    ("To enthrall", "🤩", "rare-verbs-2", "Cautivar", "Captiver", "Affascinare (incantare)", "Cativar", "{魅了|みりょう}する", "迷住", "mízhù"),
    ("To entice", "🍬", "rare-verbs-2", "Tentar (atraer)", "Attirer (allécher)", "Allettare", "Atrair (seduzir)", "{誘|さそ}う（{誘惑|ゆうわく}）", "引诱", "yǐnyòu"),
    ("To envision", "🔮", "rare-verbs-2", "Imaginar (visualizar)", "Envisager (imaginer)", "Immaginare (prefigurare)", "Vislumbrar", "{思|おも}い{描|えが}く", "展望", "zhǎnwàng"),
    ("To evade", "🌀", "rare-verbs-2", "Evadir", "Éluder (se soustraire à)", "Eludere", "Evadir", "{逃|のが}れる（{回避|かいひ}）", "逃避", "táobì"),
    ("To exalt", "👑", "rare-verbs-2", "Exaltar", "Exalter", "Esaltare", "Exaltar", "{称|たた}える", "颂扬", "sòngyáng"),
    ("To expedite", "⚡", "rare-verbs-2", "Acelerar (agilizar)", "Accélérer (expédier)", "Accelerare (sbrigare)", "Acelerar (agilizar)", "{迅速|じんそく}に{処理|しょり}する", "加快", "jiākuài"),
    ("To extol", "🏆", "rare-verbs-2", "Ensalzar", "Vanter (louer)", "Decantare", "Enaltecer", "{絶賛|ぜっさん}する", "赞美", "zànměi"),

    # ---- rare verbs III ----
    ("To fabricate", "🧵", "rare-verbs-3", "Fabricar (inventar)", "Fabriquer (inventer)", "Fabbricare (inventare)", "Fabricar (inventar)", "{捏造|ねつぞう}する", "捏造", "niēzào"),
    ("To falter", "🫨", "rare-verbs-3", "Vacilar (flaquear)", "Vaciller (fléchir)", "Vacillare", "Vacilar (fraquejar)", "よろめく（{揺|ゆ}らぐ）", "动摇（踌躇）", "chóuchú"),
    ("To feign", "🎭", "rare-verbs-3", "Fingir (simular)", "Feindre", "Fingere (simulare)", "Fingir (simular)", "{装|よそお}う", "假装（伪装）", "wěizhuāng"),
    ("To flourish", "🌸", "rare-verbs-3", "Florecer", "Prospérer (fleurir)", "Fiorire (prosperare)", "Florescer", "{繁栄|はんえい}する（{栄|さか}える）", "繁荣", "fánróng"),
    ("To forfeit", "🏳️", "rare-verbs-3", "Perder (por incumplimiento)", "Perdre (par forfait)", "Perdere (per rinuncia)", "Perder (por infração)", "{失|うしな}う（{没収|ぼっしゅう}）", "丧失（被没收）", "sàngshī"),
    ("To forgo", "🙅", "rare-verbs-3", "Renunciar (prescindir)", "Renoncer à (se passer de)", "Rinunciare (fare a meno)", "Abrir mão de", "{見送|みおく}る（{断念|だんねん}）", "放弃（不要）", "fàngqì"),
    ("To galvanize", "⚡", "rare-verbs-3", "Galvanizar (impulsar)", "Galvaniser", "Galvanizzare", "Galvanizar", "{奮|ふる}い{立|た}たせる", "激励（振奋）", "zhènfèn"),
    ("To garner", "🧺", "rare-verbs-3", "Cosechar (obtener)", "Récolter (recueillir)", "Raccogliere (ottenere)", "Angariar", "{集|あつ}める（{獲得|かくとく}）", "获得（收集）", "huòdé"),
    ("To gloat", "😏", "rare-verbs-3", "Regodearse", "Jubiler (se réjouir méchamment)", "Gongolare", "Regozijar-se", "ほくそ{笑|え}む", "幸灾乐祸", "xìngzāi lèhuò"),
    ("To grapple", "🤼", "rare-verbs-3", "Lidiar (forcejear)", "Se débattre avec", "Lottare (fare i conti)", "Lutar (lidar)", "{取|と}っ{組|く}む", "努力应对", "nǔlì yìngduì"),
    ("To harness", "🐎", "rare-verbs-3", "Aprovechar (canalizar)", "Exploiter (canaliser)", "Sfruttare (imbrigliare)", "Aproveitar (canalizar)", "{活用|かつよう}する（{制御|せいぎょ}）", "利用（驾驭）", "jiàyù"),
    ("To heed", "👂", "rare-verbs-3", "Hacer caso", "Tenir compte de", "Dare ascolto", "Dar ouvidos", "{心|こころ}に{留|と}める", "留意", "liúyì"),
    ("To hoard", "📦", "rare-verbs-3", "Acaparar", "Amasser (thésauriser)", "Accumulare (fare incetta)", "Estocar (acumular)", "{溜|た}め{込|こ}む", "囤积", "túnjī"),
    ("To impart", "🎁", "rare-verbs-3", "Impartir (transmitir)", "Transmettre (communiquer)", "Impartire (trasmettere)", "Transmitir (dar)", "{授|さず}ける", "传授", "chuánshòu"),
    ("To implore", "🙏", "rare-verbs-3", "Implorar", "Implorer", "Implorare", "Implorar", "{哀願|あいがん}する", "恳求", "kěnqiú"),
    ("To incite", "🔥", "rare-verbs-3", "Incitar", "Inciter (attiser)", "Incitare", "Incitar", "{煽|あお}る", "煽动（激起）", "jīqǐ"),
    ("To inhibit", "🚫", "rare-verbs-3", "Inhibir", "Inhiber", "Inibire", "Inibir", "{抑制|よくせい}する（{阻害|そがい}）", "抑制", "yìzhì"),
    ("To instill", "💉", "rare-verbs-3", "Inculcar", "Inculquer", "Inculcare", "Incutir", "{植|う}え{付|つ}ける", "灌输", "guànshū"),
    ("To intercede", "🤝", "rare-verbs-3", "Interceder", "Intercéder", "Intercedere", "Interceder", "{仲裁|ちゅうさい}に{入|はい}る", "说情", "shuōqíng"),
    ("To intimidate", "😨", "rare-verbs-3", "Intimidar", "Intimider", "Intimidire", "Intimidar", "{威嚇|いかく}する", "恐吓", "kǒnghè"),
    ("To jeopardize", "⚠️", "rare-verbs-3", "Poner en peligro", "Compromettre (mettre en péril)", "Mettere a repentaglio", "Pôr em risco", "{危険|きけん}にさらす", "危及", "wēijí"),
    ("To languish", "🥀", "rare-verbs-3", "Languidecer", "Languir", "Languire", "Definhar", "{衰|おとろ}える", "萎靡", "wěimí"),
    ("To lure", "🎣", "rare-verbs-3", "Atraer (con engaño)", "Attirer (appâter)", "Adescare", "Atrair (iscar)", "おびき{寄|よ}せる", "引诱（诱骗）", "yòupiàn"),
    ("To marvel", "🤩", "rare-verbs-3", "Maravillarse", "S’émerveiller", "Meravigliarsi", "Maravilhar-se", "{驚嘆|きょうたん}する", "惊叹", "jīngtàn"),
    ("To meander", "🐍", "rare-verbs-3", "Serpentear", "Serpenter", "Serpeggiare", "Serpentear", "{曲|ま}がりくねる", "蜿蜒", "wānyán"),
    ("To muster", "💪", "rare-verbs-3", "Reunir (fuerzas)", "Rassembler (son courage)", "Raccogliere (le forze)", "Reunir (forças)", "{奮|ふる}い{起|お}こす", "鼓起（勇气）", "gǔqǐ"),
    ("To obliterate", "💥", "rare-verbs-3", "Arrasar (borrar)", "Anéantir", "Annientare", "Obliterar", "{消|け}し{去|さ}る", "彻底摧毁", "chèdǐ cuīhuǐ"),
    ("To oscillate", "〰️", "rare-verbs-3", "Oscilar", "Osciller", "Oscillare", "Oscilar", "{揺|ゆ}れ{動|うご}く", "摇摆", "yáobǎi"),
    ("To ostracize", "🚪", "rare-verbs-3", "Marginar (condenar al ostracismo)", "Ostraciser", "Ostracizzare", "Ostracizar", "{仲間外|なかまはず}れにする", "排斥", "páichì"),
    ("To perpetuate", "♾️", "rare-verbs-3", "Perpetuar", "Perpétuer", "Perpetuare", "Perpetuar", "{永続|えいぞく}させる", "使永存（延续）", "yánxù"),

    # ---- rare verbs IV ----
    ("To permeate", "💧", "rare-verbs-4", "Impregnar (permear)", "Imprégner (pénétrer)", "Permeare", "Permear", "{浸透|しんとう}する", "渗透", "shèntòu"),
    ("To plummet", "📉", "rare-verbs-4", "Desplomarse", "Chuter (s’effondrer)", "Precipitare", "Despencar", "{急落|きゅうらく}する", "暴跌", "bàodiē"),
    ("To ponder", "🤔", "rare-verbs-4", "Reflexionar (meditar)", "Méditer (réfléchir)", "Ponderare", "Ponderar", "{熟考|じゅっこう}する（{思|おも}い{巡|めぐ}らす）", "沉思", "chénsī"),
    ("To preach", "📖", "rare-verbs-4", "Predicar", "Prêcher", "Predicare", "Pregar", "{説教|せっきょう}する", "说教", "shuōjiào"),
    ("To procure", "📦", "rare-verbs-4", "Procurar (conseguir)", "Se procurer", "Procurare", "Obter (adquirir)", "{調達|ちょうたつ}する", "采购（获取）", "cǎigòu"),
    ("To proliferate", "🦠", "rare-verbs-4", "Proliferar", "Proliférer", "Proliferare", "Proliferar", "{急増|きゅうぞう}する", "激增", "jīzēng"),
    ("To propel", "🚀", "rare-verbs-4", "Propulsar", "Propulser", "Spingere (propellere)", "Impulsionar", "{推進|すいしん}する", "推动", "tuīdòng"),
    ("To quell", "🧯", "rare-verbs-4", "Sofocar (reprimir)", "Réprimer (étouffer)", "Sedare", "Sufocar (reprimir)", "{鎮|しず}める", "平息", "píngxī"),
    ("To ratify", "✍️", "rare-verbs-4", "Ratificar", "Ratifier", "Ratificare", "Ratificar", "{批准|ひじゅん}する", "批准（条约）", "pīzhǔn"),
    ("To rebuke", "👎", "rare-verbs-4", "Reprender", "Réprimander", "Rimproverare", "Repreender", "{叱責|しっせき}する", "斥责", "chìzé"),
    ("To rebut", "🛡️", "rare-verbs-4", "Rebatir", "Réfuter", "Ribattere", "Rebater", "{反論|はんろん}する", "反驳", "fǎnbó"),
    ("To recant", "🔄", "rare-verbs-4", "Retractarse", "Se rétracter", "Ritrattare", "Retratar-se", "{撤回|てっかい}する", "撤回（改口）", "gǎikǒu"),
    ("To redeem", "🎟️", "rare-verbs-4", "Redimir (canjear)", "Racheter (échanger)", "Riscattare", "Redimir (resgatar)", "{償|つぐな}う（{引|ひ}き{換|か}える）", "赎回（兑换）", "shúhuí"),
    ("To refute", "❌", "rare-verbs-4", "Refutar", "Réfuter (démentir)", "Confutare", "Refutar", "{論破|ろんぱ}する", "驳斥", "bóchì"),
    ("To relish", "😋", "rare-verbs-4", "Saborear (disfrutar)", "Savourer", "Assaporare (gustarsi)", "Saborear (apreciar)", "{満喫|まんきつ}する", "享受（品味）", "pǐnwèi"),
    ("To renounce", "🙅", "rare-verbs-4", "Renunciar (abjurar)", "Renoncer (abjurer)", "Rinnegare (rinunciare)", "Renunciar (abjurar)", "{放棄|ほうき}する（{断|た}つ）", "宣布放弃", "xuānbù fàngqì"),
    ("To replenish", "🔄", "rare-verbs-4", "Reponer", "Réapprovisionner", "Rifornire", "Repor", "{補充|ほじゅう}する", "补充", "bǔchōng"),
    ("To reprimand", "🗯️", "rare-verbs-4", "Amonestar (reprender)", "Réprimander (blâmer)", "Ammonire (rimproverare)", "Advertir (repreender)", "{戒告|かいこく}する", "训斥", "xùnchì"),
    ("To repudiate", "🚫", "rare-verbs-4", "Repudiar", "Répudier", "Ripudiare", "Repudiar", "{拒否|きょひ}する（{否認|ひにん}）", "否认（拒绝接受）", "jùjué jiēshòu"),
    ("To resonate", "🔔", "rare-verbs-4", "Resonar", "Résonner", "Risuonare", "Ressoar", "{共鳴|きょうめい}する", "引起共鸣", "yǐnqǐ gòngmíng"),
    ("To retaliate", "⚔️", "rare-verbs-4", "Tomar represalias", "Riposter", "Vendicarsi (ritorsione)", "Retaliar", "{報復|ほうふく}する", "报复", "bàofù"),
    ("To revere", "🙇", "rare-verbs-4", "Reverenciar", "Révérer", "Riverire", "Reverenciar", "{崇敬|すうけい}する", "尊崇", "zūnchóng"),
    ("To revoke", "🗑️", "rare-verbs-4", "Revocar", "Révoquer", "Revocare", "Revogar", "{取|と}り{消|け}す", "撤销", "chèxiāo"),
    ("To saturate", "💧", "rare-verbs-4", "Saturar", "Saturer", "Saturare", "Saturar", "{飽和|ほうわ}させる", "使饱和", "shǐ bǎohé"),
    ("To scorn", "😒", "rare-verbs-4", "Despreciar (desdeñar)", "Mépriser (dédaigner)", "Disprezzare (schernire)", "Desprezar (escarnecer)", "あざける", "轻蔑", "qīngmiè"),
    ("To squander", "💸", "rare-verbs-4", "Despilfarrar", "Gaspiller (dilapider)", "Sperperare", "Esbanjar", "{浪費|ろうひ}する", "挥霍", "huīhuò"),
    ("To stagnate", "🪨", "rare-verbs-4", "Estancarse", "Stagner", "Ristagnare", "Estagnar", "{停滞|ていたい}する", "停滞", "tíngzhì"),
    ("To stifle", "🤐", "rare-verbs-4", "Sofocar (reprimir)", "Étouffer (réprimer)", "Soffocare (reprimere)", "Sufocar (reprimir)", "{抑|おさ}え{込|こ}む", "扼杀（压制）", "èshā"),
    ("To subside", "📉", "rare-verbs-4", "Amainar (remitir)", "S’atténuer (retomber)", "Placarsi (calare)", "Diminuir (ceder)", "{治|おさ}まる", "平息（消退）", "xiāotuì"),
    ("To succumb", "🏳️", "rare-verbs-4", "Sucumbir", "Succomber", "Soccombere", "Sucumbir", "{屈|くっ}する", "屈服", "qūfú"),

    # ---- rare verbs V ----
    ("To supplant", "🔄", "rare-verbs-5", "Suplantar", "Supplanter", "Soppiantare", "Suplantar", "{取|と}って{代|か}わる", "取代", "qǔdài"),
    ("To surmise", "🤔", "rare-verbs-5", "Conjeturar", "Conjecturer", "Supporre (arguire)", "Conjecturar", "{推測|すいそく}する（{憶測|おくそく}）", "推测", "tuīcè"),
    ("To swindle", "🎭", "rare-verbs-5", "Estafar", "Escroquer", "Truffare", "Trapacear", "だまし{取|と}る", "诈骗（骗取）", "piànqǔ"),
    ("To tarnish", "🌫️", "rare-verbs-5", "Empañar (manchar)", "Ternir", "Offuscare", "Manchar (macular)", "{傷|きず}つける（{名誉|めいよ}を）", "玷污", "diànwū"),
    ("To thwart", "🛑", "rare-verbs-5", "Frustrar (impedir)", "Contrecarrer", "Sventare", "Frustrar (impedir)", "{阻止|そし}する（くじく）", "挫败", "cuòbài"),
    ("To transcend", "🌌", "rare-verbs-5", "Trascender", "Transcender", "Trascendere", "Transcender", "{超越|ちょうえつ}する", "超越（超脱）", "chāoyuè"),
    ("To unravel", "🧶", "rare-verbs-5", "Desenmarañar", "Démêler", "Districare (svelare)", "Desvendar", "{解|と}き{明|あ}かす", "解开", "jiěkāi"),
    ("To usurp", "👑", "rare-verbs-5", "Usurpar", "Usurper", "Usurpare", "Usurpar", "{簒奪|さんだつ}する", "篡夺", "cuànduó"),
    ("To vanquish", "⚔️", "rare-verbs-5", "Vencer (derrotar)", "Vaincre", "Sconfiggere", "Vencer (derrotar)", "{打|う}ち{負|ま}かす", "征服（击败）", "zhēngfú"),
    ("To venerate", "🛐", "rare-verbs-5", "Venerar", "Vénérer", "Venerare", "Venerar", "{崇|あが}める", "崇敬", "chóngjìng"),
    ("To vilify", "🗯️", "rare-verbs-5", "Vilipendiar", "Diffamer (vilipender)", "Diffamare", "Vilipendiar", "{中傷|ちゅうしょう}する", "诽谤（诋毁）", "dǐhuǐ"),
    ("To wane", "🌘", "rare-verbs-5", "Menguar (decaer)", "Décliner (décroître)", "Calare (declinare)", "Minguar (declinar)", "{衰|おとろ}える（{欠|か}ける）", "衰落（亏缺）", "shuāiluò"),
    ("To wield", "🗡️", "rare-verbs-5", "Empuñar (ejercer)", "Manier (exercer)", "Impugnare (esercitare)", "Empunhar (exercer)", "{振|ふ}るう", "运用（挥舞）", "yùnyòng"),
    ("To writhe", "🌀", "rare-verbs-5", "Retorcerse", "Se tordre", "Contorcersi", "Contorcer-se", "{身|み}をよじる", "扭动", "niǔdòng"),
    ("To yearn", "🌙", "rare-verbs-5", "Anhelar", "Aspirer à (languir)", "Bramare", "Ansiar", "{切望|せつぼう}する", "渴望", "kěwàng"),
    ("To beget", "🌱", "rare-verbs-5", "Engendrar (originar)", "Engendrer (produire)", "Generare (produrre)", "Gerar (originar)", "{生|う}む（{引|ひ}き{起|お}こす）", "引起（产生）", "chǎnshēng"),
    ("To besiege", "🏰", "rare-verbs-5", "Asediar", "Assiéger", "Assediare", "Sitiar", "{包囲|ほうい}する", "围攻", "wéigōng"),
    ("To cajole", "🍯", "rare-verbs-5", "Engatusar", "Cajoler (amadouer)", "Blandire", "Bajular (persuadir)", "{甘言|かんげん}で{誘|さそ}う", "哄骗", "hǒngpiàn"),
    ("To coax", "🤲", "rare-verbs-5", "Persuadir (con halagos)", "Amadouer", "Persuadere (con dolcezza)", "Persuadir (com jeito)", "なだめすかす", "劝诱", "quànyòu"),
    ("To deplore", "😞", "rare-verbs-5", "Deplorar", "Déplorer", "Deplorare", "Deplorar", "{嘆|なげ}く", "痛惜", "tòngxī"),
    ("To disparage", "👎", "rare-verbs-5", "Menospreciar (denigrar)", "Dénigrer", "Denigrare", "Depreciar (denegrir)", "{見下|みくだ}す（{中傷|ちゅうしょう}）", "贬损", "biǎnsǔn"),
    ("To exhort", "📣", "rare-verbs-5", "Exhortar", "Exhorter", "Esortare", "Exortar", "{熱心|ねっしん}に{勧|すす}める", "劝勉", "quànmiǎn"),
    ("To foment", "🔥", "rare-verbs-5", "Fomentar (incitar)", "Fomenter", "Fomentare", "Fomentar (incitar)", "{扇動|せんどう}する（{助長|じょちょう}）", "煽动", "shāndòng"),
    ("To indulge", "🍰", "rare-verbs-5", "Darse el gusto", "Se laisser aller à", "Concedersi", "Entregar-se a", "{耽|ふけ}る", "放纵", "fàngzòng"),
    ("To placate", "🕊️", "rare-verbs-5", "Aplacar", "Apaiser (calmer)", "Placare (rabbonire)", "Aplacar", "{懐柔|かいじゅう}する", "安抚（平息）", "ānfǔ"),
    ("To preempt", "⏩", "rare-verbs-5", "Adelantarse a", "Devancer", "Prevenire (anticipare)", "Antecipar-se a", "{先手|せんて}を{打|う}つ", "先发制人", "xiānfā zhìrén"),
    ("To rescind", "🗑️", "rare-verbs-5", "Rescindir", "Annuler (résilier)", "Rescindere", "Rescindir", "{取|と}り{消|け}す（{契約|けいやく}を）", "废除（撤销）", "fèichú"),
    ("To stymie", "🚧", "rare-verbs-5", "Obstaculizar (bloquear)", "Contrarier (bloquer)", "Ostacolare (bloccare)", "Obstruir (bloquear)", "{妨害|ぼうがい}する", "阻挠", "zǔnáo"),
    ("To vindicate", "⚖️", "rare-verbs-5", "Vindicar (reivindicar)", "Disculper (justifier)", "Scagionare (dare ragione)", "Vindicar (justificar)", "{正当性|せいとうせい}を{証明|しょうめい}する", "证明无辜", "zhèngmíng wúgū"),
    ("To evince", "👁️", "rare-verbs-5", "Manifestar (evidenciar)", "Manifester (témoigner de)", "Manifestare (dimostrare)", "Evidenciar", "{示|しめ}す（{明|あき}らかに）", "表明（显示）", "xiǎnshì"),
]
