# -*- coding: utf-8 -*-
# B1 vocabulary batch 2 — health & fitness, food culture, housing & living, consumer life, verbs V
TIER = 'B1'
TOPICS = {
    'health-fitness': 'Health & Fitness', 'food-culture': 'Food Culture', 'housing': 'Housing & Living',
    'consumer': 'Consumer Life', 'verbs-5': 'Verbs V',
}
WORDS = [
    # ---- health & fitness ----
    ("To work out", "🏋️", "health-fitness", "Hacer ejercicio (entrenar)", "Faire de la musculation", "Allenarsi (palestra)", "Malhar", "{筋|きん}トレする", "健身", "jiànshēn"),
    ("Diet", "🥗", "health-fitness", "Dieta", "Régime", "Dieta", "Dieta", "ダイエット", "饮食", "yǐnshí"),
    ("To lose weight", "📉", "health-fitness", "Bajar de peso", "Perdre du poids", "Dimagrire", "Emagrecer", "{痩|や}せる", "减肥", "jiǎnféi"),
    ("To gain weight", "📈", "health-fitness", "Subir de peso", "Prendre du poids", "Ingrassare", "Engordar", "{太|ふと}る", "增重", "zēngzhòng"),
    ("Muscle", "💪", "health-fitness", "Músculo", "Muscle", "Muscolo", "Músculo", "{筋肉|きんにく}", "肌肉", "jīròu"),
    ("To stretch", "🤸", "health-fitness", "Estirar", "S’étirer", "Fare stretching", "Alongar", "ストレッチする", "拉伸", "lāshēn"),
    ("To warm up", "🔥", "health-fitness", "Calentar", "S’échauffer", "Riscaldarsi", "Aquecer", "ウォームアップする", "热身", "rèshēn"),
    ("Calories", "🔢", "health-fitness", "Calorías", "Calories", "Calorie", "Calorias", "カロリー", "卡路里", "kǎlùlǐ"),
    ("Protein", "🥩", "health-fitness", "Proteína", "Protéine", "Proteina", "Proteína", "タンパク{質|しつ}", "蛋白质", "dànbáizhì"),
    ("To breathe", "🌬️", "health-fitness", "Respirar", "Respirer", "Respirare", "Respirar", "{呼吸|こきゅう}する", "呼吸", "hūxī"),
    ("Heartbeat", "💓", "health-fitness", "Latido", "Battement de cœur", "Battito", "Batimento", "{鼓動|こどう}", "心跳", "xīntiào"),
    ("To sweat", "💦", "health-fitness", "Sudar", "Transpirer", "Sudare", "Suar", "{汗|あせ}をかく", "出汗", "chūhàn"),
    ("To recover", "🩹", "health-fitness", "Recuperarse", "Se remettre", "Riprendersi", "Recuperar-se", "{回復|かいふく}する", "康复", "kāngfù"),
    ("Sprain", "🦶", "health-fitness", "Esguince", "Entorse", "Distorsione", "Torção", "{捻挫|ねんざ}", "扭伤", "niǔshāng"),
    ("To faint", "😵", "health-fitness", "Desmayarse", "S’évanouir", "Svenire", "Desmaiar", "{気|き}を{失|うしな}う", "晕倒", "yūndǎo"),
    ("Dizzy", "💫", "health-fitness", "Mareado", "Étourdi", "Stordito", "Tonto", "めまいがする", "头晕", "tóuyūn"),
    ("Nausea", "🤢", "health-fitness", "Náuseas", "Nausée", "Nausea", "Náusea", "{吐|は}き{気|け}", "恶心", "ěxin"),
    ("To sneeze", "🤧", "health-fitness", "Estornudar", "Éternuer", "Starnutire", "Espirrar", "くしゃみをする", "打喷嚏", "dǎ pēntì"),
    ("Symptom", "🩺", "health-fitness", "Síntoma", "Symptôme", "Sintomo", "Sintoma", "{症状|しょうじょう}", "症状", "zhèngzhuàng"),
    ("Vaccine", "💉", "health-fitness", "Vacuna", "Vaccin", "Vaccino", "Vacina", "ワクチン", "疫苗", "yìmiáo"),
    ("Checkup", "📋", "health-fitness", "Revisión médica", "Bilan de santé", "Controllo", "Check-up", "{健康診断|けんこうしんだん}", "体检", "tǐjiǎn"),
    ("Therapy", "🛋️", "health-fitness", "Terapia", "Thérapie", "Terapia", "Terapia", "セラピー", "治疗", "zhìliáo"),
    ("To quit smoking", "🚭", "health-fitness", "Dejar de fumar", "Arrêter de fumer", "Smettere di fumare", "Parar de fumar", "{禁煙|きんえん}する", "戒烟", "jièyān"),
    ("Wellbeing", "🌿", "health-fitness", "Bienestar", "Bien-être", "Benessere", "Bem-estar", "{健康|けんこう}と{幸福|こうふく}", "幸福感", "xìngfúgǎn"),
    ("Mental health", "🧠", "health-fitness", "Salud mental", "Santé mentale", "Salute mentale", "Saúde mental", "{心|こころ}の{健康|けんこう}", "心理健康", "xīnlǐ jiànkāng"),
    ("To meditate", "🧘", "health-fitness", "Meditar", "Méditer", "Meditare", "Meditar", "{瞑想|めいそう}する", "冥想", "míngxiǎng"),
    ("Insomnia", "🌙", "health-fitness", "Insomnio", "Insomnie", "Insonnia", "Insônia", "{不眠症|ふみんしょう}", "失眠", "shīmián"),
    ("Energy", "⚡", "health-fitness", "Energía", "Énergie", "Energia", "Energia", "エネルギー", "精力", "jīnglì"),
    ("Painkiller", "💊", "health-fitness", "Analgésico", "Antidouleur", "Antidolorifico", "Analgésico", "{痛|いた}み{止|ど}め", "止痛药", "zhǐtòngyào"),
    ("Sore", "😣", "health-fitness", "Adolorido", "Endolori", "Dolorante", "Dolorido", "{筋肉痛|きんにくつう}", "酸痛", "suāntòng"),

    # ---- food culture ----
    ("Cuisine", "🍽️", "food-culture", "Cocina (gastronomía)", "Cuisine (gastronomie)", "Cucina (gastronomia)", "Culinária", "{料理|りょうり}（{各国|かっこく}の）", "菜系", "càixì"),
    ("Flavor", "👅", "food-culture", "Sabor", "Saveur", "Sapore", "Sabor", "{味|あじ}", "味道", "wèidào"),
    ("Homemade", "🏠", "food-culture", "Casero", "Fait maison", "Fatto in casa", "Caseiro", "{手作|てづく}り", "自制", "zìzhì"),
    ("Mild", "🌱", "food-culture", "Suave (no picante)", "Doux (pas épicé)", "Delicato", "Suave (não picante)", "{辛|から}くない", "清淡", "qīngdàn"),
    ("To season", "🧂", "food-culture", "Sazonar", "Assaisonner", "Condire", "Temperar", "{味付|あじつ}けする", "调味", "tiáowèi"),
    ("Portion", "🍛", "food-culture", "Porción", "Portion", "Porzione", "Porção", "{一人前|いちにんまえ}", "一份", "yí fèn"),
    ("Leftovers", "🥡", "food-culture", "Sobras", "Restes", "Avanzi", "Sobras", "{残|のこ}り{物|もの}", "剩菜", "shèngcài"),
    ("Street food", "🌮", "food-culture", "Comida callejera", "Cuisine de rue", "Cibo di strada", "Comida de rua", "{屋台|やたい}の{食|た}べ{物|もの}", "街头小吃", "jiētóu xiǎochī"),
    ("Specialty", "⭐", "food-culture", "Especialidad", "Spécialité", "Specialità", "Especialidade", "{名物|めいぶつ}", "特色菜", "tèsè cài"),
    ("To treat (pay for someone)", "🎁", "food-culture", "Invitar (pagar)", "Offrir (payer)", "Offrire", "Pagar para alguém", "おごる", "请客", "qǐngkè"),
    ("To split the bill", "➗", "food-culture", "Pagar a medias", "Partager l’addition", "Fare alla romana", "Rachar a conta", "{割|わ}り{勘|かん}にする", "AA制", "AA zhì"),
    ("Tasty", "😋", "food-culture", "Sabroso", "Savoureux", "Gustoso", "Gostoso", "おいしい（{風味|ふうみ}がいい）", "美味", "měiwèi"),
    ("Disgusting", "🤮", "food-culture", "Asqueroso", "Dégoûtant", "Disgustoso", "Nojento", "まずい", "恶心（难吃）", "nánchī"),
    ("To chew", "😬", "food-culture", "Masticar", "Mâcher", "Masticare", "Mastigar", "{噛|か}む", "咀嚼", "jǔjué"),
    ("To swallow", "😮", "food-culture", "Tragar", "Avaler", "Ingoiare", "Engolir", "{飲|の}み{込|こ}む", "吞", "tūn"),
    ("Appetite", "🍴", "food-culture", "Apetito", "Appétit", "Appetito", "Apetite", "{食欲|しょくよく}", "食欲", "shíyù"),
    ("Craving", "🍫", "food-culture", "Antojo", "Envie", "Voglia", "Desejo", "{無性|むしょう}に{食|た}べたい{気持|きも}ち", "嘴馋", "zuǐchán"),
    ("I’m full", "🈵", "food-culture", "Estoy lleno", "Je n’ai plus faim", "Sono pieno", "Estou cheio", "お{腹|なか}がいっぱい", "我饱了", "wǒ bǎo le"),
    ("To skip a meal", "⏭️", "food-culture", "Saltarse una comida", "Sauter un repas", "Saltare un pasto", "Pular uma refeição", "{食事|しょくじ}を{抜|ぬ}く", "不吃饭", "bù chīfàn"),
    ("Brunch", "🥞", "food-culture", "Brunch", "Brunch", "Brunch", "Brunch", "ブランチ", "早午餐", "zǎowǔcān"),
    ("To grab a bite", "🥪", "food-culture", "Comer algo rápido", "Manger un morceau", "Mangiare un boccone", "Comer alguma coisa", "{軽|かる}く{食|た}べる", "随便吃点", "suíbiàn chī diǎn"),
    ("A toast", "🥂", "food-culture", "Un brindis", "Un toast", "Un brindisi", "Um brinde", "{乾杯|かんぱい}", "祝酒", "zhùjiǔ"),
    ("Vegan", "🌱", "food-culture", "Vegano", "Végan", "Vegano", "Vegano", "ヴィーガン", "纯素", "chúnsù"),
    ("Gluten-free", "🌾", "food-culture", "Sin gluten", "Sans gluten", "Senza glutine", "Sem glúten", "グルテンフリー", "无麸质", "wú fūzhì"),
    ("Organic", "🍃", "food-culture", "Orgánico", "Bio", "Biologico", "Orgânico", "オーガニック", "有机", "yǒujī"),
    ("Recipe book", "📕", "food-culture", "Libro de recetas", "Livre de recettes", "Ricettario", "Livro de receitas", "{料理本|りょうりぼん}", "食谱书", "shípǔ shū"),
    ("Chopsticks", "🥢", "food-culture", "Palillos", "Baguettes", "Bacchette", "Pauzinhos", "お{箸|はし}", "筷子", "kuàizi"),
    ("Napkin", "🧻", "food-culture", "Servilleta", "Serviette (de table)", "Tovagliolo", "Guardanapo", "ナプキン", "餐巾", "cānjīn"),
    ("Reservation for dinner", "🍽️", "food-culture", "Reserva para cenar", "Réservation pour dîner", "Prenotazione per cena", "Reserva para o jantar", "{夕食|ゆうしょく}の{予約|よやく}", "晚餐预订", "wǎncān yùdìng"),
    ("Buffet", "🍱", "food-culture", "Bufé", "Buffet", "Buffet", "Bufê", "ビュッフェ", "自助餐", "zìzhùcān"),

    # ---- housing & living ----
    ("Mortgage", "🏦", "housing", "Hipoteca", "Prêt immobilier", "Mutuo", "Financiamento", "{住宅|じゅうたく}ローン", "房贷", "fángdài"),
    ("To own", "🔑", "housing", "Poseer", "Posséder", "Possedere", "Possuir", "{所有|しょゆう}する", "拥有", "yōngyǒu"),
    ("Lease", "📄", "housing", "Contrato de alquiler", "Bail", "Contratto d’affitto", "Contrato de aluguel", "{賃貸契約|ちんたいけいやく}", "租约", "zūyuē"),
    ("Security deposit", "💰", "housing", "Depósito", "Caution", "Cauzione", "Caução", "{敷金|しききん}", "押金", "yājīn"),
    ("Utilities", "💡", "housing", "Servicios", "Charges", "Utenze", "Contas de casa", "{光熱費|こうねつひ}", "水电费", "shuǐdiànfèi"),
    ("Cozy", "🕯️", "housing", "Acogedor", "Douillet", "Accogliente", "Aconchegante", "{居心地|いごこち}がいい", "温馨", "wēnxīn"),
    ("Spacious", "🏟️", "housing", "Espacioso", "Spacieux", "Spazioso", "Espaçoso", "{広々|ひろびろ}とした", "宽敞", "kuānchang"),
    ("To decorate", "🖼️", "housing", "Decorar", "Décorer", "Decorare", "Decorar", "{飾|かざ}る", "装饰", "zhuāngshì"),
    ("To renovate", "🔨", "housing", "Renovar", "Rénover", "Ristrutturare", "Reformar", "リフォームする", "翻新", "fānxīn"),
    ("To move in", "📦", "housing", "Mudarse a", "Emménager", "Trasferirsi (entrare)", "Mudar-se para", "{入居|にゅうきょ}する", "搬进", "bānjìn"),
    ("To move out", "🚚", "housing", "Mudarse de", "Déménager (partir)", "Traslocare (uscire)", "Sair (da casa)", "{退去|たいきょ}する", "搬出", "bānchū"),
    ("Suburb", "🏘️", "housing", "Suburbio", "Banlieue", "Periferia", "Subúrbio", "{郊外|こうがい}", "郊区", "jiāoqū"),
    ("Countryside", "🌾", "housing", "Campo (rural)", "Campagne", "Campagna", "Interior (zona rural)", "{田舎|いなか}", "乡下", "xiāngxia"),
    ("Balcony", "🌇", "housing", "Balcón", "Balcon", "Balcone", "Varanda", "バルコニー", "阳台", "yángtái"),
    ("Basement", "⬇️", "housing", "Sótano", "Sous-sol", "Seminterrato", "Porão", "{地下室|ちかしつ}", "地下室", "dìxiàshì"),
    ("Attic", "⬆️", "housing", "Ático", "Grenier", "Soffitta", "Sótão", "{屋根裏|やねうら}", "阁楼", "gélóu"),
    ("Garage", "🚗", "housing", "Garaje", "Garage", "Garage", "Garagem", "ガレージ", "车库", "chēkù"),
    ("Yard", "🌳", "housing", "Patio", "Cour", "Cortile", "Quintal", "{庭|にわ}（{裏庭|うらにわ}）", "院子", "yuànzi"),
    ("Fence", "🪵", "housing", "Valla", "Clôture", "Recinzione", "Cerca", "{柵|さく}", "栅栏", "zhàlan"),
    ("To lock", "🔒", "housing", "Cerrar con llave", "Fermer à clé", "Chiudere a chiave", "Trancar", "{鍵|かぎ}をかける", "锁", "suǒ"),
    ("Doorbell", "🔔", "housing", "Timbre", "Sonnette", "Campanello", "Campainha", "{呼|よ}び{鈴|りん}", "门铃", "ménlíng"),
    ("Mailbox", "📬", "housing", "Buzón", "Boîte aux lettres", "Cassetta della posta", "Caixa de correio", "{郵便受|ゆうびんう}け", "信箱", "xìnxiāng"),
    ("Hallway", "🚪", "housing", "Pasillo", "Couloir", "Corridoio", "Corredor", "{廊下|ろうか}", "走廊", "zǒuláng"),
    ("Ceiling", "⬆️", "housing", "Techo", "Plafond", "Soffitto", "Teto", "{天井|てんじょう}", "天花板", "tiānhuābǎn"),
    ("To hang (a picture)", "🖼️", "housing", "Colgar", "Accrocher", "Appendere", "Pendurar", "{掛|か}ける", "挂", "guà"),
    ("Neighborhood watch", "👀", "housing", "Vigilancia vecinal", "Voisins vigilants", "Vigilanza di quartiere", "Vigilância do bairro", "{近所|きんじょ}の{見守|みまも}り", "邻里守望", "línlǐ shǒuwàng"),
    ("Real estate agent", "🏠", "housing", "Agente inmobiliario", "Agent immobilier", "Agente immobiliare", "Corretor de imóveis", "{不動産屋|ふどうさんや}", "房产中介", "fángchǎn zhōngjiè"),
    ("Property", "🏡", "housing", "Propiedad", "Propriété", "Proprietà", "Propriedade", "{物件|ぶっけん}", "房产", "fángchǎn"),
    ("Tenant", "🧑", "housing", "Inquilino", "Locataire", "Inquilino", "Inquilino", "{借|か}り{主|ぬし}", "租户", "zūhù"),
    ("Furnished", "🛋️", "housing", "Amueblado", "Meublé", "Arredato", "Mobiliado", "{家具付|かぐつ}き", "带家具", "dài jiājù"),

    # ---- consumer life ----
    ("Bargain", "🤑", "consumer", "Ganga", "Bonne affaire", "Affare", "Pechincha", "お{買|か}い{得|どく}", "便宜货", "piányi huò"),
    ("To haggle", "🗣️", "consumer", "Regatear", "Marchander", "Contrattare", "Pechinchar", "{値切|ねぎ}る", "讨价还价", "tǎojià huánjià"),
    ("Warranty", "🛡️", "consumer", "Garantía", "Garantie", "Garanzia", "Garantia", "{保証|ほしょう}", "保修", "bǎoxiū"),
    ("To exchange (goods)", "🔁", "consumer", "Cambiar (un producto)", "Échanger", "Cambiare (un prodotto)", "Trocar (produto)", "{交換|こうかん}する", "换货", "huànhuò"),
    ("Customer service", "☎️", "consumer", "Atención al cliente", "Service client", "Servizio clienti", "Atendimento ao cliente", "カスタマーサービス", "客服", "kèfú"),
    ("To file a complaint", "📝", "consumer", "Presentar una queja", "Déposer une réclamation", "Presentare un reclamo", "Fazer uma reclamação", "{苦情|くじょう}を{申|もう}し{立|た}てる", "投诉", "tóusù"),
    ("Counterfeit", "🚫", "consumer", "Falsificado", "Contrefaçon", "Contraffatto", "Falsificado", "{偽物|にせもの}", "假货", "jiǎhuò"),
    ("Second-hand", "♻️", "consumer", "De segunda mano", "D’occasion", "Di seconda mano", "De segunda mão", "{中古|ちゅうこ}", "二手", "èrshǒu"),
    ("To browse", "👀", "consumer", "Curiosear", "Flâner (dans les rayons)", "Dare un’occhiata", "Dar uma olhada", "{見|み}て{回|まわ}る", "浏览", "liúlǎn"),
    ("To subscribe", "🔔", "consumer", "Suscribirse", "S’abonner", "Abbonarsi", "Assinar (serviço)", "{購読|こうどく}する", "订阅", "dìngyuè"),
    ("Subscription", "📅", "consumer", "Suscripción", "Abonnement", "Abbonamento", "Assinatura", "サブスク", "订阅服务", "dìngyuè fúwù"),
    ("Membership", "🪪", "consumer", "Membresía", "Adhésion", "Iscrizione", "Associação", "{会員|かいいん}", "会员", "huìyuán"),
    ("Checkout", "🧾", "consumer", "Caja", "Caisse", "Cassa", "Caixa (pagamento)", "レジ", "结账", "jiézhàng"),
    ("Out of stock", "📭", "consumer", "Agotado", "En rupture de stock", "Esaurito", "Esgotado", "{在庫切|ざいこぎ}れ", "缺货", "quēhuò"),
    ("In stock", "📦", "consumer", "En existencia", "En stock", "Disponibile", "Em estoque", "{在庫|ざいこ}あり", "有货", "yǒuhuò"),
    ("To track (a package)", "📍", "consumer", "Rastrear", "Suivre (un colis)", "Tracciare", "Rastrear", "{追跡|ついせき}する", "追踪", "zhuīzōng"),
    ("Fashion", "👗", "consumer", "Moda", "Mode", "Moda", "Moda", "ファッション", "时尚", "shíshàng"),
    ("Style", "🕶️", "consumer", "Estilo", "Style", "Stile", "Estilo", "スタイル", "风格", "fēnggé"),
    ("Trend", "📈", "consumer", "Tendencia", "Tendance", "Tendenza", "Tendência", "トレンド", "潮流", "cháoliú"),
    ("To match (clothes)", "🎨", "consumer", "Combinar", "Aller avec", "Abbinarsi", "Combinar", "{合|あ}う", "搭配", "dāpèi"),
    ("Outfit", "👔", "consumer", "Conjunto", "Tenue", "Outfit", "Roupa (conjunto)", "コーディネート", "装扮", "zhuāngbàn"),
    ("To suit (look good on)", "✨", "consumer", "Quedar bien", "Aller bien à", "Stare bene a", "Cair bem", "{似合|にあ}う", "适合", "shìhé"),
    ("Accessory", "💍", "consumer", "Accesorio", "Accessoire", "Accessorio", "Acessório", "アクセサリー", "配饰", "pèishì"),
    ("Jewelry", "💎", "consumer", "Joyas", "Bijoux", "Gioielli", "Joias", "{宝石|ほうせき}", "珠宝", "zhūbǎo"),
    ("Perfume", "🌸", "consumer", "Perfume", "Parfum", "Profumo", "Perfume", "{香水|こうすい}", "香水", "xiāngshuǐ"),
    ("Coupon", "🎟️", "consumer", "Cupón", "Bon de réduction", "Buono sconto", "Cupom", "クーポン", "优惠券", "yōuhuìquàn"),
    ("Free shipping", "🚚", "consumer", "Envío gratis", "Livraison gratuite", "Spedizione gratuita", "Frete grátis", "{送料|そうりょう}{無料|むりょう}", "包邮", "bāoyóu"),
    ("Return policy", "📜", "consumer", "Política de devoluciones", "Politique de retour", "Politica di reso", "Política de devolução", "{返品|へんぴん}ポリシー", "退货政策", "tuìhuò zhèngcè"),
    ("Impulse buy", "🛍️", "consumer", "Compra impulsiva", "Achat impulsif", "Acquisto d’impulso", "Compra por impulso", "{衝動買|しょうどうが}い", "冲动消费", "chōngdòng xiāofèi"),
    ("Value for money", "💯", "consumer", "Relación calidad-precio", "Rapport qualité-prix", "Rapporto qualità-prezzo", "Custo-benefício", "コスパ", "性价比", "xìngjiàbǐ"),

    # ---- verbs V ----
    ("To avoid", "🚫", "verbs-5", "Evitar", "Éviter", "Evitare", "Evitar", "{避|さ}ける", "避免", "bìmiǎn"),
    ("To achieve", "🏆", "verbs-5", "Lograr", "Réaliser (atteindre)", "Raggiungere", "Alcançar", "{達成|たっせい}する", "实现", "shíxiàn"),
    ("To appreciate", "🙏", "verbs-5", "Apreciar", "Apprécier", "Apprezzare", "Apreciar", "ありがたく{思|おも}う", "感激（欣赏）", "xīnshǎng"),
    ("To attend", "🎟️", "verbs-5", "Asistir", "Assister à", "Partecipare a", "Comparecer", "{出席|しゅっせき}する", "参加", "cānjiā"),
    ("To belong", "🏷️", "verbs-5", "Pertenecer", "Appartenir", "Appartenere", "Pertencer", "{属|ぞく}する", "属于", "shǔyú"),
    ("To bother", "😒", "verbs-5", "Molestar", "Déranger", "Disturbare", "Incomodar", "{邪魔|じゃま}する", "打扰", "dǎrǎo"),
    ("To care about", "💗", "verbs-5", "Importar (a alguien)", "Tenir à", "Tenere a", "Se importar com", "{気|き}にかける", "在乎", "zàihu"),
    ("To deal with", "🧰", "verbs-5", "Lidiar con", "Gérer", "Affrontare", "Lidar com", "{対処|たいしょ}する", "处理", "chǔlǐ"),
    ("To depend on", "🔗", "verbs-5", "Depender de", "Dépendre de", "Dipendere da", "Depender de", "〜による", "取决于", "qǔjué yú"),
    ("To deserve", "🏅", "verbs-5", "Merecer", "Mériter", "Meritare", "Merecer", "〜に{値|あたい}する", "值得", "zhíde"),
    ("To develop", "🌱", "verbs-5", "Desarrollar", "Développer", "Sviluppare", "Desenvolver", "{発展|はってん}させる", "发展", "fāzhǎn"),
    ("To disappear", "💨", "verbs-5", "Desaparecer", "Disparaître", "Sparire", "Desaparecer", "{消|き}える", "消失", "xiāoshī"),
    ("To encourage", "📣", "verbs-5", "Animar (alentar)", "Encourager", "Incoraggiare", "Encorajar", "{励|はげ}ます", "鼓励", "gǔlì"),
    ("To expect", "⏳", "verbs-5", "Esperar (anticipar)", "S’attendre à", "Aspettarsi", "Esperar (antecipar)", "{期待|きたい}する", "期待", "qīdài"),
    ("To handle", "🤲", "verbs-5", "Manejar", "Gérer (s’occuper de)", "Gestire", "Lidar", "{扱|あつか}う", "应对", "yìngduì"),
    ("To imagine", "🌈", "verbs-5", "Imaginar", "Imaginer", "Immaginare", "Imaginar", "{想像|そうぞう}する", "想象", "xiǎngxiàng"),
    ("To improve", "📈", "verbs-5", "Mejorar", "Améliorer", "Migliorare", "Melhorar", "{改善|かいぜん}する", "改善", "gǎishàn"),
    ("To increase", "⬆️", "verbs-5", "Aumentar", "Augmenter", "Aumentare", "Aumentar", "{増|ふ}える", "增加", "zēngjiā"),
    ("To decrease", "⬇️", "verbs-5", "Disminuir", "Diminuer", "Diminuire", "Diminuir", "{減|へ}る", "减少", "jiǎnshǎo"),
    ("To involve", "🔄", "verbs-5", "Implicar", "Impliquer", "Coinvolgere", "Envolver", "{関|かか}わる", "涉及", "shèjí"),
    ("To mention", "💬", "verbs-5", "Mencionar", "Mentionner", "Menzionare", "Mencionar", "{言及|げんきゅう}する", "提到", "tídào"),
    ("To notice", "👀", "verbs-5", "Notar", "Remarquer", "Notare", "Notar", "{気|き}がつく", "注意到", "zhùyì dào"),
    ("To offer", "🎁", "verbs-5", "Ofrecer", "Offrir (proposer)", "Offrire (proporre)", "Oferecer", "{提供|ていきょう}する", "提供", "tígōng"),
    ("To organize", "📋", "verbs-5", "Organizar", "Organiser", "Organizzare", "Organizar", "{企画|きかく}する", "组织", "zǔzhī"),
    ("To participate", "🙋", "verbs-5", "Participar", "Participer", "Partecipare", "Participar", "{参加|さんか}する", "参与", "cānyù"),
    ("To pretend", "🎭", "verbs-5", "Fingir", "Faire semblant", "Fingere", "Fingir", "〜ふりをする", "假装", "jiǎzhuāng"),
    ("To protect", "🛡️", "verbs-5", "Proteger", "Protéger", "Proteggere", "Proteger", "{守|まも}る", "保护", "bǎohù"),
    ("To provide", "📦", "verbs-5", "Proporcionar", "Fournir", "Fornire", "Fornecer", "{与|あた}える", "提供（供应）", "gōngyìng"),
    ("To recognize", "🔍", "verbs-5", "Reconocer", "Reconnaître", "Riconoscere", "Reconhecer", "{認識|にんしき}する", "认出", "rènchū"),
    ("To refuse", "🙅", "verbs-5", "Rechazar", "Refuser", "Rifiutare", "Recusar", "{断|ことわ}る", "拒绝", "jùjué"),
    ("To reduce", "📉", "verbs-5", "Reducir", "Réduire", "Ridurre", "Reduzir", "{減|へ}らす", "降低", "jiàngdī"),
    ("To regret", "😞", "verbs-5", "Arrepentirse", "Regretter", "Pentirsi", "Arrepender-se", "{後悔|こうかい}する", "后悔", "hòuhuǐ"),
    ("To remain", "⏸️", "verbs-5", "Permanecer", "Rester (demeurer)", "Rimanere", "Permanecer", "{残|のこ}る", "保持", "bǎochí"),
    ("To replace", "🔁", "verbs-5", "Reemplazar", "Remplacer", "Sostituire", "Substituir", "{取|と}り{替|か}える", "替换", "tìhuàn"),
    ("To require", "❗", "verbs-5", "Requerir", "Exiger", "Richiedere", "Exigir", "{必要|ひつよう}とする", "要求", "yāoqiú"),
]
