# -*- coding: utf-8 -*-
# A1 vocabulary batch 4 — survival phrases I & II, shopping & money, transport, everyday objects, feelings
TIER = 'A1'
TOPICS = {
    'survival-1': 'Survival Phrases I', 'survival-2': 'Survival Phrases II', 'shopping-money': 'Shopping & Money',
    'transport': 'Getting Around', 'objects': 'Everyday Objects', 'feelings': 'Feelings',
}
WORDS = [
    # ---- survival phrases I ----
    ("Help!", "🆘", "survival-1", "¡Ayuda!", "Au secours !", "Aiuto!", "Socorro!", "{助|たす}けて！", "救命！", "jiùmìng!"),
    ("Slowly, please", "🐢", "survival-1", "Despacio, por favor", "Lentement, s’il vous plaît", "Lentamente, per favore", "Devagar, por favor", "ゆっくりお{願|ねが}いします", "请慢一点", "qǐng màn yìdiǎn"),
    ("Do you speak English?", "🇬🇧", "survival-1", "¿Habla inglés?", "Parlez-vous anglais ?", "Parla inglese?", "Você fala inglês?", "{英語|えいご}を{話|はな}せますか", "你会说英语吗？", "nǐ huì shuō Yīngyǔ ma?"),
    ("I don’t know", "🤔", "survival-1", "No sé", "Je ne sais pas", "Non lo so", "Não sei", "{知|し}りません", "我不知道", "wǒ bù zhīdào"),
    ("Where is the bathroom?", "🚻", "survival-1", "¿Dónde está el baño?", "Où sont les toilettes ?", "Dov’è il bagno?", "Onde é o banheiro?", "トイレはどこですか", "洗手间在哪里？", "xǐshǒujiān zài nǎlǐ?"),
    ("Which way?", "➡️", "survival-1", "¿Por dónde?", "Par où ?", "Da che parte?", "Por onde?", "どちらですか", "往哪边走？", "wǎng nǎ biān zǒu?"),
    ("One moment, please", "☝️", "survival-1", "Un momento, por favor", "Un instant, s’il vous plaît", "Un momento, per favore", "Um momento, por favor", "{少々|しょうしょう}お{待|ま}ちください", "请稍等", "qǐng shāo děng"),
    ("Of course", "👌", "survival-1", "Claro", "Bien sûr", "Certo", "Claro", "もちろん", "当然", "dāngrán"),
    ("No problem", "😉", "survival-1", "No hay problema", "Pas de problème", "Nessun problema", "Sem problema", "{問題|もんだい}ないです", "没问题", "méi wèntí"),
    ("It’s okay", "🙆", "survival-1", "Está bien", "C’est bon", "Va bene", "Tudo bem", "{大丈夫|だいじょうぶ}", "没事", "méishì"),
    ("Let’s go", "🏁", "survival-1", "Vamos", "Allons-y", "Andiamo", "Vamos", "{行|い}きましょう", "我们走吧", "wǒmen zǒu ba"),
    ("Come in", "🚪", "survival-1", "Entre", "Entrez", "Entri", "Entre", "どうぞお{入|はい}りください", "请进", "qǐng jìn"),
    ("Be careful", "⚠️", "survival-1", "Ten cuidado", "Fais attention", "Attento", "Cuidado", "{気|き}をつけて", "小心", "xiǎoxīn"),
    ("Can you help me?", "🙋", "survival-1", "¿Puede ayudarme?", "Pouvez-vous m’aider ?", "Può aiutarmi?", "Pode me ajudar?", "{手伝|てつだ}ってくれますか", "你能帮我吗？", "nǐ néng bāng wǒ ma?"),
    ("What does that mean?", "❓", "survival-1", "¿Qué significa eso?", "Qu’est-ce que ça veut dire ?", "Cosa significa?", "O que isso significa?", "それはどういう{意味|いみ}ですか", "那是什么意思？", "nà shì shénme yìsi?"),
    ("Can you repeat that?", "🔁", "survival-1", "¿Puede repetir?", "Pouvez-vous répéter ?", "Può ripetere?", "Pode repetir?", "もう{一度|いちど}お{願|ねが}いします", "你能再说一遍吗？", "nǐ néng zài shuō yí biàn ma?"),
    ("Slower, please", "🐢", "survival-1", "Más despacio, por favor", "Plus lentement, s’il vous plaît", "Più lentamente, per favore", "Mais devagar, por favor", "もっとゆっくりお{願|ねが}いします", "请慢一点", "qǐng màn yìdiǎn"),
    ("How do you say…?", "🗨️", "survival-1", "¿Cómo se dice…?", "Comment dit-on… ?", "Come si dice…?", "Como se diz…?", "…は{何|なん}と{言|い}いますか", "……怎么说？", "…zěnme shuō?"),

    # ---- survival phrases II ----
    ("I would like…", "🙏", "survival-2", "Quisiera…", "Je voudrais…", "Vorrei…", "Eu gostaria de…", "…をお{願|ねが}いします", "我想要……", "wǒ xiǎng yào…"),
    ("The bill, please", "🧾", "survival-2", "La cuenta, por favor", "L’addition, s’il vous plaît", "Il conto, per favore", "A conta, por favor", "お{会計|かいけい}お{願|ねが}いします", "请结账", "qǐng jiézhàng"),
    ("I’m tired", "😩", "survival-2", "Estoy cansado", "Je suis fatigué", "Sono stanco", "Estou cansado", "{疲|つか}れました", "我累了", "wǒ lèi le"),
    ("I’m sick", "🤒", "survival-2", "Estoy enfermo", "Je suis malade", "Sono malato", "Estou doente", "{病気|びょうき}です", "我病了", "wǒ bìng le"),
    ("It’s an emergency", "🚨", "survival-2", "Es una emergencia", "C’est une urgence", "È un’emergenza", "É uma emergência", "{緊急|きんきゅう}です", "这是紧急情况", "zhè shì jǐnjí qíngkuàng"),
    ("Call the police", "🚓", "survival-2", "Llame a la policía", "Appelez la police", "Chiami la polizia", "Chame a polícia", "{警察|けいさつ}を{呼|よ}んでください", "叫警察", "jiào jǐngchá"),
    ("I speak a little", "🗣️", "survival-2", "Hablo un poco", "Je parle un peu", "Parlo un po’", "Falo um pouco", "{少|すこ}し{話|はな}せます", "我会说一点", "wǒ huì shuō yìdiǎn"),
    ("I love it", "😍", "survival-2", "Me encanta", "J’adore", "Mi piace tantissimo", "Eu adoro", "{大好|だいす}きです", "我很喜欢", "wǒ hěn xǐhuan"),
    ("What’s this?", "🔎", "survival-2", "¿Qué es esto?", "Qu’est-ce que c’est ?", "Che cos’è questo?", "O que é isto?", "これは{何|なん}ですか", "这是什么？", "zhè shì shénme?"),
    ("I agree", "👍", "survival-2", "Estoy de acuerdo", "Je suis d’accord", "Sono d’accordo", "Concordo", "{賛成|さんせい}です", "我同意", "wǒ tóngyì"),
    ("I don’t like it", "👎", "survival-2", "No me gusta", "Je n’aime pas ça", "Non mi piace", "Não gosto", "{好|す}きじゃないです", "我不喜欢", "wǒ bù xǐhuan"),
    ("Really?", "😮", "survival-2", "¿De verdad?", "Vraiment ?", "Davvero?", "Sério?", "{本当|ほんとう}に？", "真的吗？", "zhēn de ma?"),
    ("Exactly", "🎯", "survival-2", "Exacto", "Exactement", "Esatto", "Exatamente", "そのとおり", "没错", "méi cuò"),
    ("I think so", "🤔", "survival-2", "Creo que sí", "Je pense que oui", "Penso di sì", "Acho que sim", "そう{思|おも}います", "我想是的", "wǒ xiǎng shì de"),
    ("Don’t worry", "😌", "survival-2", "No te preocupes", "Ne t’inquiète pas", "Non preoccuparti", "Não se preocupe", "{心配|しんぱい}しないで", "别担心", "bié dānxīn"),
    ("Just a little", "🤏", "survival-2", "Solo un poco", "Juste un peu", "Solo un po’", "Só um pouco", "{少|すこ}しだけ", "就一点", "jiù yìdiǎn"),
    ("Wait a moment", "✋", "survival-2", "Espera un momento", "Attends un moment", "Aspetta un momento", "Espere um momento", "ちょっと{待|ま}って", "等一下", "děng yíxià"),
    ("Is this seat free?", "💺", "survival-2", "¿Está libre este asiento?", "Cette place est libre ?", "È libero questo posto?", "Este lugar está livre?", "この{席|せき}は{空|あ}いていますか", "这个座位有人吗？", "zhège zuòwèi yǒu rén ma?"),

    # ---- shopping & money ----
    ("Money", "💵", "shopping-money", "Dinero", "Argent", "Soldi", "Dinheiro", "お{金|かね}", "钱", "qián"),
    ("Price", "🏷️", "shopping-money", "Precio", "Prix", "Prezzo", "Preço", "{値段|ねだん}", "价格", "jiàgé"),
    ("To sell", "🏪", "shopping-money", "Vender", "Vendre", "Vendere", "Vender", "{売|う}る", "卖", "mài"),
    ("Card", "💳", "shopping-money", "Tarjeta", "Carte", "Carta", "Cartão", "カード", "卡", "kǎ"),
    ("Cash", "💴", "shopping-money", "Efectivo", "Espèces", "Contanti", "Dinheiro vivo", "{現金|げんきん}", "现金", "xiànjīn"),
    ("Receipt", "🧾", "shopping-money", "Recibo", "Reçu", "Ricevuta", "Recibo", "レシート", "收据", "shōujù"),
    ("Open (shop)", "🟢", "shopping-money", "Abierto", "Ouvert", "Aperto", "Aberto", "{営業中|えいぎょうちゅう}", "营业中", "yíngyè zhōng"),
    ("Closed (shop)", "🔴", "shopping-money", "Cerrado", "Fermé", "Chiuso", "Fechado", "{閉店|へいてん}", "关门", "guānmén"),
    ("Free (no cost)", "🆓", "shopping-money", "Gratis", "Gratuit", "Gratis", "Grátis", "{無料|むりょう}", "免费", "miǎnfèi"),
    ("Discount", "🔖", "shopping-money", "Descuento", "Réduction", "Sconto", "Desconto", "{割引|わりびき}", "折扣", "zhékòu"),
    ("How much is it?", "💰", "shopping-money", "¿Cuánto cuesta?", "Ça coûte combien ?", "Quanto costa?", "Quanto custa?", "いくらですか", "多少钱？", "duōshao qián?"),
    ("Too much", "📈", "shopping-money", "Demasiado", "Trop", "Troppo", "Demais", "{多|おお}すぎる", "太多了", "tài duō le"),
    ("Gift", "🎁", "shopping-money", "Regalo", "Cadeau", "Regalo", "Presente", "プレゼント", "礼物", "lǐwù"),
    ("Change (coins)", "🪙", "shopping-money", "Cambio", "Monnaie", "Resto", "Troco", "お{釣|つ}り", "零钱", "língqián"),
    ("Supermarket", "🛒", "shopping-money", "Supermercado", "Supermarché", "Supermercato", "Supermercado", "スーパー", "超市", "chāoshì"),
    ("Pharmacy", "💊", "shopping-money", "Farmacia", "Pharmacie", "Farmacia", "Farmácia", "{薬局|やっきょく}", "药店", "yàodiàn"),
    ("Bakery", "🥖", "shopping-money", "Panadería", "Boulangerie", "Panetteria", "Padaria", "パン{屋|や}", "面包店", "miànbāodiàn"),
    ("Is this on sale?", "🏷️", "shopping-money", "¿Está en oferta?", "C’est en promotion ?", "È in offerta?", "Está em promoção?", "これはセール{中|ちゅう}ですか", "这个在打折吗？", "zhège zài dǎzhé ma?"),

    # ---- getting around ----
    ("Car", "🚗", "transport", "Coche", "Voiture", "Macchina", "Carro", "{車|くるま}", "汽车", "qìchē"),
    ("Bus", "🚌", "transport", "Autobús", "Bus", "Autobus", "Ônibus", "バス", "公交车", "gōngjiāochē"),
    ("Train", "🚆", "transport", "Tren", "Train", "Treno", "Trem", "{電車|でんしゃ}", "火车", "huǒchē"),
    ("Plane", "✈️", "transport", "Avión", "Avion", "Aereo", "Avião", "{飛行機|ひこうき}", "飞机", "fēijī"),
    ("Bicycle", "🚲", "transport", "Bicicleta", "Vélo", "Bicicletta", "Bicicleta", "{自転車|じてんしゃ}", "自行车", "zìxíngchē"),
    ("Taxi", "🚕", "transport", "Taxi", "Taxi", "Taxi", "Táxi", "タクシー", "出租车", "chūzūchē"),
    ("Ticket", "🎫", "transport", "Boleto", "Billet", "Biglietto", "Passagem", "{切符|きっぷ}", "票", "piào"),
    ("Station", "🚉", "transport", "Estación", "Gare", "Stazione", "Estação", "{駅|えき}", "车站", "chēzhàn"),
    ("Airport", "🛫", "transport", "Aeropuerto", "Aéroport", "Aeroporto", "Aeroporto", "{空港|くうこう}", "机场", "jīchǎng"),
    ("Road", "🛣️", "transport", "Carretera", "Route", "Strada (via)", "Estrada", "{道路|どうろ}", "路", "lù"),
    ("To travel", "🧳", "transport", "Viajar", "Voyager", "Viaggiare", "Viajar", "{旅行|りょこう}する", "旅行", "lǚxíng"),
    ("Trip", "🗺️", "transport", "Viaje", "Voyage", "Viaggio", "Viagem", "{旅|たび}", "旅程", "lǚchéng"),
    ("Map", "🗾", "transport", "Mapa", "Carte (plan)", "Mappa", "Mapa", "{地図|ちず}", "地图", "dìtú"),
    ("Stop (bus stop)", "🚏", "transport", "Parada", "Arrêt", "Fermata", "Ponto", "{停留所|ていりゅうじょ}", "车站（站点）", "zhàndiǎn"),
    ("To drive", "🚙", "transport", "Conducir", "Conduire", "Guidare", "Dirigir", "{運転|うんてん}する", "开车", "kāichē"),
    ("Subway", "🚇", "transport", "Metro", "Métro", "Metropolitana", "Metrô", "{地下鉄|ちかてつ}", "地铁", "dìtiě"),
    ("Passport", "🛂", "transport", "Pasaporte", "Passeport", "Passaporto", "Passaporte", "パスポート", "护照", "hùzhào"),
    ("Suitcase", "🧳", "transport", "Maleta", "Valise", "Valigia", "Mala", "スーツケース", "行李箱", "xínglixiāng"),
    ("Exit", "🚪", "transport", "Salida", "Sortie", "Uscita", "Saída", "{出口|でぐち}", "出口", "chūkǒu"),
    ("Entrance", "🔽", "transport", "Entrada", "Entrée", "Entrata", "Entrada", "{入口|いりぐち}", "入口", "rùkǒu"),

    # ---- everyday objects ----
    ("Phone", "📱", "objects", "Teléfono", "Téléphone", "Telefono", "Telefone", "{電話|でんわ}", "电话", "diànhuà"),
    ("Book", "📚", "objects", "Libro", "Livre", "Libro", "Livro", "{本|ほん}", "书", "shū"),
    ("Pen", "🖊️", "objects", "Bolígrafo", "Stylo", "Penna", "Caneta", "ペン", "笔", "bǐ"),
    ("Paper", "📄", "objects", "Papel", "Papier", "Carta", "Papel", "{紙|かみ}", "纸", "zhǐ"),
    ("Key", "🔑", "objects", "Llave", "Clé", "Chiave", "Chave", "{鍵|かぎ}", "钥匙", "yàoshi"),
    ("Computer", "💻", "objects", "Computadora", "Ordinateur", "Computer", "Computador", "パソコン", "电脑", "diànnǎo"),
    ("Clock", "🕰️", "objects", "Reloj (de pared)", "Horloge", "Orologio (da muro)", "Relógio (de parede)", "{時計|とけい}", "钟", "zhōng"),
    ("Television", "📺", "objects", "Televisión", "Télévision", "Televisione", "Televisão", "テレビ", "电视", "diànshì"),
    ("Camera", "📷", "objects", "Cámara", "Appareil photo", "Macchina fotografica", "Câmera", "カメラ", "相机", "xiàngjī"),
    ("Box", "📦", "objects", "Caja", "Boîte", "Scatola", "Caixa", "{箱|はこ}", "盒子", "hézi"),
    ("Glass (cup)", "🥛", "objects", "Vaso", "Verre", "Bicchiere", "Copo", "グラス", "杯子", "bēizi"),
    ("Bottle", "🍾", "objects", "Botella", "Bouteille", "Bottiglia", "Garrafa", "ボトル", "瓶子", "píngzi"),
    ("Plate", "🍽️", "objects", "Plato", "Assiette", "Piatto", "Prato", "{皿|さら}", "盘子", "pánzi"),
    ("Knife", "🔪", "objects", "Cuchillo", "Couteau", "Coltello", "Faca", "ナイフ", "刀", "dāo"),
    ("Fork", "🍴", "objects", "Tenedor", "Fourchette", "Forchetta", "Garfo", "フォーク", "叉子", "chāzi"),
    ("Spoon", "🥄", "objects", "Cuchara", "Cuillère", "Cucchiaio", "Colher", "スプーン", "勺子", "sháozi"),
    ("Cup", "☕", "objects", "Taza", "Tasse", "Tazza", "Xícara", "カップ", "茶杯", "chábēi"),
    ("Soap", "🧼", "objects", "Jabón", "Savon", "Sapone", "Sabonete", "{石鹸|せっけん}", "肥皂", "féizào"),
    ("Towel", "🧺", "objects", "Toalla", "Serviette", "Asciugamano", "Toalha", "タオル", "毛巾", "máojīn"),
    ("Lamp", "💡", "objects", "Lámpara", "Lampe", "Lampada", "Lâmpada", "ランプ", "灯", "dēng"),
    ("Wallet", "👛", "objects", "Cartera", "Portefeuille", "Portafoglio", "Carteira", "{財布|さいふ}", "钱包", "qiánbāo"),
    ("Charger", "🔌", "objects", "Cargador", "Chargeur", "Caricabatterie", "Carregador", "{充電器|じゅうでんき}", "充电器", "chōngdiànqì"),
    ("Thing", "🔹", "objects", "Cosa", "Chose", "Cosa", "Coisa", "{物|もの}", "东西", "dōngxi"),
    ("Toothbrush", "🪥", "objects", "Cepillo de dientes", "Brosse à dents", "Spazzolino", "Escova de dentes", "{歯|は}ブラシ", "牙刷", "yáshuā"),

    # ---- feelings ----
    ("Angry", "😠", "feelings", "Enojado", "En colère", "Arrabbiato", "Bravo", "{怒|おこ}っている", "生气", "shēngqì"),
    ("Scared", "😨", "feelings", "Asustado", "Effrayé", "Spaventato", "Assustado", "{怖|こわ}い", "害怕", "hàipà"),
    ("Bored", "🥱", "feelings", "Aburrido", "Ennuyé", "Annoiato", "Entediado", "{退屈|たいくつ}", "无聊", "wúliáo"),
    ("Excited", "🤩", "feelings", "Emocionado", "Excité", "Entusiasta", "Animado", "わくわくしている", "兴奋", "xīngfèn"),
    ("Worried", "😟", "feelings", "Preocupado", "Inquiet", "Preoccupato", "Preocupado", "{心配|しんぱい}している", "担心", "dānxīn"),
    ("Surprised", "😲", "feelings", "Sorprendido", "Surpris", "Sorpreso", "Surpreso", "{驚|おどろ}いている", "惊讶", "jīngyà"),
    ("Calm", "😌", "feelings", "Tranquilo", "Calme", "Calmo", "Calmo", "{落|お}ち{着|つ}いている", "平静", "píngjìng"),
    ("Nervous", "😬", "feelings", "Nervioso", "Nerveux", "Nervoso", "Nervoso", "{緊張|きんちょう}している", "紧张", "jǐnzhāng"),
    ("Proud", "😤", "feelings", "Orgulloso", "Fier", "Orgoglioso", "Orgulhoso", "{誇|ほこ}りに{思|おも}う", "自豪", "zìháo"),
    ("Lonely", "😔", "feelings", "Solo (solitario)", "Seul", "Solo", "Sozinho", "{寂|さび}しい", "孤独", "gūdú"),
    ("Sleepy", "🥱", "feelings", "Con sueño", "Somnolent", "Assonnato", "Com sono", "{眠|ねむ}い", "困", "kùn"),
    ("Sick (unwell)", "🤢", "feelings", "Mal (enfermo)", "Malade", "Malato", "Doente", "{気分|きぶん}が{悪|わる}い", "不舒服", "bù shūfu"),
    ("Love", "💖", "feelings", "Amor", "Amour", "Amore", "Amor", "{愛|あい}", "爱情", "àiqíng"),
    ("Fear", "😱", "feelings", "Miedo", "Peur", "Paura", "Medo", "{恐怖|きょうふ}", "恐惧", "kǒngjù"),
    ("Joy", "🥳", "feelings", "Alegría", "Joie", "Gioia", "Alegria", "{喜|よろこ}び", "快乐", "kuàilè"),
    ("Funny", "😂", "feelings", "Gracioso", "Drôle", "Divertente", "Engraçado", "{面白|おもしろ}い", "好笑", "hǎoxiào"),
]
