# -*- coding: utf-8 -*-
# C1 vocabulary batch 3 — bureaucracy & real estate, physical sciences, verbs X & XI, advanced connectors
TIER = 'C1'
TOPICS = {
    'bureaucracy-realestate': 'Bureaucracy & Real Estate', 'physical-sciences': 'Physical & Life Sciences',
    'verbs-10': 'Advanced Verbs X', 'verbs-11': 'Advanced Verbs XI', 'connectors-3': 'Advanced Connectors',
}
WORDS = [
    # ---- bureaucracy & real estate ----
    ("Bureaucracy", "🏛️", "bureaucracy-realestate", "Burocracia", "Bureaucratie", "Burocrazia", "Burocracia", "{官僚制|かんりょうせい}", "官僚体制", "guānliáo tǐzhì"),
    ("Paperwork", "📑", "bureaucracy-realestate", "Papeleo", "Paperasse", "Scartoffie", "Papelada", "{書類仕事|しょるいしごと}", "文书工作", "wénshū gōngzuò"),
    ("To file (documents)", "🗂️", "bureaucracy-realestate", "Presentar (documentos)", "Déposer (des documents)", "Presentare (documenti)", "Protocolar", "{提出|ていしゅつ}する（{書類|しょるい}）", "提交（文件）", "tíjiāo"),
    ("Applicant", "🙋", "bureaucracy-realestate", "Solicitante", "Candidat (demandeur)", "Richiedente", "Requerente", "{申請者|しんせいしゃ}", "申请人", "shēnqǐngrén"),
    ("Eligible", "✅", "bureaucracy-realestate", "Elegible", "Éligible", "Idoneo", "Elegível", "{資格|しかく}のある", "有资格的", "yǒu zīgé de"),
    ("To qualify", "🏅", "bureaucracy-realestate", "Cumplir los requisitos", "Remplir les conditions", "Avere i requisiti", "Qualificar-se", "{条件|じょうけん}を{満|み}たす", "符合条件", "fúhé tiáojiàn"),
    ("Prerequisite", "🔑", "bureaucracy-realestate", "Requisito previo", "Prérequis", "Prerequisito", "Pré-requisito", "{前提条件|ぜんていじょうけん}", "先决条件", "xiānjué tiáojiàn"),
    ("Clause", "📜", "bureaucracy-realestate", "Cláusula", "Clause", "Clausola", "Cláusula", "{条項|じょうこう}", "条款", "tiáokuǎn"),
    ("Compliance", "📋", "bureaucracy-realestate", "Cumplimiento", "Conformité", "Conformità", "Conformidade", "{法令遵守|ほうれいじゅんしゅ}", "合规", "héguī"),
    ("Regulation", "⚖️", "bureaucracy-realestate", "Regulación", "Réglementation", "Regolamento", "Regulamentação", "{規制|きせい}", "法规", "fǎguī"),
    ("License (permit)", "🪪", "bureaucracy-realestate", "Licencia", "Licence (permis)", "Licenza", "Licença", "{免許|めんきょ}", "执照", "zhízhào"),
    ("To authorize", "✍️", "bureaucracy-realestate", "Autorizar", "Autoriser", "Autorizzare", "Autorizar", "{許可|きょか}する（{権限|けんげん}）", "授权", "shòuquán"),
    ("Notary", "🖋️", "bureaucracy-realestate", "Notario", "Notaire", "Notaio", "Tabelião", "{公証人|こうしょうにん}", "公证人", "gōngzhèngrén"),
    ("Affidavit", "📄", "bureaucracy-realestate", "Declaración jurada", "Déclaration sous serment", "Dichiarazione giurata", "Declaração juramentada", "{宣誓供述書|せんせいきょうじゅつしょ}", "宣誓书", "xuānshìshū"),
    ("Deed", "📜", "bureaucracy-realestate", "Escritura", "Acte (de propriété)", "Atto (di proprietà)", "Escritura", "{権利証|けんりしょう}", "地契", "dìqì"),
    ("Title (property)", "🏠", "bureaucracy-realestate", "Título de propiedad", "Titre de propriété", "Titolo di proprietà", "Título de propriedade", "{所有権|しょゆうけん}", "产权", "chǎnquán"),
    ("Lien", "🔗", "bureaucracy-realestate", "Gravamen", "Privilège (hypothèque)", "Vincolo (ipoteca)", "Ônus (gravame)", "{先取特権|さきどりとっけん}", "留置权", "liúzhìquán"),
    ("Easement", "🛤️", "bureaucracy-realestate", "Servidumbre", "Servitude", "Servitù", "Servidão", "{地役権|ちえきけん}", "地役权", "dìyìquán"),
    ("Appraisal", "📏", "bureaucracy-realestate", "Tasación", "Évaluation (expertise)", "Perizia", "Avaliação (laudo)", "{鑑定評価|かんていひょうか}", "估价", "gūjià"),
    ("Closing (real estate)", "🔑", "bureaucracy-realestate", "Cierre (compraventa)", "Signature (acte de vente)", "Rogito", "Fechamento (escritura)", "{決済|けっさい}（{不動産|ふどうさん}）", "交割", "jiāogē"),
    ("Escrow", "🏦", "bureaucracy-realestate", "Depósito en garantía", "Séquestre", "Deposito a garanzia", "Custódia (escrow)", "エスクロー", "第三方托管", "dìsānfāng tuōguǎn"),
    ("Commission (fee)", "💰", "bureaucracy-realestate", "Comisión", "Commission", "Provvigione", "Comissão", "{手数料|てすうりょう}（{仲介|ちゅうかい}）", "佣金", "yòngjīn"),
    ("Listing (property)", "📋", "bureaucracy-realestate", "Anuncio (inmueble)", "Annonce (immobilière)", "Annuncio (immobiliare)", "Anúncio (imóvel)", "{物件情報|ぶっけんじょうほう}", "房源", "fángyuán"),
    ("Counteroffer", "🔁", "bureaucracy-realestate", "Contraoferta", "Contre-offre", "Controfferta", "Contraproposta", "{対案|たいあん}", "还价", "huánjià"),
    ("Contingency", "🧯", "bureaucracy-realestate", "Condición (contingencia)", "Condition suspensive", "Condizione sospensiva", "Condição (contingência)", "{条件付|じょうけんつ}き", "附加条件", "fùjiā tiáojiàn"),
    ("Zoning variance", "📐", "bureaucracy-realestate", "Excepción de zonificación", "Dérogation d’urbanisme", "Deroga urbanistica", "Exceção de zoneamento", "{用途地域|ようとちいき}の{特例|とくれい}", "分区规划豁免", "fēnqū guīhuà huòmiǎn"),
    ("Deadline (filing)", "📅", "bureaucracy-realestate", "Plazo (de presentación)", "Date limite (de dépôt)", "Termine (di presentazione)", "Prazo (de entrega)", "{提出期限|ていしゅつきげん}", "申报截止日", "shēnbào jiézhǐrì"),
    ("Certified copy", "📄", "bureaucracy-realestate", "Copia certificada", "Copie certifiée", "Copia autenticata", "Cópia autenticada", "{認証|にんしょう}コピー", "认证副本", "rènzhèng fùběn"),
    ("Jurisdiction", "🗺️", "bureaucracy-realestate", "Jurisdicción", "Juridiction", "Giurisdizione", "Jurisdição", "{管轄|かんかつ}", "管辖权", "guǎnxiáquán"),
    ("Liability", "⚠️", "bureaucracy-realestate", "Responsabilidad (legal)", "Responsabilité (civile)", "Responsabilità (legale)", "Responsabilidade (legal)", "{賠償責任|ばいしょうせきにん}", "责任（法律）", "zérèn (fǎlǜ)"),

    # ---- physical & life sciences ----
    ("Galaxy", "🌌", "physical-sciences", "Galaxia", "Galaxie", "Galassia", "Galáxia", "{銀河|ぎんが}", "星系", "xīngxì"),
    ("Universe", "🪐", "physical-sciences", "Universo", "Univers", "Universo", "Universo", "{宇宙|うちゅう}", "宇宙", "yǔzhòu"),
    ("Black hole", "🕳️", "physical-sciences", "Agujero negro", "Trou noir", "Buco nero", "Buraco negro", "ブラックホール", "黑洞", "hēidòng"),
    ("Telescope", "🔭", "physical-sciences", "Telescopio", "Télescope", "Telescopio", "Telescópio", "{望遠鏡|ぼうえんきょう}", "望远镜", "wàngyuǎnjìng"),
    ("Asteroid", "☄️", "physical-sciences", "Asteroide", "Astéroïde", "Asteroide", "Asteroide", "{小惑星|しょうわくせい}", "小行星", "xiǎoxíngxīng"),
    ("Eclipse", "🌘", "physical-sciences", "Eclipse", "Éclipse", "Eclissi", "Eclipse", "{日食|にっしょく}", "日食", "rìshí"),
    ("Constellation", "✨", "physical-sciences", "Constelación", "Constellation", "Costellazione", "Constelação", "{星座|せいざ}", "星座", "xīngzuò"),
    ("Particle", "⚛️", "physical-sciences", "Partícula", "Particule", "Particella", "Partícula", "{粒子|りゅうし}", "粒子", "lìzǐ"),
    ("Radiation", "☢️", "physical-sciences", "Radiación", "Radiation", "Radiazione", "Radiação", "{放射線|ほうしゃせん}", "辐射", "fúshè"),
    ("Electron", "⚡", "physical-sciences", "Electrón", "Électron", "Elettrone", "Elétron", "{電子|でんし}", "电子", "diànzǐ"),
    ("Isotope", "🧪", "physical-sciences", "Isótopo", "Isotope", "Isotopo", "Isótopo", "{同位体|どういたい}", "同位素", "tóngwèisù"),
    ("Nuclear fusion", "☀️", "physical-sciences", "Fusión nuclear", "Fusion nucléaire", "Fusione nucleare", "Fusão nuclear", "{核融合|かくゆうごう}", "核聚变", "hé jùbiàn"),
    ("Magnetic field", "🧲", "physical-sciences", "Campo magnético", "Champ magnétique", "Campo magnetico", "Campo magnético", "{磁場|じば}", "磁场", "cíchǎng"),
    ("Friction", "🔥", "physical-sciences", "Fricción", "Friction", "Attrito", "Atrito", "{摩擦|まさつ}", "摩擦", "mócā"),
    ("Velocity", "🏎️", "physical-sciences", "Velocidad (vectorial)", "Vitesse (vecteur)", "Velocità (vettore)", "Velocidade (vetor)", "{速度|そくど}", "速度（矢量）", "sùdù"),
    ("Acceleration", "🚀", "physical-sciences", "Aceleración", "Accélération", "Accelerazione", "Aceleração", "{加速度|かそくど}", "加速度", "jiāsùdù"),
    ("Momentum", "🎳", "physical-sciences", "Impulso (cantidad de movimiento)", "Quantité de mouvement", "Quantità di moto", "Momento (quantidade de movimento)", "{運動量|うんどうりょう}", "动量", "dòngliàng"),
    ("Inertia", "🪨", "physical-sciences", "Inercia", "Inertie", "Inerzia", "Inércia", "{慣性|かんせい}", "惯性", "guànxìng"),
    ("Density", "🧱", "physical-sciences", "Densidad", "Densité", "Densità", "Densidade", "{密度|みつど}", "密度", "mìdù"),
    ("Pressure (physics)", "🌡️", "physical-sciences", "Presión", "Pression", "Pressione", "Pressão (física)", "{圧力|あつりょく}", "压强", "yāqiáng"),
    ("Vacuum", "🌌", "physical-sciences", "Vacío", "Vide", "Vuoto", "Vácuo", "{真空|しんくう}", "真空", "zhēnkōng"),
    ("Wavelength", "〰️", "physical-sciences", "Longitud de onda", "Longueur d’onde", "Lunghezza d’onda", "Comprimento de onda", "{波長|はちょう}", "波长", "bōcháng"),
    ("Frequency (physics)", "📶", "physical-sciences", "Frecuencia", "Fréquence", "Frequenza", "Frequência", "{周波数|しゅうはすう}", "频率", "pínlǜ"),
    ("Spectrum", "🌈", "physical-sciences", "Espectro", "Spectre", "Spettro", "Espectro", "スペクトル", "光谱", "guāngpǔ"),
    ("Photosynthesis", "🌿", "physical-sciences", "Fotosíntesis", "Photosynthèse", "Fotosintesi", "Fotossíntese", "{光合成|こうごうせい}", "光合作用", "guānghé zuòyòng"),
    ("Enzyme", "🧬", "physical-sciences", "Enzima", "Enzyme", "Enzima", "Enzima", "{酵素|こうそ}", "酶", "méi"),
    ("Hormone", "💊", "physical-sciences", "Hormona", "Hormone", "Ormone", "Hormônio", "ホルモン", "激素", "jīsù"),
    ("Metabolism", "🔥", "physical-sciences", "Metabolismo", "Métabolisme", "Metabolismo", "Metabolismo", "{代謝|たいしゃ}", "新陈代谢", "xīnchén dàixiè"),
    ("Mutation", "🧬", "physical-sciences", "Mutación", "Mutation", "Mutazione", "Mutação", "{突然変異|とつぜんへんい}", "突变", "tūbiàn"),
    ("Organism", "🦠", "physical-sciences", "Organismo", "Organisme", "Organismo", "Organismo", "{生物|せいぶつ}（{個体|こたい}）", "生物体", "shēngwùtǐ"),

    # ---- advanced verbs X ----
    ("To allege", "🗣️", "verbs-10", "Alegar", "Alléguer", "Sostenere (asserire)", "Alegar", "{申|もう}し{立|た}てる", "指称", "zhǐchēng"),
    ("To allude", "👉", "verbs-10", "Aludir", "Faire allusion à", "Alludere", "Aludir", "{暗|あん}に{示|しめ}す", "暗指", "ànzhǐ"),
    ("To ascertain", "🔍", "verbs-10", "Averiguar", "S’assurer de", "Accertare", "Averiguar", "{確|たし}かめる", "查明", "chámíng"),
    ("To bolster", "🧱", "verbs-10", "Reforzar (apuntalar)", "Renforcer (étayer)", "Rafforzare (sostenere)", "Fortalecer", "{強化|きょうか}する（{支|ささ}える）", "增强", "zēngqiáng"),
    ("To circumvent", "↪️", "verbs-10", "Eludir", "Contourner", "Aggirare", "Contornar", "{回避|かいひ}する", "规避", "guībì"),
    ("To coerce", "👊", "verbs-10", "Coaccionar", "Contraindre", "Costringere", "Coagir", "{強要|きょうよう}する", "胁迫", "xiépò"),
    ("To condone", "🤷", "verbs-10", "Tolerar (aprobar tácitamente)", "Fermer les yeux sur", "Tollerare (giustificare)", "Tolerar (aprovar)", "{大目|おおめ}に{見|み}る", "纵容", "zòngróng"),
    ("To consolidate", "🔗", "verbs-10", "Consolidar", "Consolider", "Consolidare", "Consolidar", "{統合|とうごう}する（{強固|きょうこ}に）", "巩固", "gǒnggù"),
    ("To curb", "🛑", "verbs-10", "Frenar (contener)", "Freiner (juguler)", "Frenare", "Conter", "{抑制|よくせい}する", "遏制", "èzhì"),
    ("To deter", "🚧", "verbs-10", "Disuadir", "Dissuader", "Dissuadere", "Dissuadir", "{思|おも}いとどまらせる", "威慑", "wēishè"),
    ("To diminish", "📉", "verbs-10", "Disminuir (menguar)", "Diminuer (amoindrir)", "Diminuire (sminuire)", "Diminuir (reduzir)", "{減|へ}らす（{弱|よわ}める）", "削弱", "xuēruò"),
    ("To disclose", "📂", "verbs-10", "Divulgar (revelar)", "Divulguer", "Divulgare", "Divulgar (revelar)", "{開示|かいじ}する", "披露", "pīlù"),
    ("To disrupt", "💥", "verbs-10", "Perturbar", "Perturber", "Sconvolgere", "Perturbar", "{混乱|こんらん}させる", "扰乱", "rǎoluàn"),
    ("To divert", "↪️", "verbs-10", "Desviar", "Détourner", "Deviare", "Desviar", "そらす", "转移", "zhuǎnyí"),
    ("To elicit", "🎣", "verbs-10", "Provocar (obtener)", "Susciter", "Suscitare", "Provocar (obter)", "{引|ひ}き{出|だ}す", "引出", "yǐnchū"),
    ("To endorse", "✅", "verbs-10", "Respaldar (avalar)", "Approuver (soutenir)", "Approvare (appoggiare)", "Endossar", "{支持|しじ}する（{推薦|すいせん}）", "支持（背书）", "bèishū"),
    ("To entail", "🔗", "verbs-10", "Conllevar", "Impliquer (entraîner)", "Comportare", "Implicar (acarretar)", "{伴|ともな}う", "需要（牵涉）", "qiānshè"),
    ("To eradicate", "🧹", "verbs-10", "Erradicar", "Éradiquer", "Sradicare", "Erradicar", "{根絶|こんぜつ}する", "根除", "gēnchú"),
    ("To exacerbate", "🔥", "verbs-10", "Agravar", "Aggraver", "Aggravare", "Agravar", "{悪化|あっか}させる", "加剧", "jiājù"),
    ("To exemplify", "📌", "verbs-10", "Ejemplificar", "Illustrer (être l’exemple de)", "Esemplificare", "Exemplificar", "{典型|てんけい}となる", "例证", "lìzhèng"),
    ("To foster", "🌱", "verbs-10", "Fomentar", "Favoriser", "Favorire (promuovere)", "Fomentar", "{育|はぐく}む", "培育", "péiyù"),
    ("To hinder", "🚧", "verbs-10", "Obstaculizar", "Entraver", "Ostacolare", "Dificultar", "{妨|さまた}げる", "阻碍", "zǔ'ài"),
    ("To impede", "⛔", "verbs-10", "Impedir (obstaculizar)", "Empêcher (gêner)", "Impedire", "Impedir", "{阻止|そし}する", "妨碍", "fáng'ài"),
    ("To instigate", "🔥", "verbs-10", "Instigar", "Provoquer (inciter)", "Istigare", "Instigar", "{扇動|せんどう}する", "煽动", "shāndòng"),
    ("To mitigate", "🧯", "verbs-10", "Mitigar", "Atténuer", "Mitigare", "Mitigar", "{緩和|かんわ}する", "缓解", "huǎnjiě"),
    ("To nurture", "🤱", "verbs-10", "Nutrir (cultivar)", "Nourrir (cultiver)", "Nutrire (coltivare)", "Nutrir (cultivar)", "{育|そだ}てる（{大切|たいせつ}に）", "培养", "péiyǎng"),
    ("To omit", "✂️", "verbs-10", "Omitir", "Omettre", "Omettere", "Omitir", "{省|はぶ}く", "省略", "shěnglüè"),
    ("To precede", "⏮️", "verbs-10", "Preceder", "Précéder", "Precedere", "Preceder", "{先行|せんこう}する", "先于", "xiānyú"),
    ("To preclude", "🚫", "verbs-10", "Excluir (impedir de antemano)", "Exclure (empêcher)", "Precludere", "Impossibilitar", "{排除|はいじょ}する（{不可能|ふかのう}にする）", "排除（使不可能）", "shǐ bù kěnéng"),
    ("To prompt", "💡", "verbs-10", "Provocar (incitar)", "Inciter (déclencher)", "Spingere (indurre)", "Levar a (provocar)", "{促|うなが}す", "促使", "cùshǐ"),

    # ---- advanced verbs XI ----
    ("To refrain", "✋", "verbs-11", "Abstenerse", "S’abstenir", "Astenersi", "Abster-se", "{控|ひか}える", "克制（不做）", "kèzhì"),
    ("To relinquish", "🏳️", "verbs-11", "Renunciar a", "Renoncer à", "Rinunciare a", "Renunciar a", "{放棄|ほうき}する", "放弃（交出）", "jiāochū"),
    ("To render", "🎨", "verbs-11", "Convertir en (volver)", "Rendre (faire devenir)", "Rendere", "Tornar", "〜にする", "使成为", "shǐ chéngwéi"),
    ("To scrutinize", "🔬", "verbs-11", "Escudriñar", "Scruter", "Esaminare attentamente", "Examinar minuciosamente", "{精査|せいさ}する", "仔细审查", "zǐxì shěnchá"),
    ("To stipulate", "📜", "verbs-11", "Estipular", "Stipuler", "Stipulare", "Estipular", "{規定|きてい}する", "规定", "guīdìng"),
    ("To substantiate", "📊", "verbs-11", "Fundamentar", "Étayer", "Comprovare", "Fundamentar", "{立証|りっしょう}する", "证实", "zhèngshí"),
    ("To thrive", "🌻", "verbs-11", "Prosperar", "Prospérer", "Prosperare", "Prosperar", "{繁栄|はんえい}する", "茁壮成长", "zhuózhuàng chéngzhǎng"),
    ("To undermine", "⛏️", "verbs-11", "Socavar", "Saper (miner)", "Minare", "Minar", "{損|そこ}なう", "破坏（暗中）", "pòhuài"),
    ("To uphold", "🏛️", "verbs-11", "Defender (mantener)", "Faire respecter", "Sostenere (difendere)", "Manter (defender)", "{支持|しじ}する（{擁護|ようご}）", "维护", "wéihù"),
    ("To waive", "🗑️", "verbs-11", "Renunciar a (un derecho)", "Renoncer à (un droit)", "Rinunciare a (un diritto)", "Renunciar a (um direito)", "{放棄|ほうき}する（{権利|けんり}）", "免除", "miǎnchú"),
    ("To yield", "🌾", "verbs-11", "Producir (rendir)", "Produire (rapporter)", "Produrre (rendere)", "Render", "{生|う}む（{産出|さんしゅつ}）", "产出", "chǎnchū"),
    ("To abolish", "🚫", "verbs-11", "Abolir", "Abolir", "Abolire", "Abolir", "{廃止|はいし}する", "废除", "fèichú"),
    ("To accommodate", "🏨", "verbs-11", "Acomodar (dar cabida)", "Accueillir (loger)", "Ospitare (soddisfare)", "Acomodar", "{収容|しゅうよう}する", "容纳", "róngnà"),
    ("To adhere", "📌", "verbs-11", "Adherirse", "Adhérer", "Aderire", "Aderir", "{忠実|ちゅうじつ}に{守|まも}る", "遵循", "zūnxún"),
    ("To attain", "🏆", "verbs-11", "Alcanzar (lograr)", "Atteindre", "Raggiungere (conseguire)", "Atingir", "{達|たっ}する", "达到", "dádào"),
    ("To compel", "👊", "verbs-11", "Obligar", "Contraindre (forcer)", "Obbligare", "Obrigar", "{強|し}いる", "迫使", "pòshǐ"),
    ("To confine", "🔒", "verbs-11", "Confinar", "Confiner", "Confinare", "Confinar", "{閉|と}じ{込|こ}める", "限制（禁闭）", "jìnbì"),
    ("To contemplate", "🤔", "verbs-11", "Contemplar (considerar)", "Envisager", "Contemplare", "Contemplar (considerar)", "{熟考|じゅっこう}する（{思案|しあん}）", "思忖", "sīcǔn"),
    ("To depict", "🖼️", "verbs-11", "Representar (describir)", "Dépeindre", "Raffigurare", "Retratar", "{描|えが}く", "描绘", "miáohuì"),
    ("To dispel", "💨", "verbs-11", "Disipar", "Dissiper", "Dissipare", "Dissipar", "{払拭|ふっしょく}する", "驱散", "qūsàn"),
    ("To embody", "🧍", "verbs-11", "Encarnar", "Incarner", "Incarnare", "Encarnar", "{体現|たいげん}する", "体现", "tǐxiàn"),
    ("To evoke", "🎻", "verbs-11", "Evocar", "Évoquer", "Evocare", "Evocar", "{呼|よ}び{起|お}こす", "唤起", "huànqǐ"),
    ("To forge", "🔨", "verbs-11", "Forjar", "Forger", "Forgiare", "Forjar", "{築|きず}く", "锻造（建立）", "duànzào"),
    ("To grasp", "✊", "verbs-11", "Captar (comprender)", "Saisir (comprendre)", "Afferrare (capire)", "Captar (compreender)", "{把握|はあく}する", "领会", "lǐnghuì"),
    ("To infringe", "⚠️", "verbs-11", "Infringir", "Enfreindre", "Violare", "Infringir", "{侵害|しんがい}する", "侵犯", "qīnfàn"),
    ("To overturn", "🔄", "verbs-11", "Anular (revocar)", "Annuler (renverser)", "Ribaltare", "Anular (reverter)", "{覆|くつがえ}す", "推翻", "tuīfān"),
    ("To plead", "🙏", "verbs-11", "Suplicar (alegar)", "Plaider", "Implorare (dichiararsi)", "Suplicar (alegar)", "{嘆願|たんがん}する", "恳求（申辩）", "shēnbiàn"),
    ("To reconcile (ideas)", "⚖️", "verbs-11", "Conciliar", "Concilier", "Conciliare", "Conciliar", "{両立|りょうりつ}させる", "调和", "tiáohé"),
    ("To surpass", "🚀", "verbs-11", "Sobrepasar", "Surpasser", "Superare (oltrepassare)", "Superar (ultrapassar)", "{上回|うわまわ}る", "超越", "chāoyuè"),
    ("To unveil", "🎭", "verbs-11", "Desvelar", "Dévoiler", "Svelare", "Revelar (desvendar)", "{公開|こうかい}する（{発表|はっぴょう}）", "揭幕", "jiēmù"),

    # ---- advanced connectors ----
    ("Albeit", "🔀", "connectors-3", "Aunque (si bien)", "Quoique", "Sebbene (seppur)", "Embora (conquanto)", "〜ではあるが", "尽管（虽然）", "jǐnguǎn"),
    ("Notwithstanding", "🧱", "connectors-3", "No obstante (a pesar de)", "Nonobstant", "Nonostante (ciò)", "Não obstante", "〜にもかかわらず（{文語|ぶんご}）", "尽管如此（书面）", "jǐnguǎn rúcǐ"),
    ("Insofar as", "📏", "connectors-3", "En la medida en que", "Dans la mesure où", "Nella misura in cui", "Na medida em que", "〜する{限|かぎ}りにおいて", "在……范围内", "zài…fànwéi nèi"),
    ("Whereby", "🔗", "connectors-3", "Por el cual", "Par lequel", "Per cui (mediante il quale)", "Pelo qual", "それによって", "凭此", "píng cǐ"),
    ("Hereby", "📜", "connectors-3", "Por la presente", "Par la présente", "Con la presente", "Pela presente", "ここに", "特此", "tècǐ"),
    ("Thereby", "➡️", "connectors-3", "Por lo tanto (de ese modo)", "Ainsi (de ce fait)", "In tal modo", "Assim (desse modo)", "それにより", "从而", "cóng'ér"),
    ("Hence", "🔜", "connectors-3", "De ahí", "D’où", "Da qui (quindi)", "Daí", "それゆえ", "因此（故）", "gù"),
    ("Thus", "➡️", "connectors-3", "Así (por consiguiente)", "Ainsi", "Così (dunque)", "Assim", "したがって（このように）", "如此（因而）", "yīn'ér"),
    ("Henceforth", "🔜", "connectors-3", "De ahora en adelante", "Désormais", "D’ora in poi", "Doravante", "{今後|こんご}", "从今以后", "cóng jīn yǐhòu"),
    ("Likewise", "🔁", "connectors-3", "Asimismo", "De même", "Allo stesso modo", "Da mesma forma", "{同様|どうよう}に", "同样", "tóngyàng"),
    ("Conversely", "↔️", "connectors-3", "A la inversa", "Inversement", "Al contrario (viceversa)", "Inversamente", "{逆|ぎゃく}に", "相反地", "xiāngfǎn de"),
    ("Namely", "📌", "connectors-3", "A saber", "À savoir", "Vale a dire", "A saber", "すなわち", "即", "jí"),
    ("In lieu of", "🔄", "connectors-3", "En lugar de (en vez de)", "Au lieu de (en remplacement)", "In luogo di", "Em lugar de", "〜の{代|か}わりに（{正式|せいしき}）", "代替", "dàitì"),
    ("In light of", "💡", "connectors-3", "A la luz de", "À la lumière de", "Alla luce di", "À luz de", "〜を{踏|ふ}まえて", "鉴于", "jiànyú"),
    ("In view of", "👁️", "connectors-3", "En vista de", "Compte tenu de", "In considerazione di", "Em vista de", "〜を{考慮|こうりょ}して", "考虑到", "kǎolǜ dào"),
    ("By virtue of", "⚖️", "connectors-3", "En virtud de", "En vertu de", "In virtù di", "Em virtude de", "〜によって（{権限|けんげん}）", "凭借", "píngjiè"),
    ("On account of", "📋", "connectors-3", "A causa de", "En raison de", "A causa di", "Por conta de", "〜のせいで", "由于", "yóuyú"),
    ("With a view to", "🎯", "connectors-3", "Con vistas a", "En vue de", "In vista di", "Com vistas a", "〜を{目的|もくてき}として", "为了（旨在）", "zhǐzài"),
    ("Provided that", "✅", "connectors-3", "Siempre y cuando", "À condition que", "A condizione che", "Desde que (contanto que)", "〜という{条件|じょうけん}で", "只要（条件是）", "zhǐyào"),
    ("Granted", "🤝", "connectors-3", "Cierto es que", "Certes", "Certo (d’accordo)", "É verdade que", "{確|たし}かに", "诚然", "chéngrán"),
    ("Admittedly", "🙋", "connectors-3", "Hay que admitir que", "Il faut admettre que", "Bisogna ammettere che", "Admito que", "{認|みと}めざるを{得|え}ないが", "无可否认", "wúkě fǒurèn"),
    ("Arguably", "💬", "connectors-3", "Podría decirse que", "Sans doute (on peut dire que)", "Probabilmente (si può sostenere)", "Possivelmente (pode-se argumentar)", "{間違|まちが}いなく〜と{言|い}える", "可以说", "kěyǐ shuō"),
    ("Presumably", "🤔", "connectors-3", "Presumiblemente", "Vraisemblablement", "Presumibilmente", "Presumivelmente", "おそらく", "大概（推测）", "dàgài"),
    ("Allegedly", "🗣️", "connectors-3", "Supuestamente (según se alega)", "Prétendument", "Presumibilmente (a quanto si dice)", "Alegadamente", "{申|もう}し{立|た}てによれば", "据称", "jùchēng"),
    ("Ostensibly", "🎭", "connectors-3", "Aparentemente", "En apparence", "Apparentemente", "Ostensivamente", "{表向|おもてむ}きは", "表面上", "biǎomiàn shàng"),
    ("Undoubtedly", "💯", "connectors-3", "Indudablemente", "Indubitablement", "Indubbiamente", "Sem dúvida", "{疑|うたが}いなく", "毫无疑问", "háowú yíwèn"),
    ("Invariably", "🔁", "connectors-3", "Invariablemente", "Invariablement", "Invariabilmente", "Invariavelmente", "{常|つね}に（{例外|れいがい}なく）", "总是（无一例外）", "wúyī lìwài"),
    ("Nevertheless (formal)", "🧱", "connectors-3", "Sin embargo (formal)", "Toutefois", "Tuttavia (formale)", "Contudo", "とはいえ（{文語|ぶんご}）", "然而（书面）", "rán'ér"),
    ("To the extent that", "📏", "connectors-3", "Hasta el punto de que", "Au point que", "Al punto che", "A tal ponto que", "〜するほどに", "到……程度", "dào…chéngdù"),
    ("For all intents and purposes", "📌", "connectors-3", "A todos los efectos", "À toutes fins utiles", "A tutti gli effetti", "Para todos os efeitos", "{事実上|じじつじょう}", "实际上（在各方面）", "shíjì shàng"),
]
