# -*- coding: utf-8 -*-
# C2 vocabulary batch 6 — rare nature, weather, architecture, household objects
TIER = 'C2'
TOPICS = {
    'nature-rare': 'Nature Up Close', 'weather-rare': 'Weather & Sky Register',
    'architecture-rare': 'Architecture & Structures', 'household-rare': 'Household Odds & Ends',
}
WORDS = [
    # ---- nature up close ----
    ("Thicket", "🌳", "nature-rare", "Matorral (espesura)", "Fourré (taillis)", "Boscaglia (macchia)", "Matagal (moita)", "{茂|しげ}み", "灌木丛", "guànmùcóng"),
    ("Undergrowth", "🌿", "nature-rare", "Maleza (sotobosque)", "Sous-bois (broussailles)", "Sottobosco", "Vegetação rasteira", "{下草|したくさ}", "林下植被", "línxià zhíbèi"),
    ("Moss", "🪨", "nature-rare", "Musgo", "Mousse", "Muschio", "Musgo", "{苔|こけ}", "苔藓", "táixiǎn"),
    ("Lichen", "🍄", "nature-rare", "Liquen", "Lichen", "Lichene", "Líquen", "{地衣類|ちいるい}", "地衣", "dìyī"),
    ("Fern", "🌿", "nature-rare", "Helecho", "Fougère", "Felce", "Samambaia", "シダ", "蕨类", "juélèi"),
    ("Sap", "🍯", "nature-rare", "Savia", "Sève", "Linfa", "Seiva", "{樹液|じゅえき}", "树液", "shùyè"),
    ("Bark (of a tree)", "🪵", "nature-rare", "Corteza", "Écorce", "Corteccia", "Casca (de árvore)", "{樹皮|じゅひ}", "树皮", "shùpí"),
    ("Sapling", "🌱", "nature-rare", "Árbol joven (plantón)", "Jeune arbre (plant)", "Alberello (piantina)", "Muda (árvore jovem)", "{若木|わかぎ}", "树苗", "shùmiáo"),
    ("Canopy (forest)", "🌴", "nature-rare", "Dosel (copa de los árboles)", "Canopée", "Chioma (volta arborea)", "Dossel (copa das árvores)", "{林冠|りんかん}", "树冠层", "shùguàncéng"),
    ("Grove", "🌲", "nature-rare", "Arboleda", "Bosquet", "Boschetto", "Bosque (arvoredo)", "{木立|こだち}", "小树林", "xiǎo shùlín"),
    ("Meadow", "🌼", "nature-rare", "Pradera (prado)", "Prairie (pré)", "Prato", "Campina (prado)", "{牧草地|ぼくそうち}", "草地", "cǎodì"),
    ("Marsh", "🐸", "nature-rare", "Marisma (pantano)", "Marais", "Palude", "Pântano (brejo)", "{湿地|しっち}", "沼泽", "zhǎozé"),
    ("Bog", "🥾", "nature-rare", "Ciénaga (turbera)", "Tourbière (marécage)", "Torbiera (acquitrino)", "Lamaçal (turfeira)", "{泥炭地|でいたんち}", "泥沼", "nízhǎo"),
    ("Estuary", "🌊", "nature-rare", "Estuario", "Estuaire", "Estuario", "Estuário", "{河口|かこう}", "河口", "hékǒu"),
    ("Tributary", "💧", "nature-rare", "Afluente", "Affluent", "Affluente", "Afluente", "{支流|しりゅう}", "支流", "zhīliú"),
    ("Ravine", "🏞️", "nature-rare", "Barranco", "Ravin", "Burrone (gola)", "Ravina (desfiladeiro)", "{渓谷|けいこく}", "峡谷（沟壑）", "gōuhè"),
    ("Gorge", "⛰️", "nature-rare", "Desfiladero (garganta)", "Gorge", "Gola", "Garganta (desfiladeiro)", "{峡谷|きょうこく}", "峡谷", "xiágǔ"),
    ("Ridge", "🗻", "nature-rare", "Cresta (cordillera)", "Crête (arête)", "Crinale (cresta)", "Cume (crista)", "{尾根|おね}", "山脊", "shānjǐ"),
    ("Summit", "🏔️", "nature-rare", "Cumbre", "Sommet", "Vetta (cima)", "Cume (pico)", "{頂上|ちょうじょう}", "山顶", "shāndǐng"),
    ("Foothills", "🌄", "nature-rare", "Estribaciones", "Contreforts", "Colline pedemontane", "Sopé (contrafortes)", "{山麓|さんろく}", "山麓", "shānlù"),
    ("Escarpment", "🧗", "nature-rare", "Escarpa", "Escarpement", "Scarpata", "Escarpa", "{急斜面|きゅうしゃめん}", "悬崖（陡坡）", "dǒupō"),
    ("Salt flat", "🧂", "nature-rare", "Salar", "Salar (plaine de sel)", "Salina (distesa di sale)", "Salar", "{塩原|えんげん}", "盐滩", "yántān"),
    ("Cove", "🏖️", "nature-rare", "Cala (ensenada)", "Crique (anse)", "Cala (insenatura)", "Enseada", "{入|い}り{江|え}", "小海湾", "xiǎo hǎiwān"),
    ("Atoll", "🏝️", "nature-rare", "Atolón", "Atoll", "Atollo", "Atol", "{環礁|かんしょう}", "环礁", "huánjiāo"),
    ("Tide pool", "🦀", "nature-rare", "Poza de marea", "Bassin de marée (flaque)", "Pozza di marea", "Poça de maré", "{潮溜|しおだ}まり", "潮池", "cháochí"),
    ("Driftwood", "🪵", "nature-rare", "Madera de deriva", "Bois flotté", "Legno portato dal mare", "Madeira flutuante", "{流木|りゅうぼく}", "浮木", "fúmù"),
    ("Pebble", "🪨", "nature-rare", "Guijarro", "Galet (caillou)", "Ciottolo", "Seixo", "{小石|こいし}", "鹅卵石", "éluǎnshí"),
    ("Boulder", "🗿", "nature-rare", "Peñasco (roca grande)", "Rocher (bloc)", "Masso", "Pedregulho (rochedo)", "{巨岩|きょがん}", "巨石", "jùshí"),
    ("Sediment", "🏺", "nature-rare", "Sedimento", "Sédiment", "Sedimento", "Sedimento", "{堆積物|たいせきぶつ}", "沉积物", "chénjīwù"),
    ("Erosion", "🌬️", "nature-rare", "Erosión", "Érosion", "Erosione", "Erosão", "{浸食|しんしょく}", "侵蚀", "qīnshí"),
    ("Burrow", "🐇", "nature-rare", "Madriguera", "Terrier", "Tana", "Toca", "{巣穴|すあな}", "洞穴（动物）", "dòngxué"),
    ("Hive", "🐝", "nature-rare", "Colmena", "Ruche", "Alveare", "Colmeia", "ミツバチの{巣|す}", "蜂巢", "fēngcháo"),
    ("Cocoon", "🐛", "nature-rare", "Capullo", "Cocon", "Bozzolo", "Casulo", "{繭|まゆ}", "茧", "jiǎn"),
    ("Antler", "🦌", "nature-rare", "Cornamenta (asta)", "Bois (de cerf)", "Corno (palco)", "Chifre (galhada)", "{枝角|えだづの}", "鹿角", "lùjiǎo"),
    ("Talon", "🦅", "nature-rare", "Garra", "Serre", "Artiglio", "Garra", "かぎ{爪|づめ}", "利爪", "lìzhǎo"),
    ("Plumage", "🦚", "nature-rare", "Plumaje", "Plumage", "Piumaggio", "Plumagem", "{羽毛|うもう}", "羽毛（羽衣）", "yǔyī"),
    ("Migration (animal)", "🦢", "nature-rare", "Migración", "Migration", "Migrazione", "Migração", "{渡|わた}り", "迁徙", "qiānxǐ"),
    ("Hibernation", "🐻", "nature-rare", "Hibernación", "Hibernation", "Letargo (ibernazione)", "Hibernação", "{冬眠|とうみん}", "冬眠", "dōngmián"),
    ("Pollination", "🌻", "nature-rare", "Polinización", "Pollinisation", "Impollinazione", "Polinização", "{受粉|じゅふん}", "授粉", "shòufěn"),
    ("Germination", "🌱", "nature-rare", "Germinación", "Germination", "Germinazione", "Germinação", "{発芽|はつが}", "发芽", "fāyá"),
    # ---- weather & sky register ----
    ("Torrential", "🌧️", "weather-rare", "Torrencial", "Torrentiel", "Torrenziale", "Torrencial", "{土砂降|どしゃぶ}りの", "倾盆的", "qīngpén de"),
    ("Monsoon", "🌊", "weather-rare", "Monzón", "Mousson", "Monsone", "Monção", "モンスーン（{季節風|きせつふう}）", "季风", "jìfēng"),
    ("Sleet", "🌨️", "weather-rare", "Aguanieve", "Grésil (neige fondue)", "Nevischio", "Chuva com neve", "みぞれ", "雨夹雪", "yǔ jiā xuě"),
    ("Flurry (snow)", "❄️", "weather-rare", "Nevisca (ráfaga de nieve)", "Bourrasque de neige", "Spruzzata di neve", "Rajada de neve", "にわか{雪|ゆき}", "小阵雪", "xiǎo zhènxuě"),
    ("Whiteout", "⬜", "weather-rare", "Visibilidad nula (por nieve)", "Blanc total (visibilité nulle)", "Visibilità zero (per neve)", "Visibilidade zero (por neve)", "ホワイトアウト", "白茫茫一片（雪盲）", "xuěmáng"),
    ("Black ice", "🧊", "weather-rare", "Hielo negro (placa de hielo)", "Verglas", "Ghiaccio nero", "Gelo negro (na pista)", "{路面|ろめん}の{薄氷|はくひょう}", "路面暗冰", "lùmiàn ànbīng"),
    ("Dew", "💧", "weather-rare", "Rocío", "Rosée", "Rugiada", "Orvalho", "{露|つゆ}", "露水", "lùshui"),
    ("Haze", "🌫️", "weather-rare", "Calima (bruma)", "Brume (voile)", "Foschia", "Névoa (bruma)", "{霞|かすみ}", "霾（薄雾）", "mái"),
    ("Clammy", "💦", "weather-rare", "Húmedo (pegajoso)", "Moite", "Umidiccio (appiccicoso)", "Úmido (pegajoso)", "じめっとした", "湿冷的", "shīlěng de"),
    ("Scorcher", "🔥", "weather-rare", "Día abrasador", "Journée de canicule", "Giornata torrida", "Dia escaldante", "{猛暑日|もうしょび}", "大热天", "dà rètiān"),
    ("Sultry", "🌡️", "weather-rare", "Sofocante", "Étouffant (lourd)", "Afoso (soffocante)", "Abafado (sufocante)", "{蒸|む}し{暑|あつ}い（うだるような）", "闷热的（酷热）", "kùrè de"),
    ("Balmy", "🌴", "weather-rare", "Templado (agradable)", "Doux (clément)", "Mite (dolce)", "Ameno (agradável)", "{穏|おだ}やかで{暖|あたた}かい", "温和宜人的", "wēnhé yírén de"),
    ("Crisp (air)", "🍁", "weather-rare", "Fresco (vigorizante)", "Vif (frais)", "Frizzante (fresco)", "Fresco (revigorante)", "{澄|す}んで{冷|ひ}んやりした", "清冽的", "qīngliè de"),
    ("Gust", "💨", "weather-rare", "Ráfaga", "Rafale", "Raffica", "Rajada", "{突風|とっぷう}", "阵风", "zhènfēng"),
    ("Gale", "🌬️", "weather-rare", "Vendaval", "Coup de vent (tempête)", "Burrasca", "Vendaval", "{強風|きょうふう}", "大风", "dàfēng"),
    ("Squall", "⛈️", "weather-rare", "Turbión (chubasco)", "Grain (bourrasque)", "Groppo (bufera)", "Borrasca (rajada)", "スコール", "狂风（骤雨）", "kuángfēng"),
    ("Thunderclap", "⚡", "weather-rare", "Trueno", "Coup de tonnerre", "Tuono", "Trovão", "{雷鳴|らいめい}", "雷声", "léishēng"),
    ("Lightning bolt", "🌩️", "weather-rare", "Rayo", "Éclair (foudre)", "Fulmine", "Raio", "{稲妻|いなずま}", "闪电", "shǎndiàn"),
    ("Cloudburst", "🌧️", "weather-rare", "Tromba de agua", "Trombe d’eau", "Nubifragio", "Tromba d’água", "{集中豪雨|しゅうちゅうごうう}", "暴雨（骤雨）", "bàoyǔ"),
    ("Nightfall", "🌃", "weather-rare", "Anochecer", "Tombée de la nuit", "Calar della notte", "Anoitecer", "{日暮|ひぐ}れ", "夜幕降临", "yèmù jiànglín"),
    ("Cold snap", "🧊", "weather-rare", "Ola de frío", "Vague de froid", "Ondata di freddo", "Onda de frio", "{寒波|かんぱ}", "寒潮", "háncháo"),
    ("Thaw", "🌊", "weather-rare", "Deshielo", "Dégel", "Disgelo", "Degelo", "{雪解|ゆきど}け", "解冻", "jiědòng"),
    ("Humidity", "💦", "weather-rare", "Humedad", "Humidité", "Umidità", "Umidade", "{湿度|しつど}", "湿度", "shīdù"),
    ("Barometer", "📉", "weather-rare", "Barómetro", "Baromètre", "Barometro", "Barômetro", "{気圧計|きあつけい}", "气压计", "qìyājì"),
    ("Forecast (verb)", "🔮", "weather-rare", "Pronosticar", "Prévoir", "Prevedere", "Prever", "{予報|よほう}する", "预报", "yùbào"),
    ("Daybreak", "🌄", "weather-rare", "Alba (romper del día)", "Point du jour", "Spuntar del giorno", "Raiar do dia", "{明|あ}け{方|がた}", "破晓", "pòxiǎo"),
    ("Aurora", "🌌", "weather-rare", "Aurora (boreal)", "Aurore (boréale)", "Aurora (boreale)", "Aurora (boreal)", "オーロラ", "极光", "jíguāng"),
    ("Twilight", "🌇", "weather-rare", "Penumbra (crepúsculo)", "Pénombre (crépuscule)", "Penombra (crepuscolo)", "Lusco-fusco", "{薄明|はくめい}", "暮色", "mùsè"),
    ("Solstice", "☀️", "weather-rare", "Solsticio", "Solstice", "Solstizio", "Solstício", "{至点|してん}（{夏至|げし}・{冬至|とうじ}）", "至日（夏至/冬至）", "zhìrì"),
    ("Equinox", "🌗", "weather-rare", "Equinoccio", "Équinoxe", "Equinozio", "Equinócio", "{分点|ぶんてん}（{春分|しゅんぶん}・{秋分|しゅうぶん}）", "分点（春分/秋分）", "fēndiǎn"),
    # ---- architecture & structures ----
    ("Arch", "🌉", "architecture-rare", "Arco", "Arche (arc)", "Arco", "Arco", "アーチ", "拱门", "gǒngmén"),
    ("Vault (ceiling)", "⛪", "architecture-rare", "Bóveda", "Voûte", "Volta", "Abóbada", "{丸天井|まるてんじょう}", "拱顶", "gǒngdǐng"),
    ("Dome", "🕌", "architecture-rare", "Cúpula", "Dôme (coupole)", "Cupola", "Cúpula", "ドーム", "穹顶", "qióngdǐng"),
    ("Spire", "⛪", "architecture-rare", "Aguja (chapitel)", "Flèche", "Guglia", "Pináculo (torre)", "{尖塔|せんとう}", "尖塔", "jiāntǎ"),
    ("Buttress", "🧱", "architecture-rare", "Contrafuerte", "Contrefort", "Contrafforte", "Contraforte", "{控|ひか}え{壁|かべ}", "扶壁", "fúbì"),
    ("Pillar", "🏛️", "architecture-rare", "Pilar", "Pilier", "Pilastro", "Pilar", "{柱|はしら}", "柱子", "zhùzi"),
    ("Column", "🏛️", "architecture-rare", "Columna", "Colonne", "Colonna", "Coluna", "{円柱|えんちゅう}", "圆柱", "yuánzhù"),
    ("Beam (structural)", "🪵", "architecture-rare", "Viga", "Poutre", "Trave", "Viga", "{梁|はり}", "横梁", "héngliáng"),
    ("Rafter", "🏠", "architecture-rare", "Cabrio (viga del tejado)", "Chevron", "Travicello (puntone)", "Caibro", "{垂木|たるき}", "椽子", "chuánzi"),
    ("Girder", "🏗️", "architecture-rare", "Viga maestra", "Poutre maîtresse", "Trave portante", "Viga mestra", "{桁|けた}（{大梁|おおばり}）", "大梁", "dàliáng"),
    ("Keystone", "🔑", "architecture-rare", "Clave (de un arco)", "Clé de voûte", "Chiave di volta", "Pedra angular (fecho)", "{要石|かなめいし}", "拱心石", "gǒngxīnshí"),
    ("Facade (building front)", "🏢", "architecture-rare", "Fachada", "Façade", "Facciata", "Fachada", "{正面|しょうめん}（ファサード）", "外立面", "wàilìmiàn"),
    ("Cornice", "📐", "architecture-rare", "Cornisa", "Corniche", "Cornice (cornicione)", "Cornija", "{軒蛇腹|のきじゃばら}", "檐口", "yánkǒu"),
    ("Gable", "🏠", "architecture-rare", "Hastial (aguilón)", "Pignon", "Timpano (frontone)", "Empena (frontão)", "{切妻|きりづま}", "山墙", "shānqiáng"),
    ("Eaves", "☔", "architecture-rare", "Alero", "Avant-toit", "Gronda", "Beiral", "{軒|のき}", "屋檐", "wūyán"),
    ("Gutter (roof)", "🌧️", "architecture-rare", "Canalón", "Gouttière", "Grondaia", "Calha", "{雨樋|あまどい}", "排水槽（天沟）", "tiāngōu"),
    ("Skylight", "🌤️", "architecture-rare", "Claraboya (tragaluz)", "Puits de lumière (lucarne)", "Lucernario", "Claraboia", "{天窓|てんまど}", "天窗", "tiānchuāng"),
    ("Balustrade", "🚧", "architecture-rare", "Balaustrada", "Balustrade", "Balaustra", "Balaustrada", "{手|て}すり（{欄干|らんかん}）", "栏杆", "lángān"),
    ("Parapet", "🏰", "architecture-rare", "Parapeto", "Parapet", "Parapetto", "Parapeito", "{胸壁|きょうへき}", "矮墙（女儿墙）", "nǚ'érqiáng"),
    ("Turret", "🏰", "architecture-rare", "Torreón (torrecilla)", "Tourelle", "Torretta", "Torreão", "{小塔|しょうとう}", "角楼", "jiǎolóu"),
    ("Moat", "🐊", "architecture-rare", "Foso", "Douve", "Fossato", "Fosso", "{堀|ほり}", "护城河", "hùchénghé"),
    ("Drawbridge", "🌉", "architecture-rare", "Puente levadizo", "Pont-levis", "Ponte levatoio", "Ponte levadiça", "{跳|は}ね{橋|ばし}", "吊桥", "diàoqiáo"),
    ("Cloister", "⛪", "architecture-rare", "Claustro", "Cloître", "Chiostro", "Claustro", "{回廊|かいろう}", "回廊", "huíláng"),
    ("Courtyard", "🏡", "architecture-rare", "Patio", "Cour intérieure", "Cortile", "Pátio", "{中庭|なかにわ}", "庭院", "tíngyuàn"),
    ("Alcove", "🛋️", "architecture-rare", "Nicho (hueco)", "Alcôve (renfoncement)", "Nicchia (alcova)", "Nicho (alcova)", "アルコーブ（{床|とこ}の{間|ま}）", "壁龛", "bìkān"),
    ("Mezzanine", "🪜", "architecture-rare", "Entreplanta", "Mezzanine", "Mezzanino (soppalco)", "Mezanino", "{中二階|ちゅうにかい}", "夹层", "jiācéng"),
    ("Atrium", "🏢", "architecture-rare", "Atrio", "Atrium", "Atrio", "Átrio", "アトリウム", "中庭（天井）", "tiānjǐng"),
    ("Mosaic", "🎨", "architecture-rare", "Mosaico", "Mosaïque", "Mosaico", "Mosaico", "モザイク", "马赛克（镶嵌画）", "mǎsàikè"),
    ("Fresco", "🖼️", "architecture-rare", "Fresco", "Fresque", "Affresco", "Afresco", "フレスコ{画|が}", "壁画（湿壁画）", "shībìhuà"),
    ("Elevation (drawing)", "📐", "architecture-rare", "Alzado", "Élévation", "Prospetto", "Elevação (desenho)", "{立面図|りつめんず}", "立面图", "lìmiàntú"),
    ("Partition wall", "🧱", "architecture-rare", "Tabique", "Cloison", "Tramezzo", "Divisória", "{間仕切|まじき}り{壁|かべ}", "隔墙", "géqiáng"),
    ("Cladding", "🪵", "architecture-rare", "Revestimiento", "Bardage (revêtement)", "Rivestimento", "Revestimento", "{外装材|がいそうざい}", "外墙覆层", "wàiqiáng fùcéng"),
    ("Plumbing (system)", "🚰", "architecture-rare", "Fontanería (tuberías)", "Plomberie", "Impianto idraulico", "Encanamento", "{配管|はいかん}", "管道系统", "guǎndào xìtǒng"),
    ("Ventilation duct", "🌬️", "architecture-rare", "Conducto de ventilación", "Gaine de ventilation", "Condotto di ventilazione", "Duto de ventilação", "{換気|かんき}ダクト", "通风管道", "tōngfēng guǎndào"),
    ("Retrofit", "🔧", "architecture-rare", "Modernización (adaptación)", "Rénovation (mise à niveau)", "Adeguamento (retrofit)", "Modernização (retrofit)", "{改修|かいしゅう}（{後付|あとづ}け）", "改造升级", "gǎizào shēngjí"),
    # ---- household odds & ends ----
    ("Colander", "🥣", "household-rare", "Colador (escurridor)", "Passoire", "Scolapasta", "Escorredor", "ざる（{水切|みずき}り）", "滤盆", "lǜpén"),
    ("Ladle", "🥄", "household-rare", "Cucharón", "Louche", "Mestolo", "Concha", "おたま", "长柄勺", "chángbǐngsháo"),
    ("Whisk", "🥚", "household-rare", "Batidor (varillas)", "Fouet", "Frusta", "Batedor (fouet)", "{泡立|あわだ}て{器|き}", "打蛋器", "dǎdànqì"),
    ("Grater", "🧀", "household-rare", "Rallador", "Râpe", "Grattugia", "Ralador", "おろし{金|がね}", "刨丝器", "páosīqì"),
    ("Tongs", "🥢", "household-rare", "Pinzas (de cocina)", "Pince (de cuisine)", "Pinze (da cucina)", "Pegador (pinça)", "トング", "夹子", "jiāzi"),
    ("Spatula", "🍳", "household-rare", "Espátula", "Spatule", "Spatola (paletta)", "Espátula", "フライ{返|がえ}し", "锅铲", "guōchǎn"),
    ("Cutting board", "🔪", "household-rare", "Tabla de cortar", "Planche à découper", "Tagliere", "Tábua de cortar", "まな{板|いた}", "砧板", "zhēnbǎn"),
    ("French press", "☕", "household-rare", "Cafetera de émbolo", "Cafetière à piston", "Caffettiera a stantuffo", "Prensa francesa", "フレンチプレス", "法压壶", "fǎyāhú"),
    ("Coaster", "🥃", "household-rare", "Posavasos", "Dessous de verre", "Sottobicchiere", "Porta-copos", "コースター", "杯垫", "bēidiàn"),
    ("Trivet", "🍲", "household-rare", "Salvamanteles", "Dessous-de-plat", "Sottopentola", "Descanso de panela", "{鍋敷|なべし}き", "隔热垫", "gérèdiàn"),
    ("Oven mitt", "🧤", "household-rare", "Manopla (guante de horno)", "Gant de cuisine (manique)", "Guanto da forno", "Luva de forno", "{鍋|なべ}つかみ", "隔热手套", "gérè shǒutào"),
    ("Dish rack", "🍽️", "household-rare", "Escurreplatos", "Égouttoir", "Scolapiatti", "Escorredor de louça", "{水切|みずき}りラック", "碗架", "wǎnjià"),
    ("Dustpan", "🧹", "household-rare", "Recogedor", "Pelle (à poussière)", "Paletta", "Pá de lixo", "ちりとり", "簸箕", "bòji"),
    ("Mop", "🧽", "household-rare", "Fregona (trapeador)", "Serpillière (balai à franges)", "Mocio (straccio)", "Esfregão (rodo)", "モップ", "拖把", "tuōbǎ"),
    ("Clothespin", "📎", "household-rare", "Pinza de la ropa", "Pince à linge", "Molletta", "Prendedor de roupa", "{洗濯|せんたく}ばさみ", "衣夹", "yījiā"),
    ("Clothesline", "👕", "household-rare", "Tendedero", "Corde à linge", "Stendibiancheria (filo)", "Varal", "{物干|ものほ}し{綱|づな}", "晾衣绳", "liàngyīshéng"),
    ("Shoehorn", "👞", "household-rare", "Calzador", "Chausse-pied", "Calzascarpe", "Calçadeira", "{靴|くつ}べら", "鞋拔子", "xiébázi"),
    ("Doormat", "🚪", "household-rare", "Felpudo", "Paillasson", "Zerbino", "Capacho", "{玄関|げんかん}マット", "门垫", "méndiàn"),
    ("Doorknob", "🔘", "household-rare", "Pomo (de la puerta)", "Poignée de porte", "Pomello (maniglia)", "Maçaneta", "ドアノブ", "门把手", "mén bǎshou"),
    ("Hinge", "🚪", "household-rare", "Bisagra", "Charnière (gond)", "Cerniera", "Dobradiça", "{蝶番|ちょうつがい}", "铰链", "jiǎoliàn"),
    ("Latch", "🔒", "household-rare", "Pestillo (cerrojo)", "Loquet", "Chiavistello", "Trinco (ferrolho)", "{掛|か}け{金|がね}", "门闩", "ménshuān"),
    ("Peephole", "👁️", "household-rare", "Mirilla", "Judas (œilleton)", "Spioncino", "Olho mágico", "ドアスコープ（のぞき{穴|あな}）", "猫眼", "māoyǎn"),
    ("Blinds (window)", "🪟", "household-rare", "Persianas", "Stores", "Tapparelle (veneziane)", "Persianas", "ブラインド", "百叶窗", "bǎiyèchuāng"),
    ("Windowsill", "🪴", "household-rare", "Alféizar", "Rebord de fenêtre", "Davanzale", "Peitoril", "{窓台|まどだい}", "窗台", "chuāngtái"),
    ("Banister", "🪜", "household-rare", "Barandilla (pasamanos)", "Rampe (d’escalier)", "Corrimano (ringhiera)", "Corrimão", "{階段|かいだん}の{手|て}すり", "楼梯扶手", "lóutī fúshǒu"),
    ("Landing (stairs)", "🏠", "household-rare", "Rellano (descansillo)", "Palier", "Pianerottolo", "Patamar", "{踊|おど}り{場|ば}", "楼梯平台", "lóutī píngtái"),
    ("Crawl space", "🕷️", "household-rare", "Cámara sanitaria (espacio bajo el suelo)", "Vide sanitaire", "Intercapedine (vespaio)", "Porão baixo (espaço sob o piso)", "{床下|ゆかした}", "低矮空间（地板下）", "dìbǎn xià kōngjiān"),
    ("Cellar", "🍷", "household-rare", "Bodega (sótano)", "Cave", "Cantina", "Porão (adega)", "{地下室|ちかしつ}", "地窖", "dìjiào"),
    ("Pantry", "🥫", "household-rare", "Despensa", "Garde-manger (cellier)", "Dispensa", "Despensa", "{食料庫|しょくりょうこ}", "食品储藏室", "shípǐn chǔcángshì"),
    ("Utility room", "🧺", "household-rare", "Lavadero (cuarto de servicio)", "Buanderie (cellier)", "Lavanderia (ripostiglio)", "Lavanderia (área de serviço)", "{家事室|かじしつ}", "杂物间（洗衣房）", "záwùjiān"),
    ("Fuse box", "⚡", "household-rare", "Cuadro eléctrico (caja de fusibles)", "Tableau électrique (boîte à fusibles)", "Quadro elettrico (scatola dei fusibili)", "Quadro de luz (caixa de fusíveis)", "ブレーカーボックス", "保险丝盒", "bǎoxiǎnsīhé"),
    ("Dimmer switch", "🔅", "household-rare", "Regulador de intensidad", "Variateur", "Dimmer (varialuce)", "Dimmer (regulador de luz)", "{調光|ちょうこう}スイッチ", "调光开关", "tiáoguāng kāiguān"),
    ("Extension cord", "🔌", "household-rare", "Alargador (extensión)", "Rallonge", "Prolunga", "Extensão (elétrica)", "{延長|えんちょう}コード", "延长线", "yánchángxiàn"),
    ("Power strip", "🔌", "household-rare", "Regleta", "Multiprise", "Ciabatta (multipresa)", "Filtro de linha (régua)", "{電源|でんげん}タップ", "插线板", "chāxiànbǎn"),
    ("Carbon monoxide alarm", "🚨", "household-rare", "Detector de monóxido de carbono", "Détecteur de monoxyde de carbone", "Rilevatore di monossido di carbonio", "Detector de monóxido de carbono", "{一酸化炭素|いっさんかたんそ}{警報器|けいほうき}", "一氧化碳报警器", "yīyǎnghuàtàn bàojǐngqì"),
    ("First-aid kit", "🩹", "household-rare", "Botiquín", "Trousse de premiers secours", "Cassetta di pronto soccorso", "Kit de primeiros socorros", "{救急箱|きゅうきゅうばこ}", "急救箱", "jíjiùxiāng"),
    ("Sewing kit", "🧵", "household-rare", "Costurero", "Nécessaire de couture", "Kit da cucito", "Kit de costura", "{裁縫|さいほう}セット", "针线包", "zhēnxiànbāo"),
    ("Toolbox", "🧰", "household-rare", "Caja de herramientas", "Boîte à outils", "Cassetta degli attrezzi", "Caixa de ferramentas", "{工具箱|こうぐばこ}", "工具箱", "gōngjùxiāng"),
    ("Allen key", "🔩", "household-rare", "Llave Allen", "Clé Allen", "Chiave a brugola", "Chave Allen", "{六角|ろっかく}レンチ", "内六角扳手", "nèi liùjiǎo bānshǒu"),
    ("Pliers", "🔧", "household-rare", "Alicates", "Pince", "Pinze", "Alicate", "ペンチ", "钳子", "qiánzi"),
    ("Wrench", "🔧", "household-rare", "Llave inglesa", "Clé (à molette)", "Chiave inglese", "Chave inglesa", "レンチ（スパナ）", "扳手", "bānshǒu"),
    ("Tape measure", "📏", "household-rare", "Cinta métrica (metro)", "Mètre ruban", "Metro a nastro", "Fita métrica (trena)", "メジャー（{巻|ま}き{尺|じゃく}）", "卷尺", "juǎnchǐ"),
    ("Spirit level", "📐", "household-rare", "Nivel (de burbuja)", "Niveau à bulle", "Livella", "Nível (de bolha)", "{水準器|すいじゅんき}", "水平仪", "shuǐpíngyí"),
    ("Drawer organizer", "🗃️", "household-rare", "Organizador de cajones", "Range-tiroir (organiseur)", "Organizzatore per cassetti", "Organizador de gaveta", "{引|ひ}き{出|だ}しの{仕切|しき}り", "抽屉收纳盒", "chōuti shōunàhé"),
    ("Bin liner", "🗑️", "household-rare", "Bolsa de basura", "Sac-poubelle", "Sacchetto per la spazzatura", "Saco de lixo", "ゴミ{袋|ぶくろ}", "垃圾袋", "lājīdài"),
]
