# -*- coding: utf-8 -*-
# B2 vocabulary batch 1 — values & ethics, workplace & business, law & crime, science & technology, environment
TIER = 'B2'
TOPICS = {
    'values-ethics': 'Values & Ethics', 'business': 'Workplace & Business', 'law-crime': 'Law & Crime',
    'science-tech': 'Science & Technology', 'environment-2': 'Environment & Climate',
}
WORDS = [
    # ---- values & ethics ----
    ("Honesty", "🤲", "values-ethics", "Honestidad", "Honnêteté", "Onestà", "Honestidade", "{正直|しょうじき}さ", "诚实（品质）", "chéngshí"),
    ("Integrity", "🧭", "values-ethics", "Integridad", "Intégrité", "Integrità", "Integridade", "{誠実|せいじつ}さ（{高潔|こうけつ}）", "正直", "zhèngzhí"),
    ("Dignity", "👑", "values-ethics", "Dignidad", "Dignité", "Dignità", "Dignidade", "{尊厳|そんげん}", "尊严", "zūnyán"),
    ("Morality", "⚖️", "values-ethics", "Moralidad", "Moralité", "Moralità", "Moralidade", "{道徳|どうとく}", "道德", "dàodé"),
    ("Principle", "📜", "values-ethics", "Principio", "Principe", "Principio", "Princípio", "{原則|げんそく}", "原则", "yuánzé"),
    ("Virtue", "🌟", "values-ethics", "Virtud", "Vertu", "Virtù", "Virtude", "{美徳|びとく}", "美德", "měidé"),
    ("Vice", "🍷", "values-ethics", "Vicio", "Vice", "Vizio", "Vício", "{悪徳|あくとく}", "恶习", "èxí"),
    ("Greed", "🤑", "values-ethics", "Codicia", "Avidité", "Avidità", "Ganância", "{欲|よく}", "贪婪", "tānlán"),
    ("Courage", "🦁", "values-ethics", "Coraje", "Courage", "Coraggio", "Coragem", "{勇気|ゆうき}", "勇气", "yǒngqì"),
    ("Cowardice", "🐔", "values-ethics", "Cobardía", "Lâcheté", "Codardia", "Covardia", "{臆病|おくびょう}さ", "胆怯", "dǎnqiè"),
    ("Generosity", "🎁", "values-ethics", "Generosidad", "Générosité", "Generosità", "Generosidade", "{寛大|かんだい}さ", "慷慨", "kāngkǎi"),
    ("Gratitude", "🙏", "values-ethics", "Gratitud", "Gratitude", "Gratitudine", "Gratidão", "{感謝|かんしゃ}", "感恩", "gǎn'ēn"),
    ("Compassion", "💙", "values-ethics", "Compasión", "Compassion", "Compassione", "Compaixão", "{思|おも}いやり", "怜悯", "liánmǐn"),
    ("Tolerance", "🤝", "values-ethics", "Tolerancia", "Tolérance", "Tolleranza", "Tolerância", "{寛容|かんよう}", "宽容", "kuānróng"),
    ("Prejudice", "🚧", "values-ethics", "Prejuicio", "Préjugé", "Pregiudizio", "Preconceito", "{偏見|へんけん}", "偏见", "piānjiàn"),
    ("Discrimination", "⛔", "values-ethics", "Discriminación", "Discrimination", "Discriminazione", "Discriminação", "{差別|さべつ}", "歧视", "qíshì"),
    ("Equality", "🟰", "values-ethics", "Igualdad", "Égalité", "Uguaglianza", "Igualdade", "{平等|びょうどう}", "平等", "píngděng"),
    ("Inequality", "📊", "values-ethics", "Desigualdad", "Inégalité", "Disuguaglianza", "Desigualdade", "{不平等|ふびょうどう}", "不平等", "bù píngděng"),
    ("Fairness", "⚖️", "values-ethics", "Justicia (equidad)", "Équité", "Equità", "Justiça (equidade)", "{公正|こうせい}さ", "公正", "gōngzhèng"),
    ("Corruption", "💸", "values-ethics", "Corrupción", "Corruption", "Corruzione", "Corrupção", "{腐敗|ふはい}", "腐败", "fǔbài"),
    ("Temptation", "🍎", "values-ethics", "Tentación", "Tentation", "Tentazione", "Tentação", "{誘惑|ゆうわく}", "诱惑", "yòuhuò"),
    ("Guilt", "😔", "values-ethics", "Culpa", "Culpabilité", "Colpa (senso di)", "Culpa", "{罪悪感|ざいあくかん}", "罪恶感", "zuì'ègǎn"),
    ("Shame", "🙈", "values-ethics", "Vergüenza", "Honte", "Vergogna", "Vergonha", "{恥|はじ}", "羞耻", "xiūchǐ"),
    ("Pride (self-respect)", "🦚", "values-ethics", "Orgullo", "Fierté", "Orgoglio", "Orgulho", "{誇|ほこ}り", "自豪感", "zìháogǎn"),
    ("Humility", "🙇", "values-ethics", "Humildad", "Humilité", "Umiltà", "Humildade", "{謙虚|けんきょ}さ", "谦逊", "qiānxùn"),
    ("Ambition", "🚀", "values-ethics", "Ambición", "Ambition", "Ambizione", "Ambição", "{野心|やしん}", "抱负", "bàofù"),
    ("Patience", "⏳", "values-ethics", "Paciencia", "Patience", "Pazienza", "Paciência", "{忍耐|にんたい}", "耐心", "nàixīn"),
    ("Sacrifice", "🕯️", "values-ethics", "Sacrificio", "Sacrifice", "Sacrificio", "Sacrifício", "{犠牲|ぎせい}", "牺牲", "xīshēng"),
    ("Duty", "🎖️", "values-ethics", "Deber", "Devoir (obligation)", "Dovere", "Dever", "{義務|ぎむ}", "义务", "yìwù"),
    ("Conscience", "🧠", "values-ethics", "Conciencia", "Conscience", "Coscienza", "Consciência", "{良心|りょうしん}", "良心", "liángxīn"),
    ("Hypocrisy", "🎭", "values-ethics", "Hipocresía", "Hypocrisie", "Ipocrisia", "Hipocrisia", "{偽善|ぎぜん}", "虚伪", "xūwěi"),
    ("Forgiveness", "🕊️", "values-ethics", "Perdón", "Pardon", "Perdono", "Perdão", "{許|ゆる}し", "宽恕", "kuānshù"),

    # ---- workplace & business ----
    ("Agenda", "📋", "business", "Orden del día", "Ordre du jour", "Ordine del giorno", "Pauta", "{議題|ぎだい}", "议程", "yìchéng"),
    ("Minutes (of a meeting)", "📝", "business", "Acta", "Compte rendu", "Verbale", "Ata", "{議事録|ぎじろく}", "会议记录", "huìyì jìlù"),
    ("Department", "🏢", "business", "Departamento", "Service (département)", "Reparto", "Departamento", "{部署|ぶしょ}", "部门", "bùmén"),
    ("Branch (office)", "🏬", "business", "Sucursal", "Succursale", "Filiale", "Filial", "{支店|してん}", "分公司", "fēngōngsī"),
    ("Headquarters", "🏛️", "business", "Sede central", "Siège social", "Sede centrale", "Sede", "{本社|ほんしゃ}", "总部", "zǒngbù"),
    ("Revenue", "💰", "business", "Ingresos (empresa)", "Chiffre d’affaires", "Fatturato", "Receita", "{売上|うりあげ}", "营收", "yíngshōu"),
    ("Stakeholder", "🧑‍🤝‍🧑", "business", "Parte interesada", "Partie prenante", "Parte interessata", "Parte interessada", "{利害関係者|りがいかんけいしゃ}", "利益相关方", "lìyì xiāngguānfāng"),
    ("Shareholder", "📈", "business", "Accionista", "Actionnaire", "Azionista", "Acionista", "{株主|かぶぬし}", "股东", "gǔdōng"),
    ("Client", "🤵", "business", "Cliente (empresa)", "Client (entreprise)", "Cliente (azienda)", "Cliente (empresa)", "クライアント", "客户", "kèhù"),
    ("Supplier", "🚚", "business", "Proveedor", "Fournisseur", "Fornitore", "Fornecedor", "{供給業者|きょうきゅうぎょうしゃ}", "供应商", "gōngyìngshāng"),
    ("Quote (price estimate)", "🧾", "business", "Presupuesto (cotización)", "Devis", "Preventivo", "Orçamento (cotação)", "{見積|みつ}もり", "报价", "bàojià"),
    ("Proposal", "📄", "business", "Propuesta", "Proposition", "Proposta", "Proposta", "{提案書|ていあんしょ}", "提案", "tí'àn"),
    ("Bid", "🔨", "business", "Oferta (licitación)", "Offre (appel d’offres)", "Offerta (gara)", "Proposta (licitação)", "{入札|にゅうさつ}", "投标", "tóubiāo"),
    ("Merger", "🔗", "business", "Fusión", "Fusion", "Fusione", "Fusão", "{合併|がっぺい}", "合并", "hébìng"),
    ("Layoff", "📉", "business", "Despido (recorte)", "Licenciement", "Licenziamento", "Demissão (corte)", "{解雇|かいこ}（{人員削減|じんいんさくげん}）", "裁员", "cáiyuán"),
    ("To outsource", "🌐", "business", "Subcontratar", "Externaliser", "Esternalizzare", "Terceirizar", "{外注|がいちゅう}する", "外包", "wàibāo"),
    ("To delegate", "👉", "business", "Delegar", "Déléguer", "Delegare", "Delegar", "{任|まか}せる", "委派", "wěipài"),
    ("To supervise", "👁️", "business", "Supervisar", "Superviser", "Supervisionare", "Supervisionar", "{監督|かんとく}する", "监督", "jiāndū"),
    ("Performance review", "📊", "business", "Evaluación de desempeño", "Entretien annuel", "Valutazione delle prestazioni", "Avaliação de desempenho", "{人事評価|じんじひょうか}", "绩效评估", "jìxiào pínggū"),
    ("Strategy", "♟️", "business", "Estrategia", "Stratégie", "Strategia", "Estratégia", "{戦略|せんりゃく}", "战略", "zhànlüè"),
    ("Target", "🎯", "business", "Objetivo (cifra)", "Objectif (chiffré)", "Obiettivo (numerico)", "Meta (numérica)", "{目標値|もくひょうち}", "指标", "zhǐbiāo"),
    ("Quarter (business)", "📆", "business", "Trimestre", "Trimestre", "Trimestre", "Trimestre", "{四半期|しはんき}", "季度", "jìdù"),
    ("Benchmark", "📏", "business", "Punto de referencia", "Référence", "Parametro di riferimento", "Referência", "{基準|きじゅん}", "基准", "jīzhǔn"),
    ("To brainstorm", "🧠", "business", "Hacer una lluvia de ideas", "Faire un brainstorming", "Fare brainstorming", "Fazer um brainstorm", "ブレストする", "集思广益", "jísī guǎngyì"),
    ("To network", "🕸️", "business", "Hacer contactos", "Réseauter", "Fare networking", "Fazer networking", "{人脈|じんみゃく}を{作|つく}る", "建立人脉", "jiànlì rénmài"),
    ("To prioritize", "🥇", "business", "Priorizar", "Prioriser", "Dare priorità", "Priorizar", "{優先|ゆうせん}する", "优先处理", "yōuxiān chǔlǐ"),
    ("To streamline", "⚡", "business", "Agilizar", "Rationaliser", "Snellire", "Otimizar", "{効率化|こうりつか}する", "精简", "jīngjiǎn"),
    ("Startup", "🚀", "business", "Startup", "Start-up", "Startup", "Startup", "スタートアップ", "创业公司", "chuàngyè gōngsī"),
    ("Entrepreneur", "💡", "business", "Emprendedor", "Entrepreneur", "Imprenditore", "Empreendedor", "{起業家|きぎょうか}", "企业家", "qǐyèjiā"),
    ("Profit margin", "📈", "business", "Margen de beneficio", "Marge bénéficiaire", "Margine di profitto", "Margem de lucro", "{利益率|りえきりつ}", "利润率", "lìrùnlǜ"),
    ("Competitor", "🏁", "business", "Competidor", "Concurrent", "Concorrente", "Concorrente", "{競合|きょうごう}", "竞争对手", "jìngzhēng duìshǒu"),
    ("Milestone (project)", "🚩", "business", "Hito (proyecto)", "Jalon", "Traguardo intermedio", "Marco (projeto)", "マイルストーン", "阶段目标", "jiēduàn mùbiāo"),

    # ---- law & crime ----
    ("Suspect", "🕵️", "law-crime", "Sospechoso", "Suspect", "Sospettato", "Suspeito", "{容疑者|ようぎしゃ}", "嫌疑人", "xiányírén"),
    ("Witness", "👁️", "law-crime", "Testigo", "Témoin", "Testimone", "Testemunha", "{目撃者|もくげきしゃ}", "证人", "zhèngrén"),
    ("Victim", "🩹", "law-crime", "Víctima", "Victime", "Vittima", "Vítima", "{被害者|ひがいしゃ}", "受害者", "shòuhàizhě"),
    ("Trial", "⚖️", "law-crime", "Juicio", "Procès", "Processo", "Julgamento", "{裁判|さいばん}", "审判", "shěnpàn"),
    ("Judge", "👨‍⚖️", "law-crime", "Juez", "Juge", "Giudice", "Juiz", "{裁判官|さいばんかん}", "法官", "fǎguān"),
    ("Jury", "👥", "law-crime", "Jurado", "Jury", "Giuria", "Júri", "{陪審|ばいしん}", "陪审团", "péishěntuán"),
    ("Verdict", "🔨", "law-crime", "Veredicto", "Verdict", "Verdetto", "Veredito", "{判決|はんけつ}", "判决", "pànjué"),
    ("Convicted", "⛓️", "law-crime", "Condenado", "Condamné", "Condannato", "Condenado", "{有罪判決|ゆうざいはんけつ}を{受|う}けた", "被定罪", "bèi dìngzuì"),
    ("Innocent", "🕊️", "law-crime", "Inocente", "Innocent", "Innocente", "Inocente", "{無罪|むざい}", "无罪", "wúzuì"),
    ("Prison sentence", "🏚️", "law-crime", "Pena de prisión", "Peine de prison", "Pena detentiva", "Pena de prisão", "{懲役|ちょうえき}", "监禁刑", "jiānjìn xíng"),
    ("Theft", "🥷", "law-crime", "Robo (hurto)", "Vol", "Furto", "Furto", "{窃盗|せっとう}", "偷窃", "tōuqiè"),
    ("Robbery", "🔫", "law-crime", "Atraco", "Braquage", "Rapina", "Assalto", "{強盗|ごうとう}", "抢劫", "qiǎngjié"),
    ("Burglary", "🏠", "law-crime", "Allanamiento", "Cambriolage", "Furto con scasso", "Arrombamento", "{住居侵入|じゅうきょしんにゅう}", "入室盗窃", "rùshì dàoqiè"),
    ("Fraud", "🎭", "law-crime", "Fraude", "Fraude", "Truffa", "Fraude", "{詐欺|さぎ}", "诈骗", "zhàpiàn"),
    ("Bribery", "💵", "law-crime", "Soborno", "Corruption (pot-de-vin)", "Corruzione (tangente)", "Suborno", "{賄賂|わいろ}", "贿赂", "huìlù"),
    ("Assault", "👊", "law-crime", "Agresión", "Agression", "Aggressione", "Agressão", "{暴行|ぼうこう}", "袭击", "xíjī"),
    ("Murder", "🔪", "law-crime", "Asesinato", "Meurtre", "Omicidio", "Assassinato", "{殺人|さつじん}", "谋杀", "móushā"),
    ("Kidnapping", "🚐", "law-crime", "Secuestro", "Enlèvement", "Rapimento", "Sequestro", "{誘拐|ゆうかい}", "绑架", "bǎngjià"),
    ("Smuggling", "📦", "law-crime", "Contrabando", "Contrebande", "Contrabbando", "Contrabando", "{密輸|みつゆ}", "走私", "zǒusī"),
    ("To arrest", "🚔", "law-crime", "Arrestar", "Arrêter", "Arrestare", "Prender", "{逮捕|たいほ}する", "逮捕", "dàibǔ"),
    ("To charge (with a crime)", "📜", "law-crime", "Acusar", "Inculper", "Incriminare", "Acusar", "{起訴|きそ}する", "起诉", "qǐsù"),
    ("To sue", "⚖️", "law-crime", "Demandar", "Poursuivre en justice", "Fare causa", "Processar", "{訴|うった}える", "控告", "kònggào"),
    ("Lawsuit", "📂", "law-crime", "Demanda", "Procès (civil)", "Causa", "Ação judicial", "{訴訟|そしょう}", "诉讼", "sùsòng"),
    ("Court", "🏛️", "law-crime", "Tribunal", "Tribunal", "Tribunale", "Tribunal", "{裁判所|さいばんしょ}", "法院", "fǎyuàn"),
    ("Prosecutor", "🧑‍⚖️", "law-crime", "Fiscal", "Procureur", "Procuratore", "Promotor", "{検察官|けんさつかん}", "检察官", "jiǎncháguān"),
    ("Defense (legal)", "🛡️", "law-crime", "Defensa", "Défense", "Difesa", "Defesa", "{弁護|べんご}", "辩护", "biànhù"),
    ("Appeal (legal)", "🔁", "law-crime", "Apelación", "Appel", "Appello", "Recurso", "{控訴|こうそ}", "上诉", "shàngsù"),
    ("Bail", "💰", "law-crime", "Fianza", "Caution (judiciaire)", "Cauzione (giudiziaria)", "Fiança", "{保釈金|ほしゃくきん}", "保释金", "bǎoshìjīn"),
    ("Alibi", "🕰️", "law-crime", "Coartada", "Alibi", "Alibi", "Álibi", "アリバイ", "不在场证明", "bùzàichǎng zhèngmíng"),
    ("Custody (police)", "🔒", "law-crime", "Detención", "Garde à vue", "Custodia", "Custódia", "{拘留|こうりゅう}", "拘留", "jūliú"),
    ("Investigation", "🔍", "law-crime", "Investigación (policial)", "Enquête", "Indagine", "Investigação", "{捜査|そうさ}", "调查", "diàochá"),
    ("Detective", "🕵️‍♀️", "law-crime", "Detective", "Enquêteur", "Detective", "Detetive", "{刑事|けいじ}", "侦探", "zhēntàn"),

    # ---- science & technology ----
    ("Experiment", "🧪", "science-tech", "Experimento", "Expérience", "Esperimento", "Experimento", "{実験|じっけん}", "实验", "shíyàn"),
    ("Hypothesis", "❔", "science-tech", "Hipótesis", "Hypothèse", "Ipotesi", "Hipótese", "{仮説|かせつ}", "假说", "jiǎshuō"),
    ("Theory", "📐", "science-tech", "Teoría", "Théorie", "Teoria", "Teoria", "{理論|りろん}", "理论", "lǐlùn"),
    ("Data", "📊", "science-tech", "Datos", "Données", "Dati", "Dados", "データ", "数据", "shùjù"),
    ("Analysis", "🔬", "science-tech", "Análisis", "Analyse", "Analisi", "Análise", "{分析|ぶんせき}", "分析", "fēnxī"),
    ("To analyze", "🧮", "science-tech", "Analizar", "Analyser", "Analizzare", "Analisar", "{分析|ぶんせき}する", "分析（动词）", "fēnxī"),
    ("To measure", "📏", "science-tech", "Medir", "Mesurer", "Misurare", "Medir", "{測|はか}る", "测量", "cèliáng"),
    ("Laboratory", "🥼", "science-tech", "Laboratorio", "Laboratoire", "Laboratorio", "Laboratório", "{実験室|じっけんしつ}", "实验室", "shíyànshì"),
    ("Chemical", "⚗️", "science-tech", "Químico", "Chimique", "Chimico", "Químico", "{化学物質|かがくぶっしつ}", "化学物质", "huàxué wùzhì"),
    ("Molecule", "🔬", "science-tech", "Molécula", "Molécule", "Molecola", "Molécula", "{分子|ぶんし}", "分子", "fēnzǐ"),
    ("Atom", "⚛️", "science-tech", "Átomo", "Atome", "Atomo", "Átomo", "{原子|げんし}", "原子", "yuánzǐ"),
    ("Cell (biology)", "🦠", "science-tech", "Célula", "Cellule", "Cellula", "Célula", "{細胞|さいぼう}", "细胞", "xìbāo"),
    ("Gene", "🧬", "science-tech", "Gen", "Gène", "Gene", "Gene", "{遺伝子|いでんし}", "基因", "jīyīn"),
    ("Evolution", "🐒", "science-tech", "Evolución", "Évolution", "Evoluzione", "Evolução", "{進化|しんか}", "进化", "jìnhuà"),
    ("Species", "🦋", "science-tech", "Especie", "Espèce", "Specie", "Espécie", "{種|しゅ}", "物种", "wùzhǒng"),
    ("Gravity", "🍎", "science-tech", "Gravedad", "Gravité", "Gravità", "Gravidade", "{重力|じゅうりょく}", "重力", "zhònglì"),
    ("Orbit", "🪐", "science-tech", "Órbita", "Orbite", "Orbita", "Órbita", "{軌道|きどう}", "轨道", "guǐdào"),
    ("Satellite", "🛰️", "science-tech", "Satélite", "Satellite", "Satellite", "Satélite", "{人工衛星|じんこうえいせい}", "卫星", "wèixīng"),
    ("Artificial intelligence", "🤖", "science-tech", "Inteligencia artificial", "Intelligence artificielle", "Intelligenza artificiale", "Inteligência artificial", "{人工知能|じんこうちのう}", "人工智能", "réngōng zhìnéng"),
    ("Algorithm", "🧮", "science-tech", "Algoritmo", "Algorithme", "Algoritmo", "Algoritmo", "アルゴリズム", "算法", "suànfǎ"),
    ("Software", "💾", "science-tech", "Software", "Logiciel", "Software", "Software", "ソフトウェア", "软件", "ruǎnjiàn"),
    ("Hardware", "🖥️", "science-tech", "Hardware", "Matériel", "Hardware", "Hardware", "ハードウェア", "硬件", "yìngjiàn"),
    ("Database", "🗄️", "science-tech", "Base de datos", "Base de données", "Database", "Banco de dados", "データベース", "数据库", "shùjùkù"),
    ("To code (program)", "👩‍💻", "science-tech", "Programar", "Coder", "Programmare", "Programar", "コードを{書|か}く", "编程", "biānchéng"),
    ("Bug (software)", "🐛", "science-tech", "Error (bug)", "Bug", "Bug", "Bug", "バグ", "程序错误", "chéngxù cuòwù"),
    ("Encryption", "🔐", "science-tech", "Cifrado", "Chiffrement", "Crittografia", "Criptografia", "{暗号化|あんごうか}", "加密", "jiāmì"),
    ("Cybersecurity", "🛡️", "science-tech", "Ciberseguridad", "Cybersécurité", "Sicurezza informatica", "Cibersegurança", "サイバーセキュリティ", "网络安全", "wǎngluò ānquán"),
    ("Virtual reality", "🥽", "science-tech", "Realidad virtual", "Réalité virtuelle", "Realtà virtuale", "Realidade virtual", "{仮想現実|かそうげんじつ}", "虚拟现实", "xūnǐ xiànshí"),
    ("Innovation", "💡", "science-tech", "Innovación", "Innovation", "Innovazione", "Inovação", "{革新|かくしん}", "创新", "chuàngxīn"),
    ("Breakthrough", "🚀", "science-tech", "Avance (descubrimiento)", "Percée", "Svolta", "Avanço", "{大発見|だいはっけん}", "突破", "tūpò"),
    ("Robot", "🤖", "science-tech", "Robot", "Robot", "Robot", "Robô", "ロボット", "机器人", "jīqìrén"),
    ("Automation", "⚙️", "science-tech", "Automatización", "Automatisation", "Automazione", "Automação", "{自動化|じどうか}", "自动化", "zìdònghuà"),

    # ---- environment & climate ----
    ("Sustainability", "🌱", "environment-2", "Sostenibilidad", "Durabilité", "Sostenibilità", "Sustentabilidade", "{持続可能性|じぞくかのうせい}", "可持续性", "kě chíxù xìng"),
    ("Sustainable", "♻️", "environment-2", "Sostenible", "Durable", "Sostenibile", "Sustentável", "{持続可能|じぞくかのう}な", "可持续的", "kě chíxù de"),
    ("Carbon footprint", "👣", "environment-2", "Huella de carbono", "Empreinte carbone", "Impronta di carbonio", "Pegada de carbono", "カーボンフットプリント", "碳足迹", "tàn zújì"),
    ("Emissions", "🏭", "environment-2", "Emisiones", "Émissions", "Emissioni", "Emissões", "{排出|はいしゅつ}", "排放", "páifàng"),
    ("Greenhouse gas", "🌫️", "environment-2", "Gas de efecto invernadero", "Gaz à effet de serre", "Gas serra", "Gás de efeito estufa", "{温室効果|おんしつこうか}ガス", "温室气体", "wēnshì qìtǐ"),
    ("Global warming", "🌡️", "environment-2", "Calentamiento global", "Réchauffement climatique", "Riscaldamento globale", "Aquecimento global", "{地球温暖化|ちきゅうおんだんか}", "全球变暖", "quánqiú biànnuǎn"),
    ("Deforestation", "🪓", "environment-2", "Deforestación", "Déforestation", "Deforestazione", "Desmatamento", "{森林破壊|しんりんはかい}", "森林砍伐", "sēnlín kǎnfá"),
    ("Biodiversity", "🦜", "environment-2", "Biodiversidad", "Biodiversité", "Biodiversità", "Biodiversidade", "{生物多様性|せいぶつたようせい}", "生物多样性", "shēngwù duōyàngxìng"),
    ("Ecosystem", "🌿", "environment-2", "Ecosistema", "Écosystème", "Ecosistema", "Ecossistema", "{生態系|せいたいけい}", "生态系统", "shēngtài xìtǒng"),
    ("Habitat", "🏞️", "environment-2", "Hábitat", "Habitat", "Habitat", "Habitat", "{生息地|せいそくち}", "栖息地", "qīxīdì"),
    ("Endangered species", "🐼", "environment-2", "Especie en peligro", "Espèce menacée", "Specie in pericolo", "Espécie ameaçada", "{絶滅危惧種|ぜつめつきぐしゅ}", "濒危物种", "bīnwēi wùzhǒng"),
    ("Extinction", "🦕", "environment-2", "Extinción", "Extinction", "Estinzione", "Extinção", "{絶滅|ぜつめつ}", "灭绝", "mièjué"),
    ("Conservation", "🛡️", "environment-2", "Conservación", "Conservation", "Conservazione", "Conservação", "{保全|ほぜん}", "保护（自然）", "bǎohù"),
    ("Wildlife", "🦌", "environment-2", "Fauna silvestre", "Faune sauvage", "Fauna selvatica", "Vida selvagem", "{野生生物|やせいせいぶつ}", "野生动物", "yěshēng dòngwù"),
    ("Natural resources", "⛏️", "environment-2", "Recursos naturales", "Ressources naturelles", "Risorse naturali", "Recursos naturais", "{天然資源|てんねんしげん}", "自然资源", "zìrán zīyuán"),
    ("Fossil fuels", "🛢️", "environment-2", "Combustibles fósiles", "Énergies fossiles", "Combustibili fossili", "Combustíveis fósseis", "{化石燃料|かせきねんりょう}", "化石燃料", "huàshí ránliào"),
    ("Solar panel", "☀️", "environment-2", "Panel solar", "Panneau solaire", "Pannello solare", "Painel solar", "ソーラーパネル", "太阳能板", "tàiyángnéng bǎn"),
    ("Wind turbine", "🌬️", "environment-2", "Turbina eólica", "Éolienne", "Turbina eolica", "Turbina eólica", "{風力|ふうりょく}タービン", "风力涡轮机", "fēnglì wōlúnjī"),
    ("Landfill", "🗑️", "environment-2", "Vertedero", "Décharge", "Discarica", "Aterro", "{埋|う}め{立|た}て{地|ち}", "垃圾填埋场", "lājī tiánmáichǎng"),
    ("Compost", "🍂", "environment-2", "Compost", "Compost", "Compost", "Compostagem", "{堆肥|たいひ}", "堆肥", "duīféi"),
    ("To conserve", "💧", "environment-2", "Conservar", "Économiser (préserver)", "Conservare", "Conservar", "{節約|せつやく}する（{資源|しげん}）", "节约（资源）", "jiéyuē"),
    ("To preserve", "🏺", "environment-2", "Preservar", "Préserver", "Preservare", "Preservar", "{保護|ほご}する", "保存", "bǎocún"),
    ("Sea level", "🌊", "environment-2", "Nivel del mar", "Niveau de la mer", "Livello del mare", "Nível do mar", "{海面|かいめん}", "海平面", "hǎipíngmiàn"),
    ("Glacier", "🧊", "environment-2", "Glaciar", "Glacier", "Ghiacciaio", "Geleira", "{氷河|ひょうが}", "冰川", "bīngchuān"),
    ("To melt", "💧", "environment-2", "Derretirse", "Fondre", "Sciogliersi", "Derreter", "{溶|と}ける", "融化", "rónghuà"),
    ("Famine", "🍽️", "environment-2", "Hambruna", "Famine", "Carestia", "Fome (coletiva)", "{飢饉|ききん}", "饥荒", "jīhuāng"),
    ("Overpopulation", "👥", "environment-2", "Superpoblación", "Surpopulation", "Sovrappopolazione", "Superpopulação", "{人口過剰|じんこうかじょう}", "人口过剩", "rénkǒu guòshèng"),
    ("To pollute", "🏭", "environment-2", "Contaminar", "Polluer", "Inquinare", "Poluir", "{汚染|おせん}する", "污染（动词）", "wūrǎn"),
    ("Single-use plastic", "🥤", "environment-2", "Plástico de un solo uso", "Plastique à usage unique", "Plastica monouso", "Plástico descartável", "{使|つか}い{捨|す}てプラスチック", "一次性塑料", "yícìxìng sùliào"),
    ("Environmentalist", "🌍", "environment-2", "Ecologista", "Écologiste", "Ambientalista", "Ambientalista", "{環境保護活動家|かんきょうほごかつどうか}", "环保主义者", "huánbǎo zhǔyìzhě"),
    ("Recycling bin", "♻️", "environment-2", "Contenedor de reciclaje", "Bac de recyclage", "Bidone della raccolta differenziata", "Lixeira de reciclagem", "リサイクル{箱|ばこ}", "回收箱", "huíshōuxiāng"),
    ("Organic farming", "🚜", "environment-2", "Agricultura ecológica", "Agriculture biologique", "Agricoltura biologica", "Agricultura orgânica", "{有機農業|ゆうきのうぎょう}", "有机农业", "yǒujī nóngyè"),
]
