# -*- coding: utf-8 -*-
# C1 vocabulary batch 1 — news & media register, academic register, phrasal verbs I & II, colloquial speech
TIER = 'C1'
TOPICS = {
    'media-register': 'News & Media Register', 'academic-register': 'Academic Register',
    'phrasal-verbs-1': 'Phrasal Verbs I', 'phrasal-verbs-2': 'Phrasal Verbs II', 'colloquial': 'Colloquial Speech',
}
WORDS = [
    # ---- news & media register ----
    ("Broadcast", "📡", "media-register", "Emisión", "Émission (diffusion)", "Trasmissione", "Transmissão", "{放送|ほうそう}", "广播（播出）", "guǎngbō"),
    ("Coverage", "📰", "media-register", "Cobertura", "Couverture (médiatique)", "Copertura", "Cobertura", "{報道|ほうどう}", "报道", "bàodào"),
    ("Correspondent", "🎤", "media-register", "Corresponsal", "Correspondant", "Corrispondente", "Correspondente", "{特派員|とくはいん}", "记者（驻外）", "zhùwài jìzhě"),
    ("Anchor (news)", "🗞️", "media-register", "Presentador", "Présentateur", "Conduttore", "Âncora", "キャスター", "主播", "zhǔbō"),
    ("Editorial", "✍️", "media-register", "Editorial", "Éditorial", "Editoriale", "Editorial", "{社説|しゃせつ}", "社论", "shèlùn"),
    ("Slant (bias)", "📐", "media-register", "Sesgo (enfoque)", "Orientation (parti pris)", "Taglio (di parte)", "Viés (enfoque)", "{偏|かたよ}り", "倾向性", "qīngxiàngxìng"),
    ("To leak", "💧", "media-register", "Filtrar", "Divulguer (fuiter)", "Far trapelare", "Vazar", "リークする", "泄露", "xièlòu"),
    ("Source (journalism)", "🕵️", "media-register", "Fuente", "Source", "Fonte", "Fonte", "{情報源|じょうほうげん}", "消息来源", "xiāoxi láiyuán"),
    ("Whistleblower", "📣", "media-register", "Denunciante", "Lanceur d’alerte", "Informatore", "Denunciante", "{内部告発者|ないぶこくはつしゃ}", "举报人", "jǔbàorén"),
    ("Censorship", "🚫", "media-register", "Censura", "Censure", "Censura", "Censura", "{検閲|けんえつ}", "审查", "shěnchá"),
    ("Propaganda", "📢", "media-register", "Propaganda", "Propagande", "Propaganda", "Propaganda", "プロパガンダ", "宣传（政治）", "xuānchuán"),
    ("Misinformation", "❌", "media-register", "Desinformación", "Désinformation", "Disinformazione", "Desinformação", "{誤情報|ごじょうほう}", "错误信息", "cuòwù xìnxī"),
    ("Fact-check", "✅", "media-register", "Verificación de datos", "Vérification des faits", "Verifica dei fatti", "Checagem de fatos", "ファクトチェック", "事实核查", "shìshí héchá"),
    ("Viral", "🦠", "media-register", "Viral", "Viral", "Virale", "Viral", "バズった", "疯传", "fēngchuán"),
    ("Clickbait", "🎣", "media-register", "Ciberanzuelo", "Piège à clics", "Clickbait", "Caça-clique", "{釣|つ}り{見出|みだ}し", "标题党", "biāotídǎng"),
    ("Tabloid", "🗞️", "media-register", "Prensa amarilla", "Tabloïd", "Tabloid", "Tabloide", "タブロイド{紙|し}", "小报", "xiǎobào"),
    ("Press conference", "🎙️", "media-register", "Rueda de prensa", "Conférence de presse", "Conferenza stampa", "Coletiva de imprensa", "{記者会見|きしゃかいけん}", "新闻发布会", "xīnwén fābùhuì"),
    ("Press release", "📄", "media-register", "Comunicado de prensa", "Communiqué de presse", "Comunicato stampa", "Comunicado à imprensa", "プレスリリース", "新闻稿", "xīnwéngǎo"),
    ("Exclusive (story)", "⭐", "media-register", "Exclusiva", "Exclusivité", "Esclusiva", "Furo (exclusivo)", "{独占|どくせん}スクープ", "独家新闻", "dújiā xīnwén"),
    ("Breaking news", "🚨", "media-register", "Última hora", "Flash info", "Ultime notizie", "Notícia de última hora", "{速報|そくほう}", "突发新闻", "tūfā xīnwén"),
    ("Viewership", "👁️", "media-register", "Audiencia", "Audience", "Ascolti", "Audiência", "{視聴者数|しちょうしゃすう}", "收视率", "shōushìlǜ"),
    ("Subscriber", "🔔", "media-register", "Suscriptor", "Abonné", "Abbonato", "Assinante", "{登録者|とうろくしゃ}", "订阅者", "dìngyuèzhě"),
    ("Paywall", "💳", "media-register", "Muro de pago", "Paywall", "Paywall", "Paywall", "ペイウォール", "付费墙", "fùfèiqiáng"),
    ("Influencer", "🤳", "media-register", "Influencer", "Influenceur", "Influencer", "Influenciador", "インフルエンサー", "网红", "wǎnghóng"),
    ("To trend", "📈", "media-register", "Ser tendencia", "Être en tendance", "Essere in tendenza", "Bombar", "トレンド{入|い}りする", "上热搜", "shàng rèsōu"),
    ("Hashtag", "#️⃣", "media-register", "Etiqueta (hashtag)", "Hashtag", "Hashtag", "Hashtag", "ハッシュタグ", "话题标签", "huàtí biāoqiān"),
    ("Op-ed", "📝", "media-register", "Artículo de opinión", "Tribune", "Articolo di opinione", "Artigo de opinião", "{寄稿|きこう}{論説|ろんせつ}", "评论文章", "pínglùn wénzhāng"),
    ("Byline", "✍️", "media-register", "Firma (del autor)", "Signature (article)", "Firma (articolo)", "Assinatura (artigo)", "{署名記事|しょめいきじ}", "署名栏", "shǔmínglán"),
    ("Segment (TV)", "🎬", "media-register", "Segmento", "Séquence", "Servizio (TV)", "Bloco", "コーナー", "节目片段", "jiémù piànduàn"),
    ("Airtime", "⏱️", "media-register", "Tiempo en antena", "Temps d’antenne", "Tempo in onda", "Tempo no ar", "{放送時間|ほうそうじかん}", "播出时间", "bōchū shíjiān"),

    # ---- academic register ----
    ("Methodology", "📐", "academic-register", "Metodología", "Méthodologie", "Metodologia", "Metodologia", "{方法論|ほうほうろん}", "方法论", "fāngfǎlùn"),
    ("Empirical", "🔬", "academic-register", "Empírico", "Empirique", "Empirico", "Empírico", "{経験的|けいけんてき}", "实证的", "shízhèng de"),
    ("Qualitative", "🗣️", "academic-register", "Cualitativo", "Qualitatif", "Qualitativo", "Qualitativo", "{質的|しつてき}", "定性的", "dìngxìng de"),
    ("Quantitative", "🔢", "academic-register", "Cuantitativo", "Quantitatif", "Quantitativo", "Quantitativo", "{量的|りょうてき}", "定量的", "dìngliàng de"),
    ("Variable", "🔀", "academic-register", "Variable", "Variable", "Variabile", "Variável", "{変数|へんすう}", "变量", "biànliàng"),
    ("Correlation", "📈", "academic-register", "Correlación", "Corrélation", "Correlazione", "Correlação", "{相関|そうかん}", "相关性", "xiāngguānxìng"),
    ("Causation", "➡️", "academic-register", "Causalidad", "Causalité", "Causalità", "Causalidade", "{因果関係|いんがかんけい}", "因果关系", "yīnguǒ guānxì"),
    ("Sample (study)", "🧪", "academic-register", "Muestra", "Échantillon", "Campione", "Amostra", "{標本|ひょうほん}", "样本", "yàngběn"),
    ("Peer review", "👥", "academic-register", "Revisión por pares", "Évaluation par les pairs", "Revisione paritaria", "Revisão por pares", "{査読|さどく}", "同行评审", "tóngháng píngshěn"),
    ("Citation", "📚", "academic-register", "Cita (referencia)", "Citation (référence)", "Citazione (riferimento)", "Citação (referência)", "{引用|いんよう}（{文献|ぶんけん}）", "引证", "yǐnzhèng"),
    ("Abstract (summary)", "📄", "academic-register", "Resumen (abstract)", "Résumé (abstract)", "Abstract", "Resumo (abstract)", "{要旨|ようし}", "摘要（论文）", "lùnwén zhāiyào"),
    ("Dissertation", "🎓", "academic-register", "Tesis doctoral", "Thèse de doctorat", "Tesi di dottorato", "Tese de doutorado", "{博士論文|はくしろんぶん}", "博士论文", "bóshì lùnwén"),
    ("Scholar", "👨‍🎓", "academic-register", "Académico", "Universitaire (chercheur)", "Studioso", "Acadêmico", "{学者|がくしゃ}", "学者", "xuézhě"),
    ("Discipline (field)", "📖", "academic-register", "Disciplina", "Discipline", "Disciplina", "Disciplina", "{学問分野|がくもんぶんや}", "学科", "xuékē"),
    ("Paradigm", "🧩", "academic-register", "Paradigma", "Paradigme", "Paradigma", "Paradigma", "パラダイム", "范式", "fànshì"),
    ("Phenomenon", "🌌", "academic-register", "Fenómeno", "Phénomène", "Fenomeno", "Fenômeno", "{現象|げんしょう}", "现象", "xiànxiàng"),
    ("Premise", "🧱", "academic-register", "Premisa", "Prémisse", "Premessa", "Premissa", "{前提|ぜんてい}", "前提", "qiántí"),
    ("Inference", "🔍", "academic-register", "Inferencia", "Inférence", "Inferenza", "Inferência", "{推論|すいろん}", "推论", "tuīlùn"),
    ("To infer", "🧠", "academic-register", "Inferir", "Inférer", "Inferire", "Inferir", "{推論|すいろん}する", "推断", "tuīduàn"),
    ("To deduce", "🕵️", "academic-register", "Deducir", "Déduire", "Dedurre", "Deduzir", "{演繹|えんえき}する", "演绎", "yǎnyì"),
    ("Rigorous", "📏", "academic-register", "Riguroso", "Rigoureux", "Rigoroso", "Rigoroso", "{厳密|げんみつ}な", "严谨的", "yánjǐn de"),
    ("Nuanced", "🎨", "academic-register", "Matizado", "Nuancé", "Sfumato", "Matizado", "{微妙|びみょう}な{違|ちが}いを{含|ふく}む", "细致入微的", "xìzhì rùwēi de"),
    ("To synthesize", "🔗", "academic-register", "Sintetizar", "Synthétiser", "Sintetizzare", "Sintetizar", "{統合|とうごう}する（{総合|そうごう}）", "综合", "zōnghé"),
    ("Critique", "🔎", "academic-register", "Crítica (análisis)", "Critique (analyse)", "Critica (analisi)", "Crítica (análise)", "{批評|ひひょう}", "评析", "píngxī"),
    ("Discourse", "🗣️", "academic-register", "Discurso", "Discours", "Discorso", "Discurso", "{言説|げんせつ}", "话语", "huàyǔ"),
    ("Hierarchy", "🏛️", "academic-register", "Jerarquía", "Hiérarchie", "Gerarchia", "Hierarquia", "{階層|かいそう}", "等级制度", "děngjí zhìdù"),
    ("Paradox", "🔄", "academic-register", "Paradoja", "Paradoxe", "Paradosso", "Paradoxo", "{逆説|ぎゃくせつ}", "悖论", "bèilùn"),
    ("Theoretical", "💭", "academic-register", "Teórico", "Théorique", "Teorico", "Teórico", "{理論的|りろんてき}", "理论的", "lǐlùn de"),
    ("Findings", "📊", "academic-register", "Hallazgos", "Résultats (conclusions)", "Risultati (ricerca)", "Descobertas", "{研究結果|けんきゅうけっか}", "研究结果", "yánjiū jiéguǒ"),
    ("Assumption", "🤔", "academic-register", "Suposición", "Hypothèse (présupposé)", "Presupposto", "Suposição", "{仮定|かてい}", "假定", "jiǎdìng"),

    # ---- phrasal verbs I ----
    ("To back up (support)", "🛡️", "phrasal-verbs-1", "Respaldar", "Soutenir (appuyer)", "Appoggiare", "Dar apoio", "{後押|あとお}しする", "支持（撑腰）", "chēngyāo"),
    ("To bring up (mention)", "💬", "phrasal-verbs-1", "Sacar (un tema)", "Aborder (un sujet)", "Tirare fuori (un argomento)", "Trazer à tona", "{話題|わだい}に{出|だ}す", "提起", "tíqǐ"),
    ("To call off", "❌", "phrasal-verbs-1", "Suspender (cancelar)", "Annuler", "Annullare", "Cancelar", "{中止|ちゅうし}する", "取消（叫停）", "jiàotíng"),
    ("To carry on", "➡️", "phrasal-verbs-1", "Seguir adelante", "Continuer", "Andare avanti", "Seguir em frente", "{続|つづ}ける", "继续（坚持）", "jìxù"),
    ("To check out (look at)", "👀", "phrasal-verbs-1", "Echar un vistazo", "Jeter un œil", "Dare un’occhiata (esaminare)", "Dar uma olhada (conferir)", "チェックする", "看看（了解）", "kànkan"),
    ("To come across", "🔍", "phrasal-verbs-1", "Toparse con", "Tomber sur", "Imbattersi in", "Deparar-se com", "{偶然|ぐうぜん}{見|み}つける", "偶然遇到", "ǒurán yùdào"),
    ("To cut down on", "✂️", "phrasal-verbs-1", "Reducir (el consumo)", "Réduire (sa consommation)", "Ridurre (il consumo)", "Reduzir (o consumo)", "{減|へ}らす（{控|ひか}える）", "减少（消费）", "jiǎnshǎo"),
    ("To do without", "🚫", "phrasal-verbs-1", "Prescindir de", "Se passer de", "Fare a meno di", "Passar sem", "〜なしで{済|す}ます", "没有……也行", "méiyǒu…yě xíng"),
    ("To fall apart", "💔", "phrasal-verbs-1", "Desmoronarse", "S’effondrer", "Andare in pezzi", "Desmoronar", "{崩|くず}れる", "崩溃（散架）", "sànjià"),
    ("To fall behind", "🐢", "phrasal-verbs-1", "Quedarse atrás", "Prendre du retard", "Rimanere indietro", "Ficar para trás", "{遅|おく}れをとる", "落后", "luòhòu"),
    ("To get away with", "😏", "phrasal-verbs-1", "Salirse con la suya", "S’en tirer", "Farla franca", "Escapar impune", "{罰|ばつ}を{逃|のが}れる", "逃脱惩罚", "táotuō chéngfá"),
    ("To get by", "🧮", "phrasal-verbs-1", "Arreglárselas (sobrevivir)", "S’en sortir", "Tirare avanti", "Se virar", "なんとかやっていく", "勉强过活", "miǎnqiǎng guòhuó"),
    ("To get over", "🌈", "phrasal-verbs-1", "Superar (recuperarse)", "Se remettre de", "Superare (riprendersi)", "Superar (recuperar-se)", "{立|た}ち{直|なお}る", "熬过去", "áo guòqù"),
    ("To give in", "🏳️", "phrasal-verbs-1", "Ceder", "Céder", "Cedere", "Ceder", "{折|お}れる", "让步", "ràngbù"),
    ("To go through (experience)", "🚪", "phrasal-verbs-1", "Pasar por", "Traverser (une épreuve)", "Passare (un momento)", "Passar por", "{経験|けいけん}する（つらいこと）", "经历（磨难）", "jīnglì"),
    ("To hold on", "✋", "phrasal-verbs-1", "Esperar (aguantar)", "Attendre (tenir bon)", "Aspettare (resistere)", "Aguentar (esperar)", "{待|ま}つ（{持|も}ちこたえる）", "等一下（坚持）", "děng yíxià"),
    ("To keep up with", "🏃", "phrasal-verbs-1", "Mantenerse al día", "Suivre (le rythme)", "Stare al passo", "Acompanhar (o ritmo)", "ついていく（{遅|おく}れない）", "跟上", "gēnshàng"),
    ("To let down", "😞", "phrasal-verbs-1", "Decepcionar", "Décevoir", "Deludere", "Decepcionar", "がっかりさせる（{裏切|うらぎ}る）", "让……失望", "ràng…shīwàng"),
    ("To look into", "🔎", "phrasal-verbs-1", "Investigar (examinar)", "Examiner", "Esaminare", "Investigar (examinar)", "{調|しら}べる", "调查（研究）", "diàochá"),
    ("To look up to", "🌟", "phrasal-verbs-1", "Admirar", "Admirer", "Ammirare", "Admirar", "{尊敬|そんけい}する", "敬仰", "jìngyǎng"),
    ("To make up for", "🎁", "phrasal-verbs-1", "Compensar", "Compenser", "Compensare", "Compensar", "{埋|う}め{合|あ}わせる", "弥补", "míbǔ"),
    ("To pass out", "😵", "phrasal-verbs-1", "Desmayarse (perder el conocimiento)", "S’évanouir (tomber dans les pommes)", "Svenire (perdere i sensi)", "Desmaiar (apagar)", "{気絶|きぜつ}する", "昏倒", "hūndǎo"),
    ("To point out", "👉", "phrasal-verbs-1", "Señalar (indicar)", "Faire remarquer", "Far notare", "Apontar (indicar)", "{指摘|してき}する", "指出", "zhǐchū"),
    ("To put up with", "😤", "phrasal-verbs-1", "Aguantar (tolerar)", "Supporter", "Sopportare", "Aguentar (tolerar)", "{我慢|がまん}する", "忍受", "rěnshòu"),
    ("To run into", "🤝", "phrasal-verbs-1", "Encontrarse con (por casualidad)", "Croiser (par hasard)", "Incontrare per caso", "Esbarrar com", "ばったり{会|あ}う", "偶遇", "ǒuyù"),
    ("To set up", "🏗️", "phrasal-verbs-1", "Montar (establecer)", "Mettre en place", "Allestire", "Montar (configurar)", "{設立|せつりつ}する", "建立（设置）", "shèzhì"),
    ("To sort out", "🧩", "phrasal-verbs-1", "Solucionar (arreglar)", "Régler", "Sistemare", "Resolver (organizar)", "{解決|かいけつ}する（{整理|せいり}）", "解决（理清）", "lǐqīng"),
    ("To stand for", "🏷️", "phrasal-verbs-1", "Significar (representar)", "Signifier (représenter)", "Stare per (significare)", "Significar (representar)", "〜を{意味|いみ}する（{略|りゃく}）", "代表（缩写）", "dàibiǎo"),
    ("To take after", "👨‍👦", "phrasal-verbs-1", "Parecerse a", "Tenir de", "Assomigliare a", "Puxar a", "〜に{似|に}る", "像（长辈）", "xiàng"),
    ("To take over", "👑", "phrasal-verbs-1", "Hacerse cargo (asumir)", "Reprendre (prendre le contrôle)", "Subentrare", "Assumir (o controle)", "{引|ひ}き{継|つ}ぐ", "接管", "jiēguǎn"),

    # ---- phrasal verbs II ----
    ("To turn down", "🙅", "phrasal-verbs-2", "Rechazar (una oferta)", "Refuser (une offre)", "Rifiutare (un’offerta)", "Recusar (uma oferta)", "{断|ことわ}る（{申|もう}し{出|で}を）", "拒绝（提议）", "jùjué"),
    ("To turn up", "🚪", "phrasal-verbs-2", "Aparecer (presentarse)", "Se pointer", "Presentarsi", "Aparecer (dar as caras)", "{現|あらわ}れる（{来|く}る）", "露面", "lòumiàn"),
    ("To work out (resolve)", "✅", "phrasal-verbs-2", "Resolverse (salir bien)", "Se régler", "Risolversi", "Dar certo", "うまくいく", "解决（成功）", "chénggōng"),
    ("To wear off", "⏳", "phrasal-verbs-2", "Pasarse (desaparecer)", "Se dissiper", "Svanire", "Passar (efeito)", "{効|き}き{目|め}が{切|き}れる", "消退", "xiāotuì"),
    ("To wind up (end up)", "🏁", "phrasal-verbs-2", "Acabar (terminar en)", "Se retrouver", "Ritrovarsi", "Acabar (terminar em)", "{結局|けっきょく}〜になる", "最后落得", "zuìhòu luòdé"),
    ("To break off", "✂️", "phrasal-verbs-2", "Romper (relaciones)", "Rompre (relations)", "Interrompere (rapporti)", "Romper (relações)", "{断絶|だんぜつ}する", "断绝", "duànjué"),
    ("To brush up on", "📚", "phrasal-verbs-2", "Repasar (refrescar)", "Réviser (rafraîchir)", "Rinfrescare", "Relembrar (revisar)", "{復習|ふくしゅう}する（{磨|みが}き{直|なお}す）", "温习", "wēnxí"),
    ("To catch on", "💡", "phrasal-verbs-2", "Ponerse de moda", "Prendre (devenir populaire)", "Prendere piede", "Pegar (virar moda)", "{流行|はや}る", "流行起来", "liúxíng qǐlái"),
    ("To come down with", "🤒", "phrasal-verbs-2", "Caer enfermo", "Attraper (une maladie)", "Beccarsi (una malattia)", "Pegar (uma doença)", "{病気|びょうき}にかかる", "染上（病）", "rǎnshàng"),
    ("To crack down on", "👮", "phrasal-verbs-2", "Tomar medidas contra", "Sévir contre", "Reprimere", "Reprimir", "{取|と}り{締|し}まる", "严厉打击", "yánlì dǎjī"),
    ("To dwell on", "🌀", "phrasal-verbs-2", "Darle vueltas a", "Ressasser", "Rimuginare", "Remoer", "くよくよ{考|かんが}える", "纠结于", "jiūjié yú"),
    ("To fall through", "💨", "phrasal-verbs-2", "Fracasar (un plan)", "Tomber à l’eau", "Andare a monte", "Não dar em nada", "{頓挫|とんざ}する", "落空", "luòkōng"),
    ("To get across", "📨", "phrasal-verbs-2", "Hacerse entender", "Faire passer (une idée)", "Far capire", "Fazer-se entender", "{伝|つた}わる", "传达清楚", "chuándá qīngchu"),
    ("To hold back", "✋", "phrasal-verbs-2", "Contenerse", "Se retenir", "Trattenersi", "Se conter", "{抑|おさ}える", "克制", "kèzhì"),
    ("To iron out", "🔧", "phrasal-verbs-2", "Limar (asperezas)", "Aplanir", "Appianare", "Aparar (arestas)", "{解消|かいしょう}する", "解决（分歧）", "jiějué (fēnqí)"),
    ("To live up to", "🎯", "phrasal-verbs-2", "Estar a la altura de", "Être à la hauteur de", "Essere all’altezza di", "Corresponder a", "{期待|きたい}に{応|こた}える", "不辜负", "bù gūfù"),
    ("To narrow down", "🔽", "phrasal-verbs-2", "Reducir (opciones)", "Restreindre (le choix)", "Restringere (le opzioni)", "Restringir (opções)", "{絞|しぼ}り{込|こ}む", "缩小范围", "suōxiǎo fànwéi"),
    ("To opt out", "🚪", "phrasal-verbs-2", "Darse de baja (optar por no)", "Se désengager", "Chiamarsi fuori", "Optar por sair", "{離脱|りだつ}する", "选择退出", "xuǎnzé tuìchū"),
    ("To phase out", "📉", "phrasal-verbs-2", "Eliminar gradualmente", "Supprimer progressivement", "Eliminare gradualmente", "Eliminar gradualmente", "{段階的|だんかいてき}に{廃止|はいし}する", "逐步淘汰", "zhúbù táotài"),
    ("To pull off", "🎩", "phrasal-verbs-2", "Lograr (con dificultad)", "Réussir (un coup)", "Riuscire (in un’impresa)", "Conseguir (uma façanha)", "やってのける", "成功做到", "chénggōng zuòdào"),
    ("To rule out", "❌", "phrasal-verbs-2", "Descartar", "Exclure", "Escludere (una possibilità)", "Descartar (excluir)", "{除外|じょがい}する（{可能性|かのうせい}）", "排除（可能性）", "páichú"),
    ("To settle for", "🤷", "phrasal-verbs-2", "Conformarse con", "Se contenter de", "Accontentarsi di", "Se contentar com", "〜で{妥協|だきょう}する", "将就", "jiāngjiu"),
    ("To stick to", "📌", "phrasal-verbs-2", "Ceñirse a", "S’en tenir à", "Attenersi a", "Ater-se a", "〜を{守|まも}る（{固守|こしゅ}）", "坚持（遵守）", "jiānchí"),
    ("To take on (a task)", "🏋️", "phrasal-verbs-2", "Asumir (una tarea)", "Se charger de", "Assumersi", "Assumir (uma tarefa)", "{引|ひ}き{受|う}ける（{仕事|しごと}）", "承担（任务）", "chéngdān"),
    ("To touch on", "👆", "phrasal-verbs-2", "Tocar (un tema)", "Effleurer (un sujet)", "Toccare (un argomento)", "Tocar (num assunto)", "{触|ふ}れる（{話題|わだい}に）", "涉及（提到）", "shèjí"),
    ("To weigh up", "⚖️", "phrasal-verbs-2", "Sopesar", "Peser (le pour et le contre)", "Soppesare", "Pesar (prós e contras)", "{比較検討|ひかくけんとう}する", "权衡", "quánhéng"),
    ("To wrap up", "🎁", "phrasal-verbs-2", "Concluir (terminar)", "Boucler", "Concludere (finire)", "Encerrar", "{締|し}めくくる", "收尾", "shōuwěi"),
    ("To zero in on", "🎯", "phrasal-verbs-2", "Centrarse en", "Se concentrer sur", "Concentrarsi su", "Focar em", "{的|まと}を{絞|しぼ}る", "聚焦于", "jùjiāo yú"),
    ("To fend off", "🛡️", "phrasal-verbs-2", "Repeler", "Repousser", "Respingere", "Repelir", "{追|お}い{払|はら}う", "抵挡", "dǐdǎng"),
    ("To stem from", "🌱", "phrasal-verbs-2", "Provenir de", "Découler de", "Derivare da", "Decorrer de", "〜に{由来|ゆらい}する", "源于", "yuányú"),

    # ---- colloquial speech ----
    ("Awesome", "🤩", "colloquial", "Genial", "Génial", "Fantastico", "Incrível", "{最高|さいこう}", "太棒了", "tài bàng le"),
    ("Gross", "🤢", "colloquial", "Asqueroso (qué asco)", "Dégueu", "Schifoso", "Nojento (eca)", "キモい", "恶心（好恶心）", "hǎo ěxin"),
    ("Lame", "🙄", "colloquial", "Cutre", "Nul", "Scarso", "Sem graça", "ダサい", "逊", "xùn"),
    ("Cheesy", "🧀", "colloquial", "Cursi", "Kitsch", "Sdolcinato", "Brega", "{安|やす}っぽい", "俗气", "súqì"),
    ("To chill", "🛋️", "colloquial", "Relajarse (chill)", "Se poser", "Rilassarsi", "Relaxar (de boa)", "まったりする", "放松（休闲）", "fàngsōng"),
    ("Dude", "🧢", "colloquial", "Tío", "Mec", "Amico (bello)", "Cara", "おい（{兄|あに}ちゃん）", "哥们儿", "gēmenr"),
    ("To ditch", "🚮", "colloquial", "Plantar (abandonar)", "Laisser tomber", "Piantare in asso", "Dar o bolo", "{見捨|みす}てる（ドタキャン）", "抛下（甩掉）", "shuǎidiào"),
    ("To bail (leave)", "🏃", "colloquial", "Rajarse (irse)", "Se barrer", "Tagliare la corda", "Vazar", "{抜|ぬ}ける", "溜走", "liūzǒu"),
    ("To crash (sleep)", "😴", "colloquial", "Quedarse a dormir", "Pioncer", "Crollare (a dormire)", "Apagar (dormir)", "{泊|と}まらせてもらう", "借宿", "jièsù"),
    ("To freak out", "😱", "colloquial", "Flipar (asustarse)", "Flipper", "Andare fuori di testa", "Surtar", "パニクる", "抓狂", "zhuākuáng"),
    ("To nail it", "🎯", "colloquial", "Clavarlo", "Assurer", "Spaccare", "Mandar bem", "バッチリ{決|き}める", "搞定", "gǎodìng"),
    ("To screw up", "🙈", "colloquial", "Cagarla", "Foirer", "Fare un casino", "Fazer besteira", "しくじる", "搞砸", "gǎozá"),
    ("A bummer", "😞", "colloquial", "Un bajón", "La poisse", "Una seccatura", "Um saco", "がっかり", "真扫兴", "zhēn sǎoxìng"),
    ("No biggie", "🤷", "colloquial", "No pasa nada", "Pas grave", "Nessun problema", "De boa", "{大|たい}したことない", "小事一桩", "xiǎoshì yì zhuāng"),
    ("To be into", "💖", "colloquial", "Estar metido en", "Être à fond dans", "Essere preso da", "Curtir", "ハマっている", "迷上", "míshàng"),
    ("Hooked", "🎣", "colloquial", "Enganchado", "Accro", "Dipendente (preso)", "Viciado", "ハマった", "上瘾了", "shàngyǐn le"),
    ("Hype", "📣", "colloquial", "Bombo", "Battage", "Hype", "Hype", "{話題沸騰|わだいふっとう}", "炒作", "chǎozuò"),
    ("Sketchy", "🕶️", "colloquial", "Turbio", "Louche", "Losco", "Suspeito", "{怪|あや}しい", "可疑", "kěyí"),
    ("Legit", "✅", "colloquial", "De verdad (auténtico)", "Réglo", "Serio (autentico)", "De verdade", "ガチ", "靠谱", "kàopǔ"),
    ("A rip-off", "💸", "colloquial", "Un robo", "Une arnaque", "Una fregatura", "Um roubo", "ぼったくり", "宰人", "zǎirén"),
    ("To ghost", "👻", "colloquial", "Hacer ghosting", "Ghoster", "Sparire (ghostare)", "Dar ghosting", "{音信不通|おんしんふつう}にする", "玩消失", "wán xiāoshī"),
    ("Cringe", "😬", "colloquial", "Vergüenza ajena", "Gênant (cringe)", "Imbarazzante (cringe)", "Vergonha alheia", "{痛|いた}い", "尴尬到脚趾抓地", "gāngà"),
    ("To wing it", "🪽", "colloquial", "Improvisar", "Improviser", "Improvvisare", "Improvisar", "アドリブでやる", "临场发挥", "línchǎng fāhuī"),
    ("To zone out", "😶‍🌫️", "colloquial", "Quedarse en blanco", "Décrocher", "Distrarsi", "Viajar (distrair-se)", "ぼーっとする", "走神", "zǒushén"),
    ("To kick back", "🛋️", "colloquial", "Relajarse (a tope)", "Se détendre", "Rilassarsi (mettersi comodo)", "Relaxar (descansar)", "くつろぐ", "放松（躺平）", "tǎngpíng"),
    ("For real", "💯", "colloquial", "En serio", "Sérieux", "Sul serio", "Sério mesmo", "マジで", "真的", "zhēn de"),
    ("Buddy", "🤝", "colloquial", "Colega", "Pote", "Amico (compare)", "Parceiro", "{相棒|あいぼう}", "伙计", "huǒji"),
    ("To hit the road", "🚗", "colloquial", "Ponerse en marcha", "Prendre la route", "Mettersi in strada", "Pegar a estrada", "{出発|しゅっぱつ}する", "上路", "shànglù"),
    ("To grab (get)", "🤏", "colloquial", "Pillar", "Choper", "Prendere (al volo)", "Pegar", "{取|と}ってくる", "拿一下", "ná yíxià"),
    ("Sweet (great)", "🍬", "colloquial", "Qué guay", "Cool", "Forte", "Massa", "いいね", "赞", "zàn"),
]
