# -*- coding: utf-8 -*-
# C2 vocabulary batch 8 — tech register, money & markets, transport register, numbers & maths, appearance & clothing
TIER = 'C2'
TOPICS = {
    'tech-rare': 'Tech & Digital Register', 'money-rare': 'Money & Markets Register',
    'transport-rare': 'Transport & Logistics', 'numbers-math-rare': 'Numbers, Maths & Data',
    'clothing-appearance-rare': 'Appearance & Tailoring',
}
WORDS = [
    # ---- tech & digital register ----
    ("Bandwidth", "📶", "tech-rare", "Ancho de banda", "Bande passante", "Larghezza di banda", "Largura de banda", "{帯域幅|たいいきはば}", "带宽", "dàikuān"),
    ("Jitter", "📶", "tech-rare", "Fluctuación (jitter)", "Gigue (jitter)", "Jitter (instabilità)", "Jitter (variação de latência)", "ジッター", "抖动", "dǒudòng"),
    ("Throughput", "🚰", "tech-rare", "Rendimiento (caudal)", "Débit", "Portata (throughput)", "Vazão (taxa de transferência)", "スループット（{処理能力|しょりのうりょく}）", "吞吐量", "tūntǔliàng"),
    ("Hashing", "#️⃣", "tech-rare", "Hash (función resumen)", "Hachage", "Hashing", "Hashing", "ハッシュ{化|か}", "哈希", "hāxī"),
    ("Intrusion detection", "🚨", "tech-rare", "Detección de intrusiones", "Détection d’intrusion", "Rilevamento delle intrusioni", "Detecção de intrusão", "{侵入検知|しんにゅうけんち}", "入侵检测", "rùqīn jiǎncè"),
    ("Vulnerability (security)", "🕳️", "tech-rare", "Vulnerabilidad", "Faille (vulnérabilité)", "Vulnerabilità", "Vulnerabilidade", "{脆弱性|ぜいじゃくせい}", "漏洞", "lòudòng"),
    ("Hotfix", "🩹", "tech-rare", "Corrección urgente (hotfix)", "Correctif urgent", "Correzione urgente (hotfix)", "Correção urgente (hotfix)", "ホットフィックス", "热修复", "rèxiūfù"),
    ("Backlog", "📚", "tech-rare", "Trabajo pendiente (acumulado)", "Arriéré (backlog)", "Arretrato (backlog)", "Pendências acumuladas (backlog)", "{未処理|みしょり}の{案件|あんけん}", "积压工作", "jīyā gōngzuò"),
    ("Rollout", "🚀", "tech-rare", "Despliegue (lanzamiento)", "Déploiement", "Lancio (distribuzione)", "Lançamento (implantação)", "{展開|てんかい}（{段階的|だんかいてき}リリース）", "推出（部署）", "tuīchū"),
    ("Rollback", "⏪", "tech-rare", "Reversión", "Retour arrière", "Ripristino (rollback)", "Reversão", "ロールバック（{巻|ま}き{戻|もど}し）", "回滚", "huígǔn"),
    ("Uptime", "✅", "tech-rare", "Tiempo de actividad", "Temps de fonctionnement (disponibilité)", "Tempo di attività", "Tempo de atividade", "{稼働時間|かどうじかん}", "正常运行时间", "zhèngcháng yùnxíng shíjiān"),
    ("Redundancy (backup)", "♻️", "tech-rare", "Redundancia", "Redondance", "Ridondanza", "Redundância", "{冗長性|じょうちょうせい}", "冗余", "rǒngyú"),
    ("Load balancing", "⚖️", "tech-rare", "Balanceo de carga", "Répartition de charge", "Bilanciamento del carico", "Balanceamento de carga", "{負荷分散|ふかぶんさん}", "负载均衡", "fùzài jūnhéng"),
    ("Legacy system", "🦕", "tech-rare", "Sistema heredado", "Système hérité (existant)", "Sistema legacy (ereditato)", "Sistema legado", "レガシーシステム", "遗留系统", "yíliú xìtǒng"),
    ("Copyleft", "🄯", "tech-rare", "Copyleft", "Copyleft (gauche d’auteur)", "Copyleft", "Copyleft", "コピーレフト", "著佐权", "zhùzuǒquán"),
    ("Proprietary", "🔒", "tech-rare", "Propietario (privativo)", "Propriétaire", "Proprietario", "Proprietário", "{独自|どくじ}の（{専有|せんゆう}の）", "专有的", "zhuānyǒu de"),
    ("Interoperability", "🔗", "tech-rare", "Interoperabilidad", "Interopérabilité", "Interoperabilità", "Interoperabilidade", "{相互運用性|そうごうんようせい}", "互操作性", "hù cāozuò xìng"),
    ("Passkey", "🔑", "tech-rare", "Llave de acceso", "Clé d’accès (passkey)", "Passkey", "Chave de acesso (passkey)", "パスキー", "通行密钥", "tōngxíng mìyào"),
    ("Social engineering", "🎭", "tech-rare", "Ingeniería social", "Ingénierie sociale", "Ingegneria sociale", "Engenharia social", "ソーシャルエンジニアリング", "社会工程学", "shèhuì gōngchéngxué"),
    ("Data breach", "💥", "tech-rare", "Filtración de datos", "Fuite de données", "Violazione dei dati", "Vazamento de dados", "{情報漏洩|じょうほうろうえい}", "数据泄露", "shùjù xièlòu"),
    ("Cache", "🗂️", "tech-rare", "Caché", "Cache (mémoire cache)", "Cache", "Cache", "キャッシュ", "缓存", "huǎncún"),
    ("Query", "❓", "tech-rare", "Consulta", "Requête", "Query (interrogazione)", "Consulta", "クエリ（{問|と}い{合|あ}わせ）", "查询", "cháxún"),
    ("Metadata", "🏷️", "tech-rare", "Metadatos", "Métadonnées", "Metadati", "Metadados", "メタデータ", "元数据", "yuánshùjù"),
    ("Placeholder", "⬜", "tech-rare", "Marcador de posición", "Espace réservé (texte provisoire)", "Segnaposto", "Espaço reservado (placeholder)", "プレースホルダー（{仮|かり}の{値|あたい}）", "占位符", "zhànwèifú"),
    ("Workaround", "🔧", "tech-rare", "Solución provisional (apaño)", "Solution de contournement", "Soluzione alternativa (espediente)", "Solução alternativa (gambiarra)", "{回避策|かいひさく}", "变通方法", "biàntōng fāngfǎ"),
    ("Bottleneck", "🍾", "tech-rare", "Cuello de botella", "Goulot d’étranglement", "Collo di bottiglia", "Gargalo", "ボトルネック（{隘路|あいろ}）", "瓶颈", "píngjǐng"),
    ("Edge case", "🧩", "tech-rare", "Caso límite", "Cas limite", "Caso limite", "Caso extremo (caso de borda)", "{極端|きょくたん}なケース", "边缘情况", "biānyuán qíngkuàng"),
    ("Deprecated", "🚫", "tech-rare", "Obsoleto (en desuso)", "Obsolète (déconseillé)", "Deprecato (obsoleto)", "Obsoleto (descontinuado)", "{非推奨|ひすいしょう}の", "已弃用的", "yǐ qìyòng de"),
    ("Sandbox", "🏖️", "tech-rare", "Entorno de pruebas (sandbox)", "Bac à sable", "Ambiente di prova (sandbox)", "Ambiente de testes (sandbox)", "サンドボックス", "沙盒", "shāhé"),
    ("Telemetry", "📡", "tech-rare", "Telemetría", "Télémétrie", "Telemetria", "Telemetria", "テレメトリ（{遠隔計測|えんかくけいそく}）", "遥测", "yáocè"),
    ("Algorithmic bias", "⚖️", "tech-rare", "Sesgo algorítmico", "Biais algorithmique", "Pregiudizio algoritmico", "Viés algorítmico", "アルゴリズムの{偏|かたよ}り", "算法偏见", "suànfǎ piānjiàn"),
    ("Overfitting", "📈", "tech-rare", "Sobreajuste", "Surapprentissage", "Overfitting (sovradattamento)", "Sobreajuste", "{過学習|かがくしゅう}", "过拟合", "guò nǐhé"),
    ("Large language model", "🗨️", "tech-rare", "Modelo de lenguaje grande", "Grand modèle de langage", "Modello linguistico di grandi dimensioni", "Modelo de linguagem grande", "{大規模言語|だいきぼげんご}モデル", "大语言模型", "dà yǔyán móxíng"),
    ("Quantum computing", "⚛️", "tech-rare", "Computación cuántica", "Informatique quantique", "Calcolo quantistico", "Computação quântica", "{量子|りょうし}コンピューティング", "量子计算", "liàngzǐ jìsuàn"),
    ("Semiconductor", "💾", "tech-rare", "Semiconductor", "Semi-conducteur", "Semiconduttore", "Semicondutor", "{半導体|はんどうたい}", "半导体", "bàndǎotǐ"),
    # ---- money & markets register ----
    ("Working capital", "🔄", "money-rare", "Capital circulante", "Fonds de roulement", "Capitale circolante", "Capital de giro", "{運転資金|うんてんしきん}", "营运资金", "yíngyùn zījīn"),
    ("Solvency", "🏦", "money-rare", "Solvencia", "Solvabilité", "Solvibilità", "Solvência", "{支払能力|しはらいのうりょく}", "偿付能力", "chángfù nénglì"),
    ("Insolvency", "📉", "money-rare", "Insolvencia", "Insolvabilité", "Insolvenza", "Insolvência", "{支払不能|しはらいふのう}", "无力偿债", "wúlì chángzhài"),
    ("Receivership", "🏚️", "money-rare", "Administración judicial", "Redressement judiciaire (mise sous séquestre)", "Amministrazione controllata", "Administração judicial (recuperação)", "{管財人|かんざいにん}による{管理|かんり}", "破产管理", "pòchǎn guǎnlǐ"),
    ("Leverage (finance)", "🎚️", "money-rare", "Apalancamiento", "Effet de levier", "Leva finanziaria", "Alavancagem", "レバレッジ（てこの{原理|げんり}）", "杠杆", "gànggǎn"),
    ("Hedge (finance)", "🛡️", "money-rare", "Cobertura", "Couverture", "Copertura", "Proteção (hedge)", "ヘッジ（{損失回避|そんしつかいひ}）", "对冲", "duìchōng"),
    ("Yield (finance)", "🌾", "money-rare", "Rendimiento", "Rendement", "Rendimento", "Rendimento", "{利回|りまわ}り", "收益率", "shōuyìlǜ"),
    ("Share buyback", "🔁", "money-rare", "Recompra de acciones", "Rachat d’actions", "Riacquisto di azioni", "Recompra de ações", "{自社株買|じしゃかぶが}い", "股票回购", "gǔpiào huígòu"),
    ("Equity (ownership)", "📊", "money-rare", "Capital (patrimonio neto)", "Capitaux propres (fonds propres)", "Capitale proprio (patrimonio netto)", "Patrimônio líquido (participação)", "{自己資本|じこしほん}（{株式|かぶしき}）", "股权（净资产）", "gǔquán"),
    ("Treasury bill", "🏛️", "money-rare", "Letra del Tesoro", "Bon du Trésor", "Buono del Tesoro", "Letra do Tesouro", "{短期国債|たんきこくさい}", "国库券", "guókùquàn"),
    ("Asset allocation", "🥧", "money-rare", "Asignación de activos", "Allocation d’actifs", "Allocazione degli attivi", "Alocação de ativos", "{資産配分|しさんはいぶん}", "资产配置", "zīchǎn pèizhì"),
    ("Volatility", "🎢", "money-rare", "Volatilidad", "Volatilité", "Volatilità", "Volatilidade", "ボラティリティ（{変動性|へんどうせい}）", "波动性", "bōdòngxìng"),
    ("Bull market", "🐂", "money-rare", "Mercado alcista", "Marché haussier", "Mercato rialzista", "Mercado em alta", "{強気相場|つよきそうば}", "牛市", "niúshì"),
    ("Bear market", "🐻", "money-rare", "Mercado bajista", "Marché baissier", "Mercato ribassista", "Mercado em baixa", "{弱気相場|よわきそうば}", "熊市", "xióngshì"),
    ("Downturn", "📉", "money-rare", "Desaceleración (recesión)", "Ralentissement (repli)", "Flessione (recessione)", "Desaceleração (retração)", "{景気|けいき}の{下降|かこう}", "经济低迷", "jīngjì dīmí"),
    ("Stagflation", "🥶", "money-rare", "Estanflación", "Stagflation", "Stagflazione", "Estagflação", "スタグフレーション", "滞胀", "zhìzhàng"),
    ("Deflation", "🧊", "money-rare", "Deflación", "Déflation", "Deflazione", "Deflação", "デフレ", "通货紧缩", "tōnghuò jǐnsuō"),
    ("Interest rate hike", "⬆️", "money-rare", "Subida de tipos de interés", "Hausse des taux d’intérêt", "Rialzo dei tassi", "Alta dos juros", "{利上|りあ}げ", "加息", "jiāxī"),
    ("Fiscal policy", "🏛️", "money-rare", "Política fiscal", "Politique budgétaire", "Politica fiscale", "Política fiscal", "{財政政策|ざいせいせいさく}", "财政政策", "cáizhèng zhèngcè"),
    ("Monetary policy", "🏦", "money-rare", "Política monetaria", "Politique monétaire", "Politica monetaria", "Política monetária", "{金融政策|きんゆうせいさく}", "货币政策", "huòbì zhèngcè"),
    ("Subsidy", "🎁", "money-rare", "Subvención", "Subvention", "Sovvenzione", "Subsídio", "{補助金|ほじょきん}", "补贴", "bǔtiē"),
    ("Trade quota", "📦", "money-rare", "Cuota (contingente) comercial", "Quota (contingent) commercial", "Quota (contingente) commerciale", "Cota de importação", "{輸入割当|ゆにゅうわりあて}", "贸易配额", "màoyì pèi'é"),
    ("Embargo", "🚫", "money-rare", "Embargo", "Embargo", "Embargo", "Embargo", "{禁輸|きんゆ}", "禁运", "jìnyùn"),
    ("Belt-tightening", "👖", "money-rare", "Apretarse el cinturón", "Serrage de ceinture", "Stretta di cinghia", "Aperto de cinto", "{緊縮|きんしゅく}（{財布|さいふ}の{紐|ひも}を{締|し}める）", "勒紧裤腰带", "lēijǐn kùyāodài"),
    ("Bailout", "🛟", "money-rare", "Rescate (financiero)", "Renflouement (sauvetage)", "Salvataggio", "Resgate (financeiro)", "{救済|きゅうさい}（{金融支援|きんゆうしえん}）", "救助（纾困）", "shūkùn"),
    ("Windfall", "🍃", "money-rare", "Ganancia inesperada", "Aubaine (manne)", "Guadagno inaspettato", "Ganho inesperado", "{棚|たな}ぼた", "意外之财", "yìwài zhī cái"),
    ("Nest egg", "🥚", "money-rare", "Ahorros (colchón)", "Bas de laine (pécule)", "Gruzzolo", "Pé-de-meia", "{蓄|たくわ}え（へそくり）", "储备金（积蓄）", "chǔbèijīn"),
    ("Slush fund", "🕶️", "money-rare", "Fondo de reptiles (caja B)", "Caisse noire", "Fondo nero", "Caixa dois", "{裏金|うらがね}", "小金库（秘密资金）", "xiǎo jīnkù"),
    ("Kickback", "🤫", "money-rare", "Comisión ilegal (mordida)", "Pot-de-vin (dessous-de-table)", "Tangente (bustarella)", "Propina (suborno)", "リベート（{賄賂|わいろ}）", "回扣", "huíkòu"),
    ("Money laundering", "🧺", "money-rare", "Blanqueo de capitales", "Blanchiment d’argent", "Riciclaggio di denaro", "Lavagem de dinheiro", "マネーロンダリング（{資金洗浄|しきんせんじょう}）", "洗钱", "xǐqián"),
    ("Tax evasion", "🏃", "money-rare", "Evasión fiscal", "Fraude fiscale", "Evasione fiscale", "Sonegação de impostos", "{脱税|だつぜい}", "逃税", "táoshuì"),
    ("Tax loophole", "🕳️", "money-rare", "Laguna fiscal", "Niche fiscale (faille)", "Scappatoia fiscale", "Brecha fiscal", "{税|ぜい}の{抜|ぬ}け{穴|あな}", "税收漏洞", "shuìshōu lòudòng"),
    ("Underwriter", "✍️", "money-rare", "Asegurador (suscriptor)", "Assureur (souscripteur)", "Sottoscrittore (assicuratore)", "Subscritor (segurador)", "{引受人|ひきうけにん}", "承保人（承销商）", "chéngbǎorén"),
    ("Sinking fund", "🏦", "money-rare", "Fondo de amortización", "Fonds d’amortissement", "Fondo di ammortamento", "Fundo de amortização", "{減債基金|げんさいききん}", "偿债基金", "chángzhài jījīn"),
    ("Arbitrage", "🔀", "money-rare", "Arbitraje (financiero)", "Arbitrage", "Arbitraggio", "Arbitragem", "{裁定取引|さいていとりひき}", "套利", "tàolì"),
    # ---- transport & logistics ----
    ("Freight", "🚛", "transport-rare", "Flete (carga)", "Fret", "Merci (carico)", "Frete (carga)", "{貨物|かもつ}", "货运", "huòyùn"),
    ("Cargo hold", "🚢", "transport-rare", "Bodega de carga", "Soute (cale)", "Stiva", "Porão de carga", "{貨物室|かもつしつ}", "货舱", "huòcāng"),
    ("Consignment", "📦", "transport-rare", "Envío (remesa)", "Envoi (expédition)", "Partita (spedizione)", "Remessa (consignação)", "{委託|いたく}（{積|つ}み{荷|に}）", "托运货物", "tuōyùn huòwù"),
    ("Customs clearance", "🛃", "transport-rare", "Despacho de aduanas", "Dédouanement", "Sdoganamento", "Desembaraço aduaneiro", "{通関|つうかん}", "清关", "qīngguān"),
    ("Red-eye flight", "😴", "transport-rare", "Vuelo nocturno", "Vol de nuit", "Volo notturno", "Voo noturno (madrugada)", "{深夜便|しんやびん}", "红眼航班", "hóngyǎn hángbān"),
    ("Turbulence", "🌪️", "transport-rare", "Turbulencia", "Turbulences", "Turbolenza", "Turbulência", "{乱気流|らんきりゅう}", "湍流（颠簸）", "diānbǒ"),
    ("Taxiing", "✈️", "transport-rare", "Rodaje (en pista)", "Roulage", "Rullaggio", "Taxiamento", "{地上走行|ちじょうそうこう}", "滑行", "huáxíng"),
    ("Cockpit", "🧑‍✈️", "transport-rare", "Cabina de mando", "Cockpit (poste de pilotage)", "Cabina di pilotaggio", "Cabine (cockpit)", "{操縦席|そうじゅうせき}", "驾驶舱", "jiàshǐcāng"),
    ("Overhead compartment", "🧳", "transport-rare", "Compartimento superior", "Compartiment à bagages (coffre)", "Cappelliera", "Compartimento superior", "{頭上|ずじょう}の{荷物入|にもつい}れ", "行李架", "xínglijià"),
    ("Aisle seat", "💺", "transport-rare", "Asiento de pasillo", "Siège côté couloir", "Posto corridoio", "Assento no corredor", "{通路側|つうろがわ}の{席|せき}", "靠过道座位", "kào guòdào zuòwèi"),
    ("Boarding pass", "🎫", "transport-rare", "Tarjeta de embarque", "Carte d’embarquement", "Carta d’imbarco", "Cartão de embarque", "{搭乗券|とうじょうけん}", "登机牌", "dēngjīpái"),
    ("Baggage carousel", "🔄", "transport-rare", "Cinta de equipajes", "Tapis à bagages", "Nastro bagagli", "Esteira de bagagem", "{手荷物|てにもつ}ターンテーブル", "行李转盘", "xíngli zhuànpán"),
    ("Jet bridge", "🌉", "transport-rare", "Pasarela (finger)", "Passerelle", "Finger (pontile d’imbarco)", "Ponte de embarque (finger)", "{搭乗橋|とうじょうきょう}", "登机桥", "dēngjīqiáo"),
    ("Tailgating (driving)", "🚗", "transport-rare", "Conducir pegado (al de delante)", "Coller au pare-chocs", "Stare attaccati (all’auto davanti)", "Colar no carro da frente", "{車間距離|しゃかんきょり}を{詰|つ}めること", "跟车过近", "gēnchē guò jìn"),
    ("Gridlock", "🚦", "transport-rare", "Atasco total (colapso)", "Embouteillage total (paralysie)", "Ingorgo totale", "Engarrafamento total", "{交通麻痺|こうつうまひ}", "交通大堵塞", "jiāotōng dà dǔsè"),
    ("Diversion (route)", "↪️", "transport-rare", "Desvío (de tráfico)", "Déviation (de circulation)", "Deviazione (del traffico)", "Desvio (de tráfego)", "{迂回|うかい}", "改道", "gǎidào"),
    ("Interchange (highway)", "🛣️", "transport-rare", "Nudo (enlace de autopista)", "Échangeur", "Svincolo", "Trevo (rodoviário)", "インターチェンジ", "立交枢纽", "lìjiāo shūniǔ"),
    ("Overpass", "🌉", "transport-rare", "Paso elevado", "Viaduc (passage supérieur)", "Cavalcavia", "Viaduto", "{高架橋|こうかきょう}", "立交桥（高架）", "lìjiāoqiáo"),
    ("Underpass", "🚇", "transport-rare", "Paso subterráneo", "Passage souterrain", "Sottopassaggio", "Passagem subterrânea", "{地下道|ちかどう}", "地下通道", "dìxià tōngdào"),
    ("Toll booth", "💰", "transport-rare", "Peaje (cabina)", "Poste de péage", "Casello", "Pedágio (cabine)", "{料金所|りょうきんじょ}", "收费站", "shōufèizhàn"),
    ("Hard shoulder", "🛣️", "transport-rare", "Arcén", "Bande d’arrêt d’urgence", "Corsia d’emergenza", "Acostamento", "{路肩|ろかた}", "紧急停车带", "jǐnjí tíngchēdài"),
    ("Speed bump", "🐢", "transport-rare", "Badén (lomo)", "Ralentisseur (dos-d’âne)", "Dosso", "Lombada (quebra-molas)", "{減速帯|げんそくたい}", "减速带", "jiǎnsùdài"),
    ("Blind spot", "👁️", "transport-rare", "Punto ciego (ángulo muerto)", "Angle mort", "Angolo cieco", "Ponto cego", "{死角|しかく}", "盲区", "mángqū"),
    ("Hazard lights", "⚠️", "transport-rare", "Luces de emergencia", "Feux de détresse (warnings)", "Quattro frecce", "Pisca-alerta", "ハザードランプ", "双闪灯", "shuāngshǎndēng"),
    ("Windshield wiper", "🌧️", "transport-rare", "Limpiaparabrisas", "Essuie-glace", "Tergicristallo", "Limpador de para-brisa", "ワイパー", "雨刷", "yǔshuā"),
    ("Clutch (car)", "🦶", "transport-rare", "Embrague", "Embrayage", "Frizione", "Embreagem", "クラッチ", "离合器", "líhéqì"),
    ("Handbrake", "🅿️", "transport-rare", "Freno de mano", "Frein à main", "Freno a mano", "Freio de mão", "サイドブレーキ", "手刹", "shǒushā"),
    ("Odometer", "🔢", "transport-rare", "Cuentakilómetros", "Compteur kilométrique", "Contachilometri", "Hodômetro", "{走行距離計|そうこうきょりけい}", "里程表", "lǐchéngbiǎo"),
    ("Tow truck", "🚚", "transport-rare", "Grúa", "Dépanneuse", "Carro attrezzi", "Guincho", "レッカー{車|しゃ}", "拖车", "tuōchē"),
    ("Commute (noun)", "🚆", "transport-rare", "Trayecto (al trabajo)", "Trajet (domicile-travail)", "Tragitto casa-lavoro (pendolarismo)", "Deslocamento (para o trabalho)", "{通勤|つうきん}", "通勤", "tōngqín"),
    # ---- numbers, maths & data ----
    ("Numerator", "🔼", "numbers-math-rare", "Numerador", "Numérateur", "Numeratore", "Numerador", "{分子|ぶんし}", "分子", "fēnzǐ"),
    ("Denominator", "🔽", "numbers-math-rare", "Denominador", "Dénominateur", "Denominatore", "Denominador", "{分母|ぶんぼ}", "分母", "fēnmǔ"),
    ("Exponent", "⬆️", "numbers-math-rare", "Exponente", "Exposant", "Esponente", "Expoente", "{指数|しすう}", "指数", "zhǐshù"),
    ("Square root", "√", "numbers-math-rare", "Raíz cuadrada", "Racine carrée", "Radice quadrata", "Raiz quadrada", "{平方根|へいほうこん}", "平方根", "píngfānggēn"),
    ("Decimal point", "•", "numbers-math-rare", "Coma decimal", "Virgule (décimale)", "Virgola decimale", "Vírgula decimal", "{小数点|しょうすうてん}", "小数点", "xiǎoshùdiǎn"),
    ("Remainder", "➗", "numbers-math-rare", "Resto", "Reste", "Resto", "Resto", "{余|あま}り", "余数", "yúshù"),
    ("Prime number", "🔢", "numbers-math-rare", "Número primo", "Nombre premier", "Numero primo", "Número primo", "{素数|そすう}", "质数", "zhìshù"),
    ("Integer", "🔟", "numbers-math-rare", "Número entero", "Nombre entier", "Numero intero", "Número inteiro", "{整数|せいすう}", "整数", "zhěngshù"),
    ("Quotient", "➗", "numbers-math-rare", "Cociente", "Quotient", "Quoziente", "Quociente", "{商|しょう}", "商（除法）", "shāng"),
    ("Percentile", "📊", "numbers-math-rare", "Percentil", "Percentile", "Percentile", "Percentil", "パーセンタイル", "百分位数", "bǎifēnwèishù"),
    ("Mean (average)", "📊", "numbers-math-rare", "Media", "Moyenne", "Media", "Média", "{平均|へいきん}", "平均值", "píngjūnzhí"),
    ("Median", "📏", "numbers-math-rare", "Mediana", "Médiane", "Mediana", "Mediana", "{中央値|ちゅうおうち}", "中位数", "zhōngwèishù"),
    ("Outlier", "🎯", "numbers-math-rare", "Valor atípico", "Valeur aberrante", "Valore anomalo", "Valor discrepante (outlier)", "{外|はず}れ{値|ち}", "离群值", "líqúnzhí"),
    ("Standard deviation", "📉", "numbers-math-rare", "Desviación estándar", "Écart-type", "Deviazione standard", "Desvio padrão", "{標準偏差|ひょうじゅんへんさ}", "标准差", "biāozhǔnchā"),
    ("Variance", "📊", "numbers-math-rare", "Varianza", "Variance", "Varianza", "Variância", "{分散|ぶんさん}", "方差", "fāngchā"),
    ("Margin of error", "±", "numbers-math-rare", "Margen de error", "Marge d’erreur", "Margine di errore", "Margem de erro", "{誤差範囲|ごさはんい}", "误差范围", "wùchā fànwéi"),
    ("Sample size", "🧪", "numbers-math-rare", "Tamaño de la muestra", "Taille de l’échantillon", "Dimensione del campione", "Tamanho da amostra", "{標本数|ひょうほんすう}", "样本量", "yàngběnliàng"),
    ("Exponential growth", "🚀", "numbers-math-rare", "Crecimiento exponencial", "Croissance exponentielle", "Crescita esponenziale", "Crescimento exponencial", "{指数関数的|しすうかんすうてき}な{成長|せいちょう}", "指数增长", "zhǐshù zēngzhǎng"),
    ("Order of magnitude", "🔟", "numbers-math-rare", "Orden de magnitud", "Ordre de grandeur", "Ordine di grandezza", "Ordem de grandeza", "{桁|けた}", "数量级", "shùliàngjí"),
    ("Rounding", "🔄", "numbers-math-rare", "Redondeo", "Arrondi", "Arrotondamento", "Arredondamento", "{四捨五入|ししゃごにゅう}", "四舍五入", "sì shě wǔ rù"),
    ("Percentage point", "📌", "numbers-math-rare", "Punto porcentual", "Point de pourcentage", "Punto percentuale", "Ponto percentual", "ポイント（{百分率|ひゃくぶんりつ}の{差|さ}）", "百分点", "bǎifēndiǎn"),
    ("Threefold", "3️⃣", "numbers-math-rare", "Triple (por tres)", "Triple (au triple)", "Triplo (tre volte)", "Triplo (três vezes)", "{三倍|さんばい}の", "三倍的", "sān bèi de"),
    ("A dozen", "🥚", "numbers-math-rare", "Una docena", "Une douzaine", "Una dozzina", "Uma dúzia", "{一|いち}ダース", "一打", "yì dá"),
    ("Round number", "🔟", "numbers-math-rare", "Número redondo", "Chiffre rond", "Cifra tonda", "Número redondo", "{切|き}りのいい{数|かず}", "整数（约数）", "zhěngshù"),
    ("Odds (probability)", "🎲", "numbers-math-rare", "Probabilidades", "Chances (probabilités)", "Probabilità", "Chances (probabilidades)", "{確率|かくりつ}（{勝算|しょうさん}）", "几率", "jīlǜ"),
    # ---- appearance & tailoring ----
    ("Inseam", "👖", "clothing-appearance-rare", "Entrepierna (largo interior)", "Entrejambe", "Cavallo (interno gamba)", "Entrepernas (gancho)", "{股下|またした}", "内缝长", "nèifèng cháng"),
    ("Dart (sewing)", "🪡", "clothing-appearance-rare", "Pinza (costura)", "Pince (couture)", "Pince (ripresa)", "Pence", "ダーツ", "省道（缝纫）", "shěngdào"),
    ("Lapel", "🤵", "clothing-appearance-rare", "Solapa", "Revers", "Risvolto (bavero)", "Lapela", "{襟|えり}（ラペル）", "翻领", "fānlǐng"),
    ("Cuff", "👔", "clothing-appearance-rare", "Puño", "Poignet (manchette)", "Polsino", "Punho", "{袖口|そでぐち}", "袖口", "xiùkǒu"),
    ("Cufflinks", "💎", "clothing-appearance-rare", "Gemelos", "Boutons de manchette", "Gemelli", "Abotoaduras", "カフスボタン", "袖扣", "xiùkòu"),
    ("Gusset", "🔺", "clothing-appearance-rare", "Escudete (refuerzo)", "Gousset (soufflet)", "Gherone (tassello)", "Nesga (reforço)", "まち", "衬料（三角布）", "sānjiǎobù"),
    ("Pleat", "👗", "clothing-appearance-rare", "Pliegue (tabla)", "Pli", "Piega", "Prega", "プリーツ（ひだ）", "褶", "zhě"),
    ("Tailored", "✂️", "clothing-appearance-rare", "A medida", "Sur mesure", "Su misura", "Sob medida", "{仕立|した}ての", "定制的", "dìngzhì de"),
    ("Bespoke", "🎩", "clothing-appearance-rare", "Hecho a medida", "Sur mesure (personnalisé)", "Su misura (bespoke)", "Feito sob medida", "オーダーメイドの", "定制的（高级）", "gāojí dìngzhì de"),
    ("Off-the-rack", "🏷️", "clothing-appearance-rare", "De confección (prêt-à-porter)", "Prêt-à-porter", "Prêt-à-porter (di serie)", "De prateleira (pronto)", "{既製|きせい}の", "成衣的", "chéngyī de"),
    ("Threadbare", "🧶", "clothing-appearance-rare", "Raído", "Élimé (usé jusqu’à la corde)", "Liso (consunto)", "Puído", "{擦|す}り{切|き}れた", "磨破的", "mópò de"),
    ("Frayed", "🪢", "clothing-appearance-rare", "Deshilachado", "Effiloché", "Sfilacciato", "Desfiado", "ほつれた", "磨损的（起毛边）", "qǐ máobiān de"),
    ("Creased", "📄", "clothing-appearance-rare", "Arrugado", "Froissé", "Sgualcito (stropicciato)", "Amassado", "しわくちゃの", "有褶皱的", "yǒu zhězhòu de"),
    ("Dapper", "🕴️", "clothing-appearance-rare", "Elegante (apuesto)", "Pimpant (tiré à quatre épingles)", "Azzimato (elegante)", "Elegante (alinhado)", "こざっぱりした（{小粋|こいき}な）", "衣冠楚楚的", "yīguān chǔchǔ de"),
    ("Disheveled", "🌪️", "clothing-appearance-rare", "Desaliñado", "Débraillé (échevelé)", "Scarmigliato (trasandato)", "Desgrenhado", "{乱|みだ}れた", "衣冠不整的", "yīguān bùzhěng de"),
    ("Scruffy", "🧢", "clothing-appearance-rare", "Desaliñado (andrajoso)", "Négligé (débraillé)", "Trasandato (sciatto)", "Desleixado (maltrapilho)", "むさくるしい", "邋遢的", "lāta de"),
    ("Garish", "🌈", "clothing-appearance-rare", "Chillón", "Criard (tape-à-l’œil)", "Sgargiante (pacchiano)", "Espalhafatoso (berrante)", "けばけばしい", "花哨刺眼的", "huāshào cìyǎn de"),
    ("Understated", "🤍", "clothing-appearance-rare", "Discreto (sobrio)", "Sobre (discret)", "Sobrio (discreto)", "Discreto (sóbrio)", "{控|ひか}えめな", "低调的", "dīdiào de"),
    ("Flattering (clothes)", "✨", "clothing-appearance-rare", "Favorecedor", "Seyant (flatteur)", "Che dona (lusinghiero)", "Que cai bem (favorecedor)", "{似合|にあ}う", "显身材的", "xiǎn shēncái de"),
    ("Baggy", "👖", "clothing-appearance-rare", "Holgado (ancho)", "Ample (large)", "Largo (abbondante)", "Largo (folgado)", "だぶだぶの", "宽松的", "kuānsōng de"),
    ("Snug", "🧤", "clothing-appearance-rare", "Ceñido (ajustado)", "Ajusté (moulant)", "Aderente (attillato)", "Justo (ajustado)", "ぴったりした", "紧身的", "jǐnshēn de"),
    ("Stubble", "🧔", "clothing-appearance-rare", "Barba incipiente", "Barbe de trois jours", "Barba incolta (di tre giorni)", "Barba por fazer", "{無精|ぶしょう}ひげ", "胡茬", "húchá"),
    ("Freckles", "🐞", "clothing-appearance-rare", "Pecas", "Taches de rousseur", "Lentiggini", "Sardas", "そばかす", "雀斑", "quèbān"),
    ("Dimple", "😊", "clothing-appearance-rare", "Hoyuelo", "Fossette", "Fossetta", "Covinha", "えくぼ", "酒窝", "jiǔwō"),
    ("Crow's feet", "👁️", "clothing-appearance-rare", "Patas de gallo", "Pattes-d’oie", "Zampe di gallina", "Pés de galinha", "{目尻|めじり}のしわ", "鱼尾纹", "yúwěiwén"),
    ("Complexion", "🧴", "clothing-appearance-rare", "Cutis (tez)", "Teint", "Carnagione", "Tez (pele)", "{肌|はだ}の{色|いろ}つや", "肤色（面色）", "fūsè"),
    ("Gaunt", "💀", "clothing-appearance-rare", "Demacrado (enjuto)", "Émacié (décharné)", "Scarno (emaciato)", "Macilento (magro)", "やせこけた", "憔悴消瘦的", "qiáocuì xiāoshòu de"),
    ("Stocky", "🧱", "clothing-appearance-rare", "Fornido (robusto)", "Trapu", "Tarchiato", "Atarracado (troncudo)", "ずんぐりした", "矮壮的", "ǎizhuàng de"),
    ("Lanky", "🦒", "clothing-appearance-rare", "Larguirucho", "Dégingandé", "Allampanato", "Desengonçado (magricela)", "ひょろ{長|なが}い", "瘦长的", "shòucháng de"),
    ("Poised", "🧘‍♀️", "clothing-appearance-rare", "Sereno (con aplomo)", "Posé (plein d’assurance)", "Composto (padrone di sé)", "Sereno (com postura)", "{落|お}ち{着|つ}き{払|はら}った", "泰然自若的", "tàirán zìruò de"),
]
