# -*- coding: utf-8 -*-
# A1 vocabulary batch 3 — core verbs I & II, basic adjectives, question words & connectors, weather & nature
TIER = 'A1'
TOPICS = {
    'verbs-1': 'Core Verbs I', 'verbs-2': 'Core Verbs II', 'adjectives-1': 'Basic Adjectives',
    'questions-connectors': 'Questions & Connectors', 'weather-nature': 'Weather & Nature',
}
WORDS = [
    # ---- core verbs I ----
    ("To be", "🧭", "verbs-1", "Ser", "Être", "Essere", "Ser", "です", "是", "shì"),
    ("To have", "🤲", "verbs-1", "Tener", "Avoir", "Avere", "Ter", "{持|も}っている", "有", "yǒu"),
    ("To do", "⚙️", "verbs-1", "Hacer", "Faire", "Fare", "Fazer", "する", "做", "zuò"),
    ("To go", "🚶", "verbs-1", "Ir", "Aller", "Andare", "Ir", "{行|い}く", "去", "qù"),
    ("To come", "🚶‍♂️", "verbs-1", "Venir", "Venir", "Venire", "Vir", "{来|く}る", "来", "lái"),
    ("To want", "🙏", "verbs-1", "Querer", "Vouloir", "Volere", "Querer", "{欲|ほ}しい", "要", "yào"),
    ("To be able to", "💪", "verbs-1", "Poder", "Pouvoir", "Potere", "Poder", "できる", "能", "néng"),
    ("To know", "🧠", "verbs-1", "Saber", "Savoir", "Sapere", "Saber", "{知|し}る", "知道", "zhīdào"),
    ("To see", "👀", "verbs-1", "Ver", "Voir", "Vedere", "Ver", "{見|み}る", "看见", "kànjiàn"),
    ("To say", "🗣️", "verbs-1", "Decir", "Dire", "Dire", "Dizer", "{言|い}う", "说", "shuō"),
    ("To eat", "🍽️", "verbs-1", "Comer", "Manger", "Mangiare", "Comer", "{食|た}べる", "吃", "chī"),
    ("To drink", "🥤", "verbs-1", "Beber", "Boire", "Bere", "Beber", "{飲|の}む", "喝", "hē"),
    ("To sleep", "😴", "verbs-1", "Dormir", "Dormir", "Dormire", "Dormir", "{寝|ね}る", "睡觉", "shuìjiào"),
    ("To live", "🏠", "verbs-1", "Vivir", "Vivre", "Vivere", "Viver", "{住|す}む", "住", "zhù"),
    ("To work", "💼", "verbs-1", "Trabajar", "Travailler", "Lavorare", "Trabalhar", "{働|はたら}く", "工作", "gōngzuò"),
    ("To speak", "💬", "verbs-1", "Hablar", "Parler", "Parlare", "Falar", "{話|はな}す", "说话", "shuōhuà"),
    ("To understand", "💡", "verbs-1", "Entender", "Comprendre", "Capire", "Entender", "わかる", "明白", "míngbai"),
    ("To like", "👍", "verbs-1", "Gustar", "Aimer", "Piacere", "Gostar", "{好|す}き", "喜欢", "xǐhuan"),
    ("To need", "🆘", "verbs-1", "Necesitar", "Avoir besoin de", "Avere bisogno di", "Precisar", "{必要|ひつよう}", "需要", "xūyào"),
    ("To give", "🎁", "verbs-1", "Dar", "Donner", "Dare", "Dar", "あげる", "给", "gěi"),
    ("To take", "✊", "verbs-1", "Tomar", "Prendre", "Prendere", "Pegar", "{取|と}る", "拿", "ná"),
    ("To think", "🤔", "verbs-1", "Pensar", "Penser", "Pensare", "Pensar", "{思|おも}う", "想", "xiǎng"),
    ("To buy", "🛍️", "verbs-1", "Comprar", "Acheter", "Comprare", "Comprar", "{買|か}う", "买", "mǎi"),
    ("To help", "🤝", "verbs-1", "Ayudar", "Aider", "Aiutare", "Ajudar", "{助|たす}ける", "帮助", "bāngzhù"),

    # ---- core verbs II ----
    ("To open", "🔓", "verbs-2", "Abrir", "Ouvrir", "Aprire", "Abrir", "{開|あ}ける", "打开", "dǎkāi"),
    ("To close", "🔒", "verbs-2", "Cerrar", "Fermer", "Chiudere", "Fechar", "{閉|し}める", "关", "guān"),
    ("To look for", "🔍", "verbs-2", "Buscar", "Chercher", "Cercare", "Procurar", "{探|さが}す", "找", "zhǎo"),
    ("To find", "🎯", "verbs-2", "Encontrar", "Trouver", "Trovare", "Encontrar", "{見|み}つける", "找到", "zhǎodào"),
    ("To wait", "⏳", "verbs-2", "Esperar", "Attendre", "Aspettare", "Esperar", "{待|ま}つ", "等", "děng"),
    ("To call (phone)", "📞", "verbs-2", "Llamar", "Appeler", "Chiamare", "Ligar", "{電話|でんわ}する", "打电话", "dǎ diànhuà"),
    ("To read", "📖", "verbs-2", "Leer", "Lire", "Leggere", "Ler", "{読|よ}む", "读", "dú"),
    ("To write", "✍️", "verbs-2", "Escribir", "Écrire", "Scrivere", "Escrever", "{書|か}く", "写", "xiě"),
    ("To listen", "👂", "verbs-2", "Escuchar", "Écouter", "Ascoltare", "Ouvir", "{聞|き}く", "听", "tīng"),
    ("To learn", "🎓", "verbs-2", "Aprender", "Apprendre", "Imparare", "Aprender", "{学|まな}ぶ", "学习", "xuéxí"),
    ("To play", "🎮", "verbs-2", "Jugar", "Jouer", "Giocare", "Brincar", "{遊|あそ}ぶ", "玩", "wán"),
    ("To walk", "🚶‍♀️", "verbs-2", "Caminar", "Marcher", "Camminare", "Caminhar", "{歩|ある}く", "走路", "zǒulù"),
    ("To run", "🏃", "verbs-2", "Correr", "Courir", "Correre", "Correr", "{走|はし}る", "跑", "pǎo"),
    ("To sit", "🪑", "verbs-2", "Sentarse", "S’asseoir", "Sedersi", "Sentar", "{座|すわ}る", "坐", "zuò"),
    ("To stand", "🧍", "verbs-2", "Estar de pie", "Être debout", "Stare in piedi", "Ficar de pé", "{立|た}つ", "站", "zhàn"),
    ("To arrive", "🛬", "verbs-2", "Llegar", "Arriver", "Arrivare", "Chegar", "{着|つ}く", "到", "dào"),
    ("To leave", "🛫", "verbs-2", "Salir", "Partir", "Partire", "Sair", "{出|で}る", "离开", "líkāi"),
    ("To return", "↩️", "verbs-2", "Volver", "Revenir", "Tornare", "Voltar", "{帰|かえ}る", "回来", "huílái"),
    ("To put", "📥", "verbs-2", "Poner", "Mettre", "Mettere", "Colocar", "{置|お}く", "放", "fàng"),
    ("To bring", "📦", "verbs-2", "Traer", "Apporter", "Portare", "Trazer", "{持|も}ってくる", "带来", "dàilái"),
    ("To ask", "❓", "verbs-2", "Preguntar", "Demander", "Chiedere", "Perguntar", "{聞|き}く（{質問|しつもん}）", "问", "wèn"),
    ("To answer", "💡", "verbs-2", "Responder", "Répondre", "Rispondere", "Responder", "{答|こた}える", "回答", "huídá"),
    ("To love", "❤️", "verbs-2", "Amar", "Aimer (d’amour)", "Amare", "Amar", "{愛|あい}する", "爱", "ài"),
    ("To pay", "💳", "verbs-2", "Pagar", "Payer", "Pagare", "Pagar", "{払|はら}う", "付钱", "fù qián"),

    # ---- basic adjectives (legacy colors-shapes has Big/Small/Long/Short) ----
    ("Good", "👍", "adjectives-1", "Bueno", "Bon", "Buono", "Bom", "いい", "好", "hǎo"),
    ("Bad", "👎", "adjectives-1", "Malo", "Mauvais", "Cattivo", "Mau", "{悪|わる}い", "坏", "huài"),
    ("New", "✨", "adjectives-1", "Nuevo", "Nouveau", "Nuovo", "Novo", "{新|あたら}しい", "新", "xīn"),
    ("Old (thing)", "🏚️", "adjectives-1", "Viejo", "Vieux", "Vecchio", "Velho", "{古|ふる}い", "旧", "jiù"),
    ("Young", "🧒", "adjectives-1", "Joven", "Jeune", "Giovane", "Jovem", "{若|わか}い", "年轻", "niánqīng"),
    ("Hot", "🔥", "adjectives-1", "Caliente", "Chaud", "Caldo", "Quente", "{熱|あつ}い", "热", "rè"),
    ("Cold", "🧊", "adjectives-1", "Frío", "Froid", "Freddo", "Frio", "{冷|つめ}たい", "冷", "lěng"),
    ("Happy", "😄", "adjectives-1", "Feliz", "Heureux", "Felice", "Feliz", "{嬉|うれ}しい", "高兴", "gāoxìng"),
    ("Sad", "😢", "adjectives-1", "Triste", "Triste", "Triste", "Triste", "{悲|かな}しい", "难过", "nánguò"),
    ("Beautiful", "🌹", "adjectives-1", "Hermoso", "Beau", "Bello", "Bonito", "{美|うつく}しい", "漂亮", "piàoliang"),
    ("Ugly", "🧟", "adjectives-1", "Feo", "Laid", "Brutto", "Feio", "{醜|みにく}い", "丑", "chǒu"),
    ("Easy", "🟢", "adjectives-1", "Fácil", "Facile", "Facile", "Fácil", "{簡単|かんたん}", "容易", "róngyì"),
    ("Difficult", "🔴", "adjectives-1", "Difícil", "Difficile", "Difficile", "Difícil", "{難|むずか}しい", "难", "nán"),
    ("Fast", "🐆", "adjectives-1", "Rápido", "Rapide", "Veloce", "Rápido", "{速|はや}い", "快", "kuài"),
    ("Slow", "🐢", "adjectives-1", "Lento", "Lent", "Lento", "Lento", "{遅|おそ}い（{速度|そくど}）", "慢", "màn"),
    ("Cheap", "🏷️", "adjectives-1", "Barato", "Bon marché", "Economico", "Barato", "{安|やす}い", "便宜", "piányi"),
    ("Expensive", "💎", "adjectives-1", "Caro", "Cher", "Caro", "Caro", "{高|たか}い（{値段|ねだん}）", "贵", "guì"),
    ("Full", "🈵", "adjectives-1", "Lleno", "Plein", "Pieno", "Cheio", "いっぱい", "满", "mǎn"),
    ("Empty", "🈳", "adjectives-1", "Vacío", "Vide", "Vuoto", "Vazio", "{空|から}", "空", "kōng"),
    ("Clean", "🧼", "adjectives-1", "Limpio", "Propre", "Pulito", "Limpo", "きれい", "干净", "gānjìng"),
    ("Dirty", "🧹", "adjectives-1", "Sucio", "Sale", "Sporco", "Sujo", "{汚|きたな}い", "脏", "zāng"),
    ("Strong", "🏋️", "adjectives-1", "Fuerte", "Fort", "Forte", "Forte", "{強|つよ}い", "强", "qiáng"),
    ("Weak", "🪶", "adjectives-1", "Débil", "Faible", "Debole", "Fraco", "{弱|よわ}い", "弱", "ruò"),
    ("Important", "❗", "adjectives-1", "Importante", "Important", "Importante", "Importante", "{大切|たいせつ}", "重要", "zhòngyào"),

    # ---- question words & connectors ----
    ("What", "❔", "questions-connectors", "Qué", "Quoi", "Cosa", "O que", "{何|なに}", "什么", "shénme"),
    ("Who", "🕵️", "questions-connectors", "Quién", "Qui", "Chi", "Quem", "{誰|だれ}", "谁", "shéi"),
    ("Where", "📍", "questions-connectors", "Dónde", "Où", "Dove", "Onde", "どこ", "哪里", "nǎlǐ"),
    ("When", "📅", "questions-connectors", "Cuándo", "Quand", "Quando", "Quando", "いつ", "什么时候", "shénme shíhou"),
    ("Why", "🤷", "questions-connectors", "Por qué", "Pourquoi", "Perché", "Por quê", "なぜ", "为什么", "wèishénme"),
    ("How", "🛠️", "questions-connectors", "Cómo", "Comment", "Come", "Como", "どう", "怎么", "zěnme"),
    ("How many", "🔢", "questions-connectors", "Cuántos", "Combien", "Quanti", "Quantos", "いくつ", "多少", "duōshao"),
    ("Which", "👆", "questions-connectors", "Cuál", "Lequel", "Quale", "Qual", "どちら", "哪个", "nǎge"),
    ("And", "➕", "questions-connectors", "Y", "Et", "E", "E", "そして", "和", "hé"),
    ("Or", "🔀", "questions-connectors", "O", "Ou", "O", "Ou", "または", "或者", "huòzhě"),
    ("But", "↔️", "questions-connectors", "Pero", "Mais", "Ma", "Mas", "でも", "但是", "dànshì"),
    ("Because", "🔗", "questions-connectors", "Porque", "Parce que", "Perché (causa)", "Porque", "なぜなら", "因为", "yīnwèi"),
    ("With", "🤝", "questions-connectors", "Con", "Avec", "Con", "Com", "〜と", "跟", "gēn"),
    ("Without", "🚫", "questions-connectors", "Sin", "Sans", "Senza", "Sem", "〜なしで", "没有", "méiyǒu"),
    ("For", "🎯", "questions-connectors", "Para", "Pour", "Per", "Para", "〜のために", "为了", "wèile"),
    ("From", "⬅️", "questions-connectors", "De", "De", "Da", "De", "〜から", "从", "cóng"),
    ("To (direction)", "➡️", "questions-connectors", "A", "À", "A", "Para (direção)", "〜へ", "到", "dào"),
    ("In", "📦", "questions-connectors", "En", "Dans", "In", "Em", "〜の{中|なか}に", "在……里", "zài…lǐ"),
    ("On", "🔝", "questions-connectors", "Sobre", "Sur", "Su", "Sobre", "〜の{上|うえ}に", "在……上", "zài…shàng"),
    ("Under", "⬇️", "questions-connectors", "Debajo de", "Sous", "Sotto", "Debaixo de", "〜の{下|した}に", "在……下", "zài…xià"),
    ("This", "👇", "questions-connectors", "Esto", "Ceci", "Questo", "Isto", "これ", "这", "zhè"),
    ("That", "👉", "questions-connectors", "Eso", "Cela", "Quello", "Isso", "それ", "那", "nà"),
    ("Very", "💯", "questions-connectors", "Muy", "Très", "Molto", "Muito", "とても", "很", "hěn"),
    ("Also", "➕", "questions-connectors", "También", "Aussi", "Anche", "Também", "〜も", "也", "yě"),
    ("Not", "❌", "questions-connectors", "No (negación)", "Ne… pas", "Non", "Não (negação)", "〜ない", "不", "bù"),
    ("Maybe", "🤞", "questions-connectors", "Quizás", "Peut-être", "Forse", "Talvez", "たぶん", "也许", "yěxǔ"),

    # ---- weather & nature ----
    ("Sun", "☀️", "weather-nature", "Sol", "Soleil", "Sole", "Sol", "{太陽|たいよう}", "太阳", "tàiyáng"),
    ("Rain", "🌧️", "weather-nature", "Lluvia", "Pluie", "Pioggia", "Chuva", "{雨|あめ}", "雨", "yǔ"),
    ("Snow", "❄️", "weather-nature", "Nieve", "Neige", "Neve", "Neve", "{雪|ゆき}", "雪", "xuě"),
    ("Wind", "🌬️", "weather-nature", "Viento", "Vent", "Vento", "Vento", "{風|かぜ}", "风", "fēng"),
    ("Cloud", "☁️", "weather-nature", "Nube", "Nuage", "Nuvola", "Nuvem", "{雲|くも}", "云", "yún"),
    ("Weather", "🌦️", "weather-nature", "Tiempo (clima)", "Temps (météo)", "Tempo (meteo)", "Tempo (clima)", "{天気|てんき}", "天气", "tiānqì"),
    ("Sky", "🌌", "weather-nature", "Cielo", "Ciel", "Cielo", "Céu", "{空|そら}", "天空", "tiānkōng"),
    ("Sea", "🌊", "weather-nature", "Mar", "Mer", "Mare", "Mar", "{海|うみ}", "海", "hǎi"),
    ("Mountain", "⛰️", "weather-nature", "Montaña", "Montagne", "Montagna", "Montanha", "{山|やま}", "山", "shān"),
    ("River", "🏞️", "weather-nature", "Río", "Rivière", "Fiume", "Rio", "{川|かわ}", "河", "hé"),
    ("Tree", "🌳", "weather-nature", "Árbol", "Arbre", "Albero", "Árvore", "{木|き}", "树", "shù"),
    ("Flower", "🌸", "weather-nature", "Flor", "Fleur", "Fiore", "Flor", "{花|はな}", "花", "huā"),
    ("Dog", "🐶", "weather-nature", "Perro", "Chien", "Cane", "Cachorro", "{犬|いぬ}", "狗", "gǒu"),
    ("Cat", "🐱", "weather-nature", "Gato", "Chat", "Gatto", "Gato", "{猫|ねこ}", "猫", "māo"),
    ("Bird", "🐦", "weather-nature", "Pájaro", "Oiseau", "Uccello", "Pássaro", "{鳥|とり}", "鸟", "niǎo"),
    ("Fish (animal)", "🐠", "weather-nature", "Pez", "Poisson (animal)", "Pesce (animale)", "Peixe (animal)", "{魚|さかな}（{生|い}き{物|もの}）", "鱼（动物）", "yú"),
    ("Horse", "🐴", "weather-nature", "Caballo", "Cheval", "Cavallo", "Cavalo", "{馬|うま}", "马", "mǎ"),
    ("Cow", "🐄", "weather-nature", "Vaca", "Vache", "Mucca", "Vaca", "{牛|うし}", "牛", "niú"),
    ("Earth", "🌍", "weather-nature", "Tierra", "Terre", "Terra", "Terra", "{地球|ちきゅう}", "地球", "dìqiú"),
    ("Moon", "🌕", "weather-nature", "Luna", "Lune", "Luna", "Lua", "{月|つき}（{天体|てんたい}）", "月亮", "yuèliang"),
    ("Star", "⭐", "weather-nature", "Estrella", "Étoile", "Stella", "Estrela", "{星|ほし}", "星星", "xīngxing"),
    ("Fire", "🔥", "weather-nature", "Fuego", "Feu", "Fuoco", "Fogo", "{火|ひ}", "火", "huǒ"),
    ("It’s windy", "🌬️", "weather-nature", "Hace viento", "Il y a du vent", "C’è vento", "Está ventando", "{風|かぜ}が{強|つよ}いです", "风很大", "fēng hěn dà"),
    ("It’s snowing", "🌨️", "weather-nature", "Está nevando", "Il neige", "Nevica", "Está nevando", "{雪|ゆき}が{降|ふ}っています", "在下雪", "zài xiàxuě"),
    ("It’s cold today", "🥶", "weather-nature", "Hoy hace frío", "Il fait froid aujourd’hui", "Oggi fa freddo", "Está frio hoje", "{今日|きょう}は{寒|さむ}い", "今天很冷", "jīntiān hěn lěng"),
    ("It’s hot today", "🥵", "weather-nature", "Hoy hace calor", "Il fait chaud aujourd’hui", "Oggi fa caldo", "Está quente hoje", "{今日|きょう}は{暑|あつ}い", "今天很热", "jīntiān hěn rè"),
]
