# -*- coding: utf-8 -*-
# Diathìris, the tongue of Diathìr: written by tools/import_rodais.py from the Diathìris dictionary.
# The reading line is the pronunciation in IPA.
LANG = 'gr'
WORDS = {
    'a1-after': ('Às dèidh sin', 'ˈaːs ˈtʃeːj ˈʃinʲ'),
    'a1-afternoon': ('Feascar', 'ˈfɛskəɾ'),
    'a1-again': ('A-rithist', 'əˈr̪ˠihɪʃtʃ'),
    'a1-airport': ('Raon-sciathan', 'ˈr̪ˠɯːnˈskʲiəhan'),
    'a1-all': ('Uile', 'ˈulʲə'),
    'a1-also': ('Cuideachd', 'ˈkʰutʃəxk'),
    'a1-always': ('An-còmhnaidh', 'ən̪ˠˈkʰɔ̃ːni'),
    'a1-and': ('Agus', 'ˈakəs'),
    'a1-and-you': ('Agus thu fhèin?', 'ˈakəs ˈu ˈheːnʲ'),
    'a1-angry': ('Feargach', 'ˈfɛɾɛkəx'),
    'a1-apple': ('Ubhal', 'ˈuvəl̪ˠ'),
    'a1-april': ('An Giblean', 'əŋ ˈkʲiplʲan'),
    'a1-arm': ('Gàirdean', 'ˈkaːɾʲtʃan'),
    'a1-august': ('An Lùnastal', 'ən̪ˠ ˈl̪ˠuːnəst̪əl̪ˠ'),
    'a1-aunt': ('Piuthar-athar', 'ˈpʲʰu.əɾˈa.əɾ'),
    'a1-autumn': ('Foghar', 'ˈfɔ.əɾ'),
    'a1-baby': ('Leanabh', 'ˈʎɛnəv'),
    'a1-back-body': ('Druim', 'ˈt̪ɾuːim'),
    'a1-bad': ('Dona', 'ˈt̪ɔnə'),
    'a1-bag': ('Poca', 'ˈpʰɔʰkə'),
    'a1-bakery': ('Taigh-fuine', 'ˈt̪ʰɤjˈfɯnʲə'),
    'a1-bank': ('Banca', 'ˈpan̪ˠkə'),
    'a1-bathroom': ('Seòmar-ionnlaid', 'ˈʃɔːməɾˈjuːn̪ˠl̪ˠɪtʃ'),
    'a1-be-careful': ('Bi faiceallach', 'ˈpi ˈfaʰkʲəl̪ˠəx'),
    'a1-beautiful': ('Brèagha', 'ˈpɾʲiə.ə'),
    'a1-because': ('Oir', 'ˈɔɾʲ'),
    'a1-bed': ('Leabaidh', 'ˈʎɛpi'),
    'a1-bedroom': ('Seòmar-cadail', 'ˈʃɔːməɾˈkʰat̪ɪlʲ'),
    'a1-beer': ('Leann', 'ˈʎaun̪ˠ'),
    'a1-before': ('Roimhe', 'ˈr̪ˠɔvə'),
    'a1-bicycle': ('Each-cuibhle', 'ˈɛxˈkʰuvlʲə'),
    'a1-big': ('Mòr', 'ˈmoːɾ'),
    'a1-bird': ('Eun', 'ˈiən'),
    'a1-birthday': ('Co-là-breith', 'kʰɔˈl̪ˠaːˈpɾʲeh'),
    'a1-black': ('Dubh', 'ˈt̪u'),
    'a1-bless-you': ('Dia leat', 'ˈtʃiə ˈʎɛʰt̪'),
    'a1-blood': ('Fuil', 'ˈfulʲ'),
    'a1-blue': ('Gorm', 'ˈkɔɾɔm'),
    'a1-body': ('Bodhaig', 'ˈpɔ.ɪkʲ'),
    'a1-book': ('Leabhar', 'ˈʎɔ.əɾ'),
    'a1-bored': ('Fo fhadachd', 'fə ˈat̪əxk'),
    'a1-bottle': ('Botal', 'ˈpɔʰt̪əl̪ˠ'),
    'a1-box': ('Bogsa', 'ˈpɔksə'),
    'a1-boy': ('Balach', 'ˈpal̪ˠəx'),
    'a1-boyfriend': ('Bràmair', 'ˈpɾaːmɪɾʲ'),
    'a1-bread': ('Aran', 'ˈaɾan'),
    'a1-breakfast': ('Biadh-maidne', 'ˈpiəɣˈmatʃnʲə'),
    'a1-brother': ('Bràthair', 'ˈpɾaːhɪɾʲ'),
    'a1-brown': ('Donn', 'ˈt̪ɔun̪ˠ'),
    'a1-bus': ('Carbad-sluaigh', 'ˈkʰaɾapət̪ˈsl̪ˠuəj'),
    'a1-but': ('Ach', 'ˈax'),
    'a1-call-the-police': ('Gairmibh luchd na faire', 'ˈkaɾʲamɪv ˈl̪ˠuxk nə ˈfaɾʲə'),
    'a1-calm': ('Ciùin', 'ˈkʲʰuːnʲ'),
    'a1-camera': ('Cìste-scàile', 'ˈkʲʰiːʃtʃəˈskaːlʲə'),
    'a1-can-you-help-me': ('An urrainn dhut mo chuideachadh?', 'ən̪ˠ ˈuːr̪ˠɪɲ ˈɣuʰt̪ mə ˈxutʃəxəɣ'),
    'a1-can-you-repeat-that': ('An urrainn dhut sin a ràdh a-rithist?', 'ən̪ˠ ˈuːr̪ˠɪɲ ˈɣuʰt̪ ˈʃinʲ ə ˈr̪ˠaːɣ əˈr̪ˠihɪʃtʃ'),
    'a1-car': ('Carbad-rathaid', 'ˈkʰaɾapət̪ˈr̪ˠahɪtʃ'),
    'a1-card': ('Cairt', 'ˈkʰaɾʲtʃ'),
    'a1-cash': ('Airgead-làimhe', 'ˈaɾʲakʲət̪ˈl̪ˠaːvə'),
    'a1-cat': ('Cat', 'ˈkʰaʰt̪'),
    'a1-chair': ('Sèithear', 'ˈʃeː.əɾ'),
    'a1-change-coins': ('Iomlaid', 'ˈiml̪ˠɪtʃ'),
    'a1-charger': ('Tobar-dealain', 'ˈt̪ʰɔpəɾˈtʃal̪ˠɪnʲ'),
    'a1-cheap': ('Saor', 'ˈsɯːɾ'),
    'a1-cheers': ('Slàinte mhath!', 'ˈsl̪ˠaːɲtʃə ˈva'),
    'a1-cheese': ('Càise', 'ˈkʰaːʃə'),
    'a1-chicken': ('Cearc', 'ˈkʲʰɛɾk'),
    'a1-child': ('Pàiste', 'ˈpʰaːʃtʃə'),
    'a1-children': ('Clann', 'ˈkʰl̪ˠaun̪ˠ'),
    'a1-church': ('Eaglais', 'ˈekl̪ˠɪʃ'),
    'a1-circle': ('Cearcall', 'ˈkʲʰɛɾkəl̪ˠ'),
    'a1-city': ('Cathair', 'ˈkʰahɪɾʲ'),
    'a1-clean': ('Glan', 'ˈkl̪ˠan'),
    'a1-clock': ('Gleoc', 'ˈkʲlʲɔʰk'),
    'a1-closed-shop': ('Dùinte', 'ˈt̪uːɲtʃə'),
    'a1-clothes': ('Aodach', 'ˈɯːt̪əx'),
    'a1-cloud': ('Scòth', 'ˈskɔː'),
    'a1-coat': ('Còta', 'ˈkʰɔːʰt̪ə'),
    'a1-coffee': ('Cofaidh', 'ˈkʰɔfi'),
    'a1-cold': ('Fuar', 'ˈfuəɾ'),
    'a1-color': ('Dath', 'ˈt̪ah'),
    'a1-come-in': ('Thig a-steach', 'ˈhikʲ əˈʃtʃɛx'),
    'a1-computer': ('Inntinn-iarainn', 'ˈiːɲtʃɪɲˈiəɾɪɲ'),
    'a1-congratulations': ('Meal do naidheachd', 'ˈmʲal̪ˠ t̪ə ˈna.əxk'),
    'a1-country': ('Dùthaich', 'ˈt̪uːhɪç'),
    'a1-cousin': ('Co-ogha', 'kʰɔˈɔ.ə'),
    'a1-cow': ('Bò', 'ˈpɔː'),
    'a1-cup': ('Cupa', 'ˈkʰuʰpə'),
    'a1-dark': ('Dorcha', 'ˈt̪ɔɾɔxə'),
    'a1-daughter': ('Nighean', 'ˈɲi.an'),
    'a1-day': ('Latha', 'ˈl̪ˠa.ə'),
    'a1-december': ('An Dùbhlachd', 'ən̪ˠ ˈt̪uːvl̪ˠəxk'),
    'a1-delicious': ('Blasta', 'ˈpl̪ˠast̪ə'),
    'a1-difficult': ('Duilich', 'ˈt̪ulʲɪç'),
    'a1-dinner': ('Dìnnear', 'ˈtʃiːɲəɾ'),
    'a1-dirty': ('Salach', 'ˈsal̪ˠəx'),
    'a1-discount': ('Lasachadh', 'ˈl̪ˠasəxəɣ'),
    'a1-do-you-speak-english': ('A bheil Beurla agaibh?', 'ə ˈvelʲ ˈpiəɾl̪ˠə ˈakɪv'),
    'a1-dog': ('Cù', 'ˈkʰuː'),
    'a1-dont-worry': ('Na gabh dragh', 'nə ˈkav ˈt̪ɾa'),
    'a1-door': ('Doras', 'ˈt̪ɔɾəs'),
    'a1-dress': ('Gùn', 'ˈkuːn'),
    'a1-drink-noun': ('Deoch', 'ˈtʃɔx'),
    'a1-ear': ('Cluas', 'ˈkʰl̪ˠuəs'),
    'a1-early': ('Tràth', 'ˈt̪ʰɾaː'),
    'a1-earth': ('Talamh', 'ˈt̪ʰal̪ˠəv'),
    'a1-easy': ('Furasta', 'ˈfuɾəst̪ə'),
    'a1-egg': ('Ugh', 'ˈu'),
    'a1-eight': ('A h-ochd', 'ə ˈhɔxk'),
    'a1-eighteen': ('A h-ochd deug', 'ə ˈhɔxk ˈtʃiək'),
    'a1-eighty': ('Ochdad', 'ˈɔxkət̪'),
    'a1-eleven': ('A h-aon deug', 'ə ˈhɯːn ˈtʃiək'),
    'a1-empty': ('Falamh', 'ˈfal̪ˠəv'),
    'a1-enjoy-your-meal': ('Gabh gu math dheth', 'ˈkav kə ˈma ˈjeh'),
    'a1-enough': ('Gu leòr', 'kə ˈʎɔːɾ'),
    'a1-entrance': ('Slighe a-steach', 'ˈʃlʲi.ə əˈʃtʃɛx'),
    'a1-evening': ('Beul na h-oidhche', 'ˈpiəl̪ˠ nə ˈhɤiçə'),
    'a1-exactly': ('Dìreach', 'ˈtʃiːɾʲəx'),
    'a1-excited': ('Air bhioran', 'ˈɛɾʲ ˈviɾan'),
    'a1-excuse-me': ('Gabh mo leisceul', 'ˈkav mə ˈlʲeʃkʲiəl̪ˠ'),
    'a1-exit': ('Slighe a-mach', 'ˈʃlʲi.ə əˈmax'),
    'a1-expensive': ('Daor', 'ˈt̪ɯːɾ'),
    'a1-eye': ('Sùil', 'ˈsuːlʲ'),
    'a1-face': ('Aodann', 'ˈɯːt̪ən̪ˠ'),
    'a1-family': ('Teaghlach', 'ˈtʃʰɛl̪ˠəx'),
    'a1-far': ("Fad' air falbh", "ˈfat̪' ˈɛɾʲ ˈfal̪ˠav"),
    'a1-fast': ('Luath', 'ˈl̪ˠuə'),
    'a1-father': ('Athair', 'ˈahɪɾʲ'),
    'a1-fear': ('Eagal', 'ˈekəl̪ˠ'),
    'a1-february': ('An Gearran', 'əŋ ˈkʲaːr̪ˠan'),
    'a1-few': ('Beagan', 'ˈpekan'),
    'a1-fifteen': ('A còig deug', 'ə ˈkʰoːkʲ ˈtʃiək'),
    'a1-fifty': ('Caogad', 'ˈkʰɯːkət̪'),
    'a1-finger': ('Corrag', 'ˈkʰɔːr̪ˠak'),
    'a1-fire': ('Teine', 'ˈtʃʰenʲə'),
    'a1-first': ("A' chiad", 'ə ˈçiət̪'),
    'a1-fish-animal': ('Iasc', 'ˈiəsk'),
    'a1-fish-food': ('Iasc', 'ˈiəsk'),
    'a1-five': ('A còig', 'ə ˈkʰoːkʲ'),
    'a1-floor-level': ('Ùrlar', 'ˈuːɾl̪ˠəɾ'),
    'a1-flower': ('Flùr', 'ˈfl̪ˠuːɾ'),
    'a1-food': ('Biadh', 'ˈpiəɣ'),
    'a1-foot': ('Troigh', 'ˈt̪ʰɾɤi'),
    'a1-for': ('Airson', 'ˈaɾsən'),
    'a1-fork': ('Forc', 'ˈfɔɾk'),
    'a1-forty': ('Ceathrad', 'ˈkʲʰɛɾət̪'),
    'a1-four': ('A ceithir', 'ə ˈkʲʰehɪɾʲ'),
    'a1-fourteen': ('A ceithir deug', 'ə ˈkʲʰehɪɾʲ ˈtʃiək'),
    'a1-free-no-cost': ('An-ascaidh', 'ən̪ˠˈaski'),
    'a1-friday': ('Dihaoine', 'tʃiˈhɯːnʲə'),
    'a1-friend': ('Caraid', 'ˈkʰaɾɪtʃ'),
    'a1-friend-female': ('Banacharaid', 'ˈpanəxəɾɪtʃ'),
    'a1-from': ('Bho', 'ˈvɔ'),
    'a1-fruit': ('Meas', 'ˈmɛs'),
    'a1-full': ('Làn', 'ˈl̪ˠaːn'),
    'a1-funny': ('Èibhinn', 'ˈeːvɪɲ'),
    'a1-garden': ('Gàrradh', 'ˈkaːr̪ˠəɣ'),
    'a1-gift': ('Tiodhlac', 'ˈtʃʰil̪ˠəʰk'),
    'a1-girl': ('Caileag', 'ˈkʰalʲak'),
    'a1-girlfriend': ('Leannan', 'ˈʎɛn̪ˠan'),
    'a1-glass-cup': ('Glainne', 'ˈkl̪ˠaɲə'),
    'a1-glasses': ('Speuclairean', 'ˈspiəʰkl̪ˠɪɾʲan'),
    'a1-gloves': ('Miotagan', 'ˈmiʰt̪əkan'),
    'a1-good': ('Math', 'ˈma'),
    'a1-good-evening': ('Feascar math', 'ˈfɛskəɾ ˈma'),
    'a1-good-luck': ('Gun èirich dhut', 'kən̪ˠ ˈeːɾʲɪç ˈɣuʰt̪'),
    'a1-good-morning': ('Madainn mhath', 'ˈmat̪ɪɲ ˈva'),
    'a1-good-night': ('Oidhche mhath', 'ˈɤiçə ˈva'),
    'a1-goodbye': ('Beannachd leat', 'ˈpɛn̪ˠəxk ˈʎɛʰt̪'),
    'a1-goodbye-for-now': ('Mar sin leat an-dràsta', 'ˈmaɾ ˈʃinʲ ˈʎɛʰt̪ ən̪ˠˈt̪ɾaːst̪ə'),
    'a1-grandfather': ('Seanair', 'ˈʃɛnɪɾʲ'),
    'a1-grandmother': ('Seanmhair', 'ˈʃɛnɛvɪɾʲ'),
    'a1-gray': ('Liath', 'ˈʎiə'),
    'a1-green': ('Uaine', 'ˈuənʲə'),
    'a1-hair': ('Falt', 'ˈfal̪ˠt̪'),
    'a1-half': ('Leth', 'ˈʎeh'),
    'a1-hand': ('Làmh', 'ˈl̪ˠaːv'),
    'a1-happy': ('Toilichte', 'ˈt̪ʰɔlʲɪçtʃə'),
    'a1-happy-birthday': ('Co-là-breith math dhut', 'kʰɔˈl̪ˠaːˈpɾʲeh ˈma ˈɣuʰt̪'),
    'a1-hat': ('Ad', 'ˈat̪'),
    'a1-have-a-nice-day': ('Latha math dhut', 'ˈl̪ˠa.ə ˈma ˈɣuʰt̪'),
    'a1-he': ('E', 'ˈɛ'),
    'a1-head': ('Ceann', 'ˈkʲʰaun̪ˠ'),
    'a1-heart': ('Cridhe', 'ˈkʰɾʲi.ə'),
    'a1-hello': ('Dia dhut', 'ˈtʃiə ˈɣuʰt̪'),
    'a1-help': ('Cuidichibh mi!', 'ˈkʰutʃɪçɪv ˈmi'),
    'a1-here': ('An seo', 'ən̪ˠ ˈʃɔ'),
    'a1-holiday': ('Latha-fèille', 'ˈl̪ˠa.əˈfeːʎə'),
    'a1-horse': ('Each', 'ˈɛx'),
    'a1-hospital': ('Ospadal', 'ˈɔspət̪əl̪ˠ'),
    'a1-hot': ('Teth', 'ˈtʃʰeh'),
    'a1-hotel': ('Taigh-òsta', 'ˈt̪ʰɤjˈɔːst̪ə'),
    'a1-hour': ('Uair', 'ˈuəɾʲ'),
    'a1-house': ('Taigh', 'ˈt̪ʰɤj'),
    'a1-how': ('Ciamar', 'ˈkʲʰimɛɾ'),
    'a1-how-are-you': ('Ciamar a tha thu?', 'ˈkʲʰimɛɾ ə ˈha ˈu'),
    'a1-how-do-you-say': ('Ciamar a chanas tu…?', 'ˈkʲʰimɛɾ ə ˈxanəs ˈt̪ʰu'),
    'a1-how-many': ('Co mheud', 'ˈkʰɔ ˈviət̪'),
    'a1-how-much-is-it': ("Dè tha e a' cosc?", 'ˈtʃeː ˈha ˈɛ ə ˈkʰɔsk'),
    'a1-husband': ('Fear-pòsta', 'ˈfɛɾˈpʰɔːst̪ə'),
    'a1-i': ('Mi', 'ˈmi'),
    'a1-i-agree': ('Tha mi ag aontachadh', 'ˈha ˈmi ək ˈɯːn̪ˠt̪əxəɣ'),
    'a1-i-dont-know': ('Chan eil fhios agam', 'xan ˈelʲ ˈis ˈakəm'),
    'a1-i-dont-like-it': ('Cha toil leam e', 'xa ˈt̪ʰɔlʲ ˈʎaum ˈɛ'),
    'a1-i-love-it': ('Tha mi fìor dhèidheil air', 'ˈha ˈmi ˈfiəɾ ˈjeː.ɪlʲ ˈɛɾʲ'),
    'a1-i-speak-a-little': ('Tha beagan agam', 'ˈha ˈpekan ˈakəm'),
    'a1-i-think-so': ("Tha mi a' smaoineachadh gu bheil", 'ˈha ˈmi ə ˈsmɯːnʲəxəɣ kə ˈvelʲ'),
    'a1-i-would-like': ('Bu toil leam…', 'pə ˈt̪ʰɔlʲ ˈʎaum'),
    'a1-im-fine': ('Tha mi gu math', 'ˈha ˈmi kə ˈma'),
    'a1-im-from-the-united-states': ('Tha mi às na Stàitean Aonaichte', 'ˈha ˈmi ˈaːs nə ˈst̪aːʰtʃan ˈɯːnɪçtʃə'),
    'a1-im-hungry': ('Tha an t-acras orm', 'ˈha ən̪ˠ ˈt̪ʰaʰkɾəs ˈɔɾɔm'),
    'a1-im-sick': ('Tha mi tinn', 'ˈha ˈmi ˈtʃʰiːɲ'),
    'a1-im-thirsty': ('Tha am pathadh orm', 'ˈha əm ˈba.əɣ ˈɔɾɔm'),
    'a1-im-tired': ('Tha mi scìth', 'ˈha ˈmi ˈskʲiː'),
    'a1-important': ('Cudromach', 'ˈkʰut̪ɾəməx'),
    'a1-in': ('Ann an', 'ˈaun̪ˠ ən̪ˠ'),
    'a1-is-this-on-sale': ('A bheil seo air lasachadh?', 'ə ˈvelʲ ˈʃɔ ˈɛɾʲ ˈl̪ˠasəxəɣ'),
    'a1-is-this-seat-free': ('A bheil an suidheachan seo saor?', 'ə ˈvelʲ ən̪ˠ ˈsu.əxan ˈʃɔ ˈsɯːɾ'),
    'a1-its-an-emergency': ("'S e èiginn a th' ann", 's ˈɛ ˈeːkʲɪɲ ə ˈhaun̪ˠ'),
    'a1-its-cold-today': ('Tha i fuar an-diugh', 'ˈha ˈi ˈfuəɾ ən̪ˠˈtʃu'),
    'a1-its-hot-today': ('Tha i teth an-diugh', 'ˈha ˈi ˈtʃʰeh ən̪ˠˈtʃu'),
    'a1-its-late': ('Tha e anmoch', 'ˈha ˈɛ ˈanaməx'),
    'a1-its-okay': ('Tha e ceart gu leòr', 'ˈha ˈɛ ˈkʲʰɛɾt̪ kə ˈʎɔːɾ'),
    'a1-its-snowing': ('Tha an sneachd ann', 'ˈha ən̪ˠ ˈʃnʲɛxk ˈaun̪ˠ'),
    'a1-its-windy': ('Tha i gaothach', 'ˈha ˈi ˈkɯː.əx'),
    'a1-jacket': ('Seacaid', 'ˈʃeʰkɪtʃ'),
    'a1-january': ('Am Faoilleach', 'əm ˈfɯːʎəx'),
    'a1-joy': ('Aoibhneas', 'ˈɯːvnʲəs'),
    'a1-juice': ('Sùgh', 'ˈsuː'),
    'a1-july': ('An t-Iuchar', 'ən̪ˠ ˈtʃʰuxəɾ'),
    'a1-june': ('An t-Ògmhios', 'ən̪ˠ ˈt̪ʰɔːkʲvəs'),
    'a1-just-a-little': ('Dìreach beagan', 'ˈtʃiːɾʲəx ˈpekan'),
    'a1-key': ('Iuchair', 'ˈjuxɪɾʲ'),
    'a1-kitchen': ('Cidsin', 'ˈkʲʰitʃʃɪnʲ'),
    'a1-knee': ('Glùin', 'ˈkl̪ˠuːnʲ'),
    'a1-knife': ('Scian', 'ˈskʲiən'),
    'a1-lamp': ('Lòchran', 'ˈl̪ˠɔːxɾan'),
    'a1-late': ('Anmoch', 'ˈanaməx'),
    'a1-later': ('Nas fhaide air adhart', 'ˈn̪ˠas ˈatʃə ˈɛɾʲ ˈa.əɾt̪'),
    'a1-left': ('Clì', 'ˈkʲʰlʲiː'),
    'a1-leg': ('Cas', 'ˈkʰas'),
    'a1-less': ('Nas lugha', 'ˈn̪ˠas ˈl̪ˠu.ə'),
    'a1-lets-go': ('Thugainn!', 'ˈhukɪɲ'),
    'a1-light-color': ('Soilleir', 'ˈsɔʎɪɾʲ'),
    'a1-line': ('Loidhne', 'ˈl̪ˠɤinʲə'),
    'a1-lonely': ('Aonaranach', 'ˈɯːnəɾanəx'),
    'a1-long': ('Fada', 'ˈfat̪ə'),
    'a1-long-time-no-see': ('Chan fhaca mi thu o chionn fhada', 'xan ˈaʰkə ˈmi ˈu ə ˈçuːn̪ˠ ˈat̪ə'),
    'a1-love': ('Gaol', 'ˈkɯːl̪ˠ'),
    'a1-lunch': ('Lòn', 'ˈl̪ˠɔːn'),
    'a1-madam': ('Bean-uasal', 'ˈpɛnˈuəsəl̪ˠ'),
    'a1-man': ('Fear', 'ˈfɛɾ'),
    'a1-many': ('Mòran', 'ˈmoːɾan'),
    'a1-map': ('Mapa', 'ˈmaʰpə'),
    'a1-march': ('Am Màrt', 'əm ˈmaːɾt̪'),
    'a1-market': ('Margadh', 'ˈmaɾakəɣ'),
    'a1-married': ('Pòsta', 'ˈpʰɔːst̪ə'),
    'a1-may': ('An Cèitean', 'əŋ ˈɡʲeːʰtʃan'),
    'a1-maybe': ("'S dòcha", 's ˈt̪ɔːxə'),
    'a1-meat': ('Feòil', 'ˈfʲɔːlʲ'),
    'a1-midnight': ('Meadhan-oidhche', 'ˈmɛ.anˈɤiçə'),
    'a1-milk': ('Bainne', 'ˈpaɲə'),
    'a1-minute': ('Mionaid', 'ˈminɪtʃ'),
    'a1-mister': ('Maighstir', 'ˈmɤjʃtʃɪɾʲ'),
    'a1-monday': ('Diluain', 'tʃiˈl̪ˠuənʲ'),
    'a1-money': ('Airgead', 'ˈaɾʲakʲət̪'),
    'a1-month': ('Mìos', 'ˈmiəs'),
    'a1-moon': ('Gealach', 'ˈkʲal̪ˠəx'),
    'a1-more': ('Barrachd', 'ˈpaːr̪ˠəxk'),
    'a1-morning': ('Madainn', 'ˈmat̪ɪɲ'),
    'a1-mother': ('Màthair', 'ˈmaːhɪɾʲ'),
    'a1-mountain': ('Beinn', 'ˈpeiɲ'),
    'a1-mouth': ('Beul', 'ˈpiəl̪ˠ'),
    'a1-my-name-is-alex': ('Is mise Alex', 'ɪs ˈmiʃə ˈalʲəx'),
    'a1-name': ('Ainm', 'ˈanʲam'),
    'a1-near': ('Faisc', 'ˈfaʃkʲ'),
    'a1-neck': ('Amhach', 'ˈavəx'),
    'a1-neighbor': ('Nàbaidh', 'ˈn̪ˠaːpi'),
    'a1-nervous': ('Nearbhasach', 'ˈɲɛɾɛvəsəx'),
    'a1-never': ('A-chaoidh', 'əˈxɯːj'),
    'a1-new': ('Ùr', 'ˈuːɾ'),
    'a1-nice-to-meet-you': ('Tha mi toilichte coinneachadh riut', 'ˈha ˈmi ˈt̪ʰɔlʲɪçtʃə ˈkʰɔɲəxəɣ ˈr̪ˠuʰt̪'),
    'a1-nice-to-see-you': ("Tha e math d' fhaicinn", 'ˈha ˈɛ ˈma ˈt̪aʰkʲɪɲ'),
    'a1-night': ('Oidhche', 'ˈɤiçə'),
    'a1-nine': ('A naoi', 'ə ˈn̪ˠɯi'),
    'a1-nineteen': ('A naoi deug', 'ə ˈn̪ˠɯi ˈtʃiək'),
    'a1-ninety': ('Naochad', 'ˈn̪ˠɯːxət̪'),
    'a1-no': ('Chan eil', 'xan ˈelʲ'),
    'a1-no-problem': ('Chan eil duilgheadas ann', 'xan ˈelʲ ˈt̪ulʲət̪əs ˈaun̪ˠ'),
    'a1-noon': ('Meadhan-latha', 'ˈmɛ.anˈl̪ˠa.ə'),
    'a1-nose': ('Sròn', 'ˈst̪ɾɔːn'),
    'a1-not': ('Cha', 'xa'),
    'a1-nothing': ('Dad', 'ˈt̪at̪'),
    'a1-november': ('An t-Samhain', 'ən̪ˠ ˈt̪avɪnʲ'),
    'a1-now': ('A-nis', 'əˈɲiʃ'),
    'a1-number': ('Àireamh', 'ˈaːɾʲəv'),
    'a1-october': ('An Dàmhair', 'ən̪ˠ ˈt̪aːvɪɾʲ'),
    'a1-of-course': ('Gu dearbh', 'kə ˈtʃɛɾɛv'),
    'a1-office': ('Oifis', 'ˈɔfɪʃ'),
    'a1-often': ('Gu tric', 'kə ˈt̪ʰɾʲiʰkʲ'),
    'a1-old-thing': ('Sean', 'ˈʃɛn'),
    'a1-older-brother': ('Bràthair as sine', 'ˈpɾaːhɪɾʲ ˈas ˈʃinʲə'),
    'a1-on': ('Air', 'ˈɛɾʲ'),
    'a1-one': ('A h-aon', 'ə ˈhɯːn'),
    'a1-one-hundred': ('Ceud', 'ˈkʲʰiət̪'),
    'a1-one-million': ('Millean', 'ˈmiʎan'),
    'a1-one-moment-please': ('Aon mhionaid, mas e ur toil e', 'ˈɯːn ˈvinɪtʃ | ˈmas ˈɛ əɾ ˈt̪ʰɔlʲ ˈɛ'),
    'a1-one-thousand': ('Mìle', 'ˈmiːlʲə'),
    'a1-open-shop': ('Foscailte', 'ˈfɔskɪlʲtʃə'),
    'a1-or': ('No', 'ˈn̪ˠɔ'),
    'a1-orange-color': ('Dearg-bhuidhe', 'ˈtʃɛɾɛkˈvu.ə'),
    'a1-pants': ('Briogais', 'ˈpɾʲikɪʃ'),
    'a1-paper': ('Pàipear', 'ˈpʰaːʰpəɾ'),
    'a1-parents': ('Pàrantan', 'ˈpʰaːɾan̪ˠt̪an'),
    'a1-park': ('Pàirc', 'ˈpʰaːɾʲkʲ'),
    'a1-passport': ('Cead-siubhail', 'ˈkʲʰɛt̪ˈʃuvɪlʲ'),
    'a1-pen': ('Peann', 'ˈpʲʰaun̪ˠ'),
    'a1-people': ('Daoine', 'ˈt̪ɯːnʲə'),
    'a1-person': ('Neach', 'ˈɲɛx'),
    'a1-pet': ('Peata', 'ˈpʰɛʰt̪ə'),
    'a1-pharmacy': ('Bùth-chungaidhean', 'ˈpuːˈxuŋɪ.an'),
    'a1-phone': ('Guth-sreinge', 'ˈkuhˈst̪ɾʲeɲə'),
    'a1-pink': ('Pinc', 'ˈpʰiɲkʲ'),
    'a1-plane': ('Eun-iarainn', 'ˈiənˈiəɾɪɲ'),
    'a1-plate': ('Truinnsear', 'ˈt̪ʰɾuːiɲʃəɾ'),
    'a1-please': ('Mas e do thoil e', 'ˈmas ˈɛ t̪ə ˈhɔlʲ ˈɛ'),
    'a1-price': ('Prìs', 'ˈpʰɾʲiːʃ'),
    'a1-proud': ('Pròiseil', 'ˈpʰɾɔːʃɪlʲ'),
    'a1-purple': ('Purpaidh', 'ˈpʰuɾpi'),
    'a1-rain': ('Uisce', 'ˈɯʃkʲə'),
    'a1-really': ('Dha-rìribh?', 'ˈɣaˈr̪ˠiːɾʲɪv'),
    'a1-receipt': ('Cuidhteas', 'ˈkʰɯjʰtʃəs'),
    'a1-red': ('Dearg', 'ˈtʃɛɾɛk'),
    'a1-restaurant': ('Taigh-bìdh', 'ˈt̪ʰɤjˈpiː'),
    'a1-rice': ('Rus', 'ˈr̪ˠus'),
    'a1-right': ('Deas', 'ˈtʃɛs'),
    'a1-river': ('Abhainn', 'ˈa.ɪɲ'),
    'a1-road': ('Rathad', 'ˈr̪ˠa.ət̪'),
    'a1-room': ('Seòmar', 'ˈʃɔːməɾ'),
    'a1-round': ('Cruinn', 'ˈkʰɾuːiɲ'),
    'a1-sad': ('Brònach', 'ˈpɾɔːnəx'),
    'a1-salt': ('Salann', 'ˈsal̪ˠən̪ˠ'),
    'a1-saturday': ('Disathairne', 'tʃiˈsahəɾnʲə'),
    'a1-scared': ('Fo eagal', 'fə ˈekəl̪ˠ'),
    'a1-scarf': ('Scarfa', 'ˈskaɾfə'),
    'a1-school': ('Scoil', 'ˈskɔlʲ'),
    'a1-sea': ('Muir', 'ˈmuɾʲ'),
    'a1-second': ('An dàrna', 'ən̪ˠ ˈt̪aːɾnə'),
    'a1-see-you-soon': ("Chì mi a dh'aithghearr thu", 'ˈçiː ˈmi ə ˈɣa.ər̪ˠ ˈu'),
    'a1-see-you-tomorrow': ('Chì mi a-màireach thu', 'ˈçiː ˈmi əˈmaːɾʲəx ˈu'),
    'a1-september': ('An t-Sultain', 'ən̪ˠ ˈt̪ul̪ˠt̪ɪnʲ'),
    'a1-seven': ('A seachd', 'ə ˈʃɛxk'),
    'a1-seventeen': ('A seachd deug', 'ə ˈʃɛxk ˈtʃiək'),
    'a1-seventy': ('Seachdad', 'ˈʃɛxkət̪'),
    'a1-shape': ('Cumadh', 'ˈkʰuməɣ'),
    'a1-she': ('I', 'ˈi'),
    'a1-shirt': ('Lèine', 'ˈʎeːnʲə'),
    'a1-shoes': ('Brògan', 'ˈpɾɔːkan'),
    'a1-short-length': ('Goirid', 'ˈkɔɾʲɪtʃ'),
    'a1-shoulder': ('Gualainn', 'ˈkuəl̪ˠɪɲ'),
    'a1-sick-unwell': ('Tinn', 'ˈtʃʰiːɲ'),
    'a1-sister': ('Piuthar', 'ˈpʲʰu.əɾ'),
    'a1-six': ('A sia', 'ə ˈʃiə'),
    'a1-sixteen': ('A sia deug', 'ə ˈʃiə ˈtʃiək'),
    'a1-sixty': ('Seascad', 'ˈʃɛskət̪'),
    'a1-size': ('Meud', 'ˈmiət̪'),
    'a1-skin': ('Craiceann', 'ˈkʰɾaʰkʲən̪ˠ'),
    'a1-skirt': ('Sciort', 'ˈskʲiɾt̪'),
    'a1-sky': ('Speur', 'ˈspiəɾ'),
    'a1-sleepy': ('Cadalach', 'ˈkʰat̪əl̪ˠəx'),
    'a1-slow': ('Slaodach', 'ˈsl̪ˠɯːt̪əx'),
    'a1-slower-please': ('Nas slaodaiche, mas e ur toil e', 'ˈn̪ˠas ˈsl̪ˠɯːt̪ɪçə | ˈmas ˈɛ əɾ ˈt̪ʰɔlʲ ˈɛ'),
    'a1-slowly-please': ('Gu slaodach, mas e ur toil e', 'kə ˈsl̪ˠɯːt̪əx | ˈmas ˈɛ əɾ ˈt̪ʰɔlʲ ˈɛ'),
    'a1-small': ('Beag', 'ˈpek'),
    'a1-snow': ('Sneachd', 'ˈʃnʲɛxk'),
    'a1-soap': ('Siabann', 'ˈʃiəpən̪ˠ'),
    'a1-socks': ('Stocainnean', 'ˈst̪ɔʰkɪɲan'),
    'a1-some': ('Cuid', 'ˈkʰutʃ'),
    'a1-sometimes': ('Uaireannan', 'ˈuəɾʲən̪ˠan'),
    'a1-son': ('Mac', 'ˈmaʰk'),
    'a1-soon': ("A dh'aithghearr", 'ə ˈɣa.ər̪ˠ'),
    'a1-sorry': ('Tha mi duilich', 'ˈha ˈmi ˈt̪ulʲɪç'),
    'a1-soup': ('Brot', 'ˈpɾɔʰt̪'),
    'a1-spicy': ('Spìosrach', 'ˈspiəsɾəx'),
    'a1-spoon': ('Spàin', 'ˈspaːnʲ'),
    'a1-spring': ('Earrach', 'ˈjaːr̪ˠəx'),
    'a1-square': ('Ceàrnag', 'ˈkʲʰaːɾnak'),
    'a1-star': ('Rionnag', 'ˈr̪ˠin̪ˠak'),
    'a1-station': ('Ionad-feithimh', 'ˈinət̪ˈfehɪv'),
    'a1-stomach': ('Stamag', 'ˈst̪amak'),
    'a1-stop-bus-stop': ('Stad-carbaid', 'ˈst̪at̪ˈkʰaɾapɪtʃ'),
    'a1-store': ('Bùth', 'ˈpuː'),
    'a1-straight-ahead': ('Dìreach air adhart', 'ˈtʃiːɾʲəx ˈɛɾʲ ˈa.əɾt̪'),
    'a1-street': ('Sràid', 'ˈst̪ɾaːtʃ'),
    'a1-strong': ('Làidir', 'ˈl̪ˠaːtʃɪɾʲ'),
    'a1-subway': ('Carbad-uamha', 'ˈkʰaɾapət̪ˈuəvə'),
    'a1-sugar': ('Siùcar', 'ˈʃuːʰkəɾ'),
    'a1-suitcase': ('Màileid', 'ˈmaːlʲɪtʃ'),
    'a1-summer': ('Samhradh', 'ˈsãũɾəɣ'),
    'a1-sun': ('Grian', 'ˈkɾʲiən'),
    'a1-sunday': ('Didòmhnaich', 'tʃiˈt̪ɔ̃ːnɪç'),
    'a1-supermarket': ('Margadh-mullaich', 'ˈmaɾakəɣˈmul̪ˠɪç'),
    'a1-surprised': ('Fo iongnadh', 'fə ˈjuːŋnəɣ'),
    'a1-sweater': ('Geansaidh', 'ˈkʲɛnsi'),
    'a1-sweet': ('Milis', 'ˈmilʲɪʃ'),
    'a1-t-shirt': ('Lèine-shamhraidh', 'ˈʎeːnʲəˈhãũɾi'),
    'a1-table': ('Bòrd', 'ˈpɔːɾt̪'),
    'a1-take-care': ('Gabh cùram', 'ˈkav ˈkʰuːɾəm'),
    'a1-taxi': ('Carbad-duaise', 'ˈkʰaɾapət̪ˈt̪uəʃə'),
    'a1-tea': ('Tì', 'ˈtʃʰiː'),
    'a1-television': ('Scàthan-sceòil', 'ˈskaːhanˈskʲɔːlʲ'),
    'a1-ten': ('A deich', 'ə ˈtʃeç'),
    'a1-thank-you': ('Gu robh math agad', 'kə ˈr̪ˠɔ ˈma ˈakət̪'),
    'a1-that': ('Sin', 'ˈʃinʲ'),
    'a1-the-bill-please': ('An cunntas, mas e ur toil e', 'əŋ ˈɡuːn̪ˠt̪əs | ˈmas ˈɛ əɾ ˈt̪ʰɔlʲ ˈɛ'),
    'a1-there': ('An sin', 'ən̪ˠ ˈʃinʲ'),
    'a1-they': ('Iad', 'ˈiət̪'),
    'a1-thing': ('Rud', 'ˈr̪ˠut̪'),
    'a1-third': ('An treas', 'ən̪ˠ ˈd̪ɾʲɛs'),
    'a1-thirteen': ('A trì deug', 'ə ˈt̪ʰɾʲiː ˈtʃiək'),
    'a1-thirty': ('Trithead', 'ˈt̪ʰɾʲi.ət̪'),
    'a1-this': ('Seo', 'ˈʃɔ'),
    'a1-three': ('A trì', 'ə ˈt̪ʰɾʲiː'),
    'a1-thursday': ('Diardaoin', 'tʃiəɾˈt̪ɯːnʲ'),
    'a1-ticket': ('Bileag-turais', 'ˈpilʲakˈt̪ʰuɾɪʃ'),
    'a1-to-answer': ('Freagairt', 'ˈfɾʲekɪɾʲtʃ'),
    'a1-to-arrive': ('Ruigsinn', 'ˈr̪ˠɯkʲʃɪɲ'),
    'a1-to-ask': ('Faighneachd', 'ˈfɤjnʲəxk'),
    'a1-to-be': ('Bhith', 'ˈvih'),
    'a1-to-be-able-to': ('Bhith comasach', 'ˈvih ˈkʰɔməsəx'),
    'a1-to-bring': ('Toirt leat', 'ˈt̪ʰɔɾʲtʃ ˈʎɛʰt̪'),
    'a1-to-buy': ('Ceannach', 'ˈkʲʰɛn̪ˠəx'),
    'a1-to-call-phone': ('Gairm-sreinge', 'ˈkaɾʲamˈst̪ɾʲeɲə'),
    'a1-to-close': ('Dùnadh', 'ˈt̪uːnəɣ'),
    'a1-to-come': ('Tighinn', 'ˈtʃʰi.ɪɲ'),
    'a1-to-direction': ('Gu', 'kə'),
    'a1-to-do': ('Dèanamh', 'ˈtʃiənəv'),
    'a1-to-drink': ('Òl', 'ˈɔːl̪ˠ'),
    'a1-to-drive': ('Stiùireadh-carbaid', 'ˈʃtʃuːɾʲəɣˈkʰaɾapɪtʃ'),
    'a1-to-eat': ('Ithe', 'ˈi.ə'),
    'a1-to-find': ('Lorg', 'ˈl̪ˠɔɾɔk'),
    'a1-to-give': ('Toirt seachad', 'ˈt̪ʰɔɾʲtʃ ˈʃɛxət̪'),
    'a1-to-go': ('Dol', 'ˈt̪ɔl̪ˠ'),
    'a1-to-have': ('Bhith aig', 'ˈvih ˈekʲ'),
    'a1-to-help': ('Cuideachadh', 'ˈkʰutʃəxəɣ'),
    'a1-to-know': ('Fios a bhith aig', 'ˈfis ə ˈvih ˈekʲ'),
    'a1-to-learn': ('Ionnsachadh', 'ˈjuːn̪ˠsəxəɣ'),
    'a1-to-leave': ('Fàgail', 'ˈfaːkɪlʲ'),
    'a1-to-like': ('Còrdadh', 'ˈkʰɔːɾt̪əɣ'),
    'a1-to-listen': ('Èisteachd', 'ˈeːʃtʃəxk'),
    'a1-to-live': ('Fuireach', 'ˈfuɾʲəx'),
    'a1-to-look-for': ('Coimhead airson', 'ˈkʰɔvət̪ ˈaɾsən'),
    'a1-to-love': ('Gràdhachadh', 'ˈkɾaː.əxəɣ'),
    'a1-to-need': ('Feumachdainn', 'ˈfiəməxkɪɲ'),
    'a1-to-open': ('Foscladh', 'ˈfɔskl̪ˠəɣ'),
    'a1-to-pay': ('Pàigheadh', 'ˈpʰaː.əɣ'),
    'a1-to-play': ('Cluich', 'ˈkʰl̪ˠuç'),
    'a1-to-put': ('Cur', 'ˈkʰuɾ'),
    'a1-to-read': ('Leughadh', 'ˈʎiə.əɣ'),
    'a1-to-return': ('Tilleadh', 'ˈtʃʰiʎəɣ'),
    'a1-to-run': ('Ruith', 'ˈr̪ˠuh'),
    'a1-to-say': ('Ràdh', 'ˈr̪ˠaːɣ'),
    'a1-to-see': ('Faicinn', 'ˈfaʰkʲɪɲ'),
    'a1-to-sell': ('Reic', 'ˈr̪ˠeʰkʲ'),
    'a1-to-sit': ('Suidhe', 'ˈsu.ə'),
    'a1-to-sleep': ('Cadal', 'ˈkʰat̪əl̪ˠ'),
    'a1-to-speak': ('Bruidhinn', 'ˈpɾu.ɪɲ'),
    'a1-to-stand': ('Seasamh', 'ˈʃɛsəv'),
    'a1-to-take': ('Gabhail', 'ˈkavɪlʲ'),
    'a1-to-think': ('Smaoineachadh', 'ˈsmɯːnʲəxəɣ'),
    'a1-to-travel': ('Siubhal', 'ˈʃuvəl̪ˠ'),
    'a1-to-understand': ('Tuigsinn', 'ˈt̪ʰɯkʲʃɪɲ'),
    'a1-to-wait': ('Feitheamh', 'ˈfe.əv'),
    'a1-to-walk': ('Coiseachd', 'ˈkʰɔʃəxk'),
    'a1-to-want': ('Iarraidh', 'ˈiər̪ˠi'),
    'a1-to-wear': ('Caitheamh', 'ˈkʰa.əv'),
    'a1-to-work': ('Obair', 'ˈɔpɪɾʲ'),
    'a1-to-write': ('Scrìobhadh', 'ˈskɾʲiəvəɣ'),
    'a1-today': ('An-diugh', 'ən̪ˠˈtʃu'),
    'a1-tomorrow': ('A-màireach', 'əˈmaːɾʲəx'),
    'a1-tonight': ('A-nochd', 'əˈn̪ˠɔxk'),
    'a1-too-much': ('Cus', 'ˈkʰus'),
    'a1-tooth': ('Fiacail', 'ˈfiəʰkɪlʲ'),
    'a1-toothbrush': ('Bruis-fhiaclan', 'ˈpɾɯʃˈiəʰkl̪ˠan'),
    'a1-towel': ('Searbhadair', 'ˈʃɛɾɛvət̪ɪɾʲ'),
    'a1-train': ('Carbad-iarainn', 'ˈkʰaɾapət̪ˈiəɾɪɲ'),
    'a1-tree': ('Craobh', 'ˈkʰɾɯːv'),
    'a1-triangle': ('Triantan', 'ˈt̪ʰɾʲiən̪ˠt̪an'),
    'a1-trip': ('Turas', 'ˈt̪ʰuɾəs'),
    'a1-tuesday': ('Dimàirt', 'tʃiˈmaːɾʲtʃ'),
    'a1-twelve': ('A dhà dheug', 'ə ˈɣaː ˈjiək'),
    'a1-twenty': ('Fichead', 'ˈfiçət̪'),
    'a1-two': ('A dhà', 'ə ˈɣaː'),
    'a1-ugly': ('Grànda', 'ˈkɾaːn̪ˠt̪ə'),
    'a1-umbrella': ('Scàilean', 'ˈskaːlʲan'),
    'a1-uncle': ('Bràthair-athar', 'ˈpɾaːhɪɾʲˈa.əɾ'),
    'a1-under': ('Fo', 'fə'),
    'a1-vegetables': ('Glasraich', 'ˈkl̪ˠasɾɪç'),
    'a1-very': ('Glè', 'ˈkʲlʲeː'),
    'a1-wait-a-moment': ('Fuirich mionaid', 'ˈfuɾʲɪç ˈminɪtʃ'),
    'a1-wall': ('Balla', 'ˈpal̪ˠə'),
    'a1-wallet': ('Sporan', 'ˈspɔɾan'),
    'a1-watch-wrist': ('Uaireadair', 'ˈuəɾʲət̪ɪɾʲ'),
    'a1-water': ('Uisce', 'ˈɯʃkʲə'),
    'a1-we': ('Sinn', 'ˈʃiːɲ'),
    'a1-weak': ('Lag', 'ˈl̪ˠak'),
    'a1-weather': ('Aimsir', 'ˈamʃɪɾʲ'),
    'a1-wednesday': ('Diciadain', 'tʃiˈkʲʰiət̪ɪnʲ'),
    'a1-week': ('Seachdain', 'ˈʃɛxkɪnʲ'),
    'a1-weekend': ('Deireadh-seachdain', 'ˈtʃeɾʲəɣˈʃɛxkɪnʲ'),
    'a1-welcome': ('Fàilte', 'ˈfaːlʲtʃə'),
    'a1-what': ('Dè', 'ˈtʃeː'),
    'a1-what-does-that-mean': ("Dè tha sin a' ciallachadh?", 'ˈtʃeː ˈha ˈʃinʲ ə ˈkʲʰiəl̪ˠəxəɣ'),
    'a1-whats-this': ('Dè tha seo?', 'ˈtʃeː ˈha ˈʃɔ'),
    'a1-whats-your-name': ("Dè an t-ainm a th' ort?", 'ˈtʃeː ən̪ˠ ˈt̪ʰanʲam ə ˈhɔɾt̪'),
    'a1-when': ('Cuin', 'ˈkʰɯnʲ'),
    'a1-where': ('Càite', 'ˈkʰaːʰtʃə'),
    'a1-where-are-you-from': ('Cò às a tha thu?', 'ˈkʰɔː ˈaːs ə ˈha ˈu'),
    'a1-where-is-it': ('Càite a bheil e?', 'ˈkʰaːʰtʃə ə ˈvelʲ ˈɛ'),
    'a1-where-is-the-bathroom': ('Càite a bheil an seòmar-ionnlaid?', 'ˈkʰaːʰtʃə ə ˈvelʲ ən̪ˠ ˈʃɔːməɾˈjuːn̪ˠl̪ˠɪtʃ'),
    'a1-which': ('Cò aca', 'ˈkʰɔː ˈaʰkə'),
    'a1-which-way': ('Dè an rathad?', 'ˈtʃeː ən̪ˠ ˈr̪ˠa.ət̪'),
    'a1-white': ('Geal', 'ˈkʲal̪ˠ'),
    'a1-who': ('Cò', 'ˈkʰɔː'),
    'a1-why': ('Carson', 'ˈkʰaɾsən'),
    'a1-wife': ('Bean-phòsta', 'ˈpɛnˈfɔːst̪ə'),
    'a1-wind': ('Gaoth', 'ˈkɯː'),
    'a1-window': ('Uinneag', 'ˈɯɲak'),
    'a1-wine': ('Fìon', 'ˈfiən'),
    'a1-winter': ('Geamhradh', 'ˈkʲãũɾəɣ'),
    'a1-with': ('Le', 'lʲə'),
    'a1-without': ('Gun', 'kən̪ˠ'),
    'a1-woman': ('Boireannach', 'ˈpɔɾʲən̪ˠəx'),
    'a1-worried': ('Iomagaineach', 'ˈiməkɪnʲəx'),
    'a1-year': ('Bliadhna', 'ˈplʲiənə'),
    'a1-yellow': ('Buidhe', 'ˈpu.ə'),
    'a1-yes': ('Seadh', 'ˈʃɛɣ'),
    'a1-yesterday': ('An-dè', 'ən̪ˠˈtʃeː'),
    'a1-you': ('Thu', 'ˈu'),
    'a1-young': ('Òg', 'ˈɔːk'),
    'a1-younger-sister': ('Piuthar as òige', 'ˈpʲʰu.əɾ ˈas ˈɔːkʲə'),
    'a1-youre-welcome': ("'S e do bheatha", 's ˈɛ t̪ə ˈvɛ.ə'),
    'a1-zero': ('Neoni', 'ˈɲɔnʲɪ'),
    'a2-a-bit': ('Beagan', 'ˈpekan'),
    'a2-a-cold-illness': ('Cnatan', 'ˈkʰn̪ˠaʰt̪an'),
    'a2-a-lot': ('Mòran', 'ˈmoːɾan'),
    'a2-a-table-for-two': ('Bòrd airson dithis', 'ˈpɔːɾt̪ ˈaɾsən ˈtʃihɪʃ'),
    'a2-abroad': ('Thall thairis', 'ˈhaul̪ˠ ˈhaɾʲɪʃ'),
    'a2-accent': ('Blas', 'ˈpl̪ˠas'),
    'a2-accountant': ('Cunntasair', 'ˈkʰuːn̪ˠt̪əsɪɾʲ'),
    'a2-actor': ('Actair', 'ˈaʰkt̪ɪɾʲ'),
    'a2-actually': ('Dha-rìribh', 'ˈɣaˈr̪ˠiːɾʲɪv'),
    'a2-address': ('Seòladh', 'ˈʃɔːl̪ˠəɣ'),
    'a2-adult': ('Inbheach', 'ˈinʲivəx'),
    'a2-age': ('Aois', 'ˈɯːʃ'),
    'a2-ago': ('O chionn', 'ə ˈçuːn̪ˠ'),
    'a2-alarm-clock': ('Gleoc-dùscaidh', 'ˈkʲlʲɔʰkˈt̪uːski'),
    'a2-allergy': ('Fuath-fola', 'ˈfuəˈfɔl̪ˠə'),
    'a2-almost': ('Cha mhòr', 'xa ˈvoːɾ'),
    'a2-already': ('Mu thràth', 'mə ˈhɾaː'),
    'a2-animal': ('Beathach', 'ˈpɛ.əx'),
    'a2-anniversary': ('Ceann-bliadhna', 'ˈkʲʰaun̪ˠˈplʲiənə'),
    'a2-answer-noun': ('Freagairt', 'ˈfɾʲekɪɾʲtʃ'),
    'a2-anyway': ('Co-dhiù', 'kʰɔˈjuː'),
    'a2-apartment': ('Còmhnaidh-làir', 'ˈkʰɔ̃ːniˈl̪ˠaːɾʲ'),
    'a2-app': ('Innleachd-clàir', 'ˈiːɲlʲəxkˈkʰl̪ˠaːɾʲ'),
    'a2-appointment': ('Àm-coinneachaidh', 'ˈaːmˈkʰɔɲəxi'),
    'a2-architect': ('Ailtire', 'ˈalʲtʃɪɾʲə'),
    'a2-are-you-free-on-saturday': ('A bheil thu saor Disathairne?', 'ə ˈvelʲ ˈu ˈsɯːɾ tʃiˈsahəɾnʲə'),
    'a2-are-you-kidding': ('A bheil thu ri fealla-dhà?', 'ə ˈvelʲ ˈu ɾʲə ˈfɛl̪ˠəˈɣaː'),
    'a2-arrival': ('Ruighinn', 'ˈr̪ˠu.ɪɲ'),
    'a2-art': ('Ealain', 'ˈjal̪ˠɪnʲ'),
    'a2-artist': ('Neach-ealain', 'ˈɲɛxˈjal̪ˠɪnʲ'),
    'a2-ashamed': ('Nàraichte', 'ˈn̪ˠaːɾɪçtʃə'),
    'a2-at-least': ("Air a' char as lugha", 'ˈɛɾʲ ə ˈxaɾ ˈas ˈl̪ˠu.ə'),
    'a2-at-the-beginning': ('Aig an toiseach', 'ˈekʲ ən̪ˠ ˈd̪ɔʃəx'),
    'a2-at-the-end': ('Aig an deireadh', 'ˈekʲ ən̪ˠ ˈtʃeɾʲəɣ'),
    'a2-atm': ('Tobar-airgid', 'ˈt̪ʰɔpəɾˈaɾʲakʲɪtʃ'),
    'a2-avocado': ('Peur-ìme', 'ˈpʰiəɾˈiːmə'),
    'a2-baker': ('Fuineadair', 'ˈfɯnʲət̪ɪɾʲ'),
    'a2-banana': ('Adharc-meala', 'ˈa.əɾkˈmʲal̪ˠə'),
    'a2-bank-account': ('Cunntas banca', 'ˈkʰuːn̪ˠt̪əs ˈpan̪ˠkə'),
    'a2-baseball': ('Cluiche-slacain', 'ˈkʰl̪ˠuçəˈsl̪ˠaʰkɪnʲ'),
    'a2-basketball': ('Cluiche-clèibh', 'ˈkʰl̪ˠuçəˈkʲʰlʲeːv'),
    'a2-battery': ('Ciste-spionnaidh', 'ˈkʲʰiʃtʃəˈspin̪ˠi'),
    'a2-beach': ('Tràigh', 'ˈt̪ʰɾaːj'),
    'a2-beans': ('Pònair', 'ˈpʰɔːnɪɾʲ'),
    'a2-beard': ('Feusag', 'ˈfiəsak'),
    'a2-bee': ('Seillean', 'ˈʃeʎan'),
    'a2-beginner': ('Neach-tòiseachaidh', 'ˈɲɛxˈt̪ʰɔːʃəxi'),
    'a2-bell-pepper': ('Piobar milis', 'ˈpʰipəɾ ˈmilʲɪʃ'),
    'a2-between': ('Eadar', 'ˈɛt̪əɾ'),
    'a2-bill-utility': ('Bile', 'ˈpilʲə'),
    'a2-bitter': ('Searbh', 'ˈʃɛɾɛv'),
    'a2-blanket': ('Plaide', 'ˈpʰl̪ˠatʃə'),
    'a2-block': ('Bloca', 'ˈpl̪ˠɔʰkə'),
    'a2-blond': ('Bàn', 'ˈpaːn'),
    'a2-blood-pressure': ('Neart-cuisle', 'ˈɲɛɾt̪ˈkʰɯʃlʲə'),
    'a2-board-game': ('Cluiche-bùird', 'ˈkʰl̪ˠuçəˈpuːɾʲtʃ'),
    'a2-boring': ('Liosda', 'ˈʎist̪ə'),
    'a2-boss': ('Ceannard', 'ˈkʲʰɛn̪ˠəɾt̪'),
    'a2-brand': ('Comharra-ceàird', 'ˈkʰɔvər̪ˠəˈkʲʰiɾʲtʃ'),
    'a2-break-pause': ('Fois', 'ˈfɔʃ'),
    'a2-bridge': ('Drochaid', 'ˈt̪ɾɔxɪtʃ'),
    'a2-budget': ('Roinn-ionmhais', 'ˈr̪ˠɔiɲˈinivɪʃ'),
    'a2-building': ('Togalach', 'ˈt̪ʰɔkəl̪ˠəx'),
    'a2-busy': ('Trang', 'ˈt̪ʰɾauŋk'),
    'a2-butter': ('Ìm', 'ˈiːm'),
    'a2-butterfly': ('Dealan-dè', 'ˈtʃal̪ˠanˈtʃeː'),
    'a2-by-the-way': ('Eadar dà sceul', 'ˈɛt̪əɾ ˈt̪aː ˈskʲiəl̪ˠ'),
    'a2-cabbage': ('Càl', 'ˈkʰaːl̪ˠ'),
    'a2-cake': ('Cèic', 'ˈkʲʰeːʰkʲ'),
    'a2-can-i-pay-by-card': ('Am faod mi pàigheadh le cairt?', 'əm ˈfɯːt̪ ˈmi ˈpʰaː.əɣ lʲə ˈkʰaɾʲtʃ'),
    'a2-can-you-call-me': ('An cuir thu guth-sreinge thugam?', 'əŋ ˈɡuɾʲ ˈu ˈkuhˈst̪ɾʲeɲə ˈhukəm'),
    'a2-candle': ('Coinneal', 'ˈkʰɔɲəl̪ˠ'),
    'a2-cards-game': ('Cairtean', 'ˈkʰaɾʲtʃan'),
    'a2-career': ('Dreuchd', 'ˈt̪ɾʲiəxk'),
    'a2-carrot': ('Curran', 'ˈkʰuːr̪ˠan'),
    'a2-cashier': ('Airgeadair', 'ˈaɾʲakʲət̪ɪɾʲ'),
    'a2-centimeter': ('Meur-slaite', 'ˈmiəɾˈsl̪ˠaʰtʃə'),
    'a2-channel': ('Sruth-sceòil', 'ˈst̪ɾuhˈskʲɔːlʲ'),
    'a2-cheaper': ('Nas saoire', 'ˈn̪ˠas ˈsɯːɾʲə'),
    'a2-check-in': ('Clàradh-ruighinn', 'ˈkʰl̪ˠaːɾəɣˈr̪ˠu.ɪɲ'),
    'a2-cheerful': ('Sunndach', 'ˈsuːn̪ˠt̪əx'),
    'a2-chef': ('Còcaire', 'ˈkʰɔːʰkɪɾʲə'),
    'a2-cherry': ('Sirist', 'ˈʃiɾʲɪʃtʃ'),
    'a2-chess': ('Tàileasc', 'ˈt̪ʰaːlʲəsk'),
    'a2-childhood': ('Leanabas', 'ˈʎɛnəpəs'),
    'a2-christmas': ('Nollaig', 'ˈn̪ˠɔl̪ˠɪkʲ'),
    'a2-cinema': ('Talla-scàile', 'ˈt̪ʰal̪ˠəˈskaːlʲə'),
    'a2-class': ('Clas', 'ˈkʰl̪ˠas'),
    'a2-classroom': ('Seòmar-teagaisc', 'ˈʃɔːməɾˈtʃʰekɪʃkʲ'),
    'a2-cloudy': ('Neulach', 'ˈɲiəl̪ˠəx'),
    'a2-coach': ('Oide-cluiche', 'ˈɔtʃəˈkʰl̪ˠuçə'),
    'a2-coconut': ('Cnò-chòco', 'ˈkʰn̪ˠɔːˈxɔːʰkə'),
    'a2-coin': ('Bonn airgid', 'ˈpɔun̪ˠ ˈaɾʲakʲɪtʃ'),
    'a2-colleague': ('Co-obraiche', 'kʰɔˈɔpɾɪçə'),
    'a2-comfortable': ('Cofhurtail', 'ˈkʰɔ.əɾt̪ɪlʲ'),
    'a2-company': ('Companaidh', 'ˈkʰɔmpani'),
    'a2-competition': ('Farpais', 'ˈfaɾpɪʃ'),
    'a2-concert': ('Cuirm-chiùil', 'ˈkʰuɾʲumˈçuːlʲ'),
    'a2-confused': ('Ann an imcheist', 'ˈaun̪ˠ ən̪ˠ ˈimçɪʃtʃ'),
    'a2-conversation': ('Còmhradh', 'ˈkʰɔ̃ːɾəɣ'),
    'a2-corn': ('Cruithneachd innseanach', 'ˈkʰɾunʲəxk ˈiːɲʃanəx'),
    'a2-corner': ('Oisean', 'ˈɔʃan'),
    'a2-correct': ('Ceart', 'ˈkʲʰɛɾt̪'),
    'a2-cough': ('Casad', 'ˈkʰasət̪'),
    'a2-couple': ('Càraid', 'ˈkʰaːɾɪtʃ'),
    'a2-course': ('Cùrsa', 'ˈkʰuːɾsə'),
    'a2-credit-card': ('Clàr-fiachan', 'ˈkʰl̪ˠaːɾˈfiəxan'),
    'a2-cucumber': ('Cularan', 'ˈkʰul̪ˠəɾan'),
    'a2-curious': ('Fiosrach', 'ˈfisɾəx'),
    'a2-curly-hair': ('Falt dualach', 'ˈfal̪ˠt̪ ˈt̪uəl̪ˠəx'),
    'a2-customer': ('Custamair', 'ˈkʰust̪əmɪɾʲ'),
    'a2-cycling': ('Marcachd-cuibhle', 'ˈmaɾkəxkˈkʰuvlʲə'),
    'a2-dangerous': ('Cunnartach', 'ˈkʰun̪ˠəɾt̪əx'),
    'a2-dark-haired': ('Dorch-fhaltach', 'ˈt̪ɔɾɔxˈal̪ˠt̪əx'),
    'a2-deadline': ('Crìoch-ama', 'ˈkʰɾʲiəxˈamə'),
    'a2-debt': ('Fiachan', 'ˈfiəxan'),
    'a2-degree': ('Ceum', 'ˈkʲʰiəm'),
    'a2-degree-temperature': ('Ceum', 'ˈkʲʰiəm'),
    'a2-delay': ('Dàil', 'ˈt̪aːlʲ'),
    'a2-delivery': ('Lìbhrigeadh', 'ˈʎiːvɾʲɪkʲəɣ'),
    'a2-dentist': ('Fiaclair', 'ˈfiəʰkl̪ˠɪɾʲ'),
    'a2-departure': ('Falbh', 'ˈfal̪ˠav'),
    'a2-desert': ('Fàsach', 'ˈfaːsəx'),
    'a2-designer': ('Dealbhaiche', 'ˈtʃal̪ˠavɪçə'),
    'a2-dessert': ('Milsean', 'ˈmilʲʃan'),
    'a2-dictionary': ('Faclair', 'ˈfaʰkl̪ˠɪɾʲ'),
    'a2-different': ('Eadar-dhealaichte', 'ˈɛt̪əɾˈjal̪ˠɪçtʃə'),
    'a2-disappointed': ('Diombach', 'ˈtʃimpəx'),
    'a2-dish': ('Mias', 'ˈmiəs'),
    'a2-dishes': ('Soithichean', 'ˈsɔhɪçan'),
    'a2-distance': ('Astar', 'ˈast̪əɾ'),
    'a2-divorced': ('Dealaichte', 'ˈtʃal̪ˠɪçtʃə'),
    'a2-do-you-have-a-discount': ('A bheil lasachadh agaibh?', 'ə ˈvelʲ ˈl̪ˠasəxəɣ ˈakɪv'),
    'a2-do-you-have-it-in-another-color': ('A bheil e agaibh ann an dath eile?', 'ə ˈvelʲ ˈɛ ˈakɪv ˈaun̪ˠ ən̪ˠ ˈt̪ah ˈelʲə'),
    'a2-doctor': ('Lighiche', 'ˈʎi.ɪçə'),
    'a2-double': ('Dùbailte', 'ˈt̪uːpɪlʲtʃə'),
    'a2-downtown': ("Meadhan a' bhaile", 'ˈmɛ.an ə ˈvalʲə'),
    'a2-dozen': ('Dusan', 'ˈt̪usan'),
    'a2-driver': ('Stiùiriche-carbaid', 'ˈʃtʃuːɾʲɪçəˈkʰaɾapɪtʃ'),
    'a2-dry': ('Tioram', 'ˈtʃʰiɾəm'),
    'a2-during': ('Rè', 'ˈr̪ˠeː'),
    'a2-electrician': ('Ceàrd-dealanaich', 'ˈkʲʰaːɾt̪ˈtʃal̪ˠanɪç'),
    'a2-elephant': ('Ailbhean', 'ˈalʲavan'),
    'a2-elevator': ('Seòmar-dìridh', 'ˈʃɔːməɾˈtʃiːɾʲi'),
    'a2-email': ('Litir-lìn', 'ˈʎiʰtʃɪɾʲˈʎiːnʲ'),
    'a2-embarrassed': ('Tàmailteach', 'ˈt̪ʰaːmɪlʲtʃəx'),
    'a2-emergency': ('Èiginn', 'ˈeːkʲɪɲ'),
    'a2-engineer': ('Innleadair', 'ˈiːɲlʲət̪ɪɾʲ'),
    'a2-every-day': ('Gach latha', 'ˈkax ˈl̪ˠa.ə'),
    'a2-exam': ('Deuchainn', 'ˈtʃiəxɪɲ'),
    'a2-example': ('Eisimpleir', 'ˈeʃɪmplʲɪɾʲ'),
    'a2-exchange-rate': ('Reat iomlaid', 'ˈr̪ˠɛʰt̪ ˈiml̪ˠɪtʃ'),
    'a2-expensive-habit': ('Cleachdadh daor', 'ˈkʲʰlʲɛxkəɣ ˈt̪ɯːɾ'),
    'a2-famous': ('Ainmeil', 'ˈanʲamɪlʲ'),
    'a2-fan-supporter': ('Neach-leantainn', 'ˈɲɛxˈʎɛn̪ˠt̪ɪɲ'),
    'a2-farm': ('Tuathanas', 'ˈt̪ʰuəhanəs'),
    'a2-farmer': ('Tuathanach', 'ˈt̪ʰuəhanəx'),
    'a2-fever': ('Fiabhras', 'ˈfiəvɾəs'),
    'a2-field': ('Achadh', 'ˈaxəɣ'),
    'a2-file': ('Duilleag-fiosa', 'ˈt̪uʎakˈfisə'),
    'a2-finally': ('Mu dheireadh', 'mə ˈjeɾʲəɣ'),
    'a2-firefighter': ('Bàthaiche-teine', 'ˈpaːhɪçəˈtʃʰenʲə'),
    'a2-fishing': ('Iascach', 'ˈiəskəx'),
    'a2-fitting-room': ('Seòmar-feuchainn', 'ˈʃɔːməɾˈfiəxɪɲ'),
    'a2-flight': ('Turas-speura', 'ˈt̪ʰuɾəsˈspiəɾə'),
    'a2-flu': ('Cnatan mòr', 'ˈkʰn̪ˠaʰt̪an ˈmoːɾ'),
    'a2-fluent': ('Fileanta', 'ˈfilʲan̪ˠt̪ə'),
    'a2-fog': ('Ceò', 'ˈkʲʰɔː'),
    'a2-folder': ('Pascan', 'ˈpʰaskan'),
    'a2-for-a-long-time': ('Fad ùine mhòr', 'ˈfat̪ ˈuːnʲə ˈvoːɾ'),
    'a2-for-example': ('Mar eisimpleir', 'ˈmaɾ ˈeʃɪmplʲɪɾʲ'),
    'a2-forecast': ('Fàisneachd-sìde', 'ˈfaːʃnʲəxkˈʃiːtʃə'),
    'a2-forest': ('Coille', 'ˈkʰɔʎə'),
    'a2-free-time': ('Ùine shaor', 'ˈuːnʲə ˈhɯːɾ'),
    'a2-fresh': ('Ùr', 'ˈuːɾ'),
    'a2-fridge': ('Cùil-reothaidh', 'ˈkʰuːlʲˈr̪ˠɔhi'),
    'a2-friendly': ('Càirdeil', 'ˈkʰaːɾʲtʃɪlʲ'),
    'a2-frustrated': ('Sàraichte', 'ˈsaːɾɪçtʃə'),
    'a2-furniture': ('Àirneis', 'ˈaːɾʲnʲɪʃ'),
    'a2-game': ('Cluiche', 'ˈkʰl̪ˠuçə'),
    'a2-garlic': ('Creamh', 'ˈkʰɾʲɛv'),
    'a2-gas-station': ('Tobar-connaidh', 'ˈt̪ʰɔpəɾˈkʰɔn̪ˠi'),
    'a2-gate': ('Geata', 'ˈkʲɛʰt̪ə'),
    'a2-generous': ('Fialaidh', 'ˈfiəl̪ˠi'),
    'a2-good-point': ('Deagh phuing', 'ˈtʃɛ ˈfuːiɲkʲ'),
    'a2-grade-mark': ('Comharra', 'ˈkʰɔvər̪ˠə'),
    'a2-gram': ('Gràinne-meidhe', 'ˈkɾaːɲəˈme.ə'),
    'a2-grandchild': ('Ogha', 'ˈɔ.ə'),
    'a2-grapes': ('Fìon-dhearcan', 'ˈfiənˈjɛɾkan'),
    'a2-grass': ('Feur', 'ˈfiəɾ'),
    'a2-grateful': ('Taingeil', 'ˈt̪ʰaɲɪlʲ'),
    'a2-guest': ('Aoigh', 'ˈɯːj'),
    'a2-guide': ('Neach-iùil', 'ˈɲɛxˈjuːlʲ'),
    'a2-gym': ('Talla-neirt', 'ˈt̪ʰal̪ˠəˈɲeɾʲtʃ'),
    'a2-habit': ('Àbhaist', 'ˈaːvɪʃtʃ'),
    'a2-hairdresser': ('Gruagaire', 'ˈkɾuəkɪɾʲə'),
    'a2-handsome': ('Eireachdail', 'ˈeɾʲəxkɪlʲ'),
    'a2-hard-firm': ('Cruaidh', 'ˈkʰɾuəj'),
    'a2-hardworking': ('Dìcheallach', 'ˈtʃiːçəl̪ˠəx'),
    'a2-headphones': ('Sligean-cluaise', 'ˈʃlʲikʲanˈkʰl̪ˠuəʃə'),
    'a2-healthy': ('Fallain', 'ˈfal̪ˠɪnʲ'),
    'a2-heavy': ('Trom', 'ˈt̪ʰɾɔum'),
    'a2-height': ('Àirde', 'ˈaːɾʲtʃə'),
    'a2-history': ('Eachdraidh', 'ˈɛxkɾi'),
    'a2-hobby': ('Cur-seachad', 'ˈkʰuɾˈʃɛxət̪'),
    'a2-homework': ('Obair-dachaigh', 'ˈɔpɪɾʲˈt̪axi'),
    'a2-honest': ('Onarach', 'ˈɔnəɾəx'),
    'a2-hopeful': ('Dòchasach', 'ˈt̪ɔːxəsəx'),
    'a2-how-do-i-get-to': ('Ciamar a gheibh mi gu…?', 'ˈkʲʰimɛɾ ə ˈjev ˈmi kə'),
    'a2-how-do-i-get-to-the-airport': ('Ciamar a ruigeas mi an cala-itealaich?', 'ˈkʲʰimɛɾ ə ˈr̪ˠɯkʲəs ˈmi əŋ ˈɡal̪ˠəˈiʰtʃəl̪ˠɪç'),
    'a2-how-much-is-this': ("Dè a' phrìs a th' air seo?", 'ˈtʃeː ə ˈfɾʲiːʃ ə ˈhɛɾʲ ˈʃɔ'),
    'a2-humid': ('Tais', 'ˈt̪ʰaʃ'),
    'a2-hurry-up': ('Greas ort!', 'ˈkɾʲɛs ˈɔɾt̪'),
    'a2-i-am-a-student': ("'S e oileanach a th' annam", 's ˈɛ ˈɔlʲanəx ə ˈhan̪ˠəm'),
    'a2-i-am-looking-for-a-job': ("Tha mi a' coimhead airson obair", 'ˈha ˈmi ə ˈkʰɔvət̪ ˈaɾsən ˈɔpɪɾʲ'),
    'a2-i-am-studying': ('Tha mi ag ionnsachadh', 'ˈha ˈmi ək ˈjuːn̪ˠsəxəɣ'),
    'a2-i-dont-feel-well': ('Chan eil mi gu math', 'xan ˈelʲ ˈmi kə ˈma'),
    'a2-i-dont-understand': ("Chan eil mi a' tuigsinn", 'xan ˈelʲ ˈmi ə ˈt̪ʰɯkʲʃɪɲ'),
    'a2-i-feel-better': ("Tha mi a' faireachdainn nas fheàrr.", 'ˈha ˈmi ə ˈfaɾʲəxkɪɲ ˈn̪ˠas ˈjaːr̪ˠ'),
    'a2-i-have-a-headache': ('Tha ceann goirt orm', 'ˈha ˈkʲʰaun̪ˠ ˈkɔɾʲtʃ ˈɔɾɔm'),
    'a2-i-have-a-meeting': ('Tha coinneamh agam', 'ˈha ˈkʰɔɲəv ˈakəm'),
    'a2-i-like-to-read': ("'S toil leam a bhith a' leughadh", 's ˈt̪ʰɔlʲ ˈʎaum ə ˈvih ə ˈʎiə.əɣ'),
    'a2-i-need-a-doctor': ('Tha feum agam air lighiche', 'ˈha ˈfiəm ˈakəm ˈɛɾʲ ˈʎi.ɪçə'),
    'a2-i-play-sports': ("Bidh mi a' dèanamh spòrs", 'ˈpiː ˈmi ə ˈtʃiənəv ˈspɔːɾs'),
    'a2-i-work-in-an-office': ('Tha mi ag obair ann an oifis', 'ˈha ˈmi ək ˈɔpɪɾʲ ˈaun̪ˠ ən̪ˠ ˈɔfɪʃ'),
    'a2-ill-take-it': ('Gabhaidh mi e', 'ˈkavi ˈmi ˈɛ'),
    'a2-im-allergic-to-peanuts': ('Tha fuath-cuirp agam ri cnòthan-talmhainn', 'ˈha ˈfuəˈkʰuɾʲp ˈakəm ɾʲə ˈkʰn̪ˠɔːhanˈt̪ʰal̪ˠavɪɲ'),
    'a2-im-busy-today': ('Tha mi trang an-diugh', 'ˈha ˈmi ˈt̪ʰɾauŋk ən̪ˠˈtʃu'),
    'a2-im-just-looking': ("Chan eil mi ach a' coimhead", 'xan ˈelʲ ˈmi ˈax ə ˈkʰɔvət̪'),
    'a2-im-lost': ('Tha mi air chall', 'ˈha ˈmi ˈɛɾʲ ˈxaul̪ˠ'),
    'a2-im-not-sure': ('Chan eil mi cinnteach', 'xan ˈelʲ ˈmi ˈkʲʰiːɲtʃəx'),
    'a2-im-on-my-way': ('Tha mi air an t-slighe', 'ˈha ˈmi ˈɛɾʲ ən̪ˠ ˈtʃlʲi.ə'),
    'a2-in-a-bad-mood': ('Ann an droch shunnd', 'ˈaun̪ˠ ən̪ˠ ˈt̪ɾɔx ˈhuːn̪ˠt̪'),
    'a2-in-a-good-mood': ('Ann an deagh shunnd', 'ˈaun̪ˠ ən̪ˠ ˈtʃɛ ˈhuːn̪ˠt̪'),
    'a2-in-a-hurry': ('Ann an cabhaig', 'ˈaun̪ˠ əŋ ˈɡavɪkʲ'),
    'a2-in-my-opinion': ('Nam bheachd-sa', 'nəm ˈvɛxkˈsa'),
    'a2-ingredient': ('Tàthchuid', 'ˈt̪ʰaːxɪtʃ'),
    'a2-injury': ('Leòn', 'ˈʎɔːn'),
    'a2-insect': ('Meanbh-bhiastag', 'ˈmɛnɛvˈviəst̪ak'),
    'a2-insurance': ('Àrachas', 'ˈaːɾəxəs'),
    'a2-interest-bank': ('Riadh', 'ˈr̪ˠiəɣ'),
    'a2-interesting': ('Inntinneach', 'ˈiːɲtʃɪɲəx'),
    'a2-internet': ('Lìon-fiosa', 'ˈʎiənˈfisə'),
    'a2-interview': ('Agallamh', 'ˈakəl̪ˠəv'),
    'a2-invitation': ('Cuireadh', 'ˈkʰuɾʲəɣ'),
    'a2-invoice': ('Fàirdeal', 'ˈfaːɾʲtʃəl̪ˠ'),
    'a2-is-it-far': ("A bheil e fad' air falbh?", "ə ˈvelʲ ˈɛ ˈfat̪' ˈɛɾʲ ˈfal̪ˠav"),
    'a2-island': ('Eilean', 'ˈelʲan'),
    'a2-it-depends': ('Tha e an crochadh', 'ˈha ˈɛ əŋ ˈɡɾɔxəɣ'),
    'a2-it-fits-me': ("Tha e a' freagairt orm.", 'ˈha ˈɛ ə ˈfɾʲekɪɾʲtʃ ˈɔɾɔm'),
    'a2-it-hurts-here': ('Tha e goirt an seo', 'ˈha ˈɛ ˈkɔɾʲtʃ ən̪ˠ ˈʃɔ'),
    'a2-its-raining': ('Tha an t-uisce ann', 'ˈha ən̪ˠ ˈt̪ʰɯʃkʲə ˈaun̪ˠ'),
    'a2-its-sunny': ("Tha a' ghrian a' deàrrsadh", 'ˈha ə ˈɣɾʲiən ə ˈtʃaːr̪ˠsəɣ'),
    'a2-its-too-expensive': ('Tha e ro dhaor', 'ˈha ˈɛ ɾə ˈɣɯːɾ'),
    'a2-its-up-to-you': ('Tha e an urra riut fhèin', 'ˈha ˈɛ ən̪ˠ ˈuːr̪ˠə ˈr̪ˠuʰt̪ ˈheːnʲ'),
    'a2-jealous': ('Eudmhor', 'ˈiət̪vəɾ'),
    'a2-job': ('Obair', 'ˈɔpɪɾʲ'),
    'a2-joke': ('Fealla-dhà', 'ˈfɛl̪ˠəˈɣaː'),
    'a2-journalist': ('Neach-naidheachd', 'ˈɲɛxˈn̪ˠa.əxk'),
    'a2-keyboard': ('Clàr-litreach', 'ˈkʰl̪ˠaːɾˈʎiʰtʃɾʲəx'),
    'a2-kilogram': ('Mìle-gràinne', 'ˈmiːlʲəˈkɾaːɲə'),
    'a2-kilometer': ('Mìle-slat', 'ˈmiːlʲəˈsl̪ˠaʰt̪'),
    'a2-kind': ('Còir', 'ˈkʰɔːɾʲ'),
    'a2-lake': ('Loch', 'ˈl̪ˠɔx'),
    'a2-landlord': ('Uachdaran', 'ˈuəxkəɾan'),
    'a2-language': ('Cànan', 'ˈkʰaːnan'),
    'a2-laptop': ('Leabhar-smuain', 'ˈʎɔ.əɾˈsmuənʲ'),
    'a2-last-week': ('An t-seachdain sa chaidh', 'ən̪ˠ ˈtʃɛxkɪnʲ sə ˈxaj'),
    'a2-last-year': ('An-uiridh', 'ən̪ˠˈuɾʲi'),
    'a2-laundry': ('Aodach-nighe', 'ˈɯːt̪əxˈɲi.ə'),
    'a2-lawyer': ('Neach-lagha', 'ˈɲɛxˈl̪ˠa.ə'),
    'a2-lazy': ('Leisc', 'ˈʎeʃkʲ'),
    'a2-leaf': ('Duilleag', 'ˈt̪uʎak'),
    'a2-lemon': ('Liomaid', 'ˈʎimɪtʃ'),
    'a2-length': ('Fad', 'ˈfat̪'),
    'a2-lesson': ('Leasan', 'ˈʎɛsan'),
    'a2-let-me-think': ('Leig leam smaoineachadh', 'ˈʎekʲ ˈʎaum ˈsmɯːnʲəxəɣ'),
    'a2-lets-meet-tomorrow': ('Coinnichidh sinn a-màireach', 'ˈkʰɔɲɪçi ˈʃiːɲ əˈmaːɾʲəx'),
    'a2-lettuce': ('Leatas', 'ˈʎɛʰt̪əs'),
    'a2-level': ('Ìre', 'ˈiːɾʲə'),
    'a2-library': ('Leabharlann', 'ˈʎɛvəɾl̪ˠən̪ˠ'),
    'a2-light-weight': ('Aotrom', 'ˈɯːʰt̪ɾəm'),
    'a2-lion': ('Leòmhann', 'ˈʎɔːvən̪ˠ'),
    'a2-liter': ('Làn-soithich', 'ˈl̪ˠaːnˈsɔhɪç'),
    'a2-loan': ('Iasad', 'ˈiəsət̪'),
    'a2-luggage': ('Treallaich', 'ˈt̪ʰɾʲɛl̪ˠɪç'),
    'a2-main-course': ('Prìomh chùrsa', 'ˈpʰɾʲiəv ˈxuːɾsə'),
    'a2-mall': ('Baile-bhùthan', 'ˈpalʲəˈvuːhan'),
    'a2-manager': ('Maor-obrach', 'ˈmɯːɾˈɔpɾəx'),
    'a2-mango': ('Ubhal-grèine', 'ˈuvəl̪ˠˈkɾʲeːnʲə'),
    'a2-math': ('Matamataig', 'ˈmaʰt̪əməʰt̪ɪkʲ'),
    'a2-me-neither': ('Mise nas motha', 'ˈmiʃə ˈn̪ˠas ˈmɔ.ə'),
    'a2-mechanic': ('Gobha-rotha', 'ˈkɔvəˈr̪ˠɔ.ə'),
    'a2-medal': ('Bonn', 'ˈpɔun̪ˠ'),
    'a2-medicine': ('Leigheas', 'ˈʎe.əs'),
    'a2-menu': ('Clàr-bìdh', 'ˈkʰl̪ˠaːɾˈpiː'),
    'a2-message': ('Teachdaireachd', 'ˈtʃʰɛxkɪɾʲəxk'),
    'a2-meter': ('Slat-riaghailt', 'ˈsl̪ˠaʰt̪ˈr̪ˠiə.ɪlʲtʃ'),
    'a2-mirror': ('Scàthan', 'ˈskaːhan'),
    'a2-mistake': ('Mearachd', 'ˈmɛɾəxk'),
    'a2-modern': ('Nuadh-aimsireil', 'ˈn̪ˠuəɣˈamʃɪɾʲɪlʲ'),
    'a2-monkey': ('Muncaidh', 'ˈmun̪ˠki'),
    'a2-mood': ('Gean', 'ˈkʲɛn'),
    'a2-mosquito': ('Corr-mhial', 'ˈkʰɔːr̪ˠˈviəl̪ˠ'),
    'a2-movie': ('Sceul-scàile', 'ˈskʲiəl̪ˠˈskaːlʲə'),
    'a2-museum': ('Taigh-tascaidh', 'ˈt̪ʰɤjˈt̪ʰaski'),
    'a2-mushroom': ('Balgan-buachair', 'ˈpal̪ˠakanˈpuəxɪɾʲ'),
    'a2-music': ('Ceòl', 'ˈkʲʰɔːl̪ˠ'),
    'a2-musician': ('Neach-ciùil', 'ˈɲɛxˈkʲʰuːlʲ'),
    'a2-my-favorite-is-music': ("'S e ceòl as fheàrr leam", 's ˈɛ ˈkʲʰɔːl̪ˠ ˈas ˈjaːr̪ˠ ˈʎaum'),
    'a2-nap': ('Norrag', 'ˈn̪ˠɔːr̪ˠak'),
    'a2-narrow': ('Cumhang', 'ˈkʰuvəŋk'),
    'a2-neighborhood': ('Nàbachd', 'ˈn̪ˠaːpəxk'),
    'a2-nephew': ('Mac peathar', 'ˈmaʰk ˈpʰɛ.əɾ'),
    'a2-never-mind': ('Coma leat', 'ˈkʰɔmə ˈʎɛʰt̪'),
    'a2-new-year': ('Bliadhna Ùr', 'ˈplʲiənə ˈuːɾ'),
    'a2-news': ('Naidheachd', 'ˈn̪ˠa.əxk'),
    'a2-next-to': ('Ri taobh', 'ɾʲə ˈt̪ʰɯːv'),
    'a2-next-week': ('An ath-sheachdain', 'ən̪ˠ ˈahˈhɛxkɪnʲ'),
    'a2-next-year': ('An ath-bhliadhna', 'ən̪ˠ ˈahˈvlʲiənə'),
    'a2-nice-person': ('Laghach', 'ˈl̪ˠa.əx'),
    'a2-niece': ('Nighean bràthar', 'ˈɲi.an ˈpɾaː.əɾ'),
    'a2-no-way': ('Cha tachair sin idir!', 'xa ˈt̪ʰaxɪɾʲ ˈʃinʲ ˈitʃɪɾʲ'),
    'a2-noisy': ('Faramach', 'ˈfaɾəməx'),
    'a2-noodles': ('Sreangan-taoise', 'ˈst̪ɾʲɛŋanˈt̪ʰɯːʃə'),
    'a2-not-yet': ('Chan ann fhathast', 'xan ˈaun̪ˠ ˈhã.əst̪'),
    'a2-notebook': ('Leabhar-notaichean', 'ˈʎɔ.əɾˈn̪ˠɔʰt̪ɪçan'),
    'a2-notification': ('Brath', 'ˈpɾah'),
    'a2-nurse': ('Banaltram', 'ˈpanəl̪ˠt̪ɾəm'),
    'a2-nuts': ('Cnò', 'ˈkʰn̪ˠɔː'),
    'a2-ocean': ('Cuan', 'ˈkʰuən'),
    'a2-oil': ('Ola', 'ˈɔl̪ˠə'),
    'a2-old-person': ('Aosta', 'ˈɯːst̪ə'),
    'a2-on-time': ('Aig an àm cheart', 'ˈekʲ ən̪ˠ ˈaːm ˈçɛɾt̪'),
    'a2-on-weekends-i-rest': ("Bidh mi a' gabhail fois aig an deireadh-sheachdain", 'ˈpiː ˈmi ə ˈkavɪlʲ ˈfɔʃ ˈekʲ ən̪ˠ ˈtʃeɾʲəɣˈhɛxkɪnʲ'),
    'a2-once': ('Aon turas', 'ˈɯːn ˈt̪ʰuɾəs'),
    'a2-one-ticket-please': ('Aon tiogaid, mas e ur toil e', 'ˈɯːn ˈtʃʰikɪtʃ | ˈmas ˈɛ əɾ ˈt̪ʰɔlʲ ˈɛ'),
    'a2-one-way': ('Aon-slighe', 'ˈɯːnˈʃlʲi.ə'),
    'a2-onion': ('Uinnean', 'ˈɯɲan'),
    'a2-online-shopping': ('Ceannach-lìn', 'ˈkʲʰɛn̪ˠəxˈʎiːnʲ'),
    'a2-only': ('A-mhàin', 'əˈvaːnʲ'),
    'a2-only-child': ('Aon-leanabh', 'ˈɯːnˈʎɛnəv'),
    'a2-opinion': ('Beachd', 'ˈpɛxk'),
    'a2-opposite': ('Mu choinneimh', 'mə ˈxɔɲɪv'),
    'a2-orange-fruit': ('Orains', 'ˈɔɾɪnʲʃ'),
    'a2-oven': ('Àmhainn', 'ˈaːvɪɲ'),
    'a2-overweight': ('Reamhar', 'ˈr̪ˠɛvəɾ'),
    'a2-package': ('Pascan', 'ˈpʰaskan'),
    'a2-pain': ('Pian', 'ˈpʰiən'),
    'a2-pair': ('Paidhir', 'ˈpʰa.ɪɾʲ'),
    'a2-parking-lot': ('Buaile-charbad', 'ˈpuəlʲəˈxaɾapət̪'),
    'a2-party': ('Cuirm', 'ˈkʰuɾʲum'),
    'a2-password': ('Facal-faire', 'ˈfaʰkəl̪ˠˈfaɾʲə'),
    'a2-patient': ('Foighidneach', 'ˈfɔ.ɪtʃnʲəx'),
    'a2-payment': ('Pàigheadh', 'ˈpʰaː.əɣ'),
    'a2-peach': ('Peitseag', 'ˈpʰeʰtʃʃak'),
    'a2-pear': ('Peur', 'ˈpʰiəɾ'),
    'a2-pepper': ('Piobar', 'ˈpʰipəɾ'),
    'a2-percent': ('Sa cheud', 'sə ˈçiət̪'),
    'a2-photo': ('Dealbh', 'ˈtʃal̪ˠav'),
    'a2-photography': ('Glacadh-scàile', 'ˈkl̪ˠaʰkəɣˈskaːlʲə'),
    'a2-picnic': ('Cuirm-chnuic', 'ˈkʰuɾʲumˈxnɯʰkʲ'),
    'a2-piece': ('Pìos', 'ˈpʰiəs'),
    'a2-pig': ('Muc', 'ˈmuʰk'),
    'a2-pillow': ('Cluasag', 'ˈkʰl̪ˠuəsak'),
    'a2-pilot': ('Stiùiriche-speura', 'ˈʃtʃuːɾʲɪçəˈspiəɾə'),
    'a2-pineapple': ('Anann', 'ˈanən̪ˠ'),
    'a2-plant': ('Lus', 'ˈl̪ˠus'),
    'a2-plumber': ('Plumair', 'ˈpʰl̪ˠumɪɾʲ'),
    'a2-podcast': ('Sceul-cluaise', 'ˈskʲiəl̪ˠˈkʰl̪ˠuəʃə'),
    'a2-police-officer': ('Maor-sìthe', 'ˈmɯːɾˈʃiː.ə'),
    'a2-police-station': ('Taigh-freiceadain', 'ˈt̪ʰɤjˈfɾʲeʰkʲət̪ɪnʲ'),
    'a2-polite': ('Modhail', 'ˈmɔ.ɪlʲ'),
    'a2-poor': ('Bochd', 'ˈpɔxk'),
    'a2-popular': ('Mòr-chòrdte', 'ˈmoːɾˈxɔːɾʲtʃtʃə'),
    'a2-post-office': ("Oifis a' phuist", 'ˈɔfɪʃ ə ˈfɯʃtʃ'),
    'a2-potato': ('Buntàta', 'ˈpun̪ˠt̪aːʰt̪ə'),
    'a2-prescription': ('Òrdugh-leighis', 'ˈɔːɾt̪əɣˈʎe.ɪʃ'),
    'a2-printer': ('Clò-bhualadair', 'ˈkʰl̪ˠɔːˈvuəl̪ˠət̪ɪɾʲ'),
    'a2-programmer': ('Ceàrd-òrduigh', 'ˈkʲʰaːɾt̪ˈɔːɾt̪i'),
    'a2-project': ('Obair-rùin', 'ˈɔpɪɾʲˈr̪ˠuːnʲ'),
    'a2-pumpkin': ('Peapag', 'ˈpʰɛʰpak'),
    'a2-puzzle': ('Tòimhseachan', 'ˈt̪ʰɔ̃ːʃəxan'),
    'a2-quality': ('Càileachd', 'ˈkʰaːlʲəxk'),
    'a2-question': ('Ceist', 'ˈkʲʰeʃtʃ'),
    'a2-quiet-person': ('Sàmhach', 'ˈsaːvəx'),
    'a2-rabbit': ('Coineanach', 'ˈkʰɔnʲanəx'),
    'a2-race': ('Rèis', 'ˈr̪ˠeːʃ'),
    'a2-ready': ('Deiseil', 'ˈtʃeʃɪlʲ'),
    'a2-recently': ('O chionn ghoirid', 'ə ˈçuːn̪ˠ ˈɣɔɾʲɪtʃ'),
    'a2-recipe': ('Reasabaidh', 'ˈr̪ˠɛsəpi'),
    'a2-referee': ('Breitheamh-cluiche', 'ˈpɾʲe.əvˈkʰl̪ˠuçə'),
    'a2-refund': ('Ais-dhìoladh', 'ˈaʃˈjiəl̪ˠəɣ'),
    'a2-relatives': ('Luchd-dàimh', 'ˈl̪ˠuxkˈt̪aːv'),
    'a2-relieved': ('Tha faochadh orm', 'ˈha ˈfɯːxəɣ ˈɔɾɔm'),
    'a2-rent': ('Màl', 'ˈmaːl̪ˠ'),
    'a2-reservation': ('Àite glèidhte', 'ˈaːʰtʃə ˈkʲlʲeːjʰtʃə'),
    'a2-rich': ('Beartach', 'ˈpɛɾt̪əx'),
    'a2-right-away': ('Sa bhad', 'sə ˈvat̪'),
    'a2-ripe': ('Abaich', 'ˈapɪç'),
    'a2-rock': ('Creag', 'ˈkʰɾʲek'),
    'a2-roommate': ('Co-lòistear', 'kʰɔˈl̪ˠɔːʃtʃəɾ'),
    'a2-round-trip': ('Turas tillidh', 'ˈt̪ʰuɾəs ˈtʃʰiʎi'),
    'a2-routine': ('Gnàth-chùrsa', 'ˈkn̪ˠaːˈxuːɾsə'),
    'a2-rude': ('Mì-mhodhail', 'ˈmiːˈvɔ.ɪlʲ'),
    'a2-running': ('Ruith', 'ˈr̪ˠuh'),
    'a2-safe': ('Sàbhailte', 'ˈsaːvɪlʲtʃə'),
    'a2-salary': ('Tuarastal', 'ˈt̪ʰuəɾəst̪əl̪ˠ'),
    'a2-salary-raise': ('Àrdachadh pàighidh', 'ˈaːɾt̪əxəɣ ˈpʰaː.i'),
    'a2-sale-discount-event': ('Reic lasachaidh', 'ˈr̪ˠeʰkʲ ˈl̪ˠasəxi'),
    'a2-salesperson': ('Neach-reic', 'ˈɲɛxˈr̪ˠeʰkʲ'),
    'a2-salty': ('Saillte', 'ˈsaiʎtʃə'),
    'a2-same': ('Ceudna', 'ˈkʲʰiət̪nə'),
    'a2-same-here': ('Mise cuideachd', 'ˈmiʃə ˈkʰutʃəxk'),
    'a2-sand': ('Gainmheach', 'ˈkanʲavəx'),
    'a2-satisfied': ('Riaraichte', 'ˈr̪ˠiəɾɪçtʃə'),
    'a2-sauce': ('Sabhs', 'ˈsavs'),
    'a2-schedule': ('Clàr-ama', 'ˈkʰl̪ˠaːɾˈamə'),
    'a2-scholarship': ('Scoilearachd', 'ˈskɔlʲəɾəxk'),
    'a2-science': ('Fios-dùile', 'ˈfisˈt̪uːlʲə'),
    'a2-scientist': ('Rannsaiche-dùile', 'ˈr̪ˠaun̪ˠsɪçəˈt̪uːlʲə'),
    'a2-score': ('Scòr', 'ˈskɔːɾ'),
    'a2-screen': ('Clàr-solais', 'ˈkʰl̪ˠaːɾˈsɔl̪ˠɪʃ'),
    'a2-screenshot': ('Samhla-glainne', 'ˈsãũl̪ˠəˈkl̪ˠaɲə'),
    'a2-seat': ('Suidheachan', 'ˈsu.əxan'),
    'a2-secret': ('Rùn-dìomhair', 'ˈr̪ˠuːnˈtʃiəvɪɾʲ'),
    'a2-see-you-later': ('Chì mi a-rithist thu', 'ˈçiː ˈmi əˈr̪ˠihɪʃtʃ ˈu'),
    'a2-selfie': ('Samhla-fèin', 'ˈsãũl̪ˠəˈfeːnʲ'),
    'a2-semester': ('Ràith-scoile', 'ˈr̪ˠaːˈskɔlʲə'),
    'a2-sentence': ('Seantans', 'ˈʃɛn̪ˠt̪ans'),
    'a2-serious': ('Stòlda', 'ˈst̪ɔːl̪ˠt̪ə'),
    'a2-several': ('Grunn', 'ˈkɾuːn̪ˠ'),
    'a2-sheep': ('Caora', 'ˈkʰɯːɾə'),
    'a2-shopping-cart': ('Cliabh-cuibhle', 'ˈkʲʰlʲiəvˈkʰuvlʲə'),
    'a2-short-height': ('Beag', 'ˈpek'),
    'a2-shower': ('Fras', 'ˈfɾas'),
    'a2-shy': ('Diùid', 'ˈtʃuːtʃ'),
    'a2-sidewalk': ('Cabhsair', 'ˈkʰavsɪɾʲ'),
    'a2-sightseeing': ('Coimhead-iongnaidh', 'ˈkʰɔvət̪ˈjuːŋni'),
    'a2-since': ('Bho', 'ˈvɔ'),
    'a2-single': ('Singilte', 'ˈʃiɲɪlʲtʃə'),
    'a2-skiing': ('Sleamhnachadh-sneachda', 'ˈʃlʲɛ̃ũnəxəɣˈʃnʲɛxkə'),
    'a2-slice': ('Sliseag', 'ˈʃlʲiʃak'),
    'a2-smart': ('Glic', 'ˈkʲlʲiʰkʲ'),
    'a2-snack': ('Greim bìdh', 'ˈkɾʲeim ˈpiː'),
    'a2-snake': ('Nathair', 'ˈn̪ˠahɪɾʲ'),
    'a2-soccer': ('Ball-coise', 'ˈpaul̪ˠˈkʰɔʃə'),
    'a2-social-media': ('Lìon-còmhraidh', 'ˈʎiənˈkʰɔ̃ːɾi'),
    'a2-sofa': ('Sòfa', 'ˈsɔːfə'),
    'a2-soft': ('Bog', 'ˈpɔk'),
    'a2-soldier': ('Saighdear', 'ˈsɤjtʃəɾ'),
    'a2-sorry-im-late': ('Tha mi duilich gu bheil mi fadalach', 'ˈha ˈmi ˈt̪ulʲɪç kə ˈvelʲ ˈmi ˈfat̪əl̪ˠəx'),
    'a2-sounds-good': ('Tha sin taghta', 'ˈha ˈʃinʲ ˈt̪ʰat̪ə'),
    'a2-souvenir': ('Cuimhneachan', 'ˈkʰũnʲəxan'),
    'a2-speaker': ('Adharc-gutha', 'ˈa.əɾkˈku.ə'),
    'a2-speed': ('Luaths', 'ˈl̪ˠuəs'),
    'a2-spinach': ('Bloinigean-gàrraidh', 'ˈpl̪ˠɔnʲɪkʲanˈkaːr̪ˠi'),
    'a2-sport': ('Spòrs', 'ˈspɔːɾs'),
    'a2-square-plaza': ('Ceàrnag', 'ˈkʲʰaːɾnak'),
    'a2-stadium': ('Raon-spòrs', 'ˈr̪ˠɯːnˈspɔːɾs'),
    'a2-stairs': ('Staidhre', 'ˈst̪ajɾʲə'),
    'a2-starter': ('Ciad chùrsa', 'ˈkʲʰiət̪ ˈxuːɾsə'),
    'a2-still': ('Fhathast', 'ˈhã.əst̪'),
    'a2-stomachache': ('Grèim-mionaich', 'ˈkɾʲeːmˈminɪç'),
    'a2-storm': ('Stoirm', 'ˈst̪ɔɾʲɔm'),
    'a2-story': ('Sceulachd', 'ˈskʲiəl̪ˠəxk'),
    'a2-stove': ('Stòbha', 'ˈst̪ɔːvə'),
    'a2-strange': ('Neònach', 'ˈɲɔːnəx'),
    'a2-strawberry': ('Sùbh-làir', 'ˈsuːvˈl̪ˠaːɾʲ'),
    'a2-stressed': ('Fo chuideam', 'fə ˈxutʃəm'),
    'a2-stubborn': ('Rag-mhuinealach', 'ˈr̪ˠakˈvɯnʲəl̪ˠəx'),
    'a2-subject': ('Cuspair', 'ˈkʰuspɪɾʲ'),
    'a2-subtitles': ('Sreathan-cainnte', 'ˈst̪ɾʲɛhanˈkʰaiɲtʃə'),
    'a2-suddenly': ('Gu h-obann', 'kə ˈhɔpən̪ˠ'),
    'a2-sure': ('Cinnteach', 'ˈkʲʰiːɲtʃəx'),
    'a2-surfing': ('Marcachd-thonn', 'ˈmaɾkəxkˈhɔun̪ˠ'),
    'a2-takeout': ('Biadh ri thoirt leat', 'ˈpiəɣ ɾʲə ˈhɔɾʲtʃ ˈʎɛʰt̪'),
    'a2-talkative': ('Bruidhneach', 'ˈpɾɯjnʲəx'),
    'a2-tall': ('Àrd', 'ˈaːɾt̪'),
    'a2-tax': ('Cìs', 'ˈkʲʰiːʃ'),
    'a2-teacher': ('Oide', 'ˈɔtʃə'),
    'a2-team': ('Scioba', 'ˈskʲipə'),
    'a2-teenager': ('Leth-inbheach', 'ˈʎehˈinʲivəx'),
    'a2-temperature': ('Tomhas-teasa', 'ˈt̪ʰɔvəsˈtʃʰɛsə'),
    'a2-tennis': ('Teanas', 'ˈtʃʰɛnəs'),
    'a2-that-makes-sense': ("Tha sin a' dèanamh ciall", 'ˈha ˈʃinʲ ə ˈtʃiənəv ˈkʲʰiəl̪ˠ'),
    'a2-thats-a-good-idea': ("Is e deagh bheachd a th' ann", 'ɪs ˈɛ ˈtʃɛ ˈvɛxk ə ˈhaun̪ˠ'),
    'a2-the-day-after-tomorrow': ('An-earar', 'ən̪ˠˈɛɾəɾ'),
    'a2-theater': ('Taigh-cluiche', 'ˈt̪ʰɤjˈkʰl̪ˠuçə'),
    'a2-thin': ('Tana', 'ˈt̪ʰanə'),
    'a2-this-month': ('Am mìos seo', 'əm ˈmiəs ˈʃɔ'),
    'a2-thunder': ('Tàirneanach', 'ˈt̪ʰaːɾʲnʲanəx'),
    'a2-tip': ('Bonn-boise', 'ˈpɔun̪ˠˈpɔʃə'),
    'a2-to-afford': ('Bi comasach air a phàigheadh', 'ˈpi ˈkʰɔməsəx ˈɛɾʲ ə ˈfaː.əɣ'),
    'a2-to-allow': ('Ceadachadh', 'ˈkʲʰɛt̪əxəɣ'),
    'a2-to-apologize': ('Gabh leisceul', 'ˈkav ˈʎeʃkʲiəl̪ˠ'),
    'a2-to-argue': ('Connsachadh', 'ˈkʰɔun̪ˠsəxəɣ'),
    'a2-to-bake': ('Fuine', 'ˈfɯnʲə'),
    'a2-to-be-afraid-of': ('Bi fo eagal ro', 'ˈpi fə ˈekəl̪ˠ ɾə'),
    'a2-to-be-born': ('Breith', 'ˈpɾʲeh'),
    'a2-to-be-honest': ('Leis an fhìrinn innse', 'ˈʎeʃ ən̪ˠ ˈiːɾʲɪɲ ˈiːɲʃə'),
    'a2-to-be-late': ('Bi fadalach', 'ˈpi ˈfat̪əl̪ˠəx'),
    'a2-to-become': ('Thig gu bhith', 'ˈhikʲ kə ˈvih'),
    'a2-to-believe': ('Creidsinn', 'ˈkʰɾʲetʃʃɪɲ'),
    'a2-to-boil': ('Goil', 'ˈkɔlʲ'),
    'a2-to-book': ('Glèidheadh', 'ˈkʲlʲeː.əɣ'),
    'a2-to-borrow': ('Faigh air iasad', 'ˈfɤj ˈɛɾʲ ˈiəsət̪'),
    'a2-to-break': ('Briseadh', 'ˈpɾʲiʃəɣ'),
    'a2-to-brush-ones-teeth': ('Glanadh nam fiaclan', 'ˈkl̪ˠanəɣ nə ˈviəʰkl̪ˠan'),
    'a2-to-build': ('Togail', 'ˈt̪ʰɔkɪlʲ'),
    'a2-to-calm-down': ('Socrachadh', 'ˈsɔʰkɾəxəɣ'),
    'a2-to-cancel': ('Cuir dheth', 'ˈkʰuɾʲ ˈjeh'),
    'a2-to-carry': ('Giùlan', 'ˈkʲuːl̪ˠan'),
    'a2-to-catch': ('Glacadh', 'ˈkl̪ˠaʰkəɣ'),
    'a2-to-celebrate': ('Comharrachadh', 'ˈkʰɔvər̪ˠəxəɣ'),
    'a2-to-change': ('Atharrachadh', 'ˈa.ər̪ˠəxəɣ'),
    'a2-to-chat': ('Dèan cabadaich', 'ˈtʃiən ˈkʰapət̪ɪç'),
    'a2-to-cheer-up': ('Tog cridhe', 'ˈt̪ʰɔk ˈkʰɾʲi.ə'),
    'a2-to-choose': ('Taghadh', 'ˈt̪ʰa.əɣ'),
    'a2-to-clean': ('Glanadh', 'ˈkl̪ˠanəɣ'),
    'a2-to-click': ('Bualadh-meòir', 'ˈpuəl̪ˠəɣˈmʲɔːɾʲ'),
    'a2-to-climb': ('Streap', 'ˈʃt̪ɾʲɛʰp'),
    'a2-to-commute': ('Siubhail gu obair', 'ˈʃuvɪlʲ kə ˈɔpɪɾʲ'),
    'a2-to-compare': ('Coimeas', 'ˈkʰɔməs'),
    'a2-to-complain': ('Gearan', 'ˈkʲɛɾan'),
    'a2-to-continue': ('Lean air', 'ˈʎɛn ˈɛɾʲ'),
    'a2-to-cook': ('Dèan còcaireachd', 'ˈtʃiən ˈkʰɔːʰkɪɾʲəxk'),
    'a2-to-correct': ('Ceartachadh', 'ˈkʲʰɛɾt̪əxəɣ'),
    'a2-to-cost': ('Cosc', 'ˈkʰɔsk'),
    'a2-to-cross': ('Rach tarsainn', 'ˈr̪ˠax ˈt̪ʰaɾsɪɲ'),
    'a2-to-cry': ('Caoineadh', 'ˈkʰɯːnʲəɣ'),
    'a2-to-cut': ('Gearradh', 'ˈkʲaːr̪ˠəɣ'),
    'a2-to-dance': ('Dannsadh', 'ˈt̪aun̪ˠsəɣ'),
    'a2-to-decide': ('Co-dhùnadh', 'kʰɔˈɣuːnəɣ'),
    'a2-to-deposit': ('Cuir a-steach', 'ˈkʰuɾʲ əˈʃtʃɛx'),
    'a2-to-describe': ('Thoir tuairisceul air', 'ˈhɔɾʲ ˈt̪ʰuəɾʲɪʃkʲiəl̪ˠ ˈɛɾʲ'),
    'a2-to-die': ('Bàsachadh', 'ˈpaːsəxəɣ'),
    'a2-to-discuss': ('Deasbad', 'ˈtʃɛspət̪'),
    'a2-to-download': ('Tarraing-a-nuas', 'ˈt̪ʰaːr̪ˠɪɲkʲˈaˈn̪ˠuəs'),
    'a2-to-draw': ('Tarraing dealbh', 'ˈt̪ʰaːr̪ˠɪɲkʲ ˈtʃal̪ˠav'),
    'a2-to-earn': ('Cosnadh', 'ˈkʰɔsnəɣ'),
    'a2-to-enjoy': ('Mealtainn', 'ˈmʲal̪ˠt̪ɪɲ'),
    'a2-to-exchange-money': ('Iomlaid', 'ˈiml̪ˠɪtʃ'),
    'a2-to-exercise': ('Dèan eacarsaich', 'ˈtʃiən ˈeʰkəɾsɪç'),
    'a2-to-explain': ('Mìneachadh', 'ˈmiːnʲəxəɣ'),
    'a2-to-fail-an-exam': ('Fàilligeadh', 'ˈfaːʎɪkʲəɣ'),
    'a2-to-fall': ('Tuiteam', 'ˈt̪ʰuʰtʃəm'),
    'a2-to-fall-asleep': ('Tuit na chadal', 'ˈt̪ʰuʰtʃ nə ˈxat̪əl̪ˠ'),
    'a2-to-fall-in-love': ('Tuit ann an gaol', 'ˈt̪ʰuʰtʃ ˈaun̪ˠ əŋ ˈkɯːl̪ˠ'),
    'a2-to-feel': ('Faireachdainn', 'ˈfaɾʲəxkɪɲ'),
    'a2-to-finish': ('Crìochnachadh', 'ˈkʰɾʲiəxnəxəɣ'),
    'a2-to-fly': ('Itealaich', 'ˈiʰtʃəl̪ˠɪç'),
    'a2-to-follow': ('Leantainn', 'ˈʎɛn̪ˠt̪ɪɲ'),
    'a2-to-forget': ('Dìochuimhneachadh', 'ˈtʃiəxɪ̃nʲəxəɣ'),
    'a2-to-fry': ('Frighigeadh', 'ˈfɾʲi.ɪkʲəɣ'),
    'a2-to-get-angry': ('Fàs feargach', 'ˈfaːs ˈfɛɾɛkəx'),
    'a2-to-get-dressed': ('Aodachadh', 'ˈɯːt̪əxəɣ'),
    'a2-to-get-married': ('Pòsadh', 'ˈpʰɔːsəɣ'),
    'a2-to-get-up': ('Èirigh', 'ˈeːɾʲi'),
    'a2-to-go-camping': ('Cadal-pubaill', 'ˈkʰat̪əl̪ˠˈpʰupɪʎ'),
    'a2-to-go-home': ('Rach dhachaigh', 'ˈr̪ˠax ˈɣaxɪ'),
    'a2-to-go-to-bed': ('Rach a laighe', 'ˈr̪ˠax ə ˈl̪ˠa.ə'),
    'a2-to-graduate': ('Ceumnachadh', 'ˈkʲʰiəmnəxəɣ'),
    'a2-to-grow': ('Fàs', 'ˈfaːs'),
    'a2-to-grow-up': ('Fàs suas', 'ˈfaːs ˈsuəs'),
    'a2-to-happen': ('Tachairt', 'ˈt̪ʰaxɪɾʲtʃ'),
    'a2-to-hate': ('Fuathachadh', 'ˈfuə.əxəɣ'),
    'a2-to-have-breakfast': ('Gabh biadh-maidne', 'ˈkav ˈpiəɣˈmatʃnʲə'),
    'a2-to-have-dinner': ('Gabh dìnnear', 'ˈkav ˈtʃiːɲəɾ'),
    'a2-to-have-lunch': ('Gabh lòn', 'ˈkav ˈl̪ˠɔːn'),
    'a2-to-hide': ('Falach', 'ˈfal̪ˠəx'),
    'a2-to-hike': ('Coiseachd nam beann', 'ˈkʰɔʃəxk nə ˈmʲaun̪ˠ'),
    'a2-to-hope': ('Bi an dòchas', 'ˈpi ən̪ˠ ˈt̪ɔːxəs'),
    'a2-to-hug': ('Teannaich ri uchd', 'ˈtʃʰɛn̪ˠɪç ɾʲə ˈuxk'),
    'a2-to-hurry': ('Greasad', 'ˈkɾʲɛsət̪'),
    'a2-to-invite': ('Thoir cuireadh', 'ˈhɔɾʲ ˈkʰuɾʲəɣ'),
    'a2-to-iron': ('Iarnaigeadh', 'ˈiəɾnɪkʲəɣ'),
    'a2-to-jump': ('Leum', 'ˈʎiəm'),
    'a2-to-keep': ('Cumail', 'ˈkʰumɪlʲ'),
    'a2-to-kiss': ('Pògadh', 'ˈpʰɔːkəɣ'),
    'a2-to-laugh': ('Dèan gàire', 'ˈtʃiən ˈkaːɾʲə'),
    'a2-to-lend': ('Thoir air iasad', 'ˈhɔɾʲ ˈɛɾʲ ˈiəsət̪'),
    'a2-to-lie': ('Innis breugan', 'ˈiɲɪʃ ˈpɾʲiəkan'),
    'a2-to-log-in': ('Foscladh-glais', 'ˈfɔskl̪ˠəɣˈkl̪ˠaʃ'),
    'a2-to-lose-a-game': ('Call', 'ˈkʰaul̪ˠ'),
    'a2-to-lose-an-object': ('Cuir air chall', 'ˈkʰuɾʲ ˈɛɾʲ ˈxaul̪ˠ'),
    'a2-to-mean': ('Ciallachadh', 'ˈkʲʰiəl̪ˠəxəɣ'),
    'a2-to-meet-someone-new': ('Cuir eòlas air', 'ˈkʰuɾʲ ˈjɔːl̪ˠəs ˈɛɾʲ'),
    'a2-to-meet-up': ('Coinneachadh', 'ˈkʰɔɲəxəɣ'),
    'a2-to-memorize': ('Cuir air mheomhair', 'ˈkʰuɾʲ ˈɛɾʲ ˈvʲɔvɪɾʲ'),
    'a2-to-miss-someone': ('Ionndrainn', 'ˈjuːn̪ˠt̪ɾɪɲ'),
    'a2-to-move-house': ('Imrich', 'ˈimɾʲɪç'),
    'a2-to-order-online': ('Òrdachadh', 'ˈɔːɾt̪əxəɣ'),
    'a2-to-owe': ('Bi fo fhiachan do', 'ˈpi fə ˈiəxan t̪ə'),
    'a2-to-paint': ('Peantadh', 'ˈpʰɛn̪ˠt̪əɣ'),
    'a2-to-pass-an-exam': ('Faigh troimhe', 'ˈfɤj ˈt̪ʰɾɔvə'),
    'a2-to-plan': ('Dealbhachadh', 'ˈtʃal̪ˠavəxəɣ'),
    'a2-to-post': ('Cuir suas', 'ˈkʰuɾʲ ˈsuəs'),
    'a2-to-postpone': ('Cuir dàil air', 'ˈkʰuɾʲ ˈt̪aːlʲ ˈɛɾʲ'),
    'a2-to-practice': ('Dèan cleachdadh', 'ˈtʃiən ˈkʲʰlʲɛxkəɣ'),
    'a2-to-prefer': ('Is fheàrr le', 'ɪs ˈjaːr̪ˠ lʲə'),
    'a2-to-print': ('Clò-bhualadh', 'ˈkʰl̪ˠɔːˈvuəl̪ˠəɣ'),
    'a2-to-promise': ('Gealltainn', 'ˈkʲaul̪ˠt̪ɪɲ'),
    'a2-to-pronounce': ('Fuaimneachadh', 'ˈfuəmnʲəxəɣ'),
    'a2-to-pull': ('Tarraing', 'ˈt̪ʰaːr̪ˠɪɲkʲ'),
    'a2-to-push': ('Putadh', 'ˈpʰuʰt̪əɣ'),
    'a2-to-receive': ('Faighinn', 'ˈfa.ɪɲ'),
    'a2-to-register': ('Clàradh', 'ˈkʰl̪ˠaːɾəɣ'),
    'a2-to-relax': ('Leig anail', 'ˈʎekʲ ˈanɪlʲ'),
    'a2-to-remember': ('Cuimhneachadh', 'ˈkʰũnʲəxəɣ'),
    'a2-to-repair': ('Càradh', 'ˈkʰaːɾəɣ'),
    'a2-to-rest': ('Gabh fois', 'ˈkav ˈfɔʃ'),
    'a2-to-return-an-item': ('Cuir air ais', 'ˈkʰuɾʲ ˈɛɾʲ ˈaʃ'),
    'a2-to-review': ('Ath-scrùdadh', 'ˈahˈskɾuːt̪əɣ'),
    'a2-to-save-money': ('Caomhnadh', 'ˈkʰɯ̃ːnəɣ'),
    'a2-to-search-online': ('Lorg-lìn', 'ˈl̪ˠɔɾɔkˈʎiːnʲ'),
    'a2-to-seem': ('Is coltach', 'ɪs ˈkʰɔl̪ˠt̪əx'),
    'a2-to-send': ('Cuir gu', 'ˈkʰuɾʲ kə'),
    'a2-to-share': ('Co-roinn', 'kʰɔˈr̪ˠɔiɲ'),
    'a2-to-shout': ('Èigheach', 'ˈeː.əx'),
    'a2-to-show': ('Sealltainn', 'ˈʃaul̪ˠt̪ɪɲ'),
    'a2-to-sing': ('Seinn', 'ˈʃeiɲ'),
    'a2-to-smell': ('Gabh fàileadh', 'ˈkav ˈfaːlʲəɣ'),
    'a2-to-smile': ('Dèan fiamh-ghàire', 'ˈtʃiən ˈfiəvˈɣaːɾʲə'),
    'a2-to-spell': ('Litreachadh', 'ˈʎiʰtʃɾʲəxəɣ'),
    'a2-to-spend-money': ('Caitheamh', 'ˈkʰa.əv'),
    'a2-to-start': ('Tòiseachadh', 'ˈt̪ʰɔːʃəxəɣ'),
    'a2-to-stay': ('Fuireach', 'ˈfuɾʲəx'),
    'a2-to-suggest': ('Moladh', 'ˈmɔl̪ˠəɣ'),
    'a2-to-swim': ('Snàmh', 'ˈsnaːv'),
    'a2-to-take-a-shower': ('Gabh fras', 'ˈkav ˈfɾas'),
    'a2-to-take-a-walk': ('Gabh cuairt', 'ˈkav ˈkʰuəɾʲtʃ'),
    'a2-to-take-care-of': ('Coimhead às dèidh', 'ˈkʰɔvət̪ ˈaːs ˈtʃeːj'),
    'a2-to-taste': ('Blasad', 'ˈpl̪ˠasət̪'),
    'a2-to-teach': ('Teagasc', 'ˈtʃʰekəsk'),
    'a2-to-thank': ('Thoir taing', 'ˈhɔɾʲ ˈt̪ʰaiɲkʲ'),
    'a2-to-throw': ('Tilgeil', 'ˈtʃʰilʲikʲɪlʲ'),
    'a2-to-tidy-up': ('Scioblachadh', 'ˈskʲipl̪ˠəxəɣ'),
    'a2-to-touch': ('Beantainn', 'ˈpɛn̪ˠt̪ɪɲ'),
    'a2-to-train': ('Trèanadh', 'ˈt̪ʰɾʲiənəɣ'),
    'a2-to-translate': ('Eadar-theangachadh', 'ˈɛt̪əɾˈhɛŋəxəɣ'),
    'a2-to-try': ('Feuchainn', 'ˈfiəxɪɲ'),
    'a2-to-try-on': ('Feuch air', 'ˈfiəx ˈɛɾʲ'),
    'a2-to-turn': ('Tionndadh', 'ˈtʃʰuːn̪ˠt̪əɣ'),
    'a2-to-turn-off': ('Cuir dheth', 'ˈkʰuɾʲ ˈjeh'),
    'a2-to-turn-on': ('Cuir air', 'ˈkʰuɾʲ ˈɛɾʲ'),
    'a2-to-type': ('Bualadh-litreach', 'ˈpuəl̪ˠəɣˈʎiʰtʃɾʲəx'),
    'a2-to-use': ('Cleachdadh', 'ˈkʲʰlʲɛxkəɣ'),
    'a2-to-visit': ('Tadhal', 'ˈt̪ʰa.əl̪ˠ'),
    'a2-to-wake-up': ('Dùscadh', 'ˈt̪uːskəɣ'),
    'a2-to-wash': ('Nighe', 'ˈɲi.ə'),
    'a2-to-wash-oneself': ('Nigh thu fhèin', 'ˈɲiː ˈu ˈheːnʲ'),
    'a2-to-watch-tv': ('Coimhead air scàthan-sceòil', 'ˈkʰɔvət̪ ˈɛɾʲ ˈskaːhanˈskʲɔːlʲ'),
    'a2-to-whisper': ('Cagarsaich', 'ˈkʰakəɾsɪç'),
    'a2-to-win': ('Buannachadh', 'ˈpuən̪ˠəxəɣ'),
    'a2-to-withdraw': ('Thoir a-mach', 'ˈhɔɾʲ əˈmax'),
    'a2-to-worry': ('Gabh dragh', 'ˈkav ˈt̪ɾa'),
    'a2-tomato': ('Ubhal-gaoil', 'ˈuvəl̪ˠˈkɯːlʲ'),
    'a2-too-big': ('Ro mhòr', 'ɾə ˈvoːɾ'),
    'a2-total': ('Iomlan', 'ˈiml̪ˠan'),
    'a2-tourist': ('Neach-turais', 'ˈɲɛxˈt̪ʰuɾɪʃ'),
    'a2-town-hall': ("Talla a' bhaile", 'ˈt̪ʰal̪ˠə ə ˈvalʲə'),
    'a2-traditional': ('Traidiseanta', 'ˈt̪ʰɾatʃɪʃan̪ˠt̪ə'),
    'a2-traffic': ('Tuil-charbad', 'ˈt̪ʰulʲˈxaɾapət̪'),
    'a2-traffic-light': ('Lòchran-stad', 'ˈl̪ˠɔːxɾanˈst̪at̪'),
    'a2-trash': ('Scudal', 'ˈskut̪əl̪ˠ'),
    'a2-truth': ('Fìrinn', 'ˈfiːɾʲɪɲ'),
    'a2-twice': ('Dà thuras', 'ˈt̪aː ˈhuɾəs'),
    'a2-twins': ('Leth-aon', 'ˈʎehˈɯːn'),
    'a2-unemployed': ('Gun obair', 'kən̪ˠ ˈɔpɪɾʲ'),
    'a2-university': ('Oilthigh', 'ˈɔlʲhi'),
    'a2-until': ('Gu ruige', 'kə ˈr̪ˠɯkʲə'),
    'a2-update': ('Ùrachadh', 'ˈuːɾəxəɣ'),
    'a2-usually': ('Mar as àbhaist', 'ˈmaɾ ˈas ˈaːvɪʃtʃ'),
    'a2-vacuum-cleaner': ('Craos-stùir', 'ˈkʰɾɯːsˈst̪uːɾʲ'),
    'a2-vegetarian': ('Luibh-itheach', 'ˈl̪ˠuˈi.əx'),
    'a2-video': ('Dealbh-gluasaid', 'ˈtʃal̪ˠavˈkl̪ˠuəsɪtʃ'),
    'a2-video-call': ('Gairm-scàthain', 'ˈkaɾʲamˈskaːhɪnʲ'),
    'a2-video-game': ('Cluiche-scàile', 'ˈkʰl̪ˠuçəˈskaːlʲə'),
    'a2-volleyball': ('Cluiche-lìn', 'ˈkʰl̪ˠuçəˈʎiːnʲ'),
    'a2-volume': ('Neart fuaime', 'ˈɲɛɾt̪ ˈfuəmə'),
    'a2-waiter': ('Frithealaiche', 'ˈfɾʲi.əl̪ˠɪçə'),
    'a2-washing-machine': ('Muileann-nighe', 'ˈmulʲən̪ˠˈɲi.ə'),
    'a2-watch-out': ('Thoir an aire!', 'ˈhɔɾʲ ən̪ˠ ˈaɾʲə'),
    'a2-watermelon': ('Meal-bhuc uisce', 'ˈmʲal̪ˠˈvuʰk ˈɯʃkʲə'),
    'a2-wave': ('Tonn', 'ˈt̪ʰɔun̪ˠ'),
    'a2-website': ('Àros-lìn', 'ˈaːɾəsˈʎiːnʲ'),
    'a2-wedding': ('Banais', 'ˈpanɪʃ'),
    'a2-weight': ('Cuideam', 'ˈkʰutʃəm'),
    'a2-wet': ('Fliuch', 'ˈflʲux'),
    'a2-what-a-pity': ('Is truagh sin', 'ɪs ˈt̪ʰɾuə ˈʃinʲ'),
    'a2-what-do-you-think': ('Dè do bheachd?', 'ˈtʃeː t̪ə ˈvɛxk'),
    'a2-what-time-is-it': ('Dè an uair a tha e?', 'ˈtʃeː ən̪ˠ ˈuəɾʲ ə ˈha ˈɛ'),
    'a2-whats-your-phone-number': ('Dè an àireamh guth-sreinge agad?', 'ˈtʃeː ən̪ˠ ˈaːɾʲəv ˈkuhˈst̪ɾʲeɲə ˈakət̪'),
    'a2-where-is-the-pharmacy': ("Càite a bheil a' bhùth-chungaidh?", 'ˈkʰaːʰtʃə ə ˈvelʲ ə ˈvuːˈxuŋi'),
    'a2-where-is-the-restroom': ('Càite a bheil an taigh-beag?', 'ˈkʰaːʰtʃə ə ˈvelʲ ən̪ˠ ˈd̪ɤjˈpek'),
    'a2-where-is-the-train-station': ("Càite a bheil stad a' charbaid-iarainn?", 'ˈkʰaːʰtʃə ə ˈvelʲ ˈst̪at̪ ə ˈxaɾapɪtʃˈiəɾɪɲ'),
    'a2-wi-fi': ('Lìon-gaoithe', 'ˈʎiənˈkɯː.ə'),
    'a2-wide': ('Leathann', 'ˈʎɛ.ən̪ˠ'),
    'a2-word': ('Facal', 'ˈfaʰkəl̪ˠ'),
    'a2-writer': ('Scrìobhadair', 'ˈskɾʲiəvət̪ɪɾʲ'),
    'a2-wrong': ('Ceàrr', 'ˈkʲʰaːr̪ˠ'),
    'a2-yoga': ('Cleas-anail', 'ˈkʲʰlʲɛsˈanɪlʲ'),
}
