# -*- coding: utf-8 -*-
LANG = 'ind'
STORIES = {
    'st-b1-01': {
        'title': 'Kereta yang Terlambat',
        'paras': [
            'Rosetta mendarat dekat sebuah kota pasar kecil. Ana dan Marco turun dari kapal untuk pergi ke stasiun kereta. Mereka ingin membeli tiket ke kota.',
            'Di stasiun, banyak orang menunggu di peron. Seorang perempuan memberi tahu mereka bahwa kereta terlambat. "Ada masalah dengan relnya," katanya.',
            'Ana melihat jam. Saat itu sudah pukul sepuluh, padahal kereta mereka seharusnya berangkat pukul sembilan tiga puluh. Marco duduk di bangku dan menghela napas.',
            'Seorang pria di sebelah mereka membuka tasnya dan mengeluarkan roti. Ia menawarkan sepotong kepada Ana dan Marco. "Kalian boleh menunggu di sini bersama saya," katanya sambil tersenyum.',
            'Mereka mengobrol dengan pria itu tentang keluarganya dan pekerjaannya. Ia bekerja di pasar dan menjual sayuran setiap hari. Ana menceritakan tentang Rosetta dan perjalanan mereka.',
            'Akhirnya, setelah satu jam, kereta pun tiba. Semua orang cepat-cepat berdiri dan berjalan menuju pintu. Ana dan Marco berterima kasih kepada pria itu atas rotinya.',
            'Di dalam kereta, Ana memandang ladang-ladang dari jendela. Ia senang mereka telah bertemu orang asing yang ramah. Marco berkata bahwa kadang-kadang kereta yang terlambat membawa kejutan yang menyenangkan.',
        ],
    },
    'st-b1-02': {
        'title': 'Makan Malam bersama Keluarga Yuki',
        'paras': [
            'Awak Rosetta mengunjungi sebuah desa yang tenang selama beberapa hari. Yuki mengajak Sam untuk makan malam bersama keluarganya. Sam merasa gugup karena ia belum terlalu mengenal mereka.',
            'Ibu Yuki membuka pintu dan tersenyum hangat. "Selamat datang," katanya. "Kami senang kamu datang." Rumah itu berbau sup dan roti segar.',
            'Di meja makan, ayah Yuki bertanya banyak hal kepada Sam tentang Rosetta. Sam menjelaskan bahwa kapal itu mengunjungi banyak kota dan membantu orang-orang. Adik laki-laki Yuki mendengarkan dengan mata terbelalak.',
            'Mereka makan sup, nasi, dan sayuran bersama-sama. Sam mencoba masakan baru yang belum pernah ia makan sebelumnya. Ia sangat menyukainya dan minta tambah.',
            'Setelah makan malam, ibu Yuki menyajikan kue untuk pencuci mulut. Ia berkata itu adalah resep istimewa dari ibunya sendiri. Semua orang mendapat sepotong besar dan bercerita tentang kenangan lama.',
            'Sam berterima kasih kepada keluarga itu atas malam yang indah. Ia berkata ia sudah merasa seperti bagian dari keluarga itu. Ayah Yuki menjabat tangannya dan mengajaknya datang lagi.',
            'Dalam perjalanan pulang ke kapal, Sam berkata kepada Yuki bahwa ia sangat menyukai makanannya. Ia berkata keluarga di mana pun sama saja: hangat dan murah hati. Yuki tersenyum dan setuju dengannya.',
        ],
    },
    'st-b2-01': {
        'title': 'Wawancara Kerja',
        'paras': [
            'Seandainya Rosetta tidak perlu diperbaiki, Marco tidak akan pernah tinggal cukup lama untuk melamar pekerjaan di kota pelabuhan itu. Ia melihat pengumuman lowongan montir dan memutuskan untuk mencoba peruntungannya. Ia penasaran bagaimana orang-orang di darat menyelesaikan masalah tanpa peralatan canggih milik kapal.',
            'Pewawancaranya, seorang perempuan tinggi bernama Ana, bertanya mengapa ia menginginkan pekerjaan itu. Marco menjelaskan bahwa ia sudah bertahun-tahun memperbaiki mesin dalam kondisi sulit, sering kali dengan suku cadang terbatas. Ia menambahkan bahwa ia lebih memilih mempelajari sistem baru dengan sungguh-sungguh daripada berpura-pura sudah tahu segalanya.',
            'Ana tampak terkesan, meski ia menunjukkan bahwa peralatan bengkel itu jauh lebih tua daripada apa pun yang biasa Marco gunakan. "Kalau kamu bekerja di sini," katanya, "kamu harus melupakan beberapa kebiasaan lamamu." Marco mengakui bahwa penyesuaian itu mungkin membutuhkan kesabaran, tetapi ia bersedia mencobanya.',
            'Ia kemudian bertanya apa yang akan Marco lakukan jika sebuah mesin rusak di tengah pekerjaan tanpa ada suku cadang pengganti. Marco berpikir sejenak dan berkata ia akan berimprovisasi dengan bahan apa pun yang tersedia, seperti yang pernah ia lakukan di atas kapal saat badai tahun lalu. Ana mengangguk perlahan, jelas sedang mempertimbangkan jawabannya.',
            'Menjelang akhir wawancara, Ana bertanya apakah Marco bisa berkomitmen untuk tetap tinggal bahkan setelah Rosetta akhirnya berangkat. Marco ragu-ragu, mengakui bahwa ia tidak yakin berapa lama ia akan tinggal di kota itu. Menurutnya, kejujuran lebih penting daripada mengatakan apa yang ingin didengar Ana.',
            'Ana berterima kasih atas kejujurannya dan berkata ia akan membicarakannya dengan rekan-rekannya sebelum mengambil keputusan. Ia menyebutkan bahwa kebanyakan pelamar melebih-lebihkan pengalaman mereka, dan sikap terus terang Marco cukup menonjol. Marco meninggalkan bengkel itu tanpa yakin apakah ia telah membantu atau merugikan peluangnya sendiri.',
            'Beberapa hari kemudian, sebuah pesan datang mengundangnya kembali untuk menjalani masa percobaan selama seminggu. Marco menyadari bahwa kejujurannya, bukan semata-mata keterampilan teknisnya, yang meyakinkan mereka untuk memberinya kesempatan. Ia bertanya-tanya apakah pada akhirnya ia harus memilih antara bengkel itu dan bintang-bintang.',
        ],
    },
    'st-b2-02': {
        'title': 'Ruang Tunggu',
        'paras': [
            'Ketika demam Sam tidak kunjung reda, dokter kapal menyarankan agar ia pergi ke rumah sakit setempat, karena peralatan di kota itu bisa melakukan pemeriksaan yang tidak dimiliki Rosetta. Yuki ikut bersamanya, sebagian karena khawatir dan sebagian karena penasaran bagaimana rumah sakit itu bekerja. Tak satu pun dari mereka menyangka ruang tunggunya akan seramai itu.',
            'Mereka duduk di antara seorang pria tua yang membaca koran dan seorang ibu muda yang berusaha menenangkan anaknya yang menangis. Seandainya Yuki tahu penantiannya akan selama itu, ia pasti membawa sesuatu untuk dibaca. Namun, ia hanya menatap jam dan mendengarkan percakapan lirih di sekelilingnya.',
            'Setelah hampir dua jam, seorang perawat memanggil nama Sam dan membawanya ke ruang pemeriksaan. Yuki menawarkan diri untuk ikut, tetapi perawat menjelaskan bahwa biasanya hanya satu orang yang diperbolehkan masuk. Sam sempat menggenggam tangan Yuki sebelum menghilang di balik pintu.',
            'Sendirian di ruang tunggu, Yuki mulai mengobrol dengan pria tua di sampingnya. Ia berkata bahwa ia datang ke rumah sakit setiap bulan untuk pemeriksaan rutin, dan para petugas selalu memperlakukannya dengan baik meskipun mereka sangat sibuk. Yuki merasa kesabarannya luar biasa, mengingat betapa lamanya semua orang harus menunggu.',
            'Ketika Sam akhirnya kembali, ia menjelaskan bahwa dokter tidak menemukan apa pun yang serius, hanya infeksi ringan yang akan sembuh dalam seminggu dengan antibiotik. Yuki merasakan kelegaan yang bahkan tidak ia sadari sedang ditahannya. Ia menggoda Sam dengan lembut karena telah membuatnya begitu khawatir.',
            'Saat mereka berjalan keluar, Sam mengakui bahwa ia sebenarnya lebih takut daripada yang ia tunjukkan, karena ia jarang sakit selama di kapal. Yuki berkata itulah tepatnya alasan ia bersikeras untuk ikut, agar Sam tidak perlu menghadapinya sendirian. Sam berterima kasih, sedikit malu karena betapa berartinya kehadiran Yuki baginya.',
            'Dalam perjalanan kembali ke Rosetta, mereka berpapasan lagi dengan pria tua itu, kini berjalan pelan menuju halte bus. Yuki melambai, dan pria itu membalas lambaian dengan senyum lelah namun tulus. Sam berkomentar bahwa rumah sakit, dengan segala penantian dan kekhawatirannya, tampaknya justru memunculkan kebaikan yang tenang dalam diri orang-orang.',
        ],
    },
    'st-c1-01': {
        'title': 'Perselisihan di Kafe',
        'paras': [
            'Kafe itu telah menjadi semacam tempat favorit bagi awak Rosetta selama mereka tinggal, meja-meja kayunya yang usang dan riuh percakapan yang tak pernah henti menawarkan kontras yang menyenangkan dari koridor kapal yang serba steril. Marco dan Ana baru saja duduk di sudut favorit mereka ketika sebuah perdebatan di meja sebelah menarik perhatian mereka. Dua pelanggan tetap sedang berdebat, dengan semangat yang nyata, tentang apakah peraturan pasar baru di kota itu akan membantu atau justru menghancurkan para pedagang lokal.',
            'Seorang pria, seorang penjual buah, bersikeras bahwa peraturan itu adalah upaya terselubung untuk menguntungkan pedagang besar yang lebih berduit, dengan mengorbankan kios-kios kecil seperti miliknya. Lawan bicaranya, yang menjalankan toko buku sederhana tidak jauh dari sana, membalas bahwa tanpa pengawasan tertentu, pasar telah menjadi kacau, dengan harga yang tidak menentu dan para pedagang saling menjatuhkan harga hingga ke titik kehancuran. Tak satu pun dari mereka tampak bersedia mengalah sedikit pun.',
            'Ana, yang selalu penasaran, condong ke arah Marco dan mengakui bahwa ia merasa terombang-ambing di antara kedua posisi itu. Marco menunjukkan bahwa kedua pria itu sama-sama memiliki keluhan yang sah, meskipun solusi yang mereka usulkan sangat berbeda arah. Ia menyadari bahwa perselisihan semacam ini jarang memiliki penjahat yang jelas; lebih sering, dua kekhawatiran yang sama-sama masuk akal saling berbenturan.',
            'Dibesarkan hatinya oleh secangkir kopi kedua, si penjual buah meninggikan suaranya, menuduh dewan kota telah tunduk pada tekanan dari para pedagang yang lebih kaya. Pemilik toko buku, terlihat jengkel, membalas bahwa tuduhan semacam itu tidak berdasar dan bahwa ia pun akan kehilangan pelanggan jika peraturan diperketat. Perdebatan mereka menjadi cukup panas hingga pengunjung lain mulai melirik ke arah mereka.',
            'Merasakan ketegangan yang hampir meledak, pemilik kafe turun tangan, meletakkan sepiring kue kering di antara kedua pria itu dengan komentar jenaka bahwa perdebatan berjalan lebih baik dengan perut yang kenyang. Gestur itu mencairkan permusuhan yang memuncak, dan kedua pria itu, dengan agak malu-malu, menerima tawaran perdamaian tersebut. Ana berbisik kepada Marco bahwa ia mengagumi betapa cekatannya pemilik kafe itu meredakan situasi.',
            'Setelah ketegangan langsung mereda, percakapan bergeser ke titik temu: keduanya sepakat bahwa dewan kota telah gagal berkonsultasi dengan para pedagang biasa sebelum menyusun peraturan tersebut. Marco merasa pergeseran ini cukup mengungkapkan sesuatu, karena hal itu menunjukkan bahwa perselisihan sesungguhnya bukan terutama soal kebijakan itu sendiri, melainkan soal siapa yang punya suara dalam membentuknya. Ana mengangguk, berkomentar bahwa pengucilan, lebih daripada perbedaan pendapat, cenderung menumbuhkan kebencian.',
            'Ketika kedua pria itu akhirnya berpisah dengan sikap ramah, Marco merenung bahwa awak Rosetta begitu sering datang dengan harapan menemukan kisah sederhana tentang keharmonisan atau konflik, hanya untuk menemukan kebenaran yang lebih rumit: sebagian besar perselisihan berakar pada ketakutan akan diabaikan. Ana setuju, menambahkan bahwa mungkin hal paling berguna yang bisa mereka laporkan kembali ke kapal bukanlah putusan tentang siapa yang benar, melainkan cerita tentang betapa cepatnya kepahitan bisa mencair begitu orang merasa didengarkan. Mereka meninggalkan kafe itu sambil sudah menantikan kunjungan berikutnya.',
        ],
    },
    'st-c2-01': {
        'title': 'Di Antara Dua Keberangkatan',
        'paras': [
            'Menjelang selesainya perbaikan Rosetta, Sam telah tumbuh rasa sayang terhadap kepala stasiun, seorang pria pendiam bernama Marco yang kekasarannya, ia sadari kemudian, menyembunyikan kesetiaan yang begitu teliti pada ketepatan waktu hingga hampir terasa seperti upacara. Percakapan mereka, yang semula canggung, telah mengendap menjadi ritme yang nyaman, tiap pertukaran kata diwarnai humor kering yang hanya bisa lahir dari rasa saling menghormati. Justru keakraban inilah, lebih daripada kerusakan mekanis yang masih tersisa, yang membuat Sam mencari-cari alasan untuk berlama-lama di dekat peron.',
            'Pada pagi yang seharusnya menjadi pagi terakhirnya di kota itu, Sam mendapati Marco tampak tidak biasa, dengan tekun menggosok sebuah lempengan kuningan yang memperingati pendirian stasiun itu puluhan tahun silam. Ketika Sam menyinggung kesentimentalan yang tidak seperti biasanya itu, Marco mengakui, dengan keengganan yang jelas, bahwa ia merasa tidak nyaman dengan perpisahan, betapa pun sering pekerjaannya memaksanya untuk menghadapinya. Itulah, ia mengaku, satu-satunya sisi pekerjaannya yang tak pernah bisa ia terima sepenuhnya.',
            'Sam, yang mengira perkenalan mereka terlalu singkat untuk memantik keterusterangan semacam itu, mendapati dirinya tersentuh secara tak terduga oleh pengakuan itu. Ia berpendapat bahwa mungkin ketidaknyamanan itu bukan berasal dari perpisahan itu sendiri, melainkan dari ketidaksetaraan yang melekat padanya: sang musafir melangkah maju menuju hal baru, sementara yang tertinggal kembali ke rutinitas, betapa pun bermartabatnya rutinitas itu. Marco mengakui pendapat itu tidak tanpa dasar, meski ia sedikit tersinggung karena dianggap semata-mata sebagai "yang tertinggal".',
            'Percakapan mereka terputus oleh interkom stasiun, yang berderak mengumumkan bahwa kereta ke utara akan tertunda lebih dari empat puluh menit akibat gangguan sinyal. Marco, tampak lega dengan penundaan itu, bergumam bahwa nasib rupanya telah bersekongkol untuk memperpanjang percakapan mereka sedikit lebih lama. Sam tertawa dan menyarankan agar mereka memanfaatkan sebaik-baiknya jeda tak terduga ini.',
            'Mereka mundur ke kantor kecil stasiun, tempat Marco mengeluarkan sepoci teh yang ia simpan, ia akui dengan agak malu-malu, khusus untuk kesempatan semacam ini. Selama setengah jam berikutnya, obrolan mereka mengalir dari urusan keberangkatan Rosetta yang sepele hingga ke wilayah yang lebih menyelidik: apakah hidup yang dihabiskan menjaga satu titik yang tetap bisa pernah menandingi hidup yang dihabiskan dalam gerak abadi, atau apakah keduanya hanya menukar satu bentuk kegelisahan dengan bentuk lainnya. Tak satu pun dari mereka mengaku telah menemukan jawaban pasti.',
            'Ketika kereta yang tertunda itu akhirnya mendecit memasuki stasiun, Marco mengantar Sam ke peron dengan sikap resmi yang, secara paradoks, justru melunakkan alih-alih mengeraskan suasana. Ia mengulurkan tangan, lalu, tampaknya berlawanan dengan penilaiannya sendiri, malah menawarkan pelukan yang canggung, bergumam sesuatu tentang membuat pengecualian. Sam meyakinkannya bahwa pengecualian itu berbalas dan sepenuhnya ia sambut.',
            'Ketika Rosetta lepas landas pada malam harinya, Sam mendapati dirinya menoleh ke arah stasiun lebih lama daripada yang sebenarnya dibutuhkan momen itu, merenungkan kembali ucapan Marco sebelumnya tentang ketidaksetaraan. Ia menduga pria tua itu, dengan caranya sendiri yang berjaga-jaga, telah mengungkapkan sesuatu yang belum pernah bisa Sam ucapkan sendiri dengan kata-kata: bahwa setiap perpisahan meminta satu orang untuk membawa kenangan itu maju, dan meninggalkan yang lain untuk menjaga tempat terjadinya kenangan itu. Itu, pikirnya, adalah pembagian tugas yang cukup adil, selama tak satu pun dari kedua pihak melupakan peran yang lainnya.',
        ],
    },
}
