# -*- coding: utf-8 -*-
# Diaithìris, the tongue of Diaithìr: written by tools/import_diaithiris.py from the Diaithìris dictionary.
# The reading line is the pronunciation in IPA.
LANG = 'gr'
WORDS = {
    'b2-3d-printing': ('Togailsnàithne', 'ˈt̪ʰɔkɪlʲˈsnaːnʲə'),
    'b2-abruptly': ('Gu hobann', 'kə ˈhɔpən̪ˠ'),
    'b2-abstract': ('Beachdail', 'ˈpɛxkɪlʲ'),
    'b2-absurd': ('Neochiallach', 'ˈɲɔˈçiəl̪ˠəx'),
    'b2-accurate': ('Neomhearachdach', 'ˈɲɔˈvɛɾəxkəx'),
    'b2-acute': ('Geur', 'ˈkʲiəɾ'),
    'b2-addiction': ('Tràilleachd', 'ˈt̪ʰɾaːʎəxk'),
    'b2-adequate': ('Cuimseach', 'ˈkʰumʃəx'),
    'b2-adoption': ('Uchdmhacachd', 'ˈuxkˈvaʰkəxk'),
    'b2-affection': ('Spèis', 'ˈspeːʃ'),
    'b2-agenda': ('Sreathcomhairle', 'ˈst̪ɾʲɛhˈkʰɔvɪɾʲlʲə'),
    'b2-agony': ('Cràdh', 'ˈkʰɾaːɣ'),
    'b2-ahead-of-schedule': ('Ron àm', 'ˈr̪ˠɔn ˈaːm'),
    'b2-alarming': ('Eagalach', 'ˈekəl̪ˠəx'),
    'b2-algorithm': ('Riancunntais', 'ˈr̪ˠiənˈkʰuːn̪ˠt̪ɪʃ'),
    'b2-alibi': ('Fianaisàite', 'ˈfiənɪʃˈaːʰtʃə'),
    'b2-all-things-considered': ("A' toirt a huile càil san àireamh", 'ə ˈt̪ʰɔɾʲtʃ ə ˈhulʲə ˈkʰaːlʲ sən̪ˠ ˈaːɾʲəv'),
    'b2-altitude': ('Àirde', 'ˈaːɾʲtʃə'),
    'b2-altogether': ('Uile gu lèir', 'ˈulʲə kə ˈʎeːɾʲ'),
    'b2-ambiguous': ('Dàsheaghach', 'ˈt̪aːˈhɛ.əx'),
    'b2-ambition': ('Glòirmhiann', 'ˈkl̪ˠɔːɾʲˈviən̪ˠ'),
    'b2-ambulance': ('Carbadeiridinn', 'ˈkʰaɾapət̪ˈeɾʲɪtʃɪɲ'),
    'b2-analysis': ('Anailis', 'ˈanɪlʲɪʃ'),
    'b2-ancestor': ('Sinnsear', 'ˈʃiːɲʃəɾ'),
    'b2-anesthesia': ('Suainlannsa', 'ˈsuənʲˈl̪ˠaun̪ˠsə'),
    'b2-ankle': ('Adhbrann', 'ˈapɾən̪ˠ'),
    'b2-announcement': ('Brath', 'ˈpɾah'),
    'b2-antibiotic': ('Nimhbhiastan', 'ˈɲivˈviəst̪an'),
    'b2-anxiety': ('Iomagain', 'ˈiməkɪnʲ'),
    'b2-apparent': ('Air choltas', 'ˈɛɾʲ ˈxɔl̪ˠt̪əs'),
    'b2-appeal-legal': ('Aththagradh', 'ˈahˈhakɾəɣ'),
    'b2-applause': ('Bualadhbhas', 'ˈpuəl̪ˠəɣˈvas'),
    'b2-apprehension': ('Iomagain', 'ˈiməkɪnʲ'),
    'b2-approach': ('Dòighobrach', 'ˈtoːjˈɔpɾəx'),
    'b2-appropriate': ('Iomchaidh', 'ˈimxi'),
    'b2-arbitrary': ('Air thuaiream', 'ˈɛɾʲ ˈhuəɾʲəm'),
    'b2-archery': ('Boghadaireachd', 'ˈpɔ.ət̪ɪɾʲəxk'),
    'b2-around-the-clock': ('Latha is oidhche', 'ˈl̪ˠa.ə ɪs ˈɤiçə'),
    'b2-artery': ('Artaire', 'ˈaɾt̪ɪɾʲə'),
    'b2-artificial-intelligence': ('Cialliarainn', 'ˈkʲʰiəl̪ˠˈiəɾɪɲ'),
    'b2-as-a-matter-of-fact': ('Leis an fhìrinn innse', 'ˈʎeʃ ən̪ˠ ˈiːɾʲɪɲ ˈiːɲʃə'),
    'b2-as-far-as-im-concerned': ('Air mo shon fhìn', 'ˈɛɾʲ mə ˈhɔn ˈiːnʲ'),
    'b2-aspect': ('Taobh', 'ˈt̪ʰɯːv'),
    'b2-assault': ('Ionnsaigh', 'ˈjuːn̪ˠsi'),
    'b2-asthma': ('Cuing', 'ˈkʰuːiɲkʲ'),
    'b2-at-the-same-time': ('Aig an aon àm', 'ˈekʲ ən̪ˠ ˈɯːn ˈaːm'),
    'b2-atom': ('Dadam', 'ˈt̪at̪əm'),
    'b2-automation': ('Obairgunlàimh', 'ˈɔpɪɾʲˈkunˈl̪ˠaːv'),
    'b2-awe': ('Urram', 'ˈuːr̪ˠəm'),
    'b2-backstage': ('Air cùl an àrdùrlair', 'ˈɛɾʲ ˈkʰuːl̪ˠ ən̪ˠ ˈaːɾt̪ˈuːɾl̪ˠɪɾʲ'),
    'b2-bacteria': ('Beathaicheandìomhair', 'ˈpɛhɪçanˈtʃiəvɪɾʲ'),
    'b2-bail': ('Urras', 'ˈuːr̪ˠəs'),
    'b2-bankruptcy': ('Briseadhcreideis', 'ˈpɾʲiʃəɣˈkʰɾʲetʃɪʃ'),
    'b2-barely': ('Air èiginn', 'ˈɛɾʲ ˈeːkʲɪɲ'),
    'b2-basil': ('Basail', 'ˈpasɪlʲ'),
    'b2-batter': ('Taois shilteach', 'ˈt̪ʰɯːʃ ˈhilʲtʃəx'),
    'b2-bay': ('Bàgh', 'ˈpaː'),
    'b2-beam': ('Sail', 'ˈsalʲ'),
    'b2-behavior': ('Giùlan', 'ˈkʲuːl̪ˠan'),
    'b2-behind-schedule': ('Air dheireadh', 'ˈɛɾʲ ˈjeɾʲəɣ'),
    'b2-belt': ('Crios', 'ˈkʰɾʲis'),
    'b2-benchmark': ('Slattomhais', 'ˈsl̪ˠaʰt̪ˈt̪ʰɔvɪʃ'),
    'b2-bias': ('Claonadh', 'ˈkʰl̪ˠɯːnəɣ'),
    'b2-biased': ('Claonbhreitheach', 'ˈkʰl̪ˠɯːnˈvɾʲe.əx'),
    'b2-bid': ('Tagradh', 'ˈt̪ʰakɾəɣ'),
    'b2-bike-lane': ('Slighecuibhle', 'ˈʃlʲi.əˈkʰuvlʲə'),
    'b2-bill-proposed-law': ('Bile', 'ˈpilʲə'),
    'b2-biodiversity': ('Pailteasghnè', 'ˈpʰalʲtʃəsˈjnʲeː'),
    'b2-birdwatching': ('Coimhead eun', 'ˈkʰɔvət̪ ˈiən'),
    'b2-bitterness': ('Searbhachd', 'ˈʃɛɾɛvəxk'),
    'b2-blood-test': ('Deuchainnfala', 'ˈtʃiəxɪɲˈfal̪ˠə'),
    'b2-blueprint': ('Dealbhsaoir', 'ˈtʃal̪ˠavˈsɯːɾʲ'),
    'b2-blunt-direct': ('Dìreach', 'ˈtʃiːɾʲəx'),
    'b2-bone': ('Cnàimh', 'ˈkʰn̪ˠaːv'),
    'b2-boots': ('Bòtannan', 'ˈpɔːʰt̪ən̪ˠan'),
    'b2-boredom': ('Leamhachas', 'ˈʎɛvəxəs'),
    'b2-bowling': ('Bòbhladh', 'ˈpɔːvl̪ˠəɣ'),
    'b2-boxing': ('Bocsadh', 'ˈpɔʰksəɣ'),
    'b2-brain': ('Eanchainn', 'ˈɛnɛxɪɲ'),
    'b2-branch-office': ('Meur', 'ˈmiəɾ'),
    'b2-breadwinner': ('Cosnaiche', 'ˈkʰɔsnɪçə'),
    'b2-breakthrough': ('Adhartas mòr', 'ˈa.əɾt̪əs ˈmoːɾ'),
    'b2-bribery': ('Brìbeadh', 'ˈpɾʲiːpəɣ'),
    'b2-broadly-speaking': ("A' bruidhinn gu farsaing", 'ə ˈpɾu.ɪɲ kə ˈfaɾsɪɲkʲ'),
    'b2-broth': ('Brot', 'ˈpɾɔʰt̪'),
    'b2-budget-deficit': ('Tollionmhais', 'ˈt̪ʰɔul̪ˠˈinivɪʃ'),
    'b2-bug-software': ('Cnuimhrainn', 'ˈkʰn̪ˠuvˈr̪ˠaiɲ'),
    'b2-burglary': ('Briseadh asteach', 'ˈpɾʲiʃəɣ əˈʃtʃɛx'),
    'b2-button': ('Putan', 'ˈpʰuʰt̪an'),
    'b2-by-accident': ('Gun fhiosta', 'kən̪ˠ ˈist̪ə'),
    'b2-by-all-means': ('Gun teagamh sam bith', 'kən̪ˠ ˈtʃʰekəv ˈsaum ˈpih'),
    'b2-by-and-large': ('Sa mhòrchuid', 'sə ˈvoːɾˈxutʃ'),
    'b2-calendar': ('Mìosachan', 'ˈmiəsəxan'),
    'b2-campaign': ('Iomairt', 'ˈimɪɾʲtʃ'),
    'b2-campaign-game': ('Iomairt', 'ˈimɪɾʲtʃ'),
    'b2-cancer': ('Aillse', 'ˈaiʎʃə'),
    'b2-candidate': ('Tagraiche', 'ˈt̪ʰakɾɪçə'),
    'b2-canvas': ('Canabhas', 'ˈkʰanəvəs'),
    'b2-canyon': ('Mòrghleann', 'ˈmoːɾˈjlʲaun̪ˠ'),
    'b2-carbon-footprint': ('Lorgdeataich', 'ˈl̪ˠɔɾɔkˈtʃɛʰt̪ɪç'),
    'b2-caregiver': ('Neachcùraim', 'ˈɲɛxˈkʰuːɾɪm'),
    'b2-casual-wear': ('Aodach cumanta', 'ˈɯːt̪əx ˈkʰuman̪ˠt̪ə'),
    'b2-cave': ('Uamh', 'ˈuəv'),
    'b2-cell-biology': ('Bolgbeatha', 'ˈpɔl̪ˠɔkˈpɛ.ə'),
    'b2-cheek': ('Gruaidh', 'ˈkɾuəj'),
    'b2-chemical': ('Dùilmheascaichte', 'ˈt̪uːlʲˈvɛskɪçtʃə'),
    'b2-chin': ('Smiogaid', 'ˈsmikɪtʃ'),
    'b2-choir': ('Còisir', 'ˈkʰɔːʃɪɾʲ'),
    'b2-chronic': ('Leantainneach', 'ˈʎɛn̪ˠt̪ɪɲəx'),
    'b2-cinnamon': ('Caineal', 'ˈkʰanʲəl̪ˠ'),
    'b2-client': ('Neachdèiligidh', 'ˈɲɛxˈtʃeːlʲɪkʲi'),
    'b2-cliff': ('Bearradh', 'ˈpʲaːr̪ˠəɣ'),
    'b2-coalition': ('Cobhanntachd', 'kʰɔˈvaun̪ˠt̪əxk'),
    'b2-coast': ('Oirthir', 'ˈɔɾʲhɪɾʲ'),
    'b2-coherent': ('Ciallach', 'ˈkʲʰiəl̪ˠəx'),
    'b2-collar': ('Coilear', 'ˈkʰɔlʲəɾ'),
    'b2-collectible': ('Rudcruinneachaidh', 'ˈr̪ˠut̪ˈkʰɾɯɲəxi'),
    'b2-comfort-zone': ('Cròsocair', 'ˈkʰɾɔːˈsɔʰkɪɾʲ'),
    'b2-compassion': ('Truas', 'ˈt̪ʰɾuəs'),
    'b2-compelling': ('Dearbhach', 'ˈtʃɛɾɛvəx'),
    'b2-competitor': ('Farpaiseach', 'ˈfaɾpɪʃəx'),
    'b2-complacency': ('Toileachasfhèin', 'ˈt̪ʰɔlʲəxəsˈheːnʲ'),
    'b2-component': ('Cophàirt', 'kʰɔˈfaːɾʲtʃ'),
    'b2-compost': ('Todhar', 'ˈt̪ʰɔ.əɾ'),
    'b2-comprehensive': ('Coileanta', 'ˈkʰɔlʲan̪ˠt̪ə'),
    'b2-compromise-noun': ('Corèiteachadh', 'kʰɔˈr̪ˠeːʰtʃəxəɣ'),
    'b2-concept': ('Bunbheachd', 'ˈpunˈvɛxk'),
    'b2-concrete': ('Nitheil', 'ˈɲihɪlʲ'),
    'b2-confession': ('Faoisid', 'ˈfɯːʃɪtʃ'),
    'b2-congestion': ('Dùmhlachdrathaid', 'ˈt̪ũːl̪ˠəxkˈr̪ˠahɪtʃ'),
    'b2-conscience': ('Cogais', 'ˈkʰɔkɪʃ'),
    'b2-consequence': ('Buil', 'ˈpulʲ'),
    'b2-conservation': ('Glèidhteachas', 'ˈkʲlʲeːjʰtʃəxəs'),
    'b2-considerably': ('Gu ìre mhòr', 'kə ˈiːɾʲə ˈvoːɾ'),
    'b2-consistent': ('Cunbhalach', 'ˈkʰunuvəl̪ˠəx'),
    'b2-construction-site': ('Làrachtogail', 'ˈl̪ˠaːɾəxˈt̪ʰɔkɪlʲ'),
    'b2-contagious': ('Gabhaltach', 'ˈkavəl̪ˠt̪əx'),
    'b2-contempt': ('Tàir', 'ˈt̪ʰaːɾʲ'),
    'b2-contentment': ('Toileachasinntinn', 'ˈt̪ʰɔlʲəxəsˈiːɲtʃɪɲ'),
    'b2-context': ('Cotheacsa', 'kʰɔˈheʰksə'),
    'b2-continent': ('Mòrthìr', 'ˈmoːɾˈhiːɾʲ'),
    'b2-contractor': ('Cunnradair', 'ˈkʰuːn̪ˠɾət̪ɪɾʲ'),
    'b2-contradictory': ('An aghaidh a chèile', 'ən̪ˠ ˈa.i ə ˈçeːlʲə'),
    'b2-controversial': ('Connspaideach', 'ˈkʰɔun̪ˠspɪtʃəx'),
    'b2-convicted': ('Dìte', 'ˈtʃiːʰtʃə'),
    'b2-corruption': ('Coirbeachd', 'ˈkʰɔɾʲɔpəxk'),
    'b2-cosplay': ('Riochduirsceil', 'ˈr̪ˠixkˈuɾʲʃkʲɪlʲ'),
    'b2-costume': ('Culaidh', 'ˈkʰul̪ˠi'),
    'b2-courage': ('Misneachd', 'ˈmiʃnʲəxk'),
    'b2-court': ('Cùirt', 'ˈkʰuːɾʲtʃ'),
    'b2-cowardice': ('Gealtachd', 'ˈkʲal̪ˠt̪əxk'),
    'b2-craft': ('Ceàird', 'ˈkʲʰiɾʲtʃ'),
    'b2-crane': ('Cranntogail', 'ˈkʰɾaun̪ˠˈt̪ʰɔkɪlʲ'),
    'b2-credible': ('Creideasach', 'ˈkʰɾʲetʃəsəx'),
    'b2-crispy': ('Brisc', 'ˈpɾʲiʃkʲ'),
    'b2-criterion': ('Slattomhais', 'ˈsl̪ˠaʰt̪ˈt̪ʰɔvɪʃ'),
    'b2-crucial': ('Deatamach', 'ˈtʃɛʰt̪əməx'),
    'b2-crust': ('Rùsc', 'ˈr̪ˠuːsk'),
    'b2-current-water': ('Sruth', 'ˈst̪ɾuh'),
    'b2-custody-police': ('Grèimfaire', 'ˈkɾʲeːmˈfaɾʲə'),
    'b2-cybersecurity': ('Dìonlìn', 'ˈtʃiənˈʎiːnʲ'),
    'b2-data': ('Cunntasfiosa', 'ˈkʰuːn̪ˠt̪əsˈfisə'),
    'b2-database': ('Cistefiosa', 'ˈkʲʰiʃtʃəˈfisə'),
    'b2-daylight-saving-time': ('Goiduaire', 'ˈkɔtʃˈuəɾʲə'),
    'b2-deadline-construction': ('Ceannama togail', 'ˈkʲʰaun̪ˠˈamə ˈt̪ʰɔkɪlʲ'),
    'b2-defense-legal': ('Dìon', 'ˈtʃiən'),
    'b2-deforestation': ('Dìchoillteachadh', 'ˈtʃiːˈxɔiʎtʃəxəɣ'),
    'b2-deliberate': ('Rùnaichte', 'ˈr̪ˠuːnɪçtʃə'),
    'b2-deliberately': ("A dh'aon ghnothach", 'ə ˈɣɯːn ˈɣnɔ.əx'),
    'b2-demolition': ('Leagail', 'ˈʎekɪlʲ'),
    'b2-denial': ('Àicheadh', 'ˈaːçəɣ'),
    'b2-department': ('Roinn', 'ˈr̪ˠɔiɲ'),
    'b2-depression': ('Trominntinn', 'ˈt̪ʰɾɔumˈiːɲtʃɪɲ'),
    'b2-descendant': ('Sliochd', 'ˈʃlʲixk'),
    'b2-detective': ('Lorgaire', 'ˈl̪ˠɔɾɔkɪɾʲə'),
    'b2-detergent': ('Stuthnighe', 'ˈst̪uhˈɲi.ə'),
    'b2-diabetes': ('Tinneas an tsiùcair', 'ˈtʃʰiɲəs ən̪ˠ ˈtʃuːʰkɪɾʲ'),
    'b2-diagnosis': ('Breithneachadh', 'ˈpɾʲenʲəxəɣ'),
    'b2-dice': ('Dìsne', 'ˈtʃiːʃnʲə'),
    'b2-dignity': ('Urram', 'ˈuːr̪ˠəm'),
    'b2-dimension': ('Taobhtomhais', 'ˈt̪ʰɯːvˈt̪ʰɔvɪʃ'),
    'b2-director-film': ('Stiùirichescàile', 'ˈʃtʃuːɾʲɪçəˈskaːlʲə'),
    'b2-disability': ('Ciorram', 'ˈkʲʰiːr̪ˠəm'),
    'b2-disbelief': ('Mìchreideas', 'ˈmiːˈxɾʲetʃəs'),
    'b2-discrimination': ('Lethbhreith', 'ˈʎehˈvɾʲeh'),
    'b2-disgust': ('Screamh', 'ˈskɾʲɛv'),
    'b2-distinct': ('Eadardhealaichte', 'ˈɛt̪əɾˈjal̪ˠɪçtʃə'),
    'b2-district': ('Scìre', 'ˈskʲiːɾʲə'),
    'b2-diverse': ('Eugsamhail', 'ˈiəksəvɪlʲ'),
    'b2-dominant': ('Ceannsalach', 'ˈkʲʰaun̪ˠsəl̪ˠəx'),
    'b2-dose': ('Dòs', 'ˈt̪ɔːs'),
    'b2-dough': ('Taois', 'ˈt̪ʰɯːʃ'),
    'b2-downtime': ('Ùinestad', 'ˈuːnʲəˈst̪at̪'),
    'b2-dread': ('Oillt', 'ˈɔiʎtʃ'),
    'b2-drywall': ('Clàraoil', 'ˈkʰl̪ˠaːɾˈɯːlʲ'),
    'b2-dune': ('Dùngainmhich', 'ˈt̪uːnˈkanʲavɪç'),
    'b2-duty': ('Dleastanas', 'ˈtʃlʲɛst̪anəs'),
    'b2-eagerness': ('Dealas', 'ˈtʃal̪ˠəs'),
    'b2-economic-growth': ('Fàsionmhais', 'ˈfaːsˈinivɪʃ'),
    'b2-ecosystem': ('Lìonbeatha', 'ˈʎiənˈpɛ.ə'),
    'b2-ecstasy': ('Àrdaoibhneas', 'ˈaːɾt̪ˈɯːvnʲəs'),
    'b2-efficiency': ('Èifeachdas', 'ˈeːfəxkəs'),
    'b2-efficient': ('Èifeachdach', 'ˈeːfəxkəx'),
    'b2-elaborate': ('Toinnte', 'ˈt̪ʰɔiɲtʃə'),
    'b2-elbow': ('Uileann', 'ˈulʲən̪ˠ'),
    'b2-elderly': ('Seann daoine', 'ˈʃaun̪ˠ ˈt̪ɯːnʲə'),
    'b2-element': ('Eileamaid', 'ˈelʲəmɪtʃ'),
    'b2-emissions': ('Scaoileadh', 'ˈskɯːlʲəɣ'),
    'b2-empathy-deep': ('Cofhaireachdainn dhomhainn', 'kʰɔˈaɾʲəxkɪɲ ˈɣɔvɪɲ'),
    'b2-encryption': ('Glasrùin', 'ˈkl̪ˠasˈr̪ˠuːnʲ'),
    'b2-endangered-species': ('Gnè ann an cunnart', 'ˈkʲɲeː ˈaun̪ˠ əŋ ˈɡun̪ˠəɾt̪'),
    'b2-engagement': ('Gealladhpòsaidh', 'ˈkʲɛl̪ˠəɣˈpʰɔːsi'),
    'b2-entirely': ('Gu hiomlan', 'kə ˈhiml̪ˠan'),
    'b2-entrepreneur': ('Sealgairbuannachd', 'ˈʃal̪ˠakɪɾʲˈpuən̪ˠəxk'),
    'b2-environmentalist': ('Buachaillefearainn', 'ˈpuəxɪʎəˈfɛɾɪɲ'),
    'b2-equality': ('Coionannachd', 'kʰɔˈinən̪ˠəxk'),
    'b2-equator': ('Criosmeadhain', 'ˈkʰɾʲisˈmɛ.ɪnʲ'),
    'b2-esports': ('Còmhragscàile', 'ˈkʰɔ̃ːɾakˈskaːlʲə'),
    'b2-euphoria': ('Mòraoibhneas', 'ˈmoːɾˈɯːvnʲəs'),
    'b2-every-now-and-then': ('Bho àm gu àm', 'ˈvɔ ˈaːm kə ˈaːm'),
    'b2-evolution': ('Caochladhghinealach', 'ˈkʰɯːxl̪ˠəɣˈjinʲəl̪ˠəx'),
    'b2-exception': ('Eisceachd', 'ˈeʃkʲəxk'),
    'b2-exhibition': ('Taisbeanadh', 'ˈt̪ʰaʃpanəɣ'),
    'b2-experiment': ('Deuchainn', 'ˈtʃiəxɪɲ'),
    'b2-explicit': ('Follaiseach', 'ˈfɔl̪ˠɪʃəx'),
    'b2-export': ('Àsmhalairt', 'ˈaːsˈval̪ˠɪɾʲtʃ'),
    'b2-extinction': ('Dol à bith', 'ˈt̪ɔl̪ˠ ˈaː ˈpih'),
    'b2-extrovert': ('Duine foscailte', 'ˈt̪ɯnʲə ˈfɔskɪlʲtʃə'),
    'b2-eyebrow': ('Mala', 'ˈmal̪ˠə'),
    'b2-eyelash': ('Fabhra', 'ˈfavɾə'),
    'b2-fabric': ('Stuth', 'ˈst̪uh'),
    'b2-factor': ('Feart', 'ˈfɛɾt̪'),
    'b2-fairly': ('Gu math', 'kə ˈma'),
    'b2-fairness': ('Cothromachd', 'ˈkʰɔɾəməxk'),
    'b2-famine': ('Gorta', 'ˈkɔɾt̪ə'),
    'b2-feasible': ('Sodhèanta', 'ˈsɔˈjiən̪ˠt̪ə'),
    'b2-feature': ('Buadh', 'ˈpuəɣ'),
    'b2-festival': ('Fèis', 'ˈfeːʃ'),
    'b2-fiance': ('Feargealladhpòsaidh', 'ˈfɛɾˈkʲɛl̪ˠəɣˈpʰɔːsi'),
    'b2-flawed': ('Easbhaidheach', 'ˈɛsvɪ.əx'),
    'b2-folklore': ('Beulaithris', 'ˈpiəl̪ˠˈaɾʲɪʃ'),
    'b2-fondness': ('Bàidh', 'ˈpaːj'),
    'b2-for-the-sake-of': ('Air scàth', 'ˈɛɾʲ ˈskaː'),
    'b2-for-the-time-being': ('Airson andràsta', 'ˈaɾsən ən̪ˠˈt̪ɾaːst̪ə'),
    'b2-forehead': ('Bathais', 'ˈpahɪʃ'),
    'b2-forgiveness': ('Mathanas', 'ˈmahanəs'),
    'b2-formal-wear': ('Aodach foirmeil', 'ˈɯːt̪əx ˈfɔɾʲɔmɪlʲ'),
    'b2-fossil-fuels': ('Connadhtalmhainn', 'ˈkʰɔn̪ˠəɣˈt̪ʰal̪ˠavɪɲ'),
    'b2-foundation-building': ('Bunait', 'ˈpunɪʰtʃ'),
    'b2-framework': ('Frèamobrach', 'ˈfɾʲiəmˈɔpɾəx'),
    'b2-fraud': ('Foill', 'ˈfɔiʎ'),
    'b2-function': ('Gnìomh', 'ˈkʲɲiəv'),
    'b2-fundamental': ('Bunaiteach', 'ˈpunɪʰtʃəx'),
    'b2-gallery': ('Gailearaidh', 'ˈkalʲəɾi'),
    'b2-gardening': ('Gàirnealaireachd', 'ˈkaːɾʲnʲəl̪ˠɪɾʲəxk'),
    'b2-gene': ('Sìoldùthchais', 'ˈʃiəl̪ˠˈt̪uːxɪʃ'),
    'b2-generosity': ('Fialaidheachd', 'ˈfiəl̪ˠɪ.əxk'),
    'b2-genre': ('Gnè', 'ˈkʲɲeː'),
    'b2-gentrification': ('Fuadachbeartais', 'ˈfuət̪əxˈpɛɾt̪ɪʃ'),
    'b2-genuine': ('Fìrinneach', 'ˈfiːɾʲɪɲəx'),
    'b2-ginger': ('Dinnsear', 'ˈtʃiːɲʃəɾ'),
    'b2-glacier': ('Eighshruth', 'ˈejˈhɾuh'),
    'b2-global-warming': ('Fiabhrastalmhainn', 'ˈfiəvɾəsˈt̪ʰal̪ˠavɪɲ'),
    'b2-glue': ('Glaodh', 'ˈkl̪ˠɯːɣ'),
    'b2-godparent': ('Pàrantbaistidh', 'ˈpʰaːɾan̪ˠt̪ˈpaʃtʃi'),
    'b2-gradually': ('Mean air mhean', 'ˈmɛn ˈɛɾʲ ˈvɛn'),
    'b2-gratitude': ('Taingealachd', 'ˈt̪ʰaɲəl̪ˠəxk'),
    'b2-gravity': ('Iomtharraing', 'ˈjuːmˈhaːr̪ˠɪɲkʲ'),
    'b2-greasy': ('Crèiseach', 'ˈkʰɾʲeːʃəx'),
    'b2-greed': ('Sannt', 'ˈsaun̪ˠt̪'),
    'b2-green-space': ('Àite uaine', 'ˈaːʰtʃə ˈuənʲə'),
    'b2-greenhouse-gas': ('Ceòteasa', 'ˈkʲʰɔːˈtʃʰɛsə'),
    'b2-grief': ('Bròn', 'ˈpɾɔːn'),
    'b2-guardian': ('Neachgleidhidh', 'ˈɲɛxˈkʲlʲe.i'),
    'b2-guilt': ('Ciont', 'ˈkʲʰin̪ˠt̪'),
    'b2-habitat': ('Àrainn', 'ˈaːɾɪɲ'),
    'b2-hanger': ('Crochadair', 'ˈkʰɾɔxət̪ɪɾʲ'),
    'b2-harbor': ('Cala', 'ˈkʰal̪ˠə'),
    'b2-hardly': ('Is gann', 'ɪs ˈkaun̪ˠ'),
    'b2-hardware': ('Colanniarainn', 'ˈkʰɔl̪ˠən̪ˠˈiəɾɪɲ'),
    'b2-having-said-that': ('Às dèidh sin a ràdh', 'ˈaːs ˈtʃeːj ˈʃinʲ ə ˈr̪ˠaːɣ'),
    'b2-headquarters': ('Prìomh oifis', 'ˈpʰɾʲiəv ˈɔfɪʃ'),
    'b2-heart-attack': ('Grèimcridhe', 'ˈkɾʲeːmˈkʰɾʲi.ə'),
    'b2-heel': ('Sàil', 'ˈsaːlʲ'),
    'b2-hem': ('Fàitheam', 'ˈfaː.əm'),
    'b2-hemisphere': ('Lethchruinne', 'ˈʎehˈxɾɯɲə'),
    'b2-herb': ('Luibh', 'ˈl̪ˠu'),
    'b2-heritage': ('Dualchas', 'ˈt̪uəl̪ˠxəs'),
    'b2-high-heels': ('Brògan àrdshàileach', 'ˈpɾɔːkan ˈaːɾt̪ˈhaːlʲəx'),
    'b2-high-rise': ('Togalach àrd', 'ˈt̪ʰɔkəl̪ˠəx ˈaːɾt̪'),
    'b2-hobbyist': ('Neachcurseachad', 'ˈɲɛxˈkʰuɾˈʃɛxət̪'),
    'b2-homelessness': ('Ciondachaigh', 'ˈkʲʰinˈt̪axi'),
    'b2-honesty': ('Onarachd', 'ˈɔnəɾəxk'),
    'b2-honeymoon': ('Mìos nam pòg', 'ˈmiəs nəm ˈbɔːk'),
    'b2-horizon': ('Fàire', 'ˈfaːɾʲə'),
    'b2-household': ('Muinntirtaighe', 'ˈmuːiɲtʃɪɾʲˈt̪ʰa.ə'),
    'b2-housing-crisis': ('Èiginn taigheadais', 'ˈeːkʲɪɲ ˈt̪ʰa.ət̪ɪʃ'),
    'b2-humiliation': ('Irioslachadh', 'ˈiɾʲəsl̪ˠəxəɣ'),
    'b2-humility': ('Irioslachd', 'ˈiɾʲəsl̪ˠəxk'),
    'b2-hypocrisy': ('Cealgaireachd', 'ˈkʲʰal̪ˠakɪɾʲəxk'),
    'b2-hypothesis': ('Beachdbharail', 'ˈpɛxkˈvaɾɪlʲ'),
    'b2-iceberg': ('Beinndeighe', 'ˈpeiɲˈtʃe.ə'),
    'b2-if-anything': ('Ma tha dad ann', 'mə ˈha ˈt̪at̪ ˈaun̪ˠ'),
    'b2-immune-system': ('Fairefala', 'ˈfaɾʲəˈfal̪ˠə'),
    'b2-impact': ('Buaidh', 'ˈpuəj'),
    'b2-implication': ('Iarmhairt', 'ˈiəɾvɪɾʲtʃ'),
    'b2-implicit': ('Fillte', 'ˈfiːʎtʃə'),
    'b2-import': ('Inmhalairt', 'ˈinʲˈval̪ˠɪɾʲtʃ'),
    'b2-in-a-nutshell': ('Ann am beagan fhaclan', 'ˈaun̪ˠ əm ˈpekan ˈaʰkl̪ˠan'),
    'b2-in-advance': ('Rolàimh', 'ˈr̪ˠɔˈl̪ˠaːv'),
    'b2-in-any-case': ('Codhiù', 'kʰɔˈjuː'),
    'b2-in-hindsight': ('Le fios às dèidh làimh', 'lʲə ˈfis ˈaːs ˈtʃeːj ˈl̪ˠaːv'),
    'b2-in-laws': ('Cleamhnaich', 'ˈkʲʰlʲɛ̃ũnɪç'),
    'b2-in-terms-of': ('A thaobh', 'ə ˈhɯːv'),
    'b2-in-the-meantime': ('Anns an eadaràm', 'ˈaun̪ˠs ən̪ˠ ˈɛt̪əɾˈaːm'),
    'b2-in-the-nick-of-time': ('Dìreach ann an àm', 'ˈtʃiːɾʲəx ˈaun̪ˠ ən̪ˠ ˈaːm'),
    'b2-increasingly': ("Nas motha 's nas motha", 'ˈn̪ˠas ˈmɔ.ə s ˈn̪ˠas ˈmɔ.ə'),
    'b2-indignation': ('Tàmailt', 'ˈt̪ʰaːmɪlʲtʃ'),
    'b2-inequality': ('Neoionannachd', 'ˈɲɔˈinən̪ˠəxk'),
    'b2-inevitable': ('Dosheachanta', 'ˈt̪ɔˈhɛxan̪ˠt̪ə'),
    'b2-infection': ('Gabhaltas', 'ˈkavəl̪ˠt̪əs'),
    'b2-infrastructure': ('Druimdùthcha', 'ˈt̪ɾuːimˈt̪uːxə'),
    'b2-inheritance': ('Oighreachd', 'ˈɤiɾʲəxk'),
    'b2-innocent': ('Neochiontach', 'ˈɲɔˈçin̪ˠt̪əx'),
    'b2-innovation': ('Ùrghnàthachadh', 'ˈuːɾˈɣnaː.əxəɣ'),
    'b2-innovative': ('Ùrghnàthach', 'ˈuːɾˈɣnaː.əx'),
    'b2-inspection': ('Scrùdadh', 'ˈskɾuːt̪əɣ'),
    'b2-instinct': ('Dùchas', 'ˈt̪uːxəs'),
    'b2-insulation': ('Cochallblàiths', 'ˈkʰɔxəl̪ˠˈpl̪ˠaːʃ'),
    'b2-integrity': ('Ionracas', 'ˈinɾəʰkəs'),
    'b2-intensive-care': ('Caithrisleighis', 'ˈkʰaɾʲɪʃˈʎe.ɪʃ'),
    'b2-interest-rate': ('Ìre rèidh', 'ˈiːɾʲə ˈr̪ˠeːj'),
    'b2-intestine': ('Caolan', 'ˈkʰɯːl̪ˠan'),
    'b2-introvert': ('Duine dùinte', 'ˈt̪ɯnʲə ˈt̪uːɲtʃə'),
    'b2-investigation': ('Rannsachadh', 'ˈr̪ˠaun̪ˠsəxəɣ'),
    'b2-investor': ('Cuiricheòir', 'ˈkʰuɾʲɪçəˈɔːɾʲ'),
    'b2-irrelevant': ('Neobhuntainneach', 'ˈɲɔˈvun̪ˠt̪ɪɲəx'),
    'b2-jaw': ('Giall', 'ˈkʲiəl̪ˠ'),
    'b2-joint': ('Alt', 'ˈal̪ˠt̪'),
    'b2-judge': ('Britheamh', 'ˈpɾʲi.əv'),
    'b2-juicy': ('Sùghmhor', 'ˈsuːvəɾ'),
    'b2-jungle': ('Dlùthchoille', 'ˈt̪l̪ˠuːˈxɔʎə'),
    'b2-jury': ('Diùraidh', 'ˈtʃuːɾi'),
    'b2-karaoke': ('Ceòlfalamh', 'ˈkʲʰɔːl̪ˠˈfal̪ˠəv'),
    'b2-kayaking': ('Iomramhcuraich', 'ˈimɾəvˈkʰuɾɪç'),
    'b2-kidnapping': ('Fuadachdaoine', 'ˈfuət̪əxˈt̪ɯːnʲə'),
    'b2-kidney': ('Dubhag', 'ˈt̪uvak'),
    'b2-kinship': ('Dàimh', 'ˈt̪aːv'),
    'b2-knitting': ('Fighe', 'ˈfi.ə'),
    'b2-laboratory': ('Obairlann', 'ˈɔpɪɾʲˈl̪ˠaun̪ˠ'),
    'b2-landfill': ('Làrachscudail', 'ˈl̪ˠaːɾəxˈskut̪ɪlʲ'),
    'b2-landscape-painting': ('Dealbhtìre', 'ˈtʃal̪ˠavˈtʃʰiːɾʲə'),
    'b2-last-minute': ("Aig a' mhionaid mu dheireadh", 'ˈekʲ ə ˈvinɪtʃ mə ˈjeɾʲəɣ'),
    'b2-latitude': ('Domhanleud', 'ˈt̪ɔvanˈʎiət̪'),
    'b2-lawsuit': ('Cùislagha', 'ˈkʰuːʃˈl̪ˠa.ə'),
    'b2-layoff': ('Cur à dreuchd', 'ˈkʰuɾ ˈaː ˈt̪ɾʲiəxk'),
    'b2-legend': ('Uirsceul', 'ˈuɾʲʃkʲiəl̪ˠ'),
    'b2-legislation': ('Reachdas', 'ˈr̪ˠɛxkəs'),
    'b2-legitimate': ('Dligheach', 'ˈtʃlʲi.əx'),
    'b2-leisure': ('Fois', 'ˈfɔʃ'),
    'b2-lining': ('Lìnigeadh', 'ˈʎiːnʲɪkʲəɣ'),
    'b2-lip': ('Bile', 'ˈpilʲə'),
    'b2-literature': ('Litreachas', 'ˈʎiʰtʃɾʲəxəs'),
    'b2-liver': ('Grùthan', 'ˈkɾuːhan'),
    'b2-long-term': ('Fadùine', 'ˈfat̪ˈuːnʲə'),
    'b2-longing': ('Ionndrainn', 'ˈjuːn̪ˠt̪ɾɪɲ'),
    'b2-lung': ('Scamhan', 'ˈskavan'),
    'b2-majority': ('Mòrchuid', 'ˈmoːɾˈxutʃ'),
    'b2-martial-arts': ('Ealainshabaid', 'ˈjal̪ˠɪnʲˈhapɪtʃ'),
    'b2-masterpiece': ('Sàrobair', 'ˈsaːɾˈɔpɪɾʲ'),
    'b2-mayor': ('Àrdbhàillidh', 'ˈaːɾt̪ˈvaːʎi'),
    'b2-melancholy': ('Lionndubh', 'ˈʎuːn̪ˠˈt̪u'),
    'b2-merely': ('Amhàin', 'əˈvaːnʲ'),
    'b2-merger': ('Pòsadhmalairt', 'ˈpʰɔːsəɣˈmal̪ˠɪɾʲtʃ'),
    'b2-metaphor': ('Meafar', 'ˈmɛfəɾ'),
    'b2-method': ('Dòigh', 'ˈtoːj'),
    'b2-milestone-project': ('Clachmhìle', 'ˈkʰl̪ˠaxˈviːlʲə'),
    'b2-mindfulness': ('Faireuaire', 'ˈfaɾʲəˈuəɾʲə'),
    'b2-miniature-figure': ('Meanbhfhigear', 'ˈmɛnɛvˈikʲəɾ'),
    'b2-minister': ('Ministear', 'ˈminʲɪʃtʃəɾ'),
    'b2-minority': ('Mionchuid', 'ˈminˈxutʃ'),
    'b2-minutes-of-a-meeting': ('Cuimhnecoinneimh', 'ˈkʰũnʲəˈkʰɔɲɪv'),
    'b2-molecule': ('Snaidhmdhadam', 'ˈsnajmˈɣat̪əm'),
    'b2-monopoly': ('Lèirshealbh', 'ˈʎeːɾʲˈhal̪ˠav'),
    'b2-morality': ('Moraltachd', 'ˈmɔɾəl̪ˠt̪əxk'),
    'b2-more-or-less': ('An ìre mhath', 'ən̪ˠ ˈiːɾʲə ˈva'),
    'b2-mostly': ('Sa mhòrchuid', 'sə ˈvoːɾˈxutʃ'),
    'b2-mother-in-law': ('Màthairchèile', 'ˈmaːhɪɾʲˈçeːlʲə'),
    'b2-motivation': ('Togradh', 'ˈt̪ʰɔkɾəɣ'),
    'b2-murder': ('Murt', 'ˈmuɾt̪'),
    'b2-mutual': ('Dàthaobhach', 'ˈt̪aːˈhɯːvəx'),
    'b2-myth': ('Miotas', 'ˈmiʰt̪əs'),
    'b2-national-debt': ('Fiachanrìoghachd', 'ˈfiəxanˈr̪ˠiə.əxk'),
    'b2-natural-resources': ('Stòras nàdarra', 'ˈst̪ɔːɾəs ˈn̪ˠaːt̪ər̪ˠə'),
    'b2-needless-to-say': ('Chan fheum mi ràdh', 'xan ˈiəm ˈmi ˈr̪ˠaːɣ'),
    'b2-negotiation': ('Barganachadh', 'ˈpaɾakanəxəɣ'),
    'b2-nerve': ('Nearbh', 'ˈɲɛɾɛv'),
    'b2-neutral': ('Neophàirteach', 'ˈɲɔˈfaːɾʲtʃəx'),
    'b2-nonetheless': ("A dh'aindeoin sin", 'ə ˈɣaɲtʃɪnʲ ˈʃinʲ'),
    'b2-norm': ('Àbhaist', 'ˈaːvɪʃtʃ'),
    'b2-notable': ('Sònraichte', 'ˈsɔːnɾɪçtʃə'),
    'b2-notion': ('Smaoin', 'ˈsmɯːnʲ'),
    'b2-oasis': ('Fuaranfàsaich', 'ˈfuəɾanˈfaːsɪç'),
    'b2-objection': ('Gearan', 'ˈkʲɛɾan'),
    'b2-obsession': ('Beòghlacadh', 'ˈpʲɔːˈɣl̪ˠaʰkəɣ'),
    'b2-obsolete': ('Bho fheum', 'ˈvɔ ˈiəm'),
    'b2-on-purpose': ("A dh'aon ghnothach", 'ə ˈɣɯːn ˈɣnɔ.əx'),
    'b2-on-second-thought': ('Air athsmaoineachadh', 'ˈɛɾʲ ˈahˈsmɯːnʲəxəɣ'),
    'b2-on-the-dot': ("Air a' bhuille", 'ˈɛɾʲ ə ˈvuʎə'),
    'b2-on-the-whole': ('Anns an fharsaingeachd', 'ˈaun̪ˠs ən̪ˠ ˈaɾsɪɲəxk'),
    'b2-opera': ('Opara', 'ˈɔʰpəɾə'),
    'b2-opposition': ('Luchddùbhlain', 'ˈl̪ˠuxkˈt̪uːvl̪ˠɪnʲ'),
    'b2-orbit': ('Reulchuairt', 'ˈr̪ˠiəl̪ˠˈxuəɾʲtʃ'),
    'b2-orchestra': ('Orcastra', 'ˈɔɾkəst̪ɾə'),
    'b2-organic-farming': ('Àiteachadhtodhair', 'ˈaːʰtʃəxəɣˈt̪ʰɔ.ɪɾʲ'),
    'b2-orphan': ('Dìlleachdan', 'ˈtʃiːʎəxkan'),
    'b2-outcome': ('Toradh', 'ˈt̪ʰɔɾəɣ'),
    'b2-outstanding': ('Barraichte', 'ˈpaːr̪ˠɪçtʃə'),
    'b2-overdue': ('Thar an ama', 'ˈhaɾ ən̪ˠ ˈamə'),
    'b2-overpopulation': ('Cus sluaigh', 'ˈkʰus ˈsl̪ˠuəj'),
    'b2-paintbrush': ('Bruispheantaidh', 'ˈpɾɯʃˈfɛn̪ˠt̪i'),
    'b2-painting': ('Peantadh', 'ˈpʰɛn̪ˠt̪əɣ'),
    'b2-pajamas': ('Aodachoidhche', 'ˈɯːt̪əxˈɤiçə'),
    'b2-palm': ('Bas', 'ˈpas'),
    'b2-parade': ('Caismeachd', 'ˈkʰaʃməxk'),
    'b2-parliament': ('Pàrlamaid', 'ˈpʰaːɾl̪ˠəmɪtʃ'),
    'b2-partially': ('Gu ìre', 'kə ˈiːɾʲə'),
    'b2-pastime': ('Curseachad', 'ˈkʰuɾˈʃɛxət̪'),
    'b2-patience': ('Foighidinn', 'ˈfɔ.ɪtʃɪɲ'),
    'b2-pedestrian-zone': ('Fearanncoisiche', 'ˈfɛɾən̪ˠˈkʰɔʃɪçə'),
    'b2-peer-pressure': ('Brùthadhchomhaoisean', 'ˈpɾuː.əɣˈxɔvɪʃan'),
    'b2-peninsula': ('Letheilean', 'ˈʎehˈelʲan'),
    'b2-perfectionism': ('Foirfeachas', 'ˈfɔɾʲfəxəs'),
    'b2-performance-review': ('Tomhassaothrach', 'ˈt̪ʰɔvəsˈsɯːɾəx'),
    'b2-permit': ('Cead', 'ˈkʲʰɛt̪'),
    'b2-persistent': ('Dùr', 'ˈt̪uːɾ'),
    'b2-personality': ('Pearsantachd', 'ˈpʰɛɾsan̪ˠt̪əxk'),
    'b2-persuasive': ('Iompaidheach', 'ˈimpɪ.əx'),
    'b2-phase': ('Ìre', 'ˈiːɾʲə'),
    'b2-plateau': ('Àrdchlàr', 'ˈaːɾt̪ˈxl̪ˠaːɾ'),
    'b2-playwright': ('Scrìobhaichedràma', 'ˈskɾʲiəvɪçəˈt̪ɾaːmə'),
    'b2-plumbing': ('Ceàirduisce', 'ˈkʲʰiɾʲtʃˈɯʃkʲə'),
    'b2-pocket': ('Pòcaid', 'ˈpʰɔːʰkɪtʃ'),
    'b2-policy': ('Poileasaidh', 'ˈpʰɔlʲəsi'),
    'b2-political-party': ('Cuideachdrùin', 'ˈkʰutʃəxkˈr̪ˠuːnʲ'),
    'b2-portrait': ('Portraid', 'ˈpʰɔɾt̪ɾɪtʃ'),
    'b2-pottery': ('Crèadhadaireachd', 'ˈkʰɾʲiə.ət̪ɪɾʲəxk'),
    'b2-precise': ('Pongail', 'ˈpʰɔŋɪlʲ'),
    'b2-precisely': ('Gu dìreach', 'kə ˈtʃiːɾʲəx'),
    'b2-pregnant': ('Leatromach', 'ˈʎɛʰt̪ɾəməx'),
    'b2-prejudice': ('Claonbhreith', 'ˈkʰl̪ˠɯːnˈvɾʲeh'),
    'b2-premiere': ('Ciadthaisbeanadh', 'ˈkʲʰiət̪ˈhaʃpanəɣ'),
    'b2-president': ('Ceannsuidhe', 'ˈkʲʰaun̪ˠˈsu.ə'),
    'b2-pride-self-respect': ('Uaill', 'ˈuəʎ'),
    'b2-prime-minister': ('Prìomhaire', 'ˈpʰɾʲiəvɪɾʲə'),
    'b2-principle': ('Prionnsabal', 'ˈpʰɾʲuːn̪ˠsəpəl̪ˠ'),
    'b2-prison-sentence': ('Binn prìosain', 'ˈpiːɲ ˈpʰɾʲiəsɪnʲ'),
    'b2-procedure': ('Modhobrach', 'ˈmɔɣˈɔpɾəx'),
    'b2-process': ('Sligheobrach', 'ˈʃlʲi.əˈɔpɾəx'),
    'b2-procrastination': ('Màirneal', 'ˈmaːɾʲnʲəl̪ˠ'),
    'b2-producer': ('Riochdaire', 'ˈr̪ˠixkɪɾʲə'),
    'b2-productivity': ('Toradhachd', 'ˈt̪ʰɔɾə.əxk'),
    'b2-profit-margin': ('Oirbuannachd', 'ˈɔɾʲˈpuən̪ˠəxk'),
    'b2-profound': ('Domhainn', 'ˈt̪ɔvɪɲ'),
    'b2-prominent': ('Cliùiteach', 'ˈkʲʰlʲuːʰtʃəx'),
    'b2-proportion': ('Cuibhreann', 'ˈkʰuvɾʲən̪ˠ'),
    'b2-proposal': ('Tairgse', 'ˈt̪ʰaɾʲakʲʃə'),
    'b2-prosecutor': ('Neachcasaid', 'ˈɲɛxˈkʰasɪtʃ'),
    'b2-prototype': ('Prìomhshamhla', 'ˈpʰɾʲiəvˈhãũl̪ˠə'),
    'b2-public-transport': ('Carbadpobaill', 'ˈkʰaɾapət̪ˈpʰɔpɪʎ'),
    'b2-pulse': ('Buillecuisle', 'ˈpuʎəˈkʰɯʃlʲə'),
    'b2-punctuality': ('Pongalachd', 'ˈpʰɔŋəl̪ˠəxk'),
    'b2-quarter-business': ('Ràith', 'ˈr̪ˠaː'),
    'b2-quotation': ('Àsaithris', 'ˈaːsˈaɾʲɪʃ'),
    'b2-quote-price-estimate': ('Tuairmseprìse', 'ˈt̪ʰuəɾʲmʃəˈpʰɾʲiːʃə'),
    'b2-rage': ('Boile', 'ˈpɔlʲə'),
    'b2-rainforest': ('Coilleuisce', 'ˈkʰɔʎəˈɯʃkʲə'),
    'b2-rapidly': ('Gu luath', 'kə ˈl̪ˠuə'),
    'b2-rather': ('Caran', 'ˈkʰaɾan'),
    'b2-ratio': ('Comheas', 'kʰɔˈvɛs'),
    'b2-recession': ('Crìonadhmalairt', 'ˈkʰɾʲiənəɣˈmal̪ˠɪɾʲtʃ'),
    'b2-recovery': ('Athshlànachadh', 'ˈahˈhl̪ˠaːnəxəɣ'),
    'b2-recycling-bin': ('Soitheachathbhreith', 'ˈsɔ.əxˈahˈvɾʲeh'),
    'b2-redundant': ('Neoriatanach', 'ˈɲɔˈr̪ˠiəʰt̪anəx'),
    'b2-reef': ('Sceir', 'ˈskʲeɾʲ'),
    'b2-reference': ('Iomradh', 'ˈimɾəɣ'),
    'b2-referendum': ('Taghadhsluaigh', 'ˈt̪ʰa.əɣˈsl̪ˠuəj'),
    'b2-reform': ('Athleasachadh', 'ˈahˈʎɛsəxəɣ'),
    'b2-rehearsal': ('Ruiththairis', 'ˈr̪ˠuhˈhaɾʲɪʃ'),
    'b2-relevant': ('Buntainneach', 'ˈpun̪ˠt̪ɪɲəx'),
    'b2-reluctance': ('Aindeoin', 'ˈaɲtʃɪnʲ'),
    'b2-reluctant': ('Aindeonach', 'ˈaɲtʃənəx'),
    'b2-reluctantly': ('Gu leisc', 'kə ˈʎeʃkʲ'),
    'b2-remark': ('Facal', 'ˈfaʰkəl̪ˠ'),
    'b2-reminder': ('Cuimhneachan', 'ˈkʰũnʲəxan'),
    'b2-remorse': ('Aithreachas', 'ˈaɾʲəxəs'),
    'b2-resentment': ('Gamhlas', 'ˈkãũl̪ˠəs'),
    'b2-resilience': ('Cruadal', 'ˈkʰɾuət̪əl̪ˠ'),
    'b2-retirement-home': ('Taighcùraim', 'ˈt̪ʰɤjˈkʰuːɾɪm'),
    'b2-revenue': ('Teachdasteach', 'ˈtʃʰɛxkˈaˈʃtʃɛx'),
    'b2-rhyme': ('Comhardadh', 'ˈkʰɔvəɾt̪əɣ'),
    'b2-rib': ('Asna', 'ˈasnə'),
    'b2-rigid': ('Rag', 'ˈr̪ˠak'),
    'b2-robbery': ('Robaireachd', 'ˈr̪ˠɔpɪɾʲəxk'),
    'b2-robot': ('Gilleiarainn', 'ˈkʲiʎəˈiəɾɪɲ'),
    'b2-rock-climbing': ('Streap chreag', 'ˈʃt̪ɾʲɛʰp ˈxɾʲek'),
    'b2-role-model': ('Eisimpleir ri leantainn', 'ˈeʃɪmplʲɪɾʲ ɾʲə ˈʎɛn̪ˠt̪ɪɲ'),
    'b2-rotten': ('Grod', 'ˈkɾɔt̪'),
    'b2-roughly': ('Timcheall air', 'ˈtʃʰimçəl̪ˠ ˈɛɾʲ'),
    'b2-rural': ('Dùthchail', 'ˈt̪uːxɪlʲ'),
    'b2-sacrifice': ('Ìobairt', 'ˈiəpɪɾʲtʃ'),
    'b2-sandals': ('Cuaranan', 'ˈkʰuəɾanan'),
    'b2-sandpaper': ('Pàipeargainmhich', 'ˈpʰaːʰpəɾˈkanʲavɪç'),
    'b2-satellite': ('Gealachiarainn', 'ˈkʲal̪ˠəxˈiəɾɪɲ'),
    'b2-savanna': ('Sabhana', 'ˈsavanə'),
    'b2-savory': ('Blasta', 'ˈpl̪ˠast̪ə'),
    'b2-scaffolding': ('Scafall', 'ˈskafəl̪ˠ'),
    'b2-scale-magnitude': ('Meud', 'ˈmiət̪'),
    'b2-scan-medical': ('Sealladhbroinne', 'ˈʃɛl̪ˠəɣˈpɾɔɲə'),
    'b2-scandal': ('Scainneal', 'ˈskaɲəl̪ˠ'),
    'b2-scope': ('Farsaingeachd', 'ˈfaɾsɪɲəxk'),
    'b2-screenplay': ('Scrìobhadhscàile', 'ˈskɾʲiəvəɣˈskaːlʲə'),
    'b2-script': ('Scriobt', 'ˈskɾʲipt̪'),
    'b2-sculpture': ('Snaidheadh', 'ˈsna.əɣ'),
    'b2-sea-level': ('Àirde na mara', 'ˈaːɾʲtʃə nə ˈmaɾə'),
    'b2-seam': ('Loidhnefuaigheil', 'ˈl̪ˠɤinʲəˈfuə.ɪlʲ'),
    'b2-seasoning': ('Stuthblasaidh', 'ˈst̪uhˈpl̪ˠasi'),
    'b2-self-awareness': ('Fèinmhothachadh', 'ˈfeːnʲˈvɔ.əxəɣ'),
    'b2-self-confidence': ('Fèinmhisneachd', 'ˈfeːnʲˈviʃnʲəxk'),
    'b2-self-esteem': ('Fèinspèis', 'ˈfeːnʲˈspeːʃ'),
    'b2-sequence': ('Sreath', 'ˈst̪ɾʲɛh'),
    'b2-serenity': ('Suaimhneas', 'ˈsũənʲəs'),
    'b2-sewing': ('Fuaigheal', 'ˈfuə.əl̪ˠ'),
    'b2-shame': ('Nàire', 'ˈn̪ˠaːɾʲə'),
    'b2-shareholder': ('Sealbhadairearrainn', 'ˈʃal̪ˠavət̪ɪɾʲˈjaːr̪ˠɪɲ'),
    'b2-shares-stocks': ('Earrann', 'ˈjaːr̪ˠən̪ˠ'),
    'b2-shelter': ('Fascadh', 'ˈfaskəɣ'),
    'b2-shore': ('Cladach', 'ˈkʰl̪ˠat̪əx'),
    'b2-short-term': ('Geàrrùine', 'ˈkʲaːr̪ˠˈuːnʲə'),
    'b2-sibling': ('Bràthair no piuthar', 'ˈpɾaːhɪɾʲ ˈn̪ˠɔ ˈpʲʰu.əɾ'),
    'b2-side-effect': ('Frithbhuaidh', 'ˈfɾʲihˈvuəj'),
    'b2-significance': ('Brìgh', 'ˈpɾʲiː'),
    'b2-significantly': ('Gu mòr', 'kə ˈmoːɾ'),
    'b2-simultaneously': ('Aig an aon àm', 'ˈekʲ ən̪ˠ ˈɯːn ˈaːm'),
    'b2-single-parent': ('Pàrant singilte', 'ˈpʰaːɾan̪ˠt̪ ˈʃiɲɪlʲtʃə'),
    'b2-single-use-plastic': ('Craiceanntilgidh', 'ˈkʰɾaʰkʲən̪ˠˈtʃʰilʲikʲi'),
    'b2-skeleton': ('Cnàimhneach', 'ˈkʰn̪ˠãːnʲəx'),
    'b2-sketch': ('Sceidse', 'ˈskʲetʃʃə'),
    'b2-skull': ('Claigeann', 'ˈkʰl̪ˠakʲən̪ˠ'),
    'b2-skyscraper': ('Suathaichenèimh', 'ˈsuəhɪçəˈɲeːv'),
    'b2-sleeve': ('Muinchill', 'ˈmɯnʲɯçɪʎ'),
    'b2-slightly': ('Beagan', 'ˈpekan'),
    'b2-slippers': ('Slapagan', 'ˈsl̪ˠaʰpəkan'),
    'b2-smuggling': ('Cùlmhùtaireachd', 'ˈkʰuːl̪ˠˈvuːʰt̪ɪɾʲəxk'),
    'b2-sneakers': ('Bròganèalaidh', 'ˈpɾɔːkanˈiəl̪ˠi'),
    'b2-software': ('Rannseunaidh', 'ˈr̪ˠaun̪ˠˈʃiəni'),
    'b2-solar-panel': ('Clàrgrèine', 'ˈkʰl̪ˠaːɾˈkɾʲeːnʲə'),
    'b2-somewhat': ('Rud beag', 'ˈr̪ˠut̪ ˈpek'),
    'b2-sooner-or-later': ('Luath no mall', 'ˈl̪ˠuə ˈn̪ˠɔ ˈmaul̪ˠ'),
    'b2-sour': ('Goirt', 'ˈkɔɾʲtʃ'),
    'b2-soy-sauce': ('Sùghpònaire', 'ˈsuːˈpʰɔːnɪɾʲə'),
    'b2-spare-time': ('Ùine shaor', 'ˈuːnʲə ˈhɯːɾ'),
    'b2-species': ('Gnè', 'ˈkʲɲeː'),
    'b2-spice': ('Spìosraidh', 'ˈspiəsɾi'),
    'b2-spine': ('Cnàimhdroma', 'ˈkʰn̪ˠaːvˈt̪ɾɔmə'),
    'b2-spouse': ('Cèile', 'ˈkʲʰeːlʲə'),
    'b2-spring-water': ('Fuaran', 'ˈfuəɾan'),
    'b2-stage': ('Àrdùrlar', 'ˈaːɾt̪ˈuːɾl̪ˠəɾ'),
    'b2-stain': ('Smal', 'ˈsmal̪ˠ'),
    'b2-stakeholder': ('Neachcuibhrinn', 'ˈɲɛxˈkʰuvɾʲɪɲ'),
    'b2-stale': ('Sean', 'ˈʃɛn'),
    'b2-standard': ('Inbhe', 'ˈinʲivə'),
    'b2-startup': ('Fiùranmalairt', 'ˈfʲuːɾanˈmal̪ˠɪɾʲtʃ'),
    'b2-statement': ('Aithris', 'ˈaɾʲɪʃ'),
    'b2-steadily': ('Gu cunbhalach', 'kə ˈkʰunuvəl̪ˠəx'),
    'b2-stepmother': ('Muime', 'ˈmumə'),
    'b2-stereotype': ('Dealbhfathainn', 'ˈtʃal̪ˠavˈfahɪɲ'),
    'b2-stew': ('Stiubha', 'ˈʃtʃuvə'),
    'b2-stock-market': ('Fèillearrann', 'ˈfeːʎˈjaːr̪ˠən̪ˠ'),
    'b2-strategy': ('Roinnleachd', 'ˈr̪ˠɔˈiːɲlʲəxk'),
    'b2-stream': ('Allt', 'ˈaul̪ˠt̪'),
    'b2-stress': ('Cuideam', 'ˈkʰutʃəm'),
    'b2-strictly-speaking': ('A rèir na litreach', 'ə ˈr̪ˠeːɾʲ nə ˈʎiʰtʃɾʲəx'),
    'b2-stroke': ('Builleeanchainne', 'ˈpuʎəˈɛnɛxɪɲə'),
    'b2-structure': ('Creattogail', 'ˈkʰɾʲɛʰt̪ˈt̪ʰɔkɪlʲ'),
    'b2-subtle': ('Fìnealta', 'ˈfiːnʲəl̪ˠt̪ə'),
    'b2-sufficient': ('Foghainteach', 'ˈfɔ.ɪɲtʃəx'),
    'b2-suit': ('Deise', 'ˈtʃeʃə'),
    'b2-summary': ('Geàrrchunntas', 'ˈkʲaːr̪ˠˈxuːn̪ˠt̪əs'),
    'b2-superficial': ('Uachdarach', 'ˈuəxkəɾəx'),
    'b2-supplier': ('Solaraiche', 'ˈsɔl̪ˠəɾɪçə'),
    'b2-surgeon': ('Lannsair', 'ˈl̪ˠaun̪ˠsɪɾʲ'),
    'b2-surgery': ('Obairlannsa', 'ˈɔpɪɾʲˈl̪ˠaun̪ˠsə'),
    'b2-suspect': ('Neach fo amharas', 'ˈɲɛx fə ˈavəɾəs'),
    'b2-suspicion': ('Amharas', 'ˈavəɾəs'),
    'b2-sustainability': ('Seasmhachd', 'ˈʃɛsvəxk'),
    'b2-sustainable': ('Seasmhach', 'ˈʃɛsvəx'),
    'b2-swamp': ('Boglach', 'ˈpɔkl̪ˠəx'),
    'b2-symphony': ('Siansadh', 'ˈʃiənsəɣ'),
    'b2-tabletop-role-playing-game': ('Cluichesceòil', 'ˈkʰl̪ˠuçəˈskʲɔːlʲ'),
    'b2-tactful': ('Tuigseach', 'ˈt̪ʰɯkʲʃəx'),
    'b2-tailor': ('Tàillear', 'ˈt̪ʰaːʎəɾ'),
    'b2-target': ('Targaid', 'ˈt̪ʰaɾakɪtʃ'),
    'b2-tariff': ('Cìschusbainn', 'ˈkʲʰiːʃˈxuspɪɲ'),
    'b2-technique': ('Dòighlàimhe', 'ˈtoːjˈl̪ˠaːvə'),
    'b2-temptation': ('Buaireadh', 'ˈpuəɾʲəɣ'),
    'b2-tenant-improvement': ('Leasachadh màladair', 'ˈʎɛsəxəɣ ˈmaːl̪ˠət̪ɪɾʲ'),
    'b2-tender': ('Maoth', 'ˈmɯː'),
    'b2-tenderness': ('Caomhalachd', 'ˈkʰɯːvəl̪ˠəxk'),
    'b2-tendon': ('Fèithlùthaidh', 'ˈfeːˈl̪ˠuːhi'),
    'b2-theft': ('Goid', 'ˈkɔtʃ'),
    'b2-theory': ('Teòiridh', 'ˈtʃʰɔːɾʲi'),
    'b2-therapist': ('Neachleigheis', 'ˈɲɛxˈʎe.ɪʃ'),
    'b2-thigh': ('Sliasaid', 'ˈʃlʲiəsɪtʃ'),
    'b2-thorough': ('Mionaideach', 'ˈminɪtʃəx'),
    'b2-thoroughly': ('Gu mionaideach', 'kə ˈminɪtʃəx'),
    'b2-throat': ('Scòrnan', 'ˈskɔːɾnan'),
    'b2-thumb': ('Òrdag', 'ˈɔːɾt̪ak'),
    'b2-tide': ('Seòlmara', 'ˈʃɔːl̪ˠˈmaɾə'),
    'b2-tie': ('Stiallmuineil', 'ˈʃtʃiəl̪ˠˈmɯnʲɪlʲ'),
    'b2-time-zone': ('Criosuaire', 'ˈkʰɾʲisˈuəɾʲə'),
    'b2-to-abandon': ('Trèigsinn', 'ˈt̪ʰɾʲeːkʲʃɪɲ'),
    'b2-to-accompany': ('Rach còmhla ri', 'ˈr̪ˠax ˈkʰɔ̃ːl̪ˠə ɾʲə'),
    'b2-to-accumulate': ('Cruinneachadh', 'ˈkʰɾɯɲəxəɣ'),
    'b2-to-acknowledge': ('Aideachadh', 'ˈatʃəxəɣ'),
    'b2-to-adapt': ('Freagarrachadh', 'ˈfɾʲekər̪ˠəxəɣ'),
    'b2-to-address-an-issue': ('Dèiligeadh ri', 'ˈtʃeːlʲɪkʲəɣ ɾʲə'),
    'b2-to-adopt': ('Uchdmhacachadh', 'ˈuxkˈvaʰkəxəɣ'),
    'b2-to-advocate': ('Tagradh', 'ˈt̪ʰakɾəɣ'),
    'b2-to-allocate': ('Riarachadh', 'ˈr̪ˠiəɾəxəɣ'),
    'b2-to-alter': ('Atharrachadh', 'ˈa.ər̪ˠəxəɣ'),
    'b2-to-analyze': ('Mionscrùdadh', 'ˈminˈskɾuːt̪əɣ'),
    'b2-to-announce': ('Ainmeachadh', 'ˈanʲaməxəɣ'),
    'b2-to-anticipate': ('Sùileachadh', 'ˈsuːlʲəxəɣ'),
    'b2-to-approve': ('Aontachadh', 'ˈɯːn̪ˠt̪əxəɣ'),
    'b2-to-arrest': ('Cuir an grèim', 'ˈkʰuɾʲ əŋ ˈkɾʲeːm'),
    'b2-to-articulate': ('Cur an cèill gu soilleir', 'ˈkʰuɾ əŋ ˈɡʲeːʎ kə ˈsɔʎɪɾʲ'),
    'b2-to-assert': ('Daingneachadh', 'ˈt̪aiɲnʲəxəɣ'),
    'b2-to-assess': ('Measadh', 'ˈmɛsəɣ'),
    'b2-to-assign': ('Sònrachadh', 'ˈsɔːnɾəxəɣ'),
    'b2-to-assure': ('Thoir cinnt do', 'ˈhɔɾʲ ˈkʲʰiːɲtʃ t̪ə'),
    'b2-to-attach': ('Ceangal', 'ˈkʲʰɛŋəl̪ˠ'),
    'b2-to-brainstorm': ('Cnuasaich còmhla', 'ˈkʰn̪ˠuəsɪç ˈkʰɔ̃ːl̪ˠə'),
    'b2-to-calculate': ('Obraich amach', 'ˈɔpɾɪç əˈmax'),
    'b2-to-cease': ('Scur', 'ˈskuɾ'),
    'b2-to-charge-with-a-crime': ('Cuir às leth', 'ˈkʰuɾʲ ˈaːs ˈʎeh'),
    'b2-to-cherish': ('Altram', 'ˈal̪ˠt̪ɾəm'),
    'b2-to-chop': ('Mionghearradh', 'ˈminˈjaːr̪ˠəɣ'),
    'b2-to-claim': ('Cumail amach', 'ˈkʰumɪlʲ əˈmax'),
    'b2-to-clarify': ('Soilleireachadh', 'ˈsɔʎɪɾʲəxəɣ'),
    'b2-to-code-program': ('Fighesheun', 'ˈfi.əˈhiən'),
    'b2-to-collaborate': ('Coobrachadh', 'kʰɔˈɔpɾəxəɣ'),
    'b2-to-comment': ('Toirt beachd', 'ˈt̪ʰɔɾʲtʃ ˈpɛxk'),
    'b2-to-commit-to': ('Gealltainn', 'ˈkʲaul̪ˠt̪ɪɲ'),
    'b2-to-comply': ('Gèilleadh', 'ˈkʲeːʎəɣ'),
    'b2-to-compromise': ('Thig gu corèiteachadh', 'ˈhikʲ kə kʰɔˈr̪ˠeːʰtʃəxəɣ'),
    'b2-to-conclude': ('Codhùnadh', 'kʰɔˈɣuːnəɣ'),
    'b2-to-conduct-carry-out': ('Làimhseachadh', 'ˈl̪ˠãːʃəxəɣ'),
    'b2-to-confess': ('Aideachadh', 'ˈatʃəxəɣ'),
    'b2-to-confirm': ('Dearbhadh', 'ˈtʃɛɾɛvəɣ'),
    'b2-to-confront': ('Cuir aghaidh ri', 'ˈkʰuɾʲ ˈa.i ɾʲə'),
    'b2-to-conserve': ('Caomhnadh', 'ˈkʰɯ̃ːnəɣ'),
    'b2-to-consist-of': ('Air a dhèanamh suas de', 'ˈɛɾʲ ə ˈjiənəv ˈsuəs tʃə'),
    'b2-to-consult': ('Cochomhairleachadh', 'kʰɔˈxɔvɪɾʲlʲəxəɣ'),
    'b2-to-contribute': ('Cuir ri', 'ˈkʰuɾʲ ɾʲə'),
    'b2-to-convert': ('Tionndadh', 'ˈtʃʰuːn̪ˠt̪əɣ'),
    'b2-to-convey': ('Toirt seachad', 'ˈt̪ʰɔɾʲtʃ ˈʃɛxət̪'),
    'b2-to-cooperate': ('Obraich còmhla', 'ˈɔpɾɪç ˈkʰɔ̃ːl̪ˠə'),
    'b2-to-cope': ('Dèilig ri', 'ˈtʃeːlʲɪkʲ ɾʲə'),
    'b2-to-declare': ('Gairm', 'ˈkaɾʲam'),
    'b2-to-decline-refuse': ('Diùltadh', 'ˈtʃuːl̪ˠt̪əɣ'),
    'b2-to-define': ('Mìneachadh', 'ˈmiːnʲəxəɣ'),
    'b2-to-delegate': ('Tiomnadh', 'ˈtʃʰimnəɣ'),
    'b2-to-demonstrate': ('Taisbeanadh', 'ˈt̪ʰaʃpanəɣ'),
    'b2-to-despise': ('Dèanamh tàir air', 'ˈtʃiənəv ˈt̪ʰaːɾʲ ˈɛɾʲ'),
    'b2-to-detect': ('Lorg', 'ˈl̪ˠɔɾɔk'),
    'b2-to-devote': ('Coisrigeadh', 'ˈkʰɔʃɾʲɪkʲəɣ'),
    'b2-to-diagnose': ('Breithneachadh tinneis', 'ˈpɾʲenʲəxəɣ ˈtʃʰiɲɪʃ'),
    'b2-to-dice': ('Gearradh na chiùban', 'ˈkʲaːr̪ˠəɣ nə ˈçuːpan'),
    'b2-to-dismiss': ('Cuir an dàrna taobh', 'ˈkʰuɾʲ ən̪ˠ ˈt̪aːɾnə ˈt̪ʰɯːv'),
    'b2-to-distinguish': ('Eadardhealachadh', 'ˈɛt̪əɾˈjal̪ˠəxəɣ'),
    'b2-to-do-list': ('Liosta rudan ri dhèanamh', 'ˈʎist̪ə ˈr̪ˠut̪an ɾʲə ˈjiənəv'),
    'b2-to-dominate': ('Smachdachadh', 'ˈsmaxkəxəɣ'),
    'b2-to-dread': ('Gabhail eagal mòr ro', 'ˈkavɪlʲ ˈekəl̪ˠ ˈmoːɾ ɾə'),
    'b2-to-elaborate': ('Leudachadh', 'ˈʎiət̪əxəɣ'),
    'b2-to-eliminate': ('Cuir às do', 'ˈkʰuɾʲ ˈaːs t̪ə'),
    'b2-to-emerge': ('Thig am bàrr', 'ˈhikʲ əm ˈpaːr̪ˠ'),
    'b2-to-emphasize': ('Cuir cuideam air', 'ˈkʰuɾʲ ˈkʰutʃəm ˈɛɾʲ'),
    'b2-to-enable': ('Comasachadh', 'ˈkʰɔməsəxəɣ'),
    'b2-to-enhance': ('Leasachadh', 'ˈʎɛsəxəɣ'),
    'b2-to-ensure': ('Dèan cinnteach', 'ˈtʃiən ˈkʲʰiːɲtʃəx'),
    'b2-to-establish': ('Stèidheachadh', 'ˈʃtʃeː.əxəɣ'),
    'b2-to-estimate': ('Tuairmseachadh', 'ˈt̪ʰuəɾʲmʃəxəɣ'),
    'b2-to-evaluate': ('Luachadh', 'ˈl̪ˠuəxəɣ'),
    'b2-to-exceed': ('Rach thairis air', 'ˈr̪ˠax ˈhaɾʲɪʃ ˈɛɾʲ'),
    'b2-to-exclude': ('Àsdùnadh', 'ˈaːsˈt̪uːnəɣ'),
    'b2-to-expand': ('Leudachadh', 'ˈʎiət̪əxəɣ'),
    'b2-to-exploit': ('Gabh brath air', 'ˈkav ˈpɾah ˈɛɾʲ'),
    'b2-to-facilitate': ('Furasdachadh', 'ˈfuɾəst̪əxəɣ'),
    'b2-to-fade': ('Call dath', 'ˈkʰaul̪ˠ ˈt̪ah'),
    'b2-to-fasten': ('Ceangal', 'ˈkʲʰɛŋəl̪ˠ'),
    'b2-to-fold': ('Pascadh', 'ˈpʰaskəɣ'),
    'b2-to-fulfill': ('Coileanadh', 'ˈkʰɔlʲanəɣ'),
    'b2-to-generate': ('Gineadh', 'ˈkʲinʲəɣ'),
    'b2-to-grate': ('Scrìobadh', 'ˈskɾʲiəpəɣ'),
    'b2-to-grill': ('Grìosachadh', 'ˈkɾʲiəsəxəɣ'),
    'b2-to-guarantee': ('Barantachadh', 'ˈpaɾan̪ˠt̪əxəɣ'),
    'b2-to-highlight': ('Comharrachadh', 'ˈkʰɔvər̪ˠəxəɣ'),
    'b2-to-hint': ('Sanas a thoirt', 'ˈsanəs ə ˈhɔɾʲtʃ'),
    'b2-to-identify': ('Aithneachadh', 'ˈanʲəxəɣ'),
    'b2-to-illustrate': ('Dealbhachadh', 'ˈtʃal̪ˠavəxəɣ'),
    'b2-to-implement': ('Cuir an gnìomh', 'ˈkʰuɾʲ əŋ ˈkʲɲiəv'),
    'b2-to-imply': ('Ciallachadh', 'ˈkʲʰiəl̪ˠəxəɣ'),
    'b2-to-impose': ('Sparradh', 'ˈspaːr̪ˠəɣ'),
    'b2-to-indicate': ('Nochdadh', 'ˈn̪ˠɔxkəɣ'),
    'b2-to-influence': ('Thoir buaidh air', 'ˈhɔɾʲ ˈpuəj ˈɛɾʲ'),
    'b2-to-inherit': ('Sealbhachadh', 'ˈʃal̪ˠavəxəɣ'),
    'b2-to-inspire': ('Misneachadh', 'ˈmiʃnʲəxəɣ'),
    'b2-to-integrate': ('Amalachadh', 'ˈaməl̪ˠəxəɣ'),
    'b2-to-interpret': ('Eadarmhìneachadh', 'ˈɛt̪əɾˈviːnʲəxəɣ'),
    'b2-to-justify': ('Fìreanachadh', 'ˈfiːɾʲanəxəɣ'),
    'b2-to-kill-time': ('Cur seachad ùine', 'ˈkʰuɾ ˈʃɛxət̪ ˈuːnʲə'),
    'b2-to-knead': ('Fuineadh', 'ˈfɯnʲəɣ'),
    'b2-to-loathe': ('Gràineachadh', 'ˈkɾaːnʲəxəɣ'),
    'b2-to-maintain': ('Cùm suas', 'ˈkʰuːm ˈsuəs'),
    'b2-to-marinate': ('Bogadh', 'ˈpɔkəɣ'),
    'b2-to-measure': ('Tomhas', 'ˈt̪ʰɔvəs'),
    'b2-to-mediate': ('Eadarmheadhanachadh', 'ˈɛt̪əɾˈvɛ.anəxəɣ'),
    'b2-to-melt': ('Leaghadh', 'ˈʎɛ.əɣ'),
    'b2-to-modify': ('Mùthadh', 'ˈmuː.əɣ'),
    'b2-to-monitor': ('Cùm sùil air', 'ˈkʰuːm ˈsuːlʲ ˈɛɾʲ'),
    'b2-to-motivate': ('Spreagadh', 'ˈspɾʲekəɣ'),
    'b2-to-multitask': ('Dèanamh iomadh rud aig an aon àm', 'ˈtʃiənəv ˈiməɣ ˈr̪ˠut̪ ˈekʲ ən̪ˠ ˈɯːn ˈaːm'),
    'b2-to-neglect': ('Dearmad', 'ˈtʃɛɾɛmət̪'),
    'b2-to-network': ('Ceangalchàirdean', 'ˈkʲʰɛŋəl̪ˠˈxaːɾʲtʃan'),
    'b2-to-object': ('Cur an aghaidh', 'ˈkʰuɾ ən̪ˠ ˈa.i'),
    'b2-to-obtain': ('Faighinn', 'ˈfa.ɪɲ'),
    'b2-to-oppose': ('Cuir an aghaidh', 'ˈkʰuɾʲ ən̪ˠ ˈa.i'),
    'b2-to-outsource': ('Curanull', 'ˈkʰuɾˈaˈn̪ˠuːl̪ˠ'),
    'b2-to-overcome': ('Faigh thairis air', 'ˈfɤj ˈhaɾʲɪʃ ˈɛɾʲ'),
    'b2-to-overlook': ('Coimhead seachad air', 'ˈkʰɔvət̪ ˈʃɛxət̪ ˈɛɾʲ'),
    'b2-to-paraphrase': ('Athfhaclachadh', 'ˈahˈaʰkl̪ˠəxəɣ'),
    'b2-to-peel': ('Rùscadh', 'ˈr̪ˠuːskəɣ'),
    'b2-to-perceive': ('Mothachadh', 'ˈmɔ.əxəɣ'),
    'b2-to-persist': ('Lean air', 'ˈʎɛn ˈɛɾʲ'),
    'b2-to-pollute': ('Truailleadh', 'ˈt̪ʰɾuəʎəɣ'),
    'b2-to-possess': ('Sealbhachadh', 'ˈʃal̪ˠavəxəɣ'),
    'b2-to-prescribe': ('Òrdachadh', 'ˈɔːɾt̪əxəɣ'),
    'b2-to-preserve': ('Glèidheadh', 'ˈkʲlʲeː.əɣ'),
    'b2-to-prevent': ('Cascadh', 'ˈkʰaskəɣ'),
    'b2-to-prioritize': ('Prìomhachadh', 'ˈpʰɾʲiəvəxəɣ'),
    'b2-to-procrastinate': ('Cuir dheth', 'ˈkʰuɾʲ ˈjeh'),
    'b2-to-propose-marriage': ('Iarraidh ri pòsadh', 'ˈiər̪ˠi ɾʲə ˈpʰɔːsəɣ'),
    'b2-to-pursue': ('Leantainn', 'ˈʎɛn̪ˠt̪ɪɲ'),
    'b2-to-put-it-simply': ('Ann am briathran sìmplidh', 'ˈaun̪ˠ əm ˈpɾʲiəɾan ˈʃiːmplʲi'),
    'b2-to-quote': ('Luaidh', 'ˈl̪ˠuəj'),
    'b2-to-reconsider': ('Athbheachdachadh', 'ˈahˈvɛxkəxəɣ'),
    'b2-to-reinforce': ('Daingneachadh', 'ˈt̪aiɲnʲəxəɣ'),
    'b2-to-reiterate': ('Athaithris', 'ˈahˈaɾʲɪʃ'),
    'b2-to-reschedule': ('Athrèiteachadh', 'ˈahˈr̪ˠeːʰtʃəxəɣ'),
    'b2-to-resent': ('Gabhail diomb ri', 'ˈkavɪlʲ ˈtʃimp ɾʲə'),
    'b2-to-resolve': ('Fuascladh', 'ˈfuəskl̪ˠəɣ'),
    'b2-to-restrict': ('Cuingealachadh', 'ˈkʰuɲəl̪ˠəxəɣ'),
    'b2-to-retain': ('Cumail', 'ˈkʰumɪlʲ'),
    'b2-to-reveal': ('Foillseachadh', 'ˈfɔiʎʃəxəɣ'),
    'b2-to-roast': ('Ròstadh', 'ˈr̪ˠɔːst̪əɣ'),
    'b2-to-saute': ('Frighigeadh gu luath', 'ˈfɾʲi.ɪkʲəɣ kə ˈl̪ˠuə'),
    'b2-to-say-the-least': ('Gun cus a ràdh', 'kən̪ˠ ˈkʰus ə ˈr̪ˠaːɣ'),
    'b2-to-shrink': ('Crupadh', 'ˈkʰɾuʰpəɣ'),
    'b2-to-simmer': ('Bruich gu socair', 'ˈpɾuç kə ˈsɔʰkɪɾʲ'),
    'b2-to-slice': ('Sliseadh', 'ˈʃlʲiʃəɣ'),
    'b2-to-some-extent': ('Gu ìre', 'kə ˈiːɾʲə'),
    'b2-to-squeeze-in': ('Brùthadh asteach', 'ˈpɾuː.əɣ əˈʃtʃɛx'),
    'b2-to-state': ('Cur an cèill', 'ˈkʰuɾ əŋ ˈɡʲeːʎ'),
    'b2-to-steam': ('Bruich le smùid', 'ˈpɾuç lʲə ˈsmuːtʃ'),
    'b2-to-stir': ('Cur mun cuairt', 'ˈkʰuɾ ˈmun ˈkʰuəɾʲtʃ'),
    'b2-to-streamline': ('Scioblachadh', 'ˈskʲipl̪ˠəxəɣ'),
    'b2-to-sue': ('Agairt', 'ˈakɪɾʲtʃ'),
    'b2-to-summarize': ('Giorrachadh', 'ˈkʲiːr̪ˠəxəɣ'),
    'b2-to-supervise': ('Stiùireadh', 'ˈʃtʃuːɾʲəɣ'),
    'b2-to-sustain': ("Cùm a' dol", 'ˈkʰuːm ə ˈt̪ɔl̪ˠ'),
    'b2-to-tackle': ('Rach an sàs ann', 'ˈr̪ˠax ən̪ˠ ˈsaːs ˈaun̪ˠ'),
    'b2-to-transform': ('Cruthatharrachadh', 'ˈkʰɾuhˈa.ər̪ˠəxəɣ'),
    'b2-to-unbutton': ('Fuascladh', 'ˈfuəskl̪ˠəɣ'),
    'b2-to-undergo': ('Rach tro', 'ˈr̪ˠax ˈt̪ʰɾɔ'),
    'b2-to-undertake': ('Gabh os làimh', 'ˈkav ˈɔs ˈl̪ˠaːv'),
    'b2-to-verify': ('Scrùdadh', 'ˈskɾuːt̪əɣ'),
    'b2-to-whisk': ('Bualadh', 'ˈpuəl̪ˠəɣ'),
    'b2-to-withdraw-pull-out': ('Tarraing amach', 'ˈt̪ʰaːr̪ˠɪɲkʲ əˈmax'),
    'b2-tolerance': ('Fulangas', 'ˈful̪ˠəŋəs'),
    'b2-tongue': ('Teanga', 'ˈtʃʰɛŋə'),
    'b2-trade-commerce': ('Malairt', 'ˈmal̪ˠɪɾʲtʃ'),
    'b2-trait': ('Feart', 'ˈfɛɾt̪'),
    'b2-transplant': ('Balliasaid', 'ˈpaul̪ˠˈiəsɪtʃ'),
    'b2-trauma': ('Leòninntinn', 'ˈʎɔːnˈiːɲtʃɪɲ'),
    'b2-treatment': ('Leigheas', 'ˈʎe.əs'),
    'b2-tremendous': ('Uabhasach', 'ˈuəvəsəx'),
    'b2-trial': ('Triail', 'ˈt̪ʰɾʲiəlʲ'),
    'b2-trivial': ('Suarach', 'ˈsuəɾəx'),
    'b2-tundra': ('Fàsachreòta', 'ˈfaːsəxˈr̪ˠɔːʰt̪ə'),
    'b2-ultimately': ("Aig a' cheann thall", 'ˈekʲ ə ˈçaun̪ˠ ˈhaul̪ˠ'),
    'b2-underwear': ('Foaodach', 'ˈfɔˈɯːt̪əx'),
    'b2-uniform': ('Èideadh', 'ˈeːtʃəɣ'),
    'b2-unprecedented': ('Gun samhail roimhe', 'kən̪ˠ ˈsavɪlʲ ˈr̪ˠɔvə'),
    'b2-up-to-a-point': ('Gu ìre àraidh', 'kə ˈiːɾʲə ˈaːɾi'),
    'b2-upbringing': ('Togail', 'ˈt̪ʰɔkɪlʲ'),
    'b2-urban': ('Bailteil', 'ˈpalʲtʃɪlʲ'),
    'b2-utterly': ('Gu tur', 'kə ˈt̪ʰuɾ'),
    'b2-vague': ('Doilleir', 'ˈt̪ɔʎɪɾʲ'),
    'b2-valley': ('Gleann', 'ˈkʲlʲaun̪ˠ'),
    'b2-vast': ('Àibheiseach', 'ˈaːvɪʃəx'),
    'b2-vein': ('Cuisle', 'ˈkʰɯʃlʲə'),
    'b2-verdict': ('Breith', 'ˈpɾʲeh'),
    'b2-versatile': ('Iolchomasach', 'ˈil̪ˠˈxɔməsəx'),
    'b2-verse': ('Rann', 'ˈr̪ˠaun̪ˠ'),
    'b2-vice': ('Dubhailc', 'ˈt̪uvɪlʲkʲ'),
    'b2-victim': ('Fulangaiche', 'ˈful̪ˠəŋɪçə'),
    'b2-vinegar': ('Fìongeur', 'ˈfiənˈkʲiəɾ'),
    'b2-virtual-reality': ('Saoghalscàile', 'ˈsɯː.əl̪ˠˈskaːlʲə'),
    'b2-virtually': ('Cha mhòr', 'xa ˈvoːɾ'),
    'b2-virtue': ('Subhailc', 'ˈsuvɪlʲkʲ'),
    'b2-virus': ('Sìolplàighe', 'ˈʃiəl̪ˠˈpʰl̪ˠaː.ə'),
    'b2-vital': ('Riatanach', 'ˈr̪ˠiəʰt̪anəx'),
    'b2-ward': ('Seòmareuslainte', 'ˈʃɔːməɾˈiəsl̪ˠɪɲtʃə'),
    'b2-wardrobe': ('Preasaodaich', 'ˈpʰɾʲɛsˈɯːt̪ɪç'),
    'b2-waterfall': ('Eas', 'ˈɛs'),
    'b2-whatsoever': ('Idir', 'ˈitʃɪɾʲ'),
    'b2-wheelchair': ('Cathairchuibhle', 'ˈkʰahɪɾʲˈxuvlʲə'),
    'b2-widespread': ('Farsaing', 'ˈfaɾsɪɲkʲ'),
    'b2-widow': ('Banntrach', 'ˈpaun̪ˠt̪ɾəx'),
    'b2-wildlife': ('Fiadhbheatha', 'ˈfiəɣˈvɛ.ə'),
    'b2-will-testament': ('Tiomnadh', 'ˈtʃʰimnəɣ'),
    'b2-willpower': ('Nearttoile', 'ˈɲɛɾt̪ˈt̪ʰɔlʲə'),
    'b2-wind-turbine': ('Rothgaoithe', 'ˈr̪ˠɔhˈkɯː.ə'),
    'b2-wiring': ('Snàthainnteine', 'ˈsnaːhɪɲˈtʃʰenʲə'),
    'b2-with-regard-to': ('Ann an cocheangal ri', 'ˈaun̪ˠ əŋ ɡɔˈçɛŋəl̪ˠ ɾʲə'),
    'b2-witness': ('Neachfianais', 'ˈɲɛxˈfiənɪʃ'),
    'b2-woodworking': ('Obairfhiodha', 'ˈɔpɪɾʲˈi.ə'),
    'b2-workbench': ('Beingobrach', 'ˈpeiɲkʲˈɔpɾəx'),
    'b2-wrinkle': ('Preasadh', 'ˈpʰɾʲɛsəɣ'),
    'b2-wrist': ('Caoldùirn', 'ˈkʰɯːl̪ˠˈt̪uːɾʲnʲ'),
    'b2-x-ray': ('Gathcnàimh', 'ˈkahˈkʰn̪ˠaːv'),
    'b2-zipper': ('Glasfhiaclach', 'ˈkl̪ˠasˈiəʰkl̪ˠəx'),
    'b2-zoning': ('Roinnfearainn', 'ˈr̪ˠɔiɲˈfɛɾɪɲ'),
}
