# -*- coding: utf-8 -*-
LANG = 'fr'
STORIES = {
    'st-b1-01': {
        'title': "Le train en retard",
        'paras': [
            "Le Rosetta a atterri près d'une petite ville de marché. Ana et Marco ont quitté le vaisseau pour aller à la gare. Ils voulaient acheter des billets pour la ville.",
            "À la gare, beaucoup de gens attendaient sur le quai. Une femme leur a dit que le train était en retard. \"Il y a un problème sur les voies\", a-t-elle dit.",
            "Ana a regardé l'horloge. Il était déjà dix heures, et leur train devait partir à neuf heures et demie. Marco s'est assis sur un banc et a soupiré.",
            "Un homme à côté d'eux a ouvert son sac et en a sorti du pain. Il en a offert un morceau à Ana et Marco. \"Vous pouvez attendre ici avec moi\", a-t-il dit avec un sourire.",
            "Ils ont parlé avec l'homme de sa famille et de son travail. Il travaillait au marché et vendait des légumes tous les jours. Ana lui a parlé du Rosetta et de leur voyage.",
            "Enfin, après une heure, le train est arrivé. Tout le monde s'est levé rapidement et s'est dirigé vers les portes. Ana et Marco ont remercié l'homme pour le pain.",
            "Dans le train, Ana regardait les champs par la fenêtre. Elle était heureuse qu'ils aient rencontré un inconnu si gentil. Marco a dit que parfois un train en retard apporte une bonne surprise.",
        ],
    },
    'st-b1-02': {
        'title': "Dîner avec la famille de Yuki",
        'paras': [
            "L'équipage du Rosetta a visité un village tranquille pendant quelques jours. Yuki a invité Sam à dîner avec sa famille. Sam était nerveux parce qu'il ne les connaissait pas bien.",
            "La mère de Yuki a ouvert la porte et a souri chaleureusement. \"Bienvenue\", a-t-elle dit. \"Nous sommes heureux que tu sois venu.\" La maison sentait la soupe et le pain frais.",
            "À table, le père de Yuki a posé beaucoup de questions à Sam sur le Rosetta. Sam a expliqué que le vaisseau visitait de nombreuses villes et aidait les gens. Le petit frère de Yuki écoutait avec de grands yeux.",
            "Ils ont mangé de la soupe, du riz et des légumes ensemble. Sam a goûté un nouveau plat qu'il n'avait jamais mangé auparavant. Il l'a beaucoup aimé et en a redemandé.",
            "Après le dîner, la mère de Yuki a apporté un gâteau pour le dessert. Elle a dit que c'était une recette spéciale de sa propre mère. Tout le monde a pris une grosse part et a parlé de vieilles histoires.",
            "Sam a remercié la famille pour cette merveilleuse soirée. Il a dit qu'il se sentait déjà comme un membre de la famille. Le père de Yuki lui a serré la main et l'a invité à revenir bientôt.",
            "En retournant au vaisseau, Sam a dit à Yuki qu'il avait adoré le repas. Il a dit que les familles étaient les mêmes partout : chaleureuses et généreuses. Yuki a souri et lui a donné raison.",
        ],
    },
    'st-b2-01': {
        'title': "L'entretien",
        'paras': [
            "Si le Rosetta n'avait pas eu besoin de réparations, Marco ne serait jamais resté assez longtemps pour postuler à un emploi dans la ville portuaire. Il avait vu une annonce pour un poste de mécanicien et avait décidé de tenter sa chance. Il était curieux de voir comment les gens au sol résolvaient les problèmes sans les outils avancés du vaisseau.",
            "L'intervieweuse, une femme grande du nom d'Ana, lui a demandé pourquoi il voulait ce poste. Marco a expliqué qu'il avait passé des années à réparer des machines dans des conditions difficiles, souvent avec des pièces limitées. Il a ajouté qu'il préférait apprendre correctement un nouveau système plutôt que de prétendre déjà tout savoir.",
            "Ana semblait impressionnée, même si elle a fait remarquer que l'équipement de l'atelier était bien plus ancien que tout ce à quoi il était habitué. \"Si vous travailliez ici\", a-t-elle dit, \"vous devriez désapprendre certaines habitudes.\" Marco a admis que s'adapter demanderait sans doute de la patience, mais qu'il était prêt à essayer.",
            "Elle lui a ensuite demandé ce qu'il ferait si une machine tombait en panne en plein travail sans pièce de rechange disponible. Marco a réfléchi un instant et a dit qu'il improviserait avec les matériaux à portée de main, comme il l'avait fait à bord du vaisseau pendant une tempête l'année précédente. Ana a hoché la tête lentement, examinant visiblement sa réponse.",
            "Vers la fin de l'entretien, Ana a demandé s'il pouvait s'engager à rester même après le départ éventuel du Rosetta. Marco a hésité, admettant qu'il ne savait pas combien de temps il resterait dans la ville. L'honnêteté, croyait-il, comptait plus que de lui dire ce qu'elle voulait entendre.",
            "Ana l'a remercié pour sa franchise et a dit qu'elle en discuterait avec ses associés avant de décider. Elle a mentionné que la plupart des candidats exagéraient leur expérience, et que sa franchise avait retenu son attention. Marco a quitté l'atelier sans savoir s'il avait aidé ou nui à ses chances.",
            "Quelques jours plus tard, un message est arrivé l'invitant à revenir pour une semaine d'essai. Marco a compris que son honnêteté, plus que sa seule compétence technique, les avait convaincus de lui donner une chance. Il se demandait s'il devrait un jour choisir entre l'atelier et les étoiles.",
        ],
    },
    'st-b2-02': {
        'title': "Salle d'attente",
        'paras': [
            "Comme la fièvre de Sam ne passait pas, le médecin du vaisseau lui a suggéré de se rendre à l'hôpital local, car l'équipement de la ville pouvait effectuer des tests dont le Rosetta ne disposait pas. Yuki l'a accompagné, en partie par inquiétude et en partie par curiosité de voir comment fonctionnait l'hôpital. Aucun des deux ne s'attendait à ce que la salle d'attente soit aussi bondée.",
            "Ils se sont assis entre un homme âgé lisant un journal et une jeune mère essayant de calmer son enfant qui pleurait. Si Yuki avait su que l'attente durerait si longtemps, elle aurait apporté de quoi lire. Au lieu de cela, elle regardait l'horloge et écoutait les conversations murmurées autour d'elle.",
            "Après presque deux heures, une infirmière a appelé Sam et l'a conduit vers une salle d'examen. Yuki a proposé de l'accompagner, mais l'infirmière a expliqué que normalement une seule personne était autorisée à entrer. Sam lui a serré rapidement la main avant de disparaître derrière la porte.",
            "Seule dans la salle d'attente, Yuki a engagé la conversation avec l'homme âgé assis à côté d'elle. Il a dit qu'il venait à l'hôpital chaque mois pour un contrôle de routine, et que le personnel le traitait toujours avec gentillesse malgré son emploi du temps chargé. Yuki a trouvé sa patience remarquable, vu le temps que tout le monde devait attendre.",
            "Quand Sam est enfin revenu, il a expliqué que le médecin n'avait rien trouvé de grave, juste une infection que des antibiotiques guériraient en une semaine. Yuki a ressenti une vague de soulagement qu'elle ne s'était pas rendu compte de retenir. Elle l'a taquiné gentiment pour l'avoir tant inquiétée.",
            "En sortant, Sam a admis qu'il avait été plus effrayé qu'il ne l'avait laissé paraître, car il était rarement malade à bord du vaisseau. Yuki a dit que c'était exactement pour cela qu'elle avait insisté pour venir, afin qu'il n'ait pas à affronter cela seul. Il l'a remerciée, un peu gêné de voir à quel point sa présence avait compté.",
            "Sur le chemin du retour vers le Rosetta, ils ont de nouveau croisé l'homme âgé, marchant lentement vers l'arrêt de bus. Yuki lui a fait signe, et il a répondu par un sourire fatigué mais sincère. Sam a remarqué que les hôpitaux, malgré toute leur attente et leur inquiétude, semblaient faire ressortir une douce bonté chez les gens.",
        ],
    },
    'st-c1-01': {
        'title': "Un désaccord au café",
        'paras': [
            "Le café était devenu une sorte de repaire pour l'équipage du Rosetta durant leur séjour, ses tables en bois usé et le bourdonnement constant des conversations offrant un contraste bienvenu avec les couloirs aseptisés du vaisseau. Marco et Ana s'étaient installés dans leur coin habituel lorsqu'un débat à la table voisine a attiré leur attention. Deux habitués discutaient, avec une passion évidente, pour savoir si les nouvelles réglementations du marché de la ville allaient aider ou ruiner les commerçants locaux.",
            "Un homme, marchand de fruits de métier, insistait sur le fait que les réglementations étaient une tentative à peine voilée de favoriser des vendeurs plus grands et mieux financés au détriment des petits étals comme le sien. Son adversaire, qui tenait une modeste librairie à proximité, rétorquait que sans un minimum de contrôle, le marché était devenu chaotique, avec des prix instables et des vendeurs se sous-cotant les uns les autres jusqu'à l'effondrement. Aucun des deux ne semblait prêt à céder un pouce de terrain.",
            "Ana, toujours curieuse, s'est penchée vers Marco et a avoué qu'elle se trouvait partagée entre les deux positions. Marco a fait remarquer que les deux hommes avaient un grief légitime, même si leurs solutions proposées divergeaient nettement. Il lui a semblé que ce genre de différend n'avait presque jamais de méchant ; le plus souvent, il opposait simplement deux peurs raisonnables l'une à l'autre.",
            "Enhardi par une deuxième tasse de café, le marchand de fruits a élevé la voix, accusant le conseil municipal de céder à la pression des commerçants plus fortunés. Le libraire, visiblement irrité, a rétorqué que de telles accusations étaient infondées et que lui aussi risquait de perdre des clients avec des règles plus strictes. Leur échange est devenu assez vif pour que d'autres clients commencent à jeter des regards vers eux.",
            "Sentant que la tension était sur le point d'exploser, le propriétaire du café est intervenu, posant une assiette de pâtisseries entre les deux hommes avec une remarque pleine d'ironie selon laquelle les disputes se passaient mieux le ventre plein. Ce geste a rompu l'hostilité montante, et les deux hommes, un peu penauds, ont accepté cette offrande de paix. Ana a chuchoté à Marco qu'elle admirait la façon dont le propriétaire avait désamorcé la situation avec tant d'habileté.",
            "Une fois la tension immédiate retombée, la conversation a glissé vers un terrain d'entente : tous deux convenaient que le conseil municipal n'avait pas consulté les commerçants ordinaires avant de rédiger les réglementations. Marco a trouvé ce glissement révélateur, car il suggérait que le véritable différend portait moins sur la politique elle-même que sur qui avait voix au chapitre pour la façonner. Ana a hoché la tête, remarquant que l'exclusion, plus que le désaccord, tendait à engendrer du ressentiment.",
            "Alors que les deux hommes se séparaient finalement en bons termes, Marco s'est dit que l'équipage du Rosetta arrivait si souvent en s'attendant à des histoires simples d'harmonie ou de conflit, pour ne découvrir qu'une vérité plus confuse : la plupart des différends prenaient racine dans la peur d'être ignoré. Ana en a convenu, ajoutant que la chose la plus utile qu'ils pourraient rapporter au vaisseau n'était peut-être pas un verdict sur qui avait raison, mais un récit de la rapidité avec laquelle l'amertume pouvait se dissiper dès que les gens se sentaient entendus. Ils ont quitté le café en attendant déjà leur prochaine visite.",
        ],
    },
    'st-c2-01': {
        'title': "Entre deux départs",
        'paras': [
            "Au moment où les réparations du Rosetta touchaient à leur fin, Sam s'était pris d'une affection presque filiale pour le chef de gare, un homme taciturne nommé Marco dont la rudesse, avait-il fini par comprendre, dissimulait un attachement méticuleux à la ponctualité confinant au cérémonial. Leurs conversations, d'abord empruntées, avaient pris un rythme confortable, chaque échange relevé d'un humour sec que seul le respect mutuel autorise. C'était cette complicité, plus qu'une quelconque panne persistante, qui poussait Sam à trouver des prétextes pour s'attarder près du quai.",
            "Le matin de ce qui devait être son dernier jour en ville, Sam trouva Marco inhabituellement silencieux, astiquant méthodiquement une plaque de laiton commémorant la fondation de la gare des décennies plus tôt. Lorsque Sam fit remarquer cette sentimentalité peu coutumière, Marco admit, avec une réticence manifeste, qu'il trouvait les adieux déplaisants, quelle que soit la fréquence à laquelle son métier l'obligeait à les endurer. C'était, confessa-t-il, le seul aspect de son travail avec lequel il ne s'était jamais réconcilié.",
            "Sam, qui avait cru leur relation trop récente pour mériter une telle franchise, se trouva étrangement touché par cet aveu. Il avança que le malaise ne venait peut-être pas de la séparation elle-même, mais de l'asymétrie qui lui était inhérente : le voyageur avance vers la nouveauté, tandis que celui qui reste retourne à la routine, si digne soit-elle. Marco concéda que l'idée n'était pas dénuée de mérite, tout en s'irritant légèrement d'être réduit au rôle de celui qui reste.",
            "Leur échange fut interrompu par l'interphone de la gare, grésillant d'une annonce selon laquelle le train en direction du nord serait retardé de plus de quarante minutes en raison d'une panne de signalisation. Marco, visiblement soulagé par ce sursis, murmura que le destin avait apparemment conspiré pour prolonger la conversation un peu plus longtemps. Sam éclata de rire et proposa de profiter au mieux de cet interlude inattendu.",
            "Ils se retirèrent dans le petit bureau de la gare, où Marco sortit une théière qu'il gardait, admit-il avec une certaine gêne, précisément pour ce genre d'occasions. Au cours de la demi-heure suivante, leur conversation dériva des considérations logistiques du départ du Rosetta vers un territoire plus introspectif : une vie passée à veiller sur un point unique et fixe pouvait-elle jamais rivaliser avec une vie de mouvement perpétuel, ou chacune ne faisait-elle qu'échanger une forme d'agitation contre une autre. Ni l'un ni l'autre ne prétendit avoir tranché la question de façon définitive.",
            "Quand le train retardé finit par entrer en gare dans un grincement, Marco raccompagna Sam sur le quai avec une solennité qui semblait, paradoxalement, adoucir l'instant plutôt que le raidir. Il tendit la main, puis, comme malgré lui, offrit à la place une accolade maladroite, marmonnant quelque chose à propos d'une exception. Sam l'assura que l'exception était réciproque et tout à fait bienvenue.",
            "Alors que le Rosetta décollait plus tard ce soir-là, Sam se surprit à regarder en arrière vers la gare plus longtemps que l'occasion ne le justifiait strictement, retournant dans son esprit la remarque de Marco sur l'asymétrie. Il soupçonnait que le vieil homme avait, à sa manière réservée, exprimé quelque chose que Sam lui-même n'avait jamais tout à fait su mettre en mots : que chaque départ demande à l'un de porter le souvenir plus loin et laisse à l'autre la garde du lieu où tout s'est passé. C'était, songea-t-il, une répartition des tâches assez équitable, tant qu'aucun des deux n'oubliait le rôle de l'autre.",
        ],
    },
}
