# -*- coding: utf-8 -*-
LANG = 'la'
WORDS = {
    'a1-hello': ('Salve', None),
    'a1-goodbye': ('Vale', None),
    'a1-please': ('Quaeso', None),
    'a1-thank-you': ('Gratias ago', None),
    'a1-excuse-me': ('Ignosce', None),
    'a1-sorry': ('Me paenitet', None),
    'a1-yes': ('Ita', None),
    'a1-no': ('Minime', None),
    'a1-my-name-is-alex': ('Mihi nomen est Alex', None),
    'a1-whats-your-name': ('Quod est tibi nomen?', None),
    'a1-nice-to-meet-you': ('Gaudeo te cognoscere', None),
    'a1-how-are-you': ('Quid agis?', None),
    'a1-mother': ('Mater', None),
    'a1-father': ('Pater', None),
    'a1-sister': ('Soror', None),
    'a1-brother': ('Frater', None),
    'a1-friend': ('Amicus', None),
    'a1-child': ('Parvulus', None),
    'a1-today': ('Hodie', None),
    'a1-tomorrow': ('Cras', None),
    'a1-yesterday': ('Heri', None),
    'a1-now': ('Nunc', None),
    'a1-morning': ('Mane', None),
    'a1-night': ('Nox', None),
    'a1-house': ('Domus', None),
    'a1-where-is-it': ('Ubi est?', None),
    'a1-left': ('Sinistra', None),
    'a1-right': ('Dextra (directio)', None),
    'a1-store': ('Taberna', None),
    'a1-bathroom': ('Latrina', None),
    'a1-water': ('Aqua', None),
    'a1-bread': ('Panis', None),
    'a1-coffee': ('Coffea', None),
    'a1-tea': ('Thea', None),
    'a1-delicious': ('Suavis', None),
    'a1-spicy': ('Acer', None),
    'a1-good-morning': ('Bonum mane', None),
    'a1-good-evening': ('Bonum vesperum', None),
    'a1-good-night': ('Bona nox', None),
    'a1-youre-welcome': ('Libenter', None),
    'a1-see-you-soon': ('Mox te videbo', None),
    'a1-see-you-tomorrow': ('Cras te videbo', None),
    'a1-welcome': ('Bene venisti', None),
    'a1-cheers': ('Propino!', None),
    'a1-congratulations': ('Gratulor', None),
    'a1-happy-birthday': ('Felix dies natalis', None),
    'a1-good-luck': ('Bona fortuna', None),
    'a1-have-a-nice-day': ('Diem bonum habeas', None),
    'a1-take-care': ('Cura ut valeas', None),
    'a1-bless-you': ('Di te servent', None),
    'a1-enjoy-your-meal': ('Bene tibi sapiat', None),
    'a1-nice-to-see-you': ('Gaudeo te videre', None),
    'a1-long-time-no-see': ('Diu te non vidi', None),
    'a1-goodbye-for-now': ('Vale interim', None),
    'a1-i': ('Ego', None),
    'a1-you': ('Tu', None),
    'a1-he': ('Is', None),
    'a1-she': ('Ea', None),
    'a1-we': ('Nos', None),
    'a1-they': ('Ii', None),
    'a1-man': ('Vir', None),
    'a1-woman': ('Femina', None),
    'a1-boy': ('Puer', None),
    'a1-girl': ('Puella', None),
    'a1-person': ('Persona', None),
    'a1-people': ('Homines', None),
    'a1-name': ('Nomen', None),
    'a1-mister': ('Dominus', None),
    'a1-madam': ('Domina', None),
    'a1-im-fine': ('Bene valeo', None),
    'a1-and-you': ('Et tu?', None),
    'a1-where-are-you-from': ('Unde es?', None),
    'a1-im-from-the-united-states': ('Ex Civitatibus Foederatis Americae sum', None),
    'a1-friend-female': ('Amica', None),
    'a1-family': ('Familia', None),
    'a1-parents': ('Parentes', None),
    'a1-son': ('Filius', None),
    'a1-daughter': ('Filia', None),
    'a1-husband': ('Maritus', None),
    'a1-wife': ('Uxor', None),
    'a1-grandmother': ('Avia', None),
    'a1-grandfather': ('Avus', None),
    'a1-baby': ('Infans', None),
    'a1-uncle': ('Patruus', None),
    'a1-aunt': ('Amita', None),
    'a1-cousin': ('Consobrinus', None),
    'a1-boyfriend': ('Amasius', None),
    'a1-girlfriend': ('Amasia', None),
    'a1-neighbor': ('Vicinus', None),
    'a1-children': ('Liberi', None),
    'a1-older-brother': ('Frater natu maior', None),
    'a1-younger-sister': ('Soror natu minor', None),
    'a1-pet': ('Deliciae', None),
    'a1-married': ('Nuptus', None),
    'a1-one': ('Unus', None),
    'a1-two': ('Duo', None),
    'a1-three': ('Tres', None),
    'a1-four': ('Quattuor', None),
    'a1-five': ('Quinque', None),
    'a1-six': ('Sex', None),
    'a1-seven': ('Septem', None),
    'a1-eight': ('Octo', None),
    'a1-nine': ('Novem', None),
    'a1-ten': ('Decem', None),
    'a1-eleven': ('Undecim', None),
    'a1-twelve': ('Duodecim', None),
    'a1-thirteen': ('Tredecim', None),
    'a1-fourteen': ('Quattuordecim', None),
    'a1-fifteen': ('Quindecim', None),
    'a1-sixteen': ('Sedecim', None),
    'a1-seventeen': ('Septendecim', None),
    'a1-eighteen': ('Duodeviginti', None),
    'a1-nineteen': ('Undeviginti', None),
    'a1-twenty': ('Viginti', None),
    'a1-zero': ('Cifra', None),
    'a1-thirty': ('Triginta', None),
    'a1-forty': ('Quadraginta', None),
    'a1-fifty': ('Quinquaginta', None),
    'a1-sixty': ('Sexaginta', None),
    'a1-seventy': ('Septuaginta', None),
    'a1-eighty': ('Octoginta', None),
    'a1-ninety': ('Nonaginta', None),
    'a1-one-hundred': ('Centum', None),
    'a1-one-thousand': ('Mille', None),
    'a1-one-million': ('Decies centena milia', None),
    'a1-first': ('Primus', None),
    'a1-second': ('Secundus', None),
    'a1-third': ('Tertius', None),
    'a1-half': ('Dimidium', None),
    'a1-many': ('Multi', None),
    'a1-few': ('Pauci', None),
    'a1-all': ('Omnis', None),
    'a1-some': ('Aliqui', None),
    'a1-nothing': ('Nihil', None),
    'a1-number': ('Numerus', None),
    'a1-more': ('Plus', None),
    'a1-less': ('Minus', None),
    'a1-enough': ('Satis', None),
    'a1-red': ('Ruber', None),
    'a1-blue': ('Caeruleus', None),
    'a1-green': ('Viridis', None),
    'a1-yellow': ('Flavus', None),
    'a1-black': ('Niger', None),
    'a1-white': ('Albus', None),
    'a1-orange-color': ('Aurantius', None),
    'a1-pink': ('Roseus', None),
    'a1-purple': ('Purpureus', None),
    'a1-brown': ('Fuscus', None),
    'a1-gray': ('Griseus', None),
    'a1-color': ('Color', None),
    'a1-light-color': ('Clarus', None),
    'a1-dark': ('Obscurus', None),
    'a1-circle': ('Circulus', None),
    'a1-square': ('Quadratum', None),
    'a1-triangle': ('Triangulum', None),
    'a1-line': ('Linea', None),
    'a1-shape': ('Forma', None),
    'a1-big': ('Magnus', None),
    'a1-small': ('Parvus', None),
    'a1-long': ('Longus', None),
    'a1-short-length': ('Brevis', None),
    'a1-round': ('Rotundus', None),
    'a1-afternoon': ('Tempus pomeridianum', None),
    'a1-evening': ('Vesper', None),
    'a1-day': ('Dies', None),
    'a1-week': ('Hebdomas', None),
    'a1-month': ('Mensis', None),
    'a1-year': ('Annus', None),
    'a1-hour': ('Hora', None),
    'a1-minute': ('Minutum', None),
    'a1-later': ('Postea', None),
    'a1-early': ('Mature', None),
    'a1-late': ('Sero', None),
    'a1-always': ('Semper', None),
    'a1-never': ('Numquam', None),
    'a1-sometimes': ('Interdum', None),
    'a1-often': ('Saepe', None),
    'a1-soon': ('Mox', None),
    'a1-again': ('Iterum', None),
    'a1-its-late': ('Sero est', None),
    'a1-tonight': ('Hac nocte', None),
    'a1-before': ('Ante', None),
    'a1-after': ('Post', None),
    'a1-noon': ('Meridies', None),
    'a1-midnight': ('Media nox', None),
    'a1-monday': ('Dies Lunae', None),
    'a1-tuesday': ('Dies Martis', None),
    'a1-wednesday': ('Dies Mercurii', None),
    'a1-thursday': ('Dies Iovis', None),
    'a1-friday': ('Dies Veneris', None),
    'a1-saturday': ('Dies Saturni', None),
    'a1-sunday': ('Dies Solis', None),
    'a1-weekend': ('Finis hebdomadis', None),
    'a1-january': ('Ianuarius', None),
    'a1-february': ('Februarius', None),
    'a1-march': ('Martius', None),
    'a1-april': ('Aprilis', None),
    'a1-may': ('Maius', None),
    'a1-june': ('Iunius', None),
    'a1-july': ('Iulius', None),
    'a1-august': ('Augustus', None),
    'a1-september': ('September', None),
    'a1-october': ('October', None),
    'a1-november': ('November', None),
    'a1-december': ('December', None),
    'a1-spring': ('Ver', None),
    'a1-summer': ('Aestas', None),
    'a1-autumn': ('Autumnus', None),
    'a1-winter': ('Hiems', None),
    'a1-birthday': ('Dies natalis', None),
    'a1-holiday': ('Dies festus', None),
    'a1-room': ('Conclave', None),
    'a1-kitchen': ('Culina', None),
    'a1-bedroom': ('Cubiculum', None),
    'a1-door': ('Ianua', None),
    'a1-window': ('Fenestra', None),
    'a1-table': ('Mensa', None),
    'a1-chair': ('Sella', None),
    'a1-bed': ('Lectus', None),
    'a1-street': ('Via', None),
    'a1-city': ('Urbs', None),
    'a1-country': ('Patria', None),
    'a1-school': ('Schola', None),
    'a1-hospital': ('Valetudinarium', None),
    'a1-bank': ('Argentaria', None),
    'a1-restaurant': ('Caupona', None),
    'a1-hotel': ('Hospitium', None),
    'a1-market': ('Forum', None),
    'a1-park': ('Viridarium', None),
    'a1-church': ('Ecclesia', None),
    'a1-office': ('Officium', None),
    'a1-here': ('Hic', None),
    'a1-there': ('Ibi', None),
    'a1-straight-ahead': ('Recta', None),
    'a1-near': ('Prope', None),
    'a1-far': ('Procul', None),
    'a1-floor-level': ('Tabulatum', None),
    'a1-garden': ('Hortus', None),
    'a1-wall': ('Murus', None),
    'a1-milk': ('Lac', None),
    'a1-rice': ('Oryza', None),
    'a1-meat': ('Caro', None),
    'a1-fish-food': ('Piscis', None),
    'a1-chicken': ('Pullus', None),
    'a1-egg': ('Ovum', None),
    'a1-fruit': ('Fructus', None),
    'a1-vegetables': ('Holera', None),
    'a1-apple': ('Malum', None),
    'a1-sugar': ('Saccharum', None),
    'a1-salt': ('Sal', None),
    'a1-beer': ('Cervisia', None),
    'a1-wine': ('Vinum', None),
    'a1-juice': ('Sucus', None),
    'a1-breakfast': ('Ientaculum', None),
    'a1-lunch': ('Prandium', None),
    'a1-dinner': ('Cena', None),
    'a1-im-hungry': ('Esurio', None),
    'a1-im-thirsty': ('Sitio', None),
    'a1-cheese': ('Caseus', None),
    'a1-soup': ('Iusculum', None),
    'a1-sweet': ('Dulcis', None),
    'a1-food': ('Cibus', None),
    'a1-drink-noun': ('Potio', None),
    'a1-head': ('Caput', None),
    'a1-hand': ('Manus', None),
    'a1-eye': ('Oculus', None),
    'a1-foot': ('Pes', None),
    'a1-mouth': ('Os', None),
    'a1-nose': ('Nasus', None),
    'a1-ear': ('Auris', None),
    'a1-arm': ('Brachium', None),
    'a1-leg': ('Crus', None),
    'a1-heart': ('Cor', None),
    'a1-hair': ('Capillus', None),
    'a1-face': ('Facies', None),
    'a1-back-body': ('Tergum', None),
    'a1-stomach': ('Venter', None),
    'a1-tooth': ('Dens', None),
    'a1-finger': ('Digitus', None),
    'a1-body': ('Corpus', None),
    'a1-blood': ('Sanguis', None),
    'a1-neck': ('Collum', None),
    'a1-shoulder': ('Umerus', None),
    'a1-knee': ('Genu', None),
    'a1-skin': ('Cutis', None),
    'a1-shirt': ('Tunica', None),
    'a1-pants': ('Bracae', None),
    'a1-shoes': ('Calcei', None),
    'a1-dress': ('Stola', None),
    'a1-hat': ('Petasus', None),
    'a1-coat': ('Paenula', None),
    'a1-jacket': ('Tunicella', None),
    'a1-socks': ('Udones', None),
    'a1-skirt': ('Gunna', None),
    'a1-bag': ('Saccus', None),
    'a1-glasses': ('Perspicilla', None),
    'a1-watch-wrist': ('Horologium', None),
    'a1-umbrella': ('Umbraculum', None),
    'a1-to-wear': ('Gerere', None),
    'a1-sweater': ('Tunica lanea', None),
    'a1-t-shirt': ('Subucula', None),
    'a1-scarf': ('Focale', None),
    'a1-gloves': ('Manicae', None),
    'a1-clothes': ('Vestimenta', None),
    'a1-size': ('Magnitudo', None),
    'a1-to-be': ('Esse', None),
    'a1-to-have': ('Habere', None),
    'a1-to-do': ('Facere', None),
    'a1-to-go': ('Ire', None),
    'a1-to-come': ('Venire', None),
    'a1-to-want': ('Velle', None),
    'a1-to-be-able-to': ('Posse', None),
    'a1-to-know': ('Scire', None),
    'a1-to-see': ('Videre', None),
    'a1-to-say': ('Dicere', None),
    'a1-to-eat': ('Edere', None),
    'a1-to-drink': ('Bibere', None),
    'a1-to-sleep': ('Dormire', None),
    'a1-to-live': ('Vivere', None),
    'a1-to-work': ('Laborare', None),
    'a1-to-speak': ('Loqui', None),
    'a1-to-understand': ('Intellegere', None),
    'a1-to-like': ('Placere', None),
    'a1-to-need': ('Egere', None),
    'a1-to-give': ('Dare', None),
    'a1-to-take': ('Sumere', None),
    'a1-to-think': ('Cogitare', None),
    'a1-to-buy': ('Emere', None),
    'a1-to-help': ('Adiuvare', None),
    'a1-to-open': ('Aperire', None),
    'a1-to-close': ('Claudere', None),
    'a1-to-look-for': ('Quaerere', None),
    'a1-to-find': ('Invenire', None),
    'a1-to-wait': ('Exspectare', None),
    'a1-to-call-phone': ('Vocare', None),
    'a1-to-read': ('Legere', None),
    'a1-to-write': ('Scribere', None),
    'a1-to-listen': ('Audire', None),
    'a1-to-learn': ('Discere', None),
    'a1-to-play': ('Ludere', None),
    'a1-to-walk': ('Ambulare', None),
    'a1-to-run': ('Currere', None),
    'a1-to-sit': ('Sedere', None),
    'a1-to-stand': ('Stare', None),
    'a1-to-arrive': ('Pervenire', None),
    'a1-to-leave': ('Discedere', None),
    'a1-to-return': ('Redire', None),
    'a1-to-put': ('Ponere', None),
    'a1-to-bring': ('Afferre', None),
    'a1-to-ask': ('Rogare', None),
    'a1-to-answer': ('Respondere', None),
    'a1-to-love': ('Amare', None),
    'a1-to-pay': ('Solvere', None),
    'a1-good': ('Bonus', None),
    'a1-bad': ('Malus', None),
    'a1-new': ('Novus', None),
    'a1-old-thing': ('Vetus', None),
    'a1-young': ('Iuvenis', None),
    'a1-hot': ('Calidus', None),
    'a1-cold': ('Frigidus', None),
    'a1-happy': ('Felix', None),
    'a1-sad': ('Tristis', None),
    'a1-beautiful': ('Pulcher', None),
    'a1-ugly': ('Turpis', None),
    'a1-easy': ('Facilis', None),
    'a1-difficult': ('Difficilis', None),
    'a1-fast': ('Celer', None),
    'a1-slow': ('Tardus', None),
    'a1-cheap': ('Vilis', None),
    'a1-expensive': ('Carus', None),
    'a1-full': ('Plenus', None),
    'a1-empty': ('Vacuus', None),
    'a1-clean': ('Mundus', None),
    'a1-dirty': ('Sordidus', None),
    'a1-strong': ('Fortis', None),
    'a1-weak': ('Infirmus', None),
    'a1-important': ('Gravis', None),
    'a1-what': ('Quid', None),
    'a1-who': ('Quis', None),
    'a1-where': ('Ubi', None),
    'a1-when': ('Quando', None),
    'a1-why': ('Cur', None),
    'a1-how': ('Quomodo', None),
    'a1-how-many': ('Quot', None),
    'a1-which': ('Qui', None),
    'a1-and': ('Et', None),
    'a1-or': ('Aut', None),
    'a1-but': ('Sed', None),
    'a1-because': ('Quia', None),
    'a1-with': ('Cum', None),
    'a1-without': ('Sine', None),
    'a1-for': ('Pro', None),
    'a1-from': ('Ab', None),
    'a1-to-direction': ('Ad', None),
    'a1-in': ('In', None),
    'a1-on': ('Super', None),
    'a1-under': ('Sub', None),
    'a1-this': ('Hoc', None),
    'a1-that': ('Illud', None),
    'a1-very': ('Valde', None),
    'a1-also': ('Etiam', None),
    'a1-not': ('Non', None),
    'a1-maybe': ('Fortasse', None),
    'a1-sun': ('Sol', None),
    'a1-rain': ('Pluvia', None),
    'a1-snow': ('Nix', None),
    'a1-wind': ('Ventus', None),
    'a1-cloud': ('Nubes', None),
    'a1-weather': ('Tempestas', None),
    'a1-sky': ('Caelum', None),
    'a1-sea': ('Mare', None),
    'a1-mountain': ('Mons', None),
    'a1-river': ('Flumen', None),
    'a1-tree': ('Arbor', None),
    'a1-flower': ('Flos', None),
    'a1-dog': ('Canis', None),
    'a1-cat': ('Feles', None),
    'a1-bird': ('Avis', None),
    'a1-fish-animal': ('Piscis', None),
    'a1-horse': ('Equus', None),
    'a1-cow': ('Vacca', None),
    'a1-earth': ('Terra', None),
    'a1-moon': ('Luna', None),
    'a1-star': ('Stella', None),
    'a1-fire': ('Ignis', None),
    'a1-its-windy': ('Ventosum est', None),
    'a1-its-snowing': ('Ningit', None),
    'a1-its-cold-today': ('Hodie frigus est', None),
    'a1-its-hot-today': ('Hodie calor est', None),
    'a1-help': ('Succurre!', None),
    'a1-slowly-please': ('Lente, quaeso', None),
    'a1-do-you-speak-english': ('Loquerisne Anglice?', None),
    'a1-i-dont-know': ('Nescio', None),
    'a1-where-is-the-bathroom': ('Ubi est latrina?', None),
    'a1-which-way': ('Qua via?', None),
    'a1-one-moment-please': ('Momentum unum, quaeso', None),
    'a1-of-course': ('Certe', None),
    'a1-no-problem': ('Nihil est negotii', None),
    'a1-its-okay': ('Bene est', None),
    'a1-lets-go': ('Eamus', None),
    'a1-come-in': ('Intra', None),
    'a1-be-careful': ('Cave', None),
    'a1-can-you-help-me': ('Potesne me adiuvare?', None),
    'a1-what-does-that-mean': ('Quid hoc sibi vult?', None),
    'a1-can-you-repeat-that': ('Potesne id iterare?', None),
    'a1-slower-please': ('Lentius, quaeso', None),
    'a1-how-do-you-say': ('Quomodo dicis...?', None),
    'a1-i-would-like': ('Vellem...', None),
    'a1-the-bill-please': ('Rationem, quaeso', None),
    'a1-im-tired': ('Fessus sum', None),
    'a1-im-sick': ('Aeger sum', None),
    'a1-its-an-emergency': ('Res urgens est', None),
    'a1-call-the-police': ('Voca vigiles', None),
    'a1-i-speak-a-little': ('Paulum loquor', None),
    'a1-i-love-it': ('Id amo', None),
    'a1-whats-this': ('Quid est hoc?', None),
    'a1-i-agree': ('Consentio', None),
    'a1-i-dont-like-it': ('Id mihi non placet', None),
    'a1-really': ('Itane?', None),
    'a1-exactly': ('Prorsus', None),
    'a1-i-think-so': ('Ita puto', None),
    'a1-dont-worry': ('Noli sollicitari', None),
    'a1-just-a-little': ('Tantum paulum', None),
    'a1-wait-a-moment': ('Exspecta paulisper', None),
    'a1-is-this-seat-free': ('Estne haec sedes vacua?', None),
    'a1-money': ('Pecunia', None),
    'a1-price': ('Pretium', None),
    'a1-to-sell': ('Vendere', None),
    'a1-card': ('Tessera nummaria', None),
    'a1-cash': ('Pecunia numerata', None),
    'a1-receipt': ('Apocha', None),
    'a1-open-shop': ('Apertus', None),
    'a1-closed-shop': ('Clausus', None),
    'a1-free-no-cost': ('Gratuitus', None),
    'a1-discount': ('Deductio', None),
    'a1-how-much-is-it': ('Quanti constat?', None),
    'a1-too-much': ('Nimium', None),
    'a1-gift': ('Donum', None),
    'a1-change-coins': ('Nummi reliqui', None),
    'a1-supermarket': ('Macellum magnum', None),
    'a1-pharmacy': ('Pharmacopolium', None),
    'a1-bakery': ('Pistrina', None),
    'a1-is-this-on-sale': ('Estne hoc pretio deminuto?', None),
    'a1-car': ('Autocinetum', None),
    'a1-bus': ('Autoraeda', None),
    'a1-train': ('Hamaxostichus', None),
    'a1-plane': ('Aeroplanum', None),
    'a1-bicycle': ('Birota', None),
    'a1-taxi': ('Raeda meritoria', None),
    'a1-ticket': ('Tessera', None),
    'a1-station': ('Statio ferriviaria', None),
    'a1-airport': ('Aeriportus', None),
    'a1-road': ('Via', None),
    'a1-to-travel': ('Peregrinari', None),
    'a1-trip': ('Iter', None),
    'a1-map': ('Tabula geographica', None),
    'a1-stop-bus-stop': ('Statio autoraedae', None),
    'a1-to-drive': ('Vehiculum agere', None),
    'a1-subway': ('Hamaxostichus subterraneus', None),
    'a1-passport': ('Diploma', None),
    'a1-suitcase': ('Vidulus', None),
    'a1-exit': ('Exitus', None),
    'a1-entrance': ('Introitus', None),
    'a1-phone': ('Telephonum', None),
    'a1-book': ('Liber', None),
    'a1-pen': ('Stilus', None),
    'a1-paper': ('Charta', None),
    'a1-key': ('Clavis', None),
    'a1-computer': ('Computatrum', None),
    'a1-clock': ('Horologium', None),
    'a1-television': ('Televisorium', None),
    'a1-camera': ('Machina photographica', None),
    'a1-box': ('Arca', None),
    'a1-glass-cup': ('Calix', None),
    'a1-bottle': ('Lagoena', None),
    'a1-plate': ('Patina', None),
    'a1-knife': ('Culter', None),
    'a1-fork': ('Furcula', None),
    'a1-spoon': ('Cochlear', None),
    'a1-cup': ('Poculum', None),
    'a1-soap': ('Sapo', None),
    'a1-towel': ('Mantele', None),
    'a1-lamp': ('Lucerna', None),
    'a1-wallet': ('Crumena', None),
    'a1-charger': ('Carricator', None),
    'a1-thing': ('Res', None),
    'a1-toothbrush': ('Peniculus dentifricius', None),
    'a1-angry': ('Iratus', None),
    'a1-scared': ('Territus', None),
    'a1-bored': ('Taedio affectus', None),
    'a1-excited': ('Alacer', None),
    'a1-worried': ('Anxius', None),
    'a1-surprised': ('Attonitus', None),
    'a1-calm': ('Tranquillus', None),
    'a1-nervous': ('Trepidus', None),
    'a1-proud': ('Superbus', None),
    'a1-lonely': ('Solus', None),
    'a1-sleepy': ('Somniculosus', None),
    'a1-sick-unwell': ('Aeger', None),
    'a1-love': ('Amor', None),
    'a1-fear': ('Metus', None),
    'a1-joy': ('Gaudium', None),
    'a1-funny': ('Ridiculus', None),
    'a2-i-work-in-an-office': ('In officio laboro', None),
    'a2-i-am-a-student': ('Discipulus sum', None),
    'a2-i-have-a-meeting': ('Conventum habeo', None),
    'a2-i-am-looking-for-a-job': ('Opus quaero', None),
    'a2-i-am-studying': ('Studeo', None),
    'a2-i-dont-understand': ('Non intellego', None),
    'a2-how-much-is-this': ('Quanti hoc constat?', None),
    'a2-its-too-expensive': ('Nimis carum est', None),
    'a2-can-i-pay-by-card': ('Possumne tessera nummaria solvere?', None),
    'a2-do-you-have-a-discount': ('Habesne deductionem?', None),
    'a2-im-just-looking': ('Tantum specto', None),
    'a2-ill-take-it': ('Id sumam', None),
    'a2-where-is-the-train-station': ('Ubi est statio ferriviaria?', None),
    'a2-one-ticket-please': ('Unam tesseram, quaeso', None),
    'a2-how-do-i-get-to-the-airport': ('Quomodo ad aeriportum pervenio?', None),
    'a2-im-lost': ('Perditus sum', None),
    'a2-is-it-far': ('Estne longe?', None),
    'a2-where-is-the-restroom': ('Ubi est necessarium?', None),
    'a2-i-dont-feel-well': ('Non bene me habeo', None),
    'a2-i-have-a-headache': ('Caput mihi dolet', None),
    'a2-where-is-the-pharmacy': ('Ubi est pharmacopolium?', None),
    'a2-i-need-a-doctor': ('Medico mihi opus est', None),
    'a2-im-allergic-to-peanuts': ('Arachidas ferre non possum', None),
    'a2-it-hurts-here': ('Hic dolet', None),
    'a2-its-sunny': ('Sol lucet', None),
    'a2-its-raining': ('Pluit', None),
    'a2-i-like-to-read': ('Legere mihi placet', None),
    'a2-my-favorite-is-music': ('Quod maxime amo musica est', None),
    'a2-on-weekends-i-rest': ('Diebus feriatis quiesco', None),
    'a2-i-play-sports': ('Corporis exercitationibus vaco', None),
    'a2-what-time-is-it': ('Quota hora est?', None),
    'a2-lets-meet-tomorrow': ('Cras conveniamus', None),
    'a2-can-you-call-me': ('Potesne me vocare?', None),
    'a2-see-you-later': ('Mox te videbo', None),
    'a2-whats-your-phone-number': ('Quis est numerus tui telephonii?', None),
    'a2-im-busy-today': ('Hodie occupatus sum', None),
    'a2-job': ('Munus', None),
    'a2-boss': ('Dominus', None),
    'a2-colleague': ('Collega', None),
    'a2-salary': ('Merces', None),
    'a2-to-earn': ('Lucrari', None),
    'a2-class': ('Schola', None),
    'a2-teacher': ('Magister', None),
    'a2-exam': ('Examen', None),
    'a2-homework': ('Pensum', None),
    'a2-university': ('Universitas', None),
    'a2-to-teach': ('Docere', None),
    'a2-project': ('Inceptum', None),
    'a2-deadline': ('Dies ultimus', None),
    'a2-interview': ('Colloquium', None),
    'a2-career': ('Cursus', None),
    'a2-break-pause': ('Intermissio', None),
    'a2-schedule': ('Tabula horaria', None),
    'a2-company': ('Societas', None),
    'a2-customer': ('Emptor', None),
    'a2-unemployed': ('Otiosus', None),
    'a2-to-try-on': ('Induere', None),
    'a2-fitting-room': ('Cella vestiaria', None),
    'a2-sale-discount-event': ('Occasio', None),
    'a2-to-return-an-item': ('Reddere', None),
    'a2-refund': ('Restitutio', None),
    'a2-brand': ('Nota', None),
    'a2-quality': ('Qualitas', None),
    'a2-cashier': ('Numularius', None),
    'a2-shopping-cart': ('Corbis mercatoria', None),
    'a2-online-shopping': ('Emptio interretialis', None),
    'a2-to-order-online': ('Mandare', None),
    'a2-delivery': ('Traditio', None),
    'a2-package': ('Fasciculus', None),
    'a2-to-choose': ('Eligere', None),
    'a2-to-compare': ('Comparare', None),
    'a2-it-fits-me': ('Mihi convenit', None),
    'a2-too-big': ('Nimis magnum', None),
    'a2-do-you-have-it-in-another-color': ('Habesne id alio colore?', None),
    'a2-mall': ('Emporium', None),
    'a2-cheaper': ('Vilior', None),
    'a2-reservation': ('Reservatio', None),
    'a2-to-book': ('Reservare', None),
    'a2-check-in': ('Inscriptio', None),
    'a2-luggage': ('Sarcina', None),
    'a2-flight': ('Volatus', None),
    'a2-delay': ('Mora', None),
    'a2-departure': ('Profectio', None),
    'a2-arrival': ('Adventus', None),
    'a2-gate': ('Porta', None),
    'a2-seat': ('Sedile', None),
    'a2-tourist': ('Peregrinator', None),
    'a2-guide': ('Dux', None),
    'a2-sightseeing': ('Peregrinatio', None),
    'a2-souvenir': ('Monumentum', None),
    'a2-beach': ('Litus', None),
    'a2-museum': ('Museum', None),
    'a2-to-visit': ('Visere', None),
    'a2-round-trip': ('Iter ultro citroque', None),
    'a2-one-way': ('Iter simplex', None),
    'a2-abroad': ('Peregre', None),
    'a2-doctor': ('Medicus', None),
    'a2-nurse': ('Nutrix', None),
    'a2-medicine': ('Medicamentum', None),
    'a2-pain': ('Dolor', None),
    'a2-fever': ('Febris', None),
    'a2-cough': ('Tussis', None),
    'a2-a-cold-illness': ('Gravedo', None),
    'a2-flu': ('Influenza', None),
    'a2-allergy': ('Allergia', None),
    'a2-appointment': ('Constitutum', None),
    'a2-prescription': ('Praescriptio medica', None),
    'a2-stomachache': ('Dolor stomachi', None),
    'a2-healthy': ('Sanus', None),
    'a2-to-rest': ('Quiescere', None),
    'a2-insurance': ('Assecuratio', None),
    'a2-emergency': ('Discrimen', None),
    'a2-dentist': ('Medicus dentarius', None),
    'a2-injury': ('Vulnus', None),
    'a2-i-feel-better': ('Melius me habeo', None),
    'a2-blood-pressure': ('Pressio sanguinis', None),
    'a2-hobby': ('Studium', None),
    'a2-music': ('Musica', None),
    'a2-movie': ('Pellicula', None),
    'a2-sport': ('Certamen', None),
    'a2-soccer': ('Pediludium', None),
    'a2-to-swim': ('Natare', None),
    'a2-to-dance': ('Saltare', None),
    'a2-to-sing': ('Cantare', None),
    'a2-to-paint': ('Pingere', None),
    'a2-game': ('Ludus', None),
    'a2-team': ('Factio', None),
    'a2-to-win': ('Vincere', None),
    'a2-to-lose-a-game': ('Vinci', None),
    'a2-concert': ('Concentus', None),
    'a2-photography': ('Photographia', None),
    'a2-to-hike': ('Peragrare', None),
    'a2-gym': ('Gymnasium', None),
    'a2-to-exercise': ('Se exercere', None),
    'a2-cloudy': ('Nubilus', None),
    'a2-storm': ('Tempestas', None),
    'a2-humid': ('Humidus', None),
    'a2-forecast': ('Praedictio', None),
    'a2-to-plan': ('Destinare', None),
    'a2-to-meet-up': ('Convenire', None),
    'a2-invitation': ('Invitatio', None),
    'a2-to-invite': ('Invitare', None),
    'a2-to-cancel': ('Rescindere', None),
    'a2-free-time': ('Otium', None),
    'a2-to-postpone': ('Differre', None),
    'a2-internet': ('Interrete', None),
    'a2-email': ('Epistula electronica', None),
    'a2-message': ('Nuntius', None),
    'a2-to-send': ('Mittere', None),
    'a2-to-download': ('Deponere', None),
    'a2-app': ('Applicatio', None),
    'a2-password': ('Tessera', None),
    'a2-screen': ('Monitorium', None),
    'a2-wi-fi': ('Rete sine filo', None),
    'a2-website': ('Situs interretialis', None),
    'a2-video-call': ('Colloquium visuale', None),
    'a2-are-you-free-on-saturday': ('Esne liber die Saturni?', None),
    'a2-sounds-good': ('Placet', None),
    'a2-to-clean': ('Purgare', None),
    'a2-to-wash': ('Lavare', None),
    'a2-dishes': ('Vasa', None),
    'a2-laundry': ('Vestimenta lavanda', None),
    'a2-to-iron': ('Levigare', None),
    'a2-trash': ('Quisquiliae', None),
    'a2-to-tidy-up': ('Ordinare', None),
    'a2-vacuum-cleaner': ('Aspirator pulveris', None),
    'a2-to-repair': ('Reficere', None),
    'a2-to-move-house': ('Domicilium mutare', None),
    'a2-rent': ('Pensio', None),
    'a2-landlord': ('Dominus', None),
    'a2-apartment': ('Cenaculum', None),
    'a2-furniture': ('Supellex', None),
    'a2-sofa': ('Sedes mollis', None),
    'a2-fridge': ('Frigidarium', None),
    'a2-oven': ('Furnus', None),
    'a2-stove': ('Focus', None),
    'a2-shower': ('Balneum pluviale', None),
    'a2-mirror': ('Speculum', None),
    'a2-pillow': ('Pulvinus', None),
    'a2-blanket': ('Stragulum', None),
    'a2-washing-machine': ('Machina lavatoria', None),
    'a2-roommate': ('Contubernalis', None),
    'a2-stairs': ('Scalae', None),
    'a2-elevator': ('Ascensorium', None),
    'a2-to-wake-up': ('Expergisci', None),
    'a2-to-get-up': ('Surgere', None),
    'a2-to-take-a-shower': ('Se abluere', None),
    'a2-to-brush-ones-teeth': ('Dentes fricare', None),
    'a2-to-get-dressed': ('Se vestire', None),
    'a2-to-have-breakfast': ('Ientare', None),
    'a2-to-commute': ('Iter ad opus facere', None),
    'a2-to-go-home': ('Domum redire', None),
    'a2-to-relax': ('Se relaxare', None),
    'a2-to-watch-tv': ('Televisionem spectare', None),
    'a2-to-go-to-bed': ('Cubitum ire', None),
    'a2-routine': ('Consuetudo', None),
    'a2-habit': ('Mos', None),
    'a2-alarm-clock': ('Horologium excitatorium', None),
    'a2-to-be-late': ('Sero venire', None),
    'a2-to-hurry': ('Festinare', None),
    'a2-on-time': ('Tempestive', None),
    'a2-nap': ('Somnus meridianus', None),
    'a2-to-take-a-walk': ('Deambulare', None),
    'a2-to-have-lunch': ('Prandere', None),
    'a2-to-have-dinner': ('Cenare', None),
    'a2-to-fall-asleep': ('Obdormire', None),
    'a2-every-day': ('Cotidie', None),
    'a2-usually': ('Plerumque', None),
    'a2-corner': ('Angulus', None),
    'a2-block': ('Insula', None),
    'a2-traffic-light': ('Semaphorum', None),
    'a2-bridge': ('Pons', None),
    'a2-square-plaza': ('Forum', None),
    'a2-downtown': ('Media urbs', None),
    'a2-neighborhood': ('Vicinia', None),
    'a2-building': ('Aedificium', None),
    'a2-sidewalk': ('Semita', None),
    'a2-to-cross': ('Transire', None),
    'a2-to-turn': ('Flectere', None),
    'a2-address': ('Inscriptio', None),
    'a2-post-office': ('Officina postalis', None),
    'a2-library': ('Bibliotheca', None),
    'a2-cinema': ('Theatrum cinematographicum', None),
    'a2-theater': ('Theatrum', None),
    'a2-stadium': ('Stadium', None),
    'a2-police-station': ('Statio vigilum', None),
    'a2-town-hall': ('Curia', None),
    'a2-parking-lot': ('Statio autocinetorum', None),
    'a2-gas-station': ('Statio benzinaria', None),
    'a2-traffic': ('Commeatus', None),
    'a2-opposite': ('Contra', None),
    'a2-next-to': ('Iuxta', None),
    'a2-between': ('Inter', None),
    'a2-how-do-i-get-to': ('Quomodo pervenio ad...?', None),
    'a2-menu': ('Index ciborum', None),
    'a2-waiter': ('Minister', None),
    'a2-dish': ('Ferculum', None),
    'a2-dessert': ('Secunda mensa', None),
    'a2-starter': ('Gustatio', None),
    'a2-main-course': ('Mensa prima', None),
    'a2-vegetarian': ('Vegetarianus', None),
    'a2-tip': ('Stips', None),
    'a2-to-cook': ('Coquere', None),
    'a2-recipe': ('Praeceptum culinarium', None),
    'a2-ingredient': ('Ingrediens', None),
    'a2-oil': ('Oleum', None),
    'a2-butter': ('Butyrum', None),
    'a2-pepper': ('Piper', None),
    'a2-onion': ('Cepa', None),
    'a2-garlic': ('Allium', None),
    'a2-tomato': ('Lycopersicum', None),
    'a2-potato': ('Malum terrestre', None),
    'a2-noodles': ('Lagana', None),
    'a2-sauce': ('Ius', None),
    'a2-to-bake': ('Furno coquere', None),
    'a2-to-fry': ('Frigere', None),
    'a2-to-boil': ('Elixare', None),
    'a2-a-table-for-two': ('Mensa duobus hominibus', None),
    'a2-takeout': ('Cibus asportandus', None),
    'a2-snack': ('Merenda', None),
    'a2-salty': ('Salsus', None),
    'a2-bitter': ('Amarus', None),
    'a2-tall': ('Procerus', None),
    'a2-short-height': ('Brevis', None),
    'a2-thin': ('Gracilis', None),
    'a2-overweight': ('Obesus', None),
    'a2-blond': ('Flavus', None),
    'a2-dark-haired': ('Fuscus', None),
    'a2-beard': ('Barba', None),
    'a2-kind': ('Benignus', None),
    'a2-nice-person': ('Comis', None),
    'a2-shy': ('Verecundus', None),
    'a2-talkative': ('Loquax', None),
    'a2-smart': ('Ingeniosus', None),
    'a2-lazy': ('Piger', None),
    'a2-hardworking': ('Industrius', None),
    'a2-polite': ('Urbanus', None),
    'a2-rude': ('Rusticus', None),
    'a2-patient': ('Patiens', None),
    'a2-honest': ('Probus', None),
    'a2-serious': ('Gravis', None),
    'a2-quiet-person': ('Taciturnus', None),
    'a2-friendly': ('Benevolus', None),
    'a2-handsome': ('Formosus', None),
    'a2-age': ('Aetas', None),
    'a2-old-person': ('Senex', None),
    'a2-curly-hair': ('Capilli crispi', None),
    'a2-cheerful': ('Hilaris', None),
    'a2-stubborn': ('Pertinax', None),
    'a2-generous': ('Liberalis', None),
    'a2-to-try': ('Conari', None),
    'a2-to-start': ('Incipere', None),
    'a2-to-finish': ('Finire', None),
    'a2-to-change': ('Mutare', None),
    'a2-to-use': ('Uti', None),
    'a2-to-receive': ('Accipere', None),
    'a2-to-decide': ('Constituere', None),
    'a2-to-forget': ('Oblivisci', None),
    'a2-to-remember': ('Meminisse', None),
    'a2-to-lose-an-object': ('Amittere', None),
    'a2-to-meet-someone-new': ('Cognoscere', None),
    'a2-to-prefer': ('Malle', None),
    'a2-to-hope': ('Sperare', None),
    'a2-to-believe': ('Credere', None),
    'a2-to-feel': ('Sentire', None),
    'a2-to-seem': ('Videri', None),
    'a2-to-happen': ('Accidere', None),
    'a2-to-stay': ('Manere', None),
    'a2-to-spend-money': ('Impendere', None),
    'a2-to-show': ('Ostendere', None),
    'a2-to-explain': ('Explicare', None),
    'a2-to-follow': ('Sequi', None),
    'a2-to-keep': ('Servare', None),
    'a2-to-allow': ('Permittere', None),
    'a2-to-become': ('Fieri', None),
    'a2-to-continue': ('Pergere', None),
    'a2-to-cut': ('Secare', None),
    'a2-to-break': ('Frangere', None),
    'a2-to-fly': ('Volare', None),
    'a2-to-draw': ('Designare', None),
    'a2-to-carry': ('Portare', None),
    'a2-to-push': ('Trudere', None),
    'a2-to-pull': ('Trahere', None),
    'a2-to-throw': ('Iacere', None),
    'a2-to-catch': ('Capere', None),
    'a2-to-build': ('Aedificare', None),
    'a2-to-grow': ('Crescere', None),
    'a2-to-fall': ('Cadere', None),
    'a2-to-climb': ('Scandere', None),
    'a2-to-jump': ('Salire', None),
    'a2-to-laugh': ('Ridere', None),
    'a2-to-cry': ('Flere', None),
    'a2-to-smile': ('Subridere', None),
    'a2-to-shout': ('Clamare', None),
    'a2-to-whisper': ('Susurrare', None),
    'a2-to-hug': ('Amplecti', None),
    'a2-to-kiss': ('Osculari', None),
    'a2-to-touch': ('Tangere', None),
    'a2-to-smell': ('Olfacere', None),
    'a2-to-taste': ('Gustare', None),
    'a2-to-wash-oneself': ('Lavari', None),
    'a2-to-hide': ('Celare', None),
    'a2-interesting': ('Iucundus', None),
    'a2-boring': ('Odiosus', None),
    'a2-comfortable': ('Commodus', None),
    'a2-dangerous': ('Periculosus', None),
    'a2-safe': ('Tutus', None),
    'a2-noisy': ('Clamosus', None),
    'a2-busy': ('Occupatus', None),
    'a2-heavy': ('Gravis', None),
    'a2-light-weight': ('Levis', None),
    'a2-wide': ('Latus', None),
    'a2-narrow': ('Angustus', None),
    'a2-soft': ('Mollis', None),
    'a2-hard-firm': ('Durus', None),
    'a2-wet': ('Umidus', None),
    'a2-dry': ('Siccus', None),
    'a2-rich': ('Dives', None),
    'a2-poor': ('Pauper', None),
    'a2-famous': ('Clarus', None),
    'a2-popular': ('Popularis', None),
    'a2-modern': ('Modernus', None),
    'a2-traditional': ('Traditionalis', None),
    'a2-ready': ('Paratus', None),
    'a2-sure': ('Certus', None),
    'a2-wrong': ('Falsus', None),
    'a2-correct': ('Rectus', None),
    'a2-strange': ('Mirus', None),
    'a2-same': ('Idem', None),
    'a2-different': ('Diversus', None),
    'a2-last-week': ('Hebdomade superiore', None),
    'a2-next-week': ('Hebdomade proxima', None),
    'a2-this-month': ('Hoc mense', None),
    'a2-last-year': ('Anno superiore', None),
    'a2-next-year': ('Anno proximo', None),
    'a2-at-the-end': ('Ad extremum', None),
    'a2-at-the-beginning': ('Principio', None),
    'a2-twice': ('Bis', None),
    'a2-once': ('Semel', None),
    'a2-in-a-hurry': ('Festinans', None),
    'a2-for-a-long-time': ('Diu', None),
    'a2-recently': ('Nuper', None),
    'a2-already': ('Iam', None),
    'a2-still': ('Adhuc', None),
    'a2-not-yet': ('Nondum', None),
    'a2-until': ('Donec', None),
    'a2-since': ('Ex quo', None),
    'a2-during': ('Per', None),
    'a2-ago': ('Abhinc', None),
    'a2-at-least': ('Saltem', None),
    'a2-right-away': ('Statim', None),
    'a2-finally': ('Tandem', None),
    'a2-suddenly': ('Subito', None),
    'a2-the-day-after-tomorrow': ('Perendie', None),
    'a2-conversation': ('Sermo', None),
    'a2-question': ('Interrogatio', None),
    'a2-answer-noun': ('Responsum', None),
    'a2-opinion': ('Opinio', None),
    'a2-to-describe': ('Describere', None),
    'a2-to-promise': ('Promittere', None),
    'a2-to-suggest': ('Proponere', None),
    'a2-to-complain': ('Queri', None),
    'a2-to-apologize': ('Se excusare', None),
    'a2-to-thank': ('Gratias agere', None),
    'a2-joke': ('Iocus', None),
    'a2-story': ('Fabula', None),
    'a2-news': ('Nuntius', None),
    'a2-to-argue': ('Rixari', None),
    'a2-to-discuss': ('Disputare', None),
    'a2-secret': ('Secretum', None),
    'a2-to-mean': ('Significare', None),
    'a2-to-pronounce': ('Pronuntiare', None),
    'a2-to-translate': ('Vertere', None),
    'a2-word': ('Verbum', None),
    'a2-sentence': ('Sententia', None),
    'a2-language': ('Lingua', None),
    'a2-to-spell': ('Litterare', None),
    'a2-to-lie': ('Mentiri', None),
    'a2-truth': ('Veritas', None),
    'a2-to-chat': ('Confabulari', None),
    'a2-accent': ('Accentus', None),
    'a2-fluent': ('Profluens', None),
    'a2-to-get-married': ('Matrimonium contrahere', None),
    'a2-wedding': ('Nuptiae', None),
    'a2-couple': ('Coniuges', None),
    'a2-childhood': ('Pueritia', None),
    'a2-teenager': ('Adulescens', None),
    'a2-adult': ('Adultus', None),
    'a2-to-grow-up': ('Adolescere', None),
    'a2-anniversary': ('Anniversarium', None),
    'a2-party': ('Convivium', None),
    'a2-guest': ('Hospes', None),
    'a2-to-celebrate': ('Celebrare', None),
    'a2-to-be-born': ('Nasci', None),
    'a2-to-die': ('Mori', None),
    'a2-relatives': ('Cognati', None),
    'a2-twins': ('Gemini', None),
    'a2-only-child': ('Filius unicus', None),
    'a2-to-take-care-of': ('Curare', None),
    'a2-nephew': ('Nepos ex fratre', None),
    'a2-niece': ('Neptis', None),
    'a2-grandchild': ('Nepos', None),
    'a2-single': ('Caelebs', None),
    'a2-divorced': ('Repudiatus', None),
    'a2-christmas': ('Nativitas', None),
    'a2-new-year': ('Annus Novus', None),
    'a2-cake': ('Placenta', None),
    'a2-candle': ('Candela', None),
    'a2-lesson': ('Lectio', None),
    'a2-course': ('Cursus', None),
    'a2-to-practice': ('Exercere', None),
    'a2-mistake': ('Error', None),
    'a2-to-correct': ('Corrigere', None),
    'a2-grade-mark': ('Nota', None),
    'a2-to-pass-an-exam': ('Superare', None),
    'a2-to-fail-an-exam': ('Deficere', None),
    'a2-to-graduate': ('Graduari', None),
    'a2-degree': ('Gradus', None),
    'a2-subject': ('Disciplina', None),
    'a2-math': ('Mathematica', None),
    'a2-history': ('Historia', None),
    'a2-science': ('Scientia', None),
    'a2-art': ('Ars', None),
    'a2-dictionary': ('Dictionarium', None),
    'a2-notebook': ('Pugillares', None),
    'a2-to-memorize': ('Ediscere', None),
    'a2-to-review': ('Repetere', None),
    'a2-classroom': ('Schola', None),
    'a2-semester': ('Semestre', None),
    'a2-scholarship': ('Stipendium', None),
    'a2-to-register': ('Nomen dare', None),
    'a2-example': ('Exemplum', None),
    'a2-level': ('Ordo', None),
    'a2-beginner': ('Tiro', None),
    'a2-to-save-money': ('Reponere', None),
    'a2-bank-account': ('Ratio argentaria', None),
    'a2-to-withdraw': ('Tollere', None),
    'a2-to-deposit': ('Deponere', None),
    'a2-atm': ('Machina nummaria', None),
    'a2-loan': ('Mutuum', None),
    'a2-debt': ('Debitum', None),
    'a2-to-borrow': ('Mutuari', None),
    'a2-to-lend': ('Commodare', None),
    'a2-to-owe': ('Debere', None),
    'a2-tax': ('Tributum', None),
    'a2-bill-utility': ('Ratio', None),
    'a2-budget': ('Ratio sumptuum', None),
    'a2-to-afford': ('Sufficere', None),
    'a2-interest-bank': ('Fenus', None),
    'a2-coin': ('Nummus', None),
    'a2-to-exchange-money': ('Permutare', None),
    'a2-exchange-rate': ('Ratio permutationis', None),
    'a2-credit-card': ('Tessera creditoria', None),
    'a2-to-cost': ('Constare', None),
    'a2-salary-raise': ('Salarii augmentum', None),
    'a2-expensive-habit': ('Consuetudo sumptuosa', None),
    'a2-invoice': ('Syngrapha', None),
    'a2-payment': ('Solutio', None),
    'a2-to-miss-someone': ('Desiderare', None),
    'a2-to-worry': ('Sollicitari', None),
    'a2-to-enjoy': ('Frui', None),
    'a2-to-hate': ('Odisse', None),
    'a2-to-be-afraid-of': ('Timere', None),
    'a2-ashamed': ('Pudibundus', None),
    'a2-jealous': ('Invidus', None),
    'a2-embarrassed': ('Perturbatus', None),
    'a2-disappointed': ('Frustratus', None),
    'a2-grateful': ('Gratus', None),
    'a2-relieved': ('Levatus', None),
    'a2-confused': ('Confusus', None),
    'a2-curious': ('Curiosus', None),
    'a2-hopeful': ('Sperans', None),
    'a2-frustrated': ('Vexatus', None),
    'a2-stressed': ('Anxius', None),
    'a2-in-a-good-mood': ('Hilaris', None),
    'a2-in-a-bad-mood': ('Morosus', None),
    'a2-to-cheer-up': ('Exhilarari', None),
    'a2-to-calm-down': ('Sedari', None),
    'a2-to-get-angry': ('Irasci', None),
    'a2-to-fall-in-love': ('Adamare', None),
    'a2-mood': ('Animus', None),
    'a2-satisfied': ('Contentus', None),
    'a2-forest': ('Silva', None),
    'a2-lake': ('Lacus', None),
    'a2-island': ('Insula', None),
    'a2-desert': ('Desertum', None),
    'a2-field': ('Ager', None),
    'a2-farm': ('Villa', None),
    'a2-animal': ('Animal', None),
    'a2-insect': ('Insectum', None),
    'a2-mosquito': ('Culex', None),
    'a2-bee': ('Apis', None),
    'a2-butterfly': ('Papilio', None),
    'a2-snake': ('Serpens', None),
    'a2-lion': ('Leo', None),
    'a2-elephant': ('Elephantus', None),
    'a2-monkey': ('Simia', None),
    'a2-rabbit': ('Cuniculus', None),
    'a2-pig': ('Porcus', None),
    'a2-sheep': ('Ovis', None),
    'a2-plant': ('Planta', None),
    'a2-grass': ('Gramen', None),
    'a2-leaf': ('Folium', None),
    'a2-rock': ('Saxum', None),
    'a2-sand': ('Arena', None),
    'a2-ocean': ('Oceanus', None),
    'a2-wave': ('Unda', None),
    'a2-thunder': ('Tonitrus', None),
    'a2-fog': ('Nebula', None),
    'a2-temperature': ('Temperies', None),
    'a2-laptop': ('Computatrum gestabile', None),
    'a2-keyboard': ('Claviatura', None),
    'a2-printer': ('Impressor', None),
    'a2-file': ('Plica', None),
    'a2-folder': ('Fasciculus', None),
    'a2-to-print': ('Imprimere', None),
    'a2-to-click': ('Clicare', None),
    'a2-to-type': ('Dactylographare', None),
    'a2-to-search-online': ('In interrete quaerere', None),
    'a2-social-media': ('Retia socialia', None),
    'a2-to-post': ('Publicare', None),
    'a2-to-share': ('Communicare', None),
    'a2-video': ('Video', None),
    'a2-photo': ('Photographema', None),
    'a2-selfie': ('Ipsephotographema', None),
    'a2-headphones': ('Auricularia', None),
    'a2-speaker': ('Sonificator', None),
    'a2-battery': ('Pila electrica', None),
    'a2-to-turn-on': ('Accendere', None),
    'a2-to-turn-off': ('Exstinguere', None),
    'a2-volume': ('Sonoritas', None),
    'a2-channel': ('Canalis', None),
    'a2-podcast': ('Podcastum', None),
    'a2-screenshot': ('Imago scrinii', None),
    'a2-update': ('Renovatio', None),
    'a2-notification': ('Nuntiatio', None),
    'a2-to-log-in': ('Ingredi', None),
    'a2-subtitles': ('Subtitula', None),
    'a2-what-do-you-think': ('Quid censes?', None),
    'a2-it-depends': ('Pendet', None),
    'a2-im-not-sure': ('Non certus sum', None),
    'a2-let-me-think': ('Sine me cogitare', None),
    'a2-what-a-pity': ('Quam dolendum est!', None),
    'a2-never-mind': ('Nihil refert', None),
    'a2-hurry-up': ('Festina', None),
    'a2-watch-out': ('Cave!', None),
    'a2-thats-a-good-idea': ('Bonum consilium est', None),
    'a2-are-you-kidding': ('Num iocaris?', None),
    'a2-its-up-to-you': ('Tuum est', None),
    'a2-im-on-my-way': ('Iam venio', None),
    'a2-same-here': ('Idem mihi', None),
    'a2-me-neither': ('Nec ego', None),
    'a2-by-the-way': ('Obiter', None),
    'a2-in-my-opinion': ('Mea sententia', None),
    'a2-to-be-honest': ('Ut vere dicam', None),
    'a2-actually': ('Re vera', None),
    'a2-anyway': ('Utcumque', None),
    'a2-for-example': ('Exempli gratia', None),
    'a2-sorry-im-late': ('Ignosce tarditati meae', None),
    'a2-no-way': ('Nullo modo!', None),
    'a2-that-makes-sense': ('Hoc rationem habet', None),
    'a2-good-point': ('Bene dictum', None),
    'a2-banana': ('Musa', None),
    'a2-orange-fruit': ('Aurantium', None),
    'a2-grapes': ('Uvae', None),
    'a2-strawberry': ('Fragum', None),
    'a2-lemon': ('Malum citreum', None),
    'a2-watermelon': ('Citrullus', None),
    'a2-peach': ('Persicum', None),
    'a2-pear': ('Pirum', None),
    'a2-carrot': ('Carota', None),
    'a2-lettuce': ('Lactuca', None),
    'a2-cucumber': ('Cucumis', None),
    'a2-bell-pepper': ('Capsicum', None),
    'a2-mushroom': ('Fungus', None),
    'a2-corn': ('Maizium', None),
    'a2-beans': ('Fabae', None),
    'a2-spinach': ('Spinacia', None),
    'a2-cabbage': ('Brassica', None),
    'a2-pumpkin': ('Cucurbita', None),
    'a2-nuts': ('Nuces', None),
    'a2-coconut': ('Nux Indica', None),
    'a2-mango': ('Mangifera', None),
    'a2-pineapple': ('Ananas', None),
    'a2-cherry': ('Cerasum', None),
    'a2-avocado': ('Persea', None),
    'a2-ripe': ('Maturus', None),
    'a2-fresh': ('Recens', None),
    'a2-kilogram': ('Chiliogramma', None),
    'a2-gram': ('Gramma', None),
    'a2-liter': ('Litra', None),
    'a2-meter': ('Metrum', None),
    'a2-kilometer': ('Chiliometrum', None),
    'a2-centimeter': ('Centimetrum', None),
    'a2-piece': ('Frustum', None),
    'a2-slice': ('Offula', None),
    'a2-dozen': ('Duodecas', None),
    'a2-pair': ('Par', None),
    'a2-percent': ('Centesima pars', None),
    'a2-degree-temperature': ('Gradus', None),
    'a2-a-bit': ('Paulum', None),
    'a2-a-lot': ('Multum', None),
    'a2-several': ('Nonnulli', None),
    'a2-double': ('Duplex', None),
    'a2-weight': ('Pondus', None),
    'a2-height': ('Altitudo', None),
    'a2-length': ('Longitudo', None),
    'a2-distance': ('Distantia', None),
    'a2-speed': ('Velocitas', None),
    'a2-total': ('Summa', None),
    'a2-almost': ('Paene', None),
    'a2-only': ('Solum', None),
    'a2-engineer': ('Machinator', None),
    'a2-lawyer': ('Advocatus', None),
    'a2-chef': ('Coquus', None),
    'a2-driver': ('Auriga', None),
    'a2-farmer': ('Agricola', None),
    'a2-artist': ('Artifex', None),
    'a2-musician': ('Musicus', None),
    'a2-actor': ('Actor', None),
    'a2-writer': ('Scriptor', None),
    'a2-journalist': ('Diurnarius', None),
    'a2-police-officer': ('Vigil', None),
    'a2-firefighter': ('Extinctor incendiorum', None),
    'a2-scientist': ('Physicus', None),
    'a2-programmer': ('Programmator', None),
    'a2-designer': ('Designator', None),
    'a2-manager': ('Procurator', None),
    'a2-salesperson': ('Mercator', None),
    'a2-mechanic': ('Faber', None),
    'a2-electrician': ('Electricarius', None),
    'a2-plumber': ('Plumbarius', None),
    'a2-pilot': ('Gubernator', None),
    'a2-accountant': ('Rationarius', None),
    'a2-architect': ('Architectus', None),
    'a2-hairdresser': ('Tonsor', None),
    'a2-soldier': ('Miles', None),
    'a2-baker': ('Pistor', None),
    'a2-basketball': ('Follis canistrifer', None),
    'a2-tennis': ('Tennis', None),
    'a2-baseball': ('Pila basica', None),
    'a2-volleyball': ('Follis volatilis', None),
    'a2-running': ('Cursus', None),
    'a2-cycling': ('Birotatio', None),
    'a2-skiing': ('Lusus schiorum', None),
    'a2-surfing': ('Fluctuum lusus', None),
    'a2-yoga': ('Yoga', None),
    'a2-chess': ('Scacchi', None),
    'a2-cards-game': ('Chartae lusoriae', None),
    'a2-board-game': ('Ludus tabularius', None),
    'a2-video-game': ('Ludus electronicus', None),
    'a2-puzzle': ('Aenigma', None),
    'a2-to-go-camping': ('Sub tentorio pernoctare', None),
    'a2-picnic': ('Prandium rusticum', None),
    'a2-fishing': ('Piscatus', None),
    'a2-race': ('Certamen', None),
    'a2-competition': ('Aemulatio', None),
    'a2-referee': ('Arbiter', None),
    'a2-coach': ('Exercitator', None),
    'a2-medal': ('Numisma', None),
    'a2-score': ('Puncta', None),
    'a2-fan-supporter': ('Fautor', None),
    'a2-to-train': ('Exercere', None),
}
