# -*- coding: utf-8 -*-
LANG = 'el'
WORDS = {
    'b2-honesty': ('Τιμιότητα', 'timiótita'),
    'b2-integrity': ('Ακεραιότητα', 'akereótita'),
    'b2-dignity': ('Αξιοπρέπεια', 'axioprépia'),
    'b2-morality': ('Ηθική', 'ithikí'),
    'b2-principle': ('Αρχή', 'arhí'),
    'b2-virtue': ('Αρετή', 'aretí'),
    'b2-vice': ('Ελάττωμα', 'eláttoma'),
    'b2-greed': ('Απληστία', 'aplistía'),
    'b2-courage': ('Θάρρος', 'thárros'),
    'b2-cowardice': ('Δειλία', 'dilía'),
    'b2-generosity': ('Γενναιοδωρία', 'gennaiodoría'),
    'b2-gratitude': ('Ευγνωμοσύνη', 'evgnomosýni'),
    'b2-compassion': ('Συμπόνια', 'sympónia'),
    'b2-tolerance': ('Ανοχή', 'anohí'),
    'b2-prejudice': ('Προκατάληψη', 'prokatálipsi'),
    'b2-discrimination': ('Διάκριση', 'diákrisi'),
    'b2-equality': ('Ισότητα', 'isótita'),
    'b2-inequality': ('Ανισότητα', 'anisótita'),
    'b2-fairness': ('Δικαιοσύνη', 'dikaiosýni'),
    'b2-corruption': ('Διαφθορά', 'diafthorá'),
    'b2-temptation': ('Πειρασμός', 'peirasmós'),
    'b2-guilt': ('Ενοχή', 'enohí'),
    'b2-shame': ('Ντροπή', 'dropí'),
    'b2-pride-self-respect': ('Περηφάνια', 'perifánia'),
    'b2-humility': ('Ταπεινότητα', 'tapeinótita'),
    'b2-ambition': ('Φιλοδοξία', 'filodoxía'),
    'b2-patience': ('Υπομονή', 'ypomoní'),
    'b2-sacrifice': ('Θυσία', 'thysía'),
    'b2-duty': ('Καθήκον', 'kathíkon'),
    'b2-conscience': ('Συνείδηση', 'syneídisi'),
    'b2-hypocrisy': ('Υποκρισία', 'ypokrisía'),
    'b2-forgiveness': ('Συγχώρεση', 'synhóresi'),
    'b2-agenda': ('Ημερήσια διάταξη', 'imerísia diátaxi'),
    'b2-minutes-of-a-meeting': ('Πρακτικά', 'praktiká'),
    'b2-department': ('Τμήμα', 'tmíma'),
    'b2-branch-office': ('Υποκατάστημα', 'ypokatástima'),
    'b2-headquarters': ('Έδρα', 'édra'),
    'b2-revenue': ('Έσοδα', 'ésoda'),
    'b2-stakeholder': ('Ενδιαφερόμενο μέρος', 'endiaferómeno méros'),
    'b2-shareholder': ('Μέτοχος', 'métohos'),
    'b2-client': ('Πελάτης', 'pelátis'),
    'b2-supplier': ('Προμηθευτής', 'promithevtís'),
    'b2-quote-price-estimate': ('Προσφορά τιμής', 'prosforá timís'),
    'b2-proposal': ('Πρόταση', 'prótasi'),
    'b2-bid': ('Προσφορά διαγωνισμού', 'prosforá diagonismoú'),
    'b2-merger': ('Συγχώνευση', 'synhónevsi'),
    'b2-layoff': ('Απόλυση', 'apólysi'),
    'b2-to-outsource': ('Εξωτερικεύω', 'exoterikévo'),
    'b2-to-delegate': ('Αναθέτω', 'anathéto'),
    'b2-to-supervise': ('Επιβλέπω', 'epivlépo'),
    'b2-performance-review': ('Αξιολόγηση απόδοσης', 'axiológisi apódosis'),
    'b2-strategy': ('Στρατηγική', 'stratigikí'),
    'b2-target': ('Στόχος', 'stóhos'),
    'b2-quarter-business': ('Τρίμηνο', 'trímino'),
    'b2-benchmark': ('Σημείο αναφοράς', 'simeío anaforás'),
    'b2-to-brainstorm': ('Κάνω καταιγισμό ιδεών', 'káno kataigismó ideón'),
    'b2-to-network': ('Δικτυώνομαι', 'diktyónome'),
    'b2-to-prioritize': ('Δίνω προτεραιότητα', 'díno proteraiótita'),
    'b2-to-streamline': ('Απλοποιώ', 'aplopoió'),
    'b2-startup': ('Νεοφυής επιχείρηση', 'neofyís epihírisi'),
    'b2-entrepreneur': ('Επιχειρηματίας', 'epihirimatías'),
    'b2-profit-margin': ('Περιθώριο κέρδους', 'perithório kérdous'),
    'b2-competitor': ('Ανταγωνιστής', 'antagonistís'),
    'b2-milestone-project': ('Ορόσημο', 'orósimo'),
    'b2-suspect': ('Ύποπτος', 'ýpoptos'),
    'b2-witness': ('Μάρτυρας', 'mártyras'),
    'b2-victim': ('Θύμα', 'thýma'),
    'b2-trial': ('Δίκη', 'díki'),
    'b2-judge': ('Δικαστής', 'dikastís'),
    'b2-jury': ('Ένορκοι', 'énorkoi'),
    'b2-verdict': ('Ετυμηγορία', 'etymigoría'),
    'b2-convicted': ('Καταδικασμένος', 'katadikasménos'),
    'b2-innocent': ('Αθώος', 'athóos'),
    'b2-prison-sentence': ('Ποινή φυλάκισης', 'poiní fylákisis'),
    'b2-theft': ('Κλοπή', 'klopí'),
    'b2-robbery': ('Ληστεία', 'listía'),
    'b2-burglary': ('Διάρρηξη', 'diárrixi'),
    'b2-fraud': ('Απάτη', 'apáti'),
    'b2-bribery': ('Δωροδοκία', 'dorodokía'),
    'b2-assault': ('Επίθεση', 'epíthesi'),
    'b2-murder': ('Δολοφονία', 'dolofonía'),
    'b2-kidnapping': ('Απαγωγή', 'apagogí'),
    'b2-smuggling': ('Λαθρεμπόριο', 'lathrempório'),
    'b2-to-arrest': ('Συλλαμβάνω', 'syllamváno'),
    'b2-to-charge-with-a-crime': ('Κατηγορώ', 'katigoró'),
    'b2-to-sue': ('Μηνύω', 'minýo'),
    'b2-lawsuit': ('Αγωγή', 'agogí'),
    'b2-court': ('Δικαστήριο', 'dikastírio'),
    'b2-prosecutor': ('Εισαγγελέας', 'eisangeléas'),
    'b2-defense-legal': ('Υπεράσπιση', 'yperáspisi'),
    'b2-appeal-legal': ('Έφεση', 'éfesi'),
    'b2-bail': ('Εγγύηση', 'engýisi'),
    'b2-alibi': ('Άλλοθι', 'állothi'),
    'b2-custody-police': ('Κράτηση', 'krátisi'),
    'b2-investigation': ('Έρευνα', 'érevna'),
    'b2-detective': ('Ντετέκτιβ', 'detektiv'),
    'b2-experiment': ('Πείραμα', 'peírama'),
    'b2-hypothesis': ('Υπόθεση', 'ypóthesi'),
    'b2-theory': ('Θεωρία', 'theoría'),
    'b2-data': ('Δεδομένα', 'dedoména'),
    'b2-analysis': ('Ανάλυση', 'análysi'),
    'b2-to-analyze': ('Αναλύω', 'analýo'),
    'b2-to-measure': ('Μετρώ', 'metró'),
    'b2-laboratory': ('Εργαστήριο', 'ergastírio'),
    'b2-chemical': ('Χημικός', 'himikós'),
    'b2-molecule': ('Μόριο', 'mório'),
    'b2-atom': ('Άτομο', 'átomo'),
    'b2-cell-biology': ('Κύτταρο', 'kýttaro'),
    'b2-gene': ('Γονίδιο', 'gonídio'),
    'b2-evolution': ('Εξέλιξη', 'exélixi'),
    'b2-species': ('Είδος', 'eídos'),
    'b2-gravity': ('Βαρύτητα', 'varýtita'),
    'b2-orbit': ('Τροχιά', 'trohiá'),
    'b2-satellite': ('Δορυφόρος', 'doryfóros'),
    'b2-artificial-intelligence': ('Τεχνητή νοημοσύνη', 'tehnití noimosýni'),
    'b2-algorithm': ('Αλγόριθμος', 'algórithmos'),
    'b2-software': ('Λογισμικό', 'logismikó'),
    'b2-hardware': ('Υλικό', 'ylikó'),
    'b2-database': ('Βάση δεδομένων', 'vási dedoménon'),
    'b2-to-code-program': ('Προγραμματίζω', 'programmatízo'),
    'b2-bug-software': ('Σφάλμα', 'sfálma'),
    'b2-encryption': ('Κρυπτογράφηση', 'kryptográfisi'),
    'b2-cybersecurity': ('Κυβερνοασφάλεια', 'kyvernoasfália'),
    'b2-virtual-reality': ('Εικονική πραγματικότητα', 'eikonikí pragmatikótita'),
    'b2-innovation': ('Καινοτομία', 'kainotomía'),
    'b2-breakthrough': ('Ανακάλυψη', 'anakálypsi'),
    'b2-robot': ('Ρομπότ', 'robot'),
    'b2-automation': ('Αυτοματοποίηση', 'aftomatopoíisi'),
    'b2-sustainability': ('Βιωσιμότητα', 'viosimótita'),
    'b2-sustainable': ('Βιώσιμος', 'viósimos'),
    'b2-carbon-footprint': ('Αποτύπωμα άνθρακα', 'apotýpoma ánthraka'),
    'b2-emissions': ('Εκπομπές', 'ekpompés'),
    'b2-greenhouse-gas': ('Αέριο του θερμοκηπίου', 'aério tou thermokipíou'),
    'b2-global-warming': ('Υπερθέρμανση του πλανήτη', 'ypertérmansi tou planíti'),
    'b2-deforestation': ('Αποψίλωση δασών', 'apopsílosi dasón'),
    'b2-biodiversity': ('Βιοποικιλότητα', 'viopoikilótita'),
    'b2-ecosystem': ('Οικοσύστημα', 'oikosýstima'),
    'b2-habitat': ('Οικότοπος', 'oikótopos'),
    'b2-endangered-species': ('Απειλούμενο είδος', 'apeiloúmeno eídos'),
    'b2-extinction': ('Εξαφάνιση', 'exafánisi'),
    'b2-conservation': ('Διατήρηση', 'diatírisi'),
    'b2-wildlife': ('Άγρια πανίδα', 'ágria panída'),
    'b2-natural-resources': ('Φυσικοί πόροι', 'fysikoí póri'),
    'b2-fossil-fuels': ('Ορυκτά καύσιμα', 'oryktá kaýsima'),
    'b2-solar-panel': ('Ηλιακό πάνελ', 'iliakó pánel'),
    'b2-wind-turbine': ('Ανεμογεννήτρια', 'anemogennítria'),
    'b2-landfill': ('Χωματερή', 'homaterí'),
    'b2-compost': ('Κομπόστ', 'kompóst'),
    'b2-to-conserve': ('Εξοικονομώ', 'exoikonomó'),
    'b2-to-preserve': ('Διατηρώ', 'diatiró'),
    'b2-sea-level': ('Στάθμη της θάλασσας', 'státhmi tis thálassas'),
    'b2-glacier': ('Παγετώνας', 'pagetónas'),
    'b2-to-melt': ('Λιώνω', 'lióno'),
    'b2-famine': ('Λιμός', 'limós'),
    'b2-overpopulation': ('Υπερπληθυσμός', 'yperplithysmós'),
    'b2-to-pollute': ('Μολύνω', 'molýno'),
    'b2-single-use-plastic': ('Πλαστικό μιας χρήσης', 'plastikó mias hrísis'),
    'b2-environmentalist': ('Οικολόγος', 'oikológos'),
    'b2-recycling-bin': ('Κάδος ανακύκλωσης', 'kádos anakýklosis'),
    'b2-organic-farming': ('Βιολογική γεωργία', 'viologikí georgía'),
    'b2-diagnosis': ('Διάγνωση', 'diágnosi'),
    'b2-to-diagnose': ('Διαγνώνω', 'diagnóno'),
    'b2-treatment': ('Θεραπεία', 'therapía'),
    'b2-surgery': ('Εγχείρηση', 'enhírisi'),
    'b2-surgeon': ('Χειρουργός', 'heirourgós'),
    'b2-anesthesia': ('Αναισθησία', 'anaisthisía'),
    'b2-to-prescribe': ('Συνταγογραφώ', 'syntagografó'),
    'b2-dose': ('Δόση', 'dósi'),
    'b2-side-effect': ('Παρενέργεια', 'parenérgeia'),
    'b2-chronic': ('Χρόνιος', 'hrónios'),
    'b2-acute': ('Οξύς', 'oxýs'),
    'b2-infection': ('Λοίμωξη', 'loímoxi'),
    'b2-virus': ('Ιός', 'iós'),
    'b2-bacteria': ('Βακτήρια', 'vaktíria'),
    'b2-immune-system': ('Ανοσοποιητικό σύστημα', 'anosopoiitikó sýstima'),
    'b2-antibiotic': ('Αντιβιοτικό', 'antiviotikó'),
    'b2-transplant': ('Μεταμόσχευση', 'metamósheysi'),
    'b2-stroke': ('Εγκεφαλικό επεισόδιο', 'egkefalikó epeisódio'),
    'b2-heart-attack': ('Καρδιακή προσβολή', 'kardiakí prosvolí'),
    'b2-diabetes': ('Διαβήτης', 'diavítis'),
    'b2-cancer': ('Καρκίνος', 'karkínos'),
    'b2-asthma': ('Άσθμα', 'ásthma'),
    'b2-blood-test': ('Εξέταση αίματος', 'exétasi aímatos'),
    'b2-x-ray': ('Ακτινογραφία', 'aktinografía'),
    'b2-scan-medical': ('Σάρωση', 'sárosi'),
    'b2-ward': ('Πτέρυγα', 'ptéryga'),
    'b2-intensive-care': ('Εντατική θεραπεία', 'entatikí therapía'),
    'b2-recovery': ('Ανάρρωση', 'anárrosi'),
    'b2-disability': ('Αναπηρία', 'anapiría'),
    'b2-wheelchair': ('Αναπηρικό αμαξίδιο', 'anapirikó amaxídio'),
    'b2-ambulance': ('Ασθενοφόρο', 'asthenofóro'),
    'b2-pregnant': ('Έγκυος', 'éngyos'),
    'b2-contagious': ('Μεταδοτικός', 'metadotikós'),
    'b2-behavior': ('Συμπεριφορά', 'symperiforá'),
    'b2-personality': ('Προσωπικότητα', 'prosopikótita'),
    'b2-trait': ('Χαρακτηριστικό', 'harakteristikó'),
    'b2-motivation': ('Κίνητρο', 'kínitro'),
    'b2-willpower': ('Δύναμη θέλησης', 'dýnami thélisis'),
    'b2-self-esteem': ('Αυτοεκτίμηση', 'aftoektímisi'),
    'b2-self-confidence': ('Αυτοπεποίθηση', 'aftopepoíthisi'),
    'b2-anxiety': ('Άγχος', 'ánhos'),
    'b2-depression': ('Κατάθλιψη', 'katáthlipsi'),
    'b2-stress': ('Στρες', 'stres'),
    'b2-trauma': ('Τραύμα', 'trávma'),
    'b2-grief': ('Πένθος', 'pénthos'),
    'b2-to-cope': ('Τα βγάζω πέρα', 'ta vgázo péra'),
    'b2-comfort-zone': ('Ζώνη άνεσης', 'zóni ánesis'),
    'b2-procrastination': ('Αναβλητικότητα', 'anavlitikótita'),
    'b2-to-procrastinate': ('Αναβάλλω', 'anavállo'),
    'b2-perfectionism': ('Τελειομανία', 'teleiomanía'),
    'b2-introvert': ('Εσωστρεφής', 'esostrefís'),
    'b2-extrovert': ('Εξωστρεφής', 'exostrefís'),
    'b2-mindfulness': ('Ενσυνειδητότητα', 'ensyneiditótita'),
    'b2-resilience': ('Ανθεκτικότητα', 'anthektikótita'),
    'b2-to-overcome': ('Ξεπερνώ', 'xepernó'),
    'b2-obsession': ('Εμμονή', 'emmoní'),
    'b2-addiction': ('Εξάρτηση', 'exártisi'),
    'b2-denial': ('Άρνηση', 'árnisi'),
    'b2-bias': ('Μεροληψία', 'merolipsía'),
    'b2-stereotype': ('Στερεότυπο', 'stereótypo'),
    'b2-peer-pressure': ('Πίεση από συνομηλίκους', 'píesi apó synomilíkous'),
    'b2-self-awareness': ('Αυτεπίγνωση', 'aftepígnosi'),
    'b2-empathy-deep': ('Ενσυναίσθηση', 'ensynaísthisi'),
    'b2-therapist': ('Θεραπευτής', 'therapeftís'),
    'b2-instinct': ('Ένστικτο', 'énstikto'),
    'b2-to-acknowledge': ('Αναγνωρίζω', 'anagnorízo'),
    'b2-to-adapt': ('Προσαρμόζομαι', 'prosarmózome'),
    'b2-to-anticipate': ('Προβλέπω', 'provlépo'),
    'b2-to-assess': ('Αξιολογώ', 'axiologó'),
    'b2-to-assign': ('Καθορίζω', 'kathorízo'),
    'b2-to-assure': ('Διαβεβαιώνω', 'diavevaióno'),
    'b2-to-calculate': ('Υπολογίζω', 'ypologízo'),
    'b2-to-clarify': ('Διευκρινίζω', 'diefkrinízo'),
    'b2-to-collaborate': ('Συνεργάζομαι', 'synergázome'),
    'b2-to-compromise': ('Συμβιβάζομαι', 'symvivázome'),
    'b2-to-conclude': ('Συμπεραίνω', 'symperaíno'),
    'b2-to-confirm': ('Επιβεβαιώνω', 'epivevaióno'),
    'b2-to-confront': ('Αντιπαρατίθεμαι', 'antiparatíthemai'),
    'b2-to-contribute': ('Συνεισφέρω', 'syneisféro'),
    'b2-to-define': ('Ορίζω', 'orízo'),
    'b2-to-demonstrate': ('Αποδεικνύω', 'apodeiknýo'),
    'b2-to-dismiss': ('Απορρίπτω', 'aporrípto'),
    'b2-to-distinguish': ('Διακρίνω', 'diakríno'),
    'b2-to-dominate': ('Κυριαρχώ', 'kyriarhó'),
    'b2-to-eliminate': ('Εξαλείφω', 'exalífo'),
    'b2-to-emphasize': ('Τονίζω', 'tonízo'),
    'b2-to-enable': ('Επιτρέπω', 'epitrépo'),
    'b2-to-enhance': ('Βελτιώνω', 'veltióno'),
    'b2-to-ensure': ('Διασφαλίζω', 'diasfalízo'),
    'b2-to-establish': ('Ιδρύω', 'idrýo'),
    'b2-to-estimate': ('Εκτιμώ', 'ektimó'),
    'b2-to-evaluate': ('Αποτιμώ', 'apotimó'),
    'b2-to-exceed': ('Υπερβαίνω', 'ypervaíno'),
    'b2-to-exploit': ('Εκμεταλλεύομαι', 'ekmetallévomai'),
    'b2-to-facilitate': ('Διευκολύνω', 'diefkolýno'),
    'b2-to-generate': ('Παράγω', 'parágo'),
    'b2-to-guarantee': ('Εγγυώμαι', 'engyóme'),
    'b2-to-highlight': ('Υπογραμμίζω', 'ypogrammízo'),
    'b2-to-identify': ('Εντοπίζω', 'entopízo'),
    'b2-to-illustrate': ('Απεικονίζω', 'apeikonízo'),
    'b2-to-implement': ('Εφαρμόζω', 'efarmózo'),
    'b2-to-imply': ('Υπονοώ', 'yponoó'),
    'b2-to-indicate': ('Υποδεικνύω', 'ypodeiknýo'),
    'b2-to-influence': ('Επηρεάζω', 'epireázo'),
    'b2-to-inspire': ('Εμπνέω', 'empnéo'),
    'b2-to-interpret': ('Ερμηνεύω', 'ermineýo'),
    'b2-to-justify': ('Δικαιολογώ', 'dikaiologó'),
    'b2-to-maintain': ('Συντηρώ', 'syntiró'),
    'b2-to-modify': ('Τροποποιώ', 'tropopoió'),
    'b2-to-monitor': ('Παρακολουθώ', 'parakolouthó'),
    'b2-to-motivate': ('Παρακινώ', 'parakinó'),
    'b2-to-obtain': ('Αποκτώ', 'apoktó'),
    'b2-to-oppose': ('Αντιτίθεμαι', 'antitíthemai'),
    'b2-to-perceive': ('Αντιλαμβάνομαι', 'antilamvánomai'),
    'b2-to-persist': ('Επιμένω', 'epiméno'),
    'b2-to-possess': ('Κατέχω', 'katého'),
    'b2-to-prevent': ('Αποτρέπω', 'apotrépo'),
    'b2-to-pursue': ('Επιδιώκω', 'epidióko'),
    'b2-to-reinforce': ('Ενισχύω', 'enishýo'),
    'b2-to-resolve': ('Επιλύω', 'epilýo'),
    'b2-to-restrict': ('Περιορίζω', 'periorízo'),
    'b2-to-retain': ('Κρατώ', 'krató'),
    'b2-to-reveal': ('Αποκαλύπτω', 'apokalýpto'),
    'b2-to-sustain': ('Υποστηρίζω', 'ypostirízo'),
    'b2-to-tackle': ('Χειρίζομαι', 'heirízome'),
    'b2-to-transform': ('Μεταμορφώνω', 'metamorfóno'),
    'b2-to-undergo': ('Υφίσταμαι', 'yfístamai'),
    'b2-to-undertake': ('Αναλαμβάνω', 'analamváno'),
    'b2-to-verify': ('Επαληθεύω', 'epalitheýo'),
    'b2-to-abandon': ('Εγκαταλείπω', 'egkataleípo'),
    'b2-to-accompany': ('Συνοδεύω', 'synodeýo'),
    'b2-to-accumulate': ('Συσσωρεύω', 'syssoreýo'),
    'b2-to-alter': ('Αλλάζω', 'allázo'),
    'b2-to-approve': ('Εγκρίνω', 'egkríno'),
    'b2-to-attach': ('Επισυνάπτω', 'episynápto'),
    'b2-to-cease': ('Παύω', 'páfo'),
    'b2-to-commit-to': ('Δεσμεύομαι', 'desmévomai'),
    'b2-to-comply': ('Συμμορφώνομαι', 'symmorfónomai'),
    'b2-to-conduct-carry-out': ('Διεξάγω', 'diexágo'),
    'b2-to-consist-of': ('Αποτελούμαι από', 'apoteloúmai apó'),
    'b2-to-convert': ('Μετατρέπω', 'metatrépo'),
    'b2-to-cooperate': ('Συμπράττω', 'sympráto'),
    'b2-to-decline-refuse': ('Αρνούμαι', 'arnoúmai'),
    'b2-to-detect': ('Ανιχνεύω', 'anihnévo'),
    'b2-to-devote': ('Αφιερώνω', 'afieróno'),
    'b2-to-emerge': ('Αναδύομαι', 'anadýomai'),
    'b2-to-exclude': ('Αποκλείω', 'apokleío'),
    'b2-to-expand': ('Επεκτείνω', 'epekteíno'),
    'b2-to-fulfill': ('Εκπληρώνω', 'ekpliróno'),
    'b2-to-impose': ('Επιβάλλω', 'epivállo'),
    'b2-to-integrate': ('Ενσωματώνω', 'ensomatóno'),
    'b2-to-neglect': ('Παραμελώ', 'parameló'),
    'b2-to-overlook': ('Παραβλέπω', 'paravlépo'),
    'b2-to-reconsider': ('Επανεξετάζω', 'epanexetázo'),
    'b2-to-withdraw-pull-out': ('Αποσύρομαι', 'aposýromai'),
    'b2-accurate': ('Ακριβής', 'akrivís'),
    'b2-adequate': ('Επαρκής', 'eparkís'),
    'b2-ambiguous': ('Διφορούμενος', 'diforoúmenos'),
    'b2-apparent': ('Προφανής', 'profanís'),
    'b2-appropriate': ('Κατάλληλος', 'katállilos'),
    'b2-arbitrary': ('Αυθαίρετος', 'afthaíretos'),
    'b2-coherent': ('Συνεκτικός', 'synektikós'),
    'b2-comprehensive': ('Εξαντλητικός', 'exantlitikós'),
    'b2-consistent': ('Συνεπής', 'synepís'),
    'b2-controversial': ('Αμφιλεγόμενος', 'amfilegómenos'),
    'b2-crucial': ('Κρίσιμος', 'krísimos'),
    'b2-deliberate': ('Σκόπιμος', 'skópimos'),
    'b2-distinct': ('Ευδιάκριτος', 'evdiákritos'),
    'b2-diverse': ('Ποικίλος', 'poikílos'),
    'b2-dominant': ('Κυρίαρχος', 'kyríarhos'),
    'b2-efficient': ('Αποδοτικός', 'apodotikós'),
    'b2-elaborate': ('Περίτεχνος', 'perítehnos'),
    'b2-explicit': ('Ρητός', 'ritós'),
    'b2-implicit': ('Σιωπηρός', 'siopirós'),
    'b2-fundamental': ('Θεμελιώδης', 'themeliódis'),
    'b2-genuine': ('Γνήσιος', 'gnísios'),
    'b2-inevitable': ('Αναπόφευκτος', 'anapófevktos'),
    'b2-legitimate': ('Νόμιμος', 'nómimos'),
    'b2-mutual': ('Αμοιβαίος', 'amoivaíos'),
    'b2-neutral': ('Ουδέτερος', 'oudéteros'),
    'b2-notable': ('Αξιοσημείωτος', 'axiosimeíotos'),
    'b2-precise': ('Λεπτομερής', 'leptomerís'),
    'b2-prominent': ('Διακεκριμένος', 'diakekriménos'),
    'b2-relevant': ('Σχετικός', 'shetikós'),
    'b2-irrelevant': ('Άσχετος', 'áshetos'),
    'b2-rigid': ('Άκαμπτος', 'ákamptos'),
    'b2-subtle': ('Λεπτός', 'leptós'),
    'b2-sufficient': ('Αρκετός', 'arketós'),
    'b2-tremendous': ('Τεράστιος', 'terástios'),
    'b2-vague': ('Ασαφής', 'asafís'),
    'b2-vast': ('Απέραντος', 'apérantos'),
    'b2-vital': ('Ζωτικός', 'zotikós'),
    'b2-widespread': ('Διαδεδομένος', 'diadedoménos'),
    'b2-reluctant': ('Απρόθυμος', 'apróthymos'),
    'b2-thorough': ('Σχολαστικός', 'sholastikós'),
    'b2-abstract': ('Αφηρημένος', 'afiriménos'),
    'b2-concrete': ('Συγκεκριμένος', 'sygkekriménos'),
    'b2-absurd': ('Παράλογος', 'parálogos'),
    'b2-alarming': ('Ανησυχητικός', 'anisyhitikós'),
    'b2-biased': ('Προκατειλημμένος', 'prokateiliménos'),
    'b2-compelling': ('Επιτακτικός', 'epitaktikós'),
    'b2-contradictory': ('Αντιφατικός', 'antifatikós'),
    'b2-credible': ('Αξιόπιστος', 'axiópistos'),
    'b2-feasible': ('Εφικτός', 'efiktós'),
    'b2-flawed': ('Ελαττωματικός', 'elattomatikós'),
    'b2-innovative': ('Καινοτόμος', 'kainotómos'),
    'b2-obsolete': ('Απαρχαιωμένος', 'aparhaioménos'),
    'b2-outstanding': ('Εξαιρετικός', 'exeretikós'),
    'b2-persistent': ('Επίμονος', 'epímonos'),
    'b2-profound': ('Βαθύς', 'vathýs'),
    'b2-redundant': ('Περιττός', 'perittós'),
    'b2-superficial': ('Επιφανειακός', 'epifaneiakós'),
    'b2-trivial': ('Ασήμαντος', 'asímantos'),
    'b2-unprecedented': ('Πρωτοφανής', 'protofanís'),
    'b2-versatile': ('Ευέλικτος', 'evéliktos'),
    'b2-as-far-as-im-concerned': ('Όσον με αφορά', 'óson me aforá'),
    'b2-to-some-extent': ('Σε κάποιο βαθμό', 'se kápoio vathmó'),
    'b2-in-terms-of': ('Όσον αφορά', 'óson aforá'),
    'b2-with-regard-to': ('Σχετικά με', 'shetiká me'),
    'b2-on-the-whole': ('Σε γενικές γραμμές', 'se genikés grammés'),
    'b2-by-and-large': ('Ως επί το πλείστον', 'os epí to pleíston'),
    'b2-in-the-meantime': ('Στο μεταξύ', 'sto metaxý'),
    'b2-at-the-same-time': ('Ταυτόχρονα', 'taftóhrona'),
    'b2-needless-to-say': ('Περιττό να πούμε', 'peritó na poúme'),
    'b2-to-put-it-simply': ('Με απλά λόγια', 'me aplá lógia'),
    'b2-in-a-nutshell': ('Με λίγα λόγια', 'me líga lógia'),
    'b2-having-said-that': ('Παρ\' όλα αυτά', 'parʼ óla aftá'),
    'b2-as-a-matter-of-fact': ('Στην πραγματικότητα', 'stin pragmatikótita'),
    'b2-for-the-time-being': ('Προς το παρόν', 'pros to parón'),
    'b2-on-second-thought': ('Αν το ξανασκεφτώ', 'an to xanaskeftó'),
    'b2-all-things-considered': ('Λαμβάνοντας όλα υπόψη', 'lamvánontas óla ypópsi'),
    'b2-if-anything': ('Αν μη τι άλλο', 'an mi ti állo'),
    'b2-in-any-case': ('Σε κάθε περίπτωση', 'se káthe períptosi'),
    'b2-more-or-less': ('Λίγο πολύ', 'lígo polý'),
    'b2-sooner-or-later': ('Αργά ή γρήγορα', 'argá í grígora'),
    'b2-every-now-and-then': ('Πότε πότε', 'póte póte'),
    'b2-on-purpose': ('Επίτηδες', 'epítides'),
    'b2-by-accident': ('Κατά λάθος', 'katá láthos'),
    'b2-by-all-means': ('Οπωσδήποτε', 'oposdípote'),
    'b2-for-the-sake-of': ('Για χάρη', 'gia hári'),
    'b2-up-to-a-point': ('Μέχρι ένα σημείο', 'méhri éna simeío'),
    'b2-to-say-the-least': ('Το λιγότερο', 'to ligótero'),
    'b2-in-hindsight': ('Εκ των υστέρων', 'ek ton ystéron'),
    'b2-strictly-speaking': ('Αυστηρά μιλώντας', 'afstirá milóntas'),
    'b2-broadly-speaking': ('Χοντρικά μιλώντας', 'hontriká milóntas'),
    'b2-parliament': ('Κοινοβούλιο', 'koinovoúlio'),
    'b2-president': ('Πρόεδρος', 'próedros'),
    'b2-prime-minister': ('Πρωθυπουργός', 'prothypourgós'),
    'b2-minister': ('Υπουργός', 'ypourgós'),
    'b2-mayor': ('Δήμαρχος', 'dímarhos'),
    'b2-policy': ('Πολιτική', 'politikí'),
    'b2-reform': ('Μεταρρύθμιση', 'metarrýthmisi'),
    'b2-legislation': ('Νομοθεσία', 'nomothesía'),
    'b2-bill-proposed-law': ('Νομοσχέδιο', 'nomoshédio'),
    'b2-referendum': ('Δημοψήφισμα', 'dimopsífisma'),
    'b2-campaign': ('Εκστρατεία', 'ekstrateía'),
    'b2-candidate': ('Υποψήφιος', 'ypopsífios'),
    'b2-political-party': ('Πολιτικό κόμμα', 'politikó kómma'),
    'b2-opposition': ('Αντιπολίτευση', 'antipolítefsi'),
    'b2-coalition': ('Συνασπισμός', 'synaspismós'),
    'b2-majority': ('Πλειοψηφία', 'pleiopsifía'),
    'b2-minority': ('Μειοψηφία', 'meiopsifía'),
    'b2-scandal': ('Σκάνδαλο', 'skándalo'),
    'b2-budget-deficit': ('Δημοσιονομικό έλλειμμα', 'dimosionomikó élleimma'),
    'b2-national-debt': ('Δημόσιο χρέος', 'dimósio hréos'),
    'b2-recession': ('Ύφεση', 'ýfesi'),
    'b2-economic-growth': ('Οικονομική ανάπτυξη', 'oikonomikí anáptyxi'),
    'b2-interest-rate': ('Επιτόκιο', 'epitókio'),
    'b2-stock-market': ('Χρηματιστήριο', 'hrimatistírio'),
    'b2-shares-stocks': ('Μετοχές', 'metohés'),
    'b2-investor': ('Επενδυτής', 'ependytís'),
    'b2-trade-commerce': ('Εμπόριο', 'empório'),
    'b2-tariff': ('Δασμός', 'dasmós'),
    'b2-export': ('Εξαγωγή', 'exagogí'),
    'b2-import': ('Εισαγωγή', 'eisagogí'),
    'b2-bankruptcy': ('Χρεοκοπία', 'hreokopía'),
    'b2-monopoly': ('Μονοπώλιο', 'monopólio'),
    'b2-in-laws': ('Πεθερικά', 'petheriká'),
    'b2-mother-in-law': ('Πεθερά', 'petherá'),
    'b2-stepmother': ('Μητριά', 'mitriá'),
    'b2-sibling': ('Αδέλφι', 'adélfi'),
    'b2-spouse': ('Σύζυγος', 'sýzygos'),
    'b2-fiance': ('Αρραβωνιαστικός', 'arravoniastikós'),
    'b2-engagement': ('Αρραβώνας', 'arravónas'),
    'b2-to-propose-marriage': ('Κάνω πρόταση γάμου', 'káno prótasi gámou'),
    'b2-honeymoon': ('Μήνας του μέλιτος', 'mínas tou mélitos'),
    'b2-single-parent': ('Μονογονιός', 'monogoniós'),
    'b2-godparent': ('Νονός', 'nonós'),
    'b2-guardian': ('Κηδεμόνας', 'kidemónas'),
    'b2-orphan': ('Ορφανός', 'orfanós'),
    'b2-adoption': ('Υιοθεσία', 'yiothesía'),
    'b2-to-adopt': ('Υιοθετώ', 'yiothetó'),
    'b2-upbringing': ('Ανατροφή', 'anatrofí'),
    'b2-household': ('Νοικοκυριό', 'noikokyrió'),
    'b2-breadwinner': ('Κουβαλητής', 'kouvalitís'),
    'b2-ancestor': ('Πρόγονος', 'prógonos'),
    'b2-descendant': ('Απόγονος', 'apógonos'),
    'b2-heritage': ('Πολιτιστική κληρονομιά', 'politistikí klironomiá'),
    'b2-inheritance': ('Κληρονομιά', 'klironomiá'),
    'b2-to-inherit': ('Κληρονομώ', 'klironomó'),
    'b2-will-testament': ('Διαθήκη', 'diathíki'),
    'b2-widow': ('Χήρα', 'híra'),
    'b2-elderly': ('Ηλικιωμένοι', 'ilikioménoi'),
    'b2-caregiver': ('Φροντιστής', 'frontistís'),
    'b2-retirement-home': ('Γηροκομείο', 'girokomeío'),
    'b2-kinship': ('Συγγένεια', 'syngéneia'),
    'b2-role-model': ('Πρότυπο', 'prótypo'),
    'b2-painting': ('Ζωγραφική', 'zografikí'),
    'b2-sculpture': ('Γλυπτική', 'glyptikí'),
    'b2-exhibition': ('Έκθεση', 'ékthesi'),
    'b2-gallery': ('Γκαλερί', 'galerí'),
    'b2-masterpiece': ('Αριστούργημα', 'aristoúrgima'),
    'b2-portrait': ('Πορτρέτο', 'portréto'),
    'b2-landscape-painting': ('Τοπίο', 'topío'),
    'b2-canvas': ('Καμβάς', 'kamvás'),
    'b2-sketch': ('Σκίτσο', 'skítso'),
    'b2-festival': ('Φεστιβάλ', 'festivál'),
    'b2-parade': ('Παρέλαση', 'parélasi'),
    'b2-folklore': ('Λαογραφία', 'laografía'),
    'b2-myth': ('Μύθος', 'mýthos'),
    'b2-legend': ('Θρύλος', 'thrýlos'),
    'b2-literature': ('Λογοτεχνία', 'logotehnía'),
    'b2-genre': ('Λογοτεχνικό είδος', 'logotehnikó eídos'),
    'b2-metaphor': ('Μεταφορά', 'metaforá'),
    'b2-rhyme': ('Ομοιοκαταληξία', 'omoiokatalixía'),
    'b2-verse': ('Στίχος', 'stíhos'),
    'b2-orchestra': ('Ορχήστρα', 'orhístra'),
    'b2-symphony': ('Συμφωνία', 'symfonía'),
    'b2-opera': ('Όπερα', 'ópera'),
    'b2-choir': ('Χορωδία', 'horodía'),
    'b2-rehearsal': ('Πρόβα', 'próva'),
    'b2-premiere': ('Πρεμιέρα', 'premiéra'),
    'b2-applause': ('Χειροκρότημα', 'heirokrótima'),
    'b2-playwright': ('Θεατρικός συγγραφέας', 'theatrikós syggraféas'),
    'b2-script': ('Σενάριο', 'senário'),
    'b2-stage': ('Σκηνή', 'skiní'),
    'b2-backstage': ('Παρασκήνια', 'paraskínia'),
    'b2-costume': ('Ενδυμασία', 'endymasía'),
    'b2-director-film': ('Σκηνοθέτης', 'skinothétis'),
    'b2-producer': ('Παραγωγός', 'paragogós'),
    'b2-screenplay': ('Σενάριο ταινίας', 'senário tainías'),
    'b2-to-marinate': ('Μαρινάρω', 'marináro'),
    'b2-to-grill': ('Ψήνω στη σχάρα', 'psíno sti shára'),
    'b2-to-roast': ('Ψήνω στο φούρνο', 'psíno sto foúrno'),
    'b2-to-steam': ('Μαγειρεύω στον ατμό', 'mageirévo ston atmó'),
    'b2-to-simmer': ('Σιγοβράζω', 'sigovrázo'),
    'b2-to-saute': ('Σοτάρω', 'sotáro'),
    'b2-to-whisk': ('Χτυπώ', 'htypó'),
    'b2-to-knead': ('Ζυμώνω', 'zymóno'),
    'b2-dough': ('Ζύμη', 'zými'),
    'b2-batter': ('Κουρκούτι', 'kourkoúti'),
    'b2-crust': ('Κόρα', 'kóra'),
    'b2-to-grate': ('Τρίβω', 'trívo'),
    'b2-to-peel': ('Ξεφλουδίζω', 'xefloudízo'),
    'b2-to-chop': ('Ψιλοκόβω', 'psilokóvo'),
    'b2-to-slice': ('Κόβω σε φέτες', 'kóvo se fétes'),
    'b2-to-dice': ('Κόβω σε κύβους', 'kóvo se kývous'),
    'b2-to-stir': ('Ανακατεύω', 'anakatévo'),
    'b2-seasoning': ('Καρύκευμα', 'karýkevma'),
    'b2-herb': ('Αρωματικό βότανο', 'aromatikó vótano'),
    'b2-spice': ('Μπαχαρικό', 'baharikó'),
    'b2-cinnamon': ('Κανέλα', 'kanéla'),
    'b2-ginger': ('Πιπερόριζα', 'piperóriza'),
    'b2-basil': ('Βασιλικός', 'vasilikós'),
    'b2-vinegar': ('Ξίδι', 'xídi'),
    'b2-soy-sauce': ('Σάλτσα σόγιας', 'sáltsa sógias'),
    'b2-broth': ('Ζωμός', 'zomós'),
    'b2-stew': ('Γιαχνί', 'yahní'),
    'b2-crispy': ('Τραγανός', 'traganós'),
    'b2-tender': ('Τρυφερός', 'tryferós'),
    'b2-juicy': ('Ζουμερός', 'zoumerós'),
    'b2-greasy': ('Λιπαρός', 'liparós'),
    'b2-stale': ('Μπαγιάτικος', 'bagiátikos'),
    'b2-rotten': ('Σάπιος', 'sápios'),
    'b2-sour': ('Ξινός', 'xinós'),
    'b2-savory': ('Αλμυρός', 'almyrós'),
    'b2-skyscraper': ('Ουρανοξύστης', 'ouranoxýstis'),
    'b2-infrastructure': ('Υποδομή', 'ypodomí'),
    'b2-public-transport': ('Δημόσιες συγκοινωνίες', 'dimósies sygkoinoníes'),
    'b2-congestion': ('Συμφόρηση', 'symfórisi'),
    'b2-urban': ('Αστικός', 'astikós'),
    'b2-rural': ('Αγροτικός', 'agrotikós'),
    'b2-district': ('Συνοικία', 'synoikía'),
    'b2-gentrification': ('Αστικός εξευγενισμός', 'astikós exevgenismós'),
    'b2-housing-crisis': ('Κρίση στέγασης', 'krísi stégasis'),
    'b2-homelessness': ('Αστεγία', 'astegía'),
    'b2-shelter': ('Καταφύγιο', 'katafýgio'),
    'b2-pedestrian-zone': ('Πεζόδρομος', 'pezódromos'),
    'b2-bike-lane': ('Ποδηλατόδρομος', 'podilatódromos'),
    'b2-green-space': ('Πράσινος χώρος', 'prásinos hóros'),
    'b2-high-rise': ('Ψηλό κτίριο', 'psiló ktírio'),
    'b2-zoning': ('Ζωνοποίηση', 'zonopoíisi'),
    'b2-demolition': ('Κατεδάφιση', 'katedáfisi'),
    'b2-construction-site': ('Εργοτάξιο', 'ergotáxio'),
    'b2-crane': ('Γερανός', 'geranós'),
    'b2-scaffolding': ('Σκαλωσιά', 'skalosiá'),
    'b2-blueprint': ('Αρχιτεκτονικό σχέδιο', 'arhitektonikó shédio'),
    'b2-permit': ('Άδεια', 'ádeia'),
    'b2-contractor': ('Εργολάβος', 'ergolávos'),
    'b2-foundation-building': ('Θεμέλια', 'themélia'),
    'b2-insulation': ('Μόνωση', 'mónosi'),
    'b2-plumbing': ('Υδραυλικές εγκαταστάσεις', 'ydravlikés egkatastáseis'),
    'b2-wiring': ('Καλωδίωση', 'kalodíosi'),
    'b2-beam': ('Δοκάρι', 'dokári'),
    'b2-drywall': ('Γυψοσανίδα', 'gypsosanída'),
    'b2-inspection': ('Επιθεώρηση', 'epitheórisi'),
    'b2-tenant-improvement': ('Διαμόρφωση χώρου ενοικιαστή', 'diamórfosi hórou enoikiastí'),
    'b2-deadline-construction': ('Προθεσμία παράδοσης έργου', 'prothesmía parádosis érgou'),
    'b2-contempt': ('Περιφρόνηση', 'perifrónisi'),
    'b2-resentment': ('Μνησικακία', 'mnisikakía'),
    'b2-bitterness': ('Πικρία', 'pikría'),
    'b2-longing': ('Λαχτάρα', 'lahtára'),
    'b2-dread': ('Τρόμος', 'trómos'),
    'b2-apprehension': ('Ανησυχία', 'anisyhía'),
    'b2-serenity': ('Γαλήνη', 'galíni'),
    'b2-contentment': ('Ικανοποίηση', 'ikanopoíisi'),
    'b2-euphoria': ('Ευφορία', 'evforía'),
    'b2-melancholy': ('Μελαγχολία', 'melagholía'),
    'b2-remorse': ('Τύψεις', 'týpseis'),
    'b2-humiliation': ('Ταπείνωση', 'tapeínosi'),
    'b2-rage': ('Οργή', 'orgí'),
    'b2-awe': ('Δέος', 'déos'),
    'b2-indignation': ('Αγανάκτηση', 'aganáktisi'),
    'b2-disgust': ('Αηδία', 'aidía'),
    'b2-boredom': ('Πλήξη', 'plíxi'),
    'b2-agony': ('Αγωνία', 'agonía'),
    'b2-ecstasy': ('Έκσταση', 'ékstasi'),
    'b2-complacency': ('Εφησυχασμός', 'efisyhasmós'),
    'b2-disbelief': ('Δυσπιστία', 'dyspistía'),
    'b2-suspicion': ('Καχυποψία', 'kahypopsía'),
    'b2-reluctance': ('Απροθυμία', 'aprothymía'),
    'b2-eagerness': ('Προθυμία', 'prothymía'),
    'b2-fondness': ('Συμπάθεια', 'sympátheia'),
    'b2-tenderness': ('Τρυφερότητα', 'tryferótita'),
    'b2-affection': ('Στοργή', 'storgí'),
    'b2-to-resent': ('Δυσανασχετώ', 'dysanashetó'),
    'b2-to-loathe': ('Απεχθάνομαι', 'apehthánomai'),
    'b2-to-cherish': ('Θησαυρίζω', 'thisavrízo'),
    'b2-to-despise': ('Περιφρονώ', 'perifronó'),
    'b2-to-dread': ('Τρέμω στη σκέψη', 'trémo sti sképsi'),
    'b2-to-state': ('Δηλώνω', 'dilóno'),
    'b2-statement': ('Δήλωση', 'dílosi'),
    'b2-to-claim': ('Ισχυρίζομαι', 'ishyrízomai'),
    'b2-to-declare': ('Διακηρύσσω', 'diakiríso'),
    'b2-to-announce': ('Ανακοινώνω', 'anakoinóno'),
    'b2-announcement': ('Ανακοίνωση', 'anakoínosi'),
    'b2-to-assert': ('Διατείνομαι', 'diateínomai'),
    'b2-to-hint': ('Υπαινίσσομαι', 'ypainíssomai'),
    'b2-to-confess': ('Ομολογώ', 'omologó'),
    'b2-confession': ('Ομολογία', 'omología'),
    'b2-to-object': ('Ενίσταμαι', 'enístamai'),
    'b2-objection': ('Ένσταση', 'énstasi'),
    'b2-to-summarize': ('Συνοψίζω', 'synopsízo'),
    'b2-summary': ('Περίληψη', 'perílipsi'),
    'b2-to-elaborate': ('Αναπτύσσω', 'anaptýsso'),
    'b2-to-paraphrase': ('Παραφράζω', 'parafrázo'),
    'b2-to-quote': ('Παραθέτω', 'parathéto'),
    'b2-quotation': ('Παράθεση', 'paráthesi'),
    'b2-reference': ('Αναφορά', 'anaforá'),
    'b2-to-address-an-issue': ('Πραγματεύομαι', 'pragmatévomai'),
    'b2-to-convey': ('Μεταδίδω', 'metadído'),
    'b2-to-articulate': ('Διατυπώνω', 'diatypóno'),
    'b2-to-reiterate': ('Επαναλαμβάνω', 'epanalamváno'),
    'b2-remark': ('Παρατήρηση', 'paratírisi'),
    'b2-to-comment': ('Σχολιάζω', 'sholiázo'),
    'b2-to-consult': ('Συμβουλεύομαι', 'symvoulévomai'),
    'b2-to-advocate': ('Τάσσομαι υπέρ', 'tássomai ypér'),
    'b2-to-mediate': ('Διαμεσολαβώ', 'diamesolavó'),
    'b2-compromise-noun': ('Συμβιβασμός', 'symvivasmós'),
    'b2-negotiation': ('Διαπραγμάτευση', 'diapragmátefsi'),
    'b2-persuasive': ('Πειστικός', 'peistikós'),
    'b2-tactful': ('Διπλωματικός', 'diplomatikós'),
    'b2-blunt-direct': ('Ωμός', 'omós'),
    'b2-efficiency': ('Αποδοτικότητα', 'apodotikótita'),
    'b2-productivity': ('Παραγωγικότητα', 'paragogikótita'),
    'b2-to-do-list': ('Λίστα εκκρεμοτήτων', 'lísta ekkremotíton'),
    'b2-reminder': ('Υπενθύμιση', 'ypenthýmisi'),
    'b2-to-reschedule': ('Αναπρογραμματίζω', 'anaprogrammatízo'),
    'b2-calendar': ('Ημερολόγιο', 'imerológio'),
    'b2-time-zone': ('Ζώνη ώρας', 'zóni óras'),
    'b2-daylight-saving-time': ('Θερινή ώρα', 'therini óra'),
    'b2-punctuality': ('Συνέπεια στην ώρα', 'synépeia stin óra'),
    'b2-ahead-of-schedule': ('Πριν την προθεσμία', 'prin tin prothesmía'),
    'b2-behind-schedule': ('Σε καθυστέρηση', 'se kathystérisi'),
    'b2-in-advance': ('Εκ των προτέρων', 'ek ton protéron'),
    'b2-last-minute': ('Της τελευταίας στιγμής', 'tis telefteías stigmís'),
    'b2-overdue': ('Εκπρόθεσμος', 'ekpróthesmos'),
    'b2-to-squeeze-in': ('Βρίσκω χρόνο για', 'vrísko hróno gia'),
    'b2-to-multitask': ('Κάνω πολλά πράγματα ταυτόχρονα', 'káno pollá prágmata taftóhrona'),
    'b2-to-allocate': ('Κατανέμω', 'katanémo'),
    'b2-downtime': ('Νεκρός χρόνος', 'nekrós hrónos'),
    'b2-spare-time': ('Ελεύθερος χρόνος', 'eléftheros hrónos'),
    'b2-to-kill-time': ('Σκοτώνω την ώρα', 'skotóno tin óra'),
    'b2-pastime': ('Ενασχόληση', 'enashólisi'),
    'b2-leisure': ('Αναψυχή', 'anapsyhí'),
    'b2-on-the-dot': ('Στην ώρα ακριβώς', 'stin óra akrivós'),
    'b2-around-the-clock': ('Όλο το εικοσιτετράωρο', 'ólo to eikositetráoro'),
    'b2-in-the-nick-of-time': ('Την τελευταία στιγμή', 'tin telefteía stigmí'),
    'b2-long-term': ('Μακροπρόθεσμος', 'makropróthesmos'),
    'b2-short-term': ('Βραχυπρόθεσμος', 'vrahypróthesmos'),
    'b2-simultaneously': ('Συγχρόνως', 'synhrónos'),
    'b2-continent': ('Ήπειρος', 'ípeiros'),
    'b2-hemisphere': ('Ημισφαίριο', 'imisfaírio'),
    'b2-equator': ('Ισημερινός', 'isimerinós'),
    'b2-latitude': ('Γεωγραφικό πλάτος', 'geografikó plátos'),
    'b2-altitude': ('Υψόμετρο', 'ypsómetro'),
    'b2-valley': ('Κοιλάδα', 'koiláda'),
    'b2-canyon': ('Φαράγγι', 'farángi'),
    'b2-cliff': ('Γκρεμός', 'gkremós'),
    'b2-cave': ('Σπηλιά', 'spiliá'),
    'b2-plateau': ('Οροπέδιο', 'oropédio'),
    'b2-peninsula': ('Χερσόνησος', 'hersónisos'),
    'b2-bay': ('Κόλπος', 'kólpos'),
    'b2-coast': ('Ακτή', 'aktí'),
    'b2-shore': ('Γιαλός', 'gialós'),
    'b2-harbor': ('Λιμάνι', 'limáni'),
    'b2-dune': ('Αμμόλοφος', 'ammólofos'),
    'b2-iceberg': ('Παγόβουνο', 'pagóvouno'),
    'b2-swamp': ('Βάλτος', 'váltos'),
    'b2-jungle': ('Ζούγκλα', 'zoúngla'),
    'b2-rainforest': ('Τροπικό δάσος', 'tropikó dásos'),
    'b2-savanna': ('Σαβάνα', 'savána'),
    'b2-tundra': ('Τούντρα', 'toúntra'),
    'b2-oasis': ('Όαση', 'óasi'),
    'b2-waterfall': ('Καταρράκτης', 'katarráktis'),
    'b2-stream': ('Ρυάκι', 'ryáki'),
    'b2-spring-water': ('Πηγή', 'pigí'),
    'b2-reef': ('Ύφαλος', 'ýfalos'),
    'b2-tide': ('Παλίρροια', 'palírroia'),
    'b2-current-water': ('Ρεύμα', 'révma'),
    'b2-horizon': ('Ορίζοντας', 'orízontas'),
    'b2-skeleton': ('Σκελετός', 'skeletós'),
    'b2-bone': ('Οστό', 'ostó'),
    'b2-skull': ('Κρανίο', 'kranío'),
    'b2-spine': ('Σπονδυλική στήλη', 'spondylikí stíli'),
    'b2-rib': ('Πλευρό', 'plevró'),
    'b2-joint': ('Άρθρωση', 'árthrosi'),
    'b2-tendon': ('Τένοντας', 'ténontas'),
    'b2-nerve': ('Νεύρο', 'névro'),
    'b2-brain': ('Εγκέφαλος', 'egkéfalos'),
    'b2-lung': ('Πνεύμονας', 'pnévmonas'),
    'b2-liver': ('Συκώτι', 'sykóti'),
    'b2-kidney': ('Νεφρό', 'nefró'),
    'b2-intestine': ('Έντερο', 'éntero'),
    'b2-artery': ('Αρτηρία', 'artiría'),
    'b2-vein': ('Φλέβα', 'fléva'),
    'b2-pulse': ('Σφυγμός', 'sfygmós'),
    'b2-wrist': ('Καρπός', 'karpós'),
    'b2-ankle': ('Αστράγαλος', 'astrágalos'),
    'b2-elbow': ('Αγκώνας', 'agkónas'),
    'b2-thigh': ('Μηρός', 'mirós'),
    'b2-heel': ('Φτέρνα', 'ftérna'),
    'b2-palm': ('Παλάμη', 'palámi'),
    'b2-thumb': ('Αντίχειρας', 'antíheiras'),
    'b2-eyebrow': ('Φρύδι', 'frýdi'),
    'b2-eyelash': ('Βλεφαρίδα', 'vlefarída'),
    'b2-chin': ('Πηγούνι', 'pigoúni'),
    'b2-cheek': ('Μάγουλο', 'mágoulo'),
    'b2-forehead': ('Μέτωπο', 'métopo'),
    'b2-jaw': ('Σαγόνι', 'sagóni'),
    'b2-throat': ('Λαιμός', 'laimós'),
    'b2-tongue': ('Γλώσσα', 'glóssa'),
    'b2-lip': ('Χείλος', 'heílos'),
    'b2-tailor': ('Ράφτης', 'ráftis'),
    'b2-fabric': ('Ύφασμα', 'ýfasma'),
    'b2-seam': ('Ραφή', 'rafí'),
    'b2-zipper': ('Φερμουάρ', 'fermouár'),
    'b2-button': ('Κουμπί', 'koumpí'),
    'b2-collar': ('Γιακάς', 'giakás'),
    'b2-sleeve': ('Μανίκι', 'maníki'),
    'b2-hem': ('Στρίφωμα', 'strífoma'),
    'b2-pocket': ('Τσέπη', 'tsépi'),
    'b2-lining': ('Φόδρα', 'fódra'),
    'b2-to-fasten': ('Κουμπώνω', 'koumpóno'),
    'b2-to-unbutton': ('Ξεκουμπώνω', 'xekoumpóno'),
    'b2-to-fold': ('Διπλώνω', 'diplóno'),
    'b2-wardrobe': ('Ντουλάπα', 'ntoulápa'),
    'b2-hanger': ('Κρεμάστρα', 'kremástra'),
    'b2-detergent': ('Απορρυπαντικό', 'aporrypantikó'),
    'b2-stain': ('Λεκές', 'lekés'),
    'b2-to-shrink': ('Μαζεύω', 'mazévo'),
    'b2-to-fade': ('Ξεθωριάζω', 'xethoriázo'),
    'b2-wrinkle': ('Τσαλάκωμα', 'tsalákoma'),
    'b2-formal-wear': ('Επίσημη ενδυμασία', 'epísimi endymasía'),
    'b2-casual-wear': ('Καθημερινά ρούχα', 'kathimeriná roúha'),
    'b2-uniform': ('Στολή', 'stolí'),
    'b2-suit': ('Κοστούμι', 'kostoúmi'),
    'b2-tie': ('Γραβάτα', 'graváta'),
    'b2-high-heels': ('Ψηλοτάκουνα', 'psilotákouna'),
    'b2-sneakers': ('Αθλητικά παπούτσια', 'athlitiká papoútsia'),
    'b2-boots': ('Μπότες', 'bótes'),
    'b2-sandals': ('Σανδάλια', 'sandália'),
    'b2-slippers': ('Παντόφλες', 'pantófles'),
    'b2-pajamas': ('Πιτζάμες', 'pitzámes'),
    'b2-underwear': ('Εσώρουχα', 'esóroha'),
    'b2-belt': ('Ζώνη', 'zóni'),
    'b2-concept': ('Έννοια', 'énnoia'),
    'b2-notion': ('Αντίληψη', 'antílipsi'),
    'b2-aspect': ('Πτυχή', 'ptyhí'),
    'b2-factor': ('Παράγοντας', 'parágontas'),
    'b2-feature': ('Γνώρισμα', 'gnórisma'),
    'b2-element': ('Στοιχείο', 'stoiheío'),
    'b2-component': ('Συστατικό', 'systatikó'),
    'b2-structure': ('Δομή', 'domí'),
    'b2-function': ('Λειτουργία', 'leitourgía'),
    'b2-process': ('Διεργασία', 'diergasía'),
    'b2-procedure': ('Διαδικασία', 'diadikasía'),
    'b2-method': ('Μέθοδος', 'méthodos'),
    'b2-approach': ('Προσέγγιση', 'proségisi'),
    'b2-technique': ('Τεχνική', 'tehnikí'),
    'b2-framework': ('Πλαίσιο', 'pláisio'),
    'b2-criterion': ('Κριτήριο', 'kritírio'),
    'b2-standard': ('Στάνταρ', 'stántar'),
    'b2-norm': ('Κανόνας', 'kanónas'),
    'b2-exception': ('Εξαίρεση', 'exaíresi'),
    'b2-phase': ('Φάση', 'fási'),
    'b2-sequence': ('Ακολουθία', 'akolouthía'),
    'b2-outcome': ('Αποτέλεσμα', 'apotélesma'),
    'b2-consequence': ('Συνέπεια', 'synépeia'),
    'b2-impact': ('Αντίκτυπος', 'antíktypos'),
    'b2-implication': ('Επίπτωση', 'epíptosi'),
    'b2-significance': ('Σημασία', 'simasía'),
    'b2-context': ('Συμφραζόμενα', 'symfrazómena'),
    'b2-scope': ('Εύρος', 'évros'),
    'b2-scale-magnitude': ('Κλίμακα', 'klímaka'),
    'b2-dimension': ('Διάσταση', 'diástasi'),
    'b2-proportion': ('Αναλογία', 'analogía'),
    'b2-ratio': ('Λόγος', 'lógos'),
    'b2-barely': ('Μόλις', 'mólis'),
    'b2-hardly': ('Σχεδόν καθόλου', 'shedón kathólou'),
    'b2-merely': ('Απλώς', 'aplós'),
    'b2-utterly': ('Εντελώς', 'entelós'),
    'b2-thoroughly': ('Διεξοδικά', 'diexodiká'),
    'b2-fairly': ('Αρκετά', 'arketá'),
    'b2-rather': ('Μάλλον', 'mállon'),
    'b2-somewhat': ('Κάπως', 'kápos'),
    'b2-slightly': ('Ελαφρώς', 'elafrós'),
    'b2-considerably': ('Σημαντικά', 'simantiká'),
    'b2-significantly': ('Αισθητά', 'aisthitá'),
    'b2-roughly': ('Περίπου', 'perípou'),
    'b2-precisely': ('Ακριβώς', 'akrivós'),
    'b2-virtually': ('Ουσιαστικά', 'ousiastiká'),
    'b2-entirely': ('Εξ ολοκλήρου', 'ex olokliroú'),
    'b2-partially': ('Εν μέρει', 'en mérei'),
    'b2-mostly': ('Κυρίως', 'kyríos'),
    'b2-increasingly': ('Όλο και περισσότερο', 'ólo kai perissótero'),
    'b2-gradually': ('Σταδιακά', 'stadiaká'),
    'b2-rapidly': ('Γρήγορα', 'grígora'),
    'b2-steadily': ('Σταθερά', 'statherá'),
    'b2-abruptly': ('Απότομα', 'apótoma'),
    'b2-ultimately': ('Τελικά', 'teliká'),
    'b2-altogether': ('Συνολικά', 'synoliká'),
    'b2-whatsoever': ('Απολύτως', 'apolýtos'),
    'b2-nonetheless': ('Ωστόσο', 'ostóso'),
    'b2-deliberately': ('Σκόπιμα', 'skópima'),
    'b2-reluctantly': ('Απρόθυμα', 'apróthyma'),
    'b2-knitting': ('Πλέξιμο', 'pléximo'),
    'b2-sewing': ('Ράψιμο', 'rápsimo'),
    'b2-pottery': ('Κεραμική', 'keramikí'),
    'b2-woodworking': ('Ξυλουργική', 'xylourgikí'),
    'b2-gardening': ('Κηπουρική', 'kipourikí'),
    'b2-birdwatching': ('Παρατήρηση πουλιών', 'paratírisi poulión'),
    'b2-kayaking': ('Καγιάκ', 'kagiák'),
    'b2-rock-climbing': ('Αναρρίχηση', 'anarríhisi'),
    'b2-martial-arts': ('Πολεμικές τέχνες', 'polemikés téhnes'),
    'b2-boxing': ('Πυγμαχία', 'pygmahía'),
    'b2-archery': ('Τοξοβολία', 'toxovolía'),
    'b2-bowling': ('Μπόουλινγκ', 'bóouling'),
    'b2-karaoke': ('Καραόκε', 'karaóke'),
    'b2-esports': ('Ηλεκτρονικά σπορ', 'ilektroniká spor'),
    'b2-collectible': ('Συλλεκτικό αντικείμενο', 'syllektikó antikeímeno'),
    'b2-cosplay': ('Κόσπλεϊ', 'kósplei'),
    'b2-3d-printing': ('Τρισδιάστατη εκτύπωση', 'trisdiástati ektýposi'),
    'b2-tabletop-role-playing-game': ('Επιτραπέζιο παιχνίδι ρόλων', 'epitrapézio paihnídi rólon'),
    'b2-miniature-figure': ('Μινιατούρα', 'miniatoúra'),
    'b2-dice': ('Ζάρια', 'zária'),
    'b2-campaign-game': ('Εκστρατεία', 'ekstrateía'),
    'b2-hobbyist': ('Ερασιτέχνης', 'erasitéhnis'),
    'b2-craft': ('Χειροτεχνία', 'heirotehnía'),
    'b2-workbench': ('Πάγκος εργασίας', 'págkos ergasías'),
    'b2-glue': ('Κόλλα', 'kólla'),
    'b2-sandpaper': ('Γυαλόχαρτο', 'gyalóharto'),
    'b2-paintbrush': ('Πινέλο', 'pinélo'),
    'b2-prototype': ('Πρωτότυπο', 'prototýpo'),
}
