# -*- coding: utf-8 -*-
LANG = 'hi'
WORDS = {
    'a1-hello': ('नमस्ते', 'namaste'),
    'a1-goodbye': ('अलविदा', 'alvida'),
    'a1-please': ('कृपया', 'kripaya'),
    'a1-thank-you': ('धन्यवाद', 'dhanyavaad'),
    'a1-excuse-me': ('माफ़ कीजिए', 'maaf kijiye'),
    'a1-sorry': ('क्षमा करें', 'kshama karen'),
    'a1-yes': ('हाँ', 'haan'),
    'a1-no': ('नहीं', 'nahin'),
    'a1-my-name-is-alex': ('मेरा नाम एलेक्स है', 'mera naam alex hai'),
    'a1-whats-your-name': ('आपका नाम क्या है?', 'aapka naam kya hai?'),
    'a1-nice-to-meet-you': ('आपसे मिलकर खुशी हुई', 'aapse milkar khushi hui'),
    'a1-how-are-you': ('आप कैसे हैं?', 'aap kaise hain?'),
    'a1-mother': ('माँ', 'maa'),
    'a1-father': ('पिता', 'pita'),
    'a1-sister': ('बहन', 'bahan'),
    'a1-brother': ('भाई', 'bhai'),
    'a1-friend': ('दोस्त', 'dost'),
    'a1-child': ('बच्चा', 'bachcha'),
    'a1-today': ('आज', 'aaj'),
    'a1-tomorrow': ('कल', 'kal'),
    'a1-yesterday': ('बीता कल', 'beeta kal'),
    'a1-now': ('अभी', 'abhi'),
    'a1-morning': ('सुबह', 'subah'),
    'a1-night': ('रात', 'raat'),
    'a1-house': ('घर', 'ghar'),
    'a1-where-is-it': ('यह कहाँ है?', 'yah kahan hai?'),
    'a1-left': ('बायाँ', 'baayan'),
    'a1-right': ('दायाँ', 'daayan'),
    'a1-store': ('दुकान', 'dukaan'),
    'a1-bathroom': ('बाथरूम', 'baathroom'),
    'a1-water': ('पानी', 'paani'),
    'a1-bread': ('ब्रेड', 'bred'),
    'a1-coffee': ('कॉफ़ी', 'kofee'),
    'a1-tea': ('चाय', 'chai'),
    'a1-delicious': ('स्वादिष्ट', 'swaadisht'),
    'a1-spicy': ('मसालेदार', 'masaaledaar'),
    'a1-good-morning': ('सुप्रभात', 'suprabhat'),
    'a1-good-evening': ('शुभ संध्या', 'shubh sandhya'),
    'a1-good-night': ('शुभ रात्रि', 'shubh raatri'),
    'a1-youre-welcome': ('कोई बात नहीं', 'koi baat nahin'),
    'a1-see-you-soon': ('जल्द मिलते हैं', 'jald milte hain'),
    'a1-see-you-tomorrow': ('कल मिलते हैं', 'kal milte hain'),
    'a1-welcome': ('स्वागत है', 'swaagat hai'),
    'a1-cheers': ('चियर्स!', 'cheers!'),
    'a1-congratulations': ('बधाई हो', 'badhai ho'),
    'a1-happy-birthday': ('जन्मदिन मुबारक हो', 'janmadin mubarak ho'),
    'a1-good-luck': ('शुभकामनाएँ', 'shubhkaamnaaen'),
    'a1-have-a-nice-day': ('आपका दिन शुभ हो', 'aapka din shubh ho'),
    'a1-take-care': ('अपना ख्याल रखना', 'apna khyaal rakhna'),
    'a1-bless-you': ('जीते रहो', 'jeete raho'),
    'a1-enjoy-your-meal': ('भोजन का आनंद लें', 'bhojan ka aanand len'),
    'a1-nice-to-see-you': ('आपको देखकर अच्छा लगा', 'aapko dekhkar achha laga'),
    'a1-long-time-no-see': ('बहुत दिनों बाद मिले', 'bahut dinon baad mile'),
    'a1-goodbye-for-now': ('फिर मिलेंगे', 'phir milenge'),
    'a1-i': ('मैं', 'main'),
    'a1-you': ('तुम', 'tum'),
    'a1-he': ('वह', 'vah'),
    'a1-she': ('वह', 'vah'),
    'a1-we': ('हम', 'hum'),
    'a1-they': ('वे', 've'),
    'a1-man': ('आदमी', 'aadmi'),
    'a1-woman': ('औरत', 'aurat'),
    'a1-boy': ('लड़का', 'ladka'),
    'a1-girl': ('लड़की', 'ladki'),
    'a1-person': ('व्यक्ति', 'vyakti'),
    'a1-people': ('लोग', 'log'),
    'a1-name': ('नाम', 'naam'),
    'a1-mister': ('श्रीमान', 'shrimaan'),
    'a1-madam': ('श्रीमती', 'shrimati'),
    'a1-im-fine': ('मैं ठीक हूँ', 'main theek hoon'),
    'a1-and-you': ('और आप?', 'aur aap?'),
    'a1-where-are-you-from': ('आप कहाँ से हैं?', 'aap kahan se hain?'),
    'a1-im-from-the-united-states': ('मैं संयुक्त राज्य अमेरिका से हूँ', 'main sanyukt rajya america se hoon'),
    'a1-friend-female': ('सहेली', 'saheli'),
    'a1-family': ('परिवार', 'parivaar'),
    'a1-parents': ('माता-पिता', 'maata-pita'),
    'a1-son': ('बेटा', 'beta'),
    'a1-daughter': ('बेटी', 'beti'),
    'a1-husband': ('पति', 'pati'),
    'a1-wife': ('पत्नी', 'patni'),
    'a1-grandmother': ('दादी', 'dadi'),
    'a1-grandfather': ('दादा', 'dada'),
    'a1-baby': ('शिशु', 'shishu'),
    'a1-uncle': ('चाचा', 'chacha'),
    'a1-aunt': ('चाची', 'chachi'),
    'a1-cousin': ('चचेरा भाई', 'chachera bhai'),
    'a1-boyfriend': ('प्रेमी', 'premi'),
    'a1-girlfriend': ('प्रेमिका', 'premika'),
    'a1-neighbor': ('पड़ोसी', 'padosi'),
    'a1-children': ('बच्चे', 'bachche'),
    'a1-older-brother': ('बड़ा भाई', 'bada bhai'),
    'a1-younger-sister': ('छोटी बहन', 'choti bahan'),
    'a1-pet': ('पालतू जानवर', 'paaltu janwar'),
    'a1-married': ('शादीशुदा', 'shaadishuda'),
    'a1-one': ('एक', 'ek'),
    'a1-two': ('दो', 'do'),
    'a1-three': ('तीन', 'teen'),
    'a1-four': ('चार', 'chaar'),
    'a1-five': ('पाँच', 'paanch'),
    'a1-six': ('छह', 'chhah'),
    'a1-seven': ('सात', 'saat'),
    'a1-eight': ('आठ', 'aath'),
    'a1-nine': ('नौ', 'nau'),
    'a1-ten': ('दस', 'das'),
    'a1-eleven': ('ग्यारह', 'gyaarah'),
    'a1-twelve': ('बारह', 'baarah'),
    'a1-thirteen': ('तेरह', 'terah'),
    'a1-fourteen': ('चौदह', 'chaudah'),
    'a1-fifteen': ('पंद्रह', 'pandrah'),
    'a1-sixteen': ('सोलह', 'solah'),
    'a1-seventeen': ('सत्रह', 'satrah'),
    'a1-eighteen': ('अठारह', 'atharah'),
    'a1-nineteen': ('उन्नीस', 'unnis'),
    'a1-twenty': ('बीस', 'bees'),
    'a1-zero': ('शून्य', 'shoonya'),
    'a1-thirty': ('तीस', 'tees'),
    'a1-forty': ('चालीस', 'chaalees'),
    'a1-fifty': ('पचास', 'pachaas'),
    'a1-sixty': ('साठ', 'saath'),
    'a1-seventy': ('सत्तर', 'sattar'),
    'a1-eighty': ('अस्सी', 'assi'),
    'a1-ninety': ('नब्बे', 'nabbe'),
    'a1-one-hundred': ('सौ', 'sau'),
    'a1-one-thousand': ('हज़ार', 'hazaar'),
    'a1-one-million': ('दस लाख', 'das laakh'),
    'a1-first': ('पहला', 'pahla'),
    'a1-second': ('दूसरा', 'doosra'),
    'a1-third': ('तीसरा', 'teesra'),
    'a1-half': ('आधा', 'aadha'),
    'a1-many': ('बहुत सारे', 'bahut saare'),
    'a1-few': ('थोड़े', 'thode'),
    'a1-all': ('सब', 'sab'),
    'a1-some': ('कुछ', 'kuchh'),
    'a1-nothing': ('कुछ नहीं', 'kuchh nahin'),
    'a1-number': ('संख्या', 'sankhya'),
    'a1-more': ('ज़्यादा', 'zyaada'),
    'a1-less': ('कम', 'kam'),
    'a1-enough': ('काफ़ी', 'kaafi'),
    'a1-red': ('लाल', 'laal'),
    'a1-blue': ('नीला', 'neela'),
    'a1-green': ('हरा', 'hara'),
    'a1-yellow': ('पीला', 'peela'),
    'a1-black': ('काला', 'kaala'),
    'a1-white': ('सफ़ेद', 'safed'),
    'a1-orange-color': ('नारंगी', 'naarangi'),
    'a1-pink': ('गुलाबी', 'gulaabi'),
    'a1-purple': ('बैंगनी', 'baingani'),
    'a1-brown': ('भूरा', 'bhoora'),
    'a1-gray': ('स्लेटी', 'sleti'),
    'a1-color': ('रंग', 'rang'),
    'a1-light-color': ('हल्का', 'halka'),
    'a1-dark': ('गहरा', 'gahra'),
    'a1-circle': ('वृत्त', 'vritt'),
    'a1-square': ('वर्ग', 'varg'),
    'a1-triangle': ('त्रिभुज', 'tribhuj'),
    'a1-line': ('रेखा', 'rekha'),
    'a1-shape': ('आकार', 'aakaar'),
    'a1-big': ('बड़ा', 'bada'),
    'a1-small': ('छोटा', 'chota'),
    'a1-long': ('लंबा', 'lamba'),
    'a1-short-length': ('छोटा (लंबाई में)', 'chota'),
    'a1-round': ('गोल', 'gol'),
    'a1-afternoon': ('दोपहर', 'dopahar'),
    'a1-evening': ('शाम', 'shaam'),
    'a1-day': ('दिन', 'din'),
    'a1-week': ('हफ़्ता', 'hafta'),
    'a1-month': ('महीना', 'maheena'),
    'a1-year': ('साल', 'saal'),
    'a1-hour': ('घंटा', 'ghanta'),
    'a1-minute': ('मिनट', 'minat'),
    'a1-later': ('बाद में', 'baad mein'),
    'a1-early': ('जल्दी', 'jaldi'),
    'a1-late': ('देर से', 'der se'),
    'a1-always': ('हमेशा', 'hamesha'),
    'a1-never': ('कभी नहीं', 'kabhi nahin'),
    'a1-sometimes': ('कभी-कभी', 'kabhi-kabhi'),
    'a1-often': ('अक्सर', 'aksar'),
    'a1-soon': ('जल्द ही', 'jald hi'),
    'a1-again': ('फिर से', 'phir se'),
    'a1-its-late': ('देर हो गई है', 'der ho gayi hai'),
    'a1-tonight': ('आज रात', 'aaj raat'),
    'a1-before': ('पहले', 'pahle'),
    'a1-after': ('के बाद', 'ke baad'),
    'a1-noon': ('मध्याह्न', 'madhyaahn'),
    'a1-midnight': ('आधी रात', 'aadhi raat'),
    'a1-monday': ('सोमवार', 'somvaar'),
    'a1-tuesday': ('मंगलवार', 'mangalvaar'),
    'a1-wednesday': ('बुधवार', 'budhvaar'),
    'a1-thursday': ('गुरुवार', 'guruvaar'),
    'a1-friday': ('शुक्रवार', 'shukravaar'),
    'a1-saturday': ('शनिवार', 'shanivaar'),
    'a1-sunday': ('रविवार', 'ravivaar'),
    'a1-weekend': ('सप्ताहांत', 'saptaahaant'),
    'a1-january': ('जनवरी', 'janvari'),
    'a1-february': ('फ़रवरी', 'farvari'),
    'a1-march': ('मार्च', 'march'),
    'a1-april': ('अप्रैल', 'aprail'),
    'a1-may': ('मई', 'mai'),
    'a1-june': ('जून', 'joon'),
    'a1-july': ('जुलाई', 'julai'),
    'a1-august': ('अगस्त', 'agast'),
    'a1-september': ('सितंबर', 'sitambar'),
    'a1-october': ('अक्तूबर', 'aktoobar'),
    'a1-november': ('नवंबर', 'navambar'),
    'a1-december': ('दिसंबर', 'disambar'),
    'a1-spring': ('बसंत', 'basant'),
    'a1-summer': ('गर्मी', 'garmi'),
    'a1-autumn': ('पतझड़', 'patjhad'),
    'a1-winter': ('सर्दी', 'sardi'),
    'a1-birthday': ('जन्मदिन', 'janmadin'),
    'a1-holiday': ('छुट्टी', 'chhutti'),
    'a1-room': ('कमरा', 'kamra'),
    'a1-kitchen': ('रसोई', 'rasoi'),
    'a1-bedroom': ('सोने का कमरा', 'sone ka kamra'),
    'a1-door': ('दरवाज़ा', 'darwaza'),
    'a1-window': ('खिड़की', 'khidki'),
    'a1-table': ('मेज़', 'mez'),
    'a1-chair': ('कुर्सी', 'kursi'),
    'a1-bed': ('बिस्तर', 'bistar'),
    'a1-street': ('सड़क', 'sadak'),
    'a1-city': ('शहर', 'shahar'),
    'a1-country': ('देश', 'desh'),
    'a1-school': ('स्कूल', 'school'),
    'a1-hospital': ('अस्पताल', 'aspataal'),
    'a1-bank': ('बैंक', 'bank'),
    'a1-restaurant': ('रेस्तराँ', 'restaraan'),
    'a1-hotel': ('होटल', 'hotel'),
    'a1-market': ('बाज़ार', 'bazaar'),
    'a1-park': ('पार्क', 'park'),
    'a1-church': ('गिरजाघर', 'girjaghar'),
    'a1-office': ('दफ़्तर', 'daftar'),
    'a1-here': ('यहाँ', 'yahan'),
    'a1-there': ('वहाँ', 'vahan'),
    'a1-straight-ahead': ('सीधे', 'seedhe'),
    'a1-near': ('पास', 'paas'),
    'a1-far': ('दूर', 'door'),
    'a1-floor-level': ('मंज़िल', 'manzil'),
    'a1-garden': ('बगीचा', 'bageecha'),
    'a1-wall': ('दीवार', 'deewar'),
    'a1-milk': ('दूध', 'doodh'),
    'a1-rice': ('चावल', 'chaawal'),
    'a1-meat': ('माँस', 'maans'),
    'a1-fish-food': ('मछली', 'machhli'),
    'a1-chicken': ('चिकन', 'chicken'),
    'a1-egg': ('अंडा', 'anda'),
    'a1-fruit': ('फल', 'phal'),
    'a1-vegetables': ('सब्ज़ियाँ', 'sabziyaan'),
    'a1-apple': ('सेब', 'seb'),
    'a1-sugar': ('चीनी', 'cheeni'),
    'a1-salt': ('नमक', 'namak'),
    'a1-beer': ('बीयर', 'beeyar'),
    'a1-wine': ('वाइन', 'wine'),
    'a1-juice': ('जूस', 'joos'),
    'a1-breakfast': ('नाश्ता', 'naashta'),
    'a1-lunch': ('दोपहर का खाना', 'dopahar ka khaana'),
    'a1-dinner': ('रात का खाना', 'raat ka khaana'),
    'a1-im-hungry': ('मुझे भूख लगी है', 'mujhe bhookh lagi hai'),
    'a1-im-thirsty': ('मुझे प्यास लगी है', 'mujhe pyaas lagi hai'),
    'a1-cheese': ('चीज़', 'cheez'),
    'a1-soup': ('सूप', 'soop'),
    'a1-sweet': ('मीठा', 'meetha'),
    'a1-food': ('खाना', 'khaana'),
    'a1-drink-noun': ('पेय', 'peya'),
    'a1-head': ('सिर', 'sir'),
    'a1-hand': ('हाथ', 'haath'),
    'a1-eye': ('आँख', 'aankh'),
    'a1-foot': ('पैर', 'pair'),
    'a1-mouth': ('मुँह', 'munh'),
    'a1-nose': ('नाक', 'naak'),
    'a1-ear': ('कान', 'kaan'),
    'a1-arm': ('बाँह', 'baanh'),
    'a1-leg': ('टाँग', 'taang'),
    'a1-heart': ('दिल', 'dil'),
    'a1-hair': ('बाल', 'baal'),
    'a1-face': ('चेहरा', 'chehra'),
    'a1-back-body': ('पीठ', 'peeth'),
    'a1-stomach': ('पेट', 'pet'),
    'a1-tooth': ('दाँत', 'daant'),
    'a1-finger': ('उंगली', 'ungli'),
    'a1-body': ('शरीर', 'shareer'),
    'a1-blood': ('खून', 'khoon'),
    'a1-neck': ('गर्दन', 'gardan'),
    'a1-shoulder': ('कंधा', 'kandha'),
    'a1-knee': ('घुटना', 'ghutna'),
    'a1-skin': ('त्वचा', 'tvacha'),
    'a1-shirt': ('कमीज़', 'kameez'),
    'a1-pants': ('पैंट', 'pant'),
    'a1-shoes': ('जूते', 'joote'),
    'a1-dress': ('पोशाक', 'poshaak'),
    'a1-hat': ('टोपी', 'topi'),
    'a1-coat': ('कोट', 'coat'),
    'a1-jacket': ('जैकेट', 'jacket'),
    'a1-socks': ('मोज़े', 'moze'),
    'a1-skirt': ('स्कर्ट', 'skirt'),
    'a1-bag': ('बैग', 'bag'),
    'a1-glasses': ('चश्मा', 'chashma'),
    'a1-watch-wrist': ('कलाई घड़ी', 'kalai ghadi'),
    'a1-umbrella': ('छाता', 'chhaata'),
    'a1-to-wear': ('पहनना', 'pahnana'),
    'a1-sweater': ('स्वेटर', 'sweater'),
    'a1-t-shirt': ('टी-शर्ट', 't-shirt'),
    'a1-scarf': ('स्कार्फ़', 'scarf'),
    'a1-gloves': ('दस्ताने', 'dastaane'),
    'a1-clothes': ('कपड़े', 'kapde'),
    'a1-size': ('साइज़', 'size'),
    'a1-to-be': ('होना', 'hona'),
    'a1-to-have': ('के पास होना', 'ke paas hona'),
    'a1-to-do': ('करना', 'karna'),
    'a1-to-go': ('जाना', 'jaana'),
    'a1-to-come': ('आना', 'aana'),
    'a1-to-want': ('चाहना', 'chaahna'),
    'a1-to-be-able-to': ('सकना', 'sakna'),
    'a1-to-know': ('जानना', 'jaanna'),
    'a1-to-see': ('देखना', 'dekhna'),
    'a1-to-say': ('कहना', 'kahna'),
    'a1-to-eat': ('खाना', 'khaana'),
    'a1-to-drink': ('पीना', 'peena'),
    'a1-to-sleep': ('सोना', 'sona'),
    'a1-to-live': ('रहना', 'rahna'),
    'a1-to-work': ('काम करना', 'kaam karna'),
    'a1-to-speak': ('बोलना', 'bolna'),
    'a1-to-understand': ('समझना', 'samajhna'),
    'a1-to-like': ('पसंद करना', 'pasand karna'),
    'a1-to-need': ('ज़रूरत होना', 'zaroorat hona'),
    'a1-to-give': ('देना', 'dena'),
    'a1-to-take': ('लेना', 'lena'),
    'a1-to-think': ('सोचना', 'sochna'),
    'a1-to-buy': ('खरीदना', 'khareedna'),
    'a1-to-help': ('मदद करना', 'madad karna'),
    'a1-to-open': ('खोलना', 'kholna'),
    'a1-to-close': ('बंद करना', 'band karna'),
    'a1-to-look-for': ('ढूँढना', 'dhoondhna'),
    'a1-to-find': ('पाना', 'paana'),
    'a1-to-wait': ('इंतज़ार करना', 'intezaar karna'),
    'a1-to-call-phone': ('फ़ोन करना', 'phone karna'),
    'a1-to-read': ('पढ़ना', 'padhna'),
    'a1-to-write': ('लिखना', 'likhna'),
    'a1-to-listen': ('सुनना', 'sunna'),
    'a1-to-learn': ('सीखना', 'seekhna'),
    'a1-to-play': ('खेलना', 'khelna'),
    'a1-to-walk': ('चलना', 'chalna'),
    'a1-to-run': ('दौड़ना', 'daudna'),
    'a1-to-sit': ('बैठना', 'baithna'),
    'a1-to-stand': ('खड़े होना', 'khade hona'),
    'a1-to-arrive': ('पहुँचना', 'pahunchna'),
    'a1-to-leave': ('निकलना', 'nikalna'),
    'a1-to-return': ('लौटना', 'lautna'),
    'a1-to-put': ('रखना', 'rakhna'),
    'a1-to-bring': ('लाना', 'laana'),
    'a1-to-ask': ('पूछना', 'poochhna'),
    'a1-to-answer': ('जवाब देना', 'jawaab dena'),
    'a1-to-love': ('प्यार करना', 'pyaar karna'),
    'a1-to-pay': ('भुगतान करना', 'bhugtaan karna'),
    'a1-good': ('अच्छा', 'achha'),
    'a1-bad': ('बुरा', 'bura'),
    'a1-new': ('नया', 'naya'),
    'a1-old-thing': ('पुराना', 'puraana'),
    'a1-young': ('जवान', 'javaan'),
    'a1-hot': ('गरम', 'garam'),
    'a1-cold': ('ठंडा', 'thanda'),
    'a1-happy': ('खुश', 'khush'),
    'a1-sad': ('उदास', 'udaas'),
    'a1-beautiful': ('सुंदर', 'sundar'),
    'a1-ugly': ('बदसूरत', 'badsoorat'),
    'a1-easy': ('आसान', 'aasaan'),
    'a1-difficult': ('मुश्किल', 'mushkil'),
    'a1-fast': ('तेज़', 'tez'),
    'a1-slow': ('धीमा', 'dheema'),
    'a1-cheap': ('सस्ता', 'sasta'),
    'a1-expensive': ('महँगा', 'mahanga'),
    'a1-full': ('भरा हुआ', 'bhara hua'),
    'a1-empty': ('खाली', 'khaali'),
    'a1-clean': ('साफ़', 'saaf'),
    'a1-dirty': ('गंदा', 'ganda'),
    'a1-strong': ('मज़बूत', 'mazboot'),
    'a1-weak': ('कमज़ोर', 'kamzor'),
    'a1-important': ('ज़रूरी', 'zaroori'),
    'a1-what': ('क्या', 'kya'),
    'a1-who': ('कौन', 'kaun'),
    'a1-where': ('कहाँ', 'kahan'),
    'a1-when': ('कब', 'kab'),
    'a1-why': ('क्यों', 'kyon'),
    'a1-how': ('कैसे', 'kaise'),
    'a1-how-many': ('कितने', 'kitne'),
    'a1-which': ('कौन सा', 'kaun sa'),
    'a1-and': ('और', 'aur'),
    'a1-or': ('या', 'ya'),
    'a1-but': ('लेकिन', 'lekin'),
    'a1-because': ('क्योंकि', 'kyonki'),
    'a1-with': ('साथ', 'saath'),
    'a1-without': ('बिना', 'bina'),
    'a1-for': ('के लिए', 'ke liye'),
    'a1-from': ('से', 'se'),
    'a1-to-direction': ('को', 'ko'),
    'a1-in': ('में', 'mein'),
    'a1-on': ('पर', 'par'),
    'a1-under': ('नीचे', 'neeche'),
    'a1-this': ('यह', 'yah'),
    'a1-that': ('वह', 'vah'),
    'a1-very': ('बहुत', 'bahut'),
    'a1-also': ('भी', 'bhi'),
    'a1-not': ('नहीं', 'nahin'),
    'a1-maybe': ('शायद', 'shaayad'),
    'a1-sun': ('सूरज', 'sooraj'),
    'a1-rain': ('बारिश', 'baarish'),
    'a1-snow': ('बर्फ़', 'barf'),
    'a1-wind': ('हवा', 'hawa'),
    'a1-cloud': ('बादल', 'baadal'),
    'a1-weather': ('मौसम', 'mausam'),
    'a1-sky': ('आकाश', 'aakaash'),
    'a1-sea': ('समुद्र', 'samudra'),
    'a1-mountain': ('पहाड़', 'pahaad'),
    'a1-river': ('नदी', 'nadi'),
    'a1-tree': ('पेड़', 'ped'),
    'a1-flower': ('फूल', 'phool'),
    'a1-dog': ('कुत्ता', 'kutta'),
    'a1-cat': ('बिल्ली', 'billi'),
    'a1-bird': ('चिड़िया', 'chidiya'),
    'a1-fish-animal': ('मछली', 'machhli'),
    'a1-horse': ('घोड़ा', 'ghoda'),
    'a1-cow': ('गाय', 'gaay'),
    'a1-earth': ('पृथ्वी', 'prithvi'),
    'a1-moon': ('चाँद', 'chaand'),
    'a1-star': ('तारा', 'taara'),
    'a1-fire': ('आग', 'aag'),
    'a1-its-windy': ('हवा चल रही है', 'hawa chal rahi hai'),
    'a1-its-snowing': ('बर्फ़ पड़ रही है', 'barf pad rahi hai'),
    'a1-its-cold-today': ('आज ठंड है', 'aaj thand hai'),
    'a1-its-hot-today': ('आज गर्मी है', 'aaj garmi hai'),
    'a1-help': ('बचाओ!', 'bachao!'),
    'a1-slowly-please': ('धीरे बोलिए, कृपया', 'dheere boliye, kripaya'),
    'a1-do-you-speak-english': ('क्या आप अंग्रेज़ी बोलते हैं?', 'kya aap angrezi bolte hain?'),
    'a1-i-dont-know': ('मुझे नहीं पता', 'mujhe nahin pata'),
    'a1-where-is-the-bathroom': ('बाथरूम कहाँ है?', 'baathroom kahan hai?'),
    'a1-which-way': ('किस तरफ़?', 'kis taraf?'),
    'a1-one-moment-please': ('एक पल रुकिए, कृपया', 'ek pal rukiye, kripaya'),
    'a1-of-course': ('बिल्कुल', 'bilkul'),
    'a1-no-problem': ('कोई दिक्कत नहीं', 'koi dikkat nahin'),
    'a1-its-okay': ('ठीक है', 'theek hai'),
    'a1-lets-go': ('चलो चलें', 'chalo chalen'),
    'a1-come-in': ('अंदर आइए', 'andar aaiye'),
    'a1-be-careful': ('सावधान रहें', 'saavdhaan rahen'),
    'a1-can-you-help-me': ('क्या आप मेरी मदद कर सकते हैं?', 'kya aap meri madad kar sakte hain?'),
    'a1-what-does-that-mean': ('इसका मतलब क्या है?', 'iska matlab kya hai?'),
    'a1-can-you-repeat-that': ('क्या आप इसे दोहरा सकते हैं?', 'kya aap ise dohra sakte hain?'),
    'a1-slower-please': ('थोड़ा धीरे बोलिए', 'thoda dheere boliye'),
    'a1-how-do-you-say': ('आप कैसे कहते हैं...?', 'aap kaise kahte hain...?'),
    'a1-i-would-like': ('मुझे चाहिए...', 'mujhe chaahiye...'),
    'a1-the-bill-please': ('बिल दीजिए', 'bil dijiye'),
    'a1-im-tired': ('मैं थका हुआ हूँ', 'main thaka hua hoon'),
    'a1-im-sick': ('मैं बीमार हूँ', 'main beemaar hoon'),
    'a1-its-an-emergency': ('यह एक आपातकाल है', 'yah ek aapaatkaal hai'),
    'a1-call-the-police': ('पुलिस को बुलाओ', 'pulis ko bulao'),
    'a1-i-speak-a-little': ('मैं थोड़ा बोलता हूँ', 'main thoda bolta hoon'),
    'a1-i-love-it': ('मुझे यह बहुत पसंद है', 'mujhe yah bahut pasand hai'),
    'a1-whats-this': ('यह क्या है?', 'yah kya hai?'),
    'a1-i-agree': ('मैं सहमत हूँ', 'main sahmat hoon'),
    'a1-i-dont-like-it': ('मुझे यह पसंद नहीं है', 'mujhe yah pasand nahin hai'),
    'a1-really': ('सच में?', 'sach mein?'),
    'a1-exactly': ('बिल्कुल सही', 'bilkul sahi'),
    'a1-i-think-so': ('मुझे ऐसा लगता है', 'mujhe aisa lagta hai'),
    'a1-dont-worry': ('चिंता मत करो', 'chinta mat karo'),
    'a1-just-a-little': ('बस थोड़ा सा', 'bas thoda sa'),
    'a1-wait-a-moment': ('एक पल रुको', 'ek pal ruko'),
    'a1-is-this-seat-free': ('क्या यह सीट खाली है?', 'kya yah seat khaali hai?'),
    'a1-money': ('पैसा', 'paisa'),
    'a1-price': ('कीमत', 'keemat'),
    'a1-to-sell': ('बेचना', 'bechna'),
    'a1-card': ('कार्ड', 'card'),
    'a1-cash': ('नकद', 'nakad'),
    'a1-receipt': ('रसीद', 'raseed'),
    'a1-open-shop': ('खुला', 'khula'),
    'a1-closed-shop': ('बंद', 'band'),
    'a1-free-no-cost': ('मुफ़्त', 'muft'),
    'a1-discount': ('छूट', 'chhoot'),
    'a1-how-much-is-it': ('इसकी कीमत क्या है?', 'iski keemat kya hai?'),
    'a1-too-much': ('बहुत ज़्यादा', 'bahut zyaada'),
    'a1-gift': ('तोहफ़ा', 'tohfa'),
    'a1-change-coins': ('खुले पैसे', 'khule paise'),
    'a1-supermarket': ('सुपरमार्केट', 'supermarket'),
    'a1-pharmacy': ('दवा की दुकान', 'dawa ki dukaan'),
    'a1-bakery': ('बेकरी', 'bakery'),
    'a1-is-this-on-sale': ('क्या यह सेल पर है?', 'kya yah sale par hai?'),
    'a1-car': ('कार', 'car'),
    'a1-bus': ('बस', 'bus'),
    'a1-train': ('ट्रेन', 'train'),
    'a1-plane': ('हवाई जहाज़', 'hawai jahaaz'),
    'a1-bicycle': ('साइकिल', 'saikil'),
    'a1-taxi': ('टैक्सी', 'taxi'),
    'a1-ticket': ('टिकट', 'tikat'),
    'a1-station': ('स्टेशन', 'station'),
    'a1-airport': ('हवाई अड्डा', 'hawai adda'),
    'a1-road': ('मार्ग', 'maarg'),
    'a1-to-travel': ('यात्रा करना', 'yaatra karna'),
    'a1-trip': ('यात्रा', 'yaatra'),
    'a1-map': ('नक्शा', 'naksha'),
    'a1-stop-bus-stop': ('बस स्टॉप', 'bus stop'),
    'a1-to-drive': ('गाड़ी चलाना', 'gaadi chalaana'),
    'a1-subway': ('मेट्रो', 'metro'),
    'a1-passport': ('पासपोर्ट', 'passport'),
    'a1-suitcase': ('सूटकेस', 'suitcase'),
    'a1-exit': ('निकास', 'nikaas'),
    'a1-entrance': ('प्रवेश', 'pravesh'),
    'a1-phone': ('फ़ोन', 'phone'),
    'a1-book': ('किताब', 'kitaab'),
    'a1-pen': ('कलम', 'kalam'),
    'a1-paper': ('काग़ज़', 'kaagaz'),
    'a1-key': ('चाबी', 'chaabi'),
    'a1-computer': ('कंप्यूटर', 'computer'),
    'a1-clock': ('दीवार घड़ी', 'deewar ghadi'),
    'a1-television': ('टेलीविज़न', 'television'),
    'a1-camera': ('कैमरा', 'camera'),
    'a1-box': ('डिब्बा', 'dibba'),
    'a1-glass-cup': ('गिलास', 'gilaas'),
    'a1-bottle': ('बोतल', 'botal'),
    'a1-plate': ('थाली', 'thaali'),
    'a1-knife': ('चाकू', 'chaaku'),
    'a1-fork': ('काँटा', 'kaanta'),
    'a1-spoon': ('चम्मच', 'chammach'),
    'a1-cup': ('कप', 'cup'),
    'a1-soap': ('साबुन', 'saabun'),
    'a1-towel': ('तौलिया', 'tauliya'),
    'a1-lamp': ('लैंप', 'lamp'),
    'a1-wallet': ('बटुआ', 'batua'),
    'a1-charger': ('चार्जर', 'charger'),
    'a1-thing': ('चीज़', 'cheez'),
    'a1-toothbrush': ('टूथब्रश', 'toothbrush'),
    'a1-angry': ('गुस्सा', 'gussa'),
    'a1-scared': ('डरा हुआ', 'dara hua'),
    'a1-bored': ('ऊबा हुआ', 'ooba hua'),
    'a1-excited': ('उत्साहित', 'utsaahit'),
    'a1-worried': ('चिंतित', 'chintit'),
    'a1-surprised': ('हैरान', 'hairaan'),
    'a1-calm': ('शांत', 'shaant'),
    'a1-nervous': ('घबराया हुआ', 'ghabraaya hua'),
    'a1-proud': ('गर्वित', 'garvit'),
    'a1-lonely': ('अकेला', 'akela'),
    'a1-sleepy': ('उनींदा', 'uninda'),
    'a1-sick-unwell': ('बीमार', 'beemaar'),
    'a1-love': ('प्यार', 'pyaar'),
    'a1-fear': ('डर', 'dar'),
    'a1-joy': ('खुशी', 'khushi'),
    'a1-funny': ('मज़ेदार', 'mazedaar'),
    'a2-i-work-in-an-office': ('मैं एक दफ़्तर में काम करता हूँ', 'main ek daftar mein kaam karta hoon'),
    'a2-i-am-a-student': ('मैं एक छात्र हूँ', 'main ek chhatra hoon'),
    'a2-i-have-a-meeting': ('मेरी एक मीटिंग है', 'meri ek meeting hai'),
    'a2-i-am-looking-for-a-job': ('मैं नौकरी ढूँढ रहा हूँ', 'main naukri dhoondh raha hoon'),
    'a2-i-am-studying': ('मैं पढ़ाई कर रहा हूँ', 'main padhai kar raha hoon'),
    'a2-i-dont-understand': ('मुझे समझ नहीं आता', 'mujhe samajh nahin aata'),
    'a2-how-much-is-this': ('यह कितने का है?', 'yah kitne ka hai?'),
    'a2-its-too-expensive': ('यह बहुत महँगा है', 'yah bahut mahanga hai'),
    'a2-can-i-pay-by-card': ('क्या मैं कार्ड से भुगतान कर सकता हूँ?', 'kya main card se bhugtaan kar sakta hoon?'),
    'a2-do-you-have-a-discount': ('क्या कोई छूट है?', 'kya koi chhoot hai?'),
    'a2-im-just-looking': ('मैं बस देख रहा हूँ', 'main bas dekh raha hoon'),
    'a2-ill-take-it': ('मैं यह ले लूँगा', 'main yah le loonga'),
    'a2-where-is-the-train-station': ('रेलवे स्टेशन कहाँ है?', 'railway station kahan hai?'),
    'a2-one-ticket-please': ('एक टिकट, कृपया', 'ek tikat, kripaya'),
    'a2-how-do-i-get-to-the-airport': ('मैं हवाई अड्डे कैसे पहुँचूँ?', 'main hawai adde kaise pahunchoon?'),
    'a2-im-lost': ('मैं रास्ता भूल गया हूँ', 'main raasta bhool gaya hoon'),
    'a2-is-it-far': ('क्या यह दूर है?', 'kya yah door hai?'),
    'a2-where-is-the-restroom': ('शौचालय कहाँ है?', 'shauchaalay kahan hai?'),
    'a2-i-dont-feel-well': ('मेरी तबीयत ठीक नहीं है', 'meri tabiyat theek nahin hai'),
    'a2-i-have-a-headache': ('मेरे सिर में दर्द है', 'mere sir mein dard hai'),
    'a2-where-is-the-pharmacy': ('दवा की दुकान कहाँ है?', 'dawa ki dukaan kahan hai?'),
    'a2-i-need-a-doctor': ('मुझे डॉक्टर चाहिए', 'mujhe doctor chaahiye'),
    'a2-im-allergic-to-peanuts': ('मुझे मूँगफली से एलर्जी है', 'mujhe moongphali se allergy hai'),
    'a2-it-hurts-here': ('यहाँ दर्द होता है', 'yahan dard hota hai'),
    'a2-its-sunny': ('धूप है', 'dhoop hai'),
    'a2-its-raining': ('बारिश हो रही है', 'baarish ho rahi hai'),
    'a2-i-like-to-read': ('मुझे पढ़ना पसंद है', 'mujhe padhna pasand hai'),
    'a2-my-favorite-is-music': ('मेरी पसंदीदा चीज़ संगीत है', 'meri pasandeeda cheez sangeet hai'),
    'a2-on-weekends-i-rest': ('सप्ताहांत में मैं आराम करता हूँ', 'saptaahaant mein main aaraam karta hoon'),
    'a2-i-play-sports': ('मैं खेल खेलता हूँ', 'main khel khelta hoon'),
    'a2-what-time-is-it': ('कितने बजे हैं?', 'kitne baje hain?'),
    'a2-lets-meet-tomorrow': ('चलो कल मिलते हैं', 'chalo kal milte hain'),
    'a2-can-you-call-me': ('क्या आप मुझे फ़ोन कर सकते हैं?', 'kya aap mujhe phone kar sakte hain?'),
    'a2-see-you-later': ('बाद में मिलते हैं', 'baad mein milte hain'),
    'a2-whats-your-phone-number': ('आपका फ़ोन नंबर क्या है?', 'aapka phone number kya hai?'),
    'a2-im-busy-today': ('आज मैं व्यस्त हूँ', 'aaj main vyast hoon'),
    'a2-job': ('नौकरी', 'naukri'),
    'a2-boss': ('बॉस', 'boss'),
    'a2-colleague': ('सहकर्मी', 'sahkarmi'),
    'a2-salary': ('वेतन', 'vetan'),
    'a2-to-earn': ('कमाना', 'kamaana'),
    'a2-class': ('कक्षा', 'kaksha'),
    'a2-teacher': ('शिक्षक', 'shikshak'),
    'a2-exam': ('परीक्षा', 'pareeksha'),
    'a2-homework': ('होमवर्क', 'homework'),
    'a2-university': ('विश्वविद्यालय', 'vishvavidyaalay'),
    'a2-to-teach': ('पढ़ाना', 'padhaana'),
    'a2-project': ('प्रोजेक्ट', 'project'),
    'a2-deadline': ('अंतिम तिथि', 'antim tithi'),
    'a2-interview': ('इंटरव्यू', 'interview'),
    'a2-career': ('करियर', 'career'),
    'a2-break-pause': ('ब्रेक', 'break'),
    'a2-schedule': ('शेड्यूल', 'schedule'),
    'a2-company': ('कंपनी', 'company'),
    'a2-customer': ('ग्राहक', 'grahak'),
    'a2-unemployed': ('बेरोज़गार', 'berozgaar'),
    'a2-to-try-on': ('पहन कर देखना', 'pahan kar dekhna'),
    'a2-fitting-room': ('ट्रायल रूम', 'trial room'),
    'a2-sale-discount-event': ('सेल', 'sale'),
    'a2-to-return-an-item': ('वापस करना', 'waapas karna'),
    'a2-refund': ('रिफंड', 'refund'),
    'a2-brand': ('ब्रांड', 'brand'),
    'a2-quality': ('गुणवत्ता', 'gunvatta'),
    'a2-cashier': ('कैशियर', 'cashier'),
    'a2-shopping-cart': ('ट्रॉली', 'trolley'),
    'a2-online-shopping': ('ऑनलाइन खरीदारी', 'online khareedaari'),
    'a2-to-order-online': ('ऑनलाइन ऑर्डर करना', 'online order karna'),
    'a2-delivery': ('डिलीवरी', 'delivery'),
    'a2-package': ('पार्सल', 'parcel'),
    'a2-to-choose': ('चुनना', 'chunna'),
    'a2-to-compare': ('तुलना करना', 'tulna karna'),
    'a2-it-fits-me': ('यह मुझ पर ठीक बैठता है', 'yah mujh par theek baithta hai'),
    'a2-too-big': ('बहुत बड़ा', 'bahut bada'),
    'a2-do-you-have-it-in-another-color': ('क्या यह किसी और रंग में है?', 'kya yah kisi aur rang mein hai?'),
    'a2-mall': ('मॉल', 'mall'),
    'a2-cheaper': ('और सस्ता', 'aur sasta'),
    'a2-reservation': ('रिज़र्वेशन', 'reservation'),
    'a2-to-book': ('बुक करना', 'book karna'),
    'a2-check-in': ('चेक-इन', 'check-in'),
    'a2-luggage': ('सामान', 'saamaan'),
    'a2-flight': ('उड़ान', 'udaan'),
    'a2-delay': ('देरी', 'deri'),
    'a2-departure': ('प्रस्थान', 'prasthaan'),
    'a2-arrival': ('आगमन', 'aagaman'),
    'a2-gate': ('गेट', 'gate'),
    'a2-seat': ('सीट', 'seat'),
    'a2-tourist': ('पर्यटक', 'paryatak'),
    'a2-guide': ('गाइड', 'guide'),
    'a2-sightseeing': ('सैर-सपाटा', 'sair-sapaata'),
    'a2-souvenir': ('स्मृति चिन्ह', 'smriti chinh'),
    'a2-beach': ('समुद्र तट', 'samudra tat'),
    'a2-museum': ('संग्रहालय', 'sangrahaalay'),
    'a2-to-visit': ('घूमने जाना', 'ghoomne jaana'),
    'a2-round-trip': ('आने-जाने का टिकट', 'aane-jaane ka tikat'),
    'a2-one-way': ('एक तरफ़ा', 'ek tarfa'),
    'a2-abroad': ('विदेश में', 'videsh mein'),
    'a2-doctor': ('डॉक्टर', 'doctor'),
    'a2-nurse': ('नर्स', 'nurse'),
    'a2-medicine': ('दवा', 'dawa'),
    'a2-pain': ('दर्द', 'dard'),
    'a2-fever': ('बुख़ार', 'bukhaar'),
    'a2-cough': ('खाँसी', 'khaansi'),
    'a2-a-cold-illness': ('ज़ुकाम', 'zukaam'),
    'a2-flu': ('फ़्लू', 'flu'),
    'a2-allergy': ('एलर्जी', 'allergy'),
    'a2-appointment': ('अपॉइंटमेंट', 'appointment'),
    'a2-prescription': ('पर्ची', 'parchi'),
    'a2-stomachache': ('पेट दर्द', 'pet dard'),
    'a2-healthy': ('स्वस्थ', 'swasth'),
    'a2-to-rest': ('आराम करना', 'aaraam karna'),
    'a2-insurance': ('बीमा', 'beema'),
    'a2-emergency': ('आपातकाल', 'aapaatkaal'),
    'a2-dentist': ('दंत चिकित्सक', 'dant chikitsak'),
    'a2-injury': ('चोट', 'chot'),
    'a2-i-feel-better': ('मुझे बेहतर महसूस हो रहा है', 'mujhe behtar mehsoos ho raha hai'),
    'a2-blood-pressure': ('रक्तचाप', 'raktachaap'),
    'a2-hobby': ('शौक', 'shauk'),
    'a2-music': ('संगीत', 'sangeet'),
    'a2-movie': ('फ़िल्म', 'film'),
    'a2-sport': ('खेल', 'khel'),
    'a2-soccer': ('फ़ुटबॉल', 'football'),
    'a2-to-swim': ('तैरना', 'tairna'),
    'a2-to-dance': ('नाचना', 'naachna'),
    'a2-to-sing': ('गाना गाना', 'gaana gaana'),
    'a2-to-paint': ('चित्र बनाना', 'chitra banaana'),
    'a2-game': ('गेम', 'game'),
    'a2-team': ('टीम', 'team'),
    'a2-to-win': ('जीतना', 'jeetna'),
    'a2-to-lose-a-game': ('हारना', 'haarna'),
    'a2-concert': ('संगीत कार्यक्रम', 'sangeet kaaryakram'),
    'a2-photography': ('फ़ोटोग्राफ़ी', 'photography'),
    'a2-to-hike': ('लंबी पैदल यात्रा करना', 'lambi paidal yaatra karna'),
    'a2-gym': ('जिम', 'gym'),
    'a2-to-exercise': ('व्यायाम करना', 'vyaayaam karna'),
    'a2-cloudy': ('बादल छाए हुए', 'baadal chhaaye hue'),
    'a2-storm': ('तूफ़ान', 'toofaan'),
    'a2-humid': ('उमस भरा', 'umas bhara'),
    'a2-forecast': ('पूर्वानुमान', 'poorvaanumaan'),
    'a2-to-plan': ('योजना बनाना', 'yojana banaana'),
    'a2-to-meet-up': ('मिलना', 'milna'),
    'a2-invitation': ('निमंत्रण', 'nimantran'),
    'a2-to-invite': ('आमंत्रित करना', 'aamantrit karna'),
    'a2-to-cancel': ('रद्द करना', 'radd karna'),
    'a2-free-time': ('खाली समय', 'khaali samay'),
    'a2-to-postpone': ('स्थगित करना', 'sthagit karna'),
    'a2-internet': ('इंटरनेट', 'internet'),
    'a2-email': ('ईमेल', 'email'),
    'a2-message': ('संदेश', 'sandesh'),
    'a2-to-send': ('भेजना', 'bhejna'),
    'a2-to-download': ('डाउनलोड करना', 'download karna'),
    'a2-app': ('ऐप', 'app'),
    'a2-password': ('पासवर्ड', 'password'),
    'a2-screen': ('स्क्रीन', 'screen'),
    'a2-wi-fi': ('वाई-फ़ाई', 'wi-fi'),
    'a2-website': ('वेबसाइट', 'website'),
    'a2-video-call': ('वीडियो कॉल', 'video call'),
    'a2-are-you-free-on-saturday': ('क्या आप शनिवार को खाली हैं?', 'kya aap shanivaar ko khaali hain?'),
    'a2-sounds-good': ('अच्छा लगता है', 'achha lagta hai'),
    'a2-to-clean': ('साफ़ करना', 'saaf karna'),
    'a2-to-wash': ('धोना', 'dhona'),
    'a2-dishes': ('बर्तन', 'bartan'),
    'a2-laundry': ('गंदे कपड़े', 'gande kapde'),
    'a2-to-iron': ('इस्त्री करना', 'istri karna'),
    'a2-trash': ('कचरा', 'kachra'),
    'a2-to-tidy-up': ('व्यवस्थित करना', 'vyavasthit karna'),
    'a2-vacuum-cleaner': ('वैक्यूम क्लीनर', 'vacuum cleaner'),
    'a2-to-repair': ('ठीक करना', 'theek karna'),
    'a2-to-move-house': ('घर बदलना', 'ghar badalna'),
    'a2-rent': ('किराया', 'kiraya'),
    'a2-landlord': ('मकान मालिक', 'makaan maalik'),
    'a2-apartment': ('फ्लैट', 'flat'),
    'a2-furniture': ('फ़र्नीचर', 'furniture'),
    'a2-sofa': ('सोफ़ा', 'sofa'),
    'a2-fridge': ('फ्रिज', 'fridge'),
    'a2-oven': ('ओवन', 'oven'),
    'a2-stove': ('चूल्हा', 'choolha'),
    'a2-shower': ('शावर', 'shower'),
    'a2-mirror': ('आईना', 'aaina'),
    'a2-pillow': ('तकिया', 'takiya'),
    'a2-blanket': ('कंबल', 'kambal'),
    'a2-washing-machine': ('वॉशिंग मशीन', 'washing machine'),
    'a2-roommate': ('साथ रहने वाला', 'saath rahne waala'),
    'a2-stairs': ('सीढ़ियाँ', 'seedhiyaan'),
    'a2-elevator': ('लिफ़्ट', 'lift'),
    'a2-to-wake-up': ('जागना', 'jaagna'),
    'a2-to-get-up': ('उठना', 'uthna'),
    'a2-to-take-a-shower': ('नहाना', 'nahaana'),
    'a2-to-brush-ones-teeth': ('दाँत साफ़ करना', 'daant saaf karna'),
    'a2-to-get-dressed': ('कपड़े पहनना', 'kapde pahnana'),
    'a2-to-have-breakfast': ('नाश्ता करना', 'naashta karna'),
    'a2-to-commute': ('काम पर आना-जाना', 'kaam par aana-jaana'),
    'a2-to-go-home': ('घर जाना', 'ghar jaana'),
    'a2-to-relax': ('सुस्ताना', 'sustaana'),
    'a2-to-watch-tv': ('टीवी देखना', 'TV dekhna'),
    'a2-to-go-to-bed': ('सोने जाना', 'sone jaana'),
    'a2-routine': ('दिनचर्या', 'dincharya'),
    'a2-habit': ('आदत', 'aadat'),
    'a2-alarm-clock': ('अलार्म घड़ी', 'alarm ghadi'),
    'a2-to-be-late': ('देर होना', 'der hona'),
    'a2-to-hurry': ('जल्दी करना', 'jaldi karna'),
    'a2-on-time': ('समय पर', 'samay par'),
    'a2-nap': ('झपकी', 'jhapki'),
    'a2-to-take-a-walk': ('टहलना', 'tahalna'),
    'a2-to-have-lunch': ('दोपहर का खाना खाना', 'dopahar ka khaana khaana'),
    'a2-to-have-dinner': ('रात का खाना खाना', 'raat ka khaana khaana'),
    'a2-to-fall-asleep': ('नींद आ जाना', 'neend aa jaana'),
    'a2-every-day': ('हर दिन', 'har din'),
    'a2-usually': ('आमतौर पर', 'aamtaur par'),
    'a2-corner': ('कोना', 'kona'),
    'a2-block': ('ब्लॉक', 'block'),
    'a2-traffic-light': ('ट्रैफ़िक लाइट', 'traffic light'),
    'a2-bridge': ('पुल', 'pul'),
    'a2-square-plaza': ('चौक', 'chauk'),
    'a2-downtown': ('शहर का केंद्र', 'shahar ka kendra'),
    'a2-neighborhood': ('मोहल्ला', 'mohalla'),
    'a2-building': ('इमारत', 'imaarat'),
    'a2-sidewalk': ('फ़ुटपाथ', 'footpath'),
    'a2-to-cross': ('पार करना', 'paar karna'),
    'a2-to-turn': ('मुड़ना', 'mudna'),
    'a2-address': ('पता', 'pata'),
    'a2-post-office': ('डाकघर', 'daakghar'),
    'a2-library': ('पुस्तकालय', 'pustakaalay'),
    'a2-cinema': ('सिनेमा', 'cinema'),
    'a2-theater': ('थिएटर', 'theatre'),
    'a2-stadium': ('स्टेडियम', 'stadium'),
    'a2-police-station': ('पुलिस स्टेशन', 'police station'),
    'a2-town-hall': ('नगर भवन', 'nagar bhavan'),
    'a2-parking-lot': ('पार्किंग', 'parking'),
    'a2-gas-station': ('पेट्रोल पंप', 'petrol pump'),
    'a2-traffic': ('ट्रैफ़िक', 'traffic'),
    'a2-opposite': ('सामने', 'saamne'),
    'a2-next-to': ('के बगल में', 'ke bagal mein'),
    'a2-between': ('बीच में', 'beech mein'),
    'a2-how-do-i-get-to': ('मैं ...कैसे पहुँचूँ?', 'main ...kaise pahunchoon?'),
    'a2-menu': ('मेनू', 'menu'),
    'a2-waiter': ('वेटर', 'waiter'),
    'a2-dish': ('व्यंजन', 'vyanjan'),
    'a2-dessert': ('मिठाई', 'mithaai'),
    'a2-starter': ('स्टार्टर', 'starter'),
    'a2-main-course': ('मुख्य व्यंजन', 'mukhya vyanjan'),
    'a2-vegetarian': ('शाकाहारी', 'shaakaahaari'),
    'a2-tip': ('टिप', 'tip'),
    'a2-to-cook': ('खाना बनाना', 'khaana banaana'),
    'a2-recipe': ('रेसिपी', 'recipe'),
    'a2-ingredient': ('सामग्री', 'saamagri'),
    'a2-oil': ('तेल', 'tel'),
    'a2-butter': ('मक्खन', 'makkhan'),
    'a2-pepper': ('काली मिर्च', 'kaali mirch'),
    'a2-onion': ('प्याज़', 'pyaaz'),
    'a2-garlic': ('लहसुन', 'lahsun'),
    'a2-tomato': ('टमाटर', 'tamaatar'),
    'a2-potato': ('आलू', 'aloo'),
    'a2-noodles': ('नूडल्स', 'noodles'),
    'a2-sauce': ('सॉस', 'sauce'),
    'a2-to-bake': ('बेक करना', 'bake karna'),
    'a2-to-fry': ('तलना', 'talna'),
    'a2-to-boil': ('उबालना', 'ubaalna'),
    'a2-a-table-for-two': ('दो लोगों के लिए मेज़', 'do logon ke liye mez'),
    'a2-takeout': ('पैक करवाना', 'pack karvaana'),
    'a2-snack': ('स्नैक्स', 'snacks'),
    'a2-salty': ('नमकीन', 'namkeen'),
    'a2-bitter': ('कड़वा', 'kadva'),
    'a2-tall': ('लंबा', 'lamba'),
    'a2-short-height': ('नाटा', 'naata'),
    'a2-thin': ('पतला', 'patla'),
    'a2-overweight': ('मोटा', 'mota'),
    'a2-blond': ('सुनहरे बालों वाला', 'sunahre baalon waala'),
    'a2-dark-haired': ('काले बालों वाला', 'kaale baalon waala'),
    'a2-beard': ('दाढ़ी', 'daadhi'),
    'a2-kind': ('दयालु', 'dayaalu'),
    'a2-nice-person': ('भला', 'bhala'),
    'a2-shy': ('शर्मीला', 'sharmeela'),
    'a2-talkative': ('बातूनी', 'baatooni'),
    'a2-smart': ('होशियार', 'hoshiyaar'),
    'a2-lazy': ('आलसी', 'aalasi'),
    'a2-hardworking': ('मेहनती', 'mehnati'),
    'a2-polite': ('विनम्र', 'vinamra'),
    'a2-rude': ('असभ्य', 'asabhya'),
    'a2-patient': ('धैर्यवान', 'dhairyavaan'),
    'a2-honest': ('ईमानदार', 'imaandaar'),
    'a2-serious': ('गंभीर', 'gambheer'),
    'a2-quiet-person': ('कम बोलने वाला', 'kam bolne waala'),
    'a2-friendly': ('मिलनसार', 'milansaar'),
    'a2-handsome': ('आकर्षक', 'aakarshak'),
    'a2-age': ('उम्र', 'umra'),
    'a2-old-person': ('बूढ़ा', 'budha'),
    'a2-curly-hair': ('घुँघराले बाल', 'ghungharaale baal'),
    'a2-cheerful': ('खुशमिज़ाज', 'khushmizaaj'),
    'a2-stubborn': ('ज़िद्दी', 'ziddi'),
    'a2-generous': ('उदार', 'udaar'),
    'a2-to-try': ('कोशिश करना', 'koshish karna'),
    'a2-to-start': ('शुरू करना', 'shuru karna'),
    'a2-to-finish': ('खत्म करना', 'khatm karna'),
    'a2-to-change': ('बदलना', 'badalna'),
    'a2-to-use': ('इस्तेमाल करना', 'istemaal karna'),
    'a2-to-receive': ('प्राप्त करना', 'praapt karna'),
    'a2-to-decide': ('फ़ैसला करना', 'faisla karna'),
    'a2-to-forget': ('भूलना', 'bhoolna'),
    'a2-to-remember': ('याद रखना', 'yaad rakhna'),
    'a2-to-lose-an-object': ('खोना', 'khona'),
    'a2-to-meet-someone-new': ('जान-पहचान करना', 'jaan-pehchaan karna'),
    'a2-to-prefer': ('ज़्यादा पसंद करना', 'zyaada pasand karna'),
    'a2-to-hope': ('आशा करना', 'aasha karna'),
    'a2-to-believe': ('विश्वास करना', 'vishwaas karna'),
    'a2-to-feel': ('महसूस करना', 'mehsoos karna'),
    'a2-to-seem': ('लगना', 'lagna'),
    'a2-to-happen': ('घटना', 'ghatna'),
    'a2-to-stay': ('रुकना', 'rukna'),
    'a2-to-spend-money': ('खर्च करना', 'kharch karna'),
    'a2-to-show': ('दिखाना', 'dikhaana'),
    'a2-to-explain': ('समझाना', 'samjhaana'),
    'a2-to-follow': ('अनुसरण करना', 'anusaran karna'),
    'a2-to-keep': ('संभाल कर रखना', 'sambhaal kar rakhna'),
    'a2-to-allow': ('अनुमति देना', 'anumati dena'),
    'a2-to-become': ('बनना', 'banna'),
    'a2-to-continue': ('जारी रखना', 'jaari rakhna'),
    'a2-to-cut': ('काटना', 'kaatna'),
    'a2-to-break': ('तोड़ना', 'todna'),
    'a2-to-fly': ('उड़ना', 'udna'),
    'a2-to-draw': ('रेखाचित्र बनाना', 'rekhaachitra banaana'),
    'a2-to-carry': ('ले जाना', 'le jaana'),
    'a2-to-push': ('धकेलना', 'dhakelna'),
    'a2-to-pull': ('खींचना', 'kheenchna'),
    'a2-to-throw': ('फेंकना', 'phenkna'),
    'a2-to-catch': ('पकड़ना', 'pakadna'),
    'a2-to-build': ('बनाना', 'banaana'),
    'a2-to-grow': ('बढ़ना', 'badhna'),
    'a2-to-fall': ('गिरना', 'girna'),
    'a2-to-climb': ('चढ़ना', 'chadhna'),
    'a2-to-jump': ('कूदना', 'koodna'),
    'a2-to-laugh': ('हँसना', 'hansna'),
    'a2-to-cry': ('रोना', 'rona'),
    'a2-to-smile': ('मुस्कुराना', 'muskuraana'),
    'a2-to-shout': ('चिल्लाना', 'chillaana'),
    'a2-to-whisper': ('फुसफुसाना', 'phusphusaana'),
    'a2-to-hug': ('गले लगाना', 'gale lagaana'),
    'a2-to-kiss': ('चूमना', 'choomna'),
    'a2-to-touch': ('छूना', 'chhoona'),
    'a2-to-smell': ('सूँघना', 'soonghna'),
    'a2-to-taste': ('चखना', 'chakhna'),
    'a2-to-wash-oneself': ('स्वयं को धोना', 'swayan ko dhona'),
    'a2-to-hide': ('छिपना', 'chhipna'),
    'a2-interesting': ('दिलचस्प', 'dilchasp'),
    'a2-boring': ('उबाऊ', 'ubaau'),
    'a2-comfortable': ('आरामदायक', 'aaraamdaayak'),
    'a2-dangerous': ('ख़तरनाक', 'khatarnaak'),
    'a2-safe': ('सुरक्षित', 'surakshit'),
    'a2-noisy': ('शोरगुल वाला', 'shorgul waala'),
    'a2-busy': ('व्यस्त', 'vyast'),
    'a2-heavy': ('भारी', 'bhaari'),
    'a2-light-weight': ('हल्का', 'halka'),
    'a2-wide': ('चौड़ा', 'chauda'),
    'a2-narrow': ('संकरा', 'sankra'),
    'a2-soft': ('नरम', 'naram'),
    'a2-hard-firm': ('सख़्त', 'sakht'),
    'a2-wet': ('गीला', 'geela'),
    'a2-dry': ('सूखा', 'sookha'),
    'a2-rich': ('अमीर', 'ameer'),
    'a2-poor': ('ग़रीब', 'gareeb'),
    'a2-famous': ('मशहूर', 'mashhoor'),
    'a2-popular': ('लोकप्रिय', 'lokpriya'),
    'a2-modern': ('आधुनिक', 'aadhunik'),
    'a2-traditional': ('पारंपरिक', 'paaramparik'),
    'a2-ready': ('तैयार', 'taiyaar'),
    'a2-sure': ('निश्चित', 'nishchit'),
    'a2-wrong': ('ग़लत', 'galat'),
    'a2-correct': ('सही', 'sahi'),
    'a2-strange': ('अजीब', 'ajeeb'),
    'a2-same': ('एक जैसा', 'ek jaisa'),
    'a2-different': ('अलग', 'alag'),
    'a2-last-week': ('पिछले हफ़्ते', 'pichhle hafte'),
    'a2-next-week': ('अगले हफ़्ते', 'agle hafte'),
    'a2-this-month': ('इस महीने', 'is maheene'),
    'a2-last-year': ('पिछले साल', 'pichhle saal'),
    'a2-next-year': ('अगले साल', 'agle saal'),
    'a2-at-the-end': ('अंत में', 'ant mein'),
    'a2-at-the-beginning': ('शुरुआत में', 'shuruaat mein'),
    'a2-twice': ('दो बार', 'do baar'),
    'a2-once': ('एक बार', 'ek baar'),
    'a2-in-a-hurry': ('जल्दी में', 'jaldi mein'),
    'a2-for-a-long-time': ('लंबे समय तक', 'lambe samay tak'),
    'a2-recently': ('हाल ही में', 'haal hi mein'),
    'a2-already': ('पहले ही', 'pahle hi'),
    'a2-still': ('अभी भी', 'abhi bhi'),
    'a2-not-yet': ('अभी तक नहीं', 'abhi tak nahin'),
    'a2-until': ('तक', 'tak'),
    'a2-since': ('जब से', 'jab se'),
    'a2-during': ('के दौरान', 'ke dauraan'),
    'a2-ago': ('पहले', 'pahle'),
    'a2-at-least': ('कम से कम', 'kam se kam'),
    'a2-right-away': ('तुरंत', 'turant'),
    'a2-finally': ('आख़िरकार', 'aakhirkaar'),
    'a2-suddenly': ('अचानक', 'achaanak'),
    'a2-the-day-after-tomorrow': ('परसों', 'parson'),
    'a2-conversation': ('बातचीत', 'baatcheet'),
    'a2-question': ('सवाल', 'savaal'),
    'a2-answer-noun': ('जवाब', 'jawaab'),
    'a2-opinion': ('राय', 'raay'),
    'a2-to-describe': ('वर्णन करना', 'varnan karna'),
    'a2-to-promise': ('वादा करना', 'vaada karna'),
    'a2-to-suggest': ('सुझाव देना', 'sujhaav dena'),
    'a2-to-complain': ('शिकायत करना', 'shikaayat karna'),
    'a2-to-apologize': ('माफ़ी माँगना', 'maafi maangna'),
    'a2-to-thank': ('धन्यवाद देना', 'dhanyavaad dena'),
    'a2-joke': ('मज़ाक', 'mazaak'),
    'a2-story': ('कहानी', 'kahaani'),
    'a2-news': ('ख़बर', 'khabar'),
    'a2-to-argue': ('बहस करना', 'bahas karna'),
    'a2-to-discuss': ('चर्चा करना', 'charcha karna'),
    'a2-secret': ('राज़', 'raaz'),
    'a2-to-mean': ('मतलब होना', 'matlab hona'),
    'a2-to-pronounce': ('उच्चारण करना', 'uchcharan karna'),
    'a2-to-translate': ('अनुवाद करना', 'anuvaad karna'),
    'a2-word': ('शब्द', 'shabd'),
    'a2-sentence': ('वाक्य', 'vaakya'),
    'a2-language': ('भाषा', 'bhaasha'),
    'a2-to-spell': ('वर्तनी लिखना', 'vartani likhna'),
    'a2-to-lie': ('झूठ बोलना', 'jhooth bolna'),
    'a2-truth': ('सच', 'sach'),
    'a2-to-chat': ('गपशप करना', 'gapshap karna'),
    'a2-accent': ('लहजा', 'lahja'),
    'a2-fluent': ('धाराप्रवाह', 'dhaaraapravaah'),
    'a2-to-get-married': ('शादी करना', 'shaadi karna'),
    'a2-wedding': ('विवाह', 'vivaah'),
    'a2-couple': ('जोड़ा', 'joda'),
    'a2-childhood': ('बचपन', 'bachpan'),
    'a2-teenager': ('किशोर', 'kishor'),
    'a2-adult': ('वयस्क', 'vayask'),
    'a2-to-grow-up': ('बड़ा होना', 'bada hona'),
    'a2-anniversary': ('सालगिरह', 'saalgirah'),
    'a2-party': ('पार्टी', 'party'),
    'a2-guest': ('मेहमान', 'mehmaan'),
    'a2-to-celebrate': ('मनाना', 'manaana'),
    'a2-to-be-born': ('जन्म लेना', 'janm lena'),
    'a2-to-die': ('मरना', 'marna'),
    'a2-relatives': ('रिश्तेदार', 'rishtedaar'),
    'a2-twins': ('जुड़वाँ', 'judwaan'),
    'a2-only-child': ('इकलौती संतान', 'iklauti santaan'),
    'a2-to-take-care-of': ('ख्याल रखना', 'khyaal rakhna'),
    'a2-nephew': ('भतीजा', 'bhateeja'),
    'a2-niece': ('भतीजी', 'bhateeji'),
    'a2-grandchild': ('पोता', 'pota'),
    'a2-single': ('अविवाहित', 'avivaahit'),
    'a2-divorced': ('तलाकशुदा', 'talaakshuda'),
    'a2-christmas': ('क्रिसमस', 'christmas'),
    'a2-new-year': ('नया साल', 'naya saal'),
    'a2-cake': ('केक', 'cake'),
    'a2-candle': ('मोमबत्ती', 'mombatti'),
    'a2-lesson': ('पाठ', 'paath'),
    'a2-course': ('कोर्स', 'course'),
    'a2-to-practice': ('अभ्यास करना', 'abhyaas karna'),
    'a2-mistake': ('ग़लती', 'galti'),
    'a2-to-correct': ('सुधारना', 'sudhaarna'),
    'a2-grade-mark': ('ग्रेड', 'grade'),
    'a2-to-pass-an-exam': ('पास होना', 'pass hona'),
    'a2-to-fail-an-exam': ('फ़ेल होना', 'fail hona'),
    'a2-to-graduate': ('स्नातक होना', 'snaatak hona'),
    'a2-degree': ('डिग्री', 'degree'),
    'a2-subject': ('विषय', 'vishay'),
    'a2-math': ('गणित', 'ganit'),
    'a2-history': ('इतिहास', 'itihaas'),
    'a2-science': ('विज्ञान', 'vigyaan'),
    'a2-art': ('कला', 'kala'),
    'a2-dictionary': ('शब्दकोश', 'shabdakosh'),
    'a2-notebook': ('नोटबुक', 'notebook'),
    'a2-to-memorize': ('याद करना', 'yaad karna'),
    'a2-to-review': ('दोहराना', 'dohraana'),
    'a2-classroom': ('कक्षा-कक्ष', 'kaksha-kaksh'),
    'a2-semester': ('सेमेस्टर', 'semester'),
    'a2-scholarship': ('छात्रवृत्ति', 'chhaatravritti'),
    'a2-to-register': ('पंजीकरण करना', 'panjeekaran karna'),
    'a2-example': ('उदाहरण', 'udaaharan'),
    'a2-level': ('स्तर', 'star'),
    'a2-beginner': ('शुरुआती', 'shuruaati'),
    'a2-to-save-money': ('बचत करना', 'bachat karna'),
    'a2-bank-account': ('बैंक खाता', 'bank khaata'),
    'a2-to-withdraw': ('निकालना', 'nikaalna'),
    'a2-to-deposit': ('जमा करना', 'jama karna'),
    'a2-atm': ('एटीएम', 'ATM'),
    'a2-loan': ('लोन', 'loan'),
    'a2-debt': ('कर्ज़', 'karz'),
    'a2-to-borrow': ('उधार लेना', 'udhaar lena'),
    'a2-to-lend': ('उधार देना', 'udhaar dena'),
    'a2-to-owe': ('कर्ज़दार होना', 'karzdaar hona'),
    'a2-tax': ('कर', 'kar'),
    'a2-bill-utility': ('बिल', 'bill'),
    'a2-budget': ('बजट', 'budget'),
    'a2-to-afford': ('खर्च उठा सकना', 'kharch utha sakna'),
    'a2-interest-bank': ('ब्याज', 'byaaj'),
    'a2-coin': ('सिक्का', 'sikka'),
    'a2-to-exchange-money': ('पैसे बदलना', 'paise badalna'),
    'a2-exchange-rate': ('विनिमय दर', 'vinimay dar'),
    'a2-credit-card': ('क्रेडिट कार्ड', 'credit card'),
    'a2-to-cost': ('कीमत होना', 'keemat hona'),
    'a2-salary-raise': ('वेतन वृद्धि', 'vetan vriddhi'),
    'a2-expensive-habit': ('महँगी आदत', 'mahangi aadat'),
    'a2-invoice': ('चालान', 'chaalaan'),
    'a2-payment': ('भुगतान', 'bhugtaan'),
    'a2-to-miss-someone': ('याद आना', 'yaad aana'),
    'a2-to-worry': ('चिंता करना', 'chinta karna'),
    'a2-to-enjoy': ('आनंद लेना', 'aanand lena'),
    'a2-to-hate': ('नफ़रत करना', 'nafrat karna'),
    'a2-to-be-afraid-of': ('डरना', 'darna'),
    'a2-ashamed': ('शर्मिंदा', 'sharminda'),
    'a2-jealous': ('ईर्ष्यालु', 'eershyaalu'),
    'a2-embarrassed': ('झेंपा हुआ', 'jhempa hua'),
    'a2-disappointed': ('निराश', 'niraash'),
    'a2-grateful': ('आभारी', 'aabhaari'),
    'a2-relieved': ('राहत महसूस करने वाला', 'raahat mehsoos karne waala'),
    'a2-confused': ('उलझन में', 'uljhan mein'),
    'a2-curious': ('जिज्ञासु', 'jigyaasu'),
    'a2-hopeful': ('आशावान', 'aashaavaan'),
    'a2-frustrated': ('हताश', 'hataash'),
    'a2-stressed': ('तनाव में', 'tanaav mein'),
    'a2-in-a-good-mood': ('अच्छे मूड में', 'achhe mood mein'),
    'a2-in-a-bad-mood': ('बुरे मूड में', 'bure mood mein'),
    'a2-to-cheer-up': ('खुश होना', 'khush hona'),
    'a2-to-calm-down': ('शांत होना', 'shaant hona'),
    'a2-to-get-angry': ('गुस्सा होना', 'gussa hona'),
    'a2-to-fall-in-love': ('प्यार हो जाना', 'pyaar ho jaana'),
    'a2-mood': ('मूड', 'mood'),
    'a2-satisfied': ('संतुष्ट', 'santusht'),
    'a2-forest': ('जंगल', 'jangal'),
    'a2-lake': ('झील', 'jheel'),
    'a2-island': ('द्वीप', 'dveep'),
    'a2-desert': ('रेगिस्तान', 'registaan'),
    'a2-field': ('खेत', 'khet'),
    'a2-farm': ('फ़ार्म', 'farm'),
    'a2-animal': ('जानवर', 'janwar'),
    'a2-insect': ('कीड़ा', 'keeda'),
    'a2-mosquito': ('मच्छर', 'machchhar'),
    'a2-bee': ('मधुमक्खी', 'madhumakkhi'),
    'a2-butterfly': ('तितली', 'titli'),
    'a2-snake': ('साँप', 'saanp'),
    'a2-lion': ('शेर', 'sher'),
    'a2-elephant': ('हाथी', 'haathi'),
    'a2-monkey': ('बंदर', 'bandar'),
    'a2-rabbit': ('खरगोश', 'khargosh'),
    'a2-pig': ('सुअर', 'suar'),
    'a2-sheep': ('भेड़', 'bhed'),
    'a2-plant': ('पौधा', 'paudha'),
    'a2-grass': ('घास', 'ghaas'),
    'a2-leaf': ('पत्ता', 'patta'),
    'a2-rock': ('चट्टान', 'chattaan'),
    'a2-sand': ('रेत', 'ret'),
    'a2-ocean': ('महासागर', 'mahaasaagar'),
    'a2-wave': ('लहर', 'lahar'),
    'a2-thunder': ('गरज', 'garaj'),
    'a2-fog': ('कोहरा', 'kohra'),
    'a2-temperature': ('तापमान', 'taapmaan'),
    'a2-laptop': ('लैपटॉप', 'laptop'),
    'a2-keyboard': ('कीबोर्ड', 'keyboard'),
    'a2-printer': ('प्रिंटर', 'printer'),
    'a2-file': ('फ़ाइल', 'file'),
    'a2-folder': ('फ़ोल्डर', 'folder'),
    'a2-to-print': ('प्रिंट करना', 'print karna'),
    'a2-to-click': ('क्लिक करना', 'click karna'),
    'a2-to-type': ('टाइप करना', 'type karna'),
    'a2-to-search-online': ('इंटरनेट पर खोजना', 'internet par khojna'),
    'a2-social-media': ('सोशल मीडिया', 'social media'),
    'a2-to-post': ('पोस्ट करना', 'post karna'),
    'a2-to-share': ('साझा करना', 'saajha karna'),
    'a2-video': ('वीडियो', 'video'),
    'a2-photo': ('फ़ोटो', 'photo'),
    'a2-selfie': ('सेल्फ़ी', 'selfie'),
    'a2-headphones': ('हेडफ़ोन', 'headphones'),
    'a2-speaker': ('स्पीकर', 'speaker'),
    'a2-battery': ('बैटरी', 'battery'),
    'a2-to-turn-on': ('चालू करना', 'chaalu karna'),
    'a2-to-turn-off': ('स्विच ऑफ़ करना', 'switch off karna'),
    'a2-volume': ('वॉल्यूम', 'volume'),
    'a2-channel': ('चैनल', 'channel'),
    'a2-podcast': ('पॉडकास्ट', 'podcast'),
    'a2-screenshot': ('स्क्रीनशॉट', 'screenshot'),
    'a2-update': ('अपडेट', 'update'),
    'a2-notification': ('सूचना', 'soochana'),
    'a2-to-log-in': ('लॉग इन करना', 'log in karna'),
    'a2-subtitles': ('उपशीर्षक', 'upasheershak'),
    'a2-what-do-you-think': ('आपको क्या लगता है?', 'aapko kya lagta hai?'),
    'a2-it-depends': ('यह निर्भर करता है', 'yah nirbhar karta hai'),
    'a2-im-not-sure': ('मुझे यक़ीन नहीं है', 'mujhe yakeen nahin hai'),
    'a2-let-me-think': ('मुझे सोचने दो', 'mujhe sochne do'),
    'a2-what-a-pity': ('कितने अफ़सोस की बात है', 'kitne afsos ki baat hai'),
    'a2-never-mind': ('छोड़ो', 'chhodo'),
    'a2-hurry-up': ('जल्दी करो', 'jaldi karo'),
    'a2-watch-out': ('ध्यान से!', 'dhyaan se!'),
    'a2-thats-a-good-idea': ('यह अच्छा विचार है', 'yah achha vichaar hai'),
    'a2-are-you-kidding': ('क्या तुम मज़ाक कर रहे हो?', 'kya tum mazaak kar rahe ho?'),
    'a2-its-up-to-you': ('यह तुम्हारी मर्ज़ी है', 'yah tumhaari marzi hai'),
    'a2-im-on-my-way': ('मैं आ रहा हूँ', 'main aa raha hoon'),
    'a2-same-here': ('मेरा भी यही हाल है', 'mera bhi yahi haal hai'),
    'a2-me-neither': ('मैं भी नहीं', 'main bhi nahin'),
    'a2-by-the-way': ('वैसे', 'vaise'),
    'a2-in-my-opinion': ('मेरी राय में', 'meri raay mein'),
    'a2-to-be-honest': ('सच कहूँ तो', 'sach kahoon to'),
    'a2-actually': ('असल में', 'asal mein'),
    'a2-anyway': ('खैर', 'khair'),
    'a2-for-example': ('उदाहरण के लिए', 'udaaharan ke liye'),
    'a2-sorry-im-late': ('देर से आने के लिए माफ़ी', 'der se aane ke liye maafi'),
    'a2-no-way': ('बिल्कुल नहीं!', 'bilkul nahin!'),
    'a2-that-makes-sense': ('यह बात समझ में आती है', 'yah baat samajh mein aati hai'),
    'a2-good-point': ('अच्छी बात है', 'achhi baat hai'),
    'a2-banana': ('केला', 'kela'),
    'a2-orange-fruit': ('संतरा', 'santra'),
    'a2-grapes': ('अंगूर', 'angoor'),
    'a2-strawberry': ('स्ट्रॉबेरी', 'strawberry'),
    'a2-lemon': ('नींबू', 'neemboo'),
    'a2-watermelon': ('तरबूज़', 'tarbooz'),
    'a2-peach': ('आड़ू', 'aadoo'),
    'a2-pear': ('नाशपाती', 'naashpaati'),
    'a2-carrot': ('गाजर', 'gaajar'),
    'a2-lettuce': ('सलाद पत्ता', 'salaad patta'),
    'a2-cucumber': ('खीरा', 'kheera'),
    'a2-bell-pepper': ('शिमला मिर्च', 'shimla mirch'),
    'a2-mushroom': ('मशरूम', 'mushroom'),
    'a2-corn': ('मक्का', 'makka'),
    'a2-beans': ('फलियाँ', 'faliyaan'),
    'a2-spinach': ('पालक', 'paalak'),
    'a2-cabbage': ('पत्ता गोभी', 'patta gobhi'),
    'a2-pumpkin': ('कद्दू', 'kaddu'),
    'a2-nuts': ('मेवे', 'meve'),
    'a2-coconut': ('नारियल', 'naariyal'),
    'a2-mango': ('आम', 'aam'),
    'a2-pineapple': ('अनानास', 'anaanaas'),
    'a2-cherry': ('चेरी', 'cherry'),
    'a2-avocado': ('एवोकाडो', 'avocado'),
    'a2-ripe': ('पका हुआ', 'paka hua'),
    'a2-fresh': ('ताज़ा', 'taaza'),
    'a2-kilogram': ('किलोग्राम', 'kilogram'),
    'a2-gram': ('ग्राम', 'gram'),
    'a2-liter': ('लीटर', 'liter'),
    'a2-meter': ('मीटर', 'meter'),
    'a2-kilometer': ('किलोमीटर', 'kilometer'),
    'a2-centimeter': ('सेंटीमीटर', 'centimeter'),
    'a2-piece': ('टुकड़ा', 'tukda'),
    'a2-slice': ('स्लाइस', 'slice'),
    'a2-dozen': ('दर्जन', 'darjan'),
    'a2-pair': ('जोड़ी', 'jodi'),
    'a2-percent': ('प्रतिशत', 'pratishat'),
    'a2-degree-temperature': ('डिग्री (तापमान)', 'degree'),
    'a2-a-bit': ('थोड़ा सा', 'thoda sa'),
    'a2-a-lot': ('बहुत सारा', 'bahut saara'),
    'a2-several': ('कई', 'kai'),
    'a2-double': ('दोगुना', 'doguna'),
    'a2-weight': ('वज़न', 'vazan'),
    'a2-height': ('ऊँचाई', 'oonchai'),
    'a2-length': ('लंबाई', 'lambai'),
    'a2-distance': ('दूरी', 'doori'),
    'a2-speed': ('गति', 'gati'),
    'a2-total': ('कुल', 'kul'),
    'a2-almost': ('लगभग', 'lagbhag'),
    'a2-only': ('केवल', 'keval'),
    'a2-engineer': ('इंजीनियर', 'engineer'),
    'a2-lawyer': ('वकील', 'vakeel'),
    'a2-chef': ('रसोइया', 'rasoiya'),
    'a2-driver': ('चालक', 'chaalak'),
    'a2-farmer': ('किसान', 'kisaan'),
    'a2-artist': ('कलाकार', 'kalaakaar'),
    'a2-musician': ('संगीतकार', 'sangeetkaar'),
    'a2-actor': ('अभिनेता', 'abhineta'),
    'a2-writer': ('लेखक', 'lekhak'),
    'a2-journalist': ('पत्रकार', 'patrakaar'),
    'a2-police-officer': ('पुलिस अधिकारी', 'police adhikaari'),
    'a2-firefighter': ('अग्निशामक', 'agnishaamak'),
    'a2-scientist': ('वैज्ञानिक', 'vaigyaanik'),
    'a2-programmer': ('प्रोग्रामर', 'programmer'),
    'a2-designer': ('डिज़ाइनर', 'designer'),
    'a2-manager': ('प्रबंधक', 'prabandhak'),
    'a2-salesperson': ('विक्रेता', 'vikreta'),
    'a2-mechanic': ('मैकेनिक', 'mechanic'),
    'a2-electrician': ('इलेक्ट्रीशियन', 'electrician'),
    'a2-plumber': ('प्लंबर', 'plumber'),
    'a2-pilot': ('पायलट', 'pilot'),
    'a2-accountant': ('लेखाकार', 'lekhaakaar'),
    'a2-architect': ('वास्तुकार', 'vaastukaar'),
    'a2-hairdresser': ('नाई', 'naai'),
    'a2-soldier': ('सैनिक', 'sainik'),
    'a2-baker': ('बेकर', 'baker'),
    'a2-basketball': ('बास्केटबॉल', 'basketball'),
    'a2-tennis': ('टेनिस', 'tennis'),
    'a2-baseball': ('बेसबॉल', 'baseball'),
    'a2-volleyball': ('वॉलीबॉल', 'volleyball'),
    'a2-running': ('रनिंग', 'running'),
    'a2-cycling': ('साइकिल चलाना', 'saikil chalaana'),
    'a2-skiing': ('स्कीइंग', 'skiing'),
    'a2-surfing': ('सर्फिंग', 'surfing'),
    'a2-yoga': ('योग', 'yoga'),
    'a2-chess': ('शतरंज', 'shatranj'),
    'a2-cards-game': ('ताश', 'taash'),
    'a2-board-game': ('बोर्ड गेम', 'board game'),
    'a2-video-game': ('वीडियो गेम', 'video game'),
    'a2-puzzle': ('पहेली', 'paheli'),
    'a2-to-go-camping': ('कैंपिंग करना', 'camping karna'),
    'a2-picnic': ('पिकनिक', 'picnic'),
    'a2-fishing': ('मछली पकड़ना', 'machhli pakadna'),
    'a2-race': ('दौड़', 'daud'),
    'a2-competition': ('प्रतियोगिता', 'pratiyogita'),
    'a2-referee': ('रेफ़री', 'referee'),
    'a2-coach': ('कोच', 'coach'),
    'a2-medal': ('पदक', 'padak'),
    'a2-score': ('स्कोर', 'score'),
    'a2-fan-supporter': ('प्रशंसक', 'prashansak'),
    'a2-to-train': ('ट्रेनिंग करना', 'training karna'),
}
