# -*- coding: utf-8 -*-
# Vietnamese skill drills: grammar (B2), idioms (C1), nuance (C2)
LANG = 'vi'

GRAMMAR = [
    {"id": "g-vi1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Hôm qua tôi ___ đi thăm bà ngoại ở quê.", "correct": "đã",
     "options": ["đã", "đang", "sẽ", "vẫn"],
     "note": "Đã marks a completed past action; the time word 'hôm qua' (yesterday) confirms past tense."},
    {"id": "g-vi2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Lúc tôi gọi điện, anh ấy ___ ăn cơm.", "correct": "đang",
     "options": ["đang", "đã", "sẽ", "mới"],
     "note": "Đang marks an action in progress at that past moment — Vietnamese uses the same marker for present and past progressive, disambiguated by context."},
    {"id": "g-vi3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "___ trời mưa thì chúng ta sẽ ở nhà.", "correct": "Nếu",
     "options": ["Nếu", "Tuy", "Vì", "Nhưng"],
     "note": "Nếu…thì… is the standard conditional frame: “if it rains, then we'll stay home.”"},
    {"id": "g-vi4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Nếu tôi có nhiều tiền hơn, tôi ___ mua một ngôi nhà.", "correct": "sẽ",
     "options": ["sẽ", "đã", "đang", "mới"],
     "note": "The result clause of a nếu-conditional takes sẽ (will) for a hypothetical future outcome."},
    {"id": "g-vi5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Tôi có một ___ sách rất hay trên bàn.", "correct": "quyển",
     "options": ["quyển", "con", "cái", "chiếc"],
     "note": "Quyển (or cuốn) is the classifier for books; classifiers must match the noun's shape/category, not be chosen freely."},
    {"id": "g-vi6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Chị ấy mới mua một ___ xe đạp màu đỏ.", "correct": "chiếc",
     "options": ["chiếc", "con", "quyển", "cái"],
     "note": "Chiếc is the classifier for vehicles like xe đạp (bicycle); con is reserved for animals."},
]

IDIOMS = [
    {"id": "i-vi1", "tier": "C1", "topic": "idiom-character",
     "phrase": "Nước đến chân mới nhảy", "correct": "To wait until the last minute to act (a chronic procrastinator)",
     "options": ["To wait until the last minute to act (a chronic procrastinator)", "To be extremely cautious in everything", "To help others without being asked", "To always finish tasks early"],
     "note": "Literally “the water reaches your feet before you jump” — describes someone who only acts once forced by an emergency."},
    {"id": "i-vi2", "tier": "C1", "topic": "idiom-character",
     "phrase": "Đứng núi này trông núi nọ", "correct": "Never satisfied, always wanting what one doesn't have",
     "options": ["Never satisfied, always wanting what one doesn't have", "Being loyal to one place or group", "Being extremely humble", "Working harder than everyone else"],
     "note": "Literally “standing on this mountain, gazing at that one” — the Vietnamese “grass is always greener,” describing a restless, never-content personality."},
    {"id": "i-vi3", "tier": "C1", "topic": "idiom-character",
     "phrase": "Ăn cây nào rào cây nấy", "correct": "To stay loyal to the group or place that supports you",
     "options": ["To stay loyal to the group or place that supports you", "To take credit for others' work", "To never trust anyone", "To switch jobs constantly"],
     "note": "Literally “eat from a tree, build the fence around that same tree” — loyalty to whoever feeds or supports you."},
    {"id": "i-vi4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "Của rẻ là của ôi", "correct": "You get what you pay for; cheap goods are poor quality",
     "options": ["You get what you pay for; cheap goods are poor quality", "Money can't buy happiness", "The best things in life are free", "Save your money for a rainy day"],
     "note": "Literally “a cheap thing is a spoiled thing” — said with a rueful shrug when a bargain turns out shoddy."},
    {"id": "i-vi5", "tier": "C1", "topic": "idiom-media",
     "phrase": "Tam sao thất bản", "correct": "Information gets distorted each time it's retold or copied",
     "options": ["Information gets distorted each time it's retold or copied", "The truth always comes out eventually", "A story with three different endings", "News travels faster than the truth"],
     "note": "Literally “three copies, and the original is lost” — used for rumors, gossip, or news that mutates with each retelling."},
    {"id": "i-vi6", "tier": "C1", "topic": "idiom-media",
     "phrase": "Nói có sách, mách có chứng", "correct": "Back up what you say with solid evidence",
     "options": ["Back up what you say with solid evidence", "Read widely before forming an opinion", "Books are more trustworthy than people", "Keep written records of everything"],
     "note": "Literally “speak with a book, report with proof” — the standard rebuke to unsubstantiated claims or hearsay reporting."},
]

NUANCE = [
    {"id": "n-vi1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Addressing an elderly stranger politely on the street", "correct": "bác",
     "options": ["bác", "mày", "tao", "ông ấy"],
     "note": "Bác (for someone roughly your parents' age or an elder) is the polite kinship pronoun; mày/tao are crude, intimate-only pronouns and ông ấy is third-person, not a direct address."},
    {"id": "n-vi2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "A young employee addressing their boss in a meeting", "correct": "anh/chị",
     "options": ["anh/chị", "mày", "ông", "bạn"],
     "note": "Anh/chị (chosen by relative age) is standard workplace-polite; mày is rude, bạn is too casual for a boss, and ông can sound distant or old-fashioned."},
    {"id": "n-vi3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Saying you 'borrowed' money that you fully intend to repay soon", "correct": "vay",
     "options": ["vay", "mượn", "xin", "lấy"],
     "note": "Vay specifically means to borrow money with expected repayment; mượn is for objects, xin means to ask for or beg, and lấy just means to take."},
    {"id": "n-vi4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Describing soup that is exactly the right temperature to drink — not hot, not cold", "correct": "ấm",
     "options": ["ấm", "nóng", "lạnh", "mát"],
     "note": "Ấm (warm) precisely denotes a comfortable middle temperature; nóng is hot, lạnh is cold, and mát is cool — swapping these changes the meaning."},
    {"id": "n-vi5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend casually that something is awesome", "correct": "đỉnh",
     "options": ["đỉnh", "xuất sắc", "tuyệt vời", "hoàn hảo"],
     "note": "Đỉnh (“the peak”) is current casual slang for “awesome”; xuất sắc and hoàn hảo read as formal or written praise."},
    {"id": "n-vi6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Writing a formal request to a government office asking them to process your paperwork", "correct": "kính đề nghị",
     "options": ["kính đề nghị", "làm ơn", "nhờ cái", "làm giùm"],
     "note": "Kính đề nghị (“respectfully request”) is bureaucratic register; làm ơn/nhờ cái/làm giùm are spoken, everyday-request phrasing."},
    {"id": "n-vi7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Sarcastically reacting to a friend who shows up late again", "correct": "Giỏi thật đấy",
     "options": ["Giỏi thật đấy", "Cảm ơn bạn đã đến", "Không sao, mình hiểu mà", "Bạn đến sớm quá"],
     "note": "Giỏi thật đấy (“well done indeed”) said flatly to a chronically late friend is sarcasm, not real praise."},
    {"id": "n-vi8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Gently softening a disagreement with your manager's idea instead of bluntly rejecting it", "correct": "Em nghĩ có lẽ nên xem lại chỗ này ạ",
     "options": ["Em nghĩ có lẽ nên xem lại chỗ này ạ", "Cái này sai rồi", "Em không đồng ý", "Ý này dở quá"],
     "note": "Em nghĩ có lẽ… ạ stacks a hedge (có lẽ) with the polite sentence-final particle ạ to soften disagreement; the alternatives are blunt or dismissive."},
]
