# -*- coding: utf-8 -*-
LANG = 'ind'
WORDS = {
    'a1-hello': ('Halo', None),
    'a1-goodbye': ('Selamat tinggal', None),
    'a1-please': ('Tolong', None),
    'a1-thank-you': ('Terima kasih', None),
    'a1-excuse-me': ('Permisi', None),
    'a1-sorry': ('Maaf', None),
    'a1-yes': ('Ya', None),
    'a1-no': ('Tidak', None),
    'a1-my-name-is-alex': ('Nama saya Alex', None),
    'a1-whats-your-name': ('Siapa nama Anda?', None),
    'a1-nice-to-meet-you': ('Senang bertemu dengan Anda', None),
    'a1-how-are-you': ('Apa kabar?', None),
    'a1-mother': ('Ibu', None),
    'a1-father': ('Ayah', None),
    'a1-sister': ('Saudari', None),
    'a1-brother': ('Saudara', None),
    'a1-friend': ('Teman', None),
    'a1-child': ('Anak', None),
    'a1-today': ('Hari ini', None),
    'a1-tomorrow': ('Besok', None),
    'a1-yesterday': ('Kemarin', None),
    'a1-now': ('Sekarang', None),
    'a1-morning': ('Pagi', None),
    'a1-night': ('Malam', None),
    'a1-house': ('Rumah', None),
    'a1-where-is-it': ('Di mana itu?', None),
    'a1-left': ('Kiri', None),
    'a1-right': ('Kanan', None),
    'a1-store': ('Toko', None),
    'a1-bathroom': ('Kamar mandi', None),
    'a1-water': ('Air', None),
    'a1-bread': ('Roti', None),
    'a1-coffee': ('Kopi', None),
    'a1-tea': ('Teh', None),
    'a1-delicious': ('Enak', None),
    'a1-spicy': ('Pedas', None),
    'a1-good-morning': ('Selamat pagi', None),
    'a1-good-evening': ('Selamat malam', None),
    'a1-good-night': ('Selamat tidur', None),
    'a1-youre-welcome': ('Sama-sama', None),
    'a1-see-you-soon': ('Sampai jumpa lagi', None),
    'a1-see-you-tomorrow': ('Sampai besok', None),
    'a1-welcome': ('Selamat datang', None),
    'a1-cheers': ('Bersulang!', None),
    'a1-congratulations': ('Selamat', None),
    'a1-happy-birthday': ('Selamat ulang tahun', None),
    'a1-good-luck': ('Semoga berhasil', None),
    'a1-have-a-nice-day': ('Semoga harimu menyenangkan', None),
    'a1-take-care': ('Jaga diri baik-baik', None),
    'a1-bless-you': ('Semoga sehat', None),
    'a1-enjoy-your-meal': ('Selamat makan', None),
    'a1-nice-to-see-you': ('Senang melihatmu', None),
    'a1-long-time-no-see': ('Lama tidak berjumpa', None),
    'a1-goodbye-for-now': ('Sampai nanti', None),
    'a1-i': ('Saya', None),
    'a1-you': ('Anda', None),
    'a1-he': ('Dia (laki-laki)', None),
    'a1-she': ('Dia (perempuan)', None),
    'a1-we': ('Kami', None),
    'a1-they': ('Mereka', None),
    'a1-man': ('Pria', None),
    'a1-woman': ('Wanita', None),
    'a1-boy': ('Anak laki-laki', None),
    'a1-girl': ('Anak perempuan', None),
    'a1-person': ('Orang', None),
    'a1-people': ('Orang-orang', None),
    'a1-name': ('Nama', None),
    'a1-mister': ('Tuan', None),
    'a1-madam': ('Nyonya', None),
    'a1-im-fine': ('Saya baik-baik saja', None),
    'a1-and-you': ('Kalau Anda?', None),
    'a1-where-are-you-from': ('Anda berasal dari mana?', None),
    'a1-im-from-the-united-states': ('Saya berasal dari Amerika Serikat', None),
    'a1-friend-female': ('Teman perempuan', None),
    'a1-family': ('Keluarga', None),
    'a1-parents': ('Orang tua', None),
    'a1-son': ('Putra', None),
    'a1-daughter': ('Putri', None),
    'a1-husband': ('Suami', None),
    'a1-wife': ('Istri', None),
    'a1-grandmother': ('Nenek', None),
    'a1-grandfather': ('Kakek', None),
    'a1-baby': ('Bayi', None),
    'a1-uncle': ('Paman', None),
    'a1-aunt': ('Bibi', None),
    'a1-cousin': ('Sepupu', None),
    'a1-boyfriend': ('Pacar (laki-laki)', None),
    'a1-girlfriend': ('Pacar (perempuan)', None),
    'a1-neighbor': ('Tetangga', None),
    'a1-children': ('Anak-anak', None),
    'a1-older-brother': ('Kakak laki-laki', None),
    'a1-younger-sister': ('Adik perempuan', None),
    'a1-pet': ('Hewan peliharaan', None),
    'a1-married': ('Menikah', None),
    'a1-one': ('Satu', None),
    'a1-two': ('Dua', None),
    'a1-three': ('Tiga', None),
    'a1-four': ('Empat', None),
    'a1-five': ('Lima', None),
    'a1-six': ('Enam', None),
    'a1-seven': ('Tujuh', None),
    'a1-eight': ('Delapan', None),
    'a1-nine': ('Sembilan', None),
    'a1-ten': ('Sepuluh', None),
    'a1-eleven': ('Sebelas', None),
    'a1-twelve': ('Dua belas', None),
    'a1-thirteen': ('Tiga belas', None),
    'a1-fourteen': ('Empat belas', None),
    'a1-fifteen': ('Lima belas', None),
    'a1-sixteen': ('Enam belas', None),
    'a1-seventeen': ('Tujuh belas', None),
    'a1-eighteen': ('Delapan belas', None),
    'a1-nineteen': ('Sembilan belas', None),
    'a1-twenty': ('Dua puluh', None),
    'a1-zero': ('Nol', None),
    'a1-thirty': ('Tiga puluh', None),
    'a1-forty': ('Empat puluh', None),
    'a1-fifty': ('Lima puluh', None),
    'a1-sixty': ('Enam puluh', None),
    'a1-seventy': ('Tujuh puluh', None),
    'a1-eighty': ('Delapan puluh', None),
    'a1-ninety': ('Sembilan puluh', None),
    'a1-one-hundred': ('Seratus', None),
    'a1-one-thousand': ('Seribu', None),
    'a1-one-million': ('Satu juta', None),
    'a1-first': ('Pertama', None),
    'a1-second': ('Kedua', None),
    'a1-third': ('Ketiga', None),
    'a1-half': ('Setengah', None),
    'a1-many': ('Banyak', None),
    'a1-few': ('Sedikit', None),
    'a1-all': ('Semua', None),
    'a1-some': ('Beberapa', None),
    'a1-nothing': ('Tidak ada apa-apa', None),
    'a1-number': ('Angka', None),
    'a1-more': ('Lebih', None),
    'a1-less': ('Kurang', None),
    'a1-enough': ('Cukup', None),
    'a1-red': ('Merah', None),
    'a1-blue': ('Biru', None),
    'a1-green': ('Hijau', None),
    'a1-yellow': ('Kuning', None),
    'a1-black': ('Hitam', None),
    'a1-white': ('Putih', None),
    'a1-orange-color': ('Oranye', None),
    'a1-pink': ('Merah muda', None),
    'a1-purple': ('Ungu', None),
    'a1-brown': ('Cokelat', None),
    'a1-gray': ('Abu-abu', None),
    'a1-color': ('Warna', None),
    'a1-light-color': ('Terang', None),
    'a1-dark': ('Gelap', None),
    'a1-circle': ('Lingkaran', None),
    'a1-square': ('Persegi', None),
    'a1-triangle': ('Segitiga', None),
    'a1-line': ('Garis', None),
    'a1-shape': ('Bentuk', None),
    'a1-big': ('Besar', None),
    'a1-small': ('Kecil', None),
    'a1-long': ('Panjang', None),
    'a1-short-length': ('Pendek', None),
    'a1-round': ('Bulat', None),
    'a1-afternoon': ('Siang', None),
    'a1-evening': ('Sore', None),
    'a1-day': ('Hari', None),
    'a1-week': ('Pekan', None),
    'a1-month': ('Bulan', None),
    'a1-year': ('Tahun', None),
    'a1-hour': ('Jam', None),
    'a1-minute': ('Menit', None),
    'a1-later': ('Nanti', None),
    'a1-early': ('Awal', None),
    'a1-late': ('Terlambat', None),
    'a1-always': ('Selalu', None),
    'a1-never': ('Tidak pernah', None),
    'a1-sometimes': ('Kadang-kadang', None),
    'a1-often': ('Sering', None),
    'a1-soon': ('Segera', None),
    'a1-again': ('Lagi', None),
    'a1-its-late': ('Sudah larut', None),
    'a1-tonight': ('Malam ini', None),
    'a1-before': ('Sebelum', None),
    'a1-after': ('Setelah', None),
    'a1-noon': ('Tengah hari', None),
    'a1-midnight': ('Tengah malam', None),
    'a1-monday': ('Senin', None),
    'a1-tuesday': ('Selasa', None),
    'a1-wednesday': ('Rabu', None),
    'a1-thursday': ('Kamis', None),
    'a1-friday': ('Jumat', None),
    'a1-saturday': ('Sabtu', None),
    'a1-sunday': ('Minggu', None),
    'a1-weekend': ('Akhir pekan', None),
    'a1-january': ('Januari', None),
    'a1-february': ('Februari', None),
    'a1-march': ('Maret', None),
    'a1-april': ('April', None),
    'a1-may': ('Mei', None),
    'a1-june': ('Juni', None),
    'a1-july': ('Juli', None),
    'a1-august': ('Agustus', None),
    'a1-september': ('September', None),
    'a1-october': ('Oktober', None),
    'a1-november': ('November', None),
    'a1-december': ('Desember', None),
    'a1-spring': ('Musim semi', None),
    'a1-summer': ('Musim panas', None),
    'a1-autumn': ('Musim gugur', None),
    'a1-winter': ('Musim dingin', None),
    'a1-birthday': ('Ulang tahun', None),
    'a1-holiday': ('Hari libur', None),
    'a1-room': ('Kamar', None),
    'a1-kitchen': ('Dapur', None),
    'a1-bedroom': ('Kamar tidur', None),
    'a1-door': ('Pintu', None),
    'a1-window': ('Jendela', None),
    'a1-table': ('Meja', None),
    'a1-chair': ('Kursi', None),
    'a1-bed': ('Tempat tidur', None),
    'a1-street': ('Jalan', None),
    'a1-city': ('Kota', None),
    'a1-country': ('Negara', None),
    'a1-school': ('Sekolah', None),
    'a1-hospital': ('Rumah sakit', None),
    'a1-bank': ('Bank', None),
    'a1-restaurant': ('Restoran', None),
    'a1-hotel': ('Hotel', None),
    'a1-market': ('Pasar', None),
    'a1-park': ('Taman', None),
    'a1-church': ('Gereja', None),
    'a1-office': ('Kantor', None),
    'a1-here': ('Di sini', None),
    'a1-there': ('Di sana', None),
    'a1-straight-ahead': ('Lurus ke depan', None),
    'a1-near': ('Dekat', None),
    'a1-far': ('Jauh', None),
    'a1-floor-level': ('Lantai', None),
    'a1-garden': ('Kebun', None),
    'a1-wall': ('Dinding', None),
    'a1-milk': ('Susu', None),
    'a1-rice': ('Nasi', None),
    'a1-meat': ('Daging', None),
    'a1-fish-food': ('Ikan', None),
    'a1-chicken': ('Ayam', None),
    'a1-egg': ('Telur', None),
    'a1-fruit': ('Buah', None),
    'a1-vegetables': ('Sayuran', None),
    'a1-apple': ('Apel', None),
    'a1-sugar': ('Gula', None),
    'a1-salt': ('Garam', None),
    'a1-beer': ('Bir', None),
    'a1-wine': ('Wine', None),
    'a1-juice': ('Jus', None),
    'a1-breakfast': ('Sarapan', None),
    'a1-lunch': ('Makan siang', None),
    'a1-dinner': ('Makan malam', None),
    'a1-im-hungry': ('Saya lapar', None),
    'a1-im-thirsty': ('Saya haus', None),
    'a1-cheese': ('Keju', None),
    'a1-soup': ('Sup', None),
    'a1-sweet': ('Manis', None),
    'a1-food': ('Makanan', None),
    'a1-drink-noun': ('Minuman', None),
    'a1-head': ('Kepala', None),
    'a1-hand': ('Tangan', None),
    'a1-eye': ('Mata', None),
    'a1-foot': ('Kaki', None),
    'a1-mouth': ('Mulut', None),
    'a1-nose': ('Hidung', None),
    'a1-ear': ('Telinga', None),
    'a1-arm': ('Lengan', None),
    'a1-leg': ('Tungkai', None),
    'a1-heart': ('Jantung', None),
    'a1-hair': ('Rambut', None),
    'a1-face': ('Wajah', None),
    'a1-back-body': ('Punggung', None),
    'a1-stomach': ('Perut', None),
    'a1-tooth': ('Gigi', None),
    'a1-finger': ('Jari', None),
    'a1-body': ('Tubuh', None),
    'a1-blood': ('Darah', None),
    'a1-neck': ('Leher', None),
    'a1-shoulder': ('Bahu', None),
    'a1-knee': ('Lutut', None),
    'a1-skin': ('Kulit', None),
    'a1-shirt': ('Kemeja', None),
    'a1-pants': ('Celana', None),
    'a1-shoes': ('Sepatu', None),
    'a1-dress': ('Gaun', None),
    'a1-hat': ('Topi', None),
    'a1-coat': ('Mantel', None),
    'a1-jacket': ('Jaket', None),
    'a1-socks': ('Kaus kaki', None),
    'a1-skirt': ('Rok', None),
    'a1-bag': ('Tas', None),
    'a1-glasses': ('Kacamata', None),
    'a1-watch-wrist': ('Jam tangan', None),
    'a1-umbrella': ('Payung', None),
    'a1-to-wear': ('Memakai', None),
    'a1-sweater': ('Sweter', None),
    'a1-t-shirt': ('Kaos', None),
    'a1-scarf': ('Syal', None),
    'a1-gloves': ('Sarung tangan', None),
    'a1-clothes': ('Pakaian', None),
    'a1-size': ('Ukuran', None),
    'a1-to-be': ('Adalah', None),
    'a1-to-have': ('Memiliki', None),
    'a1-to-do': ('Melakukan', None),
    'a1-to-go': ('Pergi', None),
    'a1-to-come': ('Datang', None),
    'a1-to-want': ('Ingin', None),
    'a1-to-be-able-to': ('Bisa', None),
    'a1-to-know': ('Mengetahui', None),
    'a1-to-see': ('Melihat', None),
    'a1-to-say': ('Mengatakan', None),
    'a1-to-eat': ('Makan', None),
    'a1-to-drink': ('Minum', None),
    'a1-to-sleep': ('Tidur', None),
    'a1-to-live': ('Tinggal', None),
    'a1-to-work': ('Bekerja', None),
    'a1-to-speak': ('Berbicara', None),
    'a1-to-understand': ('Mengerti', None),
    'a1-to-like': ('Menyukai', None),
    'a1-to-need': ('Membutuhkan', None),
    'a1-to-give': ('Memberi', None),
    'a1-to-take': ('Mengambil', None),
    'a1-to-think': ('Berpikir', None),
    'a1-to-buy': ('Membeli', None),
    'a1-to-help': ('Membantu', None),
    'a1-to-open': ('Membuka', None),
    'a1-to-close': ('Menutup', None),
    'a1-to-look-for': ('Mencari', None),
    'a1-to-find': ('Menemukan', None),
    'a1-to-wait': ('Menunggu', None),
    'a1-to-call-phone': ('Menelepon', None),
    'a1-to-read': ('Membaca', None),
    'a1-to-write': ('Menulis', None),
    'a1-to-listen': ('Mendengarkan', None),
    'a1-to-learn': ('Belajar', None),
    'a1-to-play': ('Bermain', None),
    'a1-to-walk': ('Berjalan', None),
    'a1-to-run': ('Berlari', None),
    'a1-to-sit': ('Duduk', None),
    'a1-to-stand': ('Berdiri', None),
    'a1-to-arrive': ('Tiba', None),
    'a1-to-leave': ('Berangkat', None),
    'a1-to-return': ('Kembali', None),
    'a1-to-put': ('Meletakkan', None),
    'a1-to-bring': ('Membawa', None),
    'a1-to-ask': ('Bertanya', None),
    'a1-to-answer': ('Menjawab', None),
    'a1-to-love': ('Mencintai', None),
    'a1-to-pay': ('Membayar', None),
    'a1-good': ('Baik', None),
    'a1-bad': ('Buruk', None),
    'a1-new': ('Baru', None),
    'a1-old-thing': ('Lama', None),
    'a1-young': ('Muda', None),
    'a1-hot': ('Panas', None),
    'a1-cold': ('Dingin', None),
    'a1-happy': ('Senang', None),
    'a1-sad': ('Sedih', None),
    'a1-beautiful': ('Cantik', None),
    'a1-ugly': ('Jelek', None),
    'a1-easy': ('Mudah', None),
    'a1-difficult': ('Sulit', None),
    'a1-fast': ('Cepat', None),
    'a1-slow': ('Lambat', None),
    'a1-cheap': ('Murah', None),
    'a1-expensive': ('Mahal', None),
    'a1-full': ('Penuh', None),
    'a1-empty': ('Kosong', None),
    'a1-clean': ('Bersih', None),
    'a1-dirty': ('Kotor', None),
    'a1-strong': ('Kuat', None),
    'a1-weak': ('Lemah', None),
    'a1-important': ('Penting', None),
    'a1-what': ('Apa', None),
    'a1-who': ('Siapa', None),
    'a1-where': ('Di mana', None),
    'a1-when': ('Kapan', None),
    'a1-why': ('Mengapa', None),
    'a1-how': ('Bagaimana', None),
    'a1-how-many': ('Berapa', None),
    'a1-which': ('Yang mana', None),
    'a1-and': ('Dan', None),
    'a1-or': ('Atau', None),
    'a1-but': ('Tetapi', None),
    'a1-because': ('Karena', None),
    'a1-with': ('Dengan', None),
    'a1-without': ('Tanpa', None),
    'a1-for': ('Untuk', None),
    'a1-from': ('Dari', None),
    'a1-to-direction': ('Ke', None),
    'a1-in': ('Di', None),
    'a1-on': ('Di atas', None),
    'a1-under': ('Di bawah', None),
    'a1-this': ('Ini', None),
    'a1-that': ('Itu', None),
    'a1-very': ('Sangat', None),
    'a1-also': ('Juga', None),
    'a1-not': ('Tidak', None),
    'a1-maybe': ('Mungkin', None),
    'a1-sun': ('Matahari', None),
    'a1-rain': ('Hujan', None),
    'a1-snow': ('Salju', None),
    'a1-wind': ('Angin', None),
    'a1-cloud': ('Awan', None),
    'a1-weather': ('Cuaca', None),
    'a1-sky': ('Langit', None),
    'a1-sea': ('Laut', None),
    'a1-mountain': ('Gunung', None),
    'a1-river': ('Sungai', None),
    'a1-tree': ('Pohon', None),
    'a1-flower': ('Bunga', None),
    'a1-dog': ('Anjing', None),
    'a1-cat': ('Kucing', None),
    'a1-bird': ('Burung', None),
    'a1-fish-animal': ('Ikan', None),
    'a1-horse': ('Kuda', None),
    'a1-cow': ('Sapi', None),
    'a1-earth': ('Bumi', None),
    'a1-moon': ('Bulan', None),
    'a1-star': ('Bintang', None),
    'a1-fire': ('Api', None),
    'a1-its-windy': ('Sedang berangin', None),
    'a1-its-snowing': ('Sedang turun salju', None),
    'a1-its-cold-today': ('Hari ini dingin', None),
    'a1-its-hot-today': ('Hari ini panas', None),
    'a1-help': ('Tolong!', None),
    'a1-slowly-please': ('Pelan-pelan, tolong', None),
    'a1-do-you-speak-english': ('Apakah Anda bisa berbahasa Inggris?', None),
    'a1-i-dont-know': ('Saya tidak tahu', None),
    'a1-where-is-the-bathroom': ('Di mana kamar mandi?', None),
    'a1-which-way': ('Ke arah mana?', None),
    'a1-one-moment-please': ('Sebentar, tolong', None),
    'a1-of-course': ('Tentu saja', None),
    'a1-no-problem': ('Tidak masalah', None),
    'a1-its-okay': ('Tidak apa-apa', None),
    'a1-lets-go': ('Ayo pergi', None),
    'a1-come-in': ('Silakan masuk', None),
    'a1-be-careful': ('Hati-hati', None),
    'a1-can-you-help-me': ('Bisakah Anda membantu saya?', None),
    'a1-what-does-that-mean': ('Apa artinya itu?', None),
    'a1-can-you-repeat-that': ('Bisakah Anda mengulanginya?', None),
    'a1-slower-please': ('Lebih pelan, tolong', None),
    'a1-how-do-you-say': ('Bagaimana cara mengatakan...?', None),
    'a1-i-would-like': ('Saya ingin...', None),
    'a1-the-bill-please': ('Tolong bonnya', None),
    'a1-im-tired': ('Saya lelah', None),
    'a1-im-sick': ('Saya sakit', None),
    'a1-its-an-emergency': ('Ini keadaan darurat', None),
    'a1-call-the-police': ('Panggil polisi', None),
    'a1-i-speak-a-little': ('Saya bisa berbahasa sedikit', None),
    'a1-i-love-it': ('Saya suka sekali', None),
    'a1-whats-this': ('Apa ini?', None),
    'a1-i-agree': ('Saya setuju', None),
    'a1-i-dont-like-it': ('Saya tidak suka', None),
    'a1-really': ('Benarkah?', None),
    'a1-exactly': ('Tepat sekali', None),
    'a1-i-think-so': ('Saya rasa begitu', None),
    'a1-dont-worry': ('Jangan khawatir', None),
    'a1-just-a-little': ('Sedikit saja', None),
    'a1-wait-a-moment': ('Tunggu sebentar', None),
    'a1-is-this-seat-free': ('Apakah kursi ini kosong?', None),
    'a1-money': ('Uang', None),
    'a1-price': ('Harga', None),
    'a1-to-sell': ('Menjual', None),
    'a1-card': ('Kartu', None),
    'a1-cash': ('Tunai', None),
    'a1-receipt': ('Struk', None),
    'a1-open-shop': ('Buka', None),
    'a1-closed-shop': ('Tutup', None),
    'a1-free-no-cost': ('Gratis', None),
    'a1-discount': ('Diskon', None),
    'a1-how-much-is-it': ('Berapa harganya?', None),
    'a1-too-much': ('Terlalu banyak', None),
    'a1-gift': ('Hadiah', None),
    'a1-change-coins': ('Kembalian', None),
    'a1-supermarket': ('Supermarket', None),
    'a1-pharmacy': ('Apotek', None),
    'a1-bakery': ('Toko roti', None),
    'a1-is-this-on-sale': ('Apakah ini sedang diskon?', None),
    'a1-car': ('Mobil', None),
    'a1-bus': ('Bus', None),
    'a1-train': ('Kereta', None),
    'a1-plane': ('Pesawat', None),
    'a1-bicycle': ('Sepeda', None),
    'a1-taxi': ('Taksi', None),
    'a1-ticket': ('Tiket', None),
    'a1-station': ('Stasiun', None),
    'a1-airport': ('Bandara', None),
    'a1-road': ('Jalan raya', None),
    'a1-to-travel': ('Bepergian', None),
    'a1-trip': ('Perjalanan', None),
    'a1-map': ('Peta', None),
    'a1-stop-bus-stop': ('Halte', None),
    'a1-to-drive': ('Mengemudi', None),
    'a1-subway': ('Kereta bawah tanah', None),
    'a1-passport': ('Paspor', None),
    'a1-suitcase': ('Koper', None),
    'a1-exit': ('Keluar', None),
    'a1-entrance': ('Masuk', None),
    'a1-phone': ('Telepon', None),
    'a1-book': ('Buku', None),
    'a1-pen': ('Pulpen', None),
    'a1-paper': ('Kertas', None),
    'a1-key': ('Kunci', None),
    'a1-computer': ('Komputer', None),
    'a1-clock': ('Jam dinding', None),
    'a1-television': ('Televisi', None),
    'a1-camera': ('Kamera', None),
    'a1-box': ('Kotak', None),
    'a1-glass-cup': ('Gelas', None),
    'a1-bottle': ('Botol', None),
    'a1-plate': ('Piring', None),
    'a1-knife': ('Pisau', None),
    'a1-fork': ('Garpu', None),
    'a1-spoon': ('Sendok', None),
    'a1-cup': ('Cangkir', None),
    'a1-soap': ('Sabun', None),
    'a1-towel': ('Handuk', None),
    'a1-lamp': ('Lampu', None),
    'a1-wallet': ('Dompet', None),
    'a1-charger': ('Pengisi daya', None),
    'a1-thing': ('Benda', None),
    'a1-toothbrush': ('Sikat gigi', None),
    'a1-angry': ('Marah', None),
    'a1-scared': ('Takut', None),
    'a1-bored': ('Bosan', None),
    'a1-excited': ('Bersemangat', None),
    'a1-worried': ('Khawatir', None),
    'a1-surprised': ('Terkejut', None),
    'a1-calm': ('Tenang', None),
    'a1-nervous': ('Gugup', None),
    'a1-proud': ('Bangga', None),
    'a1-lonely': ('Kesepian', None),
    'a1-sleepy': ('Mengantuk', None),
    'a1-sick-unwell': ('Sakit', None),
    'a1-love': ('Cinta', None),
    'a1-fear': ('Ketakutan', None),
    'a1-joy': ('Kegembiraan', None),
    'a1-funny': ('Lucu', None),
    'a2-i-work-in-an-office': ('Saya bekerja di kantor', None),
    'a2-i-am-a-student': ('Saya seorang pelajar', None),
    'a2-i-have-a-meeting': ('Saya ada rapat', None),
    'a2-i-am-looking-for-a-job': ('Saya sedang mencari pekerjaan', None),
    'a2-i-am-studying': ('Saya sedang belajar', None),
    'a2-i-dont-understand': ('Saya tidak mengerti', None),
    'a2-how-much-is-this': ('Berapa harga ini?', None),
    'a2-its-too-expensive': ('Ini terlalu mahal', None),
    'a2-can-i-pay-by-card': ('Bisakah saya bayar dengan kartu?', None),
    'a2-do-you-have-a-discount': ('Apakah ada diskon?', None),
    'a2-im-just-looking': ('Saya hanya lihat-lihat', None),
    'a2-ill-take-it': ('Saya ambil ini', None),
    'a2-where-is-the-train-station': ('Di mana stasiun kereta?', None),
    'a2-one-ticket-please': ('Satu tiket, tolong', None),
    'a2-how-do-i-get-to-the-airport': ('Bagaimana cara ke bandara?', None),
    'a2-im-lost': ('Saya tersesat', None),
    'a2-is-it-far': ('Apakah itu jauh?', None),
    'a2-where-is-the-restroom': ('Di mana toilet?', None),
    'a2-i-dont-feel-well': ('Saya merasa tidak enak badan', None),
    'a2-i-have-a-headache': ('Saya sakit kepala', None),
    'a2-where-is-the-pharmacy': ('Di mana apotek?', None),
    'a2-i-need-a-doctor': ('Saya butuh dokter', None),
    'a2-im-allergic-to-peanuts': ('Saya alergi kacang tanah', None),
    'a2-it-hurts-here': ('Ini sakit di sini', None),
    'a2-its-sunny': ('Cuacanya cerah', None),
    'a2-its-raining': ('Sedang hujan', None),
    'a2-i-like-to-read': ('Saya suka membaca', None),
    'a2-my-favorite-is-music': ('Favorit saya adalah musik', None),
    'a2-on-weekends-i-rest': ('Di akhir pekan saya beristirahat', None),
    'a2-i-play-sports': ('Saya berolahraga', None),
    'a2-what-time-is-it': ('Jam berapa sekarang?', None),
    'a2-lets-meet-tomorrow': ('Ayo bertemu besok', None),
    'a2-can-you-call-me': ('Bisakah Anda menelepon saya?', None),
    'a2-see-you-later': ('Sampai jumpa nanti', None),
    'a2-whats-your-phone-number': ('Berapa nomor telepon Anda?', None),
    'a2-im-busy-today': ('Hari ini saya sibuk', None),
    'a2-job': ('Pekerjaan', None),
    'a2-boss': ('Bos', None),
    'a2-colleague': ('Rekan kerja', None),
    'a2-salary': ('Gaji', None),
    'a2-to-earn': ('Menghasilkan', None),
    'a2-class': ('Kelas', None),
    'a2-teacher': ('Guru', None),
    'a2-exam': ('Ujian', None),
    'a2-homework': ('Pekerjaan rumah', None),
    'a2-university': ('Universitas', None),
    'a2-to-teach': ('Mengajar', None),
    'a2-project': ('Proyek', None),
    'a2-deadline': ('Tenggat waktu', None),
    'a2-interview': ('Wawancara', None),
    'a2-career': ('Karier', None),
    'a2-break-pause': ('Istirahat', None),
    'a2-schedule': ('Jadwal', None),
    'a2-company': ('Perusahaan', None),
    'a2-customer': ('Pelanggan', None),
    'a2-unemployed': ('Menganggur', None),
    'a2-to-try-on': ('Mencoba (pakaian)', None),
    'a2-fitting-room': ('Ruang pas', None),
    'a2-sale-discount-event': ('Obral', None),
    'a2-to-return-an-item': ('Mengembalikan', None),
    'a2-refund': ('Pengembalian dana', None),
    'a2-brand': ('Merek', None),
    'a2-quality': ('Kualitas', None),
    'a2-cashier': ('Kasir', None),
    'a2-shopping-cart': ('Troli belanja', None),
    'a2-online-shopping': ('Belanja daring', None),
    'a2-to-order-online': ('Memesan', None),
    'a2-delivery': ('Pengiriman', None),
    'a2-package': ('Paket', None),
    'a2-to-choose': ('Memilih', None),
    'a2-to-compare': ('Membandingkan', None),
    'a2-it-fits-me': ('Ini pas untuk saya', None),
    'a2-too-big': ('Terlalu besar', None),
    'a2-do-you-have-it-in-another-color': ('Apakah ada warna lain?', None),
    'a2-mall': ('Mal', None),
    'a2-cheaper': ('Lebih murah', None),
    'a2-reservation': ('Reservasi', None),
    'a2-to-book': ('Memesan', None),
    'a2-check-in': ('Check-in', None),
    'a2-luggage': ('Bagasi', None),
    'a2-flight': ('Penerbangan', None),
    'a2-delay': ('Penundaan', None),
    'a2-departure': ('Keberangkatan', None),
    'a2-arrival': ('Kedatangan', None),
    'a2-gate': ('Gerbang keberangkatan', None),
    'a2-seat': ('Kursi', None),
    'a2-tourist': ('Turis', None),
    'a2-guide': ('Pemandu', None),
    'a2-sightseeing': ('Wisata', None),
    'a2-souvenir': ('Oleh-oleh', None),
    'a2-beach': ('Pantai', None),
    'a2-museum': ('Museum', None),
    'a2-to-visit': ('Mengunjungi', None),
    'a2-round-trip': ('Pulang pergi', None),
    'a2-one-way': ('Sekali jalan', None),
    'a2-abroad': ('Di luar negeri', None),
    'a2-doctor': ('Dokter', None),
    'a2-nurse': ('Perawat', None),
    'a2-medicine': ('Obat', None),
    'a2-pain': ('Rasa sakit', None),
    'a2-fever': ('Demam', None),
    'a2-cough': ('Batuk', None),
    'a2-a-cold-illness': ('Pilek', None),
    'a2-flu': ('Flu', None),
    'a2-allergy': ('Alergi', None),
    'a2-appointment': ('Janji temu', None),
    'a2-prescription': ('Resep dokter', None),
    'a2-stomachache': ('Sakit perut', None),
    'a2-healthy': ('Sehat', None),
    'a2-to-rest': ('Beristirahat', None),
    'a2-insurance': ('Asuransi', None),
    'a2-emergency': ('Keadaan darurat', None),
    'a2-dentist': ('Dokter gigi', None),
    'a2-injury': ('Cedera', None),
    'a2-i-feel-better': ('Saya merasa lebih baik', None),
    'a2-blood-pressure': ('Tekanan darah', None),
    'a2-hobby': ('Hobi', None),
    'a2-music': ('Musik', None),
    'a2-movie': ('Film', None),
    'a2-sport': ('Olahraga', None),
    'a2-soccer': ('Sepak bola', None),
    'a2-to-swim': ('Berenang', None),
    'a2-to-dance': ('Menari', None),
    'a2-to-sing': ('Bernyanyi', None),
    'a2-to-paint': ('Melukis', None),
    'a2-game': ('Permainan', None),
    'a2-team': ('Tim', None),
    'a2-to-win': ('Menang', None),
    'a2-to-lose-a-game': ('Kalah', None),
    'a2-concert': ('Konser', None),
    'a2-photography': ('Fotografi', None),
    'a2-to-hike': ('Mendaki', None),
    'a2-gym': ('Pusat kebugaran', None),
    'a2-to-exercise': ('Berolahraga', None),
    'a2-cloudy': ('Berawan', None),
    'a2-storm': ('Badai', None),
    'a2-humid': ('Lembap', None),
    'a2-forecast': ('Ramalan cuaca', None),
    'a2-to-plan': ('Merencanakan', None),
    'a2-to-meet-up': ('Bertemu', None),
    'a2-invitation': ('Undangan', None),
    'a2-to-invite': ('Mengundang', None),
    'a2-to-cancel': ('Membatalkan', None),
    'a2-free-time': ('Waktu luang', None),
    'a2-to-postpone': ('Menunda', None),
    'a2-internet': ('Internet', None),
    'a2-email': ('Email', None),
    'a2-message': ('Pesan', None),
    'a2-to-send': ('Mengirim', None),
    'a2-to-download': ('Mengunduh', None),
    'a2-app': ('Aplikasi', None),
    'a2-password': ('Kata sandi', None),
    'a2-screen': ('Layar', None),
    'a2-wi-fi': ('Wi-Fi', None),
    'a2-website': ('Situs web', None),
    'a2-video-call': ('Panggilan video', None),
    'a2-are-you-free-on-saturday': ('Apakah Anda kosong hari Sabtu?', None),
    'a2-sounds-good': ('Kedengarannya bagus', None),
    'a2-to-clean': ('Membersihkan', None),
    'a2-to-wash': ('Mencuci', None),
    'a2-dishes': ('Cucian piring', None),
    'a2-laundry': ('Cucian baju', None),
    'a2-to-iron': ('Menyetrika', None),
    'a2-trash': ('Sampah', None),
    'a2-to-tidy-up': ('Merapikan', None),
    'a2-vacuum-cleaner': ('Penyedot debu', None),
    'a2-to-repair': ('Memperbaiki', None),
    'a2-to-move-house': ('Pindah rumah', None),
    'a2-rent': ('Sewa', None),
    'a2-landlord': ('Pemilik rumah', None),
    'a2-apartment': ('Apartemen', None),
    'a2-furniture': ('Perabotan', None),
    'a2-sofa': ('Sofa', None),
    'a2-fridge': ('Kulkas', None),
    'a2-oven': ('Oven', None),
    'a2-stove': ('Kompor', None),
    'a2-shower': ('Pancuran', None),
    'a2-mirror': ('Cermin', None),
    'a2-pillow': ('Bantal', None),
    'a2-blanket': ('Selimut', None),
    'a2-washing-machine': ('Mesin cuci', None),
    'a2-roommate': ('Teman sekamar', None),
    'a2-stairs': ('Tangga', None),
    'a2-elevator': ('Lift', None),
    'a2-to-wake-up': ('Terbangun', None),
    'a2-to-get-up': ('Bangun', None),
    'a2-to-take-a-shower': ('Mandi', None),
    'a2-to-brush-ones-teeth': ('Menyikat gigi', None),
    'a2-to-get-dressed': ('Berpakaian', None),
    'a2-to-have-breakfast': ('Sarapan', None),
    'a2-to-commute': ('Pergi ke tempat kerja', None),
    'a2-to-go-home': ('Pulang', None),
    'a2-to-relax': ('Bersantai', None),
    'a2-to-watch-tv': ('Menonton TV', None),
    'a2-to-go-to-bed': ('Pergi tidur', None),
    'a2-routine': ('Rutinitas', None),
    'a2-habit': ('Kebiasaan', None),
    'a2-alarm-clock': ('Jam weker', None),
    'a2-to-be-late': ('Terlambat', None),
    'a2-to-hurry': ('Bergegas', None),
    'a2-on-time': ('Tepat waktu', None),
    'a2-nap': ('Tidur siang', None),
    'a2-to-take-a-walk': ('Jalan-jalan', None),
    'a2-to-have-lunch': ('Makan siang', None),
    'a2-to-have-dinner': ('Makan malam', None),
    'a2-to-fall-asleep': ('Tertidur', None),
    'a2-every-day': ('Setiap hari', None),
    'a2-usually': ('Biasanya', None),
    'a2-corner': ('Sudut', None),
    'a2-block': ('Blok', None),
    'a2-traffic-light': ('Lampu lalu lintas', None),
    'a2-bridge': ('Jembatan', None),
    'a2-square-plaza': ('Alun-alun', None),
    'a2-downtown': ('Pusat kota', None),
    'a2-neighborhood': ('Lingkungan', None),
    'a2-building': ('Gedung', None),
    'a2-sidewalk': ('Trotoar', None),
    'a2-to-cross': ('Menyeberang', None),
    'a2-to-turn': ('Belok', None),
    'a2-address': ('Alamat', None),
    'a2-post-office': ('Kantor pos', None),
    'a2-library': ('Perpustakaan', None),
    'a2-cinema': ('Bioskop', None),
    'a2-theater': ('Teater', None),
    'a2-stadium': ('Stadion', None),
    'a2-police-station': ('Kantor polisi', None),
    'a2-town-hall': ('Balai kota', None),
    'a2-parking-lot': ('Tempat parkir', None),
    'a2-gas-station': ('Pom bensin', None),
    'a2-traffic': ('Lalu lintas', None),
    'a2-opposite': ('Di seberang', None),
    'a2-next-to': ('Di sebelah', None),
    'a2-between': ('Di antara', None),
    'a2-how-do-i-get-to': ('Bagaimana cara ke...?', None),
    'a2-menu': ('Menu', None),
    'a2-waiter': ('Pelayan', None),
    'a2-dish': ('Hidangan', None),
    'a2-dessert': ('Makanan penutup', None),
    'a2-starter': ('Hidangan pembuka', None),
    'a2-main-course': ('Hidangan utama', None),
    'a2-vegetarian': ('Vegetarian', None),
    'a2-tip': ('Tip', None),
    'a2-to-cook': ('Memasak', None),
    'a2-recipe': ('Resep', None),
    'a2-ingredient': ('Bahan', None),
    'a2-oil': ('Minyak', None),
    'a2-butter': ('Mentega', None),
    'a2-pepper': ('Merica', None),
    'a2-onion': ('Bawang bombay', None),
    'a2-garlic': ('Bawang putih', None),
    'a2-tomato': ('Tomat', None),
    'a2-potato': ('Kentang', None),
    'a2-noodles': ('Mi', None),
    'a2-sauce': ('Saus', None),
    'a2-to-bake': ('Memanggang', None),
    'a2-to-fry': ('Menggoreng', None),
    'a2-to-boil': ('Merebus', None),
    'a2-a-table-for-two': ('Meja untuk dua orang', None),
    'a2-takeout': ('Untuk dibawa pulang', None),
    'a2-snack': ('Camilan', None),
    'a2-salty': ('Asin', None),
    'a2-bitter': ('Pahit', None),
    'a2-tall': ('Tinggi', None),
    'a2-short-height': ('Pendek', None),
    'a2-thin': ('Kurus', None),
    'a2-overweight': ('Gemuk', None),
    'a2-blond': ('Pirang', None),
    'a2-dark-haired': ('Berambut hitam', None),
    'a2-beard': ('Janggut', None),
    'a2-kind': ('Baik hati', None),
    'a2-nice-person': ('Ramah', None),
    'a2-shy': ('Pemalu', None),
    'a2-talkative': ('Cerewet', None),
    'a2-smart': ('Pintar', None),
    'a2-lazy': ('Malas', None),
    'a2-hardworking': ('Rajin', None),
    'a2-polite': ('Sopan', None),
    'a2-rude': ('Kasar', None),
    'a2-patient': ('Sabar', None),
    'a2-honest': ('Jujur', None),
    'a2-serious': ('Serius', None),
    'a2-quiet-person': ('Pendiam', None),
    'a2-friendly': ('Bersahabat', None),
    'a2-handsome': ('Tampan', None),
    'a2-age': ('Usia', None),
    'a2-old-person': ('Tua', None),
    'a2-curly-hair': ('Rambut keriting', None),
    'a2-cheerful': ('Ceria', None),
    'a2-stubborn': ('Keras kepala', None),
    'a2-generous': ('Murah hati', None),
    'a2-to-try': ('Mencoba', None),
    'a2-to-start': ('Memulai', None),
    'a2-to-finish': ('Menyelesaikan', None),
    'a2-to-change': ('Mengubah', None),
    'a2-to-use': ('Menggunakan', None),
    'a2-to-receive': ('Menerima', None),
    'a2-to-decide': ('Memutuskan', None),
    'a2-to-forget': ('Melupakan', None),
    'a2-to-remember': ('Mengingat', None),
    'a2-to-lose-an-object': ('Kehilangan', None),
    'a2-to-meet-someone-new': ('Berkenalan', None),
    'a2-to-prefer': ('Lebih suka', None),
    'a2-to-hope': ('Berharap', None),
    'a2-to-believe': ('Percaya', None),
    'a2-to-feel': ('Merasa', None),
    'a2-to-seem': ('Tampaknya', None),
    'a2-to-happen': ('Terjadi', None),
    'a2-to-stay': ('Menginap', None),
    'a2-to-spend-money': ('Menghabiskan', None),
    'a2-to-show': ('Menunjukkan', None),
    'a2-to-explain': ('Menjelaskan', None),
    'a2-to-follow': ('Mengikuti', None),
    'a2-to-keep': ('Menyimpan', None),
    'a2-to-allow': ('Mengizinkan', None),
    'a2-to-become': ('Menjadi', None),
    'a2-to-continue': ('Melanjutkan', None),
    'a2-to-cut': ('Memotong', None),
    'a2-to-break': ('Mematahkan', None),
    'a2-to-fly': ('Terbang', None),
    'a2-to-draw': ('Menggambar', None),
    'a2-to-carry': ('Mengangkut', None),
    'a2-to-push': ('Mendorong', None),
    'a2-to-pull': ('Menarik', None),
    'a2-to-throw': ('Melempar', None),
    'a2-to-catch': ('Menangkap', None),
    'a2-to-build': ('Membangun', None),
    'a2-to-grow': ('Tumbuh', None),
    'a2-to-fall': ('Jatuh', None),
    'a2-to-climb': ('Memanjat', None),
    'a2-to-jump': ('Melompat', None),
    'a2-to-laugh': ('Tertawa', None),
    'a2-to-cry': ('Menangis', None),
    'a2-to-smile': ('Tersenyum', None),
    'a2-to-shout': ('Berteriak', None),
    'a2-to-whisper': ('Berbisik', None),
    'a2-to-hug': ('Memeluk', None),
    'a2-to-kiss': ('Mencium', None),
    'a2-to-touch': ('Menyentuh', None),
    'a2-to-smell': ('Membaui', None),
    'a2-to-taste': ('Mencicipi', None),
    'a2-to-wash-oneself': ('Membersihkan diri', None),
    'a2-to-hide': ('Menyembunyikan', None),
    'a2-interesting': ('Menarik', None),
    'a2-boring': ('Membosankan', None),
    'a2-comfortable': ('Nyaman', None),
    'a2-dangerous': ('Berbahaya', None),
    'a2-safe': ('Aman', None),
    'a2-noisy': ('Berisik', None),
    'a2-busy': ('Sibuk', None),
    'a2-heavy': ('Berat', None),
    'a2-light-weight': ('Ringan', None),
    'a2-wide': ('Lebar', None),
    'a2-narrow': ('Sempit', None),
    'a2-soft': ('Lembut', None),
    'a2-hard-firm': ('Keras', None),
    'a2-wet': ('Basah', None),
    'a2-dry': ('Kering', None),
    'a2-rich': ('Kaya', None),
    'a2-poor': ('Miskin', None),
    'a2-famous': ('Terkenal', None),
    'a2-popular': ('Populer', None),
    'a2-modern': ('Modern', None),
    'a2-traditional': ('Tradisional', None),
    'a2-ready': ('Siap', None),
    'a2-sure': ('Yakin', None),
    'a2-wrong': ('Salah', None),
    'a2-correct': ('Benar', None),
    'a2-strange': ('Aneh', None),
    'a2-same': ('Sama', None),
    'a2-different': ('Berbeda', None),
    'a2-last-week': ('Pekan lalu', None),
    'a2-next-week': ('Pekan depan', None),
    'a2-this-month': ('Bulan ini', None),
    'a2-last-year': ('Tahun lalu', None),
    'a2-next-year': ('Tahun depan', None),
    'a2-at-the-end': ('Pada akhirnya', None),
    'a2-at-the-beginning': ('Pada awalnya', None),
    'a2-twice': ('Dua kali', None),
    'a2-once': ('Sekali', None),
    'a2-in-a-hurry': ('Terburu-buru', None),
    'a2-for-a-long-time': ('Untuk waktu yang lama', None),
    'a2-recently': ('Baru-baru ini', None),
    'a2-already': ('Sudah', None),
    'a2-still': ('Masih', None),
    'a2-not-yet': ('Belum', None),
    'a2-until': ('Sampai', None),
    'a2-since': ('Sejak', None),
    'a2-during': ('Selama', None),
    'a2-ago': ('Yang lalu', None),
    'a2-at-least': ('Setidaknya', None),
    'a2-right-away': ('Langsung', None),
    'a2-finally': ('Akhirnya', None),
    'a2-suddenly': ('Tiba-tiba', None),
    'a2-the-day-after-tomorrow': ('Lusa', None),
    'a2-conversation': ('Percakapan', None),
    'a2-question': ('Pertanyaan', None),
    'a2-answer-noun': ('Jawaban', None),
    'a2-opinion': ('Pendapat', None),
    'a2-to-describe': ('Menggambarkan', None),
    'a2-to-promise': ('Berjanji', None),
    'a2-to-suggest': ('Menyarankan', None),
    'a2-to-complain': ('Mengeluh', None),
    'a2-to-apologize': ('Meminta maaf', None),
    'a2-to-thank': ('Berterima kasih', None),
    'a2-joke': ('Lelucon', None),
    'a2-story': ('Cerita', None),
    'a2-news': ('Berita', None),
    'a2-to-argue': ('Bertengkar', None),
    'a2-to-discuss': ('Membahas', None),
    'a2-secret': ('Rahasia', None),
    'a2-to-mean': ('Berarti', None),
    'a2-to-pronounce': ('Melafalkan', None),
    'a2-to-translate': ('Menerjemahkan', None),
    'a2-word': ('Kata', None),
    'a2-sentence': ('Kalimat', None),
    'a2-language': ('Bahasa', None),
    'a2-to-spell': ('Mengeja', None),
    'a2-to-lie': ('Berbohong', None),
    'a2-truth': ('Kebenaran', None),
    'a2-to-chat': ('Mengobrol', None),
    'a2-accent': ('Aksen', None),
    'a2-fluent': ('Lancar', None),
    'a2-to-get-married': ('Menikah', None),
    'a2-wedding': ('Pernikahan', None),
    'a2-couple': ('Pasangan', None),
    'a2-childhood': ('Masa kecil', None),
    'a2-teenager': ('Remaja', None),
    'a2-adult': ('Dewasa', None),
    'a2-to-grow-up': ('Tumbuh dewasa', None),
    'a2-anniversary': ('Hari jadi pernikahan', None),
    'a2-party': ('Pesta', None),
    'a2-guest': ('Tamu', None),
    'a2-to-celebrate': ('Merayakan', None),
    'a2-to-be-born': ('Lahir', None),
    'a2-to-die': ('Meninggal', None),
    'a2-relatives': ('Kerabat', None),
    'a2-twins': ('Kembar', None),
    'a2-only-child': ('Anak tunggal', None),
    'a2-to-take-care-of': ('Merawat', None),
    'a2-nephew': ('Keponakan laki-laki', None),
    'a2-niece': ('Keponakan perempuan', None),
    'a2-grandchild': ('Cucu', None),
    'a2-single': ('Lajang', None),
    'a2-divorced': ('Bercerai', None),
    'a2-christmas': ('Natal', None),
    'a2-new-year': ('Tahun Baru', None),
    'a2-cake': ('Kue', None),
    'a2-candle': ('Lilin', None),
    'a2-lesson': ('Pelajaran', None),
    'a2-course': ('Kursus', None),
    'a2-to-practice': ('Berlatih', None),
    'a2-mistake': ('Kesalahan', None),
    'a2-to-correct': ('Mengoreksi', None),
    'a2-grade-mark': ('Nilai', None),
    'a2-to-pass-an-exam': ('Lulus', None),
    'a2-to-fail-an-exam': ('Gagal', None),
    'a2-to-graduate': ('Wisuda', None),
    'a2-degree': ('Gelar', None),
    'a2-subject': ('Mata pelajaran', None),
    'a2-math': ('Matematika', None),
    'a2-history': ('Sejarah', None),
    'a2-science': ('Sains', None),
    'a2-art': ('Seni', None),
    'a2-dictionary': ('Kamus', None),
    'a2-notebook': ('Buku catatan', None),
    'a2-to-memorize': ('Menghafal', None),
    'a2-to-review': ('Meninjau', None),
    'a2-classroom': ('Ruang kelas', None),
    'a2-semester': ('Semester', None),
    'a2-scholarship': ('Beasiswa', None),
    'a2-to-register': ('Mendaftar', None),
    'a2-example': ('Contoh', None),
    'a2-level': ('Tingkat', None),
    'a2-beginner': ('Pemula', None),
    'a2-to-save-money': ('Menabung', None),
    'a2-bank-account': ('Rekening bank', None),
    'a2-to-withdraw': ('Menarik uang', None),
    'a2-to-deposit': ('Menyetor', None),
    'a2-atm': ('ATM', None),
    'a2-loan': ('Pinjaman', None),
    'a2-debt': ('Utang', None),
    'a2-to-borrow': ('Meminjam', None),
    'a2-to-lend': ('Meminjamkan', None),
    'a2-to-owe': ('Berutang', None),
    'a2-tax': ('Pajak', None),
    'a2-bill-utility': ('Tagihan', None),
    'a2-budget': ('Anggaran', None),
    'a2-to-afford': ('Mampu membeli', None),
    'a2-interest-bank': ('Bunga', None),
    'a2-coin': ('Koin', None),
    'a2-to-exchange-money': ('Menukar', None),
    'a2-exchange-rate': ('Nilai tukar', None),
    'a2-credit-card': ('Kartu kredit', None),
    'a2-to-cost': ('Berharga', None),
    'a2-salary-raise': ('Kenaikan gaji', None),
    'a2-expensive-habit': ('Kebiasaan mahal', None),
    'a2-invoice': ('Faktur', None),
    'a2-payment': ('Pembayaran', None),
    'a2-to-miss-someone': ('Merindukan', None),
    'a2-to-worry': ('Khawatir', None),
    'a2-to-enjoy': ('Menikmati', None),
    'a2-to-hate': ('Membenci', None),
    'a2-to-be-afraid-of': ('Takut akan', None),
    'a2-ashamed': ('Malu', None),
    'a2-jealous': ('Cemburu', None),
    'a2-embarrassed': ('Merasa canggung', None),
    'a2-disappointed': ('Kecewa', None),
    'a2-grateful': ('Bersyukur', None),
    'a2-relieved': ('Lega', None),
    'a2-confused': ('Bingung', None),
    'a2-curious': ('Penasaran', None),
    'a2-hopeful': ('Penuh harapan', None),
    'a2-frustrated': ('Frustrasi', None),
    'a2-stressed': ('Stres', None),
    'a2-in-a-good-mood': ('Suasana hati baik', None),
    'a2-in-a-bad-mood': ('Suasana hati buruk', None),
    'a2-to-cheer-up': ('Menghibur diri', None),
    'a2-to-calm-down': ('Menenangkan diri', None),
    'a2-to-get-angry': ('Menjadi marah', None),
    'a2-to-fall-in-love': ('Jatuh cinta', None),
    'a2-mood': ('Suasana hati', None),
    'a2-satisfied': ('Puas', None),
    'a2-forest': ('Hutan', None),
    'a2-lake': ('Danau', None),
    'a2-island': ('Pulau', None),
    'a2-desert': ('Gurun', None),
    'a2-field': ('Ladang', None),
    'a2-farm': ('Peternakan', None),
    'a2-animal': ('Hewan', None),
    'a2-insect': ('Serangga', None),
    'a2-mosquito': ('Nyamuk', None),
    'a2-bee': ('Lebah', None),
    'a2-butterfly': ('Kupu-kupu', None),
    'a2-snake': ('Ular', None),
    'a2-lion': ('Singa', None),
    'a2-elephant': ('Gajah', None),
    'a2-monkey': ('Monyet', None),
    'a2-rabbit': ('Kelinci', None),
    'a2-pig': ('Babi', None),
    'a2-sheep': ('Domba', None),
    'a2-plant': ('Tanaman', None),
    'a2-grass': ('Rumput', None),
    'a2-leaf': ('Daun', None),
    'a2-rock': ('Batu', None),
    'a2-sand': ('Pasir', None),
    'a2-ocean': ('Samudra', None),
    'a2-wave': ('Ombak', None),
    'a2-thunder': ('Guntur', None),
    'a2-fog': ('Kabut', None),
    'a2-temperature': ('Suhu', None),
    'a2-laptop': ('Laptop', None),
    'a2-keyboard': ('Papan ketik', None),
    'a2-printer': ('Printer', None),
    'a2-file': ('Berkas', None),
    'a2-folder': ('Folder', None),
    'a2-to-print': ('Mencetak', None),
    'a2-to-click': ('Mengeklik', None),
    'a2-to-type': ('Mengetik', None),
    'a2-to-search-online': ('Mencari secara daring', None),
    'a2-social-media': ('Media sosial', None),
    'a2-to-post': ('Mengunggah', None),
    'a2-to-share': ('Membagikan', None),
    'a2-video': ('Video', None),
    'a2-photo': ('Foto', None),
    'a2-selfie': ('Swafoto', None),
    'a2-headphones': ('Headphone', None),
    'a2-speaker': ('Pengeras suara', None),
    'a2-battery': ('Baterai', None),
    'a2-to-turn-on': ('Menyalakan', None),
    'a2-to-turn-off': ('Mematikan', None),
    'a2-volume': ('Volume', None),
    'a2-channel': ('Saluran', None),
    'a2-podcast': ('Podcast', None),
    'a2-screenshot': ('Tangkapan layar', None),
    'a2-update': ('Pembaruan', None),
    'a2-notification': ('Notifikasi', None),
    'a2-to-log-in': ('Masuk', None),
    'a2-subtitles': ('Subtitel', None),
    'a2-what-do-you-think': ('Menurutmu bagaimana?', None),
    'a2-it-depends': ('Tergantung', None),
    'a2-im-not-sure': ('Saya tidak yakin', None),
    'a2-let-me-think': ('Biar saya pikirkan', None),
    'a2-what-a-pity': ('Sayang sekali', None),
    'a2-never-mind': ('Lupakan saja', None),
    'a2-hurry-up': ('Ayo cepat', None),
    'a2-watch-out': ('Awas!', None),
    'a2-thats-a-good-idea': ('Itu ide yang bagus', None),
    'a2-are-you-kidding': ('Apakah kamu bercanda?', None),
    'a2-its-up-to-you': ('Terserah kamu', None),
    'a2-im-on-my-way': ('Saya sedang dalam perjalanan', None),
    'a2-same-here': ('Saya juga', None),
    'a2-me-neither': ('Saya juga tidak', None),
    'a2-by-the-way': ('Ngomong-ngomong', None),
    'a2-in-my-opinion': ('Menurut saya', None),
    'a2-to-be-honest': ('Sejujurnya', None),
    'a2-actually': ('Sebenarnya', None),
    'a2-anyway': ('Bagaimanapun juga', None),
    'a2-for-example': ('Sebagai contoh', None),
    'a2-sorry-im-late': ('Maaf saya terlambat', None),
    'a2-no-way': ('Tidak mungkin!', None),
    'a2-that-makes-sense': ('Itu masuk akal', None),
    'a2-good-point': ('Poin bagus', None),
    'a2-banana': ('Pisang', None),
    'a2-orange-fruit': ('Jeruk', None),
    'a2-grapes': ('Anggur', None),
    'a2-strawberry': ('Stroberi', None),
    'a2-lemon': ('Lemon', None),
    'a2-watermelon': ('Semangka', None),
    'a2-peach': ('Persik', None),
    'a2-pear': ('Pir', None),
    'a2-carrot': ('Wortel', None),
    'a2-lettuce': ('Selada', None),
    'a2-cucumber': ('Timun', None),
    'a2-bell-pepper': ('Paprika', None),
    'a2-mushroom': ('Jamur', None),
    'a2-corn': ('Jagung', None),
    'a2-beans': ('Buncis', None),
    'a2-spinach': ('Bayam', None),
    'a2-cabbage': ('Kubis', None),
    'a2-pumpkin': ('Labu', None),
    'a2-nuts': ('Kacang-kacangan', None),
    'a2-coconut': ('Kelapa', None),
    'a2-mango': ('Mangga', None),
    'a2-pineapple': ('Nanas', None),
    'a2-cherry': ('Ceri', None),
    'a2-avocado': ('Alpukat', None),
    'a2-ripe': ('Matang', None),
    'a2-fresh': ('Segar', None),
    'a2-kilogram': ('Kilogram', None),
    'a2-gram': ('Gram', None),
    'a2-liter': ('Liter', None),
    'a2-meter': ('Meter', None),
    'a2-kilometer': ('Kilometer', None),
    'a2-centimeter': ('Sentimeter', None),
    'a2-piece': ('Potongan', None),
    'a2-slice': ('Irisan', None),
    'a2-dozen': ('Lusin', None),
    'a2-pair': ('Pasang', None),
    'a2-percent': ('Persen', None),
    'a2-degree-temperature': ('Derajat', None),
    'a2-a-bit': ('Sedikit', None),
    'a2-a-lot': ('Banyak', None),
    'a2-several': ('Sejumlah', None),
    'a2-double': ('Dua kali lipat', None),
    'a2-weight': ('Berat', None),
    'a2-height': ('Tinggi', None),
    'a2-length': ('Panjang', None),
    'a2-distance': ('Jarak', None),
    'a2-speed': ('Kecepatan', None),
    'a2-total': ('Total', None),
    'a2-almost': ('Hampir', None),
    'a2-only': ('Hanya', None),
    'a2-engineer': ('Insinyur', None),
    'a2-lawyer': ('Pengacara', None),
    'a2-chef': ('Koki', None),
    'a2-driver': ('Sopir', None),
    'a2-farmer': ('Petani', None),
    'a2-artist': ('Seniman', None),
    'a2-musician': ('Musisi', None),
    'a2-actor': ('Aktor', None),
    'a2-writer': ('Penulis', None),
    'a2-journalist': ('Jurnalis', None),
    'a2-police-officer': ('Polisi', None),
    'a2-firefighter': ('Petugas pemadam kebakaran', None),
    'a2-scientist': ('Ilmuwan', None),
    'a2-programmer': ('Programmer', None),
    'a2-designer': ('Desainer', None),
    'a2-manager': ('Manajer', None),
    'a2-salesperson': ('Penjual', None),
    'a2-mechanic': ('Montir', None),
    'a2-electrician': ('Tukang listrik', None),
    'a2-plumber': ('Tukang ledeng', None),
    'a2-pilot': ('Pilot', None),
    'a2-accountant': ('Akuntan', None),
    'a2-architect': ('Arsitek', None),
    'a2-hairdresser': ('Penata rambut', None),
    'a2-soldier': ('Tentara', None),
    'a2-baker': ('Tukang roti', None),
    'a2-basketball': ('Bola basket', None),
    'a2-tennis': ('Tenis', None),
    'a2-baseball': ('Bisbol', None),
    'a2-volleyball': ('Bola voli', None),
    'a2-running': ('Lari', None),
    'a2-cycling': ('Bersepeda', None),
    'a2-skiing': ('Ski', None),
    'a2-surfing': ('Selancar', None),
    'a2-yoga': ('Yoga', None),
    'a2-chess': ('Catur', None),
    'a2-cards-game': ('Kartu remi', None),
    'a2-board-game': ('Permainan papan', None),
    'a2-video-game': ('Permainan video', None),
    'a2-puzzle': ('Teka-teki', None),
    'a2-to-go-camping': ('Berkemah', None),
    'a2-picnic': ('Piknik', None),
    'a2-fishing': ('Memancing', None),
    'a2-race': ('Balapan', None),
    'a2-competition': ('Kompetisi', None),
    'a2-referee': ('Wasit', None),
    'a2-coach': ('Pelatih', None),
    'a2-medal': ('Medali', None),
    'a2-score': ('Skor', None),
    'a2-fan-supporter': ('Penggemar', None),
    'a2-to-train': ('Berlatih', None),
}
