# -*- coding: utf-8 -*-
# Modern Greek (el) skill layer: extra grammar module, idioms, C2 nuance drills
LANG = 'el'

GRAMMAR = [
    {"id": "g-el1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Όταν ήμουν μικρός, ___ κάθε καλοκαίρι στο χωριό.", "correct": "πηγαίναμε",
     "options": ["πηγαίναμε", "πήγαμε", "θα πηγαίναμε", "πηγαίνουμε"],
     "romaji": {"πηγαίναμε": "pigainame", "πήγαμε": "pigame", "θα πηγαίναμε": "tha pigainame", "πηγαίνουμε": "pigainoume"},
     "note": "The imperfect πηγαίναμε narrates a repeated past habit — a storytelling staple; the aorist πήγαμε would mark a single completed trip instead."},
    {"id": "g-el2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Ξαφνικά, ενώ έτρωγα, ___ το τηλέφωνο.", "correct": "χτύπησε",
     "options": ["χτύπησε", "χτυπούσε", "θα χτυπήσει", "χτυπάει"],
     "romaji": {"χτύπησε": "chtypise", "χτυπούσε": "chtypouse", "θα χτυπήσει": "tha chtypisei", "χτυπάει": "chtypaei"},
     "note": "The aorist χτύπησε interrupts the ongoing imperfect έτρωγα — the classic background-vs-event contrast in Greek narration."},
    {"id": "g-el3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Αν ___ περισσότερο χρόνο, θα μάθαινα ελληνικά.", "correct": "είχα",
     "options": ["είχα", "έχω", "θα έχω", "θα είχα"],
     "romaji": {"είχα": "eicha", "έχω": "echo", "θα έχω": "tha echo", "θα είχα": "tha eicha"},
     "note": "Second conditional: αν + past tense (είχα) pairs with θα + past (μάθαινα) to express a hypothetical present."},
    {"id": "g-el4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Αν ___ νωρίτερα, δεν θα χάναμε το τρένο.", "correct": "είχαμε φύγει",
     "options": ["είχαμε φύγει", "φύγαμε", "θα φεύγαμε", "φεύγουμε"],
     "romaji": {"είχαμε φύγει": "eichame fygei", "φύγαμε": "fygame", "θα φεύγαμε": "tha fevgame", "φεύγουμε": "fevgoume"},
     "note": "Third conditional: αν + pluperfect (είχαμε φύγει) + θα + imperfect gives the unreal-past consequence."},
    {"id": "g-el5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Η τσάντα μου είναι πολύ ___.", "correct": "κόκκινη",
     "options": ["κόκκινη", "κόκκινο", "κόκκινος", "κόκκινους"],
     "romaji": {"κόκκινη": "kokkini", "κόκκινο": "kokkino", "κόκκινος": "kokkinos", "κόκκινους": "kokkinous"},
     "note": "Adjectives agree in gender, number and case with the noun; τσάντα is feminine singular, so the adjective takes -η."},
    {"id": "g-el6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Αυτά τα παπούτσια είναι πολύ ___.", "correct": "άνετα",
     "options": ["άνετα", "άνετος", "άνετη", "άνετους"],
     "romaji": {"άνετα": "aneta", "άνετος": "anetos", "άνετη": "aneti", "άνετους": "anetous"},
     "note": "παπούτσια is neuter plural, so the adjective takes the neuter plural ending -α."},
]

IDIOMS = [
    {"id": "i-el1", "tier": "C1", "topic": "idiom-character",
     "phrase": "Κάνει την πάπια", "romaji": "Kanei tin papia",
     "correct": "He plays dumb / pretends not to notice",
     "options": ["He plays dumb / pretends not to notice", "He works very hard", "He tells the truth bluntly", "He apologizes immediately"],
     "note": "Literally “he does/plays the duck” — said of someone who acts oblivious to avoid a problem or responsibility."},
    {"id": "i-el2", "tier": "C1", "topic": "idiom-character",
     "phrase": "Ψάχνει την τρίχα στ' αυγό", "romaji": "Psachnei tin tricha st' avgo",
     "correct": "He is excessively nitpicky",
     "options": ["He is excessively nitpicky", "He is very generous", "He is easily fooled", "He is completely careless"],
     "note": "Literally “he looks for the hair in the egg” — used for someone who obsesses over trivial flaws."},
    {"id": "i-el3", "tier": "C1", "topic": "idiom-character",
     "phrase": "Έχει μακριά γλώσσα", "romaji": "Echei makria glossa",
     "correct": "He talks too much / can't keep a secret",
     "options": ["He talks too much / can't keep a secret", "He is very shy", "He speaks several languages", "He is a great listener"],
     "note": "Literally “he has a long tongue” — describes a gossip or someone who blurts out things they shouldn't."},
    {"id": "i-el4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "Μου ήρθε σαν κεραμίδα", "romaji": "Mou irthe san keramida",
     "correct": "It hit me completely out of nowhere",
     "options": ["It hit me completely out of nowhere", "It made me very happy", "I expected it all along", "It cost me a fortune"],
     "note": "Literally “it came to me like a roof tile [falling on my head]” — an unexpected, usually unwelcome shock."},
    {"id": "i-el5", "tier": "C1", "topic": "idiom-media",
     "phrase": "Βγαίνει στον αέρα", "romaji": "Vgainei ston aera",
     "correct": "It goes live / is broadcast",
     "options": ["It goes live / is broadcast", "It gets cancelled", "It wins an award", "It goes out of print"],
     "note": "Literally “it comes out into the air” — standard phrase for a program going on air or streaming live."},
    {"id": "i-el6", "tier": "C1", "topic": "idiom-media",
     "phrase": "Κάνει πρωτοσέλιδο", "romaji": "Kanei protoselido",
     "correct": "It makes the front page / headline news",
     "options": ["It makes the front page / headline news", "It gets forgotten quickly", "It airs after midnight", "It is fact-checked"],
     "note": "Literally “it makes front page” — used when a story becomes the day's leading news item."},
]

NUANCE = [
    {"id": "n-el1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Asking a stranger on the street for directions, politely", "correct": "Συγγνώμη, θα μπορούσατε να με βοηθήσετε;",
     "options": ["Συγγνώμη, θα μπορούσατε να με βοηθήσετε;", "Πες μου πού είναι", "Δείξε μου", "Ξέρεις πού είναι, ναι ή όχι;"],
     "romaji": {"Συγγνώμη, θα μπορούσατε να με βοηθήσετε;": "Syngnomi, tha boroysate na me voithisete;", "Πες μου πού είναι": "Pes mou pou einai", "Δείξε μου": "Deixe mou", "Ξέρεις πού είναι, ναι ή όχι;": "Xereis pou einai, nai i ochi;"},
     "note": "The conditional θα μπορούσατε plus the formal σας-form is the polite register for a stranger; the others are commands you'd only use with close friends."},
    {"id": "n-el2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Writing a formal email to a professor asking for a deadline extension", "correct": "Θα ήθελα να σας παρακαλέσω για μια παράταση",
     "options": ["Θα ήθελα να σας παρακαλέσω για μια παράταση", "Δώσε μου παράταση", "Θέλω παράταση, τώρα", "Παράταση, ok;"],
     "romaji": {"Θα ήθελα να σας παρακαλέσω για μια παράταση": "Tha ithela na sas parakaleso gia mia paratasi", "Δώσε μου παράταση": "Dose mou paratasi", "Θέλω παράταση, τώρα": "Thelo paratasi, tora", "Παράταση, ok;": "Paratasi, ok;"},
     "note": "Θα ήθελα να σας παρακαλέσω stacks conditional hedging with the formal σας — the register a student owes a professor; the rest are blunt or text-message casual."},
    {"id": "n-el3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Saying you are personally acquainted with someone (the precise verb, not just general knowledge)", "correct": "γνωρίζω",
     "options": ["γνωρίζω", "ξέρω", "καταλαβαίνω", "μαθαίνω"],
     "romaji": {"γνωρίζω": "gnorizo", "ξέρω": "xero", "καταλαβαίνω": "katalavaino", "μαθαίνω": "mathaino"},
     "note": "γνωρίζω is the precise verb for personal acquaintance with a person; ξέρω is looser general knowing, καταλαβαίνω means understand, μαθαίνω means learn."},
    {"id": "n-el4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Choosing the precise word for examining something closely, not just glancing at it", "correct": "εξετάζω",
     "options": ["εξετάζω", "βλέπω", "κοιτάζω", "θωρώ"],
     "romaji": {"εξετάζω": "exetazo", "βλέπω": "vlepo", "κοιτάζω": "koitazo", "θωρώ": "thoro"},
     "note": "εξετάζω means to examine or scrutinize precisely; βλέπω is simply “to see,” κοιτάζω is “to look,” and θωρώ is an old-fashioned/dialectal word for “to see.”"},
    {"id": "n-el5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend a concert was amazing (casual spoken Greek)", "correct": "Ήταν φοβερό",
     "options": ["Ήταν φοβερό", "Ήταν εξαιρετικής ποιότητας", "Κρίθηκε ικανοποιητικό", "Ήταν αρκούντως αποδεκτό"],
     "romaji": {"Ήταν φοβερό": "Itan fovero", "Ήταν εξαιρετικής ποιότητας": "Itan exeretikis poiotitas", "Κρίθηκε ικανοποιητικό": "Krithike ikanopoiitiko", "Ήταν αρκούντως αποδεκτό": "Itan arkountos apodekto"},
     "note": "Φοβερό / απίστευτο are the spoken superlatives friends actually use; the others sound like a written evaluation report."},
    {"id": "n-el6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Formally requesting that a public office send you a document", "correct": "Παρακαλώ όπως μου αποσταλεί το σχετικό έγγραφο",
     "options": ["Παρακαλώ όπως μου αποσταλεί το σχετικό έγγραφο", "Στείλε το", "Στείλ' το τώρα", "Πες μου αν το 'στειλες"],
     "romaji": {"Παρακαλώ όπως μου αποσταλεί το σχετικό έγγραφο": "Parakalo opos mou apostalei to schetiko eggrafo", "Στείλε το": "Steile to", "Στείλ' το τώρα": "Steil' to tora", "Πες μου αν το 'στειλες": "Pes mou an to 'steiles"},
     "note": "The passive bureaucratic phrasing παρακαλώ όπως + subjunctive is standard official Greek; the rest are how you'd text a friend."},
    {"id": "n-el7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Softly disagreeing with your boss in a meeting", "correct": "Δεν είμαι σίγουρος αν είναι η καλύτερη επιλογή",
     "options": ["Δεν είμαι σίγουρος αν είναι η καλύτερη επιλογή", "Είναι χάλια", "Κάνετε λάθος", "Ό,τι να 'ναι"],
     "romaji": {"Δεν είμαι σίγουρος αν είναι η καλύτερη επιλογή": "Den eimai sigouros an einai i kalyteri epilogi", "Είναι χάλια": "Einai chalia", "Κάνετε λάθος": "Kanete lathos", "Ό,τι να 'ναι": "O,ti na 'nai"},
     "note": "The hedge δεν είμαι σίγουρος αν softens the disagreement into something safe to say to a boss; the others are blunt or dismissive."},
    {"id": "n-el8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Sarcastically reacting to yet another delay you saw coming", "correct": "Τι έκπληξη...",
     "options": ["Τι έκπληξη...", "Τι ωραία έκπληξη!", "Ευχαριστώ πολύ", "Χαίρομαι πολύ"],
     "romaji": {"Τι έκπληξη...": "Ti ekplixi...", "Τι ωραία έκπληξη!": "Ti oraia ekplixi!", "Ευχαριστώ πολύ": "Efcharisto poly", "Χαίρομαι πολύ": "Chairomai poly"},
     "note": "A flat, deadpan “τι έκπληξη...” (what a surprise...) is the standard sarcastic groan; the exclamation-marked and grateful versions read as sincere."},
]
