# -*- coding: utf-8 -*-
# Diaithìris, the tongue of Diaithìr: the six shared crew stories, paragraph for paragraph with stories_src.py.
LANG = 'gr'
STORIES = {
    'st-b1-01': {
        'title': 'An Carbadiarainn Anmoch',
        'paras': [
            "Thàinig an Rosetta gu tìr faisc air bailemargaidh beag. Dh'fhàg Ana agus Marco an long gus tadhal air an ionadfeithimh. Bha iad airson bileaganturais a cheannach dhan chathair.",
            "Aig an ionadfeithimh, bha mòran dhaoine a' feitheamh air an àrdùrlar. Thuirt boireannach riutha gun robh an carbadiarainn anmoch. \"Tha duilgheadas ann leis an tsligheiarainn,\" thuirt i.",
            "Choimhead Ana air a' ghleoc. Bha e mu thràth deich uairean, agus bha còir aig a' charbadiarainn aca falbh aig lethuair an dèidh naoi. Shuidh Marco sìos air being agus dh'osnaich e.",
            "Dh'fhoscail fear a bha rin taobh a phoca agus thug e amach aran. Thairg e pìos dhaibh le chèile. \"Faodaidh sibh feitheamh anseo còmhla rium,\" thuirt e le fiamhghàire.",
            "Bhruidhinn iad ris an duine mu a theaghlach agus mun obair aige. Bha e ag obair aig a' mhargadh, agus reiceadh e glasraich a huile latha. Dh'innis Ana dha mun Rosetta agus mun turas aca.",
            "Mu dheireadh, às dèidh uair a thìde, ràinig an carbadiarainn. Sheas a huile duine gu luath agus choisich iad a dh'ionnsaigh nan dorsan. Thug Ana agus Marco taing don duine airson an arain.",
            "Air a' charbadiarainn, choimhead Ana amach air an uinneig air na hachaidhean. Bha i toilichte gun do choinnich iad ri coigreach càirdeil. Thuirt Marco gun toir carbadiarainn anmoch iongnadh math leis uaireannan.",
        ],
    },
    'st-b1-02': {
        'title': 'Dìnnear le Teaghlach Yuki',
        'paras': [
            "Thadhail scioba na Rosetta air clachan sàmhach airson beagan làithean. Thug Yuki cuireadh do Sam dìnnear a ghabhail còmhla ri a teaghlach. Bha Sam nearbhasach, oir cha robh e eòlach orra gu math.",
            "Dh'fhoscail màthair Yuki an doras agus rinn i fiamhghàire gu blàth. \"Fàilte ort,\" thuirt i. \"Tha sinn toilichte gun tàinig thu.\" Bha fàileadh brota agus arain ùir air feadh an taighe.",
            "Aig a' bhòrd, chuir athair Yuki mòran cheistean air Sam mun Rosetta. Mhìnich Sam gun robh an long a' tadhal air mòran bhailtean agus a' cuideachadh dhaoine. Bha bràthair beag Yuki ag èisteachd agus a shùilean mòra foscailte.",
            "Dh'ith iad brot, rus agus glasraich còmhla. Dh'fheuch Sam mias ùr nach robh e air ithe ariamh roimhe. Chòrd i ris gu mòr, agus dh'iarr e tuilleadh.",
            "Às dèidh na dìnnearach, thug màthair Yuki amach cèic mar mhilsean. Thuirt i gur e reasabaidh sònraichte a bh' ann bho a màthair fhèin. Fhuair a huile duine pìos mòr, agus bhruidhinn iad mu sheann sceulachdan.",
            "Thug Sam taing don teaghlach airson an fheascair mhìorbhailich. Thuirt e gun robh e marthà a' faireachdainn mar bhall den teaghlach. Rug athair Yuki air làimh air, agus thug e cuireadh dha tilleadh a dh'aithghearr.",
            "A' coiseachd air ais chun na luinge, dh'innis Sam do Yuki gun do chòrd am biadh ris gu mòr. Thuirt e gu bheil teaghlaichean coltach ri chèile anns gach àite: blàth agus fialaidh. Rinn Yuki fiamhghàire, agus dh'aontaich i leis.",
        ],
    },
    'st-b2-01': {
        'title': 'An tAgallamh',
        'paras': [
            "Mura biodh an Rosetta feumach air càradh, cha bhiodh Marco ariamh air fuireach fada gu leòr anns a' bhailechala gus cur asteach airson obair ann. Bha e air sanas fhaicinn a bha ag ràdh gun robh gobharotha a dhìth air bùthobrach, agus chuir e roimhe a fhortan fheuchainn. Bha e fiosrach mu mar a dh'fhuascladh daoine air tìr duilgheadasan gun innealan adhartach na luinge.",
            "Dh'fhaighnich an neachagallaimh, boireannach àrd air an robh Ana, carson a bha e ag iarraidh na hobrach. Mhìnich Marco gun robh e air bliadhnaichean a chur seachad a' càradh innealan ann an suidheachaidhean doirbh, gu tric le glè bheag de phàirtean. Thuirt e cuideachd gum b' fheàrr leis rian ùr ionnsachadh gu ceart na leigeil air gun robh fios aige air a huile càil mu thràth.",
            "Bha e coltach gun robh deagh bheachd aig Ana air, ged a thuirt i gun robh uidheam na bùthaobrach fada na bu shine na rud sam bith ris an robh e cleachdte. \"Nan obraicheadh tu anseo,\" thuirt i, \"dh'fheumadh tu cuid de na hàbhaistean agad a leigeil seachad.\" Dh'aidich Marco gun iarradh freagarrachadh foighidinn, ach bha e deònach feuchainn.",
            "An uair sin dh'fhaighnich i dè a dhèanadh e nam biodh briseadh sìos air inneal ann am meadhan obrach, gun phàirtean ùra rim faighinn. Smaoinich Marco airson mionaid, agus thuirt e gun dèanadh e a' chùis le stuth sam bith a bhiodh ri làimh, dìreach mar a rinn e air bòrd na luinge ann an stoirm anuiridh. Chrom Ana a ceann gu slaodach, 's i gu follaiseach a' cnuasachadh a fhreagairt.",
            "Faisc air deireadh an agallaimh, dh'fhaighnich Ana am b' urrainn dha gealltainn gum fuiricheadh e fiù 's às dèidh don Rosetta falbh mu dheireadh. Rinn Marco sòradh, ag aideachadh nach robh e cinnteach dè cho fada 's a dh'fhuiricheadh e sa bhaile. Bha e den bheachd gun robh onarachd na bu chudromaiche na bhith ag innse dhi na bha i airson a chluinntinn.",
            "Thug Ana taing dha airson na foscarrachd aige, agus thuirt i gum bruidhneadh i ri a compàirtichean mus dèanadh i codhùnadh. Thuirt i gun robh a' mhòrchuid de thagraichean ag àibheiseachadh an eòlais, agus gun do sheas an dòigh dhìreach aige amach. Dh'fhàg Marco a' bhùthobrach gun fhios aige an do neartaich no an do lagaich e a chothrom.",
            "Beagan làithean às dèidh sin, thàinig teachdaireachd a' toirt cuireadh dha tilleadh airson seachdain dheuchainn. Thuig Marco gur e an onarachd aige, seach a scil cheàrdail amhàin, a thug orra cothrom a ghabhail air. Bha e a' faighneachd dha fhèin am feumadh e taghadh, aig a' cheann thall, eadar a' bhùthobrach agus na rionnagan.",
        ],
    },
    'st-b2-02': {
        'title': 'An Seòmarfeithimh',
        'paras': [
            "Nuair nach rachadh am fiabhras aig Sam air falbh, mhol lighiche na luinge dha tadhal air an ospadal ionadail, oir b' urrainn don uidheam aig a' bhaile deuchainnean a dhèanamh nach b' urrainn don Rosetta. Chaidh Yuki còmhla ris, pàirt air scàth iomagain agus pàirt a chionn 's gun robh i fiosrach mu mar a bha an tospadal ag obair. Cha robh dùil aig aon seach aon aca gum biodh an seòmarfeithimh cho dòmhail.",
            "Shuidh iad eadar bodach a bha a' leughadh duilleigenaidheachd agus màthair òg a bha a' feuchainn ri a leanabh, a bha a' caoineadh, a shocrachadh. Nam biodh fios air a bhith aig Yuki gum maireadh am feitheamh cho fada, bhiodh i air rudeigin a thoirt leatha ri leughadh. An àite sin, choimhead i air a' ghleoc agus dh'èist i ris na còmhraidhean ìosal mun cuairt oirre.",
            "Às dèidh faisc air dà uair a thìde, ghairm banaltram ainm Sam agus threòraich i e gu seòmarscrùdaidh. Thairg Yuki a dhol còmhla ris, ach mhìnich a' bhanaltram nach robh cead ach aig aon neach a dhol asteach, mar as àbhaist. Dh'fhàisc Sam a làmh gu luath mus deach e à sealladh air cùl an dorais.",
            "Na haonar san tseòmarfeithimh, thòisich Yuki air còmhradh leis a' bhodach ri a taobh. Thuirt e gun tigeadh e don ospadal gach mìos airson scrùdadhslàinte, agus gun robh an luchdobrach ancòmhnaidh coibhneil ris a dh'aindeoin cho trang 's a bha iad. Bha Yuki den bheachd gun robh an fhoighidinn aige iongantach, leis cho fada 's a b' fheudar do chàch feitheamh.",
            "Nuair a thill Sam mu dheireadh, mhìnich e nach do lorg an lighiche dad cudromach, dìreach gabhaltas a bheireadh nimhbhiastan air falbh taobh astaigh seachdain. Dh'fhairich Yuki tonn faochaidh, is cha robh i air mothachadh gun robh i ga chumail air ais. Thòisich i air tarraing às gu socair airson a leithid de dhragh a chur oirre.",
            "Nuair a bha iad a' coiseachd amach, dh'aidich Sam gun robh barrachd eagail air na leig e air, oir is ann ainneamh a bhiodh e tinn air bòrd na luinge. Thuirt Yuki gur e sin dìreach an tadhbhar a sheas i air tighinn, gus nach fheumadh e aghaidh a chur air na aonar. Thug e taing dhi, beagan tàmailteach leis cho cudromach 's a bha e dha gun robh i an làthair.",
            "Air an tslighe air ais chun na Rosetta, chaidh iad seachad air a' bhodach arithist, 's e anis a' coiseachd gu slaodach a dh'ionnsaigh stadcarbaid. Smèid Yuki, agus smèid esan air ais le fiamhghàire scìth ach fìrinneach. Thuirt Sam gun robh e coltach gun toireadh ospadalan, a dh'aindeoin gach feitheamh is iomagain, coibhneas sàmhach am follais ann an daoine.",
        ],
    },
    'st-c1-01': {
        'title': 'Easaonta san Taighcofaidh',
        'paras': [
            "Bha an taighcofaidh air fàs na àitetathaich aig scioba na Rosetta fad an ama a dh'fhuirich iad ann, le a bhùird fhiodha chaithte agus torman sìorraidh a' chòmhraidh a' tairgsinn caochladh fàilteach bho thrannsaichean fuara gun bheatha na luinge. Bha Marco agus Ana air suidhe san oisean àbhaisteach aca nuair a ghlac deasbad aig an ath bhòrd an aire. Bha dithis a bhiodh ann a huile latha a' connsachadh, le dealas follaiseach, an dèanadh riaghailtean ùra a' mhargaidh feum do cheannaichean a' bhaile no an cuireadh iad às dhaibh.",
            "Chùm fear dhiubh, reiceadair mheasan a thaobh ceàird, amach nach robh anns na riaghailtean ach oidhirp gun mhòran cleith air fàbhar a dhèanamh do reiceadairean mòra le barrachd airgid, air coscais bhothagan beaga mar an tè aige fhèin. Fhreagair an duine na aghaidh, aig an robh bùthleabhraichean bheag faisc air làimh, gun robh am margadh, gun smachd no maoirseachd, air fàs troimhachèile, le prìsean nach gabhadh earbsa asta agus reiceadairean a' reic nas saoire na chèile gus an robh e an impis tuiteam às a chèile. Cha robh coltas gun robh aon seach aon deònach òirleach a ghèilleadh.",
            "Lùb Ana, fiosrach mar a b' àbhaist, a dh'ionnsaigh Marco, agus dh'aidich i gun robh i air a scaradh eadar an dà bheachd. Thuirt Marco gun robh gearan dligheach aig an dithis, ged a bha na fuasclaidhean a bha iad a' moladh fada bho chèile. Bhuail e air nach biodh eucorach ann an connsachadh mar seo ach ainneamh; na bu trice, chuireadh e dà eagal reusanta an aghaidh a chèile.",
            "Le misneachd bhon dàrna cupa cofaidh, thog an reiceadair mheasan a ghuth, a' cur às leth na comhairle gun do ghèill i do chuideam bho cheannaichean na bu bheartaiche. Fhreagair fear na bùthaleabhraichean, 's e gu follaiseach air a leamhachadh, nach robh bunait sam bith aig a leithid de chasaidean, agus gun robh esan cuideachd ann an cunnart custamairean a chall fo riaghailtean na bu teinne. Dh'fhàs an còmhradh aca cho teth 's gun do thòisich daoine eile san taighcofaidh a' toirt sùil anull.",
            "A' mothachadh gun robh an teannas gu bhith a' goil thairis, chaidh sealbhadair an àite sa bheàrn, a' cur truinnsear bhreacagan sìos eadar an dithis le facal geurchùiseach gun rachadh argamaid na b' fheàrr air brù làn. Bhris an gluasadlàimhe sin an nàimhdeas a bha a' fàs, agus ghabh an dithis, rud beag nàireach, ris an tairgsesìthe. Bha Ana a' cagarsaich ri Marco gun robh meas aice air cho scileil 's a chiùinich an sealbhadair an suidheachadh.",
            "Aon uair 's gun do lasaich an suathadh, thionndaidh an còmhradh gu talamh coitcheann: dh'aontaich an dithis nach do rinn a' chomhairle cochomhairleachadh ri ceannaichean àbhaisteach mus do dhealbh i na riaghailtean. Bha Marco den bheachd gun robh an gluasad seo ag innse mòran, oir bha e a' sealltainn nach b' ann mun phoileasaidh fhèin a bha an timreasan cho mòr ri mu cò a gheibheadh guth ann a bhith ga chumadh. Chrom Ana a ceann, ag ràdh gur ann bho àsdùnadh, seach bho easaonta, a bhiodh gamhlas a' fàs mar bu trice.",
            "Nuair a dhealaich an dithis mu dheireadh gu suairc, bha Marco a' meòrachadh cho tric 's a bhiodh scioba na Rosetta a' ruigsinn an dùil ri sceulachdan sìmplidh air cochòrdadh no còmhstri, dìreach gus an fhìrinn a bu bhuaireasaiche a lorg: gun robh a' mhòrchuid de dh'imreasain a' fàs à eagal gun rachadh an dearmad. Dh'aontaich Ana, ag ràdh gur dòcha nach b' e breith air cò a bha ceart an rud a b' fheumaile a b' urrainn dhaibh aithris air ais don luing, ach cunntas air cho luath 's a b' urrainn don tsearbhachd leaghadh aon uair 's gun robh daoine a' faireachdainn gun deach èisteachd riutha. Dh'fhàg iad an taighcofaidh, a' coimhead air adhart mu thràth ris an ath thuras aca.",
        ],
    },
    'st-c2-01': {
        'title': 'Eadar Dà Fhalbh',
        'paras': [
            "Mun àm a bha càradh na Rosetta gu bhith deiseil, bha Sam air fàs cha mhòr measail air maighstir an ionaidfeithimh, duine tosdach air an robh Marco; mar a thuig Sam mu dheireadh, bha a ghairbhead a' ceiltinn dìlseachd àilleasach a thaobh pongalachd a bha faisc air a bhith deasghnàthach. Bha na còmhraidhean aca, a bha stobach an toiseach, air socrachadh ann am buille chofhurtail, le gach iomlaid air a fighe le seòrsa de dh'àbhachd thioram nach tig ach bho spèis dàthaobhach. B' e an cochòrdadh seo, barrachd air locht sam bith a bha fhathast anns an inneal, a bha a' toirt air Sam leisceulan a lorg airson a bhith a' màirneanachd faisc air an àrdùrlar.",
            "Air na bha gu bhith na mhadainn mu dheireadh aige sa bhaile, fhuair Sam Marco nas ciùine na b' àbhaist, a' lìomhadh gu dòigheil clàrcuimhne umha a bha a' comharrachadh stèidheachadh an ionaidfeithimh deicheadan roimhe sin. Nuair a thug Sam iomradh air an fhaireachdainn maothchridheach seo nach robh idir coltach ris, dh'aidich Marco, le aindeoin fhollaiseach, nach robh e measail air soraidhean ge b' e dè cho tric 's a dh'fheumadh e, air scàth a dhreuchd, am fulang. B' e seo, dh'aidich e, an aon taobh den obair nach robh e ariamh air e fhèin a rèiteachadh ris.",
            "Bha Sam den bheachd gun robh an eòlas aca air a chèile ro ghoirid airson foscarrachd mar sin, agus mar sin bha e gu neònach gluaiste leis an aideachadh. Thuirt e, gu faiceallach, 's dòcha nach ann bhon dealachadh fhèin a bha an anshocair a' tighinn ach bhon neochothromachd a bha na lùib: bha an neachsiubhail a' gluasad air adhart a dh'ionnsaigh annais, fhad 's a bha am fear a dh'fhanadh air a chùlaibh a' tilleadh gu gnàthchùrsa, ge b' e cho stòlda 's a bha e. Dh'aidich Marco nach robh an argamaid gun bhrìgh, ged a ghabh e beagan corraich ris a bhith air a chur sìos mar dìreach am fear a dh'fhàgadh air dheireadh.",
            "Chaidh stad a chur air a' chòmhradh aca le guthtaighe an ionaidfeithimh, a' dìoscail le brath gum biodh an carbadiarainn a tuath air dàil barrachd air ceathrad mionaid air scàth locht anns na comharran. Bha Marco gu follaiseach toilichte leis an fhaochadh, agus bha e a' dranndan gun robh e coltach gun robh an dàn air cofheall a dhèanamh gus an còmhradh a shìneadh greis eile. Rinn Sam gàire, agus mhol e gun dèanadh iad an fheum as fheàrr den eadarùine ris nach robh dùil.",
            "Theich iad gu oifis bheag an ionaidfeithimh, far an tug Marco amach poitthì a bhiodh e a' cumail, mar a dh'aidich e le beagan nàire, airson dìreach a leithid de thachartas. Thairis air an lethuair a lean, chaidh an còmhradh aca air seachran bho ghnothaichean saoghalta falbh na Rosetta gu raon a bha na bu doimhne: am b' urrainn do bheatha a chaidh a chur seachad a' coimhead às dèidh aon àite suidhichte ariamh a bhith coionann ri beatha ann an gluasad sìorraidh, no an robh gach tè dhiubh dìreach a' malairt aon seòrsa mìfhois airson seòrsa eile. Cha tuirt fear seach fear aca gun robh iad air a' cheist a fhuascladh gu tur.",
            "Nuair a thàinig an carbadiarainn a bha air dàil asteach don ionadfeithimh le dìoscan mu dheireadh, choisich Marco le Sam chun an àrdùrlair le deasghnàth a bha, gu frithbheachdach, a' dèanamh an ama na bu bhuige seach na bu chruaidhe. Shìn e amach a làmh, agus an uair sin, 's e coltach an aghaidh a thuigse fhèin, thug e fàscadh cearbach dha na àite, ag ràdh fo anail rudeigin mu dheidhinn eisceachd a dhèanamh. Dhearbh Sam dha gun robh an eisceachd dàthaobhach agus gu hiomlan dibeathte.",
            "Nuair a dh'èirich an Rosetta às an talamh nas anmoiche air an fheascar sin, bha Sam a' coimhead air ais a dh'ionnsaigh an ionaidfeithimh na b' fhaide na bha an tàm ag iarraidh, a' tionndadh facal Marco mun neochothromachd na inntinn. Bha amharas aige gun robh am bodach, na dhòigh fhaiceallach fhèin, air rudeigin a chur an cèill nach robh Sam fhèin ariamh air a chur ann am faclan: gu bheil gach falbh ag iarraidh air aon neach a' chuimhne a ghiùlan air adhart, agus a' fàgail an neach eile a' dìon an àite far an do thachair i. B' e sin, bha e a' smaoineachadh, roinn saothrach cothromach gu leòr, fhad 's nach dìochuimhnicheadh taobh seach taobh a' chuid a bh' aig an taobh eile ann.",
        ],
    },
}
