# -*- coding: utf-8 -*-
LANG = 'pl'
WORDS = {
    'c2-to-abate': ('Słabnąć (ustępować)', None),
    'c2-to-abhor': ('Brzydzić się', None),
    'c2-to-abstain': ('Wstrzymywać się (od)', None),
    'c2-to-accentuate': ('Uwydatniać', None),
    'c2-to-acquiesce': ('Przyzwalać (ulegać)', None),
    'c2-to-admonish': ('Upominać', None),
    'c2-to-alleviate': ('Łagodzić', None),
    'c2-to-amass': ('Gromadzić (zbierać)', None),
    'c2-to-appease': ('Ułagodzić (uspokoić)', None),
    'c2-to-ascribe': ('Przypisywać', None),
    'c2-to-augment': ('Powiększać (zwiększać)', None),
    'c2-to-avert': ('Zażegnywać', None),
    'c2-to-beckon': ('Przywoływać (gestem)', None),
    'c2-to-belittle': ('Umniejszać', None),
    'c2-to-bequeath': ('Zapisywać (w testamencie)', None),
    'c2-to-beseech': ('Błagać', None),
    'c2-to-bewilder': ('Dezorientować', None),
    'c2-to-brandish': ('Wymachiwać (bronią)', None),
    'c2-to-castigate': ('Karcić', None),
    'c2-to-coalesce': ('Scalać się', None),
    'c2-to-commend': ('Chwalić (polecać)', None),
    'c2-to-concede': ('Przyznawać (ustępować)', None),
    'c2-to-concoct': ('Uknuć (wymyślić)', None),
    'c2-to-confer': ('Nadawać (przyznawać)', None),
    'c2-to-contend': ('Utrzymywać (twierdzić)', None),
    'c2-to-corroborate': ('Potwierdzać', None),
    'c2-to-aggravate': ('Pogarszać', None),
    'c2-to-assail': ('Napadać (atakować)', None),
    'c2-to-chastise': ('Besztać', None),
    'c2-to-condescend': ('Raczyć (z łaski)', None),
    'c2-to-debunk': ('Obalać (mit)', None),
    'c2-to-decipher': ('Odszyfrowywać', None),
    'c2-to-decry': ('Potępiać (publicznie)', None),
    'c2-to-deem': ('Uznawać (za)', None),
    'c2-to-defer': ('Odraczać', None),
    'c2-to-delineate': ('Nakreślać', None),
    'c2-to-denounce': ('Denuncjować', None),
    'c2-to-deplete': ('Wyczerpywać', None),
    'c2-to-deride': ('Wyśmiewać', None),
    'c2-to-despair': ('Rozpaczać', None),
    'c2-to-detain': ('Zatrzymywać', None),
    'c2-to-deviate': ('Zbaczać (z kursu)', None),
    'c2-to-disdain': ('Gardzić', None),
    'c2-to-disperse': ('Rozpraszać', None),
    'c2-to-dissuade': ('Odwodzić (od czegoś)', None),
    'c2-to-divulge': ('Ujawniać', None),
    'c2-to-dwindle': ('Kurczyć się (maleć)', None),
    'c2-to-elude': ('Wymykać się', None),
    'c2-to-emanate': ('Emanować', None),
    'c2-to-embellish': ('Upiększać', None),
    'c2-to-encompass': ('Obejmować', None),
    'c2-to-engender': ('Wywoływać (rodzić)', None),
    'c2-to-enlighten': ('Oświecać', None),
    'c2-to-enthrall': ('Zniewalać (oczarowywać)', None),
    'c2-to-entice': ('Kusić (nęcić)', None),
    'c2-to-envision': ('Wyobrażać sobie (przewidywać)', None),
    'c2-to-evade': ('Uchylać się (od)', None),
    'c2-to-exalt': ('Wywyższać', None),
    'c2-to-expedite': ('Przyspieszać', None),
    'c2-to-extol': ('Wysławiać', None),
    'c2-to-fabricate': ('Fabrykować', None),
    'c2-to-falter': ('Chwiać się (wahać)', None),
    'c2-to-feign': ('Udawać', None),
    'c2-to-flourish': ('Rozkwitać (prosperować)', None),
    'c2-to-forfeit': ('Tracić (przez przepadek)', None),
    'c2-to-forgo': ('Rezygnować (z czegoś)', None),
    'c2-to-galvanize': ('Pobudzać (galwanizować)', None),
    'c2-to-garner': ('Zdobywać (zbierać uznanie)', None),
    'c2-to-gloat': ('Napawać się (cudzą porażką)', None),
    'c2-to-grapple': ('Zmagać się (z czymś)', None),
    'c2-to-harness': ('Ujarzmiać', None),
    'c2-to-heed': ('Baczyć (na)', None),
    'c2-to-hoard': ('Tezauryzować (chomikować)', None),
    'c2-to-impart': ('Przekazywać', None),
    'c2-to-implore': ('Zaklinać (błagać)', None),
    'c2-to-incite': ('Podżegać', None),
    'c2-to-inhibit': ('Hamować', None),
    'c2-to-instill': ('Wpajać', None),
    'c2-to-intercede': ('Wstawiać się (za kimś)', None),
    'c2-to-intimidate': ('Zastraszać', None),
    'c2-to-jeopardize': ('Narażać (na niebezpieczeństwo)', None),
    'c2-to-languish': ('Marnieć', None),
    'c2-to-lure': ('Wabić', None),
    'c2-to-marvel': ('Zachwycać się (dziwić się)', None),
    'c2-to-meander': ('Wić się (o rzece)', None),
    'c2-to-muster': ('Zbierać (siły, odwagę)', None),
    'c2-to-obliterate': ('Unicestwiać', None),
    'c2-to-oscillate': ('Oscylować', None),
    'c2-to-ostracize': ('Wykluczać (społecznie)', None),
    'c2-to-perpetuate': ('Utrwalać', None),
    'c2-to-permeate': ('Przenikać', None),
    'c2-to-plummet': ('Spadać (gwałtownie)', None),
    'c2-to-ponder': ('Rozważać', None),
    'c2-to-preach': ('Głosić kazania', None),
    'c2-to-procure': ('Pozyskiwać', None),
    'c2-to-proliferate': ('Rozprzestrzeniać się (mnożyć się)', None),
    'c2-to-propel': ('Napędzać', None),
    'c2-to-quell': ('Tłumić', None),
    'c2-to-ratify': ('Ratyfikować', None),
    'c2-to-rebuke': ('Ganić', None),
    'c2-to-rebut': ('Odpierać (zarzuty)', None),
    'c2-to-recant': ('Odwoływać (swoje słowa)', None),
    'c2-to-redeem': ('Odkupywać (wykupywać)', None),
    'c2-to-refute': ('Zbijać (argumenty)', None),
    'c2-to-relish': ('Rozkoszować się', None),
    'c2-to-renounce': ('Wyrzekać się', None),
    'c2-to-replenish': ('Uzupełniać', None),
    'c2-to-reprimand': ('Udzielać nagany', None),
    'c2-to-repudiate': ('Wypierać się (odrzucać)', None),
    'c2-to-resonate': ('Rezonować', None),
    'c2-to-retaliate': ('Brać odwet', None),
    'c2-to-revere': ('Czcić', None),
    'c2-to-revoke': ('Cofać (unieważniać)', None),
    'c2-to-saturate': ('Nasycać', None),
    'c2-to-scorn': ('Pogardzać', None),
    'c2-to-squander': ('Trwonić', None),
    'c2-to-stagnate': ('Stagnować', None),
    'c2-to-stifle': ('Dławić (tłumić)', None),
    'c2-to-subside': ('Opadać (słabnąć)', None),
    'c2-to-succumb': ('Ulegać (poddawać się)', None),
    'c2-to-supplant': ('Wypierać (zastępować)', None),
    'c2-to-surmise': ('Domniemywać (przypuszczać)', None),
    'c2-to-swindle': ('Wyłudzać (oszukiwać)', None),
    'c2-to-tarnish': ('Szargać', None),
    'c2-to-thwart': ('Udaremniać', None),
    'c2-to-transcend': ('Przekraczać (wykraczać poza)', None),
    'c2-to-unravel': ('Rozplątywać', None),
    'c2-to-usurp': ('Uzurpować (sobie)', None),
    'c2-to-vanquish': ('Pokonywać (zwyciężać)', None),
    'c2-to-venerate': ('Wielbić', None),
    'c2-to-vilify': ('Zniesławiać', None),
    'c2-to-wane': ('Zanikać (maleć)', None),
    'c2-to-wield': ('Władać (czymś)', None),
    'c2-to-writhe': ('Skręcać się (z bólu)', None),
    'c2-to-yearn': ('Tęsknić (pragnąć)', None),
    'c2-to-beget': ('Płodzić (rodzić)', None),
    'c2-to-besiege': ('Oblegać', None),
    'c2-to-cajole': ('Ugłaskać (przymilać się)', None),
    'c2-to-coax': ('Namawiać (czule)', None),
    'c2-to-deplore': ('Ubolewać (nad czymś)', None),
    'c2-to-disparage': ('Deprecjonować', None),
    'c2-to-exhort': ('Nawoływać (usilnie namawiać)', None),
    'c2-to-foment': ('Podsycać (wzniecać)', None),
    'c2-to-indulge': ('Pobłażać (sobie)', None),
    'c2-to-placate': ('Udobruchać', None),
    'c2-to-preempt': ('Uprzedzać (wyprzedzać)', None),
    'c2-to-rescind': ('Uchylać (znosić)', None),
    'c2-to-stymie': ('Blokować (utrudniać)', None),
    'c2-to-vindicate': ('Uniewinniać (usprawiedliwiać)', None),
    'c2-to-evince': ('Przejawiać (ujawniać)', None),
    'c2-affable': ('Afabilny', None),
    'c2-churlish': ('Gburowaty', None),
    'c2-astute': ('Przenikliwy', None),
    'c2-audacious': ('Zuchwały', None),
    'c2-belligerent': ('Wojowniczy', None),
    'c2-sanguine': ('Ufny (optymistyczny)', None),
    'c2-brusque': ('Szorstki', None),
    'c2-callous': ('Nieczuły (bezduszny)', None),
    'c2-truculent': ('Zadziorny', None),
    'c2-capricious': ('Kapryśny', None),
    'c2-complacent': ('Samozadowolony', None),
    'c2-unflappable': ('Niewzruszony', None),
    'c2-cunning': ('Przebiegły', None),
    'c2-diffident': ('Nieśmiały (niepewny siebie)', None),
    'c2-officious': ('Nadgorliwy', None),
    'c2-docile': ('Potulny', None),
    'c2-erudite': ('Uczony (erudycyjny)', None),
    'c2-fastidious': ('Wybredny (drobiazgowy)', None),
    'c2-flippant': ('Lekceważący (niepoważny)', None),
    'c2-garrulous': ('Gadatliwy', None),
    'c2-gregarious': ('Towarzyski', None),
    'c2-haughty': ('Wyniosły', None),
    'c2-impetuous': ('Porywczy', None),
    'c2-indolent': ('Leniwy', None),
    'c2-mercurial': ('Niestały (zmiennego usposobienia)', None),
    'c2-phlegmatic': ('Flegmatyczny', None),
    'c2-obsequious': ('Służalczy', None),
    'c2-petulant': ('Grymaśny', None),
    'c2-sanctimonious': ('Świętoszkowaty', None),
    'c2-taciturn': ('Małomówny', None),
    'c2-bountiful': ('Hojny (obfity)', None),
    'c2-arduous': ('Żmudny', None),
    'c2-banal': ('Banalny', None),
    'c2-copious': ('Obfity', None),
    'c2-cumbersome': ('Nieporęczny', None),
    'c2-deft': ('Zręczny', None),
    'c2-dire': ('Straszliwy (skrajny)', None),
    'c2-ephemeral': ('Ulotny (efemeryczny)', None),
    'c2-peerless': ('Niezrównany', None),
    'c2-feeble': ('Wątły', None),
    'c2-rickety': ('Rozklekotany', None),
    'c2-formidable': ('Groźny (imponujący)', None),
    'c2-immaculate': ('Nieskazitelny', None),
    'c2-faultless': ('Bezbłędny', None),
    'c2-innocuous': ('Niegroźny (nieszkodliwy)', None),
    'c2-insidious': ('Podstępny', None),
    'c2-labyrinthine': ('Labiryntowy (zawiły)', None),
    'c2-profligate': ('Rozrzutny (rozwiązły)', None),
    'c2-perspicuous': ('Klarowny', None),
    'c2-sparse': ('Rzadki (skąpy)', None),
    'c2-infinitesimal': ('Znikomy (nieskończenie mały)', None),
    'c2-sumptuous': ('Wystawny', None),
    'c2-paltry': ('Marny (nędzny)', None),
    'c2-unblemished': ('Nieskalany', None),
    'c2-indomitable': ('Niezłomny', None),
    'c2-scant': ('Skąpy', None),
    'c2-transcendent': ('Transcendentny', None),
    'c2-tenuous': ('Nikły (wątpliwy)', None),
    'c2-unwieldy': ('Niezgrabny (trudny w obsłudze)', None),
    'c2-boundless': ('Bezgraniczny', None),
    'c2-abstruse': ('Hermetyczny (trudny do zrozumienia)', None),
    'c2-apt': ('Trafny', None),
    'c2-cogent': ('Przekonujący', None),
    'c2-contentious': ('Kontrowersyjny', None),
    'c2-deplorable': ('Godny ubolewania', None),
    'c2-dubious': ('Wątpliwy', None),
    'c2-egregious': ('Rażący', None),
    'c2-exemplary': ('Wzorowy', None),
    'c2-fallacious': ('Błędny (zwodniczy)', None),
    'c2-futile': ('Daremny', None),
    'c2-gratuitous': ('Bezpodstawny (nieuzasadniony)', None),
    'c2-illicit': ('Nielegalny', None),
    'c2-impartial': ('Bezstronny', None),
    'c2-incongruous': ('Niedopasowany (nie na miejscu)', None),
    'c2-ineffable': ('Niewysłowiony', None),
    'c2-irrefutable': ('Niepodważalny', None),
    'c2-laudable': ('Chwalebny', None),
    'c2-moot': ('Dyskusyjny (bezprzedmiotowy)', None),
    'c2-nebulous': ('Mglisty', None),
    'c2-ostensible': ('Rzekomy (pozorny)', None),
    'c2-pernicious': ('Zgubny', None),
    'c2-plausible': ('Wiarygodny (prawdopodobny)', None),
    'c2-preposterous': ('Absurdalny', None),
    'c2-salient': ('Wyróżniający się (kluczowy)', None),
    'c2-spurious': ('Nieautentyczny (fałszywy)', None),
    'c2-superfluous': ('Zbędny', None),
    'c2-tenable': ('Możliwy do obrony', None),
    'c2-untenable': ('Nie do obrony', None),
    'c2-viable': ('Wykonalny (rentowny)', None),
    'c2-wanton': ('Rozwiązły (bezpodstawny)', None),
    'c2-ailing': ('Podupadły (chorowity)', None),
    'c2-bewildered': ('Skonsternowany', None),
    'c2-desolate': ('Opustoszały', None),
    'c2-brittle': ('Kruchy', None),
    'c2-cohesive': ('Spójny', None),
    'c2-defunct': ('Martwy (nieczynny)', None),
    'c2-derelict': ('Opuszczony (zrujnowany)', None),
    'c2-ramshackle': ('Walący się (zrujnowany)', None),
    'c2-dormant': ('Uśpiony', None),
    'c2-drowsy': ('Senny', None),
    'c2-dwindling': ('Malejący', None),
    'c2-exhilarated': ('Rozentuzjazmowany', None),
    'c2-forlorn': ('Osamotniony (żałosny)', None),
    'c2-haggard': ('Wymizerowany', None),
    'c2-imminent': ('Nieuchronny (bliski)', None),
    'c2-incessant': ('Nieustanny', None),
    'c2-inert': ('Bezwładny (obojętny chemicznie)', None),
    'c2-jaded': ('Zblazowany', None),
    'c2-languid': ('Ospały', None),
    'c2-listless': ('Apatyczny', None),
    'c2-antiquated': ('Przestarzały', None),
    'c2-precarious': ('Niepewny (chwiejny)', None),
    'c2-rampant': ('Szalejący (nagminny)', None),
    'c2-fidgety': ('Niespokojny (wiercący się)', None),
    'c2-rife': ('Roiący się (od czegoś złego)', None),
    'c2-sodden': ('Przemoczony', None),
    'c2-stagnant': ('Stagnujący', None),
    'c2-susceptible': ('Podatny (na)', None),
    'c2-volatile': ('Niestabilny (lotny)', None),
    'c2-weary': ('Zmęczony (znużony)', None),
    'c2-bombastic': ('Napuszony', None),
    'c2-vernacular': ('Potoczny (miejscowy)', None),
    'c2-concise': ('Zwięzły', None),
    'c2-tortuous': ('Kręty (zawiły)', None),
    'c2-cryptic': ('Enigmatyczny', None),
    'c2-derogatory': ('Uwłaczający (pogardliwy)', None),
    'c2-didactic': ('Dydaktyczny', None),
    'c2-silver-tongued': ('Wymowny (elokwentny)', None),
    'c2-emphatic': ('Stanowczy', None),
    'c2-euphemistic': ('Eufemistyczny', None),
    'c2-facetious': ('Żartobliwy (nie na miejscu)', None),
    'c2-florid': ('Kwiecisty', None),
    'c2-glib': ('Wygadany (powierzchowny)', None),
    'c2-hyperbolic': ('Hiperboliczny', None),
    'c2-incisive': ('Bystry (trafny)', None),
    'c2-laconic': ('Lakoniczny', None),
    'c2-long-winded': ('Rozwlekły', None),
    'c2-mordant': ('Zjadliwy', None),
    'c2-ornate': ('Ozdobny', None),
    'c2-pedantic': ('Pedantyczny', None),
    'c2-pithy': ('Treściwy', None),
    'c2-plaintive': ('Rzewny', None),
    'c2-rhetorical': ('Retoryczny', None),
    'c2-sardonic': ('Sardoniczny', None),
    'c2-scathing': ('Miażdżący (bezlitosny)', None),
    'c2-succinct': ('Lapidarny', None),
    'c2-terse': ('Oschły (zwięzły)', None),
    'c2-trite': ('Wyświechtany', None),
    'c2-verbose': ('Wielosłowny', None),
    'c2-wry': ('Ironiczny (cierpki)', None),
    'c2-acumen': ('Przenikliwość (bystrość umysłu)', None),
    'c2-alacrity': ('Skwapliwość (gorliwość)', None),
    'c2-ambivalence': ('Ambiwalencja', None),
    'c2-apathy': ('Apatia', None),
    'c2-aplomb': ('Opanowanie (pewność siebie)', None),
    'c2-audacity': ('Zuchwałość', None),
    'c2-candor': ('Szczerość', None),
    'c2-smugness': ('Zadowolenie z siebie', None),
    'c2-scorn': ('Pogarda', None),
    'c2-deference': ('Uległość (respekt)', None),
    'c2-discretion': ('Dyskrecja', None),
    'c2-disdain': ('Wzgarda', None),
    'c2-forbearance': ('Wyrozumiałość (cierpliwość)', None),
    'c2-fortitude': ('Hart ducha', None),
    'c2-hubris': ('Hybris (nadmierna pycha)', None),
    'c2-meekness': ('Łagodność (potulność)', None),
    'c2-umbrage': ('Uraza (obraza)', None),
    'c2-ingenuity': ('Pomysłowość', None),
    'c2-rectitude': ('Prawość', None),
    'c2-malice': ('Złośliwość', None),
    'c2-nostalgia': ('Nostalgia', None),
    'c2-perseverance': ('Wytrwałość', None),
    'c2-prudence': ('Roztropność', None),
    'c2-grit': ('Zaciętość', None),
    'c2-reticence': ('Powściągliwość', None),
    'c2-equanimity': ('Spokój ducha (równowaga)', None),
    'c2-tenacity': ('Nieustępliwość', None),
    'c2-vanity': ('Próżność', None),
    'c2-vigilance': ('Czujność', None),
    'c2-zeal': ('Zapał', None),
    'c2-anomaly': ('Anomalia', None),
    'c2-catalyst': ('Katalizator', None),
    'c2-conundrum': ('Zagadka (dylemat)', None),
    'c2-debacle': ('Klęska (fiasko)', None),
    'c2-deluge': ('Potop (nawała)', None),
    'c2-dearth': ('Niedostatek (brak)', None),
    'c2-dichotomy': ('Dychotomia', None),
    'c2-epitome': ('Uosobienie (kwintesencja)', None),
    'c2-exodus': ('Exodus (masowa ucieczka)', None),
    'c2-facade': ('Fasada (pozór)', None),
    'c2-fallacy': ('Błąd logiczny', None),
    'c2-hindsight': ('Perspektywa czasu (mądrość po fakcie)', None),
    'c2-impasse': ('Impas', None),
    'c2-impetus': ('Impuls (bodziec)', None),
    'c2-juncture': ('Moment (punkt w czasie)', None),
    'c2-loophole': ('Luka prawna', None),
    'c2-tipping-point': ('Punkt krytyczny', None),
    'c2-onslaught': ('Nawała (szturm)', None),
    'c2-vicious-circle': ('Błędne koło', None),
    'c2-plight': ('Ciężkie położenie', None),
    'c2-precedent': ('Precedens', None),
    'c2-quandary': ('Rozterka (dylemat)', None),
    'c2-ramification': ('Konsekwencja (rozgałęzienie)', None),
    'c2-respite': ('Wytchnienie', None),
    'c2-setback': ('Niepowodzenie', None),
    'c2-stalemate': ('Pat (sytuacja bez wyjścia)', None),
    'c2-surge': ('Nagły wzrost (fala)', None),
    'c2-turmoil': ('Zamęt', None),
    'c2-upheaval': ('Wstrząs (przewrót)', None),
    'c2-watershed': ('Przełom (punkt zwrotny)', None),
    'c2-accomplice': ('Wspólnik (współsprawca)', None),
    'c2-adversary': ('Przeciwnik', None),
    'c2-advocate': ('Rzecznik (orędownik)', None),
    'c2-benefactor': ('Dobrodziej', None),
    'c2-bystander': ('Przypadkowy świadek', None),
    'c2-charlatan': ('Szarlatan', None),
    'c2-connoisseur': ('Koneser', None),
    'c2-culprit': ('Winowajca', None),
    'c2-demagogue': ('Demagog', None),
    'c2-dilettante': ('Dyletant', None),
    'c2-envoy': ('Wysłannik', None),
    'c2-lackey': ('Lokaj (sługus)', None),
    'c2-understudy': ('Dubler', None),
    'c2-hypocrite': ('Hipokryta', None),
    'c2-insurgent': ('Powstaniec (rebeliant)', None),
    'c2-layperson': ('Laik', None),
    'c2-maverick': ('Indywidualista (nonkonformista)', None),
    'c2-sidekick': ('Kompan (pomocnik)', None),
    'c2-mercenary': ('Najemnik', None),
    'c2-novice': ('Nowicjusz', None),
    'c2-pariah': ('Wyrzutek', None),
    'c2-patron': ('Mecenas', None),
    'c2-perpetrator': ('Sprawca', None),
    'c2-prodigy': ('Cudowne dziecko (geniusz)', None),
    'c2-informant': ('Informator (donosiciel)', None),
    'c2-recluse': ('Odludek', None),
    'c2-sage': ('Mędrzec', None),
    'c2-turncoat': ('Zdrajca (odstępca)', None),
    'c2-stalwart': ('Wierny zwolennik (filar)', None),
    'c2-tycoon': ('Magnat', None),
    'c2-ambiguity': ('Niejednoznaczność', None),
    'c2-analogy': ('Analogia', None),
    'c2-axiom': ('Aksjomat', None),
    'c2-caveat': ('Zastrzeżenie', None),
    'c2-consensus': ('Konsensus', None),
    'c2-corollary': ('Naturalna konsekwencja (wniosek)', None),
    'c2-yardstick': ('Miernik (kryterium)', None),
    'c2-narrative': ('Narracja', None),
    'c2-doctrine': ('Doktryna', None),
    'c2-dogma': ('Dogmat', None),
    'c2-epiphany': ('Olśnienie (nagłe zrozumienie)', None),
    'c2-ethos': ('Etos', None),
    'c2-conjecture': ('Domysł (hipoteza)', None),
    'c2-idiosyncrasy': ('Idiosynkrazja (osobliwość)', None),
    'c2-deduction': ('Dedukcja', None),
    'c2-innuendo': ('Insynuacja', None),
    'c2-buzzword': ('Modne słówko', None),
    'c2-simile': ('Porównanie (poetyckie)', None),
    'c2-nuance': ('Niuans', None),
    'c2-archetype': ('Archetyp', None),
    'c2-platitude': ('Frazes (banał)', None),
    'c2-postulate': ('Postulat', None),
    'c2-pretext': ('Pretekst', None),
    'c2-rebuttal': ('Replika (odparcie zarzutów)', None),
    'c2-rhetoric': ('Retoryka', None),
    'c2-semantics': ('Semantyka', None),
    'c2-stigma': ('Piętno', None),
    'c2-tenet': ('Zasada (dogmat)', None),
    'c2-trope': ('Motyw (schemat narracyjny)', None),
    'c2-zeitgeist': ('Duch czasu', None),
    'c2-acrid': ('Gryzący (piekący)', None),
    'c2-astringent': ('Cierpki', None),
    'c2-bland-flavorless': ('Mdły (bez smaku)', None),
    'c2-brackish': ('Słonawy', None),
    'c2-cloying': ('Mdląco słodki (przesłodzony)', None),
    'c2-coarse': ('Chropowaty (gruboziarnisty)', None),
    'c2-creamy': ('Kremowy', None),
    'c2-crunchy': ('Chrupiący', None),
    'c2-dank': ('Wilgotny i zimny (zatęchły)', None),
    'c2-earthy': ('Ziemisty', None),
    'c2-fragrant': ('Pachnący (aromatyczny)', None),
    'c2-gooey': ('Lepki (maziowaty)', None),
    'c2-grainy': ('Ziarnisty', None),
    'c2-unctuous': ('Oleisty (przesadnie uprzejmy)', None),
    'c2-gravelly-voice': ('Chrapliwy (o głosie)', None),
    'c2-luscious': ('Soczysty (rozkoszny)', None),
    'c2-mellow': ('Łagodny (aksamitny)', None),
    'c2-hushed': ('Przyciszony', None),
    'c2-musty': ('Zatęchły (stęchły)', None),
    'c2-piercing': ('Przeszywający', None),
    'c2-pungent': ('Ostry (drażniący zapach)', None),
    'c2-putrid': ('Cuchnący (zgniły)', None),
    'c2-rancid': ('Zjełczały', None),
    'c2-bitter-aftertaste': ('Gorzki posmak', None),
    'c2-grating-sound': ('Zgrzytliwy (drażniący)', None),
    'c2-silky': ('Jedwabisty', None),
    'c2-slimy': ('Śliski (oślizgły)', None),
    'c2-soggy': ('Rozmoknięty', None),
    'c2-tangy': ('Wyrazisty (kwaskowaty)', None),
    'c2-zesty': ('Pikantny (energiczny)', None),
    'c2-better-late-than-never': ('Lepiej późno niż wcale', None),
    'c2-actions-speak-louder-than-words': ('Czyny znaczą więcej niż słowa', None),
    'c2-the-early-bird-catches-the-worm': ('Kto rano wstaje, temu Pan Bóg daje', None),
    'c2-don-t-count-your-chickens-before-they-hatch': ('Nie dziel skóry na niedźwiedziu, zanim go ubijesz', None),
    'c2-every-cloud-has-a-silver-lining': ('Nie ma tego złego, co by na dobre nie wyszło', None),
    'c2-practice-makes-perfect': ('Trening czyni mistrza', None),
    'c2-when-in-rome-do-as-the-romans-do': ('Kiedy wejdziesz między wrony, musisz krakać jak i one', None),
    'c2-two-heads-are-better-than-one': ('Co dwie głowy, to nie jedna', None),
    'c2-the-grass-is-always-greener-on-the-other-side': ('Wszędzie dobrze, gdzie nas nie ma', None),
    'c2-don-t-judge-a-book-by-its-cover': ('Nie oceniaj książki po okładce', None),
    'c2-birds-of-a-feather-flock-together': ('Ciągnie swój do swego', None),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('Lepszy wróbel w garści niż gołąb na dachu', None),
    'c2-where-there-s-a-will-there-s-a-way': ('Dla chcącego nic trudnego', None),
    'c2-rome-wasn-t-built-in-a-day': ('Nie od razu Kraków zbudowano', None),
    'c2-too-many-cooks-spoil-the-broth': ('Gdzie kucharek sześć, tam nie ma co jeść', None),
    'c2-out-of-sight-out-of-mind': ('Co z oczu, to z serca', None),
    'c2-look-before-you-leap': ('Patrz, zanim skoczysz', None),
    'c2-necessity-is-the-mother-of-invention': ('Potrzeba jest matką wynalazków', None),
    'c2-you-can-t-have-your-cake-and-eat-it-too': ('Nie można zjeść ciastka i jednocześnie je mieć', None),
    'c2-honesty-is-the-best-policy': ('Uczciwość popłaca', None),
    'c2-still-waters-run-deep': ('Cicha woda brzegi rwie', None),
    'c2-blood-is-thicker-than-water': ('Krew nie woda', None),
    'c2-absence-makes-the-heart-grow-fonder': ('Rozłąka umacnia uczucia', None),
    'c2-every-dog-has-its-day': ('Będzie i na naszej ulicy święto', None),
    'c2-haste-makes-waste': ('Co nagle, to po diable', None),
    'c2-let-sleeping-dogs-lie': ('Nie budź licha, gdy licho śpi', None),
    'c2-strike-while-the-iron-is-hot': ('Kuj żelazo, póki gorące', None),
    'c2-the-pen-is-mightier-than-the-sword': ('Pióro potężniejsze niż miecz', None),
    'c2-curiosity-killed-the-cat': ('Ciekawość to pierwszy stopień do piekła', None),
    'c2-beggars-can-t-be-choosers': ('Darowanemu koniowi nie zagląda się w zęby', None),
    'c2-to-draw-a-distinction': ('Dokonywać rozróżnienia', None),
    'c2-to-reach-a-verdict': ('Wydawać werdykt', None),
    'c2-to-pose-a-threat': ('Stanowić zagrożenie', None),
    'c2-to-bear-the-brunt': ('Ponosić główny ciężar', None),
    'c2-to-lend-credence-to': ('Nadawać wiarygodność', None),
    'c2-to-wield-influence': ('Wywierać wpływ', None),
    'c2-to-incur-a-cost': ('Ponosić koszt', None),
    'c2-to-uphold-a-principle': ('Podtrzymywać zasadę', None),
    'c2-to-exert-pressure': ('Wywierać nacisk', None),
    'c2-to-fulfil-an-obligation': ('Wypełniać zobowiązanie', None),
    'c2-to-cast-doubt-on': ('Podawać w wątpliwość', None),
    'c2-to-pay-tribute-to': ('Składać hołd', None),
    'c2-to-take-precedence-over': ('Mieć pierwszeństwo przed', None),
    'c2-to-run-the-risk-of': ('Ryzykować (że)', None),
    'c2-to-strike-a-balance': ('Znajdować równowagę', None),
    'c2-to-come-to-fruition': ('Dochodzić do skutku (ziścić się)', None),
    'c2-to-shed-light-on': ('Rzucać światło na', None),
    'c2-to-set-a-precedent': ('Ustanawiać precedens', None),
    'c2-to-give-rise-to': ('Dawać początek (czemuś)', None),
    'c2-to-take-issue-with': ('Nie zgadzać się (z czymś)', None),
    'c2-pursuant-to': ('Na mocy (zgodnie z)', None),
    'c2-heretofore': ('Dotychczas (dotąd)', None),
    'c2-inasmuch-as': ('O tyle, o ile (ponieważ)', None),
    'c2-in-conjunction-with': ('W połączeniu z', None),
    'c2-hitherto': ('Jak dotąd', None),
    'c2-forthwith': ('Niezwłocznie', None),
    'c2-whilst': ('Podczas gdy', None),
    'c2-wherein': ('W którym (gdzie)', None),
    'c2-vis-a-vis': ('W odniesieniu do (wobec)', None),
    'c2-as-regards': ('Jeśli chodzi o', None),
    'c2-for-the-sake-of-argument': ('Załóżmy, że (czysto hipotetycznie)', None),
    'c2-be-that-as-it-may': ('Jakkolwiek by nie było', None),
    'c2-on-balance': ('Biorąc wszystko pod uwagę', None),
    'c2-at-the-behest-of': ('Na polecenie (czyjeś)', None),
    'c2-in-the-wake-of': ('W następstwie', None),
    'c2-on-the-grounds-that': ('Na tej podstawie, że', None),
    'c2-in-accordance-with': ('Zgodnie z', None),
    'c2-pending': ('W oczekiwaniu na', None),
    'c2-irrespective-of': ('Niezależnie od', None),
    'c2-hereinafter': ('Zwany dalej (odtąd)', None),
    'c2-beats-me': ('Nie mam pojęcia', None),
    'c2-point-taken': ('Punkt dla ciebie (racja)', None),
    'c2-suit-yourself': ('Jak chcesz', None),
    'c2-go-figure': ('Idź to zrozum', None),
    'c2-don-t-get-me-started': ('Nie zaczynaj mnie na ten temat', None),
    'c2-bottom-line-is': ('Krótko mówiąc', None),
    'c2-off-the-top-of-my-head': ('Z głowy (bez zastanowienia)', None),
    'c2-i-ll-say': ('No pewnie', None),
    'c2-you-ve-got-to-be-kidding-me': ('Chyba żartujesz', None),
    'c2-no-offense-but': ('Bez obrazy, ale', None),
    'c2-i-m-not-gonna-lie': ('Nie będę kłamać', None),
    'c2-speak-of-the-devil': ('O wilku mowa', None),
    'c2-it-s-on-the-tip-of-my-tongue': ('Mam to na końcu języka', None),
    'c2-let-s-call-it-a-day': ('Zakończmy na dziś', None),
    'c2-it-s-not-rocket-science': ('To nie jest żadna filozofia', None),
    'c2-that-s-the-last-straw': ('To już ostatnia kropla', None),
    'c2-i-couldn-t-care-less': ('Mam to gdzieś', None),
    'c2-what-are-the-odds': ('Co za zbieg okoliczności', None),
    'c2-say-no-more': ('Nie musisz nic więcej mówić', None),
    'c2-hang-in-there': ('Trzymaj się', None),
    'c2-i-m-all-ears': ('Zamieniam się w słuch', None),
    'c2-that-s-on-me': ('To moja wina', None),
    'c2-no-hard-feelings': ('Bez urazy', None),
    'c2-ditto': ('To samo (ja też)', None),
    'c2-spill-the-beans': ('Wygadać sekret', None),
    'c2-in-one-ear-and-out-the-other': ('Jednym uchem wpada, drugim wypada', None),
    'c2-cut-to-the-chase': ('Przejdź do rzeczy', None),
    'c2-you-name-it': ('Cokolwiek zechcesz', None),
    'c2-not-in-a-million-years': ('Nigdy w życiu', None),
    'c2-it-is-what-it-is': ('Cóż, tak już jest', None),
    'c2-give-me-a-break': ('Daj spokój', None),
    'c2-hold-your-horses': ('Przyhamuj (nie tak szybko)', None),
    'c2-bite-the-bullet': ('Zacisnąć zęby', None),
    'c2-take-it-with-a-grain-of-salt': ('Traktować z przymrużeniem oka (z rezerwą)', None),
    'c2-better-safe-than-sorry': ('Lepiej dmuchać na zimne', None),
    'c2-let-s-play-it-by-ear': ('Zobaczymy, jak pójdzie', None),
    'c2-i-ll-take-a-rain-check': ('Innym razem', None),
    'c2-for-what-it-s-worth': ('Tak na marginesie', None),
    'c2-back-to-square-one': ('Powrót do punktu wyjścia', None),
    'c2-touch-wood': ('Odpukać w niemalowane', None),
    'c2-allusion': ('Aluzja', None),
    'c2-anecdote': ('Anegdota', None),
    'c2-antithesis': ('Antyteza', None),
    'c2-aphorism': ('Aforyzm', None),
    'c2-banter': ('Przekomarzanie się', None),
    'c2-circumlocution': ('Peryfraza (omówienie)', None),
    'c2-cliche': ('Komunał (oklepany zwrot)', None),
    'c2-connotation': ('Konotacja', None),
    'c2-digression': ('Dygresja', None),
    'c2-double-entendre': ('Dwuznaczność (aluzja)', None),
    'c2-eloquence': ('Elokwencja', None),
    'c2-euphemism': ('Eufemizm', None),
    'c2-gist': ('Sedno (esencja)', None),
    'c2-hyperbole': ('Hiperbola', None),
    'c2-irony': ('Ironia', None),
    'c2-juxtaposition': ('Zestawienie (kontrast)', None),
    'c2-malapropism': ('Malapropizm (przejęzyczenie)', None),
    'c2-oxymoron': ('Oksymoron', None),
    'c2-paraphrase': ('Parafraza', None),
    'c2-pun': ('Kalambur', None),
    'c2-quip': ('Docinek (błyskotliwa uwaga)', None),
    'c2-sarcasm': ('Sarkazm', None),
    'c2-slur-insult': ('Obelga', None),
    'c2-repartee': ('Cięta riposta', None),
    'c2-soliloquy': ('Monolog (wewnętrzny)', None),
    'c2-subtext': ('Podtekst', None),
    'c2-tangent': ('Zboczenie z tematu', None),
    'c2-tirade': ('Tyrada', None),
    'c2-understatement': ('Niedopowiedzenie (eufemizm zaniżający)', None),
    'c2-verbiage': ('Wielosłowie (rozwlekłość)', None),
    'c2-to-allude-to': ('Nawiązywać (do czegoś)', None),
    'c2-to-enunciate': ('Wymawiać wyraźnie (artykułować)', None),
    'c2-to-belabor-the-point': ('Rozwodzić się (nad czymś)', None),
    'c2-to-digress': ('Dygresować (zbaczać od tematu)', None),
    'c2-to-expound': ('Wykładać (szczegółowo objaśniać)', None),
    'c2-to-insinuate': ('Insynuować', None),
    'c2-to-interject': ('Wtrącać się', None),
    'c2-to-hammer-home': ('Wbijać do głowy (mocno podkreślać)', None),
    'c2-to-retort': ('Ripostować', None),
    'c2-to-waffle-be-vague': ('Owijać w bawełnę', None),
    'c2-actuary': ('Aktuariusz', None),
    'c2-anesthesiologist': ('Anestezjolog', None),
    'c2-archivist': ('Archiwista', None),
    'c2-auditor': ('Audytor', None),
    'c2-bailiff': ('Komornik', None),
    'c2-blacksmith': ('Kowal', None),
    'c2-cartographer': ('Kartograf', None),
    'c2-chiropractor': ('Kręgarz (chiropraktyk)', None),
    'c2-coroner': ('Koroner (lekarz sądowy)', None),
    'c2-curator': ('Kurator (muzealny)', None),
    'c2-diplomat': ('Dyplomata', None),
    'c2-dietitian': ('Dietetyk', None),
    'c2-entomologist': ('Entomolog', None),
    'c2-forensic-scientist': ('Ekspert kryminalistyki', None),
    'c2-geologist': ('Geolog', None),
    'c2-glazier': ('Szklarz', None),
    'c2-interpreter-simultaneous': ('Tłumacz (symultaniczny)', None),
    'c2-locksmith': ('Ślusarz', None),
    'c2-midwife': ('Położna', None),
    'c2-court-clerk': ('Protokolant sądowy', None),
    'c2-oncologist': ('Onkolog', None),
    'c2-ophthalmologist': ('Okulista', None),
    'c2-paleontologist': ('Paleontolog', None),
    'c2-paralegal': ('Asystent prawny', None),
    'c2-pathologist': ('Patolog', None),
    'c2-physiotherapist': ('Fizjoterapeuta', None),
    'c2-public-defender': ('Obrońca z urzędu', None),
    'c2-radiologist': ('Radiolog', None),
    'c2-perfumer': ('Perfumiarz', None),
    'c2-stenographer': ('Stenograf', None),
    'c2-surveyor': ('Geodeta', None),
    'c2-taxidermist': ('Taksydermista', None),
    'c2-upholsterer': ('Tapicer', None),
    'c2-veterinarian-specialist': ('Weterynarz (specjalista)', None),
    'c2-welder': ('Spawacz', None),
    'c2-anthropology': ('Antropologia', None),
    'c2-archaeology': ('Archeologia', None),
    'c2-astrophysics': ('Astrofizyka', None),
    'c2-biochemistry': ('Biochemia', None),
    'c2-botany': ('Botanika', None),
    'c2-cartography': ('Kartografia', None),
    'c2-criminology': ('Kryminologia', None),
    'c2-demography': ('Demografia', None),
    'c2-econometrics': ('Ekonometria', None),
    'c2-epidemiology': ('Epidemiologia', None),
    'c2-epistemology': ('Epistemologia', None),
    'c2-ethnography': ('Etnografia', None),
    'c2-genetics': ('Genetyka', None),
    'c2-geopolitics': ('Geopolityka', None),
    'c2-hermeneutics': ('Hermeneutyka', None),
    'c2-immunology': ('Immunologia', None),
    'c2-jurisprudence': ('Jurysprudencja (teoria prawa)', None),
    'c2-linguistics': ('Językoznawstwo', None),
    'c2-metaphysics': ('Metafizyka', None),
    'c2-meteorology': ('Meteorologia', None),
    'c2-microbiology': ('Mikrobiologia', None),
    'c2-musicology': ('Muzykologia', None),
    'c2-neuroscience': ('Neuronauka', None),
    'c2-oceanography': ('Oceanografia', None),
    'c2-ornithology': ('Ornitologia', None),
    'c2-pedagogy': ('Pedagogika', None),
    'c2-pharmacology': ('Farmakologia', None),
    'c2-philology': ('Filologia', None),
    'c2-phonetics': ('Fonetyka', None),
    'c2-seismology': ('Sejsmologia', None),
    'c2-semiotics': ('Semiotyka', None),
    'c2-sociolinguistics': ('Socjolingwistyka', None),
    'c2-theology': ('Teologia', None),
    'c2-toxicology': ('Toksykologia', None),
    'c2-zoology': ('Zoologia', None),
    'c2-acute-sudden-severe': ('Ostry', None),
    'c2-latent': ('Utajony', None),
    'c2-benign': ('Łagodny (niezłośliwy)', None),
    'c2-malignant': ('Złośliwy', None),
    'c2-biopsy': ('Biopsja', None),
    'c2-prognosis': ('Rokowanie', None),
    'c2-flare-up': ('Zaostrzenie (nawrót)', None),
    'c2-recurrence': ('Nawrót', None),
    'c2-sedative': ('Środek uspokajający', None),
    'c2-anesthetic': ('Środek znieczulający', None),
    'c2-antibody': ('Przeciwciało', None),
    'c2-inflammation': ('Zapalenie', None),
    'c2-airborne': ('Przenoszony drogą powietrzną', None),
    'c2-hereditary': ('Dziedziczny', None),
    'c2-congenital': ('Wrodzony', None),
    'c2-dosage': ('Dawkowanie', None),
    'c2-placebo': ('Placebo', None),
    'c2-contraindication': ('Przeciwwskazanie', None),
    'c2-intravenous': ('Dożylny', None),
    'c2-suture': ('Szew (chirurgiczny)', None),
    'c2-incision': ('Nacięcie', None),
    'c2-donor': ('Dawca', None),
    'c2-ultrasound': ('USG (ultrasonografia)', None),
    'c2-referral-to-a-specialist': ('Skierowanie (do specjalisty)', None),
    'c2-inpatient': ('Pacjent hospitalizowany', None),
    'c2-palliative-care': ('Opieka paliatywna', None),
    'c2-triage': ('Triaż (segregacja medyczna)', None),
    'c2-convalescence': ('Rekonwalescencja', None),
    'c2-immunity': ('Odporność', None),
    'c2-pandemic': ('Pandemia', None),
    'c2-pathogen': ('Patogen', None),
    'c2-electrolyte': ('Elektrolit', None),
    'c2-cardiovascular': ('Sercowo-naczyniowy', None),
    'c2-respiratory': ('Oddechowy', None),
    'c2-neurological': ('Neurologiczny', None),
    'c2-symptomatic': ('Objawowy', None),
    'c2-asymptomatic': ('Bezobjawowy', None),
    'c2-prescription-written-order': ('Recepta', None),
    'c2-generic-drug': ('Lek generyczny', None),
    'c2-informed-consent': ('Świadoma zgoda', None),
    'c2-acquittal': ('Uniewinnienie', None),
    'c2-conviction-guilty-verdict': ('Wyrok skazujący', None),
    'c2-deposition': ('Zeznanie (pod przysięgą)', None),
    'c2-accessory-to-a-crime': ('Współsprawca (pomocnik)', None),
    'c2-arson': ('Podpalenie', None),
    'c2-remand': ('Areszt tymczasowy', None),
    'c2-burden-of-proof': ('Ciężar dowodu', None),
    'c2-custody-detention': ('Zatrzymanie (areszt)', None),
    'c2-defendant': ('Oskarżony (pozwany)', None),
    'c2-plaintiff': ('Powód (skarżący)', None),
    'c2-embezzlement': ('Sprzeniewierzenie', None),
    'c2-extortion': ('Wymuszenie', None),
    'c2-felony': ('Zbrodnia (poważne przestępstwo)', None),
    'c2-misdemeanor': ('Wykroczenie', None),
    'c2-forgery': ('Fałszerstwo', None),
    'c2-hearsay': ('Zeznanie ze słyszenia (plotka)', None),
    'c2-indictment': ('Akt oskarżenia', None),
    'c2-injunction': ('Zakaz sądowy (nakaz sądowy)', None),
    'c2-tribunal': ('Trybunał', None),
    'c2-libel': ('Zniesławienie (pisemne)', None),
    'c2-slander': ('Pomówienie (ustne)', None),
    'c2-manslaughter': ('Zabójstwo nieumyślne', None),
    'c2-parole': ('Zwolnienie warunkowe', None),
    'c2-perjury': ('Krzywoprzysięstwo', None),
    'c2-plea-bargain': ('Ugoda z prokuraturą', None),
    'c2-probation': ('Dozór kuratorski (zawieszenie kary)', None),
    'c2-racketeering': ('Wymuszanie haraczy (zorganizowana przestępczość)', None),
    'c2-ransom': ('Okup', None),
    'c2-statute': ('Ustawa', None),
    'c2-statute-of-limitations': ('Przedawnienie', None),
    'c2-subpoena': ('Wezwanie sądowe', None),
    'c2-testimony': ('Zeznanie', None),
    'c2-ruling': ('Orzeczenie', None),
    'c2-warrant': ('Nakaz (sądowy)', None),
    'c2-witness-stand': ('Ława dla świadków', None),
    'c2-contempt-of-court': ('Obraza sądu', None),
    'c2-cross-examination': ('Przesłuchanie krzyżowe', None),
    'c2-mistrial': ('Unieważnienie procesu', None),
    'c2-sentence-punishment': ('Wyrok (kara)', None),
    'c2-to-plead-guilty': ('Przyznawać się do winy', None),
    'c2-thicket': ('Gąszcz (zarośla)', None),
    'c2-undergrowth': ('Podszyt (poszycie leśne)', None),
    'c2-moss': ('Mech', None),
    'c2-lichen': ('Porost', None),
    'c2-fern': ('Paproć', None),
    'c2-sap': ('Sok (drzewny)', None),
    'c2-bark-of-a-tree': ('Kora', None),
    'c2-sapling': ('Sadzonka (młode drzewko)', None),
    'c2-canopy-forest': ('Korona lasu (baldachim)', None),
    'c2-grove': ('Gaj', None),
    'c2-meadow': ('Łąka', None),
    'c2-marsh': ('Bagno (mokradło)', None),
    'c2-bog': ('Trzęsawisko (torfowisko)', None),
    'c2-estuary': ('Ujście rzeki (estuarium)', None),
    'c2-tributary': ('Dopływ', None),
    'c2-ravine': ('Wąwóz', None),
    'c2-gorge': ('Gardziel (kanion)', None),
    'c2-ridge': ('Grzbiet (górski)', None),
    'c2-summit': ('Szczyt', None),
    'c2-foothills': ('Podnóże gór', None),
    'c2-escarpment': ('Skarpa', None),
    'c2-salt-flat': ('Solnisko (płaskowyż solny)', None),
    'c2-cove': ('Zatoczka', None),
    'c2-atoll': ('Atol', None),
    'c2-tide-pool': ('Basen pływowy', None),
    'c2-driftwood': ('Drewno wyrzucone przez wodę', None),
    'c2-pebble': ('Kamyk', None),
    'c2-boulder': ('Głaz', None),
    'c2-sediment': ('Osad', None),
    'c2-erosion': ('Erozja', None),
    'c2-burrow': ('Nora', None),
    'c2-hive': ('Ul', None),
    'c2-cocoon': ('Kokon', None),
    'c2-antler': ('Poroże', None),
    'c2-talon': ('Szpon', None),
    'c2-plumage': ('Upierzenie', None),
    'c2-migration-animal': ('Migracja (zwierząt)', None),
    'c2-hibernation': ('Hibernacja', None),
    'c2-pollination': ('Zapylanie', None),
    'c2-germination': ('Kiełkowanie', None),
    'c2-torrential': ('Ulewny', None),
    'c2-monsoon': ('Monsun', None),
    'c2-sleet': ('Deszcz ze śniegiem', None),
    'c2-flurry-snow': ('Śnieżyca przelotna', None),
    'c2-whiteout': ('Biała mgła (zerowa widoczność)', None),
    'c2-black-ice': ('Gołoledź', None),
    'c2-dew': ('Rosa', None),
    'c2-haze': ('Mgiełka (zamglenie)', None),
    'c2-clammy': ('Wilgotny i lepki', None),
    'c2-scorcher': ('Skwarny dzień', None),
    'c2-sultry': ('Duszny', None),
    'c2-balmy': ('Łagodny (o pogodzie)', None),
    'c2-crisp-air': ('Rześki', None),
    'c2-gust': ('Podmuch', None),
    'c2-gale': ('Wichura', None),
    'c2-squall': ('Nawałnica (szkwał)', None),
    'c2-thunderclap': ('Grzmot', None),
    'c2-lightning-bolt': ('Błyskawica (piorun)', None),
    'c2-cloudburst': ('Oberwanie chmury', None),
    'c2-nightfall': ('Zapadnięcie nocy', None),
    'c2-cold-snap': ('Fala mrozów', None),
    'c2-thaw': ('Odwilż', None),
    'c2-humidity': ('Wilgotność', None),
    'c2-barometer': ('Barometr', None),
    'c2-forecast-verb': ('Prognozować', None),
    'c2-daybreak': ('Świt', None),
    'c2-aurora': ('Zorza (polarna)', None),
    'c2-twilight': ('Zmierzch (półmrok)', None),
    'c2-solstice': ('Przesilenie', None),
    'c2-equinox': ('Równonoc', None),
    'c2-arch': ('Łuk', None),
    'c2-vault-ceiling': ('Sklepienie', None),
    'c2-dome': ('Kopuła', None),
    'c2-spire': ('Iglica', None),
    'c2-buttress': ('Przypora', None),
    'c2-pillar': ('Filar', None),
    'c2-column': ('Kolumna', None),
    'c2-beam-structural': ('Belka', None),
    'c2-rafter': ('Krokiew', None),
    'c2-girder': ('Dźwigar', None),
    'c2-keystone': ('Zwornik', None),
    'c2-facade-building-front': ('Elewacja (fasada budynku)', None),
    'c2-cornice': ('Gzyms', None),
    'c2-gable': ('Naczółek', None),
    'c2-eaves': ('Okap', None),
    'c2-gutter-roof': ('Rynna', None),
    'c2-skylight': ('Świetlik (okno dachowe)', None),
    'c2-balustrade': ('Balustrada', None),
    'c2-parapet': ('Attyka (murek ochronny)', None),
    'c2-turret': ('Wieżyczka', None),
    'c2-moat': ('Fosa', None),
    'c2-drawbridge': ('Most zwodzony', None),
    'c2-cloister': ('Krużganek (klasztorny)', None),
    'c2-courtyard': ('Dziedziniec', None),
    'c2-alcove': ('Wnęka', None),
    'c2-mezzanine': ('Antresola', None),
    'c2-atrium': ('Atrium', None),
    'c2-mosaic': ('Mozaika', None),
    'c2-fresco': ('Fresk', None),
    'c2-elevation-drawing': ('Rzut elewacji (widok z boku)', None),
    'c2-partition-wall': ('Ścianka działowa', None),
    'c2-cladding': ('Okładzina (elewacyjna)', None),
    'c2-plumbing-system': ('Instalacja hydrauliczna', None),
    'c2-ventilation-duct': ('Kanał wentylacyjny', None),
    'c2-retrofit': ('Modernizacja (dostosowanie)', None),
    'c2-colander': ('Durszlak', None),
    'c2-ladle': ('Chochla', None),
    'c2-whisk': ('Trzepaczka (do jajek)', None),
    'c2-grater': ('Tarka', None),
    'c2-tongs': ('Szczypce (kuchenne)', None),
    'c2-spatula': ('Łopatka (kuchenna)', None),
    'c2-cutting-board': ('Deska do krojenia', None),
    'c2-french-press': ('Zaparzacz tłokowy', None),
    'c2-coaster': ('Podstawka pod szklankę', None),
    'c2-trivet': ('Podstawka pod gorące naczynia', None),
    'c2-oven-mitt': ('Rękawica kuchenna', None),
    'c2-dish-rack': ('Suszarka do naczyń', None),
    'c2-dustpan': ('Szufelka', None),
    'c2-mop': ('Mop', None),
    'c2-clothespin': ('Klamerka do prania', None),
    'c2-clothesline': ('Sznur do suszenia bielizny', None),
    'c2-shoehorn': ('Łyżka do butów', None),
    'c2-doormat': ('Wycieraczka', None),
    'c2-doorknob': ('Klamka (gałka drzwiowa)', None),
    'c2-hinge': ('Zawias', None),
    'c2-latch': ('Zasuwka (rygiel)', None),
    'c2-peephole': ('Wizjer', None),
    'c2-blinds-window': ('Żaluzje', None),
    'c2-windowsill': ('Parapet', None),
    'c2-banister': ('Poręcz (schodów)', None),
    'c2-landing-stairs': ('Podest (spocznik)', None),
    'c2-crawl-space': ('Przestrzeń podpodłogowa', None),
    'c2-cellar': ('Piwnica', None),
    'c2-pantry': ('Spiżarnia', None),
    'c2-utility-room': ('Pomieszczenie gospodarcze', None),
    'c2-fuse-box': ('Skrzynka bezpiecznikowa', None),
    'c2-dimmer-switch': ('Ściemniacz (regulator jasności)', None),
    'c2-extension-cord': ('Przedłużacz', None),
    'c2-power-strip': ('Listwa zasilająca', None),
    'c2-carbon-monoxide-alarm': ('Czujnik tlenku węgla', None),
    'c2-first-aid-kit': ('Apteczka', None),
    'c2-sewing-kit': ('Zestaw do szycia', None),
    'c2-toolbox': ('Skrzynka narzędziowa', None),
    'c2-allen-key': ('Klucz imbusowy', None),
    'c2-pliers': ('Szczypce (kombinerki)', None),
    'c2-wrench': ('Klucz (nastawny)', None),
    'c2-tape-measure': ('Miara zwijana (taśma miernicza)', None),
    'c2-spirit-level': ('Poziomica', None),
    'c2-drawer-organizer': ('Organizer do szuflady', None),
    'c2-bin-liner': ('Worek na śmieci', None),
    'c2-to-seethe': ('Kipieć (ze złości)', None),
    'c2-to-sulk': ('Dąsać się', None),
    'c2-to-fret': ('Zamartwiać się', None),
    'c2-to-brood': ('Rozpamiętywać', None),
    'c2-to-wallow-in-self-pity': ('Pogrążać się (w użalaniu nad sobą)', None),
    'c2-to-gloat-over-a-rival': ('Triumfować nad rywalem (złośliwie)', None),
    'c2-to-savor-the-moment': ('Delektować się chwilą', None),
    'c2-to-revel-in': ('Lubować się (w czymś)', None),
    'c2-to-marvel-at': ('Podziwiać z zachwytem', None),
    'c2-to-cringe': ('Kulić się (ze wstydu)', None),
    'c2-to-wince': ('Skrzywić się (z bólu)', None),
    'c2-to-flinch': ('Wzdrygać się (cofnąć się)', None),
    'c2-to-shudder': ('Zadrżeć (wzdrygnąć się z odrazy)', None),
    'c2-to-quiver': ('Drżeć (delikatnie)', None),
    'c2-to-swoon': ('Mdleć (z zachwytu)', None),
    'c2-to-pine-for': ('Usychać z tęsknoty', None),
    'c2-to-long-for': ('Łaknąć (pragnąć)', None),
    'c2-to-crave': ('Pożądać (mieć wielką ochotę)', None),
    'c2-to-abominate': ('Nienawidzić (czuć wstręt)', None),
    'c2-to-nurse-a-grievance': ('Żywić urazę', None),
    'c2-to-begrudge': ('Żałować (komuś czegoś)', None),
    'c2-to-grovel': ('Płaszczyć się', None),
    'c2-to-fawn-over': ('Nadskakiwać (komuś)', None),
    'c2-to-dote-on': ('Rozpieszczać (uwielbiać)', None),
    'c2-to-treasure': ('Cenić (ponad wszystko)', None),
    'c2-to-put-at-ease': ('Uspokajać (rozluźniać)', None),
    'c2-to-console': ('Pocieszać', None),
    'c2-to-commiserate': ('Współczuć', None),
    'c2-to-exasperate': ('Doprowadzać do irytacji', None),
    'c2-to-infuriate': ('Wprawiać we wściekłość', None),
    'c2-to-unnerve': ('Wytrącać z równowagi', None),
    'c2-to-mortify': ('Upokarzać', None),
    'c2-to-captivate': ('Urzekać', None),
    'c2-to-enrapture': ('Wprawiać w zachwyt (unosić)', None),
    'c2-to-disillusion': ('Rozczarowywać', None),
    'c2-to-mollify': ('Uspokoić (złagodzić czyjś gniew)', None),
    'c2-to-embolden': ('Dodawać odwagi', None),
    'c2-to-dishearten': ('Zniechęcać', None),
    'c2-to-rankle': ('Uwierać (drażnić bez ustanku)', None),
    'c2-to-smolder': ('Tlić się (skrywać wściekłość)', None),
    'c2-numbness': ('Drętwienie', None),
    'c2-tingling': ('Mrowienie', None),
    'c2-cramp': ('Skurcz', None),
    'c2-twinge': ('Ukłucie (bólu)', None),
    'c2-throbbing': ('Pulsujący (ból)', None),
    'c2-dizziness': ('Oszołomienie', None),
    'c2-lightheaded': ('Oszołomiony (z zawrotami głowy)', None),
    'c2-vertigo': ('Zawroty głowy', None),
    'c2-queasy': ('Mdlący (z mdłościami)', None),
    'c2-lethargy': ('Ospałość (letarg)', None),
    'c2-fatigue': ('Zmęczenie', None),
    'c2-stamina': ('Wytrzymałość', None),
    'c2-reflex': ('Odruch', None),
    'c2-flinch-noun': ('Odruchowe cofnięcie się', None),
    'c2-pins-and-needles': ('Cierpnięcie kończyn', None),
    'c2-shiver': ('Dreszcz', None),
    'c2-hot-flush': ('Uderzenie gorąca', None),
    'c2-blush': ('Rumieniec', None),
    'c2-yawn': ('Ziewnięcie', None),
    'c2-hiccup': ('Czkawka', None),
    'c2-sneeze': ('Kichnięcie', None),
    'c2-itch': ('Swędzenie', None),
    'c2-bruise': ('Siniak', None),
    'c2-blister': ('Pęcherz (na skórze)', None),
    'c2-pulled-muscle': ('Naciągnięty mięsień', None),
    'c2-stiffness': ('Sztywność (zakwasy)', None),
    'c2-restlessness': ('Niepokój (rozdrażnienie)', None),
    'c2-daydream': ('Marzenie na jawie', None),
    'c2-deja-vu': ('Déjà vu', None),
    'c2-hunch': ('Przeczucie', None),
    'c2-gut-feeling': ('Wewnętrzne przeczucie (instynkt)', None),
    'c2-brain-fog': ('Mgła mózgowa (zamglenie umysłu)', None),
    'c2-second-wind': ('Drugi oddech', None),
    'c2-adrenaline-rush': ('Przypływ adrenaliny', None),
    'c2-motion-sickness': ('Choroba lokomocyjna', None),
    'c2-camaraderie': ('Koleżeństwo (kameraderia)', None),
    'c2-affinity-between-people': ('Pokrewieństwo dusz (sympatia)', None),
    'c2-clique': ('Klika', None),
    'c2-entourage': ('Świta (otoczenie)', None),
    'c2-etiquette': ('Etykieta', None),
    'c2-faux-pas': ('Gafa (wpadka towarzyska)', None),
    'c2-gossip': ('Plotki', None),
    'c2-grudge': ('Uraza', None),
    'c2-chain-of-command': ('Hierarchia służbowa', None),
    'c2-nepotism': ('Nepotyzm', None),
    'c2-ostracism': ('Ostracyzm', None),
    'c2-groupthink': ('Myślenie grupowe', None),
    'c2-pecking-order': ('Hierarchia (układ zależności)', None),
    'c2-rivalry': ('Rywalizacja', None),
    'c2-solidarity': ('Solidarność', None),
    'c2-snub': ('Afront (lekceważenie)', None),
    'c2-taboo': ('Tabu', None),
    'c2-flattery': ('Pochlebstwo', None),
    'c2-backhanded-compliment': ('Dwuznaczny komplement', None),
    'c2-cold-shoulder': ('Ostentacyjne ignorowanie', None),
    'c2-small-circle-inner-circle': ('Wąskie grono (krąg zaufanych)', None),
    'c2-interloper': ('Intruz', None),
    'c2-old-hand': ('Wyga (doświadczony weteran)', None),
    'c2-wingman': ('Skrzydłowy (towarzysz wspomagający)', None),
    'c2-freeloader': ('Pieczeniarz', None),
    'c2-busybody': ('Wścibska osoba', None),
    'c2-killjoy': ('Ponurak (psujący zabawę)', None),
    'c2-show-off': ('Pozer (chwalipięta)', None),
    'c2-pushover': ('Słabeusz (łatwy do przekonania)', None),
    'c2-self-starter': ('Osoba samodzielna z inicjatywą', None),
    'c2-to-mingle': ('Krążyć wśród gości', None),
    'c2-to-schmooze': ('Kumplować się dla korzyści', None),
    'c2-to-shun': ('Unikać (stronić od)', None),
    'c2-to-patronize': ('Traktować z wyższością', None),
    'c2-to-reconcile': ('Godzić się (jednać)', None),
    'c2-to-estrange': ('Oddalać (zrażać do siebie)', None),
    'c2-to-confide-in': ('Zwierzać się (komuś)', None),
    'c2-to-hobnob': ('Zadawać się (z ważnymi osobami)', None),
    'c2-to-rub-shoulders-with': ('Obracać się (w tych samych kręgach)', None),
    'c2-to-fall-out-with': ('Poróżnić się (z kimś)', None),
    'c2-foil-character': ('Kontrast (postać kontrastująca)', None),
    'c2-anti-hero': ('Antybohater', None),
    'c2-narrator': ('Narrator', None),
    'c2-macguffin': ('MacGuffin (pretekst fabularny)', None),
    'c2-red-herring': ('Fałszywy trop', None),
    'c2-motif': ('Motyw', None),
    'c2-frame-narrative': ('Narracja ramowa', None),
    'c2-denouement': ('Rozwiązanie akcji', None),
    'c2-satire': ('Satyra', None),
    'c2-parody': ('Parodia', None),
    'c2-allegory': ('Alegoria', None),
    'c2-memoir': ('Pamiętnik (wspomnienia)', None),
    'c2-anthology': ('Antologia', None),
    'c2-manuscript': ('Manuskrypt', None),
    'c2-prose': ('Proza', None),
    'c2-couplet': ('Dwuwiersz', None),
    'c2-stanza': ('Strofa', None),
    'c2-sonnet': ('Sonet', None),
    'c2-alliteration': ('Aliteracja', None),
    'c2-meter-poetry': ('Metrum (miara wierszowa)', None),
    'c2-aesthetic': ('Estetyka', None),
    'c2-avant-garde': ('Awangarda', None),
    'c2-baroque': ('Barok', None),
    'c2-impressionism': ('Impresjonizm', None),
    'c2-surrealism': ('Surrealizm', None),
    'c2-still-life': ('Martwa natura', None),
    'c2-charcoal-drawing': ('Rysunek węglem', None),
    'c2-etching': ('Akwaforta (grafika trawiona)', None),
    'c2-bust-sculpture': ('Popiersie', None),
    'c2-chisel': ('Dłuto', None),
    'c2-easel': ('Sztaluga', None),
    'c2-palette': ('Paleta', None),
    'c2-overture': ('Uwertura', None),
    'c2-aria': ('Aria', None),
    'c2-encore': ('Bis', None),
    'c2-bandwidth': ('Pasmo (przepustowość łącza)', None),
    'c2-jitter': ('Drżenie sygnału (jitter)', None),
    'c2-throughput': ('Przepustowość (wydajność)', None),
    'c2-hashing': ('Haszowanie (funkcja skrótu)', None),
    'c2-intrusion-detection': ('Wykrywanie włamań', None),
    'c2-vulnerability-security': ('Podatność (luka bezpieczeństwa)', None),
    'c2-hotfix': ('Poprawka awaryjna (hotfix)', None),
    'c2-backlog': ('Zaległości (kolejka zadań)', None),
    'c2-rollout': ('Wdrożenie', None),
    'c2-rollback': ('Wycofanie zmian', None),
    'c2-uptime': ('Czas bezawaryjnej pracy', None),
    'c2-redundancy-backup': ('Redundancja', None),
    'c2-load-balancing': ('Równoważenie obciążenia', None),
    'c2-legacy-system': ('System przestarzały (dziedziczony)', None),
    'c2-copyleft': ('Copyleft (wolna licencja)', None),
    'c2-proprietary': ('Zastrzeżony (własnościowy)', None),
    'c2-interoperability': ('Interoperacyjność', None),
    'c2-passkey': ('Klucz dostępu', None),
    'c2-social-engineering': ('Inżynieria społeczna', None),
    'c2-data-breach': ('Wyciek danych', None),
    'c2-cache': ('Pamięć podręczna', None),
    'c2-query': ('Zapytanie', None),
    'c2-metadata': ('Metadane', None),
    'c2-placeholder': ('Symbol zastępczy', None),
    'c2-workaround': ('Obejście (problemu)', None),
    'c2-bottleneck': ('Wąskie gardło', None),
    'c2-edge-case': ('Przypadek brzegowy', None),
    'c2-deprecated': ('Przestarzały (odradzany)', None),
    'c2-sandbox': ('Piaskownica (środowisko testowe)', None),
    'c2-telemetry': ('Telemetria', None),
    'c2-algorithmic-bias': ('Błąd algorytmiczny (stronniczość)', None),
    'c2-overfitting': ('Przeuczenie', None),
    'c2-large-language-model': ('Duży model językowy', None),
    'c2-quantum-computing': ('Obliczenia kwantowe', None),
    'c2-semiconductor': ('Półprzewodnik', None),
    'c2-working-capital': ('Kapitał obrotowy', None),
    'c2-solvency': ('Wypłacalność', None),
    'c2-insolvency': ('Niewypłacalność', None),
    'c2-receivership': ('Zarząd komisaryczny', None),
    'c2-leverage-finance': ('Dźwignia finansowa', None),
    'c2-hedge-finance': ('Zabezpieczenie (hedging)', None),
    'c2-yield-finance': ('Rentowność (zysk)', None),
    'c2-share-buyback': ('Wykup akcji własnych', None),
    'c2-equity-ownership': ('Kapitał własny', None),
    'c2-treasury-bill': ('Bon skarbowy', None),
    'c2-asset-allocation': ('Alokacja aktywów', None),
    'c2-volatility': ('Zmienność', None),
    'c2-bull-market': ('Hossa', None),
    'c2-bear-market': ('Bessa', None),
    'c2-downturn': ('Spowolnienie (recesja)', None),
    'c2-stagflation': ('Stagflacja', None),
    'c2-deflation': ('Deflacja', None),
    'c2-interest-rate-hike': ('Podwyżka stóp procentowych', None),
    'c2-fiscal-policy': ('Polityka fiskalna', None),
    'c2-monetary-policy': ('Polityka pieniężna', None),
    'c2-subsidy': ('Dotacja (subwencja)', None),
    'c2-trade-quota': ('Kontyngent handlowy', None),
    'c2-embargo': ('Embargo', None),
    'c2-belt-tightening': ('Zaciskanie pasa', None),
    'c2-bailout': ('Ratunek finansowy (dokapitalizowanie)', None),
    'c2-windfall': ('Niespodziewany zysk', None),
    'c2-nest-egg': ('Oszczędności (poduszka finansowa)', None),
    'c2-slush-fund': ('Czarna kasa', None),
    'c2-kickback': ('Łapówka (prowizja pod stołem)', None),
    'c2-money-laundering': ('Pranie pieniędzy', None),
    'c2-tax-evasion': ('Uchylanie się od podatków', None),
    'c2-tax-loophole': ('Luka podatkowa', None),
    'c2-underwriter': ('Ubezpieczyciel (gwarant emisji)', None),
    'c2-sinking-fund': ('Fundusz amortyzacyjny', None),
    'c2-arbitrage': ('Arbitraż', None),
    'c2-freight': ('Fracht (ładunek)', None),
    'c2-cargo-hold': ('Ładownia', None),
    'c2-consignment': ('Przesyłka', None),
    'c2-customs-clearance': ('Odprawa celna', None),
    'c2-red-eye-flight': ('Lot nocny', None),
    'c2-turbulence': ('Turbulencje', None),
    'c2-taxiing': ('Kołowanie (samolotu)', None),
    'c2-cockpit': ('Kokpit', None),
    'c2-overhead-compartment': ('Schowek nad głową', None),
    'c2-aisle-seat': ('Miejsce przy przejściu', None),
    'c2-boarding-pass': ('Karta pokładowa', None),
    'c2-baggage-carousel': ('Taśma bagażowa', None),
    'c2-jet-bridge': ('Rękaw pasażerski', None),
    'c2-tailgating-driving': ('Jazda na zderzaku', None),
    'c2-gridlock': ('Całkowity zator (paraliż ruchu)', None),
    'c2-diversion-route': ('Objazd', None),
    'c2-interchange-highway': ('Węzeł autostradowy', None),
    'c2-overpass': ('Wiadukt', None),
    'c2-underpass': ('Przejście podziemne', None),
    'c2-toll-booth': ('Punkt poboru opłat', None),
    'c2-hard-shoulder': ('Pas awaryjny', None),
    'c2-speed-bump': ('Próg zwalniający', None),
    'c2-blind-spot': ('Martwy punkt', None),
    'c2-hazard-lights': ('Światła awaryjne', None),
    'c2-windshield-wiper': ('Wycieraczka', None),
    'c2-clutch-car': ('Sprzęgło', None),
    'c2-handbrake': ('Hamulec ręczny', None),
    'c2-odometer': ('Licznik kilometrów', None),
    'c2-tow-truck': ('Laweta (pomoc drogowa)', None),
    'c2-commute-noun': ('Dojazd do pracy', None),
    'c2-numerator': ('Licznik (ułamka)', None),
    'c2-denominator': ('Mianownik', None),
    'c2-exponent': ('Wykładnik potęgi', None),
    'c2-square-root': ('Pierwiastek kwadratowy', None),
    'c2-decimal-point': ('Przecinek dziesiętny', None),
    'c2-remainder': ('Reszta (z dzielenia)', None),
    'c2-prime-number': ('Liczba pierwsza', None),
    'c2-integer': ('Liczba całkowita', None),
    'c2-quotient': ('Iloraz', None),
    'c2-percentile': ('Percentyl', None),
    'c2-mean-average': ('Średnia', None),
    'c2-median': ('Mediana', None),
    'c2-outlier': ('Wartość odstająca', None),
    'c2-standard-deviation': ('Odchylenie standardowe', None),
    'c2-variance': ('Wariancja', None),
    'c2-margin-of-error': ('Margines błędu', None),
    'c2-sample-size': ('Wielkość próby', None),
    'c2-exponential-growth': ('Wzrost wykładniczy', None),
    'c2-order-of-magnitude': ('Rząd wielkości', None),
    'c2-rounding': ('Zaokrąglanie', None),
    'c2-percentage-point': ('Punkt procentowy', None),
    'c2-threefold': ('Trzykrotny', None),
    'c2-a-dozen': ('Tuzin', None),
    'c2-round-number': ('Liczba okrągła', None),
    'c2-odds-probability': ('Szanse (prawdopodobieństwo)', None),
    'c2-inseam': ('Długość wewnętrzna nogawki', None),
    'c2-dart-sewing': ('Zaszewka', None),
    'c2-lapel': ('Klapa (marynarki)', None),
    'c2-cuff': ('Mankiet', None),
    'c2-cufflinks': ('Spinki do mankietów', None),
    'c2-gusset': ('Klin (wstawka wzmacniająca)', None),
    'c2-pleat': ('Plisa (fałda)', None),
    'c2-tailored': ('Skrojony na miarę', None),
    'c2-bespoke': ('Szyty na miarę', None),
    'c2-off-the-rack': ('Konfekcyjny (gotowy)', None),
    'c2-threadbare': ('Wytarty (przetarty)', None),
    'c2-frayed': ('Postrzępiony', None),
    'c2-creased': ('Pomięty', None),
    'c2-dapper': ('Elegancki (wytworny)', None),
    'c2-disheveled': ('Rozczochrany (w nieładzie)', None),
    'c2-scruffy': ('Niechlujny', None),
    'c2-garish': ('Krzykliwy', None),
    'c2-understated': ('Stonowany (dyskretny)', None),
    'c2-flattering-clothes': ('Korzystny (dodający urody)', None),
    'c2-baggy': ('Workowaty', None),
    'c2-snug': ('Obcisły (dopasowany)', None),
    'c2-stubble': ('Zarost (kilkudniowy)', None),
    'c2-freckles': ('Piegi', None),
    'c2-dimple': ('Dołeczek', None),
    'c2-crow-s-feet': ('Kurze łapki', None),
    'c2-complexion': ('Cera', None),
    'c2-gaunt': ('Wychudzony', None),
    'c2-stocky': ('Krępy', None),
    'c2-lanky': ('Tyczkowaty', None),
    'c2-poised': ('Opanowany (pełen gracji)', None),
}
