# -*- coding: utf-8 -*-
LANG = 'vi'
WORDS = {
    'c2-to-abate': ('Lắng dịu', None),
    'c2-to-abhor': ('Ghê tởm', None),
    'c2-to-abstain': ('Kiêng cữ (bỏ phiếu trắng)', None),
    'c2-to-accentuate': ('Nhấn mạnh', None),
    'c2-to-acquiesce': ('Ưng thuận (miễn cưỡng)', None),
    'c2-to-admonish': ('Khiển trách (cảnh cáo)', None),
    'c2-to-alleviate': ('Giảm nhẹ', None),
    'c2-to-amass': ('Tích lũy', None),
    'c2-to-appease': ('Xoa dịu', None),
    'c2-to-ascribe': ('Quy cho', None),
    'c2-to-augment': ('Gia tăng', None),
    'c2-to-avert': ('Ngăn chặn', None),
    'c2-to-beckon': ('Vẫy gọi', None),
    'c2-to-belittle': ('Xem thường', None),
    'c2-to-bequeath': ('Di tặng', None),
    'c2-to-beseech': ('Khẩn cầu', None),
    'c2-to-bewilder': ('Làm bối rối', None),
    'c2-to-brandish': ('Vung (vũ khí)', None),
    'c2-to-castigate': ('Trừng phạt bằng lời (quở trách nặng)', None),
    'c2-to-coalesce': ('Hợp nhất', None),
    'c2-to-commend': ('Khen ngợi', None),
    'c2-to-concede': ('Nhượng bộ', None),
    'c2-to-concoct': ('Bịa đặt', None),
    'c2-to-confer': ('Trao tặng (ban cho)', None),
    'c2-to-contend': ('Khẳng định (tranh luận)', None),
    'c2-to-corroborate': ('Xác thực', None),
    'c2-to-aggravate': ('Làm trầm trọng thêm', None),
    'c2-to-assail': ('Công kích', None),
    'c2-to-chastise': ('Trừng phạt (quở trách)', None),
    'c2-to-condescend': ('Hạ cố', None),
    'c2-to-debunk': ('Vạch trần', None),
    'c2-to-decipher': ('Giải mã', None),
    'c2-to-decry': ('Lên án', None),
    'c2-to-deem': ('Coi là', None),
    'c2-to-defer': ('Trì hoãn', None),
    'c2-to-delineate': ('Phác họa', None),
    'c2-to-denounce': ('Tố cáo', None),
    'c2-to-deplete': ('Làm cạn kiệt', None),
    'c2-to-deride': ('Chế giễu', None),
    'c2-to-despair': ('Tuyệt vọng', None),
    'c2-to-detain': ('Giam giữ', None),
    'c2-to-deviate': ('Đi chệch hướng', None),
    'c2-to-disdain': ('Khinh miệt', None),
    'c2-to-disperse': ('Phân tán', None),
    'c2-to-dissuade': ('Can ngăn', None),
    'c2-to-divulge': ('Tiết lộ (bí mật)', None),
    'c2-to-dwindle': ('Suy giảm dần', None),
    'c2-to-elude': ('Né tránh', None),
    'c2-to-emanate': ('Tỏa ra', None),
    'c2-to-embellish': ('Tô điểm', None),
    'c2-to-encompass': ('Bao gồm', None),
    'c2-to-engender': ('Làm nảy sinh', None),
    'c2-to-enlighten': ('Khai sáng', None),
    'c2-to-enthrall': ('Làm say mê', None),
    'c2-to-entice': ('Dụ dỗ', None),
    'c2-to-envision': ('Hình dung', None),
    'c2-to-evade': ('Trốn tránh', None),
    'c2-to-exalt': ('Tôn vinh', None),
    'c2-to-expedite': ('Đẩy nhanh', None),
    'c2-to-extol': ('Ca tụng', None),
    'c2-to-fabricate': ('Ngụy tạo', None),
    'c2-to-falter': ('Chùn bước', None),
    'c2-to-feign': ('Giả vờ', None),
    'c2-to-flourish': ('Hưng thịnh', None),
    'c2-to-forfeit': ('Mất quyền (do vi phạm)', None),
    'c2-to-forgo': ('Từ bỏ', None),
    'c2-to-galvanize': ('Thúc đẩy (hành động)', None),
    'c2-to-garner': ('Thu được', None),
    'c2-to-gloat': ('Hả hê', None),
    'c2-to-grapple': ('Vật lộn', None),
    'c2-to-harness': ('Khai thác (tận dụng)', None),
    'c2-to-heed': ('Lưu tâm', None),
    'c2-to-hoard': ('Tích trữ', None),
    'c2-to-impart': ('Truyền đạt', None),
    'c2-to-implore': ('Van nài', None),
    'c2-to-incite': ('Kích động', None),
    'c2-to-inhibit': ('Kìm hãm', None),
    'c2-to-instill': ('Gieo vào (khắc sâu)', None),
    'c2-to-intercede': ('Can thiệp (giúp)', None),
    'c2-to-intimidate': ('Hăm dọa', None),
    'c2-to-jeopardize': ('Gây nguy hiểm', None),
    'c2-to-languish': ('Héo mòn', None),
    'c2-to-lure': ('Nhử mồi (quyến rũ)', None),
    'c2-to-marvel': ('Kinh ngạc', None),
    'c2-to-meander': ('Uốn khúc', None),
    'c2-to-muster': ('Tập hợp (sức lực)', None),
    'c2-to-obliterate': ('Hủy diệt', None),
    'c2-to-oscillate': ('Dao động', None),
    'c2-to-ostracize': ('Tẩy chay', None),
    'c2-to-perpetuate': ('Duy trì (kéo dài mãi)', None),
    'c2-to-permeate': ('Thấm khắp', None),
    'c2-to-plummet': ('Lao dốc', None),
    'c2-to-ponder': ('Suy ngẫm', None),
    'c2-to-preach': ('Thuyết giáo', None),
    'c2-to-procure': ('Thu mua (kiếm được)', None),
    'c2-to-proliferate': ('Sinh sôi nảy nở', None),
    'c2-to-propel': ('Đẩy tới (thúc đẩy)', None),
    'c2-to-quell': ('Dập tắt (trấn áp)', None),
    'c2-to-ratify': ('Phê chuẩn', None),
    'c2-to-rebuke': ('Quở mắng', None),
    'c2-to-rebut': ('Bác bỏ', None),
    'c2-to-recant': ('Rút lại lời (thoái thác)', None),
    'c2-to-redeem': ('Chuộc lại', None),
    'c2-to-refute': ('Phản bác', None),
    'c2-to-relish': ('Thưởng thức (khoái trá)', None),
    'c2-to-renounce': ('Từ khước', None),
    'c2-to-replenish': ('Bổ sung (đầy lại)', None),
    'c2-to-reprimand': ('Khiển trách chính thức', None),
    'c2-to-repudiate': ('Phủ nhận (từ chối công nhận)', None),
    'c2-to-resonate': ('Cộng hưởng', None),
    'c2-to-retaliate': ('Trả đũa', None),
    'c2-to-revere': ('Tôn kính', None),
    'c2-to-revoke': ('Thu hồi', None),
    'c2-to-saturate': ('Làm bão hòa', None),
    'c2-to-scorn': ('Khinh bỉ', None),
    'c2-to-squander': ('Phung phí', None),
    'c2-to-stagnate': ('Trì trệ', None),
    'c2-to-stifle': ('Bóp nghẹt', None),
    'c2-to-subside': ('Lắng xuống (giảm bớt)', None),
    'c2-to-succumb': ('Khuất phục', None),
    'c2-to-supplant': ('Soán ngôi (thay thế)', None),
    'c2-to-surmise': ('Phỏng đoán', None),
    'c2-to-swindle': ('Lừa đảo', None),
    'c2-to-tarnish': ('Làm hoen ố', None),
    'c2-to-thwart': ('Cản trở (phá hỏng kế hoạch)', None),
    'c2-to-transcend': ('Vượt lên trên (siêu việt)', None),
    'c2-to-unravel': ('Tháo gỡ (làm sáng tỏ)', None),
    'c2-to-usurp': ('Soán đoạt', None),
    'c2-to-vanquish': ('Đánh bại (chinh phục)', None),
    'c2-to-venerate': ('Sùng kính', None),
    'c2-to-vilify': ('Bôi nhọ', None),
    'c2-to-wane': ('Suy tàn (tàn lụi)', None),
    'c2-to-wield': ('Sử dụng (quyền lực)', None),
    'c2-to-writhe': ('Quằn quại', None),
    'c2-to-yearn': ('Khao khát', None),
    'c2-to-beget': ('Sinh ra', None),
    'c2-to-besiege': ('Bao vây', None),
    'c2-to-cajole': ('Dỗ ngọt', None),
    'c2-to-coax': ('Vỗ về (thuyết phục)', None),
    'c2-to-deplore': ('Than trách (lấy làm tiếc)', None),
    'c2-to-disparage': ('Gièm pha', None),
    'c2-to-exhort': ('Hô hào (thúc giục)', None),
    'c2-to-foment': ('Xúi giục', None),
    'c2-to-indulge': ('Buông thả (theo sở thích)', None),
    'c2-to-placate': ('Làm nguôi giận', None),
    'c2-to-preempt': ('Ra tay trước (phủ đầu)', None),
    'c2-to-rescind': ('Hủy bỏ (quyết định)', None),
    'c2-to-stymie': ('Gây bế tắc', None),
    'c2-to-vindicate': ('Minh oan', None),
    'c2-to-evince': ('Biểu lộ (rõ ràng)', None),
    'c2-affable': ('Hòa nhã', None),
    'c2-churlish': ('Cục cằn', None),
    'c2-astute': ('Tinh khôn', None),
    'c2-audacious': ('Táo bạo', None),
    'c2-belligerent': ('Hiếu chiến', None),
    'c2-sanguine': ('Lạc quan (tự tin)', None),
    'c2-brusque': ('Cộc lốc', None),
    'c2-callous': ('Chai sạn (vô cảm)', None),
    'c2-truculent': ('Hung hăng', None),
    'c2-capricious': ('Thất thường', None),
    'c2-complacent': ('Tự mãn', None),
    'c2-unflappable': ('Điềm tĩnh (không nao núng)', None),
    'c2-cunning': ('Xảo quyệt', None),
    'c2-diffident': ('Rụt rè (thiếu tự tin)', None),
    'c2-officious': ('Bao biện (xen vào việc người khác)', None),
    'c2-docile': ('Ngoan ngoãn', None),
    'c2-erudite': ('Uyên bác', None),
    'c2-fastidious': ('Kỹ tính (cầu toàn)', None),
    'c2-flippant': ('Hời hợt (bỡn cợt)', None),
    'c2-garrulous': ('Lắm lời', None),
    'c2-gregarious': ('Thích giao du', None),
    'c2-haughty': ('Kiêu ngạo', None),
    'c2-impetuous': ('Bồng bột', None),
    'c2-indolent': ('Lười biếng', None),
    'c2-mercurial': ('Đồng bóng', None),
    'c2-phlegmatic': ('Điềm đạm', None),
    'c2-obsequious': ('Nịnh bợ', None),
    'c2-petulant': ('Cáu kỉnh (hờn dỗi)', None),
    'c2-sanctimonious': ('Đạo đức giả', None),
    'c2-taciturn': ('Ít nói (trầm lặng)', None),
    'c2-bountiful': ('Hào phóng (dồi dào)', None),
    'c2-arduous': ('Gian nan', None),
    'c2-banal': ('Tầm thường (sáo rỗng)', None),
    'c2-copious': ('Phong phú (nhiều)', None),
    'c2-cumbersome': ('Cồng kềnh', None),
    'c2-deft': ('Khéo léo', None),
    'c2-dire': ('Thảm khốc (nghiêm trọng)', None),
    'c2-ephemeral': ('Phù du', None),
    'c2-peerless': ('Vô song', None),
    'c2-feeble': ('Yếu ớt', None),
    'c2-rickety': ('Ọp ẹp', None),
    'c2-formidable': ('Đáng gờm', None),
    'c2-immaculate': ('Không tì vết', None),
    'c2-faultless': ('Hoàn hảo (không sai sót)', None),
    'c2-innocuous': ('Vô hại', None),
    'c2-insidious': ('Âm ỉ (nham hiểm)', None),
    'c2-labyrinthine': ('Như mê cung (rắc rối)', None),
    'c2-profligate': ('Hoang phí (trụy lạc)', None),
    'c2-perspicuous': ('Sáng rõ (dễ hiểu)', None),
    'c2-sparse': ('Thưa thớt', None),
    'c2-infinitesimal': ('Vô cùng nhỏ', None),
    'c2-sumptuous': ('Xa hoa', None),
    'c2-paltry': ('Ít ỏi (không đáng kể)', None),
    'c2-unblemished': ('Trong sạch (không vết nhơ)', None),
    'c2-indomitable': ('Bất khuất', None),
    'c2-scant': ('Khan hiếm', None),
    'c2-transcendent': ('Siêu việt', None),
    'c2-tenuous': ('Mong manh', None),
    'c2-unwieldy': ('Khó điều khiển (kềnh càng)', None),
    'c2-boundless': ('Vô biên', None),
    'c2-abstruse': ('Khó hiểu (uyên áo)', None),
    'c2-apt': ('Thích hợp (đích đáng)', None),
    'c2-cogent': ('Thuyết phục (chặt chẽ)', None),
    'c2-contentious': ('Gây tranh cãi', None),
    'c2-deplorable': ('Đáng chê trách', None),
    'c2-dubious': ('Đáng ngờ', None),
    'c2-egregious': ('Trắng trợn (quá quắt)', None),
    'c2-exemplary': ('Mẫu mực', None),
    'c2-fallacious': ('Ngụy biện', None),
    'c2-futile': ('Vô ích', None),
    'c2-gratuitous': ('Vô cớ', None),
    'c2-illicit': ('Phi pháp', None),
    'c2-impartial': ('Công tâm', None),
    'c2-incongruous': ('Lạc lõng (không phù hợp)', None),
    'c2-ineffable': ('Khôn tả', None),
    'c2-irrefutable': ('Không thể chối cãi', None),
    'c2-laudable': ('Đáng khen', None),
    'c2-moot': ('Không còn thực tế (còn bỏ ngỏ)', None),
    'c2-nebulous': ('Mơ hồ', None),
    'c2-ostensible': ('Bề ngoài (biểu kiến)', None),
    'c2-pernicious': ('Nguy hại (ngấm ngầm)', None),
    'c2-plausible': ('Có vẻ hợp lý', None),
    'c2-preposterous': ('Lố bịch (phi lý)', None),
    'c2-salient': ('Nổi bật', None),
    'c2-spurious': ('Giả mạo', None),
    'c2-superfluous': ('Dư thừa', None),
    'c2-tenable': ('Có thể biện hộ (đứng vững)', None),
    'c2-untenable': ('Không thể biện hộ', None),
    'c2-viable': ('Khả thi', None),
    'c2-wanton': ('Bừa bãi (vô cớ)', None),
    'c2-ailing': ('Ốm yếu (suy yếu)', None),
    'c2-bewildered': ('Bối rối', None),
    'c2-desolate': ('Hoang vắng (cô quạnh)', None),
    'c2-brittle': ('Giòn (dễ vỡ)', None),
    'c2-cohesive': ('Gắn kết', None),
    'c2-defunct': ('Không còn tồn tại', None),
    'c2-derelict': ('Bị bỏ hoang', None),
    'c2-ramshackle': ('Tồi tàn (xiêu vẹo)', None),
    'c2-dormant': ('Ngủ yên (tiềm ẩn)', None),
    'c2-drowsy': ('Buồn ngủ', None),
    'c2-dwindling': ('Đang thu hẹp dần', None),
    'c2-exhilarated': ('Phấn khích', None),
    'c2-forlorn': ('Cô đơn (tuyệt vọng)', None),
    'c2-haggard': ('Hốc hác', None),
    'c2-imminent': ('Sắp xảy ra', None),
    'c2-incessant': ('Liên miên', None),
    'c2-inert': ('Trơ (bất động)', None),
    'c2-jaded': ('Chán chường', None),
    'c2-languid': ('Uể oải', None),
    'c2-listless': ('Thiếu sức sống (rã rời)', None),
    'c2-antiquated': ('Lỗi thời', None),
    'c2-precarious': ('Bấp bênh', None),
    'c2-rampant': ('Tràn lan', None),
    'c2-fidgety': ('Bồn chồn', None),
    'c2-rife': ('Đầy rẫy', None),
    'c2-sodden': ('Ướt sũng', None),
    'c2-stagnant': ('Tù đọng', None),
    'c2-susceptible': ('Dễ bị ảnh hưởng', None),
    'c2-volatile': ('Bất ổn (dễ biến động)', None),
    'c2-weary': ('Mệt mỏi', None),
    'c2-bombastic': ('Khoa trương', None),
    'c2-vernacular': ('Tiếng bản ngữ (thông tục)', None),
    'c2-concise': ('Súc tích', None),
    'c2-tortuous': ('Quanh co (rắc rối)', None),
    'c2-cryptic': ('Bí hiểm', None),
    'c2-derogatory': ('Miệt thị', None),
    'c2-didactic': ('Mang tính giáo huấn', None),
    'c2-silver-tongued': ('Khéo ăn nói', None),
    'c2-emphatic': ('Dứt khoát (nhấn mạnh)', None),
    'c2-euphemistic': ('Mang tính uyển ngữ', None),
    'c2-facetious': ('Đùa cợt', None),
    'c2-florid': ('Hoa mỹ (rườm rà)', None),
    'c2-glib': ('Trơn tru (thiếu chân thành)', None),
    'c2-hyperbolic': ('Phóng đại', None),
    'c2-incisive': ('Sắc bén', None),
    'c2-laconic': ('Kiệm lời', None),
    'c2-long-winded': ('Dài dòng', None),
    'c2-mordant': ('Cay độc (châm biếm)', None),
    'c2-ornate': ('Cầu kỳ (trang trí rườm rà)', None),
    'c2-pedantic': ('Câu nệ (sính chữ nghĩa)', None),
    'c2-pithy': ('Ngắn gọn mà sâu sắc', None),
    'c2-plaintive': ('Ai oán', None),
    'c2-rhetorical': ('Mang tính tu từ', None),
    'c2-sardonic': ('Mỉa mai (cay độc)', None),
    'c2-scathing': ('Gay gắt (cay nghiệt)', None),
    'c2-succinct': ('Ngắn gọn', None),
    'c2-terse': ('Ngắn gọn khô khan', None),
    'c2-trite': ('Sáo rỗng', None),
    'c2-verbose': ('Dông dài', None),
    'c2-wry': ('Châm biếm chua chát', None),
    'c2-acumen': ('Sự nhạy bén (tinh tường)', None),
    'c2-alacrity': ('Sự hăng hái (mau mắn)', None),
    'c2-ambivalence': ('Sự lưỡng lự (mâu thuẫn)', None),
    'c2-apathy': ('Sự thờ ơ', None),
    'c2-aplomb': ('Sự tự tin (điềm tĩnh)', None),
    'c2-audacity': ('Sự táo bạo (liều lĩnh)', None),
    'c2-candor': ('Sự thẳng thắn', None),
    'c2-smugness': ('Sự tự đắc', None),
    'c2-scorn': ('Sự khinh miệt', None),
    'c2-deference': ('Sự tôn trọng (phục tùng)', None),
    'c2-discretion': ('Sự kín đáo (thận trọng)', None),
    'c2-disdain': ('Sự khinh thường', None),
    'c2-forbearance': ('Sự nhẫn nhịn (khoan dung)', None),
    'c2-fortitude': ('Nghị lực (kiên cường)', None),
    'c2-hubris': ('Sự ngạo mạn (kiêu ngạo thái quá)', None),
    'c2-meekness': ('Sự nhu mì (khiêm nhường)', None),
    'c2-umbrage': ('Sự phật ý (bị xúc phạm)', None),
    'c2-ingenuity': ('Sự khéo léo (sáng tạo)', None),
    'c2-rectitude': ('Sự chính trực', None),
    'c2-malice': ('Ác ý', None),
    'c2-nostalgia': ('Hoài niệm', None),
    'c2-perseverance': ('Sự kiên trì', None),
    'c2-prudence': ('Sự thận trọng', None),
    'c2-grit': ('Sự bền bỉ (gan góc)', None),
    'c2-reticence': ('Sự kín tiếng (dè dặt)', None),
    'c2-equanimity': ('Sự bình thản', None),
    'c2-tenacity': ('Sự ngoan cường (kiên định)', None),
    'c2-vanity': ('Sự phù phiếm (tự phụ)', None),
    'c2-vigilance': ('Sự cảnh giác', None),
    'c2-zeal': ('Nhiệt huyết', None),
    'c2-anomaly': ('Sự bất thường', None),
    'c2-catalyst': ('Chất xúc tác', None),
    'c2-conundrum': ('Câu đố hóc búa (nan đề)', None),
    'c2-debacle': ('Thảm bại', None),
    'c2-deluge': ('Làn sóng ập đến (trận lụt)', None),
    'c2-dearth': ('Sự khan hiếm', None),
    'c2-dichotomy': ('Sự lưỡng phân', None),
    'c2-epitome': ('Hiện thân (điển hình)', None),
    'c2-exodus': ('Cuộc di cư ồ ạt', None),
    'c2-facade': ('Vẻ bề ngoài (giả tạo)', None),
    'c2-fallacy': ('Luận điểm sai lầm (ngụy biện)', None),
    'c2-hindsight': ('Cái nhìn lại (nhận thức muộn màng)', None),
    'c2-impasse': ('Bế tắc', None),
    'c2-impetus': ('Động lực (đà thúc đẩy)', None),
    'c2-juncture': ('Thời điểm (bước ngoặt)', None),
    'c2-loophole': ('Kẽ hở (pháp lý)', None),
    'c2-tipping-point': ('Điểm bùng phát', None),
    'c2-onslaught': ('Cuộc tấn công dồn dập', None),
    'c2-vicious-circle': ('Vòng luẩn quẩn', None),
    'c2-plight': ('Tình cảnh khốn đốn', None),
    'c2-precedent': ('Tiền lệ', None),
    'c2-quandary': ('Tình thế tiến thoái lưỡng nan', None),
    'c2-ramification': ('Hệ lụy (hậu quả kéo theo)', None),
    'c2-respite': ('Khoảng nghỉ (tạm ngưng)', None),
    'c2-setback': ('Trở ngại (bước lùi)', None),
    'c2-stalemate': ('Thế giằng co (bế tắc)', None),
    'c2-surge': ('Sự gia tăng đột ngột', None),
    'c2-turmoil': ('Sự hỗn loạn', None),
    'c2-upheaval': ('Sự biến động (đảo lộn)', None),
    'c2-watershed': ('Cột mốc bước ngoặt', None),
    'c2-accomplice': ('Đồng phạm', None),
    'c2-adversary': ('Đối thủ', None),
    'c2-advocate': ('Người ủng hộ (biện hộ)', None),
    'c2-benefactor': ('Ân nhân', None),
    'c2-bystander': ('Người ngoài cuộc (chứng kiến)', None),
    'c2-charlatan': ('Kẻ lừa bịp (lang băm)', None),
    'c2-connoisseur': ('Người sành sỏi', None),
    'c2-culprit': ('Thủ phạm', None),
    'c2-demagogue': ('Kẻ mị dân', None),
    'c2-dilettante': ('Người tài tử (nghiệp dư)', None),
    'c2-envoy': ('Đặc phái viên', None),
    'c2-lackey': ('Tay sai', None),
    'c2-understudy': ('Người đóng thế (dự bị)', None),
    'c2-hypocrite': ('Kẻ đạo đức giả', None),
    'c2-insurgent': ('Quân nổi dậy', None),
    'c2-layperson': ('Người ngoại đạo (không chuyên)', None),
    'c2-maverick': ('Người khác biệt (không theo khuôn mẫu)', None),
    'c2-sidekick': ('Người bạn đồng hành (phụ tá)', None),
    'c2-mercenary': ('Lính đánh thuê', None),
    'c2-novice': ('Người mới vào nghề', None),
    'c2-pariah': ('Kẻ bị ruồng bỏ', None),
    'c2-patron': ('Nhà bảo trợ', None),
    'c2-perpetrator': ('Kẻ gây án', None),
    'c2-prodigy': ('Thần đồng', None),
    'c2-informant': ('Kẻ chỉ điểm', None),
    'c2-recluse': ('Người ẩn dật', None),
    'c2-sage': ('Bậc hiền triết', None),
    'c2-turncoat': ('Kẻ phản bội (trở cờ)', None),
    'c2-stalwart': ('Người trung kiên', None),
    'c2-tycoon': ('Trùm tài phiệt', None),
    'c2-ambiguity': ('Sự mơ hồ', None),
    'c2-analogy': ('Phép loại suy (so sánh)', None),
    'c2-axiom': ('Tiên đề', None),
    'c2-caveat': ('Lời cảnh báo (điều khoản dè chừng)', None),
    'c2-consensus': ('Sự đồng thuận', None),
    'c2-corollary': ('Hệ quả tất yếu', None),
    'c2-yardstick': ('Thước đo (tiêu chuẩn)', None),
    'c2-narrative': ('Câu chuyện (luận điểm chủ đạo)', None),
    'c2-doctrine': ('Học thuyết', None),
    'c2-dogma': ('Giáo điều', None),
    'c2-epiphany': ('Sự giác ngộ bất chợt', None),
    'c2-ethos': ('Tinh thần cốt lõi', None),
    'c2-conjecture': ('Giả thuyết (phỏng đoán)', None),
    'c2-idiosyncrasy': ('Nét đặc dị (riêng biệt)', None),
    'c2-deduction': ('Phép suy diễn', None),
    'c2-innuendo': ('Lời bóng gió', None),
    'c2-buzzword': ('Từ ngữ thời thượng', None),
    'c2-simile': ('Phép so sánh (ví von)', None),
    'c2-nuance': ('Sắc thái (tinh tế)', None),
    'c2-archetype': ('Nguyên mẫu', None),
    'c2-platitude': ('Lời sáo rỗng', None),
    'c2-postulate': ('Giả định cơ bản', None),
    'c2-pretext': ('Cái cớ', None),
    'c2-rebuttal': ('Lời phản bác', None),
    'c2-rhetoric': ('Thuật hùng biện', None),
    'c2-semantics': ('Ngữ nghĩa học', None),
    'c2-stigma': ('Sự kỳ thị', None),
    'c2-tenet': ('Nguyên lý (tín điều)', None),
    'c2-trope': ('Mô típ (khuôn sáo)', None),
    'c2-zeitgeist': ('Tinh thần thời đại', None),
    'c2-acrid': ('Hắc (cay nồng)', None),
    'c2-astringent': ('Chát', None),
    'c2-bland-flavorless': ('Nhạt nhẽo', None),
    'c2-brackish': ('Lợ (nước lợ)', None),
    'c2-cloying': ('Ngấy (ngọt gắt)', None),
    'c2-coarse': ('Thô ráp', None),
    'c2-creamy': ('Béo ngậy (mịn màng)', None),
    'c2-crunchy': ('Giòn (rôm rốp)', None),
    'c2-dank': ('Ẩm mốc', None),
    'c2-earthy': ('Có mùi đất', None),
    'c2-fragrant': ('Thơm ngát', None),
    'c2-gooey': ('Dẻo dính (nhão nhoét)', None),
    'c2-grainy': ('Lợn cợn (có hạt)', None),
    'c2-unctuous': ('Nhờn (giả tạo, nịnh hót)', None),
    'c2-gravelly-voice': ('Khàn (giọng)', None),
    'c2-luscious': ('Ngon ngọt hấp dẫn', None),
    'c2-mellow': ('Êm dịu (thuần hậu)', None),
    'c2-hushed': ('Im ắng (khẽ khàng)', None),
    'c2-musty': ('Mốc meo (hôi ẩm)', None),
    'c2-piercing': ('The thé (xuyên thấu)', None),
    'c2-pungent': ('Nồng gắt (hăng)', None),
    'c2-putrid': ('Thối rữa', None),
    'c2-rancid': ('Ôi thiu', None),
    'c2-bitter-aftertaste': ('Dư vị đắng', None),
    'c2-grating-sound': ('Chói tai (kèn kẹt)', None),
    'c2-silky': ('Mượt như lụa', None),
    'c2-slimy': ('Nhớt (nhầy nhụa)', None),
    'c2-soggy': ('Nhũn nước (mềm sũng)', None),
    'c2-tangy': ('Chua nồng (đậm đà)', None),
    'c2-zesty': ('Đậm đà (hăng, tươi)', None),
    'c2-better-late-than-never': ('Muộn còn hơn không', None),
    'c2-actions-speak-louder-than-words': ('Lời nói không bằng việc làm', None),
    'c2-the-early-bird-catches-the-worm': ('Chim dậy sớm bắt được sâu (nhanh chân thì được lợi)', None),
    'c2-don-t-count-your-chickens-before-they-hatch': ('Chưa đỗ ông nghè đã đe hàng tổng', None),
    'c2-every-cloud-has-a-silver-lining': ('Trong cái rủi có cái may', None),
    'c2-practice-makes-perfect': ('Có công mài sắt có ngày nên kim', None),
    'c2-when-in-rome-do-as-the-romans-do': ('Nhập gia tùy tục', None),
    'c2-two-heads-are-better-than-one': ('Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao', None),
    'c2-the-grass-is-always-greener-on-the-other-side': ('Đứng núi này trông núi nọ', None),
    'c2-don-t-judge-a-book-by-its-cover': ('Tốt gỗ hơn tốt nước sơn (đừng trông mặt mà bắt hình dong)', None),
    'c2-birds-of-a-feather-flock-together': ('Ngưu tầm ngưu, mã tầm mã', None),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('Một con chim trong tay hơn hai con trong bụi rậm', None),
    'c2-where-there-s-a-will-there-s-a-way': ('Có chí thì nên', None),
    'c2-rome-wasn-t-built-in-a-day': ('La Mã không xây xong trong một ngày', None),
    'c2-too-many-cooks-spoil-the-broth': ('Lắm thầy nhiều ma', None),
    'c2-out-of-sight-out-of-mind': ('Xa mặt cách lòng', None),
    'c2-look-before-you-leap': ('Suy nghĩ kỹ trước khi hành động', None),
    'c2-necessity-is-the-mother-of-invention': ('Cái khó ló cái khôn', None),
    'c2-you-can-t-have-your-cake-and-eat-it-too': ('Được cái này mất cái kia', None),
    'c2-honesty-is-the-best-policy': ('Thật thà là thượng sách', None),
    'c2-still-waters-run-deep': ('Tẩm ngẩm tầm ngầm mà đấm chết voi', None),
    'c2-blood-is-thicker-than-water': ('Một giọt máu đào hơn ao nước lã', None),
    'c2-absence-makes-the-heart-grow-fonder': ('Càng xa cách càng thêm nhớ nhung', None),
    'c2-every-dog-has-its-day': ('Ai giàu ba họ, ai khó ba đời', None),
    'c2-haste-makes-waste': ('Dục tốc bất đạt', None),
    'c2-let-sleeping-dogs-lie': ('Đừng khơi lại chuyện đã yên (chớ đánh thức chó đang ngủ)', None),
    'c2-strike-while-the-iron-is-hot': ('Đánh sắt khi còn nóng', None),
    'c2-the-pen-is-mightier-than-the-sword': ('Ngòi bút mạnh hơn lưỡi gươm', None),
    'c2-curiosity-killed-the-cat': ('Tò mò hại thân', None),
    'c2-beggars-can-t-be-choosers': ('Đã ăn mày thì đừng đòi hỏi', None),
    'c2-to-draw-a-distinction': ('Phân biệt rạch ròi', None),
    'c2-to-reach-a-verdict': ('Đưa ra phán quyết', None),
    'c2-to-pose-a-threat': ('Gây ra mối đe dọa', None),
    'c2-to-bear-the-brunt': ('Gánh chịu hậu quả nặng nề', None),
    'c2-to-lend-credence-to': ('Tăng thêm độ tin cậy cho', None),
    'c2-to-wield-influence': ('Nắm giữ ảnh hưởng', None),
    'c2-to-incur-a-cost': ('Phải chịu một khoản chi phí', None),
    'c2-to-uphold-a-principle': ('Giữ vững một nguyên tắc', None),
    'c2-to-exert-pressure': ('Gây áp lực', None),
    'c2-to-fulfil-an-obligation': ('Hoàn thành nghĩa vụ', None),
    'c2-to-cast-doubt-on': ('Gieo nghi ngờ về', None),
    'c2-to-pay-tribute-to': ('Bày tỏ lòng tôn kính với', None),
    'c2-to-take-precedence-over': ('Được ưu tiên hơn', None),
    'c2-to-run-the-risk-of': ('Chấp nhận rủi ro', None),
    'c2-to-strike-a-balance': ('Tìm được sự cân bằng', None),
    'c2-to-come-to-fruition': ('Đơm hoa kết trái (thành hiện thực)', None),
    'c2-to-shed-light-on': ('Làm sáng tỏ', None),
    'c2-to-set-a-precedent': ('Tạo tiền lệ', None),
    'c2-to-give-rise-to': ('Làm phát sinh', None),
    'c2-to-take-issue-with': ('Phản đối (không đồng tình với)', None),
    'c2-pursuant-to': ('Theo (căn cứ vào)', None),
    'c2-heretofore': ('Cho đến nay (trước đây)', None),
    'c2-inasmuch-as': ('Vì lẽ (bởi lẽ)', None),
    'c2-in-conjunction-with': ('Cùng với (kết hợp với)', None),
    'c2-hitherto': ('Cho tới lúc này', None),
    'c2-forthwith': ('Ngay lập tức', None),
    'c2-whilst': ('Trong khi (mặc dù)', None),
    'c2-wherein': ('Trong đó (ở chỗ đó)', None),
    'c2-vis-a-vis': ('Đối với (so với)', None),
    'c2-as-regards': ('Về phần (liên quan đến)', None),
    'c2-for-the-sake-of-argument': ('Giả sử như (để bàn luận)', None),
    'c2-be-that-as-it-may': ('Dù sao đi nữa', None),
    'c2-on-balance': ('Nhìn chung (cân nhắc kỹ)', None),
    'c2-at-the-behest-of': ('Theo yêu cầu của', None),
    'c2-in-the-wake-of': ('Ngay sau (do hệ quả của)', None),
    'c2-on-the-grounds-that': ('Với lý do rằng', None),
    'c2-in-accordance-with': ('Phù hợp với', None),
    'c2-pending': ('Đang chờ (chưa quyết định)', None),
    'c2-irrespective-of': ('Bất kể', None),
    'c2-hereinafter': ('Sau đây (kể từ đây)', None),
    'c2-beats-me': ('Chịu thua (không biết)', None),
    'c2-point-taken': ('Tôi hiểu ý bạn (có lý)', None),
    'c2-suit-yourself': ('Tùy bạn', None),
    'c2-go-figure': ('Ai mà biết được (thật khó hiểu)', None),
    'c2-don-t-get-me-started': ('Đừng có nhắc tới chuyện đó', None),
    'c2-bottom-line-is': ('Tóm lại là', None),
    'c2-off-the-top-of-my-head': ('Nghĩ ngay ra (không cần tra cứu)', None),
    'c2-i-ll-say': ('Đúng thế (còn phải nói)', None),
    'c2-you-ve-got-to-be-kidding-me': ('Đùa tôi à', None),
    'c2-no-offense-but': ('Không có ý xúc phạm, nhưng', None),
    'c2-i-m-not-gonna-lie': ('Nói thật thì', None),
    'c2-speak-of-the-devil': ('Nhắc Tào Tháo, Tào Tháo đến', None),
    'c2-it-s-on-the-tip-of-my-tongue': ('Nó cứ ở đầu lưỡi tôi', None),
    'c2-let-s-call-it-a-day': ('Thôi, tạm dừng ở đây', None),
    'c2-it-s-not-rocket-science': ('Có gì đâu mà khó', None),
    'c2-that-s-the-last-straw': ('Giọt nước tràn ly', None),
    'c2-i-couldn-t-care-less': ('Tôi chẳng quan tâm chút nào', None),
    'c2-what-are-the-odds': ('Trùng hợp thật đấy', None),
    'c2-say-no-more': ('Khỏi cần nói thêm', None),
    'c2-hang-in-there': ('Cố lên (ráng chịu đựng)', None),
    'c2-i-m-all-ears': ('Tôi đang lắng nghe đây', None),
    'c2-that-s-on-me': ('Đó là lỗi của tôi', None),
    'c2-no-hard-feelings': ('Không giận hờn gì', None),
    'c2-ditto': ('Y hệt (giống vậy)', None),
    'c2-spill-the-beans': ('Buột miệng nói ra bí mật', None),
    'c2-in-one-ear-and-out-the-other': ('Vào tai này ra tai kia', None),
    'c2-cut-to-the-chase': ('Đi thẳng vào vấn đề', None),
    'c2-you-name-it': ('Bất cứ thứ gì bạn nghĩ ra', None),
    'c2-not-in-a-million-years': ('Không đời nào', None),
    'c2-it-is-what-it-is': ('Sự đã rồi (thế nào cũng vậy)', None),
    'c2-give-me-a-break': ('Thôi đi mà (đừng làm phiền nữa)', None),
    'c2-hold-your-horses': ('Từ từ đã (khoan đã)', None),
    'c2-bite-the-bullet': ('Cắn răng chịu đựng', None),
    'c2-take-it-with-a-grain-of-salt': ('Đừng tin hết (nghe cho biết thôi)', None),
    'c2-better-safe-than-sorry': ('Cẩn tắc vô áy náy', None),
    'c2-let-s-play-it-by-ear': ('Tùy cơ ứng biến', None),
    'c2-i-ll-take-a-rain-check': ('Hẹn dịp khác vậy', None),
    'c2-for-what-it-s-worth': ('Nếu điều đó có ý nghĩa gì', None),
    'c2-back-to-square-one': ('Trở lại vạch xuất phát', None),
    'c2-touch-wood': ('Cầu mong không xui xẻo (gõ gỗ lấy hên)', None),
    'c2-allusion': ('Sự ám chỉ', None),
    'c2-anecdote': ('Giai thoại', None),
    'c2-antithesis': ('Phản đề (sự đối lập)', None),
    'c2-aphorism': ('Cách ngôn', None),
    'c2-banter': ('Trêu chọc thân mật', None),
    'c2-circumlocution': ('Lối nói vòng vo', None),
    'c2-cliche': ('Câu sáo ngữ', None),
    'c2-connotation': ('Hàm ý (nghĩa bóng)', None),
    'c2-digression': ('Sự lạc đề (nói lan man)', None),
    'c2-double-entendre': ('Câu nói hai nghĩa (song quan ngữ)', None),
    'c2-eloquence': ('Tài hùng biện', None),
    'c2-euphemism': ('Uyển ngữ', None),
    'c2-gist': ('Ý chính (cốt lõi)', None),
    'c2-hyperbole': ('Phép ngoa dụ (cường điệu)', None),
    'c2-irony': ('Sự mỉa mai (trớ trêu)', None),
    'c2-juxtaposition': ('Sự đặt cạnh nhau (tương phản)', None),
    'c2-malapropism': ('Lỗi dùng từ sai (nói nhầm từ)', None),
    'c2-oxymoron': ('Cách nói mâu thuẫn (nghịch hợp)', None),
    'c2-paraphrase': ('Diễn giải lại (nói bằng lời khác)', None),
    'c2-pun': ('Chơi chữ', None),
    'c2-quip': ('Câu nói dí dỏm', None),
    'c2-sarcasm': ('Sự châm biếm cay độc', None),
    'c2-slur-insult': ('Lời sỉ nhục (phỉ báng)', None),
    'c2-repartee': ('Lối đối đáp dí dỏm', None),
    'c2-soliloquy': ('Độc thoại', None),
    'c2-subtext': ('Hàm ý ngầm (trong văn bản)', None),
    'c2-tangent': ('Sự đi chệch chủ đề', None),
    'c2-tirade': ('Bài công kích dài dòng', None),
    'c2-understatement': ('Cách nói giảm nhẹ', None),
    'c2-verbiage': ('Lời lẽ dài dòng (rườm rà)', None),
    'c2-to-allude-to': ('Ám chỉ đến', None),
    'c2-to-enunciate': ('Phát âm rõ ràng', None),
    'c2-to-belabor-the-point': ('Nhấn đi nhấn lại một điểm', None),
    'c2-to-digress': ('Lạc đề (nói lan man)', None),
    'c2-to-expound': ('Giải thích cặn kẽ', None),
    'c2-to-insinuate': ('Ngụ ý (bóng gió)', None),
    'c2-to-interject': ('Xen vào (ngắt lời)', None),
    'c2-to-hammer-home': ('Nhấn mạnh triệt để', None),
    'c2-to-retort': ('Đáp trả (vặn lại)', None),
    'c2-to-waffle-be-vague': ('Nói vòng vo (mập mờ)', None),
    'c2-actuary': ('Chuyên viên định phí bảo hiểm', None),
    'c2-anesthesiologist': ('Bác sĩ gây mê', None),
    'c2-archivist': ('Nhân viên lưu trữ', None),
    'c2-auditor': ('Kiểm toán viên', None),
    'c2-bailiff': ('Thừa phát lại', None),
    'c2-blacksmith': ('Thợ rèn', None),
    'c2-cartographer': ('Nhà bản đồ học', None),
    'c2-chiropractor': ('Bác sĩ nắn chỉnh cột sống', None),
    'c2-coroner': ('Nhân viên điều tra pháp y', None),
    'c2-curator': ('Giám tuyển (bảo tàng)', None),
    'c2-diplomat': ('Nhà ngoại giao', None),
    'c2-dietitian': ('Chuyên gia dinh dưỡng', None),
    'c2-entomologist': ('Nhà côn trùng học', None),
    'c2-forensic-scientist': ('Nhà khoa học pháp y', None),
    'c2-geologist': ('Nhà địa chất học', None),
    'c2-glazier': ('Thợ lắp kính', None),
    'c2-interpreter-simultaneous': ('Phiên dịch viên (đồng thời)', None),
    'c2-locksmith': ('Thợ khóa', None),
    'c2-midwife': ('Nữ hộ sinh', None),
    'c2-court-clerk': ('Thư ký tòa án', None),
    'c2-oncologist': ('Bác sĩ ung bướu', None),
    'c2-ophthalmologist': ('Bác sĩ nhãn khoa', None),
    'c2-paleontologist': ('Nhà cổ sinh vật học', None),
    'c2-paralegal': ('Trợ lý pháp lý', None),
    'c2-pathologist': ('Bác sĩ giải phẫu bệnh', None),
    'c2-physiotherapist': ('Chuyên viên vật lý trị liệu', None),
    'c2-public-defender': ('Luật sư biện hộ chỉ định', None),
    'c2-radiologist': ('Bác sĩ chẩn đoán hình ảnh', None),
    'c2-perfumer': ('Nhà điều chế nước hoa', None),
    'c2-stenographer': ('Người tốc ký', None),
    'c2-surveyor': ('Kỹ sư trắc địa', None),
    'c2-taxidermist': ('Thợ nhồi tiêu bản động vật', None),
    'c2-upholsterer': ('Thợ bọc nệm', None),
    'c2-veterinarian-specialist': ('Bác sĩ thú y (chuyên khoa)', None),
    'c2-welder': ('Thợ hàn', None),
    'c2-anthropology': ('Nhân học', None),
    'c2-archaeology': ('Khảo cổ học', None),
    'c2-astrophysics': ('Vật lý thiên văn', None),
    'c2-biochemistry': ('Hóa sinh học', None),
    'c2-botany': ('Thực vật học', None),
    'c2-cartography': ('Bản đồ học', None),
    'c2-criminology': ('Tội phạm học', None),
    'c2-demography': ('Nhân khẩu học', None),
    'c2-econometrics': ('Kinh tế lượng', None),
    'c2-epidemiology': ('Dịch tễ học', None),
    'c2-epistemology': ('Nhận thức luận', None),
    'c2-ethnography': ('Dân tộc chí (mô tả dân tộc học)', None),
    'c2-genetics': ('Di truyền học', None),
    'c2-geopolitics': ('Địa chính trị', None),
    'c2-hermeneutics': ('Thông diễn học (chú giải học)', None),
    'c2-immunology': ('Miễn dịch học', None),
    'c2-jurisprudence': ('Lý luận pháp luật', None),
    'c2-linguistics': ('Ngôn ngữ học', None),
    'c2-metaphysics': ('Siêu hình học', None),
    'c2-meteorology': ('Khí tượng học', None),
    'c2-microbiology': ('Vi sinh học', None),
    'c2-musicology': ('Âm nhạc học', None),
    'c2-neuroscience': ('Khoa học thần kinh', None),
    'c2-oceanography': ('Hải dương học', None),
    'c2-ornithology': ('Điểu học', None),
    'c2-pedagogy': ('Sư phạm học', None),
    'c2-pharmacology': ('Dược lý học', None),
    'c2-philology': ('Ngữ văn học', None),
    'c2-phonetics': ('Ngữ âm học', None),
    'c2-seismology': ('Địa chấn học', None),
    'c2-semiotics': ('Ký hiệu học', None),
    'c2-sociolinguistics': ('Ngôn ngữ học xã hội', None),
    'c2-theology': ('Thần học', None),
    'c2-toxicology': ('Độc chất học', None),
    'c2-zoology': ('Động vật học', None),
    'c2-acute-sudden-severe': ('Cấp tính', None),
    'c2-latent': ('Tiềm ẩn (chưa biểu hiện)', None),
    'c2-benign': ('Lành tính', None),
    'c2-malignant': ('Ác tính', None),
    'c2-biopsy': ('Sinh thiết', None),
    'c2-prognosis': ('Tiên lượng', None),
    'c2-flare-up': ('Đợt bùng phát (bệnh)', None),
    'c2-recurrence': ('Sự tái phát', None),
    'c2-sedative': ('Thuốc an thần', None),
    'c2-anesthetic': ('Thuốc gây mê (tê)', None),
    'c2-antibody': ('Kháng thể', None),
    'c2-inflammation': ('Sự viêm', None),
    'c2-airborne': ('Lây qua không khí', None),
    'c2-hereditary': ('Di truyền', None),
    'c2-congenital': ('Bẩm sinh', None),
    'c2-dosage': ('Liều lượng', None),
    'c2-placebo': ('Giả dược', None),
    'c2-contraindication': ('Chống chỉ định', None),
    'c2-intravenous': ('Qua đường tĩnh mạch', None),
    'c2-suture': ('Mũi khâu (chỉ khâu)', None),
    'c2-incision': ('Vết mổ (đường rạch)', None),
    'c2-donor': ('Người hiến tặng', None),
    'c2-ultrasound': ('Siêu âm', None),
    'c2-referral-to-a-specialist': ('Giấy chuyển khám chuyên khoa', None),
    'c2-inpatient': ('Bệnh nhân nội trú', None),
    'c2-palliative-care': ('Chăm sóc giảm nhẹ', None),
    'c2-triage': ('Phân loại cấp cứu (sàng lọc)', None),
    'c2-convalescence': ('Thời kỳ dưỡng bệnh', None),
    'c2-immunity': ('Khả năng miễn dịch', None),
    'c2-pandemic': ('Đại dịch', None),
    'c2-pathogen': ('Mầm bệnh', None),
    'c2-electrolyte': ('Chất điện giải', None),
    'c2-cardiovascular': ('Tim mạch', None),
    'c2-respiratory': ('Hô hấp', None),
    'c2-neurological': ('Thuộc hệ thần kinh', None),
    'c2-symptomatic': ('Có triệu chứng', None),
    'c2-asymptomatic': ('Không có triệu chứng', None),
    'c2-prescription-written-order': ('Đơn thuốc', None),
    'c2-generic-drug': ('Thuốc gốc (không thương hiệu)', None),
    'c2-informed-consent': ('Sự đồng thuận sau khi được giải thích', None),
    'c2-acquittal': ('Sự tuyên trắng án', None),
    'c2-conviction-guilty-verdict': ('Bản án kết tội', None),
    'c2-deposition': ('Lời khai có tuyên thệ', None),
    'c2-accessory-to-a-crime': ('Kẻ đồng lõa', None),
    'c2-arson': ('Tội đốt phá (phóng hỏa)', None),
    'c2-remand': ('Tạm giam (chờ xét xử)', None),
    'c2-burden-of-proof': ('Nghĩa vụ chứng minh', None),
    'c2-custody-detention': ('Sự tạm giữ', None),
    'c2-defendant': ('Bị cáo', None),
    'c2-plaintiff': ('Nguyên đơn', None),
    'c2-embezzlement': ('Tội biển thủ', None),
    'c2-extortion': ('Tội tống tiền', None),
    'c2-felony': ('Trọng tội', None),
    'c2-misdemeanor': ('Khinh tội (tội nhẹ)', None),
    'c2-forgery': ('Tội giả mạo', None),
    'c2-hearsay': ('Lời khai gián tiếp (nghe kể lại)', None),
    'c2-indictment': ('Cáo trạng', None),
    'c2-injunction': ('Lệnh cấm của tòa', None),
    'c2-tribunal': ('Hội đồng xét xử', None),
    'c2-libel': ('Phỉ báng bằng văn bản', None),
    'c2-slander': ('Vu khống bằng lời nói', None),
    'c2-manslaughter': ('Tội ngộ sát', None),
    'c2-parole': ('Tha tù có điều kiện', None),
    'c2-perjury': ('Tội khai man', None),
    'c2-plea-bargain': ('Thỏa thuận nhận tội', None),
    'c2-probation': ('Án treo (quản chế)', None),
    'c2-racketeering': ('Hoạt động băng nhóm tống tiền', None),
    'c2-ransom': ('Tiền chuộc', None),
    'c2-statute': ('Đạo luật', None),
    'c2-statute-of-limitations': ('Thời hiệu truy tố', None),
    'c2-subpoena': ('Trát đòi hầu tòa', None),
    'c2-testimony': ('Lời khai (làm chứng)', None),
    'c2-ruling': ('Phán quyết', None),
    'c2-warrant': ('Lệnh bắt giữ (khám xét)', None),
    'c2-witness-stand': ('Bục nhân chứng', None),
    'c2-contempt-of-court': ('Tội coi thường tòa án', None),
    'c2-cross-examination': ('Thẩm vấn chéo', None),
    'c2-mistrial': ('Phiên tòa bị hủy (sai thủ tục)', None),
    'c2-sentence-punishment': ('Bản án (hình phạt)', None),
    'c2-to-plead-guilty': ('Nhận tội', None),
    'c2-thicket': ('Bụi rậm', None),
    'c2-undergrowth': ('Tầng cây bụi dưới tán rừng', None),
    'c2-moss': ('Rêu', None),
    'c2-lichen': ('Địa y', None),
    'c2-fern': ('Dương xỉ', None),
    'c2-sap': ('Nhựa cây', None),
    'c2-bark-of-a-tree': ('Vỏ cây', None),
    'c2-sapling': ('Cây non', None),
    'c2-canopy-forest': ('Tán rừng', None),
    'c2-grove': ('Lùm cây (rừng nhỏ)', None),
    'c2-meadow': ('Đồng cỏ', None),
    'c2-marsh': ('Đầm lầy', None),
    'c2-bog': ('Đầm lầy than bùn', None),
    'c2-estuary': ('Cửa sông', None),
    'c2-tributary': ('Chi lưu (sông nhánh)', None),
    'c2-ravine': ('Khe núi', None),
    'c2-gorge': ('Hẻm núi sâu', None),
    'c2-ridge': ('Sống núi (dãy núi)', None),
    'c2-summit': ('Đỉnh núi', None),
    'c2-foothills': ('Chân núi (vùng đồi thấp)', None),
    'c2-escarpment': ('Vách đá dốc', None),
    'c2-salt-flat': ('Đồng muối khô', None),
    'c2-cove': ('Vịnh nhỏ', None),
    'c2-atoll': ('Đảo san hô vòng', None),
    'c2-tide-pool': ('Vũng nước thủy triều', None),
    'c2-driftwood': ('Gỗ trôi dạt', None),
    'c2-pebble': ('Sỏi', None),
    'c2-boulder': ('Tảng đá lớn', None),
    'c2-sediment': ('Trầm tích', None),
    'c2-erosion': ('Sự xói mòn', None),
    'c2-burrow': ('Hang (thú đào)', None),
    'c2-hive': ('Tổ ong', None),
    'c2-cocoon': ('Kén', None),
    'c2-antler': ('Gạc (sừng hươu)', None),
    'c2-talon': ('Móng vuốt (chim săn mồi)', None),
    'c2-plumage': ('Bộ lông vũ', None),
    'c2-migration-animal': ('Sự di cư', None),
    'c2-hibernation': ('Sự ngủ đông', None),
    'c2-pollination': ('Sự thụ phấn', None),
    'c2-germination': ('Sự nảy mầm', None),
    'c2-torrential': ('Xối xả (như trút nước)', None),
    'c2-monsoon': ('Gió mùa', None),
    'c2-sleet': ('Mưa tuyết', None),
    'c2-flurry-snow': ('Trận tuyết rơi nhẹ', None),
    'c2-whiteout': ('Mất tầm nhìn vì tuyết trắng xóa', None),
    'c2-black-ice': ('Băng đen (trên mặt đường)', None),
    'c2-dew': ('Sương', None),
    'c2-haze': ('Sương mù nhẹ (bụi mờ)', None),
    'c2-clammy': ('Ẩm dính (lạnh nhớp)', None),
    'c2-scorcher': ('Ngày nắng như thiêu đốt', None),
    'c2-sultry': ('Oi bức', None),
    'c2-balmy': ('Ôn hòa (dễ chịu)', None),
    'c2-crisp-air': ('Trong lành se lạnh', None),
    'c2-gust': ('Cơn gió giật', None),
    'c2-gale': ('Gió lớn (cuồng phong)', None),
    'c2-squall': ('Gió giật kèm mưa', None),
    'c2-thunderclap': ('Tiếng sấm rền', None),
    'c2-lightning-bolt': ('Tia sét', None),
    'c2-cloudburst': ('Mưa như trút nước đột ngột', None),
    'c2-nightfall': ('Lúc đêm buông xuống', None),
    'c2-cold-snap': ('Đợt lạnh đột ngột', None),
    'c2-thaw': ('Sự tan băng', None),
    'c2-humidity': ('Độ ẩm', None),
    'c2-barometer': ('Khí áp kế', None),
    'c2-forecast-verb': ('Dự báo', None),
    'c2-daybreak': ('Lúc rạng đông', None),
    'c2-aurora': ('Cực quang', None),
    'c2-twilight': ('Chạng vạng (hoàng hôn)', None),
    'c2-solstice': ('Điểm chí (hạ chí/đông chí)', None),
    'c2-equinox': ('Điểm phân', None),
    'c2-arch': ('Vòm cong', None),
    'c2-vault-ceiling': ('Trần vòm', None),
    'c2-dome': ('Mái vòm tròn', None),
    'c2-spire': ('Chóp nhọn (tháp)', None),
    'c2-buttress': ('Trụ chống đỡ', None),
    'c2-pillar': ('Cột trụ', None),
    'c2-column': ('Cột (kiến trúc)', None),
    'c2-beam-structural': ('Dầm (xà nhà)', None),
    'c2-rafter': ('Rui mái (kèo)', None),
    'c2-girder': ('Dầm chính', None),
    'c2-keystone': ('Đá đỉnh vòm', None),
    'c2-facade-building-front': ('Mặt tiền công trình', None),
    'c2-cornice': ('Gờ mái (phào chỉ)', None),
    'c2-gable': ('Đầu hồi', None),
    'c2-eaves': ('Mái hiên (rìa mái)', None),
    'c2-gutter-roof': ('Máng xối', None),
    'c2-skylight': ('Giếng trời (cửa sổ mái)', None),
    'c2-balustrade': ('Lan can trang trí', None),
    'c2-parapet': ('Tường chắn mái (lan can)', None),
    'c2-turret': ('Tháp nhỏ', None),
    'c2-moat': ('Hào nước', None),
    'c2-drawbridge': ('Cầu treo (cầu kéo)', None),
    'c2-cloister': ('Hành lang tu viện', None),
    'c2-courtyard': ('Sân trong', None),
    'c2-alcove': ('Hốc tường', None),
    'c2-mezzanine': ('Gác lửng', None),
    'c2-atrium': ('Sảnh trong (giếng trời)', None),
    'c2-mosaic': ('Tranh khảm', None),
    'c2-fresco': ('Tranh bích họa', None),
    'c2-elevation-drawing': ('Bản vẽ mặt đứng', None),
    'c2-partition-wall': ('Tường ngăn', None),
    'c2-cladding': ('Lớp ốp ngoài', None),
    'c2-plumbing-system': ('Hệ thống ống nước', None),
    'c2-ventilation-duct': ('Ống thông gió', None),
    'c2-retrofit': ('Cải tạo nâng cấp', None),
    'c2-colander': ('Rổ lọc', None),
    'c2-ladle': ('Muôi (vá)', None),
    'c2-whisk': ('Phới lồng (đánh trứng)', None),
    'c2-grater': ('Dụng cụ bào (nạo)', None),
    'c2-tongs': ('Kẹp gắp', None),
    'c2-spatula': ('Xẻng lật (nấu ăn)', None),
    'c2-cutting-board': ('Thớt', None),
    'c2-french-press': ('Bình pha cà phê kiểu ép', None),
    'c2-coaster': ('Lót ly', None),
    'c2-trivet': ('Đế lót nồi nóng', None),
    'c2-oven-mitt': ('Găng tay lò nướng', None),
    'c2-dish-rack': ('Giá để bát đĩa', None),
    'c2-dustpan': ('Đồ hốt rác', None),
    'c2-mop': ('Cây lau nhà', None),
    'c2-clothespin': ('Kẹp phơi đồ', None),
    'c2-clothesline': ('Dây phơi đồ', None),
    'c2-shoehorn': ('Cái đón giày', None),
    'c2-doormat': ('Thảm chùi chân', None),
    'c2-doorknob': ('Núm cửa', None),
    'c2-hinge': ('Bản lề', None),
    'c2-latch': ('Chốt cửa', None),
    'c2-peephole': ('Mắt thần cửa', None),
    'c2-blinds-window': ('Rèm sáo (mành)', None),
    'c2-windowsill': ('Bệ cửa sổ', None),
    'c2-banister': ('Tay vịn cầu thang', None),
    'c2-landing-stairs': ('Chiếu nghỉ cầu thang', None),
    'c2-crawl-space': ('Khoảng trống dưới sàn nhà', None),
    'c2-cellar': ('Tầng hầm (hầm chứa)', None),
    'c2-pantry': ('Phòng chứa thực phẩm', None),
    'c2-utility-room': ('Phòng giặt (phòng phụ)', None),
    'c2-fuse-box': ('Hộp cầu chì (tủ điện)', None),
    'c2-dimmer-switch': ('Công tắc chỉnh độ sáng', None),
    'c2-extension-cord': ('Dây nối dài (ổ cắm)', None),
    'c2-power-strip': ('Ổ cắm điện nhiều lỗ', None),
    'c2-carbon-monoxide-alarm': ('Máy báo khí carbon monoxide', None),
    'c2-first-aid-kit': ('Hộp sơ cứu', None),
    'c2-sewing-kit': ('Bộ đồ khâu vá', None),
    'c2-toolbox': ('Hộp dụng cụ', None),
    'c2-allen-key': ('Chìa khóa lục giác', None),
    'c2-pliers': ('Kìm', None),
    'c2-wrench': ('Cờ lê (mỏ lết)', None),
    'c2-tape-measure': ('Thước dây', None),
    'c2-spirit-level': ('Thước thủy (ni vô)', None),
    'c2-drawer-organizer': ('Hộp chia ngăn kéo', None),
    'c2-bin-liner': ('Túi lót thùng rác', None),
    'c2-to-seethe': ('Sôi sục (giận dữ)', None),
    'c2-to-sulk': ('Hờn dỗi', None),
    'c2-to-fret': ('Lo lắng bồn chồn', None),
    'c2-to-brood': ('Nghiền ngẫm (u sầu)', None),
    'c2-to-wallow-in-self-pity': ('Đắm chìm trong tự thương hại', None),
    'c2-to-gloat-over-a-rival': ('Hả hê trước đối thủ', None),
    'c2-to-savor-the-moment': ('Tận hưởng (khoảnh khắc)', None),
    'c2-to-revel-in': ('Đắm mình tận hưởng', None),
    'c2-to-marvel-at': ('Trầm trồ thán phục', None),
    'c2-to-cringe': ('Co rúm (ngượng ngùng)', None),
    'c2-to-wince': ('Nhăn mặt (vì đau)', None),
    'c2-to-flinch': ('Giật mình né tránh', None),
    'c2-to-shudder': ('Rùng mình (ớn lạnh)', None),
    'c2-to-quiver': ('Run rẩy', None),
    'c2-to-swoon': ('Ngất xỉu (vì xúc động)', None),
    'c2-to-pine-for': ('Khắc khoải nhớ mong', None),
    'c2-to-long-for': ('Mong mỏi da diết', None),
    'c2-to-crave': ('Thèm khát', None),
    'c2-to-abominate': ('Căm ghét tột độ', None),
    'c2-to-nurse-a-grievance': ('Nuôi mối hận', None),
    'c2-to-begrudge': ('Tiếc rẻ (không muốn cho)', None),
    'c2-to-grovel': ('Khúm núm quỵ lụy', None),
    'c2-to-fawn-over': ('Nịnh nọt tâng bốc', None),
    'c2-to-dote-on': ('Cưng chiều hết mực', None),
    'c2-to-treasure': ('Trân quý', None),
    'c2-to-put-at-ease': ('Trấn an (làm yên lòng)', None),
    'c2-to-console': ('An ủi', None),
    'c2-to-commiserate': ('Đồng cảm (chia sẻ nỗi buồn)', None),
    'c2-to-exasperate': ('Làm phát cáu', None),
    'c2-to-infuriate': ('Làm nổi giận', None),
    'c2-to-unnerve': ('Làm mất bình tĩnh', None),
    'c2-to-mortify': ('Làm bẽ mặt', None),
    'c2-to-captivate': ('Mê hoặc', None),
    'c2-to-enrapture': ('Làm ngây ngất', None),
    'c2-to-disillusion': ('Làm vỡ mộng', None),
    'c2-to-mollify': ('Làm dịu bớt', None),
    'c2-to-embolden': ('Tiếp thêm can đảm', None),
    'c2-to-dishearten': ('Làm nản lòng', None),
    'c2-to-rankle': ('Nhức nhối (âm ỉ khó chịu)', None),
    'c2-to-smolder': ('Âm ỉ cháy (dồn nén)', None),
    'c2-numbness': ('Sự tê cóng', None),
    'c2-tingling': ('Cảm giác râm ran', None),
    'c2-cramp': ('Chuột rút', None),
    'c2-twinge': ('Cơn đau nhói', None),
    'c2-throbbing': ('Đau giật theo nhịp', None),
    'c2-dizziness': ('Chóng mặt', None),
    'c2-lightheaded': ('Choáng váng (lâng lâng)', None),
    'c2-vertigo': ('Chứng chóng mặt xoay tròn', None),
    'c2-queasy': ('Buồn nôn (lợm giọng)', None),
    'c2-lethargy': ('Tình trạng lừ đừ (uể oải)', None),
    'c2-fatigue': ('Sự mệt mỏi (kiệt sức)', None),
    'c2-stamina': ('Sức bền', None),
    'c2-reflex': ('Phản xạ', None),
    'c2-flinch-noun': ('Cái giật mình né tránh', None),
    'c2-pins-and-needles': ('Cảm giác kim châm (tê rần)', None),
    'c2-shiver': ('Cơn rùng mình', None),
    'c2-hot-flush': ('Cơn bốc hỏa', None),
    'c2-blush': ('Sự đỏ mặt', None),
    'c2-yawn': ('Cái ngáp', None),
    'c2-hiccup': ('Nấc cụt', None),
    'c2-sneeze': ('Cái hắt hơi', None),
    'c2-itch': ('Cơn ngứa', None),
    'c2-bruise': ('Vết bầm tím', None),
    'c2-blister': ('Vết phồng rộp', None),
    'c2-pulled-muscle': ('Căng cơ', None),
    'c2-stiffness': ('Sự cứng mỏi (ê ẩm)', None),
    'c2-restlessness': ('Sự bồn chồn không yên', None),
    'c2-daydream': ('Mơ mộng giữa ban ngày', None),
    'c2-deja-vu': ('Cảm giác đã từng trải qua (déjà vu)', None),
    'c2-hunch': ('Linh cảm', None),
    'c2-gut-feeling': ('Trực giác mách bảo', None),
    'c2-brain-fog': ('Đầu óc mụ mị', None),
    'c2-second-wind': ('Luồng sinh lực thứ hai', None),
    'c2-adrenaline-rush': ('Cơn dồn adrenaline', None),
    'c2-motion-sickness': ('Say tàu xe', None),
    'c2-camaraderie': ('Tình đồng đội (thân thiết)', None),
    'c2-affinity-between-people': ('Sự tương hợp (hợp gu)', None),
    'c2-clique': ('Bè phái (nhóm khép kín)', None),
    'c2-entourage': ('Đoàn tùy tùng', None),
    'c2-etiquette': ('Phép xã giao', None),
    'c2-faux-pas': ('Sự thất thố (hớ hênh)', None),
    'c2-gossip': ('Chuyện ngồi lê đôi mách', None),
    'c2-grudge': ('Mối hận (dai dẳng)', None),
    'c2-chain-of-command': ('Hệ thống cấp bậc chỉ huy', None),
    'c2-nepotism': ('Chủ nghĩa gia đình trị', None),
    'c2-ostracism': ('Sự tẩy chay (khai trừ)', None),
    'c2-groupthink': ('Tư duy bầy đàn', None),
    'c2-pecking-order': ('Thứ bậc trong nhóm', None),
    'c2-rivalry': ('Sự kình địch', None),
    'c2-solidarity': ('Tinh thần đoàn kết', None),
    'c2-snub': ('Sự phớt lờ (cố ý)', None),
    'c2-taboo': ('Điều cấm kỵ', None),
    'c2-flattery': ('Lời nịnh hót', None),
    'c2-backhanded-compliment': ('Lời khen mỉa mai', None),
    'c2-cold-shoulder': ('Thái độ lạnh nhạt', None),
    'c2-small-circle-inner-circle': ('Nhóm thân cận', None),
    'c2-interloper': ('Kẻ xen vào (chen chân)', None),
    'c2-old-hand': ('Người lão luyện (kỳ cựu)', None),
    'c2-wingman': ('Người hộ tống (bạn đồng hành)', None),
    'c2-freeloader': ('Kẻ ăn bám', None),
    'c2-busybody': ('Kẻ nhiều chuyện (xen vào việc người khác)', None),
    'c2-killjoy': ('Kẻ phá đám', None),
    'c2-show-off': ('Kẻ khoe khoang', None),
    'c2-pushover': ('Người dễ bắt nạt (nhu nhược)', None),
    'c2-self-starter': ('Người chủ động (tự giác)', None),
    'c2-to-mingle': ('Hòa nhập (giao lưu)', None),
    'c2-to-schmooze': ('Bắt chuyện lấy lòng (xã giao)', None),
    'c2-to-shun': ('Lảng tránh (xa lánh)', None),
    'c2-to-patronize': ('Ra vẻ kẻ cả', None),
    'c2-to-reconcile': ('Hòa giải', None),
    'c2-to-estrange': ('Làm xa cách', None),
    'c2-to-confide-in': ('Tâm sự (thổ lộ)', None),
    'c2-to-hobnob': ('Giao du thân mật', None),
    'c2-to-rub-shoulders-with': ('Giao du (với người có địa vị)', None),
    'c2-to-fall-out-with': ('Bất hòa với', None),
    'c2-foil-character': ('Nhân vật đối lập (làm nền)', None),
    'c2-anti-hero': ('Phản anh hùng', None),
    'c2-narrator': ('Người kể chuyện', None),
    'c2-macguffin': ('Vật dẫn truyện (MacGuffin)', None),
    'c2-red-herring': ('Manh mối đánh lạc hướng', None),
    'c2-motif': ('Mô típ chủ đề', None),
    'c2-frame-narrative': ('Truyện lồng khung', None),
    'c2-denouement': ('Phần kết thúc (gỡ nút truyện)', None),
    'c2-satire': ('Trào phúng', None),
    'c2-parody': ('Nhại (giễu nhại)', None),
    'c2-allegory': ('Phúng dụ', None),
    'c2-memoir': ('Hồi ký', None),
    'c2-anthology': ('Tuyển tập', None),
    'c2-manuscript': ('Bản thảo viết tay', None),
    'c2-prose': ('Văn xuôi', None),
    'c2-couplet': ('Cặp câu thơ', None),
    'c2-stanza': ('Khổ thơ', None),
    'c2-sonnet': ('Thơ xon-nê', None),
    'c2-alliteration': ('Phép điệp âm đầu', None),
    'c2-meter-poetry': ('Luật thơ (nhịp điệu)', None),
    'c2-aesthetic': ('Mỹ học (thẩm mỹ)', None),
    'c2-avant-garde': ('Trường phái tiên phong', None),
    'c2-baroque': ('Phong cách Baroque', None),
    'c2-impressionism': ('Trường phái ấn tượng', None),
    'c2-surrealism': ('Trường phái siêu thực', None),
    'c2-still-life': ('Tranh tĩnh vật', None),
    'c2-charcoal-drawing': ('Tranh vẽ bằng than', None),
    'c2-etching': ('Tranh khắc axit', None),
    'c2-bust-sculpture': ('Tượng bán thân', None),
    'c2-chisel': ('Cái đục (điêu khắc)', None),
    'c2-easel': ('Giá vẽ', None),
    'c2-palette': ('Bảng pha màu', None),
    'c2-overture': ('Khúc dạo đầu', None),
    'c2-aria': ('Khúc độc xướng (aria)', None),
    'c2-encore': ('Diễn thêm (theo yêu cầu)', None),
    'c2-bandwidth': ('Băng thông', None),
    'c2-jitter': ('Độ rung trễ tín hiệu', None),
    'c2-throughput': ('Thông lượng (tốc độ xử lý)', None),
    'c2-hashing': ('Băm dữ liệu (hàm băm)', None),
    'c2-intrusion-detection': ('Phát hiện xâm nhập', None),
    'c2-vulnerability-security': ('Lỗ hổng bảo mật', None),
    'c2-hotfix': ('Bản vá khẩn cấp', None),
    'c2-backlog': ('Việc tồn đọng', None),
    'c2-rollout': ('Triển khai (tung ra)', None),
    'c2-rollback': ('Khôi phục về trước', None),
    'c2-uptime': ('Thời gian hoạt động liên tục', None),
    'c2-redundancy-backup': ('Hệ thống dự phòng', None),
    'c2-load-balancing': ('Cân bằng tải', None),
    'c2-legacy-system': ('Hệ thống cũ (kế thừa)', None),
    'c2-copyleft': ('Giấy phép chia sẻ tự do (copyleft)', None),
    'c2-proprietary': ('Độc quyền (sở hữu riêng)', None),
    'c2-interoperability': ('Khả năng liên thông', None),
    'c2-passkey': ('Khóa truy cập', None),
    'c2-social-engineering': ('Kỹ thuật thao túng tâm lý', None),
    'c2-data-breach': ('Vụ rò rỉ dữ liệu', None),
    'c2-cache': ('Bộ nhớ đệm', None),
    'c2-query': ('Truy vấn', None),
    'c2-metadata': ('Siêu dữ liệu', None),
    'c2-placeholder': ('Chỗ giữ trống', None),
    'c2-workaround': ('Giải pháp tạm thời (lách qua)', None),
    'c2-bottleneck': ('Nút thắt cổ chai', None),
    'c2-edge-case': ('Trường hợp biên', None),
    'c2-deprecated': ('Đã lỗi thời (ngừng hỗ trợ)', None),
    'c2-sandbox': ('Môi trường thử nghiệm cách ly', None),
    'c2-telemetry': ('Đo lường từ xa', None),
    'c2-algorithmic-bias': ('Thiên kiến thuật toán', None),
    'c2-overfitting': ('Quá khớp (học vẹt dữ liệu)', None),
    'c2-large-language-model': ('Mô hình ngôn ngữ lớn', None),
    'c2-quantum-computing': ('Điện toán lượng tử', None),
    'c2-semiconductor': ('Chất bán dẫn', None),
    'c2-working-capital': ('Vốn lưu động', None),
    'c2-solvency': ('Khả năng thanh toán', None),
    'c2-insolvency': ('Mất khả năng thanh toán', None),
    'c2-receivership': ('Sự quản lý tài sản theo lệnh tòa', None),
    'c2-leverage-finance': ('Đòn bẩy tài chính', None),
    'c2-hedge-finance': ('Biện pháp phòng ngừa rủi ro', None),
    'c2-yield-finance': ('Lợi suất', None),
    'c2-share-buyback': ('Mua lại cổ phiếu', None),
    'c2-equity-ownership': ('Vốn chủ sở hữu', None),
    'c2-treasury-bill': ('Tín phiếu kho bạc', None),
    'c2-asset-allocation': ('Phân bổ tài sản', None),
    'c2-volatility': ('Mức độ biến động (giá)', None),
    'c2-bull-market': ('Thị trường giá lên', None),
    'c2-bear-market': ('Thị trường giá xuống', None),
    'c2-downturn': ('Suy thoái (đà đi xuống)', None),
    'c2-stagflation': ('Lạm phát đình trệ', None),
    'c2-deflation': ('Giảm phát', None),
    'c2-interest-rate-hike': ('Việc tăng lãi suất', None),
    'c2-fiscal-policy': ('Chính sách tài khóa', None),
    'c2-monetary-policy': ('Chính sách tiền tệ', None),
    'c2-subsidy': ('Trợ cấp', None),
    'c2-trade-quota': ('Hạn ngạch thương mại', None),
    'c2-embargo': ('Lệnh cấm vận', None),
    'c2-belt-tightening': ('Thắt lưng buộc bụng', None),
    'c2-bailout': ('Gói cứu trợ tài chính', None),
    'c2-windfall': ('Khoản lợi bất ngờ', None),
    'c2-nest-egg': ('Khoản tiền dành dụm', None),
    'c2-slush-fund': ('Quỹ đen', None),
    'c2-kickback': ('Tiền lại quả (bất hợp pháp)', None),
    'c2-money-laundering': ('Rửa tiền', None),
    'c2-tax-evasion': ('Trốn thuế', None),
    'c2-tax-loophole': ('Kẽ hở thuế', None),
    'c2-underwriter': ('Nhà bảo lãnh (phát hành/bảo hiểm)', None),
    'c2-sinking-fund': ('Quỹ dự phòng trả nợ', None),
    'c2-arbitrage': ('Kinh doanh chênh lệch giá', None),
    'c2-freight': ('Hàng hóa vận chuyển', None),
    'c2-cargo-hold': ('Khoang chở hàng', None),
    'c2-consignment': ('Lô hàng ký gửi', None),
    'c2-customs-clearance': ('Thủ tục thông quan', None),
    'c2-red-eye-flight': ('Chuyến bay đêm', None),
    'c2-turbulence': ('Nhiễu động không khí', None),
    'c2-taxiing': ('Lăn bánh trên đường băng', None),
    'c2-cockpit': ('Buồng lái', None),
    'c2-overhead-compartment': ('Khoang hành lý trên đầu', None),
    'c2-aisle-seat': ('Ghế cạnh lối đi', None),
    'c2-boarding-pass': ('Thẻ lên máy bay', None),
    'c2-baggage-carousel': ('Băng chuyền hành lý', None),
    'c2-jet-bridge': ('Cầu ống lồng (lên máy bay)', None),
    'c2-tailgating-driving': ('Bám sát đuôi xe (quá gần)', None),
    'c2-gridlock': ('Tắc nghẽn giao thông hoàn toàn', None),
    'c2-diversion-route': ('Đường vòng tránh', None),
    'c2-interchange-highway': ('Nút giao thông', None),
    'c2-overpass': ('Cầu vượt', None),
    'c2-underpass': ('Hầm chui', None),
    'c2-toll-booth': ('Trạm thu phí', None),
    'c2-hard-shoulder': ('Làn đường khẩn cấp', None),
    'c2-speed-bump': ('Gờ giảm tốc', None),
    'c2-blind-spot': ('Điểm mù', None),
    'c2-hazard-lights': ('Đèn cảnh báo khẩn cấp', None),
    'c2-windshield-wiper': ('Cần gạt nước', None),
    'c2-clutch-car': ('Bộ ly hợp (côn xe)', None),
    'c2-handbrake': ('Phanh tay', None),
    'c2-odometer': ('Đồng hồ đo quãng đường', None),
    'c2-tow-truck': ('Xe cẩu kéo', None),
    'c2-commute-noun': ('Quãng đường đi làm', None),
    'c2-numerator': ('Tử số', None),
    'c2-denominator': ('Mẫu số', None),
    'c2-exponent': ('Số mũ', None),
    'c2-square-root': ('Căn bậc hai', None),
    'c2-decimal-point': ('Dấu thập phân', None),
    'c2-remainder': ('Số dư', None),
    'c2-prime-number': ('Số nguyên tố', None),
    'c2-integer': ('Số nguyên', None),
    'c2-quotient': ('Thương số', None),
    'c2-percentile': ('Bách phân vị', None),
    'c2-mean-average': ('Giá trị trung bình', None),
    'c2-median': ('Trung vị', None),
    'c2-outlier': ('Giá trị ngoại lai', None),
    'c2-standard-deviation': ('Độ lệch chuẩn', None),
    'c2-variance': ('Phương sai', None),
    'c2-margin-of-error': ('Biên độ sai số', None),
    'c2-sample-size': ('Kích thước mẫu', None),
    'c2-exponential-growth': ('Tăng trưởng theo cấp số mũ', None),
    'c2-order-of-magnitude': ('Bậc độ lớn', None),
    'c2-rounding': ('Phép làm tròn', None),
    'c2-percentage-point': ('Điểm phần trăm', None),
    'c2-threefold': ('Gấp ba lần', None),
    'c2-a-dozen': ('Một tá', None),
    'c2-round-number': ('Số tròn', None),
    'c2-odds-probability': ('Tỷ lệ cược (xác suất)', None),
    'c2-inseam': ('Độ dài đũng quần', None),
    'c2-dart-sewing': ('Đường chiết ly', None),
    'c2-lapel': ('Ve áo', None),
    'c2-cuff': ('Cổ tay áo', None),
    'c2-cufflinks': ('Khuy măng-sét', None),
    'c2-gusset': ('Miếng vá nêm (gia cố)', None),
    'c2-pleat': ('Nếp gấp (ly xếp)', None),
    'c2-tailored': ('May đo', None),
    'c2-bespoke': ('Đặt may riêng theo yêu cầu', None),
    'c2-off-the-rack': ('May sẵn', None),
    'c2-threadbare': ('Sờn rách (mòn chỉ)', None),
    'c2-frayed': ('Tưa chỉ (bị sờn ở mép)', None),
    'c2-creased': ('Nhăn nhúm', None),
    'c2-dapper': ('Bảnh bao', None),
    'c2-disheveled': ('Bù xù (luộm thuộm)', None),
    'c2-scruffy': ('Lôi thôi (nhếch nhác)', None),
    'c2-garish': ('Lòe loẹt', None),
    'c2-understated': ('Kín đáo tinh tế', None),
    'c2-flattering-clothes': ('Tôn dáng', None),
    'c2-baggy': ('Rộng thùng thình', None),
    'c2-snug': ('Bó sát vừa vặn', None),
    'c2-stubble': ('Râu lún phún', None),
    'c2-freckles': ('Tàn nhang', None),
    'c2-dimple': ('Lúm đồng tiền', None),
    'c2-crow-s-feet': ('Vết chân chim (nếp nhăn đuôi mắt)', None),
    'c2-complexion': ('Làn da mặt', None),
    'c2-gaunt': ('Gầy trơ xương', None),
    'c2-stocky': ('Vạm vỡ (thấp đậm)', None),
    'c2-lanky': ('Cao lêu nghêu', None),
    'c2-poised': ('Điềm tĩnh, tự tin', None),
}
