# -*- coding: utf-8 -*-
LANG = 'ar'
WORDS = {
    'c2-to-abate': ('خفّ', 'khaffa'),
    'c2-to-abhor': ('مقت', 'maqata'),
    'c2-to-abstain': ('امتنع', "imtana'a"),
    'c2-to-accentuate': ('أبرز', 'abraza'),
    'c2-to-acquiesce': ('رضخ', 'radikha'),
    'c2-to-admonish': ('أنّب', 'annaba'),
    'c2-to-alleviate': ('خفّف', 'khaffafa'),
    'c2-to-amass': ('كدّس', 'kaddasa'),
    'c2-to-appease': ('هدّأ', "hadda'a"),
    'c2-to-ascribe': ('عزا', "'aza"),
    'c2-to-augment': ('زاد', 'zada'),
    'c2-to-avert': ('تفادى', 'tafada'),
    'c2-to-beckon': ('أومأ', "awma'a"),
    'c2-to-belittle': ('استصغر', 'istasghara'),
    'c2-to-bequeath': ('ورّث', 'warratha'),
    'c2-to-beseech': ('توسل', 'tawassala'),
    'c2-to-bewilder': ('حيّر', 'hayyara'),
    'c2-to-brandish': ('لوّح بـ', 'lawwaha bi'),
    'c2-to-castigate': ('قرّع', "qarra'a"),
    'c2-to-coalesce': ('اندمج', 'indamaja'),
    'c2-to-commend': ('أثنى على', 'athna ala'),
    'c2-to-concede': ('أقرّ بـ', "aqarra bi"),
    'c2-to-concoct': ('اختلق', 'ikhtalaqa'),
    'c2-to-confer': ('منح', 'manaha'),
    'c2-to-contend': ('جادل', 'jadala'),
    'c2-to-corroborate': ('أثبت', 'athbata'),
    'c2-to-aggravate': ('فاقم', 'faqama'),
    'c2-to-assail': ('هجم على', 'hajama ala'),
    'c2-to-chastise': ('أدّب', 'addaba'),
    'c2-to-condescend': ('تنازل', 'tanazala'),
    'c2-to-debunk': ('فنّد', 'fannada'),
    'c2-to-decipher': ('فكّ الشفرة', 'fakka ash-shifra'),
    'c2-to-decry': ('استنكر', 'istankara'),
    'c2-to-deem': ('اعتبر', "i'tabara"),
    'c2-to-defer': ('أجّل', 'ajjala'),
    'c2-to-delineate': ('حدّد', 'haddada'),
    'c2-to-denounce': ('شجب', 'shajaba'),
    'c2-to-deplete': ('استنزف', 'istanzafa'),
    'c2-to-deride': ('سخر من', 'sakhira min'),
    'c2-to-despair': ('يئس', "ya'isa"),
    'c2-to-detain': ('احتجز', 'ihtajaza'),
    'c2-to-deviate': ('انحرف', 'inharafa'),
    'c2-to-disdain': ('أنف من', 'anifa min'),
    'c2-to-disperse': ('فرّق', 'farraqa'),
    'c2-to-dissuade': ('ثنى عن', 'thana an'),
    'c2-to-divulge': ('أفشى', 'afsha'),
    'c2-to-dwindle': ('تضاءل', "tada'ala"),
    'c2-to-elude': ('أفلت من', 'aflata min'),
    'c2-to-emanate': ('صدر عن', 'sadara an'),
    'c2-to-embellish': ('زيّن', 'zayyana'),
    'c2-to-encompass': ('شمل', 'shamila'),
    'c2-to-engender': ('ولّد', 'wallada'),
    'c2-to-enlighten': ('نوّر', 'nawwara'),
    'c2-to-enthrall': ('أسر', 'asara'),
    'c2-to-entice': ('أغرى', 'aghra'),
    'c2-to-envision': ('تصوّر', 'tasawwara'),
    'c2-to-evade': ('تهرّب من', 'taharraba min'),
    'c2-to-exalt': ('مجّد', 'majjada'),
    'c2-to-expedite': ('عجّل', "'ajjala"),
    'c2-to-extol': ('أشاد بـ', 'ashada bi'),
    'c2-to-fabricate': ('لفّق', 'laffaqa'),
    'c2-to-falter': ('تعثّر', "ta'aththara"),
    'c2-to-feign': ('تظاهر بـ', 'tazahara bi'),
    'c2-to-flourish': ('ازدهر', 'izdahara'),
    'c2-to-forfeit': ('فقد', 'faqada'),
    'c2-to-forgo': ('تخلى عن', 'takhalla an'),
    'c2-to-galvanize': ('حفّز', 'haffaza'),
    'c2-to-garner': ('حصد', 'hasada'),
    'c2-to-gloat': ('شمت بـ', 'shamita bi'),
    'c2-to-grapple': ('صارع', "sara'a"),
    'c2-to-harness': ('سخّر', 'sakhkhara'),
    'c2-to-heed': ('أصغى إلى', 'asgha ila'),
    'c2-to-hoard': ('اكتنز', 'iktanaza'),
    'c2-to-impart': ('أفاد بـ', 'afada bi'),
    'c2-to-implore': ('التمس', 'iltamasa'),
    'c2-to-incite': ('حرّض', 'harrada'),
    'c2-to-inhibit': ('كبح', 'kabaha'),
    'c2-to-instill': ('غرس', 'gharasa'),
    'c2-to-intercede': ('توسّط', 'tawassata'),
    'c2-to-intimidate': ('أرهب', 'arhaba'),
    'c2-to-jeopardize': ('عرّض للخطر', "'arrada lil-khatar"),
    'c2-to-languish': ('ذبل', 'dhabula'),
    'c2-to-lure': ('استدرج', 'istadraja'),
    'c2-to-marvel': ('تعجّب', "ta'ajjaba"),
    'c2-to-meander': ('تعرّج', "ta'arraja"),
    'c2-to-muster': ('حشد', 'hashada'),
    'c2-to-obliterate': ('أباد', 'abada'),
    'c2-to-oscillate': ('تذبذب', 'tadhabdhaba'),
    'c2-to-ostracize': ('نبذ', 'nabadha'),
    'c2-to-perpetuate': ('أدام', 'adama'),
    'c2-to-permeate': ('تخلّل', 'takhallala'),
    'c2-to-plummet': ('هوى', 'hawa'),
    'c2-to-ponder': ('تأمّل', "ta'ammala"),
    'c2-to-preach': ('وعظ', "wa'aza"),
    'c2-to-procure': ('حصّل', 'hassala'),
    'c2-to-proliferate': ('تكاثر', 'takathara'),
    'c2-to-propel': ('دفع', 'dafaa'),
    'c2-to-quell': ('أخمد', 'akhmada'),
    'c2-to-ratify': ('صادق على', 'sadaqa ala'),
    'c2-to-rebuke': ('وبّخ', 'wabbakha'),
    'c2-to-rebut': ('دحض', 'dahada'),
    'c2-to-recant': ('تراجع عن', 'tarajaa an'),
    'c2-to-redeem': ('افتدى', 'iftada'),
    'c2-to-refute': ('أبطل', 'abtala'),
    'c2-to-relish': ('استمتع بـ', 'istamtaa bi'),
    'c2-to-renounce': ('تبرأ من', "tabarra'a min"),
    'c2-to-replenish': ('جدّد', 'jaddada'),
    'c2-to-reprimand': ('زجر', 'zajara'),
    'c2-to-repudiate': ('تنصّل من', 'tanassala min'),
    'c2-to-resonate': ('لاقى صدى', 'laqa sadan'),
    'c2-to-retaliate': ('انتقم', 'intaqama'),
    'c2-to-revere': ('بجّل', 'bajjala'),
    'c2-to-revoke': ('ألغى', 'algha'),
    'c2-to-saturate': ('أشبع', "ashba'a"),
    'c2-to-scorn': ('ازدرى', 'izdara'),
    'c2-to-squander': ('بذّر', 'baddhara'),
    'c2-to-stagnate': ('ركد', 'rakada'),
    'c2-to-stifle': ('خنق', 'khanaqa'),
    'c2-to-subside': ('هدأ', "hada'a"),
    'c2-to-succumb': ('استسلم لـ', 'istaslama li'),
    'c2-to-supplant': ('حلّ محلّ', 'halla mahalla'),
    'c2-to-surmise': ('خمّن', 'khammana'),
    'c2-to-swindle': ('نصب على', 'nasaba ala'),
    'c2-to-tarnish': ('لطّخ', 'lattakha'),
    'c2-to-thwart': ('أحبط', 'ahbata'),
    'c2-to-transcend': ('تجاوز', 'tajawaza'),
    'c2-to-unravel': ('حلّ', 'halla'),
    'c2-to-usurp': ('اغتصب', 'ightasaba'),
    'c2-to-vanquish': ('قهر', 'qahara'),
    'c2-to-venerate': ('وقّر', 'waqqara'),
    'c2-to-vilify': ('شهّر بـ', 'shahhara bi'),
    'c2-to-wane': ('أفل', 'afala'),
    'c2-to-wield': ('قبض على', 'qabada ala'),
    'c2-to-writhe': ('تلوّى', 'talawwa'),
    'c2-to-yearn': ('تاق إلى', 'taqa ila'),
    'c2-to-beget': ('أنجب', 'anjaba'),
    'c2-to-besiege': ('حاصر', 'hasara'),
    'c2-to-cajole': ('تملّق', 'tamallaqa'),
    'c2-to-coax': ('استمال', 'istamala'),
    'c2-to-deplore': ('استهجن', 'istahjana'),
    'c2-to-disparage': ('حقّر', 'haqqara'),
    'c2-to-exhort': ('حثّ', 'haththa'),
    'c2-to-foment': ('أجّج', 'ajjaja'),
    'c2-to-indulge': ('انغمس في', 'inghamasa fi'),
    'c2-to-placate': ('استرضى', 'istarda'),
    'c2-to-preempt': ('استبق', 'istabaqa'),
    'c2-to-rescind': ('نقض', 'naqada'),
    'c2-to-stymie': ('عرقل', "'arqala"),
    'c2-to-vindicate': ('برّأ', "barra'a"),
    'c2-to-evince': ('أبدى', 'abda'),
    'c2-affable': ('ودود', 'wadud'),
    'c2-churlish': ('فظ', 'fazz'),
    'c2-astute': ('فطن', 'fatin'),
    'c2-audacious': ('جريء', "jari'"),
    'c2-belligerent': ('عدواني', 'udwani'),
    'c2-sanguine': ('متفائل', "mutafa'il"),
    'c2-brusque': ('خشن', 'khashin'),
    'c2-callous': ('قاسٍ', 'qasin'),
    'c2-truculent': ('شرس', 'sharis'),
    'c2-capricious': ('متقلب', 'mutaqallib'),
    'c2-complacent': ('متساهل', 'mutasahil'),
    'c2-unflappable': ('رابط الجأش', "rabit al-ja'sh"),
    'c2-cunning': ('مكار', 'makkar'),
    'c2-diffident': ('متردد', 'mutaraddid'),
    'c2-officious': ('متطفل', 'mutataffil'),
    'c2-docile': ('طيّع', "tayyi'"),
    'c2-erudite': ('نحرير', 'nihrir'),
    'c2-fastidious': ('وسواسي', 'waswasi'),
    'c2-flippant': ('طائش', "ta'ish"),
    'c2-garrulous': ('ثرثار', 'tharthar'),
    'c2-gregarious': ('اجتماعي', 'ijtimai'),
    'c2-haughty': ('صلف', 'salif'),
    'c2-impetuous': ('متهور', 'mutahawwir'),
    'c2-indolent': ('كسول', 'kasul'),
    'c2-mercurial': ('متقلب المزاج', 'mutaqallib al-mizaj'),
    'c2-phlegmatic': ('بارد الطبع', "barid at-tab'"),
    'c2-obsequious': ('متملق', 'mutamalliq'),
    'c2-petulant': ('متبرم', 'mutabarrim'),
    'c2-sanctimonious': ('مراءٍ', "mura'in"),
    'c2-taciturn': ('صموت', 'samut'),
    'c2-bountiful': ('سخي', 'sakhiy'),
    'c2-arduous': ('شاق', 'shaqq'),
    'c2-banal': ('مبتذل', 'mubtadhal'),
    'c2-copious': ('وفير', 'wafir'),
    'c2-cumbersome': ('مرهق', 'murhiq'),
    'c2-deft': ('ماهر', 'mahir'),
    'c2-dire': ('وخيم', 'wakhim'),
    'c2-ephemeral': ('زائل', "za'il"),
    'c2-peerless': ('لا يضاهى', 'la yudaha'),
    'c2-feeble': ('واهن', 'wahin'),
    'c2-rickety': ('متداعٍ', "mutada'in"),
    'c2-formidable': ('مهيب', 'mahib'),
    'c2-immaculate': ('نقي', 'naqiy'),
    'c2-faultless': ('سليم', 'salim'),
    'c2-innocuous': ('بريء', "bari'"),
    'c2-insidious': ('داهٍ', 'dahin'),
    'c2-labyrinthine': ('متعرج', "muta'arrij"),
    'c2-profligate': ('مبذر', 'mubadhdhir'),
    'c2-perspicuous': ('جلي', 'jaliy'),
    'c2-sparse': ('متناثر', 'mutanathir'),
    'c2-infinitesimal': ('متناهٍ في الصغر', 'mutanahin fi as-sighar'),
    'c2-sumptuous': ('فاخر', 'fakhir'),
    'c2-paltry': ('تافه', 'tafih'),
    'c2-unblemished': ('طاهر', 'tahir'),
    'c2-indomitable': ('لا يقهر', 'la yuqhar'),
    'c2-scant': ('ضئيل', "da'il"),
    'c2-transcendent': ('متعالٍ', "muta'alin"),
    'c2-tenuous': ('هش', 'hash'),
    'c2-unwieldy': ('عسير', 'asir'),
    'c2-boundless': ('لامتناهٍ', 'la-mutanahin'),
    'c2-abstruse': ('عويص', 'awis'),
    'c2-apt': ('ملائم', "mula'im"),
    'c2-cogent': ('مقنع', "muqni'"),
    'c2-contentious': ('مثير للجدل', 'muthir lil-jadal'),
    'c2-deplorable': ('شائن', "sha'in"),
    'c2-dubious': ('مشكوك فيه', 'mashkuk fih'),
    'c2-egregious': ('شنيع', "shani'"),
    'c2-exemplary': ('مثالي', 'mithali'),
    'c2-fallacious': ('باطل', 'batil'),
    'c2-futile': ('عقيم', 'aqim'),
    'c2-gratuitous': ('غير مبرر', 'ghayr mubarrar'),
    'c2-illicit': ('غير مشروع', "ghayr mashru'"),
    'c2-impartial': ('محايد', 'muhayid'),
    'c2-incongruous': ('غير متسق', 'ghayr muttasiq'),
    'c2-ineffable': ('لا يوصف', 'la yusaf'),
    'c2-irrefutable': ('لا يدحض', 'la yudhad'),
    'c2-laudable': ('محمود', 'mahmud'),
    'c2-moot': ('جدلي', 'jadali'),
    'c2-nebulous': ('غامض', 'ghamid'),
    'c2-ostensible': ('ظاهري', 'zahiri'),
    'c2-pernicious': ('مهلك', 'muhlik'),
    'c2-plausible': ('معقول', "ma'qul"),
    'c2-preposterous': ('سخيف', 'sakhif'),
    'c2-salient': ('بارز', 'bariz'),
    'c2-spurious': ('زائف', "za'if"),
    'c2-superfluous': ('فائض', "fa'id"),
    'c2-tenable': ('مبرر', 'mubarrar'),
    'c2-untenable': ('غير قابل للاستمرار', 'ghayr qabil lil-istimrar'),
    'c2-viable': ('قابل للتطبيق', 'qabil lil-tatbiq'),
    'c2-wanton': ('منفلت', 'munfalit'),
    'c2-ailing': ('عليل', 'alil'),
    'c2-bewildered': ('حائر', "ha'ir"),
    'c2-desolate': ('موحش', 'muhish'),
    'c2-brittle': ('قصف', 'qasif'),
    'c2-cohesive': ('متماسك', 'mutamasik'),
    'c2-defunct': ('بائد', "ba'id"),
    'c2-derelict': ('مهجور', 'mahjur'),
    'c2-ramshackle': ('متهالك', 'mutahalik'),
    'c2-dormant': ('كامن', 'kamin'),
    'c2-drowsy': ('وسنان', 'wasnan'),
    'c2-dwindling': ('متناقص', 'mutanaqis'),
    'c2-exhilarated': ('منتشٍ', 'muntashin'),
    'c2-forlorn': ('بائس', "ba'is"),
    'c2-haggard': ('منهك', 'munhak'),
    'c2-imminent': ('وشيك', 'washik'),
    'c2-incessant': ('متواصل', 'mutawasil'),
    'c2-inert': ('خامل', 'khamil'),
    'c2-jaded': ('سئم', "sa'im"),
    'c2-languid': ('متراخٍ', 'mutarakhin'),
    'c2-listless': ('فاتر الهمة', 'fatir al-himma'),
    'c2-antiquated': ('بالٍ', 'balin'),
    'c2-precarious': ('متقلقل', 'mutaqalqil'),
    'c2-rampant': ('متفشٍّ', 'mutafashshin'),
    'c2-fidgety': ('نزق', 'naziq'),
    'c2-rife': ('منتشر', 'muntashir'),
    'c2-sodden': ('مبلل', 'muballal'),
    'c2-stagnant': ('راكد', 'rakid'),
    'c2-susceptible': ('عرضة لـ', 'urda li'),
    'c2-volatile': ('متفجر', 'mutafajjir'),
    'c2-weary': ('متعب', "mut'ab"),
    'c2-bombastic': ('طنان', 'tannan'),
    'c2-vernacular': ('عامي', 'aammi'),
    'c2-concise': ('موجز', 'mujaz'),
    'c2-tortuous': ('ملتوٍ', 'multawin'),
    'c2-cryptic': ('مبهم', 'mubham'),
    'c2-derogatory': ('تحقيري', 'tahqiri'),
    'c2-didactic': ('تعليمي', "ta'limi"),
    'c2-silver-tongued': ('فصيح اللسان', 'fasih al-lisan'),
    'c2-emphatic': ('قاطع', "qati'"),
    'c2-euphemistic': ('تلطيفي', 'talttifi'),
    'c2-facetious': ('هزلي', 'hazli'),
    'c2-florid': ('مزخرف', 'muzakhraf'),
    'c2-glib': ('زلق', 'zaliq'),
    'c2-hyperbolic': ('مبالغ فيه', 'mubalagh fih'),
    'c2-incisive': ('ثاقب', 'thaqib'),
    'c2-laconic': ('قليل الكلام', 'qalil al-kalam'),
    'c2-long-winded': ('مطنب', 'mutnib'),
    'c2-mordant': ('لاذع', "ladhi'"),
    'c2-ornate': ('منمق', 'munammaq'),
    'c2-pedantic': ('متحذلق', 'mutahadhliq'),
    'c2-pithy': ('وجيز', 'wajiz'),
    'c2-plaintive': ('شجي', 'shaji'),
    'c2-rhetorical': ('خطابي', 'khatabi'),
    'c2-sardonic': ('ساخر', 'sakhir'),
    'c2-scathing': ('جارح', 'jarih'),
    'c2-succinct': ('مختصر', 'mukhtasar'),
    'c2-terse': ('مقتضب', 'muqtadab'),
    'c2-trite': ('مكرر', 'mukarrar'),
    'c2-verbose': ('مسهب', 'mus-hib'),
    'c2-wry': ('متهكم', 'mutahakkim'),
    'c2-acumen': ('فطنة', 'fitna'),
    'c2-alacrity': ('همة', 'himma'),
    'c2-ambivalence': ('تناقض المشاعر', "tanaqud al-masha'ir"),
    'c2-apathy': ('لامبالاة', 'la-mubalah'),
    'c2-aplomb': ('رباطة جأش', "rabatat ja'sh"),
    'c2-audacity': ('جرأة', "jur'a"),
    'c2-candor': ('صراحة', 'sarahah'),
    'c2-smugness': ('غرور', 'ghurur'),
    'c2-scorn': ('ازدراء', "izdira'"),
    'c2-deference': ('إذعان', "idh'an"),
    'c2-discretion': ('تكتم', 'takattum'),
    'c2-disdain': ('استخفاف', 'istikhfaf'),
    'c2-forbearance': ('تحمل', 'tahammul'),
    'c2-fortitude': ('جلد', 'jalad'),
    'c2-hubris': ('غطرسة', 'ghatrasa'),
    'c2-meekness': ('وداعة', 'wadaa'),
    'c2-umbrage': ('استياء', "istiya'"),
    'c2-ingenuity': ('براعة', 'baraa'),
    'c2-rectitude': ('استقامة', 'istiqama'),
    'c2-malice': ('خبث', 'khubth'),
    'c2-nostalgia': ('حنين', 'hanin'),
    'c2-perseverance': ('مثابرة', 'muthabara'),
    'c2-prudence': ('حصافة', 'hasafa'),
    'c2-grit': ('عزيمة', 'azima'),
    'c2-reticence': ('تحفظ', 'tahafuz'),
    'c2-equanimity': ('اتزان', 'ittizan'),
    'c2-tenacity': ('إصرار', 'israr'),
    'c2-vanity': ('زهو', 'zahw'),
    'c2-vigilance': ('يقظة', 'yaqaza'),
    'c2-zeal': ('حماسة', 'hamasa'),
    'c2-anomaly': ('شذوذ', 'shudhudh'),
    'c2-catalyst': ('حافز', 'hafiz'),
    'c2-conundrum': ('أحجية', 'uhjiyya'),
    'c2-debacle': ('كارثة', 'karitha'),
    'c2-deluge': ('طوفان', 'tufan'),
    'c2-dearth': ('ندرة', 'nudra'),
    'c2-dichotomy': ('ثنائية', "thuna'iyya"),
    'c2-epitome': ('المثال الأعلى', 'al-mithal al-aala'),
    'c2-exodus': ('نزوح', 'nuzuh'),
    'c2-facade': ('واجهة', 'wajiha'),
    'c2-fallacy': ('مغالطة', 'mughalata'),
    'c2-hindsight': ('نظرة استرجاعية', 'nazra istirjaiyya'),
    'c2-impasse': ('طريق مسدود', 'tariq masdud'),
    'c2-impetus': ('دافع', "dafi'"),
    'c2-juncture': ('منعطف', "mun'ataf"),
    'c2-loophole': ('ثغرة', 'thughra'),
    'c2-tipping-point': ('نقطة التحول', 'nuqtat at-tahawwul'),
    'c2-onslaught': ('هجوم كاسح', 'hujum kasih'),
    'c2-vicious-circle': ('حلقة مفرغة', 'halaqa mufragha'),
    'c2-plight': ('محنة', 'mihna'),
    'c2-precedent': ('سابقة', 'sabiqa'),
    'c2-quandary': ('مأزق', "ma'ziq"),
    'c2-ramification': ('تداعيات', "tada'iyat"),
    'c2-respite': ('استراحة', 'istiraha'),
    'c2-setback': ('نكسة', 'naksa'),
    'c2-stalemate': ('تعادل', "ta'adul"),
    'c2-surge': ('طفرة', 'tafra'),
    'c2-turmoil': ('اضطراب', 'idtirab'),
    'c2-upheaval': ('هزة', 'hazza'),
    'c2-watershed': ('نقطة فاصلة', 'nuqta fasila'),
    'c2-accomplice': ('متواطئ', "mutawati'"),
    'c2-adversary': ('خصم', 'khasm'),
    'c2-advocate': ('مناصر', 'munasir'),
    'c2-benefactor': ('محسن', 'muhsin'),
    'c2-bystander': ('متفرج', 'mutafarrij'),
    'c2-charlatan': ('دجال', 'dajjal'),
    'c2-connoisseur': ('ذواق', 'dhawwaq'),
    'c2-culprit': ('جانٍ', 'janin'),
    'c2-demagogue': ('غوغائي', "ghawgha'i"),
    'c2-dilettante': ('هاوٍ', 'hawin'),
    'c2-envoy': ('مبعوث', "mab'uth"),
    'c2-lackey': ('تابع', "tabi'"),
    'c2-understudy': ('بديل', 'badil'),
    'c2-hypocrite': ('منافق', 'munafiq'),
    'c2-insurgent': ('متمرد', 'mutamarrid'),
    'c2-layperson': ('غير مختص', 'ghayr mukhtass'),
    'c2-maverick': ('غير تقليدي', 'ghayr taqlidi'),
    'c2-sidekick': ('مرافق', 'murafiq'),
    'c2-mercenary': ('مرتزق', 'murtaziq'),
    'c2-novice': ('مبتدئ', "mubtadi'"),
    'c2-pariah': ('منبوذ', 'manbudh'),
    'c2-patron': ('راعٍ', "ra'in"),
    'c2-perpetrator': ('مرتكب', 'murtakib'),
    'c2-prodigy': ('نابغة', 'nabigha'),
    'c2-informant': ('مخبر', 'mukhbir'),
    'c2-recluse': ('منعزل', "mun'azil"),
    'c2-sage': ('حكيم', 'hakim'),
    'c2-turncoat': ('منشق', 'munshaqq'),
    'c2-stalwart': ('ركيزة', 'rakiza'),
    'c2-tycoon': ('قطب', 'qutb'),
    'c2-ambiguity': ('غموض', 'ghumud'),
    'c2-analogy': ('قياس', 'qiyas'),
    'c2-axiom': ('بديهية', 'badihiyya'),
    'c2-caveat': ('تنبيه', 'tanbih'),
    'c2-consensus': ('إجماع', 'ijmaa'),
    'c2-corollary': ('لازمة', 'lazima'),
    'c2-yardstick': ('معيار', "mi'yar"),
    'c2-narrative': ('سردية', 'sardiyya'),
    'c2-doctrine': ('مذهب', 'madhhab'),
    'c2-dogma': ('عقيدة', 'aqida'),
    'c2-epiphany': ('استبصار', 'istibsar'),
    'c2-ethos': ('طابع', "tabi'"),
    'c2-conjecture': ('تخمين', 'takhmin'),
    'c2-idiosyncrasy': ('خصوصية', 'khususiyya'),
    'c2-deduction': ('استنتاج', 'istintaj'),
    'c2-innuendo': ('تلميح', 'talmih'),
    'c2-buzzword': ('كلمة رائجة', "kalima ra'ija"),
    'c2-simile': ('تشبيه', 'tashbih'),
    'c2-nuance': ('فارق دقيق', 'fariq daqiq'),
    'c2-archetype': ('نموذج أصلي', 'namudhaj asli'),
    'c2-platitude': ('عبارة مبتذلة', 'ibara mubtadhala'),
    'c2-postulate': ('مسلمة', 'musallama'),
    'c2-pretext': ('ذريعة', "dhari'a"),
    'c2-rebuttal': ('تفنيد', 'tafnid'),
    'c2-rhetoric': ('بلاغة', 'balagha'),
    'c2-semantics': ('دلالة', 'dalala'),
    'c2-stigma': ('وصمة', 'wasma'),
    'c2-tenet': ('مبدأ', "mabda'"),
    'c2-trope': ('صورة نمطية', 'sura namatiyya'),
    'c2-zeitgeist': ('روح العصر', "ruh al-asr"),
    'c2-acrid': ('نفاذ', 'naffadh'),
    'c2-astringent': ('قابض', 'qabid'),
    'c2-bland-flavorless': ('بلا طعم', "bila ta'm"),
    'c2-brackish': ('أجاج', 'ujaj'),
    'c2-cloying': ('مفرط الحلاوة', 'mufrit al-halawa'),
    'c2-coarse': ('غليظ', 'ghaliz'),
    'c2-creamy': ('قشدي', 'qishdi'),
    'c2-crunchy': ('مقرمش', 'muqarmish'),
    'c2-dank': ('رطب', 'ratib'),
    'c2-earthy': ('ترابي', 'turabi'),
    'c2-fragrant': ('عطر', 'atir'),
    'c2-gooey': ('لزج', 'lazij'),
    'c2-grainy': ('حبيبي', 'hubaybi'),
    'c2-unctuous': ('دهني', 'duhni'),
    'c2-gravelly-voice': ('أجش', 'ajashsh'),
    'c2-luscious': ('شهي', 'shahi'),
    'c2-mellow': ('لين', 'layyin'),
    'c2-hushed': ('خافت', 'khafit'),
    'c2-musty': ('عفن', 'afin'),
    'c2-piercing': ('حاد', 'hadd'),
    'c2-pungent': ('حريف', 'hirrif'),
    'c2-putrid': ('متعفن', "muta'affin"),
    'c2-rancid': ('زنخ', 'zanikh'),
    'c2-bitter-aftertaste': ('نكهة مرة لاحقة', 'nakha murra lahiqa'),
    'c2-grating-sound': ('نشاز', 'nashaz'),
    'c2-silky': ('حريري', 'hariri'),
    'c2-slimy': ('دبق', 'dabiq'),
    'c2-soggy': ('متشبع بالماء', "mutashabbi' bil-ma'"),
    'c2-tangy': ('حامض', 'hamid'),
    'c2-zesty': ('منعش', "muna'ash"),
    'c2-better-late-than-never': ('التأخر خير من الغياب', "at-ta'akhkhur khayr min al-ghiyab"),
    'c2-actions-speak-louder-than-words': ('الأفعال أبلغ من الأقوال', "al-af'al ablagh min al-aqwal"),
    'c2-the-early-bird-catches-the-worm': ('من جد وجد', 'man jadda wajad'),
    'c2-don-t-count-your-chickens-before-they-hatch': ('لا تبع السمك في الماء', "la tabi' as-samak fi al-ma'"),
    'c2-every-cloud-has-a-silver-lining': ('رب ضارة نافعة', "rubba darratin nafi'a"),
    'c2-practice-makes-perfect': ('التكرار يعلم الشطار', "at-tikrar yu'allim ash-shuttar"),
    'c2-when-in-rome-do-as-the-romans-do': ('إذا كنت في روما فافعل كما يفعل الرومان', "idha kunta fi ruma fa-if'al kama yaf'al ar-ruman"),
    'c2-two-heads-are-better-than-one': ('رأيان خير من رأي واحد', "ra'yan khayr min ra'y wahid"),
    'c2-the-grass-is-always-greener-on-the-other-side': ('العشب دائما أخضر في الجانب الآخر', "al-'ushb da'iman akhdar fi al-janib al-akhar"),
    'c2-don-t-judge-a-book-by-its-cover': ('لا تحكم على الكتاب من غلافه', 'la tahkum ala al-kitab min ghilafih'),
    'c2-birds-of-a-feather-flock-together': ('الطيور على أشكالها تقع', 'at-tuyur ala ashkaliha taqa'),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('عصفور في اليد خير من عشرة على الشجرة', "usfur fi al-yad khayr min 'ashara ala ash-shajara"),
    'c2-where-there-s-a-will-there-s-a-way': ('حيث توجد الإرادة توجد الوسيلة', 'haythu tujad al-irada tujad al-wasila'),
    'c2-rome-wasn-t-built-in-a-day': ('روما لم تبن في يوم واحد', 'ruma lam tubna fi yawm wahid'),
    'c2-too-many-cooks-spoil-the-broth': ('كثرة الطباخين تفسد الطبخة', 'kathrat at-tabbakhin tufsid at-tabkha'),
    'c2-out-of-sight-out-of-mind': ('بعيد عن العين بعيد عن القلب', "ba'id an al-ayn ba'id an al-qalb"),
    'c2-look-before-you-leap': ('التأني من الرحمن والعجلة من الشيطان', "at-ta'ani min ar-rahman wal-ajala min ash-shaytan"),
    'c2-necessity-is-the-mother-of-invention': ('الحاجة أم الاختراع', 'al-haja umm al-ikhtira'),
    'c2-you-can-t-have-your-cake-and-eat-it-too': ('لا يمكنك أن تنعم بالكعكة وتأكلها في آن واحد', "la yumkinuka an tan'am bil-ka'ka wa ta'kuluha fi an wahid"),
    'c2-honesty-is-the-best-policy': ('الصدق منجاة', 'as-sidq manjah'),
    'c2-still-waters-run-deep': ('تحت الرماد جمر', 'taht ar-ramad jamr'),
    'c2-blood-is-thicker-than-water': ('الدم لا يتحول ماء', "ad-damm la yatahawwal ma'an"),
    'c2-absence-makes-the-heart-grow-fonder': ('البعد يزيد القلب شوقا', "al-bu'd yazid al-qalb shawqan"),
    'c2-every-dog-has-its-day': ('لكل امرئ نصيب من الحظ', "likulli imri'in nasib min al-hazz"),
    'c2-haste-makes-waste': ('في العجلة الندامة', 'fi al-ajala an-nadama'),
    'c2-let-sleeping-dogs-lie': ('لا توقظ الفتنة النائمة', "la tuqiz al-fitna an-na'ima"),
    'c2-strike-while-the-iron-is-hot': ('اضرب الحديد وهو ساخن', 'idrib al-hadid wa huwa sakhin'),
    'c2-the-pen-is-mightier-than-the-sword': ('القلم أقوى من السيف', 'al-qalam aqwa min as-sayf'),
    'c2-curiosity-killed-the-cat': ('الفضول قتل القط', 'al-fudul qatal al-qitt'),
    'c2-beggars-can-t-be-choosers': ('لا اختيار لمن يطلب', 'la ikhtiyar liman yatlub'),
    'c2-to-draw-a-distinction': ('ميز بين', 'mayyaza bayna'),
    'c2-to-reach-a-verdict': ('أصدر حكما', 'asdara hukman'),
    'c2-to-pose-a-threat': ('شكل تهديدا', 'shakkala tahdidan'),
    'c2-to-bear-the-brunt': ('تحمل وطأة', "tahammala wat'a"),
    'c2-to-lend-credence-to': ('أضفى مصداقية على', 'adfa masdaqiyya ala'),
    'c2-to-wield-influence': ('مارس نفوذا', 'marasa nufudhan'),
    'c2-to-incur-a-cost': ('تكبد تكلفة', 'takabbada taklifa'),
    'c2-to-uphold-a-principle': ('تمسك بمبدأ', "tamassaka bi-mabda'"),
    'c2-to-exert-pressure': ('مارس ضغطا', 'marasa daghtan'),
    'c2-to-fulfil-an-obligation': ('أوفى بالتزام', 'awfa bi-iltizam'),
    'c2-to-cast-doubt-on': ('شكك في', 'shakkaka fi'),
    'c2-to-pay-tribute-to': ('كرّم', 'karrama'),
    'c2-to-take-precedence-over': ('له الأولوية على', 'lahu al-awlawiyya ala'),
    'c2-to-run-the-risk-of': ('خاطر بـ', 'khatara bi'),
    'c2-to-strike-a-balance': ('حقق توازنا', 'haqqaqa tawazunan'),
    'c2-to-come-to-fruition': ('تحقق', 'tahaqqaqa'),
    'c2-to-shed-light-on': ('سلط الضوء على', "sallata ad-daw' ala"),
    'c2-to-set-a-precedent': ('أرسى سابقة', 'arsa sabiqa'),
    'c2-to-give-rise-to': ('أدى إلى', 'adda ila'),
    'c2-to-take-issue-with': ('اعترض على', "i'tarada ala"),
    'c2-pursuant-to': ('عملا بـ', 'amalan bi'),
    'c2-heretofore': ('فيما سبق', 'fima sabaq'),
    'c2-inasmuch-as': ('بما أن', 'bima anna'),
    'c2-in-conjunction-with': ('بالاقتران مع', "bil-iqtiran ma'a"),
    'c2-hitherto': ('حتى الآن', 'hatta al-an'),
    'c2-forthwith': ('فورا', 'fawran'),
    'c2-whilst': ('بينما', 'baynama'),
    'c2-wherein': ('حيث', 'haythu'),
    'c2-vis-a-vis': ('إزاء', "iza'"),
    'c2-as-regards': ('فيما يتعلق بـ', "fima yata'allaqu bi"),
    'c2-for-the-sake-of-argument': ('على سبيل الجدل', 'ala sabil al-jadal'),
    'c2-be-that-as-it-may': ('مهما يكن', 'mahma yakun'),
    'c2-on-balance': ('في المحصلة', 'fi al-muhassala'),
    'c2-at-the-behest-of': ('بناء على طلب', "bina'an ala talab"),
    'c2-in-the-wake-of': ('في أعقاب', "fi a'qab"),
    'c2-on-the-grounds-that': ('على أساس أن', 'ala asas anna'),
    'c2-in-accordance-with': ('وفقا لـ', 'wafqan li'),
    'c2-pending': ('في انتظار', 'fi intizar'),
    'c2-irrespective-of': ('بصرف النظر عن', 'bi-sarf an-nazar an'),
    'c2-hereinafter': ('فيما بعد', "fima ba'd"),
    'c2-beats-me': ('لا أدري', 'la adri'),
    'c2-point-taken': ('فهمت قصدك', 'fahimtu qasdak'),
    'c2-suit-yourself': ('كما يحلو لك', 'kama yahlu laka'),
    'c2-go-figure': ('من يدري', 'man yadri'),
    'c2-don-t-get-me-started': ('لا تجعلني أبدأ', "la taj'alni abda'"),
    'c2-bottom-line-is': ('خلاصة القول', 'khulasat al-qawl'),
    'c2-off-the-top-of-my-head': ('من الذاكرة مباشرة', 'min adh-dhakira mubasharatan'),
    'c2-i-ll-say': ('أوافقك تماما', 'uwafiquka tamaman'),
    'c2-you-ve-got-to-be-kidding-me': ('لا بد أنك تمزح', 'la budda annaka tamzah'),
    'c2-no-offense-but': ('لا أقصد الإساءة لكن', "la aqsidu al-isa'a lakin"),
    'c2-i-m-not-gonna-lie': ('لن أكذب عليك', 'lan akdhiba alayka'),
    'c2-speak-of-the-devil': ('ذكرته فحضر', 'dhakartuhu fahadar'),
    'c2-it-s-on-the-tip-of-my-tongue': ('على طرف لساني', 'ala taraf lisani'),
    'c2-let-s-call-it-a-day': ('لنكتف بهذا القدر اليوم', 'linaktafi bi-hadha al-qadr al-yawm'),
    'c2-it-s-not-rocket-science': ('الأمر ليس علم فلك', 'al-amr laysa ilm falak'),
    'c2-that-s-the-last-straw': ('هذه القشة التي قصمت ظهر البعير', "hadhihi al-qashsha allati qasamat zahr al-ba'ir"),
    'c2-i-couldn-t-care-less': ('لا يهمني الأمر إطلاقا', 'la yahummuni al-amr itlaqan'),
    'c2-what-are-the-odds': ('يا للمصادفة', 'ya lil-musadafa'),
    'c2-say-no-more': ('لا داعي لمزيد من الكلام', "la da'i li-mazid min al-kalam"),
    'c2-hang-in-there': ('تماسك', 'tamasak'),
    'c2-i-m-all-ears': ('أنا كلي آذان صاغية', 'ana kulli adhan sagiya'),
    'c2-that-s-on-me': ('هذا خطئي', "hadha khata'i"),
    'c2-no-hard-feelings': ('بلا ضغائن', 'bila daghain'),
    'c2-ditto': ('كذلك', 'kadhalik'),
    'c2-spill-the-beans': ('كشف الخبايا', 'kashafa al-khabaya'),
    'c2-in-one-ear-and-out-the-other': ('يدخل من أذن ويخرج من الأخرى', 'yadkhul min udhn wa yakhruj min al-ukhra'),
    'c2-cut-to-the-chase': ('اذهب مباشرة إلى صلب الموضوع', "idhhab mubasharatan ila sulb al-mawdu'"),
    'c2-you-name-it': ('أي شيء تريده', "ayyu shay' turiduh"),
    'c2-not-in-a-million-years': ('لن يحدث أبدا', 'lan yahduth abadan'),
    'c2-it-is-what-it-is': ('هذا هو الواقع', "hadha huwa al-waqi'"),
    'c2-give-me-a-break': ('أرحني قليلا', 'arihni qalilan'),
    'c2-hold-your-horses': ('تمهل', 'tamahhal'),
    'c2-bite-the-bullet': ('تجرع الدواء المر', "tajarra'a ad-dawa' al-murr"),
    'c2-take-it-with-a-grain-of-salt': ('خذه بتحفظ', 'khudhhu bi-tahaffuz'),
    'c2-better-safe-than-sorry': ('الوقاية خير من العلاج', "al-wiqaya khayr min al-'ilaj"),
    'c2-let-s-play-it-by-ear': ('سنرى ما يحدث', 'sanara ma yahduth'),
    'c2-i-ll-take-a-rain-check': ('لنؤجلها لوقت آخر', "linu'ajjilha li-waqt akhar"),
    'c2-for-what-it-s-worth': ('على أي حال', 'ala ayyi hal'),
    'c2-back-to-square-one': ('العودة إلى نقطة الصفر', 'al-awda ila nuqtat as-sifr'),
    'c2-touch-wood': ('أطرق على الخشب', 'atruqu ala al-khashab'),
    'c2-allusion': ('إحالة', 'ihala'),
    'c2-anecdote': ('نادرة', 'nadira'),
    'c2-antithesis': ('طباق', 'tibaq'),
    'c2-aphorism': ('قول مأثور', "qawl ma'thur"),
    'c2-banter': ('مزاح خفيف', 'mizah khafif'),
    'c2-circumlocution': ('إطناب', 'itnab'),
    'c2-cliche': ('كليشيه', 'klishih'),
    'c2-connotation': ('إيحاء', "iha'"),
    'c2-digression': ('استطراد', 'istitrad'),
    'c2-double-entendre': ('عبارة ذات معنيين', "ibara dhat ma'nayayn"),
    'c2-eloquence': ('فصاحة', 'fasaha'),
    'c2-euphemism': ('تلطيف', 'taltif'),
    'c2-gist': ('لب الموضوع', 'lubb al-mawdu'),
    'c2-hyperbole': ('مبالغة', 'mubalagha'),
    'c2-irony': ('مفارقة', 'mufaraqa'),
    'c2-juxtaposition': ('تجاور', 'tajawur'),
    'c2-malapropism': ('لحن مضحك', 'lahn mudhik'),
    'c2-oxymoron': ('تناقض لفظي', 'tanaqud lafzi'),
    'c2-paraphrase': ('إعادة صياغة', "i'adat siyagha"),
    'c2-pun': ('تورية', 'tawriya'),
    'c2-quip': ('نكتة عابرة', "nukta 'abira"),
    'c2-sarcasm': ('سخرية', 'sukhriya'),
    'c2-slur-insult': ('شتيمة', 'shatima'),
    'c2-repartee': ('بديهة', 'badiha'),
    'c2-soliloquy': ('مناجاة', 'munaja'),
    'c2-subtext': ('معنى ضمني', "ma'na dimni"),
    'c2-tangent': ('خروج عن الموضوع', "khuruj 'an al-mawdu'"),
    'c2-tirade': ('ثورة كلامية', 'thawra kalamiyya'),
    'c2-understatement': ('تهوين', 'tahwin'),
    'c2-verbiage': ('حشو الكلام', 'hashw al-kalam'),
    'c2-to-allude-to': ('لمح إلى', 'lammaha ila'),
    'c2-to-enunciate': ('نطق بوضوح', 'nataqa bi-wuduh'),
    'c2-to-belabor-the-point': ('أسهب في', "as-haba fi"),
    'c2-to-digress': ('استطرد', 'istatrada'),
    'c2-to-expound': ('شرح بالتفصيل', 'sharaha bit-tafsil'),
    'c2-to-insinuate': ('أوحى بـ', 'awha bi'),
    'c2-to-interject': ('قاطع', "qata'a"),
    'c2-to-hammer-home': ('أكد بإصرار', 'akkada bi-israr'),
    'c2-to-retort': ('رد', 'radda'),
    'c2-to-waffle-be-vague': ('راوغ', 'rawagha'),
    'c2-actuary': ('خبير اكتواري', 'khabir iktiwari'),
    'c2-anesthesiologist': ('طبيب تخدير', 'tabib takhdir'),
    'c2-archivist': ('أمين محفوظات', 'amin mahfuzat'),
    'c2-auditor': ('مدقق حسابات', 'mudaqqiq hisabat'),
    'c2-bailiff': ('محضر', 'muhdir'),
    'c2-blacksmith': ('حداد', 'haddad'),
    'c2-cartographer': ('رسام خرائط', "rassam khara'it"),
    'c2-chiropractor': ('مقوم العظام', 'muqawwim al-izam'),
    'c2-coroner': ('طبيب شرعي', "tabib shar'i"),
    'c2-curator': ('أمين متحف', 'amin mathaf'),
    'c2-diplomat': ('دبلوماسي', 'diblumasi'),
    'c2-dietitian': ('أخصائي تغذية', "akhissa'i taghdhiya"),
    'c2-entomologist': ('عالم حشرات', 'alim hasharat'),
    'c2-forensic-scientist': ('خبير جنائي', 'khabir jina-i'),
    'c2-geologist': ('جيولوجي', 'jiyuluji'),
    'c2-glazier': ('زجاج', 'zajjaj'),
    'c2-interpreter-simultaneous': ('مترجم فوري', 'mutarjim fawri'),
    'c2-locksmith': ('قفال', 'qaffal'),
    'c2-midwife': ('قابلة', 'qabila'),
    'c2-court-clerk': ('كاتب محكمة', 'katib mahkama'),
    'c2-oncologist': ('أخصائي الأورام', "akhissa'i al-awram"),
    'c2-ophthalmologist': ('طبيب عيون', 'tabib uyun'),
    'c2-paleontologist': ('عالم أحافير', 'alim ahafir'),
    'c2-paralegal': ('مساعد قانوني', 'musa-id qanuni'),
    'c2-pathologist': ('أخصائي علم الأمراض', "akhissa'i ilm al-amrad"),
    'c2-physiotherapist': ('أخصائي علاج طبيعي', "akhissa'i ilaj tabi'i"),
    'c2-public-defender': ('محام معين من المحكمة', "muham mu'ayyan min al-mahkama"),
    'c2-radiologist': ('أخصائي أشعة', "akhissa'i ashi'a"),
    'c2-perfumer': ('عطار', 'attar'),
    'c2-stenographer': ('كاتب اختزال', 'katib ikhtizal'),
    'c2-surveyor': ('مساح', 'massah'),
    'c2-taxidermist': ('حناط', 'hannat'),
    'c2-upholsterer': ('منجد', 'munajjid'),
    'c2-veterinarian-specialist': ('طبيب بيطري', 'tabib baytari'),
    'c2-welder': ('لحام', 'lahham'),
    'c2-anthropology': ('علم الإنسان', 'ilm al-insan'),
    'c2-archaeology': ('علم الآثار', 'ilm al-athar'),
    'c2-astrophysics': ('الفيزياء الفلكية', "al-fizya' al-falakiyya"),
    'c2-biochemistry': ('الكيمياء الحيوية', "al-kimya' al-hayawiyya"),
    'c2-botany': ('علم النبات', 'ilm an-nabat'),
    'c2-cartography': ('رسم الخرائط', "rasm al-khara'it"),
    'c2-criminology': ('علم الإجرام', 'ilm al-ijram'),
    'c2-demography': ('علم السكان', 'ilm as-sukkan'),
    'c2-econometrics': ('الاقتصاد القياسي', 'al-iqtisad al-qiyasi'),
    'c2-epidemiology': ('علم الأوبئة', "ilm al-awbi'a"),
    'c2-epistemology': ('نظرية المعرفة', 'nazariyyat al-ma-rifa'),
    'c2-ethnography': ('علم وصف الأعراق', "ilm wasf al-a'raq"),
    'c2-genetics': ('علم الوراثة', 'ilm al-wiratha'),
    'c2-geopolitics': ('الجغرافيا السياسية', 'al-jughrafiya as-siyasiyya'),
    'c2-hermeneutics': ('علم التأويل', "ilm at-ta'wil"),
    'c2-immunology': ('علم المناعة', "ilm al-mana'a"),
    'c2-jurisprudence': ('فلسفة القانون', 'falsafat al-qanun'),
    'c2-linguistics': ('علم اللغة', 'ilm al-lugha'),
    'c2-metaphysics': ('ما وراء الطبيعة', "ma wara' at-tabi'a"),
    'c2-meteorology': ('علم الأرصاد الجوية', 'ilm al-arsad al-jawwiyya'),
    'c2-microbiology': ('علم الأحياء الدقيقة', "ilm al-ahya' ad-daqiqa"),
    'c2-musicology': ('علم الموسيقى', 'ilm al-musiqa'),
    'c2-neuroscience': ('علم الأعصاب', "ilm al-a'sab"),
    'c2-oceanography': ('علم المحيطات', 'ilm al-muhitat'),
    'c2-ornithology': ('علم الطيور', 'ilm at-tuyur'),
    'c2-pedagogy': ('علم التربية', 'ilm at-tarbiya'),
    'c2-pharmacology': ('علم الأدوية', 'ilm al-adwiya'),
    'c2-philology': ('علم فقه اللغة', 'ilm fiqh al-lugha'),
    'c2-phonetics': ('علم الأصوات', 'ilm al-aswat'),
    'c2-seismology': ('علم الزلازل', 'ilm az-zalazil'),
    'c2-semiotics': ('علم العلامات', "ilm al-'alamat"),
    'c2-sociolinguistics': ('علم اللغة الاجتماعي', "ilm al-lugha al-ijtima'i"),
    'c2-theology': ('علم اللاهوت', 'ilm al-lahut'),
    'c2-toxicology': ('علم السموم', 'ilm as-sumum'),
    'c2-zoology': ('علم الحيوان', 'ilm al-hayawan'),
    'c2-acute-sudden-severe': ('حاد', 'hadd'),
    'c2-latent': ('خفي', 'khafi'),
    'c2-benign': ('حميد', 'hamid'),
    'c2-malignant': ('خبيث', 'khabith'),
    'c2-biopsy': ('خزعة', "khuz'a"),
    'c2-prognosis': ('تكهن', 'takahhun'),
    'c2-flare-up': ('نوبة', 'nawba'),
    'c2-recurrence': ('انتكاسة', 'intikasa'),
    'c2-sedative': ('مهدئ', "muhaddi'"),
    'c2-anesthetic': ('مخدر', 'mukhaddir'),
    'c2-antibody': ('جسم مضاد', 'jism mudadd'),
    'c2-inflammation': ('التهاب', 'iltihab'),
    'c2-airborne': ('محمول جوا', 'mahmul jawwan'),
    'c2-hereditary': ('وراثي', 'wirathi'),
    'c2-congenital': ('خلقي', 'khilqi'),
    'c2-dosage': ('جرعة', "jur'a"),
    'c2-placebo': ('دواء وهمي', "dawa' wahmi"),
    'c2-contraindication': ('موانع الاستعمال', "mawani' al-isti'mal"),
    'c2-intravenous': ('وريدي', 'waridi'),
    'c2-suture': ('غرزة', 'ghurza'),
    'c2-incision': ('شق جراحي', 'shaqq jirahi'),
    'c2-donor': ('متبرع', "mutabarri'"),
    'c2-ultrasound': ('موجات فوق صوتية', 'mawjat fawq sawtiyya'),
    'c2-referral-to-a-specialist': ('تحويل إلى أخصائي', "tahwil ila akhissa'i"),
    'c2-inpatient': ('مريض داخلي', 'marid dakhili'),
    'c2-palliative-care': ('رعاية تلطيفية', 'ri-aya taltifiyya'),
    'c2-triage': ('فرز المرضى', 'farz al-marda'),
    'c2-convalescence': ('نقاهة', 'naqaha'),
    'c2-immunity': ('مناعة', "mana'a"),
    'c2-pandemic': ('جائحة', "ja'iha"),
    'c2-pathogen': ('عامل ممرض', 'amil mumridd'),
    'c2-electrolyte': ('شارد', 'sharid'),
    'c2-cardiovascular': ('قلبي وعائي', "qalbi wi'a'i"),
    'c2-respiratory': ('تنفسي', 'tanaffusi'),
    'c2-neurological': ('عصبي', 'asabi'),
    'c2-symptomatic': ('عرضي', 'aradi'),
    'c2-asymptomatic': ('بلا أعراض', "bila a'rad"),
    'c2-prescription-written-order': ('وصفة طبية', 'wasfa tibbiyya'),
    'c2-generic-drug': ('دواء جنيس', "dawa' janis"),
    'c2-informed-consent': ('موافقة مستنيرة', 'muwafaqa mustanira'),
    'c2-acquittal': ('براءة', "bara'a"),
    'c2-conviction-guilty-verdict': ('إدانة', 'idana'),
    'c2-deposition': ('إفادة', 'ifada'),
    'c2-accessory-to-a-crime': ('شريك في الجريمة', 'sharik fi al-jarima'),
    'c2-arson': ('حريق متعمد', "hariq muta'ammad"),
    'c2-remand': ('حبس احتياطي', 'habs ihtiyati'),
    'c2-burden-of-proof': ('عبء الإثبات', "ib' al-ithbat"),
    'c2-custody-detention': ('احتجاز', 'ihtijaz'),
    'c2-defendant': ('متهم', 'muttaham'),
    'c2-plaintiff': ('مدعٍ', "mudda'in"),
    'c2-embezzlement': ('اختلاس', 'ikhtilas'),
    'c2-extortion': ('ابتزاز', 'ibtizaz'),
    'c2-felony': ('جناية', 'jinaya'),
    'c2-misdemeanor': ('جنحة', 'junha'),
    'c2-forgery': ('تزوير', 'tazwir'),
    'c2-hearsay': ('شهادة سماعية', 'shahada sama-iyya'),
    'c2-indictment': ('لائحة اتهام', "la'ihat ittiham"),
    'c2-injunction': ('أمر زجري', 'amr zajri'),
    'c2-tribunal': ('محكمة', 'mahkama'),
    'c2-libel': ('قذف مكتوب', 'qadhf maktub'),
    'c2-slander': ('قذف شفهي', 'qadhf shafahi'),
    'c2-manslaughter': ('قتل غير عمد', "qatl ghayr 'amd"),
    'c2-parole': ('إفراج مشروط', 'ifraj mashrut'),
    'c2-perjury': ('شهادة زور', 'shahadat zur'),
    'c2-plea-bargain': ('صفقة إقرار بالذنب', "safqat iqrar bidh-dhanb"),
    'c2-probation': ('مراقبة قضائية', "muraqaba qada'iyya"),
    'c2-racketeering': ('ابتزاز منظم', 'ibtizaz munazzam'),
    'c2-ransom': ('فدية', 'fidya'),
    'c2-statute': ('قانون', 'qanun'),
    'c2-statute-of-limitations': ('تقادم', 'taqadum'),
    'c2-subpoena': ('استدعاء قضائي', "istid'a' qada'i"),
    'c2-testimony': ('شهادة', 'shahada'),
    'c2-ruling': ('حكم', 'hukm'),
    'c2-warrant': ('مذكرة توقيف', 'mudhakkirat tawqif'),
    'c2-witness-stand': ('منصة الشهود', 'minassat ash-shuhud'),
    'c2-contempt-of-court': ('إهانة المحكمة', 'ihanat al-mahkama'),
    'c2-cross-examination': ('استجواب مضاد', 'istijwab mudadd'),
    'c2-mistrial': ('محاكمة باطلة', 'muhakama batila'),
    'c2-sentence-punishment': ('عقوبة', "uquba"),
    'c2-to-plead-guilty': ('أقر بالذنب', "aqarra bidh-dhanb"),
    'c2-thicket': ('أجمة', 'ajama'),
    'c2-undergrowth': ('أدغال', 'adghal'),
    'c2-moss': ('طحلب', 'tuhlub'),
    'c2-lichen': ('أشنة', 'ushna'),
    'c2-fern': ('سرخس', 'sarkhas'),
    'c2-sap': ('نسغ', 'nusgh'),
    'c2-bark-of-a-tree': ('لحاء', "liha'"),
    'c2-sapling': ('شتلة', 'shatla'),
    'c2-canopy-forest': ('مظلة الغابة', 'mizallat al-ghaba'),
    'c2-grove': ('غيضة', 'ghaydah'),
    'c2-meadow': ('مرج', 'marj'),
    'c2-marsh': ('مستنقع', "mustanqa'"),
    'c2-bog': ('أرض خثية', 'ard khathiyya'),
    'c2-estuary': ('مصب نهر', 'masabb nahr'),
    'c2-tributary': ('رافد', 'rafid'),
    'c2-ravine': ('شعب', "shi'b"),
    'c2-gorge': ('مضيق', 'madiq'),
    'c2-ridge': ('سلسلة', 'silsila'),
    'c2-summit': ('قمة', 'qimma'),
    'c2-foothills': ('سفوح الجبال', 'sufuh al-jibal'),
    'c2-escarpment': ('منحدر صخري', 'munhadar sakhri'),
    'c2-salt-flat': ('سبخة', 'sabkha'),
    'c2-cove': ('خور', 'khawr'),
    'c2-atoll': ('جزيرة مرجانية', 'jazira marjaniyya'),
    'c2-tide-pool': ('بركة مدية', 'birka maddiyya'),
    'c2-driftwood': ('خشب طاف', 'khashab tafin'),
    'c2-pebble': ('حصاة', 'hasah'),
    'c2-boulder': ('صخرة ضخمة', 'sakhra dakhma'),
    'c2-sediment': ('رواسب', 'rawasib'),
    'c2-erosion': ('تعرية', "ta'riya"),
    'c2-burrow': ('جحر', 'juhr'),
    'c2-hive': ('خلية نحل', 'khaliyyat nahl'),
    'c2-cocoon': ('شرنقة', 'sharnaqa'),
    'c2-antler': ('قرن الأيل', 'qarn al-ayyil'),
    'c2-talon': ('مخلب', 'mikhlab'),
    'c2-plumage': ('ريش', 'rish'),
    'c2-migration-animal': ('هجرة', 'hijra'),
    'c2-hibernation': ('سبات شتوي', 'subat shitwi'),
    'c2-pollination': ('تلقيح', 'talqih'),
    'c2-germination': ('إنبات', 'inbat'),
    'c2-torrential': ('منهمر', 'munhamir'),
    'c2-monsoon': ('الرياح الموسمية', 'ar-riyah al-mawsimiyya'),
    'c2-sleet': ('مطر ثلجي', 'matar thalji'),
    'c2-flurry-snow': ('زخة ثلج', 'zakhkhat thalj'),
    'c2-whiteout': ('انعدام الرؤية الثلجي', "in'idam ar-ru'ya ath-thalji"),
    'c2-black-ice': ('جليد أسود', 'jalid aswad'),
    'c2-dew': ('ندى', 'nada'),
    'c2-haze': ('غباش', 'ghubash'),
    'c2-clammy': ('رطب لزج', 'ratib lazij'),
    'c2-scorcher': ('يوم قائظ', "yawm qa'iz"),
    'c2-sultry': ('خانق', 'khaniq'),
    'c2-balmy': ('لطيف', 'latif'),
    'c2-crisp-air': ('هواء منعش', "hawa' mun'ish"),
    'c2-gust': ('هبة ريح', 'habbat rih'),
    'c2-gale': ('عاصفة', 'asifa'),
    'c2-squall': ('زوبعة', "zawba'a"),
    'c2-thunderclap': ('قصف الرعد', 'qasf ar-ra-d'),
    'c2-lightning-bolt': ('صاعقة', "sa'iqa"),
    'c2-cloudburst': ('وابل مفاجئ', "wabil mufaji'"),
    'c2-nightfall': ('حلول الليل', 'hulul al-layl'),
    'c2-cold-snap': ('موجة برد', 'mawjat bard'),
    'c2-thaw': ('ذوبان', 'dhawaban'),
    'c2-humidity': ('رطوبة', 'rutuba'),
    'c2-barometer': ('مقياس الضغط الجوي', "miqyas ad-daght al-jawwi"),
    'c2-forecast-verb': ('تنبأ بالطقس', "tanabba'a bit-taqs"),
    'c2-daybreak': ('بزوغ الفجر', 'buzugh al-fajr'),
    'c2-aurora': ('الشفق القطبي', 'ash-shafaq al-qutbi'),
    'c2-twilight': ('شفق', 'shafaq'),
    'c2-solstice': ('انقلاب شمسي', 'inqilab shamsi'),
    'c2-equinox': ('اعتدال', "i'tidal"),
    'c2-arch': ('قوس', 'qaws'),
    'c2-vault-ceiling': ('قبو', 'qabw'),
    'c2-dome': ('قبة', 'qubba'),
    'c2-spire': ('برج مدبب', 'burj mudabbab'),
    'c2-buttress': ('دعامة', "di'ama"),
    'c2-pillar': ('سارية', 'sariya'),
    'c2-column': ('عمود', 'amud'),
    'c2-beam-structural': ('عارضة', 'arida'),
    'c2-rafter': ('جائز', "ja'iz"),
    'c2-girder': ('عارضة معدنية', "arida ma'daniyya"),
    'c2-keystone': ('حجر القوس', 'hajar al-qaws'),
    'c2-facade-building-front': ('واجهة', 'wajiha'),
    'c2-cornice': ('إفريز', 'ifriz'),
    'c2-gable': ('جملون', 'jumalun'),
    'c2-eaves': ('حافة السقف', 'hafat as-saqf'),
    'c2-gutter-roof': ('ميزاب', 'mizrab'),
    'c2-skylight': ('منور سقفي', 'munawwir saqfi'),
    'c2-balustrade': ('درابزين', 'darabzin'),
    'c2-parapet': ('متراس', 'mitras'),
    'c2-turret': ('برَيج', 'burayj'),
    'c2-moat': ('خندق', 'khandaq'),
    'c2-drawbridge': ('جسر متحرك', 'jisr mutaharrik'),
    'c2-cloister': ('رواق', 'riwaq'),
    'c2-courtyard': ('فناء', "fina'"),
    'c2-alcove': ('مشكاة', 'mashkat'),
    'c2-mezzanine': ('طابق نصفي', 'tabiq nisfi'),
    'c2-atrium': ('بهو داخلي', 'bahw dakhili'),
    'c2-mosaic': ('فسيفساء', "fusayfisa'"),
    'c2-fresco': ('جدارية', 'jidariyya'),
    'c2-elevation-drawing': ('مسقط جانبي', 'masqat janibi'),
    'c2-partition-wall': ('جدار فاصل', 'jidar fasil'),
    'c2-cladding': ('تكسية خارجية', 'taksiya kharijiyya'),
    'c2-plumbing-system': ('تمديدات صحية', 'tamdidat sihhiyya'),
    'c2-ventilation-duct': ('مجرى تهوية', 'majra tahwiya'),
    'c2-retrofit': ('تحديث', 'tahdith'),
    'c2-colander': ('مصفاة', 'misfah'),
    'c2-ladle': ('مغرفة', 'mighrafa'),
    'c2-whisk': ('خفاقة', 'khaffaqa'),
    'c2-grater': ('مبشرة', 'mibshara'),
    'c2-tongs': ('ملقط', 'malqat'),
    'c2-spatula': ('ملعقة مسطحة', "mil'aqa musattaha"),
    'c2-cutting-board': ('لوح تقطيع', "lawh taqti'"),
    'c2-french-press': ('كباسة قهوة', 'kabbasat qahwa'),
    'c2-coaster': ('حامل كوب', 'hamil kub'),
    'c2-trivet': ('مسند قدور', 'masnad qudur'),
    'c2-oven-mitt': ('قفاز فرن', 'quffaz furn'),
    'c2-dish-rack': ('مجفف أطباق', 'mujaffif atbaq'),
    'c2-dustpan': ('جاروف', 'jaruf'),
    'c2-mop': ('ممسحة', 'mimsaha'),
    'c2-clothespin': ('مشبك غسيل', 'mishbak ghasil'),
    'c2-clothesline': ('حبل غسيل', 'habl ghasil'),
    'c2-shoehorn': ('ملعقة أحذية', "mil'aqat ahdhiya"),
    'c2-doormat': ('ممسحة أرجل', 'mimsahat arjul'),
    'c2-doorknob': ('مقبض باب', 'miqbad bab'),
    'c2-hinge': ('مفصلة', 'mifsala'),
    'c2-latch': ('مزلاج', 'mizlaj'),
    'c2-peephole': ('عين الباب', 'ayn al-bab'),
    'c2-blinds-window': ('ستائر شرائحية', "sata'ir shara'ihiyya"),
    'c2-windowsill': ('حافة النافذة', 'haffat an-nafidha'),
    'c2-banister': ('حاجز درج', 'hajiz daraj'),
    'c2-landing-stairs': ('بسطة السلم', 'bastat as-sullam'),
    'c2-crawl-space': ('فراغ تحت الأرض', 'faragh taht al-ard'),
    'c2-cellar': ('سرداب', 'sirdab'),
    'c2-pantry': ("مخزن مؤن", "makhzan mu'an"),
    'c2-utility-room': ('غرفة الخدمات', 'ghurfat al-khidamat'),
    'c2-fuse-box': ('لوحة الكهرباء', "lawhat al-kahraba'"),
    'c2-dimmer-switch': ('مفتاح تعتيم', 'miftah ta-tim'),
    'c2-extension-cord': ('وصلة كهربائية', "wasla kahraba'iyya"),
    'c2-power-strip': ('مقبس متعدد', "maqbas muta'addid"),
    'c2-carbon-monoxide-alarm': ('جهاز كشف أول أكسيد الكربون', 'jihaz kashf awwal uksid al-karbun'),
    'c2-first-aid-kit': ('حقيبة إسعافات أولية', 'haqibat is-afat awwaliyya'),
    'c2-sewing-kit': ('عدة خياطة', "uddat khiyata"),
    'c2-toolbox': ('صندوق عدة', "sunduq udda"),
    'c2-allen-key': ('مفتاح ألن', 'miftah alan'),
    'c2-pliers': ('كماشة', 'kammasha'),
    'c2-wrench': ('مفتاح ربط', 'miftah rabt'),
    'c2-tape-measure': ('شريط قياس', 'sharit qiyas'),
    'c2-spirit-level': ('ميزان تسوية', 'mizan taswiya'),
    'c2-drawer-organizer': ('منظم أدراج', 'munazzim adraj'),
    'c2-bin-liner': ('كيس قمامة', 'kis qumama'),
    'c2-to-seethe': ('غلى غضبا', 'ghala ghadaban'),
    'c2-to-sulk': ('تعبس', "ta'abbasa"),
    'c2-to-fret': ('قلق', 'qaliqa'),
    'c2-to-brood': ('اجتر الهم', 'ijtarra al-hamm'),
    'c2-to-wallow-in-self-pity': ('تمرغ في الشفقة على الذات', 'tamarragha fi ash-shafaqa ala adh-dhat'),
    'c2-to-gloat-over-a-rival': ('شمت بمنافس', 'shamita bi-munafis'),
    'c2-to-savor-the-moment': ('تذوق اللحظة', 'tadhawwaqa al-lahza'),
    'c2-to-revel-in': ('انتشى بـ', 'intasha bi'),
    'c2-to-marvel-at': ('تعجب من', "ta'ajjaba min"),
    'c2-to-cringe': ('انقبض خجلا', 'inqabada khajalan'),
    'c2-to-wince': ('كشر ألما', 'kashshara alaman'),
    'c2-to-flinch': ('جفل', 'jafala'),
    'c2-to-shudder': ('ارتعش', "irta'asha"),
    'c2-to-quiver': ('ارتجف', 'irtajafa'),
    'c2-to-swoon': ('أغمي عليه', 'ughmiya alayhi'),
    'c2-to-pine-for': ('تلهف على', 'talahhafa ala'),
    'c2-to-long-for': ('حن إلى', 'hanna ila'),
    'c2-to-crave': ('اشتهى', 'ishtaha'),
    'c2-to-abominate': ('استقبح', 'istaqbaha'),
    'c2-to-nurse-a-grievance': ('أضمر ضغينة', 'admara daghina'),
    'c2-to-begrudge': ('ضن بـ', 'danna bi'),
    'c2-to-grovel': ('تذلل', 'tadhallala'),
    'c2-to-fawn-over': ('تزلف', 'tazallafa'),
    'c2-to-dote-on': ('دلل', 'dallala'),
    'c2-to-treasure': ('اعتز بـ', "i'tazza bi"),
    'c2-to-put-at-ease': ('طمأن', "tam'ana"),
    'c2-to-console': ('عزى', 'azza'),
    'c2-to-commiserate': ('واسى', 'wasa'),
    'c2-to-exasperate': ('أضجر', 'adjara'),
    'c2-to-infuriate': ('أغاظ', 'aghaza'),
    'c2-to-unnerve': ('أربك', 'arbaka'),
    'c2-to-mortify': ('أخزى', 'akhza'),
    'c2-to-captivate': ('خلب', 'khalaba'),
    'c2-to-enrapture': ('أطرب', 'atraba'),
    'c2-to-disillusion': ('خيب أمل', 'khayyaba amal'),
    'c2-to-mollify': ('سكن', 'sakkana'),
    'c2-to-embolden': ('جرأ', "jarra'a"),
    'c2-to-dishearten': ('فت في عضده', "fatta fi 'adudih"),
    'c2-to-rankle': ('أحنق', 'ahnaqa'),
    'c2-to-smolder': ('احتدم داخليا', 'ihtadama dakhiliyyan'),
    'c2-numbness': ('خدر', 'khadar'),
    'c2-tingling': ('تنميل', 'tanmil'),
    'c2-cramp': ('تشنج', 'tashannuj'),
    'c2-twinge': ('وخزة', 'wakhza'),
    'c2-throbbing': ('نبضان', 'nabadan'),
    'c2-dizziness': ('دوار', 'duwar'),
    'c2-lightheaded': ('دائخ', "da'ikh"),
    'c2-vertigo': ('دوام', 'duwam'),
    'c2-queasy': ('يشعر بالغثيان', 'yash-ur bil-ghathayan'),
    'c2-lethargy': ('خمول', 'khumul'),
    'c2-fatigue': ('إرهاق', 'irhaq'),
    'c2-stamina': ('طاقة تحمل', 'taqat tahammul'),
    'c2-reflex': ("منعكس", "mun'akas"),
    'c2-flinch-noun': ('جفلة', 'jafla'),
    'c2-pins-and-needles': ('وخز كالإبر', "wakhz kal-ibar"),
    'c2-shiver': ('قشعريرة', "qush'arira"),
    'c2-hot-flush': ('هبة سخونة', 'habbat sukhuna'),
    'c2-blush': ('احمرار الوجه', 'ihmirar al-wajh'),
    'c2-yawn': ('تثاؤب', "tatha'ub"),
    'c2-hiccup': ('فواق', 'fuwaq'),
    'c2-sneeze': ('عطاس', 'utas'),
    'c2-itch': ('حكة', 'hikka'),
    'c2-bruise': ('كدمة', 'kadma'),
    'c2-blister': ('نفاطة', 'naffata'),
    'c2-pulled-muscle': ('تمزق عضلي', 'tamazzuq adali'),
    'c2-stiffness': ('تيبس', 'tayabbus'),
    'c2-restlessness': ('توتر', 'tawattur'),
    'c2-daydream': ('أحلام يقظة', 'ahlam yaqaza'),
    'c2-deja-vu': ('شعور بسبق رؤية', "shu'ur bi-sabq ru'ya"),
    'c2-hunch': ('حدس', 'hads'),
    'c2-gut-feeling': ('إحساس داخلي', 'ihsas dakhili'),
    'c2-brain-fog': ('ضبابية ذهنية', 'dababiyya dhihniyya'),
    'c2-second-wind': ('نفس ثانٍ', 'nafas thanin'),
    'c2-adrenaline-rush': ('اندفاع الأدرينالين', "indifa' al-adrinalin"),
    'c2-motion-sickness': ('دوار الحركة', 'duwar al-haraka'),
    'c2-camaraderie': ('روح الزمالة', 'ruh az-zamala'),
    'c2-affinity-between-people': ('تقارب', 'taqarub'),
    'c2-clique': ('زمرة', 'zumra'),
    'c2-entourage': ('حاشية', 'hashiya'),
    'c2-etiquette': ('أصول اللياقة', 'usul al-liyaqa'),
    'c2-faux-pas': ('زلة اجتماعية', 'zalla ijtima-iyya'),
    'c2-gossip': ('نميمة', 'namima'),
    'c2-grudge': ('ضغينة', 'daghina'),
    'c2-chain-of-command': ('تسلسل قيادي', 'tasalsul qiyadi'),
    'c2-nepotism': ('محاباة', 'muhabah'),
    'c2-ostracism': ('نبذ', 'nabdh'),
    'c2-groupthink': ('تفكير جماعي', 'tafkir jama-i'),
    'c2-pecking-order': ('ترتيب هرمي', 'tartib haramiy'),
    'c2-rivalry': ('تنافس', 'tanafus'),
    'c2-solidarity': ('تضامن', 'tadamun'),
    'c2-snub': ('تجاهل متعمد', "tajahul muta'ammad"),
    'c2-taboo': ('محرم', 'muharram'),
    'c2-flattery': ('تملق', 'tamalluq'),
    'c2-backhanded-compliment': ('إطراء ذو حدين', "itra' dhu haddayn"),
    'c2-cold-shoulder': ('برود متعمد', "burud muta'ammad"),
    'c2-small-circle-inner-circle': ('الدائرة الضيقة', "ad-da'ira ad-dayyiqa"),
    'c2-interloper': ('دخيل', 'dakhil'),
    'c2-old-hand': ('مخضرم', 'mukhadram'),
    'c2-wingman': ('رفيق مساند', 'rafiq musanid'),
    'c2-freeloader': ('طفيلي', 'tufayli'),
    'c2-busybody': ('فضولي', 'fudduli'),
    'c2-killjoy': ('مفسد الفرح', 'mufsid al-farah'),
    'c2-show-off': ('متباهٍ', 'mutabahin'),
    'c2-pushover': ('سهل الانقياد', 'sahl al-inqiyad'),
    'c2-self-starter': ('صاحب مبادرة', 'sahib mubadara'),
    'c2-to-mingle': ('اختلط', 'ikhtalata'),
    'c2-to-schmooze': ('تودد', 'tawaddada'),
    'c2-to-shun': ('تجنب', 'tajannaba'),
    'c2-to-patronize': ('ترفع على', 'tarafa-a ala'),
    'c2-to-reconcile': ('تصالح', 'tasalaha'),
    'c2-to-estrange': ('نفر', 'naffara'),
    'c2-to-confide-in': ('أسر لـ', 'asarra li'),
    'c2-to-hobnob': ('خالط', 'khalata'),
    'c2-to-rub-shoulders-with': ('عاشر', 'ashara'),
    'c2-to-fall-out-with': ('تخاصم مع', "takhasama ma'a"),
    'c2-foil-character': ('شخصية مقابلة', 'shakhsiyya muqabila'),
    'c2-anti-hero': ('بطل مضاد', 'batal mudadd'),
    'c2-narrator': ('راوٍ', 'rawin'),
    'c2-macguffin': ('حافز الحبكة', 'hafiz al-hubka'),
    'c2-red-herring': ('دليل مضلل', 'dalil mudallil'),
    'c2-motif': ('موضوع متكرر', "mawdu' mutakarrir"),
    'c2-frame-narrative': ('سرد إطاري', 'sard itari'),
    'c2-denouement': ('خاتمة الحبكة', 'khatimat al-hubka'),
    'c2-satire': ('هجاء', "hija'"),
    'c2-parody': ('محاكاة ساخرة', 'muhakat sakhira'),
    'c2-allegory': ('أثولة', 'uthula'),
    'c2-memoir': ('مذكرات', 'mudhakkirat'),
    'c2-anthology': ('مختارات', 'mukhtarat'),
    'c2-manuscript': ('مخطوطة', 'makhtuta'),
    'c2-prose': ('نثر', 'nathr'),
    'c2-couplet': ('بيت', 'bayt'),
    'c2-stanza': ('مقطع', "maqta'"),
    'c2-sonnet': ('سونيتة', 'sunita'),
    'c2-alliteration': ('جناس صوتي', 'jinas sawti'),
    'c2-meter-poetry': ('بحر', 'bahr'),
    'c2-aesthetic': ('جمالي', 'jamali'),
    'c2-avant-garde': ('طليعي', "tali'i"),
    'c2-baroque': ('باروكي', 'baruki'),
    'c2-impressionism': ('الانطباعية', "al-intiba'iyya"),
    'c2-surrealism': ('السريالية', 'as-siryaliyya'),
    'c2-still-life': ('طبيعة صامتة', 'tabi-a samita'),
    'c2-charcoal-drawing': ('رسم بالفحم', 'rasm bil-fahm'),
    'c2-etching': ('حفر', 'hafr'),
    'c2-bust-sculpture': ('تمثال نصفي', 'timthal nisfi'),
    'c2-chisel': ('إزميل', 'izmil'),
    'c2-easel': ('حامل الرسم', 'hamil ar-rasm'),
    'c2-palette': ('لوحة ألوان', 'lawhat alwan'),
    'c2-overture': ('افتتاحية موسيقية', 'iftitahiyya musiqiyya'),
    'c2-aria': ('أريا', 'arya'),
    'c2-encore': ('إعادة', "i'ada"),
    'c2-bandwidth': ('عرض النطاق', 'ard an-nitaq'),
    'c2-jitter': ('ارتعاش الإشارة', "irti'ash al-ishara"),
    'c2-throughput': ('معدل الإنتاجية', "mu'addal al-intajiyya"),
    'c2-hashing': ('تجزئة', "tajzi'a"),
    'c2-intrusion-detection': ('كشف التسلل', 'kashf at-tasallul'),
    'c2-vulnerability-security': ('ثغرة أمنية', 'thaghra amniyya'),
    'c2-hotfix': ('تصحيح عاجل', 'tas-hih ajil'),
    'c2-backlog': ('عمل متراكم', 'amal mutarakim'),
    'c2-rollout': ('نشر', 'nashr'),
    'c2-rollback': ('تراجع', "tarajo'"),
    'c2-uptime': ('زمن التشغيل', 'zaman at-tashghil'),
    'c2-redundancy-backup': ('تكرار احتياطي', 'takrar ihtiyati'),
    'c2-load-balancing': ('موازنة الحمل', 'muwazanat al-himl'),
    'c2-legacy-system': ('نظام موروث', 'nizam mawruth'),
    'c2-copyleft': ('الحق المتروك', 'al-haqq al-matruk'),
    'c2-proprietary': ('ملكي', 'milki'),
    'c2-interoperability': ('قابلية التشغيل البيني', 'qabiliyyat at-tashghil al-bayni'),
    'c2-passkey': ('مفتاح الدخول', 'miftah ad-dukhul'),
    'c2-social-engineering': ('الهندسة الاجتماعية', 'al-handasa al-ijtima-iyya'),
    'c2-data-breach': ('اختراق البيانات', 'ikhtiraq al-bayanat'),
    'c2-cache': ('ذاكرة مؤقتة', 'dhakira mu-aqqata'),
    'c2-query': ('استعلام', 'isti-lam'),
    'c2-metadata': ('بيانات وصفية', 'bayanat wasfiyya'),
    'c2-placeholder': ('عنصر نائب', "unsur na'ib"),
    'c2-workaround': ('حل مؤقت', "hall mu'aqqat"),
    'c2-bottleneck': ('عنق الزجاجة', 'unuq az-zujaja'),
    'c2-edge-case': ('حالة حدية', 'hala haddiyya'),
    'c2-deprecated': ('مهمل', 'muhmal'),
    'c2-sandbox': ('بيئة تجريبية', 'bi-a tajribiyya'),
    'c2-telemetry': ('قياس عن بعد', 'qiyas an bu-d'),
    'c2-algorithmic-bias': ('تحيز خوارزمي', 'tahayyuz khawarizmi'),
    'c2-overfitting': ('فرط التخصيص', 'fart at-takhsis'),
    'c2-large-language-model': ('نموذج لغوي كبير', 'namudhaj lughawi kabir'),
    'c2-quantum-computing': ('الحوسبة الكمية', 'al-hawsaba al-kammiyya'),
    'c2-semiconductor': ('شبه موصل', 'shibh muwassil'),
    'c2-working-capital': ("رأس المال العامل", "ra's al-mal al-amil"),
    'c2-solvency': ('ملاءة مالية', "mala'a maliyya"),
    'c2-insolvency': ("إعسار", "i'sar"),
    'c2-receivership': ('الحراسة القضائية', 'al-hirasa al-qada-iyya'),
    'c2-leverage-finance': ('الرافعة المالية', "ar-rafi'a al-maliyya"),
    'c2-hedge-finance': ('تحوط', 'tahawwut'),
    'c2-yield-finance': ("عائد", "a'id"),
    'c2-share-buyback': ('إعادة شراء الأسهم', "i'adat shira' al-ashum"),
    'c2-equity-ownership': ('حقوق ملكية', 'huquq milkiyya'),
    'c2-treasury-bill': ('أذون الخزانة', 'udhun al-khizana'),
    'c2-asset-allocation': ('توزيع الأصول', "tawzi' al-usul"),
    'c2-volatility': ('تقلب', 'taqallub'),
    'c2-bull-market': ('سوق صاعدة', "suq sa'ida"),
    'c2-bear-market': ('سوق هابطة', 'suq habita'),
    'c2-downturn': ('تباطؤ اقتصادي', "tabatu' iqtisadi"),
    'c2-stagflation': ('ركود تضخمي', 'rukud tadakhkhumi'),
    'c2-deflation': ('انكماش', 'inkimash'),
    'c2-interest-rate-hike': ('رفع أسعار الفائدة', "raf' as'ar al-fa'ida"),
    'c2-fiscal-policy': ('السياسة المالية', 'as-siyasa al-maliyya'),
    'c2-monetary-policy': ('السياسة النقدية', 'as-siyasa an-naqdiyya'),
    'c2-subsidy': ('دعم حكومي', "da'm hukumi"),
    'c2-trade-quota': ('حصة تجارية', 'hissa tijariyya'),
    'c2-embargo': ('حظر تجاري', 'hazr tijari'),
    'c2-belt-tightening': ('شد الحزام', 'shadd al-hizam'),
    'c2-bailout': ('إنقاذ مالي', 'inqadh mali'),
    'c2-windfall': ('مكسب غير متوقع', "maksab ghayr mutawaqqa'"),
    'c2-nest-egg': ('مدخرات', 'muddakharat'),
    'c2-slush-fund': ('صندوق سري', 'sunduq sirri'),
    'c2-kickback': ('عمولة غير مشروعة', "umula ghayr mashru'a"),
    'c2-money-laundering': ('غسيل الأموال', 'ghasil al-amwal'),
    'c2-tax-evasion': ('التهرب الضريبي', 'at-taharrub ad-daribi'),
    'c2-tax-loophole': ('ثغرة ضريبية', 'thaghra daribiyya'),
    'c2-underwriter': ('مكتتب', 'muktatib'),
    'c2-sinking-fund': ('صندوق الاستهلاك', 'sunduq al-istihlak'),
    'c2-arbitrage': ('مراجحة', 'murajaha'),
    'c2-freight': ('شحن', 'shahn'),
    'c2-cargo-hold': ('عنبر الشحن', 'anbar ash-shahn'),
    'c2-consignment': ('إرسالية', 'irsaliyya'),
    'c2-customs-clearance': ('تخليص جمركي', 'takhlis jumruki'),
    'c2-red-eye-flight': ('رحلة ليلية', 'rihla laylia'),
    'c2-turbulence': ('اضطراب جوي', 'idtirab jawwi'),
    'c2-taxiing': ('الجريان على المدرج', 'al-jarayan ala al-madraj'),
    'c2-cockpit': ('قمرة القيادة', 'qumrat al-qiyada'),
    'c2-overhead-compartment': ('الرف العلوي', 'ar-raff al-ulwi'),
    'c2-aisle-seat': ('مقعد الممر', 'maq-ad al-mamarr'),
    'c2-boarding-pass': ('بطاقة الصعود', 'bitaqat as-su-ud'),
    'c2-baggage-carousel': ('حزام نقل الأمتعة', "hizam naql al-amti'a"),
    'c2-jet-bridge': ('جسر الركاب', 'jisr ar-rukkab'),
    'c2-tailgating-driving': ('اللصوق بالسيارة الأمامية', 'al-lusuq bis-sayyara al-amamiyya'),
    'c2-gridlock': ('اختناق مروري', 'ikhtinaq mururi'),
    'c2-diversion-route': ('تحويلة مرورية', 'tahwila mururiyya'),
    'c2-interchange-highway': ('تقاطع الطرق السريعة', "taqatu' at-turuq as-sari'a"),
    'c2-overpass': ('جسر علوي', 'jisr ulwi'),
    'c2-underpass': ('ممر سفلي', 'mamarr sufli'),
    'c2-toll-booth': ('كشك الرسوم', 'kushk ar-rusum'),
    'c2-hard-shoulder': ('كتف الطريق', 'katif at-tariq'),
    'c2-speed-bump': ('مطب صناعي', 'matabb sina-i'),
    'c2-blind-spot': ("نقطة عمياء", "nuqta amya'"),
    'c2-hazard-lights': ("أضواء التحذير", "adwa' at-tahdhir"),
    'c2-windshield-wiper': ('مساحة الزجاج', 'massahat az-zujaj'),
    'c2-clutch-car': ('دبرياج', 'dabriyaj'),
    'c2-handbrake': ('فرامل اليد', 'faramil al-yad'),
    'c2-odometer': ('عداد المسافة', 'addad al-masafa'),
    'c2-tow-truck': ('سيارة سحب', 'sayyarat sahb'),
    'c2-commute-noun': ('تنقل يومي', 'tanaqqul yawmi'),
    'c2-numerator': ('بسط', 'bast'),
    'c2-denominator': ('مقام', 'maqam'),
    'c2-exponent': ('أس', 'uss'),
    'c2-square-root': ('جذر تربيعي', "jadhr tarbi'i"),
    'c2-decimal-point': ('فاصلة عشرية', 'fasila ushriyya'),
    'c2-remainder': ('باقٍ', 'baqin'),
    'c2-prime-number': ('عدد أولي', 'adad awwali'),
    'c2-integer': ('عدد صحيح', 'adad sahih'),
    'c2-quotient': ('خارج القسمة', 'kharij al-qisma'),
    'c2-percentile': ('مئين', "mi'in"),
    'c2-mean-average': ('متوسط', 'mutawassit'),
    'c2-median': ('وسيط', 'wasit'),
    'c2-outlier': ('قيمة شاذة', 'qima shadhdha'),
    'c2-standard-deviation': ('الانحراف المعياري', "al-inhiraf al-mi'yari"),
    'c2-variance': ('تباين', 'tabayun'),
    'c2-margin-of-error': ("هامش الخطأ", "hamish al-khata'"),
    'c2-sample-size': ("حجم العينة", "hajm al-'ayyina"),
    'c2-exponential-growth': ('نمو أسي', 'numuww ussi'),
    'c2-order-of-magnitude': ('رتبة الحجم', 'rutbat al-hajm'),
    'c2-rounding': ('تقريب', 'taqrib'),
    'c2-percentage-point': ('نقطة مئوية', "nuqta mi'awiyya"),
    'c2-threefold': ('ثلاثة أضعاف', "thalathat ad'af"),
    'c2-a-dozen': ('دستة', 'dasta'),
    'c2-round-number': ('رقم مدور', 'raqm mudawwar'),
    'c2-odds-probability': ('احتمالات', 'ihtimalat'),
    'c2-inseam': ('طول الساق الداخلي', 'tul as-saq ad-dakhili'),
    'c2-dart-sewing': ('بنصة خياطة', 'binsat khiyata'),
    'c2-lapel': ('طية الياقة', 'tayyat al-yaqa'),
    'c2-cuff': ('كفة', 'kaffa'),
    'c2-cufflinks': ('أزرار الكم', 'azrar al-kumm'),
    'c2-gusset': ('قطعة تقوية', "qit'at taqwiya"),
    'c2-pleat': ('ثنية', 'thanya'),
    'c2-tailored': ('مفصل', 'mufassal'),
    'c2-bespoke': ('حسب الطلب', 'hasb at-talab'),
    'c2-off-the-rack': ('جاهز', 'jahiz'),
    'c2-threadbare': ('مهترئ', "muhtari'"),
    'c2-frayed': ('مهلهل', 'muhalhal'),
    'c2-creased': ('مجعد', 'mujaaad'),
    'c2-dapper': ('أنيق', 'aniq'),
    'c2-disheveled': ("أشعث", "ash'ath"),
    'c2-scruffy': ('مهمل المظهر', 'muhmal al-mazhar'),
    'c2-garish': ('فاقع', "fai'"),
    'c2-understated': ('بسيط الأناقة', 'basit al-anaqa'),
    'c2-flattering-clothes': ('لائق', "la'iq"),
    'c2-baggy': ('فضفاض', 'fadfad'),
    'c2-snug': ('محكم', 'muhkam'),
    'c2-stubble': ('لحية خفيفة', 'lihya khafifa'),
    'c2-freckles': ('نمش', 'namash'),
    'c2-dimple': ('غمازة', 'ghammaza'),
    'c2-crow-s-feet': ("تجاعيد حول العينين", "taja'id hawla al-aynayn"),
    'c2-complexion': ('بشرة', 'bashara'),
    'c2-gaunt': ('هزيل', 'hazil'),
    'c2-stocky': ('مكتنز', 'muktaniz'),
    'c2-lanky': ("فارع الطول", "fari' at-tul"),
    'c2-poised': ('رزين', 'razin'),
}
