# -*- coding: utf-8 -*-
LANG = 'vi'
WORDS = {
    'b1-friendship': ('Tình bạn', None),
    'b1-trust': ('Sự tin tưởng', None),
    'b1-to-trust': ('Tin tưởng', None),
    'b1-to-get-along': ('Hòa hợp', None),
    'b1-to-break-up': ('Chia tay', None),
    'b1-to-date-someone': ('Hẹn hò (với ai đó)', None),
    'b1-argument-quarrel': ('Cãi vã', None),
    'b1-to-forgive': ('Tha thứ', None),
    'b1-to-support': ('Ủng hộ', None),
    'b1-loyalty': ('Lòng trung thành', None),
    'b1-to-rely-on': ('Dựa vào', None),
    'b1-close-friend': ('Bạn thân', None),
    'b1-acquaintance': ('Người quen', None),
    'b1-partner-romantic': ('Người yêu', None),
    'b1-ex': ('Người yêu cũ', None),
    'b1-crush': ('Cảm nắng', None),
    'b1-to-flirt': ('Tán tỉnh', None),
    'b1-to-make-up-reconcile': ('Làm lành', None),
    'b1-to-hang-out': ('Đi chơi cùng bạn bè', None),
    'b1-to-get-to-know': ('Làm quen với', None),
    'b1-to-keep-in-touch': ('Giữ liên lạc', None),
    'b1-to-lose-touch': ('Mất liên lạc', None),
    'b1-reunion': ('Cuộc hội ngộ', None),
    'b1-to-introduce': ('Giới thiệu', None),
    'b1-respect': ('Sự tôn trọng', None),
    'b1-sincerity': ('Sự chân thành', None),
    'b1-best-friend': ('Bạn thân nhất', None),
    'b1-stranger': ('Người lạ', None),
    'b1-to-betray': ('Phản bội', None),
    'b1-bond': ('Mối liên kết', None),
    'b1-to-agree': ('Đồng ý', None),
    'b1-to-disagree': ('Không đồng ý', None),
    'b1-point-of-view': ('Quan điểm', None),
    'b1-argument-reasoning': ('Lập luận', None),
    'b1-to-convince': ('Thuyết phục', None),
    'b1-to-doubt': ('Nghi ngờ', None),
    'b1-to-admit': ('Thừa nhận', None),
    'b1-to-deny': ('Phủ nhận', None),
    'b1-to-insist': ('Khăng khăng', None),
    'b1-obviously': ('Rõ ràng là', None),
    'b1-probably': ('Có lẽ', None),
    'b1-definitely': ('Chắc chắn', None),
    'b1-according-to': ('Theo', None),
    'b1-on-the-other-hand': ('Mặt khác', None),
    'b1-however': ('Tuy nhiên', None),
    'b1-although': ('Mặc dù', None),
    'b1-therefore': ('Vì vậy', None),
    'b1-in-fact': ('Thực ra', None),
    'b1-whereas': ('Trong khi đó', None),
    'b1-unless': ('Trừ khi', None),
    'b1-in-spite-of': ('Bất chấp', None),
    'b1-as-long-as': ('Miễn là', None),
    'b1-to-consider': ('Cân nhắc', None),
    'b1-to-assume': ('Cho rằng', None),
    'b1-to-realize': ('Nhận ra', None),
    'b1-to-wonder': ('Tự hỏi', None),
    'b1-to-prove': ('Chứng minh', None),
    'b1-evidence': ('Bằng chứng', None),
    'b1-to-exaggerate': ('Phóng đại', None),
    'b1-fair': ('Công bằng', None),
    'b1-unfair': ('Không công bằng', None),
    'b1-anxious': ('Lo lắng', None),
    'b1-overwhelmed': ('Choáng ngợp', None),
    'b1-thrilled': ('Phấn khích', None),
    'b1-homesick': ('Nhớ nhà', None),
    'b1-moved-emotionally': ('Xúc động', None),
    'b1-guilty': ('Có lỗi', None),
    'b1-awkward': ('Ngượng ngùng', None),
    'b1-upset': ('Buồn bực', None),
    'b1-furious': ('Giận dữ', None),
    'b1-delighted': ('Vui sướng', None),
    'b1-hesitant': ('Do dự', None),
    'b1-indifferent': ('Thờ ơ', None),
    'b1-insecure': ('Thiếu tự tin', None),
    'b1-confident': ('Tự tin', None),
    'b1-motivated': ('Có động lực', None),
    'b1-exhausted': ('Kiệt sức', None),
    'b1-restless': ('Bồn chồn', None),
    'b1-grumpy': ('Cáu kỉnh', None),
    'b1-nostalgic': ('Hoài niệm', None),
    'b1-pleased': ('Hài lòng', None),
    'b1-annoyed': ('Khó chịu', None),
    'b1-terrified': ('Kinh hãi', None),
    'b1-amused': ('Thích thú', None),
    'b1-envious': ('Ghen tị', None),
    'b1-hopeless': ('Tuyệt vọng', None),
    'b1-bittersweet': ('Vui buồn lẫn lộn', None),
    'b1-at-ease': ('Thoải mái', None),
    'b1-uneasy': ('Bất an', None),
    'b1-speechless': ('Không nói nên lời', None),
    'b1-touched': ('Cảm động', None),
    'b1-to-apply-for-a-job': ('Nộp đơn xin việc', None),
    'b1-resume': ('Sơ yếu lý lịch', None),
    'b1-to-get-promoted': ('Được thăng chức', None),
    'b1-to-quit': ('Nghỉ việc', None),
    'b1-to-fire-someone': ('Sa thải', None),
    'b1-to-retire': ('Nghỉ hưu', None),
    'b1-part-time': ('Bán thời gian', None),
    'b1-full-time': ('Toàn thời gian', None),
    'b1-overtime': ('Làm thêm giờ', None),
    'b1-shift': ('Ca làm việc', None),
    'b1-to-negotiate': ('Đàm phán', None),
    'b1-contract': ('Hợp đồng', None),
    'b1-to-sign': ('Ký', None),
    'b1-freelance': ('Tự do (không theo biên chế)', None),
    'b1-presentation': ('Bài thuyết trình', None),
    'b1-teamwork': ('Làm việc nhóm', None),
    'b1-responsibility': ('Trách nhiệm', None),
    'b1-task': ('Nhiệm vụ', None),
    'b1-goal': ('Mục tiêu', None),
    'b1-feedback': ('Phản hồi', None),
    'b1-to-be-in-charge': ('Phụ trách', None),
    'b1-employee': ('Nhân viên', None),
    'b1-employer': ('Người sử dụng lao động', None),
    'b1-to-earn-a-living': ('Kiếm sống', None),
    'b1-workload': ('Khối lượng công việc', None),
    'b1-burnout': ('Kiệt sức vì công việc', None),
    'b1-day-off': ('Ngày nghỉ', None),
    'b1-vacation': ('Kỳ nghỉ', None),
    'b1-coworker': ('Đồng nghiệp', None),
    'b1-experience': ('Kinh nghiệm', None),
    'b1-skill': ('Kỹ năng', None),
    'b1-to-train-someone': ('Đào tạo', None),
    'b1-to-explore': ('Khám phá', None),
    'b1-adventure': ('Cuộc phiêu lưu', None),
    'b1-backpack': ('Ba lô', None),
    'b1-hostel': ('Nhà nghỉ tập thể', None),
    'b1-to-wander': ('Lang thang', None),
    'b1-landmark': ('Địa danh', None),
    'b1-view': ('Tầm nhìn', None),
    'b1-scenery': ('Phong cảnh', None),
    'b1-local-person': ('Người bản địa', None),
    'b1-custom-tradition': ('Phong tục', None),
    'b1-culture': ('Văn hóa', None),
    'b1-to-experience': ('Trải nghiệm', None),
    'b1-to-recommend': ('Đề xuất', None),
    'b1-itinerary': ('Lịch trình', None),
    'b1-unforgettable': ('Khó quên', None),
    'b1-jet-lag': ('Lệch múi giờ', None),
    'b1-to-pack': ('Xếp hành lý', None),
    'b1-destination': ('Điểm đến', None),
    'b1-journey': ('Hành trình', None),
    'b1-cruise': ('Du thuyền', None),
    'b1-to-rent-a-car': ('Thuê ô tô', None),
    'b1-border': ('Biên giới', None),
    'b1-visa': ('Thị thực', None),
    'b1-currency': ('Tiền tệ', None),
    'b1-to-take-a-photo': ('Chụp ảnh', None),
    'b1-to-get-around': ('Đi lại (trong thành phố)', None),
    'b1-off-the-beaten-path': ('Nơi ít người biết đến', None),
    'b1-tourist-trap': ('Bẫy du lịch', None),
    'b1-layover': ('Điểm quá cảnh', None),
    'b1-sunburn': ('Cháy nắng', None),
    'b1-to-work-out': ('Tập thể dục', None),
    'b1-diet': ('Chế độ ăn kiêng', None),
    'b1-to-lose-weight': ('Giảm cân', None),
    'b1-to-gain-weight': ('Tăng cân', None),
    'b1-muscle': ('Cơ bắp', None),
    'b1-to-stretch': ('Kéo giãn cơ', None),
    'b1-to-warm-up': ('Khởi động', None),
    'b1-calories': ('Calo', None),
    'b1-protein': ('Chất đạm', None),
    'b1-to-breathe': ('Thở', None),
    'b1-heartbeat': ('Nhịp tim', None),
    'b1-to-sweat': ('Đổ mồ hôi', None),
    'b1-to-recover': ('Hồi phục', None),
    'b1-sprain': ('Bong gân', None),
    'b1-to-faint': ('Ngất xỉu', None),
    'b1-dizzy': ('Chóng mặt', None),
    'b1-nausea': ('Buồn nôn', None),
    'b1-to-sneeze': ('Hắt hơi', None),
    'b1-symptom': ('Triệu chứng', None),
    'b1-vaccine': ('Vắc-xin', None),
    'b1-checkup': ('Khám sức khỏe', None),
    'b1-therapy': ('Liệu pháp trị liệu', None),
    'b1-to-quit-smoking': ('Bỏ thuốc lá', None),
    'b1-wellbeing': ('Sự an lành', None),
    'b1-mental-health': ('Sức khỏe tâm thần', None),
    'b1-to-meditate': ('Thiền', None),
    'b1-insomnia': ('Mất ngủ', None),
    'b1-energy': ('Năng lượng', None),
    'b1-painkiller': ('Thuốc giảm đau', None),
    'b1-sore': ('Đau nhức', None),
    'b1-cuisine': ('Ẩm thực', None),
    'b1-flavor': ('Hương vị', None),
    'b1-homemade': ('Tự làm tại nhà', None),
    'b1-mild': ('Nhẹ (không cay)', None),
    'b1-to-season': ('Nêm gia vị', None),
    'b1-portion': ('Khẩu phần', None),
    'b1-leftovers': ('Đồ ăn thừa', None),
    'b1-street-food': ('Đồ ăn đường phố', None),
    'b1-specialty': ('Món đặc sản', None),
    'b1-to-treat-pay-for-someone': ('Đãi (trả tiền cho ai đó)', None),
    'b1-to-split-the-bill': ('Chia tiền hóa đơn', None),
    'b1-tasty': ('Ngon', None),
    'b1-disgusting': ('Kinh tởm', None),
    'b1-to-chew': ('Nhai', None),
    'b1-to-swallow': ('Nuốt', None),
    'b1-appetite': ('Sự thèm ăn', None),
    'b1-craving': ('Cơn thèm', None),
    'b1-im-full': ('Tôi no rồi', None),
    'b1-to-skip-a-meal': ('Bỏ bữa', None),
    'b1-brunch': ('Bữa sáng muộn', None),
    'b1-to-grab-a-bite': ('Ăn nhanh gì đó', None),
    'b1-a-toast': ('Một lời chúc nâng ly', None),
    'b1-vegan': ('Thuần chay', None),
    'b1-gluten-free': ('Không chứa gluten', None),
    'b1-organic': ('Hữu cơ', None),
    'b1-recipe-book': ('Sách công thức nấu ăn', None),
    'b1-chopsticks': ('Đũa', None),
    'b1-napkin': ('Khăn ăn', None),
    'b1-reservation-for-dinner': ('Đặt bàn ăn tối', None),
    'b1-buffet': ('Tiệc buffet', None),
    'b1-mortgage': ('Khoản vay mua nhà', None),
    'b1-to-own': ('Sở hữu', None),
    'b1-lease': ('Hợp đồng thuê nhà', None),
    'b1-security-deposit': ('Tiền đặt cọc', None),
    'b1-utilities': ('Chi phí điện nước', None),
    'b1-cozy': ('Ấm cúng', None),
    'b1-spacious': ('Rộng rãi', None),
    'b1-to-decorate': ('Trang trí', None),
    'b1-to-renovate': ('Cải tạo', None),
    'b1-to-move-in': ('Chuyển đến nhà mới', None),
    'b1-to-move-out': ('Chuyển đi khỏi nhà', None),
    'b1-suburb': ('Ngoại ô', None),
    'b1-countryside': ('Vùng nông thôn', None),
    'b1-balcony': ('Ban công', None),
    'b1-basement': ('Tầng hầm', None),
    'b1-attic': ('Gác mái', None),
    'b1-garage': ('Nhà để xe', None),
    'b1-yard': ('Sân', None),
    'b1-fence': ('Hàng rào', None),
    'b1-to-lock': ('Khóa', None),
    'b1-doorbell': ('Chuông cửa', None),
    'b1-mailbox': ('Hộp thư', None),
    'b1-hallway': ('Hành lang', None),
    'b1-ceiling': ('Trần nhà', None),
    'b1-to-hang-a-picture': ('Treo (tranh)', None),
    'b1-neighborhood-watch': ('Đội tự quản khu phố', None),
    'b1-real-estate-agent': ('Môi giới bất động sản', None),
    'b1-property': ('Bất động sản', None),
    'b1-tenant': ('Người thuê nhà', None),
    'b1-furnished': ('Có nội thất đầy đủ', None),
    'b1-bargain': ('Món hời', None),
    'b1-to-haggle': ('Mặc cả', None),
    'b1-warranty': ('Bảo hành', None),
    'b1-to-exchange-goods': ('Đổi (hàng)', None),
    'b1-customer-service': ('Dịch vụ khách hàng', None),
    'b1-to-file-a-complaint': ('Nộp đơn khiếu nại', None),
    'b1-counterfeit': ('Hàng giả', None),
    'b1-second-hand': ('Đồ cũ', None),
    'b1-to-browse': ('Xem qua (dạo quanh cửa hàng)', None),
    'b1-to-subscribe': ('Đăng ký (theo dõi)', None),
    'b1-subscription': ('Gói đăng ký', None),
    'b1-membership': ('Tư cách thành viên', None),
    'b1-checkout': ('Quầy thanh toán', None),
    'b1-out-of-stock': ('Hết hàng', None),
    'b1-in-stock': ('Còn hàng', None),
    'b1-to-track-a-package': ('Theo dõi (đơn hàng)', None),
    'b1-fashion': ('Thời trang', None),
    'b1-style': ('Phong cách', None),
    'b1-trend': ('Xu hướng', None),
    'b1-to-match-clothes': ('Phối đồ', None),
    'b1-outfit': ('Bộ trang phục', None),
    'b1-to-suit-look-good-on': ('Hợp với (ai đó)', None),
    'b1-accessory': ('Phụ kiện', None),
    'b1-jewelry': ('Trang sức', None),
    'b1-perfume': ('Nước hoa', None),
    'b1-coupon': ('Phiếu giảm giá', None),
    'b1-free-shipping': ('Miễn phí vận chuyển', None),
    'b1-return-policy': ('Chính sách đổi trả', None),
    'b1-impulse-buy': ('Mua sắm bốc đồng', None),
    'b1-value-for-money': ('Đáng đồng tiền', None),
    'b1-to-avoid': ('Tránh', None),
    'b1-to-achieve': ('Đạt được', None),
    'b1-to-appreciate': ('Trân trọng', None),
    'b1-to-attend': ('Tham dự', None),
    'b1-to-belong': ('Thuộc về', None),
    'b1-to-bother': ('Làm phiền', None),
    'b1-to-care-about': ('Quan tâm đến', None),
    'b1-to-deal-with': ('Đối phó với', None),
    'b1-to-depend-on': ('Phụ thuộc vào', None),
    'b1-to-deserve': ('Xứng đáng', None),
    'b1-to-develop': ('Phát triển', None),
    'b1-to-disappear': ('Biến mất', None),
    'b1-to-encourage': ('Khuyến khích', None),
    'b1-to-expect': ('Mong đợi', None),
    'b1-to-handle': ('Xử lý', None),
    'b1-to-imagine': ('Tưởng tượng', None),
    'b1-to-improve': ('Cải thiện', None),
    'b1-to-increase': ('Tăng lên', None),
    'b1-to-decrease': ('Giảm xuống', None),
    'b1-to-involve': ('Liên quan đến (bao gồm)', None),
    'b1-to-mention': ('Đề cập đến', None),
    'b1-to-notice': ('Nhận thấy', None),
    'b1-to-offer': ('Đề nghị', None),
    'b1-to-organize': ('Tổ chức', None),
    'b1-to-participate': ('Tham gia', None),
    'b1-to-pretend': ('Giả vờ', None),
    'b1-to-protect': ('Bảo vệ', None),
    'b1-to-provide': ('Cung cấp', None),
    'b1-to-recognize': ('Nhận ra', None),
    'b1-to-refuse': ('Từ chối', None),
    'b1-to-reduce': ('Giảm bớt', None),
    'b1-to-regret': ('Hối tiếc', None),
    'b1-to-remain': ('Vẫn còn', None),
    'b1-to-replace': ('Thay thế', None),
    'b1-to-require': ('Yêu cầu', None),
    'b1-to-solve': ('Giải quyết', None),
    'b1-to-struggle': ('Vật lộn (khó khăn)', None),
    'b1-to-succeed': ('Thành công', None),
    'b1-to-suffer': ('Chịu đựng', None),
    'b1-to-survive': ('Sống sót', None),
    'b1-to-warn': ('Cảnh báo', None),
    'b1-to-manage-to-cope': ('Xoay xở', None),
    'b1-to-perform': ('Biểu diễn', None),
    'b1-to-fail-in-general': ('Thất bại', None),
    'b1-to-attempt': ('Cố gắng thử', None),
    'b1-to-complain-about': ('Phàn nàn về', None),
    'b1-to-rely-on-someone': ('Dựa vào ai đó', None),
    'b1-to-take-part': ('Góp mặt', None),
    'b1-to-turn-out': ('Hóa ra', None),
    'b1-to-end-up': ('Kết cục là', None),
    'b1-to-give-up': ('Từ bỏ', None),
    'b1-to-look-forward-to': ('Mong chờ', None),
    'b1-to-put-off': ('Trì hoãn', None),
    'b1-to-run-out-of': ('Hết (cạn)', None),
    'b1-to-get-rid-of': ('Loại bỏ', None),
    'b1-to-come-up-with': ('Nghĩ ra', None),
    'b1-to-figure-out': ('Tìm ra (hiểu ra)', None),
    'b1-to-catch-up': ('Bắt kịp', None),
    'b1-to-show-up': ('Xuất hiện', None),
    'b1-to-break-down-machine': ('Bị hỏng', None),
    'b1-to-fill-in-a-form': ('Điền vào (biểu mẫu)', None),
    'b1-to-pick-up-collect': ('Đón (lấy)', None),
    'b1-to-drop-off': ('Thả (ai đó) xuống', None),
    'b1-to-hang-up-phone': ('Cúp máy', None),
    'b1-to-look-after': ('Chăm sóc', None),
    'b1-reliable': ('Đáng tin cậy', None),
    'b1-responsible': ('Có trách nhiệm', None),
    'b1-ambitious': ('Tham vọng', None),
    'b1-creative': ('Sáng tạo', None),
    'b1-flexible': ('Linh hoạt', None),
    'b1-independent': ('Độc lập', None),
    'b1-mature': ('Chín chắn', None),
    'b1-sensitive': ('Nhạy cảm', None),
    'b1-sensible': ('Sáng suốt', None),
    'b1-selfish': ('Ích kỷ', None),
    'b1-humble': ('Khiêm tốn', None),
    'b1-arrogant': ('Kiêu ngạo', None),
    'b1-easygoing': ('Dễ tính', None),
    'b1-outgoing': ('Hướng ngoại', None),
    'b1-moody': ('Thất thường', None),
    'b1-picky': ('Kén chọn', None),
    'b1-clumsy': ('Vụng về', None),
    'b1-brave': ('Dũng cảm', None),
    'b1-cowardly': ('Nhát gan', None),
    'b1-wise': ('Khôn ngoan', None),
    'b1-naive': ('Ngây thơ', None),
    'b1-thoughtful': ('Chu đáo', None),
    'b1-careless': ('Bất cẩn', None),
    'b1-careful': ('Cẩn thận', None),
    'b1-punctual': ('Đúng giờ', None),
    'b1-greedy': ('Tham lam', None),
    'b1-loyal': ('Trung thành', None),
    'b1-charming': ('Duyên dáng', None),
    'b1-weird': ('Kỳ quặc', None),
    'b1-down-to-earth': ('Thực tế, giản dị', None),
    'b1-available': ('Có sẵn (rảnh)', None),
    'b1-convenient': ('Tiện lợi', None),
    'b1-complicated': ('Phức tạp', None),
    'b1-obvious': ('Rõ ràng', None),
    'b1-essential': ('Thiết yếu', None),
    'b1-necessary': ('Cần thiết', None),
    'b1-useful': ('Hữu ích', None),
    'b1-useless': ('Vô ích', None),
    'b1-worth-it': ('Đáng giá', None),
    'b1-affordable': ('Vừa túi tiền', None),
    'b1-valuable': ('Có giá trị', None),
    'b1-reasonable': ('Hợp lý', None),
    'b1-ridiculous': ('Lố bịch', None),
    'b1-impressive': ('Ấn tượng', None),
    'b1-disappointing': ('Đáng thất vọng', None),
    'b1-exciting': ('Thú vị, hào hứng', None),
    'b1-relaxing': ('Thư giãn', None),
    'b1-tiring': ('Mệt mỏi', None),
    'b1-annoying': ('Gây bực mình', None),
    'b1-embarrassing': ('Gây xấu hổ', None),
    'b1-confusing': ('Gây bối rối', None),
    'b1-satisfying': ('Thỏa mãn', None),
    'b1-awful': ('Kinh khủng', None),
    'b1-terrific': ('Tuyệt vời', None),
    'b1-decent': ('Tử tế, đàng hoàng', None),
    'b1-average': ('Trung bình', None),
    'b1-rare': ('Hiếm', None),
    'b1-common': ('Phổ biến', None),
    'b1-typical': ('Điển hình', None),
    'b1-unusual': ('Khác thường', None),
    'b1-first-of-all': ('Trước hết', None),
    'b1-then': ('Rồi', None),
    'b1-after-that': ('Sau đó', None),
    'b1-in-addition': ('Thêm vào đó', None),
    'b1-besides': ('Bên cạnh đó', None),
    'b1-for-instance': ('Ví dụ như', None),
    'b1-in-other-words': ('Nói cách khác', None),
    'b1-on-the-contrary': ('Ngược lại', None),
    'b1-nevertheless': ('Dù sao đi nữa', None),
    'b1-meanwhile': ('Trong lúc đó', None),
    'b1-as-a-result': ('Kết quả là', None),
    'b1-in-conclusion': ('Tóm lại', None),
    'b1-in-short': ('Nói ngắn gọn', None),
    'b1-at-first': ('Lúc đầu', None),
    'b1-eventually': ('Cuối cùng', None),
    'b1-otherwise': ('Nếu không thì', None),
    'b1-in-case': ('Phòng khi', None),
    'b1-as-soon-as': ('Ngay khi', None),
    'b1-even-though': ('Dù cho', None),
    'b1-as-if': ('Như thể', None),
    'b1-so-that': ('Để mà', None),
    'b1-in-order-to': ('Để', None),
    'b1-apart-from': ('Trừ ra', None),
    'b1-instead-of': ('Thay vì', None),
    'b1-despite': ('Bất kể', None),
    'b1-thanks-to': ('Nhờ có', None),
    'b1-above-all': ('Trên hết', None),
    'b1-basically': ('Về cơ bản', None),
    'b1-luckily': ('May mắn thay', None),
    'b1-unfortunately': ('Không may là', None),
    'b1-government': ('Chính phủ', None),
    'b1-election': ('Cuộc bầu cử', None),
    'b1-to-vote': ('Bỏ phiếu', None),
    'b1-law': ('Luật pháp', None),
    'b1-crime': ('Tội phạm', None),
    'b1-justice': ('Công lý', None),
    'b1-rights': ('Quyền lợi', None),
    'b1-freedom': ('Tự do', None),
    'b1-economy': ('Kinh tế', None),
    'b1-unemployment': ('Thất nghiệp', None),
    'b1-poverty': ('Nghèo đói', None),
    'b1-wealth': ('Sự giàu có', None),
    'b1-immigration': ('Nhập cư', None),
    'b1-protest': ('Cuộc biểu tình', None),
    'b1-strike': ('Cuộc đình công', None),
    'b1-war': ('Chiến tranh', None),
    'b1-peace': ('Hòa bình', None),
    'b1-citizen': ('Công dân', None),
    'b1-community': ('Cộng đồng', None),
    'b1-charity': ('Tổ chức từ thiện', None),
    'b1-volunteer': ('Tình nguyện viên', None),
    'b1-to-donate': ('Quyên góp', None),
    'b1-environment': ('Môi trường', None),
    'b1-pollution': ('Ô nhiễm', None),
    'b1-climate-change': ('Biến đổi khí hậu', None),
    'b1-to-recycle': ('Tái chế', None),
    'b1-waste-garbage': ('Rác thải', None),
    'b1-renewable-energy': ('Năng lượng tái tạo', None),
    'b1-population': ('Dân số', None),
    'b1-politics': ('Chính trị', None),
    'b1-series': ('Loạt phim', None),
    'b1-episode': ('Tập phim', None),
    'b1-season-tv': ('Mùa phim', None),
    'b1-plot': ('Cốt truyện', None),
    'b1-character-story': ('Nhân vật', None),
    'b1-ending': ('Cái kết', None),
    'b1-spoiler': ('Tiết lộ nội dung', None),
    'b1-soundtrack': ('Nhạc phim', None),
    'b1-trailer': ('Đoạn giới thiệu phim', None),
    'b1-to-binge-watch': ('Xem liền một mạch', None),
    'b1-documentary': ('Phim tài liệu', None),
    'b1-comedy': ('Phim hài', None),
    'b1-drama': ('Phim chính kịch', None),
    'b1-thriller': ('Phim giật gân', None),
    'b1-horror': ('Phim kinh dị', None),
    'b1-animation': ('Phim hoạt hình', None),
    'b1-novel': ('Tiểu thuyết', None),
    'b1-poem': ('Bài thơ', None),
    'b1-author': ('Tác giả', None),
    'b1-chapter': ('Chương', None),
    'b1-headline': ('Tiêu đề tin tức', None),
    'b1-article': ('Bài báo', None),
    'b1-magazine': ('Tạp chí', None),
    'b1-review': ('Bài đánh giá', None),
    'b1-rating': ('Xếp hạng', None),
    'b1-celebrity': ('Người nổi tiếng', None),
    'b1-fame': ('Danh tiếng', None),
    'b1-audience': ('Khán giả', None),
    'b1-live-broadcast': ('Trực tiếp', None),
    'b1-streaming': ('Phát trực tuyến', None),
    'b1-material': ('Chất liệu', None),
    'b1-wooden': ('Bằng gỗ', None),
    'b1-plastic': ('Bằng nhựa', None),
    'b1-metal': ('Kim loại', None),
    'b1-glass-material': ('Thủy tinh', None),
    'b1-leather': ('Da thuộc', None),
    'b1-cotton': ('Vải bông', None),
    'b1-wool': ('Len', None),
    'b1-silk': ('Lụa', None),
    'b1-smooth': ('Mịn', None),
    'b1-rough': ('Thô ráp', None),
    'b1-sharp': ('Sắc bén', None),
    'b1-blunt': ('Cùn', None),
    'b1-flat': ('Phẳng', None),
    'b1-thick': ('Dày', None),
    'b1-slim': ('Mỏng, mảnh', None),
    'b1-transparent': ('Trong suốt', None),
    'b1-shiny': ('Bóng loáng', None),
    'b1-dull': ('Xỉn màu', None),
    'b1-fragile': ('Dễ vỡ', None),
    'b1-sturdy': ('Chắc chắn', None),
    'b1-tiny': ('Nhỏ xíu', None),
    'b1-huge': ('Khổng lồ', None),
    'b1-medium': ('Cỡ vừa', None),
    'b1-pattern': ('Họa tiết', None),
    'b1-striped': ('Kẻ sọc', None),
    'b1-plain-no-pattern': ('Trơn, không họa tiết', None),
    'b1-fancy': ('Sang trọng, cầu kỳ', None),
    'b1-elegant': ('Thanh lịch', None),
    'b1-handmade': ('Làm bằng tay', None),
    'b1-lifetime': ('Cả cuộc đời', None),
    'b1-decade': ('Thập kỷ', None),
    'b1-century': ('Thế kỷ', None),
    'b1-era': ('Thời đại', None),
    'b1-youth': ('Tuổi trẻ', None),
    'b1-middle-age': ('Tuổi trung niên', None),
    'b1-old-age': ('Tuổi già', None),
    'b1-retirement': ('Sự nghỉ hưu', None),
    'b1-milestone': ('Cột mốc quan trọng', None),
    'b1-to-turn-an-age': ('Tròn (tuổi)', None),
    'b1-to-age': ('Già đi', None),
    'b1-life-expectancy': ('Tuổi thọ trung bình', None),
    'b1-memory-recollection': ('Ký ức', None),
    'b1-to-look-back': ('Nhìn lại', None),
    'b1-the-past': ('Quá khứ', None),
    'b1-the-present': ('Hiện tại', None),
    'b1-the-future': ('Tương lai', None),
    'b1-nowadays': ('Ngày nay', None),
    'b1-in-the-long-run': ('Về lâu dài', None),
    'b1-temporary': ('Tạm thời', None),
    'b1-permanent': ('Vĩnh viễn', None),
    'b1-forever': ('Mãi mãi', None),
    'b1-occasionally': ('Thỉnh thoảng', None),
    'b1-rarely': ('Hiếm khi', None),
    'b1-frequently': ('Thường xuyên', None),
    'b1-daily': ('Hàng ngày', None),
    'b1-weekly': ('Hàng tuần', None),
    'b1-monthly': ('Hàng tháng', None),
    'b1-annual': ('Hàng năm', None),
    'b1-generation-gap': ('Khoảng cách thế hệ', None),
    'b1-you-know-what-i-mean': ('Bạn hiểu ý tôi chứ?', None),
    'b1-i-see-what-you-mean': ('Tôi hiểu ý bạn', None),
    'b1-that-reminds-me': ('Điều đó làm tôi nhớ ra', None),
    'b1-speaking-of-which': ('Nhắc mới nhớ', None),
    'b1-long-story-short': ('Nói cho gọn', None),
    'b1-im-afraid-so': ('Tôi e là vậy', None),
    'b1-i-doubt-it': ('Tôi nghi ngờ điều đó', None),
    'b1-its-worth-a-try': ('Đáng để thử', None),
    'b1-take-it-easy': ('Thư giãn đi', None),
    'b1-dont-get-me-wrong': ('Đừng hiểu lầm tôi', None),
    'b1-i-couldnt-agree-more': ('Tôi hoàn toàn đồng ý', None),
    'b1-whats-up': ('Có gì mới không?', None),
    'b1-not-bad': ('Không tệ', None),
    'b1-so-far-so-good': ('Đến giờ vẫn ổn', None),
    'b1-its-been-a-while': ('Lâu rồi không gặp', None),
    'b1-guess-what': ('Đoán xem?', None),
    'b1-tell-me-about-it': ('Đúng là như vậy đó!', None),
    'b1-ill-let-you-know': ('Tôi sẽ báo cho bạn biết', None),
    'b1-count-me-in': ('Tính tôi vào cùng', None),
    'b1-id-rather-not': ('Tôi thà không', None),
    'b1-fair-enough': ('Cũng hợp lý', None),
    'b1-no-worries': ('Đừng lo', None),
    'b1-sounds-like-a-plan': ('Nghe có vẻ ổn đấy', None),
    'b1-lets-play-it-by-ear': ('Cứ để tùy cơ ứng biến', None),
    'b1-its-a-deal': ('Thỏa thuận vậy nhé', None),
    'b1-my-bad': ('Lỗi của tôi', None),
    'b1-how-come': ('Sao lại vậy?', None),
    'b1-never-mind-that': ('Đừng bận tâm chuyện đó', None),
    'b1-i-cant-stand-it': ('Tôi không chịu nổi', None),
    'b1-it-slipped-my-mind': ('Tôi quên mất', None),
    'b1-thought': ('Suy nghĩ', None),
    'b1-idea': ('Ý tưởng', None),
    'b1-to-concentrate': ('Tập trung', None),
    'b1-attention': ('Sự chú ý', None),
    'b1-to-focus': ('Chú tâm vào', None),
    'b1-to-daydream': ('Mơ mộng', None),
    'b1-imagination': ('Trí tưởng tượng', None),
    'b1-creativity': ('Sự sáng tạo', None),
    'b1-logic': ('Logic', None),
    'b1-reason-cause': ('Lý do', None),
    'b1-common-sense': ('Lẽ thường', None),
    'b1-intuition': ('Trực giác', None),
    'b1-to-guess': ('Đoán', None),
    'b1-to-predict': ('Dự đoán', None),
    'b1-to-make-up-ones-mind': ('Quyết định dứt khoát', None),
    'b1-decision': ('Quyết định', None),
    'b1-choice': ('Sự lựa chọn', None),
    'b1-to-hesitate': ('Do dự', None),
    'b1-to-plan-ahead': ('Lên kế hoạch trước', None),
    'b1-mindset': ('Lối suy nghĩ', None),
    'b1-perspective': ('Góc nhìn', None),
    'b1-to-overthink': ('Suy nghĩ quá nhiều', None),
    'b1-curiosity': ('Sự tò mò', None),
    'b1-knowledge': ('Kiến thức', None),
    'b1-wisdom': ('Trí tuệ', None),
    'b1-to-be-aware': ('Ý thức được', None),
    'b1-doubt-noun': ('Sự nghi ngờ', None),
    'b1-belief': ('Niềm tin', None),
    'b1-confusion': ('Sự bối rối', None),
    'b1-to-reflect-think-over': ('Suy ngẫm', None),
    'b1-to-nod': ('Gật đầu', None),
    'b1-to-shake-ones-head': ('Lắc đầu', None),
    'b1-to-wave': ('Vẫy tay', None),
    'b1-to-wink': ('Nháy mắt', None),
    'b1-to-blink': ('Chớp mắt', None),
    'b1-to-yawn': ('Ngáp', None),
    'b1-to-sigh': ('Thở dài', None),
    'b1-to-cough': ('Ho', None),
    'b1-to-lean': ('Nghiêng người, tựa vào', None),
    'b1-to-bend': ('Cúi, uốn cong', None),
    'b1-to-kneel': ('Quỳ xuống', None),
    'b1-to-crawl': ('Bò', None),
    'b1-to-tiptoe': ('Đi nhón chân', None),
    'b1-to-stumble': ('Vấp', None),
    'b1-to-trip-over': ('Vấp phải', None),
    'b1-to-slip': ('Trượt chân', None),
    'b1-to-grab': ('Nắm lấy, chộp', None),
    'b1-to-squeeze': ('Bóp, siết', None),
    'b1-to-scratch': ('Gãi', None),
    'b1-to-rub': ('Xoa, chà', None),
    'b1-to-shiver': ('Run rẩy', None),
    'b1-to-bite': ('Cắn', None),
    'b1-to-lick': ('Liếm', None),
    'b1-to-stare': ('Nhìn chằm chằm', None),
    'b1-to-glance': ('Liếc nhìn', None),
    'b1-to-frown': ('Cau mày', None),
    'b1-to-shrug': ('Nhún vai', None),
    'b1-to-point': ('Chỉ bằng ngón tay', None),
    'b1-to-clap': ('Vỗ tay', None),
    'b1-to-bow': ('Cúi chào', None),
    'b1-traffic-jam': ('Kẹt xe', None),
    'b1-rush-hour': ('Giờ cao điểm', None),
    'b1-speed-limit': ('Giới hạn tốc độ', None),
    'b1-fine-penalty': ('Tiền phạt', None),
    'b1-drivers-license': ('Bằng lái xe', None),
    'b1-to-park': ('Đỗ xe', None),
    'b1-highway': ('Đường cao tốc', None),
    'b1-lane': ('Làn đường', None),
    'b1-roundabout': ('Vòng xuyến', None),
    'b1-toll': ('Phí cầu đường', None),
    'b1-to-overtake': ('Vượt xe', None),
    'b1-seatbelt': ('Dây an toàn', None),
    'b1-engine': ('Động cơ', None),
    'b1-tire': ('Lốp xe', None),
    'b1-flat-tire': ('Lốp xe xẹp', None),
    'b1-to-tow': ('Kéo (xe)', None),
    'b1-fuel': ('Nhiên liệu', None),
    'b1-electric-car': ('Xe điện', None),
    'b1-to-give-a-ride': ('Chở đi bằng xe', None),
    'b1-to-hitchhike': ('Đi nhờ xe', None),
    'b1-to-miss-the-bus': ('Lỡ chuyến xe buýt', None),
    'b1-to-catch-the-train': ('Bắt kịp chuyến tàu', None),
    'b1-platform': ('Sân ga', None),
    'b1-timetable': ('Bảng giờ', None),
    'b1-to-be-delayed': ('Bị trễ', None),
    'b1-to-transfer-change-lines': ('Chuyển tuyến', None),
    'b1-pedestrian': ('Người đi bộ', None),
    'b1-crosswalk': ('Vạch qua đường', None),
    'b1-accident': ('Tai nạn', None),
    'b1-detour': ('Đường vòng', None),
    'b1-income': ('Thu nhập', None),
    'b1-expenses': ('Chi phí', None),
    'b1-to-invest': ('Đầu tư', None),
    'b1-investment': ('Khoản đầu tư', None),
    'b1-savings': ('Tiền tiết kiệm', None),
    'b1-pension': ('Lương hưu', None),
    'b1-inflation': ('Lạm phát', None),
    'b1-cost-of-living': ('Chi phí sinh hoạt', None),
    'b1-to-make-ends-meet': ('Xoay xở đủ sống', None),
    'b1-allowance': ('Tiền tiêu vặt', None),
    'b1-to-waste-money': ('Lãng phí tiền', None),
    'b1-to-be-broke': ('Hết tiền, cháy túi', None),
    'b1-wealthy': ('Giàu có', None),
    'b1-to-pay-back': ('Trả lại tiền', None),
    'b1-installment': ('Khoản trả góp', None),
    'b1-to-insure': ('Mua bảo hiểm', None),
    'b1-financial': ('Thuộc về tài chính', None),
    'b1-bank-transfer': ('Chuyển khoản ngân hàng', None),
    'b1-fee': ('Phí', None),
    'b1-to-overspend': ('Chi tiêu quá mức', None),
    'b1-stingy': ('Keo kiệt', None),
    'b1-thrifty': ('Tiết kiệm', None),
    'b1-cheapskate': ('Người bủn xỉn', None),
    'b1-profit': ('Lợi nhuận', None),
    'b1-loss-financial': ('Khoản lỗ', None),
    'b1-receipt-proof': ('Hóa đơn, biên nhận', None),
    'b1-tip-advice': ('Lời khuyên', None),
    'b1-to-split-costs': ('Chia sẻ chi phí', None),
    'b1-cash-flow': ('Dòng tiền', None),
    'b1-deal-agreement': ('Thỏa thuận', None),
    'b1-lecture': ('Bài giảng', None),
    'b1-seminar': ('Hội thảo chuyên đề', None),
    'b1-essay': ('Bài luận', None),
    'b1-thesis': ('Luận văn', None),
    'b1-research': ('Nghiên cứu', None),
    'b1-to-research': ('Tiến hành nghiên cứu', None),
    'b1-tutor': ('Gia sư', None),
    'b1-campus': ('Khuôn viên trường', None),
    'b1-dormitory': ('Ký túc xá', None),
    'b1-major-field-of-study': ('Chuyên ngành', None),
    'b1-to-major-in': ('Học chuyên ngành', None),
    'b1-to-drop-out': ('Bỏ học', None),
    'b1-to-enroll': ('Ghi danh nhập học', None),
    'b1-tuition': ('Học phí', None),
    'b1-assignment': ('Bài tập', None),
    'b1-group-work': ('Bài tập nhóm', None),
    'b1-to-cheat': ('Gian lận', None),
    'b1-plagiarism': ('Đạo văn', None),
    'b1-extension-deadline': ('Gia hạn', None),
    'b1-to-submit': ('Nộp bài', None),
    'b1-transcript': ('Bảng điểm', None),
    'b1-certificate': ('Chứng chỉ', None),
    'b1-workshop': ('Buổi tập huấn', None),
    'b1-internship': ('Thực tập', None),
    'b1-apprenticeship': ('Học nghề', None),
    'b1-exchange-program': ('Chương trình trao đổi', None),
    'b1-to-study-abroad': ('Du học', None),
    'b1-curriculum': ('Chương trình học', None),
    'b1-professor': ('Giáo sư', None),
    'b1-grant': ('Khoản tài trợ', None),
    'b1-microwave': ('Lò vi sóng', None),
    'b1-dishwasher': ('Máy rửa bát', None),
    'b1-toaster': ('Máy nướng bánh mì', None),
    'b1-kettle': ('Ấm đun nước', None),
    'b1-blender': ('Máy xay sinh tố', None),
    'b1-hair-dryer': ('Máy sấy tóc', None),
    'b1-air-conditioner': ('Máy điều hòa', None),
    'b1-heater': ('Máy sưởi', None),
    'b1-fan-appliance': ('Quạt điện', None),
    'b1-remote-control': ('Điều khiển từ xa', None),
    'b1-outlet-socket': ('Ổ cắm điện', None),
    'b1-plug': ('Phích cắm', None),
    'b1-cable': ('Dây cáp', None),
    'b1-light-bulb': ('Bóng đèn', None),
    'b1-switch': ('Công tắc', None),
    'b1-thermostat': ('Bộ điều nhiệt', None),
    'b1-smoke-detector': ('Máy báo khói', None),
    'b1-router': ('Bộ định tuyến', None),
    'b1-appliance': ('Thiết bị gia dụng', None),
    'b1-to-plug-in': ('Cắm điện', None),
    'b1-to-unplug': ('Rút phích cắm', None),
    'b1-to-adjust': ('Điều chỉnh', None),
    'b1-to-reset': ('Đặt lại', None),
    'b1-tool': ('Dụng cụ', None),
    'b1-screwdriver': ('Tua vít', None),
    'b1-hammer': ('Búa', None),
    'b1-nail-metal': ('Đinh', None),
    'b1-drill': ('Máy khoan', None),
    'b1-tape-adhesive': ('Băng dính', None),
    'b1-ladder': ('Thang', None),
    'b1-breeze': ('Gió nhẹ', None),
    'b1-drizzle': ('Mưa phùn', None),
    'b1-downpour': ('Mưa như trút', None),
    'b1-hail': ('Mưa đá', None),
    'b1-frost': ('Sương giá', None),
    'b1-ice': ('Băng', None),
    'b1-heatwave': ('Đợt nắng nóng', None),
    'b1-sunrise': ('Bình minh', None),
    'b1-sunset': ('Hoàng hôn', None),
    'b1-dawn': ('Rạng sáng', None),
    'b1-dusk': ('Chạng vạng', None),
    'b1-shade': ('Bóng râm', None),
    'b1-shadow': ('Cái bóng', None),
    'b1-rainbow': ('Cầu vồng', None),
    'b1-flood': ('Lũ lụt', None),
    'b1-drought': ('Hạn hán', None),
    'b1-earthquake': ('Động đất', None),
    'b1-hurricane': ('Bão lớn', None),
    'b1-tornado': ('Lốc xoáy', None),
    'b1-blizzard': ('Bão tuyết', None),
    'b1-mild-weather': ('Ôn hòa', None),
    'b1-chilly': ('Se lạnh', None),
    'b1-freezing': ('Lạnh cóng', None),
    'b1-muggy': ('Oi bức', None),
    'b1-clear-sky': ('Trời quang đãng', None),
    'b1-overcast': ('Nhiều mây, u ám', None),
    'b1-lightning': ('Tia chớp', None),
    'b1-avalanche': ('Tuyết lở', None),
    'b1-wildfire': ('Cháy rừng', None),
    'b1-volcano': ('Núi lửa', None),
    'b1-to-comfort': ('An ủi', None),
    'b1-to-reassure': ('Trấn an', None),
    'b1-to-blame': ('Đổ lỗi', None),
    'b1-to-praise': ('Khen ngợi', None),
    'b1-compliment': ('Lời khen', None),
    'b1-criticism': ('Sự phê bình', None),
    'b1-to-criticize': ('Phê bình', None),
    'b1-to-tease': ('Trêu chọc', None),
    'b1-to-bully': ('Bắt nạt', None),
    'b1-to-insult': ('Sỉ nhục', None),
    'b1-to-offend': ('Xúc phạm', None),
    'b1-to-congratulate': ('Chúc mừng', None),
    'b1-to-greet': ('Chào hỏi', None),
    'b1-to-welcome': ('Chào đón', None),
    'b1-sympathy': ('Sự cảm thông', None),
    'b1-empathy': ('Sự đồng cảm', None),
    'b1-to-cheer-on': ('Cổ vũ', None),
    'b1-to-show-off': ('Khoe khoang', None),
    'b1-to-brag': ('Khoác lác', None),
    'b1-to-gossip': ('Buôn chuyện', None),
    'b1-rumor': ('Tin đồn', None),
    'b1-to-ignore': ('Phớt lờ', None),
    'b1-to-interrupt': ('Ngắt lời', None),
    'b1-to-nag': ('Cằn nhằn', None),
    'b1-to-persuade': ('Khuyên nhủ', None),
    'b1-to-beg': ('Van xin', None),
    'b1-to-threaten': ('Đe dọa', None),
    'b1-to-reject': ('Khước từ', None),
    'b1-favor': ('Ơn, sự giúp đỡ', None),
    'b1-small-talk': ('Chuyện phiếm', None),
}
