# -*- coding: utf-8 -*-
LANG = 'nl'
WORDS = {
    'b2-honesty': ('Eerlijkheid', None),
    'b2-integrity': ('Integriteit', None),
    'b2-dignity': ('Waardigheid', None),
    'b2-morality': ('Moraliteit', None),
    'b2-principle': ('Principe', None),
    'b2-virtue': ('Deugd', None),
    'b2-vice': ('Ondeugd', None),
    'b2-greed': ('Hebzucht', None),
    'b2-courage': ('Moed', None),
    'b2-cowardice': ('Lafheid', None),
    'b2-generosity': ('Vrijgevigheid', None),
    'b2-gratitude': ('Dankbaarheid', None),
    'b2-compassion': ('Medeleven', None),
    'b2-tolerance': ('Tolerantie', None),
    'b2-prejudice': ('Vooroordeel', None),
    'b2-discrimination': ('Discriminatie', None),
    'b2-equality': ('Gelijkheid', None),
    'b2-inequality': ('Ongelijkheid', None),
    'b2-fairness': ('Rechtvaardigheid', None),
    'b2-corruption': ('Corruptie', None),
    'b2-temptation': ('Verleiding', None),
    'b2-guilt': ('Schuldgevoel', None),
    'b2-shame': ('Schaamte', None),
    'b2-pride-self-respect': ('Trots (eigenwaarde)', None),
    'b2-humility': ('Nederigheid', None),
    'b2-ambition': ('Ambitie', None),
    'b2-patience': ('Geduld', None),
    'b2-sacrifice': ('Offer', None),
    'b2-duty': ('Plicht', None),
    'b2-conscience': ('Geweten', None),
    'b2-hypocrisy': ('Hypocrisie', None),
    'b2-forgiveness': ('Vergeving', None),
    'b2-agenda': ('Agenda', None),
    'b2-minutes-of-a-meeting': ('Notulen', None),
    'b2-department': ('Afdeling', None),
    'b2-branch-office': ('Vestiging', None),
    'b2-headquarters': ('Hoofdkantoor', None),
    'b2-revenue': ('Omzet', None),
    'b2-stakeholder': ('Belanghebbende', None),
    'b2-shareholder': ('Aandeelhouder', None),
    'b2-client': ('Klant (zakelijk)', None),
    'b2-supplier': ('Leverancier', None),
    'b2-quote-price-estimate': ('Prijsopgave', None),
    'b2-proposal': ('Voorstel', None),
    'b2-bid': ('Bod (aanbesteding)', None),
    'b2-merger': ('Fusie', None),
    'b2-layoff': ('Ontslag (bezuiniging)', None),
    'b2-to-outsource': ('Uitbesteden', None),
    'b2-to-delegate': ('Delegeren', None),
    'b2-to-supervise': ('Toezicht houden op', None),
    'b2-performance-review': ('Functioneringsgesprek', None),
    'b2-strategy': ('Strategie', None),
    'b2-target': ('Doel (streefcijfer)', None),
    'b2-quarter-business': ('Kwartaal', None),
    'b2-benchmark': ('IJkpunt', None),
    'b2-to-brainstorm': ('Brainstormen', None),
    'b2-to-network': ('Netwerken', None),
    'b2-to-prioritize': ('Prioriteren', None),
    'b2-to-streamline': ('Stroomlijnen', None),
    'b2-startup': ('Startup', None),
    'b2-entrepreneur': ('Ondernemer', None),
    'b2-profit-margin': ('Winstmarge', None),
    'b2-competitor': ('Concurrent', None),
    'b2-milestone-project': ('Mijlpaal (project)', None),
    'b2-suspect': ('Verdachte', None),
    'b2-witness': ('Getuige', None),
    'b2-victim': ('Slachtoffer', None),
    'b2-trial': ('Proces (rechtszaak)', None),
    'b2-judge': ('Rechter', None),
    'b2-jury': ('Jury', None),
    'b2-verdict': ('Vonnis', None),
    'b2-convicted': ('Veroordeeld', None),
    'b2-innocent': ('Onschuldig', None),
    'b2-prison-sentence': ('Gevangenisstraf', None),
    'b2-theft': ('Diefstal', None),
    'b2-robbery': ('Roofoverval', None),
    'b2-burglary': ('Inbraak', None),
    'b2-fraud': ('Fraude', None),
    'b2-bribery': ('Omkoping', None),
    'b2-assault': ('Mishandeling', None),
    'b2-murder': ('Moord', None),
    'b2-kidnapping': ('Ontvoering', None),
    'b2-smuggling': ('Smokkel', None),
    'b2-to-arrest': ('Arresteren', None),
    'b2-to-charge-with-a-crime': ('Beschuldigen (van een misdrijf)', None),
    'b2-to-sue': ('Aanklagen (voor de rechter)', None),
    'b2-lawsuit': ('Rechtszaak', None),
    'b2-court': ('Rechtbank', None),
    'b2-prosecutor': ('Officier van justitie', None),
    'b2-defense-legal': ('Verdediging', None),
    'b2-appeal-legal': ('Beroep (juridisch)', None),
    'b2-bail': ('Borgtocht', None),
    'b2-alibi': ('Alibi', None),
    'b2-custody-police': ('Voorarrest', None),
    'b2-investigation': ('Onderzoek (politie)', None),
    'b2-detective': ('Rechercheur', None),
    'b2-experiment': ('Experiment', None),
    'b2-hypothesis': ('Hypothese', None),
    'b2-theory': ('Theorie', None),
    'b2-data': ('Gegevens', None),
    'b2-analysis': ('Analyse', None),
    'b2-to-analyze': ('Analyseren', None),
    'b2-to-measure': ('Meten', None),
    'b2-laboratory': ('Laboratorium', None),
    'b2-chemical': ('Chemisch', None),
    'b2-molecule': ('Molecuul', None),
    'b2-atom': ('Atoom', None),
    'b2-cell-biology': ('Cel (biologie)', None),
    'b2-gene': ('Gen', None),
    'b2-evolution': ('Evolutie', None),
    'b2-species': ('Soort', None),
    'b2-gravity': ('Zwaartekracht', None),
    'b2-orbit': ('Baan (omloopbaan)', None),
    'b2-satellite': ('Satelliet', None),
    'b2-artificial-intelligence': ('Kunstmatige intelligentie', None),
    'b2-algorithm': ('Algoritme', None),
    'b2-software': ('Software', None),
    'b2-hardware': ('Hardware', None),
    'b2-database': ('Database', None),
    'b2-to-code-program': ('Programmeren', None),
    'b2-bug-software': ('Bug (software)', None),
    'b2-encryption': ('Versleuteling', None),
    'b2-cybersecurity': ('Cyberveiligheid', None),
    'b2-virtual-reality': ('Virtuele realiteit', None),
    'b2-innovation': ('Innovatie', None),
    'b2-breakthrough': ('Doorbraak', None),
    'b2-robot': ('Robot', None),
    'b2-automation': ('Automatisering', None),
    'b2-sustainability': ('Duurzaamheid', None),
    'b2-sustainable': ('Duurzaam', None),
    'b2-carbon-footprint': ('Koolstofvoetafdruk', None),
    'b2-emissions': ('Uitstoot', None),
    'b2-greenhouse-gas': ('Broeikasgas', None),
    'b2-global-warming': ('Opwarming van de aarde', None),
    'b2-deforestation': ('Ontbossing', None),
    'b2-biodiversity': ('Biodiversiteit', None),
    'b2-ecosystem': ('Ecosysteem', None),
    'b2-habitat': ('Habitat', None),
    'b2-endangered-species': ('Bedreigde diersoort', None),
    'b2-extinction': ('Uitsterven', None),
    'b2-conservation': ('Natuurbehoud', None),
    'b2-wildlife': ('Wilde dieren', None),
    'b2-natural-resources': ('Natuurlijke hulpbronnen', None),
    'b2-fossil-fuels': ('Fossiele brandstoffen', None),
    'b2-solar-panel': ('Zonnepaneel', None),
    'b2-wind-turbine': ('Windturbine', None),
    'b2-landfill': ('Vuilnisbelt', None),
    'b2-compost': ('Compost', None),
    'b2-to-conserve': ('Besparen (op)', None),
    'b2-to-preserve': ('Behouden', None),
    'b2-sea-level': ('Zeeniveau', None),
    'b2-glacier': ('Gletsjer', None),
    'b2-to-melt': ('Smelten', None),
    'b2-famine': ('Hongersnood', None),
    'b2-overpopulation': ('Overbevolking', None),
    'b2-to-pollute': ('Vervuilen', None),
    'b2-single-use-plastic': ('Wegwerpplastic', None),
    'b2-environmentalist': ('Milieuactivist', None),
    'b2-recycling-bin': ('Recyclingbak', None),
    'b2-organic-farming': ('Biologische landbouw', None),
    'b2-diagnosis': ('Diagnose', None),
    'b2-to-diagnose': ('Diagnosticeren', None),
    'b2-treatment': ('Behandeling', None),
    'b2-surgery': ('Operatie', None),
    'b2-surgeon': ('Chirurg', None),
    'b2-anesthesia': ('Verdoving', None),
    'b2-to-prescribe': ('Voorschrijven', None),
    'b2-dose': ('Dosis', None),
    'b2-side-effect': ('Bijwerking', None),
    'b2-chronic': ('Chronisch', None),
    'b2-acute': ('Acuut', None),
    'b2-infection': ('Infectie', None),
    'b2-virus': ('Virus', None),
    'b2-bacteria': ('Bacteriën', None),
    'b2-immune-system': ('Immuunsysteem', None),
    'b2-antibiotic': ('Antibioticum', None),
    'b2-transplant': ('Transplantatie', None),
    'b2-stroke': ('Beroerte', None),
    'b2-heart-attack': ('Hartaanval', None),
    'b2-diabetes': ('Diabetes', None),
    'b2-cancer': ('Kanker', None),
    'b2-asthma': ('Astma', None),
    'b2-blood-test': ('Bloedonderzoek', None),
    'b2-x-ray': ('Röntgenfoto', None),
    'b2-scan-medical': ('Scan (medisch)', None),
    'b2-ward': ('Afdeling (ziekenhuis)', None),
    'b2-intensive-care': ('Intensive care', None),
    'b2-recovery': ('Herstel', None),
    'b2-disability': ('Handicap', None),
    'b2-wheelchair': ('Rolstoel', None),
    'b2-ambulance': ('Ambulance', None),
    'b2-pregnant': ('Zwanger', None),
    'b2-contagious': ('Besmettelijk', None),
    'b2-behavior': ('Gedrag', None),
    'b2-personality': ('Persoonlijkheid', None),
    'b2-trait': ('Karaktertrek', None),
    'b2-motivation': ('Motivatie', None),
    'b2-willpower': ('Wilskracht', None),
    'b2-self-esteem': ('Zelfrespect', None),
    'b2-self-confidence': ('Zelfvertrouwen', None),
    'b2-anxiety': ('Angst', None),
    'b2-depression': ('Depressie', None),
    'b2-stress': ('Stress', None),
    'b2-trauma': ('Trauma', None),
    'b2-grief': ('Rouw', None),
    'b2-to-cope': ('Omgaan met', None),
    'b2-comfort-zone': ('Comfortzone', None),
    'b2-procrastination': ('Uitstelgedrag', None),
    'b2-to-procrastinate': ('Uitstellen', None),
    'b2-perfectionism': ('Perfectionisme', None),
    'b2-introvert': ('Introvert', None),
    'b2-extrovert': ('Extravert', None),
    'b2-mindfulness': ('Mindfulness', None),
    'b2-resilience': ('Veerkracht', None),
    'b2-to-overcome': ('Overwinnen', None),
    'b2-obsession': ('Obsessie', None),
    'b2-addiction': ('Verslaving', None),
    'b2-denial': ('Ontkenning', None),
    'b2-bias': ('Vooringenomenheid', None),
    'b2-stereotype': ('Stereotype', None),
    'b2-peer-pressure': ('Groepsdruk', None),
    'b2-self-awareness': ('Zelfbewustzijn', None),
    'b2-empathy-deep': ('Empathie (diepgaand)', None),
    'b2-therapist': ('Therapeut', None),
    'b2-instinct': ('Instinct', None),
    'b2-to-acknowledge': ('Erkennen', None),
    'b2-to-adapt': ('Aanpassen', None),
    'b2-to-anticipate': ('Anticiperen', None),
    'b2-to-assess': ('Beoordelen', None),
    'b2-to-assign': ('Toewijzen', None),
    'b2-to-assure': ('Verzekeren (garanderen)', None),
    'b2-to-calculate': ('Berekenen', None),
    'b2-to-clarify': ('Verduidelijken', None),
    'b2-to-collaborate': ('Samenwerken', None),
    'b2-to-compromise': ('Een compromis sluiten', None),
    'b2-to-conclude': ('Concluderen', None),
    'b2-to-confirm': ('Bevestigen', None),
    'b2-to-confront': ('Confronteren', None),
    'b2-to-contribute': ('Bijdragen', None),
    'b2-to-define': ('Definiëren', None),
    'b2-to-demonstrate': ('Aantonen', None),
    'b2-to-dismiss': ('Afwijzen', None),
    'b2-to-distinguish': ('Onderscheiden', None),
    'b2-to-dominate': ('Domineren', None),
    'b2-to-eliminate': ('Elimineren', None),
    'b2-to-emphasize': ('Benadrukken', None),
    'b2-to-enable': ('Mogelijk maken', None),
    'b2-to-enhance': ('Verbeteren (versterken)', None),
    'b2-to-ensure': ('Waarborgen', None),
    'b2-to-establish': ('Vestigen (oprichten)', None),
    'b2-to-estimate': ('Schatten', None),
    'b2-to-evaluate': ('Evalueren', None),
    'b2-to-exceed': ('Overtreffen', None),
    'b2-to-exploit': ('Uitbuiten', None),
    'b2-to-facilitate': ('Faciliteren', None),
    'b2-to-generate': ('Genereren', None),
    'b2-to-guarantee': ('Garanderen', None),
    'b2-to-highlight': ('Uitlichten', None),
    'b2-to-identify': ('Identificeren', None),
    'b2-to-illustrate': ('Illustreren', None),
    'b2-to-implement': ('Implementeren', None),
    'b2-to-imply': ('Impliceren', None),
    'b2-to-indicate': ('Aangeven', None),
    'b2-to-influence': ('Beïnvloeden', None),
    'b2-to-inspire': ('Inspireren', None),
    'b2-to-interpret': ('Interpreteren', None),
    'b2-to-justify': ('Rechtvaardigen', None),
    'b2-to-maintain': ('Onderhouden (handhaven)', None),
    'b2-to-modify': ('Wijzigen', None),
    'b2-to-monitor': ('Monitoren', None),
    'b2-to-motivate': ('Motiveren', None),
    'b2-to-obtain': ('Verkrijgen', None),
    'b2-to-oppose': ('Zich verzetten tegen', None),
    'b2-to-perceive': ('Waarnemen', None),
    'b2-to-persist': ('Volharden', None),
    'b2-to-possess': ('Bezitten', None),
    'b2-to-prevent': ('Voorkomen', None),
    'b2-to-pursue': ('Nastreven', None),
    'b2-to-reinforce': ('Versterken', None),
    'b2-to-resolve': ('Oplossen', None),
    'b2-to-restrict': ('Beperken', None),
    'b2-to-retain': ('Vasthouden (behouden)', None),
    'b2-to-reveal': ('Onthullen', None),
    'b2-to-sustain': ('Ondersteunen (in stand houden)', None),
    'b2-to-tackle': ('Aanpakken', None),
    'b2-to-transform': ('Transformeren', None),
    'b2-to-undergo': ('Ondergaan', None),
    'b2-to-undertake': ('Ondernemen', None),
    'b2-to-verify': ('Verifiëren', None),
    'b2-to-abandon': ('Verlaten (opgeven)', None),
    'b2-to-accompany': ('Vergezellen', None),
    'b2-to-accumulate': ('Opstapelen', None),
    'b2-to-alter': ('Veranderen', None),
    'b2-to-approve': ('Goedkeuren', None),
    'b2-to-attach': ('Bijvoegen', None),
    'b2-to-cease': ('Ophouden', None),
    'b2-to-commit-to': ('Zich vastleggen op', None),
    'b2-to-comply': ('Naleven', None),
    'b2-to-conduct-carry-out': ('Uitvoeren', None),
    'b2-to-consist-of': ('Bestaan uit', None),
    'b2-to-convert': ('Omzetten', None),
    'b2-to-cooperate': ('Meewerken', None),
    'b2-to-decline-refuse': ('Weigeren', None),
    'b2-to-detect': ('Detecteren', None),
    'b2-to-devote': ('Wijden aan', None),
    'b2-to-emerge': ('Opkomen', None),
    'b2-to-exclude': ('Uitsluiten', None),
    'b2-to-expand': ('Uitbreiden', None),
    'b2-to-fulfill': ('Vervullen', None),
    'b2-to-impose': ('Opleggen', None),
    'b2-to-integrate': ('Integreren', None),
    'b2-to-neglect': ('Verwaarlozen', None),
    'b2-to-overlook': ('Over het hoofd zien', None),
    'b2-to-reconsider': ('Heroverwegen', None),
    'b2-to-withdraw-pull-out': ('Zich terugtrekken', None),
    'b2-accurate': ('Nauwkeurig', None),
    'b2-adequate': ('Toereikend', None),
    'b2-ambiguous': ('Dubbelzinnig', None),
    'b2-apparent': ('Ogenschijnlijk', None),
    'b2-appropriate': ('Passend', None),
    'b2-arbitrary': ('Willekeurig', None),
    'b2-coherent': ('Samenhangend', None),
    'b2-comprehensive': ('Uitgebreid', None),
    'b2-consistent': ('Consistent', None),
    'b2-controversial': ('Controversieel', None),
    'b2-crucial': ('Cruciaal', None),
    'b2-deliberate': ('Opzettelijk', None),
    'b2-distinct': ('Duidelijk onderscheiden', None),
    'b2-diverse': ('Divers', None),
    'b2-dominant': ('Dominant', None),
    'b2-efficient': ('Efficiënt', None),
    'b2-elaborate': ('Uitgewerkt', None),
    'b2-explicit': ('Expliciet', None),
    'b2-implicit': ('Impliciet', None),
    'b2-fundamental': ('Fundamenteel', None),
    'b2-genuine': ('Oprecht (echt)', None),
    'b2-inevitable': ('Onvermijdelijk', None),
    'b2-legitimate': ('Legitiem', None),
    'b2-mutual': ('Wederzijds', None),
    'b2-neutral': ('Neutraal', None),
    'b2-notable': ('Opmerkelijk', None),
    'b2-precise': ('Precies (gedetailleerd)', None),
    'b2-prominent': ('Prominent', None),
    'b2-relevant': ('Relevant', None),
    'b2-irrelevant': ('Irrelevant', None),
    'b2-rigid': ('Rigide', None),
    'b2-subtle': ('Subtiel', None),
    'b2-sufficient': ('Voldoende', None),
    'b2-tremendous': ('Enorm', None),
    'b2-vague': ('Vaag', None),
    'b2-vast': ('Uitgestrekt', None),
    'b2-vital': ('Essentieel', None),
    'b2-widespread': ('Wijdverbreid', None),
    'b2-reluctant': ('Terughoudend', None),
    'b2-thorough': ('Grondig', None),
    'b2-abstract': ('Abstract', None),
    'b2-concrete': ('Concreet', None),
    'b2-absurd': ('Absurd', None),
    'b2-alarming': ('Alarmerend', None),
    'b2-biased': ('Bevooroordeeld', None),
    'b2-compelling': ('Overtuigend', None),
    'b2-contradictory': ('Tegenstrijdig', None),
    'b2-credible': ('Geloofwaardig', None),
    'b2-feasible': ('Haalbaar', None),
    'b2-flawed': ('Gebrekkig', None),
    'b2-innovative': ('Innovatief', None),
    'b2-obsolete': ('Verouderd', None),
    'b2-outstanding': ('Uitstekend', None),
    'b2-persistent': ('Aanhoudend', None),
    'b2-profound': ('Diepgaand', None),
    'b2-redundant': ('Overbodig', None),
    'b2-superficial': ('Oppervlakkig', None),
    'b2-trivial': ('Triviaal', None),
    'b2-unprecedented': ('Ongekend', None),
    'b2-versatile': ('Veelzijdig', None),
    'b2-as-far-as-im-concerned': ('Wat mij betreft', None),
    'b2-to-some-extent': ('In zekere mate', None),
    'b2-in-terms-of': ('Wat betreft', None),
    'b2-with-regard-to': ('Met betrekking tot', None),
    'b2-on-the-whole': ('Over het algemeen', None),
    'b2-by-and-large': ('Grotendeels', None),
    'b2-in-the-meantime': ('Ondertussen', None),
    'b2-at-the-same-time': ('Tegelijkertijd', None),
    'b2-needless-to-say': ('Overbodig te zeggen', None),
    'b2-to-put-it-simply': ('Simpel gezegd', None),
    'b2-in-a-nutshell': ('Kort gezegd', None),
    'b2-having-said-that': ('Dat gezegd hebbende', None),
    'b2-as-a-matter-of-fact': ('In feite', None),
    'b2-for-the-time-being': ('Voorlopig', None),
    'b2-on-second-thought': ('Bij nader inzien', None),
    'b2-all-things-considered': ('Alles bij elkaar genomen', None),
    'b2-if-anything': ('Als er al iets is', None),
    'b2-in-any-case': ('In elk geval', None),
    'b2-more-or-less': ('Min of meer', None),
    'b2-sooner-or-later': ('Vroeg of laat', None),
    'b2-every-now-and-then': ('Af en toe', None),
    'b2-on-purpose': ('Met opzet', None),
    'b2-by-accident': ('Per ongeluk', None),
    'b2-by-all-means': ('Zeker (ga vooral je gang)', None),
    'b2-for-the-sake-of': ('Omwille van', None),
    'b2-up-to-a-point': ('Tot op zekere hoogte', None),
    'b2-to-say-the-least': ('Op zijn zachtst gezegd', None),
    'b2-in-hindsight': ('Achteraf gezien', None),
    'b2-strictly-speaking': ('Strikt genomen', None),
    'b2-broadly-speaking': ('In grote lijnen', None),
    'b2-parliament': ('Parlement', None),
    'b2-president': ('President', None),
    'b2-prime-minister': ('Premier', None),
    'b2-minister': ('Minister', None),
    'b2-mayor': ('Burgemeester', None),
    'b2-policy': ('Beleid', None),
    'b2-reform': ('Hervorming', None),
    'b2-legislation': ('Wetgeving', None),
    'b2-bill-proposed-law': ('Wetsvoorstel', None),
    'b2-referendum': ('Referendum', None),
    'b2-campaign': ('Campagne', None),
    'b2-candidate': ('Kandidaat', None),
    'b2-political-party': ('Politieke partij', None),
    'b2-opposition': ('Oppositie', None),
    'b2-coalition': ('Coalitie', None),
    'b2-majority': ('Meerderheid', None),
    'b2-minority': ('Minderheid', None),
    'b2-scandal': ('Schandaal', None),
    'b2-budget-deficit': ('Begrotingstekort', None),
    'b2-national-debt': ('Staatsschuld', None),
    'b2-recession': ('Recessie', None),
    'b2-economic-growth': ('Economische groei', None),
    'b2-interest-rate': ('Rentevoet', None),
    'b2-stock-market': ('Aandelenmarkt', None),
    'b2-shares-stocks': ('Aandelen', None),
    'b2-investor': ('Investeerder', None),
    'b2-trade-commerce': ('Handel', None),
    'b2-tariff': ('Tarief (invoerrecht)', None),
    'b2-export': ('Export', None),
    'b2-import': ('Import', None),
    'b2-bankruptcy': ('Faillissement', None),
    'b2-monopoly': ('Monopolie', None),
    'b2-in-laws': ('Schoonfamilie', None),
    'b2-mother-in-law': ('Schoonmoeder', None),
    'b2-stepmother': ('Stiefmoeder', None),
    'b2-sibling': ('Broer of zus', None),
    'b2-spouse': ('Echtgenoot/echtgenote', None),
    'b2-fiance': ('Verloofde', None),
    'b2-engagement': ('Verloving', None),
    'b2-to-propose-marriage': ('Ten huwelijk vragen', None),
    'b2-honeymoon': ('Huwelijksreis', None),
    'b2-single-parent': ('Alleenstaande ouder', None),
    'b2-godparent': ('Peetouder', None),
    'b2-guardian': ('Voogd', None),
    'b2-orphan': ('Wees', None),
    'b2-adoption': ('Adoptie', None),
    'b2-to-adopt': ('Adopteren', None),
    'b2-upbringing': ('Opvoeding', None),
    'b2-household': ('Huishouden', None),
    'b2-breadwinner': ('Kostwinner', None),
    'b2-ancestor': ('Voorouder', None),
    'b2-descendant': ('Afstammeling', None),
    'b2-heritage': ('Erfgoed', None),
    'b2-inheritance': ('Erfenis', None),
    'b2-to-inherit': ('Erven', None),
    'b2-will-testament': ('Testament', None),
    'b2-widow': ('Weduwe', None),
    'b2-elderly': ('Ouderen', None),
    'b2-caregiver': ('Verzorger', None),
    'b2-retirement-home': ('Bejaardentehuis', None),
    'b2-kinship': ('Verwantschap', None),
    'b2-role-model': ('Rolmodel', None),
    'b2-painting': ('Schilderij', None),
    'b2-sculpture': ('Beeldhouwwerk', None),
    'b2-exhibition': ('Tentoonstelling', None),
    'b2-gallery': ('Galerie', None),
    'b2-masterpiece': ('Meesterwerk', None),
    'b2-portrait': ('Portret', None),
    'b2-landscape-painting': ('Landschap (schilderij)', None),
    'b2-canvas': ('Canvas (schildersdoek)', None),
    'b2-sketch': ('Schets', None),
    'b2-festival': ('Festival', None),
    'b2-parade': ('Optocht', None),
    'b2-folklore': ('Folklore', None),
    'b2-myth': ('Mythe', None),
    'b2-legend': ('Legende', None),
    'b2-literature': ('Literatuur', None),
    'b2-genre': ('Genre', None),
    'b2-metaphor': ('Metafoor', None),
    'b2-rhyme': ('Rijm', None),
    'b2-verse': ('Vers', None),
    'b2-orchestra': ('Orkest', None),
    'b2-symphony': ('Symfonie', None),
    'b2-opera': ('Opera', None),
    'b2-choir': ('Koor', None),
    'b2-rehearsal': ('Repetitie', None),
    'b2-premiere': ('Première', None),
    'b2-applause': ('Applaus', None),
    'b2-playwright': ('Toneelschrijver', None),
    'b2-script': ('Script (tekst)', None),
    'b2-stage': ('Podium', None),
    'b2-backstage': ('Achter de schermen', None),
    'b2-costume': ('Kostuum', None),
    'b2-director-film': ('Regisseur', None),
    'b2-producer': ('Producent', None),
    'b2-screenplay': ('Filmscenario', None),
    'b2-to-marinate': ('Marineren', None),
    'b2-to-grill': ('Grillen', None),
    'b2-to-roast': ('Roosteren (in de oven)', None),
    'b2-to-steam': ('Stomen', None),
    'b2-to-simmer': ('Zachtjes laten sudderen', None),
    'b2-to-saute': ('Sauteren', None),
    'b2-to-whisk': ('Kloppen (mengen)', None),
    'b2-to-knead': ('Kneden', None),
    'b2-dough': ('Deeg', None),
    'b2-batter': ('Beslag', None),
    'b2-crust': ('Korst', None),
    'b2-to-grate': ('Raspen', None),
    'b2-to-peel': ('Schillen', None),
    'b2-to-chop': ('Hakken (snijden)', None),
    'b2-to-slice': ('In plakjes snijden', None),
    'b2-to-dice': ('In blokjes snijden', None),
    'b2-to-stir': ('Roeren', None),
    'b2-seasoning': ('Kruiden (smaakmaker)', None),
    'b2-herb': ('Kruid', None),
    'b2-spice': ('Specerij', None),
    'b2-cinnamon': ('Kaneel', None),
    'b2-ginger': ('Gember', None),
    'b2-basil': ('Basilicum', None),
    'b2-vinegar': ('Azijn', None),
    'b2-soy-sauce': ('Sojasaus', None),
    'b2-broth': ('Bouillon', None),
    'b2-stew': ('Stoofpot', None),
    'b2-crispy': ('Krokant', None),
    'b2-tender': ('Mals', None),
    'b2-juicy': ('Sappig', None),
    'b2-greasy': ('Vettig', None),
    'b2-stale': ('Oudbakken', None),
    'b2-rotten': ('Rot', None),
    'b2-sour': ('Zuur', None),
    'b2-savory': ('Hartig', None),
    'b2-skyscraper': ('Wolkenkrabber', None),
    'b2-infrastructure': ('Infrastructuur', None),
    'b2-public-transport': ('Openbaar vervoer', None),
    'b2-congestion': ('Verkeersopstopping', None),
    'b2-urban': ('Stedelijk', None),
    'b2-rural': ('Landelijk', None),
    'b2-district': ('Wijk', None),
    'b2-gentrification': ('Gentrificatie', None),
    'b2-housing-crisis': ('Woningcrisis', None),
    'b2-homelessness': ('Dakloosheid', None),
    'b2-shelter': ('Opvang (schuilplaats)', None),
    'b2-pedestrian-zone': ('Voetgangerszone', None),
    'b2-bike-lane': ('Fietspad', None),
    'b2-green-space': ('Groene ruimte', None),
    'b2-high-rise': ('Hoogbouw', None),
    'b2-zoning': ('Zonering', None),
    'b2-demolition': ('Sloop', None),
    'b2-construction-site': ('Bouwplaats', None),
    'b2-crane': ('Kraan (bouw)', None),
    'b2-scaffolding': ('Steiger', None),
    'b2-blueprint': ('Bouwtekening', None),
    'b2-permit': ('Vergunning', None),
    'b2-contractor': ('Aannemer', None),
    'b2-foundation-building': ('Fundering', None),
    'b2-insulation': ('Isolatie', None),
    'b2-plumbing': ('Loodgieterswerk', None),
    'b2-wiring': ('Bedrading', None),
    'b2-beam': ('Balk', None),
    'b2-drywall': ('Gipsplaat', None),
    'b2-inspection': ('Inspectie', None),
    'b2-tenant-improvement': ('Huurdersaanpassing', None),
    'b2-deadline-construction': ('Opleverdatum', None),
    'b2-contempt': ('Minachting', None),
    'b2-resentment': ('Wrok', None),
    'b2-bitterness': ('Bitterheid', None),
    'b2-longing': ('Verlangen', None),
    'b2-dread': ('Angst (voorgevoel)', None),
    'b2-apprehension': ('Bezorgdheid', None),
    'b2-serenity': ('Sereniteit', None),
    'b2-contentment': ('Tevredenheid', None),
    'b2-euphoria': ('Euforie', None),
    'b2-melancholy': ('Melancholie', None),
    'b2-remorse': ('Berouw', None),
    'b2-humiliation': ('Vernedering', None),
    'b2-rage': ('Woede', None),
    'b2-awe': ('Ontzag', None),
    'b2-indignation': ('Verontwaardiging', None),
    'b2-disgust': ('Walging', None),
    'b2-boredom': ('Verveling', None),
    'b2-agony': ('Doodsangst (kwelling)', None),
    'b2-ecstasy': ('Extase', None),
    'b2-complacency': ('Zelfgenoegzaamheid', None),
    'b2-disbelief': ('Ongeloof', None),
    'b2-suspicion': ('Achterdocht', None),
    'b2-reluctance': ('Onwil', None),
    'b2-eagerness': ('Enthousiasme (ongeduld)', None),
    'b2-fondness': ('Genegenheid', None),
    'b2-tenderness': ('Tederheid', None),
    'b2-affection': ('Affectie', None),
    'b2-to-resent': ('Wrok koesteren tegen', None),
    'b2-to-loathe': ('Verafschuwen', None),
    'b2-to-cherish': ('Koesteren', None),
    'b2-to-despise': ('Verachten', None),
    'b2-to-dread': ('Vrezen (met angst)', None),
    'b2-to-state': ('Stellen', None),
    'b2-statement': ('Verklaring', None),
    'b2-to-claim': ('Beweren', None),
    'b2-to-declare': ('Verklaren', None),
    'b2-to-announce': ('Aankondigen', None),
    'b2-announcement': ('Aankondiging', None),
    'b2-to-assert': ('Beweren (met klem)', None),
    'b2-to-hint': ('Hinten (laten doorschemeren)', None),
    'b2-to-confess': ('Bekennen', None),
    'b2-confession': ('Bekentenis', None),
    'b2-to-object': ('Bezwaar maken', None),
    'b2-objection': ('Bezwaar', None),
    'b2-to-summarize': ('Samenvatten', None),
    'b2-summary': ('Samenvatting', None),
    'b2-to-elaborate': ('Uitweiden', None),
    'b2-to-paraphrase': ('Parafraseren', None),
    'b2-to-quote': ('Citeren', None),
    'b2-quotation': ('Citaat', None),
    'b2-reference': ('Verwijzing', None),
    'b2-to-address-an-issue': ('Aanpakken (een kwestie)', None),
    'b2-to-convey': ('Overbrengen', None),
    'b2-to-articulate': ('Verwoorden', None),
    'b2-to-reiterate': ('Herhalen', None),
    'b2-remark': ('Opmerking', None),
    'b2-to-comment': ('Commentaar geven', None),
    'b2-to-consult': ('Raadplegen', None),
    'b2-to-advocate': ('Pleiten voor', None),
    'b2-to-mediate': ('Bemiddelen', None),
    'b2-compromise-noun': ('Compromis', None),
    'b2-negotiation': ('Onderhandeling', None),
    'b2-persuasive': ('Overtuigend', None),
    'b2-tactful': ('Tactvol', None),
    'b2-blunt-direct': ('Bot (direct)', None),
    'b2-efficiency': ('Efficiëntie', None),
    'b2-productivity': ('Productiviteit', None),
    'b2-to-do-list': ('Takenlijst', None),
    'b2-reminder': ('Herinnering', None),
    'b2-to-reschedule': ('Verzetten (afspraak)', None),
    'b2-calendar': ('Kalender', None),
    'b2-time-zone': ('Tijdzone', None),
    'b2-daylight-saving-time': ('Zomertijd', None),
    'b2-punctuality': ('Stiptheid', None),
    'b2-ahead-of-schedule': ('Voor op schema', None),
    'b2-behind-schedule': ('Achter op schema', None),
    'b2-in-advance': ('Van tevoren', None),
    'b2-last-minute': ('Op het laatste moment', None),
    'b2-overdue': ('Achterstallig', None),
    'b2-to-squeeze-in': ('Inplannen (met moeite)', None),
    'b2-to-multitask': ('Multitasken', None),
    'b2-to-allocate': ('Toebedelen', None),
    'b2-downtime': ('Stilstand (rusttijd)', None),
    'b2-spare-time': ('Vrije tijd', None),
    'b2-to-kill-time': ('De tijd doden', None),
    'b2-pastime': ('Tijdverdrijf', None),
    'b2-leisure': ('Ontspanning', None),
    'b2-on-the-dot': ('Precies op tijd', None),
    'b2-around-the-clock': ('Dag en nacht', None),
    'b2-in-the-nick-of-time': ('Nog net op tijd', None),
    'b2-long-term': ('Langetermijn- (adj.)', None),
    'b2-short-term': ('Kortetermijn- (adj.)', None),
    'b2-simultaneously': ('Gelijktijdig', None),
    'b2-continent': ('Continent', None),
    'b2-hemisphere': ('Halfrond', None),
    'b2-equator': ('Evenaar', None),
    'b2-latitude': ('Breedtegraad', None),
    'b2-altitude': ('Hoogte', None),
    'b2-valley': ('Vallei', None),
    'b2-canyon': ('Kloof (canyon)', None),
    'b2-cliff': ('Klif', None),
    'b2-cave': ('Grot', None),
    'b2-plateau': ('Plateau', None),
    'b2-peninsula': ('Schiereiland', None),
    'b2-bay': ('Baai', None),
    'b2-coast': ('Kust', None),
    'b2-shore': ('Oever', None),
    'b2-harbor': ('Haven', None),
    'b2-dune': ('Duin', None),
    'b2-iceberg': ('IJsberg', None),
    'b2-swamp': ('Moeras', None),
    'b2-jungle': ('Jungle', None),
    'b2-rainforest': ('Regenwoud', None),
    'b2-savanna': ('Savanne', None),
    'b2-tundra': ('Toendra', None),
    'b2-oasis': ('Oase', None),
    'b2-waterfall': ('Waterval', None),
    'b2-stream': ('Beek', None),
    'b2-spring-water': ('Bron', None),
    'b2-reef': ('Rif', None),
    'b2-tide': ('Getij', None),
    'b2-current-water': ('Stroming', None),
    'b2-horizon': ('Horizon', None),
    'b2-skeleton': ('Skelet', None),
    'b2-bone': ('Bot', None),
    'b2-skull': ('Schedel', None),
    'b2-spine': ('Ruggengraat', None),
    'b2-rib': ('Rib', None),
    'b2-joint': ('Gewricht', None),
    'b2-tendon': ('Pees', None),
    'b2-nerve': ('Zenuw', None),
    'b2-brain': ('Hersenen', None),
    'b2-lung': ('Long', None),
    'b2-liver': ('Lever', None),
    'b2-kidney': ('Nier', None),
    'b2-intestine': ('Darm', None),
    'b2-artery': ('Slagader', None),
    'b2-vein': ('Ader', None),
    'b2-pulse': ('Polsslag', None),
    'b2-wrist': ('Pols', None),
    'b2-ankle': ('Enkel', None),
    'b2-elbow': ('Elleboog', None),
    'b2-thigh': ('Dij', None),
    'b2-heel': ('Hiel', None),
    'b2-palm': ('Handpalm', None),
    'b2-thumb': ('Duim', None),
    'b2-eyebrow': ('Wenkbrauw', None),
    'b2-eyelash': ('Wimper', None),
    'b2-chin': ('Kin', None),
    'b2-cheek': ('Wang', None),
    'b2-forehead': ('Voorhoofd', None),
    'b2-jaw': ('Kaak', None),
    'b2-throat': ('Keel', None),
    'b2-tongue': ('Tong (orgaan)', None),
    'b2-lip': ('Lip', None),
    'b2-tailor': ('Kleermaker', None),
    'b2-fabric': ('Stof', None),
    'b2-seam': ('Naad', None),
    'b2-zipper': ('Rits', None),
    'b2-button': ('Knoop', None),
    'b2-collar': ('Kraag', None),
    'b2-sleeve': ('Mouw', None),
    'b2-hem': ('Zoom', None),
    'b2-pocket': ('Zak', None),
    'b2-lining': ('Voering', None),
    'b2-to-fasten': ('Vastmaken', None),
    'b2-to-unbutton': ('Losknopen', None),
    'b2-to-fold': ('Vouwen', None),
    'b2-wardrobe': ('Kledingkast', None),
    'b2-hanger': ('Kleerhanger', None),
    'b2-detergent': ('Wasmiddel', None),
    'b2-stain': ('Vlek', None),
    'b2-to-shrink': ('Krimpen', None),
    'b2-to-fade': ('Verbleken', None),
    'b2-wrinkle': ('Kreukel', None),
    'b2-formal-wear': ('Formele kleding', None),
    'b2-casual-wear': ('Casual kleding', None),
    'b2-uniform': ('Uniform', None),
    'b2-suit': ('Pak', None),
    'b2-tie': ('Stropdas', None),
    'b2-high-heels': ('Hoge hakken', None),
    'b2-sneakers': ('Sneakers', None),
    'b2-boots': ('Laarzen', None),
    'b2-sandals': ('Sandalen', None),
    'b2-slippers': ('Pantoffels', None),
    'b2-pajamas': ('Pyjama', None),
    'b2-underwear': ('Ondergoed', None),
    'b2-belt': ('Riem', None),
    'b2-concept': ('Concept', None),
    'b2-notion': ('Notie', None),
    'b2-aspect': ('Aspect', None),
    'b2-factor': ('Factor', None),
    'b2-feature': ('Kenmerk', None),
    'b2-element': ('Element', None),
    'b2-component': ('Component', None),
    'b2-structure': ('Structuur', None),
    'b2-function': ('Functie', None),
    'b2-process': ('Proces', None),
    'b2-procedure': ('Procedure', None),
    'b2-method': ('Methode', None),
    'b2-approach': ('Benadering', None),
    'b2-technique': ('Techniek', None),
    'b2-framework': ('Raamwerk', None),
    'b2-criterion': ('Criterium', None),
    'b2-standard': ('Standaard', None),
    'b2-norm': ('Norm', None),
    'b2-exception': ('Uitzondering', None),
    'b2-phase': ('Fase', None),
    'b2-sequence': ('Volgorde', None),
    'b2-outcome': ('Uitkomst', None),
    'b2-consequence': ('Gevolg', None),
    'b2-impact': ('Impact', None),
    'b2-implication': ('Implicatie', None),
    'b2-significance': ('Belang (betekenis)', None),
    'b2-context': ('Context', None),
    'b2-scope': ('Bereik (omvang)', None),
    'b2-scale-magnitude': ('Schaal', None),
    'b2-dimension': ('Dimensie', None),
    'b2-proportion': ('Verhouding', None),
    'b2-ratio': ('Ratio', None),
    'b2-barely': ('Nauwelijks', None),
    'b2-hardly': ('Amper', None),
    'b2-merely': ('Louter', None),
    'b2-utterly': ('Volkomen', None),
    'b2-thoroughly': ('Grondig', None),
    'b2-fairly': ('Tamelijk', None),
    'b2-rather': ('Eerder (nogal)', None),
    'b2-somewhat': ('Enigszins', None),
    'b2-slightly': ('Licht (een beetje)', None),
    'b2-considerably': ('Aanzienlijk', None),
    'b2-significantly': ('Aanmerkelijk', None),
    'b2-roughly': ('Ongeveer', None),
    'b2-precisely': ('Precies', None),
    'b2-virtually': ('Vrijwel', None),
    'b2-entirely': ('Volledig', None),
    'b2-partially': ('Gedeeltelijk', None),
    'b2-mostly': ('Meestal', None),
    'b2-increasingly': ('Steeds meer', None),
    'b2-gradually': ('Geleidelijk', None),
    'b2-rapidly': ('Snel', None),
    'b2-steadily': ('Gestaag', None),
    'b2-abruptly': ('Abrupt', None),
    'b2-ultimately': ('Uiteindelijk', None),
    'b2-altogether': ('In totaal', None),
    'b2-whatsoever': ('Ook maar enigszins', None),
    'b2-nonetheless': ('Niettemin', None),
    'b2-deliberately': ('Opzettelijk', None),
    'b2-reluctantly': ('Met tegenzin', None),
    'b2-knitting': ('Breien', None),
    'b2-sewing': ('Naaien', None),
    'b2-pottery': ('Pottenbakken', None),
    'b2-woodworking': ('Houtbewerking', None),
    'b2-gardening': ('Tuinieren', None),
    'b2-birdwatching': ('Vogels spotten', None),
    'b2-kayaking': ('Kajakken', None),
    'b2-rock-climbing': ('Klimmen (rotsklimmen)', None),
    'b2-martial-arts': ('Vechtsporten', None),
    'b2-boxing': ('Boksen', None),
    'b2-archery': ('Boogschieten', None),
    'b2-bowling': ('Bowlen', None),
    'b2-karaoke': ('Karaoke', None),
    'b2-esports': ('E-sports', None),
    'b2-collectible': ('Verzamelobject', None),
    'b2-cosplay': ('Cosplay', None),
    'b2-3d-printing': ('3D-printen', None),
    'b2-tabletop-role-playing-game': ('Tafelrollenspel', None),
    'b2-miniature-figure': ('Miniatuur (figuurtje)', None),
    'b2-dice': ('Dobbelstenen', None),
    'b2-campaign-game': ('Campagne (spel)', None),
    'b2-hobbyist': ('Hobbyist', None),
    'b2-craft': ('Ambacht', None),
    'b2-workbench': ('Werkbank', None),
    'b2-glue': ('Lijm', None),
    'b2-sandpaper': ('Schuurpapier', None),
    'b2-paintbrush': ('Kwast', None),
    'b2-prototype': ('Prototype', None),
}
