# -*- coding: utf-8 -*-
LANG = 'la'

SENTENCES = {
    'b1-dr1': ['Disco', 'currum', 'agere'],
    'b1-dr2': ['Soleo', 'mane', 'expergisci'],
    'b1-dr3': ['Heri', 'totam domum', 'purgavi'],
    'b1-dr4': ['Numquam', 'diem operis', 'omisi'],
    'b1-fs1': ['Frater meus', 'non', 'exercetur'],
    'b1-fs2': ['Parentes nostros', 'vocare', 'debemus'],
    'b1-fs3': ['Potesne', 'me adiuvare', 'in hoc,', 'quaeso?'],
    'b1-fs4': ['Soror mea', 'loquacior est', 'quam ego'],
    'b1-te1': ['Heri', 'urbem novam', 'visitavi'],
    'b1-te2': ['Si pluet,', 'in deversorio', 'manebimus'],
    'b1-te3': ['Numquam', 'Iaponiam', 'adii'],
    'b1-te4': ['Potesne', 'bonum deversorium', 'commendare?'],
    'b1-op1': ['Musica', 'valde', 'sonora est'],
    'b1-op2': ['Haec urbs', 'carior est', 'quam illa'],
    'b1-op3': ['Puto', 'hunc librum', 'valde iucundum', 'esse'],
    'b1-op4': ['Mea sententia,', 'mature', 'proficisci', 'debemus'],
    'c2-s01': ['Sincere dicam,', 'bis cogitavissem', 'antequam', 'tale quid', 'subscriberem'],
    'c2-s02': ['Non est quod nihil curem,', 'sed quod', 'nihil amplius', 'dandum habeo'],
    'c2-s03': ['Quidquid feceris,', 'noli sinere', 'ut tibi', 'persuadeat'],
    'c2-s04': ['Si scivissem', 'hoc tam diu', 'tracturum esse,', 'numquam', 'consensissem'],
    'c2-s05': ['Illa rem neglexit,', 'sed apparebat', 'eam id', 'permovisse'],
    'c2-s06': ['Dicas quod voles', 'de illo,', 'sed', 'res gerit'],
    'c2-s07': ['Non sum', 'veniam petiturus', 'pro re', 'quam ne feci quidem'],
    'c2-s08': ['Dum tandem', 'id reficere', 'aggrediuntur,', 'damnum', 'iam factum erat'],
    'c2-s09': ['Inter nos dictum sit,', 'non puto', 'pactionem', 'confectum iri'],
    'c2-s10': ['Crederes', 'eos iam', 'didicisse,', 'nonne?'],
    'c2-s11': ['Vix', 'consederamus', 'cum', 'tintinnabulum incendii', 'sonuit'],
    'c2-s12': ['Si tibi aeque est,', 'mallem', 'hoc inter nos', 'maneret'],
    'c1-m01': ['Res publica', 'nova consilia', 'ad inflationem minuendam', 'nuntiavit'],
    'c1-m02': ['Ut nuntiatum est,', 'inopia operis', 'tertio mense', 'continuo', 'decrevit'],
    'c1-m03': ['Numquam dixi', 'me discessurum esse;', 'dixi', 'me tempore egere'],
    'c1-m04': ['Quidquid hac nocte', 'acciderit,', 'noli', 'illam ianuam', 'aperire'],
    'c1-m05': ['Physici monent', 'glaciem', 'intra decem annos', 'disparituram esse'],
    'c1-m06': ['Si mihi', 'veritatem', 'dixisses,', 'nihil horum', 'accidisset'],
    'c1-m07': ['Suspectus', 'paulo post', 'comprehensus est', 'quam vigiles', 'indicium anonymum', 'acceperunt'],
    'c1-m08': ['Sincere dicam,', 'puto', 'nos ambos', 'culpandos esse', 'eius rei quae accidit'],
    'c1-m09': ['Societas', 'crimina negavit', 'sed', 'amplius dicere', 'recusavit'],
    'c1-m10': ['Non scis', 'quid reliquerim', 'ut huc', 'pervenirem'],
    'c1-m11': ['Suffragatores', 'die Solis', 'ad comitia ibunt', 'inter crescentem dubitationem'],
    'c1-m12': ['Dicamus tantum', 'id non evenisse', 'ut', 'consilium ceperam'],
}

DIALOGUES = {
    'd-a2-01': ['Salve, Marta sum. Gaudeo te cognoscere.', 'Et ego gaudeo; Alexander sum.', 'Non, gratias.', 'Ad dextram est.', 'Hora tertia est.'],
    'd-a2-02': ['Unde es?', 'Sum ex Chicagia, in Civitatibus Foederatis Americae.', 'Mihi sunt viginti anni.', 'Cafea mihi placet.', 'In argentaria laboro.'],
    'd-a2-03': ['Quid facis ut vivas?', 'Sum designator, domi laboro.', 'Prope hortum publicum habito.', 'Theam malo.', 'Cras pluet.'],
    'd-a2-04': ['Quamdiu hic es?', 'Duos menses hic sum.', 'Decem euronis constat.', 'Diebus Solis clausum est.', 'Duos fratres habeo.'],
    'd-a2-05': ['Habesne fratres?', 'Sic, sororem maiorem natu.', 'Sic, hora octava.', 'Non, nimis carum est.', 'In culina est.'],
    'd-a2-06': ['Gratias quod venisti, mox iterum!', 'Tibi gratias ago, optimum fuit! Mox iterum.', 'Cupio poculum cafeae.', 'Ignosce, non intellego.', 'Latrina illic est.'],
    'd-a2-07': ['Quam frigidum est hodie, nonne?', 'Sic, valde. Et dicunt cras nivem casuram esse.', 'Sic, Alexander vocor.', 'Non, fratres non habeo.', 'Quinque euronis constat.'],
    'd-a2-08': ['Quid consilii habes in fine hebdomadis?', 'Parentes meos visitabo.', 'In officio laboro.', 'Ad sinistram est.', 'Rubrum malo.'],
    'd-a2-09': ['Bibemusne cras cafeam simul?', 'Certe! Placetne tibi hora decima?', 'Ex Matrito sum.', 'Canem habeo.', 'Multum pluit.'],
    'd-a2-10': ['Qua hora incipit pellicula?', 'Incipit hora septima et dimidia.', 'Valde longinquum est.', 'Mihi valde placet.', 'Discipulus sum.'],
    'd-a2-11': ['Quomodo hodie tibi fuit?', 'Satis bene, sed fessus sum.', 'Duo eurones sunt.', 'In tertio tabulato habito.', 'Soror mea est.'],
    'd-a2-12': ['Quo vadis?', 'Ad macellum, nihil ad cenam habeo.', 'Triginta annos habeo.', 'Valde calet.', 'Sic, paulum loquor.'],
    'd-b1-01': ['Quam diu! Quid egisti?', 'Nam duobus mensibus abhinc opus mutavi et valde gaudeo.', 'Traha hora nona proficiscitur.', 'Theam cafeae praefero.', 'Duobus a hoc loco insulis abest.'],
    'd-b1-02': ['Nuper valde anxius sum ob opus.', 'Doleo id audire. Visne de eo loqui?', 'Ego birotam novam emi.', 'Pellicula hora octava incipit.', 'Soror mea Romae habitat.'],
    'd-b1-03': ['Quomodo iter fuit? Omnia mihi narra!', 'Mirabile. Cibus, homines… iam reverti cupio.', 'Lac emere debeo.', 'Ab hora nona ad quintam laboro.', 'Ianuario frigus est.'],
    'd-b1-04': ['Lucia et ego proxima hebdomade diiuncti sumus.', 'Eheu, hoc nesciebam. Quomodo id feres?', 'Gratulor! Quam bonum nuntium!', 'Qua hora convenimus?', 'Museum diebus Lunae clauditur.'],
    'd-b1-05': ['Adhucne ad gymnasium is?', 'Vere, id reliqui. Nunc mane curro.', 'Sic, panis valde suavis est.', 'In quinto tabulato habito.', 'Cras dies Martis est.'],
    'd-b1-06': ['Vidistine iam fabulam quam commendavi? Quid tibi visum est?', 'Me a primo capite cepit, quamquam finis me paulum destituit.', 'Viginti euronis constat.', 'Duos feles habeo.', 'Latrina in fundo est.'],
    'd-b1-07': ['Ibimusne die Saturni ambulatum in montibus?', 'Die Saturni non possum, nuptias habeo. Placetne tibi die Solis?', 'Sic, Alexander vocor.', 'Signum viarium rubrum est.', 'Hoc vinum e Chile est.'],
    'd-b1-08': ['Ignosce, quindecim minutis serius veniam.', 'Ne cures, te in taberna cafearia ad angulum exspectabo.', 'Color caeruleus mihi placet.', 'Hodie multus ventus est.', 'Dies natalis meus mense Maio est.'],
    'd-b1-09': ['Rationemne dividimus, an ego hac vice solvo?', 'Dividamus, sed proxima vice ego te invitabo.', 'Iterum pluit.', 'Chicagiae natus sum.', 'Autocinetum publicum omnibus decem minutis praeterit.'],
    'd-b1-10': ['Adiuvabisne me in re migranda die Iovis?', 'Certe, in me confide. Ab opere hora sexta exeo, satisne est?', 'Caseus in frigidario est.', 'Iaponicam linguam iam anno disco.', 'Litus longinquum est.'],
    'd-b1-11': ['Cenabimusne in nova taberna carnaria?', 'Res est quod vegetarianus sum. Nostine locum aliquem pluribus optionibus?', 'Diebus Lunae lectionem clavichordii habeo.', 'Via clausa est.', 'Pater meus medicus est.'],
    'd-b1-12': ['Potesne mihi quinquaginta eurones usque ad diem Veneris commodare?', 'Sic, nullo negotio. Statim tibi per transscriptionem argentariam mittam.', 'Fenestram corridori praefero.', 'Sol in litore lucet.', 'Avia mea octoginta annos habet.'],
    'd-b2-01': ['Puto opus remotum collaborationi nocere.', 'Non tam certus sum. Mea experientia, bonis instrumentis usus, coetus aeque vel melius efficit.', 'Relatio in chartophylacio caeruleo est.', 'Cafeam sine saccharo praefero.', 'Cras erit operariorum trahae ferratae cessatio.'],
    'd-b2-02': ['Retia socialia nos solitariores reddunt.', 'Ex parte ita est, quamquam multis quoque adiumento fuerunt ad communitates inveniendas quas prope non habebant.', 'Tessera mea secreta octo litteras habet.', 'Illa caupona hora undecima clauditur.', 'Tesseras heri emi.'],
    'd-b2-03': ['Credisne autocineta in media urbe prohiberi debere?', 'Sic, dummodo vecturam publicam meliorem reddant; alioquin tantum in vicos problema transferunt.', 'Media urbs decem minutis pedibus abest.', 'Autocinetum meum rubrum est.', 'Diebus Solis non laboro.'],
    'd-b2-04': ['Sex linguas simul discere impossibile est.', 'Difficile, sic, sed non impossibile: linguae Romanicae se invicem confirmant, et Iaponica Sinicaque multas litteras communes habent.', 'Hodie viginti gradus sunt.', 'Cum dentista mihi conventus est.', 'Sarcina die Iovis advenit.'],
    'd-b2-05': ['Pensio proximo mense viginti centesimis augebitur.', 'Intellego sumptus auctos esse, sed viginti centesimae multum sunt. Possumusne decem centesimas constituere et per duos annos renovare?', 'Latrina in fine corridoris est.', 'Prospectus hinc mihi valde placet.', 'Hodie est dies natalis meus.'],
    'd-b2-06': ['Opus duabus hebdomadibus differetur.', 'Quae est causa exacte? Diem certam mihi opus est ut inquilinum moneam.', 'Tesserae parietales colore cinereo sunt.', 'In re aedificatoria laboro.', 'Pharmacopolium ad angulum est.'],
    'd-b2-07': ['Doleo, petitio tua pecuniae reddendae reiecta est.', 'Secundum vestram rationem, triginta dies habeo ut id reddam, et duodecim tantum praeterierunt. Cum quo loqui possum ut haec sententia recognoscatur?', 'Mensam quattuor personis cupio.', 'Prope flumen habito.', 'Frater meus machinator est.'],
    'd-b2-08': ['Heri nocte musica nimis clara erat, dormire non potui.', 'Plane recte dicis, valde doleo. Ex hoc tempore post horam decimam sonum minuam.', 'Macellum hora octava aperitur.', 'Canis tuus mihi valde placet.', 'Linguam Italicam disco.'],
    'd-c2-01': ['Bella statio! Num diploma tuum in tessera fortunae nactus es?', 'Saltem ego autocinetum habeo, tu scutero veheris.', 'Valde doleo, non iterum accidet.', 'Autocinetum caeruleum est.', 'Hodie multus calor est.'],
    'd-c2-02': ['Te in quolibet certamine vincam, tu elige.', 'Bene: videamus uter diutius sine telephono suo aspiciendo perseveret.', 'Recte dicis, in omnibus melior es.', 'Certamen hora octava incipit.', 'Soror mea Hispali habitat.'],
    'd-c2-03': ['Adhucne istud telephonum functionatur? Res musei est.', 'Heus, meum est antiquarium, non vetus.', 'Sic, novum cras ipso emere debeo.', 'Museum diebus Lunae clauditur.', 'Instrumento onerando mihi opus est.'],
    'd-c2-04': ['Non male, pro te quidem.', 'Ab eo qui aquam adurit veniens, hoc pro laude accipio.', 'Gratias, gaudeo tibi placere.', 'Sal in mensa est.', 'Hora nona cenavi.'],
    'd-c2-05': ['Retia disputationem publicam prorsus destruxerunt, et punctum.', 'Partem culpae habent, sic, sed antea disputatio a paucis ephemeridibus regebatur.', 'Prorsus consentio, nihil amplius dicendum.', 'Ratio mea mille sectatores habet.', 'Ephemeris mane advenit.'],
    'd-c2-06': ['Iuvenes hodierni laborare nolunt, plane hoc est.', 'An forte nolunt laborare mercede quae ne pensionem quidem solvit?', 'Verum est, ignavi sumus.', 'Ego in officio laboro.', 'Pensio primo die mensis solvitur.'],
    'd-c2-07': ['Autocineta in tota media urbe prohibenda essent, sine exceptione.', 'Sine exceptione minime: quid de vehiculis sanitatis, de mercibus deferendis, de hominibus motu impeditis?', 'Sic, omnia cras prohibeamus.', 'Autocinetum meum rubrum est.', 'Media urbs multas tabernas habet.'],
    'd-c2-08': ['Linguas discere iam non prodest, nam machina intellegens omnia vertit.', 'Verba vertit, sic; sed iocum, tonum, et fiduciam alterius nemo tibi vertit.', 'Verum, cursum hodie ipso relinquo.', 'Applicatio gratuita est.', 'Hispanicam linguam diebus Martis disco.'],
}
