# -*- coding: utf-8 -*-
# Ròdais, the tongue of Rodos: written by tools/import_rodais.py from the Ròdais dictionary.
# The reading line is the pronunciation in IPA.
LANG = 'gr'
WORDS = {
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ("Is fheàrr eun san làimh na dhà air a' chraoibh.", 'ɪs ˈjaːr̪ˠ ˈiən sən̪ˠ ˈl̪ˠaːv nə ˈɣaː ˈɛɾʲ ə ˈxɾɯːv'),
    'c2-a-dozen': ('Dusan', 'ˈt̪usan'),
    'c2-absence-makes-the-heart-grow-fonder': ('Leis an astar, fàsaidh an gaol.', 'ˈʎeʃ ən̪ˠ ˈast̪əɾ | ˈfaːsi əŋ ˈkɯːl̪ˠ'),
    'c2-abstruse': ('Do-thuigsinn', 'ˈt̪ɔˈhɯkʲʃɪɲ'),
    'c2-accessory-to-a-crime': ('Co-chiontach', 'kʰɔˈçin̪ˠt̪əx'),
    'c2-accomplice': ('Co-chiontach', 'kʰɔˈçin̪ˠt̪əx'),
    'c2-acquittal': ('Saoradh', 'ˈsɯːɾəɣ'),
    'c2-acrid': ('Loisceach', 'ˈl̪ˠɔʃkʲəx'),
    'c2-actions-speak-louder-than-words': ('Is fheàrr aon ghnìomh na ceud facal.', 'ɪs ˈjaːr̪ˠ ˈɯːn ˈjnʲiəv nə ˈkʲʰiət̪ ˈfaʰkəl̪ˠ'),
    'c2-actuary': ('Cunntair-cunnairt', 'ˈkʰuːn̪ˠt̪ɪɾʲˈkʰun̪ˠɪɾʲtʃ'),
    'c2-acumen': ('Geur-chùiseachd', 'ˈkʲiəɾˈxuːʃəxk'),
    'c2-acute-sudden-severe': ('Dian', 'ˈtʃiən'),
    'c2-adrenaline-rush': ('Lasadh-fala', 'ˈl̪ˠasəɣˈfal̪ˠə'),
    'c2-adversary': ('Eascaraid', 'ˈɛskəɾɪtʃ'),
    'c2-advocate': ('Tagraiche', 'ˈt̪ʰakɾɪçə'),
    'c2-aesthetic': ('Maiseachd', 'ˈmaʃəxk'),
    'c2-affable': ('Suairc', 'ˈsuəɾʲkʲ'),
    'c2-affinity-between-people': ('Dàimh', 'ˈt̪aːv'),
    'c2-ailing': ('Euslainteach', 'ˈiəsl̪ˠɪɲtʃəx'),
    'c2-airborne': ('Air a ghiùlan san adhar', 'ˈɛɾʲ ə ˈjuːl̪ˠan sən̪ˠ ˈa.əɾ'),
    'c2-aisle-seat': ('Suidheachan-trannsa', 'ˈsu.əxanˈt̪ʰɾaun̪ˠsə'),
    'c2-alacrity': ('Ealamhachd', 'ˈjal̪ˠəvəxk'),
    'c2-alcove': ('Cùil', 'ˈkʰuːlʲ'),
    'c2-algorithmic-bias': ('Claonadh-inneil', 'ˈkʰl̪ˠɯːnəɣˈiɲɪlʲ'),
    'c2-allegory': ('Cosamhlachd', 'ˈkʰɔsə̃l̪ˠəxk'),
    'c2-allen-key': ('Iuchair-chrom', 'ˈjuxɪɾʲˈxɾɔum'),
    'c2-alliteration': ('Uaim', 'ˈuəm'),
    'c2-allusion': ('Iomradh', 'ˈimɾəɣ'),
    'c2-ambiguity': ('Dà-sheaghachas', 'ˈt̪aːˈhɛ.əxəs'),
    'c2-ambivalence': ('Eadar dà lionn', 'ˈɛt̪əɾ ˈt̪aː ˈʎuːn̪ˠ'),
    'c2-analogy': ('Co-choltas', 'kʰɔˈxɔl̪ˠt̪əs'),
    'c2-anecdote': ('Naidheachd', 'ˈn̪ˠa.əxk'),
    'c2-anesthesiologist': ('Draoidh-suain', 'ˈt̪ɾɯːjˈsuənʲ'),
    'c2-anesthetic': ('Ceò-suain', 'ˈkʲʰɔːˈsuənʲ'),
    'c2-anomaly': ('Neo-riaghailteachd', 'ˈɲɔˈr̪ˠiə.ɪlʲtʃəxk'),
    'c2-anthology': ('Duanaire', 'ˈt̪uənɪɾʲə'),
    'c2-anthropology': ('Seanchas-dhaoine', 'ˈʃɛnɛxəsˈɣɯːnʲə'),
    'c2-anti-hero': ('Frith-ghaisceach', 'ˈfɾʲihˈɣaʃkʲəx'),
    'c2-antibody': ('Saighdear-fala', 'ˈsɤjtʃəɾˈfal̪ˠə'),
    'c2-antiquated': ('Seann-fhasanta', 'ˈʃaun̪ˠˈasan̪ˠt̪ə'),
    'c2-antithesis': ('Frith-bheachd', 'ˈfɾʲihˈvɛxk'),
    'c2-antler': ('Cabar', 'ˈkʰapəɾ'),
    'c2-apathy': ('Coma-co-dhiù', 'ˈkʰɔməˈkʰɔˈjuː'),
    'c2-aphorism': ('Gnàth-fhacal', 'ˈkn̪ˠaːˈaʰkəl̪ˠ'),
    'c2-aplomb': ('Fèin-mhisneachd', 'ˈfeːnʲˈviʃnʲəxk'),
    'c2-apt': ('Freagarrach', 'ˈfɾʲekər̪ˠəx'),
    'c2-arbitrage': ('Buannachd-beàirn', 'ˈpuən̪ˠəxkˈpiɾʲnʲ'),
    'c2-arch': ('Bogha', 'ˈpɔ.ə'),
    'c2-archaeology': ('Fios-làraichean', 'ˈfisˈl̪ˠaːɾɪçan'),
    'c2-archetype': ('Prìomh-shamhla', 'ˈpʰɾʲiəvˈhãũl̪ˠə'),
    'c2-archivist': ('Tasclannaiche', 'ˈt̪ʰaskl̪ˠən̪ˠɪçə'),
    'c2-arduous': ('Saothrachail', 'ˈsɯːɾəxɪlʲ'),
    'c2-aria': ('Òran-aonair', 'ˈɔːɾanˈɯːnɪɾʲ'),
    'c2-arson': ('Loscadh le droch rùn', 'ˈl̪ˠɔskəɣ lʲə ˈt̪ɾɔx ˈr̪ˠuːn'),
    'c2-as-regards': ('A thaobh', 'ə ˈhɯːv'),
    'c2-asset-allocation': ('Riarachadh-stòrais', 'ˈr̪ˠiəɾəxəɣˈst̪ɔːɾɪʃ'),
    'c2-astringent': ('Ceanglach', 'ˈkʲʰauŋl̪ˠəx'),
    'c2-astrophysics': ('Fios-reultan', 'ˈfisˈr̪ˠiəl̪ˠt̪an'),
    'c2-astute': ('Geur-chùiseach', 'ˈkʲiəɾˈxuːʃəx'),
    'c2-asymptomatic': ('Gun chomharraidhean', 'kən̪ˠ ˈxɔvər̪ˠɪ.an'),
    'c2-at-the-behest-of': ('Air iarrtas', 'ˈɛɾʲ ˈiər̪ˠt̪əs'),
    'c2-atoll': ('Fàinne-mara', 'ˈfaːɲəˈmaɾə'),
    'c2-atrium': ('Cridhe-taighe', 'ˈkʰɾʲi.əˈt̪ʰa.ə'),
    'c2-audacious': ('Dàna', 'ˈt̪aːnə'),
    'c2-audacity': ('Dànadas', 'ˈt̪aːnət̪əs'),
    'c2-auditor': ('Neach-scrùdaidh', 'ˈɲɛxˈskɾuːt̪i'),
    'c2-aurora': ('Na Fir-chlis', 'nə ˈfiɾʲˈçlʲiʃ'),
    'c2-avant-garde': ('Ro-fheachd', 'ˈr̪ˠɔˈɛxk'),
    'c2-axiom': ('Fèin-fhìrinn', 'ˈfeːnʲˈiːɾʲɪɲ'),
    'c2-back-to-square-one': ('Air ais aig an toiseach', 'ˈɛɾʲ ˈaʃ ˈekʲ ən̪ˠ ˈd̪ɔʃəx'),
    'c2-backhanded-compliment': ('Moladh le càineadh', 'ˈmɔl̪ˠəɣ lʲə ˈkʰaːnʲəɣ'),
    'c2-backlog': ('Obair air dheireadh', 'ˈɔpɪɾʲ ˈɛɾʲ ˈjeɾʲəɣ'),
    'c2-baggage-carousel': ('Cuibhle-mhàileid', 'ˈkʰuvlʲəˈvaːlʲɪtʃ'),
    'c2-baggy': ('Farsaing', 'ˈfaɾsɪɲkʲ'),
    'c2-bailiff': ('Maor', 'ˈmɯːɾ'),
    'c2-bailout': ('Tèarnadh-ciste', 'ˈtʃʰiəɾnəɣˈkʲʰiʃtʃə'),
    'c2-balmy': ('Tlàth', 'ˈt̪ʰl̪ˠaː'),
    'c2-balustrade': ('Callaid-cholbh', 'ˈkʰal̪ˠɪtʃˈxɔl̪ˠɔv'),
    'c2-banal': ('Leamh', 'ˈʎɛv'),
    'c2-bandwidth': ('Leud-aibhne', 'ˈʎiət̪ˈavnʲə'),
    'c2-banister': ('Rèile-staidhre', 'ˈr̪ˠeːlʲəˈst̪ajɾʲə'),
    'c2-banter': ('Tarraing-às', 'ˈt̪ʰaːr̪ˠɪɲkʲˈaːs'),
    'c2-bark-of-a-tree': ('Rùsc', 'ˈr̪ˠuːsk'),
    'c2-barometer': ('Glainne-sìde', 'ˈkl̪ˠaɲəˈʃiːtʃə'),
    'c2-baroque': ('Ealain-sceadachaidh', 'ˈjal̪ˠɪnʲˈskʲɛt̪əxi'),
    'c2-be-that-as-it-may': ('Biodh sin mar a bhitheas e', 'ˈpiɣ ˈʃinʲ ˈmaɾ ə ˈvi.əs ˈɛ'),
    'c2-beam-structural': ('Sail', 'ˈsalʲ'),
    'c2-bear-market': ('Margadh mathain', 'ˈmaɾakəɣ ˈmahɪnʲ'),
    'c2-beats-me': ('Cò aige tha fios?', 'ˈkʰɔː ˈakʲə ˈha ˈfis'),
    'c2-beggars-can-t-be-choosers': ('Cha bhi roghainn aig an fheumach.', 'xa ˈvi ˈr̪ˠɔ.ɪɲ ˈekʲ ən̪ˠ ˈiəməx'),
    'c2-belligerent': ('Cogach', 'ˈkʰɔkəx'),
    'c2-belt-tightening': ("Teannachadh a' chrios", 'ˈtʃʰɛn̪ˠəxəɣ ə ˈxɾʲis'),
    'c2-benefactor': ('Tabhartaiche', 'ˈt̪ʰavəɾt̪ɪçə'),
    'c2-benign': ('Mìn-fhàsach', 'ˈmiːnʲˈaːsəx'),
    'c2-bespoke': ('Dèanta a rèir òrduigh', 'ˈtʃiən̪ˠt̪ə ə ˈr̪ˠeːɾʲ ˈɔːɾt̪i'),
    'c2-better-late-than-never': ('Is fheàrr anmoch na chaoidh.', 'ɪs ˈjaːr̪ˠ ˈanaməx nə ˈxɯːj'),
    'c2-better-safe-than-sorry': ('Is fheàrr a bhith cinnteach na bhith duilich.', 'ɪs ˈjaːr̪ˠ ə ˈvih ˈkʲʰiːɲtʃəx nə ˈvih ˈt̪ulʲɪç'),
    'c2-bewildered': ('Troimh-a-chèile', 'ˈt̪ʰɾɔvˈaˈçeːlʲə'),
    'c2-bin-liner': ('Poca-scudail', 'ˈpʰɔʰkəˈskut̪ɪlʲ'),
    'c2-biochemistry': ('Meascadh-beatha', 'ˈmɛskəɣˈpɛ.ə'),
    'c2-biopsy': ('Mìr-dearbhaidh', 'ˈmiːɾʲˈtʃɛɾɛvi'),
    'c2-birds-of-a-feather-flock-together': ("Bidh eòin den aon iteig a' tighinn còmhla.", 'ˈpiː ˈjɔːnʲ tʃən̪ˠ ˈɯːn ˈiʰtʃɪkʲ ə ˈtʃʰi.ɪɲ ˈkʰɔ̃ːl̪ˠə'),
    'c2-bite-the-bullet': ('Gabh ris le misneachd', 'ˈkav ˈr̪ˠiʃ lʲə ˈmiʃnʲəxk'),
    'c2-bitter-aftertaste': ('Iar-bhlas searbh', 'ˈiəɾˈvl̪ˠas ˈʃɛɾɛv'),
    'c2-black-ice': ('Deigh dhubh', 'ˈtʃej ˈɣu'),
    'c2-blacksmith': ('Gobha', 'ˈkɔvə'),
    'c2-bland-flavorless': ('Gun bhlas', 'kən̪ˠ ˈvl̪ˠas'),
    'c2-blind-spot': ('Àite dall', 'ˈaːʰtʃə ˈt̪aul̪ˠ'),
    'c2-blinds-window': ('Scàilean-uinneig', 'ˈskaːlʲanˈɯɲɪkʲ'),
    'c2-blister': ('Balg', 'ˈpal̪ˠak'),
    'c2-blood-is-thicker-than-water': ('Is tighe fuil na uisce.', 'ɪs ˈtʃʰi.ə ˈfulʲ nə ˈɯʃkʲə'),
    'c2-blush': ('Rudhadh', 'ˈr̪ˠu.əɣ'),
    'c2-boarding-pass': ('Comharra-dìridh', 'ˈkʰɔvər̪ˠəˈtʃiːɾʲi'),
    'c2-bog': ('Fèith', 'ˈfeː'),
    'c2-bombastic': ('Spaglainneach', 'ˈspakl̪ˠɪɲəx'),
    'c2-botany': ('Luibh-eòlas', 'ˈl̪ˠuˈjɔːl̪ˠəs'),
    'c2-bottleneck': ('Cumhang', 'ˈkʰuvəŋk'),
    'c2-bottom-line-is': ('Aig deireadh an latha', 'ˈekʲ ˈtʃeɾʲəɣ ən̪ˠ ˈl̪ˠa.ə'),
    'c2-boulder': ('Ulbhag', 'ˈul̪ˠuvak'),
    'c2-boundless': ('Neo-chrìochnach', 'ˈɲɔˈxɾʲiəxnəx'),
    'c2-bountiful': ('Pailt', 'ˈpʰalʲtʃ'),
    'c2-brackish': ('Leth-shaillte', 'ˈʎehˈhaiʎtʃə'),
    'c2-brain-fog': ('Ceò-inntinn', 'ˈkʲʰɔːˈiːɲtʃɪɲ'),
    'c2-brittle': ('Brisc', 'ˈpɾʲiʃkʲ'),
    'c2-bruise': ('Bruthadh', 'ˈpɾu.əɣ'),
    'c2-brusque': ('Cas', 'ˈkʰas'),
    'c2-bull-market': ('Margadh tairbh', 'ˈmaɾakəɣ ˈt̪ʰaɾʲav'),
    'c2-burden-of-proof': ('Uallach dearbhaidh', 'ˈuəl̪ˠəx ˈtʃɛɾɛvi'),
    'c2-burrow': ('Toll-talmhainn', 'ˈt̪ʰɔul̪ˠˈt̪ʰal̪ˠavɪɲ'),
    'c2-bust-sculpture': ('Ìomhaigh-uchd', 'ˈiəviˈuxk'),
    'c2-busybody': ('Gobaire', 'ˈkɔpɪɾʲə'),
    'c2-buttress': ('Taic-bhalla', 'ˈt̪ʰaʰkʲˈval̪ˠə'),
    'c2-buzzword': ('Facal-seillein', 'ˈfaʰkəl̪ˠˈʃeʎɪnʲ'),
    'c2-bystander': ('Neach-coimhid', 'ˈɲɛxˈkʰɔvɪtʃ'),
    'c2-cache': ('Stòr-làimhe', 'ˈst̪ɔːɾˈl̪ˠaːvə'),
    'c2-callous': ('Cruaidh-chridheach', 'ˈkʰɾuəjˈxɾʲi.əx'),
    'c2-camaraderie': ('Companas', 'ˈkʰɔmpanəs'),
    'c2-candor': ('Foscarrachd', 'ˈfɔskər̪ˠəxk'),
    'c2-canopy-forest': ('Mullach na coille', 'ˈmul̪ˠəx nə ˈkʰɔʎə'),
    'c2-capricious': ('Luaineach', 'ˈl̪ˠuənʲəx'),
    'c2-carbon-monoxide-alarm': ('Clag-ceò-bàis', 'ˈkʰl̪ˠakˈkʲʰɔːˈpaːʃ'),
    'c2-cardiovascular': ('Cridhe-cuisleach', 'ˈkʰɾʲi.əˈkʰɯʃlʲəx'),
    'c2-cargo-hold': ('Toll-luchda', 'ˈt̪ʰɔul̪ˠˈl̪ˠuxkə'),
    'c2-cartographer': ('Mapaiche', 'ˈmaʰpɪçə'),
    'c2-cartography': ('Dealbhadh mhapaichean', 'ˈtʃal̪ˠavəɣ ˈvaʰpɪçan'),
    'c2-catalyst': ('Aibhleag-caochlaidh', 'ˈavlʲakˈkʰɯːxl̪ˠi'),
    'c2-caveat': ('Rabhadh', 'ˈr̪ˠavəɣ'),
    'c2-cellar': ('Seilear', 'ˈʃelʲəɾ'),
    'c2-chain-of-command': ('Slabhraidh-ùghdarrais', 'ˈsl̪ˠavɾiˈuːt̪ər̪ˠɪʃ'),
    'c2-charcoal-drawing': ('Dealbh gual-fiodha', 'ˈtʃal̪ˠav ˈkuəl̪ˠˈfi.ə'),
    'c2-charlatan': ('Mealltair', 'ˈmʲaul̪ˠt̪ɪɾʲ'),
    'c2-chiropractor': ('Ceartaiche-droma', 'ˈkʲʰɛɾt̪ɪçəˈt̪ɾɔmə'),
    'c2-chisel': ('Sceilb', 'ˈskʲelʲep'),
    'c2-churlish': ('Iargalta', 'ˈiəɾkəl̪ˠt̪ə'),
    'c2-circumlocution': ('Cuairt-chainnt', 'ˈkʰuəɾʲtʃˈxaiɲtʃ'),
    'c2-cladding': ('Còmhdach', 'ˈkʰɔ̃ːt̪əx'),
    'c2-clammy': ('Tais', 'ˈt̪ʰaʃ'),
    'c2-cliche': ('Abairt chaithte', 'ˈapɪɾʲtʃ ˈxatʃə'),
    'c2-clique': ('Buidheann dùinte', 'ˈpu.ən̪ˠ ˈt̪uːɲtʃə'),
    'c2-cloister': ('Clabhstair', 'ˈkʰl̪ˠavst̪ɪɾʲ'),
    'c2-clothesline': ('Ròpa-aodaich', 'ˈr̪ˠɔːʰpəˈɯːt̪ɪç'),
    'c2-clothespin': ('Cnag-aodaich', 'ˈkʰn̪ˠakˈɯːt̪ɪç'),
    'c2-cloudburst': ('Dìle', 'ˈtʃiːlʲə'),
    'c2-cloying': ('Ro-mhilis', 'ˈr̪ˠɔˈvilʲɪʃ'),
    'c2-clutch-car': ('Greim-cuibhle', 'ˈkɾʲeimˈkʰuvlʲə'),
    'c2-coarse': ('Garbh', 'ˈkaɾav'),
    'c2-coaster': ('Leac-copain', 'ˈʎeʰkˈkʰɔʰpɪnʲ'),
    'c2-cockpit': ('Ceann-eòin', 'ˈkʲʰaun̪ˠˈjɔːnʲ'),
    'c2-cocoon': ('Cochall', 'ˈkʰɔxəl̪ˠ'),
    'c2-cogent': ('Làidir', 'ˈl̪ˠaːtʃɪɾʲ'),
    'c2-cohesive': ('Co-leanailteach', 'kʰɔˈʎɛnɪlʲtʃəx'),
    'c2-colander': ('Sìolachan', 'ˈʃiəl̪ˠəxan'),
    'c2-cold-shoulder': ('Sùil fhuar', 'ˈsuːlʲ ˈuəɾ'),
    'c2-cold-snap': ('Greis fhuar', 'ˈkɾʲeʃ ˈuəɾ'),
    'c2-column': ('Colbh', 'ˈkʰɔl̪ˠɔv'),
    'c2-commute-noun': ('Siubhal-obrach', 'ˈʃuvəl̪ˠˈɔpɾəx'),
    'c2-complacent': ('Fèin-riaraichte', 'ˈfeːnʲˈr̪ˠiəɾɪçtʃə'),
    'c2-complexion': ('Tuar', 'ˈt̪ʰuəɾ'),
    'c2-concise': ('Cuimir', 'ˈkʰumɪɾʲ'),
    'c2-congenital': ('Bho bhreith', 'ˈvɔ ˈvɾʲeh'),
    'c2-conjecture': ('Tuaiream', 'ˈt̪ʰuəɾʲəm'),
    'c2-connoisseur': ('Eòlaiche', 'ˈjɔːl̪ˠɪçə'),
    'c2-connotation': ('Co-chiall', 'kʰɔˈçiəl̪ˠ'),
    'c2-consensus': ('Co-aontachd', 'kʰɔˈɯːn̪ˠt̪əxk'),
    'c2-consignment': ('Cuibhreann bathair', 'ˈkʰuvɾʲən̪ˠ ˈpahɪɾʲ'),
    'c2-contempt-of-court': ("Tàir air a' chùirt", 'ˈt̪ʰaːɾʲ ˈɛɾʲ ə ˈxuːɾʲtʃ'),
    'c2-contentious': ('Connspaideach', 'ˈkʰɔun̪ˠspɪtʃəx'),
    'c2-contraindication': ('Comharra-bacaidh', 'ˈkʰɔvər̪ˠəˈpaʰki'),
    'c2-conundrum': ('Tòimhseachan', 'ˈt̪ʰɔ̃ːʃəxan'),
    'c2-convalescence': ('Ath-shlànachadh', 'ˈahˈhl̪ˠaːnəxəɣ'),
    'c2-conviction-guilty-verdict': ('Dìteadh', 'ˈtʃiːʰtʃəɣ'),
    'c2-copious': ('Lìonmhor', 'ˈʎiənvəɾ'),
    'c2-copyleft': ('Còir-fialachd', 'ˈkʰɔːɾʲˈfiəl̪ˠəxk'),
    'c2-cornice': ('Bàrr-bhalla', 'ˈpaːr̪ˠˈval̪ˠə'),
    'c2-corollary': ('Co-thoradh', 'kʰɔˈhɔɾəɣ'),
    'c2-coroner': ('Crùnair', 'ˈkʰɾuːnɪɾʲ'),
    'c2-couplet': ('Dà-shreathach', 'ˈt̪aːˈhɾʲɛ.əx'),
    'c2-court-clerk': ('Clèireach cùirte', 'ˈkʲʰlʲeːɾʲəx ˈkʰuːɾʲtʃə'),
    'c2-courtyard': ('Lios', 'ˈʎis'),
    'c2-cove': ('Camas', 'ˈkʰaməs'),
    'c2-cramp': ('Crampa', 'ˈkʰɾampə'),
    'c2-crawl-space': ('Fo-làr', 'ˈfɔˈl̪ˠaːɾ'),
    'c2-creamy': ('Uachdarach', 'ˈuəxkəɾəx'),
    'c2-creased': ('Preasach', 'ˈpʰɾʲɛsəx'),
    'c2-criminology': ('Fios-eucorach', 'ˈfisˈiəʰkəɾəx'),
    'c2-crisp-air': ('Fionnar', 'ˈfin̪ˠəɾ'),
    'c2-cross-examination': ('Ceasnachadh-tarsainn', 'ˈkʲʰɛsnəxəɣˈt̪ʰaɾsɪɲ'),
    'c2-crow-s-feet': ('Casan-feannaig', 'ˈkʰasanˈfɛn̪ˠɪkʲ'),
    'c2-crunchy': ('Cnagach', 'ˈkʰn̪ˠakəx'),
    'c2-cryptic': ('Dìomhair', 'ˈtʃiəvɪɾʲ'),
    'c2-cuff': ('Bann-dùirn', 'ˈpaun̪ˠˈt̪uːɾʲnʲ'),
    'c2-cufflinks': ('Putanan-dùirn', 'ˈpʰuʰt̪ananˈt̪uːɾʲnʲ'),
    'c2-culprit': ('Ciontach', 'ˈkʲʰin̪ˠt̪əx'),
    'c2-cumbersome': ('Liobasta', 'ˈʎipəst̪ə'),
    'c2-cunning': ('Carach', 'ˈkʰaɾəx'),
    'c2-curator': ('Glèidheadair', 'ˈkʲlʲeː.ət̪ɪɾʲ'),
    'c2-curiosity-killed-the-cat': ('Mharbh feòrachas an cat.', 'ˈvaɾav ˈfʲɔːɾəxəs əŋ ˈɡaʰt̪'),
    'c2-custody-detention': ('Grèim', 'ˈkɾʲeːm'),
    'c2-customs-clearance': ('Cead cusbainn', 'ˈkʲʰɛt̪ ˈkʰuspɪɲ'),
    'c2-cut-to-the-chase': ('Thig chun na puinge!', 'ˈhikʲ ˈxun nə ˈpʰuɲə'),
    'c2-cutting-board': ('Bòrd-gearraidh', 'ˈpɔːɾt̪ˈkʲaːr̪ˠi'),
    'c2-dank': ('Tais', 'ˈt̪ʰaʃ'),
    'c2-dapper': ('Snasail', 'ˈsnasɪlʲ'),
    'c2-dart-sewing': ('Fillteag', 'ˈfiːʎtʃak'),
    'c2-data-breach': ('Aoidion-fiosa', 'ˈɯːtʃənˈfisə'),
    'c2-daybreak': ('Bristeadh na fàire', 'ˈpɾʲiʃtʃəɣ nə ˈfaːɾʲə'),
    'c2-daydream': ('Aisling-latha', 'ˈaʃlʲɪɲkʲˈl̪ˠa.ə'),
    'c2-dearth': ('Gainne', 'ˈkaɲə'),
    'c2-debacle': ('Tubaist', 'ˈt̪ʰupɪʃtʃ'),
    'c2-decimal-point': ('Puing dheicheach', 'ˈpʰuːiɲkʲ ˈjeçəx'),
    'c2-deduction': ('Co-dhùnadh', 'kʰɔˈɣuːnəɣ'),
    'c2-defendant': ('Neach-dìona', 'ˈɲɛxˈtʃiənə'),
    'c2-deference': ('Ùmhlachd', 'ˈũːl̪ˠəxk'),
    'c2-deflation': ('Seargadh-luach', 'ˈʃɛɾɛkəɣˈl̪ˠuəx'),
    'c2-deft': ('Deas-làmhach', 'ˈtʃɛsˈl̪ˠaːvəx'),
    'c2-defunct': ('À bith', 'ˈaː ˈpih'),
    'c2-deja-vu': ('Ath-shealladh', 'ˈahˈhɛl̪ˠəɣ'),
    'c2-deluge': ('Dìle', 'ˈtʃiːlʲə'),
    'c2-demagogue': ('Buaireadair-sluaigh', 'ˈpuəɾʲət̪ɪɾʲˈsl̪ˠuəj'),
    'c2-demography': ('Tomhas-sluaigh', 'ˈt̪ʰɔvəsˈsl̪ˠuəj'),
    'c2-denominator': ('Roinneadair', 'ˈr̪ˠɔɲət̪ɪɾʲ'),
    'c2-denouement': ('Fuascladh', 'ˈfuəskl̪ˠəɣ'),
    'c2-deplorable': ('Maslach', 'ˈmasl̪ˠəx'),
    'c2-deposition': ('Fianais mhionnaichte', 'ˈfiənɪʃ ˈvin̪ˠɪçtʃə'),
    'c2-deprecated': ('Air a dhol à cleachdadh', 'ˈɛɾʲ ə ˈɣɔl̪ˠ ˈaː ˈkʲʰlʲɛxkəɣ'),
    'c2-derelict': ('Trèigte', 'ˈt̪ʰɾʲeːkʲtʃə'),
    'c2-derogatory': ('Tàireil', 'ˈt̪ʰaːɾʲɪlʲ'),
    'c2-desolate': ('Fàsail', 'ˈfaːsɪlʲ'),
    'c2-dew': ('Driùchd', 'ˈt̪ɾʲuːxk'),
    'c2-dichotomy': ('Dà-scaradh', 'ˈt̪aːˈskaɾəɣ'),
    'c2-didactic': ('Teagaisceach', 'ˈtʃʰekɪʃkʲəx'),
    'c2-dietitian': ('Leigh-bìdh', 'ˈʎejˈpiː'),
    'c2-diffident': ('Diùid', 'ˈtʃuːtʃ'),
    'c2-digression': ('Claonadh', 'ˈkʰl̪ˠɯːnəɣ'),
    'c2-dilettante': ('Leth-eòlaiche', 'ˈʎehˈjɔːl̪ˠɪçə'),
    'c2-dimmer-switch': ('Maothaiche-solais', 'ˈmɯːhɪçəˈsɔl̪ˠɪʃ'),
    'c2-dimple': ('Tibhre', 'ˈtʃʰivɾʲə'),
    'c2-diplomat': ('Figheadair-sìthe', 'ˈfi.ət̪ɪɾʲˈʃiː.ə'),
    'c2-dire': ('Uabhasach', 'ˈuəvəsəx'),
    'c2-discretion': ('Faiceallachd', 'ˈfaʰkʲəl̪ˠəxk'),
    'c2-disdain': ('Dìmeas', 'ˈtʃiːməs'),
    'c2-dish-rack': ('Raca-shoithichean', 'ˈr̪ˠaʰkəˈhɔhɪçan'),
    'c2-disheveled': ('Mì-sciobalta', 'ˈmiːˈskʲipəl̪ˠt̪ə'),
    'c2-ditto': ('Mar an ceudna', 'ˈmaɾ əŋ ˈɡʲiət̪nə'),
    'c2-diversion-route': ('Claon-rathad', 'ˈkʰl̪ˠɯːnˈr̪ˠa.ət̪'),
    'c2-dizziness': ('Tuaineal', 'ˈt̪ʰuənʲəl̪ˠ'),
    'c2-docile': ('Soitheamh', 'ˈsɔ.əv'),
    'c2-doctrine': ('Teagasc', 'ˈtʃʰekəsk'),
    'c2-dogma': ('Creud', 'ˈkʰɾʲiət̪'),
    'c2-dome': ('Cruinneachan', 'ˈkʰɾɯɲəxan'),
    'c2-don-t-count-your-chickens-before-they-hatch': ('Na cunnt na h-iseanan mus tig iad às an ugh.', 'nə ˈkʰuːn̪ˠt̪ nə ˈhiʃanan məs ˈtʃʰikʲ ˈiət̪ ˈaːs ən̪ˠ ˈu'),
    'c2-don-t-get-me-started': ('Na toir orm tòiseachadh.', 'nə ˈt̪ʰɔɾʲ ˈɔɾɔm ˈt̪ʰɔːʃəxəɣ'),
    'c2-don-t-judge-a-book-by-its-cover': ('Na toir breith air leabhar air a chòmhdach.', 'nə ˈt̪ʰɔɾʲ ˈpɾʲeh ˈɛɾʲ ˈʎɔ.əɾ ˈɛɾʲ ə ˈxɔ̃ːt̪əx'),
    'c2-donor': ('Neach-tabhartais', 'ˈɲɛxˈt̪ʰavəɾt̪ɪʃ'),
    'c2-doorknob': ('Làmh-dorais', 'ˈl̪ˠaːvˈt̪ɔɾɪʃ'),
    'c2-doormat': ('Brat-dorais', 'ˈpɾaʰt̪ˈt̪ɔɾɪʃ'),
    'c2-dormant': ('Na thàmh', 'nə ˈhaːv'),
    'c2-dosage': ('Tomhas-cungaidh', 'ˈt̪ʰɔvəsˈkʰuŋi'),
    'c2-double-entendre': ('Facal dà-sheaghach', 'ˈfaʰkəl̪ˠ ˈt̪aːˈhɛ.əx'),
    'c2-downturn': ('Crìonadh', 'ˈkʰɾʲiənəɣ'),
    'c2-drawbridge': ('Drochaid-thogalach', 'ˈt̪ɾɔxɪtʃˈhɔkəl̪ˠəx'),
    'c2-drawer-organizer': ('Roinneadair-ciste', 'ˈr̪ˠɔɲət̪ɪɾʲˈkʲʰiʃtʃə'),
    'c2-driftwood': ('Fiodh-cladaich', 'ˈfiɣˈkʰl̪ˠat̪ɪç'),
    'c2-drowsy': ('Cadalach', 'ˈkʰat̪əl̪ˠəx'),
    'c2-dubious': ('Teagmhach', 'ˈtʃʰekvəx'),
    'c2-dustpan': ('Sluasaid-dhuslaich', 'ˈsl̪ˠuəsɪtʃˈɣusl̪ˠɪç'),
    'c2-dwindling': ("A' crìonadh", 'ə ˈkʰɾʲiənəɣ'),
    'c2-earthy': ('Ùireach', 'ˈuːɾʲəx'),
    'c2-easel': ('Sorchan', 'ˈsɔɾɔxan'),
    'c2-eaves': ('Anainn', 'ˈanɪɲ'),
    'c2-econometrics': ('Tomhas-ionmhais', 'ˈt̪ʰɔvəsˈinivɪʃ'),
    'c2-edge-case': ('Cùis-iomaill', 'ˈkʰuːʃˈimɪʎ'),
    'c2-egregious': ('Uabhasach', 'ˈuəvəsəx'),
    'c2-electrolyte': ('Salann-fala', 'ˈsal̪ˠən̪ˠˈfal̪ˠə'),
    'c2-elevation-drawing': ('Àrd-dhealbh', 'ˈaːɾt̪ˈjal̪ˠav'),
    'c2-eloquence': ('Deas-bhriathrachd', 'ˈtʃɛsˈvɾʲiəɾəxk'),
    'c2-embargo': ('Bacadh', 'ˈpaʰkəɣ'),
    'c2-embezzlement': ('Mèirle-earbsa', 'ˈmeːɾʲlʲəˈɛɾɛpsə'),
    'c2-emphatic': ('Deimhinnte', 'ˈtʃevɪɲtʃə'),
    'c2-encore': ('Òran a bharrachd', 'ˈɔːɾan ə ˈvaːr̪ˠəxk'),
    'c2-entomologist': ('Saoi-bhiastag', 'ˈsɯiˈviəst̪ak'),
    'c2-entourage': ('Luchd-coimhideachd', 'ˈl̪ˠuxkˈkʰɔvɪtʃəxk'),
    'c2-envoy': ('Toscaire', 'ˈt̪ʰɔskɪɾʲə'),
    'c2-ephemeral': ('Diombuan', 'ˈtʃimpuən'),
    'c2-epidemiology': ('Lorg-plàighe', 'ˈl̪ˠɔɾɔkˈpʰl̪ˠaː.ə'),
    'c2-epiphany': ('Foillseachadh', 'ˈfɔiʎʃəxəɣ'),
    'c2-epistemology': ('Freumh-fiosa', 'ˈfɾʲiəvˈfisə'),
    'c2-epitome': ('Fìor-eisimpleir', 'ˈfiəɾˈeʃɪmplʲɪɾʲ'),
    'c2-equanimity': ('Ciùineas', 'ˈkʲʰuːnʲəs'),
    'c2-equinox': ('Co-fhad-thràth', 'kʰɔˈat̪ˈhɾaː'),
    'c2-equity-ownership': ('Cuid-seilbhe', 'ˈkʰutʃˈʃelʲevə'),
    'c2-erosion': ('Creimeadh', 'ˈkʰɾʲeməɣ'),
    'c2-erudite': ('Foghlaimte', 'ˈfɔl̪ˠɪmtʃə'),
    'c2-escarpment': ('Bearradh', 'ˈpʲaːr̪ˠəɣ'),
    'c2-estuary': ('Inbhir', 'ˈinʲivɪɾʲ'),
    'c2-etching': ('Gràbhaladh searbhaig', 'ˈkɾaːvəl̪ˠəɣ ˈʃɛɾɛvɪkʲ'),
    'c2-ethnography': ('Seanchas-chinnidh', 'ˈʃɛnɛxəsˈçiɲi'),
    'c2-ethos': ('Beus', 'ˈpiəs'),
    'c2-etiquette': ('Modhalachd', 'ˈmɔ.əl̪ˠəxk'),
    'c2-euphemism': ('Maoth-fhacal', 'ˈmɯːˈaʰkəl̪ˠ'),
    'c2-euphemistic': ('Maoth-fhaclach', 'ˈmɯːˈaʰkl̪ˠəx'),
    'c2-every-cloud-has-a-silver-lining': ('Chan eil olc ann nach dèan math do chuideigin.', 'xan ˈelʲ ˈɔl̪ˠk ˈaun̪ˠ nəx ˈtʃiən ˈma t̪ə ˈxutʃɪkʲɪnʲ'),
    'c2-every-dog-has-its-day': ("Thig latha a' choin duibh.", 'ˈhikʲ ˈl̪ˠa.ə ə ˈxɔnʲ ˈt̪u'),
    'c2-exemplary': ('Eisimpleireach', 'ˈeʃɪmplʲɪɾʲəx'),
    'c2-exhilarated': ('Air mhire', 'ˈɛɾʲ ˈviɾʲə'),
    'c2-exodus': ('Às-imrich', 'ˈaːsˈimɾʲɪç'),
    'c2-exponent': ('Cumhachd-àireimh', 'ˈkʰuvəxkˈaːɾʲɪv'),
    'c2-exponential-growth': ('Fàs-lasrach', 'ˈfaːsˈl̪ˠasɾəx'),
    'c2-extension-cord': ('Sreang-sìnidh', 'ˈst̪ɾʲauŋkˈʃiːnʲi'),
    'c2-extortion': ('Foireigneadh', 'ˈfɔɾʲɪkʲnʲəɣ'),
    'c2-facade': ('Aghaidh', 'ˈa.i'),
    'c2-facade-building-front': ('Aghaidh togalaich', 'ˈa.i ˈt̪ʰɔkəl̪ˠɪç'),
    'c2-facetious': ('Fealla-dhàach', 'ˈfɛl̪ˠəˈɣax'),
    'c2-fallacious': ('Mearachdach', 'ˈmɛɾəxkəx'),
    'c2-fallacy': ('Mearachd', 'ˈmɛɾəxk'),
    'c2-fastidious': ('Àilleasach', 'ˈaːʎəsəx'),
    'c2-fatigue': ('Scìths', 'ˈskʲiːʃ'),
    'c2-faultless': ('Gun lochd', 'kən̪ˠ ˈl̪ˠɔxk'),
    'c2-faux-pas': ('Tuisleadh', 'ˈt̪ʰɯʃlʲəɣ'),
    'c2-feeble': ('Anfhann', 'ˈanən̪ˠ'),
    'c2-felony': ('Eucoir throm', 'ˈiəʰkɪɾʲ ˈhɾɔum'),
    'c2-fern': ('Raineach', 'ˈr̪ˠanʲəx'),
    'c2-fidgety': ('Luascanach', 'ˈl̪ˠuəskanəx'),
    'c2-first-aid-kit': ('Pascan ciad-chobhair', 'ˈpʰaskan ˈkʲʰiət̪ˈxɔvɪɾʲ'),
    'c2-fiscal-policy': ('Rian-cìse', 'ˈr̪ˠiənˈkʲʰiːʃə'),
    'c2-flare-up': ('Lasadh', 'ˈl̪ˠasəɣ'),
    'c2-flattering-clothes': ('Freagarrach', 'ˈfɾʲekər̪ˠəx'),
    'c2-flattery': ('Miodal', 'ˈmit̪əl̪ˠ'),
    'c2-flinch-noun': ('Clisc', 'ˈkʲʰlʲiʃkʲ'),
    'c2-flippant': ('Guanach', 'ˈkuənəx'),
    'c2-florid': ('Ro-sceadaichte', 'ˈr̪ˠɔˈskʲɛt̪ɪçtʃə'),
    'c2-flurry-snow': ('Fras-shneachda', 'ˈfɾasˈhnʲɛxkə'),
    'c2-foil-character': ('Scàthan-coimeis', 'ˈskaːhanˈkʰɔmɪʃ'),
    'c2-foothills': ('Bun-bheanntan', 'ˈpunˈvʲaun̪ˠt̪an'),
    'c2-for-the-sake-of-argument': ('Airson na h-argamaid', 'ˈaɾsən nə ˈhaɾakəmɪtʃ'),
    'c2-for-what-it-s-worth': ('Airson na fiach e', 'ˈaɾsən nə ˈfiəx ˈɛ'),
    'c2-forbearance': ('Foighidinn', 'ˈfɔ.ɪtʃɪɲ'),
    'c2-forecast-verb': ('Ro-innse', 'ˈr̪ˠɔˈiːɲʃə'),
    'c2-forensic-scientist': ('Lorgaire-fola', 'ˈl̪ˠɔɾɔkɪɾʲəˈfɔl̪ˠə'),
    'c2-forgery': ('Fallsachadh', 'ˈfaul̪ˠsəxəɣ'),
    'c2-forlorn': ('Aonaranach', 'ˈɯːnəɾanəx'),
    'c2-formidable': ('Eagalach', 'ˈekəl̪ˠəx'),
    'c2-forthwith': ('Gun dàil', 'kən̪ˠ ˈt̪aːlʲ'),
    'c2-fortitude': ('Cruadal', 'ˈkʰɾuət̪əl̪ˠ'),
    'c2-fragrant': ('Cùbhraidh', 'ˈkʰuːvɾi'),
    'c2-frame-narrative': ('Cochall-sceòil', 'ˈkʰɔxəl̪ˠˈskʲɔːlʲ'),
    'c2-frayed': ('Fuascailte aig na h-oirean', 'ˈfuəskɪlʲtʃə ˈekʲ nə ˈhɔɾʲan'),
    'c2-freckles': ('Breac-sheunain', 'ˈpɾʲeʰkˈhiənɪnʲ'),
    'c2-freeloader': ('Scimilear', 'ˈskʲimɪlʲəɾ'),
    'c2-freight': ('Luchd', 'ˈl̪ˠuxk'),
    'c2-french-press': ('Poit-bhrùthaidh', 'ˈpʰɔʰtʃˈvɾuːhi'),
    'c2-fresco': ('Dealbh-balla', 'ˈtʃal̪ˠavˈpal̪ˠə'),
    'c2-fuse-box': ('Ciste-dealain', 'ˈkʲʰiʃtʃəˈtʃal̪ˠɪnʲ'),
    'c2-futile': ('Dìomhain', 'ˈtʃiəvɪnʲ'),
    'c2-gable': ('Stuadh', 'ˈst̪uəɣ'),
    'c2-gale': ('Gèile', 'ˈkʲeːlʲə'),
    'c2-garish': ('Glaodhach', 'ˈkl̪ˠɯː.əx'),
    'c2-garrulous': ('Cabach', 'ˈkʰapəx'),
    'c2-gaunt': ('Seang', 'ˈʃauŋk'),
    'c2-generic-drug': ('Cungaidh-gun-ainm', 'ˈkʰuŋiˈkunˈanʲam'),
    'c2-genetics': ('Fios-sìl', 'ˈfisˈʃiːlʲ'),
    'c2-geologist': ('Saoi-chreige', 'ˈsɯiˈxɾʲekʲə'),
    'c2-geopolitics': ('Cluich-rìoghachdan', 'ˈkʰl̪ˠuçˈr̪ˠiə.əxkan'),
    'c2-germination': ('Dùscadh-sìl', 'ˈt̪uːskəɣˈʃiːlʲ'),
    'c2-girder': ('Sail-iarainn', 'ˈsalʲˈiəɾɪɲ'),
    'c2-gist': ('Brìgh', 'ˈpɾʲiː'),
    'c2-give-me-a-break': ('Leig leam!', 'ˈʎekʲ ˈʎaum'),
    'c2-glazier': ('Glainneadair', 'ˈkl̪ˠaɲət̪ɪɾʲ'),
    'c2-glib': ('Sleamhainn', 'ˈʃlʲɛvɪɲ'),
    'c2-go-figure': ('Cò shaoileadh?', 'ˈkʰɔː ˈhɯːlʲəɣ'),
    'c2-gooey': ('Glaodhach', 'ˈkl̪ˠɯː.əx'),
    'c2-gorge': ('Mòr-ghil', 'ˈmoːɾˈjilʲ'),
    'c2-gossip': ('Clabaireachd', 'ˈkʰl̪ˠapɪɾʲəxk'),
    'c2-grainy': ('Gràineach', 'ˈkɾaːnʲəx'),
    'c2-grater': ('Scrìobadair', 'ˈskɾʲiəpət̪ɪɾʲ'),
    'c2-grating-sound': ('Scrìobach', 'ˈskɾʲiəpəx'),
    'c2-gratuitous': ('Gun adhbhar', 'kən̪ˠ ˈavəɾ'),
    'c2-gravelly-voice': ('Tùchanach', 'ˈt̪ʰuːxanəx'),
    'c2-gregarious': ('Cuideachdail', 'ˈkʰutʃəxkɪlʲ'),
    'c2-gridlock': ('Glasadh-rathaid', 'ˈkl̪ˠasəɣˈr̪ˠahɪtʃ'),
    'c2-grit': ('Smior', 'ˈsmiɾ'),
    'c2-groupthink': ('Ciall-treuda', 'ˈkʲʰiəl̪ˠˈt̪ʰɾʲiət̪ə'),
    'c2-grove': ('Doire', 'ˈt̪ɔɾʲə'),
    'c2-grudge': ('Gamhlas', 'ˈkãũl̪ˠəs'),
    'c2-gusset': ('Guiseid', 'ˈkɯʃɪtʃ'),
    'c2-gust': ('Osag', 'ˈɔsak'),
    'c2-gut-feeling': ('Faireachdainn-mionaich', 'ˈfaɾʲəxkɪɲˈminɪç'),
    'c2-gutter-roof': ('Guitear', 'ˈkuʰtʃəɾ'),
    'c2-haggard': ('Seargte', 'ˈʃɛɾʲɛkʲtʃə'),
    'c2-handbrake': ('Bacadh-làimhe', 'ˈpaʰkəɣˈl̪ˠaːvə'),
    'c2-hang-in-there': ('Cùm ort!', 'ˈkʰuːm ˈɔɾt̪'),
    'c2-hard-shoulder': ('Guala-rathaid', 'ˈkuəl̪ˠəˈr̪ˠahɪtʃ'),
    'c2-hashing': ('Pronnadh-rùin', 'ˈpʰɾɔn̪ˠəɣˈr̪ˠuːnʲ'),
    'c2-haste-makes-waste': ('Nì cabhag maill.', 'ˈɲiː ˈkʰavak ˈmaiʎ'),
    'c2-haughty': ('Àrdanach', 'ˈaːɾt̪anəx'),
    'c2-hazard-lights': ('Solais-cunnairt', 'ˈsɔl̪ˠɪʃˈkʰun̪ˠɪɾʲtʃ'),
    'c2-haze': ('Ceathach', 'ˈkʲʰɛ.əx'),
    'c2-hearsay': ('Fianais-chluaise', 'ˈfiənɪʃˈxl̪ˠuəʃə'),
    'c2-hedge-finance': ('Sciath-ionmhais', 'ˈskʲiəˈinivɪʃ'),
    'c2-hereditary': ('Oighreachail', 'ˈɤiɾʲəxɪlʲ'),
    'c2-hereinafter': ('Bho seo a-mach', 'ˈvɔ ˈʃɔ əˈmax'),
    'c2-heretofore': ('Roimhe seo', 'ˈr̪ˠɔvə ˈʃɔ'),
    'c2-hermeneutics': ('Ealain-mhìneachaidh', 'ˈjal̪ˠɪnʲˈviːnʲəxi'),
    'c2-hibernation': ('Cadal-geamhraidh', 'ˈkʰat̪əl̪ˠˈkʲɛ̃ũɾi'),
    'c2-hiccup': ('Aileag', 'ˈalʲak'),
    'c2-hindsight': ('Iar-shealladh', 'ˈiəɾˈhɛl̪ˠəɣ'),
    'c2-hinge': ('Lùdag', 'ˈl̪ˠuːt̪ak'),
    'c2-hitherto': ('Gu ruige seo', 'kə ˈr̪ˠɯkʲə ˈʃɔ'),
    'c2-hive': ('Sceap', 'ˈskʲɛʰp'),
    'c2-hold-your-horses': ('Air do shocair!', 'ˈɛɾʲ t̪ə ˈhɔʰkɪɾʲ'),
    'c2-honesty-is-the-best-policy': ('Is e an onair an dòigh as fheàrr.', 'ɪs ˈɛ ən̪ˠ ˈɔnɪɾʲ ən̪ˠ ˈtoːj ˈas ˈjaːr̪ˠ'),
    'c2-hot-flush': ('Teas-lasadh', 'ˈtʃʰɛsˈl̪ˠasəɣ'),
    'c2-hotfix': ('Brèid-èiginn', 'ˈpɾʲeːtʃˈeːkʲɪɲ'),
    'c2-hubris': ('Uabhar', 'ˈuəvəɾ'),
    'c2-humidity': ('Taiseachd', 'ˈt̪ʰaʃəxk'),
    'c2-hunch': ('Amharas', 'ˈavəɾəs'),
    'c2-hushed': ('Mùchte', 'ˈmuːçtʃə'),
    'c2-hyperbole': ('Àibheiseachadh', 'ˈaːvɪʃəxəɣ'),
    'c2-hyperbolic': ('Àibheiseach', 'ˈaːvɪʃəx'),
    'c2-hypocrite': ('Cealgair', 'ˈkʲʰal̪ˠakɪɾʲ'),
    'c2-i-couldn-t-care-less': ('Tha mi coma co-dhiù.', 'ˈha ˈmi ˈkʰɔmə kʰɔˈjuː'),
    'c2-i-ll-say': ('Seadh gu dearbh!', 'ˈʃɛɣ kə ˈtʃɛɾɛv'),
    'c2-i-ll-take-a-rain-check': ('Uair eile, ma-thà.', 'ˈuəɾʲ ˈelʲə | məˈhaː'),
    'c2-i-m-all-ears': ('Tha mi ag èisteachd gu dlùth.', 'ˈha ˈmi ək ˈeːʃtʃəxk kə ˈt̪l̪ˠuː'),
    'c2-i-m-not-gonna-lie': ('Cha dèan mi breug', 'xa ˈtʃiən ˈmi ˈpɾʲiək'),
    'c2-idiosyncrasy': ('Annasachd', 'ˈan̪ˠəsəxk'),
    'c2-illicit': ('Mì-laghail', 'ˈmiːˈl̪ˠa.ɪlʲ'),
    'c2-immaculate': ('Gun smal', 'kən̪ˠ ˈsmal̪ˠ'),
    'c2-imminent': ('Faisc air làimh', 'ˈfaʃkʲ ˈɛɾʲ ˈl̪ˠaːv'),
    'c2-immunity': ('Dìonachd', 'ˈtʃiənəxk'),
    'c2-immunology': ('Fios-dìon-fala', 'ˈfisˈtʃiənˈfal̪ˠə'),
    'c2-impartial': ('Neo-phàirteach', 'ˈɲɔˈfaːɾʲtʃəx'),
    'c2-impasse': ('Bacadh', 'ˈpaʰkəɣ'),
    'c2-impetuous': ('Bras', 'ˈpɾas'),
    'c2-impetus': ('Brosnachadh', 'ˈpɾɔsnəxəɣ'),
    'c2-impressionism': ('Dealbh-plathaidh', 'ˈtʃal̪ˠavˈpʰl̪ˠahi'),
    'c2-in-accordance-with': ('Ann an co-rèir ri', 'ˈaun̪ˠ əŋ ɡɔˈr̪ˠeːɾʲ ɾʲə'),
    'c2-in-conjunction-with': ('An co-bhonn ri', 'əŋ ɡɔˈvɔun̪ˠ ɾʲə'),
    'c2-in-one-ear-and-out-the-other': ("A-steach air an dàrna cluais 's a-mach air a' chluais eile", 'əˈʃtʃɛx ˈɛɾʲ ən̪ˠ ˈt̪aːɾnə ˈkʰl̪ˠuəʃ s əˈmax ˈɛɾʲ ə ˈxl̪ˠuəʃ ˈelʲə'),
    'c2-in-the-wake-of': ('An lorg', 'ən̪ˠ ˈl̪ˠɔɾɔk'),
    'c2-inasmuch-as': ("A chionn 's gu", 'ə ˈçuːn̪ˠ s kə'),
    'c2-incessant': ('Gun scur', 'kən̪ˠ ˈskuɾ'),
    'c2-incision': ('Gearradh', 'ˈkʲaːr̪ˠəɣ'),
    'c2-incisive': ('Geur', 'ˈkʲiəɾ'),
    'c2-incongruous': ('Mì-fhreagarrach', 'ˈmiːˈɾʲekər̪ˠəx'),
    'c2-indictment': ('Casaid fhoirmeil', 'ˈkʰasɪtʃ ˈɔɾʲɔmɪlʲ'),
    'c2-indolent': ('Leisc', 'ˈʎeʃkʲ'),
    'c2-indomitable': ('Do-cheannsachaidh', 'ˈt̪ɔˈçaun̪ˠsəxi'),
    'c2-ineffable': ('Do-labhairt', 'ˈt̪ɔˈl̪ˠavɪɾʲtʃ'),
    'c2-inert': ('Marbhanta', 'ˈmaɾavan̪ˠt̪ə'),
    'c2-infinitesimal': ('Beag bìodach', 'ˈpek ˈpiət̪əx'),
    'c2-inflammation': ('Atadh', 'ˈaʰt̪əɣ'),
    'c2-informant': ('Neach-fiosrachaidh', 'ˈɲɛxˈfisɾəxi'),
    'c2-informed-consent': ('Aonta-fiosa', 'ˈɯːn̪ˠt̪əˈfisə'),
    'c2-ingenuity': ('Innleachdas', 'ˈiːɲlʲəxkəs'),
    'c2-injunction': ('Òrdugh-toirmisc', 'ˈɔːɾt̪əɣˈt̪ʰɔɾʲɔmɪʃkʲ'),
    'c2-innocuous': ('Neo-lochdach', 'ˈɲɔˈl̪ˠɔxkəx'),
    'c2-innuendo': ('Sanas', 'ˈsanəs'),
    'c2-inpatient': ('Euslainteach san ospadal', 'ˈiəsl̪ˠɪɲtʃəx sən̪ˠ ˈɔspət̪əl̪ˠ'),
    'c2-inseam': ('Fad na coise a-staigh', 'ˈfat̪ nə ˈkʰɔʃə əˈst̪ɤj'),
    'c2-insidious': ('Fealltach', 'ˈfʲaul̪ˠt̪əx'),
    'c2-insolvency': ('Neo-chomas pàighidh', 'ˈɲɔˈxɔməs ˈpʰaː.i'),
    'c2-insurgent': ('Ceannairceach', 'ˈkʲʰɛn̪ˠɪɾʲkʲəx'),
    'c2-integer': ('Slàn-àireamh', 'ˈsl̪ˠaːnˈaːɾʲəv'),
    'c2-interchange-highway': ('Snaim-rathaid', 'ˈsnaimˈr̪ˠahɪtʃ'),
    'c2-interest-rate-hike': ('Àrdachadh-rèidh', 'ˈaːɾt̪əxəɣˈr̪ˠeːj'),
    'c2-interloper': ('Coigreach gun chuireadh', 'ˈkʰɔkʲɾʲəx kən̪ˠ ˈxuɾʲəɣ'),
    'c2-interoperability': ('Rèite-innealan', 'ˈr̪ˠeːʰtʃəˈiɲəl̪ˠan'),
    'c2-interpreter-simultaneous': ('Mac-talla-cainnte', 'ˈmaʰkˈt̪ʰal̪ˠəˈkʰaiɲtʃə'),
    'c2-intravenous': ('Tro fhèith', 'ˈt̪ʰɾɔ ˈeː'),
    'c2-intrusion-detection': ('Faire-mèirlich', 'ˈfaɾʲəˈmeːɾʲlʲɪç'),
    'c2-irony': ('Ìoranas', 'ˈiəɾanəs'),
    'c2-irrefutable': ('Do-àicheadh', 'ˈt̪ɔˈaːçəɣ'),
    'c2-irrespective-of': ('Gun aire do', 'kən̪ˠ ˈaɾʲə t̪ə'),
    'c2-it-is-what-it-is': ('Tha e mar a tha e.', 'ˈha ˈɛ ˈmaɾ ə ˈha ˈɛ'),
    'c2-it-s-not-rocket-science': ("Chan e saighead-nèimh a th' ann.", 'xan ˈɛ ˈsa.ət̪ˈɲeːv ə ˈhaun̪ˠ'),
    'c2-it-s-on-the-tip-of-my-tongue': ('Tha e air bàrr mo theanga.', 'ˈha ˈɛ ˈɛɾʲ ˈpaːr̪ˠ mə ˈhɛŋə'),
    'c2-itch': ('Tachas', 'ˈt̪ʰaxəs'),
    'c2-jaded': ('Sàraichte', 'ˈsaːɾɪçtʃə'),
    'c2-jet-bridge': ('Drochaid-eòin', 'ˈt̪ɾɔxɪtʃˈjɔːnʲ'),
    'c2-jitter': ('Crith-sanais', 'ˈkʰɾʲihˈsanɪʃ'),
    'c2-juncture': ('Ìre', 'ˈiːɾʲə'),
    'c2-jurisprudence': ('Lagh-eòlas', 'ˈl̪ˠaˈjɔːl̪ˠəs'),
    'c2-juxtaposition': ('Co-shuidheachadh', 'kʰɔˈhu.əxəɣ'),
    'c2-keystone': ('Clach-ghlasaidh', 'ˈkʰl̪ˠaxˈɣl̪ˠasi'),
    'c2-kickback': ('Brìb', 'ˈpɾʲiːp'),
    'c2-killjoy': ('Milleadair-spòrs', 'ˈmiʎət̪ɪɾʲˈspɔːɾs'),
    'c2-labyrinthine': ('Ioma-lùbach', 'ˈiməˈl̪ˠuːpəx'),
    'c2-lackey': ('Gille-coise', 'ˈkʲiʎəˈkʰɔʃə'),
    'c2-laconic': ('Beag-bhriathrach', 'ˈpekˈvɾʲiəɾəx'),
    'c2-ladle': ('Ladar', 'ˈl̪ˠat̪əɾ'),
    'c2-landing-stairs': ('Ceann-staidhre', 'ˈkʲʰaun̪ˠˈst̪ajɾʲə'),
    'c2-languid': ('Fann', 'ˈfaun̪ˠ'),
    'c2-lanky': ('Fada-caol', 'ˈfat̪əˈkʰɯːl̪ˠ'),
    'c2-lapel': ('Liopaid', 'ˈʎiʰpɪtʃ'),
    'c2-large-language-model': ('Coire-bhriathran', 'ˈkʰɔɾʲəˈvɾʲiəɾan'),
    'c2-latch': ('Clàimhean', 'ˈkʰl̪ˠaːvan'),
    'c2-latent': ('Falaichte', 'ˈfal̪ˠɪçtʃə'),
    'c2-laudable': ('Ionmholta', 'ˈinivəl̪ˠt̪ə'),
    'c2-layperson': ('Neo-eòlaiche', 'ˈɲɔˈjɔːl̪ˠɪçə'),
    'c2-legacy-system': ('Inneal-sinnsre', 'ˈiɲəl̪ˠˈʃiːɲʃɾʲə'),
    'c2-let-s-call-it-a-day': ('Scuireamaid an-diugh.', 'ˈskuɾʲəmɪtʃ ən̪ˠˈtʃu'),
    'c2-let-s-play-it-by-ear': ('Chì sinn mar a thèid dhuinn.', 'ˈçiː ˈʃiːɲ ˈmaɾ ə ˈheːtʃ ˈɣuːiɲ'),
    'c2-let-sleeping-dogs-lie': ('Na dùisc an cù a tha na chadal.', 'nə ˈt̪uːʃkʲ əŋ ˈɡuː ə ˈha nə ˈxat̪əl̪ˠ'),
    'c2-lethargy': ('Marbhantachd', 'ˈmaɾavan̪ˠt̪əxk'),
    'c2-leverage-finance': ('Luamhan-iasaid', 'ˈl̪ˠuəvanˈiəsɪtʃ'),
    'c2-libel': ('Tuaileas', 'ˈt̪ʰuəlʲəs'),
    'c2-lichen': ('Crotal', 'ˈkʰɾɔʰt̪əl̪ˠ'),
    'c2-lightheaded': ('Aotrom sa cheann', 'ˈɯːʰt̪ɾəm sə ˈçaun̪ˠ'),
    'c2-lightning-bolt': ('Saighead-dealanaich', 'ˈsa.ət̪ˈtʃal̪ˠanɪç'),
    'c2-linguistics': ('Fios-cainnte', 'ˈfisˈkʰaiɲtʃə'),
    'c2-listless': ('Gun sunnd', 'kən̪ˠ ˈsuːn̪ˠt̪'),
    'c2-load-balancing': ('Roinn-eallaich', 'ˈr̪ˠɔiɲˈɛl̪ˠɪç'),
    'c2-locksmith': ('Glasadair', 'ˈkl̪ˠasət̪ɪɾʲ'),
    'c2-long-winded': ('Fad-chainnteach', 'ˈfat̪ˈxaiɲtʃəx'),
    'c2-look-before-you-leap': ('Seall romhad mus leum thu.', 'ˈʃaul̪ˠ ˈr̪ˠɔvət̪ məs ˈʎiəm ˈu'),
    'c2-loophole': ('Beàrn', 'ˈpʲaːɾn'),
    'c2-luscious': ('Sùghmhor', 'ˈsuːvəɾ'),
    'c2-macguffin': ('Ulaidh-sceòil', 'ˈul̪ˠiˈskʲɔːlʲ'),
    'c2-malapropism': ('Mearachd-fhacail', 'ˈmɛɾəxkˈaʰkɪlʲ'),
    'c2-malice': ('Mì-rùn', 'ˈmiːˈr̪ˠuːn'),
    'c2-malignant': ('Aillseach', 'ˈaiʎʃəx'),
    'c2-manslaughter': ('Marbhadh gun rùn', 'ˈmaɾavəɣ kən̪ˠ ˈr̪ˠuːn'),
    'c2-manuscript': ('Làmh-scrìobhainn', 'ˈl̪ˠaːvˈskɾʲiəvɪɲ'),
    'c2-margin-of-error': ('Iomall mearachd', 'ˈiməl̪ˠ ˈmɛɾəxk'),
    'c2-marsh': ('Boglach', 'ˈpɔkl̪ˠəx'),
    'c2-maverick': ('Neach neo-ghèilleach', 'ˈɲɛx ˈɲɔˈjeːʎəx'),
    'c2-meadow': ('Cluain', 'ˈkʰl̪ˠuənʲ'),
    'c2-mean-average': ('Cuibheas', 'ˈkʰuvəs'),
    'c2-median': ('Meadhan', 'ˈmɛ.an'),
    'c2-meekness': ('Macantas', 'ˈmaʰkan̪ˠt̪əs'),
    'c2-mellow': ('Tlàth', 'ˈt̪ʰl̪ˠaː'),
    'c2-memoir': ('Cuimhneachan', 'ˈkʰũnʲəxan'),
    'c2-mercenary': ('Saighdear-duaise', 'ˈsɤjtʃəɾˈt̪uəʃə'),
    'c2-mercurial': ('Caochlaideach', 'ˈkʰɯːxl̪ˠɪtʃəx'),
    'c2-metadata': ('Scàil-fiosa', 'ˈskaːlʲˈfisə'),
    'c2-metaphysics': ('Fios-thar-nàdair', 'ˈfisˈhaɾˈn̪ˠaːt̪ɪɾʲ'),
    'c2-meteorology': ('Eòlas-sìde', 'ˈjɔːl̪ˠəsˈʃiːtʃə'),
    'c2-meter-poetry': ('Meadrachd', 'ˈmɛt̪ɾəxk'),
    'c2-mezzanine': ('Leth-lobhta', 'ˈʎehˈl̪ˠɔvt̪ə'),
    'c2-microbiology': ('Fios-mhìolan', 'ˈfisˈviəl̪ˠan'),
    'c2-midwife': ('Bean-ghlùine', 'ˈpɛnˈɣl̪ˠuːnʲə'),
    'c2-migration-animal': ('Imrich', 'ˈimɾʲɪç'),
    'c2-misdemeanor': ('Eucoir aotrom', 'ˈiəʰkɪɾʲ ˈɯːʰt̪ɾəm'),
    'c2-mistrial': ('Cùis-fhaoin', 'ˈkʰuːʃˈɯːnʲ'),
    'c2-moat': ('Dìg', 'ˈtʃiːkʲ'),
    'c2-monetary-policy': ('Rian-airgid', 'ˈr̪ˠiənˈaɾʲakʲɪtʃ'),
    'c2-money-laundering': ('Nighe airgid', 'ˈɲi.ə ˈaɾʲakʲɪtʃ'),
    'c2-monsoon': ('Gaoth-ràithe', 'ˈkɯːˈr̪ˠaː.ə'),
    'c2-moot': ('Deasbadach', 'ˈtʃɛspət̪əx'),
    'c2-mop': ('Moibeal', 'ˈmɔpəl̪ˠ'),
    'c2-mordant': ('Guineach', 'ˈkɯnʲəx'),
    'c2-mosaic': ('Dealbh-chlach', 'ˈtʃal̪ˠavˈxl̪ˠax'),
    'c2-moss': ('Còinneach', 'ˈkʰɔːɲəx'),
    'c2-motif': ('Snàth-sceòil', 'ˈsnaːˈskʲɔːlʲ'),
    'c2-motion-sickness': ('Tinneas-siubhail', 'ˈtʃʰiɲəsˈʃuvɪlʲ'),
    'c2-musicology': ('Seanchas-ciùil', 'ˈʃɛnɛxəsˈkʲʰuːlʲ'),
    'c2-musty': ('Fuaraidh', 'ˈfuəɾi'),
    'c2-narrative': ('Aithris', 'ˈaɾʲɪʃ'),
    'c2-narrator': ('Neach-aithris', 'ˈɲɛxˈaɾʲɪʃ'),
    'c2-nebulous': ('Neo-shoilleir', 'ˈɲɔˈhɔʎɪɾʲ'),
    'c2-necessity-is-the-mother-of-invention': ('Is i an èiginn màthair na h-innleachd.', 'ɪs ˈi ən̪ˠ ˈeːkʲɪɲ ˈmaːhɪɾʲ nə ˈhiːɲlʲəxk'),
    'c2-nepotism': ('Fàbhar-dàimh', 'ˈfaːvəɾˈt̪aːv'),
    'c2-nest-egg': ('Airgead-tascaidh', 'ˈaɾʲakʲət̪ˈt̪ʰaski'),
    'c2-neurological': ('Fèith-eanchainneach', 'ˈfeːˈɛnɛxɪɲəx'),
    'c2-neuroscience': ('Fios-eanchainn', 'ˈfisˈɛnɛxɪɲ'),
    'c2-nightfall': ('Tuiteam na h-oidhche', 'ˈt̪ʰuʰtʃəm nə ˈhɤiçə'),
    'c2-no-hard-feelings': ('Gun droch-fhaireachdainn', 'kən̪ˠ ˈt̪ɾɔxˈaɾʲəxkɪɲ'),
    'c2-no-offense-but': ('Gun oilbheum, ach', 'kən̪ˠ ˈɔlʲɔviəm | ˈax'),
    'c2-nostalgia': ('Cianalas', 'ˈkʲʰiənəl̪ˠəs'),
    'c2-not-in-a-million-years': ('Chan ann gu sìorraidh!', 'xan ˈaun̪ˠ kə ˈʃiər̪ˠi'),
    'c2-novice': ('Tòiseachaiche', 'ˈt̪ʰɔːʃəxɪçə'),
    'c2-nuance': ('Mion-dhealachadh', 'ˈminˈjal̪ˠəxəɣ'),
    'c2-numbness': ('Cion-mothachaidh', 'ˈkʲʰinˈmɔ.əxi'),
    'c2-numerator': ('Àireamhaiche', 'ˈaːɾʲəvɪçə'),
    'c2-obsequious': ('Sodalach', 'ˈsɔt̪əl̪ˠəx'),
    'c2-oceanography': ('Fios-cuain', 'ˈfisˈkʰuənʲ'),
    'c2-odds-probability': ('Coltachd', 'ˈkʰɔl̪ˠt̪əxk'),
    'c2-odometer': ('Cunntair-slighe', 'ˈkʰuːn̪ˠt̪ɪɾʲˈʃlʲi.ə'),
    'c2-off-the-rack': ('Bhon sceilp', 'ˈvɔn ˈskʲelʲp'),
    'c2-off-the-top-of-my-head': ('Gun ro-smaoineachadh', 'kən̪ˠ ˈr̪ˠɔˈsmɯːnʲəxəɣ'),
    'c2-officious': ('Gnothachail', 'ˈkn̪ˠɔ.əxɪlʲ'),
    'c2-old-hand': ('Seann eòlaiche', 'ˈʃaun̪ˠ ˈjɔːl̪ˠɪçə'),
    'c2-on-balance': ('Uile gu lèir', 'ˈulʲə kə ˈʎeːɾʲ'),
    'c2-on-the-grounds-that': ("Air scàth 's gu", 'ˈɛɾʲ ˈskaː s kə'),
    'c2-oncologist': ('Sealgair-aillse', 'ˈʃal̪ˠakɪɾʲˈaiʎʃə'),
    'c2-onslaught': ('Ionnsaigh', 'ˈjuːn̪ˠsi'),
    'c2-ophthalmologist': ('Lighiche-sùla', 'ˈʎi.ɪçəˈsuːl̪ˠə'),
    'c2-order-of-magnitude': ('Ìre meudachd', 'ˈiːɾʲə ˈmiət̪əxk'),
    'c2-ornate': ('Sceadaichte', 'ˈskʲɛt̪ɪçtʃə'),
    'c2-ornithology': ('Eun-eòlas', 'ˈiənˈjɔːl̪ˠəs'),
    'c2-ostensible': ('A rèir coltais', 'ə ˈr̪ˠeːɾʲ ˈkʰɔl̪ˠt̪ɪʃ'),
    'c2-ostracism': ('Fògradh-fine', 'ˈfɔːkɾəɣˈfinʲə'),
    'c2-out-of-sight-out-of-mind': ("Fad às an t-sùil, fad às a' chridhe.", 'ˈfat̪ ˈaːs ən̪ˠ ˈt̪uːlʲ | ˈfat̪ ˈaːs ə ˈxɾʲi.ə'),
    'c2-outlier': ('Luach iomallach', 'ˈl̪ˠuəx ˈiməl̪ˠəx'),
    'c2-oven-mitt': ('Miotag-àmhainn', 'ˈmiʰt̪akˈaːvɪɲ'),
    'c2-overfitting': ('Ionnsachadh-dall', 'ˈjuːn̪ˠsəxəɣˈt̪aul̪ˠ'),
    'c2-overhead-compartment': ('Ciste-mhullaich', 'ˈkʲʰiʃtʃəˈvul̪ˠɪç'),
    'c2-overpass': ('Os-rathad', 'ˈɔsˈr̪ˠa.ət̪'),
    'c2-overture': ('Ro-cheòl', 'ˈr̪ˠɔˈçɔːl̪ˠ'),
    'c2-oxymoron': ('Frith-ràdh', 'ˈfɾʲihˈr̪ˠaːɣ'),
    'c2-paleontologist': ('Cladhaire-chnàmh', 'ˈkʰl̪ˠa.ɪɾʲəˈxnaːv'),
    'c2-palette': ('Clàr-dhathan', 'ˈkʰl̪ˠaːɾˈɣahan'),
    'c2-palliative-care': ('Faochadh-deiridh', 'ˈfɯːxəɣˈtʃeɾʲi'),
    'c2-paltry': ('Crìon', 'ˈkʰɾʲiən'),
    'c2-pandemic': ('Galar mòr-scaoilte', 'ˈkal̪ˠəɾ ˈmoːɾˈskɯːlʲtʃə'),
    'c2-pantry': ('Pantraidh', 'ˈpʰan̪ˠt̪ɾi'),
    'c2-paralegal': ('Gille-lagha', 'ˈkʲiʎəˈl̪ˠa.ə'),
    'c2-parapet': ('Uchd-bhalla', 'ˈuxkˈval̪ˠə'),
    'c2-paraphrase': ('Ath-fhaclachadh', 'ˈahˈaʰkl̪ˠəxəɣ'),
    'c2-pariah': ('Dìobarach', 'ˈtʃiəpəɾəx'),
    'c2-parody': ('Fochaid-dàin', 'ˈfɔxɪtʃˈt̪aːnʲ'),
    'c2-parole': ('Saorsa-geallaidh', 'ˈsɯːɾsəˈkʲɛl̪ˠi'),
    'c2-partition-wall': ('Balla-dealachaidh', 'ˈpal̪ˠəˈtʃal̪ˠəxi'),
    'c2-passkey': ('Iuchair-aithne', 'ˈjuxɪɾʲˈanʲə'),
    'c2-pathogen': ('Sìol-galair', 'ˈʃiəl̪ˠˈkal̪ˠɪɾʲ'),
    'c2-pathologist': ('Saoi-ghalair', 'ˈsɯiˈɣal̪ˠɪɾʲ'),
    'c2-patron': ('Pàtran', 'ˈpʰaːʰt̪ɾan'),
    'c2-pebble': ('Molag', 'ˈmɔl̪ˠak'),
    'c2-pecking-order': ('Òrdugh-inbhe', 'ˈɔːɾt̪əɣˈinʲivə'),
    'c2-pedagogy': ('Oide-eòlas', 'ˈɔtʃəˈjɔːl̪ˠəs'),
    'c2-pedantic': ('Rag-fhoghlamach', 'ˈr̪ˠakˈɔl̪ˠəməx'),
    'c2-peephole': ('Toll-coimhead', 'ˈt̪ʰɔul̪ˠˈkʰɔvət̪'),
    'c2-peerless': ('Gun choimeas', 'kən̪ˠ ˈxɔməs'),
    'c2-pending': ("A' feitheamh air", 'ə ˈfe.əv ˈɛɾʲ'),
    'c2-percentage-point': ('Puing-sa-cheud', 'ˈpʰuːiɲkʲˈsaˈçiət̪'),
    'c2-percentile': ('Ceudadach', 'ˈkʲʰiət̪ət̪əx'),
    'c2-perfumer': ('Cùbhradair', 'ˈkʰuːvɾət̪ɪɾʲ'),
    'c2-perjury': ('Eitheach', 'ˈe.əx'),
    'c2-pernicious': ('Millteach', 'ˈmiːʎtʃəx'),
    'c2-perpetrator': ('Eucoireach', 'ˈiəʰkɪɾʲəx'),
    'c2-perseverance': ('Buanseasmhachd', 'ˈpuənʲʃəsvəxk'),
    'c2-perspicuous': ('Soilleir', 'ˈsɔʎɪɾʲ'),
    'c2-petulant': ('Frionasach', 'ˈfɾʲinəsəx'),
    'c2-pharmacology': ('Fios-ìocshlainte', 'ˈfisˈiəʰkhl̪ˠɪɲtʃə'),
    'c2-philology': ('Seanchas-fhaclan', 'ˈʃɛnɛxəsˈaʰkl̪ˠan'),
    'c2-phlegmatic': ('Ciùin', 'ˈkʲʰuːnʲ'),
    'c2-phonetics': ('Fios-fuaime', 'ˈfisˈfuəmə'),
    'c2-physiotherapist': ('Suathaire-fèithe', 'ˈsuəhɪɾʲəˈfeː.ə'),
    'c2-piercing': ('Druidhteach', 'ˈt̪ɾɯjʰtʃəx'),
    'c2-pillar': ('Carragh', 'ˈkʰaːr̪ˠəɣ'),
    'c2-pins-and-needles': ('Cadal-deilgneach', 'ˈkʰat̪əl̪ˠˈtʃelʲekʲnʲəx'),
    'c2-pithy': ('Brìghmhor', 'ˈpɾʲiːvəɾ'),
    'c2-placebo': ('Leigheas-creidimh', 'ˈʎe.əsˈkʰɾʲetʃɪv'),
    'c2-placeholder': ('Àite-gleidhidh', 'ˈaːʰtʃəˈkʲlʲe.i'),
    'c2-plaintiff': ('Neach-agairt', 'ˈɲɛxˈakɪɾʲtʃ'),
    'c2-plaintive': ('Tiamhaidh', 'ˈtʃʰiəvi'),
    'c2-platitude': ('Facal caithte', 'ˈfaʰkəl̪ˠ ˈkʰatʃə'),
    'c2-plausible': ('Creideasach', 'ˈkʰɾʲetʃəsəx'),
    'c2-plea-bargain': ('Cùmhnant-aideachaidh', 'ˈkʰũːnan̪ˠt̪ˈatʃəxi'),
    'c2-pleat': ('Filleadh', 'ˈfiʎəɣ'),
    'c2-pliers': ('Greimiche', 'ˈkɾʲemɪçə'),
    'c2-plight': ('Càs', 'ˈkʰaːs'),
    'c2-plumage': ('Iteach', 'ˈiʰtʃəx'),
    'c2-plumbing-system': ('Lìon-uisce', 'ˈʎiənˈɯʃkʲə'),
    'c2-point-taken': ("Tha mi a' tuigsinn.", 'ˈha ˈmi ə ˈt̪ʰɯkʲʃɪɲ'),
    'c2-poised': ('Suidhichte', 'ˈsu.ɪçtʃə'),
    'c2-pollination': ('Pòsadh-blàtha', 'ˈpʰɔːsəɣˈpl̪ˠaː.ə'),
    'c2-postulate': ('Bun-bheachd', 'ˈpunˈvɛxk'),
    'c2-power-strip': ('Clàr-dealain', 'ˈkʰl̪ˠaːɾˈtʃal̪ˠɪnʲ'),
    'c2-practice-makes-perfect': ('Nì cleachdadh teòma.', 'ˈɲiː ˈkʲʰlʲɛxkəɣ ˈtʃʰɔːmə'),
    'c2-precarious': ('Cugallach', 'ˈkʰukəl̪ˠəx'),
    'c2-precedent': ('Ro-eisimpleir', 'ˈr̪ˠɔˈeʃɪmplʲɪɾʲ'),
    'c2-preposterous': ('Amaideach', 'ˈamɪtʃəx'),
    'c2-prescription-written-order': ('Òrdugh-cungaidh', 'ˈɔːɾt̪əɣˈkʰuŋi'),
    'c2-pretext': ('Leisceul', 'ˈʎeʃkʲiəl̪ˠ'),
    'c2-prime-number': ('Prìomh-àireamh', 'ˈpʰɾʲiəvˈaːɾʲəv'),
    'c2-probation': ('Saorsa-faire', 'ˈsɯːɾsəˈfaɾʲə'),
    'c2-prodigy': ('Leanabh-iongantais', 'ˈʎɛnəvˈiŋan̪ˠt̪ɪʃ'),
    'c2-profligate': ('Stròdhail', 'ˈst̪ɾɔː.ɪlʲ'),
    'c2-prognosis': ('Ro-aithne', 'ˈr̪ˠɔˈanʲə'),
    'c2-proprietary': ('Seilbheach', 'ˈʃelʲevəx'),
    'c2-prose': ('Rosc', 'ˈr̪ˠɔsk'),
    'c2-prudence': ('Crìonnachd', 'ˈkʰɾʲiən̪ˠəxk'),
    'c2-public-defender': ('Guth-nam-bochd', 'ˈkuhˈn̪ˠaumˈpɔxk'),
    'c2-pulled-muscle': ('Fèith shìnte', 'ˈfeː ˈhiːɲtʃə'),
    'c2-pun': ('Cluich-fhacal', 'ˈkʰl̪ˠuçˈaʰkəl̪ˠ'),
    'c2-pungent': ('Geur-fhàileach', 'ˈkʲiəɾˈaːlʲəx'),
    'c2-pursuant-to': ('A rèir', 'ə ˈr̪ˠeːɾʲ'),
    'c2-pushover': ('Duine bog', 'ˈt̪ɯnʲə ˈpɔk'),
    'c2-putrid': ('Grod', 'ˈkɾɔt̪'),
    'c2-quandary': ('Imcheist', 'ˈimçɪʃtʃ'),
    'c2-quantum-computing': ('Cunntas-draoidh', 'ˈkʰuːn̪ˠt̪əsˈt̪ɾɯːj'),
    'c2-queasy': ('Sleogach', 'ˈʃlʲɔkəx'),
    'c2-query': ('Ceist-rannsachaidh', 'ˈkʲʰeʃtʃˈr̪ˠaun̪ˠsəxi'),
    'c2-quip': ('Gearr-fhacal', 'ˈkʲaːr̪ˠˈaʰkəl̪ˠ'),
    'c2-quotient': ('Toradh-roinn', 'ˈt̪ʰɔɾəɣˈr̪ˠɔiɲ'),
    'c2-racketeering': ('Creach-buidhne', 'ˈkʰɾʲɛxˈpɯjnʲə'),
    'c2-radiologist': ('Saoi-scàile', 'ˈsɯiˈskaːlʲə'),
    'c2-rafter': ('Taobhan', 'ˈt̪ʰɯːvan'),
    'c2-ramification': ('Iarmhairt', 'ˈiəɾvɪɾʲtʃ'),
    'c2-rampant': ('Gun srian', 'kən̪ˠ ˈst̪ɾʲiən'),
    'c2-ramshackle': ('Robach', 'ˈr̪ˠɔpəx'),
    'c2-rancid': ('Breun', 'ˈpɾʲiən'),
    'c2-ransom': ('Èirig', 'ˈeːɾʲɪkʲ'),
    'c2-ravine': ('Clais', 'ˈkʰl̪ˠaʃ'),
    'c2-rebuttal': ('Breugnachadh', 'ˈpɾʲiəknəxəɣ'),
    'c2-receivership': ('Glacadh-fiachan', 'ˈkl̪ˠaʰkəɣˈfiəxan'),
    'c2-recluse': ('Dìthreabhach', 'ˈtʃiːɾʲəvəx'),
    'c2-rectitude': ('Ionracas', 'ˈinɾəʰkəs'),
    'c2-recurrence': ('Ath-thilleadh', 'ˈahˈhiʎəɣ'),
    'c2-red-eye-flight': ('Siubhal-comhachaig', 'ˈʃuvəl̪ˠˈkʰɔvəxɪkʲ'),
    'c2-red-herring': ('Sanas meallta', 'ˈsanəs ˈmʲaul̪ˠt̪ə'),
    'c2-redundancy-backup': ('Iomarcachd', 'ˈiməɾkəxk'),
    'c2-referral-to-a-specialist': ('Tar-chur', 'ˈt̪ʰaɾˈxuɾ'),
    'c2-reflex': ('Ath-bhualadh', 'ˈahˈvuəl̪ˠəɣ'),
    'c2-remainder': ('Fuidheall', 'ˈfu.əl̪ˠ'),
    'c2-remand': ('Cumail an grèim', 'ˈkʰumɪlʲ əŋ ˈkɾʲeːm'),
    'c2-repartee': ('Geur-fhreagairt', 'ˈkʲiəɾˈɾʲekɪɾʲtʃ'),
    'c2-respiratory': ('Analach', 'ˈanəl̪ˠəx'),
    'c2-respite': ('Faochadh', 'ˈfɯːxəɣ'),
    'c2-restlessness': ('Mì-fhois', 'ˈmiːˈɔʃ'),
    'c2-reticence': ('Dùinteachd', 'ˈt̪uːɲtʃəxk'),
    'c2-retrofit': ('Ath-ghleusadh', 'ˈahˈjlʲiəsəɣ'),
    'c2-rhetoric': ('Òraidheachd', 'ˈɔːɾɪ.əxk'),
    'c2-rhetorical': ('Òraideach', 'ˈɔːɾɪtʃəx'),
    'c2-rickety': ('Cugallach', 'ˈkʰukəl̪ˠəx'),
    'c2-ridge': ('Druim', 'ˈt̪ɾuːim'),
    'c2-rife': ('Lìonmhor', 'ˈʎiənvəɾ'),
    'c2-rivalry': ('Còmhstri', 'ˈkʰɔ̃ːʃtʃɾʲɪ'),
    'c2-rollback': ('Tilleadh air ais', 'ˈtʃʰiʎəɣ ˈɛɾʲ ˈaʃ'),
    'c2-rollout': ('Cur an sàs', 'ˈkʰuɾ ən̪ˠ ˈsaːs'),
    'c2-rome-wasn-t-built-in-a-day': ('Cha deach an Ròimh a thogail ann an aon latha.', 'xa ˈtʃɛx ən̪ˠ ˈr̪ˠɔːv ə ˈhɔkɪlʲ ˈaun̪ˠ ən̪ˠ ˈɯːn ˈl̪ˠa.ə'),
    'c2-round-number': ('Àireamh chruinn', 'ˈaːɾʲəv ˈxɾuːiɲ'),
    'c2-rounding': ('Cruinneachadh àireamhan', 'ˈkʰɾɯɲəxəɣ ˈaːɾʲəvan'),
    'c2-ruling': ('Breith', 'ˈpɾʲeh'),
    'c2-sage': ('Saoi', 'ˈsɯi'),
    'c2-salient': ('Follaiseach', 'ˈfɔl̪ˠɪʃəx'),
    'c2-salt-flat': ('Còmhnard salainn', 'ˈkʰɔ̃ːnəɾt̪ ˈsal̪ˠɪɲ'),
    'c2-sample-size': ('Meud-blasaid', 'ˈmiət̪ˈpl̪ˠasɪtʃ'),
    'c2-sanctimonious': ('Fuar-chràbhach', 'ˈfuəɾˈxɾaːvəx'),
    'c2-sandbox': ('Bogsa-gainmhich', 'ˈpɔksəˈkanʲavɪç'),
    'c2-sanguine': ('Dòchasach', 'ˈt̪ɔːxəsəx'),
    'c2-sap': ('Snodhach', 'ˈsnɔ.əx'),
    'c2-sapling': ('Faillean', 'ˈfaʎan'),
    'c2-sarcasm': ('Searbhas', 'ˈʃɛɾɛvəs'),
    'c2-sardonic': ('Fanaideach', 'ˈfanɪtʃəx'),
    'c2-satire': ('Aoir', 'ˈɯːɾʲ'),
    'c2-say-no-more': ('Na can an còrr.', 'nə ˈkʰan əŋ ˈɡɔːr̪ˠ'),
    'c2-scant': ('Gann', 'ˈkaun̪ˠ'),
    'c2-scathing': ('Scaiteach', 'ˈskaʰtʃəx'),
    'c2-scorcher': ('Latha loisceach', 'ˈl̪ˠa.ə ˈl̪ˠɔʃkʲəx'),
    'c2-scorn': ('Tàir', 'ˈt̪ʰaːɾʲ'),
    'c2-scruffy': ('Robach', 'ˈr̪ˠɔpəx'),
    'c2-second-wind': ('Dara anail', 'ˈt̪aɾə ˈanɪlʲ'),
    'c2-sedative': ('Deoch-shuaimhneis', 'ˈtʃɔxˈhũənʲɪʃ'),
    'c2-sediment': ('Grùid', 'ˈkɾuːtʃ'),
    'c2-seismology': ('Fios-crithe', 'ˈfisˈkʰɾʲi.ə'),
    'c2-self-starter': ('Fear-tionnscain', 'ˈfɛɾˈtʃʰuːn̪ˠskɪnʲ'),
    'c2-semantics': ('Fios-brìghe', 'ˈfisˈpɾʲiː.ə'),
    'c2-semiconductor': ('Clach-dealain', 'ˈkʰl̪ˠaxˈtʃal̪ˠɪnʲ'),
    'c2-semiotics': ('Fios-chomharran', 'ˈfisˈxɔvər̪ˠan'),
    'c2-sentence-punishment': ('Binn', 'ˈpiːɲ'),
    'c2-setback': ('Ceum air ais', 'ˈkʲʰiəm ˈɛɾʲ ˈaʃ'),
    'c2-sewing-kit': ('Pascan fuaigheil', 'ˈpʰaskan ˈfuə.ɪlʲ'),
    'c2-share-buyback': ('Cùl-cheannach', 'ˈkʰuːl̪ˠˈçɛn̪ˠəx'),
    'c2-shiver': ('Ball-chrith', 'ˈpaul̪ˠˈxɾʲih'),
    'c2-shoehorn': ('Adharc-bhròg', 'ˈa.əɾkˈvɾɔːk'),
    'c2-show-off': ('Bragaire', 'ˈpɾakɪɾʲə'),
    'c2-sidekick': ('Companach', 'ˈkʰɔmpanəx'),
    'c2-silky': ('Sìodach', 'ˈʃiət̪əx'),
    'c2-silver-tongued': ('Deas-bhriathrach', 'ˈtʃɛsˈvɾʲiəɾəx'),
    'c2-simile': ('Samhlachas', 'ˈsãũl̪ˠəxəs'),
    'c2-sinking-fund': ('Maoin-dìolaidh', 'ˈmɯːnʲˈtʃiəl̪ˠi'),
    'c2-skylight': ('Uinneag-mhullaich', 'ˈɯɲakˈvul̪ˠɪç'),
    'c2-slander': ('Cùl-chàineadh', 'ˈkʰuːl̪ˠˈxaːnʲəɣ'),
    'c2-sleet': ('Flin', 'ˈflʲinʲ'),
    'c2-slimy': ('Ramallach', 'ˈr̪ˠaməl̪ˠəx'),
    'c2-slur-insult': ('Masladh', 'ˈmasl̪ˠəɣ'),
    'c2-slush-fund': ('Ciste dhìomhair', 'ˈkʲʰiʃtʃə ˈjiəvɪɾʲ'),
    'c2-small-circle-inner-circle': ('Cearcall dlùth', 'ˈkʲʰɛɾkəl̪ˠ ˈt̪l̪ˠuː'),
    'c2-smugness': ('Fèin-riarachas', 'ˈfeːnʲˈr̪ˠiəɾəxəs'),
    'c2-sneeze': ('Sreothart', 'ˈst̪ɾʲɔ.əɾt̪'),
    'c2-snub': ('Dìmeas', 'ˈtʃiːməs'),
    'c2-snug': ('Teann', 'ˈtʃʰaun̪ˠ'),
    'c2-social-engineering': ('Mealladh-cainnte', 'ˈmɛl̪ˠəɣˈkʰaiɲtʃə'),
    'c2-sociolinguistics': ('Fios-cainnt-sluaigh', 'ˈfisˈkʰaiɲtʃˈsl̪ˠuəj'),
    'c2-sodden': ('Bog fliuch', 'ˈpɔk ˈflʲux'),
    'c2-soggy': ('Bog', 'ˈpɔk'),
    'c2-solidarity': ('Dlùthachd', 'ˈt̪l̪ˠuː.əxk'),
    'c2-soliloquy': ('Fèin-chòmhradh', 'ˈfeːnʲˈxɔ̃ːɾəɣ'),
    'c2-solstice': ('Grian-stad', 'ˈkɾʲiənˈst̪at̪'),
    'c2-solvency': ('Comas-pàighidh', 'ˈkʰɔməsˈpʰaː.i'),
    'c2-sonnet': ('Duan-ceithir-deug', 'ˈt̪uənˈkʲʰehɪɾʲˈtʃiək'),
    'c2-sparse': ('Tearc', 'ˈtʃʰɛɾk'),
    'c2-spatula': ('Spadal', 'ˈspat̪əl̪ˠ'),
    'c2-speak-of-the-devil': ("Bruidhinn air an donas, 's nochdaidh e.", 'ˈpɾu.ɪɲ ˈɛɾʲ ən̪ˠ ˈt̪ɔnəs | s ˈn̪ˠɔxki ˈɛ'),
    'c2-speed-bump': ('Cnap-astair', 'ˈkʰn̪ˠaʰpˈast̪ɪɾʲ'),
    'c2-spill-the-beans': ('Scaoil an rùn', 'ˈskɯːlʲ ən̪ˠ ˈr̪ˠuːn'),
    'c2-spire': ('Binnean', 'ˈpiɲan'),
    'c2-spirit-level': ('Còmhnardair', 'ˈkʰɔ̃ːnəɾt̪ɪɾʲ'),
    'c2-spurious': ('Fuadain', 'ˈfuət̪ɪnʲ'),
    'c2-squall': ('Scal', 'ˈskal̪ˠ'),
    'c2-square-root': ('Freumh ceàrnagach', 'ˈfɾʲiəv ˈkʲʰaːɾnəkəx'),
    'c2-stagflation': ('At-crìonaidh', 'ˈaʰt̪ˈkʰɾʲiəni'),
    'c2-stagnant': ('Marbh', 'ˈmaɾav'),
    'c2-stalemate': ('Staid gun bhuannachd', 'ˈst̪atʃ kən̪ˠ ˈvuən̪ˠəxk'),
    'c2-stalwart': ('Neach-taice dìleas', 'ˈɲɛxˈt̪ʰaʰkʲə ˈtʃiːlʲəs'),
    'c2-stamina': ('Fulangas', 'ˈful̪ˠəŋəs'),
    'c2-standard-deviation': ('Claonadh coitcheann', 'ˈkʰl̪ˠɯːnəɣ ˈkʰɔʰtʃçən̪ˠ'),
    'c2-stanza': ('Rann', 'ˈr̪ˠaun̪ˠ'),
    'c2-statute': ('Reachd', 'ˈr̪ˠɛxk'),
    'c2-statute-of-limitations': ('Crìoch-ùine laghail', 'ˈkʰɾʲiəxˈuːnʲə ˈl̪ˠa.ɪlʲ'),
    'c2-stenographer': ('Geàrr-scrìobhaiche', 'ˈkʲaːr̪ˠˈskɾʲiəvɪçə'),
    'c2-stiffness': ('Raige', 'ˈr̪ˠakʲə'),
    'c2-stigma': ('Làrach-nàire', 'ˈl̪ˠaːɾəxˈn̪ˠaːɾʲə'),
    'c2-still-life': ('Beatha shàmhach', 'ˈpɛ.ə ˈhaːvəx'),
    'c2-still-waters-run-deep': ('Is domhainn na h-uisceachan ciùin.', 'ɪs ˈt̪ɔvɪɲ nə ˈhɯʃkʲəxan ˈkʲʰuːnʲ'),
    'c2-stocky': ('Calma', 'ˈkʰal̪ˠamə'),
    'c2-strike-while-the-iron-is-hot': ("Buail an t-iarann fhad 's a tha e teth.", 'ˈpuəlʲ ən̪ˠ ˈtʃʰiəɾən̪ˠ ˈat̪ s ə ˈha ˈɛ ˈtʃʰeh'),
    'c2-stubble': ('Feusag ghoirid', 'ˈfiəsak ˈɣɔɾʲɪtʃ'),
    'c2-subpoena': ('Bàirlinn', 'ˈpaːɾʲlʲɪɲ'),
    'c2-subsidy': ('Taic-crùin', 'ˈt̪ʰaʰkʲˈkʰɾuːnʲ'),
    'c2-subtext': ('Fo-bhrìgh', 'ˈfɔˈvɾʲiː'),
    'c2-succinct': ('Pongail', 'ˈpʰɔŋɪlʲ'),
    'c2-suit-yourself': ('Mar as toil leat.', 'ˈmaɾ ˈas ˈt̪ʰɔlʲ ˈʎɛʰt̪'),
    'c2-sultry': ('Bruthainneach', 'ˈpɾuhɪɲəx'),
    'c2-summit': ('Mullach', 'ˈmul̪ˠəx'),
    'c2-sumptuous': ('Sòghail', 'ˈsɔː.ɪlʲ'),
    'c2-superfluous': ('Iomarcach', 'ˈiməɾkəx'),
    'c2-surge': ('Bàrcadh', 'ˈpaːɾkəɣ'),
    'c2-surrealism': ('Ealain-aislinge', 'ˈjal̪ˠɪnʲˈaʃlʲɪɲə'),
    'c2-surveyor': ('Tomhasair', 'ˈt̪ʰɔvəsɪɾʲ'),
    'c2-susceptible': ('Buailteach', 'ˈpuəlʲtʃəx'),
    'c2-suture': ('Grèim', 'ˈkɾʲeːm'),
    'c2-symptomatic': ('Le comharraidhean', 'lʲə ˈkʰɔvər̪ˠɪ.an'),
    'c2-taboo': ('Toirmeasc', 'ˈt̪ʰɔɾʲɔməsk'),
    'c2-taciturn': ('Tosdach', 'ˈt̪ʰɔst̪əx'),
    'c2-tailgating-driving': ('Teannadh-earbaill', 'ˈtʃʰɛn̪ˠəɣˈɛɾɛpɪʎ'),
    'c2-tailored': ('Tàillearaichte', 'ˈt̪ʰaːʎəɾɪçtʃə'),
    'c2-take-it-with-a-grain-of-salt': ('Gabh le pinne salainn e', 'ˈkav lʲə ˈpʰiɲə ˈsal̪ˠɪɲ ˈɛ'),
    'c2-talon': ('Spuir', 'ˈspuɾʲ'),
    'c2-tangent': ('Seachran', 'ˈʃɛxɾan'),
    'c2-tangy': ('Geur-bhlasta', 'ˈkʲiəɾˈvl̪ˠast̪ə'),
    'c2-tape-measure': ('Stiall-tomhais', 'ˈʃtʃiəl̪ˠˈt̪ʰɔvɪʃ'),
    'c2-tax-evasion': ('Seachnadh cìse', 'ˈʃɛxnəɣ ˈkʲʰiːʃə'),
    'c2-tax-loophole': ('Beàrn-cìse', 'ˈpʲaːɾnˈkʲʰiːʃə'),
    'c2-taxidermist': ('Lìonadair-bhian', 'ˈʎiənət̪ɪɾʲˈviən'),
    'c2-taxiing': ('Coiseachd-eòin', 'ˈkʰɔʃəxkˈjɔːnʲ'),
    'c2-telemetry': ('Sceul-cèin', 'ˈskʲiəl̪ˠˈkʲʰeːnʲ'),
    'c2-tenable': ('So-dhìon', 'ˈsɔˈjiən'),
    'c2-tenacity': ('Diongmhaltas', 'ˈtʃuːŋvəl̪ˠt̪əs'),
    'c2-tenet': ('Prionnsabal', 'ˈpʰɾʲuːn̪ˠsəpəl̪ˠ'),
    'c2-tenuous': ('Caol', 'ˈkʰɯːl̪ˠ'),
    'c2-terse': ('Aithghearr', 'ˈa.ər̪ˠ'),
    'c2-testimony': ('Fianais', 'ˈfiənɪʃ'),
    'c2-that-s-on-me': ("Is e mo choire-sa a th' ann.", 'ɪs ˈɛ mə ˈxɔɾʲəˈsa ə ˈhaun̪ˠ'),
    'c2-that-s-the-last-straw': ('Sin an sop mu dheireadh.', 'ˈʃinʲ ən̪ˠ ˈsɔʰp mə ˈjeɾʲəɣ'),
    'c2-thaw': ('Aiteamh', 'ˈaʰtʃəv'),
    'c2-the-early-bird-catches-the-worm': ("Gheibh an t-eun moch a' chnuimh.", 'ˈjev ən̪ˠ ˈtʃʰiən ˈmɔx ə ˈxnuv'),
    'c2-the-grass-is-always-greener-on-the-other-side': ('Is gorm na cnuic a bhios fada bhuainn.', 'ɪs ˈkɔɾɔm nə ˈkʰn̪ˠɯʰkʲ ə ˈvis ˈfat̪ə ˈvuəɲ'),
    'c2-the-pen-is-mightier-than-the-sword': ('Is cumhachdaiche am peann na an claidheamh.', 'ɪs ˈkʰuvəxkɪçə əm ˈbʲaun̪ˠ nə əŋ ˈɡl̪ˠa.əv'),
    'c2-theology': ('Diadhachd', 'ˈtʃiə.əxk'),
    'c2-thicket': ('Preasarnach', 'ˈpʰɾʲɛsəɾnəx'),
    'c2-threadbare': ('Lom-chaithte', 'ˈl̪ˠɔumˈxatʃə'),
    'c2-threefold': ('Trìfillte', 'ˈt̪ʰɾʲiːfɪʎtʃə'),
    'c2-throbbing': ('Ploscartach', 'ˈpʰl̪ˠɔskəɾt̪əx'),
    'c2-throughput': ('Tomhas-sruthaidh', 'ˈt̪ʰɔvəsˈst̪ɾuhi'),
    'c2-thunderclap': ('Brag tàirneanaich', 'ˈpɾak ˈt̪ʰaːɾʲnʲanɪç'),
    'c2-tide-pool': ('Glumag-chladaich', 'ˈkl̪ˠumakˈxl̪ˠat̪ɪç'),
    'c2-tingling': ('Biorgadh', 'ˈpiɾikəɣ'),
    'c2-tipping-point': ('Puing-tionndaidh', 'ˈpʰuːiɲkʲˈtʃʰuːn̪ˠt̪i'),
    'c2-tirade': ('Ionnsaigh-chainnte', 'ˈjuːn̪ˠsiˈxaiɲtʃə'),
    'c2-to-abate': ('Lagachadh', 'ˈl̪ˠakəxəɣ'),
    'c2-to-abhor': ('Fuathachadh', 'ˈfuə.əxəɣ'),
    'c2-to-abominate': ('Gràineachadh', 'ˈkɾaːnʲəxəɣ'),
    'c2-to-abstain': ('Staonadh', 'ˈst̪ɯːnəɣ'),
    'c2-to-accentuate': ('Cur cuideam air', 'ˈkʰuɾ ˈkʰutʃəm ˈɛɾʲ'),
    'c2-to-acquiesce': ('Gèilleadh', 'ˈkʲeːʎəɣ'),
    'c2-to-admonish': ('Earalachadh', 'ˈɛɾəl̪ˠəxəɣ'),
    'c2-to-aggravate': ('Dèanamh nas miosa', 'ˈtʃiənəv ˈn̪ˠas ˈmisə'),
    'c2-to-alleviate': ('Faothachadh', 'ˈfɯː.əxəɣ'),
    'c2-to-allude-to': ('Toirt iomradh air', 'ˈt̪ʰɔɾʲtʃ ˈimɾəɣ ˈɛɾʲ'),
    'c2-to-amass': ('Cruinneachadh', 'ˈkʰɾɯɲəxəɣ'),
    'c2-to-appease': ('Ciùineachadh', 'ˈkʲʰuːnʲəxəɣ'),
    'c2-to-ascribe': ('Cur às leth', 'ˈkʰuɾ ˈaːs ˈʎeh'),
    'c2-to-assail': ('Toirt ionnsaigh air', 'ˈt̪ʰɔɾʲtʃ ˈjuːn̪ˠsi ˈɛɾʲ'),
    'c2-to-augment': ('Meudachadh', 'ˈmiət̪əxəɣ'),
    'c2-to-avert': ('Cascadh', 'ˈkʰaskəɣ'),
    'c2-to-bear-the-brunt': ('Giùlan an ualaich as truime', 'ˈkʲuːl̪ˠan ən̪ˠ ˈuəl̪ˠɪç ˈas ˈt̪ʰɾumə'),
    'c2-to-beckon': ('Smèideadh', 'ˈsmeːtʃəɣ'),
    'c2-to-beget': ('Sìolachadh', 'ˈʃiəl̪ˠəxəɣ'),
    'c2-to-begrudge': ('Maoidheadh', 'ˈmɯː.əɣ'),
    'c2-to-belabor-the-point': ('Sìor-bhruidhinn air', 'ˈʃiəɾˈvɾu.ɪɲ ˈɛɾʲ'),
    'c2-to-belittle': ('Beag-chùiseachadh', 'ˈpekˈxuːʃəxəɣ'),
    'c2-to-bequeath': ('Tiomnadh', 'ˈtʃʰimnəɣ'),
    'c2-to-beseech': ('Guidhe', 'ˈku.ə'),
    'c2-to-besiege': ('Sèisdeadh', 'ˈʃeːʃtʃəɣ'),
    'c2-to-bewilder': ('Cur an imcheist', 'ˈkʰuɾ ən̪ˠ ˈimçɪʃtʃ'),
    'c2-to-brandish': ('Crathadh', 'ˈkʰɾa.əɣ'),
    'c2-to-brood': ('Cnuasachadh', 'ˈkʰn̪ˠuəsəxəɣ'),
    'c2-to-cajole': ('Brìodal', 'ˈpɾʲiət̪əl̪ˠ'),
    'c2-to-captivate': ('Cur fo gheasaibh', 'ˈkʰuɾ fə ˈjɛsɪv'),
    'c2-to-cast-doubt-on': ('Teagamh a chur air', 'ˈtʃʰekəv ə ˈxuɾ ˈɛɾʲ'),
    'c2-to-castigate': ('Sciùrsadh', 'ˈskʲuːɾsəɣ'),
    'c2-to-chastise': ('Peanasachadh', 'ˈpʰɛnəsəxəɣ'),
    'c2-to-coalesce': ('Co-leaghadh', 'kʰɔˈʎɛ.əɣ'),
    'c2-to-coax': ('Cur impidh air', 'ˈkʰuɾ ˈimpi ˈɛɾʲ'),
    'c2-to-come-to-fruition': ('Tighinn gu buil', 'ˈtʃʰi.ɪɲ kə ˈpulʲ'),
    'c2-to-commend': ('Moladh', 'ˈmɔl̪ˠəɣ'),
    'c2-to-commiserate': ('Dèanamh co-bhròn ri', 'ˈtʃiənəv kʰɔˈvɾɔːn ɾʲə'),
    'c2-to-concede': ('Aideachadh', 'ˈatʃəxəɣ'),
    'c2-to-concoct': ('Innleachadh', 'ˈiːɲlʲəxəɣ'),
    'c2-to-condescend': ('Bruidhinn sìos ri', 'ˈpɾu.ɪɲ ˈʃiəs ɾʲə'),
    'c2-to-confer': ('Buileachadh', 'ˈpulʲəxəɣ'),
    'c2-to-confide-in': ('Leigeil rùin ri', 'ˈʎekʲɪlʲ ˈr̪ˠuːnʲ ɾʲə'),
    'c2-to-console': ('Comhfhurtachadh', 'ˈkʰɔ̃.əɾt̪əxəɣ'),
    'c2-to-contend': ('Cumail a-mach', 'ˈkʰumɪlʲ əˈmax'),
    'c2-to-corroborate': ('Dearbhadh', 'ˈtʃɛɾɛvəɣ'),
    'c2-to-crave': ('Sanntachadh', 'ˈsaun̪ˠt̪əxəɣ'),
    'c2-to-cringe': ('Crùbadh le nàire', 'ˈkʰɾuːpəɣ lʲə ˈn̪ˠaːɾʲə'),
    'c2-to-debunk': ('Rùscadh', 'ˈr̪ˠuːskəɣ'),
    'c2-to-decipher': ('Fuascladh', 'ˈfuəskl̪ˠəɣ'),
    'c2-to-decry': ('Càineadh', 'ˈkʰaːnʲəɣ'),
    'c2-to-deem': ('Meas', 'ˈmɛs'),
    'c2-to-defer': ('Cur dàil air', 'ˈkʰuɾ ˈt̪aːlʲ ˈɛɾʲ'),
    'c2-to-delineate': ('Comharrachadh', 'ˈkʰɔvər̪ˠəxəɣ'),
    'c2-to-denounce': ('Brathadh', 'ˈpɾa.əɣ'),
    'c2-to-deplete': ('Traoghadh', 'ˈt̪ʰɾɯː.əɣ'),
    'c2-to-deplore': ('Dìteadh', 'ˈtʃiːʰtʃəɣ'),
    'c2-to-deride': ('Magadh', 'ˈmakəɣ'),
    'c2-to-despair': ('Tuiteam an eu-dòchas', 'ˈt̪ʰuʰtʃəm ən̪ˠ ˈiəˈt̪ɔːxəs'),
    'c2-to-detain': ('Cumail an grèim', 'ˈkʰumɪlʲ əŋ ˈkɾʲeːm'),
    'c2-to-deviate': ('Claonadh', 'ˈkʰl̪ˠɯːnəɣ'),
    'c2-to-digress': ('Dol far an rathaid', 'ˈt̪ɔl̪ˠ ˈfaɾ ən̪ˠ ˈr̪ˠahɪtʃ'),
    'c2-to-disdain': ('Dìmeasachadh', 'ˈtʃiːməsəxəɣ'),
    'c2-to-dishearten': ('Mì-mhisneachadh', 'ˈmiːˈviʃnʲəxəɣ'),
    'c2-to-disillusion': ('Mì-mhealladh', 'ˈmiːˈvɛl̪ˠəɣ'),
    'c2-to-disparage': ('Cur sìos air', 'ˈkʰuɾ ˈʃiəs ˈɛɾʲ'),
    'c2-to-disperse': ('Scapadh', 'ˈskaʰpəɣ'),
    'c2-to-dissuade': ('Comhairleachadh an aghaidh', 'ˈkʰɔvɪɾʲlʲəxəɣ ən̪ˠ ˈa.i'),
    'c2-to-divulge': ('Leigeil ris', 'ˈʎekʲɪlʲ ˈr̪ˠiʃ'),
    'c2-to-dote-on': ('Toirt gaol thar tomhais do', 'ˈt̪ʰɔɾʲtʃ ˈkɯːl̪ˠ ˈhaɾ ˈt̪ʰɔvɪʃ t̪ə'),
    'c2-to-draw-a-distinction': ('Dèanamh eadar-dhealachadh', 'ˈtʃiənəv ˈɛt̪əɾˈjal̪ˠəxəɣ'),
    'c2-to-dwindle': ('Crìonadh', 'ˈkʰɾʲiənəɣ'),
    'c2-to-elude': ('Seachnadh', 'ˈʃɛxnəɣ'),
    'c2-to-emanate': ('Sruthadh', 'ˈst̪ɾu.əɣ'),
    'c2-to-embellish': ('Sceadachadh', 'ˈskʲɛt̪əxəɣ'),
    'c2-to-embolden': ('Misneachadh', 'ˈmiʃnʲəxəɣ'),
    'c2-to-encompass': ('Gabhail a-steach', 'ˈkavɪlʲ əˈʃtʃɛx'),
    'c2-to-engender': ('Gineadh', 'ˈkʲinʲəɣ'),
    'c2-to-enlighten': ('Soillseachadh', 'ˈsɔiʎʃəxəɣ'),
    'c2-to-enrapture': ('Cur air mhire', 'ˈkʰuɾ ˈɛɾʲ ˈviɾʲə'),
    'c2-to-enthrall': ('Cur fo dhraoidheachd', 'ˈkʰuɾ fə ˈɣɾɯː.əxk'),
    'c2-to-entice': ('Tàladh', 'ˈt̪ʰaːl̪ˠəɣ'),
    'c2-to-enunciate': ('Fuaimneachadh gu soilleir', 'ˈfuəmnʲəxəɣ kə ˈsɔʎɪɾʲ'),
    'c2-to-envision': ('Faicinn san inntinn', 'ˈfaʰkʲɪɲ sən̪ˠ ˈiːɲtʃɪɲ'),
    'c2-to-estrange': ('Scaradh', 'ˈskaɾəɣ'),
    'c2-to-evade': ('Teicheadh bho', 'ˈtʃʰeçəɣ ˈvɔ'),
    'c2-to-evince': ('Nochdadh', 'ˈn̪ˠɔxkəɣ'),
    'c2-to-exalt': ('Àrdachadh', 'ˈaːɾt̪əxəɣ'),
    'c2-to-exasperate': ('Leamhachadh', 'ˈʎɛvəxəɣ'),
    'c2-to-exert-pressure': ('Cuideam a chur air', 'ˈkʰutʃəm ə ˈxuɾ ˈɛɾʲ'),
    'c2-to-exhort': ('Brosnachadh', 'ˈpɾɔsnəxəɣ'),
    'c2-to-expedite': ('Luathachadh', 'ˈl̪ˠuə.əxəɣ'),
    'c2-to-expound': ('Mìneachadh', 'ˈmiːnʲəxəɣ'),
    'c2-to-extol': ('Àrd-mholadh', 'ˈaːɾt̪ˈvɔl̪ˠəɣ'),
    'c2-to-fabricate': ('Dèanamh suas', 'ˈtʃiənəv ˈsuəs'),
    'c2-to-fall-out-with': ('Dol a-mach air', 'ˈt̪ɔl̪ˠ əˈmax ˈɛɾʲ'),
    'c2-to-falter': ('Tuisleadh', 'ˈt̪ʰɯʃlʲəɣ'),
    'c2-to-fawn-over': ('Dèanamh sodal ri', 'ˈtʃiənəv ˈsɔt̪əl̪ˠ ɾʲə'),
    'c2-to-feign': ('Leigeil air', 'ˈʎekʲɪlʲ ˈɛɾʲ'),
    'c2-to-flinch': ('Clisceadh', 'ˈkʲʰlʲiʃkʲəɣ'),
    'c2-to-flourish': ('Soirbheachadh', 'ˈsɔɾʲɔvəxəɣ'),
    'c2-to-foment': ('Fadadh', 'ˈfat̪əɣ'),
    'c2-to-forfeit': ('Call', 'ˈkʰaul̪ˠ'),
    'c2-to-forgo': ('Dèanamh às aonais', 'ˈtʃiənəv ˈaːs ˈɯːnɪʃ'),
    'c2-to-fret': ('Gabhail iomagain', 'ˈkavɪlʲ ˈiməkɪnʲ'),
    'c2-to-fulfil-an-obligation': ('Dleastanas a choileanadh', 'ˈtʃlʲɛst̪anəs ə ˈxɔlʲanəɣ'),
    'c2-to-galvanize': ('Beòthachadh', 'ˈpʲɔː.əxəɣ'),
    'c2-to-garner': ('Cosnadh', 'ˈkʰɔsnəɣ'),
    'c2-to-give-rise-to': ('Adhbhrachadh', 'ˈavɾəxəɣ'),
    'c2-to-gloat': ('Dèanamh uaill à', 'ˈtʃiənəv ˈuəʎ ˈaː'),
    'c2-to-gloat-over-a-rival': ('Dèanamh gàirdeachas thar farpaiseach', 'ˈtʃiənəv ˈkaːɾʲtʃəxəs ˈhaɾ ˈfaɾpɪʃəx'),
    'c2-to-grapple': ('Gleac', 'ˈkʲlʲeʰk'),
    'c2-to-grovel': ('Snàgadh', 'ˈsnaːkəɣ'),
    'c2-to-hammer-home': ('Sparradh', 'ˈspaːr̪ˠəɣ'),
    'c2-to-harness': ('Cur gu feum', 'ˈkʰuɾ kə ˈfiəm'),
    'c2-to-heed': ('Toirt feart air', 'ˈt̪ʰɔɾʲtʃ ˈfɛɾt̪ ˈɛɾʲ'),
    'c2-to-hoard': ('Càrnadh', 'ˈkʰaːɾnəɣ'),
    'c2-to-hobnob': ('Cur eòlas air na daoine mòra', 'ˈkʰuɾ ˈjɔːl̪ˠəs ˈɛɾʲ nə ˈt̪ɯːnʲə ˈmoːɾə'),
    'c2-to-impart': ('Toirt seachad', 'ˈt̪ʰɔɾʲtʃ ˈʃɛxət̪'),
    'c2-to-implore': ('Aslachadh', 'ˈasl̪ˠəxəɣ'),
    'c2-to-incite': ('Buaireadh', 'ˈpuəɾʲəɣ'),
    'c2-to-incur-a-cost': ('Coscais a ghabhail', 'ˈkʰɔskɪʃ ə ˈɣavɪlʲ'),
    'c2-to-indulge': ('Toileachadh', 'ˈt̪ʰɔlʲəxəɣ'),
    'c2-to-infuriate': ('Cur air bhoil', 'ˈkʰuɾ ˈɛɾʲ ˈvɔlʲ'),
    'c2-to-inhibit': ('Cumail air ais', 'ˈkʰumɪlʲ ˈɛɾʲ ˈaʃ'),
    'c2-to-insinuate': ('Leth-fhacal a thilgeil', 'ˈʎehˈaʰkəl̪ˠ ə ˈhilʲikʲɪlʲ'),
    'c2-to-instill': ('Freumhachadh', 'ˈfɾʲiəvəxəɣ'),
    'c2-to-intercede': ('Eadar-ghuidhe', 'ˈɛt̪əɾˈɣu.ə'),
    'c2-to-interject': ('Cur a-steach', 'ˈkʰuɾ əˈʃtʃɛx'),
    'c2-to-intimidate': ('Cur eagal air', 'ˈkʰuɾ ˈekəl̪ˠ ˈɛɾʲ'),
    'c2-to-jeopardize': ('Cur ann an cunnart', 'ˈkʰuɾ ˈaun̪ˠ əŋ ˈɡun̪ˠəɾt̪'),
    'c2-to-languish': ('Seargadh', 'ˈʃɛɾɛkəɣ'),
    'c2-to-lend-credence-to': ('Creideas a thoirt do', 'ˈkʰɾʲetʃəs ə ˈhɔɾʲtʃ t̪ə'),
    'c2-to-long-for': ('Miannachadh', 'ˈmiən̪ˠəxəɣ'),
    'c2-to-lure': ('Mealladh', 'ˈmɛl̪ˠəɣ'),
    'c2-to-marvel': ('Gabhail iongnadh', 'ˈkavɪlʲ ˈjuːŋnəɣ'),
    'c2-to-marvel-at': ('Gabhail iongnadh ri', 'ˈkavɪlʲ ˈjuːŋnəɣ ɾʲə'),
    'c2-to-meander': ('Lùbadh', 'ˈl̪ˠuːpəɣ'),
    'c2-to-mingle': ('Meascachadh', 'ˈmɛskəxəɣ'),
    'c2-to-mollify': ('Ciùineachadh', 'ˈkʲʰuːnʲəxəɣ'),
    'c2-to-mortify': ('Nàrachadh', 'ˈn̪ˠaːɾəxəɣ'),
    'c2-to-muster': ('Tional', 'ˈtʃʰinəl̪ˠ'),
    'c2-to-nurse-a-grievance': ('Àrach gearain', 'ˈaːɾəx ˈkʲɛɾɪnʲ'),
    'c2-to-obliterate': ('Scrios', 'ˈskɾʲis'),
    'c2-to-oscillate': ('Luascadh', 'ˈl̪ˠuəskəɣ'),
    'c2-to-ostracize': ('Fògradh', 'ˈfɔːkɾəɣ'),
    'c2-to-patronize': ('Bruidhinn sìos ri', 'ˈpɾu.ɪɲ ˈʃiəs ɾʲə'),
    'c2-to-pay-tribute-to': ('Urram a thoirt do', 'ˈuːr̪ˠəm ə ˈhɔɾʲtʃ t̪ə'),
    'c2-to-permeate': ('Drùdhadh', 'ˈt̪ɾuː.əɣ'),
    'c2-to-perpetuate': ('Buanachadh', 'ˈpuənəxəɣ'),
    'c2-to-pine-for': ('Ionndrainn', 'ˈjuːn̪ˠt̪ɾɪɲ'),
    'c2-to-placate': ('Sìothachadh', 'ˈʃiə.əxəɣ'),
    'c2-to-plead-guilty': ('Aidich ciontach', 'ˈatʃɪç ˈkʲʰin̪ˠt̪əx'),
    'c2-to-plummet': ('Tuiteam gu grad', 'ˈt̪ʰuʰtʃəm kə ˈkɾat̪'),
    'c2-to-ponder': ('Beachd-smaoineachadh', 'ˈpɛxkˈsmɯːnʲəxəɣ'),
    'c2-to-pose-a-threat': ('Bhith na chunnart', 'ˈvih nə ˈxun̪ˠəɾt̪'),
    'c2-to-preach': ('Searmonachadh', 'ˈʃɛɾɛmənəxəɣ'),
    'c2-to-preempt': ('Dol air thoiseach air', 'ˈt̪ɔl̪ˠ ˈɛɾʲ ˈhɔʃəx ˈɛɾʲ'),
    'c2-to-procure': ('Solarachadh', 'ˈsɔl̪ˠəɾəxəɣ'),
    'c2-to-proliferate': ('Iomadachadh', 'ˈimət̪əxəɣ'),
    'c2-to-propel': ('Iomain', 'ˈimɪnʲ'),
    'c2-to-put-at-ease': ('Cur aig fois', 'ˈkʰuɾ ˈekʲ ˈfɔʃ'),
    'c2-to-quell': ('Mùchadh', 'ˈmuːxəɣ'),
    'c2-to-quiver': ('Crith', 'ˈkʰɾʲih'),
    'c2-to-rankle': ('Cnàmh', 'ˈkʰn̪ˠaːv'),
    'c2-to-ratify': ('Daingneachadh', 'ˈt̪aiɲnʲəxəɣ'),
    'c2-to-reach-a-verdict': ('Tighinn gu breith', 'ˈtʃʰi.ɪɲ kə ˈpɾʲeh'),
    'c2-to-rebuke': ('Trod', 'ˈt̪ʰɾɔt̪'),
    'c2-to-rebut': ('Cur an aghaidh', 'ˈkʰuɾ ən̪ˠ ˈa.i'),
    'c2-to-recant': ('Tarraing air ais', 'ˈt̪ʰaːr̪ˠɪɲkʲ ˈɛɾʲ ˈaʃ'),
    'c2-to-reconcile': ('Rèiteachadh', 'ˈr̪ˠeːʰtʃəxəɣ'),
    'c2-to-redeem': ('Ath-cheannach', 'ˈahˈçɛn̪ˠəx'),
    'c2-to-refute': ('Breugnachadh', 'ˈpɾʲiəknəxəɣ'),
    'c2-to-relish': ('Gabhail tlachd ann', 'ˈkavɪlʲ ˈt̪ʰl̪ˠaxk ˈaun̪ˠ'),
    'c2-to-renounce': ('Cur cùl ri', 'ˈkʰuɾ ˈkʰuːl̪ˠ ɾʲə'),
    'c2-to-replenish': ('Ath-lìonadh', 'ˈahˈʎiənəɣ'),
    'c2-to-reprimand': ('Toirt achmhasan', 'ˈt̪ʰɔɾʲtʃ ˈaxvəsan'),
    'c2-to-repudiate': ('Diùltadh', 'ˈtʃuːl̪ˠt̪əɣ'),
    'c2-to-rescind': ('Aischaireadh', 'ˈasxɪɾʲəɣ'),
    'c2-to-resonate': ('Ath-fhuaimneachadh', 'ˈahˈuəmnʲəxəɣ'),
    'c2-to-retaliate': ('Dìoladh', 'ˈtʃiəl̪ˠəɣ'),
    'c2-to-retort': ('Freagairt gu geur', 'ˈfɾʲekɪɾʲtʃ kə ˈkʲiəɾ'),
    'c2-to-revel-in': ('Mealtainn', 'ˈmʲal̪ˠt̪ɪɲ'),
    'c2-to-revere': ('Urramachadh', 'ˈuːr̪ˠəməxəɣ'),
    'c2-to-revoke': ('Cur an neoni', 'ˈkʰuɾ ən̪ˠ ˈɲɔnʲɪ'),
    'c2-to-rub-shoulders-with': ('Suathadh ri', 'ˈsuə.əɣ ɾʲə'),
    'c2-to-run-the-risk-of': ('Cunnart a ghabhail', 'ˈkʰun̪ˠəɾt̪ ə ˈɣavɪlʲ'),
    'c2-to-saturate': ('Làn-lìonadh', 'ˈl̪ˠaːnˈʎiənəɣ'),
    'c2-to-savor-the-moment': ('Blasadh', 'ˈpl̪ˠasəɣ'),
    'c2-to-schmooze': ('Dèanamh brìodail', 'ˈtʃiənəv ˈpɾʲiət̪ɪlʲ'),
    'c2-to-scorn': ('Dèanamh tàir air', 'ˈtʃiənəv ˈt̪ʰaːɾʲ ˈɛɾʲ'),
    'c2-to-seethe': ('Goil le fearg', 'ˈkɔlʲ lʲə ˈfɛɾɛk'),
    'c2-to-set-a-precedent': ('Ro-eisimpleir a stèidheachadh', 'ˈr̪ˠɔˈeʃɪmplʲɪɾʲ ə ˈʃtʃeː.əxəɣ'),
    'c2-to-shed-light-on': ('Solas a thilgeil air', 'ˈsɔl̪ˠəs ə ˈhilʲikʲɪlʲ ˈɛɾʲ'),
    'c2-to-shudder': ('Criothnachadh', 'ˈkʰɾʲinəxəɣ'),
    'c2-to-shun': ('Seachnadh', 'ˈʃɛxnəɣ'),
    'c2-to-smolder': ('Dubh-loscadh', 'ˈt̪uˈl̪ˠɔskəɣ'),
    'c2-to-squander': ('Struidheadh', 'ˈst̪ɾu.əɣ'),
    'c2-to-stagnate': ('Fàs marbhanta', 'ˈfaːs ˈmaɾavan̪ˠt̪ə'),
    'c2-to-stifle': ('Tachdadh', 'ˈt̪ʰaxkəɣ'),
    'c2-to-strike-a-balance': ('Cothromachadh a lorg', 'ˈkʰɔɾəməxəɣ ə ˈl̪ˠɔɾɔk'),
    'c2-to-stymie': ('Amladh', 'ˈaml̪ˠəɣ'),
    'c2-to-subside': ('Sìoladh', 'ˈʃiəl̪ˠəɣ'),
    'c2-to-succumb': ('Strìochdadh', 'ˈʃt̪ɾʲiəxkəɣ'),
    'c2-to-sulk': ('Gabhail stuirc', 'ˈkavɪlʲ ˈst̪uɾʲkʲ'),
    'c2-to-supplant': ('Cur à àite', 'ˈkʰuɾ ˈaː ˈaːʰtʃə'),
    'c2-to-surmise': ('Tuaireamachadh', 'ˈt̪ʰuəɾʲəməxəɣ'),
    'c2-to-swindle': ('Toirt car à', 'ˈt̪ʰɔɾʲtʃ ˈkʰaɾ ˈaː'),
    'c2-to-swoon': ('Fanntachadh', 'ˈfaun̪ˠt̪əxəɣ'),
    'c2-to-take-issue-with': ('Easaontachadh le', 'ˈɛsən̪ˠt̪əxəɣ lʲə'),
    'c2-to-take-precedence-over': ('Tighinn air thoiseach air', 'ˈtʃʰi.ɪɲ ˈɛɾʲ ˈhɔʃəx ˈɛɾʲ'),
    'c2-to-tarnish': ('Smalachadh', 'ˈsmal̪ˠəxəɣ'),
    'c2-to-thwart': ('Bacadh', 'ˈpaʰkəɣ'),
    'c2-to-transcend': ('Dol thairis air', 'ˈt̪ɔl̪ˠ ˈhaɾʲɪʃ ˈɛɾʲ'),
    'c2-to-treasure': ('Cumail mar ulaidh', 'ˈkʰumɪlʲ ˈmaɾ ˈul̪ˠi'),
    'c2-to-unnerve': ('Cur troimh-a-chèile', 'ˈkʰuɾ ˈt̪ʰɾɔvˈaˈçeːlʲə'),
    'c2-to-unravel': ('Rèiteachadh', 'ˈr̪ˠeːʰtʃəxəɣ'),
    'c2-to-uphold-a-principle': ('Prionnsabal a chumail suas', 'ˈpʰɾʲuːn̪ˠsəpəl̪ˠ ə ˈxumɪlʲ ˈsuəs'),
    'c2-to-usurp': ('Glacadh gu mì-laghail', 'ˈkl̪ˠaʰkəɣ kə ˈmiːˈl̪ˠa.ɪlʲ'),
    'c2-to-vanquish': ('Ceannsachadh', 'ˈkʲʰaun̪ˠsəxəɣ'),
    'c2-to-venerate': ('Onarachadh', 'ˈɔnəɾəxəɣ'),
    'c2-to-vilify': ('Mì-chliùthachadh', 'ˈmiːˈçlʲuː.əxəɣ'),
    'c2-to-vindicate': ('Fìreanachadh', 'ˈfiːɾʲanəxəɣ'),
    'c2-to-waffle-be-vague': ('Bruidhinn gun bhrìgh', 'ˈpɾu.ɪɲ kən̪ˠ ˈvɾʲiː'),
    'c2-to-wallow-in-self-pity': ('Tuiteam ann am fèin-thruas', 'ˈt̪ʰuʰtʃəm ˈaun̪ˠ əm ˈfeːnʲˈhɾuəs'),
    'c2-to-wane': ('Lùghdachadh', 'ˈl̪ˠuːt̪əxəɣ'),
    'c2-to-wield': ('Làimhseachadh', 'ˈl̪ˠãːʃəxəɣ'),
    'c2-to-wield-influence': ('Buaidh a chleachdadh', 'ˈpuəj ə ˈçlʲɛxkəɣ'),
    'c2-to-wince': ('Dèanamh gnùis-ghoirt', 'ˈtʃiənəv ˈkn̪ˠuːʃˈɣɔɾʲtʃ'),
    'c2-to-writhe': ('Toinneamh', 'ˈt̪ʰɔɲəv'),
    'c2-to-yearn': ('Miannachadh', 'ˈmiən̪ˠəxəɣ'),
    'c2-toll-booth': ('Bothan-cìse', 'ˈpɔhanˈkʲʰiːʃə'),
    'c2-tongs': ('Clobha', 'ˈkʰl̪ˠɔvə'),
    'c2-too-many-cooks-spoil-the-broth': ('Millidh cus chòcairean am brot.', 'ˈmiʎi ˈkʰus ˈxɔːʰkɪɾʲan əm ˈpɾɔʰt̪'),
    'c2-toolbox': ('Bogsa-innealan', 'ˈpɔksəˈiɲəl̪ˠan'),
    'c2-torrential': ('Tuilteach', 'ˈt̪ʰulʲtʃəx'),
    'c2-tortuous': ('Lùbach', 'ˈl̪ˠuːpəx'),
    'c2-touch-wood': ('Buin ri fiodh!', 'ˈpɯnʲ ɾʲə ˈfiɣ'),
    'c2-tow-truck': ('Carbad-slaodaidh', 'ˈkʰaɾapət̪ˈsl̪ˠɯːt̪i'),
    'c2-toxicology': ('Fios-nimhe', 'ˈfisˈɲivə'),
    'c2-trade-quota': ('Cuibhreann-malairt', 'ˈkʰuvɾʲən̪ˠˈmal̪ˠɪɾʲtʃ'),
    'c2-transcendent': ('Os cionn gach nì', 'ˈɔs ˈkʲʰuːn̪ˠ ˈkax ˈɲiː'),
    'c2-treasury-bill': ('Geall-ionmhais', 'ˈkʲaul̪ˠˈinivɪʃ'),
    'c2-triage': ('Criathradh-leòinteach', 'ˈkʰɾʲiəɾəɣˈʎɔːɲtʃəx'),
    'c2-tribunal': ('Mòd-breitheanais', 'ˈmɔːt̪ˈpɾʲehanɪʃ'),
    'c2-tributary': ('Fo-abhainn', 'ˈfɔˈa.ɪɲ'),
    'c2-trite': ('Caithte', 'ˈkʰatʃə'),
    'c2-trivet': ('Brandair', 'ˈpɾan̪ˠt̪ɪɾʲ'),
    'c2-trope': ('Nòs-sceòil', 'ˈn̪ˠɔːsˈskʲɔːlʲ'),
    'c2-truculent': ('Connspaideach', 'ˈkʰɔun̪ˠspɪtʃəx'),
    'c2-turbulence': ('Crathadh-speura', 'ˈkʰɾa.əɣˈspiəɾə'),
    'c2-turmoil': ('Buaireas', 'ˈpuəɾʲəs'),
    'c2-turncoat': ('Brathadair', 'ˈpɾa.ət̪ɪɾʲ'),
    'c2-turret': ('Turaid', 'ˈt̪ʰuɾɪtʃ'),
    'c2-twilight': ('Eadar-sholas', 'ˈɛt̪əɾˈhɔl̪ˠəs'),
    'c2-twinge': ('Guin', 'ˈkɯnʲ'),
    'c2-two-heads-are-better-than-one': ('Is fheàrr dà cheann na aon cheann.', 'ɪs ˈjaːr̪ˠ ˈt̪aː ˈçaun̪ˠ nə ˈɯːn ˈçaun̪ˠ'),
    'c2-tycoon': ('Toiceach', 'ˈt̪ʰɔʰkʲəx'),
    'c2-ultrasound': ('Dealbh-fuaime', 'ˈtʃal̪ˠavˈfuəmə'),
    'c2-umbrage': ('Oilbheum', 'ˈɔlʲɔviəm'),
    'c2-unblemished': ('Neo-thruaillte', 'ˈɲɔˈhɾuəʎtʃə'),
    'c2-unctuous': ('Ùilleach', 'ˈuːʎəx'),
    'c2-undergrowth': ('Fo-fhàs', 'ˈfɔˈaːs'),
    'c2-underpass': ('Fo-rathad', 'ˈfɔˈr̪ˠa.ət̪'),
    'c2-understated': ('Stòlda', 'ˈst̪ɔːl̪ˠt̪ə'),
    'c2-understatement': ('Lughdachadh', 'ˈl̪ˠut̪əxəɣ'),
    'c2-understudy': ('Ionadaire', 'ˈinət̪ɪɾʲə'),
    'c2-underwriter': ('Fo-scrìobhadair', 'ˈfɔˈskɾʲiəvət̪ɪɾʲ'),
    'c2-unflappable': ('Stòlda', 'ˈst̪ɔːl̪ˠt̪ə'),
    'c2-untenable': ('Do-dhìon', 'ˈt̪ɔˈjiən'),
    'c2-unwieldy': ('Mì-làimhseachail', 'ˈmiːˈl̪ˠãːʃəxɪlʲ'),
    'c2-upheaval': ('Ùpraid', 'ˈuːʰpɾɪtʃ'),
    'c2-upholsterer': ('Neach-còmhdachaidh àirneis', 'ˈɲɛxˈkʰɔ̃ːt̪əxi ˈaːɾʲnʲɪʃ'),
    'c2-uptime': ('Ùine-dùscaidh', 'ˈuːnʲəˈt̪uːski'),
    'c2-utility-room': ('Seòmar-nighe', 'ˈʃɔːməɾˈɲi.ə'),
    'c2-vanity': ('Fèin-spèis', 'ˈfeːnʲˈspeːʃ'),
    'c2-variance': ('Caochladh', 'ˈkʰɯːxl̪ˠəɣ'),
    'c2-vault-ceiling': ('Mullach boghach', 'ˈmul̪ˠəx ˈpɔ.əx'),
    'c2-ventilation-duct': ('Slighe-gaoithe', 'ˈʃlʲi.əˈkɯː.ə'),
    'c2-verbiage': ('Briathrachas', 'ˈpɾʲiəɾəxəs'),
    'c2-verbose': ('Briathrach', 'ˈpɾʲiəɾəx'),
    'c2-vernacular': ('Dùthchasach', 'ˈt̪uːxəsəx'),
    'c2-vertigo': ('Tuainealaich', 'ˈt̪ʰuənʲəl̪ˠɪç'),
    'c2-veterinarian-specialist': ('Lighiche-sprèidh', 'ˈʎi.ɪçəˈspɾʲeːj'),
    'c2-viable': ('So-dhèanta', 'ˈsɔˈjiən̪ˠt̪ə'),
    'c2-vicious-circle': ('Cearcall dìobhalach', 'ˈkʲʰɛɾkəl̪ˠ ˈtʃiəvəl̪ˠəx'),
    'c2-vigilance': ('Furachras', 'ˈfuɾəxɾəs'),
    'c2-vis-a-vis': ('An coimeas ri', 'əŋ ˈɡɔməs ɾʲə'),
    'c2-volatile': ('Caochlaideach', 'ˈkʰɯːxl̪ˠɪtʃəx'),
    'c2-volatility': ('Caochlaideachd', 'ˈkʰɯːxl̪ˠɪtʃəxk'),
    'c2-vulnerability-security': ('So-leòntachd', 'ˈsɔˈʎɔːn̪ˠt̪əxk'),
    'c2-wanton': ('Mì-chiallach', 'ˈmiːˈçiəl̪ˠəx'),
    'c2-warrant': ('Barantas', 'ˈpaɾan̪ˠt̪əs'),
    'c2-watershed': ('Uisce-dhruim', 'ˈɯʃkʲəˈɣɾuːim'),
    'c2-weary': ('Claoidhte', 'ˈkʰl̪ˠɯːjʰtʃə'),
    'c2-welder': ('Tàthadair', 'ˈt̪ʰaː.ət̪ɪɾʲ'),
    'c2-what-are-the-odds': ('Abair co-thuiteamas!', 'ˈapɪɾʲ kʰɔˈhuʰtʃəməs'),
    'c2-when-in-rome-do-as-the-romans-do': ('Nuair a bhios tu san Ròimh, dèan mar a nì na Ròmanaich.', 'ˈn̪ˠuəɾʲ ə ˈvis ˈt̪ʰu sən̪ˠ ˈr̪ˠɔːv | ˈtʃiən ˈmaɾ ə ˈɲiː nə ˈr̪ˠɔːmanɪç'),
    'c2-where-there-s-a-will-there-s-a-way': ('Far a bheil toil, tha dòigh.', 'ˈfaɾ ə ˈvelʲ ˈt̪ʰɔlʲ | ˈha ˈtoːj'),
    'c2-wherein': ('Anns a bheil', 'ˈaun̪ˠs ə ˈvelʲ'),
    'c2-whilst': ("Fhad 's a", 'ˈat̪ s ə'),
    'c2-whisk': ('Buailtear-uighean', 'ˈpuəlʲtʃəɾˈu.an'),
    'c2-whiteout': ('Cathadh', 'ˈkʰa.əɣ'),
    'c2-windfall': ('Turchairt', 'ˈt̪ʰuɾuxɪɾʲtʃ'),
    'c2-windowsill': ('Leac-uinneig', 'ˈʎeʰkˈɯɲɪkʲ'),
    'c2-windshield-wiper': ('Làmh-shiabaidh', 'ˈl̪ˠaːvˈhiəpi'),
    'c2-wingman': ('Fear-taice', 'ˈfɛɾˈt̪ʰaʰkʲə'),
    'c2-witness-stand': ('Cathair-fianais', 'ˈkʰahɪɾʲˈfiənɪʃ'),
    'c2-workaround': ('Dòigh timcheall', 'ˈtoːj ˈtʃʰimçəl̪ˠ'),
    'c2-working-capital': ('Ionmhas-làimhe', 'ˈinivəsˈl̪ˠaːvə'),
    'c2-wrench': ('Spanair', 'ˈspanɪɾʲ'),
    'c2-wry': ('Tioram', 'ˈtʃʰiɾəm'),
    'c2-yardstick': ('Slat-tomhais', 'ˈsl̪ˠaʰt̪ˈt̪ʰɔvɪʃ'),
    'c2-yawn': ('Mèaran', 'ˈmiəɾan'),
    'c2-yield-finance': ('Toradh', 'ˈt̪ʰɔɾəɣ'),
    'c2-you-can-t-have-your-cake-and-eat-it-too': ('Chan urrainn dhut do chèic a chumail agus a h-ithe.', 'xan ˈuːr̪ˠɪɲ ˈɣuʰt̪ t̪ə ˈçeːʰkʲ ə ˈxumɪlʲ ˈakəs ə ˈhi.ə'),
    'c2-you-name-it': ('Rud sam bith a thogras tu', 'ˈr̪ˠut̪ ˈsaum ˈpih ə ˈhɔkɾəs ˈt̪ʰu'),
    'c2-you-ve-got-to-be-kidding-me': ('Chan eil thu dha-rìribh!', 'xan ˈelʲ ˈu ˈɣaˈr̪ˠiːɾʲɪv'),
    'c2-zeal': ('Dìoghras', 'ˈtʃiəɾəs'),
    'c2-zeitgeist': ('Spiorad na linn', 'ˈspiɾət̪ nə ˈʎiːɲ'),
    'c2-zesty': ('Blasta', 'ˈpl̪ˠast̪ə'),
    'c2-zoology': ('Ainmh-eòlas', 'ˈanʲavˈjɔːl̪ˠəs'),
}
