# -*- coding: utf-8 -*-
# Ròdais, the Gaelic of Rodos: written by tools/import_rodais.py from the Ròdais dictionary.
# The reading line is the pronunciation in IPA.
LANG = 'gr'
WORDS = {
    'b1-a-toast': ('Deoch-slàinte', 'ˈtʃɔxˈsl̪ˠaːɲtʃə'),
    'b1-above-all': ('Os cionn gach nì', 'ˈɔs ˈkʲʰuːn̪ˠ ˈkax ˈɲiː'),
    'b1-accessory': ('Ball-sceadachaidh', 'ˈpaul̪ˠˈskʲɛt̪əxi'),
    'b1-accident': ('Tubaist', 'ˈt̪ʰupɪʃtʃ'),
    'b1-according-to': ('A rèir', 'ə ˈr̪ˠeːɾʲ'),
    'b1-acquaintance': ('Neach-eòlais', 'ˈɲɛxˈjɔːl̪ˠɪʃ'),
    'b1-adventure': ('Dàn-thuras', 'ˈt̪aːnˈhuɾəs'),
    'b1-affordable': ('Ruigsinneach', 'ˈr̪ˠɯkʲʃɪɲəx'),
    'b1-after-that': ('Às dèidh sin', 'ˈaːs ˈtʃeːj ˈʃinʲ'),
    'b1-air-conditioner': ('Anail-gheamhraidh', 'ˈanɪlʲˈjɛ̃ũɾi'),
    'b1-allowance': ('Airgead-pòca', 'ˈaɾʲakʲət̪ˈpʰɔːʰkə'),
    'b1-although': ('Ged', 'ˈkʲetʃ'),
    'b1-ambitious': ('Àrd-amasach', 'ˈaːɾt̪ˈaməsəx'),
    'b1-amused': ('Air a dhibhearsanachadh', 'ˈɛɾʲ ə ˈjivəɾsanəxəɣ'),
    'b1-animation': ('Beothachadh', 'ˈpʲɔ.əxəɣ'),
    'b1-annoyed': ('Air a leamhachadh', 'ˈɛɾʲ ə ˈʎɛvəxəɣ'),
    'b1-annoying': ('Leamh', 'ˈʎɛv'),
    'b1-annual': ('Bliadhnail', 'ˈplʲiənɪlʲ'),
    'b1-anxious': ('Iomagaineach', 'ˈiməkɪnʲəx'),
    'b1-apart-from': ('Ach a-mhàin', 'ˈax əˈvaːnʲ'),
    'b1-appetite': ('Càil', 'ˈkʰaːlʲ'),
    'b1-appliance': ('Inneal', 'ˈiɲəl̪ˠ'),
    'b1-apprenticeship': ('Preantasachd', 'ˈpʰɾʲɛn̪ˠt̪əsəxk'),
    'b1-argument-quarrel': ('Connsachadh', 'ˈkʰɔun̪ˠsəxəɣ'),
    'b1-argument-reasoning': ('Argamaid', 'ˈaɾakəmɪtʃ'),
    'b1-arrogant': ('Àrdanach', 'ˈaːɾt̪anəx'),
    'b1-article': ('Artaigil', 'ˈaɾt̪ɪkʲɪlʲ'),
    'b1-as-a-result': ('Mar thoradh air sin', 'ˈmaɾ ˈhɔɾəɣ ˈɛɾʲ ˈʃinʲ'),
    'b1-as-if': ('Mar gum', 'ˈmaɾ kəm'),
    'b1-as-long-as': ("Cho fad 's a", 'ˈxɔ ˈfat̪ s ə'),
    'b1-as-soon-as': ("Cho luath 's a", 'ˈxɔ ˈl̪ˠuə s ə'),
    'b1-assignment': ('Obair-shònraichte', 'ˈɔpɪɾʲˈhɔːnɾɪçtʃə'),
    'b1-at-ease': ('Aig fois', 'ˈekʲ ˈfɔʃ'),
    'b1-at-first': ('An toiseach', 'ən̪ˠ ˈd̪ɔʃəx'),
    'b1-attention': ('Aire', 'ˈaɾʲə'),
    'b1-attic': ('Lobhta', 'ˈl̪ˠɔvt̪ə'),
    'b1-audience': ('Luchd-èisteachd', 'ˈl̪ˠuxkˈeːʃtʃəxk'),
    'b1-author': ('Ùghdar', 'ˈuːt̪əɾ'),
    'b1-available': ('Ri fhaighinn', 'ɾʲə ˈa.ɪɲ'),
    'b1-avalanche': ('Maoim-sneachda', 'ˈmɯːmˈʃnʲɛxkə'),
    'b1-average': ('Cuibheasach', 'ˈkʰuvəsəx'),
    'b1-awful': ('Uabhasach', 'ˈuəvəsəx'),
    'b1-awkward': ('Cearbach', 'ˈkʲʰɛɾɛpəx'),
    'b1-backpack': ('Màileid-droma', 'ˈmaːlʲɪtʃˈt̪ɾɔmə'),
    'b1-balcony': ('Balcanaidh', 'ˈpal̪ˠkani'),
    'b1-bank-transfer': ('Gluasad-ionmhais', 'ˈkl̪ˠuəsət̪ˈinivɪʃ'),
    'b1-bargain': ('Bargan', 'ˈpaɾakan'),
    'b1-basement': ('Seòmar-ìochdair', 'ˈʃɔːməɾˈiəxkɪɾʲ'),
    'b1-basically': ('Gu bunaiteach', 'kə ˈpunɪʰtʃəx'),
    'b1-belief': ('Creideas', 'ˈkʰɾʲetʃəs'),
    'b1-besides': ('A thuilleadh air sin', 'ə ˈhuʎəɣ ˈɛɾʲ ˈʃinʲ'),
    'b1-best-friend': ('Caraid as fheàrr', 'ˈkʰaɾɪtʃ ˈas ˈjaːr̪ˠ'),
    'b1-bittersweet': ('Searbh-milis', 'ˈʃɛɾɛvˈmilʲɪʃ'),
    'b1-blender': ('Muileann-brochain', 'ˈmulʲən̪ˠˈpɾɔxɪnʲ'),
    'b1-blizzard': ('Cathadh-sneachda', 'ˈkʰa.əɣˈʃnʲɛxkə'),
    'b1-blunt': ('Maol', 'ˈmɯːl̪ˠ'),
    'b1-bond': ('Ceangal', 'ˈkʲʰɛŋəl̪ˠ'),
    'b1-border': ('Crìoch', 'ˈkʰɾʲiəx'),
    'b1-brave': ('Gaisceil', 'ˈkaʃkʲɪlʲ'),
    'b1-breeze': ('Oiteag', 'ˈɔʰtʃak'),
    'b1-brunch': ('Lòn-maidne', 'ˈl̪ˠɔːnˈmatʃnʲə'),
    'b1-buffet': ('Bufaidh', 'ˈpufi'),
    'b1-burnout': ('Luaithre-anama', 'ˈl̪ˠuəɾʲəˈanəmə'),
    'b1-cable': ('Sreang-theine', 'ˈst̪ɾʲauŋkˈhenʲə'),
    'b1-calories': ('Connadh-bìdh', 'ˈkʰɔn̪ˠəɣˈpiː'),
    'b1-campus': ('Àrainn', 'ˈaːɾɪɲ'),
    'b1-careful': ('Faiceallach', 'ˈfaʰkʲəl̪ˠəx'),
    'b1-careless': ('Mì-chùramach', 'ˈmiːˈxuːɾəməx'),
    'b1-cash-flow': ('Sruthan-sporain', 'ˈst̪ɾuhanˈspɔɾɪnʲ'),
    'b1-ceiling': ('Mullach', 'ˈmul̪ˠəx'),
    'b1-celebrity': ('Neach ainmeil', 'ˈɲɛx ˈanʲamɪlʲ'),
    'b1-century': ('Linn', 'ˈʎiːɲ'),
    'b1-certificate': ('Teisteanas', 'ˈtʃʰeʃtʃanəs'),
    'b1-chapter': ('Caibideil', 'ˈkʰapɪtʃɪlʲ'),
    'b1-character-story': ('Pearsa', 'ˈpʰɛɾsə'),
    'b1-charity': ('Carthannas', 'ˈkʰaɾən̪ˠəs'),
    'b1-charming': ('Taitneach', 'ˈt̪ʰaʰtʃnʲəx'),
    'b1-cheapskate': ('Spìocaire', 'ˈspiəʰkɪɾʲə'),
    'b1-checkout': ('Àite-pàighidh', 'ˈaːʰtʃəˈpʰaː.i'),
    'b1-checkup': ('Scrùdadh-slàinte', 'ˈskɾuːt̪əɣˈsl̪ˠaːɲtʃə'),
    'b1-chilly': ('Fuaraidh', 'ˈfuəɾi'),
    'b1-choice': ('Roghainn', 'ˈr̪ˠɔ.ɪɲ'),
    'b1-chopsticks': ('Maidean-ithe', 'ˈmatʃanˈi.ə'),
    'b1-citizen': ('Saoranach', 'ˈsɯːɾanəx'),
    'b1-clear-sky': ('Speur soilleir', 'ˈspiəɾ ˈsɔʎɪɾʲ'),
    'b1-climate-change': ('Caochladh-sìne', 'ˈkʰɯːxl̪ˠəɣˈʃiːnʲə'),
    'b1-close-friend': ('Dlùth-charaid', 'ˈt̪l̪ˠuːˈxaɾɪtʃ'),
    'b1-clumsy': ('Cearbach', 'ˈkʲʰɛɾɛpəx'),
    'b1-comedy': ('Comadaidh', 'ˈkʰɔmət̪i'),
    'b1-common': ('Cumanta', 'ˈkʰuman̪ˠt̪ə'),
    'b1-common-sense': ('Toinisc', 'ˈt̪ʰɔnʲɪʃkʲ'),
    'b1-community': ('Coimhearsnachd', 'ˈkʰɔvəɾsnəxk'),
    'b1-complicated': ('Iom-fhillte', 'ˈjuːmˈiːʎtʃə'),
    'b1-compliment': ('Facal molaidh', 'ˈfaʰkəl̪ˠ ˈmɔl̪ˠi'),
    'b1-confident': ('Fèin-mhisneachail', 'ˈfeːnʲˈviʃnʲəxɪlʲ'),
    'b1-confusing': ('Mì-shoilleir', 'ˈmiːˈhɔʎɪɾʲ'),
    'b1-confusion': ('Troimh-chèile', 'ˈt̪ʰɾɔvˈçeːlʲə'),
    'b1-contract': ('Cùmhnant', 'ˈkʰũːnan̪ˠt̪'),
    'b1-convenient': ('Goireasach', 'ˈkɔɾʲəsəx'),
    'b1-cost-of-living': ('Coscais-bheatha', 'ˈkʰɔskɪʃˈvɛ.ə'),
    'b1-cotton': ('Cotan', 'ˈkʰɔʰt̪an'),
    'b1-count-me-in': ('Tha mise ann', 'ˈha ˈmiʃə ˈaun̪ˠ'),
    'b1-counterfeit': ('Fuadain', 'ˈfuət̪ɪnʲ'),
    'b1-countryside': ('Dùthaich', 'ˈt̪uːhɪç'),
    'b1-coupon': ('Bileag-lùghdachaidh', 'ˈpilʲakˈl̪ˠuːt̪əxi'),
    'b1-cowardly': ('Gealtach', 'ˈkʲal̪ˠt̪əx'),
    'b1-coworker': ('Co-obraiche', 'kʰɔˈɔpɾɪçə'),
    'b1-cozy': ('Seascair', 'ˈʃɛskɪɾʲ'),
    'b1-craving': ('Miann', 'ˈmiən̪ˠ'),
    'b1-creative': ('Cruthachail', 'ˈkʰɾu.əxɪlʲ'),
    'b1-creativity': ('Cruthachalachd', 'ˈkʰɾu.əxəl̪ˠəxk'),
    'b1-crime': ('Eucoir', 'ˈiəʰkɪɾʲ'),
    'b1-criticism': ('Càineadh', 'ˈkʰaːnʲəɣ'),
    'b1-crosswalk': ('Àth-coise', 'ˈaːˈkʰɔʃə'),
    'b1-cruise': ('Turas-mara', 'ˈt̪ʰuɾəsˈmaɾə'),
    'b1-crush': ('Leannan-dìomhair', 'ˈʎɛn̪ˠanˈtʃiəvɪɾʲ'),
    'b1-cuisine': ('Còcaireachd', 'ˈkʰɔːʰkɪɾʲəxk'),
    'b1-culture': ('Dòigh-sluaigh', 'ˈtoːjˈsl̪ˠuəj'),
    'b1-curiosity': ('Feòrachas', 'ˈfʲɔːɾəxəs'),
    'b1-currency': ('Bonn-rìoghachd', 'ˈpɔun̪ˠˈr̪ˠiə.əxk'),
    'b1-curriculum': ('Curraicealam', 'ˈkʰuːr̪ˠɪʰkʲəl̪ˠəm'),
    'b1-custom-tradition': ('Nòs', 'ˈn̪ˠɔːs'),
    'b1-customer-service': ('Seirbheis luchd-ceannach', 'ˈʃeɾʲevɪʃ ˈl̪ˠuxkˈkʲʰɛn̪ˠəx'),
    'b1-daily': ('Làitheil', 'ˈl̪ˠaːhɪlʲ'),
    'b1-dawn': ('Camhanaich', 'ˈkʰavanɪç'),
    'b1-day-off': ('Latha dheth', 'ˈl̪ˠa.ə ˈjeh'),
    'b1-deal-agreement': ('Cùmhnant', 'ˈkʰũːnan̪ˠt̪'),
    'b1-decade': ('Deichead', 'ˈtʃeçət̪'),
    'b1-decent': ('Còir', 'ˈkʰɔːɾʲ'),
    'b1-decision': ('Co-dhùnadh', 'kʰɔˈɣuːnəɣ'),
    'b1-definitely': ('Gun teagamh', 'kən̪ˠ ˈtʃʰekəv'),
    'b1-delighted': ('Air leth toilichte', 'ˈɛɾʲ ˈʎeh ˈt̪ʰɔlʲɪçtʃə'),
    'b1-despite': ("A dh'aindeoin", 'ə ˈɣaɲtʃɪnʲ'),
    'b1-destination': ('Ceann-uidhe', 'ˈkʲʰaun̪ˠˈu.ə'),
    'b1-detour': ('Rathad timcheall', 'ˈr̪ˠa.ət̪ ˈtʃʰimçəl̪ˠ'),
    'b1-diet': ('Daithead', 'ˈt̪a.ət̪'),
    'b1-disappointing': ('Tàmailteach', 'ˈt̪ʰaːmɪlʲtʃəx'),
    'b1-disgusting': ('Screamhail', 'ˈskɾʲɛvɪlʲ'),
    'b1-dishwasher': ('Gille-nan-soithichean', 'ˈkʲiʎəˈn̪ˠanˈsɔhɪçan'),
    'b1-dizzy': ('Tuainealach', 'ˈt̪ʰuənʲəl̪ˠəx'),
    'b1-documentary': ('Sceul-fìrinne', 'ˈskʲiəl̪ˠˈfiːɾʲɪɲə'),
    'b1-dont-get-me-wrong': ('Na tog ceàrr mi', 'nə ˈt̪ʰɔk ˈkʲʰaːr̪ˠ ˈmi'),
    'b1-doorbell': ('Clag-dorais', 'ˈkʰl̪ˠakˈt̪ɔɾɪʃ'),
    'b1-dormitory': ('Talla-còmhnaidh', 'ˈt̪ʰal̪ˠəˈkʰɔ̃ːni'),
    'b1-doubt-noun': ('Teagamh', 'ˈtʃʰekəv'),
    'b1-down-to-earth': ('Stòlda', 'ˈst̪ɔːl̪ˠt̪ə'),
    'b1-downpour': ('Dìle', 'ˈtʃiːlʲə'),
    'b1-drama': ('Dràma', 'ˈt̪ɾaːmə'),
    'b1-drill': ('Tora-dealanaich', 'ˈt̪ʰɔɾəˈtʃal̪ˠanɪç'),
    'b1-drivers-license': ('Cead-stiùiridh', 'ˈkʲʰɛt̪ˈʃtʃuːɾʲi'),
    'b1-drizzle': ('Ciùthran', 'ˈkʲʰuːɾan'),
    'b1-drought': ('Tiormachd', 'ˈtʃʰiɾiməxk'),
    'b1-dull': ('Doilleir', 'ˈt̪ɔʎɪɾʲ'),
    'b1-dusk': ('Ciaradh', 'ˈkʲʰiəɾəɣ'),
    'b1-earthquake': ('Crith-thalmhainn', 'ˈkʰɾʲihˈhal̪ˠavɪɲ'),
    'b1-easygoing': ('Socair', 'ˈsɔʰkɪɾʲ'),
    'b1-economy': ('Rian-maoine', 'ˈr̪ˠiənˈmɯːnʲə'),
    'b1-election': ('Taghadh', 'ˈt̪ʰa.əɣ'),
    'b1-electric-car': ('Carbad-dealanaich', 'ˈkʰaɾapət̪ˈtʃal̪ˠanɪç'),
    'b1-elegant': ('Grinn', 'ˈkɾʲiːɲ'),
    'b1-embarrassing': ('Nàireach', 'ˈn̪ˠaːɾʲəx'),
    'b1-empathy': ('Co-fhaireachdainn', 'kʰɔˈaɾʲəxkɪɲ'),
    'b1-employee': ('Neach-obrach', 'ˈɲɛxˈɔpɾəx'),
    'b1-employer': ('Fastaiche', 'ˈfast̪ɪçə'),
    'b1-ending': ('Deireadh', 'ˈtʃeɾʲəɣ'),
    'b1-energy': ('Lùth', 'ˈl̪ˠuː'),
    'b1-engine': ('Cridhe-iarainn', 'ˈkʰɾʲi.əˈiəɾɪɲ'),
    'b1-envious': ('Farmadach', 'ˈfaɾamət̪əx'),
    'b1-environment': ('Crios-beatha', 'ˈkʰɾʲisˈpɛ.ə'),
    'b1-episode': ('Earrann', 'ˈjaːr̪ˠən̪ˠ'),
    'b1-era': ('Aois', 'ˈɯːʃ'),
    'b1-essay': ('Aiste', 'ˈaʃtʃə'),
    'b1-essential': ('Deatamach', 'ˈtʃɛʰt̪əməx'),
    'b1-even-though': ('Ged a', 'ˈkʲetʃ ə'),
    'b1-eventually': ('Mu dheireadh', 'mə ˈjeɾʲəɣ'),
    'b1-evidence': ('Fianais', 'ˈfiənɪʃ'),
    'b1-ex': ('Seann-leannan', 'ˈʃaun̪ˠˈʎɛn̪ˠan'),
    'b1-exchange-program': ('Iomlaid-scoilearan', 'ˈiml̪ˠɪtʃˈskɔlʲəɾan'),
    'b1-exciting': ('Togarrach', 'ˈt̪ʰɔkər̪ˠəx'),
    'b1-exhausted': ('Claoidhte', 'ˈkʰl̪ˠɯːjʰtʃə'),
    'b1-expenses': ('Coscaisean', 'ˈkʰɔskɪʃan'),
    'b1-experience': ('Eòlas', 'ˈjɔːl̪ˠəs'),
    'b1-extension-deadline': ('Sìneadh-ama', 'ˈʃiːnʲəɣˈamə'),
    'b1-fair': ('Cothromach', 'ˈkʰɔɾəməx'),
    'b1-fair-enough': ('Ceart gu leòr', 'ˈkʲʰɛɾt̪ kə ˈʎɔːɾ'),
    'b1-fame': ('Cliù', 'ˈkʲʰlʲuː'),
    'b1-fan-appliance': ('Sciath-ghaoithe', 'ˈskʲiəˈɣɯː.ə'),
    'b1-fancy': ('Spaideil', 'ˈspatʃɪlʲ'),
    'b1-fashion': ('Fasan', 'ˈfasan'),
    'b1-favor': ('Fàbhar', 'ˈfaːvəɾ'),
    'b1-fee': ('Tàille', 'ˈt̪ʰaːʎə'),
    'b1-feedback': ('Sceul-tillidh', 'ˈskʲiəl̪ˠˈtʃʰiʎi'),
    'b1-fence': ('Feansa', 'ˈfɛnsə'),
    'b1-financial': ('Ionmhasail', 'ˈinivəsɪlʲ'),
    'b1-fine-penalty': ('Càin', 'ˈkʰaːnʲ'),
    'b1-first-of-all': ('Sa chiad àite', 'sə ˈçiət̪ ˈaːʰtʃə'),
    'b1-flat': ('Còmhnard', 'ˈkʰɔ̃ːnəɾt̪'),
    'b1-flat-tire': ('Bròg-thollta', 'ˈpɾɔːkˈhɔul̪ˠt̪ə'),
    'b1-flavor': ('Blas', 'ˈpl̪ˠas'),
    'b1-flexible': ('Sùbailte', 'ˈsuːpɪlʲtʃə'),
    'b1-flood': ('Tuil', 'ˈt̪ʰulʲ'),
    'b1-for-instance': ('Mar eisimpleir', 'ˈmaɾ ˈeʃɪmplʲɪɾʲ'),
    'b1-forever': ('Gu bràth', 'kə ˈpɾaː'),
    'b1-fragile': ('Brisc', 'ˈpɾʲiʃkʲ'),
    'b1-free-shipping': ('Giùlan-saor', 'ˈkʲuːl̪ˠanˈsɯːɾ'),
    'b1-freedom': ('Saorsa', 'ˈsɯːɾsə'),
    'b1-freelance': ('Fèin-fhastaichte', 'ˈfeːnʲˈast̪ɪçtʃə'),
    'b1-freezing': ('Reòthte', 'ˈr̪ˠɔːtʃə'),
    'b1-frequently': ('Gu tric', 'kə ˈt̪ʰɾʲiʰkʲ'),
    'b1-friendship': ('Càirdeas', 'ˈkʰaːɾʲtʃəs'),
    'b1-frost': ('Reothadh', 'ˈr̪ˠɔ.əɣ'),
    'b1-fuel': ('Connadh', 'ˈkʰɔn̪ˠəɣ'),
    'b1-full-time': ('Làn-ùine', 'ˈl̪ˠaːnˈuːnʲə'),
    'b1-furious': ('Air bhoil', 'ˈɛɾʲ ˈvɔlʲ'),
    'b1-furnished': ('Àirneisichte', 'ˈaːɾʲnʲɪʃɪçtʃə'),
    'b1-garage': ('Bothan-carbaid', 'ˈpɔhanˈkʰaɾapɪtʃ'),
    'b1-generation-gap': ('Beàrn-ghlùine', 'ˈpʲaːɾnˈɣl̪ˠuːnʲə'),
    'b1-glass-material': ('Glainne', 'ˈkl̪ˠaɲə'),
    'b1-gluten-free': ('Gun-ghlaodh', 'ˈkunˈɣl̪ˠɯːɣ'),
    'b1-goal': ('Amas', 'ˈaməs'),
    'b1-government': ('Riaghaltas', 'ˈr̪ˠiə.əl̪ˠt̪əs'),
    'b1-grant': ('Tabhartas', 'ˈt̪ʰavəɾt̪əs'),
    'b1-greedy': ('Sanntach', 'ˈsaun̪ˠt̪əx'),
    'b1-group-work': ('Obair buidhne', 'ˈɔpɪɾʲ ˈpɯjnʲə'),
    'b1-grumpy': ('Greannach', 'ˈkɾʲɛn̪ˠəx'),
    'b1-guess-what': ('Tomhais dè?', 'ˈt̪ʰɔvɪʃ ˈtʃeː'),
    'b1-guilty': ('Ciontach', 'ˈkʲʰin̪ˠt̪əx'),
    'b1-hail': ('Clach-mheallain', 'ˈkʰl̪ˠaxˈvɛl̪ˠɪnʲ'),
    'b1-hair-dryer': ('Osag-fuilt', 'ˈɔsakˈfulʲtʃ'),
    'b1-hallway': ('Trannsa', 'ˈt̪ʰɾaun̪ˠsə'),
    'b1-hammer': ('Òrd', 'ˈɔːɾt̪'),
    'b1-handmade': ('Làmh-dhèanta', 'ˈl̪ˠaːvˈjiən̪ˠt̪ə'),
    'b1-headline': ('Ceann-naidheachd', 'ˈkʲʰaun̪ˠˈn̪ˠa.əxk'),
    'b1-heartbeat': ('Buille-cridhe', 'ˈpuʎəˈkʰɾʲi.ə'),
    'b1-heater': ('Teine-gun-lasair', 'ˈtʃʰenʲəˈkunˈl̪ˠasɪɾʲ'),
    'b1-heatwave': ('Tonn-teasa', 'ˈt̪ʰɔun̪ˠˈtʃʰɛsə'),
    'b1-hesitant': ('Teagmhach', 'ˈtʃʰekvəx'),
    'b1-highway': ('Mòr-rathad', 'ˈmoːɾˈr̪ˠa.ət̪'),
    'b1-homemade': ('Dèanta aig an taigh', 'ˈtʃiən̪ˠt̪ə ˈekʲ ən̪ˠ ˈd̪ɤj'),
    'b1-homesick': ('Fo chianalas', 'fə ˈçiənəl̪ˠəs'),
    'b1-hopeless': ('Eu-dòchasach', 'ˈiəˈt̪ɔːxəsəx'),
    'b1-horror': ('Uabhas', 'ˈuəvəs'),
    'b1-hostel': ('Ostail', 'ˈɔst̪ɪlʲ'),
    'b1-how-come': ('Ciamar sin?', 'ˈkʲʰimɛɾ ˈʃinʲ'),
    'b1-however': ('Ge-tà', 'ˈkʲeˈt̪ʰaː'),
    'b1-huge': ('Àibheiseach', 'ˈaːvɪʃəx'),
    'b1-humble': ('Iriosal', 'ˈiɾʲəsəl̪ˠ'),
    'b1-hurricane': ('Doineann', 'ˈt̪ɔnʲən̪ˠ'),
    'b1-i-cant-stand-it': ('Chan fhulaing mi e', 'xan ˈul̪ˠɪɲkʲ ˈmi ˈɛ'),
    'b1-i-couldnt-agree-more': ('Tha mi ag aontachadh gu tur', 'ˈha ˈmi ək ˈɯːn̪ˠt̪əxəɣ kə ˈt̪ʰuɾ'),
    'b1-i-doubt-it': ('Tha mi an teagamh', 'ˈha ˈmi ən̪ˠ ˈdʒekəv'),
    'b1-i-see-what-you-mean': ("Tha mi a' tuigsinn dè tha thu a' ciallachadh", 'ˈha ˈmi ə ˈt̪ʰɯkʲʃɪɲ ˈtʃeː ˈha ˈu ə ˈkʲʰiəl̪ˠəxəɣ'),
    'b1-ice': ('Deigh', 'ˈtʃej'),
    'b1-id-rather-not': ("B' fheàrr leam gun", 'ˈpjaːr̪ˠ ˈʎaum kən̪ˠ'),
    'b1-idea': ('Beachd', 'ˈpɛxk'),
    'b1-ill-let-you-know': ('Innsidh mi dhut', 'ˈiːɲʃi ˈmi ˈɣuʰt̪'),
    'b1-im-afraid-so': ('Tha eagal orm gu bheil', 'ˈha ˈekəl̪ˠ ˈɔɾɔm kə ˈvelʲ'),
    'b1-im-full': ('Tha mi làn', 'ˈha ˈmi ˈl̪ˠaːn'),
    'b1-imagination': ('Mac-meanmna', 'ˈmaʰkˈmɛnɛmnə'),
    'b1-immigration': ('In-imrich', 'ˈinʲˈimɾʲɪç'),
    'b1-impressive': ('Drùidhteach', 'ˈt̪ɾuːjʰtʃəx'),
    'b1-impulse-buy': ('Ceannach bras', 'ˈkʲʰɛn̪ˠəx ˈpɾas'),
    'b1-in-addition': ('A bharrachd air sin', 'ə ˈvaːr̪ˠəxk ˈɛɾʲ ˈʃinʲ'),
    'b1-in-case': ("Air eagal 's gu", 'ˈɛɾʲ ˈekəl̪ˠ s kə'),
    'b1-in-conclusion': ('Mar cho-dhùnadh', 'ˈmaɾ ˈxɔˈɣuːnəɣ'),
    'b1-in-fact': ('Gu dearbh', 'kə ˈtʃɛɾɛv'),
    'b1-in-order-to': ('Gus', 'ˈkus'),
    'b1-in-other-words': ('Ann am faclan eile', 'ˈaun̪ˠ əm ˈfaʰkl̪ˠan ˈelʲə'),
    'b1-in-short': ('Ann am beagan fhaclan', 'ˈaun̪ˠ əm ˈpekan ˈaʰkl̪ˠan'),
    'b1-in-spite-of': ("A dh'aindeoin", 'ə ˈɣaɲtʃɪnʲ'),
    'b1-in-stock': ('Ann an stoc', 'ˈaun̪ˠ ən̪ˠ ˈst̪ɔʰk'),
    'b1-in-the-long-run': ('San fhad-ùine', 'sən̪ˠ ˈat̪ˈuːnʲə'),
    'b1-income': ('Teachd-a-steach', 'ˈtʃʰɛxkˈaˈʃtʃɛx'),
    'b1-independent': ('Neo-eisimeileach', 'ˈɲɔˈeʃɪmɪlʲəx'),
    'b1-indifferent': ('Coma', 'ˈkʰɔmə'),
    'b1-inflation': ('Lobhadh-airgid', 'ˈl̪ˠɔvəɣˈaɾʲakʲɪtʃ'),
    'b1-insecure': ('Mì-chinnteach', 'ˈmiːˈçiːɲtʃəx'),
    'b1-insomnia': ('Dìth-cadail', 'ˈtʃiːˈkʰat̪ɪlʲ'),
    'b1-installment': ('Cuibhreann-pàighidh', 'ˈkʰuvɾʲən̪ˠˈpʰaː.i'),
    'b1-instead-of': ('An àite', 'ən̪ˠ ˈaːʰtʃə'),
    'b1-internship': ('Greis-obrach', 'ˈkɾʲeʃˈɔpɾəx'),
    'b1-intuition': ('Imfhios', 'ˈiməs'),
    'b1-investment': ('Tascadh', 'ˈt̪ʰaskəɣ'),
    'b1-it-slipped-my-mind': ('Chaidh e às mo cheann', 'ˈxaj ˈɛ ˈaːs mə ˈçaun̪ˠ'),
    'b1-itinerary': ('Clàr-siubhail', 'ˈkʰl̪ˠaːɾˈʃuvɪlʲ'),
    'b1-its-a-deal': ("Is e bargan a th' ann", 'ɪs ˈɛ ˈpaɾakan ə ˈhaun̪ˠ'),
    'b1-its-been-a-while': ('Tha greis ann', 'ˈha ˈkɾʲeʃ ˈaun̪ˠ'),
    'b1-its-worth-a-try': ('Is fhiach feuchainn', 'ɪs ˈiəx ˈfiəxɪɲ'),
    'b1-jet-lag': ('Suain-siubhail', 'ˈsuənʲˈʃuvɪlʲ'),
    'b1-jewelry': ('Seudraidh', 'ˈʃiət̪ɾi'),
    'b1-journey': ('Turas', 'ˈt̪ʰuɾəs'),
    'b1-justice': ('Ceartas', 'ˈkʲʰɛɾt̪əs'),
    'b1-kettle': ('Coire', 'ˈkʰɔɾʲə'),
    'b1-knowledge': ('Eòlas', 'ˈjɔːl̪ˠəs'),
    'b1-ladder': ('Fàradh', 'ˈfaːɾəɣ'),
    'b1-landmark': ('Comharra-tìre', 'ˈkʰɔvər̪ˠəˈtʃʰiːɾʲə'),
    'b1-lane': ('Sreath-rathaid', 'ˈst̪ɾʲɛhˈr̪ˠahɪtʃ'),
    'b1-law': ('Lagh', 'ˈl̪ˠa'),
    'b1-layover': ('Stad-siubhail', 'ˈst̪at̪ˈʃuvɪlʲ'),
    'b1-lease': ('Aonta-màil', 'ˈɯːn̪ˠt̪əˈmaːlʲ'),
    'b1-leather': ('Leathar', 'ˈʎɛ.əɾ'),
    'b1-lecture': ('Òraid', 'ˈɔːɾɪtʃ'),
    'b1-leftovers': ('Fuigheall', 'ˈfu.əl̪ˠ'),
    'b1-lets-play-it-by-ear': ('Chì sinn mar a thèid dhuinn', 'ˈçiː ˈʃiːɲ ˈmaɾ ə ˈheːtʃ ˈɣuːiɲ'),
    'b1-life-expectancy': ('Tomhas-saoghail', 'ˈt̪ʰɔvəsˈsɯː.ɪlʲ'),
    'b1-lifetime': ('Fad-beatha', 'ˈfat̪ˈpɛ.ə'),
    'b1-light-bulb': ('Bolgan', 'ˈpɔl̪ˠɔkan'),
    'b1-lightning': ('Dealanach', 'ˈtʃal̪ˠanəx'),
    'b1-live-broadcast': ('Beò', 'ˈpʲɔː'),
    'b1-local-person': ('Neach ionadail', 'ˈɲɛx ˈinət̪ɪlʲ'),
    'b1-logic': ('Loidsig', 'ˈl̪ˠɔtʃʃɪkʲ'),
    'b1-long-story-short': ('Gus sceul fada a dhèanamh goirid', 'ˈkus ˈskʲiəl̪ˠ ˈfat̪ə ə ˈjiənəv ˈkɔɾʲɪtʃ'),
    'b1-loss-financial': ('Call', 'ˈkʰaul̪ˠ'),
    'b1-loyal': ('Dìleas', 'ˈtʃiːlʲəs'),
    'b1-loyalty': ('Dìlseachd', 'ˈtʃiːlʲʃəxk'),
    'b1-luckily': ('Gu fortanach', 'kə ˈfɔɾt̪anəx'),
    'b1-magazine': ('Iris', 'ˈiɾʲɪʃ'),
    'b1-mailbox': ('Ciste-litreach', 'ˈkʲʰiʃtʃəˈʎiʰtʃɾʲəx'),
    'b1-major-field-of-study': ('Prìomh chuspair', 'ˈpʰɾʲiəv ˈxuspɪɾʲ'),
    'b1-material': ('Stuth', 'ˈst̪uh'),
    'b1-mature': ('Inbheach', 'ˈinʲivəx'),
    'b1-meanwhile': ('San eadar-àm', 'sən̪ˠ ˈɛt̪əɾˈaːm'),
    'b1-medium': ('Meadhanach', 'ˈmɛ.anəx'),
    'b1-membership': ('Ballrachd', 'ˈpaul̪ˠɾəxk'),
    'b1-memory-recollection': ('Cuimhne', 'ˈkʰũnʲə'),
    'b1-mental-health': ('Slàinte-inntinn', 'ˈsl̪ˠaːɲtʃəˈiːɲtʃɪɲ'),
    'b1-metal': ('Meatailt', 'ˈmɛʰt̪ɪlʲtʃ'),
    'b1-microwave': ('Àmhainn-dhìomhair', 'ˈaːvɪɲˈjiəvɪɾʲ'),
    'b1-middle-age': ('Meadhan-aois', 'ˈmɛ.anˈɯːʃ'),
    'b1-mild': ('Tlàth', 'ˈt̪ʰl̪ˠaː'),
    'b1-mild-weather': ('Tlàth', 'ˈt̪ʰl̪ˠaː'),
    'b1-milestone': ('Clach-mhìle', 'ˈkʰl̪ˠaxˈviːlʲə'),
    'b1-mindset': ('Dòigh-smaoineachaidh', 'ˈtoːjˈsmɯːnʲəxi'),
    'b1-monthly': ('Mìosail', 'ˈmiəsɪlʲ'),
    'b1-moody': ('Caochlaideach', 'ˈkʰɯːxl̪ˠɪtʃəx'),
    'b1-mortgage': ('Morgaids', 'ˈmɔɾɔkɪtʃʃ'),
    'b1-motivated': ('Brosnaichte', 'ˈpɾɔsnɪçtʃə'),
    'b1-moved-emotionally': ('Gluaiste', 'ˈkl̪ˠuəʃtʃə'),
    'b1-muggy': ('Bruthainneach', 'ˈpɾuhɪɲəx'),
    'b1-muscle': ('Fèith', 'ˈfeː'),
    'b1-my-bad': ('Mo choire', 'mə ˈxɔɾʲə'),
    'b1-nail-metal': ('Tarrang', 'ˈt̪ʰaːr̪ˠəŋk'),
    'b1-naive': ('Soineanta', 'ˈsɔnʲan̪ˠt̪ə'),
    'b1-napkin': ('Nèapraigear', 'ˈɲiəʰpɾɪkʲəɾ'),
    'b1-nausea': ('Sleogadh', 'ˈʃlʲɔkəɣ'),
    'b1-necessary': ('Riatanach', 'ˈr̪ˠiəʰt̪anəx'),
    'b1-neighborhood-watch': ('Faire nàbachd', 'ˈfaɾʲə ˈn̪ˠaːpəxk'),
    'b1-never-mind-that': ('Coma leat sin', 'ˈkʰɔmə ˈʎɛʰt̪ ˈʃinʲ'),
    'b1-nevertheless': ("A dh'aindeoin sin", 'ə ˈɣaɲtʃɪnʲ ˈʃinʲ'),
    'b1-no-worries': ('Na gabh dragh', 'nə ˈkav ˈt̪ɾa'),
    'b1-nostalgic': ('Cianalach', 'ˈkʲʰiənəl̪ˠəx'),
    'b1-not-bad': ('Chan eil dona', 'xan ˈelʲ ˈt̪ɔnə'),
    'b1-novel': ('Leabhar-sceòil', 'ˈʎɔ.əɾˈskʲɔːlʲ'),
    'b1-nowadays': ('Na làithean seo', 'nə ˈl̪ˠaːhan ˈʃɔ'),
    'b1-obvious': ('Follaiseach', 'ˈfɔl̪ˠɪʃəx'),
    'b1-obviously': ('Gu follaiseach', 'kə ˈfɔl̪ˠɪʃəx'),
    'b1-occasionally': ('Bho àm gu àm', 'ˈvɔ ˈaːm kə ˈaːm'),
    'b1-off-the-beaten-path': ('Far an rathaid mhòir', 'ˈfaɾ ən̪ˠ ˈr̪ˠahɪtʃ ˈvoːɾʲ'),
    'b1-old-age': ('Seann aois', 'ˈʃaun̪ˠ ˈɯːʃ'),
    'b1-on-the-contrary': ('Air a chaochladh', 'ˈɛɾʲ ə ˈxɯːxl̪ˠəɣ'),
    'b1-on-the-other-hand': ('Air an làimh eile', 'ˈɛɾʲ ən̪ˠ ˈl̪ˠaːv ˈelʲə'),
    'b1-organic': ('Glan-talmhainn', 'ˈkl̪ˠanˈt̪ʰal̪ˠavɪɲ'),
    'b1-otherwise': ('Air neo', 'ˈɛɾʲ ˈɲɔ'),
    'b1-out-of-stock': ('A-mach à stoc', 'əˈmax ˈaː ˈst̪ɔʰk'),
    'b1-outfit': ('Culaidh', 'ˈkʰul̪ˠi'),
    'b1-outgoing': ('Cuideachdail', 'ˈkʰutʃəxkɪlʲ'),
    'b1-outlet-socket': ('Tobar-dealanaich', 'ˈt̪ʰɔpəɾˈtʃal̪ˠanɪç'),
    'b1-overcast': ('Trom-neulach', 'ˈt̪ʰɾɔumˈɲiəl̪ˠəx'),
    'b1-overtime': ('Seach-ùine', 'ˈʃɛxˈuːnʲə'),
    'b1-overwhelmed': ('Fo uallach', 'fə ˈuəl̪ˠəx'),
    'b1-painkiller': ('Luibh-faochaidh', 'ˈl̪ˠuˈfɯːxi'),
    'b1-part-time': ('Pàirt-ùine', 'ˈpʰaːɾʲtʃˈuːnʲə'),
    'b1-partner-romantic': ('Companach', 'ˈkʰɔmpanəx'),
    'b1-pattern': ('Pàtran', 'ˈpʰaːʰt̪ɾan'),
    'b1-peace': ('Sìth', 'ˈʃiː'),
    'b1-pedestrian': ('Coisiche', 'ˈkʰɔʃɪçə'),
    'b1-pension': ('Peinnsean', 'ˈpʰeiɲʃan'),
    'b1-perfume': ('Cùbhrachd', 'ˈkʰuːvɾəxk'),
    'b1-permanent': ('Maireannach', 'ˈmaɾʲən̪ˠəx'),
    'b1-perspective': ('Sealladh', 'ˈʃɛl̪ˠəɣ'),
    'b1-picky': ('Àilgheasach', 'ˈaːlʲəsəx'),
    'b1-plagiarism': ('Mèirle-inntleachd', 'ˈmeːɾʲlʲəˈiːɲtʃlʲəxk'),
    'b1-plain-no-pattern': ('Aon-dathach', 'ˈɯːnˈt̪a.əx'),
    'b1-plastic': ('Cèir-chruaidh', 'ˈkʲʰeːɾʲˈxɾuəj'),
    'b1-platform': ('Àrd-ùrlar', 'ˈaːɾt̪ˈuːɾl̪ˠəɾ'),
    'b1-pleased': ('Toilichte', 'ˈt̪ʰɔlʲɪçtʃə'),
    'b1-plot': ('Cuilbheart', 'ˈkʰulʲuvəɾt̪'),
    'b1-plug': ('Ceann-sreinge', 'ˈkʲʰaun̪ˠˈst̪ɾʲeɲə'),
    'b1-poem': ('Dàn', 'ˈt̪aːn'),
    'b1-point-of-view': ('Sealladh pearsanta', 'ˈʃɛl̪ˠəɣ ˈpʰɛɾsan̪ˠt̪ə'),
    'b1-politics': ('Poileataics', 'ˈpʰɔlʲəʰt̪ɪʰkʲʃ'),
    'b1-pollution': ('Truailleadh', 'ˈt̪ʰɾuəʎəɣ'),
    'b1-population': ('Àireamh-shluaigh', 'ˈaːɾʲəvˈhl̪ˠuəj'),
    'b1-portion': ('Cuibhreann', 'ˈkʰuvɾʲən̪ˠ'),
    'b1-poverty': ('Bochdainn', 'ˈpɔxkɪɲ'),
    'b1-presentation': ('Taisbeanadh', 'ˈt̪ʰaʃpanəɣ'),
    'b1-probably': ('Is coltach', 'ɪs ˈkʰɔl̪ˠt̪əx'),
    'b1-professor': ('Àrd-ollamh', 'ˈaːɾt̪ˈɔl̪ˠəv'),
    'b1-profit': ('Prothaid', 'ˈpʰɾɔhɪtʃ'),
    'b1-property': ('Seilbh', 'ˈʃelʲev'),
    'b1-protein': ('Brìgh-feòla', 'ˈpɾʲiːˈfʲɔːl̪ˠə'),
    'b1-protest': ('Gearan', 'ˈkʲɛɾan'),
    'b1-punctual': ('Pongail', 'ˈpʰɔŋɪlʲ'),
    'b1-rainbow': ('Bogha-frois', 'ˈpɔ.əˈfɾɔʃ'),
    'b1-rare': ('Ainneamh', 'ˈaɲəv'),
    'b1-rarely': ('Gu h-ainneamh', 'kə ˈhaɲəv'),
    'b1-rating': ('Measadh', 'ˈmɛsəɣ'),
    'b1-real-estate-agent': ('Neach-reic thaighean', 'ˈɲɛxˈr̪ˠeʰkʲ ˈha.an'),
    'b1-reason-cause': ('Adhbhar', 'ˈavəɾ'),
    'b1-reasonable': ('Reusanta', 'ˈr̪ˠiəsan̪ˠt̪ə'),
    'b1-receipt-proof': ('Cuidhteas', 'ˈkʰɯjʰtʃəs'),
    'b1-recipe-book': ('Leabhar-reasabaidh', 'ˈʎɔ.əɾˈr̪ˠɛsəpi'),
    'b1-relaxing': ('Socrachail', 'ˈsɔʰkɾəxɪlʲ'),
    'b1-reliable': ('Earbsach', 'ˈɛɾɛpsəx'),
    'b1-remote-control': ('Slat-draoidh', 'ˈsl̪ˠaʰt̪ˈt̪ɾɯːj'),
    'b1-renewable-energy': ('Lùth-sìorraidh', 'ˈl̪ˠuːˈʃiər̪ˠi'),
    'b1-research': ('Rannsachadh', 'ˈr̪ˠaun̪ˠsəxəɣ'),
    'b1-reservation-for-dinner': ('Glèidheadh airson dìnnearach', 'ˈkʲlʲeː.əɣ ˈaɾsən ˈtʃiːɲəɾəx'),
    'b1-respect': ('Spèis', 'ˈspeːʃ'),
    'b1-responsibility': ('Uallach', 'ˈuəl̪ˠəx'),
    'b1-responsible': ('Cunntachail', 'ˈkʰuːn̪ˠt̪əxɪlʲ'),
    'b1-restless': ('Mì-fhoisneach', 'ˈmiːˈɔʃnʲəx'),
    'b1-resume': ('Cunntas-beatha', 'ˈkʰuːn̪ˠt̪əsˈpɛ.ə'),
    'b1-retirement': ('Cluaineas', 'ˈkʰl̪ˠuənʲəs'),
    'b1-return-policy': ('Riaghailt-tillidh', 'ˈr̪ˠiə.ɪlʲtʃˈtʃʰiʎi'),
    'b1-reunion': ('Ath-choinneachadh', 'ˈahˈxɔɲəxəɣ'),
    'b1-review': ('Lèirmheas', 'ˈʎeːɾʲvəs'),
    'b1-ridiculous': ('Amaideach', 'ˈamɪtʃəx'),
    'b1-rights': ('Còraichean', 'ˈkʰɔːɾɪçan'),
    'b1-rough': ('Garbh', 'ˈkaɾav'),
    'b1-roundabout': ('Fàinne-rathaid', 'ˈfaːɲəˈr̪ˠahɪtʃ'),
    'b1-router': ('Drochaid-lìn', 'ˈt̪ɾɔxɪtʃˈʎiːnʲ'),
    'b1-rumor': ('Fathann', 'ˈfa.ən̪ˠ'),
    'b1-rush-hour': ('Tràth-bruthaidh', 'ˈt̪ʰɾaːˈpɾuhi'),
    'b1-satisfying': ('Sàsachail', 'ˈsaːsəxɪlʲ'),
    'b1-savings': ('Airgead-tascaidh', 'ˈaɾʲakʲət̪ˈt̪ʰaski'),
    'b1-scenery': ('Cruth-tìre', 'ˈkʰɾuhˈtʃʰiːɾʲə'),
    'b1-screwdriver': ('Snìomhaire-tairnge', 'ˈʃnʲiəvɪɾʲəˈt̪ʰaɾʲɲə'),
    'b1-season-tv': ('Ràith-sceòil', 'ˈr̪ˠaːˈskʲɔːlʲ'),
    'b1-seatbelt': ('Crios-dìona', 'ˈkʰɾʲisˈtʃiənə'),
    'b1-second-hand': ('Ath-làimh', 'ˈahˈl̪ˠaːv'),
    'b1-security-deposit': ('Tascadh', 'ˈt̪ʰaskəɣ'),
    'b1-selfish': ('Fèineil', 'ˈfeːnʲɪlʲ'),
    'b1-seminar': ('Cearcall-foghlaim', 'ˈkʲʰɛɾkəl̪ˠˈfɔl̪ˠɪm'),
    'b1-sensible': ('Ciallach', 'ˈkʲʰiəl̪ˠəx'),
    'b1-sensitive': ('Mothachail', 'ˈmɔ.əxɪlʲ'),
    'b1-series': ('Sreath', 'ˈst̪ɾʲɛh'),
    'b1-shade': ('Dubhar', 'ˈt̪uvəɾ'),
    'b1-shadow': ('Faileas', 'ˈfalʲəs'),
    'b1-sharp': ('Geur', 'ˈkʲiəɾ'),
    'b1-shift': ('Faire-obrach', 'ˈfaɾʲəˈɔpɾəx'),
    'b1-shiny': ('Deàlrach', 'ˈtʃaːl̪ˠɾəx'),
    'b1-silk': ('Sìoda', 'ˈʃiət̪ə'),
    'b1-sincerity': ('Treibhdhireas', 'ˈt̪ʰɾʲevɪɾʲəs'),
    'b1-skill': ('Scil', 'ˈskʲilʲ'),
    'b1-slim': ('Caol', 'ˈkʰɯːl̪ˠ'),
    'b1-small-talk': ('Cabadaich', 'ˈkʰapət̪ɪç'),
    'b1-smoke-detector': ('Faire-deataich', 'ˈfaɾʲəˈtʃɛʰt̪ɪç'),
    'b1-smooth': ('Mìn', 'ˈmiːnʲ'),
    'b1-so-far-so-good': ('Math gu ruige seo', 'ˈma kə ˈr̪ˠɯkʲə ˈʃɔ'),
    'b1-so-that': ('Los gu', 'ˈl̪ˠɔs kə'),
    'b1-sore': ('Goirt', 'ˈkɔɾʲtʃ'),
    'b1-sounds-like-a-plan': ("Is e plana math a th' ann", 'ɪs ˈɛ ˈpʰl̪ˠanə ˈma ə ˈhaun̪ˠ'),
    'b1-soundtrack': ('Ceòl-deilbh', 'ˈkʲʰɔːl̪ˠˈtʃelʲev'),
    'b1-spacious': ('Farsaing', 'ˈfaɾsɪɲkʲ'),
    'b1-speaking-of-which': ("A' bruidhinn air sin", 'ə ˈpɾu.ɪɲ ˈɛɾʲ ˈʃinʲ'),
    'b1-specialty': ('Speisealachd', 'ˈspeʃəl̪ˠəxk'),
    'b1-speechless': ('Gun facal', 'kən̪ˠ ˈfaʰkəl̪ˠ'),
    'b1-speed-limit': ('Srian-siubhail', 'ˈst̪ɾʲiənˈʃuvɪlʲ'),
    'b1-spoiler': ('Brath-sceòil', 'ˈpɾahˈskʲɔːlʲ'),
    'b1-sprain': ('Scochadh', 'ˈskɔxəɣ'),
    'b1-stingy': ('Spìocach', 'ˈspiəʰkəx'),
    'b1-stranger': ('Coigreach', 'ˈkʰɔkʲɾʲəx'),
    'b1-streaming': ('Sruthadh', 'ˈst̪ɾu.əɣ'),
    'b1-street-food': ('Biadh-sràide', 'ˈpiəɣˈst̪ɾaːtʃə'),
    'b1-strike': ('Stad-oibre', 'ˈst̪at̪ˈɔpɾʲə'),
    'b1-striped': ('Stiallach', 'ˈʃtʃiəl̪ˠəx'),
    'b1-sturdy': ('Calma', 'ˈkʰal̪ˠamə'),
    'b1-style': ('Stoidhle', 'ˈst̪ɤilʲə'),
    'b1-subscription': ('Fo-scrìobhadh', 'ˈfɔˈskɾʲiəvəɣ'),
    'b1-suburb': ('Iomall-baile', 'ˈiməl̪ˠˈpalʲə'),
    'b1-sunburn': ('Loscadh-grèine', 'ˈl̪ˠɔskəɣˈkɾʲeːnʲə'),
    'b1-sunrise': ('Èirigh na grèine', 'ˈeːɾʲi nə ˈkɾʲeːnʲə'),
    'b1-sunset': ('Dol fodha na grèine', 'ˈt̪ɔl̪ˠ ˈfɔ.ə nə ˈkɾʲeːnʲə'),
    'b1-switch': ('Glas-solais', 'ˈkl̪ˠasˈsɔl̪ˠɪʃ'),
    'b1-sympathy': ('Co-fhulangas', 'kʰɔˈul̪ˠəŋəs'),
    'b1-symptom': ('Comharra', 'ˈkʰɔvər̪ˠə'),
    'b1-take-it-easy': ('Gabh air do shocair', 'ˈkav ˈɛɾʲ t̪ə ˈhɔʰkɪɾʲ'),
    'b1-tape-adhesive': ('Stiall-ghlaodhach', 'ˈʃtʃiəl̪ˠˈɣl̪ˠɯː.əx'),
    'b1-task': ('Gnìomh', 'ˈkʲɲiəv'),
    'b1-tasty': ('Blasta', 'ˈpl̪ˠast̪ə'),
    'b1-teamwork': ('Obair-scioba', 'ˈɔpɪɾʲˈskʲipə'),
    'b1-tell-me-about-it': ('Na bruidhinn rium air!', 'nə ˈpɾu.ɪɲ ˈr̪ˠum ˈɛɾʲ'),
    'b1-temporary': ('Sealach', 'ˈʃal̪ˠəx'),
    'b1-tenant': ('Gabhaltaiche', 'ˈkavəl̪ˠt̪ɪçə'),
    'b1-terrific': ('Scoinneil', 'ˈskɔɲɪlʲ'),
    'b1-terrified': ('Fo oillt', 'fə ˈɔiʎtʃ'),
    'b1-thanks-to': ('Taing do', 'ˈt̪ʰaiɲkʲ t̪ə'),
    'b1-that-reminds-me': ("Tha sin a' cur nam chuimhne", 'ˈha ˈʃinʲ ə ˈkʰuɾ nəm ˈxũnʲə'),
    'b1-the-future': ('An t-àm ri teachd', 'ən̪ˠ ˈt̪ʰaːm ɾʲə ˈtʃʰɛxk'),
    'b1-the-past': ("An t-àm a dh'fhalbh", 'ən̪ˠ ˈt̪ʰaːm ə ˈɣal̪ˠav'),
    'b1-the-present': ('An t-àm seo', 'ən̪ˠ ˈt̪ʰaːm ˈʃɔ'),
    'b1-then': ('An uair sin', 'ən̪ˠ ˈuəɾʲ ˈʃinʲ'),
    'b1-therapy': ('Leigheas-cainnte', 'ˈʎe.əsˈkʰaiɲtʃə'),
    'b1-therefore': ('Uime sin', 'ˈumə ˈʃinʲ'),
    'b1-thermostat': ('Breitheamh-blàiths', 'ˈpɾʲe.əvˈpl̪ˠaːʃ'),
    'b1-thesis': ('Tràchdas', 'ˈt̪ʰɾaːxkəs'),
    'b1-thick': ('Tiugh', 'ˈtʃʰu'),
    'b1-thought': ('Smuain', 'ˈsmuənʲ'),
    'b1-thoughtful': ('Suimeil', 'ˈsumɪlʲ'),
    'b1-thrifty': ('Glèidhteach', 'ˈkʲlʲeːjʰtʃəx'),
    'b1-thrilled': ('Air bhioran', 'ˈɛɾʲ ˈviɾan'),
    'b1-thriller': ('Sceul-crithe', 'ˈskʲiəl̪ˠˈkʰɾʲi.ə'),
    'b1-timetable': ('Clàr-ama', 'ˈkʰl̪ˠaːɾˈamə'),
    'b1-tiny': ('Bìodach', 'ˈpiət̪əx'),
    'b1-tip-advice': ('Comhairle', 'ˈkʰɔvɪɾʲlʲə'),
    'b1-tire': ('Bròg-cuibhle', 'ˈpɾɔːkˈkʰuvlʲə'),
    'b1-tiring': ('Scìtheil', 'ˈskʲiːhɪlʲ'),
    'b1-to-achieve': ('Coileanadh', 'ˈkʰɔlʲanəɣ'),
    'b1-to-adjust': ('Gleusadh', 'ˈkʲlʲiəsəɣ'),
    'b1-to-admit': ('Aideachadh', 'ˈatʃəxəɣ'),
    'b1-to-age': ('Fàs sean', 'ˈfaːs ˈʃɛn'),
    'b1-to-agree': ('Aontachadh', 'ˈɯːn̪ˠt̪əxəɣ'),
    'b1-to-apply-for-a-job': ('Cuir a-steach airson obair', 'ˈkʰuɾʲ əˈʃtʃɛx ˈaɾsən ˈɔpɪɾʲ'),
    'b1-to-appreciate': ('Cur luach air', 'ˈkʰuɾ ˈl̪ˠuəx ˈɛɾʲ'),
    'b1-to-assume': ('Gabh ris', 'ˈkav ˈr̪ˠiʃ'),
    'b1-to-attempt': ('Oidhirpeachadh', 'ˈɔ.ɪɾʲpəxəɣ'),
    'b1-to-attend': ('Frithealadh', 'ˈfɾʲi.əl̪ˠəɣ'),
    'b1-to-avoid': ('Seachnadh', 'ˈʃɛxnəɣ'),
    'b1-to-be-aware': ('Bhith mothachail', 'ˈvih ˈmɔ.əxɪlʲ'),
    'b1-to-be-broke': ('Bhith gun scillinn', 'ˈvih kən̪ˠ ˈskʲiʎɪɲ'),
    'b1-to-be-delayed': ('Bhith air dàil', 'ˈvih ˈɛɾʲ ˈt̪aːlʲ'),
    'b1-to-be-in-charge': ('Bi os cionn', 'ˈpi ˈɔs ˈkʲʰuːn̪ˠ'),
    'b1-to-beg': ('Guidhe', 'ˈku.ə'),
    'b1-to-belong': ('Buntainn', 'ˈpun̪ˠt̪ɪɲ'),
    'b1-to-bend': ('Lùbadh', 'ˈl̪ˠuːpəɣ'),
    'b1-to-betray': ('Brathadh', 'ˈpɾa.əɣ'),
    'b1-to-binge-watch': ('Craos-amharc', 'ˈkʰɾɯːsˈavəɾk'),
    'b1-to-bite': ('Bìdeadh', 'ˈpiːtʃəɣ'),
    'b1-to-blame': ('Coireachadh', 'ˈkʰɔɾʲəxəɣ'),
    'b1-to-blink': ('Priobadh', 'ˈpʰɾʲipəɣ'),
    'b1-to-bother': ('Bodraigeadh', 'ˈpɔt̪ɾɪkʲəɣ'),
    'b1-to-bow': ('Umhlachadh', 'ˈũl̪ˠəxəɣ'),
    'b1-to-brag': ('Bòstadh', 'ˈpɔːst̪əɣ'),
    'b1-to-break-down-machine': ('Briseadh sìos', 'ˈpɾʲiʃəɣ ˈʃiəs'),
    'b1-to-break-up': ('Dealachadh', 'ˈtʃal̪ˠəxəɣ'),
    'b1-to-breathe': ('Tarraing anail', 'ˈt̪ʰaːr̪ˠɪɲkʲ ˈanɪlʲ'),
    'b1-to-browse': ('Coimhead mun cuairt', 'ˈkʰɔvət̪ ˈmun ˈkʰuəɾʲtʃ'),
    'b1-to-bully': ('Dèan burraidheachd air', 'ˈtʃiən ˈpuːr̪ˠɪ.əxk ˈɛɾʲ'),
    'b1-to-care-about': ('Gabhail suim de', 'ˈkavɪlʲ ˈsuːim tʃə'),
    'b1-to-catch-the-train': ("Glacadh a' charbaid-iarainn", 'ˈkl̪ˠaʰkəɣ ə ˈxaɾapɪtʃˈiəɾɪɲ'),
    'b1-to-catch-up': ('Breith air', 'ˈpɾʲeh ˈɛɾʲ'),
    'b1-to-cheat': ('Dèanamh foill', 'ˈtʃiənəv ˈfɔiʎ'),
    'b1-to-cheer-on': ('Brosnachadh', 'ˈpɾɔsnəxəɣ'),
    'b1-to-chew': ('Cagnadh', 'ˈkʰaknəɣ'),
    'b1-to-clap': ('Bualadh bhasan', 'ˈpuəl̪ˠəɣ ˈvasan'),
    'b1-to-come-up-with': ('Smaoineachadh air', 'ˈsmɯːnʲəxəɣ ˈɛɾʲ'),
    'b1-to-comfort': ('Comhfhurtachd', 'ˈkʰɔ̃.əɾt̪əxk'),
    'b1-to-complain-about': ('Gearan mu', 'ˈkʲɛɾan mə'),
    'b1-to-concentrate': ('Cur aire air', 'ˈkʰuɾ ˈaɾʲə ˈɛɾʲ'),
    'b1-to-congratulate': ('Cuir meal-a-naidheachd air', 'ˈkʰuɾʲ ˈmʲal̪ˠˈaˈn̪ˠa.əxk ˈɛɾʲ'),
    'b1-to-consider': ('Beachdachadh', 'ˈpɛxkəxəɣ'),
    'b1-to-convince': ('Thoir a chreidsinn air', 'ˈhɔɾʲ ə ˈxɾʲetʃʃɪɲ ˈɛɾʲ'),
    'b1-to-cough': ('Casadaich', 'ˈkʰasət̪ɪç'),
    'b1-to-crawl': ('Snàgail', 'ˈsnaːkɪlʲ'),
    'b1-to-criticize': ('Lochdachadh', 'ˈl̪ˠɔxkəxəɣ'),
    'b1-to-date-someone': ('Rach a-mach le', 'ˈr̪ˠax əˈmax lʲə'),
    'b1-to-daydream': ('Bruadar na dhùisc', 'ˈpɾuət̪əɾ nə ˈɣuːʃkʲ'),
    'b1-to-deal-with': ('Dèiligeadh ri', 'ˈtʃeːlʲɪkʲəɣ ɾʲə'),
    'b1-to-decorate': ('Sceadachadh', 'ˈskʲɛt̪əxəɣ'),
    'b1-to-decrease': ('Lùghdachadh', 'ˈl̪ˠuːt̪əxəɣ'),
    'b1-to-deny': ('Àicheadh', 'ˈaːçəɣ'),
    'b1-to-depend-on': ('Crochadh air', 'ˈkʰɾɔxəɣ ˈɛɾʲ'),
    'b1-to-deserve': ('Toilltinn', 'ˈt̪ʰɔiʎtʃɪɲ'),
    'b1-to-develop': ('Leasachadh', 'ˈʎɛsəxəɣ'),
    'b1-to-disagree': ('Easaontachadh', 'ˈɛsən̪ˠt̪əxəɣ'),
    'b1-to-disappear': ('Dol à sealladh', 'ˈt̪ɔl̪ˠ ˈaː ˈʃɛl̪ˠəɣ'),
    'b1-to-donate': ('Toirt seachad', 'ˈt̪ʰɔɾʲtʃ ˈʃɛxət̪'),
    'b1-to-doubt': ('Cuir teagamh ann', 'ˈkʰuɾʲ ˈtʃʰekəv ˈaun̪ˠ'),
    'b1-to-drop-off': ('Fàgail aig', 'ˈfaːkɪlʲ ˈekʲ'),
    'b1-to-drop-out': ('Fàgail an oilthigh', 'ˈfaːkɪlʲ ən̪ˠ ˈɔlʲhi'),
    'b1-to-earn-a-living': ('Coisinn beòshlaint', 'ˈkʰɔʃɪɲ ˈpʲɔːhl̪ˠɪɲtʃ'),
    'b1-to-encourage': ('Brosnachadh', 'ˈpɾɔsnəxəɣ'),
    'b1-to-end-up': ('Tighinn gu crìch', 'ˈtʃʰi.ɪɲ kə ˈkʰɾʲiːç'),
    'b1-to-enroll': ('Clàradh', 'ˈkʰl̪ˠaːɾəɣ'),
    'b1-to-exaggerate': ('Àibheiseachadh', 'ˈaːvɪʃəxəɣ'),
    'b1-to-exchange-goods': ('Malairteachadh', 'ˈmal̪ˠɪɾʲtʃəxəɣ'),
    'b1-to-expect': ('Sùileachadh', 'ˈsuːlʲəxəɣ'),
    'b1-to-experience': ('Faigh eòlas air', 'ˈfɤj ˈjɔːl̪ˠəs ˈɛɾʲ'),
    'b1-to-explore': ('Rannsachadh', 'ˈr̪ˠaun̪ˠsəxəɣ'),
    'b1-to-fail-in-general': ('Fàilligeadh', 'ˈfaːʎɪkʲəɣ'),
    'b1-to-faint': ('Rach an laigse', 'ˈr̪ˠax ən̪ˠ ˈl̪ˠakʲʃə'),
    'b1-to-figure-out': ('Obrachadh a-mach', 'ˈɔpɾəxəɣ əˈmax'),
    'b1-to-file-a-complaint': ('Cuir a-steach gearan', 'ˈkʰuɾʲ əˈʃtʃɛx ˈkʲɛɾan'),
    'b1-to-fill-in-a-form': ('Lìonadh a-steach', 'ˈʎiənəɣ əˈʃtʃɛx'),
    'b1-to-fire-someone': ('Cuir à dreuchd', 'ˈkʰuɾʲ ˈaː ˈt̪ɾʲiəxk'),
    'b1-to-flirt': ('Dèan beadradh', 'ˈtʃiən ˈpɛt̪ɾəɣ'),
    'b1-to-focus': ('Teannadh-inntinn', 'ˈtʃʰɛn̪ˠəɣˈiːɲtʃɪɲ'),
    'b1-to-forgive': ('Mathadh', 'ˈma.əɣ'),
    'b1-to-frown': ('Cur gruaim ort', 'ˈkʰuɾ ˈkɾuəm ˈɔɾt̪'),
    'b1-to-gain-weight': ('Cuir suas cuideam', 'ˈkʰuɾʲ ˈsuəs ˈkʰutʃəm'),
    'b1-to-get-along': ('Thig air adhart le', 'ˈhikʲ ˈɛɾʲ ˈa.əɾt̪ lʲə'),
    'b1-to-get-around': ('Faigh mun cuairt', 'ˈfɤj ˈmun ˈkʰuəɾʲtʃ'),
    'b1-to-get-promoted': ('Faigh àrdachadh', 'ˈfɤj ˈaːɾt̪əxəɣ'),
    'b1-to-get-rid-of': ('Faighinn cuidhteas', 'ˈfa.ɪɲ ˈkʰɯjʰtʃəs'),
    'b1-to-get-to-know': ('Cuir eòlas air', 'ˈkʰuɾʲ ˈjɔːl̪ˠəs ˈɛɾʲ'),
    'b1-to-give-a-ride': ('Toirt-marcachd', 'ˈt̪ʰɔɾʲtʃˈmaɾkəxk'),
    'b1-to-give-up': ('Leigeil seachad', 'ˈʎekʲɪlʲ ˈʃɛxət̪'),
    'b1-to-glance': ('Toirt sùil', 'ˈt̪ʰɔɾʲtʃ ˈsuːlʲ'),
    'b1-to-gossip': ('Dèan gobaireachd', 'ˈtʃiən ˈkɔpɪɾʲəxk'),
    'b1-to-grab': ('Glacadh', 'ˈkl̪ˠaʰkəɣ'),
    'b1-to-grab-a-bite': ('Gabh greim bìdh', 'ˈkav ˈkɾʲeim ˈpiː'),
    'b1-to-greet': ('Beannachadh', 'ˈpɛn̪ˠəxəɣ'),
    'b1-to-guess': ('Tomhas', 'ˈt̪ʰɔvəs'),
    'b1-to-haggle': ('Barganachadh', 'ˈpaɾakanəxəɣ'),
    'b1-to-handle': ('Làimhseachadh', 'ˈl̪ˠãːʃəxəɣ'),
    'b1-to-hang-a-picture': ('Crochadh', 'ˈkʰɾɔxəɣ'),
    'b1-to-hang-out': ('Cuir seachad ùine còmhla', 'ˈkʰuɾʲ ˈʃɛxət̪ ˈuːnʲə ˈkʰɔ̃ːl̪ˠə'),
    'b1-to-hang-up-phone': ('Cur sìos', 'ˈkʰuɾ ˈʃiəs'),
    'b1-to-hesitate': ('Sòradh', 'ˈsɔːɾəɣ'),
    'b1-to-hitchhike': ('Siubhal-ordaig', 'ˈʃuvəl̪ˠˈɔɾt̪ɪkʲ'),
    'b1-to-ignore': ('Leig seachad', 'ˈʎekʲ ˈʃɛxət̪'),
    'b1-to-imagine': ('Mac-meanmnachadh', 'ˈmaʰkˈmɛnɛmnəxəɣ'),
    'b1-to-improve': ('Feabhsachadh', 'ˈfɛvsəxəɣ'),
    'b1-to-increase': ('Meudachadh', 'ˈmiət̪əxəɣ'),
    'b1-to-insist': ('Seas air', 'ˈʃɛs ˈɛɾʲ'),
    'b1-to-insult': ('Tàmailteachadh', 'ˈt̪ʰaːmɪlʲtʃəxəɣ'),
    'b1-to-insure': ('Àrachadh', 'ˈaːɾəxəɣ'),
    'b1-to-interrupt': ('Bris a-steach air', 'ˈpɾʲiʃ əˈʃtʃɛx ˈɛɾʲ'),
    'b1-to-introduce': ('Cuir an aithne', 'ˈkʰuɾʲ ən̪ˠ ˈanʲə'),
    'b1-to-invest': ('Cur airgead ann', 'ˈkʰuɾ ˈaɾʲakʲət̪ ˈaun̪ˠ'),
    'b1-to-involve': ('Gabhail a-steach', 'ˈkavɪlʲ əˈʃtʃɛx'),
    'b1-to-keep-in-touch': ('Cùm ann an conaltradh', 'ˈkʰuːm ˈaun̪ˠ əŋ ˈɡɔnəl̪ˠt̪ɾəɣ'),
    'b1-to-kneel': ('Dol air do ghlùinean', 'ˈt̪ɔl̪ˠ ˈɛɾʲ t̪ə ˈɣl̪ˠuːnʲan'),
    'b1-to-lean': ('Leigeil do thaic ri', 'ˈʎekʲɪlʲ t̪ə ˈhaʰkʲ ɾʲə'),
    'b1-to-lick': ('Imlich', 'ˈimlʲɪç'),
    'b1-to-lock': ('Glasadh', 'ˈkl̪ˠasəɣ'),
    'b1-to-look-after': ('Coimhead às dèidh', 'ˈkʰɔvət̪ ˈaːs ˈtʃeːj'),
    'b1-to-look-back': ('Coimhead air ais', 'ˈkʰɔvət̪ ˈɛɾʲ ˈaʃ'),
    'b1-to-look-forward-to': ('Coimhead air adhart ri', 'ˈkʰɔvət̪ ˈɛɾʲ ˈa.əɾt̪ ɾʲə'),
    'b1-to-lose-touch': ('Caill conaltradh', 'ˈkʰaiʎ ˈkʰɔnəl̪ˠt̪ɾəɣ'),
    'b1-to-lose-weight': ('Caill cuideam', 'ˈkʰaiʎ ˈkʰutʃəm'),
    'b1-to-major-in': ('Dèanamh ceum ann an', 'ˈtʃiənəv ˈkʲʰiəm ˈaun̪ˠ ən̪ˠ'),
    'b1-to-make-ends-meet': ("Cumail a' dol", 'ˈkʰumɪlʲ ə ˈt̪ɔl̪ˠ'),
    'b1-to-make-up-ones-mind': ('Cur romhad', 'ˈkʰuɾ ˈr̪ˠɔvət̪'),
    'b1-to-make-up-reconcile': ('Rèiteachadh', 'ˈr̪ˠeːʰtʃəxəɣ'),
    'b1-to-manage-to-cope': ("Dèanamh a' chùis", 'ˈtʃiənəv ə ˈxuːʃ'),
    'b1-to-match-clothes': ('Co-fhreagairt', 'kʰɔˈɾʲekɪɾʲtʃ'),
    'b1-to-meditate': ('Meòrachadh', 'ˈmʲɔːɾəxəɣ'),
    'b1-to-mention': ('Toirt iomradh air', 'ˈt̪ʰɔɾʲtʃ ˈimɾəɣ ˈɛɾʲ'),
    'b1-to-miss-the-bus': ("Call a' charbaid-shluaigh", 'ˈkʰaul̪ˠ ə ˈxaɾapɪtʃˈhl̪ˠuəj'),
    'b1-to-move-in': ('Gluais a-steach', 'ˈkl̪ˠuəʃ əˈʃtʃɛx'),
    'b1-to-move-out': ('Gluais a-mach', 'ˈkl̪ˠuəʃ əˈmax'),
    'b1-to-nag': ('Sàrachadh', 'ˈsaːɾəxəɣ'),
    'b1-to-negotiate': ('Co-rèiteachadh', 'kʰɔˈr̪ˠeːʰtʃəxəɣ'),
    'b1-to-nod': ('Cromadh do chinn', 'ˈkʰɾɔməɣ t̪ə ˈçiːɲ'),
    'b1-to-notice': ('Mothachadh', 'ˈmɔ.əxəɣ'),
    'b1-to-offend': ('Thoir oilbheum do', 'ˈhɔɾʲ ˈɔlʲɔviəm t̪ə'),
    'b1-to-offer': ('Tairgsinn', 'ˈt̪ʰaɾʲakʲʃɪɲ'),
    'b1-to-organize': ('Eagrachadh', 'ˈekɾəxəɣ'),
    'b1-to-overspend': ('Caitheamh cus', 'ˈkʰa.əv ˈkʰus'),
    'b1-to-overtake': ('Dol seachad air', 'ˈt̪ɔl̪ˠ ˈʃɛxət̪ ˈɛɾʲ'),
    'b1-to-overthink': ('Smaoineachadh cus', 'ˈsmɯːnʲəxəɣ ˈkʰus'),
    'b1-to-own': ('Sealbhachadh', 'ˈʃal̪ˠavəxəɣ'),
    'b1-to-pack': ('Pacadh', 'ˈpʰaʰkəɣ'),
    'b1-to-park': ('Parcadh', 'ˈpʰaɾkəɣ'),
    'b1-to-participate': ('Com-pàirteachadh', 'ˈkʰɔumˈpʰaːɾʲtʃəxəɣ'),
    'b1-to-pay-back': ('Pàigheadh air ais', 'ˈpʰaː.əɣ ˈɛɾʲ ˈaʃ'),
    'b1-to-perform': ('Cur an gnìomh', 'ˈkʰuɾ əŋ ˈkʲɲiəv'),
    'b1-to-persuade': ('Cuir ìmpidh air', 'ˈkʰuɾʲ ˈiːmpi ˈɛɾʲ'),
    'b1-to-pick-up-collect': ('Togail', 'ˈt̪ʰɔkɪlʲ'),
    'b1-to-plan-ahead': ('Planadh ro-làimh', 'ˈpʰl̪ˠanəɣ ˈr̪ˠɔˈl̪ˠaːv'),
    'b1-to-plug-in': ('Ceangal ris an tobar', 'ˈkʲʰɛŋəl̪ˠ ˈr̪ˠiʃ ən̪ˠ ˈd̪ɔpəɾ'),
    'b1-to-point': ('Comharrachadh', 'ˈkʰɔvər̪ˠəxəɣ'),
    'b1-to-praise': ('Moladh', 'ˈmɔl̪ˠəɣ'),
    'b1-to-predict': ('Ro-innse', 'ˈr̪ˠɔˈiːɲʃə'),
    'b1-to-pretend': ('Leigeil air', 'ˈʎekʲɪlʲ ˈɛɾʲ'),
    'b1-to-protect': ('Dìon', 'ˈtʃiən'),
    'b1-to-prove': ('Dearbhadh', 'ˈtʃɛɾɛvəɣ'),
    'b1-to-provide': ('Solarachadh', 'ˈsɔl̪ˠəɾəxəɣ'),
    'b1-to-put-off': ('Cur air dàil', 'ˈkʰuɾ ˈɛɾʲ ˈt̪aːlʲ'),
    'b1-to-quit': ('Leig dhiot', 'ˈʎekʲ ˈjiʰt̪'),
    'b1-to-quit-smoking': ('Scuir de smocadh', 'ˈskuɾʲ tʃə ˈsmɔʰkəɣ'),
    'b1-to-realize': ('Mothachadh', 'ˈmɔ.əxəɣ'),
    'b1-to-reassure': ('Cuir inntinn aig fois', 'ˈkʰuɾʲ ˈiːɲtʃɪɲ ˈekʲ ˈfɔʃ'),
    'b1-to-recognize': ('Aithneachadh', 'ˈanʲəxəɣ'),
    'b1-to-recommend': ('Moladh', 'ˈmɔl̪ˠəɣ'),
    'b1-to-recover': ('Slànachadh', 'ˈsl̪ˠaːnəxəɣ'),
    'b1-to-recycle': ('Cur-an-ath-fheum', 'ˈkʰuɾˈanˈahˈiəm'),
    'b1-to-reduce': ('Ìsleachadh', 'ˈiːʃlʲəxəɣ'),
    'b1-to-reflect-think-over': ('Meòrachadh', 'ˈmʲɔːɾəxəɣ'),
    'b1-to-refuse': ('Diùltadh', 'ˈtʃuːl̪ˠt̪əɣ'),
    'b1-to-regret': ('Gabhail aithreachais', 'ˈkavɪlʲ ˈaɾʲəxɪʃ'),
    'b1-to-reject': ('Cuir cùl ri', 'ˈkʰuɾʲ ˈkʰuːl̪ˠ ɾʲə'),
    'b1-to-rely-on': ('Earb à', 'ˈɛɾɛp ˈaː'),
    'b1-to-rely-on-someone': ('Cur earbsa ann', 'ˈkʰuɾ ˈɛɾɛpsə ˈaun̪ˠ'),
    'b1-to-remain': ('Fantainn', 'ˈfan̪ˠt̪ɪɲ'),
    'b1-to-renovate': ('Ath-nuadhachadh', 'ˈahˈn̪ˠuə.əxəɣ'),
    'b1-to-rent-a-car': ('Fastadh-carbaid', 'ˈfast̪əɣˈkʰaɾapɪtʃ'),
    'b1-to-replace': ('Cur an àite', 'ˈkʰuɾ ən̪ˠ ˈaːʰtʃə'),
    'b1-to-require': ('Bhith feumach air', 'ˈvih ˈfiəməx ˈɛɾʲ'),
    'b1-to-research': ('Dèanamh rannsachadh', 'ˈtʃiənəv ˈr̪ˠaun̪ˠsəxəɣ'),
    'b1-to-reset': ('Ath-shuidheachadh', 'ˈahˈhu.əxəɣ'),
    'b1-to-retire': ('Gabh cluaineas', 'ˈkav ˈkʰl̪ˠuənʲəs'),
    'b1-to-rub': ('Suathadh', 'ˈsuə.əɣ'),
    'b1-to-run-out-of': ('Ruith a-mach à', 'ˈr̪ˠuh əˈmax ˈaː'),
    'b1-to-scratch': ('Scròbadh', 'ˈskɾɔːpəɣ'),
    'b1-to-season': ('Blasachadh', 'ˈpl̪ˠasəxəɣ'),
    'b1-to-shake-ones-head': ('Crathadh do chinn', 'ˈkʰɾa.əɣ t̪ə ˈçiːɲ'),
    'b1-to-shiver': ('Crith', 'ˈkʰɾʲih'),
    'b1-to-show-off': ('Dèan spaglainn', 'ˈtʃiən ˈspakl̪ˠɪɲ'),
    'b1-to-show-up': ('Nochdadh', 'ˈn̪ˠɔxkəɣ'),
    'b1-to-shrug': ('Crathadh do ghuailnean', 'ˈkʰɾa.əɣ t̪ə ˈɣuəlʲnʲan'),
    'b1-to-sigh': ('Osnaich', 'ˈɔsnɪç'),
    'b1-to-sign': ('Cuir ainm ri', 'ˈkʰuɾʲ ˈanʲam ɾʲə'),
    'b1-to-skip-a-meal': ('Leig seachad biadh', 'ˈʎekʲ ˈʃɛxət̪ ˈpiəɣ'),
    'b1-to-slip': ('Sleamhnachadh', 'ˈʃlʲɛ̃ũnəxəɣ'),
    'b1-to-sneeze': ('Dèan sreothart', 'ˈtʃiən ˈst̪ɾʲɔ.əɾt̪'),
    'b1-to-solve': ('Fuascladh', 'ˈfuəskl̪ˠəɣ'),
    'b1-to-split-costs': ('Roinn nan coscaisean', 'ˈr̪ˠɔiɲ nəŋ ˈɡɔskɪʃan'),
    'b1-to-split-the-bill': ("Roinn a' bhile", 'ˈr̪ˠɔiɲ ə ˈvilʲə'),
    'b1-to-squeeze': ('Fàscadh', 'ˈfaːskəɣ'),
    'b1-to-stare': ('Spleuchdadh', 'ˈsplʲiəxkəɣ'),
    'b1-to-stretch': ('Sìneadh', 'ˈʃiːnʲəɣ'),
    'b1-to-struggle': ('Strì', 'ˈʃt̪ɾʲiː'),
    'b1-to-study-abroad': ('Ionnsachadh thall thairis', 'ˈjuːn̪ˠsəxəɣ ˈhaul̪ˠ ˈhaɾʲɪʃ'),
    'b1-to-stumble': ('Tuisleadh', 'ˈt̪ʰɯʃlʲəɣ'),
    'b1-to-submit': ('Cur a-steach', 'ˈkʰuɾ əˈʃtʃɛx'),
    'b1-to-subscribe': ('Clàraich airson', 'ˈkʰl̪ˠaːɾɪç ˈaɾsən'),
    'b1-to-succeed': ('Soirbheachadh', 'ˈsɔɾʲɔvəxəɣ'),
    'b1-to-suffer': ('Fulang', 'ˈful̪ˠəŋk'),
    'b1-to-suit-look-good-on': ('Tighinn do', 'ˈtʃʰi.ɪɲ t̪ə'),
    'b1-to-support': ('Cuir taic ri', 'ˈkʰuɾʲ ˈt̪ʰaʰkʲ ɾʲə'),
    'b1-to-survive': ('Mairsinn beò', 'ˈmaɾʲʃɪɲ ˈpʲɔː'),
    'b1-to-swallow': ('Slugadh', 'ˈsl̪ˠukəɣ'),
    'b1-to-sweat': ('Fallasachadh', 'ˈfal̪ˠəsəxəɣ'),
    'b1-to-take-a-photo': ('Tog dealbh', 'ˈt̪ʰɔk ˈtʃal̪ˠav'),
    'b1-to-take-part': ('Gabhail pàirt', 'ˈkavɪlʲ ˈpʰaːɾʲtʃ'),
    'b1-to-tease': ('Tarraing à', 'ˈt̪ʰaːr̪ˠɪɲkʲ ˈaː'),
    'b1-to-threaten': ('Maoidheadh', 'ˈmɯː.əɣ'),
    'b1-to-tiptoe': ('Coiseachd air corra-biod', 'ˈkʰɔʃəxk ˈɛɾʲ ˈkʰɔːr̪ˠəˈpit̪'),
    'b1-to-tow': ('Slaodadh', 'ˈsl̪ˠɯːt̪əɣ'),
    'b1-to-track-a-package': ('Lorg', 'ˈl̪ˠɔɾɔk'),
    'b1-to-train-someone': ('Oideachadh', 'ˈɔtʃəxəɣ'),
    'b1-to-transfer-change-lines': ('Atharrachadh loidhne', 'ˈa.ər̪ˠəxəɣ ˈl̪ˠɤinʲə'),
    'b1-to-treat-pay-for-someone': ('Pàigh do chuideigin', 'ˈpʰaːj t̪ə ˈxutʃɪkʲɪnʲ'),
    'b1-to-trip-over': ('Tuiteam thairis air', 'ˈt̪ʰuʰtʃəm ˈhaɾʲɪʃ ˈɛɾʲ'),
    'b1-to-trust': ('Cuir earbsa ann', 'ˈkʰuɾʲ ˈɛɾɛpsə ˈaun̪ˠ'),
    'b1-to-turn-an-age': ('Ruigsinn', 'ˈr̪ˠɯkʲʃɪɲ'),
    'b1-to-turn-out': ('Tionndadh a-mach', 'ˈtʃʰuːn̪ˠt̪əɣ əˈmax'),
    'b1-to-unplug': ('Fuascladh on tobar', 'ˈfuəskl̪ˠəɣ ˈɔn ˈt̪ʰɔpəɾ'),
    'b1-to-vote': ('Bhòtadh', 'ˈvɔːʰt̪əɣ'),
    'b1-to-wander': ('Falbh air seachran', 'ˈfal̪ˠav ˈɛɾʲ ˈʃɛxɾan'),
    'b1-to-warm-up': ('Blàthachadh', 'ˈpl̪ˠaː.əxəɣ'),
    'b1-to-warn': ('Toirt rabhaidh', 'ˈt̪ʰɔɾʲtʃ ˈr̪ˠavi'),
    'b1-to-waste-money': ('Ana-caitheamh airgid', 'ˈanəˈkʰa.əv ˈaɾʲakʲɪtʃ'),
    'b1-to-wave': ('Smèideadh', 'ˈsmeːtʃəɣ'),
    'b1-to-welcome': ('Cuir fàilte air', 'ˈkʰuɾʲ ˈfaːlʲtʃə ˈɛɾʲ'),
    'b1-to-wink': ('Caogadh', 'ˈkʰɯːkəɣ'),
    'b1-to-wonder': ('Faighnich dhìot fhèin', 'ˈfɤjnʲɪç ˈjiəʰt̪ ˈheːnʲ'),
    'b1-to-work-out': ('Dèan eacarsaich', 'ˈtʃiən ˈeʰkəɾsɪç'),
    'b1-to-yawn': ('Mèaranaich', 'ˈmiəɾanɪç'),
    'b1-toaster': ('Teallach-arain', 'ˈtʃʰɛl̪ˠəxˈaɾɪnʲ'),
    'b1-toll': ('Cìs-rathaid', 'ˈkʲʰiːʃˈr̪ˠahɪtʃ'),
    'b1-tool': ('Ball-acainn', 'ˈpaul̪ˠˈaʰkɪɲ'),
    'b1-tornado': ('Iomghaoth', 'ˈimə'),
    'b1-touched': ('Drùidhte', 'ˈt̪ɾuːjʰtʃə'),
    'b1-tourist-trap': ('Ribe-choigreach', 'ˈr̪ˠipəˈxɔkʲɾʲəx'),
    'b1-traffic-jam': ('Tachdadh-rathaid', 'ˈt̪ʰaxkəɣˈr̪ˠahɪtʃ'),
    'b1-trailer': ('Blas-deilbh', 'ˈpl̪ˠasˈtʃelʲev'),
    'b1-transcript': ('Clàr-comharran', 'ˈkʰl̪ˠaːɾˈkʰɔvər̪ˠan'),
    'b1-transparent': ('Trìd-shoilleir', 'ˈt̪ʰɾʲiːtʃˈhɔʎɪɾʲ'),
    'b1-trend': ('Gluasad', 'ˈkl̪ˠuəsət̪'),
    'b1-trust': ('Earbsa', 'ˈɛɾɛpsə'),
    'b1-tuition': ('Cìsean-teagaisc', 'ˈkʲʰiːʃanˈtʃʰekɪʃkʲ'),
    'b1-tutor': ('Oide', 'ˈɔtʃə'),
    'b1-typical': ('Àbhaisteach', 'ˈaːvɪʃtʃəx'),
    'b1-uneasy': ('Anfhoiseil', 'ˈanɪʃɪlʲ'),
    'b1-unemployment': ('Cion-cosnaidh', 'ˈkʲʰinˈkʰɔsni'),
    'b1-unfair': ('Mì-chothromach', 'ˈmiːˈxɔɾəməx'),
    'b1-unforgettable': ('Do-dhìochuimhnichte', 'ˈt̪ɔˈjiəxɪ̃nʲɪçtʃə'),
    'b1-unfortunately': ('Gu mì-fhortanach', 'kə ˈmiːˈɔɾt̪anəx'),
    'b1-unless': ('Mura', 'muɾə'),
    'b1-unusual': ('Neo-àbhaisteach', 'ˈɲɔˈaːvɪʃtʃəx'),
    'b1-upset': ('Troimh-a-chèile', 'ˈt̪ʰɾɔvˈaˈçeːlʲə'),
    'b1-useful': ('Feumail', 'ˈfiəmɪlʲ'),
    'b1-useless': ('Gun fheum', 'kən̪ˠ ˈiəm'),
    'b1-utilities': ('Goireasan', 'ˈkɔɾʲəsan'),
    'b1-vacation': ('Saor-làithean', 'ˈsɯːɾˈl̪ˠaːhan'),
    'b1-vaccine': ('Banachdach', 'ˈpanəxkəx'),
    'b1-valuable': ('Luachmhor', 'ˈl̪ˠuəxvəɾ'),
    'b1-value-for-money': ('Luach airgid', 'ˈl̪ˠuəx ˈaɾʲakʲɪtʃ'),
    'b1-vegan': ('Feòil-sheachnach', 'ˈfʲɔːlʲˈhɛxnəx'),
    'b1-view': ('Sealladh', 'ˈʃɛl̪ˠəɣ'),
    'b1-visa': ('Cead-crìche', 'ˈkʲʰɛt̪ˈkʰɾʲiːçə'),
    'b1-volcano': ('Beinn-theine', 'ˈpeiɲˈhenʲə'),
    'b1-volunteer': ('Saor-thoileach', 'ˈsɯːɾˈhɔlʲəx'),
    'b1-war': ('Cogadh', 'ˈkʰɔkəɣ'),
    'b1-warranty': ('Barantas', 'ˈpaɾan̪ˠt̪əs'),
    'b1-waste-garbage': ('Scudal', 'ˈskut̪əl̪ˠ'),
    'b1-wealth': ('Beartas', 'ˈpɛɾt̪əs'),
    'b1-wealthy': ('Beartach', 'ˈpɛɾt̪əx'),
    'b1-weekly': ('Seachdaineil', 'ˈʃɛxkɪnʲɪlʲ'),
    'b1-weird': ('Neònach', 'ˈɲɔːnəx'),
    'b1-wellbeing': ('Sunnd', 'ˈsuːn̪ˠt̪'),
    'b1-whats-up': ('Dè tha dol?', 'ˈtʃeː ˈha ˈt̪ɔl̪ˠ'),
    'b1-whereas': ("Fhad 's a", 'ˈat̪ s ə'),
    'b1-wildfire': ('Teine fiadhaich', 'ˈtʃʰenʲə ˈfiə.ɪç'),
    'b1-wisdom': ('Gliocas', 'ˈkʲlʲiʰkəs'),
    'b1-wise': ('Glic', 'ˈkʲlʲiʰkʲ'),
    'b1-wooden': ('Fiodha', 'ˈfi.ə'),
    'b1-wool': ('Clòimh', 'ˈkʰl̪ˠɔːv'),
    'b1-workload': ('Eallach obrach', 'ˈɛl̪ˠəx ˈɔpɾəx'),
    'b1-workshop': ('Bùth-obrach', 'ˈpuːˈɔpɾəx'),
    'b1-worth-it': ('Is fhiach e', 'ɪs ˈiəx ˈɛ'),
    'b1-yard': ('Lios', 'ˈʎis'),
    'b1-you-know-what-i-mean': ("A bheil fios agad dè tha mi a' ciallachadh?", 'ə ˈvelʲ ˈfis ˈakət̪ ˈtʃeː ˈha ˈmi ə ˈkʲʰiəl̪ˠəxəɣ'),
    'b1-youth': ('Òige', 'ˈɔːkʲə'),
}
