# -*- coding: utf-8 -*-
LANG = 'tr'
WORDS = {
    'c1-broadcast': ('Yayın', None),
    'c1-coverage': ('Haber kapsamı', None),
    'c1-correspondent': ('Muhabir', None),
    'c1-anchor-news': ('Spiker (haber)', None),
    'c1-editorial': ('Başyazı', None),
    'c1-slant-bias': ('Yanlılık (bakış açısı)', None),
    'c1-to-leak': ('Sızdırmak', None),
    'c1-source-journalism': ('Kaynak (gazetecilik)', None),
    'c1-whistleblower': ('Muhbir (ihbarcı)', None),
    'c1-censorship': ('Sansür', None),
    'c1-propaganda': ('Propaganda', None),
    'c1-misinformation': ('Yanlış bilgi', None),
    'c1-fact-check': ('Bilgi doğrulama', None),
    'c1-viral': ('Viral', None),
    'c1-clickbait': ('Tık tuzağı', None),
    'c1-tabloid': ('Magazin gazetesi', None),
    'c1-press-conference': ('Basın toplantısı', None),
    'c1-press-release': ('Basın bülteni', None),
    'c1-exclusive-story': ('Özel haber', None),
    'c1-breaking-news': ('Son dakika haberi', None),
    'c1-viewership': ('İzleyici sayısı', None),
    'c1-subscriber': ('Abone', None),
    'c1-paywall': ('Ücret duvarı', None),
    'c1-influencer': ('Fenomen (influencer)', None),
    'c1-to-trend': ('Gündem olmak', None),
    'c1-hashtag': ('Hashtag (etiket)', None),
    'c1-op-ed': ('Köşe yazısı', None),
    'c1-byline': ('Yazar imzası', None),
    'c1-segment-tv': ('Bölüm (TV)', None),
    'c1-airtime': ('Yayın süresi', None),
    'c1-methodology': ('Metodoloji', None),
    'c1-empirical': ('Ampirik', None),
    'c1-qualitative': ('Nitel', None),
    'c1-quantitative': ('Nicel', None),
    'c1-variable': ('Değişken', None),
    'c1-correlation': ('Korelasyon', None),
    'c1-causation': ('Nedensellik', None),
    'c1-sample-study': ('Örneklem', None),
    'c1-peer-review': ('Hakem değerlendirmesi', None),
    'c1-citation': ('Alıntı (kaynak gösterme)', None),
    'c1-abstract-summary': ('Özet', None),
    'c1-dissertation': ('Doktora tezi', None),
    'c1-scholar': ('Akademisyen', None),
    'c1-discipline-field': ('Disiplin (alan)', None),
    'c1-paradigm': ('Paradigma', None),
    'c1-phenomenon': ('Olgu (fenomen)', None),
    'c1-premise': ('Öncül (önerme)', None),
    'c1-inference': ('Çıkarım', None),
    'c1-to-infer': ('Çıkarımda bulunmak', None),
    'c1-to-deduce': ('Tümdengelimle çıkarmak', None),
    'c1-rigorous': ('Titiz (sıkı)', None),
    'c1-nuanced': ('İnce ayrımlı', None),
    'c1-to-synthesize': ('Sentezlemek', None),
    'c1-critique': ('Eleştiri (analiz)', None),
    'c1-discourse': ('Söylem', None),
    'c1-hierarchy': ('Hiyerarşi', None),
    'c1-paradox': ('Paradoks', None),
    'c1-theoretical': ('Kuramsal', None),
    'c1-findings': ('Bulgular', None),
    'c1-assumption': ('Varsayım', None),
    'c1-to-back-up-support': ('Desteklemek', None),
    'c1-to-bring-up-mention': ('Söz açmak', None),
    'c1-to-call-off': ('İptal etmek', None),
    'c1-to-carry-on': ('Devam etmek', None),
    'c1-to-check-out-look-at': ('Göz atmak', None),
    'c1-to-come-across': ('Rastlamak', None),
    'c1-to-cut-down-on': ('Azaltmak (tüketimi)', None),
    'c1-to-do-without': ('Vazgeçmek (idare etmek)', None),
    'c1-to-fall-apart': ('Dağılmak (çökmek)', None),
    'c1-to-fall-behind': ('Geride kalmak', None),
    'c1-to-get-away-with': ('Paçayı sıyırmak', None),
    'c1-to-get-by': ('İdare etmek (geçinmek)', None),
    'c1-to-get-over': ('Atlatmak', None),
    'c1-to-give-in': ('Boyun eğmek', None),
    'c1-to-go-through-experience': ('Yaşamak (zor bir dönemi)', None),
    'c1-to-hold-on': ('Beklemek (dayanmak)', None),
    'c1-to-keep-up-with': ('Ayak uydurmak', None),
    'c1-to-let-down': ('Hayal kırıklığına uğratmak', None),
    'c1-to-look-into': ('Araştırmak (incelemek)', None),
    'c1-to-look-up-to': ('Örnek almak', None),
    'c1-to-make-up-for': ('Telafi etmek', None),
    'c1-to-pass-out': ('Bayılmak', None),
    'c1-to-point-out': ('Belirtmek (işaret etmek)', None),
    'c1-to-put-up-with': ('Katlanmak (tahammül etmek)', None),
    'c1-to-run-into': ('Rastlaşmak', None),
    'c1-to-set-up': ('Kurmak', None),
    'c1-to-sort-out': ('Halletmek', None),
    'c1-to-stand-for': ('Anlamına gelmek (temsil etmek)', None),
    'c1-to-take-after': ('Benzemek (birine çekmek)', None),
    'c1-to-take-over': ('Devralmak', None),
    'c1-to-turn-down': ('Reddetmek', None),
    'c1-to-turn-up': ('Çıkagelmek', None),
    'c1-to-work-out-resolve': ('Çözülmek (iyi sonuçlanmak)', None),
    'c1-to-wear-off': ('Etkisi geçmek', None),
    'c1-to-wind-up-end-up': ('Sonunda bir durumda bulmak', None),
    'c1-to-break-off': ('Koparmak (ilişkiyi kesmek)', None),
    'c1-to-brush-up-on': ('Tazelemek (bilgiyi)', None),
    'c1-to-catch-on': ('Yaygınlaşmak (moda olmak)', None),
    'c1-to-come-down-with': ('Yakalanmak (hastalığa)', None),
    'c1-to-crack-down-on': ('Sıkı önlem almak', None),
    'c1-to-dwell-on': ('Üzerinde durmak (takılıp kalmak)', None),
    'c1-to-fall-through': ('Suya düşmek', None),
    'c1-to-get-across': ('Anlatabilmek (fikri iletmek)', None),
    'c1-to-hold-back': ('Kendini tutmak', None),
    'c1-to-iron-out': ('Pürüzleri gidermek', None),
    'c1-to-live-up-to': ('Beklentiyi karşılamak', None),
    'c1-to-narrow-down': ('Daraltmak (seçenekleri)', None),
    'c1-to-opt-out': ('Vazgeçmek (katılmamayı seçmek)', None),
    'c1-to-phase-out': ('Kademeli olarak kaldırmak', None),
    'c1-to-pull-off': ('Başarmak (zorlu bir işi)', None),
    'c1-to-rule-out': ('Olasılık dışı bırakmak', None),
    'c1-to-settle-for': ('Yetinmek', None),
    'c1-to-stick-to': ('Sadık kalmak', None),
    'c1-to-take-on-a-task': ('Üstlenmek', None),
    'c1-to-touch-on': ('Değinmek', None),
    'c1-to-weigh-up': ('Tartmak (artı ve eksileri)', None),
    'c1-to-wrap-up': ('Sonuçlandırmak', None),
    'c1-to-zero-in-on': ('Odaklanmak', None),
    'c1-to-fend-off': ('Savuşturmak', None),
    'c1-to-stem-from': ('Kaynaklanmak', None),
    'c1-awesome': ('Harika', None),
    'c1-gross': ('İğrenç', None),
    'c1-lame': ('Berbat (sıkıcı)', None),
    'c1-cheesy': ('Yapmacık (bayat)', None),
    'c1-to-chill': ('Takılmak (rahatlamak)', None),
    'c1-dude': ('Dostum', None),
    'c1-to-ditch': ('Ekmek (terk etmek)', None),
    'c1-to-bail-leave': ('Sıvışmak', None),
    'c1-to-crash-sleep': ('Yıkılıp uyumak', None),
    'c1-to-freak-out': ('Panik yapmak', None),
    'c1-to-nail-it': ('On numara yapmak', None),
    'c1-to-screw-up': ('İşi batırmak', None),
    'c1-a-bummer': ('Hayal kırıklığı (kötü haber)', None),
    'c1-no-biggie': ('Önemli değil', None),
    'c1-to-be-into': ('Meraklısı olmak', None),
    'c1-hooked': ('Bağımlı (tutkun)', None),
    'c1-hype': ('Yaygara (hype)', None),
    'c1-sketchy': ('Şüpheli', None),
    'c1-legit': ('Gerçek (güvenilir)', None),
    'c1-a-rip-off': ('Kazık (dolandırıcılık)', None),
    'c1-to-ghost': ('Habersiz kesip atmak', None),
    'c1-cringe': ('Tuhaf utanç', None),
    'c1-to-wing-it': ('Doğaçlama yapmak', None),
    'c1-to-zone-out': ('Dalıp gitmek', None),
    'c1-to-kick-back': ('Keyfine bakmak', None),
    'c1-for-real': ('Cidden', None),
    'c1-buddy': ('Arkadaş (dostum)', None),
    'c1-to-hit-the-road': ('Yola koyulmak', None),
    'c1-to-grab-get': ('Kapmak', None),
    'c1-sweet-great': ('Süper', None),
    'c1-eloquent': ('Belagatli', None),
    'c1-poignant': ('Dokunaklı', None),
    'c1-vivid': ('Canlı (net)', None),
    'c1-lucid': ('Berrak (açık zihinli)', None),
    'c1-sublime': ('Yüce (muhteşem)', None),
    'c1-exquisite': ('Enfes (seçkin)', None),
    'c1-serene': ('Dingin', None),
    'c1-somber': ('Kasvetli', None),
    'c1-bleak': ('İç karartıcı', None),
    'c1-grim': ('Vahim (acımasız)', None),
    'c1-austere': ('Sade (çileci)', None),
    'c1-opulent': ('Görkemli (zengin)', None),
    'c1-lavish': ('Şatafatlı', None),
    'c1-meager': ('Kıt (az)', None),
    'c1-scarce': ('Nadir bulunur', None),
    'c1-abundant': ('Bol', None),
    'c1-pristine': ('Bakir (el değmemiş)', None),
    'c1-dilapidated': ('Harap (yıkık dökük)', None),
    'c1-quaint': ('Şirin (eski usul)', None),
    'c1-picturesque': ('Pitoresk', None),
    'c1-ominous': ('Uğursuz', None),
    'c1-eerie': ('Ürkütücü (tekinsiz)', None),
    'c1-uncanny': ('Esrarengiz', None),
    'c1-whimsical': ('Kaprisli (hayalperest)', None),
    'c1-wistful': ('Hüzünlü (özlem dolu)', None),
    'c1-fleeting': ('Geçici (kısa süreli)', None),
    'c1-enduring': ('Kalıcı (sürekli)', None),
    'c1-ubiquitous': ('Her yerde bulunan', None),
    'c1-elusive': ('Ele geçmez (bulunması güç)', None),
    'c1-tangible': ('Somut', None),
    'c1-meticulous': ('Titiz', None),
    'c1-conscientious': ('Vicdanlı (özenli)', None),
    'c1-diligent': ('Çalışkan (gayretli)', None),
    'c1-pragmatic': ('Pragmatik', None),
    'c1-cynical': ('Kinik (şüpheci alaycı)', None),
    'c1-skeptical': ('Şüpheci', None),
    'c1-gullible': ('Saf (kolay kanan)', None),
    'c1-smug': ('Kendini beğenmiş', None),
    'c1-aloof': ('Mesafeli', None),
    'c1-candid': ('Samimi (açık sözlü)', None),
    'c1-tactless': ('Patavatsız', None),
    'c1-assertive': ('Kendine güvenen (iddialı)', None),
    'c1-submissive': ('İtaatkâr (boyun eğen)', None),
    'c1-vindictive': ('Kindar', None),
    'c1-magnanimous': ('Yüce gönüllü', None),
    'c1-benevolent': ('İyiliksever', None),
    'c1-malicious': ('Kötü niyetli', None),
    'c1-frugal': ('Tutumlu', None),
    'c1-extravagant': ('Savurgan', None),
    'c1-impulsive': ('Dürtüsel', None),
    'c1-spontaneous': ('Anlık (plansız)', None),
    'c1-calculating': ('Hesapçı', None),
    'c1-eccentric': ('Eksantrik', None),
    'c1-unconventional': ('Alışılmadık', None),
    'c1-sophisticated': ('Sofistike (incelikli)', None),
    'c1-witty': ('Nüktedan', None),
    'c1-sarcastic': ('İğneleyici (alaycı)', None),
    'c1-charismatic': ('Karizmatik', None),
    'c1-condescending': ('Tepeden bakan', None),
    'c1-pretentious': ('Yapmacık (gösterişçi)', None),
    'c1-empire': ('İmparatorluk', None),
    'c1-colony': ('Koloni', None),
    'c1-revolution': ('Devrim', None),
    'c1-uprising': ('Ayaklanma', None),
    'c1-dictatorship': ('Diktatörlük', None),
    'c1-democracy': ('Demokrasi', None),
    'c1-monarchy': ('Monarşi', None),
    'c1-republic': ('Cumhuriyet', None),
    'c1-regime': ('Rejim', None),
    'c1-treaty': ('Antlaşma', None),
    'c1-alliance': ('İttifak', None),
    'c1-invasion': ('İstila', None),
    'c1-occupation-military': ('İşgal', None),
    'c1-independence': ('Bağımsızlık', None),
    'c1-sovereignty': ('Egemenlik', None),
    'c1-civil-war': ('İç savaş', None),
    'c1-ceasefire': ('Ateşkes', None),
    'c1-refugee': ('Mülteci', None),
    'c1-asylum': ('Sığınma (iltica)', None),
    'c1-exile': ('Sürgün', None),
    'c1-dynasty': ('Hanedan', None),
    'c1-heir': ('Varis', None),
    'c1-coup': ('Darbe', None),
    'c1-sanctions': ('Yaptırımlar', None),
    'c1-diplomacy': ('Diplomasi', None),
    'c1-ambassador': ('Büyükelçi', None),
    'c1-embassy': ('Büyükelçilik', None),
    'c1-summit-meeting': ('Zirve', None),
    'c1-constitution': ('Anayasa', None),
    'c1-amendment': ('Anayasa değişikliği', None),
    'c1-bottom-line': ('Özünde (sonuç olarak)', None),
    'c1-ballpark-figure': ('Yaklaşık rakam', None),
    'c1-to-touch-base': ('İrtibata geçmek', None),
    'c1-to-circle-back': ('Sonra dönüp bakmak', None),
    'c1-bandwidth-capacity': ('Zaman ve enerji (kapasite)', None),
    'c1-to-leverage': ('Kaldıraç olarak kullanmak', None),
    'c1-synergy': ('Sinerji', None),
    'c1-to-scale-up': ('Büyütmek (ölçeklendirmek)', None),
    'c1-to-pivot': ('Yön değiştirmek', None),
    'c1-to-onboard': ('İşe alıştırmak', None),
    'c1-to-roll-out': ('Devreye almak (yaygınlaştırmak)', None),
    'c1-to-ramp-up': ('Hızlandırmak (artırmak)', None),
    'c1-to-wind-down': ('Kademeli olarak azaltmak', None),
    'c1-to-cut-corners': ('Ucuza kaçmak', None),
    'c1-red-tape': ('Bürokrasi (kırtasiyecilik)', None),
    'c1-to-go-the-extra-mile': ('Fazlasını yapmak', None),
    'c1-on-the-same-page': ('Aynı fikirde olmak', None),
    'c1-to-keep-in-the-loop': ('Bilgilendirmek (haberdar etmek)', None),
    'c1-to-drop-the-ball': ('İşi yüzüstü bırakmak', None),
    'c1-to-think-outside-the-box': ('Kalıpların dışında düşünmek', None),
    'c1-win-win': ('Karşılıklı kazanç', None),
    'c1-game-changer': ('Oyunu değiştiren şey', None),
    'c1-low-hanging-fruit': ('Kolay hedef', None),
    'c1-deliverable': ('Teslim edilecek çıktı', None),
    'c1-return-on-investment': ('Yatırım getirisi', None),
    'c1-to-sign-off-on': ('Onaylamak', None),
    'c1-to-run-something-by-someone': ('Birine danışmak', None),
    'c1-stakeholder-buy-in': ('Paydaş desteği', None),
    'c1-back-to-the-drawing-board': ('Baştan başlamak', None),
    'c1-take-it-offline': ('Bunu özelde konuşalım', None),
    'c1-over-the-moon': ('Çok mutlu', None),
    'c1-down-in-the-dumps': ('Kederli (moralsiz)', None),
    'c1-on-edge': ('Gergin', None),
    'c1-fed-up': ('Bıkmış (bezmiş)', None),
    'c1-at-a-loss': ('Ne yapacağını bilememek', None),
    'c1-in-two-minds': ('Kararsız', None),
    'c1-under-the-weather': ('Keyifsiz (biraz hasta)', None),
    'c1-taken-aback': ('Şaşkına dönmüş', None),
    'c1-blown-away': ('Hayran kalmış', None),
    'c1-torn-between': ('İkilemde kalmış', None),
    'c1-beside-oneself': ('Kendinden geçmiş', None),
    'c1-heartbroken': ('Kalbi kırık', None),
    'c1-on-the-fence': ('Kararsız (taraf tutmayan)', None),
    'c1-laid-back': ('Rahat (kaygısız)', None),
    'c1-uptight': ('Gergin (sıkı)', None),
    'c1-sick-and-tired': ('Bıkmış usanmış', None),
    'c1-in-a-rut': ('Rutine sıkışmış', None),
    'c1-head-over-heels': ('Delicesine âşık', None),
    'c1-cold-feet': ('Son anda korkma', None),
    'c1-second-thoughts': ('Tereddüt (yeniden düşünme)', None),
    'c1-a-weight-off-my-shoulders': ('Üzerimden bir yük kalktı', None),
    'c1-butterflies-in-my-stomach': ('Karnımda kelebekler', None),
    'c1-a-lump-in-my-throat': ('Boğazımda düğüm', None),
    'c1-goosebumps': ('Tüyler ürpermesi', None),
    'c1-speechless-with-joy': ('Sevinçten dili tutulmuş', None),
    'c1-out-of-sorts': ('Keyifsiz (halsiz)', None),
    'c1-keyed-up': ('Gergin (heyecanlı)', None),
    'c1-wound-up': ('Sinirleri gerilmiş', None),
    'c1-mixed-feelings': ('Karışık duygular', None),
    'c1-at-peace': ('Huzurlu', None),
    'c1-bureaucracy': ('Bürokrasi', None),
    'c1-paperwork': ('Evrak işleri', None),
    'c1-to-file-documents': ('Resmi olarak sunmak (belge)', None),
    'c1-applicant': ('Başvuru sahibi', None),
    'c1-eligible': ('Uygun (hak sahibi)', None),
    'c1-to-qualify': ('Şartları sağlamak', None),
    'c1-prerequisite': ('Ön koşul', None),
    'c1-clause': ('Madde (hüküm)', None),
    'c1-compliance': ('Uyum (mevzuata uyma)', None),
    'c1-regulation': ('Yönetmelik (düzenleme)', None),
    'c1-license-permit': ('Ruhsat (izin belgesi)', None),
    'c1-to-authorize': ('Yetki vermek', None),
    'c1-notary': ('Noter', None),
    'c1-affidavit': ('Yeminli beyan', None),
    'c1-deed': ('Tapu senedi', None),
    'c1-title-property': ('Mülkiyet belgesi', None),
    'c1-lien': ('Rehin hakkı (ipotek)', None),
    'c1-easement': ('İrtifak hakkı', None),
    'c1-appraisal': ('Değerleme (kıymet takdiri)', None),
    'c1-closing-real-estate': ('Satışın kapanışı (tapu devri)', None),
    'c1-escrow': ('Emanet hesabı', None),
    'c1-commission-fee': ('Komisyon', None),
    'c1-listing-property': ('İlan (emlak)', None),
    'c1-counteroffer': ('Karşı teklif', None),
    'c1-contingency': ('Şarta bağlı koşul', None),
    'c1-zoning-variance': ('İmar istisnası', None),
    'c1-deadline-filing': ('Son başvuru tarihi', None),
    'c1-certified-copy': ('Onaylı suret', None),
    'c1-jurisdiction': ('Yargı yetkisi', None),
    'c1-liability': ('Sorumluluk (yükümlülük)', None),
    'c1-galaxy': ('Galaksi', None),
    'c1-universe': ('Evren', None),
    'c1-black-hole': ('Kara delik', None),
    'c1-telescope': ('Teleskop', None),
    'c1-asteroid': ('Asteroit', None),
    'c1-eclipse': ('Tutulma', None),
    'c1-constellation': ('Takımyıldız', None),
    'c1-particle': ('Parçacık', None),
    'c1-radiation': ('Radyasyon', None),
    'c1-electron': ('Elektron', None),
    'c1-isotope': ('İzotop', None),
    'c1-nuclear-fusion': ('Nükleer füzyon', None),
    'c1-magnetic-field': ('Manyetik alan', None),
    'c1-friction': ('Sürtünme', None),
    'c1-velocity': ('Hız (vektörel)', None),
    'c1-acceleration': ('İvme', None),
    'c1-momentum': ('Momentum', None),
    'c1-inertia': ('Atalet', None),
    'c1-density': ('Yoğunluk', None),
    'c1-pressure-physics': ('Basınç', None),
    'c1-vacuum': ('Vakum (boşluk)', None),
    'c1-wavelength': ('Dalga boyu', None),
    'c1-frequency-physics': ('Frekans', None),
    'c1-spectrum': ('Tayf (spektrum)', None),
    'c1-photosynthesis': ('Fotosentez', None),
    'c1-enzyme': ('Enzim', None),
    'c1-hormone': ('Hormon', None),
    'c1-metabolism': ('Metabolizma', None),
    'c1-mutation': ('Mutasyon', None),
    'c1-organism': ('Organizma', None),
    'c1-to-allege': ('İddia etmek', None),
    'c1-to-allude': ('İma etmek', None),
    'c1-to-ascertain': ('Kesin olarak tespit etmek', None),
    'c1-to-bolster': ('Güçlendirmek (desteklemek)', None),
    'c1-to-circumvent': ('Aşmak (dolanmak)', None),
    'c1-to-coerce': ('Zorlamak (baskı yapmak)', None),
    'c1-to-condone': ('Göz yummak', None),
    'c1-to-consolidate': ('Pekiştirmek (birleştirmek)', None),
    'c1-to-curb': ('Frenlemek (sınırlamak)', None),
    'c1-to-deter': ('Caydırmak', None),
    'c1-to-diminish': ('Azaltmak (küçültmek)', None),
    'c1-to-disclose': ('İfşa etmek (açıklamak)', None),
    'c1-to-disrupt': ('Aksatmak (bozmak)', None),
    'c1-to-divert': ('Yönünü değiştirmek (saptırmak)', None),
    'c1-to-elicit': ('Ortaya çıkarmak (tepki almak)', None),
    'c1-to-endorse': ('Onaylamak (destek vermek)', None),
    'c1-to-entail': ('Gerektirmek', None),
    'c1-to-eradicate': ('Kökünü kazımak', None),
    'c1-to-exacerbate': ('Kötüleştirmek (şiddetlendirmek)', None),
    'c1-to-exemplify': ('Örneklendirmek', None),
    'c1-to-foster': ('Teşvik etmek (geliştirmek)', None),
    'c1-to-hinder': ('Engellemek', None),
    'c1-to-impede': ('Engel olmak (yavaşlatmak)', None),
    'c1-to-instigate': ('Kışkırtmak (başlatmak)', None),
    'c1-to-mitigate': ('Hafifletmek', None),
    'c1-to-nurture': ('Beslemek (yetiştirmek)', None),
    'c1-to-omit': ('Atlamak (dahil etmemek)', None),
    'c1-to-precede': ('Önce gelmek', None),
    'c1-to-preclude': ('Önlemek (imkânsız kılmak)', None),
    'c1-to-prompt': ('Harekete geçirmek', None),
    'c1-to-refrain': ('Kaçınmak (kendini alıkoymak)', None),
    'c1-to-relinquish': ('Vazgeçmek (bırakmak)', None),
    'c1-to-render': ('Hale getirmek (dönüştürmek)', None),
    'c1-to-scrutinize': ('Didik didik incelemek', None),
    'c1-to-stipulate': ('Şart koşmak', None),
    'c1-to-substantiate': ('Kanıtlarla desteklemek', None),
    'c1-to-thrive': ('Gelişip serpilmek', None),
    'c1-to-undermine': ('Zayıflatmak (baltalamak)', None),
    'c1-to-uphold': ('Yürürlükte tutmak (savunmak)', None),
    'c1-to-waive': ('Feragat etmek', None),
    'c1-to-yield': ('Ürün vermek (getirmek)', None),
    'c1-to-abolish': ('Kaldırmak (lağvetmek)', None),
    'c1-to-accommodate': ('Barındırmak (uyum sağlamak)', None),
    'c1-to-adhere': ('Bağlı kalmak (uymak)', None),
    'c1-to-attain': ('Ulaşmak (elde etmek)', None),
    'c1-to-compel': ('Zorunlu kılmak', None),
    'c1-to-confine': ('Sınırlamak (kapatmak)', None),
    'c1-to-contemplate': ('Üzerinde düşünmek', None),
    'c1-to-depict': ('Betimlemek (tasvir etmek)', None),
    'c1-to-dispel': ('Dağıtmak (gidermek)', None),
    'c1-to-embody': ('Somutlaştırmak (temsil etmek)', None),
    'c1-to-evoke': ('Çağrıştırmak (uyandırmak)', None),
    'c1-to-forge': ('Şekillendirmek (kurmak)', None),
    'c1-to-grasp': ('Kavramak', None),
    'c1-to-infringe': ('İhlal etmek', None),
    'c1-to-overturn': ('Bozmak (tersine çevirmek)', None),
    'c1-to-plead': ('Yalvarmak (savunmak)', None),
    'c1-to-reconcile-ideas': ('Bağdaştırmak (uzlaştırmak)', None),
    'c1-to-surpass': ('Geçmek (aşmak)', None),
    'c1-to-unveil': ('Açığa çıkarmak (tanıtmak)', None),
    'c1-albeit': ('Gerçi (her ne kadar)', None),
    'c1-notwithstanding': ('Buna rağmen', None),
    'c1-insofar-as': ('-diği ölçüde', None),
    'c1-whereby': ('Bununla (bu sayede)', None),
    'c1-hereby': ('İşbu belgeyle', None),
    'c1-thereby': ('Bu suretle', None),
    'c1-hence': ('Bu nedenle', None),
    'c1-thus': ('Böylece', None),
    'c1-henceforth': ('Bundan böyle', None),
    'c1-likewise': ('Aynı şekilde', None),
    'c1-conversely': ('Tam tersine', None),
    'c1-namely': ('Yani (şöyle ki)', None),
    'c1-in-lieu-of': ('Yerine', None),
    'c1-in-light-of': ('Işığında', None),
    'c1-in-view-of': ('Göz önüne alındığında', None),
    'c1-by-virtue-of': ('Sayesinde', None),
    'c1-on-account-of': ('Nedeniyle', None),
    'c1-with-a-view-to': ('Amacıyla', None),
    'c1-provided-that': ('Şartıyla', None),
    'c1-granted': ('Doğrusu (kabul etmek gerekirse)', None),
    'c1-admittedly': ('Kabul etmek gerekirse', None),
    'c1-arguably': ('Belki de (tartışmaya açık şekilde)', None),
    'c1-presumably': ('Muhtemelen (tahminen)', None),
    'c1-allegedly': ('Sözde (iddia edildiğine göre)', None),
    'c1-ostensibly': ('Görünüşte', None),
    'c1-undoubtedly': ('Kuşkusuz', None),
    'c1-invariably': ('Değişmez biçimde', None),
    'c1-nevertheless-formal': ('Yine de (resmi)', None),
    'c1-to-the-extent-that': ('-dığı ölçüde ki', None),
    'c1-for-all-intents-and-purposes': ('Fiilen (her bakımdan)', None),
    'c1-sommelier': ('Sommelier (şarap uzmanı)', None),
    'c1-vintage-wine': ('Yıllanmış şarap', None),
    'c1-aroma': ('Aroma', None),
    'c1-palate': ('Damak (tat alma duyusu)', None),
    'c1-aftertaste': ('Ağızda kalan tat', None),
    'c1-full-bodied': ('Gövdeli (dolgun)', None),
    'c1-dry-wine': ('Sek (şarap)', None),
    'c1-sparkling': ('Köpüklü', None),
    'c1-brew': ('Demleme (kaynatılmış içecek)', None),
    'c1-roast-coffee': ('Kavurma', None),
    'c1-espresso': ('Espresso', None),
    'c1-decaf': ('Kafeinsiz', None),
    'c1-barista': ('Barista', None),
    'c1-tasting-menu': ('Tadım menüsü', None),
    'c1-pairing': ('Eşleştirme (yemek-şarap uyumu)', None),
    'c1-a-la-carte': ('A la carte (seçmeli menü)', None),
    'c1-garnish': ('Süsleme (garnitür)', None),
    'c1-drizzle-of-oil': ('Bir tutam gezdirme (yağ)', None),
    'c1-reduction-sauce': ('Kısılmış sos', None),
    'c1-glaze': ('Sırlama (parlatma sosu)', None),
    'c1-umami': ('Umami', None),
    'c1-zest': ('Kabuk rendesi', None),
    'c1-to-caramelize': ('Karamelize etmek', None),
    'c1-to-braise': ('Buğulamak', None),
    'c1-to-poach': ('Haşlamak', None),
    'c1-al-dente': ('Al dente (dişe gelir kıvamda)', None),
    'c1-medium-rare': ('Az pişmiş', None),
    'c1-well-done': ('İyi pişmiş', None),
    'c1-signature-dish': ('İmza yemeği', None),
    'c1-chefs-recommendation': ('Şefin önerisi', None),
    'c1-floor-plan': ('Kat planı', None),
    'c1-open-plan': ('Açık plan', None),
    'c1-layout': ('Yerleşim (düzen)', None),
    'c1-fixture': ('Sabit tesisat', None),
    'c1-cabinetry': ('Dolap sistemi', None),
    'c1-countertop': ('Tezgah', None),
    'c1-backsplash': ('Sıçrama önleyici duvar paneli', None),
    'c1-grout': ('Derz dolgusu', None),
    'c1-hardwood-floor': ('Masif ahşap zemin', None),
    'c1-laminate': ('Laminat', None),
    'c1-molding-trim': ('Kalıp bordür (süpürgelik profili)', None),
    'c1-baseboard': ('Süpürgelik', None),
    'c1-crown-molding': ('Tavan kartonpiyeri', None),
    'c1-sconce': ('Duvar apliği', None),
    'c1-pendant-light': ('Sarkıt lamba', None),
    'c1-recessed-lighting': ('Gömme aydınlatma', None),
    'c1-dimmer': ('Karartma anahtarı', None),
    'c1-vent': ('Havalandırma ızgarası', None),
    'c1-duct': ('Hava kanalı', None),
    'c1-hvac': ('Isıtma-soğutma-havalandırma sistemi', None),
    'c1-sump-pump': ('Sızıntı suyu pompası', None),
    'c1-water-heater': ('Su ısıtıcısı', None),
    'c1-circuit-breaker': ('Sigorta (devre kesici)', None),
    'c1-load-bearing-wall': ('Taşıyıcı duvar', None),
    'c1-joist': ('Kiriş', None),
    'c1-stud-wall': ('Dikme (duvar iskeleti)', None),
    'c1-subfloor': ('Alt zemin', None),
    'c1-caulk': ('Dolgu macunu', None),
    'c1-primer-paint': ('Astar (boya)', None),
    'c1-punch-list': ('Eksik iş listesi', None),
    'c1-change-order': ('Değişiklik emri', None),
    'c1-scope-of-work': ('İş kapsamı', None),
    'c1-rapport': ('İyi ilişki (uyum)', None),
    'c1-chemistry-between-people': ('Kimya (insanlar arası uyum)', None),
    'c1-affinity': ('Yakınlık (eğilim)', None),
    'c1-estranged': ('Küskün (ilişkisi kopmuş)', None),
    'c1-reconciliation': ('Barışma', None),
    'c1-to-confide': ('Sır vermek', None),
    'c1-confidant': ('Sırdaş', None),
    'c1-to-fall-out': ('Küsmek (bozuşmak)', None),
    'c1-to-patch-things-up': ('Aralarını düzeltmek', None),
    'c1-to-drift-apart': ('Zamanla uzaklaşmak', None),
    'c1-to-hit-it-off': ('Hemen kaynaşmak', None),
    'c1-to-have-a-soft-spot-for': ('Zaafı olmak', None),
    'c1-to-hold-a-grudge': ('Kin tutmak', None),
    'c1-to-bury-the-hatchet': ('Husumeti sona erdirmek', None),
    'c1-to-make-amends': ('Telafi etmek (özrünü ödemek)', None),
    'c1-to-take-for-granted': ('Değerini bilmemek', None),
    'c1-to-lean-on': ('Dayanmak (destek almak)', None),
    'c1-to-stick-up-for': ('Savunmak (arka çıkmak)', None),
    'c1-to-look-out-for': ('Gözetmek (kollamak)', None),
    'c1-to-see-eye-to-eye': ('Aynı görüşte olmak', None),
    'c1-to-get-on-someones-nerves': ('Sinirine dokunmak', None),
    'c1-to-give-the-benefit-of-the-doubt': ('Şüpheden yararlandırmak', None),
    'c1-to-read-between-the-lines': ('Satır aralarını okumak', None),
    'c1-to-beat-around-the-bush': ('Lafı dolandırmak', None),
    'c1-to-get-to-the-point': ('Sadede gelmek', None),
    'c1-to-keep-someone-at-arms-length': ('Mesafeli tutmak', None),
    'c1-to-go-behind-someones-back': ('Birinin arkasından iş çevirmek', None),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('Duygularını açıkça göstermek', None),
    'c1-tactfully': ('İncelikle', None),
    'c1-passive-aggressive': ('Pasif-agresif', None),
    'c1-mediocre': ('Vasat', None),
    'c1-subpar': ('Beklenenin altında', None),
    'c1-top-notch': ('Birinci sınıf', None),
    'c1-first-rate': ('Üstün nitelikli', None),
    'c1-second-rate': ('İkinci sınıf', None),
    'c1-state-of-the-art': ('Son teknoloji', None),
    'c1-cutting-edge': ('Öncü (en yeni)', None),
    'c1-run-of-the-mill': ('Sıradan', None),
    'c1-exceptional': ('Olağanüstü', None),
    'c1-flawless': ('Kusursuz (hatasız)', None),
    'c1-impeccable': ('Eksiksiz (mükemmel)', None),
    'c1-shoddy': ('Kalitesiz (özensiz)', None),
    'c1-sloppy': ('Özensiz (baştan savma)', None),
    'c1-half-baked': ('Yarım yamalak', None),
    'c1-polished': ('Cilalı (özenli)', None),
    'c1-crude': ('Kaba (ham)', None),
    'c1-rudimentary': ('İlkel (temel düzeyde)', None),
    'c1-intricate': ('İnce işlenmiş (karmaşık)', None),
    'c1-convoluted': ('Girift (dolambaçlı)', None),
    'c1-user-friendly': ('Kullanıcı dostu', None),
    'c1-foolproof': ('Şaşmaz (yanılmaz)', None),
    'c1-robust': ('Sağlam (dayanıklı)', None),
    'c1-seamless': ('Sorunsuz (kesintisiz)', None),
    'c1-glitchy': ('Aksaklıklı (hatalı)', None),
    'c1-clunky': ('Hantal', None),
    'c1-sleek': ('Zarif (şık, akıcı tasarım)', None),
    'c1-bulky': ('Hacimli (iri)', None),
    'c1-compact': ('Kompakt', None),
    'c1-flimsy': ('Dayanıksız (cılız)', None),
    'c1-durable': ('Dayanıklı', None),
    'c1-to-mumble': ('Mırıldanmak', None),
    'c1-to-mutter': ('Homurdanmak', None),
    'c1-to-stutter': ('Kekelemek', None),
    'c1-to-slur': ('Kelimeleri yutarak konuşmak', None),
    'c1-to-ramble': ('Dereden tepeden konuşmak', None),
    'c1-to-rant': ('Ateş püskürmek', None),
    'c1-to-grumble': ('Söylenmek (mırın kırın etmek)', None),
    'c1-to-whine': ('Sızlanmak', None),
    'c1-to-snap-at-someone': ('Ters cevap vermek', None),
    'c1-hoarse': ('Boğuk (kısık)', None),
    'c1-raspy': ('Hırıltılı', None),
    'c1-monotone': ('Tekdüze', None),
    'c1-shrill': ('Tiz (keskin)', None),
    'c1-deafening': ('Sağır edici', None),
    'c1-muffled': ('Boğuklaşmış', None),
    'c1-faint-sound': ('Belli belirsiz (ses)', None),
    'c1-to-hum': ('Mırıldanarak şarkı söylemek', None),
    'c1-to-chant': ('Slogan atarak tekrarlamak', None),
    'c1-to-murmur': ('Fısıldar gibi konuşmak', None),
    'c1-to-bellow': ('Böğürmek (bağırmak)', None),
    'c1-to-chuckle': ('Kıkırdamak (hafifçe gülmek)', None),
    'c1-to-giggle': ('Kıkır kıkır gülmek', None),
    'c1-to-snicker': ('Alaycı bir şekilde gülmek', None),
    'c1-to-sob': ('Hıçkıra hıçkıra ağlamak', None),
    'c1-to-wail': ('Feryat etmek', None),
    'c1-to-howl': ('Ulumak', None),
    'c1-to-shriek': ('Tiz çığlık atmak', None),
    'c1-to-gasp': ('Nefesi kesilmek', None),
    'c1-pitch-voice': ('Ses tonu (perde)', None),
    'c1-accent-stress': ('Vurgu', None),
    'c1-asset': ('Varlık (aktif)', None),
    'c1-liability-finance': ('Pasif (borç)', None),
    'c1-equity': ('Özkaynak', None),
    'c1-portfolio': ('Portföy', None),
    'c1-dividend': ('Temettü', None),
    'c1-bond-finance': ('Tahvil', None),
    'c1-hedge': ('Riskten korunma', None),
    'c1-liquidity': ('Likidite', None),
    'c1-collateral': ('Teminat', None),
    'c1-default-loan': ('Temerrüt (ödeme yapmama)', None),
    'c1-foreclosure': ('İpoteğin icrası (haciz)', None),
    'c1-appreciation-value': ('Değer artışı', None),
    'c1-depreciation': ('Amortisman (değer kaybı)', None),
    'c1-capital-gains': ('Sermaye kazancı', None),
    'c1-write-off': ('Zarar yazma', None),
    'c1-overhead': ('Genel giderler', None),
    'c1-payroll': ('Bordro', None),
    'c1-gross-before-deductions': ('Brüt', None),
    'c1-net': ('Net', None),
    'c1-deductible': ('Vergiden düşülebilir', None),
    'c1-exemption': ('Muafiyet', None),
    'c1-audit': ('Denetim', None),
    'c1-ledger': ('Defteri kebir', None),
    'c1-bookkeeping': ('Muhasebe (defter tutma)', None),
    'c1-break-even': ('Başabaş noktası', None),
    'c1-turnover': ('Ciro', None),
    'c1-markup': ('Kâr marjı', None),
    'c1-cash-reserve': ('Nakit rezervi', None),
    'c1-venture-capital': ('Girişim sermayesi', None),
    'c1-fiscal-year': ('Mali yıl', None),
    'c1-expedition': ('Sefer (keşif gezisi)', None),
    'c1-pilgrimage': ('Hac (kutsal yolculuk)', None),
    'c1-getaway': ('Kısa kaçamak', None),
    'c1-sabbatical': ('Sabbatical izni', None),
    'c1-nomad': ('Göçebe', None),
    'c1-expatriate': ('Gurbetçi', None),
    'c1-immigrant': ('Göçmen', None),
    'c1-to-relocate': ('Taşınmak (yer değiştirmek)', None),
    'c1-to-settle-down': ('Yerleşmek', None),
    'c1-culture-shock': ('Kültür şoku', None),
    'c1-to-assimilate': ('Bütünleşmek (asimile olmak)', None),
    'c1-bilingual': ('İki dilli', None),
    'c1-multilingual': ('Çok dilli', None),
    'c1-mother-tongue': ('Ana dil', None),
    'c1-dialect': ('Lehçe', None),
    'c1-slang': ('Argo', None),
    'c1-jargon': ('Jargon (mesleki dil)', None),
    'c1-register-language': ('Dil kaydı (üslup düzeyi)', None),
    'c1-colloquial': ('Günlük konuşma dili', None),
    'c1-fluency': ('Akıcılık', None),
    'c1-proficiency': ('Yetkinlik (dil hakimiyeti)', None),
    'c1-to-master': ('Ustalaşmak', None),
    'c1-immersion': ('Dil banyosu (tam daldırma)', None),
    'c1-intonation': ('Tonlama', None),
    'c1-to-mispronounce': ('Yanlış telaffuz etmek', None),
    'c1-false-friend': ('Sahte akraba kelime', None),
    'c1-cognate': ('Kökteş kelime', None),
    'c1-loanword': ('Ödünç kelime', None),
    'c1-literacy': ('Okuryazarlık', None),
    'c1-interpreter': ('Sözlü çevirmen', None),
    'c1-latency': ('Gecikme süresi', None),
    'c1-server': ('Sunucu', None),
    'c1-cloud-computing': ('Bulut bilişim', None),
    'c1-backup-data': ('Yedekleme', None),
    'c1-firewall': ('Güvenlik duvarı', None),
    'c1-malware': ('Kötü amaçlı yazılım', None),
    'c1-phishing': ('Oltalama saldırısı', None),
    'c1-two-factor-authentication': ('İki aşamalı doğrulama', None),
    'c1-biometric': ('Biyometrik', None),
    'c1-open-source': ('Açık kaynak', None),
    'c1-interface': ('Arayüz', None),
    'c1-plugin': ('Eklenti', None),
    'c1-patch-software': ('Yama', None),
    'c1-to-deploy': ('Devreye almak (yayına almak)', None),
    'c1-release-version': ('Sürüm', None),
    'c1-beta': ('Beta', None),
    'c1-blockchain': ('Blok zinciri', None),
    'c1-cryptocurrency': ('Kripto para', None),
    'c1-machine-learning': ('Makine öğrenmesi', None),
    'c1-neural-network': ('Sinir ağı', None),
    'c1-dataset': ('Veri kümesi', None),
    'c1-drone': ('İnsansız hava aracı', None),
    'c1-sensor': ('Sensör', None),
    'c1-augmented-reality': ('Artırılmış gerçeklik', None),
    'c1-wearable': ('Giyilebilir teknoloji', None),
    'c1-smart-home': ('Akıllı ev', None),
    'c1-bandwidth-network': ('Bant genişliği', None),
    'c1-outage': ('Kesinti (hizmet kesintisi)', None),
    'c1-scalability': ('Ölçeklenebilirlik', None),
    'c1-encryption-key': ('Şifreleme anahtarı', None),
    'c1-cinematography': ('Sinematografi', None),
    'c1-close-up': ('Yakın çekim', None),
    'c1-wide-shot': ('Geniş açı çekim', None),
    'c1-montage': ('Montaj (sahne kurgusu)', None),
    'c1-flashback': ('Geriye dönüş', None),
    'c1-voice-over': ('Seslendirme (dış ses)', None),
    'c1-subplot': ('Yan hikâye', None),
    'c1-protagonist': ('Baş kahraman', None),
    'c1-antagonist': ('Karşıt kahraman', None),
    'c1-cliffhanger': ('Merakta bırakan final', None),
    'c1-plot-twist': ('Beklenmedik olay dönüşü', None),
    'c1-foreshadowing': ('Önceden sezdirme', None),
    'c1-pacing': ('Anlatım temposu', None),
    'c1-casting': ('Oyuncu seçimi', None),
    'c1-cameo': ('Kısa özel rol (cameo)', None),
    'c1-sequel': ('Devam filmi', None),
    'c1-prequel': ('Öncül film', None),
    'c1-reboot': ('Yeniden başlatma', None),
    'c1-box-office': ('Gişe', None),
    'c1-blockbuster': ('Gişe rekortmeni', None),
    'c1-indie-film': ('Bağımsız film', None),
    'c1-cult-classic': ('Kült klasik', None),
    'c1-critically-acclaimed': ('Eleştirmenlerce beğenilen', None),
    'c1-dubbed': ('Dublajlı', None),
    'c1-subtitled': ('Altyazılı', None),
    'c1-screening': ('Gösterim', None),
    'c1-pilot-episode': ('Pilot bölüm', None),
    'c1-season-finale': ('Sezon finali', None),
    'c1-showrunner': ('Yapımcı yönetmen', None),
    'c1-storyboard': ('Hikâye tahtası', None),
    'c1-on-the-mend': ('İyileşmekte', None),
    'c1-run-down-exhausted': ('Bitkin (tükenmiş)', None),
    'c1-in-good-shape': ('Formda', None),
    'c1-out-of-shape': ('Formsuz', None),
    'c1-a-clean-bill-of-health': ('Tertemiz sağlık raporu', None),
    'c1-to-pull-a-muscle': ('Kas incitmek', None),
    'c1-wear-and-tear': ('Aşınma ve yıpranma', None),
    'c1-to-nod-off': ('Kestirmek (dalıp uyuklamak)', None),
    'c1-to-sleep-like-a-log': ('Kütük gibi uyumak', None),
    'c1-to-toss-and-turn': ('Bir o yana bir bu yana dönmek', None),
    'c1-over-the-counter': ('Reçetesiz satılan', None),
    'c1-second-opinion': ('İkinci görüş', None),
    'c1-bedside-manner': ('Hastayla iletişim tarzı', None),
    'c1-to-be-discharged': ('Taburcu edilmek', None),
    'c1-to-be-admitted-hospital': ('Hastaneye yatırılmak', None),
    'c1-outpatient': ('Ayakta tedavi gören hasta', None),
    'c1-follow-up-appointment': ('Kontrol randevusu', None),
    'c1-referral': ('Sevk', None),
    'c1-to-take-a-turn-for-the-worse': ('Kötüye gitmek', None),
    'c1-to-black-out': ('Bilincini kaybetmek', None),
    'c1-under-the-knife': ('Ameliyat masasında', None),
    'c1-slipped-disc': ('Bel fıtığı', None),
    'c1-jet-lagged': ('Jet lag yaşayan', None),
    'c1-on-medication': ('Tedavi altında (ilaç kullanan)', None),
    'c1-immune-to': ('Bağışık (dokunulmaz)', None),
    'c1-prone-to': ('Eğilimli (yatkın)', None),
    'c1-relapse': ('Nüksetme', None),
    'c1-remission': ('Remisyon (hastalığın gerilemesi)', None),
    'c1-a-no-brainer': ('Apaçık ortada olan şey', None),
    'c1-a-long-shot': ('Zayıf ihtimal', None),
    'c1-a-close-call': ('Kıl payı atlatma', None),
    'c1-a-wake-up-call': ('Uyarı niteliğinde olay', None),
    'c1-a-catch-hidden-problem': ('Gizli bir sorun (bit yeniği)', None),
    'c1-the-upside': ('İyi yanı', None),
    'c1-the-downside': ('Kötü yanı', None),
    'c1-a-trade-off': ('Ödünleşim', None),
    'c1-a-loophole': ('Yasal boşluk', None),
    'c1-a-setback': ('Aksilik (gerileme)', None),
    'c1-a-blessing-in-disguise': ('Kılık değiştirmiş nimet', None),
    'c1-the-tip-of-the-iceberg': ('Buzdağının görünen ucu', None),
    'c1-the-last-straw': ('Bardağı taşıran son damla', None),
    'c1-a-double-edged-sword': ('İki ucu keskin kılıç', None),
    'c1-the-elephant-in-the-room': ('Görmezden gelinen büyük sorun', None),
    'c1-a-grey-area': ('Gri alan (belirsiz durum)', None),
    'c1-a-slippery-slope': ('Kaygan zemin (tehlikeli gidişat)', None),
    'c1-a-vicious-circle': ('Kısır döngü', None),
    'c1-a-stepping-stone': ('Sıçrama tahtası', None),
    'c1-a-rule-of-thumb': ('Tecrübeye dayalı genel kural', None),
    'c1-a-rain-check': ('Ertelenmiş davet', None),
    'c1-a-heads-up': ('Ön bilgi (uyarı)', None),
    'c1-a-hunch': ('Önsezi', None),
    'c1-a-knack': ('Ustalık (özel yetenek)', None),
    'c1-a-pet-peeve': ('Can sıkan küçük şey', None),
    'c1-a-red-flag': ('Alarm işareti', None),
    'c1-a-silver-lining': ('Umut ışığı', None),
    'c1-a-drop-in-the-ocean': ('Denizde bir damla', None),
    'c1-a-piece-of-cake': ('Çocuk oyuncağı', None),
    'c1-a-far-cry-from': ('-den çok uzak', None),
    'c1-a-handful': ('Bir avuç', None),
    'c1-a-fair-amount': ('Hatırı sayılır miktar', None),
    'c1-the-lions-share': ('Aslan payı', None),
    'c1-a-fraction': ('Küçük bir kısım', None),
    'c1-the-vast-majority': ('Büyük çoğunluk', None),
    'c1-next-to-nothing': ('Neredeyse hiç', None),
    'c1-a-great-deal': ('Büyük bir miktar', None),
    'c1-at-most': ('En fazla', None),
    'c1-at-best': ('En iyi ihtimalle', None),
    'c1-at-worst': ('En kötü ihtimalle', None),
    'c1-in-bulk': ('Toptan', None),
    'c1-on-average': ('Ortalama olarak', None),
    'c1-per-capita': ('Kişi başına', None),
    'c1-give-or-take': ('Aşağı yukarı', None),
    'c1-a-rough-estimate': ('Kaba bir tahmin', None),
    'c1-a-round-number': ('Yuvarlak bir rakam', None),
    'c1-the-odds': ('Olasılıklar (ihtimaller)', None),
    'c1-by-a-narrow-margin': ('Az bir farkla', None),
    'c1-by-a-landslide': ('Ezici bir farkla', None),
    'c1-one-in-ten': ('On kişiden biri', None),
    'c1-twofold': ('İki kat', None),
    'c1-exponentially': ('Katlanarak (üstel biçimde)', None),
    'c1-marginally': ('Çok az (marjinal olarak)', None),
    'c1-negligible': ('İhmal edilebilir', None),
    'c1-sizable': ('Hatırı sayılır (oldukça büyük)', None),
    'c1-umpteen': ('Sayısız (bir sürü)', None),
    'c1-in-the-region-of': ('Yaklaşık olarak', None),
    'c1-odds-and-ends': ('Ufak tefek şeyler', None),
    'c1-mentor': ('Akıl hocası', None),
    'c1-protege': ('Yetiştirilen kişi', None),
    'c1-intern': ('Stajyer', None),
    'c1-veteran-experienced': ('Kıdemli (deneyimli)', None),
    'c1-rookie': ('Çaylak', None),
    'c1-whiz': ('Dâhi (usta)', None),
    'c1-workaholic': ('İş bağımlısı', None),
    'c1-slacker': ('Tembel (işten kaçan)', None),
    'c1-know-it-all': ('Ukala (her şeyi bilen)', None),
    'c1-yes-man': ('Evet efendimci', None),
    'c1-gatekeeper': ('Kapı bekçisi (filtre)', None),
    'c1-middleman': ('Aracı', None),
    'c1-liaison': ('İrtibat görevlisi', None),
    'c1-spokesperson': ('Sözcü', None),
    'c1-figurehead': ('Göstermelik lider', None),
    'c1-frontrunner': ('Favori (önde giden)', None),
    'c1-underdog': ('Şansı düşük görülen', None),
    'c1-dark-horse': ('Sürpriz aday', None),
    'c1-wildcard': ('Belirsiz unsur (joker)', None),
    'c1-heavyweight': ('Ağır sıklet (önemli isim)', None),
    'c1-newcomer': ('Yeni gelen', None),
    'c1-insider': ('İçeriden biri', None),
    'c1-outsider': ('Dışarıdan biri (yabancı)', None),
    'c1-consultant': ('Danışman', None),
    'c1-subcontractor': ('Taşeron', None),
    'c1-headhunter': ('Yetenek avcısı', None),
    'c1-scapegoat': ('Günah keçisi', None),
    'c1-go-getter': ('Girişken (hedefine koşan)', None),
    'c1-universal-healthcare': ('Evrensel sağlık hizmeti', None),
    'c1-minimum-wage': ('Asgari ücret', None),
    'c1-affordable-housing': ('Uygun fiyatlı konut', None),
    'c1-surveillance': ('Gözetim', None),
    'c1-privacy': ('Mahremiyet', None),
    'c1-free-speech': ('İfade özgürlüğü', None),
    'c1-polarization': ('Kutuplaşma', None),
    'c1-populism': ('Popülizm', None),
    'c1-nationalism': ('Milliyetçilik', None),
    'c1-globalization': ('Küreselleşme', None),
    'c1-austerity': ('Kemer sıkma', None),
    'c1-welfare': ('Sosyal yardım', None),
    'c1-aging-population': ('Yaşlanan nüfus', None),
    'c1-birth-rate': ('Doğum oranı', None),
    'c1-brain-drain': ('Beyin göçü', None),
    'c1-gig-economy': ('Gündelik iş ekonomisi', None),
    'c1-job-displacement': ('İş kaybı (otomasyon nedeniyle)', None),
    'c1-universal-basic-income': ('Evrensel temel gelir', None),
    'c1-carbon-tax': ('Karbon vergisi', None),
    'c1-nuclear-energy': ('Nükleer enerji', None),
    'c1-food-security': ('Gıda güvenliği', None),
    'c1-water-scarcity': ('Su kıtlığı', None),
    'c1-urban-sprawl': ('Kentsel yayılma', None),
    'c1-rent-control': ('Kira kontrolü', None),
    'c1-public-transit-funding': ('Toplu taşıma finansmanı', None),
    'c1-data-protection': ('Veri koruma', None),
    'c1-wealth-gap': ('Servet uçurumu', None),
    'c1-voter-turnout': ('Seçime katılım oranı', None),
    'c1-bustling': ('Hareketli (kaynaşan)', None),
    'c1-sleepy-town': ('Sakin (uyuşuk kasaba)', None),
    'c1-vibrant': ('Canlı (renkli, hareketli)', None),
    'c1-deserted': ('Issız (tenha)', None),
    'c1-packed': ('Tıklım tıklım dolu', None),
    'c1-cramped': ('Dar (sıkışık)', None),
    'c1-airy': ('Ferah', None),
    'c1-stuffy': ('Havasız (boğucu)', None),
    'c1-gloomy': ('Kasvetli (loş)', None),
    'c1-dingy': ('Pis ve karanlık', None),
    'c1-shabby': ('Eski püskü (bakımsız)', None),
    'c1-chic': ('Şık', None),
    'c1-trendy': ('Moda (güncel)', None),
    'c1-upscale': ('Lüks (üst düzey)', None),
    'c1-seedy': ('Kötü şöhretli (bakımsız)', None),
    'c1-leafy': ('Ağaçlık', None),
    'c1-sprawling': ('Yayılmış (dağınık genişlemiş)', None),
    'c1-walkable': ('Yürünebilir', None),
    'c1-secluded': ('Tenha (özel, uzak)', None),
    'c1-remote-place': ('Issız (uzak, erişimi zor)', None),
    'c1-touristy': ('Fazla turistik', None),
    'c1-unspoiled': ('Bozulmamış (el değmemiş)', None),
    'c1-well-kept': ('Bakımlı', None),
    'c1-overgrown': ('Yabani otlarla kaplı', None),
    'c1-tucked-away': ('Saklı (gizlenmiş köşede)', None),
    'c1-nestled': ('Kucaklanmış gibi konumlanmış', None),
    'c1-lively': ('Canlı (neşeli)', None),
    'c1-run-down-place': ('Harap (bakımsız yer)', None),
}
