# -*- coding: utf-8 -*-
LANG = 'pl'
WORDS = {
    'a1-hello': ('Cześć', None),
    'a1-goodbye': ('Do widzenia', None),
    'a1-please': ('Proszę', None),
    'a1-thank-you': ('Dziękuję', None),
    'a1-excuse-me': ('Przepraszam', None),
    'a1-sorry': ('Przykro mi', None),
    'a1-yes': ('Tak', None),
    'a1-no': ('Nie', None),
    'a1-my-name-is-alex': ('Mam na imię Alex', None),
    'a1-whats-your-name': ('Jak masz na imię?', None),
    'a1-nice-to-meet-you': ('Miło mi cię poznać', None),
    'a1-how-are-you': ('Jak się masz?', None),
    'a1-mother': ('Matka', None),
    'a1-father': ('Ojciec', None),
    'a1-sister': ('Siostra', None),
    'a1-brother': ('Brat', None),
    'a1-friend': ('Przyjaciel', None),
    'a1-child': ('Dziecko', None),
    'a1-today': ('Dzisiaj', None),
    'a1-tomorrow': ('Jutro', None),
    'a1-yesterday': ('Wczoraj', None),
    'a1-now': ('Teraz', None),
    'a1-morning': ('Ranek', None),
    'a1-night': ('Noc', None),
    'a1-house': ('Dom', None),
    'a1-where-is-it': ('Gdzie to jest?', None),
    'a1-left': ('Lewo', None),
    'a1-right': ('Prawo', None),
    'a1-store': ('Sklep', None),
    'a1-bathroom': ('Łazienka', None),
    'a1-water': ('Woda', None),
    'a1-bread': ('Chleb', None),
    'a1-coffee': ('Kawa', None),
    'a1-tea': ('Herbata', None),
    'a1-delicious': ('Pyszny', None),
    'a1-spicy': ('Pikantny', None),
    'a1-good-morning': ('Dzień dobry', None),
    'a1-good-evening': ('Dobry wieczór', None),
    'a1-good-night': ('Dobranoc', None),
    'a1-youre-welcome': ('Nie ma za co', None),
    'a1-see-you-soon': ('Do zobaczenia wkrótce', None),
    'a1-see-you-tomorrow': ('Do zobaczenia jutro', None),
    'a1-welcome': ('Witamy', None),
    'a1-cheers': ('Na zdrowie!', None),
    'a1-congratulations': ('Gratulacje', None),
    'a1-happy-birthday': ('Wszystkiego najlepszego', None),
    'a1-good-luck': ('Powodzenia', None),
    'a1-have-a-nice-day': ('Miłego dnia', None),
    'a1-take-care': ('Trzymaj się', None),
    'a1-bless-you': ('Na zdrowie', None),
    'a1-enjoy-your-meal': ('Smacznego', None),
    'a1-nice-to-see-you': ('Miło cię widzieć', None),
    'a1-long-time-no-see': ('Dawno się nie widzieliśmy', None),
    'a1-goodbye-for-now': ('Na razie', None),
    'a1-i': ('Ja', None),
    'a1-you': ('Ty', None),
    'a1-he': ('On', None),
    'a1-she': ('Ona', None),
    'a1-we': ('My', None),
    'a1-they': ('Oni', None),
    'a1-man': ('Mężczyzna', None),
    'a1-woman': ('Kobieta', None),
    'a1-boy': ('Chłopiec', None),
    'a1-girl': ('Dziewczynka', None),
    'a1-person': ('Osoba', None),
    'a1-people': ('Ludzie', None),
    'a1-name': ('Imię', None),
    'a1-mister': ('Pan', None),
    'a1-madam': ('Pani', None),
    'a1-im-fine': ('Dobrze', None),
    'a1-and-you': ('A ty?', None),
    'a1-where-are-you-from': ('Skąd jesteś?', None),
    'a1-im-from-the-united-states': ('Jestem ze Stanów Zjednoczonych', None),
    'a1-friend-female': ('Przyjaciółka', None),
    'a1-family': ('Rodzina', None),
    'a1-parents': ('Rodzice', None),
    'a1-son': ('Syn', None),
    'a1-daughter': ('Córka', None),
    'a1-husband': ('Mąż', None),
    'a1-wife': ('Żona', None),
    'a1-grandmother': ('Babcia', None),
    'a1-grandfather': ('Dziadek', None),
    'a1-baby': ('Niemowlę', None),
    'a1-uncle': ('Wujek', None),
    'a1-aunt': ('Ciocia', None),
    'a1-cousin': ('Kuzyn', None),
    'a1-boyfriend': ('Chłopak', None),
    'a1-girlfriend': ('Dziewczyna', None),
    'a1-neighbor': ('Sąsiad', None),
    'a1-children': ('Dzieci', None),
    'a1-older-brother': ('Starszy brat', None),
    'a1-younger-sister': ('Młodsza siostra', None),
    'a1-pet': ('Zwierzę domowe', None),
    'a1-married': ('Żonaty', None),
    'a1-one': ('Jeden', None),
    'a1-two': ('Dwa', None),
    'a1-three': ('Trzy', None),
    'a1-four': ('Cztery', None),
    'a1-five': ('Pięć', None),
    'a1-six': ('Sześć', None),
    'a1-seven': ('Siedem', None),
    'a1-eight': ('Osiem', None),
    'a1-nine': ('Dziewięć', None),
    'a1-ten': ('Dziesięć', None),
    'a1-eleven': ('Jedenaście', None),
    'a1-twelve': ('Dwanaście', None),
    'a1-thirteen': ('Trzynaście', None),
    'a1-fourteen': ('Czternaście', None),
    'a1-fifteen': ('Piętnaście', None),
    'a1-sixteen': ('Szesnaście', None),
    'a1-seventeen': ('Siedemnaście', None),
    'a1-eighteen': ('Osiemnaście', None),
    'a1-nineteen': ('Dziewiętnaście', None),
    'a1-twenty': ('Dwadzieścia', None),
    'a1-zero': ('Zero', None),
    'a1-thirty': ('Trzydzieści', None),
    'a1-forty': ('Czterdzieści', None),
    'a1-fifty': ('Pięćdziesiąt', None),
    'a1-sixty': ('Sześćdziesiąt', None),
    'a1-seventy': ('Siedemdziesiąt', None),
    'a1-eighty': ('Osiemdziesiąt', None),
    'a1-ninety': ('Dziewięćdziesiąt', None),
    'a1-one-hundred': ('Sto', None),
    'a1-one-thousand': ('Tysiąc', None),
    'a1-one-million': ('Milion', None),
    'a1-first': ('Pierwszy', None),
    'a1-second': ('Drugi', None),
    'a1-third': ('Trzeci', None),
    'a1-half': ('Połowa', None),
    'a1-many': ('Wiele', None),
    'a1-few': ('Mało', None),
    'a1-all': ('Wszystko', None),
    'a1-some': ('Niektóre', None),
    'a1-nothing': ('Nic', None),
    'a1-number': ('Liczba', None),
    'a1-more': ('Więcej', None),
    'a1-less': ('Mniej', None),
    'a1-enough': ('Wystarczająco', None),
    'a1-red': ('Czerwony', None),
    'a1-blue': ('Niebieski', None),
    'a1-green': ('Zielony', None),
    'a1-yellow': ('Żółty', None),
    'a1-black': ('Czarny', None),
    'a1-white': ('Biały', None),
    'a1-orange-color': ('Pomarańczowy', None),
    'a1-pink': ('Różowy', None),
    'a1-purple': ('Fioletowy', None),
    'a1-brown': ('Brązowy', None),
    'a1-gray': ('Szary', None),
    'a1-color': ('Kolor', None),
    'a1-light-color': ('Jasny', None),
    'a1-dark': ('Ciemny', None),
    'a1-circle': ('Koło', None),
    'a1-square': ('Kwadrat', None),
    'a1-triangle': ('Trójkąt', None),
    'a1-line': ('Linia', None),
    'a1-shape': ('Kształt', None),
    'a1-big': ('Duży', None),
    'a1-small': ('Mały', None),
    'a1-long': ('Długi', None),
    'a1-short-length': ('Krótki', None),
    'a1-round': ('Okrągły', None),
    'a1-afternoon': ('Popołudnie', None),
    'a1-evening': ('Wieczór', None),
    'a1-day': ('Dzień', None),
    'a1-week': ('Tydzień', None),
    'a1-month': ('Miesiąc', None),
    'a1-year': ('Rok', None),
    'a1-hour': ('Godzina', None),
    'a1-minute': ('Minuta', None),
    'a1-later': ('Później', None),
    'a1-early': ('Wcześnie', None),
    'a1-late': ('Późno', None),
    'a1-always': ('Zawsze', None),
    'a1-never': ('Nigdy', None),
    'a1-sometimes': ('Czasami', None),
    'a1-often': ('Często', None),
    'a1-soon': ('Wkrótce', None),
    'a1-again': ('Znowu', None),
    'a1-its-late': ('Jest późno', None),
    'a1-tonight': ('Dziś wieczorem', None),
    'a1-before': ('Przed', None),
    'a1-after': ('Po', None),
    'a1-noon': ('Południe', None),
    'a1-midnight': ('Północ', None),
    'a1-monday': ('Poniedziałek', None),
    'a1-tuesday': ('Wtorek', None),
    'a1-wednesday': ('Środa', None),
    'a1-thursday': ('Czwartek', None),
    'a1-friday': ('Piątek', None),
    'a1-saturday': ('Sobota', None),
    'a1-sunday': ('Niedziela', None),
    'a1-weekend': ('Weekend', None),
    'a1-january': ('Styczeń', None),
    'a1-february': ('Luty', None),
    'a1-march': ('Marzec', None),
    'a1-april': ('Kwiecień', None),
    'a1-may': ('Maj', None),
    'a1-june': ('Czerwiec', None),
    'a1-july': ('Lipiec', None),
    'a1-august': ('Sierpień', None),
    'a1-september': ('Wrzesień', None),
    'a1-october': ('Październik', None),
    'a1-november': ('Listopad', None),
    'a1-december': ('Grudzień', None),
    'a1-spring': ('Wiosna', None),
    'a1-summer': ('Lato', None),
    'a1-autumn': ('Jesień', None),
    'a1-winter': ('Zima', None),
    'a1-birthday': ('Urodziny', None),
    'a1-holiday': ('Święto', None),
    'a1-room': ('Pokój', None),
    'a1-kitchen': ('Kuchnia', None),
    'a1-bedroom': ('Sypialnia', None),
    'a1-door': ('Drzwi', None),
    'a1-window': ('Okno', None),
    'a1-table': ('Stół', None),
    'a1-chair': ('Krzesło', None),
    'a1-bed': ('Łóżko', None),
    'a1-street': ('Ulica', None),
    'a1-city': ('Miasto', None),
    'a1-country': ('Kraj', None),
    'a1-school': ('Szkoła', None),
    'a1-hospital': ('Szpital', None),
    'a1-bank': ('Bank', None),
    'a1-restaurant': ('Restauracja', None),
    'a1-hotel': ('Hotel', None),
    'a1-market': ('Targ', None),
    'a1-park': ('Park', None),
    'a1-church': ('Kościół', None),
    'a1-office': ('Biuro', None),
    'a1-here': ('Tutaj', None),
    'a1-there': ('Tam', None),
    'a1-straight-ahead': ('Prosto', None),
    'a1-near': ('Blisko', None),
    'a1-far': ('Daleko', None),
    'a1-floor-level': ('Piętro', None),
    'a1-garden': ('Ogród', None),
    'a1-wall': ('Ściana', None),
    'a1-milk': ('Mleko', None),
    'a1-rice': ('Ryż', None),
    'a1-meat': ('Mięso', None),
    'a1-fish-food': ('Ryba', None),
    'a1-chicken': ('Kurczak', None),
    'a1-egg': ('Jajko', None),
    'a1-fruit': ('Owoc', None),
    'a1-vegetables': ('Warzywa', None),
    'a1-apple': ('Jabłko', None),
    'a1-sugar': ('Cukier', None),
    'a1-salt': ('Sól', None),
    'a1-beer': ('Piwo', None),
    'a1-wine': ('Wino', None),
    'a1-juice': ('Sok', None),
    'a1-breakfast': ('Śniadanie', None),
    'a1-lunch': ('Obiad', None),
    'a1-dinner': ('Kolacja', None),
    'a1-im-hungry': ('Jestem głodny', None),
    'a1-im-thirsty': ('Chce mi się pić', None),
    'a1-cheese': ('Ser', None),
    'a1-soup': ('Zupa', None),
    'a1-sweet': ('Słodki', None),
    'a1-food': ('Jedzenie', None),
    'a1-drink-noun': ('Napój', None),
    'a1-head': ('Głowa', None),
    'a1-hand': ('Dłoń', None),
    'a1-eye': ('Oko', None),
    'a1-foot': ('Stopa', None),
    'a1-mouth': ('Usta', None),
    'a1-nose': ('Nos', None),
    'a1-ear': ('Ucho', None),
    'a1-arm': ('Ramię', None),
    'a1-leg': ('Noga', None),
    'a1-heart': ('Serce', None),
    'a1-hair': ('Włosy', None),
    'a1-face': ('Twarz', None),
    'a1-back-body': ('Plecy', None),
    'a1-stomach': ('Brzuch', None),
    'a1-tooth': ('Ząb', None),
    'a1-finger': ('Palec', None),
    'a1-body': ('Ciało', None),
    'a1-blood': ('Krew', None),
    'a1-neck': ('Szyja', None),
    'a1-shoulder': ('Bark', None),
    'a1-knee': ('Kolano', None),
    'a1-skin': ('Skóra', None),
    'a1-shirt': ('Koszula', None),
    'a1-pants': ('Spodnie', None),
    'a1-shoes': ('Buty', None),
    'a1-dress': ('Sukienka', None),
    'a1-hat': ('Kapelusz', None),
    'a1-coat': ('Płaszcz', None),
    'a1-jacket': ('Kurtka', None),
    'a1-socks': ('Skarpetki', None),
    'a1-skirt': ('Spódnica', None),
    'a1-bag': ('Torba', None),
    'a1-glasses': ('Okulary', None),
    'a1-watch-wrist': ('Zegarek', None),
    'a1-umbrella': ('Parasol', None),
    'a1-to-wear': ('Nosić', None),
    'a1-sweater': ('Sweter', None),
    'a1-t-shirt': ('Koszulka', None),
    'a1-scarf': ('Szalik', None),
    'a1-gloves': ('Rękawiczki', None),
    'a1-clothes': ('Ubrania', None),
    'a1-size': ('Rozmiar', None),
    'a1-to-be': ('Być', None),
    'a1-to-have': ('Mieć', None),
    'a1-to-do': ('Robić', None),
    'a1-to-go': ('Iść', None),
    'a1-to-come': ('Przychodzić', None),
    'a1-to-want': ('Chcieć', None),
    'a1-to-be-able-to': ('Móc', None),
    'a1-to-know': ('Wiedzieć', None),
    'a1-to-see': ('Widzieć', None),
    'a1-to-say': ('Powiedzieć', None),
    'a1-to-eat': ('Jeść', None),
    'a1-to-drink': ('Pić', None),
    'a1-to-sleep': ('Spać', None),
    'a1-to-live': ('Mieszkać', None),
    'a1-to-work': ('Pracować', None),
    'a1-to-speak': ('Mówić', None),
    'a1-to-understand': ('Rozumieć', None),
    'a1-to-like': ('Lubić', None),
    'a1-to-need': ('Potrzebować', None),
    'a1-to-give': ('Dawać', None),
    'a1-to-take': ('Brać', None),
    'a1-to-think': ('Myśleć', None),
    'a1-to-buy': ('Kupować', None),
    'a1-to-help': ('Pomagać', None),
    'a1-to-open': ('Otwierać', None),
    'a1-to-close': ('Zamykać', None),
    'a1-to-look-for': ('Szukać', None),
    'a1-to-find': ('Znajdować', None),
    'a1-to-wait': ('Czekać', None),
    'a1-to-call-phone': ('Dzwonić', None),
    'a1-to-read': ('Czytać', None),
    'a1-to-write': ('Pisać', None),
    'a1-to-listen': ('Słuchać', None),
    'a1-to-learn': ('Uczyć się', None),
    'a1-to-play': ('Grać', None),
    'a1-to-walk': ('Chodzić', None),
    'a1-to-run': ('Biegać', None),
    'a1-to-sit': ('Siadać', None),
    'a1-to-stand': ('Stać', None),
    'a1-to-arrive': ('Przyjeżdżać', None),
    'a1-to-leave': ('Wychodzić', None),
    'a1-to-return': ('Wracać', None),
    'a1-to-put': ('Kłaść', None),
    'a1-to-bring': ('Przynosić', None),
    'a1-to-ask': ('Pytać', None),
    'a1-to-answer': ('Odpowiadać', None),
    'a1-to-love': ('Kochać', None),
    'a1-to-pay': ('Płacić', None),
    'a1-good': ('Dobry', None),
    'a1-bad': ('Zły', None),
    'a1-new': ('Nowy', None),
    'a1-old-thing': ('Stary', None),
    'a1-young': ('Młody', None),
    'a1-hot': ('Gorący', None),
    'a1-cold': ('Zimny', None),
    'a1-happy': ('Szczęśliwy', None),
    'a1-sad': ('Smutny', None),
    'a1-beautiful': ('Piękny', None),
    'a1-ugly': ('Brzydki', None),
    'a1-easy': ('Łatwy', None),
    'a1-difficult': ('Trudny', None),
    'a1-fast': ('Szybki', None),
    'a1-slow': ('Wolny', None),
    'a1-cheap': ('Tani', None),
    'a1-expensive': ('Drogi', None),
    'a1-full': ('Pełny', None),
    'a1-empty': ('Pusty', None),
    'a1-clean': ('Czysty', None),
    'a1-dirty': ('Brudny', None),
    'a1-strong': ('Silny', None),
    'a1-weak': ('Słaby', None),
    'a1-important': ('Ważny', None),
    'a1-what': ('Co', None),
    'a1-who': ('Kto', None),
    'a1-where': ('Gdzie', None),
    'a1-when': ('Kiedy', None),
    'a1-why': ('Dlaczego', None),
    'a1-how': ('Jak', None),
    'a1-how-many': ('Ile', None),
    'a1-which': ('Który', None),
    'a1-and': ('I', None),
    'a1-or': ('Lub', None),
    'a1-but': ('Ale', None),
    'a1-because': ('Ponieważ', None),
    'a1-with': ('Z', None),
    'a1-without': ('Bez', None),
    'a1-for': ('Dla', None),
    'a1-from': ('Od', None),
    'a1-to-direction': ('Do', None),
    'a1-in': ('W', None),
    'a1-on': ('Na', None),
    'a1-under': ('Pod', None),
    'a1-this': ('To', None),
    'a1-that': ('Tamto', None),
    'a1-very': ('Bardzo', None),
    'a1-also': ('Także', None),
    'a1-not': ('Nie', None),
    'a1-maybe': ('Może', None),
    'a1-sun': ('Słońce', None),
    'a1-rain': ('Deszcz', None),
    'a1-snow': ('Śnieg', None),
    'a1-wind': ('Wiatr', None),
    'a1-cloud': ('Chmura', None),
    'a1-weather': ('Pogoda', None),
    'a1-sky': ('Niebo', None),
    'a1-sea': ('Morze', None),
    'a1-mountain': ('Góra', None),
    'a1-river': ('Rzeka', None),
    'a1-tree': ('Drzewo', None),
    'a1-flower': ('Kwiat', None),
    'a1-dog': ('Pies', None),
    'a1-cat': ('Kot', None),
    'a1-bird': ('Ptak', None),
    'a1-fish-animal': ('Ryba', None),
    'a1-horse': ('Koń', None),
    'a1-cow': ('Krowa', None),
    'a1-earth': ('Ziemia', None),
    'a1-moon': ('Księżyc', None),
    'a1-star': ('Gwiazda', None),
    'a1-fire': ('Ogień', None),
    'a1-its-windy': ('Jest wietrznie', None),
    'a1-its-snowing': ('Pada śnieg', None),
    'a1-its-cold-today': ('Dziś jest zimno', None),
    'a1-its-hot-today': ('Dziś jest gorąco', None),
    'a1-help': ('Pomocy!', None),
    'a1-slowly-please': ('Mów wolno, proszę', None),
    'a1-do-you-speak-english': ('Czy mówisz po angielsku?', None),
    'a1-i-dont-know': ('Nie wiem', None),
    'a1-where-is-the-bathroom': ('Gdzie jest łazienka?', None),
    'a1-which-way': ('Którędy?', None),
    'a1-one-moment-please': ('Chwileczkę, proszę', None),
    'a1-of-course': ('Oczywiście', None),
    'a1-no-problem': ('Nie ma problemu', None),
    'a1-its-okay': ('W porządku', None),
    'a1-lets-go': ('Chodźmy', None),
    'a1-come-in': ('Wejdź', None),
    'a1-be-careful': ('Uważaj', None),
    'a1-can-you-help-me': ('Czy możesz mi pomóc?', None),
    'a1-what-does-that-mean': ('Co to znaczy?', None),
    'a1-can-you-repeat-that': ('Czy możesz to powtórzyć?', None),
    'a1-slower-please': ('Wolniej, proszę', None),
    'a1-how-do-you-say': ('Jak się mówi…?', None),
    'a1-i-would-like': ('Chciałbym…', None),
    'a1-the-bill-please': ('Proszę o rachunek', None),
    'a1-im-tired': ('Jestem zmęczony', None),
    'a1-im-sick': ('Jestem chory', None),
    'a1-its-an-emergency': ('To nagły wypadek', None),
    'a1-call-the-police': ('Wezwij policję', None),
    'a1-i-speak-a-little': ('Mówię trochę', None),
    'a1-i-love-it': ('Uwielbiam to', None),
    'a1-whats-this': ('Co to jest?', None),
    'a1-i-agree': ('Zgadzam się', None),
    'a1-i-dont-like-it': ('Nie podoba mi się to', None),
    'a1-really': ('Naprawdę?', None),
    'a1-exactly': ('Dokładnie', None),
    'a1-i-think-so': ('Myślę, że tak', None),
    'a1-dont-worry': ('Nie martw się', None),
    'a1-just-a-little': ('Tylko trochę', None),
    'a1-wait-a-moment': ('Poczekaj chwilę', None),
    'a1-is-this-seat-free': ('Czy to miejsce jest wolne?', None),
    'a1-money': ('Pieniądze', None),
    'a1-price': ('Cena', None),
    'a1-to-sell': ('Sprzedawać', None),
    'a1-card': ('Karta', None),
    'a1-cash': ('Gotówka', None),
    'a1-receipt': ('Paragon', None),
    'a1-open-shop': ('Otwarte', None),
    'a1-closed-shop': ('Zamknięte', None),
    'a1-free-no-cost': ('Darmowy', None),
    'a1-discount': ('Zniżka', None),
    'a1-how-much-is-it': ('Ile kosztuje?', None),
    'a1-too-much': ('Za dużo', None),
    'a1-gift': ('Prezent', None),
    'a1-change-coins': ('Reszta', None),
    'a1-supermarket': ('Supermarket', None),
    'a1-pharmacy': ('Apteka', None),
    'a1-bakery': ('Piekarnia', None),
    'a1-is-this-on-sale': ('Czy to jest w promocji?', None),
    'a1-car': ('Samochód', None),
    'a1-bus': ('Autobus', None),
    'a1-train': ('Pociąg', None),
    'a1-plane': ('Samolot', None),
    'a1-bicycle': ('Rower', None),
    'a1-taxi': ('Taksówka', None),
    'a1-ticket': ('Bilet', None),
    'a1-station': ('Stacja', None),
    'a1-airport': ('Lotnisko', None),
    'a1-road': ('Droga', None),
    'a1-to-travel': ('Podróżować', None),
    'a1-trip': ('Podróż', None),
    'a1-map': ('Mapa', None),
    'a1-stop-bus-stop': ('Przystanek', None),
    'a1-to-drive': ('Prowadzić', None),
    'a1-subway': ('Metro', None),
    'a1-passport': ('Paszport', None),
    'a1-suitcase': ('Walizka', None),
    'a1-exit': ('Wyjście', None),
    'a1-entrance': ('Wejście', None),
    'a1-phone': ('Telefon', None),
    'a1-book': ('Książka', None),
    'a1-pen': ('Długopis', None),
    'a1-paper': ('Papier', None),
    'a1-key': ('Klucz', None),
    'a1-computer': ('Komputer', None),
    'a1-clock': ('Zegar', None),
    'a1-television': ('Telewizor', None),
    'a1-camera': ('Aparat', None),
    'a1-box': ('Pudełko', None),
    'a1-glass-cup': ('Szklanka', None),
    'a1-bottle': ('Butelka', None),
    'a1-plate': ('Talerz', None),
    'a1-knife': ('Nóż', None),
    'a1-fork': ('Widelec', None),
    'a1-spoon': ('Łyżka', None),
    'a1-cup': ('Filiżanka', None),
    'a1-soap': ('Mydło', None),
    'a1-towel': ('Ręcznik', None),
    'a1-lamp': ('Lampa', None),
    'a1-wallet': ('Portfel', None),
    'a1-charger': ('Ładowarka', None),
    'a1-thing': ('Rzecz', None),
    'a1-toothbrush': ('Szczoteczka do zębów', None),
    'a1-angry': ('Rozgniewany', None),
    'a1-scared': ('Przestraszony', None),
    'a1-bored': ('Znudzony', None),
    'a1-excited': ('Podekscytowany', None),
    'a1-worried': ('Zmartwiony', None),
    'a1-surprised': ('Zaskoczony', None),
    'a1-calm': ('Spokojny', None),
    'a1-nervous': ('Zdenerwowany', None),
    'a1-proud': ('Dumny', None),
    'a1-lonely': ('Samotny', None),
    'a1-sleepy': ('Śpiący', None),
    'a1-sick-unwell': ('Chory', None),
    'a1-love': ('Miłość', None),
    'a1-fear': ('Strach', None),
    'a1-joy': ('Radość', None),
    'a1-funny': ('Zabawny', None),
    'a2-i-work-in-an-office': ('Pracuję w biurze', None),
    'a2-i-am-a-student': ('Jestem studentem', None),
    'a2-i-have-a-meeting': ('Mam spotkanie', None),
    'a2-i-am-looking-for-a-job': ('Szukam pracy', None),
    'a2-i-am-studying': ('Uczę się', None),
    'a2-i-dont-understand': ('Nie rozumiem', None),
    'a2-how-much-is-this': ('Ile to kosztuje?', None),
    'a2-its-too-expensive': ('To jest za drogie', None),
    'a2-can-i-pay-by-card': ('Czy mogę zapłacić kartą?', None),
    'a2-do-you-have-a-discount': ('Czy macie zniżkę?', None),
    'a2-im-just-looking': ('Tylko oglądam', None),
    'a2-ill-take-it': ('Biorę to', None),
    'a2-where-is-the-train-station': ('Gdzie jest dworzec kolejowy?', None),
    'a2-one-ticket-please': ('Jeden bilet, proszę', None),
    'a2-how-do-i-get-to-the-airport': ('Jak dojechać na lotnisko?', None),
    'a2-im-lost': ('Zgubiłem się', None),
    'a2-is-it-far': ('Czy to daleko?', None),
    'a2-where-is-the-restroom': ('Gdzie jest toaleta?', None),
    'a2-i-dont-feel-well': ('Źle się czuję', None),
    'a2-i-have-a-headache': ('Boli mnie głowa', None),
    'a2-where-is-the-pharmacy': ('Gdzie jest apteka?', None),
    'a2-i-need-a-doctor': ('Potrzebuję lekarza', None),
    'a2-im-allergic-to-peanuts': ('Jestem uczulony na orzeszki ziemne', None),
    'a2-it-hurts-here': ('Tutaj boli', None),
    'a2-its-sunny': ('Jest słonecznie', None),
    'a2-its-raining': ('Pada deszcz', None),
    'a2-i-like-to-read': ('Lubię czytać', None),
    'a2-my-favorite-is-music': ('Moją ulubioną rzeczą jest muzyka', None),
    'a2-on-weekends-i-rest': ('W weekendy odpoczywam', None),
    'a2-i-play-sports': ('Uprawiam sport', None),
    'a2-what-time-is-it': ('Która jest godzina?', None),
    'a2-lets-meet-tomorrow': ('Spotkajmy się jutro', None),
    'a2-can-you-call-me': ('Czy możesz do mnie zadzwonić?', None),
    'a2-see-you-later': ('Do zobaczenia później', None),
    'a2-whats-your-phone-number': ('Jaki jest twój numer telefonu?', None),
    'a2-im-busy-today': ('Dzisiaj jestem zajęty', None),
    'a2-job': ('Praca', None),
    'a2-boss': ('Szef', None),
    'a2-colleague': ('Kolega z pracy', None),
    'a2-salary': ('Pensja', None),
    'a2-to-earn': ('Zarabiać', None),
    'a2-class': ('Zajęcia', None),
    'a2-teacher': ('Nauczyciel', None),
    'a2-exam': ('Egzamin', None),
    'a2-homework': ('Praca domowa', None),
    'a2-university': ('Uniwersytet', None),
    'a2-to-teach': ('Nauczać', None),
    'a2-project': ('Projekt', None),
    'a2-deadline': ('Termin', None),
    'a2-interview': ('Rozmowa kwalifikacyjna', None),
    'a2-career': ('Kariera', None),
    'a2-break-pause': ('Przerwa', None),
    'a2-schedule': ('Harmonogram', None),
    'a2-company': ('Firma', None),
    'a2-customer': ('Klient', None),
    'a2-unemployed': ('Bezrobotny', None),
    'a2-to-try-on': ('Przymierzać', None),
    'a2-fitting-room': ('Przymierzalnia', None),
    'a2-sale-discount-event': ('Wyprzedaż', None),
    'a2-to-return-an-item': ('Zwracać', None),
    'a2-refund': ('Zwrot pieniędzy', None),
    'a2-brand': ('Marka', None),
    'a2-quality': ('Jakość', None),
    'a2-cashier': ('Kasjer', None),
    'a2-shopping-cart': ('Wózek na zakupy', None),
    'a2-online-shopping': ('Zakupy online', None),
    'a2-to-order-online': ('Zamawiać online', None),
    'a2-delivery': ('Dostawa', None),
    'a2-package': ('Paczka', None),
    'a2-to-choose': ('Wybierać', None),
    'a2-to-compare': ('Porównywać', None),
    'a2-it-fits-me': ('Dobrze na mnie leży', None),
    'a2-too-big': ('Za duże', None),
    'a2-do-you-have-it-in-another-color': ('Czy macie to w innym kolorze?', None),
    'a2-mall': ('Centrum handlowe', None),
    'a2-cheaper': ('Tańszy', None),
    'a2-reservation': ('Rezerwacja', None),
    'a2-to-book': ('Rezerwować', None),
    'a2-check-in': ('Odprawa', None),
    'a2-luggage': ('Bagaż', None),
    'a2-flight': ('Lot', None),
    'a2-delay': ('Opóźnienie', None),
    'a2-departure': ('Odlot', None),
    'a2-arrival': ('Przylot', None),
    'a2-gate': ('Bramka', None),
    'a2-seat': ('Miejsce', None),
    'a2-tourist': ('Turysta', None),
    'a2-guide': ('Przewodnik', None),
    'a2-sightseeing': ('Zwiedzanie', None),
    'a2-souvenir': ('Pamiątka', None),
    'a2-beach': ('Plaża', None),
    'a2-museum': ('Muzeum', None),
    'a2-to-visit': ('Zwiedzać', None),
    'a2-round-trip': ('W obie strony', None),
    'a2-one-way': ('W jedną stronę', None),
    'a2-abroad': ('Za granicą', None),
    'a2-doctor': ('Lekarz', None),
    'a2-nurse': ('Pielęgniarka', None),
    'a2-medicine': ('Lekarstwo', None),
    'a2-pain': ('Ból', None),
    'a2-fever': ('Gorączka', None),
    'a2-cough': ('Kaszel', None),
    'a2-a-cold-illness': ('Przeziębienie', None),
    'a2-flu': ('Grypa', None),
    'a2-allergy': ('Alergia', None),
    'a2-appointment': ('Wizyta', None),
    'a2-prescription': ('Recepta', None),
    'a2-stomachache': ('Ból brzucha', None),
    'a2-healthy': ('Zdrowy', None),
    'a2-to-rest': ('Odpoczywać', None),
    'a2-insurance': ('Ubezpieczenie', None),
    'a2-emergency': ('Nagły wypadek', None),
    'a2-dentist': ('Dentysta', None),
    'a2-injury': ('Kontuzja', None),
    'a2-i-feel-better': ('Czuję się lepiej', None),
    'a2-blood-pressure': ('Ciśnienie krwi', None),
    'a2-hobby': ('Hobby', None),
    'a2-music': ('Muzyka', None),
    'a2-movie': ('Film', None),
    'a2-sport': ('Sport', None),
    'a2-soccer': ('Piłka nożna', None),
    'a2-to-swim': ('Pływać', None),
    'a2-to-dance': ('Tańczyć', None),
    'a2-to-sing': ('Śpiewać', None),
    'a2-to-paint': ('Malować', None),
    'a2-game': ('Gra', None),
    'a2-team': ('Drużyna', None),
    'a2-to-win': ('Wygrywać', None),
    'a2-to-lose-a-game': ('Przegrywać', None),
    'a2-concert': ('Koncert', None),
    'a2-photography': ('Fotografia', None),
    'a2-to-hike': ('Chodzić po górach', None),
    'a2-gym': ('Siłownia', None),
    'a2-to-exercise': ('Ćwiczyć', None),
    'a2-cloudy': ('Pochmurny', None),
    'a2-storm': ('Burza', None),
    'a2-humid': ('Wilgotny', None),
    'a2-forecast': ('Prognoza', None),
    'a2-to-plan': ('Planować', None),
    'a2-to-meet-up': ('Umawiać się', None),
    'a2-invitation': ('Zaproszenie', None),
    'a2-to-invite': ('Zapraszać', None),
    'a2-to-cancel': ('Odwoływać', None),
    'a2-free-time': ('Wolny czas', None),
    'a2-to-postpone': ('Odkładać', None),
    'a2-internet': ('Internet', None),
    'a2-email': ('E-mail', None),
    'a2-message': ('Wiadomość', None),
    'a2-to-send': ('Wysyłać', None),
    'a2-to-download': ('Pobierać', None),
    'a2-app': ('Aplikacja', None),
    'a2-password': ('Hasło', None),
    'a2-screen': ('Ekran', None),
    'a2-wi-fi': ('Wi-Fi', None),
    'a2-website': ('Strona internetowa', None),
    'a2-video-call': ('Rozmowa wideo', None),
    'a2-are-you-free-on-saturday': ('Czy masz czas w sobotę?', None),
    'a2-sounds-good': ('Brzmi dobrze', None),
    'a2-to-clean': ('Sprzątać', None),
    'a2-to-wash': ('Myć', None),
    'a2-dishes': ('Naczynia', None),
    'a2-laundry': ('Pranie', None),
    'a2-to-iron': ('Prasować', None),
    'a2-trash': ('Śmieci', None),
    'a2-to-tidy-up': ('Porządkować', None),
    'a2-vacuum-cleaner': ('Odkurzacz', None),
    'a2-to-repair': ('Naprawiać', None),
    'a2-to-move-house': ('Przeprowadzać się', None),
    'a2-rent': ('Czynsz', None),
    'a2-landlord': ('Właściciel mieszkania', None),
    'a2-apartment': ('Mieszkanie', None),
    'a2-furniture': ('Meble', None),
    'a2-sofa': ('Sofa', None),
    'a2-fridge': ('Lodówka', None),
    'a2-oven': ('Piekarnik', None),
    'a2-stove': ('Kuchenka', None),
    'a2-shower': ('Prysznic', None),
    'a2-mirror': ('Lustro', None),
    'a2-pillow': ('Poduszka', None),
    'a2-blanket': ('Koc', None),
    'a2-washing-machine': ('Pralka', None),
    'a2-roommate': ('Współlokator', None),
    'a2-stairs': ('Schody', None),
    'a2-elevator': ('Winda', None),
    'a2-to-wake-up': ('Budzić się', None),
    'a2-to-get-up': ('Wstawać', None),
    'a2-to-take-a-shower': ('Brać prysznic', None),
    'a2-to-brush-ones-teeth': ('Myć zęby', None),
    'a2-to-get-dressed': ('Ubierać się', None),
    'a2-to-have-breakfast': ('Jeść śniadanie', None),
    'a2-to-commute': ('Dojeżdżać do pracy', None),
    'a2-to-go-home': ('Wracać do domu', None),
    'a2-to-relax': ('Relaksować się', None),
    'a2-to-watch-tv': ('Oglądać telewizję', None),
    'a2-to-go-to-bed': ('Kłaść się spać', None),
    'a2-routine': ('Rutyna', None),
    'a2-habit': ('Nawyk', None),
    'a2-alarm-clock': ('Budzik', None),
    'a2-to-be-late': ('Spóźniać się', None),
    'a2-to-hurry': ('Spieszyć się', None),
    'a2-on-time': ('Na czas', None),
    'a2-nap': ('Drzemka', None),
    'a2-to-take-a-walk': ('Iść na spacer', None),
    'a2-to-have-lunch': ('Jeść obiad', None),
    'a2-to-have-dinner': ('Jeść kolację', None),
    'a2-to-fall-asleep': ('Zasypiać', None),
    'a2-every-day': ('Codziennie', None),
    'a2-usually': ('Zwykle', None),
    'a2-corner': ('Róg', None),
    'a2-block': ('Kwartał', None),
    'a2-traffic-light': ('Sygnalizacja świetlna', None),
    'a2-bridge': ('Most', None),
    'a2-square-plaza': ('Plac', None),
    'a2-downtown': ('Centrum miasta', None),
    'a2-neighborhood': ('Dzielnica', None),
    'a2-building': ('Budynek', None),
    'a2-sidewalk': ('Chodnik', None),
    'a2-to-cross': ('Przechodzić', None),
    'a2-to-turn': ('Skręcać', None),
    'a2-address': ('Adres', None),
    'a2-post-office': ('Poczta', None),
    'a2-library': ('Biblioteka', None),
    'a2-cinema': ('Kino', None),
    'a2-theater': ('Teatr', None),
    'a2-stadium': ('Stadion', None),
    'a2-police-station': ('Komisariat', None),
    'a2-town-hall': ('Ratusz', None),
    'a2-parking-lot': ('Parking', None),
    'a2-gas-station': ('Stacja benzynowa', None),
    'a2-traffic': ('Ruch uliczny', None),
    'a2-opposite': ('Naprzeciwko', None),
    'a2-next-to': ('Obok', None),
    'a2-between': ('Między', None),
    'a2-how-do-i-get-to': ('Jak dojść do…?', None),
    'a2-menu': ('Menu', None),
    'a2-waiter': ('Kelner', None),
    'a2-dish': ('Danie', None),
    'a2-dessert': ('Deser', None),
    'a2-starter': ('Przystawka', None),
    'a2-main-course': ('Danie główne', None),
    'a2-vegetarian': ('Wegetariański', None),
    'a2-tip': ('Napiwek', None),
    'a2-to-cook': ('Gotować', None),
    'a2-recipe': ('Przepis', None),
    'a2-ingredient': ('Składnik', None),
    'a2-oil': ('Olej', None),
    'a2-butter': ('Masło', None),
    'a2-pepper': ('Pieprz', None),
    'a2-onion': ('Cebula', None),
    'a2-garlic': ('Czosnek', None),
    'a2-tomato': ('Pomidor', None),
    'a2-potato': ('Ziemniak', None),
    'a2-noodles': ('Makaron', None),
    'a2-sauce': ('Sos', None),
    'a2-to-bake': ('Piec', None),
    'a2-to-fry': ('Smażyć', None),
    'a2-to-boil': ('Gotować (w wodzie)', None),
    'a2-a-table-for-two': ('Stolik dla dwóch osób', None),
    'a2-takeout': ('Na wynos', None),
    'a2-snack': ('Przekąska', None),
    'a2-salty': ('Słony', None),
    'a2-bitter': ('Gorzki', None),
    'a2-tall': ('Wysoki', None),
    'a2-short-height': ('Niski', None),
    'a2-thin': ('Szczupły', None),
    'a2-overweight': ('Otyły', None),
    'a2-blond': ('Blond', None),
    'a2-dark-haired': ('Ciemnowłosy', None),
    'a2-beard': ('Broda', None),
    'a2-kind': ('Miły', None),
    'a2-nice-person': ('Sympatyczny', None),
    'a2-shy': ('Nieśmiały', None),
    'a2-talkative': ('Gadatliwy', None),
    'a2-smart': ('Inteligentny', None),
    'a2-lazy': ('Leniwy', None),
    'a2-hardworking': ('Pracowity', None),
    'a2-polite': ('Uprzejmy', None),
    'a2-rude': ('Niegrzeczny', None),
    'a2-patient': ('Cierpliwy', None),
    'a2-honest': ('Uczciwy', None),
    'a2-serious': ('Poważny', None),
    'a2-quiet-person': ('Cichy', None),
    'a2-friendly': ('Przyjazny', None),
    'a2-handsome': ('Przystojny', None),
    'a2-age': ('Wiek', None),
    'a2-old-person': ('Starszy', None),
    'a2-curly-hair': ('Kręcone włosy', None),
    'a2-cheerful': ('Radosny', None),
    'a2-stubborn': ('Uparty', None),
    'a2-generous': ('Hojny', None),
    'a2-to-try': ('Próbować', None),
    'a2-to-start': ('Zaczynać', None),
    'a2-to-finish': ('Kończyć', None),
    'a2-to-change': ('Zmieniać', None),
    'a2-to-use': ('Używać', None),
    'a2-to-receive': ('Otrzymywać', None),
    'a2-to-decide': ('Decydować', None),
    'a2-to-forget': ('Zapominać', None),
    'a2-to-remember': ('Pamiętać', None),
    'a2-to-lose-an-object': ('Gubić', None),
    'a2-to-meet-someone-new': ('Poznawać', None),
    'a2-to-prefer': ('Woleć', None),
    'a2-to-hope': ('Mieć nadzieję', None),
    'a2-to-believe': ('Wierzyć', None),
    'a2-to-feel': ('Czuć', None),
    'a2-to-seem': ('Wydawać się', None),
    'a2-to-happen': ('Zdarzać się', None),
    'a2-to-stay': ('Zostawać', None),
    'a2-to-spend-money': ('Wydawać (pieniądze)', None),
    'a2-to-show': ('Pokazywać', None),
    'a2-to-explain': ('Wyjaśniać', None),
    'a2-to-follow': ('Podążać', None),
    'a2-to-keep': ('Zachowywać', None),
    'a2-to-allow': ('Pozwalać', None),
    'a2-to-become': ('Stawać się', None),
    'a2-to-continue': ('Kontynuować', None),
    'a2-to-cut': ('Ciąć', None),
    'a2-to-break': ('Łamać', None),
    'a2-to-fly': ('Latać', None),
    'a2-to-draw': ('Rysować', None),
    'a2-to-carry': ('Nieść', None),
    'a2-to-push': ('Pchać', None),
    'a2-to-pull': ('Ciągnąć', None),
    'a2-to-throw': ('Rzucać', None),
    'a2-to-catch': ('Łapać', None),
    'a2-to-build': ('Budować', None),
    'a2-to-grow': ('Rosnąć', None),
    'a2-to-fall': ('Upadać', None),
    'a2-to-climb': ('Wspinać się', None),
    'a2-to-jump': ('Skakać', None),
    'a2-to-laugh': ('Śmiać się', None),
    'a2-to-cry': ('Płakać', None),
    'a2-to-smile': ('Uśmiechać się', None),
    'a2-to-shout': ('Krzyczeć', None),
    'a2-to-whisper': ('Szeptać', None),
    'a2-to-hug': ('Przytulać', None),
    'a2-to-kiss': ('Całować', None),
    'a2-to-touch': ('Dotykać', None),
    'a2-to-smell': ('Wąchać', None),
    'a2-to-taste': ('Smakować', None),
    'a2-to-wash-oneself': ('Myć się', None),
    'a2-to-hide': ('Chować się', None),
    'a2-interesting': ('Ciekawy', None),
    'a2-boring': ('Nudny', None),
    'a2-comfortable': ('Wygodny', None),
    'a2-dangerous': ('Niebezpieczny', None),
    'a2-safe': ('Bezpieczny', None),
    'a2-noisy': ('Głośny', None),
    'a2-busy': ('Zajęty', None),
    'a2-heavy': ('Ciężki', None),
    'a2-light-weight': ('Lekki', None),
    'a2-wide': ('Szeroki', None),
    'a2-narrow': ('Wąski', None),
    'a2-soft': ('Miękki', None),
    'a2-hard-firm': ('Twardy', None),
    'a2-wet': ('Mokry', None),
    'a2-dry': ('Suchy', None),
    'a2-rich': ('Bogaty', None),
    'a2-poor': ('Biedny', None),
    'a2-famous': ('Sławny', None),
    'a2-popular': ('Popularny', None),
    'a2-modern': ('Nowoczesny', None),
    'a2-traditional': ('Tradycyjny', None),
    'a2-ready': ('Gotowy', None),
    'a2-sure': ('Pewny', None),
    'a2-wrong': ('Niewłaściwy', None),
    'a2-correct': ('Poprawny', None),
    'a2-strange': ('Dziwny', None),
    'a2-same': ('Taki sam', None),
    'a2-different': ('Inny', None),
    'a2-last-week': ('W zeszłym tygodniu', None),
    'a2-next-week': ('W przyszłym tygodniu', None),
    'a2-this-month': ('W tym miesiącu', None),
    'a2-last-year': ('W zeszłym roku', None),
    'a2-next-year': ('W przyszłym roku', None),
    'a2-at-the-end': ('Na końcu', None),
    'a2-at-the-beginning': ('Na początku', None),
    'a2-twice': ('Dwa razy', None),
    'a2-once': ('Raz', None),
    'a2-in-a-hurry': ('W pośpiechu', None),
    'a2-for-a-long-time': ('Przez długi czas', None),
    'a2-recently': ('Ostatnio', None),
    'a2-already': ('Już', None),
    'a2-still': ('Nadal', None),
    'a2-not-yet': ('Jeszcze nie', None),
    'a2-until': ('Aż do', None),
    'a2-since': ('Odkąd', None),
    'a2-during': ('Podczas', None),
    'a2-ago': ('Temu', None),
    'a2-at-least': ('Przynajmniej', None),
    'a2-right-away': ('Od razu', None),
    'a2-finally': ('W końcu', None),
    'a2-suddenly': ('Nagle', None),
    'a2-the-day-after-tomorrow': ('Pojutrze', None),
    'a2-conversation': ('Rozmowa', None),
    'a2-question': ('Pytanie', None),
    'a2-answer-noun': ('Odpowiedź', None),
    'a2-opinion': ('Opinia', None),
    'a2-to-describe': ('Opisywać', None),
    'a2-to-promise': ('Obiecywać', None),
    'a2-to-suggest': ('Sugerować', None),
    'a2-to-complain': ('Skarżyć się', None),
    'a2-to-apologize': ('Przepraszać', None),
    'a2-to-thank': ('Dziękować', None),
    'a2-joke': ('Żart', None),
    'a2-story': ('Historia', None),
    'a2-news': ('Wiadomości', None),
    'a2-to-argue': ('Kłócić się', None),
    'a2-to-discuss': ('Dyskutować', None),
    'a2-secret': ('Sekret', None),
    'a2-to-mean': ('Znaczyć', None),
    'a2-to-pronounce': ('Wymawiać', None),
    'a2-to-translate': ('Tłumaczyć', None),
    'a2-word': ('Słowo', None),
    'a2-sentence': ('Zdanie', None),
    'a2-language': ('Język', None),
    'a2-to-spell': ('Literować', None),
    'a2-to-lie': ('Kłamać', None),
    'a2-truth': ('Prawda', None),
    'a2-to-chat': ('Gawędzić', None),
    'a2-accent': ('Akcent', None),
    'a2-fluent': ('Płynny', None),
    'a2-to-get-married': ('Pobierać się', None),
    'a2-wedding': ('Ślub', None),
    'a2-couple': ('Parka', None),
    'a2-childhood': ('Dzieciństwo', None),
    'a2-teenager': ('Nastolatek', None),
    'a2-adult': ('Dorosły', None),
    'a2-to-grow-up': ('Dorastać', None),
    'a2-anniversary': ('Rocznica', None),
    'a2-party': ('Impreza', None),
    'a2-guest': ('Gość', None),
    'a2-to-celebrate': ('Świętować', None),
    'a2-to-be-born': ('Rodzić się', None),
    'a2-to-die': ('Umierać', None),
    'a2-relatives': ('Krewni', None),
    'a2-twins': ('Bliźniaki', None),
    'a2-only-child': ('Jedynak', None),
    'a2-to-take-care-of': ('Opiekować się', None),
    'a2-nephew': ('Bratanek', None),
    'a2-niece': ('Bratanica', None),
    'a2-grandchild': ('Wnuk', None),
    'a2-single': ('Wolny (stanu)', None),
    'a2-divorced': ('Rozwiedziony', None),
    'a2-christmas': ('Boże Narodzenie', None),
    'a2-new-year': ('Nowy Rok', None),
    'a2-cake': ('Ciasto', None),
    'a2-candle': ('Świeczka', None),
    'a2-lesson': ('Lekcja', None),
    'a2-course': ('Kurs', None),
    'a2-to-practice': ('Praktykować', None),
    'a2-mistake': ('Błąd', None),
    'a2-to-correct': ('Poprawiać', None),
    'a2-grade-mark': ('Ocena', None),
    'a2-to-pass-an-exam': ('Zdawać egzamin', None),
    'a2-to-fail-an-exam': ('Oblewać egzamin', None),
    'a2-to-graduate': ('Kończyć studia', None),
    'a2-degree': ('Dyplom', None),
    'a2-subject': ('Przedmiot', None),
    'a2-math': ('Matematyka', None),
    'a2-history': ('Historia (przedmiot)', None),
    'a2-science': ('Nauka', None),
    'a2-art': ('Sztuka', None),
    'a2-dictionary': ('Słownik', None),
    'a2-notebook': ('Zeszyt', None),
    'a2-to-memorize': ('Zapamiętywać', None),
    'a2-to-review': ('Powtarzać materiał', None),
    'a2-classroom': ('Sala lekcyjna', None),
    'a2-semester': ('Semestr', None),
    'a2-scholarship': ('Stypendium', None),
    'a2-to-register': ('Zapisywać się', None),
    'a2-example': ('Przykład', None),
    'a2-level': ('Poziom', None),
    'a2-beginner': ('Początkujący', None),
    'a2-to-save-money': ('Oszczędzać', None),
    'a2-bank-account': ('Konto bankowe', None),
    'a2-to-withdraw': ('Wypłacać', None),
    'a2-to-deposit': ('Wpłacać', None),
    'a2-atm': ('Bankomat', None),
    'a2-loan': ('Pożyczka', None),
    'a2-debt': ('Dług', None),
    'a2-to-borrow': ('Pożyczać (od kogoś)', None),
    'a2-to-lend': ('Pożyczać (komuś)', None),
    'a2-to-owe': ('Być winnym', None),
    'a2-tax': ('Podatek', None),
    'a2-bill-utility': ('Rachunek', None),
    'a2-budget': ('Budżet', None),
    'a2-to-afford': ('Móc sobie pozwolić', None),
    'a2-interest-bank': ('Odsetki', None),
    'a2-coin': ('Moneta', None),
    'a2-to-exchange-money': ('Wymieniać', None),
    'a2-exchange-rate': ('Kurs wymiany', None),
    'a2-credit-card': ('Karta kredytowa', None),
    'a2-to-cost': ('Kosztować', None),
    'a2-salary-raise': ('Podwyżka', None),
    'a2-expensive-habit': ('Kosztowny nawyk', None),
    'a2-invoice': ('Faktura', None),
    'a2-payment': ('Płatność', None),
    'a2-to-miss-someone': ('Tęsknić za', None),
    'a2-to-worry': ('Martwić się', None),
    'a2-to-enjoy': ('Cieszyć się', None),
    'a2-to-hate': ('Nienawidzić', None),
    'a2-to-be-afraid-of': ('Bać się', None),
    'a2-ashamed': ('Zawstydzony', None),
    'a2-jealous': ('Zazdrosny', None),
    'a2-embarrassed': ('Zażenowany', None),
    'a2-disappointed': ('Rozczarowany', None),
    'a2-grateful': ('Wdzięczny', None),
    'a2-relieved': ('Odczuwający ulgę', None),
    'a2-confused': ('Zdezorientowany', None),
    'a2-curious': ('Ciekawski', None),
    'a2-hopeful': ('Pełen nadziei', None),
    'a2-frustrated': ('Sfrustrowany', None),
    'a2-stressed': ('Zestresowany', None),
    'a2-in-a-good-mood': ('W dobrym nastroju', None),
    'a2-in-a-bad-mood': ('W złym nastroju', None),
    'a2-to-cheer-up': ('Rozweselać się', None),
    'a2-to-calm-down': ('Uspokajać się', None),
    'a2-to-get-angry': ('Złościć się', None),
    'a2-to-fall-in-love': ('Zakochiwać się', None),
    'a2-mood': ('Nastrój', None),
    'a2-satisfied': ('Zadowolony', None),
    'a2-forest': ('Las', None),
    'a2-lake': ('Jezioro', None),
    'a2-island': ('Wyspa', None),
    'a2-desert': ('Pustynia', None),
    'a2-field': ('Pole', None),
    'a2-farm': ('Gospodarstwo', None),
    'a2-animal': ('Zwierzę', None),
    'a2-insect': ('Owad', None),
    'a2-mosquito': ('Komar', None),
    'a2-bee': ('Pszczoła', None),
    'a2-butterfly': ('Motyl', None),
    'a2-snake': ('Wąż', None),
    'a2-lion': ('Lew', None),
    'a2-elephant': ('Słoń', None),
    'a2-monkey': ('Małpa', None),
    'a2-rabbit': ('Królik', None),
    'a2-pig': ('Świnia', None),
    'a2-sheep': ('Owca', None),
    'a2-plant': ('Roślina', None),
    'a2-grass': ('Trawa', None),
    'a2-leaf': ('Liść', None),
    'a2-rock': ('Skała', None),
    'a2-sand': ('Piasek', None),
    'a2-ocean': ('Ocean', None),
    'a2-wave': ('Fala', None),
    'a2-thunder': ('Grzmot', None),
    'a2-fog': ('Mgła', None),
    'a2-temperature': ('Temperatura', None),
    'a2-laptop': ('Laptop', None),
    'a2-keyboard': ('Klawiatura', None),
    'a2-printer': ('Drukarka', None),
    'a2-file': ('Plik', None),
    'a2-folder': ('Folder', None),
    'a2-to-print': ('Drukować', None),
    'a2-to-click': ('Klikać', None),
    'a2-to-type': ('Pisać na klawiaturze', None),
    'a2-to-search-online': ('Szukać w internecie', None),
    'a2-social-media': ('Media społecznościowe', None),
    'a2-to-post': ('Publikować', None),
    'a2-to-share': ('Udostępniać', None),
    'a2-video': ('Wideo', None),
    'a2-photo': ('Zdjęcie', None),
    'a2-selfie': ('Selfie', None),
    'a2-headphones': ('Słuchawki', None),
    'a2-speaker': ('Głośnik', None),
    'a2-battery': ('Bateria', None),
    'a2-to-turn-on': ('Włączać', None),
    'a2-to-turn-off': ('Wyłączać', None),
    'a2-volume': ('Głośność', None),
    'a2-channel': ('Kanał', None),
    'a2-podcast': ('Podcast', None),
    'a2-screenshot': ('Zrzut ekranu', None),
    'a2-update': ('Aktualizacja', None),
    'a2-notification': ('Powiadomienie', None),
    'a2-to-log-in': ('Logować się', None),
    'a2-subtitles': ('Napisy', None),
    'a2-what-do-you-think': ('Co o tym myślisz?', None),
    'a2-it-depends': ('To zależy', None),
    'a2-im-not-sure': ('Nie jestem pewien', None),
    'a2-let-me-think': ('Pozwól mi pomyśleć', None),
    'a2-what-a-pity': ('Jaka szkoda', None),
    'a2-never-mind': ('Nieważne', None),
    'a2-hurry-up': ('Pospiesz się', None),
    'a2-watch-out': ('Uważaj!', None),
    'a2-thats-a-good-idea': ('To dobry pomysł', None),
    'a2-are-you-kidding': ('Żartujesz?', None),
    'a2-its-up-to-you': ('To zależy od ciebie', None),
    'a2-im-on-my-way': ('Już idę', None),
    'a2-same-here': ('Ja też', None),
    'a2-me-neither': ('Ja też nie', None),
    'a2-by-the-way': ('Nawiasem mówiąc', None),
    'a2-in-my-opinion': ('Moim zdaniem', None),
    'a2-to-be-honest': ('Szczerze mówiąc', None),
    'a2-actually': ('Właściwie', None),
    'a2-anyway': ('W każdym razie', None),
    'a2-for-example': ('Na przykład', None),
    'a2-sorry-im-late': ('Przepraszam za spóźnienie', None),
    'a2-no-way': ('W żadnym wypadku!', None),
    'a2-that-makes-sense': ('To ma sens', None),
    'a2-good-point': ('Dobra uwaga', None),
    'a2-banana': ('Banan', None),
    'a2-orange-fruit': ('Pomarańcza', None),
    'a2-grapes': ('Winogrona', None),
    'a2-strawberry': ('Truskawka', None),
    'a2-lemon': ('Cytryna', None),
    'a2-watermelon': ('Arbuz', None),
    'a2-peach': ('Brzoskwinia', None),
    'a2-pear': ('Gruszka', None),
    'a2-carrot': ('Marchewka', None),
    'a2-lettuce': ('Sałata', None),
    'a2-cucumber': ('Ogórek', None),
    'a2-bell-pepper': ('Papryka', None),
    'a2-mushroom': ('Grzyb', None),
    'a2-corn': ('Kukurydza', None),
    'a2-beans': ('Fasola', None),
    'a2-spinach': ('Szpinak', None),
    'a2-cabbage': ('Kapusta', None),
    'a2-pumpkin': ('Dynia', None),
    'a2-nuts': ('Orzechy', None),
    'a2-coconut': ('Kokos', None),
    'a2-mango': ('Mango', None),
    'a2-pineapple': ('Ananas', None),
    'a2-cherry': ('Wiśnia', None),
    'a2-avocado': ('Awokado', None),
    'a2-ripe': ('Dojrzały', None),
    'a2-fresh': ('Świeży', None),
    'a2-kilogram': ('Kilogram', None),
    'a2-gram': ('Gram', None),
    'a2-liter': ('Litr', None),
    'a2-meter': ('Metr', None),
    'a2-kilometer': ('Kilometr', None),
    'a2-centimeter': ('Centymetr', None),
    'a2-piece': ('Kawałek', None),
    'a2-slice': ('Plasterek', None),
    'a2-dozen': ('Tuzin', None),
    'a2-pair': ('Para', None),
    'a2-percent': ('Procent', None),
    'a2-degree-temperature': ('Stopień', None),
    'a2-a-bit': ('Trochę', None),
    'a2-a-lot': ('Dużo', None),
    'a2-several': ('Kilka', None),
    'a2-double': ('Podwójny', None),
    'a2-weight': ('Waga', None),
    'a2-height': ('Wzrost', None),
    'a2-length': ('Długość', None),
    'a2-distance': ('Odległość', None),
    'a2-speed': ('Prędkość', None),
    'a2-total': ('Suma', None),
    'a2-almost': ('Prawie', None),
    'a2-only': ('Tylko', None),
    'a2-engineer': ('Inżynier', None),
    'a2-lawyer': ('Prawnik', None),
    'a2-chef': ('Kucharz', None),
    'a2-driver': ('Kierowca', None),
    'a2-farmer': ('Rolnik', None),
    'a2-artist': ('Artysta', None),
    'a2-musician': ('Muzyk', None),
    'a2-actor': ('Aktor', None),
    'a2-writer': ('Pisarz', None),
    'a2-journalist': ('Dziennikarz', None),
    'a2-police-officer': ('Policjant', None),
    'a2-firefighter': ('Strażak', None),
    'a2-scientist': ('Naukowiec', None),
    'a2-programmer': ('Programista', None),
    'a2-designer': ('Projektant', None),
    'a2-manager': ('Kierownik', None),
    'a2-salesperson': ('Sprzedawca', None),
    'a2-mechanic': ('Mechanik', None),
    'a2-electrician': ('Elektryk', None),
    'a2-plumber': ('Hydraulik', None),
    'a2-pilot': ('Pilot', None),
    'a2-accountant': ('Księgowy', None),
    'a2-architect': ('Architekt', None),
    'a2-hairdresser': ('Fryzjer', None),
    'a2-soldier': ('Żołnierz', None),
    'a2-baker': ('Piekarz', None),
    'a2-basketball': ('Koszykówka', None),
    'a2-tennis': ('Tenis', None),
    'a2-baseball': ('Baseball', None),
    'a2-volleyball': ('Siatkówka', None),
    'a2-running': ('Bieganie', None),
    'a2-cycling': ('Kolarstwo', None),
    'a2-skiing': ('Narciarstwo', None),
    'a2-surfing': ('Surfing', None),
    'a2-yoga': ('Joga', None),
    'a2-chess': ('Szachy', None),
    'a2-cards-game': ('Karty', None),
    'a2-board-game': ('Gra planszowa', None),
    'a2-video-game': ('Gra wideo', None),
    'a2-puzzle': ('Puzzle', None),
    'a2-to-go-camping': ('Jechać na kemping', None),
    'a2-picnic': ('Piknik', None),
    'a2-fishing': ('Wędkarstwo', None),
    'a2-race': ('Wyścig', None),
    'a2-competition': ('Zawody', None),
    'a2-referee': ('Sędzia', None),
    'a2-coach': ('Trener', None),
    'a2-medal': ('Medal', None),
    'a2-score': ('Wynik', None),
    'a2-fan-supporter': ('Kibic', None),
    'a2-to-train': ('Trenować', None),
}
