# -*- coding: utf-8 -*-
LANG = 'ind'
SENTENCES = {
    'b1-dr1': ['Saya', 'sedang belajar', 'menyetir'],
    'b1-dr2': ['Biasanya', 'saya bangun', 'pagi-pagi'],
    'b1-dr3': ['Kemarin', 'saya membersihkan', 'seluruh', 'rumah'],
    'b1-dr4': ['Saya', 'tidak pernah', 'absen kerja', 'sehari pun'],
    'b1-fs1': ['Saudara saya', 'tidak', 'berolahraga'],
    'b1-fs2': ['Kita sebaiknya', 'menelepon', 'orang tua', 'kita'],
    'b1-fs3': ['Bisakah Anda', 'membantu saya', 'dengan ini,', 'tolong?'],
    'b1-fs4': ['Saudari saya', 'lebih', 'cerewet', 'daripada saya'],
    'b1-te1': ['Kemarin', 'saya mengunjungi', 'kota', 'baru'],
    'b1-te2': ['Jika hujan,', 'kami akan tinggal', 'di hotel'],
    'b1-te3': ['Saya', 'belum pernah', 'ke Jepang'],
    'b1-te4': ['Bisakah Anda', 'merekomendasikan', 'hotel yang bagus?'],
    'b1-op1': ['Musiknya', 'sangat', 'keras'],
    'b1-op2': ['Kota ini', 'lebih mahal', 'daripada', 'kota itu'],
    'b1-op3': ['Saya rasa', 'buku ini', 'sangat', 'menarik'],
    'b1-op4': ['Menurut saya,', 'kita sebaiknya', 'berangkat', 'lebih awal'],
    'c2-s01': ['Sejujurnya,', 'saya akan berpikir', 'dua kali', 'sebelum menandatangani', 'hal semacam itu'],
    'c2-s02': ['Bukannya', 'saya tidak peduli,', 'tapi saya', 'sudah tidak punya apa-apa lagi', 'untuk diberikan'],
    'c2-s03': ['Apa pun yang kamu lakukan,', 'jangan biarkan', 'dia membujukmu', 'untuk melakukannya'],
    'c2-s04': ['Seandainya saya tahu', 'ini akan berlarut-larut', 'selama ini,', 'saya tidak akan pernah', 'setuju'],
    'c2-s05': ['Dia menganggapnya sepele,', 'tapi jelas terlihat', 'itu sudah', 'membuatnya terganggu'],
    'c2-s06': ['Katakan apa pun', 'tentang dia,', 'tapi', 'dia bisa', 'menyelesaikan segala sesuatu'],
    'c2-s07': ['Saya tidak akan', 'minta maaf', 'atas sesuatu', 'yang bahkan tidak', 'saya lakukan'],
    'c2-s08': ['Pada saat', 'mereka akhirnya mulai', 'memperbaikinya,', 'kerusakan', 'sudah terjadi'],
    'c2-s09': ['Di antara kita saja,', 'saya rasa', 'kesepakatan ini', 'tidak akan', 'berhasil'],
    'c2-s10': ['Kamu pasti mengira', 'mereka sudah', 'belajar', 'sekarang ini,', 'bukan?'],
    'c2-s11': ['Baru saja', 'kami duduk,', 'alarm kebakaran', 'sudah', 'berbunyi'],
    'c2-s12': ['Kalau kamu', 'tidak keberatan,', 'saya lebih suka', 'ini', 'tidak resmi'],
    'c1-m01': ['Pemerintah', 'mengumumkan', 'langkah-langkah baru', 'untuk menekan', 'inflasi'],
    'c1-m02': ['Menurut laporan itu,', 'pengangguran', 'turun', 'untuk bulan ketiga', 'berturut-turut'],
    'c1-m03': ['Saya tidak pernah bilang', 'saya akan pergi;', 'saya bilang', 'saya butuh', 'waktu'],
    'c1-m04': ['Apa pun yang terjadi', 'malam ini,', 'jangan buka', 'pintu itu'],
    'c1-m05': ['Para ilmuwan', 'memperingatkan', 'bahwa gletser itu', 'bisa menghilang', 'dalam satu dekade'],
    'c1-m06': ['Jika kamu sudah', 'memberitahuku', 'yang sebenarnya,', 'semua ini', 'tidak akan terjadi'],
    'c1-m07': ['Tersangka', 'ditangkap', 'tak lama setelah', 'polisi menerima', 'laporan anonim'],
    'c1-m08': ['Sejujurnya,', 'saya rasa', 'kita berdua yang bersalah', 'atas apa yang terjadi'],
    'c1-m09': ['Perusahaan itu', 'membantah', 'tuduhan tersebut', 'tetapi menolak', 'memberikan komentar lebih lanjut'],
    'c1-m10': ['Kamu tidak tahu', 'apa yang sudah', 'kukorbankan', 'untuk sampai di sini'],
    'c1-m11': ['Para pemilih', 'akan pergi ke', 'tempat pemungutan suara', 'pada hari Minggu,', 'di tengah ketidakpastian yang meningkat'],
    'c1-m12': ['Bisa dibilang', 'semuanya tidak berjalan', 'seperti yang', 'sudah kurencanakan'],
}
DIALOGUES = {
    'd-a2-01': ['Halo, saya Marta. Senang bertemu Anda.', 'Senang bertemu Anda juga, saya Alex.', 'Tidak, terima kasih.', 'Itu di sebelah kanan.', 'Sekarang pukul tiga.'],
    'd-a2-02': ['Anda berasal dari mana?', 'Saya berasal dari Chicago, di Amerika Serikat.', 'Usia saya dua puluh tahun.', 'Saya suka kopi.', 'Saya bekerja di bank.'],
    'd-a2-03': ['Apa pekerjaan Anda?', 'Saya seorang desainer, saya bekerja dari rumah.', 'Saya tinggal dekat taman.', 'Saya lebih suka teh.', 'Besok akan hujan.'],
    'd-a2-04': ['Sudah berapa lama Anda di sini?', 'Saya sudah di sini selama dua bulan.', 'Harganya sepuluh euro.', 'Itu tutup pada hari Minggu.', 'Saya punya dua saudara.'],
    'd-a2-05': ['Apakah Anda punya saudara?', 'Ya, seorang kakak perempuan.', 'Ya, pukul delapan.', 'Tidak, itu sangat mahal.', 'Itu ada di dapur.'],
    'd-a2-06': ['Terima kasih sudah datang, sampai jumpa lagi!', 'Terima kasih kembali, ini luar biasa! Sampai jumpa lagi.', 'Saya ingin kopi.', 'Maaf, saya tidak mengerti.', 'Kamar mandi ada di sana.'],
    'd-a2-07': ['Dingin sekali hari ini, ya?', 'Ya, sangat dingin. Dan katanya besok akan turun salju.', 'Ya, nama saya Alex.', 'Tidak, saya tidak punya saudara.', 'Harganya lima euro.'],
    'd-a2-08': ['Apa rencana Anda untuk akhir pekan?', 'Saya akan mengunjungi orang tua saya.', 'Saya bekerja di kantor.', 'Itu di sebelah kiri.', 'Saya lebih suka warna merah.'],
    'd-a2-09': ['Bagaimana kalau kita minum kopi besok?', 'Tentu saja! Apakah jam sepuluh cocok untuk Anda?', 'Saya berasal dari Madrid.', 'Saya punya seekor anjing.', 'Sedang hujan deras.'],
    'd-a2-10': ['Jam berapa filmnya mulai?', 'Mulai jam setengah delapan.', 'Itu sangat jauh.', 'Saya sangat menyukainya.', 'Saya seorang pelajar.'],
    'd-a2-11': ['Bagaimana hari Anda hari ini?', 'Cukup baik, tapi saya lelah.', 'Itu dua euro.', 'Saya tinggal di lantai tiga.', 'Itu saudari saya.'],
    'd-a2-12': ['Anda mau ke mana?', 'Ke supermarket, saya tidak punya apa-apa untuk makan malam.', 'Usia saya tiga puluh tahun.', 'Cuacanya sangat panas.', 'Ya, saya bisa berbahasa sedikit.'],
    'd-b1-01': ['Lama tidak bertemu! Apa yang sedang Anda lakukan akhir-akhir ini?', 'Saya ganti pekerjaan dua bulan lalu dan saya sangat senang.', 'Keretanya berangkat jam sembilan.', 'Saya lebih suka teh daripada kopi.', 'Itu dua blok dari sini.'],
    'd-b1-02': ['Akhir-akhir ini saya sangat stres dengan pekerjaan.', 'Saya turut prihatin. Apakah Anda ingin membicarakannya?', 'Saya membeli sepeda baru.', 'Filmnya mulai jam delapan.', 'Saudari saya tinggal di Roma.'],
    'd-b1-03': ['Bagaimana perjalanannya? Ceritakan semuanya!', 'Luar biasa. Makanannya, orang-orangnya... saya sudah ingin kembali.', 'Saya perlu membeli susu.', 'Saya bekerja dari jam sembilan sampai jam lima.', 'Bulan Januari cuacanya dingin.'],
    'd-b1-04': ['Lucía dan saya putus pekan lalu.', 'Wah, saya tidak tahu. Bagaimana perasaan Anda sekarang?', 'Selamat! Itu kabar yang bagus.', 'Jam berapa kita bertemu?', 'Museum itu tutup pada hari Senin.'],
    'd-b1-05': ['Apakah Anda masih pergi ke pusat kebugaran?', 'Sebenarnya, saya sudah berhenti. Sekarang saya lari pagi-pagi.', 'Ya, rotinya sangat enak.', 'Saya tinggal di lantai lima.', 'Besok hari Selasa.'],
    'd-b1-06': ['Apakah Anda sudah menonton serial yang saya rekomendasikan? Bagaimana menurut Anda?', 'Saya langsung ketagihan sejak episode pertama, meskipun akhirnya agak mengecewakan.', 'Harganya dua puluh euro.', 'Saya punya dua kucing.', 'Kamar mandinya ada di belakang.'],
    'd-b1-07': ['Bagaimana kalau kita mendaki hari Sabtu?', 'Hari Sabtu saya tidak bisa, ada pernikahan. Apakah hari Minggu cocok untuk Anda?', 'Ya, nama saya Alex.', 'Lampu lalu lintasnya merah.', 'Wine ini berasal dari Chili.'],
    'd-b1-08': ['Maaf, saya akan datang terlambat lima belas menit.', 'Tidak apa-apa, saya akan menunggu Anda di kafe di sudut jalan.', 'Saya suka warna biru.', 'Hari ini sangat berangin.', 'Ulang tahun saya pada bulan Mei.'],
    'd-b1-09': ['Kita bagi tagihannya atau saya yang bayar kali ini?', 'Kita bagi saja, tapi lain kali saya yang traktir.', 'Sedang hujan lagi.', 'Saya lahir di Chicago.', 'Bus itu lewat setiap sepuluh menit.'],
    'd-b1-10': ['Bisakah Anda membantu saya pindah rumah hari Kamis?', 'Tentu saja, Anda bisa mengandalkan saya. Saya selesai kerja jam enam, apakah itu cocok?', 'Kejunya ada di kulkas.', 'Saya sudah belajar bahasa Jepang selama satu tahun.', 'Pantainya jauh.'],
    'd-b1-11': ['Bagaimana kalau kita makan malam di tempat panggang yang baru?', 'Sebenarnya saya vegetarian. Apakah Anda tahu tempat dengan lebih banyak pilihan?', 'Setiap hari Senin saya ada kelas piano.', 'Jalannya ditutup.', 'Ayah saya seorang dokter.'],
    'd-b1-12': ['Bisakah Anda meminjamkan saya lima puluh euro sampai hari Jumat?', 'Ya, tidak masalah. Saya akan mentransfernya sekarang.', 'Saya lebih suka tempat duduk dekat jendela daripada lorong.', 'Cuacanya cerah di pantai.', 'Nenek saya berusia delapan puluh tahun.'],
    'd-b2-01': ['Saya rasa kerja jarak jauh merugikan kerja sama tim.', 'Saya tidak begitu yakin. Menurut pengalaman saya, dengan alat yang baik tim bisa bekerja sama baiknya atau bahkan lebih baik.', 'Laporannya ada di folder biru.', 'Saya lebih suka kopi tanpa gula.', 'Besok ada mogok kereta.'],
    'd-b2-02': ['Media sosial membuat kita semakin kesepian.', 'Sebagian benar, meskipun media sosial juga membantu banyak orang menemukan komunitas yang tidak mereka miliki di dekat mereka.', 'Kata sandi saya terdiri dari delapan karakter.', 'Restoran itu tutup jam sebelas.', 'Saya membeli tiketnya kemarin.'],
    'd-b2-03': ['Apakah menurut Anda mobil sebaiknya dilarang di pusat kota?', 'Ya, asalkan transportasi umum diperbaiki; jika tidak, itu hanya memindahkan masalahnya ke lingkungan lain.', 'Pusat kota berjarak sepuluh menit jalan kaki.', 'Mobil saya berwarna merah.', 'Saya tidak bekerja pada hari Minggu.'],
    'd-b2-04': ['Belajar enam bahasa sekaligus itu mustahil.', 'Sulit, ya, tapi bukan mustahil: bahasa-bahasa Roman saling memperkuat satu sama lain, dan bahasa Jepang serta Mandarin berbagi banyak karakter.', 'Hari ini suhunya dua puluh derajat.', 'Saya ada janji dengan dokter gigi.', 'Paketnya tiba hari Kamis.'],
    'd-b2-05': ['Sewanya akan naik dua puluh persen bulan depan.', 'Saya mengerti biaya-biaya sudah naik, tapi dua puluh persen itu banyak. Bisakah kita sepakat sepuluh persen dan memperpanjang kontrak selama dua tahun?', 'Kamar mandinya ada di ujung lorong.', 'Saya sangat suka pemandangan dari sini.', 'Hari ini ulang tahun saya.'],
    'd-b2-06': ['Pekerjaannya akan terlambat dua minggu.', 'Apa alasannya secara pasti? Saya butuh tanggal yang pasti untuk memberi tahu penyewa.', 'Ubinnya berwarna abu-abu.', 'Saya bekerja di bidang properti.', 'Ada apotek di sudut jalan.'],
    'd-b2-07': ['Maaf, permintaan pengembalian dana Anda telah ditolak.', 'Menurut kebijakan Anda, saya punya waktu tiga puluh hari untuk mengembalikannya dan baru dua belas hari berlalu. Dengan siapa saya bisa bicara untuk meninjau kembali keputusan ini?', 'Saya ingin meja untuk empat orang.', 'Saya tinggal dekat sungai.', 'Saudara saya seorang insinyur.'],
    'd-b2-08': ['Semalam musiknya terlalu keras, saya tidak bisa tidur.', 'Anda benar sekali, saya sangat minta maaf. Mulai sekarang saya akan mengecilkan volumenya setelah jam sepuluh.', 'Supermarketnya buka jam delapan.', 'Saya sangat suka anjing Anda.', 'Saya sedang belajar bahasa Italia.'],
    'd-c2-01': ['Parkir yang hebat, apakah SIM Anda didapat dari kupon undian?', 'Setidaknya saya punya mobil, Anda datang naik skuter.', 'Saya sangat minta maaf, itu tidak akan terjadi lagi.', 'Mobilnya berwarna biru.', 'Hari ini sangat panas.'],
    'd-c2-02': ['Saya bisa mengalahkan Anda dalam hal apa pun, silakan pilih.', 'Baiklah: mari lihat siapa yang tahan lebih lama tanpa melihat ponsel.', 'Anda benar, Anda lebih baik dalam segala hal.', 'Pertandingannya mulai jam delapan.', 'Saudari saya tinggal di Sevilla.'],
    'd-c2-03': ['Ponsel itu masih berfungsi? Itu barang museum.', 'Hei, punya saya itu vintage, bukan usang.', 'Ya, saya sebaiknya membeli yang baru besok juga.', 'Museumnya tutup pada hari Senin.', 'Saya butuh pengisi daya.'],
    'd-c2-04': ['Yah, tidak buruk juga, untuk ukuran Anda.', 'Datang dari seseorang yang bahkan bisa menggosongkan air, saya anggap itu pujian.', 'Terima kasih, saya senang Anda menyukainya.', 'Garamnya ada di meja.', 'Saya makan malam jam sembilan.'],
    'd-c2-05': ['Media sosial telah menghancurkan debat publik, titik.', 'Mereka memang punya andil, ya, tapi dulu debatnya hanya dikendalikan oleh segelintir surat kabar.', 'Setuju sepenuhnya, tidak ada lagi yang perlu dibicarakan.', 'Akun saya punya seribu pengikut.', 'Surat kabarnya tiba pada pagi hari.'],
    'd-c2-06': ['Anak muda zaman sekarang tidak mau bekerja, sesederhana itu.', 'Atau mungkin mereka tidak mau bekerja demi gaji yang bahkan tidak cukup untuk membayar sewa?', 'Benar, kami memang pemalas.', 'Saya bekerja di kantor.', 'Sewanya dibayar pada tanggal satu.'],
    'd-c2-07': ['Sebaiknya mobil dilarang di seluruh pusat kota, tanpa pengecualian.', 'Jangan tanpa pengecualian: bagaimana dengan ambulans, pengiriman barang, orang dengan mobilitas terbatas?', 'Ya, mari kita larang semuanya mulai besok.', 'Mobil saya berwarna merah.', 'Pusat kota punya banyak toko.'],
    'd-c2-08': ['Belajar bahasa sudah tidak masuk akal lagi, AI bisa menerjemahkan semuanya.', 'AI menerjemahkan kata-kata, ya; tapi leluconnya, nadanya, dan kepercayaan orang lain tidak bisa diterjemahkan oleh siapa pun.', 'Benar, saya berhenti kursus hari ini juga.', 'Aplikasinya gratis.', 'Saya belajar bahasa Spanyol setiap hari Selasa.'],
}
