# -*- coding: utf-8 -*-
LANG = 'de'
WORDS = {
    'c1-broadcast': ('Sendung', None),
    'c1-coverage': ('Berichterstattung', None),
    'c1-correspondent': ('Korrespondent', None),
    'c1-anchor-news': ('Nachrichtensprecher', None),
    'c1-editorial': ('Leitartikel', None),
    'c1-slant-bias': ('Tendenz (Voreingenommenheit)', None),
    'c1-to-leak': ('durchsickern lassen', None),
    'c1-source-journalism': ('Quelle', None),
    'c1-whistleblower': ('Whistleblower', None),
    'c1-censorship': ('Zensur', None),
    'c1-propaganda': ('Propaganda', None),
    'c1-misinformation': ('Fehlinformation', None),
    'c1-fact-check': ('Faktencheck', None),
    'c1-viral': ('viral', None),
    'c1-clickbait': ('Klickköder', None),
    'c1-tabloid': ('Boulevardblatt', None),
    'c1-press-conference': ('Pressekonferenz', None),
    'c1-press-release': ('Pressemitteilung', None),
    'c1-exclusive-story': ('Exklusivbericht', None),
    'c1-breaking-news': ('Eilmeldung', None),
    'c1-viewership': ('Zuschauerzahl', None),
    'c1-subscriber': ('Abonnent', None),
    'c1-paywall': ('Bezahlschranke', None),
    'c1-influencer': ('Influencer', None),
    'c1-to-trend': ('im Trend liegen', None),
    'c1-hashtag': ('Hashtag', None),
    'c1-op-ed': ('Gastkommentar', None),
    'c1-byline': ('Autorenzeile', None),
    'c1-segment-tv': ('Beitrag (Sendung)', None),
    'c1-airtime': ('Sendezeit', None),
    'c1-methodology': ('Methodik', None),
    'c1-empirical': ('empirisch', None),
    'c1-qualitative': ('qualitativ', None),
    'c1-quantitative': ('quantitativ', None),
    'c1-variable': ('Variable', None),
    'c1-correlation': ('Korrelation', None),
    'c1-causation': ('Kausalität', None),
    'c1-sample-study': ('Stichprobe', None),
    'c1-peer-review': ('Peer-Review', None),
    'c1-citation': ('Zitat (Quellenangabe)', None),
    'c1-abstract-summary': ('Abstract (Zusammenfassung)', None),
    'c1-dissertation': ('Dissertation', None),
    'c1-scholar': ('Gelehrter', None),
    'c1-discipline-field': ('Fachrichtung', None),
    'c1-paradigm': ('Paradigma', None),
    'c1-phenomenon': ('Phänomen', None),
    'c1-premise': ('Prämisse', None),
    'c1-inference': ('Schlussfolgerung', None),
    'c1-to-infer': ('folgern', None),
    'c1-to-deduce': ('deduzieren', None),
    'c1-rigorous': ('rigoros', None),
    'c1-nuanced': ('nuanciert', None),
    'c1-to-synthesize': ('synthetisieren', None),
    'c1-critique': ('Kritik', None),
    'c1-discourse': ('Diskurs', None),
    'c1-hierarchy': ('Hierarchie', None),
    'c1-paradox': ('Paradox', None),
    'c1-theoretical': ('theoretisch', None),
    'c1-findings': ('Befunde', None),
    'c1-assumption': ('Annahme', None),
    'c1-to-back-up-support': ('unterstützen', None),
    'c1-to-bring-up-mention': ('ansprechen', None),
    'c1-to-call-off': ('absagen', None),
    'c1-to-carry-on': ('weitermachen', None),
    'c1-to-check-out-look-at': ('sich ansehen', None),
    'c1-to-come-across': ('stoßen auf', None),
    'c1-to-cut-down-on': ('einschränken', None),
    'c1-to-do-without': ('verzichten auf', None),
    'c1-to-fall-apart': ('auseinanderfallen', None),
    'c1-to-fall-behind': ('zurückfallen', None),
    'c1-to-get-away-with': ('davonkommen mit', None),
    'c1-to-get-by': ('zurechtkommen', None),
    'c1-to-get-over': ('überwinden', None),
    'c1-to-give-in': ('nachgeben', None),
    'c1-to-go-through-experience': ('durchmachen', None),
    'c1-to-hold-on': ('durchhalten', None),
    'c1-to-keep-up-with': ('Schritt halten mit', None),
    'c1-to-let-down': ('enttäuschen', None),
    'c1-to-look-into': ('untersuchen', None),
    'c1-to-look-up-to': ('bewundern', None),
    'c1-to-make-up-for': ('wettmachen', None),
    'c1-to-pass-out': ('ohnmächtig werden', None),
    'c1-to-point-out': ('hinweisen auf', None),
    'c1-to-put-up-with': ('ertragen', None),
    'c1-to-run-into': ('zufällig treffen', None),
    'c1-to-set-up': ('einrichten', None),
    'c1-to-sort-out': ('klären', None),
    'c1-to-stand-for': ('stehen für', None),
    'c1-to-take-after': ('ähneln', None),
    'c1-to-take-over': ('übernehmen', None),
    'c1-to-turn-down': ('ablehnen', None),
    'c1-to-turn-up': ('auftauchen', None),
    'c1-to-work-out-resolve': ('sich klären', None),
    'c1-to-wear-off': ('nachlassen', None),
    'c1-to-wind-up-end-up': ('landen (enden)', None),
    'c1-to-break-off': ('abbrechen', None),
    'c1-to-brush-up-on': ('auffrischen', None),
    'c1-to-catch-on': ('sich durchsetzen', None),
    'c1-to-come-down-with': ('sich zuziehen', None),
    'c1-to-crack-down-on': ('hart vorgehen gegen', None),
    'c1-to-dwell-on': ('grübeln über', None),
    'c1-to-fall-through': ('scheitern', None),
    'c1-to-get-across': ('vermitteln', None),
    'c1-to-hold-back': ('sich zurückhalten', None),
    'c1-to-iron-out': ('ausbügeln', None),
    'c1-to-live-up-to': ('gerecht werden', None),
    'c1-to-narrow-down': ('eingrenzen', None),
    'c1-to-opt-out': ('aussteigen', None),
    'c1-to-phase-out': ('auslaufen lassen', None),
    'c1-to-pull-off': ('hinbekommen', None),
    'c1-to-rule-out': ('ausschließen', None),
    'c1-to-settle-for': ('sich zufriedengeben mit', None),
    'c1-to-stick-to': ('sich halten an', None),
    'c1-to-take-on-a-task': ('sich annehmen (eine Aufgabe)', None),
    'c1-to-touch-on': ('anschneiden', None),
    'c1-to-weigh-up': ('abwägen', None),
    'c1-to-wrap-up': ('abschließen', None),
    'c1-to-zero-in-on': ('sich konzentrieren auf', None),
    'c1-to-fend-off': ('abwehren', None),
    'c1-to-stem-from': ('herrühren von', None),
    'c1-awesome': ('genial', None),
    'c1-gross': ('eklig', None),
    'c1-lame': ('lahm', None),
    'c1-cheesy': ('kitschig', None),
    'c1-to-chill': ('chillen', None),
    'c1-dude': ('Alter', None),
    'c1-to-ditch': ('sitzenlassen', None),
    'c1-to-bail-leave': ('abhauen', None),
    'c1-to-crash-sleep': ('pennen', None),
    'c1-to-freak-out': ('ausflippen', None),
    'c1-to-nail-it': ('hinkriegen', None),
    'c1-to-screw-up': ('vermasseln', None),
    'c1-a-bummer': ('Mist', None),
    'c1-no-biggie': ('kein Ding', None),
    'c1-to-be-into': ('stehen auf', None),
    'c1-hooked': ('süchtig', None),
    'c1-hype': ('Hype', None),
    'c1-sketchy': ('zwielichtig', None),
    'c1-legit': ('echt', None),
    'c1-a-rip-off': ('Abzocke', None),
    'c1-to-ghost': ('ghosten', None),
    'c1-cringe': ('cringe', None),
    'c1-to-wing-it': ('improvisieren', None),
    'c1-to-zone-out': ('gedanklich abschalten', None),
    'c1-to-kick-back': ('entspannen', None),
    'c1-for-real': ('im Ernst', None),
    'c1-buddy': ('Kumpel', None),
    'c1-to-hit-the-road': ('sich auf den Weg machen', None),
    'c1-to-grab-get': ('schnappen', None),
    'c1-sweet-great': ('klasse', None),
    'c1-eloquent': ('eloquent', None),
    'c1-poignant': ('ergreifend', None),
    'c1-vivid': ('bildhaft', None),
    'c1-lucid': ('klar', None),
    'c1-sublime': ('erhaben', None),
    'c1-exquisite': ('exquisit', None),
    'c1-serene': ('gelassen', None),
    'c1-somber': ('düster', None),
    'c1-bleak': ('trostlos', None),
    'c1-grim': ('grimmig', None),
    'c1-austere': ('karg', None),
    'c1-opulent': ('opulent', None),
    'c1-lavish': ('üppig', None),
    'c1-meager': ('dürftig', None),
    'c1-scarce': ('knapp', None),
    'c1-abundant': ('reichlich', None),
    'c1-pristine': ('makellos', None),
    'c1-dilapidated': ('verfallen', None),
    'c1-quaint': ('urig', None),
    'c1-picturesque': ('malerisch', None),
    'c1-ominous': ('unheilvoll', None),
    'c1-eerie': ('unheimlich', None),
    'c1-uncanny': ('sonderbar', None),
    'c1-whimsical': ('verspielt', None),
    'c1-wistful': ('wehmütig', None),
    'c1-fleeting': ('flüchtig', None),
    'c1-enduring': ('dauerhaft', None),
    'c1-ubiquitous': ('allgegenwärtig', None),
    'c1-elusive': ('schwer fassbar', None),
    'c1-tangible': ('greifbar', None),
    'c1-meticulous': ('akribisch', None),
    'c1-conscientious': ('gewissenhaft', None),
    'c1-diligent': ('emsig', None),
    'c1-pragmatic': ('pragmatisch', None),
    'c1-cynical': ('zynisch', None),
    'c1-skeptical': ('skeptisch', None),
    'c1-gullible': ('leichtgläubig', None),
    'c1-smug': ('selbstgefällig', None),
    'c1-aloof': ('distanziert', None),
    'c1-candid': ('freimütig', None),
    'c1-tactless': ('taktlos', None),
    'c1-assertive': ('durchsetzungsfähig', None),
    'c1-submissive': ('unterwürfig', None),
    'c1-vindictive': ('rachsüchtig', None),
    'c1-magnanimous': ('großmütig', None),
    'c1-benevolent': ('wohlwollend', None),
    'c1-malicious': ('böswillig', None),
    'c1-frugal': ('sparsam', None),
    'c1-extravagant': ('extravagant', None),
    'c1-impulsive': ('impulsiv', None),
    'c1-spontaneous': ('spontan', None),
    'c1-calculating': ('berechnend', None),
    'c1-eccentric': ('exzentrisch', None),
    'c1-unconventional': ('unkonventionell', None),
    'c1-sophisticated': ('kultiviert', None),
    'c1-witty': ('geistreich', None),
    'c1-sarcastic': ('sarkastisch', None),
    'c1-charismatic': ('charismatisch', None),
    'c1-condescending': ('herablassend', None),
    'c1-pretentious': ('anmaßend', None),
    'c1-empire': ('Reich', None),
    'c1-colony': ('Kolonie', None),
    'c1-revolution': ('Revolution', None),
    'c1-uprising': ('Aufstand', None),
    'c1-dictatorship': ('Diktatur', None),
    'c1-democracy': ('Demokratie', None),
    'c1-monarchy': ('Monarchie', None),
    'c1-republic': ('Republik', None),
    'c1-regime': ('Regime', None),
    'c1-treaty': ('Vertrag', None),
    'c1-alliance': ('Bündnis', None),
    'c1-invasion': ('Invasion', None),
    'c1-occupation-military': ('Besatzung', None),
    'c1-independence': ('Unabhängigkeit', None),
    'c1-sovereignty': ('Souveränität', None),
    'c1-civil-war': ('Bürgerkrieg', None),
    'c1-ceasefire': ('Waffenstillstand', None),
    'c1-refugee': ('Flüchtling', None),
    'c1-asylum': ('Asyl', None),
    'c1-exile': ('Exil', None),
    'c1-dynasty': ('Dynastie', None),
    'c1-heir': ('Erbe', None),
    'c1-coup': ('Staatsstreich', None),
    'c1-sanctions': ('Sanktionen', None),
    'c1-diplomacy': ('Diplomatie', None),
    'c1-ambassador': ('Botschafter', None),
    'c1-embassy': ('Botschaft', None),
    'c1-summit-meeting': ('Gipfeltreffen', None),
    'c1-constitution': ('Verfassung', None),
    'c1-amendment': ('Verfassungsänderung', None),
    'c1-bottom-line': ('das Wesentliche', None),
    'c1-ballpark-figure': ('grobe Schätzung', None),
    'c1-to-touch-base': ('Kontakt aufnehmen', None),
    'c1-to-circle-back': ('später darauf zurückkommen', None),
    'c1-bandwidth-capacity': ('Kapazität', None),
    'c1-to-leverage': ('nutzen (Hebelwirkung)', None),
    'c1-synergy': ('Synergie', None),
    'c1-to-scale-up': ('hochskalieren', None),
    'c1-to-pivot': ('die Richtung ändern', None),
    'c1-to-onboard': ('einarbeiten', None),
    'c1-to-roll-out': ('ausrollen', None),
    'c1-to-ramp-up': ('hochfahren', None),
    'c1-to-wind-down': ('herunterfahren', None),
    'c1-to-cut-corners': ('Abstriche machen', None),
    'c1-red-tape': ('Bürokratie', None),
    'c1-to-go-the-extra-mile': ('sich besonders anstrengen', None),
    'c1-on-the-same-page': ('einer Meinung sein', None),
    'c1-to-keep-in-the-loop': ('auf dem Laufenden halten', None),
    'c1-to-drop-the-ball': ('es versäumen', None),
    'c1-to-think-outside-the-box': ('unkonventionell denken', None),
    'c1-win-win': ('Win-win-Situation', None),
    'c1-game-changer': ('Wendepunkt', None),
    'c1-low-hanging-fruit': ('niedrig hängende Früchte', None),
    'c1-deliverable': ('Liefergegenstand', None),
    'c1-return-on-investment': ('Kapitalrendite', None),
    'c1-to-sign-off-on': ('absegnen', None),
    'c1-to-run-something-by-someone': ('mit jemandem abstimmen', None),
    'c1-stakeholder-buy-in': ('Zustimmung der Stakeholder', None),
    'c1-back-to-the-drawing-board': ('zurück an den Start', None),
    'c1-take-it-offline': ('das unter vier Augen besprechen', None),
    'c1-over-the-moon': ('überglücklich', None),
    'c1-down-in-the-dumps': ('niedergeschlagen', None),
    'c1-on-edge': ('angespannt', None),
    'c1-fed-up': ('es satt haben', None),
    'c1-at-a-loss': ('ratlos', None),
    'c1-in-two-minds': ('unschlüssig', None),
    'c1-under-the-weather': ('angeschlagen', None),
    'c1-taken-aback': ('verblüfft', None),
    'c1-blown-away': ('überwältigt', None),
    'c1-torn-between': ('hin- und hergerissen', None),
    'c1-beside-oneself': ('außer sich', None),
    'c1-heartbroken': ('mit gebrochenem Herzen', None),
    'c1-on-the-fence': ('unentschlossen', None),
    'c1-laid-back': ('entspannt', None),
    'c1-uptight': ('verklemmt', None),
    'c1-sick-and-tired': ('die Nase voll haben', None),
    'c1-in-a-rut': ('im Trott feststecken', None),
    'c1-head-over-heels': ('bis über beide Ohren verliebt', None),
    'c1-cold-feet': ('kalte Füße', None),
    'c1-second-thoughts': ('Bedenken', None),
    'c1-a-weight-off-my-shoulders': ('ein Stein fällt vom Herzen', None),
    'c1-butterflies-in-my-stomach': ('Schmetterlinge im Bauch', None),
    'c1-a-lump-in-my-throat': ('ein Kloß im Hals', None),
    'c1-goosebumps': ('Gänsehaut', None),
    'c1-speechless-with-joy': ('sprachlos vor Freude', None),
    'c1-out-of-sorts': ('unpässlich', None),
    'c1-keyed-up': ('aufgekratzt', None),
    'c1-wound-up': ('aufgewühlt', None),
    'c1-mixed-feelings': ('gemischte Gefühle', None),
    'c1-at-peace': ('im Reinen', None),
    'c1-bureaucracy': ('Bürokratie', None),
    'c1-paperwork': ('Papierkram', None),
    'c1-to-file-documents': ('einreichen', None),
    'c1-applicant': ('Antragsteller', None),
    'c1-eligible': ('berechtigt', None),
    'c1-to-qualify': ('die Voraussetzungen erfüllen', None),
    'c1-prerequisite': ('Voraussetzung', None),
    'c1-clause': ('Klausel', None),
    'c1-compliance': ('Einhaltung', None),
    'c1-regulation': ('Vorschrift', None),
    'c1-license-permit': ('Genehmigung', None),
    'c1-to-authorize': ('genehmigen', None),
    'c1-notary': ('Notar', None),
    'c1-affidavit': ('eidesstattliche Erklärung', None),
    'c1-deed': ('Urkunde', None),
    'c1-title-property': ('Eigentumstitel', None),
    'c1-lien': ('Pfandrecht', None),
    'c1-easement': ('Dienstbarkeit', None),
    'c1-appraisal': ('Schätzung', None),
    'c1-closing-real-estate': ('Kaufabschluss', None),
    'c1-escrow': ('Treuhandkonto', None),
    'c1-commission-fee': ('Provision', None),
    'c1-listing-property': ('Immobilienanzeige', None),
    'c1-counteroffer': ('Gegenangebot', None),
    'c1-contingency': ('Vorbehalt', None),
    'c1-zoning-variance': ('Ausnahmegenehmigung (Bebauung)', None),
    'c1-deadline-filing': ('Einreichungsfrist', None),
    'c1-certified-copy': ('beglaubigte Abschrift', None),
    'c1-jurisdiction': ('Gerichtsbarkeit', None),
    'c1-liability': ('Haftung', None),
    'c1-galaxy': ('Galaxie', None),
    'c1-universe': ('Universum', None),
    'c1-black-hole': ('Schwarzes Loch', None),
    'c1-telescope': ('Teleskop', None),
    'c1-asteroid': ('Asteroid', None),
    'c1-eclipse': ('Finsternis', None),
    'c1-constellation': ('Sternbild', None),
    'c1-particle': ('Teilchen', None),
    'c1-radiation': ('Strahlung', None),
    'c1-electron': ('Elektron', None),
    'c1-isotope': ('Isotop', None),
    'c1-nuclear-fusion': ('Kernfusion', None),
    'c1-magnetic-field': ('Magnetfeld', None),
    'c1-friction': ('Reibung', None),
    'c1-velocity': ('Geschwindigkeit', None),
    'c1-acceleration': ('Beschleunigung', None),
    'c1-momentum': ('Impuls', None),
    'c1-inertia': ('Trägheit', None),
    'c1-density': ('Dichte', None),
    'c1-pressure-physics': ('Druck', None),
    'c1-vacuum': ('Vakuum', None),
    'c1-wavelength': ('Wellenlänge', None),
    'c1-frequency-physics': ('Frequenz', None),
    'c1-spectrum': ('Spektrum', None),
    'c1-photosynthesis': ('Photosynthese', None),
    'c1-enzyme': ('Enzym', None),
    'c1-hormone': ('Hormon', None),
    'c1-metabolism': ('Stoffwechsel', None),
    'c1-mutation': ('Mutation', None),
    'c1-organism': ('Organismus', None),
    'c1-to-allege': ('behaupten', None),
    'c1-to-allude': ('anspielen auf', None),
    'c1-to-ascertain': ('in Erfahrung bringen', None),
    'c1-to-bolster': ('untermauern', None),
    'c1-to-circumvent': ('umgehen', None),
    'c1-to-coerce': ('nötigen', None),
    'c1-to-condone': ('stillschweigend billigen', None),
    'c1-to-consolidate': ('konsolidieren', None),
    'c1-to-curb': ('eindämmen', None),
    'c1-to-deter': ('abschrecken', None),
    'c1-to-diminish': ('vermindern', None),
    'c1-to-disclose': ('offenlegen', None),
    'c1-to-disrupt': ('stören', None),
    'c1-to-divert': ('umleiten', None),
    'c1-to-elicit': ('hervorrufen', None),
    'c1-to-endorse': ('befürworten', None),
    'c1-to-entail': ('mit sich bringen', None),
    'c1-to-eradicate': ('ausrotten', None),
    'c1-to-exacerbate': ('verschärfen', None),
    'c1-to-exemplify': ('veranschaulichen', None),
    'c1-to-foster': ('fördern', None),
    'c1-to-hinder': ('behindern', None),
    'c1-to-impede': ('erschweren', None),
    'c1-to-instigate': ('anstiften', None),
    'c1-to-mitigate': ('abmildern', None),
    'c1-to-nurture': ('hegen', None),
    'c1-to-omit': ('auslassen', None),
    'c1-to-precede': ('vorausgehen', None),
    'c1-to-preclude': ('von vornherein ausschließen', None),
    'c1-to-prompt': ('veranlassen', None),
    'c1-to-refrain': ('sich enthalten', None),
    'c1-to-relinquish': ('aufgeben', None),
    'c1-to-render': ('machen zu', None),
    'c1-to-scrutinize': ('genau prüfen', None),
    'c1-to-stipulate': ('festlegen', None),
    'c1-to-substantiate': ('belegen', None),
    'c1-to-thrive': ('gedeihen', None),
    'c1-to-undermine': ('untergraben', None),
    'c1-to-uphold': ('aufrechterhalten', None),
    'c1-to-waive': ('verzichten auf', None),
    'c1-to-yield': ('abwerfen', None),
    'c1-to-abolish': ('abschaffen', None),
    'c1-to-accommodate': ('unterbringen', None),
    'c1-to-adhere': ('festhalten an', None),
    'c1-to-attain': ('erreichen', None),
    'c1-to-compel': ('zwingen', None),
    'c1-to-confine': ('beschränken', None),
    'c1-to-contemplate': ('erwägen', None),
    'c1-to-depict': ('darstellen', None),
    'c1-to-dispel': ('zerstreuen', None),
    'c1-to-embody': ('verkörpern', None),
    'c1-to-evoke': ('heraufbeschwören', None),
    'c1-to-forge': ('schmieden', None),
    'c1-to-grasp': ('begreifen', None),
    'c1-to-infringe': ('verletzen', None),
    'c1-to-overturn': ('aufheben', None),
    'c1-to-plead': ('plädieren', None),
    'c1-to-reconcile-ideas': ('in Einklang bringen', None),
    'c1-to-surpass': ('übertreffen', None),
    'c1-to-unveil': ('enthüllen', None),
    'c1-albeit': ('obgleich', None),
    'c1-notwithstanding': ('ungeachtet', None),
    'c1-insofar-as': ('insofern als', None),
    'c1-whereby': ('wodurch', None),
    'c1-hereby': ('hiermit', None),
    'c1-thereby': ('dadurch', None),
    'c1-hence': ('daher', None),
    'c1-thus': ('somit', None),
    'c1-henceforth': ('fortan', None),
    'c1-likewise': ('ebenso', None),
    'c1-conversely': ('umgekehrt', None),
    'c1-namely': ('nämlich', None),
    'c1-in-lieu-of': ('anstelle von', None),
    'c1-in-light-of': ('angesichts', None),
    'c1-in-view-of': ('im Hinblick auf', None),
    'c1-by-virtue-of': ('kraft', None),
    'c1-on-account-of': ('aufgrund von', None),
    'c1-with-a-view-to': ('mit dem Ziel, zu', None),
    'c1-provided-that': ('vorausgesetzt, dass', None),
    'c1-granted': ('zugegeben', None),
    'c1-admittedly': ('zugegebenermaßen', None),
    'c1-arguably': ('man könnte argumentieren, dass', None),
    'c1-presumably': ('vermutlich', None),
    'c1-allegedly': ('angeblich', None),
    'c1-ostensibly': ('vorgeblich', None),
    'c1-undoubtedly': ('zweifellos', None),
    'c1-invariably': ('ausnahmslos', None),
    'c1-nevertheless-formal': ('dennoch', None),
    'c1-to-the-extent-that': ('in dem Maße, dass', None),
    'c1-for-all-intents-and-purposes': ('im Grunde genommen', None),
    'c1-sommelier': ('Sommelier', None),
    'c1-vintage-wine': ('Jahrgang', None),
    'c1-aroma': ('Aroma', None),
    'c1-palate': ('Gaumen', None),
    'c1-aftertaste': ('Nachgeschmack', None),
    'c1-full-bodied': ('vollmundig', None),
    'c1-dry-wine': ('trocken', None),
    'c1-sparkling': ('perlend', None),
    'c1-brew': ('Aufguss', None),
    'c1-roast-coffee': ('Röstung', None),
    'c1-espresso': ('Espresso', None),
    'c1-decaf': ('koffeinfrei', None),
    'c1-barista': ('Barista', None),
    'c1-tasting-menu': ('Degustationsmenü', None),
    'c1-pairing': ('Kombination (Speisen und Getränke)', None),
    'c1-a-la-carte': ('à la carte', None),
    'c1-garnish': ('Garnitur', None),
    'c1-drizzle-of-oil': ('Schuss (Öl)', None),
    'c1-reduction-sauce': ('Reduktion', None),
    'c1-glaze': ('Glasur', None),
    'c1-umami': ('Umami', None),
    'c1-zest': ('Zeste', None),
    'c1-to-caramelize': ('karamellisieren', None),
    'c1-to-braise': ('schmoren', None),
    'c1-to-poach': ('pochieren', None),
    'c1-al-dente': ('al dente', None),
    'c1-medium-rare': ('medium rare', None),
    'c1-well-done': ('durchgebraten', None),
    'c1-signature-dish': ('Spezialität des Hauses', None),
    'c1-chefs-recommendation': ('Empfehlung des Kochs', None),
    'c1-floor-plan': ('Grundriss', None),
    'c1-open-plan': ('offener Grundriss', None),
    'c1-layout': ('Aufteilung', None),
    'c1-fixture': ('Ausstattung (fest installiert)', None),
    'c1-cabinetry': ('Einbauschränke', None),
    'c1-countertop': ('Arbeitsplatte', None),
    'c1-backsplash': ('Spritzschutz', None),
    'c1-grout': ('Fugenmasse', None),
    'c1-hardwood-floor': ('Massivholzboden', None),
    'c1-laminate': ('Laminat', None),
    'c1-molding-trim': ('Zierleiste', None),
    'c1-baseboard': ('Fußleiste', None),
    'c1-crown-molding': ('Stuckleiste', None),
    'c1-sconce': ('Wandleuchte', None),
    'c1-pendant-light': ('Pendelleuchte', None),
    'c1-recessed-lighting': ('Einbaubeleuchtung', None),
    'c1-dimmer': ('Dimmer', None),
    'c1-vent': ('Lüftungsgitter', None),
    'c1-duct': ('Lüftungskanal', None),
    'c1-hvac': ('Heizungs-, Lüftungs- und Klimatechnik', None),
    'c1-sump-pump': ('Schmutzwasserpumpe', None),
    'c1-water-heater': ('Warmwasserbereiter', None),
    'c1-circuit-breaker': ('Sicherungsautomat', None),
    'c1-load-bearing-wall': ('tragende Wand', None),
    'c1-joist': ('Deckenbalken', None),
    'c1-stud-wall': ('Wandständer', None),
    'c1-subfloor': ('Unterboden', None),
    'c1-caulk': ('Dichtmasse', None),
    'c1-primer-paint': ('Grundierung', None),
    'c1-punch-list': ('Mängelliste', None),
    'c1-change-order': ('Änderungsauftrag', None),
    'c1-scope-of-work': ('Leistungsumfang', None),
    'c1-rapport': ('gutes Verhältnis', None),
    'c1-chemistry-between-people': ('Chemie (zwischenmenschlich)', None),
    'c1-affinity': ('Affinität', None),
    'c1-estranged': ('entfremdet', None),
    'c1-reconciliation': ('Versöhnung', None),
    'c1-to-confide': ('sich anvertrauen', None),
    'c1-confidant': ('Vertrauter', None),
    'c1-to-fall-out': ('sich zerstreiten', None),
    'c1-to-patch-things-up': ('sich versöhnen', None),
    'c1-to-drift-apart': ('sich auseinanderleben', None),
    'c1-to-hit-it-off': ('sich auf Anhieb verstehen', None),
    'c1-to-have-a-soft-spot-for': ('eine Schwäche haben für', None),
    'c1-to-hold-a-grudge': ('nachtragend sein', None),
    'c1-to-bury-the-hatchet': ('das Kriegsbeil begraben', None),
    'c1-to-make-amends': ('es wiedergutmachen', None),
    'c1-to-take-for-granted': ('als selbstverständlich ansehen', None),
    'c1-to-lean-on': ('sich stützen auf', None),
    'c1-to-stick-up-for': ('sich einsetzen für', None),
    'c1-to-look-out-for': ('aufpassen auf', None),
    'c1-to-see-eye-to-eye': ('die gleiche Sichtweise haben', None),
    'c1-to-get-on-someones-nerves': ('jemandem auf die Nerven gehen', None),
    'c1-to-give-the-benefit-of-the-doubt': ('jemandem einen Vertrauensvorschuss geben', None),
    'c1-to-read-between-the-lines': ('zwischen den Zeilen lesen', None),
    'c1-to-beat-around-the-bush': ('um den heißen Brei herumreden', None),
    'c1-to-get-to-the-point': ('auf den Punkt kommen', None),
    'c1-to-keep-someone-at-arms-length': ('jemanden auf Distanz halten', None),
    'c1-to-go-behind-someones-back': ('hinter jemandes Rücken handeln', None),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('das Herz auf der Zunge tragen', None),
    'c1-tactfully': ('taktvoll', None),
    'c1-passive-aggressive': ('passiv-aggressiv', None),
    'c1-mediocre': ('mittelmäßig', None),
    'c1-subpar': ('unterdurchschnittlich', None),
    'c1-top-notch': ('erstklassig', None),
    'c1-first-rate': ('erstrangig', None),
    'c1-second-rate': ('zweitklassig', None),
    'c1-state-of-the-art': ('hochmodern', None),
    'c1-cutting-edge': ('bahnbrechend', None),
    'c1-run-of-the-mill': ('gewöhnlich', None),
    'c1-exceptional': ('außergewöhnlich', None),
    'c1-flawless': ('fehlerfrei', None),
    'c1-impeccable': ('tadellos', None),
    'c1-shoddy': ('minderwertig', None),
    'c1-sloppy': ('schlampig', None),
    'c1-half-baked': ('unausgereift', None),
    'c1-polished': ('ausgefeilt', None),
    'c1-crude': ('grob', None),
    'c1-rudimentary': ('rudimentär', None),
    'c1-intricate': ('vertrackt', None),
    'c1-convoluted': ('verworren', None),
    'c1-user-friendly': ('benutzerfreundlich', None),
    'c1-foolproof': ('narrensicher', None),
    'c1-robust': ('robust', None),
    'c1-seamless': ('nahtlos', None),
    'c1-glitchy': ('fehleranfällig', None),
    'c1-clunky': ('unhandlich', None),
    'c1-sleek': ('schnittig', None),
    'c1-bulky': ('sperrig', None),
    'c1-compact': ('kompakt', None),
    'c1-flimsy': ('wacklig', None),
    'c1-durable': ('langlebig', None),
    'c1-to-mumble': ('nuscheln', None),
    'c1-to-mutter': ('brummeln', None),
    'c1-to-stutter': ('stottern', None),
    'c1-to-slur': ('lallen', None),
    'c1-to-ramble': ('schwafeln', None),
    'c1-to-rant': ('wettern', None),
    'c1-to-grumble': ('meckern', None),
    'c1-to-whine': ('quengeln', None),
    'c1-to-snap-at-someone': ('anfahren', None),
    'c1-hoarse': ('heiser', None),
    'c1-raspy': ('rau', None),
    'c1-monotone': ('monoton', None),
    'c1-shrill': ('schrill', None),
    'c1-deafening': ('ohrenbetäubend', None),
    'c1-muffled': ('gedämpft', None),
    'c1-faint-sound': ('kaum hörbar', None),
    'c1-to-hum': ('summen', None),
    'c1-to-chant': ('skandieren', None),
    'c1-to-murmur': ('murmeln', None),
    'c1-to-bellow': ('brüllen', None),
    'c1-to-chuckle': ('glucksen', None),
    'c1-to-giggle': ('kichern', None),
    'c1-to-snicker': ('hämisch grinsen', None),
    'c1-to-sob': ('schluchzen', None),
    'c1-to-wail': ('wehklagen', None),
    'c1-to-howl': ('heulen', None),
    'c1-to-shriek': ('kreischen', None),
    'c1-to-gasp': ('nach Luft schnappen', None),
    'c1-pitch-voice': ('Tonhöhe', None),
    'c1-accent-stress': ('Betonung', None),
    'c1-asset': ('Vermögenswert', None),
    'c1-liability-finance': ('Verbindlichkeit', None),
    'c1-equity': ('Eigenkapital', None),
    'c1-portfolio': ('Portfolio', None),
    'c1-dividend': ('Dividende', None),
    'c1-bond-finance': ('Anleihe', None),
    'c1-hedge': ('Absicherung', None),
    'c1-liquidity': ('Liquidität', None),
    'c1-collateral': ('Sicherheit', None),
    'c1-default-loan': ('Zahlungsausfall', None),
    'c1-foreclosure': ('Zwangsvollstreckung', None),
    'c1-appreciation-value': ('Wertsteigerung', None),
    'c1-depreciation': ('Wertminderung', None),
    'c1-capital-gains': ('Veräußerungsgewinne', None),
    'c1-write-off': ('Abschreibung', None),
    'c1-overhead': ('Gemeinkosten', None),
    'c1-payroll': ('Lohnabrechnung', None),
    'c1-gross-before-deductions': ('brutto', None),
    'c1-net': ('netto', None),
    'c1-deductible': ('absetzbar', None),
    'c1-exemption': ('Befreiung', None),
    'c1-audit': ('Prüfung', None),
    'c1-ledger': ('Hauptbuch', None),
    'c1-bookkeeping': ('Buchführung', None),
    'c1-break-even': ('Gewinnschwelle', None),
    'c1-turnover': ('Umsatz', None),
    'c1-markup': ('Aufschlag', None),
    'c1-cash-reserve': ('Barreserve', None),
    'c1-venture-capital': ('Risikokapital', None),
    'c1-fiscal-year': ('Geschäftsjahr', None),
    'c1-expedition': ('Expedition', None),
    'c1-pilgrimage': ('Pilgerfahrt', None),
    'c1-getaway': ('Kurzurlaub', None),
    'c1-sabbatical': ('Sabbatjahr', None),
    'c1-nomad': ('Nomade', None),
    'c1-expatriate': ('Expat', None),
    'c1-immigrant': ('Einwanderer', None),
    'c1-to-relocate': ('umziehen', None),
    'c1-to-settle-down': ('sesshaft werden', None),
    'c1-culture-shock': ('Kulturschock', None),
    'c1-to-assimilate': ('sich assimilieren', None),
    'c1-bilingual': ('zweisprachig', None),
    'c1-multilingual': ('mehrsprachig', None),
    'c1-mother-tongue': ('Muttersprache', None),
    'c1-dialect': ('Dialekt', None),
    'c1-slang': ('Slang', None),
    'c1-jargon': ('Fachjargon', None),
    'c1-register-language': ('Sprachregister', None),
    'c1-colloquial': ('umgangssprachlich', None),
    'c1-fluency': ('Sprachgewandtheit', None),
    'c1-proficiency': ('Sprachkompetenz', None),
    'c1-to-master': ('beherrschen', None),
    'c1-immersion': ('Sprachbad', None),
    'c1-intonation': ('Intonation', None),
    'c1-to-mispronounce': ('falsch aussprechen', None),
    'c1-false-friend': ('falscher Freund', None),
    'c1-cognate': ('verwandtes Wort', None),
    'c1-loanword': ('Lehnwort', None),
    'c1-literacy': ('Alphabetisierung', None),
    'c1-interpreter': ('Dolmetscher', None),
    'c1-latency': ('Latenz', None),
    'c1-server': ('Server', None),
    'c1-cloud-computing': ('Cloud-Computing', None),
    'c1-backup-data': ('Sicherungskopie', None),
    'c1-firewall': ('Firewall', None),
    'c1-malware': ('Schadsoftware', None),
    'c1-phishing': ('Phishing', None),
    'c1-two-factor-authentication': ('Zwei-Faktor-Authentifizierung', None),
    'c1-biometric': ('biometrisch', None),
    'c1-open-source': ('quelloffen', None),
    'c1-interface': ('Schnittstelle', None),
    'c1-plugin': ('Plug-in', None),
    'c1-patch-software': ('Patch', None),
    'c1-to-deploy': ('bereitstellen', None),
    'c1-release-version': ('Veröffentlichung', None),
    'c1-beta': ('Beta', None),
    'c1-blockchain': ('Blockchain', None),
    'c1-cryptocurrency': ('Kryptowährung', None),
    'c1-machine-learning': ('maschinelles Lernen', None),
    'c1-neural-network': ('neuronales Netz', None),
    'c1-dataset': ('Datensatz', None),
    'c1-drone': ('Drohne', None),
    'c1-sensor': ('Sensor', None),
    'c1-augmented-reality': ('erweiterte Realität', None),
    'c1-wearable': ('tragbares Gerät', None),
    'c1-smart-home': ('intelligentes Zuhause', None),
    'c1-bandwidth-network': ('Bandbreite', None),
    'c1-outage': ('Ausfall', None),
    'c1-scalability': ('Skalierbarkeit', None),
    'c1-encryption-key': ('Verschlüsselungsschlüssel', None),
    'c1-cinematography': ('Kameraführung', None),
    'c1-close-up': ('Nahaufnahme', None),
    'c1-wide-shot': ('Totale', None),
    'c1-montage': ('Montage', None),
    'c1-flashback': ('Rückblende', None),
    'c1-voice-over': ('Off-Stimme', None),
    'c1-subplot': ('Nebenhandlung', None),
    'c1-protagonist': ('Protagonist', None),
    'c1-antagonist': ('Antagonist', None),
    'c1-cliffhanger': ('Cliffhanger', None),
    'c1-plot-twist': ('Handlungswendung', None),
    'c1-foreshadowing': ('Vorausdeutung', None),
    'c1-pacing': ('Erzähltempo', None),
    'c1-casting': ('Besetzung', None),
    'c1-cameo': ('Gastauftritt', None),
    'c1-sequel': ('Fortsetzung', None),
    'c1-prequel': ('Prequel', None),
    'c1-reboot': ('Neuauflage', None),
    'c1-box-office': ('Kinokasse', None),
    'c1-blockbuster': ('Kassenschlager', None),
    'c1-indie-film': ('Independentfilm', None),
    'c1-cult-classic': ('Kultfilm', None),
    'c1-critically-acclaimed': ('von der Kritik gefeiert', None),
    'c1-dubbed': ('synchronisiert', None),
    'c1-subtitled': ('untertitelt', None),
    'c1-screening': ('Vorführung', None),
    'c1-pilot-episode': ('Pilotfolge', None),
    'c1-season-finale': ('Staffelfinale', None),
    'c1-showrunner': ('Showrunner', None),
    'c1-storyboard': ('Storyboard', None),
    'c1-on-the-mend': ('auf dem Weg der Besserung', None),
    'c1-run-down-exhausted': ('erschöpft', None),
    'c1-in-good-shape': ('in guter Verfassung', None),
    'c1-out-of-shape': ('außer Form', None),
    'c1-a-clean-bill-of-health': ('ein einwandfreier Gesundheitsbefund', None),
    'c1-to-pull-a-muscle': ('sich einen Muskel zerren', None),
    'c1-wear-and-tear': ('Verschleiß', None),
    'c1-to-nod-off': ('einnicken', None),
    'c1-to-sleep-like-a-log': ('schlafen wie ein Stein', None),
    'c1-to-toss-and-turn': ('sich hin und her wälzen', None),
    'c1-over-the-counter': ('rezeptfrei', None),
    'c1-second-opinion': ('Zweitmeinung', None),
    'c1-bedside-manner': ('Umgang mit Patienten', None),
    'c1-to-be-discharged': ('entlassen werden', None),
    'c1-to-be-admitted-hospital': ('eingeliefert werden', None),
    'c1-outpatient': ('ambulanter Patient', None),
    'c1-follow-up-appointment': ('Nachuntersuchung', None),
    'c1-referral': ('Überweisung', None),
    'c1-to-take-a-turn-for-the-worse': ('sich verschlechtern', None),
    'c1-to-black-out': ('das Bewusstsein verlieren', None),
    'c1-under-the-knife': ('unters Messer kommen', None),
    'c1-slipped-disc': ('Bandscheibenvorfall', None),
    'c1-jet-lagged': ('unter Jetlag leidend', None),
    'c1-on-medication': ('in medikamentöser Behandlung', None),
    'c1-immune-to': ('immun gegen', None),
    'c1-prone-to': ('anfällig für', None),
    'c1-relapse': ('Rückfall', None),
    'c1-remission': ('Remission', None),
    'c1-a-no-brainer': ('eine klare Sache', None),
    'c1-a-long-shot': ('eine vage Chance', None),
    'c1-a-close-call': ('knapp davongekommen', None),
    'c1-a-wake-up-call': ('ein Weckruf', None),
    'c1-a-catch-hidden-problem': ('ein Haken', None),
    'c1-the-upside': ('der Vorteil', None),
    'c1-the-downside': ('der Nachteil', None),
    'c1-a-trade-off': ('ein Kompromiss', None),
    'c1-a-loophole': ('ein Schlupfloch', None),
    'c1-a-setback': ('ein Rückschlag', None),
    'c1-a-blessing-in-disguise': ('ein Glück im Unglück', None),
    'c1-the-tip-of-the-iceberg': ('die Spitze des Eisbergs', None),
    'c1-the-last-straw': ('der Tropfen, der das Fass zum Überlaufen bringt', None),
    'c1-a-double-edged-sword': ('ein zweischneidiges Schwert', None),
    'c1-the-elephant-in-the-room': ('der Elefant im Raum', None),
    'c1-a-grey-area': ('eine Grauzone', None),
    'c1-a-slippery-slope': ('eine schiefe Bahn', None),
    'c1-a-vicious-circle': ('ein Teufelskreis', None),
    'c1-a-stepping-stone': ('ein Sprungbrett', None),
    'c1-a-rule-of-thumb': ('eine Faustregel', None),
    'c1-a-rain-check': ('eine Vertagung', None),
    'c1-a-heads-up': ('eine Vorwarnung', None),
    'c1-a-hunch': ('eine Ahnung', None),
    'c1-a-knack': ('ein Talent', None),
    'c1-a-pet-peeve': ('ein persönliches Ärgernis', None),
    'c1-a-red-flag': ('ein Warnsignal', None),
    'c1-a-silver-lining': ('ein Lichtblick', None),
    'c1-a-drop-in-the-ocean': ('ein Tropfen auf den heißen Stein', None),
    'c1-a-piece-of-cake': ('ein Kinderspiel', None),
    'c1-a-far-cry-from': ('weit entfernt von', None),
    'c1-a-handful': ('eine Handvoll', None),
    'c1-a-fair-amount': ('eine ordentliche Menge', None),
    'c1-the-lions-share': ('der Löwenanteil', None),
    'c1-a-fraction': ('ein Bruchteil', None),
    'c1-the-vast-majority': ('die überwiegende Mehrheit', None),
    'c1-next-to-nothing': ('so gut wie nichts', None),
    'c1-a-great-deal': ('sehr viel', None),
    'c1-at-most': ('höchstens', None),
    'c1-at-best': ('bestenfalls', None),
    'c1-at-worst': ('schlimmstenfalls', None),
    'c1-in-bulk': ('in großen Mengen', None),
    'c1-on-average': ('im Durchschnitt', None),
    'c1-per-capita': ('pro Kopf', None),
    'c1-give-or-take': ('mehr oder weniger', None),
    'c1-a-rough-estimate': ('eine grobe Schätzung', None),
    'c1-a-round-number': ('eine runde Zahl', None),
    'c1-the-odds': ('die Chancen', None),
    'c1-by-a-narrow-margin': ('mit knappem Vorsprung', None),
    'c1-by-a-landslide': ('haushoch', None),
    'c1-one-in-ten': ('einer von zehn', None),
    'c1-twofold': ('zweifach', None),
    'c1-exponentially': ('exponentiell', None),
    'c1-marginally': ('geringfügig', None),
    'c1-negligible': ('vernachlässigbar', None),
    'c1-sizable': ('beträchtlich', None),
    'c1-umpteen': ('zig', None),
    'c1-in-the-region-of': ('in der Größenordnung von', None),
    'c1-odds-and-ends': ('Kleinkram', None),
    'c1-mentor': ('Mentor', None),
    'c1-protege': ('Schützling', None),
    'c1-intern': ('Praktikant', None),
    'c1-veteran-experienced': ('Veteran', None),
    'c1-rookie': ('Neuling', None),
    'c1-whiz': ('Ass', None),
    'c1-workaholic': ('Workaholic', None),
    'c1-slacker': ('Faulenzer', None),
    'c1-know-it-all': ('Besserwisser', None),
    'c1-yes-man': ('Jasager', None),
    'c1-gatekeeper': ('Türhüter', None),
    'c1-middleman': ('Zwischenhändler', None),
    'c1-liaison': ('Verbindungsperson', None),
    'c1-spokesperson': ('Sprecher', None),
    'c1-figurehead': ('Galionsfigur', None),
    'c1-frontrunner': ('Favorit', None),
    'c1-underdog': ('Außenseiter', None),
    'c1-dark-horse': ('Überraschungskandidat', None),
    'c1-wildcard': ('Wildcard', None),
    'c1-heavyweight': ('Schwergewicht', None),
    'c1-newcomer': ('Neuankömmling', None),
    'c1-insider': ('Insider', None),
    'c1-outsider': ('Außenstehender', None),
    'c1-consultant': ('Berater', None),
    'c1-subcontractor': ('Subunternehmer', None),
    'c1-headhunter': ('Headhunter', None),
    'c1-scapegoat': ('Sündenbock', None),
    'c1-go-getter': ('Draufgänger', None),
    'c1-universal-healthcare': ('allgemeine Gesundheitsversorgung', None),
    'c1-minimum-wage': ('Mindestlohn', None),
    'c1-affordable-housing': ('bezahlbarer Wohnraum', None),
    'c1-surveillance': ('Überwachung', None),
    'c1-privacy': ('Privatsphäre', None),
    'c1-free-speech': ('Meinungsfreiheit', None),
    'c1-polarization': ('Polarisierung', None),
    'c1-populism': ('Populismus', None),
    'c1-nationalism': ('Nationalismus', None),
    'c1-globalization': ('Globalisierung', None),
    'c1-austerity': ('Sparpolitik', None),
    'c1-welfare': ('Sozialhilfe', None),
    'c1-aging-population': ('alternde Bevölkerung', None),
    'c1-birth-rate': ('Geburtenrate', None),
    'c1-brain-drain': ('Braindrain', None),
    'c1-gig-economy': ('Plattformökonomie', None),
    'c1-job-displacement': ('Arbeitsplatzverdrängung', None),
    'c1-universal-basic-income': ('bedingungsloses Grundeinkommen', None),
    'c1-carbon-tax': ('CO2-Steuer', None),
    'c1-nuclear-energy': ('Kernenergie', None),
    'c1-food-security': ('Ernährungssicherheit', None),
    'c1-water-scarcity': ('Wasserknappheit', None),
    'c1-urban-sprawl': ('Zersiedelung', None),
    'c1-rent-control': ('Mietpreisbindung', None),
    'c1-public-transit-funding': ('Finanzierung des öffentlichen Nahverkehrs', None),
    'c1-data-protection': ('Datenschutz', None),
    'c1-wealth-gap': ('Vermögenskluft', None),
    'c1-voter-turnout': ('Wahlbeteiligung', None),
    'c1-bustling': ('belebt', None),
    'c1-sleepy-town': ('verschlafen', None),
    'c1-vibrant': ('pulsierend', None),
    'c1-deserted': ('menschenleer', None),
    'c1-packed': ('überfüllt', None),
    'c1-cramped': ('beengt', None),
    'c1-airy': ('luftig', None),
    'c1-stuffy': ('stickig', None),
    'c1-gloomy': ('trübselig', None),
    'c1-dingy': ('schmuddelig', None),
    'c1-shabby': ('schäbig', None),
    'c1-chic': ('schick', None),
    'c1-trendy': ('angesagt', None),
    'c1-upscale': ('gehoben', None),
    'c1-seedy': ('anrüchig', None),
    'c1-leafy': ('baumreich', None),
    'c1-sprawling': ('weitläufig', None),
    'c1-walkable': ('fußgängerfreundlich', None),
    'c1-secluded': ('abgeschieden', None),
    'c1-remote-place': ('abgelegen', None),
    'c1-touristy': ('touristisch überlaufen', None),
    'c1-unspoiled': ('unberührt', None),
    'c1-well-kept': ('gepflegt', None),
    'c1-overgrown': ('zugewachsen', None),
    'c1-tucked-away': ('versteckt', None),
    'c1-nestled': ('eingebettet', None),
    'c1-lively': ('lebendig', None),
    'c1-run-down-place': ('heruntergekommen', None),
}
