# -*- coding: utf-8 -*-
LANG = 'de'

GRAMMAR = [
    {"id": "g-de1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Es war einmal ein König, der drei Töchter ___.", "correct": "hatte",
     "options": ["hatte", "hat", "haben", "hätte"],
     "note": "German narration uses the Präteritum (hatte) for storytelling, not the Perfekt or present tense."},
    {"id": "g-de2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Nachdem wir gegessen ___, gingen wir spazieren.", "correct": "hatten",
     "options": ["hatten", "haben", "hatte", "hätten"],
     "note": "Nachdem + Plusquamperfekt (hatten gegessen) marks the action completed before the following Präteritum clause (gingen)."},
    {"id": "g-de3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Wenn ich mehr Zeit ___, würde ich nach Japan reisen.", "correct": "hätte",
     "options": ["hätte", "habe", "hatte", "haben"],
     "note": "Irreal condition: wenn + Konjunktiv II (hätte) pairs with würde + infinitive (reisen)."},
    {"id": "g-de4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Wäre ich früher losgefahren, ___ ich den Zug nicht verpasst.", "correct": "hätte",
     "options": ["hätte", "habe", "würde", "war"],
     "note": "Inverted conditional without wenn: Wäre... losgefahren, hätte... verpasst — both clauses in Konjunktiv II der Vergangenheit."},
    {"id": "g-de5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Sie trägt einen ___ Mantel.", "correct": "roten",
     "options": ["roten", "rote", "rot", "rotem"],
     "note": "After the masculine accusative article \"einen\", the adjective takes the weak ending -en (roten Mantel)."},
    {"id": "g-de6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Das Café befindet sich ___ der Ecke.", "correct": "an",
     "options": ["an", "in", "auf", "bei"],
     "note": "\"An der Ecke\" (on the corner) is the fixed preposition for describing a location by a corner; \"in\" or \"auf\" sound off here."},
]

IDIOMS = [
    {"id": "i-de1", "tier": "C1", "topic": "idiom-character",
     "phrase": "ein Sturkopf sein", "correct": "to be stubborn as a mule",
     "options": ["to be stubborn as a mule", "to be a quick learner", "to be generous with money", "to be easily frightened"],
     "note": "Literally \"to be a stubborn-head\"; used for someone who won't budge once they've made up their mind."},
    {"id": "i-de2", "tier": "C1", "topic": "idiom-character",
     "phrase": "das Herz auf dem rechten Fleck haben", "correct": "to have one's heart in the right place",
     "options": ["to have one's heart in the right place", "to be heartbroken", "to be cold and calculating", "to fall in love easily"],
     "note": "Literally \"to have the heart in the right spot\"; praises someone's fundamentally good instincts and character."},
    {"id": "i-de3", "tier": "C1", "topic": "idiom-character",
     "phrase": "ein Hans Dampf in allen Gassen sein", "correct": "to be a jack-of-all-trades who has a hand in everything",
     "options": ["to be a jack-of-all-trades who has a hand in everything", "to be shy and withdrawn", "to be highly disciplined", "to be a slow, methodical worker"],
     "note": "Literally \"a Hans Steam in every alley\"; describes a restless busybody involved in every project going."},
    {"id": "i-de4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "die Kirche im Dorf lassen", "correct": "to not overreact and keep things in proportion",
     "options": ["to not overreact and keep things in proportion", "to attend a religious service", "to move somewhere quiet", "to settle an old dispute"],
     "note": "Literally \"to leave the church in the village\"; a plea not to blow a small matter out of proportion."},
    {"id": "i-de5", "tier": "C1", "topic": "idiom-media",
     "phrase": "etwas an die große Glocke hängen", "correct": "to broadcast something loudly to everyone",
     "options": ["to broadcast something loudly to everyone", "to keep something a closely guarded secret", "to forget about something entirely", "to write something down carefully"],
     "note": "Literally \"to hang something on the big bell\"; used when someone makes sure news reaches as many people as possible."},
    {"id": "i-de6", "tier": "C1", "topic": "idiom-media",
     "phrase": "zwischen den Zeilen lesen", "correct": "to read between the lines",
     "options": ["to read between the lines", "to skim without understanding", "to quote something word for word", "to translate literally"],
     "note": "Literally \"to read between the lines\"; used for picking up on an implied meaning in an article, speech, or report."},
]

NUANCE = [
    {"id": "n-de1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Asking a stranger on the street for directions politely",
     "correct": "Entschuldigen Sie, könnten Sie mir helfen?",
     "options": ["Entschuldigen Sie, könnten Sie mir helfen?", "Hey, wo geht's hier lang?", "Sag mal, wo ist das?", "Zeig mir den Weg."],
     "note": "Entschuldigen Sie + Konjunktiv II (könnten) is the standard polite approach to a stranger; the others are casual du-forms."},
    {"id": "n-de2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Closing a formal business email to a contact you don't know well",
     "correct": "Mit freundlichen Grüßen",
     "options": ["Mit freundlichen Grüßen", "Bis bald", "Tschüss", "Liebe Grüße"],
     "note": "Mit freundlichen Grüßen is the neutral formal sign-off for business correspondence; the rest suit friends or acquaintances."},
    {"id": "n-de3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Saying you know a city well, having lived there for years",
     "correct": "kennen",
     "options": ["kennen", "wissen", "können", "erkennen"],
     "note": "Kennen is for familiarity with people or places; wissen is for facts, können for abilities, erkennen for recognizing something."},
    {"id": "n-de4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Saying you changed jobs last year",
     "correct": "die Stelle wechseln",
     "options": ["die Stelle wechseln", "die Stelle ändern", "die Stelle verändern", "die Stelle tauschen"],
     "note": "Die Stelle wechseln (\"switch job\") is the set expression; ändern/verändern fit modifying something, tauschen means swapping with someone else."},
    {"id": "n-de5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend a concert was awesome (casual)",
     "correct": "Das war der Hammer",
     "options": ["Das war der Hammer", "Das war äußerst angenehm", "Das war zufriedenstellend", "Das erwies sich als angemessen"],
     "note": "Der Hammer / geil / krass are the spoken superlatives; the other options read like a written evaluation report."},
    {"id": "n-de6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Writing formally to a government office asking them to send a document",
     "correct": "Ich wäre Ihnen dankbar, wenn Sie mir das Dokument zusenden könnten",
     "options": ["Ich wäre Ihnen dankbar, wenn Sie mir das Dokument zusenden könnten", "Schickt mir das", "Sendet das mal rüber", "Gebt mir das Ding"],
     "note": "Ich wäre Ihnen dankbar, wenn + Konjunktiv II is the formal Sie-register request; the rest are du/ihr-level and far too blunt for an office."},
    {"id": "n-de7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Softly disagreeing with your boss in a meeting",
     "correct": "Ich bin mir nicht sicher, ob das die beste Lösung ist",
     "options": ["Ich bin mir nicht sicher, ob das die beste Lösung ist", "Das ist falsch", "Das stimmt nicht", "Quatsch"],
     "note": "Ich bin mir nicht sicher, ob softens the objection into a diplomatic doubt; the other options sound like flat contradictions."},
    {"id": "n-de8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Sarcastically reacting to yet another delay",
     "correct": "Na, was für eine Überraschung",
     "options": ["Na, was für eine Überraschung", "Das freut mich sehr", "Wie schön", "Danke vielmals"],
     "note": "\"Na, was für eine Überraschung\" (\"well, what a surprise\") said flatly is the standard sarcastic groan; the other three read as sincere unless heavily inflected."},
]
