# -*- coding: utf-8 -*-
# Dutch skill layer 2: extra grammar (storytelling, complex conditionals, everyday descriptions),
# idioms (character, everyday moments, media), and C2 nuance drills.
LANG = 'nl'

GRAMMAR = [
    {"id": "g-nl1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Terwijl ik ___ was, ging de telefoon.", "correct": "aan het koken",
     "options": ["aan het koken", "gekookt", "kook", "kookte"],
     "note": "The \"aan het + infinitive\" construction marks an action in progress at the moment of interruption, like the English past continuous."},
    {"id": "g-nl2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Nadat we ___ hadden gegeten, gingen we een wandeling maken.", "correct": "klaar",
     "options": ["klaar", "eerst", "al", "nog"],
     "note": "\"Klaar\" here signals the meal was finished before the next action — a common way to sequence events in a narrative."},
    {"id": "g-nl3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Als ik dat ___ geweten, had ik het anders gedaan.", "correct": "had",
     "options": ["had", "heb", "zou", "was"],
     "note": "Third conditional: als + past perfect (had geweten) pairs with had gedaan — a hypothetical about the unchangeable past."},
    {"id": "g-nl4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Mocht het ___ regenen, dan gaat het feest niet door.", "correct": "toch",
     "options": ["toch", "nooit", "vaak", "al"],
     "note": "\"Mocht + subject\" (inverted, no \"als\") is a formal conditional opener meaning \"should it happen that\"; \"toch\" adds \"after all/despite expectations.\""},
    {"id": "g-nl5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Dat is de man ___ auto voor de deur staat.", "correct": "wiens",
     "options": ["wiens", "die", "wie", "wat"],
     "note": "\"Wiens\" is the possessive relative pronoun (\"whose\") used for a masculine/common antecedent — distinct from \"die\" or \"wie.\""},
    {"id": "g-nl6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Het huis waar we ___ wonen, is meer dan honderd jaar oud.", "correct": "nu",
     "options": ["nu", "toen", "ooit", "nooit"],
     "note": "\"Waar\" replaces \"in welk huis\" for places; \"nu\" anchors the description in the present, typical of everyday descriptive Dutch."},
]

IDIOMS = [
    {"id": "i-nl1", "tier": "C1", "topic": "idiom-character",
     "phrase": "Hij heeft het hart op de tong", "correct": "He says exactly what he thinks, very openly",
     "options": ["He says exactly what he thinks, very openly", "He is very shy and quiet", "He lies constantly", "He is easily offended"],
     "note": "Literally \"he has the heart on the tongue\" — a person who speaks their mind without filtering."},
    {"id": "i-nl2", "tier": "C1", "topic": "idiom-character",
     "phrase": "Ze is een stijve hark", "correct": "She is rigid and formal, no sense of fun",
     "options": ["She is rigid and formal, no sense of fun", "She is extremely athletic", "She is very generous", "She is always late"],
     "note": "Literally \"she is a stiff rake\" — describes someone stiff, humorless, or socially awkward."},
    {"id": "i-nl3", "tier": "C1", "topic": "idiom-character",
     "phrase": "Hij is niet op zijn mondje gevallen", "correct": "He is quick-witted and never at a loss for words",
     "options": ["He is quick-witted and never at a loss for words", "He talks too little", "He is clumsy with his hands", "He is a picky eater"],
     "note": "Literally \"he didn't fall on his little mouth\" — someone who always has a sharp, ready reply."},
    {"id": "i-nl4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "De aap komt uit de mouw", "correct": "The real, hidden truth finally comes out",
     "options": ["The real, hidden truth finally comes out", "Everyone starts laughing", "The plan works perfectly", "It starts raining suddenly"],
     "note": "Literally \"the monkey comes out of the sleeve\" — used the moment a concealed truth or trick is revealed."},
    {"id": "i-nl5", "tier": "C1", "topic": "idiom-media",
     "phrase": "Dat is de knuppel in het hoenderhok gooien", "correct": "To say or do something that stirs up controversy",
     "options": ["To say or do something that stirs up controversy", "To calm everyone down", "To make a boring announcement", "To agree with everyone at once"],
     "note": "Literally \"to throw the club into the chicken coop\" — a comment or move on the news that provokes uproar."},
    {"id": "i-nl6", "tier": "C1", "topic": "idiom-media",
     "phrase": "Dat verhaal is met een korreltje zout te nemen", "correct": "That story should be treated with skepticism, not fully believed",
     "options": ["That story should be treated with skepticism, not fully believed", "That story is officially confirmed", "That story is very funny", "That story is too long to read"],
     "note": "Literally \"to be taken with a grain of salt\" — the same idiom as in English, common in media commentary about dubious claims."},
]

NUANCE = [
    {"id": "n-nl1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Asking a stranger on the street for directions, politely",
     "correct": "Zou u me kunnen helpen?",
     "options": ["Zou u me kunnen helpen?", "Help me even", "Kun jij me helpen ofzo", "Wijs me de weg"],
     "note": "\"Zou u kunnen\" combines the formal \"u\" with a conditional, the softest and most polite way to make a request of a stranger."},
    {"id": "n-nl2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Declining a second helping of food at a friend's parents' house, graciously",
     "correct": "Nee, dank u, het was heerlijk zo",
     "options": ["Nee, dank u, het was heerlijk zo", "Nee, ik hoef niet meer", "Genoeg, echt", "Ik zit vol"],
     "note": "Pairing a polite refusal with a compliment (\"it was delicious as it is\") shows the register a guest is expected to use with elders."},
    {"id": "n-nl3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Describing a plan that is likely but not fully confirmed yet",
     "correct": "vermoedelijk",
     "options": ["vermoedelijk", "zeker", "absoluut", "gegarandeerd"],
     "note": "\"Vermoedelijk\" (presumably) precisely conveys likelihood without certainty, unlike the absolute words in the other options."},
    {"id": "n-nl4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Describing a decrease that is small but noticeable, in a formal report",
     "correct": "een lichte daling",
     "options": ["een lichte daling", "een enorme daling", "een instorting", "een kleine ramp"],
     "note": "\"Een lichte daling\" (a slight decline) is the precise, measured term reports use, avoiding the exaggeration of \"instorting\" or \"ramp.\""},
    {"id": "n-nl5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend you're exhausted after a long day (casual spoken Dutch)",
     "correct": "Ik ben kapot",
     "options": ["Ik ben kapot", "Ik ben uitermate vermoeid", "Ik verkeer in een staat van uitputting", "Ik ben afgemat"],
     "note": "\"Ik ben kapot\" (literally \"I'm broken\") is the everyday spoken way to say you're wiped out — the other options sound stiff or written."},
    {"id": "n-nl6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Casually agreeing with a friend's plan, in relaxed spoken Dutch",
     "correct": "Prima, doen we",
     "options": ["Prima, doen we", "Ik ga akkoord met uw voorstel", "Dat lijkt mij een uitstekend idee", "Ik stem daarmee in"],
     "note": "\"Prima, doen we\" (fine, let's do it) is short and casual; the alternatives belong in formal correspondence, not a chat between friends."},
    {"id": "n-nl7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Gently teasing a friend about being late, without real anger",
     "correct": "Typisch jij, weer te laat",
     "options": ["Typisch jij, weer te laat", "Je bent onbetrouwbaar", "Ik ben woedend op je", "Dit is onacceptabel"],
     "note": "\"Typisch jij\" (typical you) carries an affectionate, joking tone — the other options shift to genuine anger or formal complaint."},
    {"id": "n-nl8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Expressing mild disappointment about weather ruining a picnic, without overreacting",
     "correct": "Jammer genoeg regent het",
     "options": ["Jammer genoeg regent het", "Wat een ramp, het regent", "Dit verpest alles totaal", "Ik ben er kapot van dat het regent"],
     "note": "\"Jammer genoeg\" (unfortunately) is a mild, measured shade of disappointment, unlike the dramatic overtones of \"ramp\" or \"verpest alles.\""},
]
