# -*- coding: utf-8 -*-
LANG = 'sv'
WORDS = {
    'c2-to-abate': ('Avta', None),
    'c2-to-abhor': ('Avsky', None),
    'c2-to-abstain': ('Avstå', None),
    'c2-to-accentuate': ('Accentuera', None),
    'c2-to-acquiesce': ('Finna sig i', None),
    'c2-to-admonish': ('Förmana', None),
    'c2-to-alleviate': ('Lindra', None),
    'c2-to-amass': ('Hopa', None),
    'c2-to-appease': ('Blidka', None),
    'c2-to-ascribe': ('Tillskriva', None),
    'c2-to-augment': ('Utöka', None),
    'c2-to-avert': ('Avvärja', None),
    'c2-to-beckon': ('Vinka till sig', None),
    'c2-to-belittle': ('Förringa', None),
    'c2-to-bequeath': ('Testamentera', None),
    'c2-to-beseech': ('Bönfalla', None),
    'c2-to-bewilder': ('Förbrylla', None),
    'c2-to-brandish': ('Svinga', None),
    'c2-to-castigate': ('Gissla', None),
    'c2-to-coalesce': ('Sammansmälta', None),
    'c2-to-commend': ('Berömma', None),
    'c2-to-concede': ('Medge', None),
    'c2-to-concoct': ('Hopdikta', None),
    'c2-to-confer': ('Förläna', None),
    'c2-to-contend': ('Hävda', None),
    'c2-to-corroborate': ('Bestyrka', None),
    'c2-to-aggravate': ('Förvärra', None),
    'c2-to-assail': ('Bestorma', None),
    'c2-to-chastise': ('Tukta', None),
    'c2-to-condescend': ('Nedlåta sig', None),
    'c2-to-debunk': ('Avslöja', None),
    'c2-to-decipher': ('Dechiffrera', None),
    'c2-to-decry': ('Brännmärka', None),
    'c2-to-deem': ('Anse', None),
    'c2-to-defer': ('Uppskjuta', None),
    'c2-to-delineate': ('Avgränsa', None),
    'c2-to-denounce': ('Fördöma', None),
    'c2-to-deplete': ('Uttömma', None),
    'c2-to-deride': ('Förlöjliga', None),
    'c2-to-despair': ('Förtvivla', None),
    'c2-to-detain': ('Anhålla', None),
    'c2-to-deviate': ('Avvika', None),
    'c2-to-disdain': ('Förakta', None),
    'c2-to-disperse': ('Skingra', None),
    'c2-to-dissuade': ('Avråda', None),
    'c2-to-divulge': ('Yppa', None),
    'c2-to-dwindle': ('Krympa', None),
    'c2-to-elude': ('Undgå', None),
    'c2-to-emanate': ('Härröra', None),
    'c2-to-embellish': ('Utsmycka', None),
    'c2-to-encompass': ('Omfatta', None),
    'c2-to-engender': ('Alstra', None),
    'c2-to-enlighten': ('Upplysa', None),
    'c2-to-enthrall': ('Fängsla', None),
    'c2-to-entice': ('Locka', None),
    'c2-to-envision': ('Föreställa sig', None),
    'c2-to-evade': ('Kringgå', None),
    'c2-to-exalt': ('Upphöja', None),
    'c2-to-expedite': ('Påskynda', None),
    'c2-to-extol': ('Lovprisa', None),
    'c2-to-fabricate': ('Fabricera', None),
    'c2-to-falter': ('Vackla', None),
    'c2-to-feign': ('Låtsas', None),
    'c2-to-flourish': ('Blomstra', None),
    'c2-to-forfeit': ('Förverka', None),
    'c2-to-forgo': ('Försaka', None),
    'c2-to-galvanize': ('Sporra', None),
    'c2-to-garner': ('Skörda', None),
    'c2-to-gloat': ('Yvas', None),
    'c2-to-grapple': ('Brottas', None),
    'c2-to-harness': ('Utnyttja', None),
    'c2-to-heed': ('Beakta', None),
    'c2-to-hoard': ('Hamstra', None),
    'c2-to-impart': ('Förmedla', None),
    'c2-to-implore': ('Besvärja', None),
    'c2-to-incite': ('Egga', None),
    'c2-to-inhibit': ('Hämma', None),
    'c2-to-instill': ('Ingjuta', None),
    'c2-to-intercede': ('Gå i förbön', None),
    'c2-to-intimidate': ('Kuva', None),
    'c2-to-jeopardize': ('Äventyra', None),
    'c2-to-languish': ('Tyna bort', None),
    'c2-to-lure': ('Locka in', None),
    'c2-to-marvel': ('Förundras', None),
    'c2-to-meander': ('Slingra sig', None),
    'c2-to-muster': ('Uppbåda', None),
    'c2-to-obliterate': ('Utplåna', None),
    'c2-to-oscillate': ('Oscillera', None),
    'c2-to-ostracize': ('Utstöta', None),
    'c2-to-perpetuate': ('Vidmakthålla', None),
    'c2-to-permeate': ('Genomsyra', None),
    'c2-to-plummet': ('Störtdyka', None),
    'c2-to-ponder': ('Begrunda', None),
    'c2-to-preach': ('Predika', None),
    'c2-to-procure': ('Anskaffa', None),
    'c2-to-proliferate': ('Föröka sig', None),
    'c2-to-propel': ('Driva framåt', None),
    'c2-to-quell': ('Kväsa', None),
    'c2-to-ratify': ('Ratificera', None),
    'c2-to-rebuke': ('Läxa upp', None),
    'c2-to-rebut': ('Vederlägga', None),
    'c2-to-recant': ('Avsvärja sig', None),
    'c2-to-redeem': ('Återlösa', None),
    'c2-to-refute': ('Motbevisa', None),
    'c2-to-relish': ('Njuta av', None),
    'c2-to-renounce': ('Avsäga sig', None),
    'c2-to-replenish': ('Fylla på', None),
    'c2-to-reprimand': ('Tillrättavisa', None),
    'c2-to-repudiate': ('Förkasta', None),
    'c2-to-resonate': ('Genljuda', None),
    'c2-to-retaliate': ('Vedergälla', None),
    'c2-to-revere': ('Vörda', None),
    'c2-to-revoke': ('Återkalla', None),
    'c2-to-saturate': ('Mätta', None),
    'c2-to-scorn': ('Ringakta', None),
    'c2-to-squander': ('Slösa bort', None),
    'c2-to-stagnate': ('Stagnera', None),
    'c2-to-stifle': ('Kväva', None),
    'c2-to-subside': ('Lägga sig', None),
    'c2-to-succumb': ('Duka under', None),
    'c2-to-supplant': ('Undantränga', None),
    'c2-to-surmise': ('Förmoda', None),
    'c2-to-swindle': ('Svindla', None),
    'c2-to-tarnish': ('Befläcka', None),
    'c2-to-thwart': ('Omintetgöra', None),
    'c2-to-transcend': ('Överskrida', None),
    'c2-to-unravel': ('Nysta upp', None),
    'c2-to-usurp': ('Tillskansa sig', None),
    'c2-to-vanquish': ('Besegra', None),
    'c2-to-venerate': ('Dyrka', None),
    'c2-to-vilify': ('Smäda', None),
    'c2-to-wane': ('Dala', None),
    'c2-to-wield': ('Bruka', None),
    'c2-to-writhe': ('Vrida sig', None),
    'c2-to-yearn': ('Längta', None),
    'c2-to-beget': ('Avla', None),
    'c2-to-besiege': ('Belägra', None),
    'c2-to-cajole': ('Lirka med', None),
    'c2-to-coax': ('Övertala', None),
    'c2-to-deplore': ('Deplorera', None),
    'c2-to-disparage': ('Nedvärdera', None),
    'c2-to-exhort': ('Mana', None),
    'c2-to-foment': ('Underblåsa', None),
    'c2-to-indulge': ('Hänge sig åt', None),
    'c2-to-placate': ('Stilla', None),
    'c2-to-preempt': ('Förekomma', None),
    'c2-to-rescind': ('Upphäva', None),
    'c2-to-stymie': ('Stäcka', None),
    'c2-to-vindicate': ('Rentvå', None),
    'c2-to-evince': ('Ådagalägga', None),
    'c2-affable': ('Älskvärd', None),
    'c2-churlish': ('Buttrig', None),
    'c2-astute': ('Skarpsinnig', None),
    'c2-audacious': ('Dristig', None),
    'c2-belligerent': ('Stridslysten', None),
    'c2-sanguine': ('Sangvinisk', None),
    'c2-brusque': ('Brysk', None),
    'c2-callous': ('Känslokall', None),
    'c2-truculent': ('Barsk', None),
    'c2-capricious': ('Nyckfull', None),
    'c2-complacent': ('Självbelåten', None),
    'c2-unflappable': ('Orubblig', None),
    'c2-cunning': ('Listig', None),
    'c2-diffident': ('Försagd', None),
    'c2-officious': ('Beskäftig', None),
    'c2-docile': ('Foglig', None),
    'c2-erudite': ('Lärd', None),
    'c2-fastidious': ('Kräsen', None),
    'c2-flippant': ('Nonchalant', None),
    'c2-garrulous': ('Pratsjuk', None),
    'c2-gregarious': ('Sällskaplig', None),
    'c2-haughty': ('Högdragen', None),
    'c2-impetuous': ('Obetänksam', None),
    'c2-indolent': ('Indolent', None),
    'c2-mercurial': ('Lynnig', None),
    'c2-phlegmatic': ('Flegmatisk', None),
    'c2-obsequious': ('Inställsam', None),
    'c2-petulant': ('Grinig', None),
    'c2-sanctimonious': ('Skenhelig', None),
    'c2-taciturn': ('Fåordig', None),
    'c2-bountiful': ('Ymnig', None),
    'c2-arduous': ('Mödosam', None),
    'c2-banal': ('Banal', None),
    'c2-copious': ('Riklig', None),
    'c2-cumbersome': ('Otymplig', None),
    'c2-deft': ('Fingerfärdig', None),
    'c2-dire': ('Ödesdiger', None),
    'c2-ephemeral': ('Flyktig', None),
    'c2-peerless': ('Makalös', None),
    'c2-feeble': ('Kraftlös', None),
    'c2-rickety': ('Skranglig', None),
    'c2-formidable': ('Formidabel', None),
    'c2-immaculate': ('Fläckfri', None),
    'c2-faultless': ('Felfri', None),
    'c2-innocuous': ('Oskadlig', None),
    'c2-insidious': ('Lömsk', None),
    'c2-labyrinthine': ('Labyrintisk', None),
    'c2-profligate': ('Slösaktig', None),
    'c2-perspicuous': ('Lättfattlig', None),
    'c2-sparse': ('Gles', None),
    'c2-infinitesimal': ('Infinitesimal', None),
    'c2-sumptuous': ('Praktfull', None),
    'c2-paltry': ('Futtig', None),
    'c2-unblemished': ('Obefläckad', None),
    'c2-indomitable': ('Okuvlig', None),
    'c2-scant': ('Knapp', None),
    'c2-transcendent': ('Transcendent', None),
    'c2-tenuous': ('Skör', None),
    'c2-unwieldy': ('Klumpig', None),
    'c2-boundless': ('Gränslös', None),
    'c2-abstruse': ('Svårbegriplig', None),
    'c2-apt': ('Träffande', None),
    'c2-cogent': ('Övertygande', None),
    'c2-contentious': ('Omtvistad', None),
    'c2-deplorable': ('Beklaglig', None),
    'c2-dubious': ('Tvivelaktig', None),
    'c2-egregious': ('Flagrant', None),
    'c2-exemplary': ('Föredömlig', None),
    'c2-fallacious': ('Vilseledande', None),
    'c2-futile': ('Fåfäng', None),
    'c2-gratuitous': ('Omotiverad', None),
    'c2-illicit': ('Olovlig', None),
    'c2-impartial': ('Opartisk', None),
    'c2-incongruous': ('Malplacerad', None),
    'c2-ineffable': ('Outsäglig', None),
    'c2-irrefutable': ('Obestridlig', None),
    'c2-laudable': ('Lovvärd', None),
    'c2-moot': ('Akademisk (om fråga)', None),
    'c2-nebulous': ('Dunkel', None),
    'c2-ostensible': ('Skenbar', None),
    'c2-pernicious': ('Fördärvlig', None),
    'c2-plausible': ('Trovärdig', None),
    'c2-preposterous': ('Befängd', None),
    'c2-salient': ('Framträdande', None),
    'c2-spurious': ('Oäkta', None),
    'c2-superfluous': ('Överflödig', None),
    'c2-tenable': ('Hållbar', None),
    'c2-untenable': ('Ohållbar', None),
    'c2-viable': ('Genomförbar', None),
    'c2-wanton': ('Lättsinnig', None),
    'c2-ailing': ('Sjuklig', None),
    'c2-bewildered': ('Förbryllad', None),
    'c2-desolate': ('Ödslig', None),
    'c2-brittle': ('Spröd', None),
    'c2-cohesive': ('Sammanhållen', None),
    'c2-defunct': ('Utdöd', None),
    'c2-derelict': ('Övergiven', None),
    'c2-ramshackle': ('Fallfärdig', None),
    'c2-dormant': ('Vilande', None),
    'c2-drowsy': ('Dåsig', None),
    'c2-dwindling': ('Avtagande', None),
    'c2-exhilarated': ('Upprymd', None),
    'c2-forlorn': ('Tröstlös', None),
    'c2-haggard': ('Tärd', None),
    'c2-imminent': ('Nära förestående', None),
    'c2-incessant': ('Oupphörlig', None),
    'c2-inert': ('Inert', None),
    'c2-jaded': ('Luttrad', None),
    'c2-languid': ('Slö', None),
    'c2-listless': ('Håglös', None),
    'c2-antiquated': ('Föråldrad', None),
    'c2-precarious': ('Prekär', None),
    'c2-rampant': ('Utbredd', None),
    'c2-fidgety': ('Rastlös', None),
    'c2-rife': ('Florerande', None),
    'c2-sodden': ('Genomblöt', None),
    'c2-stagnant': ('Stillastående', None),
    'c2-susceptible': ('Mottaglig', None),
    'c2-volatile': ('Oberäknelig', None),
    'c2-weary': ('Trött', None),
    'c2-bombastic': ('Bombastisk', None),
    'c2-vernacular': ('Vardaglig', None),
    'c2-concise': ('Koncis', None),
    'c2-tortuous': ('Vindlande', None),
    'c2-cryptic': ('Kryptisk', None),
    'c2-derogatory': ('Nedsättande', None),
    'c2-didactic': ('Didaktisk', None),
    'c2-silver-tongued': ('Vältalig', None),
    'c2-emphatic': ('Eftertrycklig', None),
    'c2-euphemistic': ('Förskönande', None),
    'c2-facetious': ('Skämtsam', None),
    'c2-florid': ('Svulstig', None),
    'c2-glib': ('Munvig', None),
    'c2-hyperbolic': ('Hyperbolisk', None),
    'c2-incisive': ('Skarp', None),
    'c2-laconic': ('Lakonisk', None),
    'c2-long-winded': ('Mångordig', None),
    'c2-mordant': ('Bitsk', None),
    'c2-ornate': ('Utsirad', None),
    'c2-pedantic': ('Pedantisk', None),
    'c2-pithy': ('Kärnfull', None),
    'c2-plaintive': ('Klagande', None),
    'c2-rhetorical': ('Retorisk', None),
    'c2-sardonic': ('Sardonisk', None),
    'c2-scathing': ('Förintande', None),
    'c2-succinct': ('Kortfattad', None),
    'c2-terse': ('Kärv', None),
    'c2-trite': ('Utnött', None),
    'c2-verbose': ('Ordrik', None),
    'c2-wry': ('Spydig', None),
    'c2-acumen': ('Skarpsinne', None),
    'c2-alacrity': ('Beredvillighet', None),
    'c2-ambivalence': ('Ambivalens', None),
    'c2-apathy': ('Apati', None),
    'c2-aplomb': ('Aplomb', None),
    'c2-audacity': ('Dristighet', None),
    'c2-candor': ('Uppriktighet', None),
    'c2-smugness': ('Självbelåtenhet', None),
    'c2-scorn': ('Förakt', None),
    'c2-deference': ('Aktning', None),
    'c2-discretion': ('Diskretion', None),
    'c2-disdain': ('Ringaktning', None),
    'c2-forbearance': ('Tålamod', None),
    'c2-fortitude': ('Själsstyrka', None),
    'c2-hubris': ('Hybris', None),
    'c2-meekness': ('Ödmjukhet', None),
    'c2-umbrage': ('Harm', None),
    'c2-ingenuity': ('Uppfinningsrikedom', None),
    'c2-rectitude': ('Rättskaffenhet', None),
    'c2-malice': ('Illvilja', None),
    'c2-nostalgia': ('Nostalgi', None),
    'c2-perseverance': ('Uthållighet', None),
    'c2-prudence': ('Försiktighet', None),
    'c2-grit': ('Beslutsamhet', None),
    'c2-reticence': ('Tystlåtenhet', None),
    'c2-equanimity': ('Jämnmod', None),
    'c2-tenacity': ('Envishet', None),
    'c2-vanity': ('Fåfänga', None),
    'c2-vigilance': ('Vaksamhet', None),
    'c2-zeal': ('Nitälskan', None),
    'c2-anomaly': ('Avvikelse', None),
    'c2-catalyst': ('Katalysator', None),
    'c2-conundrum': ('Huvudbry', None),
    'c2-debacle': ('Debakel', None),
    'c2-deluge': ('Störtflod', None),
    'c2-dearth': ('Brist', None),
    'c2-dichotomy': ('Dikotomi', None),
    'c2-epitome': ('Inbegrepp', None),
    'c2-exodus': ('Exodus', None),
    'c2-facade': ('Fasad', None),
    'c2-fallacy': ('Felslut', None),
    'c2-hindsight': ('Efterklokhet', None),
    'c2-impasse': ('Dödläge', None),
    'c2-impetus': ('Drivkraft', None),
    'c2-juncture': ('Skede', None),
    'c2-loophole': ('Kryphål', None),
    'c2-tipping-point': ('Brytpunkt', None),
    'c2-onslaught': ('Anstormning', None),
    'c2-vicious-circle': ('Ond cirkel', None),
    'c2-plight': ('Nödläge', None),
    'c2-precedent': ('Prejudikat', None),
    'c2-quandary': ('Klämma', None),
    'c2-ramification': ('Följdverkan', None),
    'c2-respite': ('Andrum', None),
    'c2-setback': ('Bakslag', None),
    'c2-stalemate': ('Patt', None),
    'c2-surge': ('Uppsving', None),
    'c2-turmoil': ('Tumult', None),
    'c2-upheaval': ('Omvälvning', None),
    'c2-watershed': ('Vattendelare', None),
    'c2-accomplice': ('Medbrottsling', None),
    'c2-adversary': ('Motståndare', None),
    'c2-advocate': ('Förespråkare', None),
    'c2-benefactor': ('Välgörare', None),
    'c2-bystander': ('Åskådare', None),
    'c2-charlatan': ('Charlatan', None),
    'c2-connoisseur': ('Kännare', None),
    'c2-culprit': ('Bov', None),
    'c2-demagogue': ('Demagog', None),
    'c2-dilettante': ('Dilettant', None),
    'c2-envoy': ('Sändebud', None),
    'c2-lackey': ('Lakej', None),
    'c2-understudy': ('Ersättare', None),
    'c2-hypocrite': ('Hycklare', None),
    'c2-insurgent': ('Upprorsman', None),
    'c2-layperson': ('Lekman', None),
    'c2-maverick': ('Särling', None),
    'c2-sidekick': ('Följeslagare', None),
    'c2-mercenary': ('Legosoldat', None),
    'c2-novice': ('Novis', None),
    'c2-pariah': ('Paria', None),
    'c2-patron': ('Mecenat', None),
    'c2-perpetrator': ('Gärningsman', None),
    'c2-prodigy': ('Underbarn', None),
    'c2-informant': ('Angivare', None),
    'c2-recluse': ('Eremit', None),
    'c2-sage': ('Vis man', None),
    'c2-turncoat': ('Avfälling', None),
    'c2-stalwart': ('Stöttepelare', None),
    'c2-tycoon': ('Magnat', None),
    'c2-ambiguity': ('Tvetydighet', None),
    'c2-analogy': ('Analogi', None),
    'c2-axiom': ('Axiom', None),
    'c2-caveat': ('Förbehåll', None),
    'c2-consensus': ('Konsensus', None),
    'c2-corollary': ('Följdsats', None),
    'c2-yardstick': ('Måttstock', None),
    'c2-narrative': ('Narrativ', None),
    'c2-doctrine': ('Doktrin', None),
    'c2-dogma': ('Dogm', None),
    'c2-epiphany': ('Uppenbarelse', None),
    'c2-ethos': ('Etos', None),
    'c2-conjecture': ('Förmodan', None),
    'c2-idiosyncrasy': ('Egenhet', None),
    'c2-deduction': ('Deduktion', None),
    'c2-innuendo': ('Insinuation', None),
    'c2-buzzword': ('Modeord', None),
    'c2-simile': ('Liknelse', None),
    'c2-nuance': ('Nyans', None),
    'c2-archetype': ('Arketyp', None),
    'c2-platitude': ('Plattityd', None),
    'c2-postulate': ('Postulat', None),
    'c2-pretext': ('Förevändning', None),
    'c2-rebuttal': ('Vederläggning', None),
    'c2-rhetoric': ('Retorik', None),
    'c2-semantics': ('Semantik', None),
    'c2-stigma': ('Stigma', None),
    'c2-tenet': ('Grundsats', None),
    'c2-trope': ('Trop', None),
    'c2-zeitgeist': ('Tidsanda', None),
    'c2-acrid': ('Frän', None),
    'c2-astringent': ('Sammandragande', None),
    'c2-bland-flavorless': ('Smaklös', None),
    'c2-brackish': ('Bräckt', None),
    'c2-cloying': ('Kväljande', None),
    'c2-coarse': ('Grov', None),
    'c2-creamy': ('Krämig', None),
    'c2-crunchy': ('Knaprig', None),
    'c2-dank': ('Fuktkall', None),
    'c2-earthy': ('Jordig', None),
    'c2-fragrant': ('Doftande', None),
    'c2-gooey': ('Kladdig', None),
    'c2-grainy': ('Grynig', None),
    'c2-unctuous': ('Oljig', None),
    'c2-gravelly-voice': ('Skrovlig (röst)', None),
    'c2-luscious': ('Läcker', None),
    'c2-mellow': ('Mild', None),
    'c2-hushed': ('Dämpad', None),
    'c2-musty': ('Unken', None),
    'c2-piercing': ('Genomträngande', None),
    'c2-pungent': ('Stickande', None),
    'c2-putrid': ('Ruttet', None),
    'c2-rancid': ('Härsket', None),
    'c2-bitter-aftertaste': ('Bitter eftersmak', None),
    'c2-grating-sound': ('Skärande (ljud)', None),
    'c2-silky': ('Silkeslen', None),
    'c2-slimy': ('Slemmig', None),
    'c2-soggy': ('Uppblötad', None),
    'c2-tangy': ('Syrlig', None),
    'c2-zesty': ('Kryddig', None),
    'c2-better-late-than-never': ('Bättre sent än aldrig', None),
    'c2-actions-speak-louder-than-words': ('Handling talar högre än ord', None),
    'c2-the-early-bird-catches-the-worm': ('Morgonstund har guld i mund', None),
    "c2-don-t-count-your-chickens-before-they-hatch": ('Man ska inte sälja skinnet innan björnen är skjuten', None),
    'c2-every-cloud-has-a-silver-lining': ('Inget ont som inte har något gott med sig', None),
    'c2-practice-makes-perfect': ('Övning ger färdighet', None),
    'c2-when-in-rome-do-as-the-romans-do': ('När du är i Rom, gör som romarna', None),
    'c2-two-heads-are-better-than-one': ('Två huvuden är bättre än ett', None),
    'c2-the-grass-is-always-greener-on-the-other-side': ('Gräset är alltid grönare på andra sidan', None),
    "c2-don-t-judge-a-book-by-its-cover": ('Döm inte boken efter omslaget', None),
    'c2-birds-of-a-feather-flock-together': ('Kaka söker maka', None),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('Bättre en fågel i handen än tio i skogen', None),
    "c2-where-there-s-a-will-there-s-a-way": ('Där det finns en vilja finns det en väg', None),
    "c2-rome-wasn-t-built-in-a-day": ('Rom byggdes inte på en dag', None),
    'c2-too-many-cooks-spoil-the-broth': ('Ju fler kockar, desto sämre soppa', None),
    'c2-out-of-sight-out-of-mind': ('Ur syn, ur sinn', None),
    'c2-look-before-you-leap': ('Se dig för innan du hoppar', None),
    'c2-necessity-is-the-mother-of-invention': ('Nöden är uppfinningarnas moder', None),
    "c2-you-can-t-have-your-cake-and-eat-it-too": ('Man kan inte äta kakan och ha den kvar', None),
    'c2-honesty-is-the-best-policy': ('Ärlighet varar längst', None),
    'c2-still-waters-run-deep': ('Stilla vatten har djupa bottnar', None),
    'c2-blood-is-thicker-than-water': ('Blod är tjockare än vatten', None),
    'c2-absence-makes-the-heart-grow-fonder': ('Avstånd gör hjärtat varmare', None),
    'c2-every-dog-has-its-day': ('Varje hund har sin dag', None),
    'c2-haste-makes-waste': ('Skynda långsamt', None),
    'c2-let-sleeping-dogs-lie': ('Väck inte den björn som sover', None),
    'c2-strike-while-the-iron-is-hot': ('Smida medan järnet är varmt', None),
    'c2-the-pen-is-mightier-than-the-sword': ('Pennan är mäktigare än svärdet', None),
    'c2-curiosity-killed-the-cat': ('Nyfikenheten dödade katten', None),
    "c2-beggars-can-t-be-choosers": ('Den som tigger kan inte välja', None),
    'c2-to-draw-a-distinction': ('Göra en åtskillnad', None),
    'c2-to-reach-a-verdict': ('Avkunna en dom', None),
    'c2-to-pose-a-threat': ('Utgöra ett hot', None),
    'c2-to-bear-the-brunt': ('Ta smällen', None),
    'c2-to-lend-credence-to': ('Ge trovärdighet åt', None),
    'c2-to-wield-influence': ('Utöva inflytande', None),
    'c2-to-incur-a-cost': ('Ådra sig en kostnad', None),
    'c2-to-uphold-a-principle': ('Upprätthålla en princip', None),
    'c2-to-exert-pressure': ('Utöva påtryckningar', None),
    'c2-to-fulfil-an-obligation': ('Uppfylla en skyldighet', None),
    'c2-to-cast-doubt-on': ('Så tvivel om', None),
    'c2-to-pay-tribute-to': ('Hylla', None),
    'c2-to-take-precedence-over': ('Ha företräde framför', None),
    'c2-to-run-the-risk-of': ('Löpa risken att', None),
    'c2-to-strike-a-balance': ('Hitta en balans', None),
    'c2-to-come-to-fruition': ('Bära frukt', None),
    'c2-to-shed-light-on': ('Kasta ljus över', None),
    'c2-to-set-a-precedent': ('Skapa ett prejudikat', None),
    'c2-to-give-rise-to': ('Ge upphov till', None),
    'c2-to-take-issue-with': ('Ifrågasätta', None),
    'c2-pursuant-to': ('I enlighet med', None),
    'c2-heretofore': ('Hittills', None),
    'c2-inasmuch-as': ('I den mån som', None),
    'c2-in-conjunction-with': ('I samband med', None),
    'c2-hitherto': ('Dittills', None),
    'c2-forthwith': ('Omedelbart', None),
    'c2-whilst': ('Medan', None),
    'c2-wherein': ('Vari', None),
    'c2-vis-a-vis': ('Gentemot', None),
    'c2-as-regards': ('Beträffande', None),
    'c2-for-the-sake-of-argument': ('För resonemangets skull', None),
    'c2-be-that-as-it-may': ('Hur det än må vara', None),
    'c2-on-balance': ('Allt sammantaget', None),
    'c2-at-the-behest-of': ('På begäran av', None),
    'c2-in-the-wake-of': ('I kölvattnet av', None),
    'c2-on-the-grounds-that': ('Med motiveringen att', None),
    'c2-in-accordance-with': ('I överensstämmelse med', None),
    'c2-pending': ('I avvaktan på', None),
    'c2-irrespective-of': ('Oavsett', None),
    'c2-hereinafter': ('Hädanefter', None),
    'c2-beats-me': ('Ingen aning', None),
    'c2-point-taken': ('Poängen är tagen', None),
    'c2-suit-yourself': ('Gör som du vill', None),
    'c2-go-figure': ('Gå veta', None),
    "c2-don-t-get-me-started": ('Sätt inte igång mig', None),
    'c2-bottom-line-is': ('Kort sagt', None),
    'c2-off-the-top-of-my-head': ('På rak arm', None),
    "c2-i-ll-say": ('Och hur', None),
    "c2-you-ve-got-to-be-kidding-me": ('Du skämtar väl', None),
    'c2-no-offense-but': ('Inte illa menat, men', None),
    "c2-i-m-not-gonna-lie": ('Jag ska inte ljuga', None),
    'c2-speak-of-the-devil': ('Tala om trollen', None),
    "c2-it-s-on-the-tip-of-my-tongue": ('Jag har det på tungan', None),
    "c2-let-s-call-it-a-day": ('Nu slutar vi för idag', None),
    "c2-it-s-not-rocket-science": ('Det är ingen hjärnkirurgi', None),
    "c2-that-s-the-last-straw": ('Det är droppen', None),
    "c2-i-couldn-t-care-less": ('Det struntar jag fullständigt i', None),
    'c2-what-are-the-odds': ('Vilken slump', None),
    'c2-say-no-more': ('Säg inte mer', None),
    'c2-hang-in-there': ('Håll ut', None),
    "c2-i-m-all-ears": ('Jag är idel öra', None),
    "c2-that-s-on-me": ('Det är mitt fel', None),
    'c2-no-hard-feelings': ('Inget agg', None),
    'c2-ditto': ('Detsamma', None),
    'c2-spill-the-beans': ('Skvallra', None),
    'c2-in-one-ear-and-out-the-other': ('In genom ena örat och ut genom det andra', None),
    'c2-cut-to-the-chase': ('Gå rakt på sak', None),
    'c2-you-name-it': ('Vad som helst', None),
    'c2-not-in-a-million-years': ('Aldrig i livet', None),
    'c2-it-is-what-it-is': ('Det är som det är', None),
    'c2-give-me-a-break': ('Lägg av', None),
    'c2-hold-your-horses': ('Ta det lugnt', None),
    'c2-bite-the-bullet': ('Bita ihop', None),
    'c2-take-it-with-a-grain-of-salt': ('Ta det med en nypa salt', None),
    'c2-better-safe-than-sorry': ('Bättre stämma i bäcken än i ån', None),
    "c2-let-s-play-it-by-ear": ('Vi tar det som det kommer', None),
    "c2-i-ll-take-a-rain-check": ('Vi tar det en annan gång', None),
    "c2-for-what-it-s-worth": ('För vad det nu är värt', None),
    'c2-back-to-square-one': ('Tillbaka på ruta ett', None),
    'c2-touch-wood': ('Peppar, peppar, ta i trä', None),
    'c2-allusion': ('Anspelning', None),
    'c2-anecdote': ('Anekdot', None),
    'c2-antithesis': ('Antites', None),
    'c2-aphorism': ('Aforism', None),
    'c2-banter': ('Retsamt käbbel', None),
    'c2-circumlocution': ('Omskrivning', None),
    'c2-cliche': ('Klyscha', None),
    'c2-connotation': ('Bibetydelse', None),
    'c2-digression': ('Utvikning', None),
    'c2-double-entendre': ('Dubbeltydighet', None),
    'c2-eloquence': ('Vältalighet', None),
    'c2-euphemism': ('Eufemism', None),
    'c2-gist': ('Kärnan (i saken)', None),
    'c2-hyperbole': ('Hyperbol', None),
    'c2-irony': ('Ironi', None),
    'c2-juxtaposition': ('Sammanställning', None),
    'c2-malapropism': ('Felsägning', None),
    'c2-oxymoron': ('Oxymoron', None),
    'c2-paraphrase': ('Parafras', None),
    'c2-pun': ('Ordvits', None),
    'c2-quip': ('Kvickhet', None),
    'c2-sarcasm': ('Sarkasm', None),
    'c2-slur-insult': ('Glåpord', None),
    'c2-repartee': ('Slagfärdighet', None),
    'c2-soliloquy': ('Monolog', None),
    'c2-subtext': ('Underton', None),
    'c2-tangent': ('Sidospår', None),
    'c2-tirade': ('Tirad', None),
    'c2-understatement': ('Underdrift', None),
    'c2-verbiage': ('Ordflöde', None),
    'c2-to-allude-to': ('Anspela på', None),
    'c2-to-enunciate': ('Artikulera', None),
    'c2-to-belabor-the-point': ('Älta', None),
    'c2-to-digress': ('Sväva ut', None),
    'c2-to-expound': ('Utveckla', None),
    'c2-to-insinuate': ('Antyda', None),
    'c2-to-interject': ('Flika in', None),
    'c2-to-hammer-home': ('Inskärpa', None),
    'c2-to-retort': ('Genmäla', None),
    'c2-to-waffle-be-vague': ('Svamla', None),
    'c2-actuary': ('Aktuarie', None),
    'c2-anesthesiologist': ('Anestesiolog', None),
    'c2-archivist': ('Arkivarie', None),
    'c2-auditor': ('Revisor', None),
    'c2-bailiff': ('Kronofogde', None),
    'c2-blacksmith': ('Smed', None),
    'c2-cartographer': ('Kartograf', None),
    'c2-chiropractor': ('Kiropraktor', None),
    'c2-coroner': ('Rättsläkare', None),
    'c2-curator': ('Intendent', None),
    'c2-diplomat': ('Diplomat', None),
    'c2-dietitian': ('Dietist', None),
    'c2-entomologist': ('Entomolog', None),
    'c2-forensic-scientist': ('Kriminaltekniker', None),
    'c2-geologist': ('Geolog', None),
    'c2-glazier': ('Glasmästare', None),
    'c2-interpreter-simultaneous': ('Simultantolk', None),
    'c2-locksmith': ('Låssmed', None),
    'c2-midwife': ('Barnmorska', None),
    'c2-court-clerk': ('Notarie', None),
    'c2-oncologist': ('Onkolog', None),
    'c2-ophthalmologist': ('Ögonläkare', None),
    'c2-paleontologist': ('Paleontolog', None),
    'c2-paralegal': ('Juristassistent', None),
    'c2-pathologist': ('Patolog', None),
    'c2-physiotherapist': ('Fysioterapeut', None),
    'c2-public-defender': ('Offentlig försvarare', None),
    'c2-radiologist': ('Radiolog', None),
    'c2-perfumer': ('Parfymör', None),
    'c2-stenographer': ('Stenograf', None),
    'c2-surveyor': ('Lantmätare', None),
    'c2-taxidermist': ('Taxidermist', None),
    'c2-upholsterer': ('Tapetserare', None),
    'c2-veterinarian-specialist': ('Veterinär', None),
    'c2-welder': ('Svetsare', None),
    'c2-anthropology': ('Antropologi', None),
    'c2-archaeology': ('Arkeologi', None),
    'c2-astrophysics': ('Astrofysik', None),
    'c2-biochemistry': ('Biokemi', None),
    'c2-botany': ('Botanik', None),
    'c2-cartography': ('Kartografi', None),
    'c2-criminology': ('Kriminologi', None),
    'c2-demography': ('Demografi', None),
    'c2-econometrics': ('Ekonometri', None),
    'c2-epidemiology': ('Epidemiologi', None),
    'c2-epistemology': ('Epistemologi', None),
    'c2-ethnography': ('Etnografi', None),
    'c2-genetics': ('Genetik', None),
    'c2-geopolitics': ('Geopolitik', None),
    'c2-hermeneutics': ('Hermeneutik', None),
    'c2-immunology': ('Immunologi', None),
    'c2-jurisprudence': ('Rättsvetenskap', None),
    'c2-linguistics': ('Lingvistik', None),
    'c2-metaphysics': ('Metafysik', None),
    'c2-meteorology': ('Meteorologi', None),
    'c2-microbiology': ('Mikrobiologi', None),
    'c2-musicology': ('Musikvetenskap', None),
    'c2-neuroscience': ('Neurovetenskap', None),
    'c2-oceanography': ('Oceanografi', None),
    'c2-ornithology': ('Ornitologi', None),
    'c2-pedagogy': ('Pedagogik', None),
    'c2-pharmacology': ('Farmakologi', None),
    'c2-philology': ('Filologi', None),
    'c2-phonetics': ('Fonetik', None),
    'c2-seismology': ('Seismologi', None),
    'c2-semiotics': ('Semiotik', None),
    'c2-sociolinguistics': ('Sociolingvistik', None),
    'c2-theology': ('Teologi', None),
    'c2-toxicology': ('Toxikologi', None),
    'c2-zoology': ('Zoologi', None),
    'c2-acute-sudden-severe': ('Akut', None),
    'c2-latent': ('Latent', None),
    'c2-benign': ('Godartad', None),
    'c2-malignant': ('Elakartad', None),
    'c2-biopsy': ('Biopsi', None),
    'c2-prognosis': ('Prognos', None),
    'c2-flare-up': ('Skov', None),
    'c2-recurrence': ('Återfall', None),
    'c2-sedative': ('Lugnande medel', None),
    'c2-anesthetic': ('Bedövningsmedel', None),
    'c2-antibody': ('Antikropp', None),
    'c2-inflammation': ('Inflammation', None),
    'c2-airborne': ('Luftburen', None),
    'c2-hereditary': ('Ärftlig', None),
    'c2-congenital': ('Medfödd', None),
    'c2-dosage': ('Dosering', None),
    'c2-placebo': ('Placebo', None),
    'c2-contraindication': ('Kontraindikation', None),
    'c2-intravenous': ('Intravenös', None),
    'c2-suture': ('Sutur', None),
    'c2-incision': ('Incision', None),
    'c2-donor': ('Donator', None),
    'c2-ultrasound': ('Ultraljud', None),
    'c2-referral-to-a-specialist': ('Remiss', None),
    'c2-inpatient': ('Inneliggande patient', None),
    'c2-palliative-care': ('Palliativ vård', None),
    'c2-triage': ('Triage', None),
    'c2-convalescence': ('Konvalescens', None),
    'c2-immunity': ('Immunitet', None),
    'c2-pandemic': ('Pandemi', None),
    'c2-pathogen': ('Patogen', None),
    'c2-electrolyte': ('Elektrolyt', None),
    'c2-cardiovascular': ('Kardiovaskulär', None),
    'c2-respiratory': ('Respiratorisk', None),
    'c2-neurological': ('Neurologisk', None),
    'c2-symptomatic': ('Symtomatisk', None),
    'c2-asymptomatic': ('Asymtomatisk', None),
    'c2-prescription-written-order': ('Recept', None),
    'c2-generic-drug': ('Generiskt läkemedel', None),
    'c2-informed-consent': ('Informerat samtycke', None),
    'c2-acquittal': ('Frikännande', None),
    'c2-conviction-guilty-verdict': ('Fällande dom', None),
    'c2-deposition': ('Vittnesutsaga', None),
    'c2-accessory-to-a-crime': ('Medhjälpare till brott', None),
    'c2-arson': ('Mordbrand', None),
    'c2-remand': ('Häktning', None),
    'c2-burden-of-proof': ('Bevisbörda', None),
    'c2-custody-detention': ('Kvarhållande', None),
    'c2-defendant': ('Tilltalad', None),
    'c2-plaintiff': ('Kärande', None),
    'c2-embezzlement': ('Förskingring', None),
    'c2-extortion': ('Utpressning', None),
    'c2-felony': ('Grovt brott', None),
    'c2-misdemeanor': ('Förseelse', None),
    'c2-forgery': ('Förfalskning', None),
    'c2-hearsay': ('Hörsägen', None),
    'c2-indictment': ('Åtal', None),
    'c2-injunction': ('Föreläggande', None),
    'c2-tribunal': ('Tribunal', None),
    'c2-libel': ('Förtal', None),
    'c2-slander': ('Ärekränkning', None),
    'c2-manslaughter': ('Dråp', None),
    'c2-parole': ('Villkorlig frigivning', None),
    'c2-perjury': ('Mened', None),
    'c2-plea-bargain': ('Erkännandeuppgörelse', None),
    'c2-probation': ('Skyddstillsyn', None),
    'c2-racketeering': ('Beskyddarverksamhet', None),
    'c2-ransom': ('Lösensumma', None),
    'c2-statute': ('Författning', None),
    'c2-statute-of-limitations': ('Preskriptionstid', None),
    'c2-subpoena': ('Kallelse', None),
    'c2-testimony': ('Vittnesmål', None),
    'c2-ruling': ('Domslut', None),
    'c2-warrant': ('Arresteringsorder', None),
    'c2-witness-stand': ('Vittnesbås', None),
    'c2-contempt-of-court': ('Domstolstrots', None),
    'c2-cross-examination': ('Korsförhör', None),
    'c2-mistrial': ('Ogiltigförklarad rättegång', None),
    'c2-sentence-punishment': ('Straff', None),
    'c2-to-plead-guilty': ('Erkänna sig skyldig', None),
    'c2-thicket': ('Snår', None),
    'c2-undergrowth': ('Undervegetation', None),
    'c2-moss': ('Mossa', None),
    'c2-lichen': ('Lav', None),
    'c2-fern': ('Ormbunke', None),
    'c2-sap': ('Sav', None),
    'c2-bark-of-a-tree': ('Bark', None),
    'c2-sapling': ('Telning', None),
    'c2-canopy-forest': ('Lövtak', None),
    'c2-grove': ('Lund', None),
    'c2-meadow': ('Äng', None),
    'c2-marsh': ('Träsk', None),
    'c2-bog': ('Myr', None),
    'c2-estuary': ('Flodmynning', None),
    'c2-tributary': ('Biflod', None),
    'c2-ravine': ('Ravin', None),
    'c2-gorge': ('Klyfta', None),
    'c2-ridge': ('Bergskam', None),
    'c2-summit': ('Topp', None),
    'c2-foothills': ('Förberg', None),
    'c2-escarpment': ('Brant', None),
    'c2-salt-flat': ('Saltslätt', None),
    'c2-cove': ('Vik', None),
    'c2-atoll': ('Atoll', None),
    'c2-tide-pool': ('Tidvattenpöl', None),
    'c2-driftwood': ('Drivved', None),
    'c2-pebble': ('Kiselsten', None),
    'c2-boulder': ('Flyttblock', None),
    'c2-sediment': ('Sediment', None),
    'c2-erosion': ('Erosion', None),
    'c2-burrow': ('Lya', None),
    'c2-hive': ('Bikupa', None),
    'c2-cocoon': ('Kokong', None),
    'c2-antler': ('Gevir', None),
    'c2-talon': ('Klo', None),
    'c2-plumage': ('Fjäderdräkt', None),
    'c2-migration-animal': ('Flyttning', None),
    'c2-hibernation': ('Vinterdvala', None),
    'c2-pollination': ('Pollinering', None),
    'c2-germination': ('Groning', None),
    'c2-torrential': ('Skyfallsartad', None),
    'c2-monsoon': ('Monsun', None),
    'c2-sleet': ('Snöblandat regn', None),
    'c2-flurry-snow': ('Snöby', None),
    'c2-whiteout': ('Vitout', None),
    'c2-black-ice': ('Svart is', None),
    'c2-dew': ('Dagg', None),
    'c2-haze': ('Dis', None),
    'c2-clammy': ('Klibbig', None),
    'c2-scorcher': ('Stekhet dag', None),
    'c2-sultry': ('Tryckande', None),
    'c2-balmy': ('Ljummen', None),
    'c2-crisp-air': ('Frisk (luft)', None),
    'c2-gust': ('Vindby', None),
    'c2-gale': ('Kuling', None),
    'c2-squall': ('Kastby', None),
    'c2-thunderclap': ('Åskskräll', None),
    'c2-lightning-bolt': ('Blixt', None),
    'c2-cloudburst': ('Skyfall', None),
    'c2-nightfall': ('Mörkrets inbrott', None),
    'c2-cold-snap': ('Köldknäpp', None),
    'c2-thaw': ('Tö', None),
    'c2-humidity': ('Luftfuktighet', None),
    'c2-barometer': ('Barometer', None),
    'c2-forecast-verb': ('Förutspå', None),
    'c2-daybreak': ('Gryning', None),
    'c2-aurora': ('Norrsken', None),
    'c2-twilight': ('Skymning', None),
    'c2-solstice': ('Solstånd', None),
    'c2-equinox': ('Dagjämning', None),
    'c2-arch': ('Valvbåge', None),
    'c2-vault-ceiling': ('Valv', None),
    'c2-dome': ('Kupol', None),
    'c2-spire': ('Spira', None),
    'c2-buttress': ('Strävpelare', None),
    'c2-pillar': ('Pelare', None),
    'c2-column': ('Kolonn', None),
    'c2-beam-structural': ('Bjälke', None),
    'c2-rafter': ('Sparre', None),
    'c2-girder': ('Bärbalk', None),
    'c2-keystone': ('Slutsten', None),
    'c2-facade-building-front': ('Fasad', None),
    'c2-cornice': ('Gesims', None),
    'c2-gable': ('Gavel', None),
    'c2-eaves': ('Takfot', None),
    'c2-gutter-roof': ('Takränna', None),
    'c2-skylight': ('Takfönster', None),
    'c2-balustrade': ('Balustrad', None),
    'c2-parapet': ('Bröstvärn', None),
    'c2-turret': ('Litet torn', None),
    'c2-moat': ('Vallgrav', None),
    'c2-drawbridge': ('Vindbrygga', None),
    'c2-cloister': ('Kloster', None),
    'c2-courtyard': ('Innergård', None),
    'c2-alcove': ('Nisch', None),
    'c2-mezzanine': ('Mellanvåning', None),
    'c2-atrium': ('Atrium', None),
    'c2-mosaic': ('Mosaik', None),
    'c2-fresco': ('Fresk', None),
    'c2-elevation-drawing': ('Fasadritning', None),
    'c2-partition-wall': ('Mellanvägg', None),
    'c2-cladding': ('Fasadbeklädnad', None),
    'c2-plumbing-system': ('Rörsystem', None),
    'c2-ventilation-duct': ('Ventilationskanal', None),
    'c2-retrofit': ('Eftermontering', None),
    'c2-colander': ('Durkslag', None),
    'c2-ladle': ('Slev', None),
    'c2-whisk': ('Visp', None),
    'c2-grater': ('Rivjärn', None),
    'c2-tongs': ('Tång', None),
    'c2-spatula': ('Stekspade', None),
    'c2-cutting-board': ('Skärbräda', None),
    'c2-french-press': ('Pressbryggare', None),
    'c2-coaster': ('Glasunderlägg', None),
    'c2-trivet': ('Grytunderlägg', None),
    'c2-oven-mitt': ('Ugnsvante', None),
    'c2-dish-rack': ('Diskställ', None),
    'c2-dustpan': ('Sopskyffel', None),
    'c2-mop': ('Mopp', None),
    'c2-clothespin': ('Klädnypa', None),
    'c2-clothesline': ('Tvättlina', None),
    'c2-shoehorn': ('Skohorn', None),
    'c2-doormat': ('Dörrmatta', None),
    'c2-doorknob': ('Dörrvred', None),
    'c2-hinge': ('Gångjärn', None),
    'c2-latch': ('Haspa', None),
    'c2-peephole': ('Dörrspion', None),
    'c2-blinds-window': ('Persienner', None),
    'c2-windowsill': ('Fönsterbräda', None),
    'c2-banister': ('Ledstång', None),
    'c2-landing-stairs': ('Trappavsats', None),
    'c2-crawl-space': ('Krypgrund', None),
    'c2-cellar': ('Källare', None),
    'c2-pantry': ('Skafferi', None),
    'c2-utility-room': ('Grovkök', None),
    'c2-fuse-box': ('Säkringsskåp', None),
    'c2-dimmer-switch': ('Dimmer', None),
    'c2-extension-cord': ('Förlängningssladd', None),
    'c2-power-strip': ('Grenuttag', None),
    'c2-carbon-monoxide-alarm': ('Kolmonoxidlarm', None),
    'c2-first-aid-kit': ('Förbandslåda', None),
    'c2-sewing-kit': ('Syskrin', None),
    'c2-toolbox': ('Verktygslåda', None),
    'c2-allen-key': ('Insexnyckel', None),
    'c2-pliers': ('Kniptång', None),
    'c2-wrench': ('Skiftnyckel', None),
    'c2-tape-measure': ('Måttband', None),
    'c2-spirit-level': ('Vattenpass', None),
    'c2-drawer-organizer': ('Lådinsats', None),
    'c2-bin-liner': ('Soppåse', None),
    'c2-to-seethe': ('Sjuda av ilska', None),
    'c2-to-sulk': ('Tjura', None),
    'c2-to-fret': ('Gräma sig', None),
    'c2-to-brood': ('Grubbla', None),
    'c2-to-wallow-in-self-pity': ('Vältra sig i självömkan', None),
    'c2-to-gloat-over-a-rival': ('Triumfera skadeglatt över', None),
    'c2-to-savor-the-moment': ('Smaka på ögonblicket', None),
    'c2-to-revel-in': ('Frossa i', None),
    'c2-to-marvel-at': ('Förundras över', None),
    'c2-to-cringe': ('Krypa ihop av obehag', None),
    'c2-to-wince': ('Rycka till', None),
    'c2-to-flinch': ('Rygga', None),
    'c2-to-shudder': ('Rysa', None),
    'c2-to-quiver': ('Darra', None),
    'c2-to-swoon': ('Svimma av hänförelse', None),
    'c2-to-pine-for': ('Tråna efter', None),
    'c2-to-long-for': ('Längta efter', None),
    'c2-to-crave': ('Åtrå', None),
    'c2-to-abominate': ('Förfasa sig över', None),
    'c2-to-nurse-a-grievance': ('Hysa agg', None),
    'c2-to-begrudge': ('Missunna', None),
    'c2-to-grovel': ('Krypa för', None),
    'c2-to-fawn-over': ('Fjäska för', None),
    'c2-to-dote-on': ('Avguda', None),
    'c2-to-treasure': ('Skatta högt', None),
    'c2-to-put-at-ease': ('Lugna', None),
    'c2-to-console': ('Trösta', None),
    'c2-to-commiserate': ('Visa medkänsla', None),
    'c2-to-exasperate': ('Förarga starkt', None),
    'c2-to-infuriate': ('Göra rasande', None),
    'c2-to-unnerve': ('Skaka om', None),
    'c2-to-mortify': ('Förnedra', None),
    'c2-to-captivate': ('Tjusa', None),
    'c2-to-enrapture': ('Hänföra', None),
    'c2-to-disillusion': ('Desillusionera', None),
    'c2-to-mollify': ('Lugna ner', None),
    'c2-to-embolden': ('Ge mod åt', None),
    'c2-to-dishearten': ('Ta modet ur', None),
    'c2-to-rankle': ('Gnaga', None),
    'c2-to-smolder': ('Pyra', None),
    'c2-numbness': ('Domning', None),
    'c2-tingling': ('Stickningar', None),
    'c2-cramp': ('Kramp', None),
    'c2-twinge': ('Hugg', None),
    'c2-throbbing': ('Bultande', None),
    'c2-dizziness': ('Yrsel', None),
    'c2-lightheaded': ('Yr i huvudet', None),
    'c2-vertigo': ('Svindel', None),
    'c2-queasy': ('Illamående', None),
    'c2-lethargy': ('Letargi', None),
    'c2-fatigue': ('Utmattning', None),
    'c2-stamina': ('Kondition', None),
    'c2-reflex': ('Reflex', None),
    'c2-flinch-noun': ('Ryckning', None),
    'c2-pins-and-needles': ('Myrkrypningar', None),
    'c2-shiver': ('Rysning', None),
    'c2-hot-flush': ('Värmevallning', None),
    'c2-blush': ('Rodnad', None),
    'c2-yawn': ('Gäspning', None),
    'c2-hiccup': ('Hicka', None),
    'c2-sneeze': ('Nysning', None),
    'c2-itch': ('Klåda', None),
    'c2-bruise': ('Blåmärke', None),
    'c2-blister': ('Blåsa', None),
    'c2-pulled-muscle': ('Muskelsträckning', None),
    'c2-stiffness': ('Stelhet', None),
    'c2-restlessness': ('Rastlöshet', None),
    'c2-daydream': ('Dagdröm', None),
    'c2-deja-vu': ('Déjà vu', None),
    'c2-hunch': ('Aning', None),
    'c2-gut-feeling': ('Magkänsla', None),
    'c2-brain-fog': ('Hjärndimma', None),
    'c2-second-wind': ('Andra andningen', None),
    'c2-adrenaline-rush': ('Adrenalinkick', None),
    'c2-motion-sickness': ('Åksjuka', None),
    'c2-camaraderie': ('Kamratskap', None),
    'c2-affinity-between-people': ('Samhörighet', None),
    'c2-clique': ('Klick', None),
    'c2-entourage': ('Följe', None),
    'c2-etiquette': ('Etikett', None),
    'c2-faux-pas': ('Fadäs', None),
    'c2-gossip': ('Skvaller', None),
    'c2-grudge': ('Agg', None),
    'c2-chain-of-command': ('Befälsordning', None),
    'c2-nepotism': ('Nepotism', None),
    'c2-ostracism': ('Utfrysning', None),
    'c2-groupthink': ('Grupptänkande', None),
    'c2-pecking-order': ('Rangordning', None),
    'c2-rivalry': ('Rivalitet', None),
    'c2-solidarity': ('Solidaritet', None),
    'c2-snub': ('Avsnäsning', None),
    'c2-taboo': ('Tabu', None),
    'c2-flattery': ('Smicker', None),
    'c2-backhanded-compliment': ('Giftig komplimang', None),
    'c2-cold-shoulder': ('Kalla handen', None),
    'c2-small-circle-inner-circle': ('Inre krets', None),
    'c2-interloper': ('Inkräktare', None),
    'c2-old-hand': ('Gammal räv', None),
    'c2-wingman': ('Draghjälp', None),
    'c2-freeloader': ('Snyltare', None),
    'c2-busybody': ('Snokare', None),
    'c2-killjoy': ('Glädjedödare', None),
    'c2-show-off': ('Skrytmåns', None),
    'c2-pushover': ('Mes', None),
    'c2-self-starter': ('Initiativtagare', None),
    'c2-to-mingle': ('Mingla', None),
    'c2-to-schmooze': ('Charma sig fram', None),
    'c2-to-shun': ('Frysa ut', None),
    'c2-to-patronize': ('Behandla nedlåtande', None),
    'c2-to-reconcile': ('Försonas', None),
    'c2-to-estrange': ('Fjärma', None),
    'c2-to-confide-in': ('Anförtro sig åt', None),
    'c2-to-hobnob': ('Frottera sig', None),
    'c2-to-rub-shoulders-with': ('Röra sig i samma kretsar som', None),
    'c2-to-fall-out-with': ('Bli osams med', None),
    'c2-foil-character': ('Kontrastfigur', None),
    'c2-anti-hero': ('Antihjälte', None),
    'c2-narrator': ('Berättare', None),
    'c2-macguffin': ('Macguffin', None),
    'c2-red-herring': ('Falskt spår', None),
    'c2-motif': ('Motiv', None),
    'c2-frame-narrative': ('Ramberättelse', None),
    'c2-denouement': ('Upplösning', None),
    'c2-satire': ('Satir', None),
    'c2-parody': ('Parodi', None),
    'c2-allegory': ('Allegori', None),
    'c2-memoir': ('Memoarer', None),
    'c2-anthology': ('Antologi', None),
    'c2-manuscript': ('Manuskript', None),
    'c2-prose': ('Prosa', None),
    'c2-couplet': ('Parrim', None),
    'c2-stanza': ('Strof', None),
    'c2-sonnet': ('Sonett', None),
    'c2-alliteration': ('Allitteration', None),
    'c2-meter-poetry': ('Versmått', None),
    'c2-aesthetic': ('Estetik', None),
    'c2-avant-garde': ('Avantgarde', None),
    'c2-baroque': ('Barock', None),
    'c2-impressionism': ('Impressionism', None),
    'c2-surrealism': ('Surrealism', None),
    'c2-still-life': ('Stilleben', None),
    'c2-charcoal-drawing': ('Kolteckning', None),
    'c2-etching': ('Etsning', None),
    'c2-bust-sculpture': ('Byst', None),
    'c2-chisel': ('Mejsel', None),
    'c2-easel': ('Staffli', None),
    'c2-palette': ('Palett', None),
    'c2-overture': ('Uvertyr', None),
    'c2-aria': ('Aria', None),
    'c2-encore': ('Extranummer', None),
    'c2-bandwidth': ('Bandbredd', None),
    'c2-jitter': ('Jitter', None),
    'c2-throughput': ('Genomströmning', None),
    'c2-hashing': ('Hashning', None),
    'c2-intrusion-detection': ('Intrångsdetektering', None),
    'c2-vulnerability-security': ('Sårbarhet', None),
    'c2-hotfix': ('Snabbfix', None),
    'c2-backlog': ('Backlogg', None),
    'c2-rollout': ('Utrullning', None),
    'c2-rollback': ('Återställning', None),
    'c2-uptime': ('Drifttid', None),
    'c2-redundancy-backup': ('Redundans', None),
    'c2-load-balancing': ('Lastbalansering', None),
    'c2-legacy-system': ('Äldre system', None),
    'c2-copyleft': ('Copyleft', None),
    'c2-proprietary': ('Proprietär', None),
    'c2-interoperability': ('Interoperabilitet', None),
    'c2-passkey': ('Åtkomstnyckel', None),
    'c2-social-engineering': ('Social manipulation', None),
    'c2-data-breach': ('Dataintrång', None),
    'c2-cache': ('Cacheminne', None),
    'c2-query': ('Sökfråga', None),
    'c2-metadata': ('Metadata', None),
    'c2-placeholder': ('Platshållare', None),
    'c2-workaround': ('Tillfällig lösning', None),
    'c2-bottleneck': ('Flaskhals', None),
    'c2-edge-case': ('Gränsfall', None),
    'c2-deprecated': ('Utfasad', None),
    'c2-sandbox': ('Sandlåda', None),
    'c2-telemetry': ('Telemetri', None),
    'c2-algorithmic-bias': ('Algoritmisk snedvridning', None),
    'c2-overfitting': ('Överanpassning', None),
    'c2-large-language-model': ('Stor språkmodell', None),
    'c2-quantum-computing': ('Kvantdatorteknik', None),
    'c2-semiconductor': ('Halvledare', None),
    'c2-working-capital': ('Rörelsekapital', None),
    'c2-solvency': ('Solvens', None),
    'c2-insolvency': ('Insolvens', None),
    'c2-receivership': ('Konkursförvaltning', None),
    'c2-leverage-finance': ('Hävstång', None),
    'c2-hedge-finance': ('Säkring', None),
    'c2-yield-finance': ('Avkastning', None),
    'c2-share-buyback': ('Återköp av aktier', None),
    'c2-equity-ownership': ('Eget kapital', None),
    'c2-treasury-bill': ('Statsskuldväxel', None),
    'c2-asset-allocation': ('Tillgångsallokering', None),
    'c2-volatility': ('Volatilitet', None),
    'c2-bull-market': ('Tjurmarknad', None),
    'c2-bear-market': ('Björnmarknad', None),
    'c2-downturn': ('Nedgång', None),
    'c2-stagflation': ('Stagflation', None),
    'c2-deflation': ('Deflation', None),
    'c2-interest-rate-hike': ('Räntehöjning', None),
    'c2-fiscal-policy': ('Finanspolitik', None),
    'c2-monetary-policy': ('Penningpolitik', None),
    'c2-subsidy': ('Subvention', None),
    'c2-trade-quota': ('Handelskvot', None),
    'c2-embargo': ('Embargo', None),
    'c2-belt-tightening': ('Dra åt svångremmen', None),
    'c2-bailout': ('Räddningspaket', None),
    'c2-windfall': ('Skänk från ovan', None),
    'c2-nest-egg': ('Sparkapital', None),
    'c2-slush-fund': ('Svart kassa', None),
    'c2-kickback': ('Olaglig provision', None),
    'c2-money-laundering': ('Penningtvätt', None),
    'c2-tax-evasion': ('Skatteflykt', None),
    'c2-tax-loophole': ('Skattekryphål', None),
    'c2-underwriter': ('Försäkringsgivare', None),
    'c2-sinking-fund': ('Amorteringsfond', None),
    'c2-arbitrage': ('Arbitrage', None),
    'c2-freight': ('Frakt', None),
    'c2-cargo-hold': ('Lastrum', None),
    'c2-consignment': ('Sändning', None),
    'c2-customs-clearance': ('Tullklarering', None),
    'c2-red-eye-flight': ('Nattflyg', None),
    'c2-turbulence': ('Turbulens', None),
    'c2-taxiing': ('Taxning', None),
    'c2-cockpit': ('Cockpit', None),
    'c2-overhead-compartment': ('Bagagehylla', None),
    'c2-aisle-seat': ('Gångplats', None),
    'c2-boarding-pass': ('Boardingkort', None),
    'c2-baggage-carousel': ('Bagageband', None),
    'c2-jet-bridge': ('Ombordningsbrygga', None),
    'c2-tailgating-driving': ('Köra tätt inpå', None),
    'c2-gridlock': ('Total trafikstockning', None),
    'c2-diversion-route': ('Omledning', None),
    'c2-interchange-highway': ('Trafikplats', None),
    'c2-overpass': ('Viadukt', None),
    'c2-underpass': ('Underfart', None),
    'c2-toll-booth': ('Betalstation', None),
    'c2-hard-shoulder': ('Vägren', None),
    'c2-speed-bump': ('Farthinder', None),
    'c2-blind-spot': ('Döda vinkeln', None),
    'c2-hazard-lights': ('Varningsblinkers', None),
    'c2-windshield-wiper': ('Vindrutetorkare', None),
    'c2-clutch-car': ('Koppling', None),
    'c2-handbrake': ('Handbroms', None),
    'c2-odometer': ('Vägmätare', None),
    'c2-tow-truck': ('Bärgningsbil', None),
    'c2-commute-noun': ('Arbetspendling', None),
    'c2-numerator': ('Täljare', None),
    'c2-denominator': ('Nämnare', None),
    'c2-exponent': ('Exponent', None),
    'c2-square-root': ('Kvadratrot', None),
    'c2-decimal-point': ('Decimalkomma', None),
    'c2-remainder': ('Rest', None),
    'c2-prime-number': ('Primtal', None),
    'c2-integer': ('Heltal', None),
    'c2-quotient': ('Kvot', None),
    'c2-percentile': ('Percentil', None),
    'c2-mean-average': ('Medelvärde', None),
    'c2-median': ('Median', None),
    'c2-outlier': ('Extremvärde', None),
    'c2-standard-deviation': ('Standardavvikelse', None),
    'c2-variance': ('Varians', None),
    'c2-margin-of-error': ('Felmarginal', None),
    'c2-sample-size': ('Stickprovsstorlek', None),
    'c2-exponential-growth': ('Exponentiell tillväxt', None),
    'c2-order-of-magnitude': ('Storleksordning', None),
    'c2-rounding': ('Avrundning', None),
    'c2-percentage-point': ('Procentenhet', None),
    'c2-threefold': ('Tredubbel', None),
    'c2-a-dozen': ('Ett dussin', None),
    'c2-round-number': ('Runt tal', None),
    'c2-odds-probability': ('Odds', None),
    'c2-inseam': ('Innerbenslängd', None),
    'c2-dart-sewing': ('Tuck', None),
    'c2-lapel': ('Kavajslag', None),
    'c2-cuff': ('Manschett', None),
    'c2-cufflinks': ('Manschettknappar', None),
    'c2-gusset': ('Kil', None),
    'c2-pleat': ('Veck', None),
    'c2-tailored': ('Skräddarsydd', None),
    'c2-bespoke': ('Måttbeställd', None),
    'c2-off-the-rack': ('Konfektion', None),
    'c2-threadbare': ('Luggsliten', None),
    'c2-frayed': ('Fransig', None),
    'c2-creased': ('Skrynklig', None),
    'c2-dapper': ('Flott', None),
    'c2-disheveled': ('Rufsig', None),
    'c2-scruffy': ('Sjaskig', None),
    'c2-garish': ('Gräll', None),
    'c2-understated': ('Diskret', None),
    'c2-flattering-clothes': ('Klädsam', None),
    'c2-baggy': ('Säckig', None),
    'c2-snug': ('Åtsittande', None),
    'c2-stubble': ('Skäggstubb', None),
    'c2-freckles': ('Fräknar', None),
    'c2-dimple': ('Smilgrop', None),
    "c2-crow-s-feet": ('Skrattrynkor', None),
    'c2-complexion': ('Hy', None),
    'c2-gaunt': ('Avmagrad', None),
    'c2-stocky': ('Satt', None),
    'c2-lanky': ('Gänglig', None),
    'c2-poised': ('Behärskad', None),
}
