# -*- coding: utf-8 -*-
LANG = 'de'

SENTENCES = {
    'b1-dr1': ['Ich', 'lerne', 'Auto', 'zu fahren'],
    'b1-dr2': ['Normalerweise', 'wache ich', 'früh auf'],
    'b1-dr3': ['Gestern', 'habe ich', 'das ganze', 'Haus geputzt'],
    'b1-dr4': ['Ich habe', 'noch nie', 'einen Arbeitstag', 'verpasst'],
    'b1-fs1': ['Mein Bruder', 'treibt', 'keinen', 'Sport'],
    'b1-fs2': ['Wir sollten', 'unsere', 'Eltern', 'anrufen'],
    'b1-fs3': ['Könnten Sie', 'mir dabei', 'bitte', 'helfen?'],
    'b1-fs4': ['Meine Schwester', 'ist', 'gesprächiger', 'als ich'],
    'b1-te1': ['Gestern', 'habe ich', 'eine neue Stadt', 'besucht'],
    'b1-te2': ['Wenn es regnet,', 'bleiben wir', 'im Hotel'],
    'b1-te3': ['Ich war', 'noch nie', 'in Japan'],
    'b1-te4': ['Kannst du', 'ein gutes Hotel', 'empfehlen?'],
    'b1-op1': ['Die Musik', 'ist', 'sehr', 'laut'],
    'b1-op2': ['Diese Stadt', 'ist', 'teurer', 'als jene'],
    'b1-op3': ['Ich finde,', 'dieses Buch', 'ist sehr', 'interessant'],
    'b1-op4': ['Meiner Meinung nach,', 'sollten wir', 'früh', 'losgehen'],
    'c2-s01': ['Ehrlich gesagt,', 'hätte ich es mir', 'zweimal überlegt,', 'bevor ich', 'so etwas unterschreibe'],
    'c2-s02': ['Es ist nicht so,', 'dass es mir egal wäre —', 'es ist so,', 'dass mir nichts', 'mehr zu geben bleibt'],
    'c2-s03': ['Was du auch tust,', 'lass nicht zu,', 'dass er dich', 'dazu überredet'],
    'c2-s04': ['Hätte ich gewusst,', 'dass es sich so lange hinzieht,', 'hätte ich nie', 'zugestimmt'],
    'c2-s05': ['Sie tat es als nichts ab,', 'aber man merkte,', 'dass es sie', 'mitgenommen hatte'],
    'c2-s06': ['Sag, was du willst', 'über ihn,', 'aber', 'er bringt die Dinge', 'zustande'],
    'c2-s07': ['Ich werde mich', 'nicht entschuldigen', 'für etwas,', 'das ich nicht einmal', 'getan habe'],
    'c2-s08': ['Bis sie', 'es endlich', 'reparierten,', 'war der Schaden', 'schon angerichtet'],
    'c2-s09': ['Unter uns gesagt,', 'ich glaube nicht,', 'dass der Deal', 'zustande', 'kommt'],
    'c2-s10': ['Man sollte meinen,', 'dass sie es', 'inzwischen', 'gelernt hätten,', 'oder?'],
    'c2-s11': ['Kaum', 'hatten wir uns gesetzt,', 'da', 'ging der', 'Feueralarm los'],
    'c2-s12': ['Wenn es dir', 'nichts ausmacht,', 'würde ich lieber,', 'dass das', 'inoffiziell bleibt'],
    'c1-m01': ['Die Regierung', 'kündigte', 'neue Maßnahmen an,', 'um die Inflation', 'zu senken'],
    'c1-m02': ['Laut dem Bericht,', 'sank die', 'Arbeitslosigkeit', 'den dritten Monat', 'in Folge'],
    'c1-m03': ['Ich habe nie gesagt,', 'dass ich gehe;', 'ich sagte,', 'dass ich Zeit', 'brauche'],
    'c1-m04': ['Was auch immer', 'heute Nacht passiert,', 'öffne diese', 'Tür nicht'],
    'c1-m05': ['Wissenschaftler', 'warnen,', 'dass der Gletscher', 'innerhalb eines Jahrzehnts', 'verschwinden könnte'],
    'c1-m06': ['Wenn du mir', 'die Wahrheit gesagt hättest,', 'wäre nichts', 'davon passiert'],
    'c1-m07': ['Der Verdächtige', 'wurde festgenommen,', 'kurz nachdem', 'die Polizei einen', 'anonymen Hinweis erhalten hatte'],
    'c1-m08': ['Ehrlich gesagt,', 'glaube ich,', 'dass wir beide schuld sind', 'an dem, was passiert ist'],
    'c1-m09': ['Das Unternehmen', 'wies', 'die Vorwürfe zurück,', 'wollte sich aber', 'nicht weiter dazu äußern'],
    'c1-m10': ['Du hast keine Ahnung,', 'worauf ich verzichtet habe,', 'um hierher', 'zu kommen'],
    'c1-m11': ['Die Wähler', 'werden am Sonntag', 'zur Wahl gehen,', 'inmitten', 'wachsender Unsicherheit'],
    'c1-m12': ['Sagen wir einfach,', 'es lief nicht so,', 'wie ich es', 'geplant hatte'],
}

DIALOGUES = {
    'd-a2-01': ['Hallo, ich bin Marta. Freut mich.', 'Freut mich, ich bin Alex.', 'Nein, danke.', 'Es ist rechts.', 'Es ist drei Uhr.'],
    'd-a2-02': ['Woher kommst du?', 'Ich komme aus Chicago, in den USA.', 'Ich bin zwanzig Jahre alt.', 'Ich mag Kaffee.', 'Ich arbeite in einer Bank.'],
    'd-a2-03': ['Was machst du beruflich?', 'Ich bin Designer, ich arbeite von zu Hause aus.', 'Ich wohne in der Nähe des Parks.', 'Ich bevorzuge Tee.', 'Morgen regnet es.'],
    'd-a2-04': ['Wie lange bist du schon hier?', 'Ich bin seit zwei Monaten hier.', 'Es kostet zehn Euro.', 'Es ist sonntags geschlossen.', 'Ich habe zwei Brüder.'],
    'd-a2-05': ['Hast du Geschwister?', 'Ja, eine ältere Schwester.', 'Ja, um acht Uhr.', 'Nein, es ist sehr teuer.', 'Es ist in der Küche.'],
    'd-a2-06': ['Danke fürs Kommen, bis bald!', 'Danke dir, es war toll! Bis bald.', 'Ich hätte gern einen Kaffee.', 'Entschuldigung, ich verstehe nicht.', 'Die Toilette ist dort.'],
    'd-a2-07': ['Ist das heute kalt, oder?', 'Ja, wirklich sehr. Und sie sagen, dass es morgen schneit.', 'Ja, ich heiße Alex.', 'Nein, ich habe keine Geschwister.', 'Es kostet fünf Euro.'],
    'd-a2-08': ['Was hast du für Pläne fürs Wochenende?', 'Ich werde meine Eltern besuchen.', 'Ich arbeite in einem Büro.', 'Es ist links.', 'Ich bevorzuge Rot.'],
    'd-a2-09': ['Trinken wir morgen einen Kaffee?', 'Klar! Passt dir zehn Uhr?', 'Ich komme aus Madrid.', 'Ich habe einen Hund.', 'Es regnet sehr stark.'],
    'd-a2-10': ['Um wie viel Uhr fängt der Film an?', 'Er fängt um halb acht an.', 'Es ist sehr weit.', 'Es gefällt mir sehr.', 'Ich bin Student.'],
    'd-a2-11': ['Wie war dein Tag heute?', 'Ziemlich gut, aber ich bin müde.', 'Das macht zwei Euro.', 'Ich wohne im dritten Stock.', 'Das ist meine Schwester.'],
    'd-a2-12': ['Wohin gehst du?', 'Zum Supermarkt, ich habe nichts zum Abendessen.', 'Ich bin dreißig Jahre alt.', 'Es ist sehr heiß.', 'Ja, ich spreche ein bisschen.'],
    'd-b1-01': ['Lange nicht gesehen! Was hast du so gemacht?', 'Nun, ich habe vor zwei Monaten den Job gewechselt und bin begeistert.', 'Der Zug fährt um neun Uhr ab.', 'Ich bevorzuge Tee gegenüber Kaffee.', 'Es ist zwei Blocks von hier entfernt.'],
    'd-b1-02': ['In letzter Zeit bin ich mit der Arbeit sehr gestresst.', 'Das tut mir sehr leid. Möchtest du darüber reden?', 'Ich habe ein neues Fahrrad gekauft.', 'Der Film fängt um acht Uhr an.', 'Meine Schwester lebt in Rom.'],
    'd-b1-03': ['Wie war die Reise? Erzähl mir alles!', 'Unglaublich. Das Essen, die Leute… ich will schon zurück.', 'Ich muss Milch kaufen.', 'Ich arbeite von neun bis fünf.', 'Im Januar ist es kalt.'],
    'd-b1-04': ['Lucía und ich haben letzte Woche Schluss gemacht.', 'Oh, das wusste ich nicht. Wie kommst du damit klar?', 'Herzlichen Glückwunsch! Was für eine gute Nachricht.', 'Um wie viel Uhr treffen wir uns?', 'Das Museum schließt montags.'],
    'd-b1-05': ['Gehst du noch ins Fitnessstudio?', 'Ehrlich gesagt, ich habe aufgehört. Jetzt gehe ich morgens joggen.', 'Ja, das Brot schmeckt sehr gut.', 'Ich wohne im fünften Stock.', 'Morgen ist Dienstag.'],
    'd-b1-06': ['Hast du schon die Serie gesehen, die ich dir empfohlen habe? Was hast du davon gehalten?', 'Sie hat mich schon ab der ersten Folge gefesselt, auch wenn mich das Ende etwas enttäuscht hat.', 'Es kostet zwanzig Euro.', 'Ich habe zwei Katzen.', 'Die Toilette ist hinten.'],
    'd-b1-07': ['Gehen wir am Samstag wandern?', 'Am Samstag kann ich nicht, ich habe eine Hochzeit. Passt dir der Sonntag?', 'Ja, ich heiße Alex.', 'Die Ampel ist rot.', 'Dieser Wein kommt aus Chile.'],
    'd-b1-08': ['Entschuldigung, ich werde fünfzehn Minuten zu spät kommen.', 'Kein Problem, ich warte auf dich im Café an der Ecke.', 'Ich mag die Farbe Blau.', 'Heute ist es sehr windig.', 'Mein Geburtstag ist im Mai.'],
    'd-b1-09': ['Teilen wir die Rechnung, oder zahle ich diesmal?', 'Teilen wir, aber das nächste Mal lade ich ein.', 'Es regnet wieder.', 'Ich bin in Chicago geboren.', 'Der Bus fährt alle zehn Minuten.'],
    'd-b1-10': ['Hilfst du mir am Donnerstag beim Umzug?', 'Klar, du kannst auf mich zählen. Ich höre um sechs Uhr mit der Arbeit auf, passt dir das?', 'Der Käse ist im Kühlschrank.', 'Ich lerne seit einem Jahr Japanisch.', 'Der Strand ist weit weg.'],
    'd-b1-11': ['Essen wir im neuen Grillrestaurant zu Abend?', 'Das Ding ist, ich bin Vegetarier. Kennst du einen Ort mit mehr Auswahl?', 'Montags habe ich Klavierunterricht.', 'Die Straße ist gesperrt.', 'Mein Vater ist Arzt.'],
    'd-b1-12': ['Kannst du mir fünfzig Euro bis Freitag leihen?', 'Ja, kein Problem. Ich überweise sie dir jetzt gleich.', 'Ich bevorzuge das Fenster gegenüber dem Gang.', 'Am Strand scheint die Sonne.', 'Meine Großmutter ist achtzig Jahre alt.'],
    'd-b2-01': ['Ich glaube, Homeoffice schadet der Teamarbeit.', 'Da bin ich mir nicht so sicher. Meiner Erfahrung nach leistet das Team mit guten Werkzeugen genauso gut oder besser.', 'Der Bericht ist im blauen Ordner.', 'Ich bevorzuge Kaffee ohne Zucker.', 'Morgen gibt es einen Zugstreik.'],
    'd-b2-02': ['Die sozialen Medien machen uns einsamer.', 'Zum Teil schon, auch wenn sie vielen Menschen geholfen haben, Gemeinschaften zu finden, die sie in ihrer Nähe nicht hatten.', 'Mein Passwort hat acht Zeichen.', 'Dieses Restaurant schließt um elf Uhr.', 'Ich habe gestern die Tickets gekauft.'],
    'd-b2-03': ['Glaubst du, man sollte Autos im Zentrum verbieten?', 'Ja, vorausgesetzt sie verbessern den öffentlichen Nahverkehr; sonst verlagert man das Problem nur in die Stadtviertel.', 'Das Zentrum ist zehn Minuten zu Fuß entfernt.', 'Mein Auto ist rot.', 'Sonntags arbeite ich nicht.'],
    'd-b2-04': ['Sechs Sprachen gleichzeitig zu lernen ist unmöglich.', 'Schwierig, ja, aber nicht unmöglich: Die romanischen Sprachen stärken sich gegenseitig, und Japanisch und Chinesisch teilen viele Zeichen.', 'Heute sind es zwanzig Grad.', 'Ich habe einen Termin beim Zahnarzt.', 'Das Paket kommt am Donnerstag an.'],
    'd-b2-05': ['Die Miete wird nächsten Monat um zwanzig Prozent steigen.', 'Ich verstehe, dass die Kosten gestiegen sind, aber zwanzig Prozent sind viel. Könnten wir uns auf zehn einigen und für zwei Jahre verlängern?', 'Das Badezimmer ist am Ende des Flurs.', 'Ich liebe die Aussicht von hier.', 'Heute ist mein Geburtstag.'],
    'd-b2-06': ['Die Baustelle wird sich um zwei Wochen verzögern.', 'Was genau ist der Grund? Ich brauche ein festes Datum, um den Mieter zu informieren.', 'Die Fliesen sind grau.', 'Ich arbeite in der Immobilienbranche.', 'An der Ecke ist eine Apotheke.'],
    'd-b2-07': ['Es tut mir leid, Ihr Antrag auf Rückerstattung wurde abgelehnt.', 'Laut Ihrer Richtlinie habe ich dreißig Tage, um es zurückzugeben, und es sind erst zwölf vergangen. Mit wem kann ich sprechen, um die Entscheidung überprüfen zu lassen?', 'Ich hätte gern einen Tisch für vier.', 'Ich wohne in der Nähe des Flusses.', 'Mein Bruder ist Ingenieur.'],
    'd-b2-08': ['Gestern Abend war die Musik zu laut, ich konnte nicht schlafen.', 'Sie haben völlig recht, das tut mir sehr leid. Von jetzt an werde ich die Lautstärke nach zehn Uhr leiser stellen.', 'Der Supermarkt öffnet um acht Uhr.', 'Ich mag deinen Hund sehr.', 'Ich lerne Italienisch.'],
    'd-c2-01': ['Toll geparkt, hast du deinen Führerschein in der Lostrommel gewonnen?', 'Wenigstens habe ich ein Auto, du kommst mit dem Roller.', 'Es tut mir wirklich leid, das wird nicht wieder vorkommen.', 'Das Auto ist blau.', 'Heute ist es sehr heiß.'],
    'd-c2-02': ['Ich schlage dich in allem, was du willst, such dir was aus.', 'Gut: mal sehen, wer länger ohne aufs Handy zu schauen aushält.', 'Du hast recht, du bist in allem besser.', 'Das Spiel beginnt um acht Uhr.', 'Meine Schwester lebt in Sevilla.'],
    'd-c2-03': ['Funktioniert das Handy noch? Das ist ein Museumsstück.', 'Hey, bei mir heißt das Vintage, nicht alt.', 'Ja, ich sollte gleich morgen ein neues kaufen.', 'Das Museum schließt montags.', 'Ich brauche ein Ladegerät.'],
    'd-c2-04': ['Also, es ist gar nicht schlecht, für deine Verhältnisse.', 'Von jemandem, der sogar Wasser anbrennen lässt, nehme ich das als Kompliment.', 'Danke, ich freue mich, dass es dir gefällt.', 'Das Salz steht auf dem Tisch.', 'Ich habe um neun Uhr zu Abend gegessen.'],
    'd-c2-05': ['Die sozialen Netzwerke haben die öffentliche Debatte zerstört, Punkt.', 'Sie tragen ihren Teil der Schuld, ja, aber früher kontrollierten die Debatte nur ein paar Zeitungen.', 'Völlig einverstanden, dazu gibt es nichts mehr zu sagen.', 'Mein Konto hat tausend Follower.', 'Die Zeitung kommt am Morgen.'],
    'd-c2-06': ['Die jungen Leute von heute wollen nicht arbeiten, so einfach ist das.', 'Oder wollen sie vielleicht nicht für Löhne arbeiten, die nicht einmal die Miete zahlen?', 'Das stimmt, wir sind faul.', 'Ich arbeite in einem Büro.', 'Die Miete wird am Ersten bezahlt.'],
    'd-c2-07': ['Man müsste Autos im ganzen Zentrum verbieten, ohne Ausnahmen.', 'Ohne Ausnahmen nicht: und die Krankenwagen, die Lieferungen, die Menschen mit eingeschränkter Mobilität?', 'Ja, verbieten wir gleich morgen alles.', 'Mein Auto ist rot.', 'Das Zentrum hat viele Geschäfte.'],
    'd-c2-08': ['Sprachen zu lernen ergibt keinen Sinn mehr, die KI übersetzt alles.', 'Sie übersetzt Wörter, ja; aber den Witz, den Ton und das Vertrauen der anderen Person übersetzt dir niemand.', 'Stimmt, ich höre heute noch mit dem Kurs auf.', 'Die App ist kostenlos.', 'Ich lerne dienstags Spanisch.'],
}
