# -*- coding: utf-8 -*-
LANG = 'tr'
WORDS = {
    'a1-hello': ('Merhaba', None),
    'a1-goodbye': ('Hoşça kal', None),
    'a1-please': ('Lütfen', None),
    'a1-thank-you': ('Teşekkür ederim', None),
    'a1-excuse-me': ('Affedersiniz', None),
    'a1-sorry': ('Özür dilerim', None),
    'a1-yes': ('Evet', None),
    'a1-no': ('Hayır', None),
    'a1-my-name-is-alex': ('Benim adım Alex', None),
    'a1-whats-your-name': ('Adın ne?', None),
    'a1-nice-to-meet-you': ('Tanıştığımıza memnun oldum', None),
    'a1-how-are-you': ('Nasılsın?', None),
    'a1-mother': ('Anne', None),
    'a1-father': ('Baba', None),
    'a1-sister': ('Kız kardeş', None),
    'a1-brother': ('Erkek kardeş', None),
    'a1-friend': ('Arkadaş', None),
    'a1-child': ('Çocuk', None),
    'a1-today': ('Bugün', None),
    'a1-tomorrow': ('Yarın', None),
    'a1-yesterday': ('Dün', None),
    'a1-now': ('Şimdi', None),
    'a1-morning': ('Sabah', None),
    'a1-night': ('Gece', None),
    'a1-house': ('Ev', None),
    'a1-where-is-it': ('Nerede?', None),
    'a1-left': ('Sol', None),
    'a1-right': ('Sağ', None),
    'a1-store': ('Mağaza', None),
    'a1-bathroom': ('Tuvalet', None),
    'a1-water': ('Su', None),
    'a1-bread': ('Ekmek', None),
    'a1-coffee': ('Kahve', None),
    'a1-tea': ('Çay', None),
    'a1-delicious': ('Lezzetli', None),
    'a1-spicy': ('Acılı', None),
    'a1-good-morning': ('Günaydın', None),
    'a1-good-evening': ('İyi akşamlar', None),
    'a1-good-night': ('İyi geceler', None),
    'a1-youre-welcome': ('Rica ederim', None),
    'a1-see-you-soon': ('Yakında görüşürüz', None),
    'a1-see-you-tomorrow': ('Yarın görüşürüz', None),
    'a1-welcome': ('Hoş geldiniz', None),
    'a1-cheers': ('Şerefe!', None),
    'a1-congratulations': ('Tebrikler', None),
    'a1-happy-birthday': ('İyi ki doğdun', None),
    'a1-good-luck': ('İyi şanslar', None),
    'a1-have-a-nice-day': ('İyi günler', None),
    'a1-take-care': ('Kendine iyi bak', None),
    'a1-bless-you': ('Çok yaşa', None),
    'a1-enjoy-your-meal': ('Afiyet olsun', None),
    'a1-nice-to-see-you': ('Seni görmek güzel', None),
    'a1-long-time-no-see': ('Uzun zamandır görüşmüyoruz', None),
    'a1-goodbye-for-now': ('Şimdilik hoşça kal', None),
    'a1-i': ('Ben', None),
    'a1-you': ('Sen', None),
    'a1-he': ('O (erkek)', None),
    'a1-she': ('O (kadın)', None),
    'a1-we': ('Biz', None),
    'a1-they': ('Onlar', None),
    'a1-man': ('Adam', None),
    'a1-woman': ('Kadın', None),
    'a1-boy': ('Erkek çocuk', None),
    'a1-girl': ('Kız çocuk', None),
    'a1-person': ('Kişi', None),
    'a1-people': ('İnsanlar', None),
    'a1-name': ('İsim', None),
    'a1-mister': ('Bey', None),
    'a1-madam': ('Hanım', None),
    'a1-im-fine': ('İyiyim', None),
    'a1-and-you': ('Ya sen?', None),
    'a1-where-are-you-from': ('Nerelisin?', None),
    'a1-im-from-the-united-states': ("Amerika Birleşik Devletleri'ndenim", None),
    'a1-friend-female': ('Arkadaş (kadın)', None),
    'a1-family': ('Aile', None),
    'a1-parents': ('Ebeveynler', None),
    'a1-son': ('Oğul', None),
    'a1-daughter': ('Kız evlat', None),
    'a1-husband': ('Koca', None),
    'a1-wife': ('Eş (kadın)', None),
    'a1-grandmother': ('Büyükanne', None),
    'a1-grandfather': ('Büyükbaba', None),
    'a1-baby': ('Bebek', None),
    'a1-uncle': ('Amca', None),
    'a1-aunt': ('Teyze', None),
    'a1-cousin': ('Kuzen', None),
    'a1-boyfriend': ('Erkek arkadaş', None),
    'a1-girlfriend': ('Kız arkadaş', None),
    'a1-neighbor': ('Komşu', None),
    'a1-children': ('Çocuklar', None),
    'a1-older-brother': ('Abi', None),
    'a1-younger-sister': ('Küçük kız kardeş', None),
    'a1-pet': ('Evcil hayvan', None),
    'a1-married': ('Evli', None),
    'a1-one': ('Bir', None),
    'a1-two': ('İki', None),
    'a1-three': ('Üç', None),
    'a1-four': ('Dört', None),
    'a1-five': ('Beş', None),
    'a1-six': ('Altı', None),
    'a1-seven': ('Yedi', None),
    'a1-eight': ('Sekiz', None),
    'a1-nine': ('Dokuz', None),
    'a1-ten': ('On', None),
    'a1-eleven': ('On bir', None),
    'a1-twelve': ('On iki', None),
    'a1-thirteen': ('On üç', None),
    'a1-fourteen': ('On dört', None),
    'a1-fifteen': ('On beş', None),
    'a1-sixteen': ('On altı', None),
    'a1-seventeen': ('On yedi', None),
    'a1-eighteen': ('On sekiz', None),
    'a1-nineteen': ('On dokuz', None),
    'a1-twenty': ('Yirmi', None),
    'a1-zero': ('Sıfır', None),
    'a1-thirty': ('Otuz', None),
    'a1-forty': ('Kırk', None),
    'a1-fifty': ('Elli', None),
    'a1-sixty': ('Altmış', None),
    'a1-seventy': ('Yetmiş', None),
    'a1-eighty': ('Seksen', None),
    'a1-ninety': ('Doksan', None),
    'a1-one-hundred': ('Yüz', None),
    'a1-one-thousand': ('Bin', None),
    'a1-one-million': ('Bir milyon', None),
    'a1-first': ('Birinci', None),
    'a1-second': ('İkinci', None),
    'a1-third': ('Üçüncü', None),
    'a1-half': ('Yarım', None),
    'a1-many': ('Birçok', None),
    'a1-few': ('Az', None),
    'a1-all': ('Hepsi', None),
    'a1-some': ('Bazı', None),
    'a1-nothing': ('Hiçbir şey', None),
    'a1-number': ('Sayı', None),
    'a1-more': ('Daha fazla', None),
    'a1-less': ('Daha az', None),
    'a1-enough': ('Yeterli', None),
    'a1-red': ('Kırmızı', None),
    'a1-blue': ('Mavi', None),
    'a1-green': ('Yeşil', None),
    'a1-yellow': ('Sarı', None),
    'a1-black': ('Siyah', None),
    'a1-white': ('Beyaz', None),
    'a1-orange-color': ('Turuncu', None),
    'a1-pink': ('Pembe', None),
    'a1-purple': ('Mor', None),
    'a1-brown': ('Kahverengi', None),
    'a1-gray': ('Gri', None),
    'a1-color': ('Renk', None),
    'a1-light-color': ('Açık (renk)', None),
    'a1-dark': ('Koyu', None),
    'a1-circle': ('Daire', None),
    'a1-square': ('Kare', None),
    'a1-triangle': ('Üçgen', None),
    'a1-line': ('Çizgi', None),
    'a1-shape': ('Şekil', None),
    'a1-big': ('Büyük', None),
    'a1-small': ('Küçük', None),
    'a1-long': ('Uzun', None),
    'a1-short-length': ('Kısa', None),
    'a1-round': ('Yuvarlak', None),
    'a1-afternoon': ('Öğleden sonra', None),
    'a1-evening': ('Akşam', None),
    'a1-day': ('Gün', None),
    'a1-week': ('Hafta', None),
    'a1-month': ('Ay', None),
    'a1-year': ('Yıl', None),
    'a1-hour': ('Saat', None),
    'a1-minute': ('Dakika', None),
    'a1-later': ('Daha sonra', None),
    'a1-early': ('Erken', None),
    'a1-late': ('Geç', None),
    'a1-always': ('Her zaman', None),
    'a1-never': ('Asla', None),
    'a1-sometimes': ('Bazen', None),
    'a1-often': ('Sık sık', None),
    'a1-soon': ('Yakında', None),
    'a1-again': ('Tekrar', None),
    'a1-its-late': ('Geç oldu', None),
    'a1-tonight': ('Bu gece', None),
    'a1-before': ('Önce', None),
    'a1-after': ('Sonra', None),
    'a1-noon': ('Öğle', None),
    'a1-midnight': ('Gece yarısı', None),
    'a1-monday': ('Pazartesi', None),
    'a1-tuesday': ('Salı', None),
    'a1-wednesday': ('Çarşamba', None),
    'a1-thursday': ('Perşembe', None),
    'a1-friday': ('Cuma', None),
    'a1-saturday': ('Cumartesi', None),
    'a1-sunday': ('Pazar', None),
    'a1-weekend': ('Hafta sonu', None),
    'a1-january': ('Ocak', None),
    'a1-february': ('Şubat', None),
    'a1-march': ('Mart', None),
    'a1-april': ('Nisan', None),
    'a1-may': ('Mayıs', None),
    'a1-june': ('Haziran', None),
    'a1-july': ('Temmuz', None),
    'a1-august': ('Ağustos', None),
    'a1-september': ('Eylül', None),
    'a1-october': ('Ekim', None),
    'a1-november': ('Kasım', None),
    'a1-december': ('Aralık', None),
    'a1-spring': ('İlkbahar', None),
    'a1-summer': ('Yaz', None),
    'a1-autumn': ('Sonbahar', None),
    'a1-winter': ('Kış', None),
    'a1-birthday': ('Doğum günü', None),
    'a1-holiday': ('Tatil günü', None),
    'a1-room': ('Oda', None),
    'a1-kitchen': ('Mutfak', None),
    'a1-bedroom': ('Yatak odası', None),
    'a1-door': ('Kapı', None),
    'a1-window': ('Pencere', None),
    'a1-table': ('Masa', None),
    'a1-chair': ('Sandalye', None),
    'a1-bed': ('Yatak', None),
    'a1-street': ('Sokak', None),
    'a1-city': ('Şehir', None),
    'a1-country': ('Ülke', None),
    'a1-school': ('Okul', None),
    'a1-hospital': ('Hastane', None),
    'a1-bank': ('Banka', None),
    'a1-restaurant': ('Restoran', None),
    'a1-hotel': ('Otel', None),
    'a1-market': ('Pazar yeri', None),
    'a1-park': ('Park', None),
    'a1-church': ('Kilise', None),
    'a1-office': ('Ofis', None),
    'a1-here': ('Burada', None),
    'a1-there': ('Orada', None),
    'a1-straight-ahead': ('Dosdoğru', None),
    'a1-near': ('Yakın', None),
    'a1-far': ('Uzak', None),
    'a1-floor-level': ('Kat', None),
    'a1-garden': ('Bahçe', None),
    'a1-wall': ('Duvar', None),
    'a1-milk': ('Süt', None),
    'a1-rice': ('Pirinç', None),
    'a1-meat': ('Et', None),
    'a1-fish-food': ('Balık (yiyecek)', None),
    'a1-chicken': ('Tavuk', None),
    'a1-egg': ('Yumurta', None),
    'a1-fruit': ('Meyve', None),
    'a1-vegetables': ('Sebze', None),
    'a1-apple': ('Elma', None),
    'a1-sugar': ('Şeker', None),
    'a1-salt': ('Tuz', None),
    'a1-beer': ('Bira', None),
    'a1-wine': ('Şarap', None),
    'a1-juice': ('Meyve suyu', None),
    'a1-breakfast': ('Kahvaltı', None),
    'a1-lunch': ('Öğle yemeği', None),
    'a1-dinner': ('Akşam yemeği', None),
    'a1-im-hungry': ('Açım', None),
    'a1-im-thirsty': ('Susadım', None),
    'a1-cheese': ('Peynir', None),
    'a1-soup': ('Çorba', None),
    'a1-sweet': ('Tatlı', None),
    'a1-food': ('Yiyecek', None),
    'a1-drink-noun': ('İçecek', None),
    'a1-head': ('Baş', None),
    'a1-hand': ('El', None),
    'a1-eye': ('Göz', None),
    'a1-foot': ('Ayak', None),
    'a1-mouth': ('Ağız', None),
    'a1-nose': ('Burun', None),
    'a1-ear': ('Kulak', None),
    'a1-arm': ('Kol', None),
    'a1-leg': ('Bacak', None),
    'a1-heart': ('Kalp', None),
    'a1-hair': ('Saç', None),
    'a1-face': ('Yüz', None),
    'a1-back-body': ('Sırt', None),
    'a1-stomach': ('Mide', None),
    'a1-tooth': ('Diş', None),
    'a1-finger': ('Parmak', None),
    'a1-body': ('Vücut', None),
    'a1-blood': ('Kan', None),
    'a1-neck': ('Boyun', None),
    'a1-shoulder': ('Omuz', None),
    'a1-knee': ('Diz', None),
    'a1-skin': ('Deri', None),
    'a1-shirt': ('Gömlek', None),
    'a1-pants': ('Pantolon', None),
    'a1-shoes': ('Ayakkabı', None),
    'a1-dress': ('Elbise', None),
    'a1-hat': ('Şapka', None),
    'a1-coat': ('Palto', None),
    'a1-jacket': ('Ceket', None),
    'a1-socks': ('Çorap', None),
    'a1-skirt': ('Etek', None),
    'a1-bag': ('Çanta', None),
    'a1-glasses': ('Gözlük', None),
    'a1-watch-wrist': ('Kol saati', None),
    'a1-umbrella': ('Şemsiye', None),
    'a1-to-wear': ('Giymek', None),
    'a1-sweater': ('Kazak', None),
    'a1-t-shirt': ('Tişört', None),
    'a1-scarf': ('Atkı', None),
    'a1-gloves': ('Eldiven', None),
    'a1-clothes': ('Kıyafet', None),
    'a1-size': ('Beden', None),
    'a1-to-be': ('Olmak', None),
    'a1-to-have': ('Sahip olmak', None),
    'a1-to-do': ('Yapmak', None),
    'a1-to-go': ('Gitmek', None),
    'a1-to-come': ('Gelmek', None),
    'a1-to-want': ('İstemek', None),
    'a1-to-be-able-to': ('Yapabilmek', None),
    'a1-to-know': ('Bilmek', None),
    'a1-to-see': ('Görmek', None),
    'a1-to-say': ('Söylemek', None),
    'a1-to-eat': ('Yemek', None),
    'a1-to-drink': ('İçmek', None),
    'a1-to-sleep': ('Uyumak', None),
    'a1-to-live': ('Yaşamak', None),
    'a1-to-work': ('Çalışmak', None),
    'a1-to-speak': ('Konuşmak', None),
    'a1-to-understand': ('Anlamak', None),
    'a1-to-like': ('Hoşlanmak', None),
    'a1-to-need': ('İhtiyaç duymak', None),
    'a1-to-give': ('Vermek', None),
    'a1-to-take': ('Almak', None),
    'a1-to-think': ('Düşünmek', None),
    'a1-to-buy': ('Satın almak', None),
    'a1-to-help': ('Yardım etmek', None),
    'a1-to-open': ('Açmak', None),
    'a1-to-close': ('Kapatmak', None),
    'a1-to-look-for': ('Aramak', None),
    'a1-to-find': ('Bulmak', None),
    'a1-to-wait': ('Beklemek', None),
    'a1-to-call-phone': ('Aramak (telefonla)', None),
    'a1-to-read': ('Okumak', None),
    'a1-to-write': ('Yazmak', None),
    'a1-to-listen': ('Dinlemek', None),
    'a1-to-learn': ('Öğrenmek', None),
    'a1-to-play': ('Oynamak', None),
    'a1-to-walk': ('Yürümek', None),
    'a1-to-run': ('Koşmak', None),
    'a1-to-sit': ('Oturmak', None),
    'a1-to-stand': ('Ayakta durmak', None),
    'a1-to-arrive': ('Varmak', None),
    'a1-to-leave': ('Ayrılmak', None),
    'a1-to-return': ('Geri dönmek', None),
    'a1-to-put': ('Koymak', None),
    'a1-to-bring': ('Getirmek', None),
    'a1-to-ask': ('Sormak', None),
    'a1-to-answer': ('Cevap vermek', None),
    'a1-to-love': ('Sevmek', None),
    'a1-to-pay': ('Ödemek', None),
    'a1-good': ('İyi', None),
    'a1-bad': ('Kötü', None),
    'a1-new': ('Yeni', None),
    'a1-old-thing': ('Eski', None),
    'a1-young': ('Genç', None),
    'a1-hot': ('Sıcak', None),
    'a1-cold': ('Soğuk', None),
    'a1-happy': ('Mutlu', None),
    'a1-sad': ('Üzgün', None),
    'a1-beautiful': ('Güzel', None),
    'a1-ugly': ('Çirkin', None),
    'a1-easy': ('Kolay', None),
    'a1-difficult': ('Zor', None),
    'a1-fast': ('Hızlı', None),
    'a1-slow': ('Yavaş', None),
    'a1-cheap': ('Ucuz', None),
    'a1-expensive': ('Pahalı', None),
    'a1-full': ('Dolu', None),
    'a1-empty': ('Boş', None),
    'a1-clean': ('Temiz', None),
    'a1-dirty': ('Kirli', None),
    'a1-strong': ('Güçlü', None),
    'a1-weak': ('Zayıf', None),
    'a1-important': ('Önemli', None),
    'a1-what': ('Ne', None),
    'a1-who': ('Kim', None),
    'a1-where': ('Nerede', None),
    'a1-when': ('Ne zaman', None),
    'a1-why': ('Neden', None),
    'a1-how': ('Nasıl', None),
    'a1-how-many': ('Kaç tane', None),
    'a1-which': ('Hangi', None),
    'a1-and': ('Ve', None),
    'a1-or': ('Veya', None),
    'a1-but': ('Ama', None),
    'a1-because': ('Çünkü', None),
    'a1-with': ('İle', None),
    'a1-without': ('Olmadan', None),
    'a1-for': ('İçin', None),
    'a1-from': ('-den', None),
    'a1-to-direction': ('-e', None),
    'a1-in': ('İçinde', None),
    'a1-on': ('Üzerinde', None),
    'a1-under': ('Altında', None),
    'a1-this': ('Bu', None),
    'a1-that': ('Şu', None),
    'a1-very': ('Çok', None),
    'a1-also': ('Ayrıca', None),
    'a1-not': ('Değil', None),
    'a1-maybe': ('Belki', None),
    'a1-sun': ('Güneş', None),
    'a1-rain': ('Yağmur', None),
    'a1-snow': ('Kar', None),
    'a1-wind': ('Rüzgar', None),
    'a1-cloud': ('Bulut', None),
    'a1-weather': ('Hava durumu', None),
    'a1-sky': ('Gökyüzü', None),
    'a1-sea': ('Deniz', None),
    'a1-mountain': ('Dağ', None),
    'a1-river': ('Nehir', None),
    'a1-tree': ('Ağaç', None),
    'a1-flower': ('Çiçek', None),
    'a1-dog': ('Köpek', None),
    'a1-cat': ('Kedi', None),
    'a1-bird': ('Kuş', None),
    'a1-fish-animal': ('Balık (hayvan)', None),
    'a1-horse': ('At', None),
    'a1-cow': ('İnek', None),
    'a1-earth': ('Dünya', None),
    'a1-moon': ('Ay', None),
    'a1-star': ('Yıldız', None),
    'a1-fire': ('Ateş', None),
    'a1-its-windy': ('Rüzgarlı', None),
    'a1-its-snowing': ('Kar yağıyor', None),
    'a1-its-cold-today': ('Bugün hava soğuk', None),
    'a1-its-hot-today': ('Bugün hava sıcak', None),
    'a1-help': ('İmdat!', None),
    'a1-slowly-please': ('Yavaşça, lütfen', None),
    'a1-do-you-speak-english': ('İngilizce biliyor musun?', None),
    'a1-i-dont-know': ('Bilmiyorum', None),
    'a1-where-is-the-bathroom': ('Tuvalet nerede?', None),
    'a1-which-way': ('Hangi yöne?', None),
    'a1-one-moment-please': ('Bir dakika, lütfen', None),
    'a1-of-course': ('Tabii ki', None),
    'a1-no-problem': ('Sorun değil', None),
    'a1-its-okay': ('Sorun yok', None),
    'a1-lets-go': ('Hadi gidelim', None),
    'a1-come-in': ('Buyurun', None),
    'a1-be-careful': ('Dikkatli ol', None),
    'a1-can-you-help-me': ('Bana yardım edebilir misin?', None),
    'a1-what-does-that-mean': ('Bu ne demek?', None),
    'a1-can-you-repeat-that': ('Tekrar edebilir misin?', None),
    'a1-slower-please': ('Daha yavaş, lütfen', None),
    'a1-how-do-you-say': ('...nasıl söylenir?', None),
    'a1-i-would-like': ('...istiyorum', None),
    'a1-the-bill-please': ('Hesap, lütfen', None),
    'a1-im-tired': ('Yorgunum', None),
    'a1-im-sick': ('Hastayım', None),
    'a1-its-an-emergency': ('Bu bir acil durum', None),
    'a1-call-the-police': ('Polisi arayın', None),
    'a1-i-speak-a-little': ('Biraz konuşuyorum', None),
    'a1-i-love-it': ('Bayıldım', None),
    'a1-whats-this': ('Bu nedir?', None),
    'a1-i-agree': ('Katılıyorum', None),
    'a1-i-dont-like-it': ('Bunu beğenmedim', None),
    'a1-really': ('Gerçekten mi?', None),
    'a1-exactly': ('Kesinlikle', None),
    'a1-i-think-so': ('Sanırım öyle', None),
    'a1-dont-worry': ('Merak etme', None),
    'a1-just-a-little': ('Sadece biraz', None),
    'a1-wait-a-moment': ('Bir dakika bekle', None),
    'a1-is-this-seat-free': ('Bu koltuk boş mu?', None),
    'a1-money': ('Para', None),
    'a1-price': ('Fiyat', None),
    'a1-to-sell': ('Satmak', None),
    'a1-card': ('Kart', None),
    'a1-cash': ('Nakit', None),
    'a1-receipt': ('Fiş', None),
    'a1-open-shop': ('Açık', None),
    'a1-closed-shop': ('Kapalı', None),
    'a1-free-no-cost': ('Ücretsiz', None),
    'a1-discount': ('İndirim', None),
    'a1-how-much-is-it': ('Bu ne kadar?', None),
    'a1-too-much': ('Çok fazla', None),
    'a1-gift': ('Hediye', None),
    'a1-change-coins': ('Bozuk para', None),
    'a1-supermarket': ('Süpermarket', None),
    'a1-pharmacy': ('Eczane', None),
    'a1-bakery': ('Fırın', None),
    'a1-is-this-on-sale': ('Bu indirimde mi?', None),
    'a1-car': ('Araba', None),
    'a1-bus': ('Otobüs', None),
    'a1-train': ('Tren', None),
    'a1-plane': ('Uçak', None),
    'a1-bicycle': ('Bisiklet', None),
    'a1-taxi': ('Taksi', None),
    'a1-ticket': ('Bilet', None),
    'a1-station': ('İstasyon', None),
    'a1-airport': ('Havalimanı', None),
    'a1-road': ('Yol', None),
    'a1-to-travel': ('Seyahat etmek', None),
    'a1-trip': ('Gezi', None),
    'a1-map': ('Harita', None),
    'a1-stop-bus-stop': ('Durak', None),
    'a1-to-drive': ('Araba kullanmak', None),
    'a1-subway': ('Metro', None),
    'a1-passport': ('Pasaport', None),
    'a1-suitcase': ('Bavul', None),
    'a1-exit': ('Çıkış', None),
    'a1-entrance': ('Giriş', None),
    'a1-phone': ('Telefon', None),
    'a1-book': ('Kitap', None),
    'a1-pen': ('Kalem', None),
    'a1-paper': ('Kağıt', None),
    'a1-key': ('Anahtar', None),
    'a1-computer': ('Bilgisayar', None),
    'a1-clock': ('Duvar saati', None),
    'a1-television': ('Televizyon', None),
    'a1-camera': ('Kamera', None),
    'a1-box': ('Kutu', None),
    'a1-glass-cup': ('Bardak', None),
    'a1-bottle': ('Şişe', None),
    'a1-plate': ('Tabak', None),
    'a1-knife': ('Bıçak', None),
    'a1-fork': ('Çatal', None),
    'a1-spoon': ('Kaşık', None),
    'a1-cup': ('Fincan', None),
    'a1-soap': ('Sabun', None),
    'a1-towel': ('Havlu', None),
    'a1-lamp': ('Lamba', None),
    'a1-wallet': ('Cüzdan', None),
    'a1-charger': ('Şarj aleti', None),
    'a1-thing': ('Şey', None),
    'a1-toothbrush': ('Diş fırçası', None),
    'a1-angry': ('Kızgın', None),
    'a1-scared': ('Korkmuş', None),
    'a1-bored': ('Sıkılmış', None),
    'a1-excited': ('Heyecanlı', None),
    'a1-worried': ('Endişeli', None),
    'a1-surprised': ('Şaşırmış', None),
    'a1-calm': ('Sakin', None),
    'a1-nervous': ('Gergin', None),
    'a1-proud': ('Gururlu', None),
    'a1-lonely': ('Yalnız', None),
    'a1-sleepy': ('Uykulu', None),
    'a1-sick-unwell': ('Hasta', None),
    'a1-love': ('Aşk', None),
    'a1-fear': ('Korku', None),
    'a1-joy': ('Neşe', None),
    'a1-funny': ('Komik', None),
    'a2-i-work-in-an-office': ('Bir ofiste çalışıyorum', None),
    'a2-i-am-a-student': ('Ben öğrenciyim', None),
    'a2-i-have-a-meeting': ('Bir toplantım var', None),
    'a2-i-am-looking-for-a-job': ('İş arıyorum', None),
    'a2-i-am-studying': ('Ders çalışıyorum', None),
    'a2-i-dont-understand': ('Anlamıyorum', None),
    'a2-how-much-is-this': ('Bu ne kadar?', None),
    'a2-its-too-expensive': ('Çok pahalı', None),
    'a2-can-i-pay-by-card': ('Kartla ödeyebilir miyim?', None),
    'a2-do-you-have-a-discount': ('İndiriminiz var mı?', None),
    'a2-im-just-looking': ('Sadece bakıyorum', None),
    'a2-ill-take-it': ('Bunu alıyorum', None),
    'a2-where-is-the-train-station': ('Tren istasyonu nerede?', None),
    'a2-one-ticket-please': ('Bir bilet, lütfen', None),
    'a2-how-do-i-get-to-the-airport': ('Havalimanına nasıl giderim?', None),
    'a2-im-lost': ('Kayboldum', None),
    'a2-is-it-far': ('Uzak mı?', None),
    'a2-where-is-the-restroom': ('Tuvalet nerede?', None),
    'a2-i-dont-feel-well': ('Kendimi iyi hissetmiyorum', None),
    'a2-i-have-a-headache': ('Başım ağrıyor', None),
    'a2-where-is-the-pharmacy': ('Eczane nerede?', None),
    'a2-i-need-a-doctor': ('Bir doktora ihtiyacım var', None),
    'a2-im-allergic-to-peanuts': ('Fıstığa alerjim var', None),
    'a2-it-hurts-here': ('Burası ağrıyor', None),
    'a2-its-sunny': ('Hava güneşli', None),
    'a2-its-raining': ('Yağmur yağıyor', None),
    'a2-i-like-to-read': ('Okumayı severim', None),
    'a2-my-favorite-is-music': ('En sevdiğim şey müzik', None),
    'a2-on-weekends-i-rest': ('Hafta sonları dinlenirim', None),
    'a2-i-play-sports': ('Spor yaparım', None),
    'a2-what-time-is-it': ('Saat kaç?', None),
    'a2-lets-meet-tomorrow': ('Yarın buluşalım', None),
    'a2-can-you-call-me': ('Beni arayabilir misin?', None),
    'a2-see-you-later': ('Sonra görüşürüz', None),
    'a2-whats-your-phone-number': ('Telefon numaran ne?', None),
    'a2-im-busy-today': ('Bugün meşgulüm', None),
    'a2-job': ('İş', None),
    'a2-boss': ('Patron', None),
    'a2-colleague': ('Meslektaş', None),
    'a2-salary': ('Maaş', None),
    'a2-to-earn': ('Kazanmak', None),
    'a2-class': ('Sınıf', None),
    'a2-teacher': ('Öğretmen', None),
    'a2-exam': ('Sınav', None),
    'a2-homework': ('Ev ödevi', None),
    'a2-university': ('Üniversite', None),
    'a2-to-teach': ('Öğretmek', None),
    'a2-project': ('Proje', None),
    'a2-deadline': ('Son teslim tarihi', None),
    'a2-interview': ('Mülakat', None),
    'a2-career': ('Kariyer', None),
    'a2-break-pause': ('Mola', None),
    'a2-schedule': ('Program', None),
    'a2-company': ('Şirket', None),
    'a2-customer': ('Müşteri', None),
    'a2-unemployed': ('İşsiz', None),
    'a2-to-try-on': ('Prova etmek', None),
    'a2-fitting-room': ('Deneme kabini', None),
    'a2-sale-discount-event': ('İndirim dönemi', None),
    'a2-to-return-an-item': ('İade etmek', None),
    'a2-refund': ('Geri ödeme', None),
    'a2-brand': ('Marka', None),
    'a2-quality': ('Kalite', None),
    'a2-cashier': ('Kasiyer', None),
    'a2-shopping-cart': ('Alışveriş arabası', None),
    'a2-online-shopping': ('Online alışveriş', None),
    'a2-to-order-online': ('Sipariş vermek', None),
    'a2-delivery': ('Teslimat', None),
    'a2-package': ('Paket', None),
    'a2-to-choose': ('Seçmek', None),
    'a2-to-compare': ('Karşılaştırmak', None),
    'a2-it-fits-me': ('Bana uyuyor', None),
    'a2-too-big': ('Çok büyük', None),
    'a2-do-you-have-it-in-another-color': ('Başka renkte var mı?', None),
    'a2-mall': ('Alışveriş merkezi', None),
    'a2-cheaper': ('Daha ucuz', None),
    'a2-reservation': ('Rezervasyon', None),
    'a2-to-book': ('Rezervasyon yapmak', None),
    'a2-check-in': ('Giriş işlemi', None),
    'a2-luggage': ('Bagaj', None),
    'a2-flight': ('Uçuş', None),
    'a2-delay': ('Gecikme', None),
    'a2-departure': ('Kalkış', None),
    'a2-arrival': ('Varış', None),
    'a2-gate': ('Kapı (biniş)', None),
    'a2-seat': ('Koltuk', None),
    'a2-tourist': ('Turist', None),
    'a2-guide': ('Rehber', None),
    'a2-sightseeing': ('Gezi (turistik)', None),
    'a2-souvenir': ('Hediyelik eşya', None),
    'a2-beach': ('Plaj', None),
    'a2-museum': ('Müze', None),
    'a2-to-visit': ('Ziyaret etmek', None),
    'a2-round-trip': ('Gidiş-dönüş', None),
    'a2-one-way': ('Tek yön', None),
    'a2-abroad': ('Yurt dışında', None),
    'a2-doctor': ('Doktor', None),
    'a2-nurse': ('Hemşire', None),
    'a2-medicine': ('İlaç', None),
    'a2-pain': ('Ağrı', None),
    'a2-fever': ('Ateş (yüksek ateş)', None),
    'a2-cough': ('Öksürük', None),
    'a2-a-cold-illness': ('Soğuk algınlığı', None),
    'a2-flu': ('Grip', None),
    'a2-allergy': ('Alerji', None),
    'a2-appointment': ('Randevu', None),
    'a2-prescription': ('Reçete', None),
    'a2-stomachache': ('Karın ağrısı', None),
    'a2-healthy': ('Sağlıklı', None),
    'a2-to-rest': ('Dinlenmek', None),
    'a2-insurance': ('Sigorta', None),
    'a2-emergency': ('Acil durum', None),
    'a2-dentist': ('Diş hekimi', None),
    'a2-injury': ('Yaralanma', None),
    'a2-i-feel-better': ('Kendimi daha iyi hissediyorum', None),
    'a2-blood-pressure': ('Tansiyon', None),
    'a2-hobby': ('Hobi', None),
    'a2-music': ('Müzik', None),
    'a2-movie': ('Film', None),
    'a2-sport': ('Spor', None),
    'a2-soccer': ('Futbol', None),
    'a2-to-swim': ('Yüzmek', None),
    'a2-to-dance': ('Dans etmek', None),
    'a2-to-sing': ('Şarkı söylemek', None),
    'a2-to-paint': ('Resim yapmak', None),
    'a2-game': ('Oyun', None),
    'a2-team': ('Takım', None),
    'a2-to-win': ('Kazanmak (oyun)', None),
    'a2-to-lose-a-game': ('Kaybetmek', None),
    'a2-concert': ('Konser', None),
    'a2-photography': ('Fotoğrafçılık', None),
    'a2-to-hike': ('Doğa yürüyüşü yapmak', None),
    'a2-gym': ('Spor salonu', None),
    'a2-to-exercise': ('Egzersiz yapmak', None),
    'a2-cloudy': ('Bulutlu', None),
    'a2-storm': ('Fırtına', None),
    'a2-humid': ('Nemli', None),
    'a2-forecast': ('Hava tahmini', None),
    'a2-to-plan': ('Planlamak', None),
    'a2-to-meet-up': ('Buluşmak', None),
    'a2-invitation': ('Davet', None),
    'a2-to-invite': ('Davet etmek', None),
    'a2-to-cancel': ('İptal etmek', None),
    'a2-free-time': ('Boş zaman', None),
    'a2-to-postpone': ('Ertelemek', None),
    'a2-internet': ('İnternet', None),
    'a2-email': ('E-posta', None),
    'a2-message': ('Mesaj', None),
    'a2-to-send': ('Göndermek', None),
    'a2-to-download': ('İndirmek', None),
    'a2-app': ('Uygulama', None),
    'a2-password': ('Şifre', None),
    'a2-screen': ('Ekran', None),
    'a2-wi-fi': ('Wi-Fi', None),
    'a2-website': ('Web sitesi', None),
    'a2-video-call': ('Görüntülü arama', None),
    'a2-are-you-free-on-saturday': ('Cumartesi müsait misin?', None),
    'a2-sounds-good': ('Kulağa hoş geliyor', None),
    'a2-to-clean': ('Temizlemek', None),
    'a2-to-wash': ('Yıkamak', None),
    'a2-dishes': ('Bulaşık', None),
    'a2-laundry': ('Kirli çamaşır', None),
    'a2-to-iron': ('Ütülemek', None),
    'a2-trash': ('Çöp', None),
    'a2-to-tidy-up': ('Toplamak', None),
    'a2-vacuum-cleaner': ('Elektrikli süpürge', None),
    'a2-to-repair': ('Onarmak', None),
    'a2-to-move-house': ('Taşınmak', None),
    'a2-rent': ('Kira', None),
    'a2-landlord': ('Ev sahibi', None),
    'a2-apartment': ('Daire', None),
    'a2-furniture': ('Mobilya', None),
    'a2-sofa': ('Kanepe', None),
    'a2-fridge': ('Buzdolabı', None),
    'a2-oven': ('Fırın (mutfak aleti)', None),
    'a2-stove': ('Ocak', None),
    'a2-shower': ('Duş', None),
    'a2-mirror': ('Ayna', None),
    'a2-pillow': ('Yastık', None),
    'a2-blanket': ('Battaniye', None),
    'a2-washing-machine': ('Çamaşır makinesi', None),
    'a2-roommate': ('Ev arkadaşı', None),
    'a2-stairs': ('Merdiven', None),
    'a2-elevator': ('Asansör', None),
    'a2-to-wake-up': ('Uyanmak', None),
    'a2-to-get-up': ('Kalkmak', None),
    'a2-to-take-a-shower': ('Duş almak', None),
    "a2-to-brush-ones-teeth": ('Dişlerini fırçalamak', None),
    'a2-to-get-dressed': ('Giyinmek', None),
    'a2-to-have-breakfast': ('Kahvaltı yapmak', None),
    'a2-to-commute': ('İşe gidip gelmek', None),
    'a2-to-go-home': ('Eve gitmek', None),
    'a2-to-relax': ('Rahatlamak', None),
    'a2-to-watch-tv': ('Televizyon izlemek', None),
    'a2-to-go-to-bed': ('Yatağa gitmek', None),
    'a2-routine': ('Rutin', None),
    'a2-habit': ('Alışkanlık', None),
    'a2-alarm-clock': ('Çalar saat', None),
    'a2-to-be-late': ('Geç kalmak', None),
    'a2-to-hurry': ('Acele etmek', None),
    'a2-on-time': ('Zamanında', None),
    'a2-nap': ('Kısa uyku', None),
    'a2-to-take-a-walk': ('Yürüyüşe çıkmak', None),
    'a2-to-have-lunch': ('Öğle yemeği yemek', None),
    'a2-to-have-dinner': ('Akşam yemeği yemek', None),
    'a2-to-fall-asleep': ('Uykuya dalmak', None),
    'a2-every-day': ('Her gün', None),
    'a2-usually': ('Genellikle', None),
    'a2-corner': ('Köşe', None),
    'a2-block': ('Blok', None),
    'a2-traffic-light': ('Trafik ışığı', None),
    'a2-bridge': ('Köprü', None),
    'a2-square-plaza': ('Meydan', None),
    'a2-downtown': ('Şehir merkezi', None),
    'a2-neighborhood': ('Mahalle', None),
    'a2-building': ('Bina', None),
    'a2-sidewalk': ('Kaldırım', None),
    'a2-to-cross': ('Karşıya geçmek', None),
    'a2-to-turn': ('Dönmek', None),
    'a2-address': ('Adres', None),
    'a2-post-office': ('Postane', None),
    'a2-library': ('Kütüphane', None),
    'a2-cinema': ('Sinema', None),
    'a2-theater': ('Tiyatro', None),
    'a2-stadium': ('Stadyum', None),
    'a2-police-station': ('Karakol', None),
    'a2-town-hall': ('Belediye binası', None),
    'a2-parking-lot': ('Otopark', None),
    'a2-gas-station': ('Benzin istasyonu', None),
    'a2-traffic': ('Trafik', None),
    'a2-opposite': ('Karşısında', None),
    'a2-next-to': ('Yanında', None),
    'a2-between': ('Arasında', None),
    'a2-how-do-i-get-to': ("...'a nasıl giderim?", None),
    'a2-menu': ('Menü', None),
    'a2-waiter': ('Garson', None),
    'a2-dish': ('Yemek (tabak)', None),
    'a2-dessert': ('Tatlı (yemek)', None),
    'a2-starter': ('Başlangıç (yemek)', None),
    'a2-main-course': ('Ana yemek', None),
    'a2-vegetarian': ('Vejetaryen', None),
    'a2-tip': ('Bahşiş', None),
    'a2-to-cook': ('Yemek yapmak', None),
    'a2-recipe': ('Tarif', None),
    'a2-ingredient': ('Malzeme', None),
    'a2-oil': ('Yağ', None),
    'a2-butter': ('Tereyağı', None),
    'a2-pepper': ('Karabiber', None),
    'a2-onion': ('Soğan', None),
    'a2-garlic': ('Sarımsak', None),
    'a2-tomato': ('Domates', None),
    'a2-potato': ('Patates', None),
    'a2-noodles': ('Erişte', None),
    'a2-sauce': ('Sos', None),
    'a2-to-bake': ('Fırında pişirmek', None),
    'a2-to-fry': ('Kızartmak', None),
    'a2-to-boil': ('Kaynatmak', None),
    'a2-a-table-for-two': ('İki kişilik bir masa', None),
    'a2-takeout': ('Paket servis', None),
    'a2-snack': ('Atıştırmalık', None),
    'a2-salty': ('Tuzlu', None),
    'a2-bitter': ('Acı (tat)', None),
    'a2-tall': ('Uzun boylu', None),
    'a2-short-height': ('Kısa boylu', None),
    'a2-thin': ('İnce', None),
    'a2-overweight': ('Kilolu', None),
    'a2-blond': ('Sarışın', None),
    'a2-dark-haired': ('Esmer', None),
    'a2-beard': ('Sakal', None),
    'a2-kind': ('Nazik', None),
    'a2-nice-person': ('Cana yakın', None),
    'a2-shy': ('Utangaç', None),
    'a2-talkative': ('Konuşkan', None),
    'a2-smart': ('Zeki', None),
    'a2-lazy': ('Tembel', None),
    'a2-hardworking': ('Çalışkan', None),
    'a2-polite': ('Kibar', None),
    'a2-rude': ('Kaba', None),
    'a2-patient': ('Sabırlı', None),
    'a2-honest': ('Dürüst', None),
    'a2-serious': ('Ciddi', None),
    'a2-quiet-person': ('Sessiz', None),
    'a2-friendly': ('Arkadaş canlısı', None),
    'a2-handsome': ('Yakışıklı', None),
    'a2-age': ('Yaş', None),
    'a2-old-person': ('Yaşlı', None),
    'a2-curly-hair': ('Kıvırcık saç', None),
    'a2-cheerful': ('Neşeli', None),
    'a2-stubborn': ('İnatçı', None),
    'a2-generous': ('Cömert', None),
    'a2-to-try': ('Denemek', None),
    'a2-to-start': ('Başlamak', None),
    'a2-to-finish': ('Bitirmek', None),
    'a2-to-change': ('Değiştirmek', None),
    'a2-to-use': ('Kullanmak', None),
    'a2-to-receive': ('Almak (teslim almak)', None),
    'a2-to-decide': ('Karar vermek', None),
    'a2-to-forget': ('Unutmak', None),
    'a2-to-remember': ('Hatırlamak', None),
    'a2-to-lose-an-object': ('Kaybetmek (eşya)', None),
    'a2-to-meet-someone-new': ('Tanışmak', None),
    'a2-to-prefer': ('Tercih etmek', None),
    'a2-to-hope': ('Ummak', None),
    'a2-to-believe': ('İnanmak', None),
    'a2-to-feel': ('Hissetmek', None),
    'a2-to-seem': ('Görünmek', None),
    'a2-to-happen': ('Gerçekleşmek', None),
    'a2-to-stay': ('Kalmak', None),
    'a2-to-spend-money': ('Harcamak', None),
    'a2-to-show': ('Göstermek', None),
    'a2-to-explain': ('Açıklamak', None),
    'a2-to-follow': ('Takip etmek', None),
    'a2-to-keep': ('Saklamak', None),
    'a2-to-allow': ('İzin vermek', None),
    'a2-to-become': ('Haline gelmek', None),
    'a2-to-continue': ('Devam etmek', None),
    'a2-to-cut': ('Kesmek', None),
    'a2-to-break': ('Kırmak', None),
    'a2-to-fly': ('Uçmak', None),
    'a2-to-draw': ('Çizmek', None),
    'a2-to-carry': ('Taşımak', None),
    'a2-to-push': ('İtmek', None),
    'a2-to-pull': ('Çekmek', None),
    'a2-to-throw': ('Atmak', None),
    'a2-to-catch': ('Yakalamak', None),
    'a2-to-build': ('İnşa etmek', None),
    'a2-to-grow': ('Büyümek', None),
    'a2-to-fall': ('Düşmek', None),
    'a2-to-climb': ('Tırmanmak', None),
    'a2-to-jump': ('Zıplamak', None),
    'a2-to-laugh': ('Gülmek', None),
    'a2-to-cry': ('Ağlamak', None),
    'a2-to-smile': ('Gülümsemek', None),
    'a2-to-shout': ('Bağırmak', None),
    'a2-to-whisper': ('Fısıldamak', None),
    'a2-to-hug': ('Sarılmak', None),
    'a2-to-kiss': ('Öpmek', None),
    'a2-to-touch': ('Dokunmak', None),
    'a2-to-smell': ('Koklamak', None),
    'a2-to-taste': ('Tatmak', None),
    'a2-to-wash-oneself': ('Yıkanmak', None),
    'a2-to-hide': ('Saklanmak', None),
    'a2-interesting': ('İlginç', None),
    'a2-boring': ('Sıkıcı', None),
    'a2-comfortable': ('Rahat', None),
    'a2-dangerous': ('Tehlikeli', None),
    'a2-safe': ('Güvenli', None),
    'a2-noisy': ('Gürültülü', None),
    'a2-busy': ('Meşgul', None),
    'a2-heavy': ('Ağır', None),
    'a2-light-weight': ('Hafif', None),
    'a2-wide': ('Geniş', None),
    'a2-narrow': ('Dar', None),
    'a2-soft': ('Yumuşak', None),
    'a2-hard-firm': ('Sert', None),
    'a2-wet': ('Islak', None),
    'a2-dry': ('Kuru', None),
    'a2-rich': ('Zengin', None),
    'a2-poor': ('Fakir', None),
    'a2-famous': ('Ünlü', None),
    'a2-popular': ('Popüler', None),
    'a2-modern': ('Modern', None),
    'a2-traditional': ('Geleneksel', None),
    'a2-ready': ('Hazır', None),
    'a2-sure': ('Emin', None),
    'a2-wrong': ('Yanlış', None),
    'a2-correct': ('Doğru', None),
    'a2-strange': ('Garip', None),
    'a2-same': ('Aynı', None),
    'a2-different': ('Farklı', None),
    'a2-last-week': ('Geçen hafta', None),
    'a2-next-week': ('Gelecek hafta', None),
    'a2-this-month': ('Bu ay', None),
    'a2-last-year': ('Geçen yıl', None),
    'a2-next-year': ('Gelecek yıl', None),
    'a2-at-the-end': ('Sonunda', None),
    'a2-at-the-beginning': ('Başlangıçta', None),
    'a2-twice': ('İki kez', None),
    'a2-once': ('Bir kez', None),
    'a2-in-a-hurry': ('Acele ile', None),
    'a2-for-a-long-time': ('Uzun süre', None),
    'a2-recently': ('Son zamanlarda', None),
    'a2-already': ('Zaten', None),
    'a2-still': ('Hâlâ', None),
    'a2-not-yet': ('Henüz değil', None),
    'a2-until': ('Kadar', None),
    'a2-since': ('-den beri', None),
    'a2-during': ('Sırasında', None),
    'a2-ago': ('Önce (zaman)', None),
    'a2-at-least': ('En azından', None),
    'a2-right-away': ('Hemen', None),
    'a2-finally': ('Nihayet', None),
    'a2-suddenly': ('Aniden', None),
    'a2-the-day-after-tomorrow': ('Öbür gün', None),
    'a2-conversation': ('Sohbet', None),
    'a2-question': ('Soru', None),
    'a2-answer-noun': ('Cevap', None),
    'a2-opinion': ('Görüş', None),
    'a2-to-describe': ('Tanımlamak', None),
    'a2-to-promise': ('Söz vermek', None),
    'a2-to-suggest': ('Önermek', None),
    'a2-to-complain': ('Şikayet etmek', None),
    'a2-to-apologize': ('Özür dilemek', None),
    'a2-to-thank': ('Teşekkür etmek', None),
    'a2-joke': ('Şaka', None),
    'a2-story': ('Hikaye', None),
    'a2-news': ('Haberler', None),
    'a2-to-argue': ('Kavga etmek', None),
    'a2-to-discuss': ('Tartışmak', None),
    'a2-secret': ('Sır', None),
    'a2-to-mean': ('Anlamına gelmek', None),
    'a2-to-pronounce': ('Telaffuz etmek', None),
    'a2-to-translate': ('Tercüme etmek', None),
    'a2-word': ('Kelime', None),
    'a2-sentence': ('Cümle', None),
    'a2-language': ('Dil', None),
    'a2-to-spell': ('Hecelemek', None),
    'a2-to-lie': ('Yalan söylemek', None),
    'a2-truth': ('Gerçek', None),
    'a2-to-chat': ('Sohbet etmek', None),
    'a2-accent': ('Aksan', None),
    'a2-fluent': ('Akıcı', None),
    'a2-to-get-married': ('Evlenmek', None),
    'a2-wedding': ('Düğün', None),
    'a2-couple': ('Çift', None),
    'a2-childhood': ('Çocukluk', None),
    'a2-teenager': ('Ergen', None),
    'a2-adult': ('Yetişkin', None),
    'a2-to-grow-up': ('Yetişkin olmak', None),
    'a2-anniversary': ('Yıl dönümü', None),
    'a2-party': ('Parti', None),
    'a2-guest': ('Misafir', None),
    'a2-to-celebrate': ('Kutlamak', None),
    'a2-to-be-born': ('Doğmak', None),
    'a2-to-die': ('Ölmek', None),
    'a2-relatives': ('Akrabalar', None),
    'a2-twins': ('İkizler', None),
    'a2-only-child': ('Tek çocuk', None),
    'a2-to-take-care-of': ('Bakmak (birine)', None),
    'a2-nephew': ('Yeğen (erkek)', None),
    'a2-niece': ('Yeğen (kız)', None),
    'a2-grandchild': ('Torun', None),
    'a2-single': ('Bekar', None),
    'a2-divorced': ('Boşanmış', None),
    'a2-christmas': ('Noel', None),
    'a2-new-year': ('Yeni Yıl', None),
    'a2-cake': ('Pasta', None),
    'a2-candle': ('Mum', None),
    'a2-lesson': ('Ders', None),
    'a2-course': ('Kurs', None),
    'a2-to-practice': ('Pratik yapmak', None),
    'a2-mistake': ('Hata', None),
    'a2-to-correct': ('Düzeltmek', None),
    'a2-grade-mark': ('Not', None),
    'a2-to-pass-an-exam': ('Sınavı geçmek', None),
    'a2-to-fail-an-exam': ('Sınavda kalmak', None),
    'a2-to-graduate': ('Mezun olmak', None),
    'a2-degree': ('Diploma', None),
    'a2-subject': ('Branş', None),
    'a2-math': ('Matematik', None),
    'a2-history': ('Tarih', None),
    'a2-science': ('Bilim', None),
    'a2-art': ('Sanat', None),
    'a2-dictionary': ('Sözlük', None),
    'a2-notebook': ('Defter', None),
    'a2-to-memorize': ('Ezberlemek', None),
    'a2-to-review': ('Tekrar etmek', None),
    'a2-classroom': ('Sınıf (oda)', None),
    'a2-semester': ('Dönem', None),
    'a2-scholarship': ('Burs', None),
    'a2-to-register': ('Kayıt olmak', None),
    'a2-example': ('Örnek', None),
    'a2-level': ('Seviye', None),
    'a2-beginner': ('Başlangıç seviyesi', None),
    'a2-to-save-money': ('Para biriktirmek', None),
    'a2-bank-account': ('Banka hesabı', None),
    'a2-to-withdraw': ('Para çekmek', None),
    'a2-to-deposit': ('Para yatırmak', None),
    'a2-atm': ('ATM', None),
    'a2-loan': ('Kredi', None),
    'a2-debt': ('Borç', None),
    'a2-to-borrow': ('Ödünç almak', None),
    'a2-to-lend': ('Ödünç vermek', None),
    'a2-to-owe': ('Borçlu olmak', None),
    'a2-tax': ('Vergi', None),
    'a2-bill-utility': ('Fatura', None),
    'a2-budget': ('Bütçe', None),
    'a2-to-afford': ('Gücü yetmek', None),
    'a2-interest-bank': ('Faiz', None),
    'a2-coin': ('Madeni para', None),
    'a2-to-exchange-money': ('Para bozdurmak', None),
    'a2-exchange-rate': ('Döviz kuru', None),
    'a2-credit-card': ('Kredi kartı', None),
    'a2-to-cost': ('Fiyatı olmak', None),
    'a2-salary-raise': ('Maaş artışı', None),
    'a2-expensive-habit': ('Pahalı alışkanlık', None),
    'a2-invoice': ('Fatura (ticari)', None),
    'a2-payment': ('Ödeme', None),
    'a2-to-miss-someone': ('Özlemek', None),
    'a2-to-worry': ('Endişelenmek', None),
    'a2-to-enjoy': ('Keyif almak', None),
    'a2-to-hate': ('Nefret etmek', None),
    'a2-to-be-afraid-of': ('Korkmak', None),
    'a2-ashamed': ('Utanmış', None),
    'a2-jealous': ('Kıskanç', None),
    'a2-embarrassed': ('Mahcup', None),
    'a2-disappointed': ('Hayal kırıklığına uğramış', None),
    'a2-grateful': ('Minnettar', None),
    'a2-relieved': ('Rahatlamış', None),
    'a2-confused': ('Kafası karışık', None),
    'a2-curious': ('Meraklı', None),
    'a2-hopeful': ('Umutlu', None),
    'a2-frustrated': ('Bunalmış', None),
    'a2-stressed': ('Stresli', None),
    'a2-in-a-good-mood': ('İyi bir ruh halinde', None),
    'a2-in-a-bad-mood': ('Kötü bir ruh halinde', None),
    'a2-to-cheer-up': ('Neşelenmek', None),
    'a2-to-calm-down': ('Sakinleşmek', None),
    'a2-to-get-angry': ('Sinirlenmek', None),
    'a2-to-fall-in-love': ('Aşık olmak', None),
    'a2-mood': ('Ruh hali', None),
    'a2-satisfied': ('Memnun', None),
    'a2-forest': ('Orman', None),
    'a2-lake': ('Göl', None),
    'a2-island': ('Ada', None),
    'a2-desert': ('Çöl', None),
    'a2-field': ('Tarla', None),
    'a2-farm': ('Çiftlik', None),
    'a2-animal': ('Hayvan', None),
    'a2-insect': ('Böcek', None),
    'a2-mosquito': ('Sivrisinek', None),
    'a2-bee': ('Arı', None),
    'a2-butterfly': ('Kelebek', None),
    'a2-snake': ('Yılan', None),
    'a2-lion': ('Aslan', None),
    'a2-elephant': ('Fil', None),
    'a2-monkey': ('Maymun', None),
    'a2-rabbit': ('Tavşan', None),
    'a2-pig': ('Domuz', None),
    'a2-sheep': ('Koyun', None),
    'a2-plant': ('Bitki', None),
    'a2-grass': ('Çim', None),
    'a2-leaf': ('Yaprak', None),
    'a2-rock': ('Kaya', None),
    'a2-sand': ('Kum', None),
    'a2-ocean': ('Okyanus', None),
    'a2-wave': ('Dalga', None),
    'a2-thunder': ('Gök gürültüsü', None),
    'a2-fog': ('Sis', None),
    'a2-temperature': ('Sıcaklık', None),
    'a2-laptop': ('Dizüstü bilgisayar', None),
    'a2-keyboard': ('Klavye', None),
    'a2-printer': ('Yazıcı', None),
    'a2-file': ('Dosya', None),
    'a2-folder': ('Klasör', None),
    'a2-to-print': ('Yazdırmak', None),
    'a2-to-click': ('Tıklamak', None),
    'a2-to-type': ('Yazmak (klavyeyle)', None),
    'a2-to-search-online': ('İnternette aramak', None),
    'a2-social-media': ('Sosyal medya', None),
    'a2-to-post': ('Gönderi paylaşmak', None),
    'a2-to-share': ('Paylaşmak', None),
    'a2-video': ('Video', None),
    'a2-photo': ('Fotoğraf', None),
    'a2-selfie': ('Selfi', None),
    'a2-headphones': ('Kulaklık', None),
    'a2-speaker': ('Hoparlör', None),
    'a2-battery': ('Pil', None),
    'a2-to-turn-on': ('Açmak', None),
    'a2-to-turn-off': ('Kapatmak', None),
    'a2-volume': ('Ses seviyesi', None),
    'a2-channel': ('Kanal', None),
    'a2-podcast': ('Podcast', None),
    'a2-screenshot': ('Ekran görüntüsü', None),
    'a2-update': ('Güncelleme', None),
    'a2-notification': ('Bildirim', None),
    'a2-to-log-in': ('Giriş yapmak', None),
    'a2-subtitles': ('Altyazı', None),
    'a2-what-do-you-think': ('Sen ne düşünüyorsun?', None),
    'a2-it-depends': ('Duruma göre değişir', None),
    'a2-im-not-sure': ('Emin değilim', None),
    'a2-let-me-think': ('Bir düşüneyim', None),
    'a2-what-a-pity': ('Ne yazık', None),
    'a2-never-mind': ('Boş ver', None),
    'a2-hurry-up': ('Acele et', None),
    'a2-watch-out': ('Dikkat et!', None),
    'a2-thats-a-good-idea': ('Bu iyi bir fikir', None),
    'a2-are-you-kidding': ('Şaka mı yapıyorsun?', None),
    'a2-its-up-to-you': ('Sana kalmış', None),
    'a2-im-on-my-way': ('Geliyorum', None),
    'a2-same-here': ('Bende öyle', None),
    'a2-me-neither': ('Ben de değil', None),
    'a2-by-the-way': ('Bu arada', None),
    'a2-in-my-opinion': ('Bence', None),
    'a2-to-be-honest': ('Dürüst olmak gerekirse', None),
    'a2-actually': ('Aslında', None),
    'a2-anyway': ('Her neyse', None),
    'a2-for-example': ('Örneğin', None),
    'a2-sorry-im-late': ('Geciktiğim için özür dilerim', None),
    'a2-no-way': ('Asla!', None),
    'a2-that-makes-sense': ('Bu mantıklı', None),
    'a2-good-point': ('İyi nokta', None),
    'a2-banana': ('Muz', None),
    'a2-orange-fruit': ('Portakal', None),
    'a2-grapes': ('Üzüm', None),
    'a2-strawberry': ('Çilek', None),
    'a2-lemon': ('Limon', None),
    'a2-watermelon': ('Karpuz', None),
    'a2-peach': ('Şeftali', None),
    'a2-pear': ('Armut', None),
    'a2-carrot': ('Havuç', None),
    'a2-lettuce': ('Marul', None),
    'a2-cucumber': ('Salatalık', None),
    'a2-bell-pepper': ('Dolmalık biber', None),
    'a2-mushroom': ('Mantar', None),
    'a2-corn': ('Mısır', None),
    'a2-beans': ('Fasulye', None),
    'a2-spinach': ('Ispanak', None),
    'a2-cabbage': ('Lahana', None),
    'a2-pumpkin': ('Bal kabağı', None),
    'a2-nuts': ('Kuruyemiş', None),
    'a2-coconut': ('Hindistan cevizi', None),
    'a2-mango': ('Mango', None),
    'a2-pineapple': ('Ananas', None),
    'a2-cherry': ('Kiraz', None),
    'a2-avocado': ('Avokado', None),
    'a2-ripe': ('Olgun', None),
    'a2-fresh': ('Taze', None),
    'a2-kilogram': ('Kilogram', None),
    'a2-gram': ('Gram', None),
    'a2-liter': ('Litre', None),
    'a2-meter': ('Metre', None),
    'a2-kilometer': ('Kilometre', None),
    'a2-centimeter': ('Santimetre', None),
    'a2-piece': ('Parça', None),
    'a2-slice': ('Dilim', None),
    'a2-dozen': ('Düzine', None),
    'a2-pair': ('Çift (adet)', None),
    'a2-percent': ('Yüzde', None),
    'a2-degree-temperature': ('Derece', None),
    'a2-a-bit': ('Biraz', None),
    'a2-a-lot': ('Bir sürü', None),
    'a2-several': ('Birkaç', None),
    'a2-double': ('İki kat', None),
    'a2-weight': ('Ağırlık', None),
    'a2-height': ('Boy', None),
    'a2-length': ('Uzunluk', None),
    'a2-distance': ('Mesafe', None),
    'a2-speed': ('Hız', None),
    'a2-total': ('Toplam', None),
    'a2-almost': ('Neredeyse', None),
    'a2-only': ('Sadece', None),
    'a2-engineer': ('Mühendis', None),
    'a2-lawyer': ('Avukat', None),
    'a2-chef': ('Şef (aşçı)', None),
    'a2-driver': ('Şoför', None),
    'a2-farmer': ('Çiftçi', None),
    'a2-artist': ('Sanatçı', None),
    'a2-musician': ('Müzisyen', None),
    'a2-actor': ('Oyuncu', None),
    'a2-writer': ('Yazar', None),
    'a2-journalist': ('Gazeteci', None),
    'a2-police-officer': ('Polis', None),
    'a2-firefighter': ('İtfaiyeci', None),
    'a2-scientist': ('Bilim insanı', None),
    'a2-programmer': ('Programcı', None),
    'a2-designer': ('Tasarımcı', None),
    'a2-manager': ('Yönetici', None),
    'a2-salesperson': ('Satış elemanı', None),
    'a2-mechanic': ('Tamirci', None),
    'a2-electrician': ('Elektrikçi', None),
    'a2-plumber': ('Tesisatçı', None),
    'a2-pilot': ('Pilot', None),
    'a2-accountant': ('Muhasebeci', None),
    'a2-architect': ('Mimar', None),
    'a2-hairdresser': ('Kuaför', None),
    'a2-soldier': ('Asker', None),
    'a2-baker': ('Fırıncı', None),
    'a2-basketball': ('Basketbol', None),
    'a2-tennis': ('Tenis', None),
    'a2-baseball': ('Beyzbol', None),
    'a2-volleyball': ('Voleybol', None),
    'a2-running': ('Koşu', None),
    'a2-cycling': ('Bisiklete binme', None),
    'a2-skiing': ('Kayak', None),
    'a2-surfing': ('Sörf', None),
    'a2-yoga': ('Yoga', None),
    'a2-chess': ('Satranç', None),
    'a2-cards-game': ('Kartlar', None),
    'a2-board-game': ('Masa oyunu', None),
    'a2-video-game': ('Video oyunu', None),
    'a2-puzzle': ('Yapboz', None),
    'a2-to-go-camping': ('Kamp yapmak', None),
    'a2-picnic': ('Piknik', None),
    'a2-fishing': ('Balık tutma', None),
    'a2-race': ('Yarış', None),
    'a2-competition': ('Yarışma', None),
    'a2-referee': ('Hakem', None),
    'a2-coach': ('Antrenör', None),
    'a2-medal': ('Madalya', None),
    'a2-score': ('Skor', None),
    'a2-fan-supporter': ('Taraftar', None),
    'a2-to-train': ('Antrenman yapmak', None),
}
