# -*- coding: utf-8 -*-
LANG = 'tr'
WORDS = {
    'b1-friendship': ('Arkadaşlık', None),
    'b1-trust': ('Güven', None),
    'b1-to-trust': ('Güvenmek', None),
    'b1-to-get-along': ('Anlaşmak', None),
    'b1-to-break-up': ('Ayrılmak', None),
    'b1-to-date-someone': ('Biriyle çıkmak', None),
    'b1-argument-quarrel': ('Tartışma (kavga)', None),
    'b1-to-forgive': ('Affetmek', None),
    'b1-to-support': ('Desteklemek', None),
    'b1-loyalty': ('Sadakat', None),
    'b1-to-rely-on': ('Güvenmek (dayanmak)', None),
    'b1-close-friend': ('Yakın arkadaş', None),
    'b1-acquaintance': ('Tanıdık', None),
    'b1-partner-romantic': ('Sevgili', None),
    'b1-ex': ('Eski sevgili', None),
    'b1-crush': ('Aşk (tutulma)', None),
    'b1-to-flirt': ('Flört etmek', None),
    'b1-to-make-up-reconcile': ('Barışmak', None),
    'b1-to-hang-out': ('Takılmak', None),
    'b1-to-get-to-know': ('Tanımak (tanışmak)', None),
    'b1-to-keep-in-touch': ('İletişimde kalmak', None),
    'b1-to-lose-touch': ('İletişimi kaybetmek', None),
    'b1-reunion': ('Buluşma (yeniden bir araya gelme)', None),
    'b1-to-introduce': ('Tanıştırmak', None),
    'b1-respect': ('Saygı', None),
    'b1-sincerity': ('Samimiyet', None),
    'b1-best-friend': ('En iyi arkadaş', None),
    'b1-stranger': ('Yabancı', None),
    'b1-to-betray': ('İhanet etmek', None),
    'b1-bond': ('Bağ', None),
    'b1-to-agree': ('Katılmak (hemfikir olmak)', None),
    'b1-to-disagree': ('Katılmamak', None),
    'b1-point-of-view': ('Bakış açısı', None),
    'b1-argument-reasoning': ('Argüman (gerekçe)', None),
    'b1-to-convince': ('İkna etmek', None),
    'b1-to-doubt': ('Şüphe etmek', None),
    'b1-to-admit': ('Kabul etmek (itiraf etmek)', None),
    'b1-to-deny': ('İnkâr etmek', None),
    'b1-to-insist': ('Israr etmek', None),
    'b1-obviously': ('Açıkça', None),
    'b1-probably': ('Muhtemelen', None),
    'b1-definitely': ('Kesinlikle', None),
    'b1-according-to': ('-e göre', None),
    'b1-on-the-other-hand': ('Öte yandan', None),
    'b1-however': ('Ancak', None),
    'b1-although': ('Her ne kadar', None),
    'b1-therefore': ('Bu yüzden', None),
    'b1-in-fact': ('Aslında', None),
    'b1-whereas': ('Oysa ki', None),
    'b1-unless': ('-medikçe', None),
    'b1-in-spite-of': ('-e rağmen', None),
    'b1-as-long-as': ('-diği sürece', None),
    'b1-to-consider': ('Düşünmek (göz önünde bulundurmak)', None),
    'b1-to-assume': ('Varsaymak', None),
    'b1-to-realize': ('Fark etmek', None),
    'b1-to-wonder': ('Merak etmek', None),
    'b1-to-prove': ('Kanıtlamak', None),
    'b1-evidence': ('Kanıt', None),
    'b1-to-exaggerate': ('Abartmak', None),
    'b1-fair': ('Adil', None),
    'b1-unfair': ('Adaletsiz', None),
    'b1-anxious': ('Endişeli', None),
    'b1-overwhelmed': ('Bunalmış', None),
    'b1-thrilled': ('Heyecanlı (çok mutlu)', None),
    'b1-homesick': ('Sıla hasreti çeken', None),
    'b1-moved-emotionally': ('Duygulanmış', None),
    'b1-guilty': ('Suçlu (vicdan azabı duyan)', None),
    'b1-awkward': ('Garip (utanç verici)', None),
    'b1-upset': ('Üzgün', None),
    'b1-furious': ('Çok öfkeli', None),
    'b1-delighted': ('Memnun', None),
    'b1-hesitant': ('Kararsız', None),
    'b1-indifferent': ('Kayıtsız', None),
    'b1-insecure': ('Kendine güvensiz', None),
    'b1-confident': ('Kendine güvenen', None),
    'b1-motivated': ('Motive olmuş', None),
    'b1-exhausted': ('Bitkin', None),
    'b1-restless': ('Huzursuz', None),
    'b1-grumpy': ('Huysuz', None),
    'b1-nostalgic': ('Nostaljik', None),
    'b1-pleased': ('Memnun (hoşnut)', None),
    'b1-annoyed': ('Sinirlenmiş', None),
    'b1-terrified': ('Dehşete düşmüş', None),
    'b1-amused': ('Eğlenmiş', None),
    'b1-envious': ('Kıskanç', None),
    'b1-hopeless': ('Umutsuz', None),
    'b1-bittersweet': ('Hem tatlı hem acı', None),
    'b1-at-ease': ('Rahat', None),
    'b1-uneasy': ('Huzursuz (rahatsız)', None),
    'b1-speechless': ('Şaşkınlıktan dili tutulmuş', None),
    'b1-touched': ('Duygulanmış (etkilenmiş)', None),
    'b1-to-apply-for-a-job': ('İş başvurusu yapmak', None),
    'b1-resume': ('Özgeçmiş', None),
    'b1-to-get-promoted': ('Terfi etmek', None),
    'b1-to-quit': ('İstifa etmek', None),
    'b1-to-fire-someone': ('Birini işten çıkarmak', None),
    'b1-to-retire': ('Emekli olmak', None),
    'b1-part-time': ('Yarı zamanlı', None),
    'b1-full-time': ('Tam zamanlı', None),
    'b1-overtime': ('Mesai (fazla mesai)', None),
    'b1-shift': ('Vardiya', None),
    'b1-to-negotiate': ('Pazarlık yapmak', None),
    'b1-contract': ('Sözleşme', None),
    'b1-to-sign': ('İmzalamak', None),
    'b1-freelance': ('Serbest çalışan', None),
    'b1-presentation': ('Sunum', None),
    'b1-teamwork': ('Takım çalışması', None),
    'b1-responsibility': ('Sorumluluk', None),
    'b1-task': ('Görev (iş)', None),
    'b1-goal': ('Hedef', None),
    'b1-feedback': ('Geri bildirim', None),
    'b1-to-be-in-charge': ('Sorumlu olmak', None),
    'b1-employee': ('Çalışan', None),
    'b1-employer': ('İşveren', None),
    'b1-to-earn-a-living': ('Hayatını kazanmak', None),
    'b1-workload': ('İş yükü', None),
    'b1-burnout': ('Tükenmişlik', None),
    'b1-day-off': ('İzin günü', None),
    'b1-vacation': ('Tatil', None),
    'b1-coworker': ('İş arkadaşı', None),
    'b1-experience': ('Deneyim', None),
    'b1-skill': ('Beceri', None),
    'b1-to-train-someone': ('Birini eğitmek', None),
    'b1-to-explore': ('Keşfetmek', None),
    'b1-adventure': ('Macera', None),
    'b1-backpack': ('Sırt çantası', None),
    'b1-hostel': ('Hostel', None),
    'b1-to-wander': ('Dolaşmak (amaçsızca)', None),
    'b1-landmark': ('Simgesel yapı', None),
    'b1-view': ('Manzara', None),
    'b1-scenery': ('Doğal manzara', None),
    'b1-local-person': ('Yerli (bölge sakini)', None),
    'b1-custom-tradition': ('Gelenek', None),
    'b1-culture': ('Kültür', None),
    'b1-to-experience': ('Yaşamak (deneyimlemek)', None),
    'b1-to-recommend': ('Tavsiye etmek', None),
    'b1-itinerary': ('Seyahat planı', None),
    'b1-unforgettable': ('Unutulmaz', None),
    'b1-jet-lag': ('Jet lag', None),
    'b1-to-pack': ('Bavul hazırlamak', None),
    'b1-destination': ('Varış noktası', None),
    'b1-journey': ('Yolculuk', None),
    'b1-cruise': ('Gemi turu', None),
    'b1-to-rent-a-car': ('Araba kiralamak', None),
    'b1-border': ('Sınır', None),
    'b1-visa': ('Vize', None),
    'b1-currency': ('Para birimi', None),
    'b1-to-take-a-photo': ('Fotoğraf çekmek', None),
    'b1-to-get-around': ('Etrafta dolaşmak (ulaşım sağlamak)', None),
    'b1-off-the-beaten-path': ('Az bilinen (turistik olmayan)', None),
    'b1-tourist-trap': ('Turist tuzağı', None),
    'b1-layover': ('Ara durak (aktarma)', None),
    'b1-sunburn': ('Güneş yanığı', None),
    'b1-to-work-out': ('Egzersiz yapmak', None),
    'b1-diet': ('Diyet', None),
    'b1-to-lose-weight': ('Kilo vermek', None),
    'b1-to-gain-weight': ('Kilo almak', None),
    'b1-muscle': ('Kas', None),
    'b1-to-stretch': ('Esnemek (germe hareketi yapmak)', None),
    'b1-to-warm-up': ('Isınmak', None),
    'b1-calories': ('Kalori', None),
    'b1-protein': ('Protein', None),
    'b1-to-breathe': ('Nefes almak', None),
    'b1-heartbeat': ('Kalp atışı', None),
    'b1-to-sweat': ('Terlemek', None),
    'b1-to-recover': ('İyileşmek', None),
    'b1-sprain': ('Burkulma', None),
    'b1-to-faint': ('Bayılmak', None),
    'b1-dizzy': ('Baş dönmesi çeken', None),
    'b1-nausea': ('Bulantı', None),
    'b1-to-sneeze': ('Hapşırmak', None),
    'b1-symptom': ('Belirti', None),
    'b1-vaccine': ('Aşı', None),
    'b1-checkup': ('Sağlık kontrolü', None),
    'b1-therapy': ('Terapi', None),
    'b1-to-quit-smoking': ('Sigarayı bırakmak', None),
    'b1-wellbeing': ('İyi oluş hali', None),
    'b1-mental-health': ('Ruh sağlığı', None),
    'b1-to-meditate': ('Meditasyon yapmak', None),
    'b1-insomnia': ('Uykusuzluk', None),
    'b1-energy': ('Enerji', None),
    'b1-painkiller': ('Ağrı kesici', None),
    'b1-sore': ('Ağrıyan', None),
    'b1-cuisine': ('Mutfak (yemek kültürü)', None),
    'b1-flavor': ('Tat (lezzet)', None),
    'b1-homemade': ('Ev yapımı', None),
    'b1-mild': ('Az baharatlı (yumuşak)', None),
    'b1-to-season': ('Baharatlamak', None),
    'b1-portion': ('Porsiyon', None),
    'b1-leftovers': ('Artık yemek', None),
    'b1-street-food': ('Sokak yemeği', None),
    'b1-specialty': ('Spesiyalite', None),
    'b1-to-treat-pay-for-someone': ('Birine ısmarlamak', None),
    'b1-to-split-the-bill': ('Hesabı bölüşmek', None),
    'b1-tasty': ('Lezzetli', None),
    'b1-disgusting': ('İğrenç', None),
    'b1-to-chew': ('Çiğnemek', None),
    'b1-to-swallow': ('Yutmak', None),
    'b1-appetite': ('İştah', None),
    'b1-craving': ('Aşerme (canı çekme)', None),
    'b1-im-full': ('Doydum', None),
    'b1-to-skip-a-meal': ('Öğün atlamak', None),
    'b1-brunch': ('Brunch', None),
    'b1-to-grab-a-bite': ('Hızlıca bir şeyler yemek', None),
    'b1-a-toast': ('Kadeh kaldırma', None),
    'b1-vegan': ('Vegan', None),
    'b1-gluten-free': ('Glütensiz', None),
    'b1-organic': ('Organik', None),
    'b1-recipe-book': ('Yemek tarifi kitabı', None),
    'b1-chopsticks': ('Çin çubukları', None),
    'b1-napkin': ('Peçete', None),
    'b1-reservation-for-dinner': ('Akşam yemeği rezervasyonu', None),
    'b1-buffet': ('Açık büfe', None),
    'b1-mortgage': ('Konut kredisi', None),
    'b1-to-own': ('Sahip olmak', None),
    'b1-lease': ('Kira sözleşmesi', None),
    'b1-security-deposit': ('Depozito', None),
    'b1-utilities': ('Faturalar (su, elektrik vb.)', None),
    'b1-cozy': ('Rahat (sıcak samimi)', None),
    'b1-spacious': ('Geniş', None),
    'b1-to-decorate': ('Dekore etmek', None),
    'b1-to-renovate': ('Yenilemek (tadilat yapmak)', None),
    'b1-to-move-in': ('Taşınmak (eve girmek)', None),
    'b1-to-move-out': ('Taşınmak (evden çıkmak)', None),
    'b1-suburb': ('Banliyö', None),
    'b1-countryside': ('Kırsal bölge', None),
    'b1-balcony': ('Balkon', None),
    'b1-basement': ('Bodrum', None),
    'b1-attic': ('Çatı katı', None),
    'b1-garage': ('Garaj', None),
    'b1-yard': ('Bahçe (avlu)', None),
    'b1-fence': ('Çit', None),
    'b1-to-lock': ('Kilitlemek', None),
    'b1-doorbell': ('Kapı zili', None),
    'b1-mailbox': ('Posta kutusu', None),
    'b1-hallway': ('Koridor', None),
    'b1-ceiling': ('Tavan', None),
    'b1-to-hang-a-picture': ('Tablo asmak', None),
    'b1-neighborhood-watch': ('Mahalle bekçiliği', None),
    'b1-real-estate-agent': ('Emlakçı', None),
    'b1-property': ('Mülk', None),
    'b1-tenant': ('Kiracı', None),
    'b1-furnished': ('Eşyalı', None),
    'b1-bargain': ('Kelepir', None),
    'b1-to-haggle': ('Pazarlık etmek', None),
    'b1-warranty': ('Garanti', None),
    'b1-to-exchange-goods': ('Değiştirmek (ürün)', None),
    'b1-customer-service': ('Müşteri hizmetleri', None),
    'b1-to-file-a-complaint': ('Şikayette bulunmak', None),
    'b1-counterfeit': ('Sahte (taklit)', None),
    'b1-second-hand': ('İkinci el', None),
    'b1-to-browse': ('Göz atmak (bakınmak)', None),
    'b1-to-subscribe': ('Abone olmak', None),
    'b1-subscription': ('Abonelik', None),
    'b1-membership': ('Üyelik', None),
    'b1-checkout': ('Kasa', None),
    'b1-out-of-stock': ('Stokta yok', None),
    'b1-in-stock': ('Stokta var', None),
    'b1-to-track-a-package': ('Kargoyu takip etmek', None),
    'b1-fashion': ('Moda', None),
    'b1-style': ('Tarz', None),
    'b1-trend': ('Trend', None),
    'b1-to-match-clothes': ('Kombinlemek (kıyafet)', None),
    'b1-outfit': ('Kombin', None),
    'b1-to-suit-look-good-on': ('Yakışmak', None),
    'b1-accessory': ('Aksesuar', None),
    'b1-jewelry': ('Mücevher', None),
    'b1-perfume': ('Parfüm', None),
    'b1-coupon': ('İndirim kuponu', None),
    'b1-free-shipping': ('Ücretsiz kargo', None),
    'b1-return-policy': ('İade politikası', None),
    'b1-impulse-buy': ('Anlık alışveriş', None),
    'b1-value-for-money': ('Fiyat performans', None),
    'b1-to-avoid': ('Kaçınmak', None),
    'b1-to-achieve': ('Başarmak', None),
    'b1-to-appreciate': ('Değer vermek (takdir etmek)', None),
    'b1-to-attend': ('Katılmak (etkinliğe)', None),
    'b1-to-belong': ('Ait olmak', None),
    'b1-to-bother': ('Rahatsız etmek', None),
    'b1-to-care-about': ('Önemsemek', None),
    'b1-to-deal-with': ('Baş etmek', None),
    'b1-to-depend-on': ('Bağlı olmak (bir şeye)', None),
    'b1-to-deserve': ('Hak etmek', None),
    'b1-to-develop': ('Geliştirmek', None),
    'b1-to-disappear': ('Kaybolmak', None),
    'b1-to-encourage': ('Cesaretlendirmek', None),
    'b1-to-expect': ('Beklemek (ummak)', None),
    'b1-to-handle': ('Halletmek', None),
    'b1-to-imagine': ('Hayal etmek', None),
    'b1-to-improve': ('İyileştirmek (geliştirmek)', None),
    'b1-to-increase': ('Artırmak', None),
    'b1-to-decrease': ('Azaltmak', None),
    'b1-to-involve': ('İçermek (kapsamak)', None),
    'b1-to-mention': ('Bahsetmek', None),
    'b1-to-notice': ('Fark etmek', None),
    'b1-to-offer': ('Teklif etmek', None),
    'b1-to-organize': ('Düzenlemek (organize etmek)', None),
    'b1-to-participate': ('Katılmak', None),
    'b1-to-pretend': ('Numara yapmak (yalandan yapmak)', None),
    'b1-to-protect': ('Korumak', None),
    'b1-to-provide': ('Sağlamak (temin etmek)', None),
    'b1-to-recognize': ('Tanımak (fark etmek)', None),
    'b1-to-refuse': ('Reddetmek', None),
    'b1-to-reduce': ('Azaltmak', None),
    'b1-to-regret': ('Pişman olmak', None),
    'b1-to-remain': ('Kalmak (devam etmek)', None),
    'b1-to-replace': ('Değiştirmek (yerine koymak)', None),
    'b1-to-require': ('Gerektirmek', None),
    'b1-to-solve': ('Çözmek', None),
    'b1-to-struggle': ('Mücadele etmek', None),
    'b1-to-succeed': ('Başarılı olmak', None),
    'b1-to-suffer': ('Acı çekmek', None),
    'b1-to-survive': ('Hayatta kalmak', None),
    'b1-to-warn': ('Uyarmak', None),
    'b1-to-manage-to-cope': ('Başarmak (idare etmek)', None),
    'b1-to-perform': ('Sahne almak (icra etmek)', None),
    'b1-to-fail-in-general': ('Başarısız olmak', None),
    'b1-to-attempt': ('Girişimde bulunmak', None),
    'b1-to-complain-about': ('Şikayet etmek', None),
    'b1-to-rely-on-someone': ('Birine güvenmek', None),
    'b1-to-take-part': ('Katılmak (yer almak)', None),
    'b1-to-turn-out': ('Ortaya çıkmak (öyle çıkmak)', None),
    'b1-to-end-up': ('Sonunda -mek (bir sonuca varmak)', None),
    'b1-to-give-up': ('Vazgeçmek', None),
    'b1-to-look-forward-to': ('Sabırsızlıkla beklemek', None),
    'b1-to-put-off': ('Ertelemek', None),
    'b1-to-run-out-of': ('Tükenmek (bir şeyi bitirmek)', None),
    'b1-to-get-rid-of': ('Kurtulmak (bir şeyden)', None),
    'b1-to-come-up-with': ('Bulmak (fikir üretmek)', None),
    'b1-to-figure-out': ('Çözmek (anlamak)', None),
    'b1-to-catch-up': ('Yetişmek (aradaki farkı kapatmak)', None),
    'b1-to-show-up': ('Ortaya çıkmak (gelmek)', None),
    'b1-to-break-down-machine': ('Arızalanmak (makine)', None),
    'b1-to-fill-in-a-form': ('Formu doldurmak', None),
    'b1-to-pick-up-collect': ('Almak (teslim almak)', None),
    'b1-to-drop-off': ('Bırakmak (birini indirmek)', None),
    'b1-to-hang-up-phone': ('Telefonu kapatmak', None),
    'b1-to-look-after': ('Bakmak (ilgilenmek)', None),
    'b1-reliable': ('Güvenilir', None),
    'b1-responsible': ('Sorumlu', None),
    'b1-ambitious': ('Hırslı', None),
    'b1-creative': ('Yaratıcı', None),
    'b1-flexible': ('Esnek', None),
    'b1-independent': ('Bağımsız', None),
    'b1-mature': ('Olgun', None),
    'b1-sensitive': ('Duyarlı (hassas)', None),
    'b1-sensible': ('Mantıklı (sağduyulu)', None),
    'b1-selfish': ('Bencil', None),
    'b1-humble': ('Alçakgönüllü', None),
    'b1-arrogant': ('Kibirli', None),
    'b1-easygoing': ('Rahat (kolay geçinen)', None),
    'b1-outgoing': ('Girişken (dışa dönük)', None),
    'b1-moody': ('Değişken ruh halli', None),
    'b1-picky': ('Titiz (seçici)', None),
    'b1-clumsy': ('Sakar', None),
    'b1-brave': ('Cesur', None),
    'b1-cowardly': ('Korkak', None),
    'b1-wise': ('Bilge', None),
    'b1-naive': ('Saf (safdil)', None),
    'b1-thoughtful': ('Düşünceli', None),
    'b1-careless': ('Dikkatsiz', None),
    'b1-careful': ('Dikkatli', None),
    'b1-punctual': ('Dakik', None),
    'b1-greedy': ('Açgözlü', None),
    'b1-loyal': ('Sadık', None),
    'b1-charming': ('Çekici (etkileyici)', None),
    'b1-weird': ('Tuhaf', None),
    'b1-down-to-earth': ('Ayakları yere basan', None),
    'b1-available': ('Müsait', None),
    'b1-convenient': ('Uygun (elverişli)', None),
    'b1-complicated': ('Karmaşık', None),
    'b1-obvious': ('Belli (aşikâr)', None),
    'b1-essential': ('Gerekli (esas)', None),
    'b1-necessary': ('Gerekli', None),
    'b1-useful': ('Yararlı', None),
    'b1-useless': ('Yararsız', None),
    'b1-worth-it': ('Buna değer', None),
    'b1-affordable': ('Uygun fiyatlı', None),
    'b1-valuable': ('Değerli', None),
    'b1-reasonable': ('Makul', None),
    'b1-ridiculous': ('Saçma', None),
    'b1-impressive': ('Etkileyici', None),
    'b1-disappointing': ('Hayal kırıklığı yaratan', None),
    'b1-exciting': ('Heyecan verici', None),
    'b1-relaxing': ('Rahatlatıcı', None),
    'b1-tiring': ('Yorucu', None),
    'b1-annoying': ('Can sıkıcı', None),
    'b1-embarrassing': ('Utandırıcı', None),
    'b1-confusing': ('Kafa karıştırıcı', None),
    'b1-satisfying': ('Tatmin edici', None),
    'b1-awful': ('Berbat', None),
    'b1-terrific': ('Muhteşem', None),
    'b1-decent': ('Gayet iyi (düzgün)', None),
    'b1-average': ('Ortalama', None),
    'b1-rare': ('Nadir', None),
    'b1-common': ('Yaygın', None),
    'b1-typical': ('Tipik', None),
    'b1-unusual': ('Sıra dışı', None),
    'b1-first-of-all': ('Her şeyden önce', None),
    'b1-then': ('Sonra', None),
    'b1-after-that': ('Ondan sonra', None),
    'b1-in-addition': ('Ayrıca (buna ek olarak)', None),
    'b1-besides': ('Bunun yanı sıra', None),
    'b1-for-instance': ('Örneğin', None),
    'b1-in-other-words': ('Başka bir deyişle', None),
    'b1-on-the-contrary': ('Aksine', None),
    'b1-nevertheless': ('Yine de', None),
    'b1-meanwhile': ('Bu arada', None),
    'b1-as-a-result': ('Sonuç olarak', None),
    'b1-in-conclusion': ('Sonuç olarak (özetle)', None),
    'b1-in-short': ('Kısacası', None),
    'b1-at-first': ('İlk başta', None),
    'b1-eventually': ('Sonunda', None),
    'b1-otherwise': ('Aksi takdirde', None),
    'b1-in-case': ('Her ihtimale karşı', None),
    'b1-as-soon-as': ('-er -mez', None),
    'b1-even-though': ('Her ne kadar da olsa', None),
    'b1-as-if': ('Sanki', None),
    'b1-so-that': ('-mesi için (öyle ki)', None),
    'b1-in-order-to': ('-mek amacıyla', None),
    'b1-apart-from': ('-in dışında', None),
    'b1-instead-of': ('Yerine', None),
    'b1-despite': ('-e rağmen', None),
    'b1-thanks-to': ('Sayesinde', None),
    'b1-above-all': ('Her şeyden önce (özellikle)', None),
    'b1-basically': ('Temelde', None),
    'b1-luckily': ('Neyse ki', None),
    'b1-unfortunately': ('Maalesef', None),
    'b1-government': ('Hükümet', None),
    'b1-election': ('Seçim', None),
    'b1-to-vote': ('Oy vermek', None),
    'b1-law': ('Kanun', None),
    'b1-crime': ('Suç', None),
    'b1-justice': ('Adalet', None),
    'b1-rights': ('Haklar', None),
    'b1-freedom': ('Özgürlük', None),
    'b1-economy': ('Ekonomi', None),
    'b1-unemployment': ('İşsizlik', None),
    'b1-poverty': ('Yoksulluk', None),
    'b1-wealth': ('Zenginlik', None),
    'b1-immigration': ('Göç', None),
    'b1-protest': ('Protesto', None),
    'b1-strike': ('Grev', None),
    'b1-war': ('Savaş', None),
    'b1-peace': ('Barış', None),
    'b1-citizen': ('Vatandaş', None),
    'b1-community': ('Topluluk', None),
    'b1-charity': ('Hayır kurumu', None),
    'b1-volunteer': ('Gönüllü', None),
    'b1-to-donate': ('Bağışlamak', None),
    'b1-environment': ('Çevre', None),
    'b1-pollution': ('Kirlilik', None),
    'b1-climate-change': ('İklim değişikliği', None),
    'b1-to-recycle': ('Geri dönüştürmek', None),
    'b1-waste-garbage': ('Atık (çöp)', None),
    'b1-renewable-energy': ('Yenilenebilir enerji', None),
    'b1-population': ('Nüfus', None),
    'b1-politics': ('Siyaset', None),
    'b1-series': ('Dizi', None),
    'b1-episode': ('Bölüm', None),
    'b1-season-tv': ('Sezon', None),
    'b1-plot': ('Olay örgüsü', None),
    'b1-character-story': ('Karakter', None),
    'b1-ending': ('Son (bitiş)', None),
    'b1-spoiler': ('Spoyler', None),
    'b1-soundtrack': ('Film müziği', None),
    'b1-trailer': ('Fragman', None),
    'b1-to-binge-watch': ('Arka arkaya izlemek', None),
    'b1-documentary': ('Belgesel', None),
    'b1-comedy': ('Komedi', None),
    'b1-drama': ('Dram', None),
    'b1-thriller': ('Gerilim (film)', None),
    'b1-horror': ('Korku', None),
    'b1-animation': ('Animasyon', None),
    'b1-novel': ('Roman', None),
    'b1-poem': ('Şiir', None),
    'b1-author': ('Yazar', None),
    'b1-chapter': ('Bölüm (kitap)', None),
    'b1-headline': ('Manşet', None),
    'b1-article': ('Makale', None),
    'b1-magazine': ('Dergi', None),
    'b1-review': ('İnceleme (eleştiri)', None),
    'b1-rating': ('Puan (derecelendirme)', None),
    'b1-celebrity': ('Ünlü', None),
    'b1-fame': ('Şöhret', None),
    'b1-audience': ('İzleyici kitlesi', None),
    'b1-live-broadcast': ('Canlı yayın', None),
    'b1-streaming': ('Yayın akışı', None),
    'b1-material': ('Malzeme', None),
    'b1-wooden': ('Ahşap', None),
    'b1-plastic': ('Plastik', None),
    'b1-metal': ('Metal', None),
    'b1-glass-material': ('Cam', None),
    'b1-leather': ('Deri', None),
    'b1-cotton': ('Pamuk', None),
    'b1-wool': ('Yün', None),
    'b1-silk': ('İpek', None),
    'b1-smooth': ('Pürüzsüz', None),
    'b1-rough': ('Pürüzlü', None),
    'b1-sharp': ('Keskin', None),
    'b1-blunt': ('Kör (kesmeyen)', None),
    'b1-flat': ('Düz', None),
    'b1-thick': ('Kalın', None),
    'b1-slim': ('İnce', None),
    'b1-transparent': ('Şeffaf', None),
    'b1-shiny': ('Parlak', None),
    'b1-dull': ('Mat (donuk)', None),
    'b1-fragile': ('Kırılgan', None),
    'b1-sturdy': ('Sağlam (dayanıklı)', None),
    'b1-tiny': ('Minik', None),
    'b1-huge': ('Kocaman', None),
    'b1-medium': ('Orta boy', None),
    'b1-pattern': ('Desen', None),
    'b1-striped': ('Çizgili', None),
    'b1-plain-no-pattern': ('Düz (desensiz)', None),
    'b1-fancy': ('Şık (gösterişli)', None),
    'b1-elegant': ('Zarif', None),
    'b1-handmade': ('El yapımı', None),
    'b1-lifetime': ('Ömür', None),
    'b1-decade': ('On yıl', None),
    'b1-century': ('Yüzyıl', None),
    'b1-era': ('Çağ (dönem)', None),
    'b1-youth': ('Gençlik', None),
    'b1-middle-age': ('Orta yaş', None),
    'b1-old-age': ('Yaşlılık', None),
    'b1-retirement': ('Emeklilik', None),
    'b1-milestone': ('Dönüm noktası', None),
    'b1-to-turn-an-age': ('Yaşına girmek', None),
    'b1-to-age': ('Yaşlanmak', None),
    'b1-life-expectancy': ('Yaşam beklentisi', None),
    'b1-memory-recollection': ('Anı', None),
    'b1-to-look-back': ('Geriye dönüp bakmak', None),
    'b1-the-past': ('Geçmiş', None),
    'b1-the-present': ('Şimdiki zaman', None),
    'b1-the-future': ('Gelecek', None),
    'b1-nowadays': ('Günümüzde', None),
    'b1-in-the-long-run': ('Uzun vadede', None),
    'b1-temporary': ('Geçici', None),
    'b1-permanent': ('Kalıcı', None),
    'b1-forever': ('Sonsuza dek', None),
    'b1-occasionally': ('Ara sıra', None),
    'b1-rarely': ('Nadiren', None),
    'b1-frequently': ('Sık sık', None),
    'b1-daily': ('Günlük', None),
    'b1-weekly': ('Haftalık', None),
    'b1-monthly': ('Aylık', None),
    'b1-annual': ('Yıllık', None),
    'b1-generation-gap': ('Kuşak farkı', None),
    'b1-you-know-what-i-mean': ('Ne demek istediğimi anlıyor musun?', None),
    'b1-i-see-what-you-mean': ('Ne demek istediğini anlıyorum', None),
    'b1-that-reminds-me': ('Bu bana hatırlattı', None),
    'b1-speaking-of-which': ('Bahsi geçmişken', None),
    'b1-long-story-short': ('Uzun lafın kısası', None),
    'b1-im-afraid-so': ('Korkarım öyle', None),
    'b1-i-doubt-it': ('Şüpheliyim', None),
    'b1-its-worth-a-try': ('Denemeye değer', None),
    'b1-take-it-easy': ('Sakin ol', None),
    'b1-dont-get-me-wrong': ('Beni yanlış anlama', None),
    'b1-i-couldnt-agree-more': ('Tamamen katılıyorum', None),
    'b1-whats-up': ('Naber?', None),
    'b1-not-bad': ('Fena değil', None),
    'b1-so-far-so-good': ('Şimdilik iyi gidiyor', None),
    'b1-its-been-a-while': ('Uzun zaman oldu', None),
    'b1-guess-what': ('Bil bakalım ne oldu?', None),
    'b1-tell-me-about-it': ('Sorma bana!', None),
    'b1-ill-let-you-know': ('Sana haber veririm', None),
    'b1-count-me-in': ('Bana da güven (ben de varım)', None),
    'b1-id-rather-not': ('Tercih etmem', None),
    'b1-fair-enough': ('Anlaşıldı (makul)', None),
    'b1-no-worries': ('Sorun değil', None),
    'b1-sounds-like-a-plan': ('Kulağa iyi bir plan gibi geliyor', None),
    'b1-lets-play-it-by-ear': ('Anlık kararlar alalım', None),
    'b1-its-a-deal': ('Anlaştık', None),
    'b1-my-bad': ('Benim hatam', None),
    'b1-how-come': ('Nasıl olur da?', None),
    'b1-never-mind-that': ('Onu boş ver', None),
    'b1-i-cant-stand-it': ('Buna dayanamıyorum', None),
    'b1-it-slipped-my-mind': ('Aklımdan çıktı', None),
    'b1-thought': ('Düşünce', None),
    'b1-idea': ('Fikir', None),
    'b1-to-concentrate': ('Konsantre olmak', None),
    'b1-attention': ('Dikkat', None),
    'b1-to-focus': ('Odaklanmak', None),
    'b1-to-daydream': ('Hayal kurmak', None),
    'b1-imagination': ('Hayal gücü', None),
    'b1-creativity': ('Yaratıcılık', None),
    'b1-logic': ('Mantık', None),
    'b1-reason-cause': ('Sebep', None),
    'b1-common-sense': ('Sağduyu', None),
    'b1-intuition': ('Sezgi', None),
    'b1-to-guess': ('Tahmin etmek', None),
    'b1-to-predict': ('Öngörmek', None),
    'b1-to-make-up-ones-mind': ('Karar vermek', None),
    'b1-decision': ('Karar', None),
    'b1-choice': ('Seçim', None),
    'b1-to-hesitate': ('Tereddüt etmek', None),
    'b1-to-plan-ahead': ('Önceden planlamak', None),
    'b1-mindset': ('Zihniyet', None),
    'b1-perspective': ('Bakış açısı (perspektif)', None),
    'b1-to-overthink': ('Fazla düşünmek', None),
    'b1-curiosity': ('Merak', None),
    'b1-knowledge': ('Bilgi', None),
    'b1-wisdom': ('Bilgelik', None),
    'b1-to-be-aware': ('Farkında olmak', None),
    'b1-doubt-noun': ('Kuşku', None),
    'b1-belief': ('İnanç', None),
    'b1-confusion': ('Kafa karışıklığı', None),
    'b1-to-reflect-think-over': ('Üzerinde düşünmek', None),
    'b1-to-nod': ('Başını sallamak (onay)', None),
    'b1-to-shake-ones-head': ('Başını sallamak (ret)', None),
    'b1-to-wave': ('El sallamak', None),
    'b1-to-wink': ('Göz kırpmak', None),
    'b1-to-blink': ('Gözünü kırpıştırmak', None),
    'b1-to-yawn': ('Esnemek', None),
    'b1-to-sigh': ('İç çekmek', None),
    'b1-to-cough': ('Öksürmek', None),
    'b1-to-lean': ('Yaslanmak (eğilmek)', None),
    'b1-to-bend': ('Eğmek (bükmek)', None),
    'b1-to-kneel': ('Diz çökmek', None),
    'b1-to-crawl': ('Emeklemek', None),
    'b1-to-tiptoe': ('Parmak uçlarında yürümek', None),
    'b1-to-stumble': ('Sendelemek', None),
    'b1-to-trip-over': ('Takılmak (tökezlemek)', None),
    'b1-to-slip': ('Kaymak', None),
    'b1-to-grab': ('Kapmak', None),
    'b1-to-squeeze': ('Sıkmak', None),
    'b1-to-scratch': ('Kaşımak', None),
    'b1-to-rub': ('Ovalamak', None),
    'b1-to-shiver': ('Titremek', None),
    'b1-to-bite': ('Isırmak', None),
    'b1-to-lick': ('Yalamak', None),
    'b1-to-stare': ('Dik dik bakmak', None),
    'b1-to-glance': ('Göz atmak', None),
    'b1-to-frown': ('Kaşlarını çatmak', None),
    'b1-to-shrug': ('Omuz silkmek', None),
    'b1-to-point': ('İşaret etmek', None),
    'b1-to-clap': ('Alkışlamak', None),
    'b1-to-bow': ('Eğilerek selamlamak', None),
    'b1-traffic-jam': ('Trafik sıkışıklığı', None),
    'b1-rush-hour': ('Yoğun saat', None),
    'b1-speed-limit': ('Hız sınırı', None),
    'b1-fine-penalty': ('Ceza (para cezası)', None),
    'b1-drivers-license': ('Ehliyet', None),
    'b1-to-park': ('Park etmek', None),
    'b1-highway': ('Otoyol', None),
    'b1-lane': ('Şerit', None),
    'b1-roundabout': ('Ada kavşağı', None),
    'b1-toll': ('Geçiş ücreti', None),
    'b1-to-overtake': ('Sollamak', None),
    'b1-seatbelt': ('Emniyet kemeri', None),
    'b1-engine': ('Motor', None),
    'b1-tire': ('Lastik', None),
    'b1-flat-tire': ('Patlak lastik', None),
    'b1-to-tow': ('Çekmek (araç)', None),
    'b1-fuel': ('Yakıt', None),
    'b1-electric-car': ('Elektrikli araba', None),
    'b1-to-give-a-ride': ('Arabayla bırakmak', None),
    'b1-to-hitchhike': ('Otostop çekmek', None),
    'b1-to-miss-the-bus': ('Otobüsü kaçırmak', None),
    'b1-to-catch-the-train': ('Treni yakalamak', None),
    'b1-platform': ('Peron', None),
    'b1-timetable': ('Tarife', None),
    'b1-to-be-delayed': ('Gecikmek', None),
    'b1-to-transfer-change-lines': ('Aktarma yapmak', None),
    'b1-pedestrian': ('Yaya', None),
    'b1-crosswalk': ('Yaya geçidi', None),
    'b1-accident': ('Kaza', None),
    'b1-detour': ('Yol sapması', None),
    'b1-income': ('Gelir', None),
    'b1-expenses': ('Giderler', None),
    'b1-to-invest': ('Yatırım yapmak', None),
    'b1-investment': ('Yatırım', None),
    'b1-savings': ('Birikim', None),
    'b1-pension': ('Emekli maaşı', None),
    'b1-inflation': ('Enflasyon', None),
    'b1-cost-of-living': ('Yaşam maliyeti', None),
    'b1-to-make-ends-meet': ('Geçinip gitmek', None),
    'b1-allowance': ('Harçlık', None),
    'b1-to-waste-money': ('Parayı çarçur etmek', None),
    'b1-to-be-broke': ('Meteliksiz olmak', None),
    'b1-wealthy': ('Zengin (varlıklı)', None),
    'b1-to-pay-back': ('Geri ödemek', None),
    'b1-installment': ('Taksit', None),
    'b1-to-insure': ('Sigortalamak', None),
    'b1-financial': ('Mali (finansal)', None),
    'b1-bank-transfer': ('Banka havalesi', None),
    'b1-fee': ('Ücret (komisyon)', None),
    'b1-to-overspend': ('Fazla harcamak', None),
    'b1-stingy': ('Cimri', None),
    'b1-thrifty': ('Tutumlu', None),
    'b1-cheapskate': ('Pinti', None),
    'b1-profit': ('Kâr', None),
    'b1-loss-financial': ('Zarar', None),
    'b1-receipt-proof': ('Makbuz (fiş)', None),
    'b1-tip-advice': ('Tavsiye', None),
    'b1-to-split-costs': ('Masrafları bölüşmek', None),
    'b1-cash-flow': ('Nakit akışı', None),
    'b1-deal-agreement': ('Anlaşma', None),
    'b1-lecture': ('Ders (üniversite dersi)', None),
    'b1-seminar': ('Seminer', None),
    'b1-essay': ('Deneme (makale ödevi)', None),
    'b1-thesis': ('Tez', None),
    'b1-research': ('Araştırma', None),
    'b1-to-research': ('Araştırmak', None),
    'b1-tutor': ('Özel ders öğretmeni', None),
    'b1-campus': ('Kampüs', None),
    'b1-dormitory': ('Yurt', None),
    'b1-major-field-of-study': ('Bölüm (ana dal)', None),
    'b1-to-major-in': ('-de uzmanlaşmak', None),
    'b1-to-drop-out': ('Okulu bırakmak', None),
    'b1-to-enroll': ('Kayıt olmak', None),
    'b1-tuition': ('Öğrenim ücreti', None),
    'b1-assignment': ('Ödev', None),
    'b1-group-work': ('Grup çalışması', None),
    'b1-to-cheat': ('Kopya çekmek', None),
    'b1-plagiarism': ('İntihal', None),
    'b1-extension-deadline': ('Ek süre', None),
    'b1-to-submit': ('Teslim etmek', None),
    'b1-transcript': ('Not dökümü', None),
    'b1-certificate': ('Sertifika', None),
    'b1-workshop': ('Atölye çalışması', None),
    'b1-internship': ('Staj', None),
    'b1-apprenticeship': ('Çıraklık', None),
    'b1-exchange-program': ('Değişim programı', None),
    'b1-to-study-abroad': ('Yurt dışında okumak', None),
    'b1-curriculum': ('Müfredat', None),
    'b1-professor': ('Profesör', None),
    'b1-grant': ('Burs (hibe)', None),
    'b1-microwave': ('Mikrodalga fırın', None),
    'b1-dishwasher': ('Bulaşık makinesi', None),
    'b1-toaster': ('Tost makinesi', None),
    'b1-kettle': ('Su ısıtıcısı', None),
    'b1-blender': ('Blender', None),
    'b1-hair-dryer': ('Saç kurutma makinesi', None),
    'b1-air-conditioner': ('Klima', None),
    'b1-heater': ('Isıtıcı', None),
    'b1-fan-appliance': ('Vantilatör', None),
    'b1-remote-control': ('Uzaktan kumanda', None),
    'b1-outlet-socket': ('Priz', None),
    'b1-plug': ('Fiş', None),
    'b1-cable': ('Kablo', None),
    'b1-light-bulb': ('Ampul', None),
    'b1-switch': ('Anahtar (elektrik düğmesi)', None),
    'b1-thermostat': ('Termostat', None),
    'b1-smoke-detector': ('Duman dedektörü', None),
    'b1-router': ('Yönlendirici', None),
    'b1-appliance': ('Ev aleti', None),
    'b1-to-plug-in': ('Fişe takmak', None),
    'b1-to-unplug': ('Fişten çekmek', None),
    'b1-to-adjust': ('Ayarlamak', None),
    'b1-to-reset': ('Sıfırlamak', None),
    'b1-tool': ('Alet', None),
    'b1-screwdriver': ('Tornavida', None),
    'b1-hammer': ('Çekiç', None),
    'b1-nail-metal': ('Çivi', None),
    'b1-drill': ('Matkap', None),
    'b1-tape-adhesive': ('Bant (yapışkan)', None),
    'b1-ladder': ('Merdiven (el merdiveni)', None),
    'b1-breeze': ('Meltem', None),
    'b1-drizzle': ('Çisenti', None),
    'b1-downpour': ('Sağanak', None),
    'b1-hail': ('Dolu', None),
    'b1-frost': ('Kırağı', None),
    'b1-ice': ('Buz', None),
    'b1-heatwave': ('Sıcak hava dalgası', None),
    'b1-sunrise': ('Gün doğumu', None),
    'b1-sunset': ('Gün batımı', None),
    'b1-dawn': ('Şafak', None),
    'b1-dusk': ('Alacakaranlık', None),
    'b1-shade': ('Gölge (serinlik)', None),
    'b1-shadow': ('Gölge (siluet)', None),
    'b1-rainbow': ('Gökkuşağı', None),
    'b1-flood': ('Sel', None),
    'b1-drought': ('Kuraklık', None),
    'b1-earthquake': ('Deprem', None),
    'b1-hurricane': ('Kasırga', None),
    'b1-tornado': ('Hortum', None),
    'b1-blizzard': ('Kar fırtınası', None),
    'b1-mild-weather': ('Ilıman (hava)', None),
    'b1-chilly': ('Serin', None),
    'b1-freezing': ('Dondurucu', None),
    'b1-muggy': ('Boğucu (nemli sıcak)', None),
    'b1-clear-sky': ('Açık gökyüzü', None),
    'b1-overcast': ('Kapalı (bulutlu)', None),
    'b1-lightning': ('Şimşek', None),
    'b1-avalanche': ('Çığ', None),
    'b1-wildfire': ('Orman yangını', None),
    'b1-volcano': ('Yanardağ', None),
    'b1-to-comfort': ('Teselli etmek', None),
    'b1-to-reassure': ('Güven vermek', None),
    'b1-to-blame': ('Suçlamak', None),
    'b1-to-praise': ('Övmek', None),
    'b1-compliment': ('İltifat', None),
    'b1-criticism': ('Eleştiri', None),
    'b1-to-criticize': ('Eleştirmek', None),
    'b1-to-tease': ('Takılmak (şakayla)', None),
    'b1-to-bully': ('Zorbalık yapmak', None),
    'b1-to-insult': ('Hakaret etmek', None),
    'b1-to-offend': ('Gücendirmek', None),
    'b1-to-congratulate': ('Tebrik etmek', None),
    'b1-to-greet': ('Selamlamak', None),
    'b1-to-welcome': ('Hoş karşılamak', None),
    'b1-sympathy': ('Sempati (başsağlığı)', None),
    'b1-empathy': ('Empati', None),
    'b1-to-cheer-on': ('Tezahürat yapmak', None),
    'b1-to-show-off': ('Hava atmak', None),
    'b1-to-brag': ('Övünmek', None),
    'b1-to-gossip': ('Dedikodu yapmak', None),
    'b1-rumor': ('Söylenti', None),
    'b1-to-ignore': ('Görmezden gelmek', None),
    'b1-to-interrupt': ('Sözünü kesmek', None),
    'b1-to-nag': ('Dırdır etmek', None),
    'b1-to-persuade': ('İkna etmek', None),
    'b1-to-beg': ('Yalvarmak', None),
    'b1-to-threaten': ('Tehdit etmek', None),
    'b1-to-reject': ('Reddetmek (birini)', None),
    'b1-favor': ('İyilik', None),
    'b1-small-talk': ('Sohbet (gündelik muhabbet)', None),
}
