# -*- coding: utf-8 -*-
LANG = 'de'
WORDS = {
    'a1-hello': ('Hallo', None),
    'a1-goodbye': ('Auf Wiedersehen', None),
    'a1-please': ('Bitte', None),
    'a1-thank-you': ('Danke', None),
    'a1-excuse-me': ('Entschuldigung', None),
    'a1-sorry': ('Tut mir leid', None),
    'a1-yes': ('Ja', None),
    'a1-no': ('Nein', None),
    'a1-my-name-is-alex': ('Ich heiße Alex', None),
    'a1-whats-your-name': ('Wie heißt du?', None),
    'a1-nice-to-meet-you': ('Freut mich', None),
    'a1-how-are-you': ('Wie geht es dir?', None),
    'a1-mother': ('Mutter', None),
    'a1-father': ('Vater', None),
    'a1-sister': ('Schwester', None),
    'a1-brother': ('Bruder', None),
    'a1-friend': ('Freund', None),
    'a1-child': ('Kind', None),
    'a1-today': ('Heute', None),
    'a1-tomorrow': ('Morgen', None),
    'a1-yesterday': ('Gestern', None),
    'a1-now': ('Jetzt', None),
    'a1-morning': ('Vormittag', None),
    'a1-night': ('Nacht', None),
    'a1-house': ('Haus', None),
    'a1-where-is-it': ('Wo ist es?', None),
    'a1-left': ('Links', None),
    'a1-right': ('Rechts', None),
    'a1-store': ('Geschäft', None),
    'a1-bathroom': ('Badezimmer', None),
    'a1-water': ('Wasser', None),
    'a1-bread': ('Brot', None),
    'a1-coffee': ('Kaffee', None),
    'a1-tea': ('Tee', None),
    'a1-delicious': ('Lecker', None),
    'a1-spicy': ('Scharf', None),
    'a1-good-morning': ('Guten Morgen', None),
    'a1-good-evening': ('Guten Abend', None),
    'a1-good-night': ('Gute Nacht', None),
    'a1-youre-welcome': ('Gern geschehen', None),
    'a1-see-you-soon': ('Bis bald', None),
    'a1-see-you-tomorrow': ('Bis morgen', None),
    'a1-welcome': ('Willkommen', None),
    'a1-cheers': ('Prost!', None),
    'a1-congratulations': ('Herzlichen Glückwunsch', None),
    'a1-happy-birthday': ('Alles Gute zum Geburtstag', None),
    'a1-good-luck': ('Viel Glück', None),
    'a1-have-a-nice-day': ('Schönen Tag noch', None),
    'a1-take-care': ('Pass auf dich auf', None),
    'a1-bless-you': ('Gesundheit', None),
    'a1-enjoy-your-meal': ('Guten Appetit', None),
    'a1-nice-to-see-you': ('Schön, dich zu sehen', None),
    'a1-long-time-no-see': ('Lange nicht gesehen', None),
    'a1-goodbye-for-now': ('Bis dann', None),
    'a1-i': ('Ich', None),
    'a1-you': ('Du', None),
    'a1-he': ('Er', None),
    'a1-she': ('Sie', None),
    'a1-we': ('Wir', None),
    'a1-they': ('Sie (Plural)', None),
    'a1-man': ('Mann', None),
    'a1-woman': ('Frau', None),
    'a1-boy': ('Junge', None),
    'a1-girl': ('Mädchen', None),
    'a1-person': ('Person', None),
    'a1-people': ('Leute', None),
    'a1-name': ('Name', None),
    'a1-mister': ('Herr', None),
    'a1-madam': ('Dame', None),
    'a1-im-fine': ('Mir geht es gut', None),
    'a1-and-you': ('Und dir?', None),
    'a1-where-are-you-from': ('Woher kommst du?', None),
    'a1-im-from-the-united-states': ('Ich komme aus den USA', None),
    'a1-friend-female': ('Freundin', None),
    'a1-family': ('Familie', None),
    'a1-parents': ('Eltern', None),
    'a1-son': ('Sohn', None),
    'a1-daughter': ('Tochter', None),
    'a1-husband': ('Ehemann', None),
    'a1-wife': ('Ehefrau', None),
    'a1-grandmother': ('Großmutter', None),
    'a1-grandfather': ('Großvater', None),
    'a1-baby': ('Baby', None),
    'a1-uncle': ('Onkel', None),
    'a1-aunt': ('Tante', None),
    'a1-cousin': ('Cousin', None),
    'a1-boyfriend': ('Fester Freund', None),
    'a1-girlfriend': ('Feste Freundin', None),
    'a1-neighbor': ('Nachbar', None),
    'a1-children': ('Kinder', None),
    'a1-older-brother': ('Älterer Bruder', None),
    'a1-younger-sister': ('Jüngere Schwester', None),
    'a1-pet': ('Haustier', None),
    'a1-married': ('Verheiratet', None),
    'a1-one': ('Eins', None),
    'a1-two': ('Zwei', None),
    'a1-three': ('Drei', None),
    'a1-four': ('Vier', None),
    'a1-five': ('Fünf', None),
    'a1-six': ('Sechs', None),
    'a1-seven': ('Sieben', None),
    'a1-eight': ('Acht', None),
    'a1-nine': ('Neun', None),
    'a1-ten': ('Zehn', None),
    'a1-eleven': ('Elf', None),
    'a1-twelve': ('Zwölf', None),
    'a1-thirteen': ('Dreizehn', None),
    'a1-fourteen': ('Vierzehn', None),
    'a1-fifteen': ('Fünfzehn', None),
    'a1-sixteen': ('Sechzehn', None),
    'a1-seventeen': ('Siebzehn', None),
    'a1-eighteen': ('Achtzehn', None),
    'a1-nineteen': ('Neunzehn', None),
    'a1-twenty': ('Zwanzig', None),
    'a1-zero': ('Null', None),
    'a1-thirty': ('Dreißig', None),
    'a1-forty': ('Vierzig', None),
    'a1-fifty': ('Fünfzig', None),
    'a1-sixty': ('Sechzig', None),
    'a1-seventy': ('Siebzig', None),
    'a1-eighty': ('Achtzig', None),
    'a1-ninety': ('Neunzig', None),
    'a1-one-hundred': ('Hundert', None),
    'a1-one-thousand': ('Tausend', None),
    'a1-one-million': ('Eine Million', None),
    'a1-first': ('Erste', None),
    'a1-second': ('Zweite', None),
    'a1-third': ('Dritte', None),
    'a1-half': ('Hälfte', None),
    'a1-many': ('Viele', None),
    'a1-few': ('Wenige', None),
    'a1-all': ('Alle', None),
    'a1-some': ('Einige', None),
    'a1-nothing': ('Nichts', None),
    'a1-number': ('Zahl', None),
    'a1-more': ('Mehr', None),
    'a1-less': ('Weniger', None),
    'a1-enough': ('Genug', None),
    'a1-red': ('Rot', None),
    'a1-blue': ('Blau', None),
    'a1-green': ('Grün', None),
    'a1-yellow': ('Gelb', None),
    'a1-black': ('Schwarz', None),
    'a1-white': ('Weiß', None),
    'a1-orange-color': ('Orange (Farbe)', None),
    'a1-pink': ('Rosa', None),
    'a1-purple': ('Lila', None),
    'a1-brown': ('Braun', None),
    'a1-gray': ('Grau', None),
    'a1-color': ('Farbe', None),
    'a1-light-color': ('Hell', None),
    'a1-dark': ('Dunkel', None),
    'a1-circle': ('Kreis', None),
    'a1-square': ('Quadrat', None),
    'a1-triangle': ('Dreieck', None),
    'a1-line': ('Linie', None),
    'a1-shape': ('Form', None),
    'a1-big': ('Groß', None),
    'a1-small': ('Klein', None),
    'a1-long': ('Lang', None),
    'a1-short-length': ('Kurz', None),
    'a1-round': ('Rund', None),
    'a1-afternoon': ('Nachmittag', None),
    'a1-evening': ('Abend', None),
    'a1-day': ('Tag', None),
    'a1-week': ('Woche', None),
    'a1-month': ('Monat', None),
    'a1-year': ('Jahr', None),
    'a1-hour': ('Stunde', None),
    'a1-minute': ('Minute', None),
    'a1-later': ('Später', None),
    'a1-early': ('Früh', None),
    'a1-late': ('Spät', None),
    'a1-always': ('Immer', None),
    'a1-never': ('Nie', None),
    'a1-sometimes': ('Manchmal', None),
    'a1-often': ('Oft', None),
    'a1-soon': ('Bald', None),
    'a1-again': ('Wieder', None),
    'a1-its-late': ('Es ist spät', None),
    'a1-tonight': ('Heute Abend', None),
    'a1-before': ('Vorher', None),
    'a1-after': ('Danach', None),
    'a1-noon': ('Mittag', None),
    'a1-midnight': ('Mitternacht', None),
    'a1-monday': ('Montag', None),
    'a1-tuesday': ('Dienstag', None),
    'a1-wednesday': ('Mittwoch', None),
    'a1-thursday': ('Donnerstag', None),
    'a1-friday': ('Freitag', None),
    'a1-saturday': ('Samstag', None),
    'a1-sunday': ('Sonntag', None),
    'a1-weekend': ('Wochenende', None),
    'a1-january': ('Januar', None),
    'a1-february': ('Februar', None),
    'a1-march': ('März', None),
    'a1-april': ('April', None),
    'a1-may': ('Mai', None),
    'a1-june': ('Juni', None),
    'a1-july': ('Juli', None),
    'a1-august': ('August', None),
    'a1-september': ('September', None),
    'a1-october': ('Oktober', None),
    'a1-november': ('November', None),
    'a1-december': ('Dezember', None),
    'a1-spring': ('Frühling', None),
    'a1-summer': ('Sommer', None),
    'a1-autumn': ('Herbst', None),
    'a1-winter': ('Winter', None),
    'a1-birthday': ('Geburtstag', None),
    'a1-holiday': ('Feiertag', None),
    'a1-room': ('Zimmer', None),
    'a1-kitchen': ('Küche', None),
    'a1-bedroom': ('Schlafzimmer', None),
    'a1-door': ('Tür', None),
    'a1-window': ('Fenster', None),
    'a1-table': ('Tisch', None),
    'a1-chair': ('Stuhl', None),
    'a1-bed': ('Bett', None),
    'a1-street': ('Straße', None),
    'a1-city': ('Stadt', None),
    'a1-country': ('Land', None),
    'a1-school': ('Schule', None),
    'a1-hospital': ('Krankenhaus', None),
    'a1-bank': ('Bank', None),
    'a1-restaurant': ('Restaurant', None),
    'a1-hotel': ('Hotel', None),
    'a1-market': ('Markt', None),
    'a1-park': ('Park', None),
    'a1-church': ('Kirche', None),
    'a1-office': ('Büro', None),
    'a1-here': ('Hier', None),
    'a1-there': ('Dort', None),
    'a1-straight-ahead': ('Geradeaus', None),
    'a1-near': ('Nah', None),
    'a1-far': ('Weit', None),
    'a1-floor-level': ('Stockwerk', None),
    'a1-garden': ('Garten', None),
    'a1-wall': ('Wand', None),
    'a1-milk': ('Milch', None),
    'a1-rice': ('Reis', None),
    'a1-meat': ('Fleisch', None),
    'a1-fish-food': ('Fisch (Essen)', None),
    'a1-chicken': ('Hähnchen', None),
    'a1-egg': ('Ei', None),
    'a1-fruit': ('Obst', None),
    'a1-vegetables': ('Gemüse', None),
    'a1-apple': ('Apfel', None),
    'a1-sugar': ('Zucker', None),
    'a1-salt': ('Salz', None),
    'a1-beer': ('Bier', None),
    'a1-wine': ('Wein', None),
    'a1-juice': ('Saft', None),
    'a1-breakfast': ('Frühstück', None),
    'a1-lunch': ('Mittagessen', None),
    'a1-dinner': ('Abendessen', None),
    'a1-im-hungry': ('Ich habe Hunger', None),
    'a1-im-thirsty': ('Ich habe Durst', None),
    'a1-cheese': ('Käse', None),
    'a1-soup': ('Suppe', None),
    'a1-sweet': ('Süß', None),
    'a1-food': ('Nahrung', None),
    'a1-drink-noun': ('Getränk', None),
    'a1-head': ('Kopf', None),
    'a1-hand': ('Hand', None),
    'a1-eye': ('Auge', None),
    'a1-foot': ('Fuß', None),
    'a1-mouth': ('Mund', None),
    'a1-nose': ('Nase', None),
    'a1-ear': ('Ohr', None),
    'a1-arm': ('Arm', None),
    'a1-leg': ('Bein', None),
    'a1-heart': ('Herz', None),
    'a1-hair': ('Haare', None),
    'a1-face': ('Gesicht', None),
    'a1-back-body': ('Rücken', None),
    'a1-stomach': ('Bauch', None),
    'a1-tooth': ('Zahn', None),
    'a1-finger': ('Finger', None),
    'a1-body': ('Körper', None),
    'a1-blood': ('Blut', None),
    'a1-neck': ('Hals', None),
    'a1-shoulder': ('Schulter', None),
    'a1-knee': ('Knie', None),
    'a1-skin': ('Haut', None),
    'a1-shirt': ('Hemd', None),
    'a1-pants': ('Hose', None),
    'a1-shoes': ('Schuhe', None),
    'a1-dress': ('Kleid', None),
    'a1-hat': ('Hut', None),
    'a1-coat': ('Mantel', None),
    'a1-jacket': ('Jacke', None),
    'a1-socks': ('Socken', None),
    'a1-skirt': ('Rock', None),
    'a1-bag': ('Tasche', None),
    'a1-glasses': ('Brille', None),
    'a1-watch-wrist': ('Armbanduhr', None),
    'a1-umbrella': ('Regenschirm', None),
    'a1-to-wear': ('Tragen (Kleidung)', None),
    'a1-sweater': ('Pullover', None),
    'a1-t-shirt': ('T-Shirt', None),
    'a1-scarf': ('Schal', None),
    'a1-gloves': ('Handschuhe', None),
    'a1-clothes': ('Kleidung', None),
    'a1-size': ('Größe', None),
    'a1-to-be': ('Sein', None),
    'a1-to-have': ('Haben', None),
    'a1-to-do': ('Tun', None),
    'a1-to-go': ('Gehen', None),
    'a1-to-come': ('Kommen', None),
    'a1-to-want': ('Wollen', None),
    'a1-to-be-able-to': ('Können', None),
    'a1-to-know': ('Wissen', None),
    'a1-to-see': ('Sehen', None),
    'a1-to-say': ('Sagen', None),
    'a1-to-eat': ('Essen', None),
    'a1-to-drink': ('Trinken', None),
    'a1-to-sleep': ('Schlafen', None),
    'a1-to-live': ('Leben', None),
    'a1-to-work': ('Arbeiten', None),
    'a1-to-speak': ('Sprechen', None),
    'a1-to-understand': ('Verstehen', None),
    'a1-to-like': ('Mögen', None),
    'a1-to-need': ('Brauchen', None),
    'a1-to-give': ('Geben', None),
    'a1-to-take': ('Nehmen', None),
    'a1-to-think': ('Denken', None),
    'a1-to-buy': ('Kaufen', None),
    'a1-to-help': ('Helfen', None),
    'a1-to-open': ('Öffnen', None),
    'a1-to-close': ('Schließen', None),
    'a1-to-look-for': ('Suchen', None),
    'a1-to-find': ('Finden', None),
    'a1-to-wait': ('Warten', None),
    'a1-to-call-phone': ('Anrufen', None),
    'a1-to-read': ('Lesen', None),
    'a1-to-write': ('Schreiben', None),
    'a1-to-listen': ('Hören', None),
    'a1-to-learn': ('Lernen', None),
    'a1-to-play': ('Spielen', None),
    'a1-to-walk': ('Laufen', None),
    'a1-to-run': ('Rennen (laufen)', None),
    'a1-to-sit': ('Sitzen', None),
    'a1-to-stand': ('Stehen', None),
    'a1-to-arrive': ('Ankommen', None),
    'a1-to-leave': ('Verlassen', None),
    'a1-to-return': ('Zurückkehren', None),
    'a1-to-put': ('Legen', None),
    'a1-to-bring': ('Bringen', None),
    'a1-to-ask': ('Fragen', None),
    'a1-to-answer': ('Antworten', None),
    'a1-to-love': ('Lieben', None),
    'a1-to-pay': ('Bezahlen', None),
    'a1-good': ('Gut', None),
    'a1-bad': ('Schlecht', None),
    'a1-new': ('Neu', None),
    'a1-old-thing': ('Alt', None),
    'a1-young': ('Jung', None),
    'a1-hot': ('Heiß', None),
    'a1-cold': ('Kalt', None),
    'a1-happy': ('Glücklich', None),
    'a1-sad': ('Traurig', None),
    'a1-beautiful': ('Schön', None),
    'a1-ugly': ('Hässlich', None),
    'a1-easy': ('Einfach', None),
    'a1-difficult': ('Schwierig', None),
    'a1-fast': ('Schnell', None),
    'a1-slow': ('Langsam', None),
    'a1-cheap': ('Billig', None),
    'a1-expensive': ('Teuer', None),
    'a1-full': ('Voll', None),
    'a1-empty': ('Leer', None),
    'a1-clean': ('Sauber', None),
    'a1-dirty': ('Schmutzig', None),
    'a1-strong': ('Stark', None),
    'a1-weak': ('Schwach', None),
    'a1-important': ('Wichtig', None),
    'a1-what': ('Was', None),
    'a1-who': ('Wer', None),
    'a1-where': ('Wo', None),
    'a1-when': ('Wann', None),
    'a1-why': ('Warum', None),
    'a1-how': ('Wie', None),
    'a1-how-many': ('Wie viele', None),
    'a1-which': ('Welche', None),
    'a1-and': ('Und', None),
    'a1-or': ('Oder', None),
    'a1-but': ('Aber', None),
    'a1-because': ('Weil', None),
    'a1-with': ('Mit', None),
    'a1-without': ('Ohne', None),
    'a1-for': ('Für', None),
    'a1-from': ('Von', None),
    'a1-to-direction': ('Zu', None),
    'a1-in': ('In', None),
    'a1-on': ('Auf', None),
    'a1-under': ('Unter', None),
    'a1-this': ('Dies', None),
    'a1-that': ('Das', None),
    'a1-very': ('Sehr', None),
    'a1-also': ('Auch', None),
    'a1-not': ('Nicht', None),
    'a1-maybe': ('Vielleicht', None),
    'a1-sun': ('Sonne', None),
    'a1-rain': ('Regen', None),
    'a1-snow': ('Schnee', None),
    'a1-wind': ('Wind', None),
    'a1-cloud': ('Wolke', None),
    'a1-weather': ('Wetter', None),
    'a1-sky': ('Himmel', None),
    'a1-sea': ('Meer', None),
    'a1-mountain': ('Berg', None),
    'a1-river': ('Fluss', None),
    'a1-tree': ('Baum', None),
    'a1-flower': ('Blume', None),
    'a1-dog': ('Hund', None),
    'a1-cat': ('Katze', None),
    'a1-bird': ('Vogel', None),
    'a1-fish-animal': ('Fisch (Tier)', None),
    'a1-horse': ('Pferd', None),
    'a1-cow': ('Kuh', None),
    'a1-earth': ('Erde', None),
    'a1-moon': ('Mond', None),
    'a1-star': ('Stern', None),
    'a1-fire': ('Feuer', None),
    'a1-its-windy': ('Es ist windig', None),
    'a1-its-snowing': ('Es schneit', None),
    'a1-its-cold-today': ('Heute ist es kalt', None),
    'a1-its-hot-today': ('Heute ist es heiß', None),
    'a1-help': ('Hilfe!', None),
    'a1-slowly-please': ('Langsam, bitte', None),
    'a1-do-you-speak-english': ('Sprechen Sie Englisch?', None),
    'a1-i-dont-know': ('Ich weiß nicht', None),
    'a1-where-is-the-bathroom': ('Wo ist die Toilette?', None),
    'a1-which-way': ('Welcher Weg?', None),
    'a1-one-moment-please': ('Einen Moment, bitte', None),
    'a1-of-course': ('Natürlich', None),
    'a1-no-problem': ('Kein Problem', None),
    'a1-its-okay': ('Es ist okay', None),
    'a1-lets-go': ('Los geht’s', None),
    'a1-come-in': ('Komm rein', None),
    'a1-be-careful': ('Sei vorsichtig', None),
    'a1-can-you-help-me': ('Kannst du mir helfen?', None),
    'a1-what-does-that-mean': ('Was bedeutet das?', None),
    'a1-can-you-repeat-that': ('Kannst du das wiederholen?', None),
    'a1-slower-please': ('Langsamer, bitte', None),
    'a1-how-do-you-say': ('Wie sagt man…?', None),
    'a1-i-would-like': ('Ich hätte gern…', None),
    'a1-the-bill-please': ('Die Rechnung, bitte', None),
    'a1-im-tired': ('Ich bin müde', None),
    'a1-im-sick': ('Ich bin krank', None),
    'a1-its-an-emergency': ('Es ist ein Notfall', None),
    'a1-call-the-police': ('Rufen Sie die Polizei', None),
    'a1-i-speak-a-little': ('Ich spreche ein bisschen', None),
    'a1-i-love-it': ('Ich liebe es', None),
    'a1-whats-this': ('Was ist das?', None),
    'a1-i-agree': ('Ich stimme zu', None),
    'a1-i-dont-like-it': ('Es gefällt mir nicht', None),
    'a1-really': ('Wirklich?', None),
    'a1-exactly': ('Genau', None),
    'a1-i-think-so': ('Ich glaube schon', None),
    'a1-dont-worry': ('Keine Sorge', None),
    'a1-just-a-little': ('Nur ein bisschen', None),
    'a1-wait-a-moment': ('Warte einen Moment', None),
    'a1-is-this-seat-free': ('Ist dieser Platz frei?', None),
    'a1-money': ('Geld', None),
    'a1-price': ('Preis', None),
    'a1-to-sell': ('Verkaufen', None),
    'a1-card': ('Karte', None),
    'a1-cash': ('Bargeld', None),
    'a1-receipt': ('Quittung', None),
    'a1-open-shop': ('Geöffnet', None),
    'a1-closed-shop': ('Geschlossen', None),
    'a1-free-no-cost': ('Kostenlos', None),
    'a1-discount': ('Rabatt', None),
    'a1-how-much-is-it': ('Wie viel kostet es?', None),
    'a1-too-much': ('Zu viel', None),
    'a1-gift': ('Geschenk', None),
    'a1-change-coins': ('Wechselgeld', None),
    'a1-supermarket': ('Supermarkt', None),
    'a1-pharmacy': ('Apotheke', None),
    'a1-bakery': ('Bäckerei', None),
    'a1-is-this-on-sale': ('Ist das im Angebot?', None),
    'a1-car': ('Auto', None),
    'a1-bus': ('Bus', None),
    'a1-train': ('Zug', None),
    'a1-plane': ('Flugzeug', None),
    'a1-bicycle': ('Fahrrad', None),
    'a1-taxi': ('Taxi', None),
    'a1-ticket': ('Fahrkarte', None),
    'a1-station': ('Bahnhof', None),
    'a1-airport': ('Flughafen', None),
    'a1-road': ('Landstraße', None),
    'a1-to-travel': ('Reisen', None),
    'a1-trip': ('Reise', None),
    'a1-map': ('Landkarte', None),
    'a1-stop-bus-stop': ('Haltestelle', None),
    'a1-to-drive': ('Fahren', None),
    'a1-subway': ('U-Bahn', None),
    'a1-passport': ('Reisepass', None),
    'a1-suitcase': ('Koffer', None),
    'a1-exit': ('Ausgang', None),
    'a1-entrance': ('Eingang', None),
    'a1-phone': ('Telefon', None),
    'a1-book': ('Buch', None),
    'a1-pen': ('Stift', None),
    'a1-paper': ('Papier', None),
    'a1-key': ('Schlüssel', None),
    'a1-computer': ('Computer', None),
    'a1-clock': ('Uhr', None),
    'a1-television': ('Fernseher', None),
    'a1-camera': ('Kamera', None),
    'a1-box': ('Kiste', None),
    'a1-glass-cup': ('Glas', None),
    'a1-bottle': ('Flasche', None),
    'a1-plate': ('Teller', None),
    'a1-knife': ('Messer', None),
    'a1-fork': ('Gabel', None),
    'a1-spoon': ('Löffel', None),
    'a1-cup': ('Tasse', None),
    'a1-soap': ('Seife', None),
    'a1-towel': ('Handtuch', None),
    'a1-lamp': ('Lampe', None),
    'a1-wallet': ('Geldbeutel', None),
    'a1-charger': ('Ladegerät', None),
    'a1-thing': ('Ding', None),
    'a1-toothbrush': ('Zahnbürste', None),
    'a1-angry': ('Wütend', None),
    'a1-scared': ('Ängstlich', None),
    'a1-bored': ('Gelangweilt', None),
    'a1-excited': ('Aufgeregt', None),
    'a1-worried': ('Besorgt', None),
    'a1-surprised': ('Überrascht', None),
    'a1-calm': ('Ruhig', None),
    'a1-nervous': ('Nervös', None),
    'a1-proud': ('Stolz', None),
    'a1-lonely': ('Einsam', None),
    'a1-sleepy': ('Schläfrig', None),
    'a1-sick-unwell': ('Krank', None),
    'a1-love': ('Liebe', None),
    'a1-fear': ('Angst', None),
    'a1-joy': ('Freude', None),
    'a1-funny': ('Lustig', None),
    'a2-i-work-in-an-office': ('Ich arbeite in einem Büro', None),
    'a2-i-am-a-student': ('Ich bin Student', None),
    'a2-i-have-a-meeting': ('Ich habe eine Besprechung', None),
    'a2-i-am-looking-for-a-job': ('Ich suche einen Job', None),
    'a2-i-am-studying': ('Ich studiere', None),
    'a2-i-dont-understand': ('Ich verstehe nicht', None),
    'a2-how-much-is-this': ('Wie viel kostet das?', None),
    'a2-its-too-expensive': ('Es ist zu teuer', None),
    'a2-can-i-pay-by-card': ('Kann ich mit Karte bezahlen?', None),
    'a2-do-you-have-a-discount': ('Haben Sie einen Rabatt?', None),
    'a2-im-just-looking': ('Ich schaue nur', None),
    'a2-ill-take-it': ('Ich nehme es', None),
    'a2-where-is-the-train-station': ('Wo ist der Bahnhof?', None),
    'a2-one-ticket-please': ('Eine Fahrkarte, bitte', None),
    'a2-how-do-i-get-to-the-airport': ('Wie komme ich zum Flughafen?', None),
    'a2-im-lost': ('Ich habe mich verlaufen', None),
    'a2-is-it-far': ('Ist es weit?', None),
    'a2-where-is-the-restroom': ('Wo ist das WC?', None),
    'a2-i-dont-feel-well': ('Ich fühle mich nicht gut', None),
    'a2-i-have-a-headache': ('Ich habe Kopfschmerzen', None),
    'a2-where-is-the-pharmacy': ('Wo ist die Apotheke?', None),
    'a2-i-need-a-doctor': ('Ich brauche einen Arzt', None),
    'a2-im-allergic-to-peanuts': ('Ich bin allergisch gegen Erdnüsse', None),
    'a2-it-hurts-here': ('Es tut hier weh', None),
    'a2-its-sunny': ('Es ist sonnig', None),
    'a2-its-raining': ('Es regnet', None),
    'a2-i-like-to-read': ('Ich lese gern', None),
    'a2-my-favorite-is-music': ('Mein Favorit ist Musik', None),
    'a2-on-weekends-i-rest': ('Am Wochenende ruhe ich mich aus', None),
    'a2-i-play-sports': ('Ich mache Sport', None),
    'a2-what-time-is-it': ('Wie spät ist es?', None),
    'a2-lets-meet-tomorrow': ('Treffen wir uns morgen', None),
    'a2-can-you-call-me': ('Kannst du mich anrufen?', None),
    'a2-see-you-later': ('Bis später', None),
    'a2-whats-your-phone-number': ('Wie ist deine Telefonnummer?', None),
    'a2-im-busy-today': ('Ich bin heute beschäftigt', None),
    'a2-job': ('Job', None),
    'a2-boss': ('Chef', None),
    'a2-colleague': ('Kollege', None),
    'a2-salary': ('Gehalt', None),
    'a2-to-earn': ('Verdienen', None),
    'a2-class': ('Klasse', None),
    'a2-teacher': ('Lehrer', None),
    'a2-exam': ('Prüfung', None),
    'a2-homework': ('Hausaufgaben', None),
    'a2-university': ('Universität', None),
    'a2-to-teach': ('Unterrichten', None),
    'a2-project': ('Projekt', None),
    'a2-deadline': ('Frist', None),
    'a2-interview': ('Vorstellungsgespräch', None),
    'a2-career': ('Karriere', None),
    'a2-break-pause': ('Pause', None),
    'a2-schedule': ('Zeitplan', None),
    'a2-company': ('Firma', None),
    'a2-customer': ('Kunde', None),
    'a2-unemployed': ('Arbeitslos', None),
    'a2-to-try-on': ('Anprobieren', None),
    'a2-fitting-room': ('Umkleidekabine', None),
    'a2-sale-discount-event': ('Ausverkauf', None),
    'a2-to-return-an-item': ('Zurückgeben', None),
    'a2-refund': ('Rückerstattung', None),
    'a2-brand': ('Marke', None),
    'a2-quality': ('Qualität', None),
    'a2-cashier': ('Kassierer', None),
    'a2-shopping-cart': ('Einkaufswagen', None),
    'a2-online-shopping': ('Online-Shopping', None),
    'a2-to-order-online': ('Bestellen', None),
    'a2-delivery': ('Lieferung', None),
    'a2-package': ('Paket', None),
    'a2-to-choose': ('Wählen', None),
    'a2-to-compare': ('Vergleichen', None),
    'a2-it-fits-me': ('Es passt mir', None),
    'a2-too-big': ('Zu groß', None),
    'a2-do-you-have-it-in-another-color': ('Haben Sie es in einer anderen Farbe?', None),
    'a2-mall': ('Einkaufszentrum', None),
    'a2-cheaper': ('Günstiger', None),
    'a2-reservation': ('Reservierung', None),
    'a2-to-book': ('Buchen', None),
    'a2-check-in': ('Check-in', None),
    'a2-luggage': ('Gepäck', None),
    'a2-flight': ('Flug', None),
    'a2-delay': ('Verspätung', None),
    'a2-departure': ('Abfahrt', None),
    'a2-arrival': ('Ankunft', None),
    'a2-gate': ('Flugsteig', None),
    'a2-seat': ('Sitzplatz', None),
    'a2-tourist': ('Tourist', None),
    'a2-guide': ('Reiseführer', None),
    'a2-sightseeing': ('Besichtigung', None),
    'a2-souvenir': ('Souvenir', None),
    'a2-beach': ('Strand', None),
    'a2-museum': ('Museum', None),
    'a2-to-visit': ('Besuchen', None),
    'a2-round-trip': ('Hin- und Rückfahrt', None),
    'a2-one-way': ('Einfache Fahrt', None),
    'a2-abroad': ('Ausland', None),
    'a2-doctor': ('Arzt', None),
    'a2-nurse': ('Krankenschwester', None),
    'a2-medicine': ('Medizin', None),
    'a2-pain': ('Schmerz', None),
    'a2-fever': ('Fieber', None),
    'a2-cough': ('Husten', None),
    'a2-a-cold-illness': ('Erkältung', None),
    'a2-flu': ('Grippe', None),
    'a2-allergy': ('Allergie', None),
    'a2-appointment': ('Termin', None),
    'a2-prescription': ('Rezept (ärztlich)', None),
    'a2-stomachache': ('Bauchschmerzen', None),
    'a2-healthy': ('Gesund', None),
    'a2-to-rest': ('Sich ausruhen', None),
    'a2-insurance': ('Versicherung', None),
    'a2-emergency': ('Notfall', None),
    'a2-dentist': ('Zahnarzt', None),
    'a2-injury': ('Verletzung', None),
    'a2-i-feel-better': ('Ich fühle mich besser', None),
    'a2-blood-pressure': ('Blutdruck', None),
    'a2-hobby': ('Hobby', None),
    'a2-music': ('Musik', None),
    'a2-movie': ('Film', None),
    'a2-sport': ('Sport', None),
    'a2-soccer': ('Fußball', None),
    'a2-to-swim': ('Schwimmen', None),
    'a2-to-dance': ('Tanzen', None),
    'a2-to-sing': ('Singen', None),
    'a2-to-paint': ('Malen', None),
    'a2-game': ('Spiel', None),
    'a2-team': ('Mannschaft', None),
    'a2-to-win': ('Gewinnen', None),
    'a2-to-lose-a-game': ('Verlieren (Spiel)', None),
    'a2-concert': ('Konzert', None),
    'a2-photography': ('Fotografie', None),
    'a2-to-hike': ('Wandern', None),
    'a2-gym': ('Fitnessstudio', None),
    'a2-to-exercise': ('Sport treiben', None),
    'a2-cloudy': ('Bewölkt', None),
    'a2-storm': ('Sturm', None),
    'a2-humid': ('Feucht', None),
    'a2-forecast': ('Vorhersage', None),
    'a2-to-plan': ('Planen', None),
    'a2-to-meet-up': ('Sich treffen', None),
    'a2-invitation': ('Einladung', None),
    'a2-to-invite': ('Einladen', None),
    'a2-to-cancel': ('Absagen', None),
    'a2-free-time': ('Freizeit', None),
    'a2-to-postpone': ('Verschieben', None),
    'a2-internet': ('Internet', None),
    'a2-email': ('E-Mail', None),
    'a2-message': ('Nachricht', None),
    'a2-to-send': ('Senden', None),
    'a2-to-download': ('Herunterladen', None),
    'a2-app': ('App', None),
    'a2-password': ('Passwort', None),
    'a2-screen': ('Bildschirm', None),
    'a2-wi-fi': ('WLAN', None),
    'a2-website': ('Webseite', None),
    'a2-video-call': ('Videoanruf', None),
    'a2-are-you-free-on-saturday': ('Hast du am Samstag Zeit?', None),
    'a2-sounds-good': ('Klingt gut', None),
    'a2-to-clean': ('Putzen', None),
    'a2-to-wash': ('Waschen', None),
    'a2-dishes': ('Geschirr', None),
    'a2-laundry': ('Wäsche', None),
    'a2-to-iron': ('Bügeln', None),
    'a2-trash': ('Müll', None),
    'a2-to-tidy-up': ('Aufräumen', None),
    'a2-vacuum-cleaner': ('Staubsauger', None),
    'a2-to-repair': ('Reparieren', None),
    'a2-to-move-house': ('Umziehen', None),
    'a2-rent': ('Miete', None),
    'a2-landlord': ('Vermieter', None),
    'a2-apartment': ('Wohnung', None),
    'a2-furniture': ('Möbel', None),
    'a2-sofa': ('Sofa', None),
    'a2-fridge': ('Kühlschrank', None),
    'a2-oven': ('Backofen', None),
    'a2-stove': ('Herd', None),
    'a2-shower': ('Dusche', None),
    'a2-mirror': ('Spiegel', None),
    'a2-pillow': ('Kissen', None),
    'a2-blanket': ('Decke', None),
    'a2-washing-machine': ('Waschmaschine', None),
    'a2-roommate': ('Mitbewohner', None),
    'a2-stairs': ('Treppe', None),
    'a2-elevator': ('Aufzug', None),
    'a2-to-wake-up': ('Aufwachen', None),
    'a2-to-get-up': ('Aufstehen', None),
    'a2-to-take-a-shower': ('Duschen', None),
    'a2-to-brush-ones-teeth': ('Sich die Zähne putzen', None),
    'a2-to-get-dressed': ('Sich anziehen', None),
    'a2-to-have-breakfast': ('Frühstücken', None),
    'a2-to-commute': ('Pendeln', None),
    'a2-to-go-home': ('Nach Hause gehen', None),
    'a2-to-relax': ('Entspannen', None),
    'a2-to-watch-tv': ('Fernsehen', None),
    'a2-to-go-to-bed': ('Ins Bett gehen', None),
    'a2-routine': ('Routine', None),
    'a2-habit': ('Gewohnheit', None),
    'a2-alarm-clock': ('Wecker', None),
    'a2-to-be-late': ('Zu spät kommen', None),
    'a2-to-hurry': ('Sich beeilen', None),
    'a2-on-time': ('Pünktlich', None),
    'a2-nap': ('Nickerchen', None),
    'a2-to-take-a-walk': ('Spazieren gehen', None),
    'a2-to-have-lunch': ('Zu Mittag essen', None),
    'a2-to-have-dinner': ('Zu Abend essen', None),
    'a2-to-fall-asleep': ('Einschlafen', None),
    'a2-every-day': ('Jeden Tag', None),
    'a2-usually': ('Normalerweise', None),
    'a2-corner': ('Ecke', None),
    'a2-block': ('Block', None),
    'a2-traffic-light': ('Ampel', None),
    'a2-bridge': ('Brücke', None),
    'a2-square-plaza': ('Platz', None),
    'a2-downtown': ('Innenstadt', None),
    'a2-neighborhood': ('Viertel', None),
    'a2-building': ('Gebäude', None),
    'a2-sidewalk': ('Bürgersteig', None),
    'a2-to-cross': ('Überqueren', None),
    'a2-to-turn': ('Abbiegen', None),
    'a2-address': ('Adresse', None),
    'a2-post-office': ('Post', None),
    'a2-library': ('Bibliothek', None),
    'a2-cinema': ('Kino', None),
    'a2-theater': ('Theater', None),
    'a2-stadium': ('Stadion', None),
    'a2-police-station': ('Polizeistation', None),
    'a2-town-hall': ('Rathaus', None),
    'a2-parking-lot': ('Parkplatz', None),
    'a2-gas-station': ('Tankstelle', None),
    'a2-traffic': ('Verkehr', None),
    'a2-opposite': ('Gegenüber', None),
    'a2-next-to': ('Neben', None),
    'a2-between': ('Zwischen', None),
    'a2-how-do-i-get-to': ('Wie komme ich zu…?', None),
    'a2-menu': ('Speisekarte', None),
    'a2-waiter': ('Kellner', None),
    'a2-dish': ('Gericht', None),
    'a2-dessert': ('Nachtisch', None),
    'a2-starter': ('Vorspeise', None),
    'a2-main-course': ('Hauptgericht', None),
    'a2-vegetarian': ('Vegetarisch', None),
    'a2-tip': ('Trinkgeld', None),
    'a2-to-cook': ('Kochen', None),
    'a2-recipe': ('Rezept (Kochen)', None),
    'a2-ingredient': ('Zutat', None),
    'a2-oil': ('Öl', None),
    'a2-butter': ('Butter', None),
    'a2-pepper': ('Pfeffer', None),
    'a2-onion': ('Zwiebel', None),
    'a2-garlic': ('Knoblauch', None),
    'a2-tomato': ('Tomate', None),
    'a2-potato': ('Kartoffel', None),
    'a2-noodles': ('Nudeln', None),
    'a2-sauce': ('Soße', None),
    'a2-to-bake': ('Backen', None),
    'a2-to-fry': ('Braten', None),
    'a2-to-boil': ('Sieden', None),
    'a2-a-table-for-two': ('Einen Tisch für zwei', None),
    'a2-takeout': ('Zum Mitnehmen', None),
    'a2-snack': ('Snack', None),
    'a2-salty': ('Salzig', None),
    'a2-bitter': ('Bitter', None),
    'a2-tall': ('Großgewachsen', None),
    'a2-short-height': ('Klein (Körpergröße)', None),
    'a2-thin': ('Dünn', None),
    'a2-overweight': ('Übergewichtig', None),
    'a2-blond': ('Blond', None),
    'a2-dark-haired': ('Dunkelhaarig', None),
    'a2-beard': ('Bart', None),
    'a2-kind': ('Gütig', None),
    'a2-nice-person': ('Nett', None),
    'a2-shy': ('Schüchtern', None),
    'a2-talkative': ('Gesprächig', None),
    'a2-smart': ('Klug', None),
    'a2-lazy': ('Faul', None),
    'a2-hardworking': ('Fleißig', None),
    'a2-polite': ('Höflich', None),
    'a2-rude': ('Unhöflich', None),
    'a2-patient': ('Geduldig', None),
    'a2-honest': ('Ehrlich', None),
    'a2-serious': ('Ernst', None),
    'a2-quiet-person': ('Still', None),
    'a2-friendly': ('Freundlich', None),
    'a2-handsome': ('Gutaussehend', None),
    'a2-age': ('Alter', None),
    'a2-old-person': ('Alt (Person)', None),
    'a2-curly-hair': ('Lockiges Haar', None),
    'a2-cheerful': ('Fröhlich', None),
    'a2-stubborn': ('Stur', None),
    'a2-generous': ('Großzügig', None),
    'a2-to-try': ('Versuchen', None),
    'a2-to-start': ('Anfangen', None),
    'a2-to-finish': ('Beenden', None),
    'a2-to-change': ('Ändern', None),
    'a2-to-use': ('Benutzen', None),
    'a2-to-receive': ('Erhalten', None),
    'a2-to-decide': ('Entscheiden', None),
    'a2-to-forget': ('Vergessen', None),
    'a2-to-remember': ('Sich erinnern', None),
    'a2-to-lose-an-object': ('Verlieren (Sache)', None),
    'a2-to-meet-someone-new': ('Kennenlernen', None),
    'a2-to-prefer': ('Bevorzugen', None),
    'a2-to-hope': ('Hoffen', None),
    'a2-to-believe': ('Glauben', None),
    'a2-to-feel': ('Fühlen', None),
    'a2-to-seem': ('Scheinen', None),
    'a2-to-happen': ('Passieren', None),
    'a2-to-stay': ('Bleiben', None),
    'a2-to-spend-money': ('Ausgeben', None),
    'a2-to-show': ('Zeigen', None),
    'a2-to-explain': ('Erklären', None),
    'a2-to-follow': ('Folgen', None),
    'a2-to-keep': ('Behalten', None),
    'a2-to-allow': ('Erlauben', None),
    'a2-to-become': ('Werden', None),
    'a2-to-continue': ('Fortsetzen', None),
    'a2-to-cut': ('Schneiden', None),
    'a2-to-break': ('Zerbrechen', None),
    'a2-to-fly': ('Fliegen', None),
    'a2-to-draw': ('Zeichnen', None),
    'a2-to-carry': ('Tragen (etwas)', None),
    'a2-to-push': ('Schieben', None),
    'a2-to-pull': ('Ziehen', None),
    'a2-to-throw': ('Werfen', None),
    'a2-to-catch': ('Fangen', None),
    'a2-to-build': ('Bauen', None),
    'a2-to-grow': ('Wachsen', None),
    'a2-to-fall': ('Fallen', None),
    'a2-to-climb': ('Klettern', None),
    'a2-to-jump': ('Springen', None),
    'a2-to-laugh': ('Lachen', None),
    'a2-to-cry': ('Weinen', None),
    'a2-to-smile': ('Lächeln', None),
    'a2-to-shout': ('Schreien', None),
    'a2-to-whisper': ('Flüstern', None),
    'a2-to-hug': ('Umarmen', None),
    'a2-to-kiss': ('Küssen', None),
    'a2-to-touch': ('Berühren', None),
    'a2-to-smell': ('Riechen', None),
    'a2-to-taste': ('Probieren', None),
    'a2-to-wash-oneself': ('Sich waschen', None),
    'a2-to-hide': ('Verstecken', None),
    'a2-interesting': ('Interessant', None),
    'a2-boring': ('Langweilig', None),
    'a2-comfortable': ('Bequem', None),
    'a2-dangerous': ('Gefährlich', None),
    'a2-safe': ('Sicher (ungefährlich)', None),
    'a2-noisy': ('Laut', None),
    'a2-busy': ('Beschäftigt', None),
    'a2-heavy': ('Schwer', None),
    'a2-light-weight': ('Leicht', None),
    'a2-wide': ('Breit', None),
    'a2-narrow': ('Eng', None),
    'a2-soft': ('Weich', None),
    'a2-hard-firm': ('Hart', None),
    'a2-wet': ('Nass', None),
    'a2-dry': ('Trocken', None),
    'a2-rich': ('Reich', None),
    'a2-poor': ('Arm (bedürftig)', None),
    'a2-famous': ('Berühmt', None),
    'a2-popular': ('Beliebt', None),
    'a2-modern': ('Modern', None),
    'a2-traditional': ('Traditionell', None),
    'a2-ready': ('Bereit', None),
    'a2-sure': ('Sicher (gewiss)', None),
    'a2-wrong': ('Falsch', None),
    'a2-correct': ('Richtig', None),
    'a2-strange': ('Seltsam', None),
    'a2-same': ('Gleich', None),
    'a2-different': ('Unterschiedlich', None),
    'a2-last-week': ('Letzte Woche', None),
    'a2-next-week': ('Nächste Woche', None),
    'a2-this-month': ('Diesen Monat', None),
    'a2-last-year': ('Letztes Jahr', None),
    'a2-next-year': ('Nächstes Jahr', None),
    'a2-at-the-end': ('Am Ende', None),
    'a2-at-the-beginning': ('Am Anfang', None),
    'a2-twice': ('Zweimal', None),
    'a2-once': ('Einmal', None),
    'a2-in-a-hurry': ('In Eile', None),
    'a2-for-a-long-time': ('Lange Zeit', None),
    'a2-recently': ('Kürzlich', None),
    'a2-already': ('Schon', None),
    'a2-still': ('Noch', None),
    'a2-not-yet': ('Noch nicht', None),
    'a2-until': ('Bis', None),
    'a2-since': ('Seit', None),
    'a2-during': ('Während', None),
    'a2-ago': ('Vor', None),
    'a2-at-least': ('Mindestens', None),
    'a2-right-away': ('Sofort', None),
    'a2-finally': ('Endlich', None),
    'a2-suddenly': ('Plötzlich', None),
    'a2-the-day-after-tomorrow': ('Übermorgen', None),
    'a2-conversation': ('Gespräch', None),
    'a2-question': ('Frage', None),
    'a2-answer-noun': ('Antwort', None),
    'a2-opinion': ('Meinung', None),
    'a2-to-describe': ('Beschreiben', None),
    'a2-to-promise': ('Versprechen', None),
    'a2-to-suggest': ('Vorschlagen', None),
    'a2-to-complain': ('Sich beschweren', None),
    'a2-to-apologize': ('Sich entschuldigen', None),
    'a2-to-thank': ('Danken', None),
    'a2-joke': ('Witz', None),
    'a2-story': ('Geschichte (Erzählung)', None),
    'a2-news': ('Nachrichten', None),
    'a2-to-argue': ('Streiten', None),
    'a2-to-discuss': ('Diskutieren', None),
    'a2-secret': ('Geheimnis', None),
    'a2-to-mean': ('Bedeuten', None),
    'a2-to-pronounce': ('Aussprechen', None),
    'a2-to-translate': ('Übersetzen', None),
    'a2-word': ('Wort', None),
    'a2-sentence': ('Satz', None),
    'a2-language': ('Sprache', None),
    'a2-to-spell': ('Buchstabieren', None),
    'a2-to-lie': ('Lügen', None),
    'a2-truth': ('Wahrheit', None),
    'a2-to-chat': ('Plaudern', None),
    'a2-accent': ('Akzent', None),
    'a2-fluent': ('Fließend', None),
    'a2-to-get-married': ('Heiraten', None),
    'a2-wedding': ('Hochzeit', None),
    'a2-couple': ('Paar (Liebespaar)', None),
    'a2-childhood': ('Kindheit', None),
    'a2-teenager': ('Teenager', None),
    'a2-adult': ('Erwachsener', None),
    'a2-to-grow-up': ('Aufwachsen', None),
    'a2-anniversary': ('Jahrestag', None),
    'a2-party': ('Party', None),
    'a2-guest': ('Gast', None),
    'a2-to-celebrate': ('Feiern', None),
    'a2-to-be-born': ('Geboren werden', None),
    'a2-to-die': ('Sterben', None),
    'a2-relatives': ('Verwandte', None),
    'a2-twins': ('Zwillinge', None),
    'a2-only-child': ('Einzelkind', None),
    'a2-to-take-care-of': ('Sich kümmern um', None),
    'a2-nephew': ('Neffe', None),
    'a2-niece': ('Nichte', None),
    'a2-grandchild': ('Enkelkind', None),
    'a2-single': ('Single', None),
    'a2-divorced': ('Geschieden', None),
    'a2-christmas': ('Weihnachten', None),
    'a2-new-year': ('Neujahr', None),
    'a2-cake': ('Kuchen', None),
    'a2-candle': ('Kerze', None),
    'a2-lesson': ('Lektion', None),
    'a2-course': ('Kurs', None),
    'a2-to-practice': ('Üben', None),
    'a2-mistake': ('Fehler', None),
    'a2-to-correct': ('Korrigieren', None),
    'a2-grade-mark': ('Note', None),
    'a2-to-pass-an-exam': ('Bestehen', None),
    'a2-to-fail-an-exam': ('Durchfallen', None),
    'a2-to-graduate': ('Absolvieren', None),
    'a2-degree': ('Abschluss', None),
    'a2-subject': ('Fach', None),
    'a2-math': ('Mathe', None),
    'a2-history': ('Geschichte (Fach)', None),
    'a2-science': ('Wissenschaft', None),
    'a2-art': ('Kunst', None),
    'a2-dictionary': ('Wörterbuch', None),
    'a2-notebook': ('Heft', None),
    'a2-to-memorize': ('Auswendig lernen', None),
    'a2-to-review': ('Wiederholen', None),
    'a2-classroom': ('Klassenzimmer', None),
    'a2-semester': ('Semester', None),
    'a2-scholarship': ('Stipendium', None),
    'a2-to-register': ('Sich anmelden', None),
    'a2-example': ('Beispiel', None),
    'a2-level': ('Niveau', None),
    'a2-beginner': ('Anfänger', None),
    'a2-to-save-money': ('Sparen', None),
    'a2-bank-account': ('Bankkonto', None),
    'a2-to-withdraw': ('Abheben', None),
    'a2-to-deposit': ('Einzahlen', None),
    'a2-atm': ('Geldautomat', None),
    'a2-loan': ('Kredit', None),
    'a2-debt': ('Schulden', None),
    'a2-to-borrow': ('Borgen', None),
    'a2-to-lend': ('Leihen', None),
    'a2-to-owe': ('Schuldig sein', None),
    'a2-tax': ('Steuer', None),
    'a2-bill-utility': ('Rechnung (Nebenkosten)', None),
    'a2-budget': ('Budget', None),
    'a2-to-afford': ('Sich leisten', None),
    'a2-interest-bank': ('Zinsen', None),
    'a2-coin': ('Münze', None),
    'a2-to-exchange-money': ('Wechseln', None),
    'a2-exchange-rate': ('Wechselkurs', None),
    'a2-credit-card': ('Kreditkarte', None),
    'a2-to-cost': ('Kosten', None),
    'a2-salary-raise': ('Gehaltserhöhung', None),
    'a2-expensive-habit': ('Teure Angewohnheit', None),
    'a2-invoice': ('Rechnung (geschäftlich)', None),
    'a2-payment': ('Zahlung', None),
    'a2-to-miss-someone': ('Vermissen', None),
    'a2-to-worry': ('Sich sorgen', None),
    'a2-to-enjoy': ('Genießen', None),
    'a2-to-hate': ('Hassen', None),
    'a2-to-be-afraid-of': ('Angst haben vor', None),
    'a2-ashamed': ('Beschämt', None),
    'a2-jealous': ('Eifersüchtig', None),
    'a2-embarrassed': ('Verlegen', None),
    'a2-disappointed': ('Enttäuscht', None),
    'a2-grateful': ('Dankbar', None),
    'a2-relieved': ('Erleichtert', None),
    'a2-confused': ('Verwirrt', None),
    'a2-curious': ('Neugierig', None),
    'a2-hopeful': ('Hoffnungsvoll', None),
    'a2-frustrated': ('Frustriert', None),
    'a2-stressed': ('Gestresst', None),
    'a2-in-a-good-mood': ('Gut gelaunt', None),
    'a2-in-a-bad-mood': ('Schlecht gelaunt', None),
    'a2-to-cheer-up': ('Aufmuntern', None),
    'a2-to-calm-down': ('Sich beruhigen', None),
    'a2-to-get-angry': ('Wütend werden', None),
    'a2-to-fall-in-love': ('Sich verlieben', None),
    'a2-mood': ('Laune', None),
    'a2-satisfied': ('Zufrieden', None),
    'a2-forest': ('Wald', None),
    'a2-lake': ('See', None),
    'a2-island': ('Insel', None),
    'a2-desert': ('Wüste', None),
    'a2-field': ('Feld', None),
    'a2-farm': ('Bauernhof', None),
    'a2-animal': ('Tier', None),
    'a2-insect': ('Insekt', None),
    'a2-mosquito': ('Mücke', None),
    'a2-bee': ('Biene', None),
    'a2-butterfly': ('Schmetterling', None),
    'a2-snake': ('Schlange', None),
    'a2-lion': ('Löwe', None),
    'a2-elephant': ('Elefant', None),
    'a2-monkey': ('Affe', None),
    'a2-rabbit': ('Kaninchen', None),
    'a2-pig': ('Schwein', None),
    'a2-sheep': ('Schaf', None),
    'a2-plant': ('Pflanze', None),
    'a2-grass': ('Gras', None),
    'a2-leaf': ('Blatt', None),
    'a2-rock': ('Felsen', None),
    'a2-sand': ('Sand', None),
    'a2-ocean': ('Ozean', None),
    'a2-wave': ('Welle', None),
    'a2-thunder': ('Donner', None),
    'a2-fog': ('Nebel', None),
    'a2-temperature': ('Temperatur', None),
    'a2-laptop': ('Laptop', None),
    'a2-keyboard': ('Tastatur', None),
    'a2-printer': ('Drucker', None),
    'a2-file': ('Datei', None),
    'a2-folder': ('Ordner', None),
    'a2-to-print': ('Drucken', None),
    'a2-to-click': ('Klicken', None),
    'a2-to-type': ('Tippen', None),
    'a2-to-search-online': ('Online suchen', None),
    'a2-social-media': ('Soziale Medien', None),
    'a2-to-post': ('Posten', None),
    'a2-to-share': ('Teilen', None),
    'a2-video': ('Video', None),
    'a2-photo': ('Foto', None),
    'a2-selfie': ('Selfie', None),
    'a2-headphones': ('Kopfhörer', None),
    'a2-speaker': ('Lautsprecher', None),
    'a2-battery': ('Akku', None),
    'a2-to-turn-on': ('Einschalten', None),
    'a2-to-turn-off': ('Ausschalten', None),
    'a2-volume': ('Lautstärke', None),
    'a2-channel': ('Kanal', None),
    'a2-podcast': ('Podcast', None),
    'a2-screenshot': ('Screenshot', None),
    'a2-update': ('Update', None),
    'a2-notification': ('Benachrichtigung', None),
    'a2-to-log-in': ('Sich einloggen', None),
    'a2-subtitles': ('Untertitel', None),
    'a2-what-do-you-think': ('Was denkst du?', None),
    'a2-it-depends': ('Es kommt darauf an', None),
    'a2-im-not-sure': ('Ich bin nicht sicher', None),
    'a2-let-me-think': ('Lass mich nachdenken', None),
    'a2-what-a-pity': ('Wie schade', None),
    'a2-never-mind': ('Macht nichts', None),
    'a2-hurry-up': ('Beeil dich', None),
    'a2-watch-out': ('Pass auf!', None),
    'a2-thats-a-good-idea': ('Das ist eine gute Idee', None),
    'a2-are-you-kidding': ('Machst du Witze?', None),
    'a2-its-up-to-you': ('Das liegt an dir', None),
    'a2-im-on-my-way': ('Ich bin unterwegs', None),
    'a2-same-here': ('Gleichfalls', None),
    'a2-me-neither': ('Ich auch nicht', None),
    'a2-by-the-way': ('Übrigens', None),
    'a2-in-my-opinion': ('Meiner Meinung nach', None),
    'a2-to-be-honest': ('Ehrlich gesagt', None),
    'a2-actually': ('Eigentlich', None),
    'a2-anyway': ('Sowieso', None),
    'a2-for-example': ('Zum Beispiel', None),
    'a2-sorry-im-late': ('Entschuldigung für die Verspätung', None),
    'a2-no-way': ('Auf keinen Fall!', None),
    'a2-that-makes-sense': ('Das ergibt Sinn', None),
    'a2-good-point': ('Guter Punkt', None),
    'a2-banana': ('Banane', None),
    'a2-orange-fruit': ('Orange (Frucht)', None),
    'a2-grapes': ('Trauben', None),
    'a2-strawberry': ('Erdbeere', None),
    'a2-lemon': ('Zitrone', None),
    'a2-watermelon': ('Wassermelone', None),
    'a2-peach': ('Pfirsich', None),
    'a2-pear': ('Birne', None),
    'a2-carrot': ('Karotte', None),
    'a2-lettuce': ('Salat', None),
    'a2-cucumber': ('Gurke', None),
    'a2-bell-pepper': ('Paprika', None),
    'a2-mushroom': ('Pilz', None),
    'a2-corn': ('Mais', None),
    'a2-beans': ('Bohnen', None),
    'a2-spinach': ('Spinat', None),
    'a2-cabbage': ('Kohl', None),
    'a2-pumpkin': ('Kürbis', None),
    'a2-nuts': ('Nüsse', None),
    'a2-coconut': ('Kokosnuss', None),
    'a2-mango': ('Mango', None),
    'a2-pineapple': ('Ananas', None),
    'a2-cherry': ('Kirsche', None),
    'a2-avocado': ('Avocado', None),
    'a2-ripe': ('Reif', None),
    'a2-fresh': ('Frisch', None),
    'a2-kilogram': ('Kilogramm', None),
    'a2-gram': ('Gramm', None),
    'a2-liter': ('Liter', None),
    'a2-meter': ('Meter', None),
    'a2-kilometer': ('Kilometer', None),
    'a2-centimeter': ('Zentimeter', None),
    'a2-piece': ('Stück', None),
    'a2-slice': ('Scheibe', None),
    'a2-dozen': ('Dutzend', None),
    'a2-pair': ('Paar (zwei Stück)', None),
    'a2-percent': ('Prozent', None),
    'a2-degree-temperature': ('Grad', None),
    'a2-a-bit': ('Ein bisschen', None),
    'a2-a-lot': ('Viel', None),
    'a2-several': ('Mehrere', None),
    'a2-double': ('Doppelt', None),
    'a2-weight': ('Gewicht', None),
    'a2-height': ('Höhe', None),
    'a2-length': ('Länge', None),
    'a2-distance': ('Entfernung', None),
    'a2-speed': ('Geschwindigkeit', None),
    'a2-total': ('Gesamt', None),
    'a2-almost': ('Fast', None),
    'a2-only': ('Nur', None),
    'a2-engineer': ('Ingenieur', None),
    'a2-lawyer': ('Anwalt', None),
    'a2-chef': ('Koch', None),
    'a2-driver': ('Fahrer', None),
    'a2-farmer': ('Landwirt', None),
    'a2-artist': ('Künstler', None),
    'a2-musician': ('Musiker', None),
    'a2-actor': ('Schauspieler', None),
    'a2-writer': ('Schriftsteller', None),
    'a2-journalist': ('Journalist', None),
    'a2-police-officer': ('Polizist', None),
    'a2-firefighter': ('Feuerwehrmann', None),
    'a2-scientist': ('Wissenschaftler', None),
    'a2-programmer': ('Programmierer', None),
    'a2-designer': ('Designer', None),
    'a2-manager': ('Manager', None),
    'a2-salesperson': ('Verkäufer', None),
    'a2-mechanic': ('Mechaniker', None),
    'a2-electrician': ('Elektriker', None),
    'a2-plumber': ('Klempner', None),
    'a2-pilot': ('Pilot', None),
    'a2-accountant': ('Buchhalter', None),
    'a2-architect': ('Architekt', None),
    'a2-hairdresser': ('Friseur', None),
    'a2-soldier': ('Soldat', None),
    'a2-baker': ('Bäcker', None),
    'a2-basketball': ('Basketball', None),
    'a2-tennis': ('Tennis', None),
    'a2-baseball': ('Baseball', None),
    'a2-volleyball': ('Volleyball', None),
    'a2-running': ('Joggen', None),
    'a2-cycling': ('Radfahren', None),
    'a2-skiing': ('Skifahren', None),
    'a2-surfing': ('Surfen', None),
    'a2-yoga': ('Yoga', None),
    'a2-chess': ('Schach', None),
    'a2-cards-game': ('Karten', None),
    'a2-board-game': ('Brettspiel', None),
    'a2-video-game': ('Videospiel', None),
    'a2-puzzle': ('Puzzle', None),
    'a2-to-go-camping': ('Zelten gehen', None),
    'a2-picnic': ('Picknick', None),
    'a2-fishing': ('Angeln', None),
    'a2-race': ('Rennen (Wettbewerb)', None),
    'a2-competition': ('Wettbewerb', None),
    'a2-referee': ('Schiedsrichter', None),
    'a2-coach': ('Trainer', None),
    'a2-medal': ('Medaille', None),
    'a2-score': ('Punktzahl', None),
    'a2-fan-supporter': ('Fan', None),
    'a2-to-train': ('Trainieren', None),
}
