# -*- coding: utf-8 -*-
LANG = 'ar'

GRAMMAR = [
    {"id": "g-ar1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "كان يا ما ___، في قديم الزمان ملك له ثلاث بنات.", "correct": "كان",
     "options": ["كان", "يكون", "كانت", "سيكون"],
     "romaji": {"كان": "kaan", "يكون": "yakuun", "كانت": "kaanat", "سيكون": "sayakuun"},
     "note": "The classic fairy-tale opener doubles \"kaan\" (was) — كان يا ما كان is fixed storytelling formula, like \"once upon a time.\""},
    {"id": "g-ar2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "بعدما ___ الطعام، خرجنا نتمشى.", "correct": "أكلنا",
     "options": ["أكلنا", "نأكل", "سنأكل", "يأكلون"],
     "romaji": {"أكلنا": "akalnaa", "نأكل": "na'kul", "سنأكل": "sana'kul", "يأكلون": "ya'kuluun"},
     "note": "بعدما + past tense (أكلنا) marks the completed action before the following past-tense clause (خرجنا) — normal narrative sequencing."},
    {"id": "g-ar3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "لو كان عندي وقت أكثر، ___ إلى اليابان.", "correct": "لسافرت",
     "options": ["لسافرت", "أسافر", "سأسافر", "أسافرُ"],
     "romaji": {"لسافرت": "lasaafartu", "أسافر": "usaafiru", "سأسافر": "sa'usaafiru", "أسافرُ": "usaafiru"},
     "note": "Unreal past condition: لو + past verb (كان) pairs with ل + past verb (لسافرت) in the result clause — never a future form."},
    {"id": "g-ar4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "___ تدرس، تنجح في الامتحان.", "correct": "إن",
     "options": ["إن", "لو", "لأن", "لكن"],
     "romaji": {"إن": "in", "لو": "law", "لأن": "li'anna", "لكن": "laakin"},
     "note": "إن introduces a real, likely-to-happen conditional (\"if you study, you'll pass\"); لو is reserved for unreal or hypothetical conditions."},
    {"id": "g-ar5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "اشتريت سيارة ___.", "correct": "حمراء",
     "options": ["حمراء", "أحمر", "حمر", "حمراوان"],
     "romaji": {"حمراء": "hamraa'", "أحمر": "ahmar", "حمر": "humr", "حمراوان": "hamraawaan"},
     "note": "سيارة is feminine, so the color adjective takes the feminine pattern حمراء (not the masculine أحمر)."},
    {"id": "g-ar6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "المقهى يقع ___ الزاوية.", "correct": "عند",
     "options": ["عند", "في", "على", "من"],
     "romaji": {"عند": "'inda", "في": "fii", "على": "'alaa", "من": "min"},
     "note": "عند الزاوية (\"at the corner\") is the fixed preposition for this location; في or على would sound off in this everyday phrase."},
]

IDIOMS = [
    {"id": "i-ar1", "tier": "C1", "topic": "idiom-character",
     "phrase": "رأسه ناشف", "romaji": "raasu naashif",
     "correct": "to be stubborn as a mule",
     "options": ["to be stubborn as a mule", "to be a quick learner", "to be generous with money", "to be easily frightened"],
     "note": "Literally \"his head is dry (hard)\"; used for someone who won't budge once their mind is made up."},
    {"id": "i-ar2", "tier": "C1", "topic": "idiom-character",
     "phrase": "قلبه أبيض", "romaji": "qalbuh abyad",
     "correct": "to have a kind, good-hearted nature",
     "options": ["to have a kind, good-hearted nature", "to be heartbroken", "to be cold and calculating", "to fall in love easily"],
     "note": "Literally \"his heart is white\"; praises someone's fundamentally good, generous character."},
    {"id": "i-ar3", "tier": "C1", "topic": "idiom-character",
     "phrase": "له إيد في كل حتة", "romaji": "luh iid fii kull hitta",
     "correct": "to be a jack-of-all-trades who has a hand in everything",
     "options": ["to be a jack-of-all-trades who has a hand in everything", "to be shy and withdrawn", "to be highly disciplined", "to be a slow, methodical worker"],
     "note": "Literally \"he has a hand in every place\"; describes a restless busybody involved in every project going."},
    {"id": "i-ar4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "لا تكبر الموضوع", "romaji": "laa tkabbir al-mawdoo'",
     "correct": "to not overreact and keep things in proportion",
     "options": ["to not overreact and keep things in proportion", "to attend a religious service", "to move somewhere quiet", "to settle an old dispute"],
     "note": "Literally \"don't enlarge the topic\"; a plea not to blow a small matter out of proportion."},
    {"id": "i-ar5", "tier": "C1", "topic": "idiom-media",
     "phrase": "دقّ الطبول لكل الناس", "romaji": "daqqa at-tuboul li-kull an-naas",
     "correct": "to broadcast something loudly to everyone",
     "options": ["to broadcast something loudly to everyone", "to keep something a closely guarded secret", "to forget about something entirely", "to write something down carefully"],
     "note": "Literally \"to beat the drums for everyone\"; used when someone makes sure news reaches as many people as possible."},
    {"id": "i-ar6", "tier": "C1", "topic": "idiom-media",
     "phrase": "يقرأ ما بين السطور", "romaji": "yaqra' maa bayn as-sutuur",
     "correct": "to read between the lines",
     "options": ["to read between the lines", "to skim without understanding", "to quote something word for word", "to translate literally"],
     "note": "Literally \"he reads what is between the lines\"; used for picking up an implied meaning in an article, speech, or report."},
]

NUANCE = [
    {"id": "n-ar1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Asking a stranger on the street for directions politely",
     "correct": "لو سمحت، هل يمكنني أن أسألك عن الطريق؟",
     "options": ["لو سمحت، هل يمكنني أن أسألك عن الطريق؟", "وين الطريق؟", "دلّني عالطريق", "فين الشارع ده؟"],
     "romaji": {"لو سمحت، هل يمكنني أن أسألك عن الطريق؟": "law samaht, hal yumkinunii an as'alak 'an at-tariiq?",
                "وين الطريق؟": "wayn at-tariiq?", "دلّني عالطريق": "dallinii 'a-t-tariiq", "فين الشارع ده؟": "feen ash-shaari' dah?"},
     "note": "لو سمحت (\"if you would permit\") plus the formal question frame is the polite register with strangers; the others are blunt regional colloquialisms."},
    {"id": "n-ar2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Opening a formal letter to a government office",
     "correct": "تحية طيبة وبعد،",
     "options": ["تحية طيبة وبعد،", "يا هلا", "إزيك", "شلونك"],
     "romaji": {"تحية طيبة وبعد،": "tahiyyatan tayyibatan wa ba'd,", "يا هلا": "yaa hala", "إزيك": "izzayyak", "شلونك": "shlonak"},
     "note": "تحية طيبة وبعد (\"warm greetings, and thereafter\") is the standard formal-letter opener across Modern Standard Arabic; the rest are spoken greetings."},
    {"id": "n-ar3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Describing a policy change that is temporary, not permanent",
     "correct": "مؤقت",
     "options": ["مؤقت", "دائم", "نهائي", "أبدي"],
     "romaji": {"مؤقت": "mu'aqqat", "دائم": "daa'im", "نهائي": "nihaa'ii", "أبدي": "abadii"},
     "note": "مؤقت precisely means \"temporary\"; the distractors all describe permanence, the opposite nuance a precise report needs to avoid."},
    {"id": "n-ar4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Reporting that a claim is probable but not yet confirmed",
     "correct": "مرجّح",
     "options": ["مرجّح", "مؤكد", "مستحيل", "ثابت"],
     "romaji": {"مرجّح": "murajjah", "مؤكد": "mu'akkad", "مستحيل": "mustahiil", "ثابت": "thaabit"},
     "note": "مرجّح (\"likely, probable\") signals a careful hedge; مؤكد and ثابت overstate certainty the writer does not have."},
    {"id": "n-ar5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend a movie was amazing (casual)",
     "correct": "كان تحفة",
     "options": ["كان تحفة", "كان رائعاً للغاية", "كان مُرضياً", "بدا لائقاً"],
     "romaji": {"كان تحفة": "kaan tuhfa", "كان رائعاً للغاية": "kaan raa'i'an lil-ghaaya", "كان مُرضياً": "kaan murdiyan", "بدا لائقاً": "badaa laa'iqan"},
     "note": "تحفة / جامد / خرافي are the street superlatives for \"amazing\"; the other options sound like a written review."},
    {"id": "n-ar6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Asking a colleague informally if they finished the report",
     "correct": "خلصت التقرير؟",
     "options": ["خلصت التقرير؟", "هل أنجزت إعداد التقرير؟", "هل تفضلتم بإتمام التقرير؟", "أرجو الإفادة عن حالة التقرير"],
     "romaji": {"خلصت التقرير؟": "khallast at-taqriir?", "هل أنجزت إعداد التقرير؟": "hal anjazta i'daad at-taqriir?",
                "هل تفضلتم بإتمام التقرير؟": "hal tafaddaltum bi-itmaam at-taqriir?", "أرجو الإفادة عن حالة التقرير": "arjuu al-ifaada 'an haalat at-taqriir"},
     "note": "خلصت is the everyday colloquial \"did you finish\"; the alternatives escalate into bureaucratic MSA a coworker would never use casually."},
    {"id": "n-ar7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Softly disagreeing with your boss in a meeting",
     "correct": "لست متأكداً أن هذا هو الخيار الأفضل",
     "options": ["لست متأكداً أن هذا هو الخيار الأفضل", "هذا كلام فارغ", "أنت مخطئ", "هذا غير منطقي إطلاقاً"],
     "romaji": {"لست متأكداً أن هذا هو الخيار الأفضل": "lastu muta'akkidan anna haadhaa huwa al-khiyaar al-afdal",
                "هذا كلام فارغ": "haadhaa kalaam faarigh", "أنت مخطئ": "anta mukhti'", "هذا غير منطقي إطلاقاً": "haadhaa ghayr mantiqii itlaaqan"},
     "note": "\"لست متأكداً أن\" (I'm not sure that) is the diplomatic hedge; the other options are blunt enough to embarrass a boss."},
    {"id": "n-ar8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Sarcastic reply when a friend says they'll \"definitely\" pay you back tomorrow",
     "correct": "أكيد أكيد، زي المرة اللي فاتت",
     "options": ["أكيد أكيد، زي المرة اللي فاتت", "ممتاز، شكراً لك", "أنا واثق منك", "لا مشكلة أبداً"],
     "romaji": {"أكيد أكيد، زي المرة اللي فاتت": "akiid akiid, zayy al-marra illi faatat",
                "ممتاز، شكراً لك": "mumtaaz, shukran lak", "أنا واثق منك": "anaa waathiq minak", "لا مشكلة أبداً": "laa mushkila abadan"},
     "note": "Doubling \"أكيد أكيد\" plus \"just like last time\" signals dry sarcasm; the other options read as sincere agreement."},
]
