# -*- coding: utf-8 -*-
LANG = 'nl'
WORDS = {
    'c1-broadcast': ('Uitzending', None),
    'c1-coverage': ('Berichtgeving', None),
    'c1-correspondent': ('Correspondent', None),
    'c1-anchor-news': ('Nieuwsanker', None),
    'c1-editorial': ('Hoofdredactioneel commentaar', None),
    'c1-slant-bias': ('Kleuring (vooringenomenheid)', None),
    'c1-to-leak': ('Uitlekken', None),
    'c1-source-journalism': ('Bron', None),
    'c1-whistleblower': ('Klokkenluider', None),
    'c1-censorship': ('Censuur', None),
    'c1-propaganda': ('Propaganda', None),
    'c1-misinformation': ('Desinformatie', None),
    'c1-fact-check': ('Feitencheck', None),
    'c1-viral': ('Viraal', None),
    'c1-clickbait': ('Clickbait', None),
    'c1-tabloid': ('Roddelblad', None),
    'c1-press-conference': ('Persconferentie', None),
    'c1-press-release': ('Persbericht', None),
    'c1-exclusive-story': ('Primeur', None),
    'c1-breaking-news': ('Laatste nieuws', None),
    'c1-viewership': ('Kijkerspubliek', None),
    'c1-subscriber': ('Abonnee', None),
    'c1-paywall': ('Betaalmuur', None),
    'c1-influencer': ('Influencer', None),
    'c1-to-trend': ('Trending zijn', None),
    'c1-hashtag': ('Hashtag', None),
    'c1-op-ed': ('Opiniestuk', None),
    'c1-byline': ('Naamsvermelding (auteur)', None),
    'c1-segment-tv': ('Segment (tv)', None),
    'c1-airtime': ('Zendtijd', None),
    'c1-methodology': ('Methodologie', None),
    'c1-empirical': ('Empirisch', None),
    'c1-qualitative': ('Kwalitatief', None),
    'c1-quantitative': ('Kwantitatief', None),
    'c1-variable': ('Variabele', None),
    'c1-correlation': ('Correlatie', None),
    'c1-causation': ('Causaliteit', None),
    'c1-sample-study': ('Steekproef', None),
    'c1-peer-review': ('Collegiale toetsing', None),
    'c1-citation': ('Citaat (verwijzing)', None),
    'c1-abstract-summary': ('Samenvatting (abstract)', None),
    'c1-dissertation': ('Proefschrift', None),
    'c1-scholar': ('Geleerde', None),
    'c1-discipline-field': ('Discipline (vakgebied)', None),
    'c1-paradigm': ('Paradigma', None),
    'c1-phenomenon': ('Fenomeen', None),
    'c1-premise': ('Premisse', None),
    'c1-inference': ('Gevolgtrekking', None),
    'c1-to-infer': ('Afleiden', None),
    'c1-to-deduce': ('Deduceren', None),
    'c1-rigorous': ('Rigoureus', None),
    'c1-nuanced': ('Genuanceerd', None),
    'c1-to-synthesize': ('Synthetiseren', None),
    'c1-critique': ('Kritische analyse', None),
    'c1-discourse': ('Discours', None),
    'c1-hierarchy': ('Hiërarchie', None),
    'c1-paradox': ('Paradox', None),
    'c1-theoretical': ('Theoretisch', None),
    'c1-findings': ('Bevindingen', None),
    'c1-assumption': ('Aanname', None),
    'c1-to-back-up-support': ('Onderbouwen (steunen)', None),
    'c1-to-bring-up-mention': ('Ter sprake brengen', None),
    'c1-to-call-off': ('Afgelasten', None),
    'c1-to-carry-on': ('Doorgaan', None),
    'c1-to-check-out-look-at': ('Bekijken', None),
    'c1-to-come-across': ('Tegenkomen', None),
    'c1-to-cut-down-on': ('Minderen met', None),
    'c1-to-do-without': ('Het stellen zonder', None),
    'c1-to-fall-apart': ('Uiteenvallen', None),
    'c1-to-fall-behind': ('Achterop raken', None),
    'c1-to-get-away-with': ('Ermee wegkomen', None),
    'c1-to-get-by': ('Zich redden', None),
    'c1-to-get-over': ('Te boven komen', None),
    'c1-to-give-in': ('Toegeven', None),
    'c1-to-go-through-experience': ('Doormaken', None),
    'c1-to-hold-on': ('Volhouden (wachten)', None),
    'c1-to-keep-up-with': ('Bijhouden', None),
    'c1-to-let-down': ('Teleurstellen', None),
    'c1-to-look-into': ('Onderzoeken', None),
    'c1-to-look-up-to': ('Opkijken naar', None),
    'c1-to-make-up-for': ('Goedmaken', None),
    'c1-to-pass-out': ('Flauwvallen', None),
    'c1-to-point-out': ('Erop wijzen', None),
    'c1-to-put-up-with': ('Verdragen', None),
    'c1-to-run-into': ('Tegen het lijf lopen', None),
    'c1-to-set-up': ('Opzetten', None),
    'c1-to-sort-out': ('Uitzoeken (regelen)', None),
    'c1-to-stand-for': ('Staan voor', None),
    'c1-to-take-after': ('Aardigen naar', None),
    'c1-to-take-over': ('Overnemen', None),
    'c1-to-turn-down': ('Afwijzen', None),
    'c1-to-turn-up': ('Opdagen', None),
    'c1-to-work-out-resolve': ('Zich oplossen', None),
    'c1-to-wear-off': ('Uitwerken (verdwijnen)', None),
    'c1-to-wind-up-end-up': ('Uiteindelijk belanden', None),
    'c1-to-break-off': ('Verbreken', None),
    'c1-to-brush-up-on': ('Opfrissen', None),
    'c1-to-catch-on': ('Ingang vinden (populair worden)', None),
    'c1-to-come-down-with': ('Oplopen (een ziekte)', None),
    'c1-to-crack-down-on': ('Hard optreden tegen', None),
    'c1-to-dwell-on': ('Blijven hangen bij', None),
    'c1-to-fall-through': ('Niet doorgaan', None),
    'c1-to-get-across': ('Overbrengen (duidelijk maken)', None),
    'c1-to-hold-back': ('Inhouden', None),
    'c1-to-iron-out': ('Gladstrijken', None),
    'c1-to-live-up-to': ('Waarmaken', None),
    'c1-to-narrow-down': ('Beperken (tot een selectie)', None),
    'c1-to-opt-out': ('Zich terugtrekken', None),
    'c1-to-phase-out': ('Geleidelijk afschaffen', None),
    'c1-to-pull-off': ('Voor elkaar krijgen', None),
    'c1-to-rule-out': ('Uitsluiten', None),
    'c1-to-settle-for': ('Genoegen nemen met', None),
    'c1-to-stick-to': ('Zich houden aan', None),
    'c1-to-take-on-a-task': ('Op zich nemen', None),
    'c1-to-touch-on': ('Aanstippen', None),
    'c1-to-weigh-up': ('Afwegen', None),
    'c1-to-wrap-up': ('Afronden', None),
    'c1-to-zero-in-on': ('Zich richten op', None),
    'c1-to-fend-off': ('Afweren', None),
    'c1-to-stem-from': ('Voortkomen uit', None),
    'c1-awesome': ('Te gek', None),
    'c1-gross': ('Vies (walgelijk)', None),
    'c1-lame': ('Waardeloos (saai)', None),
    'c1-cheesy': ('Cheesy', None),
    'c1-to-chill': ('Chillen', None),
    'c1-dude': ('Gozer', None),
    'c1-to-ditch': ('Dumpen (achterlaten)', None),
    'c1-to-bail-leave': ('Ervandoor gaan', None),
    'c1-to-crash-sleep': ('Pitten', None),
    'c1-to-freak-out': ('Doordraaien', None),
    'c1-to-nail-it': ('Het helemaal goed doen', None),
    'c1-to-screw-up': ('Verkloten', None),
    'c1-a-bummer': ('Een afknapper', None),
    'c1-no-biggie': ('Geen probleem', None),
    'c1-to-be-into': ('Fan zijn van', None),
    'c1-hooked': ('Verslaafd (gehooked)', None),
    'c1-hype': ('Hype', None),
    'c1-sketchy': ('Louche', None),
    'c1-legit': ('Legit (echt)', None),
    'c1-a-rip-off': ('Een afzetterij', None),
    'c1-to-ghost': ('Ghosten', None),
    'c1-cringe': ('Gênant', None),
    'c1-to-wing-it': ('Improviseren', None),
    'c1-to-zone-out': ('Wegzakken (afdwalen)', None),
    'c1-to-kick-back': ('Achteroverleunen', None),
    'c1-for-real': ('Serieus (echt waar)', None),
    'c1-buddy': ('Maatje', None),
    'c1-to-hit-the-road': ('Vertrekken', None),
    'c1-to-grab-get': ('Pakken (bemachtigen)', None),
    'c1-sweet-great': ('Vet (geweldig)', None),
    'c1-eloquent': ('Welbespraakt', None),
    'c1-poignant': ('Aangrijpend', None),
    'c1-vivid': ('Levendig', None),
    'c1-lucid': ('Helder (lucide)', None),
    'c1-sublime': ('Verheven (subliem)', None),
    'c1-exquisite': ('Voortreffelijk', None),
    'c1-serene': ('Sereen', None),
    'c1-somber': ('Somber', None),
    'c1-bleak': ('Troosteloos', None),
    'c1-grim': ('Grimmig', None),
    'c1-austere': ('Sober (streng)', None),
    'c1-opulent': ('Weelderig', None),
    'c1-lavish': ('Overvloedig', None),
    'c1-meager': ('Karig', None),
    'c1-scarce': ('Schaars', None),
    'c1-abundant': ('Overvloedig', None),
    'c1-pristine': ('Ongerept', None),
    'c1-dilapidated': ('Vervallen', None),
    'c1-quaint': ('Pittoresk (ouderwets charmant)', None),
    'c1-picturesque': ('Schilderachtig', None),
    'c1-ominous': ('Onheilspellend', None),
    'c1-eerie': ('Griezelig', None),
    'c1-uncanny': ('Bevreemdend', None),
    'c1-whimsical': ('Grillig (speels)', None),
    'c1-wistful': ('Weemoedig', None),
    'c1-fleeting': ('Vluchtig', None),
    'c1-enduring': ('Blijvend', None),
    'c1-ubiquitous': ('Alomtegenwoordig', None),
    'c1-elusive': ('Ongrijpbaar', None),
    'c1-tangible': ('Tastbaar', None),
    'c1-meticulous': ('Nauwgezet', None),
    'c1-conscientious': ('Consciëntieus', None),
    'c1-diligent': ('Ijverig', None),
    'c1-pragmatic': ('Pragmatisch', None),
    'c1-cynical': ('Cynisch', None),
    'c1-skeptical': ('Sceptisch', None),
    'c1-gullible': ('Goedgelovig', None),
    'c1-smug': ('Zelfingenomen', None),
    'c1-aloof': ('Afstandelijk', None),
    'c1-candid': ('Openhartig', None),
    'c1-tactless': ('Tactloos', None),
    'c1-assertive': ('Assertief', None),
    'c1-submissive': ('Onderdanig', None),
    'c1-vindictive': ('Wraakzuchtig', None),
    'c1-magnanimous': ('Grootmoedig', None),
    'c1-benevolent': ('Welwillend', None),
    'c1-malicious': ('Kwaadaardig', None),
    'c1-frugal': ('Zuinig', None),
    'c1-extravagant': ('Buitensporig (verkwistend)', None),
    'c1-impulsive': ('Impulsief', None),
    'c1-spontaneous': ('Spontaan', None),
    'c1-calculating': ('Berekenend', None),
    'c1-eccentric': ('Excentriek', None),
    'c1-unconventional': ('Onconventioneel', None),
    'c1-sophisticated': ('Verfijnd', None),
    'c1-witty': ('Geestig', None),
    'c1-sarcastic': ('Sarcastisch', None),
    'c1-charismatic': ('Charismatisch', None),
    'c1-condescending': ('Neerbuigend', None),
    'c1-pretentious': ('Pretentieus', None),
    'c1-empire': ('Rijk (imperium)', None),
    'c1-colony': ('Kolonie', None),
    'c1-revolution': ('Revolutie', None),
    'c1-uprising': ('Opstand', None),
    'c1-dictatorship': ('Dictatuur', None),
    'c1-democracy': ('Democratie', None),
    'c1-monarchy': ('Monarchie', None),
    'c1-republic': ('Republiek', None),
    'c1-regime': ('Regime', None),
    'c1-treaty': ('Verdrag', None),
    'c1-alliance': ('Bondgenootschap', None),
    'c1-invasion': ('Invasie', None),
    'c1-occupation-military': ('Bezetting', None),
    'c1-independence': ('Onafhankelijkheid', None),
    'c1-sovereignty': ('Soevereiniteit', None),
    'c1-civil-war': ('Burgeroorlog', None),
    'c1-ceasefire': ('Staakt-het-vuren', None),
    'c1-refugee': ('Vluchteling', None),
    'c1-asylum': ('Asiel', None),
    'c1-exile': ('Ballingschap', None),
    'c1-dynasty': ('Dynastie', None),
    'c1-heir': ('Erfgenaam', None),
    'c1-coup': ('Staatsgreep', None),
    'c1-sanctions': ('Sancties', None),
    'c1-diplomacy': ('Diplomatie', None),
    'c1-ambassador': ('Ambassadeur', None),
    'c1-embassy': ('Ambassade', None),
    'c1-summit-meeting': ('Topontmoeting', None),
    'c1-constitution': ('Grondwet', None),
    'c1-amendment': ('Amendement', None),
    'c1-bottom-line': ('De essentie (het eindresultaat)', None),
    'c1-ballpark-figure': ('Ruwe schatting', None),
    'c1-to-touch-base': ('Contact opnemen', None),
    'c1-to-circle-back': ('Later terugkomen op', None),
    'c1-bandwidth-capacity': ('Capaciteit (tijd)', None),
    'c1-to-leverage': ('Benutten', None),
    'c1-synergy': ('Synergie', None),
    'c1-to-scale-up': ('Opschalen', None),
    'c1-to-pivot': ('Van koers veranderen', None),
    'c1-to-onboard': ('Inwerken', None),
    'c1-to-roll-out': ('Uitrollen', None),
    'c1-to-ramp-up': ('Opvoeren', None),
    'c1-to-wind-down': ('Afbouwen', None),
    'c1-to-cut-corners': ('Bochten afsnijden (slordig werken)', None),
    'c1-red-tape': ('Bureaucratie', None),
    'c1-to-go-the-extra-mile': ('Een stap extra zetten', None),
    'c1-on-the-same-page': ('Op één lijn zitten', None),
    'c1-to-keep-in-the-loop': ('Op de hoogte houden', None),
    'c1-to-drop-the-ball': ('Een steek laten vallen', None),
    'c1-to-think-outside-the-box': ('Buiten de gebaande paden denken', None),
    'c1-win-win': ('Win-winsituatie', None),
    'c1-game-changer': ('Kentering (doorbraak)', None),
    'c1-low-hanging-fruit': ('Makkelijke winst', None),
    'c1-deliverable': ('Op te leveren product', None),
    'c1-return-on-investment': ('Rendement op investering', None),
    'c1-to-sign-off-on': ('Goedkeuren', None),
    'c1-to-run-something-by-someone': ('Iets voorleggen aan iemand', None),
    'c1-stakeholder-buy-in': ('Instemming van belanghebbenden', None),
    'c1-back-to-the-drawing-board': ('Terug naar de tekentafel', None),
    'c1-take-it-offline': ('Het apart bespreken', None),
    'c1-over-the-moon': ('Dolgelukkig', None),
    'c1-down-in-the-dumps': ('In de put', None),
    'c1-on-edge': ('Nerveus (op scherp)', None),
    'c1-fed-up': ('Beu', None),
    'c1-at-a-loss': ('Met de handen in het haar', None),
    'c1-in-two-minds': ('Weifelend', None),
    'c1-under-the-weather': ('Niet lekker in zijn vel', None),
    'c1-taken-aback': ('Overrompeld', None),
    'c1-blown-away': ('Ondersteboven (van bewondering)', None),
    'c1-torn-between': ('Verscheurd (tussen)', None),
    'c1-beside-oneself': ('Buiten zichzelf', None),
    'c1-heartbroken': ('Gebroken hart', None),
    'c1-on-the-fence': ('Nog geen keuze gemaakt', None),
    'c1-laid-back': ('Relaxed', None),
    'c1-uptight': ('Gespannen (stijf)', None),
    'c1-sick-and-tired': ('Meer dan beu', None),
    'c1-in-a-rut': ('In een sleur', None),
    'c1-head-over-heels': ('Smoorverliefd', None),
    'c1-cold-feet': ('Plankenkoorts (op het laatste moment)', None),
    'c1-second-thoughts': ('Twijfels achteraf', None),
    'c1-a-weight-off-my-shoulders': ('Een last van mijn schouders', None),
    'c1-butterflies-in-my-stomach': ('Vlinders in mijn buik', None),
    'c1-a-lump-in-my-throat': ('Een brok in mijn keel', None),
    'c1-goosebumps': ('Kippenvel', None),
    'c1-speechless-with-joy': ('Sprakeloos van vreugde', None),
    'c1-out-of-sorts': ('Niet in orde (uit balans)', None),
    'c1-keyed-up': ('Opgefokt (gespannen)', None),
    'c1-wound-up': ('Opgewonden (van streek)', None),
    'c1-mixed-feelings': ('Gemengde gevoelens', None),
    'c1-at-peace': ('In vrede', None),
    'c1-bureaucracy': ('Bureaucratie', None),
    'c1-paperwork': ('Papierwerk', None),
    'c1-to-file-documents': ('Indienen (documenten)', None),
    'c1-applicant': ('Aanvrager', None),
    'c1-eligible': ('In aanmerking komend', None),
    'c1-to-qualify': ('Voldoen aan de voorwaarden', None),
    'c1-prerequisite': ('Vereiste (voorwaarde)', None),
    'c1-clause': ('Clausule', None),
    'c1-compliance': ('Naleving', None),
    'c1-regulation': ('Regelgeving', None),
    'c1-license-permit': ('Vergunning', None),
    'c1-to-authorize': ('Machtigen', None),
    'c1-notary': ('Notaris', None),
    'c1-affidavit': ('Beëdigde verklaring', None),
    'c1-deed': ('Akte', None),
    'c1-title-property': ('Eigendomstitel', None),
    'c1-lien': ('Pandrecht', None),
    'c1-easement': ('Erfdienstbaarheid', None),
    'c1-appraisal': ('Taxatie', None),
    'c1-closing-real-estate': ('Notariële overdracht', None),
    'c1-escrow': ('Derdenrekening (borgsom)', None),
    'c1-commission-fee': ('Commissie', None),
    'c1-listing-property': ('Woningaanbieding', None),
    'c1-counteroffer': ('Tegenbod', None),
    'c1-contingency': ('Ontbindende voorwaarde', None),
    'c1-zoning-variance': ('Bestemmingsplanafwijking', None),
    'c1-deadline-filing': ('Indieningstermijn', None),
    'c1-certified-copy': ('Gewaarmerkte kopie', None),
    'c1-jurisdiction': ('Rechtsgebied', None),
    'c1-liability': ('Aansprakelijkheid', None),
    'c1-galaxy': ('Melkwegstelsel', None),
    'c1-universe': ('Heelal', None),
    'c1-black-hole': ('Zwart gat', None),
    'c1-telescope': ('Telescoop', None),
    'c1-asteroid': ('Asteroïde', None),
    'c1-eclipse': ('Eclips', None),
    'c1-constellation': ('Sterrenbeeld', None),
    'c1-particle': ('Deeltje', None),
    'c1-radiation': ('Straling', None),
    'c1-electron': ('Elektron', None),
    'c1-isotope': ('Isotoop', None),
    'c1-nuclear-fusion': ('Kernfusie', None),
    'c1-magnetic-field': ('Magnetisch veld', None),
    'c1-friction': ('Wrijving', None),
    'c1-velocity': ('Snelheid (vector)', None),
    'c1-acceleration': ('Versnelling', None),
    'c1-momentum': ('Impuls (bewegingshoeveelheid)', None),
    'c1-inertia': ('Traagheid', None),
    'c1-density': ('Dichtheid', None),
    'c1-pressure-physics': ('Druk', None),
    'c1-vacuum': ('Vacuüm', None),
    'c1-wavelength': ('Golflengte', None),
    'c1-frequency-physics': ('Frequentie', None),
    'c1-spectrum': ('Spectrum', None),
    'c1-photosynthesis': ('Fotosynthese', None),
    'c1-enzyme': ('Enzym', None),
    'c1-hormone': ('Hormoon', None),
    'c1-metabolism': ('Metabolisme', None),
    'c1-mutation': ('Mutatie', None),
    'c1-organism': ('Organisme', None),
    'c1-to-allege': ('Beweren', None),
    'c1-to-allude': ('Zinspelen op', None),
    'c1-to-ascertain': ('Vaststellen (nagaan)', None),
    'c1-to-bolster': ('Versterken (schragen)', None),
    'c1-to-circumvent': ('Omzeilen', None),
    'c1-to-coerce': ('Dwingen', None),
    'c1-to-condone': ('Door de vingers zien', None),
    'c1-to-consolidate': ('Consolideren', None),
    'c1-to-curb': ('Beteugelen', None),
    'c1-to-deter': ('Afschrikken', None),
    'c1-to-diminish': ('Verminderen', None),
    'c1-to-disclose': ('Openbaren (onthullen)', None),
    'c1-to-disrupt': ('Verstoren', None),
    'c1-to-divert': ('Omleiden', None),
    'c1-to-elicit': ('Ontlokken', None),
    'c1-to-endorse': ('Onderschrijven (goedkeuren)', None),
    'c1-to-entail': ('Met zich meebrengen', None),
    'c1-to-eradicate': ('Uitroeien', None),
    'c1-to-exacerbate': ('Verergeren', None),
    'c1-to-exemplify': ('Illustreren (als voorbeeld dienen)', None),
    'c1-to-foster': ('Bevorderen', None),
    'c1-to-hinder': ('Belemmeren', None),
    'c1-to-impede': ('Hinderen', None),
    'c1-to-instigate': ('Aanstichten', None),
    'c1-to-mitigate': ('Verzachten (matigen)', None),
    'c1-to-nurture': ('Koesteren', None),
    'c1-to-omit': ('Weglaten', None),
    'c1-to-precede': ('Voorafgaan aan', None),
    'c1-to-preclude': ('Uitsluiten (voorkomen)', None),
    'c1-to-prompt': ('Aanzetten tot', None),
    'c1-to-refrain': ('Zich onthouden', None),
    'c1-to-relinquish': ('Afstand doen van', None),
    'c1-to-render': ('Doen worden (maken tot)', None),
    'c1-to-scrutinize': ('Nauwkeurig onderzoeken', None),
    'c1-to-stipulate': ('Bepalen (als voorwaarde stellen)', None),
    'c1-to-substantiate': ('Staven', None),
    'c1-to-thrive': ('Gedijen', None),
    'c1-to-undermine': ('Ondermijnen', None),
    'c1-to-uphold': ('Handhaven', None),
    'c1-to-waive': ('Afzien van (een recht)', None),
    'c1-to-yield': ('Opleveren', None),
    'c1-to-abolish': ('Afschaffen', None),
    'c1-to-accommodate': ('Tegemoetkomen (plaats bieden aan)', None),
    'c1-to-adhere': ('Zich houden aan', None),
    'c1-to-attain': ('Bereiken', None),
    'c1-to-compel': ('Dwingen', None),
    'c1-to-confine': ('Opsluiten (beperken)', None),
    'c1-to-contemplate': ('Overwegen', None),
    'c1-to-depict': ('Uitbeelden', None),
    'c1-to-dispel': ('Wegnemen (verdrijven)', None),
    'c1-to-embody': ('Belichamen', None),
    'c1-to-evoke': ('Oproepen (evoceren)', None),
    'c1-to-forge': ('Smeden', None),
    'c1-to-grasp': ('Begrijpen (vatten)', None),
    'c1-to-infringe': ('Inbreuk maken op', None),
    'c1-to-overturn': ('Herroepen (omverwerpen)', None),
    'c1-to-plead': ('Pleiten (smeken)', None),
    'c1-to-reconcile-ideas': ('Verzoenen', None),
    'c1-to-surpass': ('Overtreffen', None),
    'c1-to-unveil': ('Onthullen', None),
    'c1-albeit': ('Hoewel', None),
    'c1-notwithstanding': ('Niettegenstaande', None),
    'c1-insofar-as': ('Voor zover', None),
    'c1-whereby': ('Waardoor (waarmee)', None),
    'c1-hereby': ('Hierbij', None),
    'c1-thereby': ('Daarmee (daardoor)', None),
    'c1-hence': ('Vandaar', None),
    'c1-thus': ('Aldus', None),
    'c1-henceforth': ('Voortaan', None),
    'c1-likewise': ('Evenzo', None),
    'c1-conversely': ('Omgekeerd', None),
    'c1-namely': ('Namelijk', None),
    'c1-in-lieu-of': ('In plaats van', None),
    'c1-in-light-of': ('In het licht van', None),
    'c1-in-view-of': ('Gezien (met het oog op)', None),
    'c1-by-virtue-of': ('Krachtens', None),
    'c1-on-account-of': ('Vanwege', None),
    'c1-with-a-view-to': ('Met het oog op', None),
    'c1-provided-that': ('Mits', None),
    'c1-granted': ('Toegegeven', None),
    'c1-admittedly': ('Weliswaar', None),
    'c1-arguably': ('Wellicht (aantoonbaar)', None),
    'c1-presumably': ('Vermoedelijk', None),
    'c1-allegedly': ('Naar verluidt (zogenaamd)', None),
    'c1-ostensibly': ('Ogenschijnlijk', None),
    'c1-undoubtedly': ('Ongetwijfeld', None),
    'c1-invariably': ('Onveranderlijk', None),
    'c1-nevertheless-formal': ('Niettemin', None),
    'c1-to-the-extent-that': ('In die mate dat', None),
    'c1-for-all-intents-and-purposes': ('In feite (praktisch gezien)', None),
    'c1-sommelier': ('Sommelier', None),
    'c1-vintage-wine': ('Jaargang (wijn)', None),
    'c1-aroma': ('Aroma', None),
    'c1-palate': ('Gehemelte (smaak)', None),
    'c1-aftertaste': ('Nasmaak', None),
    'c1-full-bodied': ('Volle smaak', None),
    'c1-dry-wine': ('Droog (wijn)', None),
    'c1-sparkling': ('Mousserend', None),
    'c1-brew': ('Brouwsel (aftreksel)', None),
    'c1-roast-coffee': ('Branding (koffie)', None),
    'c1-espresso': ('Espresso', None),
    'c1-decaf': ('Cafeïnevrij', None),
    'c1-barista': ('Barista', None),
    'c1-tasting-menu': ('Proeverijmenu', None),
    'c1-pairing': ('Combinatie (spijs-wijn)', None),
    'c1-a-la-carte': ('À la carte', None),
    'c1-garnish': ('Garnering', None),
    'c1-drizzle-of-oil': ('Scheutje (olie)', None),
    'c1-reduction-sauce': ('Reductie (saus)', None),
    'c1-glaze': ('Glazuur', None),
    'c1-umami': ('Umami', None),
    'c1-zest': ('Rasp (citrus)', None),
    'c1-to-caramelize': ('Karamelliseren', None),
    'c1-to-braise': ('Smoren', None),
    'c1-to-poach': ('Pocheren', None),
    'c1-al-dente': ('Al dente', None),
    'c1-medium-rare': ('Medium rare', None),
    'c1-well-done': ('Doorbakken', None),
    'c1-signature-dish': ('Kenmerkend gerecht', None),
    'c1-chefs-recommendation': ('Aanbeveling van de chef', None),
    'c1-floor-plan': ('Plattegrond', None),
    'c1-open-plan': ('Open indeling', None),
    'c1-layout': ('Indeling', None),
    'c1-fixture': ('Vast onderdeel', None),
    'c1-cabinetry': ('Kastenwand', None),
    'c1-countertop': ('Werkblad', None),
    'c1-backsplash': ('Spatwand', None),
    'c1-grout': ('Voegmiddel', None),
    'c1-hardwood-floor': ('Houten vloer', None),
    'c1-laminate': ('Laminaat', None),
    'c1-molding-trim': ('Lijstwerk', None),
    'c1-baseboard': ('Plint', None),
    'c1-crown-molding': ('Kroonlijst', None),
    'c1-sconce': ('Wandlamp', None),
    'c1-pendant-light': ('Hanglamp', None),
    'c1-recessed-lighting': ('Inbouwverlichting', None),
    'c1-dimmer': ('Dimmer', None),
    'c1-vent': ('Ventilatierooster', None),
    'c1-duct': ('Luchtkanaal', None),
    'c1-hvac': ('Klimaatbeheersing', None),
    'c1-sump-pump': ('Vuilwaterpomp', None),
    'c1-water-heater': ('Boiler', None),
    'c1-circuit-breaker': ('Stroomonderbreker', None),
    'c1-load-bearing-wall': ('Dragende muur', None),
    'c1-joist': ('Balk', None),
    'c1-stud-wall': ('Stijl (wandconstructie)', None),
    'c1-subfloor': ('Onderlaag (vloer)', None),
    'c1-caulk': ('Kit (afdichtmiddel)', None),
    'c1-primer-paint': ('Grondverf', None),
    'c1-punch-list': ('Opleveringslijst', None),
    'c1-change-order': ('Wijzigingsopdracht', None),
    'c1-scope-of-work': ('Werkomvang', None),
    'c1-rapport': ('Goede verstandhouding', None),
    'c1-chemistry-between-people': ('Chemie (tussen mensen)', None),
    'c1-affinity': ('Affiniteit', None),
    'c1-estranged': ('Vervreemd', None),
    'c1-reconciliation': ('Verzoening', None),
    'c1-to-confide': ('Toevertrouwen', None),
    'c1-confidant': ('Vertrouweling', None),
    'c1-to-fall-out': ('Ruzie krijgen', None),
    'c1-to-patch-things-up': ('Het weer goedmaken', None),
    'c1-to-drift-apart': ('Uit elkaar groeien', None),
    'c1-to-hit-it-off': ('Het meteen goed kunnen vinden', None),
    'c1-to-have-a-soft-spot-for': ('Een zwak hebben voor', None),
    'c1-to-hold-a-grudge': ('Wrok koesteren', None),
    'c1-to-bury-the-hatchet': ('De strijdbijl begraven', None),
    'c1-to-make-amends': ('Het goedmaken', None),
    'c1-to-take-for-granted': ('Als vanzelfsprekend beschouwen', None),
    'c1-to-lean-on': ('Steunen op', None),
    'c1-to-stick-up-for': ('Opkomen voor', None),
    'c1-to-look-out-for': ('Waken over', None),
    'c1-to-see-eye-to-eye': ('Het roerend eens zijn', None),
    'c1-to-get-on-someones-nerves': ('Op iemands zenuwen werken', None),
    'c1-to-give-the-benefit-of-the-doubt': ('Het voordeel van de twijfel geven', None),
    'c1-to-read-between-the-lines': ('Tussen de regels lezen', None),
    'c1-to-beat-around-the-bush': ('Om de hete brij heen draaien', None),
    'c1-to-get-to-the-point': ('Ter zake komen', None),
    'c1-to-keep-someone-at-arms-length': ('Op afstand houden', None),
    'c1-to-go-behind-someones-back': ('Achter iemands rug om handelen', None),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('Zijn hart op de tong dragen', None),
    'c1-tactfully': ('Tactvol', None),
    'c1-passive-aggressive': ('Passief-agressief', None),
    'c1-mediocre': ('Middelmatig', None),
    'c1-subpar': ('Ondermaats', None),
    'c1-top-notch': ('Uitstekend', None),
    'c1-first-rate': ('Eersteklas', None),
    'c1-second-rate': ('Tweederangs', None),
    'c1-state-of-the-art': ('Modernst', None),
    'c1-cutting-edge': ('Baanbrekend', None),
    'c1-run-of-the-mill': ('Alledaags', None),
    'c1-exceptional': ('Uitzonderlijk', None),
    'c1-flawless': ('Foutloos', None),
    'c1-impeccable': ('Onberispelijk', None),
    'c1-shoddy': ('Prutswerk (van slechte kwaliteit)', None),
    'c1-sloppy': ('Slordig', None),
    'c1-half-baked': ('Onuitgewerkt', None),
    'c1-polished': ('Gepolijst (verfijnd)', None),
    'c1-crude': ('Grof', None),
    'c1-rudimentary': ('Rudimentair', None),
    'c1-intricate': ('Ingewikkeld', None),
    'c1-convoluted': ('Omslachtig', None),
    'c1-user-friendly': ('Gebruiksvriendelijk', None),
    'c1-foolproof': ('Onfeilbaar', None),
    'c1-robust': ('Robuust', None),
    'c1-seamless': ('Naadloos', None),
    'c1-glitchy': ('Storingsgevoelig', None),
    'c1-clunky': ('Log', None),
    'c1-sleek': ('Strak (gestileerd)', None),
    'c1-bulky': ('Log (omvangrijk)', None),
    'c1-compact': ('Compact', None),
    'c1-flimsy': ('Broos (wankel)', None),
    'c1-durable': ('Duurzaam', None),
    'c1-to-mumble': ('Mompelen', None),
    'c1-to-mutter': ('Binnensmonds mopperen', None),
    'c1-to-stutter': ('Stotteren', None),
    'c1-to-slur': ('Onduidelijk articuleren', None),
    'c1-to-ramble': ('Bazelen (afdwalen)', None),
    'c1-to-rant': ('Tieren', None),
    'c1-to-grumble': ('Mopperen', None),
    'c1-to-whine': ('Zeuren', None),
    'c1-to-snap-at-someone': ('Afsnauwen', None),
    'c1-hoarse': ('Hees', None),
    'c1-raspy': ('Schor', None),
    'c1-monotone': ('Monotoon', None),
    'c1-shrill': ('Schel', None),
    'c1-deafening': ('Oorverdovend', None),
    'c1-muffled': ('Gedempt', None),
    'c1-faint-sound': ('Zwak (geluid)', None),
    'c1-to-hum': ('Neuriën', None),
    'c1-to-chant': ('Scanderen', None),
    'c1-to-murmur': ('Murmelen', None),
    'c1-to-bellow': ('Bulderen', None),
    'c1-to-chuckle': ('Grinniken', None),
    'c1-to-giggle': ('Giechelen', None),
    'c1-to-snicker': ('Gniffelen', None),
    'c1-to-sob': ('Snikken', None),
    'c1-to-wail': ('Weeklagen', None),
    'c1-to-howl': ('Huilen (janken)', None),
    'c1-to-shriek': ('Gillen', None),
    'c1-to-gasp': ('Naar adem happen', None),
    'c1-pitch-voice': ('Toonhoogte (stem)', None),
    'c1-accent-stress': ('Klemtoon', None),
    'c1-asset': ('Activum', None),
    'c1-liability-finance': ('Passivum', None),
    'c1-equity': ('Eigen vermogen', None),
    'c1-portfolio': ('Portefeuille', None),
    'c1-dividend': ('Dividend', None),
    'c1-bond-finance': ('Obligatie', None),
    'c1-hedge': ('Afdekking (hedge)', None),
    'c1-liquidity': ('Liquiditeit', None),
    'c1-collateral': ('Onderpand', None),
    'c1-default-loan': ('Wanbetaling', None),
    'c1-foreclosure': ('Executieverkoop', None),
    'c1-appreciation-value': ('Waardestijging', None),
    'c1-depreciation': ('Waardevermindering', None),
    'c1-capital-gains': ('Vermogenswinst', None),
    'c1-write-off': ('Afschrijving', None),
    'c1-overhead': ('Overheadkosten', None),
    'c1-payroll': ('Loonlijst', None),
    'c1-gross-before-deductions': ('Bruto', None),
    'c1-net': ('Netto', None),
    'c1-deductible': ('Aftrekbaar', None),
    'c1-exemption': ('Vrijstelling', None),
    'c1-audit': ('Controle (audit)', None),
    'c1-ledger': ('Grootboek', None),
    'c1-bookkeeping': ('Boekhouding', None),
    'c1-break-even': ('Break-evenpunt', None),
    'c1-turnover': ('Omzet', None),
    'c1-markup': ('Winstopslag', None),
    'c1-cash-reserve': ('Kasreserve', None),
    'c1-venture-capital': ('Durfkapitaal', None),
    'c1-fiscal-year': ('Boekjaar', None),
    'c1-expedition': ('Expeditie', None),
    'c1-pilgrimage': ('Pelgrimstocht', None),
    'c1-getaway': ('Uitstapje', None),
    'c1-sabbatical': ('Sabbatical', None),
    'c1-nomad': ('Nomade', None),
    'c1-expatriate': ('Expat', None),
    'c1-immigrant': ('Immigrant', None),
    'c1-to-relocate': ('Verhuizen', None),
    'c1-to-settle-down': ('Zich vestigen', None),
    'c1-culture-shock': ('Cultuurshock', None),
    'c1-to-assimilate': ('Zich assimileren', None),
    'c1-bilingual': ('Tweetalig', None),
    'c1-multilingual': ('Meertalig', None),
    'c1-mother-tongue': ('Moedertaal', None),
    'c1-dialect': ('Dialect', None),
    'c1-slang': ('Straattaal', None),
    'c1-jargon': ('Jargon', None),
    'c1-register-language': ('Taalregister', None),
    'c1-colloquial': ('Informeel (spreektalig)', None),
    'c1-fluency': ('Vloeiendheid', None),
    'c1-proficiency': ('Beheersing (van een taal)', None),
    'c1-to-master': ('Beheersen (onder de knie krijgen)', None),
    'c1-immersion': ('Onderdompeling', None),
    'c1-intonation': ('Intonatie', None),
    'c1-to-mispronounce': ('Verkeerd uitspreken', None),
    'c1-false-friend': ('Valse vriend', None),
    'c1-cognate': ('Verwant woord', None),
    'c1-loanword': ('Leenwoord', None),
    'c1-literacy': ('Geletterdheid', None),
    'c1-interpreter': ('Tolk', None),
    'c1-latency': ('Latentie', None),
    'c1-server': ('Server', None),
    'c1-cloud-computing': ('Cloudcomputing', None),
    'c1-backup-data': ('Back-up', None),
    'c1-firewall': ('Firewall', None),
    'c1-malware': ('Schadelijke software', None),
    'c1-phishing': ('Phishing', None),
    'c1-two-factor-authentication': ('Tweefactorauthenticatie', None),
    'c1-biometric': ('Biometrisch', None),
    'c1-open-source': ('Open source', None),
    'c1-interface': ('Interface', None),
    'c1-plugin': ('Invoegtoepassing', None),
    'c1-patch-software': ('Patch (software)', None),
    'c1-to-deploy': ('Uitrollen (in productie nemen)', None),
    'c1-release-version': ('Versie (release)', None),
    'c1-beta': ('Bèta', None),
    'c1-blockchain': ('Blockchain', None),
    'c1-cryptocurrency': ('Cryptovaluta', None),
    'c1-machine-learning': ('Machinaal leren', None),
    'c1-neural-network': ('Neuraal netwerk', None),
    'c1-dataset': ('Gegevensverzameling', None),
    'c1-drone': ('Drone', None),
    'c1-sensor': ('Sensor', None),
    'c1-augmented-reality': ('Verrijkte realiteit', None),
    'c1-wearable': ('Draagbaar apparaat', None),
    'c1-smart-home': ('Slim huis', None),
    'c1-bandwidth-network': ('Bandbreedte', None),
    'c1-outage': ('Storing (uitval)', None),
    'c1-scalability': ('Schaalbaarheid', None),
    'c1-encryption-key': ('Versleutelingssleutel', None),
    'c1-cinematography': ('Cinematografie', None),
    'c1-close-up': ('Close-up', None),
    'c1-wide-shot': ('Totaalshot', None),
    'c1-montage': ('Montage', None),
    'c1-flashback': ('Flashback', None),
    'c1-voice-over': ('Voice-over', None),
    'c1-subplot': ('Zijverhaal', None),
    'c1-protagonist': ('Hoofdpersoon', None),
    'c1-antagonist': ('Tegenstander (antagonist)', None),
    'c1-cliffhanger': ('Cliffhanger', None),
    'c1-plot-twist': ('Plotwending', None),
    'c1-foreshadowing': ('Vooruitwijzing', None),
    'c1-pacing': ('Tempo (verhaal)', None),
    'c1-casting': ('Casting', None),
    'c1-cameo': ('Gastoptreden', None),
    'c1-sequel': ('Vervolg', None),
    'c1-prequel': ('Voorloper (prequel)', None),
    'c1-reboot': ('Herstart (reboot)', None),
    'c1-box-office': ('Kassucces (bioscoopopbrengst)', None),
    'c1-blockbuster': ('Kaskraker', None),
    'c1-indie-film': ('Onafhankelijke film', None),
    'c1-cult-classic': ('Cultklassieker', None),
    'c1-critically-acclaimed': ('Alom geprezen door critici', None),
    'c1-dubbed': ('Nagesynchroniseerd', None),
    'c1-subtitled': ('Ondertiteld', None),
    'c1-screening': ('Vertoning', None),
    'c1-pilot-episode': ('Pilotaflevering', None),
    'c1-season-finale': ('Seizoensfinale', None),
    'c1-showrunner': ('Showrunner', None),
    'c1-storyboard': ('Storyboard', None),
    'c1-on-the-mend': ('Aan de beterende hand', None),
    'c1-run-down-exhausted': ('Op (uitgeput)', None),
    'c1-in-good-shape': ('In goede conditie', None),
    'c1-out-of-shape': ('Uit conditie', None),
    'c1-a-clean-bill-of-health': ('Helemaal gezond verklaard', None),
    'c1-to-pull-a-muscle': ('Een spier verrekken', None),
    'c1-wear-and-tear': ('Slijtage', None),
    'c1-to-nod-off': ('In slaap sukkelen', None),
    'c1-to-sleep-like-a-log': ('Slapen als een roos', None),
    'c1-to-toss-and-turn': ('Woelen (in bed)', None),
    'c1-over-the-counter': ('Zonder recept', None),
    'c1-second-opinion': ('Tweede mening', None),
    'c1-bedside-manner': ('Omgang met patiënten', None),
    'c1-to-be-discharged': ('Ontslagen worden (uit het ziekenhuis)', None),
    'c1-to-be-admitted-hospital': ('Opgenomen worden', None),
    'c1-outpatient': ('Poliklinische patiënt', None),
    'c1-follow-up-appointment': ('Vervolgafspraak', None),
    'c1-referral': ('Doorverwijzing', None),
    'c1-to-take-a-turn-for-the-worse': ('Verslechteren', None),
    'c1-to-black-out': ('Buiten bewustzijn raken', None),
    'c1-under-the-knife': ('Onder het mes', None),
    'c1-slipped-disc': ('Hernia', None),
    'c1-jet-lagged': ('Last van jetlag', None),
    'c1-on-medication': ('Onder medicatie', None),
    'c1-immune-to': ('Immuun voor', None),
    'c1-prone-to': ('Vatbaar voor', None),
    'c1-relapse': ('Terugval', None),
    'c1-remission': ('Remissie', None),
    'c1-a-no-brainer': ('Een uitgemaakte zaak', None),
    'c1-a-long-shot': ('Een gok met weinig kans', None),
    'c1-a-close-call': ('Op het nippertje', None),
    'c1-a-wake-up-call': ('Een wake-upcall', None),
    'c1-a-catch-hidden-problem': ('Een addertje onder het gras', None),
    'c1-the-upside': ('De voordelen', None),
    'c1-the-downside': ('Het nadeel', None),
    'c1-a-trade-off': ('Een afweging', None),
    'c1-a-loophole': ('Een mazen in de wet', None),
    'c1-a-setback': ('Een tegenslag', None),
    'c1-a-blessing-in-disguise': ('Een geluk bij een ongeluk', None),
    'c1-the-tip-of-the-iceberg': ('Het topje van de ijsberg', None),
    'c1-the-last-straw': ('De druppel die de emmer doet overlopen', None),
    'c1-a-double-edged-sword': ('Een tweesnijdend zwaard', None),
    'c1-the-elephant-in-the-room': ('De olifant in de kamer', None),
    'c1-a-grey-area': ('Een grijs gebied', None),
    'c1-a-slippery-slope': ('Een hellend vlak', None),
    'c1-a-vicious-circle': ('Een vicieuze cirkel', None),
    'c1-a-stepping-stone': ('Een opstap', None),
    'c1-a-rule-of-thumb': ('Een vuistregel', None),
    'c1-a-rain-check': ('Een volgende keer (uitstel)', None),
    'c1-a-heads-up': ('Een tip vooraf', None),
    'c1-a-hunch': ('Een voorgevoel', None),
    'c1-a-knack': ('Een handigheidje (talent)', None),
    'c1-a-pet-peeve': ('Een ergernis', None),
    'c1-a-red-flag': ('Een waarschuwingssignaal', None),
    'c1-a-silver-lining': ('Een lichtpuntje', None),
    'c1-a-drop-in-the-ocean': ('Een druppel op een gloeiende plaat', None),
    'c1-a-piece-of-cake': ('Een fluitje van een cent', None),
    'c1-a-far-cry-from': ('Verre van', None),
    'c1-a-handful': ('Een handvol', None),
    'c1-a-fair-amount': ('Een aanzienlijke hoeveelheid', None),
    'c1-the-lions-share': ('Het leeuwendeel', None),
    'c1-a-fraction': ('Een fractie', None),
    'c1-the-vast-majority': ('De overgrote meerderheid', None),
    'c1-next-to-nothing': ('Bijna niets', None),
    'c1-a-great-deal': ('Een groot deel (heel veel)', None),
    'c1-at-most': ('Hoogstens', None),
    'c1-at-best': ('In het beste geval', None),
    'c1-at-worst': ('In het slechtste geval', None),
    'c1-in-bulk': ('In bulk', None),
    'c1-on-average': ('Gemiddeld', None),
    'c1-per-capita': ('Per hoofd van de bevolking', None),
    'c1-give-or-take': ('Min of meer', None),
    'c1-a-rough-estimate': ('Een ruwe schatting', None),
    'c1-a-round-number': ('Een rond getal', None),
    'c1-the-odds': ('De kansen', None),
    'c1-by-a-narrow-margin': ('Met een nipte marge', None),
    'c1-by-a-landslide': ('Met een verpletterende meerderheid', None),
    'c1-one-in-ten': ('Een op de tien', None),
    'c1-twofold': ('Tweevoudig', None),
    'c1-exponentially': ('Exponentieel', None),
    'c1-marginally': ('Marginaal', None),
    'c1-negligible': ('Verwaarloosbaar', None),
    'c1-sizable': ('Aanzienlijk', None),
    'c1-umpteen': ('Talloze', None),
    'c1-in-the-region-of': ('Rond de (ongeveer)', None),
    'c1-odds-and-ends': ('Rommeltjes (losse spulletjes)', None),
    'c1-mentor': ('Mentor', None),
    'c1-protege': ('Beschermeling', None),
    'c1-intern': ('Stagiair', None),
    'c1-veteran-experienced': ('Veteraan', None),
    'c1-rookie': ('Beginneling', None),
    'c1-whiz': ('Kei (talent)', None),
    'c1-workaholic': ('Workaholic', None),
    'c1-slacker': ('Luilak', None),
    'c1-know-it-all': ('Weetal', None),
    'c1-yes-man': ('Jaknikker', None),
    'c1-gatekeeper': ('Poortwachter', None),
    'c1-middleman': ('Tussenpersoon', None),
    'c1-liaison': ('Verbindingspersoon', None),
    'c1-spokesperson': ('Woordvoerder', None),
    'c1-figurehead': ('Boegbeeld', None),
    'c1-frontrunner': ('Koploper', None),
    'c1-underdog': ('Underdog', None),
    'c1-dark-horse': ('Onverwachte kanshebber', None),
    'c1-wildcard': ('Onvoorspelbare factor', None),
    'c1-heavyweight': ('Zwaargewicht', None),
    'c1-newcomer': ('Nieuwkomer', None),
    'c1-insider': ('Ingewijde', None),
    'c1-outsider': ('Buitenstaander', None),
    'c1-consultant': ('Adviseur', None),
    'c1-subcontractor': ('Onderaannemer', None),
    'c1-headhunter': ('Headhunter', None),
    'c1-scapegoat': ('Zondebok', None),
    'c1-go-getter': ('Doorzetter', None),
    'c1-universal-healthcare': ('Universele gezondheidszorg', None),
    'c1-minimum-wage': ('Minimumloon', None),
    'c1-affordable-housing': ('Betaalbare huisvesting', None),
    'c1-surveillance': ('Bewaking (toezicht)', None),
    'c1-privacy': ('Privacy', None),
    'c1-free-speech': ('Vrijheid van meningsuiting', None),
    'c1-polarization': ('Polarisatie', None),
    'c1-populism': ('Populisme', None),
    'c1-nationalism': ('Nationalisme', None),
    'c1-globalization': ('Globalisering', None),
    'c1-austerity': ('Bezuinigingsbeleid', None),
    'c1-welfare': ('Sociale voorzieningen', None),
    'c1-aging-population': ('Vergrijzing', None),
    'c1-birth-rate': ('Geboortecijfer', None),
    'c1-brain-drain': ('Braindrain', None),
    'c1-gig-economy': ('Platformeconomie', None),
    'c1-job-displacement': ('Verdringing van banen', None),
    'c1-universal-basic-income': ('Basisinkomen', None),
    'c1-carbon-tax': ('Koolstofbelasting', None),
    'c1-nuclear-energy': ('Kernenergie', None),
    'c1-food-security': ('Voedselzekerheid', None),
    'c1-water-scarcity': ('Waterschaarste', None),
    'c1-urban-sprawl': ('Verstedelijking (ongebreideld)', None),
    'c1-rent-control': ('Huurregulering', None),
    'c1-public-transit-funding': ('Financiering van openbaar vervoer', None),
    'c1-data-protection': ('Gegevensbescherming', None),
    'c1-wealth-gap': ('Welvaartskloof', None),
    'c1-voter-turnout': ('Opkomst (verkiezingen)', None),
    'c1-bustling': ('Bruisend', None),
    'c1-sleepy-town': ('Slaperig (dorp)', None),
    'c1-vibrant': ('Levendig', None),
    'c1-deserted': ('Verlaten', None),
    'c1-packed': ('Overvol', None),
    'c1-cramped': ('Krap', None),
    'c1-airy': ('Luchtig', None),
    'c1-stuffy': ('Benauwd', None),
    'c1-gloomy': ('Somber', None),
    'c1-dingy': ('Grauw (smoezelig)', None),
    'c1-shabby': ('Sjofel', None),
    'c1-chic': ('Chic', None),
    'c1-trendy': ('Trendy', None),
    'c1-upscale': ('Chic (exclusief)', None),
    'c1-seedy': ('Louche (verlopen)', None),
    'c1-leafy': ('Groen (bomenrijk)', None),
    'c1-sprawling': ('Uitgestrekt', None),
    'c1-walkable': ('Goed te belopen', None),
    'c1-secluded': ('Afgezonderd', None),
    'c1-remote-place': ('Afgelegen', None),
    'c1-touristy': ('Toeristisch (overdreven)', None),
    'c1-unspoiled': ('Ongerept', None),
    'c1-well-kept': ('Goed onderhouden', None),
    'c1-overgrown': ('Overwoekerd', None),
    'c1-tucked-away': ('Weggestopt', None),
    'c1-nestled': ('Genesteld', None),
    'c1-lively': ('Levendig', None),
    'c1-run-down-place': ('Vervallen', None),
}
