# -*- coding: utf-8 -*-
# Polish skill drills: grammar (B2), idioms (C1), nuance (C2)
LANG = 'pl'

GRAMMAR = [
    {"id": "g-pl1", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Kiedy ___ do domu, zaczęło padać.", "correct": "wracałem",
     "options": ["wracałem", "wróciłem", "wrócę", "wracam"],
     "note": "Imperfective past (wracałem) frames the ongoing action interrupted by the rain — a classic narrative backdrop."},
    {"id": "g-pl2", "tier": "B2", "topic": "gram-telling-stories",
     "sentence": "Opowiedział nam, co ___ podczas wakacji.", "correct": "mu się przydarzyło",
     "options": ["mu się przydarzyło", "mu się przydarza", "mu się przydarzy", "mu się przydarzać"],
     "note": "Reported past event: przydarzyć się (perfective past) — “what had happened to him.”"},
    {"id": "g-pl3", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Gdybym miał więcej czasu, ___ japońskiego.", "correct": "uczyłbym się",
     "options": ["uczyłbym się", "uczę się", "nauczę się", "uczyłem się"],
     "note": "Second conditional: gdybym + past (miał) pairs with the conditional uczyłbym się (would learn)."},
    {"id": "g-pl4", "tier": "B2", "topic": "gram-conditionals-complex",
     "sentence": "Gdyby ___ wcześniej, zdążylibyśmy na pociąg.", "correct": "wyszedł",
     "options": ["wyszedł", "wyjdzie", "wychodzi", "wyszedłby"],
     "note": "Past unreal conditional: gdyby + past perfective (wyszedł) + conditional (zdążylibyśmy) — “if he had left earlier.”"},
    {"id": "g-pl5", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Ten sweter jest zrobiony ___ wełny.", "correct": "z",
     "options": ["z", "od", "przez", "na"],
     "note": "Material is marked with z + genitive (z wełny, “out of wool”), not od or przez."},
    {"id": "g-pl6", "tier": "B2", "topic": "gram-everyday-descriptions",
     "sentence": "Mieszkanie znajduje się ___ trzecim piętrze.", "correct": "na",
     "options": ["na", "w", "do", "przy"],
     "note": "Floor location uses na + locative (na trzecim piętrze, “on the third floor”)."},
]

IDIOMS = [
    {"id": "i-pl1", "tier": "C1", "topic": "idiom-character",
     "phrase": "Nie w ciemię bity", "correct": "sharp-witted, not easily fooled",
     "options": ["sharp-witted, not easily fooled", "hot-tempered and reckless", "painfully shy", "generous to a fault"],
     "note": "Literally “not beaten on the soft spot of the skull” — used for someone quick-witted who can't easily be tricked."},
    {"id": "i-pl2", "tier": "C1", "topic": "idiom-character",
     "phrase": "Człowiek z jajami", "correct": "a person with guts, someone bold",
     "options": ["a person with guts, someone bold", "a person who lies constantly", "a very stingy person", "a person who never commits"],
     "note": "Literally “a man with eggs” — colloquial for someone with courage or nerve, roughly “has balls.”"},
    {"id": "i-pl3", "tier": "C1", "topic": "idiom-character",
     "phrase": "Mieć węża w kieszeni", "correct": "to be very stingy",
     "options": ["to be very stingy", "to be extremely nervous", "to be a compulsive liar", "to be unusually generous"],
     "note": "Literally “to have a snake in one's pocket” — the snake supposedly bites your hand before you can pull out your wallet."},
    {"id": "i-pl4", "tier": "C1", "topic": "idiom-everyday-moments",
     "phrase": "Wpaść jak śliwka w kompot", "correct": "to get caught up in trouble unexpectedly",
     "options": ["to get caught up in trouble unexpectedly", "to arrive fashionably late", "to succeed effortlessly", "to fall asleep instantly"],
     "note": "Literally “to fall in like a plum into compote” — describes stumbling helplessly into an unwanted situation."},
    {"id": "i-pl5", "tier": "C1", "topic": "idiom-media",
     "phrase": "Zjeść z kimś beczkę soli", "correct": "to know someone very well over a long time",
     "options": ["to know someone very well over a long time", "to have a brief argument with someone", "to owe someone a favor", "to compete fiercely with someone"],
     "note": "Literally “to eat a barrel of salt with someone” — used in interviews/media about long friendships or partnerships."},
    {"id": "i-pl6", "tier": "C1", "topic": "idiom-media",
     "phrase": "Wywołać burzę w mediach", "correct": "to spark a media storm",
     "options": ["to spark a media storm", "to quietly leak a story", "to retract a public statement", "to boost television ratings"],
     "note": "Literally “to call up a storm in the media” — a stock phrase in Polish news coverage for a controversy going viral."},
]

NUANCE = [
    {"id": "n-pl1", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "You're asking a stranger for directions on the street, politely.", "correct": "Czy mógłby mi Pan pomóc?",
     "options": ["Czy mógłby mi Pan pomóc?", "Pomożesz mi?", "Pomóż mi.", "Musisz mi pomóc."],
     "note": "The conditional mógłby with the formal Pan address is the polite register for approaching a stranger."},
    {"id": "n-pl2", "tier": "C2", "topic": "nuance-politeness-register",
     "context": "Emailing a professor to request an extension, formally.", "correct": "Uprzejmie proszę o wydłużenie terminu",
     "options": ["Uprzejmie proszę o wydłużenie terminu", "Daj mi więcej czasu", "Chcę więcej czasu, ok?", "Musi Pan mi dać więcej czasu"],
     "note": "“Uprzejmie proszę” (I kindly ask) is the standard formal-email opener; the alternatives are too blunt or presumptuous for a professor."},
    {"id": "n-pl3", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Describing a decision made without any hesitation at all.", "correct": "bez wahania",
     "options": ["bez wahania", "od czasu do czasu", "mniej więcej", "w miarę możliwości"],
     "note": "Bez wahania (without hesitation) precisely conveys instant decisiveness, unlike the vaguer alternatives."},
    {"id": "n-pl4", "tier": "C2", "topic": "nuance-precise-wording",
     "context": "Saying an estimate is only roughly accurate, not exact.", "correct": "z grubsza",
     "options": ["z grubsza", "dokładnie", "co do joty", "bez wyjątku"],
     "note": "Z grubsza (roughly) is the precise hedge for an approximate figure, contrasting with dokładnie (exactly)."},
    {"id": "n-pl5", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "A friend casually asking what's going on, in relaxed spoken Polish.", "correct": "Co jest grane?",
     "options": ["Co jest grane?", "Co się wydarzyło, jeśli mogę spytać?", "Proszę mnie poinformować o sytuacji.", "Jaka jest aktualna sytuacja?"],
     "note": "“Co jest grane?” (literally “what's being played?”) is casual slang for “what's up?” — only fits informal speech among friends."},
    {"id": "n-pl6", "tier": "C2", "topic": "nuance-spoken-register",
     "context": "Telling a close friend, informally, that something is awesome.", "correct": "Ale odjazd!",
     "options": ["Ale odjazd!", "To jest wysoce satysfakcjonujące.", "Jestem pod wrażeniem tej sytuacji.", "Uważam to za bardzo pozytywne."],
     "note": "“Ale odjazd!” is colloquial slang (literally “what a departure!”) for “that's wild/awesome” — strictly spoken register."},
    {"id": "n-pl7", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Expressing mild, good-natured annoyance at a friend's lateness.", "correct": "No coś ty",
     "options": ["No coś ty", "Jestem wściekły", "To niedopuszczalne", "Nienawidzę cię za to"],
     "note": "“No coś ty” is a light, teasing reproach — far softer than wściekły (furious) or nienawidzę (I hate)."},
    {"id": "n-pl8", "tier": "C2", "topic": "nuance-tone-shades",
     "context": "Expressing genuine, sharp irritation at a serious betrayal.", "correct": "Jestem oburzony",
     "options": ["Jestem oburzony", "Trochę mnie to irytuje", "No coś ty", "Jest mi wszystko jedno"],
     "note": "Jestem oburzony (I am outraged) carries real indignation, unlike the mild irritation of the other options."},
]
