# -*- coding: utf-8 -*-
LANG = 'hi'
WORDS = {
    'c2-to-abate': ('थमना', 'thamna'),
    'c2-to-abhor': ('घृणा करना', 'ghrina karna'),
    'c2-to-abstain': ('विरत रहना', 'virat rehna'),
    'c2-to-accentuate': ('उभारना', 'ubhaarna'),
    'c2-to-acquiesce': ('सहमत होना', 'sahmat hona'),
    'c2-to-admonish': ('चेतावनी देना', 'chetavani dena'),
    'c2-to-alleviate': ('हल्का करना', 'halka karna'),
    'c2-to-amass': ('इकट्ठा करना', 'ikattha karna'),
    'c2-to-appease': ('तुष्ट करना', 'tusht karna'),
    'c2-to-ascribe': ('आरोपित करना', 'aaropit karna'),
    'c2-to-augment': ('बढ़ाना', 'badhana'),
    'c2-to-avert': ('टालना', 'taalna'),
    'c2-to-beckon': ('इशारा करना', 'ishara karna'),
    'c2-to-belittle': ('छोटा समझना', 'chhota samajhna'),
    'c2-to-bequeath': ('वसीयत में देना', 'vasiyat mein dena'),
    'c2-to-beseech': ('गिड़गिड़ाना', 'gidgidana'),
    'c2-to-bewilder': ('हतप्रभ करना', 'hatprabh karna'),
    'c2-to-brandish': ('लहराना', 'leharana'),
    'c2-to-castigate': ('कड़ी आलोचना करना', 'kadi aalochana karna'),
    'c2-to-coalesce': ('एक हो जाना', 'ek ho jana'),
    'c2-to-commend': ('प्रशंसा करना', 'prashansa karna'),
    'c2-to-concede': ('स्वीकार करना', 'svikar karna'),
    'c2-to-concoct': ('गढ़ना', 'gadhna'),
    'c2-to-confer': ('प्रदान करना', 'pradan karna'),
    'c2-to-contend': ('दावा करना', 'dawa karna'),
    'c2-to-corroborate': ('पुष्टि करना', 'pushti karna'),
    'c2-to-aggravate': ('बिगाड़ना', 'bigadna'),
    'c2-to-assail': ('हमला करना', 'hamla karna'),
    'c2-to-chastise': ('दंड देना', 'dand dena'),
    'c2-to-condescend': ('उपकार जताना', 'upkar jatana'),
    'c2-to-debunk': ('पर्दाफाश करना', 'pardafash karna'),
    'c2-to-decipher': ('पहेली सुलझाना', 'paheli suljhana'),
    'c2-to-decry': ('निंदा करना', 'ninda karna'),
    'c2-to-deem': ('मानना', 'maanna'),
    'c2-to-defer': ('स्थगित करना', 'sthagit karna'),
    'c2-to-delineate': ('रेखांकित करना', 'rekhankit karna'),
    'c2-to-denounce': ('सार्वजनिक निंदा करना', 'sarvajanik ninda karna'),
    'c2-to-deplete': ('क्षीण करना', 'kshin karna'),
    'c2-to-deride': ('उपहास करना', 'upahaas karna'),
    'c2-to-despair': ('निराश होना', 'nirash hona'),
    'c2-to-detain': ('हिरासत में लेना', 'hirasat mein lena'),
    'c2-to-deviate': ('विचलित होना', 'vichalit hona'),
    'c2-to-disdain': ('तिरस्कार करना', 'tiraskar karna'),
    'c2-to-disperse': ('तितर-बितर होना', 'titar-bitar hona'),
    'c2-to-dissuade': ('विरत करना', 'virat karna'),
    'c2-to-divulge': ('भेद खोलना', 'bhed kholna'),
    'c2-to-dwindle': ('घटते जाना', 'ghatate jana'),
    'c2-to-elude': ('चकमा देना', 'chakma dena'),
    'c2-to-emanate': ('उद्भूत होना', 'udbhoot hona'),
    'c2-to-embellish': ('सजाना', 'sajana'),
    'c2-to-encompass': ('समाविष्ट करना', 'samavisht karna'),
    'c2-to-engender': ('उत्पन्न करना', 'utpann karna'),
    'c2-to-enlighten': ('प्रबुद्ध करना', 'prabuddh karna'),
    'c2-to-enthrall': ('मंत्रमुग्ध करना', 'mantramugdh karna'),
    'c2-to-entice': ('लुभाना', 'lubhana'),
    'c2-to-envision': ('कल्पना करना', 'kalpana karna'),
    'c2-to-evade': ('बच निकलना', 'bach nikalna'),
    'c2-to-exalt': ('महिमामंडित करना', 'mahimamandit karna'),
    'c2-to-expedite': ('त्वरित करना', 'tvarit karna'),
    'c2-to-extol': ('गुणगान करना', 'gungan karna'),
    'c2-to-fabricate': ('मनगढ़ंत बनाना', 'mangadhant banana'),
    'c2-to-falter': ('लड़खड़ाना', 'ladkhadana'),
    'c2-to-feign': ('ढोंग करना', 'dhong karna'),
    'c2-to-flourish': ('फलना-फूलना', 'phalna-phoolna'),
    'c2-to-forfeit': ('गंवाना', 'ganwana'),
    'c2-to-forgo': ('छोड़ देना', 'chhod dena'),
    'c2-to-galvanize': ('उत्प्रेरित करना', 'utprerit karna'),
    'c2-to-garner': ('अर्जित करना', 'arjit karna'),
    'c2-to-gloat': ('इतराना', 'itarana'),
    'c2-to-grapple': ('जूझना', 'joojhna'),
    'c2-to-harness': ('दोहन करना', 'dohan karna'),
    'c2-to-heed': ('ध्यान देना', 'dhyan dena'),
    'c2-to-hoard': ('जमाखोरी करना', 'jamakhori karna'),
    'c2-to-impart': ('संचारित करना', 'sancharit karna'),
    'c2-to-implore': ('मिन्नत करना', 'minnat karna'),
    'c2-to-incite': ('भड़काना', 'bhadkana'),
    'c2-to-inhibit': ('बाधित करना', 'baadhit karna'),
    'c2-to-instill': ('भर देना', 'bhar dena'),
    'c2-to-intercede': ('मध्यस्थता करना', 'madhyasthata karna'),
    'c2-to-intimidate': ('धमकाना', 'dhamkana'),
    'c2-to-jeopardize': ('खतरे में डालना', 'khatre mein daalna'),
    'c2-to-languish': ('मुरझाना', 'murjhana'),
    'c2-to-lure': ('फुसलाना', 'phuslana'),
    'c2-to-marvel': ('अचंभित होना', 'achambhit hona'),
    'c2-to-meander': ('बलखाना', 'balkhana'),
    'c2-to-muster': ('जुटाना', 'jutana'),
    'c2-to-obliterate': ('मिटा देना', 'mita dena'),
    'c2-to-oscillate': ('दोलन करना', 'dolan karna'),
    'c2-to-ostracize': ('बहिष्कृत करना', 'bahishkrit karna'),
    'c2-to-perpetuate': ('चिरस्थायी बनाना', 'chirasthayi banana'),
    'c2-to-permeate': ('व्याप्त होना', 'vyapt hona'),
    'c2-to-plummet': ('तेज़ी से गिरना', 'tezi se girna'),
    'c2-to-ponder': ('चिंतन करना', 'chintan karna'),
    'c2-to-preach': ('उपदेश देना', 'updesh dena'),
    'c2-to-procure': ('प्राप्त करना', 'prapt karna'),
    'c2-to-proliferate': ('तेज़ी से फैलना', 'tezi se phailna'),
    'c2-to-propel': ('गति देना', 'gati dena'),
    'c2-to-quell': ('दबाना', 'dabana'),
    'c2-to-ratify': ('अनुसमर्थन करना', 'anusamarthan karna'),
    'c2-to-rebuke': ('डांटना', 'daantna'),
    'c2-to-rebut': ('प्रत्युत्तर देना', 'pratyuttar dena'),
    'c2-to-recant': ('मुकरना', 'mukarna'),
    'c2-to-redeem': ('मोचन करना', 'mochan karna'),
    'c2-to-refute': ('खंडन करना', 'khandan karna'),
    'c2-to-relish': ('भरपूर आनंद लेना', 'bharpoor anand lena'),
    'c2-to-renounce': ('त्याग देना', 'tyag dena'),
    'c2-to-replenish': ('फिर से भरना', 'phir se bharna'),
    'c2-to-reprimand': ('फटकारना', 'phatkarna'),
    'c2-to-repudiate': ('अस्वीकार करना', 'asvikar karna'),
    'c2-to-resonate': ('गूंजना', 'goonjna'),
    'c2-to-retaliate': ('बदला लेना', 'badla lena'),
    'c2-to-revere': ('श्रद्धा रखना', 'shraddha rakhna'),
    'c2-to-revoke': ('रद्द करना', 'radd karna'),
    'c2-to-saturate': ('संतृप्त करना', 'santript karna'),
    'c2-to-scorn': ('अवमानना करना', 'avmanana karna'),
    'c2-to-squander': ('बर्बाद करना', 'barbaad karna'),
    'c2-to-stagnate': ('ठप हो जाना', 'thap ho jana'),
    'c2-to-stifle': ('कुचल देना', 'kuchal dena'),
    'c2-to-subside': ('शांत होना', 'shant hona'),
    'c2-to-succumb': ('अधीन हो जाना', 'adhin ho jana'),
    'c2-to-supplant': ('स्थानापन्न करना', 'sthanapann karna'),
    'c2-to-surmise': ('अनुमान लगाना', 'anuman lagana'),
    'c2-to-swindle': ('ठगना', 'thagna'),
    'c2-to-tarnish': ('धूमिल करना', 'dhoomil karna'),
    'c2-to-thwart': ('विफल करना', 'viphal karna'),
    'c2-to-transcend': ('से ऊपर उठना', 'se oopar uthna'),
    'c2-to-unravel': ('सुलझाना', 'suljhana'),
    'c2-to-usurp': ('हड़पना', 'hadapna'),
    'c2-to-vanquish': ('पराजित करना', 'parajit karna'),
    'c2-to-venerate': ('पूजना', 'poojna'),
    'c2-to-vilify': ('बदनाम करना', 'badnaam karna'),
    'c2-to-wane': ('क्षीण होना', 'kshin hona'),
    'c2-to-wield': ('चलाना', 'chalana'),
    'c2-to-writhe': ('छटपटाना', 'chatpatana'),
    'c2-to-yearn': ('तरसना', 'tarasna'),
    'c2-to-beget': ('जन्म देना', 'janm dena'),
    'c2-to-besiege': ('घेराबंदी करना', 'gherabandi karna'),
    'c2-to-cajole': ('पुचकारना', 'puchkarna'),
    'c2-to-coax': ('मनाना', 'manana'),
    'c2-to-deplore': ('खेद प्रकट करना', 'khed prakat karna'),
    'c2-to-disparage': ('नीचा दिखाना', 'neecha dikhana'),
    'c2-to-exhort': ('प्रोत्साहित करना', 'protsahit karna'),
    'c2-to-foment': ('उकसाना', 'ukasana'),
    'c2-to-indulge': ('भोग करना', 'bhog karna'),
    'c2-to-placate': ('शांत करना', 'shant karna'),
    'c2-to-preempt': ('पहले से रोक देना', 'pehle se rok dena'),
    'c2-to-rescind': ('निरस्त करना', 'nirast karna'),
    'c2-to-stymie': ('बाधा डालना', 'baadha daalna'),
    'c2-to-vindicate': ('निर्दोष सिद्ध करना', 'nirdosh siddh karna'),
    'c2-to-evince': ('प्रदर्शित करना', 'pradarshit karna'),
    'c2-affable': ('मिलनसार', 'milansaar'),
    'c2-churlish': ('रूखा', 'rookha'),
    'c2-astute': ('चतुर', 'chatur'),
    'c2-audacious': ('साहसी', 'saahasi'),
    'c2-belligerent': ('आक्रामक', 'aakraamak'),
    'c2-sanguine': ('आशावादी', 'aashawaadi'),
    'c2-brusque': ('अक्खड़', 'akkhad'),
    'c2-callous': ('निर्दयी', 'nirdayi'),
    'c2-truculent': ('झगड़ालू', 'jhagdalu'),
    'c2-capricious': ('मनमौजी', 'manmauji'),
    'c2-complacent': ('आत्मसंतुष्ट', 'aatmasantusht'),
    'c2-unflappable': ('अविचलित', 'avichalit'),
    'c2-cunning': ('चालाक', 'chaalaak'),
    'c2-diffident': ('संकोची', 'sankochi'),
    'c2-officious': ('दखलंदाज़', 'dakhalandaaz'),
    'c2-docile': ('आज्ञाकारी', 'aagyakari'),
    'c2-erudite': ('विद्वान', 'vidwan'),
    'c2-fastidious': ('चूज़ी', 'choozi'),
    'c2-flippant': ('उथला', 'uthla'),
    'c2-garrulous': ('बातूनी', 'baatuni'),
    'c2-gregarious': ('समूहप्रिय', 'samoohpriya'),
    'c2-haughty': ('घमंडी', 'ghamandi'),
    'c2-impetuous': ('उतावला', 'utaawla'),
    'c2-indolent': ('आलसी', 'aalasi'),
    'c2-mercurial': ('चंचल', 'chanchal'),
    'c2-phlegmatic': ('स्थितप्रज्ञ', 'sthitpragya'),
    'c2-obsequious': ('चापलूस', 'chaaplus'),
    'c2-petulant': ('चिड़चिड़ा', 'chidchida'),
    'c2-sanctimonious': ('आडंबरी', 'aadambari'),
    'c2-taciturn': ('मितभाषी', 'mitbhashi'),
    'c2-bountiful': ('प्रचुर', 'prachur'),
    'c2-arduous': ('श्रमसाध्य', 'shramsadhya'),
    'c2-banal': ('सपाट', 'sapaat'),
    'c2-copious': ('विपुल', 'vipul'),
    'c2-cumbersome': ('बोझिल', 'bojhil'),
    'c2-deft': ('निपुण', 'nipun'),
    'c2-dire': ('भयंकर', 'bhayankar'),
    'c2-ephemeral': ('क्षणभंगुर', 'kshanbhangur'),
    'c2-peerless': ('अद्वितीय', 'advitiya'),
    'c2-feeble': ('कमज़ोर', 'kamzor'),
    'c2-rickety': ('डगमगाता', 'dagmagata'),
    'c2-formidable': ('दुर्जेय', 'durjay'),
    'c2-immaculate': ('निष्कलंक', 'nishkalank'),
    'c2-faultless': ('निर्दोष', 'nirdosh'),
    'c2-innocuous': ('हानिरहित', 'haanirahit'),
    'c2-insidious': ('कपटी', 'kapati'),
    'c2-labyrinthine': ('भूलभुलैया जैसा', 'bhoolbhulaiya jaisa'),
    'c2-profligate': ('फिजूलखर्च', 'fizulkharch'),
    'c2-perspicuous': ('सुबोध', 'subodh'),
    'c2-sparse': ('विरल', 'viral'),
    'c2-infinitesimal': ('अत्यल्प', 'atyalp'),
    'c2-sumptuous': ('आलीशान', 'aalishaan'),
    'c2-paltry': ('तुच्छ', 'tuchchh'),
    'c2-unblemished': ('बेदाग़', 'bedaag'),
    'c2-indomitable': ('अजेय', 'ajay'),
    'c2-scant': ('अल्प', 'alp'),
    'c2-transcendent': ('पारलौकिक', 'paralaukik'),
    'c2-tenuous': ('क्षीण', 'kshin'),
    'c2-unwieldy': ('बेढब', 'bedhab'),
    'c2-boundless': ('असीम', 'aseem'),
    'c2-abstruse': ('दुर्बोध', 'durbodh'),
    'c2-apt': ('उपयुक्त', 'upyukt'),
    'c2-cogent': ('ठोस', 'thos'),
    'c2-contentious': ('विवादास्पद', 'vivadaspad'),
    'c2-deplorable': ('निंदनीय', 'nindaniya'),
    'c2-dubious': ('संदिग्ध', 'sandigdh'),
    'c2-egregious': ('घोर', 'ghor'),
    'c2-exemplary': ('अनुकरणीय', 'anukaraniya'),
    'c2-fallacious': ('भ्रामक', 'bhramak'),
    'c2-futile': ('व्यर्थ', 'vyarth'),
    'c2-gratuitous': ('अनावश्यक', 'anaavashyak'),
    'c2-illicit': ('अवैध', 'avaidh'),
    'c2-impartial': ('निष्पक्ष', 'nishpaksh'),
    'c2-incongruous': ('असंगत', 'asangat'),
    'c2-ineffable': ('अवर्णनीय', 'avarnaniya'),
    'c2-irrefutable': ('अकाट्य', 'akaatya'),
    'c2-laudable': ('प्रशंसनीय', 'prashansaniya'),
    'c2-moot': ('अप्रासंगिक', 'aprasangik'),
    'c2-nebulous': ('धुंधला', 'dhundhla'),
    'c2-ostensible': ('कथित', 'kathit'),
    'c2-pernicious': ('हानिकारक', 'haanikarak'),
    'c2-plausible': ('विश्वसनीय', 'vishwasniya'),
    'c2-preposterous': ('बेतुका', 'betuka'),
    'c2-salient': ('प्रमुख', 'pramukh'),
    'c2-spurious': ('जाली', 'jaali'),
    'c2-superfluous': ('फ़ालतू', 'faltu'),
    'c2-tenable': ('समर्थनीय', 'samarthniya'),
    'c2-untenable': ('असमर्थनीय', 'asamarthniya'),
    'c2-viable': ('व्यावहारिक', 'vyavaharik'),
    'c2-wanton': ('निरंकुश', 'nirankush'),
    'c2-ailing': ('रुग्ण', 'rugna'),
    'c2-bewildered': ('चकित', 'chakit'),
    'c2-desolate': ('उजाड़', 'ujaad'),
    'c2-brittle': ('भंगुर', 'bhangur'),
    'c2-cohesive': ('एकजुट', 'ekjut'),
    'c2-defunct': ('समाप्त', 'samapt'),
    'c2-derelict': ('परित्यक्त', 'parityakt'),
    'c2-ramshackle': ('जर्जर', 'jarjar'),
    'c2-dormant': ('निष्क्रिय', 'nishkriya'),
    'c2-drowsy': ('उनींदा', 'uneenda'),
    'c2-dwindling': ('घटता हुआ', 'ghatata hua'),
    'c2-exhilarated': ('उत्साहित', 'utsahit'),
    'c2-forlorn': ('बेसहारा', 'besahara'),
    'c2-haggard': ('क्षीणकाय', 'kshinkaay'),
    'c2-imminent': ('आसन्न', 'aasann'),
    'c2-incessant': ('अविरत', 'avirat'),
    'c2-inert': ('जड़', 'jad'),
    'c2-jaded': ('उकताया हुआ', 'uktaya hua'),
    'c2-languid': ('सुस्त', 'sust'),
    'c2-listless': ('उदासीन', 'udaseen'),
    'c2-antiquated': ('दक़ियानूसी', 'dakiyanoosi'),
    'c2-precarious': ('अस्थिर', 'asthir'),
    'c2-rampant': ('बेलगाम', 'belgaam'),
    'c2-fidgety': ('बेचैन', 'bechain'),
    'c2-rife': ('प्रचलित', 'prachalit'),
    'c2-sodden': ('तरबतर', 'tarbatar'),
    'c2-stagnant': ('रुका हुआ', 'ruka hua'),
    'c2-susceptible': ('प्रवण', 'pravan'),
    'c2-volatile': ('उतार-चढ़ाव वाला', 'utar-chadhav wala'),
    'c2-weary': ('थका हुआ', 'thaka hua'),
    'c2-bombastic': ('आडंबरपूर्ण', 'aadambarpurna'),
    'c2-vernacular': ('देशज', 'deshaj'),
    'c2-concise': ('संक्षिप्त', 'sankshipt'),
    'c2-tortuous': ('पेचीदा', 'pechida'),
    'c2-cryptic': ('गूढ़', 'goodh'),
    'c2-derogatory': ('अपमानजनक', 'apmaanjanak'),
    'c2-didactic': ('उपदेशात्मक', 'updeshaatmak'),
    'c2-silver-tongued': ('मधुरभाषी', 'madhurbhashi'),
    'c2-emphatic': ('दृढ़', 'dridh'),
    'c2-euphemistic': ('सौम्योक्तिपूर्ण', 'saumyoktipurna'),
    'c2-facetious': ('मज़ाकिया', 'mazakiya'),
    'c2-florid': ('अलंकृत', 'alankrit'),
    'c2-glib': ('चिकना-चुपड़ा', 'chikna-chupda'),
    'c2-hyperbolic': ('अतिशयोक्तिपूर्ण', 'atishayoktipurna'),
    'c2-incisive': ('पैनी', 'paini'),
    'c2-laconic': ('अल्पभाषी', 'alpabhashi'),
    'c2-long-winded': ('लंबा-चौड़ा', 'lamba-chaudha'),
    'c2-mordant': ('तीखा', 'teekha'),
    'c2-ornate': ('सजावटी', 'sajawati'),
    'c2-pedantic': ('पंडिताऊ', 'panditau'),
    'c2-pithy': ('सारगर्भित', 'saargarbhit'),
    'c2-plaintive': ('करुण', 'karun'),
    'c2-rhetorical': ('अलंकारिक', 'alankarik'),
    'c2-sardonic': ('व्यंग्यात्मक', 'vyangyaatmak'),
    'c2-scathing': ('कटु', 'katu'),
    'c2-succinct': ('सारांशित', 'saaranshit'),
    'c2-terse': ('खरा', 'khara'),
    'c2-trite': ('घिसा-पिटा', 'ghisa-pita'),
    'c2-verbose': ('शब्दाडंबरपूर्ण', 'shabdadambarpurna'),
    'c2-wry': ('तिरछा', 'tircha'),
    'c2-acumen': ('कुशाग्रबुद्धि', 'kushagrabuddhi'),
    'c2-alacrity': ('तत्परता', 'tatparta'),
    'c2-ambivalence': ('दुविधा', 'duvidha'),
    'c2-apathy': ('उदासीनता', 'udaseenta'),
    'c2-aplomb': ('आत्मविश्वास', 'aatmavishwas'),
    'c2-audacity': ('दुस्साहस', 'dussahas'),
    'c2-candor': ('स्पष्टवादिता', 'spashtavadita'),
    'c2-smugness': ('दंभ', 'dambh'),
    'c2-scorn': ('अवमानना', 'avmanana'),
    'c2-deference': ('विनयशीलता', 'vinayasheelta'),
    'c2-discretion': ('विवेक', 'vivek'),
    'c2-disdain': ('तिरस्कार', 'tiraskar'),
    'c2-forbearance': ('सहनशीलता', 'sahansheelta'),
    'c2-fortitude': ('धैर्य', 'dhairya'),
    'c2-hubris': ('अहंकार', 'ahankar'),
    'c2-meekness': ('विनम्रता', 'vinamrata'),
    'c2-umbrage': ('रोष', 'rosh'),
    'c2-ingenuity': ('सूझ-बूझ', 'soojh-boojh'),
    'c2-rectitude': ('सदाचार', 'sadachaar'),
    'c2-malice': ('द्वेष', 'dwesh'),
    'c2-nostalgia': ('यादों की टीस', 'yaadon ki tees'),
    'c2-perseverance': ('अध्यवसाय', 'adhyavasaya'),
    'c2-prudence': ('सावधानी', 'savdhani'),
    'c2-grit': ('जीवट', 'jeevat'),
    'c2-reticence': ('मौनप्रियता', 'maunapriyata'),
    'c2-equanimity': ('समभाव', 'samabhav'),
    'c2-tenacity': ('दृढ़ता', 'dridhta'),
    'c2-vanity': ('आत्ममुग्धता', 'aatmamugdhta'),
    'c2-vigilance': ('सतर्कता', 'satarkta'),
    'c2-zeal': ('उत्साह', 'utsah'),
    'c2-anomaly': ('विसंगति', 'visangati'),
    'c2-catalyst': ('उत्प्रेरक', 'utprerak'),
    'c2-conundrum': ('पहेली', 'paheli'),
    'c2-debacle': ('तबाही', 'tabahi'),
    'c2-deluge': ('सैलाब', 'sailaab'),
    'c2-dearth': ('अभाव', 'abhav'),
    'c2-dichotomy': ('द्विभाजन', 'dwibhajan'),
    'c2-epitome': ('प्रतिमूर्ति', 'pratimurti'),
    'c2-exodus': ('पलायन', 'palayan'),
    'c2-facade': ('आडंबर', 'aadambar'),
    'c2-fallacy': ('भ्रांति', 'bhranti'),
    'c2-hindsight': ('पश्चातबुद्धि', 'pashchaatbuddhi'),
    'c2-impasse': ('गतिरोध', 'gatirodh'),
    'c2-impetus': ('प्रेरणा', 'prerna'),
    'c2-juncture': ('संधिकाल', 'sandhikaal'),
    'c2-loophole': ('खामी', 'khaami'),
    'c2-tipping-point': ('निर्णायक मोड़', 'nirnayak mod'),
    'c2-onslaught': ('प्रचंड हमला', 'prachand hamla'),
    'c2-vicious-circle': ('दुष्चक्र', 'dushchakra'),
    'c2-plight': ('दुर्दशा', 'durdasha'),
    'c2-precedent': ('मिसाल', 'misaal'),
    'c2-quandary': ('असमंजस', 'asmanjas'),
    'c2-ramification': ('दूरगामी परिणाम', 'dooragami parinam'),
    'c2-respite': ('राहत', 'rahat'),
    'c2-setback': ('झटका', 'jhatka'),
    'c2-stalemate': ('बराबरी की स्थिति', 'barabari ki sthiti'),
    'c2-surge': ('उछाल', 'uchhal'),
    'c2-turmoil': ('उथल-पुथल', 'uthal-puthal'),
    'c2-upheaval': ('उलट-फेर', 'ulat-pher'),
    'c2-watershed': ('ऐतिहासिक मोड़', 'aitihasik mod'),
    'c2-accomplice': ('सहअपराधी', 'sah-apradhi'),
    'c2-adversary': ('प्रतिद्वंद्वी', 'pratidwandvi'),
    'c2-advocate': ('पैरोकार', 'pairokaar'),
    'c2-benefactor': ('परोपकारी', 'paropkari'),
    'c2-bystander': ('मूकदर्शक', 'mookdarshak'),
    'c2-charlatan': ('ढोंगी', 'dhongi'),
    'c2-connoisseur': ('पारखी', 'paarkhi'),
    'c2-culprit': ('अपराधी', 'apradhi'),
    'c2-demagogue': ('भड़काऊ नेता', 'bhadkau neta'),
    'c2-dilettante': ('शौकिया', 'shaukiya'),
    'c2-envoy': ('दूत', 'doot'),
    'c2-lackey': ('पिछलग्गू', 'pichhlaggu'),
    'c2-understudy': ('विकल्प कलाकार', 'vikalp kalakar'),
    'c2-hypocrite': ('पाखंडी', 'pakhandi'),
    'c2-insurgent': ('विद्रोही', 'vidrohi'),
    'c2-layperson': ('अनभिज्ञ व्यक्ति', 'anabhigya vyakti'),
    'c2-maverick': ('स्वतंत्र विचारक', 'swatantra vichaarak'),
    'c2-sidekick': ('सहचर', 'sahchar'),
    'c2-mercenary': ('भाड़े का सैनिक', 'bhade ka sainik'),
    'c2-novice': ('नौसिखिया', 'nausikhiya'),
    'c2-pariah': ('अछूत', 'achhoot'),
    'c2-patron': ('संरक्षक', 'sanrakshak'),
    'c2-perpetrator': ('अपराधकर्ता', 'apradhkarta'),
    'c2-prodigy': ('विलक्षण प्रतिभा', 'vilakshan pratibha'),
    'c2-informant': ('मुखबिर', 'mukhbir'),
    'c2-recluse': ('एकांतवासी', 'ekantavasi'),
    'c2-sage': ('ऋषि', 'rishi'),
    'c2-turncoat': ('दलबदलू', 'dalbadlu'),
    'c2-stalwart': ('दृढ़ समर्थक', 'dridh samarthak'),
    'c2-tycoon': ('उद्योगपति', 'udyogpati'),
    'c2-ambiguity': ('अस्पष्टता', 'aspashtata'),
    'c2-analogy': ('सादृश्य', 'saadrishya'),
    'c2-axiom': ('स्वयंसिद्ध', 'swayamsiddh'),
    'c2-caveat': ('शर्त', 'shart'),
    'c2-consensus': ('सर्वसम्मति', 'sarvasammati'),
    'c2-corollary': ('स्वाभाविक परिणाम', 'swabhavik parinam'),
    'c2-yardstick': ('मापदंड', 'mapdand'),
    'c2-narrative': ('आख्यान', 'aakhyan'),
    'c2-doctrine': ('सिद्धांत', 'siddhant'),
    'c2-dogma': ('हठधर्मिता', 'hathdharmita'),
    'c2-epiphany': ('बोधोदय', 'bodhoday'),
    'c2-ethos': ('लोकाचार', 'lokachar'),
    'c2-conjecture': ('अटकल', 'atkal'),
    'c2-idiosyncrasy': ('व्यक्तिगत विचित्रता', 'vyaktigat vichitrata'),
    'c2-deduction': ('निष्कर्ष', 'nishkarsh'),
    'c2-innuendo': ('व्यंग्योक्ति', 'vyangyokti'),
    'c2-buzzword': ('प्रचलित शब्दजाल', 'prachalit shabdjaal'),
    'c2-simile': ('उपमा', 'upama'),
    'c2-nuance': ('सूक्ष्म भेद', 'sookshma bhed'),
    'c2-archetype': ('आद्यरूप', 'aadyaroop'),
    'c2-platitude': ('रटा-रटाया वाक्य', 'rata-rataya vakya'),
    'c2-postulate': ('अभिगृहीत', 'abhigriheet'),
    'c2-pretext': ('बहाना', 'bahana'),
    'c2-rebuttal': ('प्रत्युत्तर', 'pratyuttar'),
    'c2-rhetoric': ('अलंकारशास्त्र', 'alankarshastra'),
    'c2-semantics': ('अर्थविज्ञान', 'arthavigyan'),
    'c2-stigma': ('कलंक', 'kalank'),
    'c2-tenet': ('मान्यता', 'manyata'),
    'c2-trope': ('रूढ़ बिंब', 'rudh bimb'),
    'c2-zeitgeist': ('युगचेतना', 'yugchetna'),
    'c2-acrid': ('उग्र', 'ugra'),
    'c2-astringent': ('कसैला', 'kasaila'),
    'c2-bland-flavorless': ('बेस्वाद', 'beswaad'),
    'c2-brackish': ('खारा', 'khaara'),
    'c2-cloying': ('अतिमीठा', 'atimeetha'),
    'c2-coarse': ('खुरदुरा', 'khurdura'),
    'c2-creamy': ('मलाईदार', 'malaidar'),
    'c2-crunchy': ('कुरकुरा', 'kurkura'),
    'c2-dank': ('सीलनयुक्त', 'seelanyukt'),
    'c2-earthy': ('मिट्टी जैसा', 'mitti jaisa'),
    'c2-fragrant': ('सुगंधित', 'sugandhit'),
    'c2-gooey': ('लसलसा', 'laslasa'),
    'c2-grainy': ('दानेदार', 'daanedar'),
    'c2-unctuous': ('चिकनाईयुक्त', 'chiknaiyukt'),
    'c2-gravelly-voice': ('खरखराती आवाज़ वाला', 'kharkharati awaaz wala'),
    'c2-luscious': ('रसीला', 'rasila'),
    'c2-mellow': ('सुमधुर', 'sumadhur'),
    'c2-hushed': ('धीमा', 'dheema'),
    'c2-musty': ('फफूंदी जैसी गंध वाला', 'fafoondi jaisi gandh wala'),
    'c2-piercing': ('चुभने वाला', 'chubhne wala'),
    'c2-pungent': ('तेज़', 'tez'),
    'c2-putrid': ('सड़ा हुआ', 'sada hua'),
    'c2-rancid': ('बासी', 'basi'),
    'c2-bitter-aftertaste': ('बाद में कड़वाहट', 'baad mein kadvahat'),
    'c2-grating-sound': ('कर्कश', 'karkash'),
    'c2-silky': ('रेशमी', 'reshmi'),
    'c2-slimy': ('चिपचिपा', 'chipchipa'),
    'c2-soggy': ('गीला व मुलायम', 'geela va mulayam'),
    'c2-tangy': ('चटपटा', 'chatpata'),
    'c2-zesty': ('मसालेदार', 'masaledar'),
    'c2-better-late-than-never': ('देर आए दुरुस्त आए', 'der aaye durust aaye'),
    'c2-actions-speak-louder-than-words': ('करनी बोलती है, कथनी नहीं', 'karni bolti hai, kathni nahi'),
    'c2-the-early-bird-catches-the-worm': ('जो जागे सो पावे', 'jo jage so pave'),
    "c2-don-t-count-your-chickens-before-they-hatch": ("अंडे सेने से पहले चूज़े मत गिनो", "ande sene se pehle chooze mat gino"),
    'c2-every-cloud-has-a-silver-lining': ('हर अंधेरे के बाद उजाला होता है', 'har andhere ke baad ujala hota hai'),
    'c2-practice-makes-perfect': ('करत करत अभ्यास के जड़मति होत सुजान', 'karat karat abhyas ke jadmati hot sujan'),
    'c2-when-in-rome-do-as-the-romans-do': ('जैसा देस वैसा भेस', 'jaisa des vaisa bhes'),
    'c2-two-heads-are-better-than-one': ('एक से भले दो', 'ek se bhale do'),
    'c2-the-grass-is-always-greener-on-the-other-side': ('दूर के ढोल सुहावने', 'door ke dhol suhavne'),
    "c2-don-t-judge-a-book-by-its-cover": ("सूरत पर मत जाओ, सीरत परखो", "surat par mat jao, seerat parkho"),
    'c2-birds-of-a-feather-flock-together': ('एक ही थैली के चट्टे-बट्टे', 'ek hi thaili ke chatte-batte'),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('नौ नकद न तेरह उधार', 'nau nakad na terah udhaar'),
    "c2-where-there-s-a-will-there-s-a-way": ("जहाँ चाह वहाँ राह", "jahan chah wahan raah"),
    "c2-rome-wasn-t-built-in-a-day": ("रोम एक दिन में नहीं बना", "Rome ek din mein nahi bana"),
    'c2-too-many-cooks-spoil-the-broth': ('अधिक जोगी मठ उजाड़', 'adhik jogi math ujaad'),
    'c2-out-of-sight-out-of-mind': ('आँख से दूर, दिल से दूर', 'aankh se door, dil se door'),
    'c2-look-before-you-leap': ('सोच-समझकर कदम बढ़ाओ', 'soch-samajhkar kadam badhao'),
    'c2-necessity-is-the-mother-of-invention': ('आवश्यकता आविष्कार की जननी है', 'aavashyakta avishkar ki janani hai'),
    "c2-you-can-t-have-your-cake-and-eat-it-too": ("एक साथ दो नावों की सवारी नहीं हो सकती", "ek saath do naavon ki sawari nahi ho sakti"),
    'c2-honesty-is-the-best-policy': ('ईमानदारी सबसे अच्छी नीति है', 'imandari sabse achi neeti hai'),
    'c2-still-waters-run-deep': ('ठहरा पानी गहरा होता है', 'thehra pani gehra hota hai'),
    'c2-blood-is-thicker-than-water': ('खून का रिश्ता पानी से गाढ़ा होता है', 'khoon ka rishta pani se gadha hota hai'),
    'c2-absence-makes-the-heart-grow-fonder': ('दूरियां प्यार बढ़ाती हैं', 'dooriyan pyar badhati hain'),
    'c2-every-dog-has-its-day': ('हर किसी का अच्छा वक़्त ज़रूर आता है', 'har kisi ka accha waqt zaroor aata hai'),
    'c2-haste-makes-waste': ('जल्दी का काम शैतान का', 'jaldi ka kaam shaitan ka'),
    'c2-let-sleeping-dogs-lie': ('सोते हुए शेर को मत छेड़ो', 'sote hue sher ko mat chhedo'),
    'c2-strike-while-the-iron-is-hot': ('लोहा गरम है, मार दो हथौड़ा', 'loha garam hai, maar do hathauda'),
    'c2-the-pen-is-mightier-than-the-sword': ('क़लम तलवार से बड़ी है', 'qalam talwar se badi hai'),
    'c2-curiosity-killed-the-cat': ('ज़्यादा जिज्ञासा मुसीबत लाती है', 'zyada jigyasa museebat lati hai'),
    "c2-beggars-can-t-be-choosers": ("मांगने वाले को चुनने का हक नहीं", "mangne wale ko chunne ka haq nahi"),
    'c2-to-draw-a-distinction': ('भेद करना', 'bhed karna'),
    'c2-to-reach-a-verdict': ('फैसला सुनाना', 'faisla sunana'),
    'c2-to-pose-a-threat': ('खतरा उत्पन्न करना', 'khatra utpann karna'),
    'c2-to-bear-the-brunt': ('सबसे ज़्यादा नुकसान झेलना', 'sabse zyada nuksan jhelna'),
    'c2-to-lend-credence-to': ('विश्वसनीयता प्रदान करना', 'vishwasniyata pradan karna'),
    'c2-to-wield-influence': ('प्रभाव रखना', 'prabhav rakhna'),
    'c2-to-incur-a-cost': ('लागत वहन करना', 'laagat vahan karna'),
    'c2-to-uphold-a-principle': ('सिद्धांत को बनाए रखना', 'siddhant ko banaye rakhna'),
    'c2-to-exert-pressure': ('दबाव डालना', 'dabaav daalna'),
    'c2-to-fulfil-an-obligation': ('दायित्व पूरा करना', 'dayitva pura karna'),
    'c2-to-cast-doubt-on': ('संदेह उत्पन्न करना', 'sandeh utpann karna'),
    'c2-to-pay-tribute-to': ('श्रद्धांजलि देना', 'shraddhanjali dena'),
    'c2-to-take-precedence-over': ('से अधिक प्राथमिकता रखना', 'se adhik prathmikta rakhna'),
    'c2-to-run-the-risk-of': ('का जोखिम उठाना', 'ka jokhim uthana'),
    'c2-to-strike-a-balance': ('संतुलन बनाना', 'santulan banana'),
    'c2-to-come-to-fruition': ('साकार होना', 'saakar hona'),
    'c2-to-shed-light-on': ('प्रकाश डालना', 'prakash daalna'),
    'c2-to-set-a-precedent': ('मिसाल कायम करना', 'misaal kayam karna'),
    'c2-to-give-rise-to': ('को जन्म देना', 'ko janm dena'),
    'c2-to-take-issue-with': ('पर आपत्ति जताना', 'par aapatti jatana'),
    'c2-pursuant-to': ('के अनुसरण में', 'ke anusaran mein'),
    'c2-heretofore': ('अब तक', 'ab tak'),
    'c2-inasmuch-as': ('चूंकि', 'choonki'),
    'c2-in-conjunction-with': ('के साथ मिलकर', 'ke saath milkar'),
    'c2-hitherto': ('इससे पहले', 'isse pehle'),
    'c2-forthwith': ('तुरंत', 'turant'),
    'c2-whilst': ('जबकि', 'jabki'),
    'c2-wherein': ('जिसमें', 'jismein'),
    'c2-vis-a-vis': ('की तुलना में', 'ki tulna mein'),
    'c2-as-regards': ('के संबंध में', 'ke sambandh mein'),
    'c2-for-the-sake-of-argument': ('तर्क के लिए मान लें', 'tark ke liye maan len'),
    'c2-be-that-as-it-may': ('जो भी हो', 'jo bhi ho'),
    'c2-on-balance': ('कुल मिलाकर', 'kul milakar'),
    'c2-at-the-behest-of': ('के कहने पर', 'ke kehne par'),
    'c2-in-the-wake-of': ('के परिणामस्वरूप', 'ke parinaamswarup'),
    'c2-on-the-grounds-that': ('इस आधार पर कि', 'is aadhar par ki'),
    'c2-in-accordance-with': ('के अनुसार', 'ke anusaar'),
    'c2-pending': ('लंबित', 'lambit'),
    'c2-irrespective-of': ('की परवाह किए बिना', 'ki parwah kiye bina'),
    'c2-hereinafter': ('इसके बाद', 'iske baad'),
    'c2-beats-me': ('मुझे नहीं पता', 'mujhe nahi pata'),
    'c2-point-taken': ('बात समझ में आ गई', 'baat samajh mein aa gayi'),
    'c2-suit-yourself': ('जैसी तुम्हारी मर्ज़ी', 'jaisi tumhari marzi'),
    'c2-go-figure': ('कौन जाने क्यों', 'kaun jaane kyun'),
    "c2-don-t-get-me-started": ("मुझे मत छेड़ो इस बारे में", "mujhe mat chhedo is bare mein"),
    'c2-bottom-line-is': ('बात यह है कि', 'baat yah hai ki'),
    'c2-off-the-top-of-my-head': ('जो अभी दिमाग़ में आया', 'jo abhi dimaag mein aaya'),
    "c2-i-ll-say": ("बिल्कुल सही कहा", "bilkul sahi kaha"),
    "c2-you-ve-got-to-be-kidding-me": ("तुम मज़ाक कर रहे हो क्या", "tum mazak kar rahe ho kya"),
    "c2-no-offense-but": ("बुरा मत मानना, लेकिन", "bura mat maanna, lekin"),
    "c2-i-m-not-gonna-lie": ("सच कहूं तो", "sach kahun to"),
    'c2-speak-of-the-devil': ('नाम लो और हाज़िर हो जाओ', 'naam lo aur haazir ho jao'),
    "c2-it-s-on-the-tip-of-my-tongue": ("ज़ुबान पर है", "zubaan par hai"),
    "c2-let-s-call-it-a-day": ("आज के लिए इतना ही", "aaj ke liye itna hi"),
    "c2-it-s-not-rocket-science": ("इसमें कौन सी बड़ी बात है", "isme kaun si badi baat hai"),
    "c2-that-s-the-last-straw": ("अब बर्दाश्त की हद हो गई", "ab bardaasht ki had ho gayi"),
    "c2-i-couldn-t-care-less": ("मुझे कोई फ़र्क़ नहीं पड़ता", "mujhe koi farq nahi padta"),
    'c2-what-are-the-odds': ('क्या इत्तेफ़ाक़ है', 'kya ittefaq hai'),
    'c2-say-no-more': ('बस, समझ गया', 'bas, samajh gaya'),
    'c2-hang-in-there': ('हिम्मत रखो', 'himmat rakho'),
    "c2-i-m-all-ears": ("मैं ध्यान से सुन रहा हूं", "main dhyan se sun raha hoon"),
    "c2-that-s-on-me": ("यह मेरी ग़लती है", "yeh meri galti hai"),
    'c2-no-hard-feelings': ('कोई बुरा मत मानना', 'koi bura mat maanna'),
    'c2-ditto': ('वही बात', 'wahi baat'),
    'c2-spill-the-beans': ('राज़ खोल दो', 'raaz khol do'),
    'c2-in-one-ear-and-out-the-other': ('एक कान से सुनना दूसरे से निकालना', 'ek kaan se sunna dusre se nikalna'),
    'c2-cut-to-the-chase': ('सीधे मुद्दे पर आओ', 'seedhe mudde par aao'),
    'c2-you-name-it': ('जो भी चाहो', 'jo bhi chaho'),
    'c2-not-in-a-million-years': ('किसी भी सूरत में नहीं', 'kisi bhi soorat mein nahi'),
    "c2-it-is-what-it-is": ("जो है सो है", "jo hai so hai"),
    'c2-give-me-a-break': ('बस भी करो', 'bas bhi karo'),
    'c2-hold-your-horses': ('थोड़ा रुको', 'thoda ruko'),
    'c2-bite-the-bullet': ('हिम्मत करके सामना करना', 'himmat karke samna karna'),
    'c2-take-it-with-a-grain-of-salt': ('पूरी तरह मत मान लेना', 'poori tarah mat maan lena'),
    'c2-better-safe-than-sorry': ('सावधानी बरतना ही बेहतर है', 'savdhani baratna hi behtar hai'),
    "c2-let-s-play-it-by-ear": ("जैसा वक़्त बताएगा वैसा करेंगे", "jaisa waqt batayega vaisa karenge"),
    "c2-i-ll-take-a-rain-check": ("फिर कभी सही", "phir kabhi sahi"),
    "c2-for-what-it-s-worth": ("अगर इससे कोई फ़र्क़ पड़े तो", "agar isse koi farq pade to"),
    'c2-back-to-square-one': ('फिर वहीं के वहीं', 'phir wahin ke wahin'),
    'c2-touch-wood': ('मैं लकड़ी छूता हूं', 'main lakdi chhoota hoon'),
    'c2-allusion': ('संकेत', 'sanket'),
    'c2-anecdote': ('किस्सा', 'kissa'),
    'c2-antithesis': ('विलोम', 'vilom'),
    'c2-aphorism': ('सूक्ति', 'sookti'),
    'c2-banter': ('हंसी-मज़ाक', 'hansi-mazak'),
    'c2-circumlocution': ('घुमावदार वर्णन', 'ghumavdar varnan'),
    'c2-cliche': ('घिसी-पिटी बात', 'ghisi-piti baat'),
    'c2-connotation': ('भावार्थ', 'bhavarth'),
    'c2-digression': ('विषयांतर', 'vishayantar'),
    'c2-double-entendre': ('दोहरा अर्थ', 'dohra arth'),
    'c2-eloquence': ('वाक्पटुता', 'vakpatuta'),
    'c2-euphemism': ('सौम्योक्ति', 'saumyokti'),
    'c2-gist': ('सार', 'saar'),
    'c2-hyperbole': ('अतिशयोक्ति', 'atishayokti'),
    'c2-irony': ('विडंबना', 'vidambana'),
    'c2-juxtaposition': ('सह-स्थापन', 'sah-sthapan'),
    'c2-malapropism': ('शब्द-भ्रम', 'shabd-bhram'),
    'c2-oxymoron': ('विरोधाभासी युग्म', 'virodhabhasi yugma'),
    'c2-paraphrase': ('पुनर्कथन', 'punarkathan'),
    'c2-pun': ('श्लेष', 'shlesh'),
    'c2-quip': ('चुटीली टिप्पणी', 'chutili tippani'),
    'c2-sarcasm': ('व्यंग्य', 'vyangya'),
    'c2-slur-insult': ('अपशब्द', 'apshabd'),
    'c2-repartee': ('चुटीला प्रत्युत्तर', 'chutila pratyuttar'),
    'c2-soliloquy': ('स्वगत भाषण', 'swagat bhashan'),
    'c2-subtext': ('अंतर्निहित अर्थ', 'antarnihit arth'),
    'c2-tangent': ('मूल विषय से भटकाव', 'mool vishay se bhatkaav'),
    'c2-tirade': ('क्रोधपूर्ण भाषण', 'krodhpurna bhashan'),
    'c2-understatement': ('अल्पोक्ति', 'alpokti'),
    'c2-verbiage': ('शब्दाडंबर', 'shabdadambar'),
    'c2-to-allude-to': ('संकेत करना', 'sanket karna'),
    'c2-to-enunciate': ('स्पष्ट उच्चारण करना', 'spasht uchcharan karna'),
    'c2-to-belabor-the-point': ('बात को बार-बार दोहराना', 'baat ko baar-baar dohrana'),
    'c2-to-digress': ('विषयांतर करना', 'vishayantar karna'),
    'c2-to-expound': ('विस्तार से समझाना', 'vistar se samjhana'),
    'c2-to-insinuate': ('परोक्ष आरोप लगाना', 'paroksh aarop lagana'),
    'c2-to-interject': ('बीच में बोलना', 'beech mein bolna'),
    'c2-to-hammer-home': ('ज़ोर देकर समझाना', 'zor dekar samjhana'),
    'c2-to-retort': ('पलटवार करना', 'paltvaar karna'),
    'c2-to-waffle-be-vague': ('टालमटोल करना', 'taalmatol karna'),
    'c2-actuary': ('बीमांकिक', 'bimankik'),
    'c2-anesthesiologist': ('निश्चेतक चिकित्सक', 'nishchetak chikitsak'),
    'c2-archivist': ('अभिलेखपाल', 'abhilekhpal'),
    'c2-auditor': ('लेखा परीक्षक', 'lekha parikshak'),
    'c2-bailiff': ('न्यायालय अधिकारी', 'nyayalay adhikari'),
    'c2-blacksmith': ('लोहार', 'lohar'),
    'c2-cartographer': ('मानचित्रकार', 'manachitrakar'),
    'c2-chiropractor': ('हड्डी समायोजन विशेषज्ञ', 'haddi samayojan visheshagya'),
    'c2-coroner': ('शव परीक्षक', 'shav parikshak'),
    'c2-curator': ('संग्रहाध्यक्ष', 'sangrahadhyaksh'),
    'c2-diplomat': ('राजनयिक', 'rajnayik'),
    'c2-dietitian': ('आहार विशेषज्ञ', 'aahar visheshagya'),
    'c2-entomologist': ('कीटविज्ञानी', 'keetvigyani'),
    'c2-forensic-scientist': ('न्यायालयिक वैज्ञानिक', 'nyayalayik vaigyanik'),
    'c2-geologist': ('भूविज्ञानी', 'bhoovigyani'),
    'c2-glazier': ('शीशासाज़', 'sheeshasaz'),
    'c2-interpreter-simultaneous': ('दुभाषिया', 'dubhashiya'),
    'c2-locksmith': ('तालासाज़', 'talasaz'),
    'c2-midwife': ('दाई', 'dai'),
    'c2-court-clerk': ('न्यायालय लिपिक', 'nyayalay lipik'),
    'c2-oncologist': ('अर्बुद रोग विशेषज्ञ', 'arbud rog visheshagya'),
    'c2-ophthalmologist': ('नेत्र रोग विशेषज्ञ', 'netra rog visheshagya'),
    'c2-paleontologist': ('जीवाश्मविज्ञानी', 'jeevashmavigyani'),
    'c2-paralegal': ('विधि सहायक', 'vidhi sahayak'),
    'c2-pathologist': ('रोगविज्ञानी', 'rogvigyani'),
    'c2-physiotherapist': ('भौतिक चिकित्सक', 'bhautik chikitsak'),
    'c2-public-defender': ('शासकीय बचाव अधिवक्ता', 'shaskiya bachav adhivakta'),
    'c2-radiologist': ('विकिरण विशेषज्ञ', 'vikiran visheshagya'),
    'c2-perfumer': ('इत्रसाज़', 'itrasaz'),
    'c2-stenographer': ('आशुलिपिक', 'aashulipik'),
    'c2-surveyor': ('भूमि सर्वेक्षक', 'bhoomi sarvekshak'),
    'c2-taxidermist': ('पशुशव-संरक्षक', 'pashushav-sanrakshak'),
    'c2-upholsterer': ('गद्दीसाज़', 'gaddisaz'),
    'c2-veterinarian-specialist': ('पशु चिकित्सक', 'pashu chikitsak'),
    'c2-welder': ('वेल्डर', 'veldar'),
    'c2-anthropology': ('मानवविज्ञान', 'manavavigyan'),
    'c2-archaeology': ('पुरातत्व विज्ञान', 'puratatva vigyan'),
    'c2-astrophysics': ('खगोल भौतिकी', 'khagol bhautiki'),
    'c2-biochemistry': ('जैव रसायन विज्ञान', 'jaiv rasayan vigyan'),
    'c2-botany': ('वनस्पति विज्ञान', 'vanaspati vigyan'),
    'c2-cartography': ('मानचित्रकला', 'manachitrakala'),
    'c2-criminology': ('अपराध विज्ञान', 'apradh vigyan'),
    'c2-demography': ('जनसांख्यिकी', 'janasankhyiki'),
    'c2-econometrics': ('अर्थमिति', 'arthmiti'),
    'c2-epidemiology': ('महामारी विज्ञान', 'mahamari vigyan'),
    'c2-epistemology': ('ज्ञानमीमांसा', 'gyanmimamsa'),
    'c2-ethnography': ('नृजाति विज्ञान', 'nrijati vigyan'),
    'c2-genetics': ('आनुवंशिकी', 'aanuvanshiki'),
    'c2-geopolitics': ('भूराजनीति', 'bhoorajniti'),
    'c2-hermeneutics': ('व्याख्याशास्त्र', 'vyakhyashastra'),
    'c2-immunology': ('प्रतिरक्षा विज्ञान', 'pratiraksha vigyan'),
    'c2-jurisprudence': ('न्यायशास्त्र', 'nyayashastra'),
    'c2-linguistics': ('भाषाविज्ञान', 'bhashavigyan'),
    'c2-metaphysics': ('तत्वमीमांसा', 'tatvamimamsa'),
    'c2-meteorology': ('मौसम विज्ञान', 'mausam vigyan'),
    'c2-microbiology': ('सूक्ष्मजीव विज्ञान', 'sookshmajeev vigyan'),
    'c2-musicology': ('संगीतशास्त्र', 'sangeetshastra'),
    'c2-neuroscience': ('तंत्रिका विज्ञान', 'tantrika vigyan'),
    'c2-oceanography': ('समुद्र विज्ञान', 'samudra vigyan'),
    'c2-ornithology': ('पक्षी विज्ञान', 'pakshi vigyan'),
    'c2-pedagogy': ('शिक्षाशास्त्र', 'shikshashastra'),
    'c2-pharmacology': ('औषधि विज्ञान', 'aushadhi vigyan'),
    'c2-philology': ('प्राचीन भाषा अध्ययन', 'prachin bhasha adhyayan'),
    'c2-phonetics': ('स्वनविज्ञान', 'swanvigyan'),
    'c2-seismology': ('भूकंप विज्ञान', 'bhookamp vigyan'),
    'c2-semiotics': ('संकेतविज्ञान', 'sanketvigyan'),
    'c2-sociolinguistics': ('समाजभाषाविज्ञान', 'samajbhashavigyan'),
    'c2-theology': ('धर्मशास्त्र', 'dharmashastra'),
    'c2-toxicology': ('विषविज्ञान', 'vishvigyan'),
    'c2-zoology': ('प्राणिविज्ञान', 'praanivigyan'),
    'c2-acute-sudden-severe': ('तीव्र', 'teevra'),
    'c2-latent': ('सुप्त', 'supt'),
    'c2-benign': ('सौम्य', 'saumya'),
    'c2-malignant': ('घातक', 'ghatak'),
    'c2-biopsy': ('जीव ऊतक परीक्षण', 'jeev ootak parikshan'),
    'c2-prognosis': ('रोग-पूर्वानुमान', 'rog-purvanuman'),
    'c2-flare-up': ('अचानक तीव्रता', 'achanak teevrata'),
    'c2-recurrence': ('पुनरावृत्ति', 'punaravritti'),
    'c2-sedative': ('शामक', 'shaamak'),
    'c2-anesthetic': ('निश्चेतक', 'nishchetak'),
    'c2-antibody': ('प्रतिरक्षी', 'pratirakshi'),
    'c2-inflammation': ('सूजन', 'soojan'),
    'c2-airborne': ('वायुजनित', 'vayujanit'),
    'c2-hereditary': ('वंशानुगत', 'vanshanugat'),
    'c2-congenital': ('जन्मजात', 'janmajat'),
    'c2-dosage': ('मात्रा', 'matra'),
    'c2-placebo': ('मिथ्या औषधि', 'mithya aushadhi'),
    'c2-contraindication': ('प्रतिनिषेध', 'pratinishedh'),
    'c2-intravenous': ('अंतःशिरा', 'antahshira'),
    'c2-suture': ('टांका', 'taanka'),
    'c2-incision': ('चीरा', 'cheera'),
    'c2-donor': ('दाता', 'data'),
    'c2-ultrasound': ('ध्वनितरंग परीक्षण', 'dhwanitarang parikshan'),
    'c2-referral-to-a-specialist': ('विशेषज्ञ के पास भेजना', 'visheshagya ke paas bhejna'),
    'c2-inpatient': ('भर्ती रोगी', 'bharti rogi'),
    'c2-palliative-care': ('उपशामक देखभाल', 'upshamak dekhbhal'),
    'c2-triage': ('रोगी वर्गीकरण', 'rogi vargikaran'),
    'c2-convalescence': ('स्वास्थ्यलाभ', 'swasthyalabh'),
    'c2-immunity': ('प्रतिरक्षा', 'pratiraksha'),
    'c2-pandemic': ('महामारी', 'mahamari'),
    'c2-pathogen': ('रोगजनक', 'rogjanak'),
    'c2-electrolyte': ('विद्युत-अपघट्य', 'vidyut-apghatya'),
    'c2-cardiovascular': ('हृदय-संवहनी', 'hriday-sanvahani'),
    'c2-respiratory': ('श्वसन संबंधी', 'shwasan sambandhi'),
    'c2-neurological': ('तंत्रिका संबंधी', 'tantrika sambandhi'),
    'c2-symptomatic': ('लक्षणात्मक', 'lakshanaatmak'),
    'c2-asymptomatic': ('अलक्षणात्मक', 'alakshanaatmak'),
    'c2-prescription-written-order': ('नुस्खा', 'nuskha'),
    'c2-generic-drug': ('सामान्य औषधि', 'samanya aushadhi'),
    'c2-informed-consent': ('सूचित सहमति', 'soochit sahmati'),
    'c2-acquittal': ('दोषमुक्ति', 'doshmukti'),
    'c2-conviction-guilty-verdict': ('दोषसिद्धि', 'doshsiddhi'),
    'c2-deposition': ('बयान', 'bayan'),
    'c2-accessory-to-a-crime': ('अपराध में सहयोगी', 'apradh mein sahyogi'),
    'c2-arson': ('आगजनी', 'aagjani'),
    'c2-remand': ('न्यायिक हिरासत', 'nyayik hirasat'),
    'c2-burden-of-proof': ('सबूत का भार', 'saboot ka bhaar'),
    'c2-custody-detention': ('हिरासत', 'hirasat'),
    'c2-defendant': ('प्रतिवादी', 'prativadi'),
    'c2-plaintiff': ('वादी', 'vadi'),
    'c2-embezzlement': ('गबन', 'gaban'),
    'c2-extortion': ('जबरन वसूली', 'jabaran vasooli'),
    'c2-felony': ('गंभीर अपराध', 'gambhir apradh'),
    'c2-misdemeanor': ('लघु अपराध', 'laghu apradh'),
    'c2-forgery': ('जालसाजी', 'jaalsaji'),
    'c2-hearsay': ('सुनी-सुनाई बात', 'suni-sunai baat'),
    'c2-indictment': ('अभियोग', 'abhiyog'),
    'c2-injunction': ('निषेधाज्ञा', 'nishedhagya'),
    'c2-tribunal': ('अधिकरण', 'adhikaran'),
    'c2-libel': ('लिखित मानहानि', 'likhit maanhani'),
    'c2-slander': ('मौखिक मानहानि', 'maukhik maanhani'),
    'c2-manslaughter': ('अनैच्छिक हत्या', 'anaichchhik hatya'),
    'c2-parole': ('सशर्त रिहाई', 'sashart rihai'),
    'c2-perjury': ('झूठी गवाही', 'jhoothi gawahi'),
    'c2-plea-bargain': ('अभियोग समझौता', 'abhiyog samjhauta'),
    'c2-probation': ('परिवीक्षा', 'pariveeksha'),
    'c2-racketeering': ('संगठित जबरन वसूली', 'sangathit jabaran vasooli'),
    'c2-ransom': ('फिरौती', 'firauti'),
    'c2-statute': ('अधिनियम', 'adhiniyam'),
    'c2-statute-of-limitations': ('परिसीमा अवधि', 'parisima avadhi'),
    'c2-subpoena': ('न्यायालय समन', 'nyayalay saman'),
    'c2-testimony': ('गवाही', 'gawahi'),
    'c2-ruling': ('निर्णय', 'nirnay'),
    'c2-warrant': ('गिरफ़्तारी आदेश', 'giraftari aadesh'),
    'c2-witness-stand': ('गवाह कठघरा', 'gawah kathghara'),
    'c2-contempt-of-court': ('न्यायालय की अवमानना', 'nyayalay ki avmanana'),
    'c2-cross-examination': ('जिरह', 'jirah'),
    'c2-mistrial': ('अमान्य मुक़दमा', 'amanya muqadma'),
    'c2-sentence-punishment': ('सज़ा', 'saza'),
    'c2-to-plead-guilty': ('दोष स्वीकार करना', 'dosh svikar karna'),
    'c2-thicket': ('झाड़ी', 'jhadi'),
    'c2-undergrowth': ('झाड़-झंखाड़', 'jhaad-jhankhad'),
    'c2-moss': ('काई', 'kai'),
    'c2-lichen': ('लाइकेन', 'laiken'),
    'c2-fern': ('फर्न', 'fern'),
    'c2-sap': ('रस', 'ras'),
    'c2-bark-of-a-tree': ('छाल', 'chhaal'),
    'c2-sapling': ('पौध', 'paudh'),
    'c2-canopy-forest': ('वृक्ष-छत्र', 'vriksha-chhatra'),
    'c2-grove': ('उपवन', 'upvan'),
    'c2-meadow': ('घास का मैदान', 'ghaas ka maidan'),
    'c2-marsh': ('दलदल', 'daldal'),
    'c2-bog': ('कच्छ भूमि', 'kachchh bhoomi'),
    'c2-estuary': ('नदमुख', 'nadmukh'),
    'c2-tributary': ('सहायक नदी', 'sahayak nadi'),
    'c2-ravine': ('खड्ड', 'khadd'),
    'c2-gorge': ('गहरी घाटी', 'gehri ghati'),
    'c2-ridge': ('कटक', 'katak'),
    'c2-summit': ('शिखर', 'shikhar'),
    'c2-foothills': ('तराई', 'tarai'),
    'c2-escarpment': ('खड़ी चट्टान', 'khadi chattan'),
    'c2-salt-flat': ('नमक का मैदान', 'namak ka maidan'),
    'c2-cove': ('छोटी खाड़ी', 'chhoti khadi'),
    'c2-atoll': ('प्रवाल द्वीप', 'praval dweep'),
    'c2-tide-pool': ('ज्वारीय पोखर', 'jwariya pokhar'),
    'c2-driftwood': ('बहती हुई लकड़ी', 'bahti hui lakdi'),
    'c2-pebble': ('कंकड़', 'kankad'),
    'c2-boulder': ('शिलाखंड', 'shilakhand'),
    'c2-sediment': ('तलछट', 'talchhat'),
    'c2-erosion': ('अपरदन', 'aparadan'),
    'c2-burrow': ('बिल', 'bil'),
    'c2-hive': ('छत्ता', 'chhatta'),
    'c2-cocoon': ('कोया', 'koya'),
    'c2-antler': ('सींग', 'seeng'),
    'c2-talon': ('पंजा', 'panja'),
    'c2-plumage': ('पिच्छावली', 'pichchhavali'),
    'c2-migration-animal': ('प्रवासन', 'pravasan'),
    'c2-hibernation': ('शीतनिष्क्रियता', 'sheetnishkriyata'),
    'c2-pollination': ('परागण', 'paragan'),
    'c2-germination': ('अंकुरण', 'ankuran'),
    'c2-torrential': ('मूसलाधार', 'moosladhar'),
    'c2-monsoon': ('मानसून', 'monsoon'),
    'c2-sleet': ('मिश्रित हिम-वर्षा', 'mishrit him-varsha'),
    'c2-flurry-snow': ('हल्की बर्फ़बारी', 'halki barfbari'),
    'c2-whiteout': ('श्वेत अंधकार', 'shwet andhakar'),
    'c2-black-ice': ('काली बर्फ़', 'kaali barf'),
    'c2-dew': ('ओस', 'os'),
    'c2-haze': ('धुंध', 'dhundh'),
    'c2-clammy': ('नम व ठंडा', 'nam va thanda'),
    'c2-scorcher': ('झुलसाने वाला दिन', 'jhulsane wala din'),
    'c2-sultry': ('उमस भरा', 'umas bhara'),
    'c2-balmy': ('सुहाना', 'suhana'),
    'c2-crisp-air': ('स्फूर्तिदायक', 'sphurtidayak'),
    'c2-gust': ('झोंका', 'jhonka'),
    'c2-gale': ('तेज़ आंधी', 'tez aandhi'),
    'c2-squall': ('झक्कड़', 'jhakkad'),
    'c2-thunderclap': ('बादल की गरज', 'baadal ki garaj'),
    'c2-lightning-bolt': ('वज्रपात', 'vajrapaat'),
    'c2-cloudburst': ('बादल फटना', 'baadal phatna'),
    'c2-nightfall': ('अंधेरा घिरना', 'andhera ghirna'),
    'c2-cold-snap': ('अचानक शीत लहर', 'achanak sheet lehar'),
    'c2-thaw': ('बर्फ़ पिघलना', 'barf pighalna'),
    'c2-humidity': ('आर्द्रता', 'aardrata'),
    'c2-barometer': ('वायुदाबमापी', 'vayudabmapi'),
    'c2-forecast-verb': ('पूर्वानुमान लगाना', 'purvanuman lagana'),
    'c2-daybreak': ('भोर', 'bhor'),
    'c2-aurora': ('ध्रुवीय ज्योति', 'dhruviya jyoti'),
    'c2-twilight': ('गोधूलि', 'godhuli'),
    'c2-solstice': ('अयनांत', 'ayanaant'),
    'c2-equinox': ('विषुव', 'vishuv'),
    'c2-arch': ('मेहराब', 'mehrab'),
    'c2-vault-ceiling': ('मेहराबदार छत', 'mehrabdar chhat'),
    'c2-dome': ('गुंबद', 'gumbad'),
    'c2-spire': ('स्तूपिका', 'stoopika'),
    'c2-buttress': ('आधार-स्तंभ', 'aadhar-stambh'),
    'c2-pillar': ('स्तंभ', 'stambh'),
    'c2-column': ('खंभा', 'khambha'),
    'c2-beam-structural': ('शहतीर', 'shahteer'),
    'c2-rafter': ('बल्ली', 'balli'),
    'c2-girder': ('मुख्य शहतीर', 'mukhya shahteer'),
    'c2-keystone': ('कुंजी पत्थर', 'kunji patthar'),
    'c2-facade-building-front': ('अग्रभाग', 'agrabhaag'),
    'c2-cornice': ('कंगनी', 'kangani'),
    'c2-gable': ('त्रिकोणी छत-शीर्ष', 'trikoni chhat-shirsh'),
    'c2-eaves': ('छज्जा', 'chhajja'),
    'c2-gutter-roof': ('नाली', 'naali'),
    'c2-skylight': ('छत-रोशनदान', 'chhat-roshandan'),
    'c2-balustrade': ('जंगला', 'jangla'),
    'c2-parapet': ('मुंडेर', 'munder'),
    'c2-turret': ('बुर्ज', 'burj'),
    'c2-moat': ('खाई', 'khai'),
    'c2-drawbridge': ('खिंचने वाला पुल', 'khinchne wala pul'),
    'c2-cloister': ('मठ गलियारा', 'math galiyara'),
    'c2-courtyard': ('आंगन', 'aangan'),
    'c2-alcove': ('ताखा', 'taakha'),
    'c2-mezzanine': ('अर्धमंज़िल', 'ardhamanzil'),
    'c2-atrium': ('मध्य प्रांगण', 'madhya prangan'),
    'c2-mosaic': ('पच्चीकारी', 'pachchikari'),
    'c2-fresco': ('भित्तिचित्र', 'bhittichitra'),
    'c2-elevation-drawing': ('भवन-अग्रदृश्य', 'bhavan-agradrishya'),
    'c2-partition-wall': ('विभाजक दीवार', 'vibhajak deewar'),
    'c2-cladding': ('आवरण', 'aavaran'),
    'c2-plumbing-system': ('नलसाज़ी', 'nalsazi'),
    'c2-ventilation-duct': ('वायु नलिका', 'vayu nalika'),
    'c2-retrofit': ('आधुनिकीकरण', 'aadhunikikaran'),
    'c2-colander': ('छलनी', 'chhalni'),
    'c2-ladle': ('करछुल', 'karchhul'),
    'c2-whisk': ('फेंटनी', 'phentani'),
    'c2-grater': ('कद्दूकस', 'kaddukas'),
    'c2-tongs': ('चिमटा', 'chimta'),
    'c2-spatula': ('खुरचनी', 'khurchani'),
    'c2-cutting-board': ('काटने का तख्ता', 'kaatne ka takhta'),
    'c2-french-press': ('फ्रेंच प्रेस', 'French press'),
    'c2-coaster': ('गिलास-आधार', 'gilas-aadhar'),
    'c2-trivet': ('गर्म बर्तन आधार', 'garam bartan aadhar'),
    'c2-oven-mitt': ('ओवन दस्ताना', 'oven dastana'),
    'c2-dish-rack': ('बर्तन स्टैंड', 'bartan stand'),
    'c2-dustpan': ('धूलपात्र', 'dhoolpatra'),
    'c2-mop': ('पोंछा', 'poncha'),
    'c2-clothespin': ('कपड़े की चिमटी', 'kapde ki chimti'),
    'c2-clothesline': ('कपड़े सुखाने की रस्सी', 'kapde sukhane ki rassi'),
    'c2-shoehorn': ('जूता चम्मच', 'joota chammach'),
    'c2-doormat': ('पायदान', 'paydan'),
    'c2-doorknob': ('दरवाज़े की घुंडी', 'darwaze ki ghundi'),
    'c2-hinge': ('कब्ज़ा', 'kabza'),
    'c2-latch': ('सिटकिनी', 'sitkini'),
    'c2-peephole': ('द्वार-छिद्र', 'dwar-chhidra'),
    'c2-blinds-window': ('झिलमिली', 'jhilmili'),
    'c2-windowsill': ('खिड़की की चौखट', 'khidki ki chaukhat'),
    'c2-banister': ('सीढ़ी रेलिंग', 'seedhi railing'),
    'c2-landing-stairs': ('सीढ़ियों का चबूतरा', 'seedhiyon ka chabootara'),
    'c2-crawl-space': ('रेंगने की जगह', 'rengne ki jagah'),
    'c2-cellar': ('तहखाना', 'tehkhana'),
    'c2-pantry': ('रसोई भंडार', 'rasoi bhandar'),
    'c2-utility-room': ('उपयोगिता कक्ष', 'upyogita kaksh'),
    'c2-fuse-box': ('विद्युत नियंत्रण बक्सा', 'vidyut niyantran baksa'),
    'c2-dimmer-switch': ('मंद प्रकाश स्विच', 'mand prakash switch'),
    'c2-extension-cord': ('विस्तार तार', 'vistaar taar'),
    'c2-power-strip': ('बहु-सॉकेट पट्टी', 'bahu-socket patti'),
    'c2-carbon-monoxide-alarm': ('कार्बन मोनोऑक्साइड अलार्म', 'carbon monoxide alarm'),
    'c2-first-aid-kit': ('प्राथमिक चिकित्सा बॉक्स', 'prathmik chikitsa box'),
    'c2-sewing-kit': ('सिलाई किट', 'silai kit'),
    'c2-toolbox': ('औज़ार पेटी', 'auzar peti'),
    'c2-allen-key': ('षट्कोणीय चाबी', 'shatkoniya chaabi'),
    'c2-pliers': ('सांडसी', 'saandsi'),
    'c2-wrench': ('पाना', 'pana'),
    'c2-tape-measure': ('मापन फ़ीता', 'maapan feeta'),
    'c2-spirit-level': ('समतलमापी', 'samtalmapi'),
    'c2-drawer-organizer': ('दराज़ आयोजक', 'daraz aayojak'),
    'c2-bin-liner': ('कूड़ेदान की थैली', 'kudedan ki thaili'),
    'c2-to-seethe': ('उबलना', 'ubalna'),
    'c2-to-sulk': ('मुंह फुलाना', 'moonh phulana'),
    'c2-to-fret': ('कुढ़ना', 'kudhna'),
    'c2-to-brood': ('चिंता में डूबे रहना', 'chinta mein doobe rehna'),
    'c2-to-wallow-in-self-pity': ('आत्म-दया में डूबे रहना', 'aatma-daya mein doobe rehna'),
    'c2-to-gloat-over-a-rival': ('प्रतिद्वंद्वी पर इतराना', 'pratidwandvi par itarana'),
    'c2-to-savor-the-moment': ('पल का आनंद लेना', 'pal ka anand lena'),
    'c2-to-revel-in': ('मग्न होना', 'magn hona'),
    'c2-to-marvel-at': ('पर अचंभित होना', 'par achambhit hona'),
    'c2-to-cringe': ('सिकुड़ जाना', 'sikud jana'),
    'c2-to-wince': ('दर्द से मुंह बिचकाना', 'dard se moonh bichkana'),
    'c2-to-flinch': ('सिहर उठना', 'sihar uthna'),
    'c2-to-shudder': ('कांप उठना', 'kaanp uthna'),
    'c2-to-quiver': ('थरथराना', 'thartharana'),
    'c2-to-swoon': ('बेहोश हो जाना', 'behosh ho jana'),
    'c2-to-pine-for': ('विरह में तड़पना', 'virah mein tadapna'),
    'c2-to-long-for': ('की चाह रखना', 'ki chah rakhna'),
    'c2-to-crave': ('तीव्र इच्छा होना', 'teevra ichchha hona'),
    'c2-to-abominate': ('नफ़रत करना', 'nafrat karna'),
    'c2-to-nurse-a-grievance': ('मन में शिकायत पालना', 'man mein shikayat paalna'),
    'c2-to-begrudge': ('मन में जलन रखना', 'man mein jalan rakhna'),
    'c2-to-grovel': ('दीनतापूर्वक झुकना', 'deenatapurvak jhukna'),
    'c2-to-fawn-over': ('चापलूसी करना', 'chaplusi karna'),
    'c2-to-dote-on': ('बहुत लाड़ करना', 'bahut laad karna'),
    'c2-to-treasure': ('संजोकर रखना', 'sanjokar rakhna'),
    'c2-to-put-at-ease': ('सहज महसूस कराना', 'sahaj mehsoos karana'),
    'c2-to-console': ('सांत्वना देना', 'santwana dena'),
    'c2-to-commiserate': ('सहानुभूति जताना', 'sahanubhuti jatana'),
    'c2-to-exasperate': ('झुंझलाहट पैदा करना', 'jhunjhlahat paida karna'),
    'c2-to-infuriate': ('क्रोधित करना', 'krodhit karna'),
    'c2-to-unnerve': ('विचलित कर देना', 'vichalit kar dena'),
    'c2-to-mortify': ('अपमानित महसूस कराना', 'apmaanit mehsoos karana'),
    'c2-to-captivate': ('मोहित करना', 'mohit karna'),
    'c2-to-enrapture': ('आनंदविभोर करना', 'aanandvibhor karna'),
    'c2-to-disillusion': ('मोहभंग करना', 'mohbhang karna'),
    'c2-to-mollify': ('नरम करना', 'naram karna'),
    'c2-to-embolden': ('साहस बढ़ाना', 'saahas badhana'),
    'c2-to-dishearten': ('निराश करना', 'nirash karna'),
    'c2-to-rankle': ('खटकना', 'khatakna'),
    'c2-to-smolder': ('सुलगना', 'sulagna'),
    'c2-numbness': ('सुन्नता', 'sunnata'),
    'c2-tingling': ('झुनझुनी', 'jhunjhuni'),
    'c2-cramp': ('ऐंठन', 'aithan'),
    'c2-twinge': ('टीस', 'tees'),
    'c2-throbbing': ('धड़कता हुआ दर्द', 'dhadakta hua dard'),
    'c2-dizziness': ('चक्कर', 'chakkar'),
    'c2-lightheaded': ('सिर हल्का महसूस होना', 'sir halka mehsoos hona'),
    'c2-vertigo': ('भ्रम-चक्कर', 'bhram-chakkar'),
    'c2-queasy': ('जी मिचलाने जैसा', 'ji michlane jaisa'),
    'c2-lethargy': ('सुस्ती', 'susti'),
    'c2-fatigue': ('थकावट', 'thakawat'),
    'c2-stamina': ('सहनशक्ति', 'sahanshakti'),
    'c2-reflex': ('प्रतिवर्त', 'prativart'),
    'c2-flinch-noun': ('सिहरन', 'siharan'),
    'c2-pins-and-needles': ('सुई जैसी चुभन', 'sui jaisi chubhan'),
    'c2-shiver': ('कंपकंपी', 'kapkapi'),
    'c2-hot-flush': ('गर्मी की लहर', 'garmi ki lehar'),
    'c2-blush': ('लाली', 'laali'),
    'c2-yawn': ('जम्हाई', 'jamhai'),
    'c2-hiccup': ('हिचकी', 'hichki'),
    'c2-sneeze': ('छींक', 'chheenk'),
    'c2-itch': ('खुजली', 'khujli'),
    'c2-bruise': ('नील', 'neel'),
    'c2-blister': ('छाला', 'chhala'),
    'c2-pulled-muscle': ('मांसपेशी में खिंचाव', 'mansapeshi mein khinchaav'),
    'c2-stiffness': ('अकड़न', 'akadan'),
    'c2-restlessness': ('बेचैनी', 'bechaini'),
    'c2-daydream': ('दिवास्वप्न', 'divaswapna'),
    'c2-deja-vu': ('पूर्वानुभूति', 'purvanubhuti'),
    'c2-hunch': ('पूर्वाभास', 'purvabhaas'),
    'c2-gut-feeling': ('अंतर्ज्ञान', 'antargyan'),
    'c2-brain-fog': ('मानसिक धुंधलापन', 'mansik dhundhlapan'),
    'c2-second-wind': ('नई ऊर्जा', 'nai oorja'),
    'c2-adrenaline-rush': ('एड्रेनालाईन का उछाल', 'adrenaline ka uchhal'),
    'c2-motion-sickness': ('यात्रा में मितली', 'yatra mein mitli'),
    'c2-camaraderie': ('सौहार्द', 'sauhard'),
    'c2-affinity-between-people': ('आत्मीयता', 'aatmiyata'),
    'c2-clique': ('गुट', 'gut'),
    'c2-entourage': ('अनुचर मंडली', 'anuchar mandali'),
    'c2-etiquette': ('शिष्टाचार', 'shishtachar'),
    'c2-faux-pas': ('सामाजिक भूल', 'samajik bhool'),
    'c2-gossip': ('गपशप', 'gapshap'),
    'c2-grudge': ('रंजिश', 'ranjish'),
    'c2-chain-of-command': ('आदेश शृंखला', 'aadesh shrinkhala'),
    'c2-nepotism': ('भाई-भतीजावाद', 'bhai-bhatijawad'),
    'c2-ostracism': ('बहिष्कार', 'bahishkar'),
    'c2-groupthink': ('सामूहिक चिंतन', 'samoohik chintan'),
    'c2-pecking-order': ('वरिष्ठता क्रम', 'varishthata kram'),
    'c2-rivalry': ('प्रतिद्वंद्विता', 'pratidwandvita'),
    'c2-solidarity': ('एकजुटता', 'ekjutta'),
    'c2-snub': ('उपेक्षा', 'upeksha'),
    'c2-taboo': ('वर्जना', 'varjana'),
    'c2-flattery': ('चापलूसी', 'chaplusi'),
    'c2-backhanded-compliment': ('व्यंग्यात्मक तारीफ़', 'vyangyaatmak tarif'),
    'c2-cold-shoulder': ('जानबूझकर अनदेखी', 'janboojhkar andekhi'),
    'c2-small-circle-inner-circle': ('घनिष्ठ मंडली', 'ghanishtha mandali'),
    'c2-interloper': ('घुसपैठिया', 'ghuspaithiya'),
    'c2-old-hand': ('अनुभवी व्यक्ति', 'anubhavi vyakti'),
    'c2-wingman': ('सहायक मित्र', 'sahayak mitr'),
    'c2-freeloader': ('मुफ़्तखोर', 'muftkhor'),
    'c2-busybody': ('टांग अड़ाने वाला', 'taang adane wala'),
    'c2-killjoy': ('मज़ा किरकिरा करने वाला', 'maza kirkira karne wala'),
    'c2-show-off': ('दिखावा करने वाला', 'dikhava karne wala'),
    'c2-pushover': ('आसानी से दब जाने वाला', 'aasani se dab jane wala'),
    'c2-self-starter': ('स्वप्रेरित व्यक्ति', 'swaprerit vyakti'),
    'c2-to-mingle': ('घुलना-मिलना', 'ghulna-milna'),
    'c2-to-schmooze': ('जान-पहचान बढ़ाना', 'jaan-pehchan badhana'),
    'c2-to-shun': ('से बचना', 'se bachna'),
    'c2-to-patronize': ('तुच्छ समझकर व्यवहार करना', 'tuchchh samajhkar vyavahar karna'),
    'c2-to-reconcile': ('सुलह करना', 'sulah karna'),
    'c2-to-estrange': ('रिश्ता तोड़ देना', 'rishta tod dena'),
    'c2-to-confide-in': ('दिल की बात बताना', 'dil ki baat batana'),
    'c2-to-hobnob': ('उठना-बैठना', 'uthna-baithna'),
    'c2-to-rub-shoulders-with': ('संपर्क में रहना', 'sampark mein rehna'),
    'c2-to-fall-out-with': ('से झगड़ा हो जाना', 'se jhagda ho jana'),
    'c2-foil-character': ('प्रतिपात्र', 'pratipatra'),
    'c2-anti-hero': ('प्रति-नायक', 'prati-nayak'),
    'c2-narrator': ('कथावाचक', 'kathavachak'),
    'c2-macguffin': ('कथानक-प्रेरक वस्तु', 'kathanak-prerak vastu'),
    'c2-red-herring': ('भ्रामक सुराग', 'bhramak surag'),
    'c2-motif': ('आवृत्त बिंब', 'aavritt bimb'),
    'c2-frame-narrative': ('बाह्य कथा-ढांचा', 'bahya katha-dhancha'),
    'c2-denouement': ('कथा का समापन', 'katha ka samapan'),
    'c2-satire': ('व्यंग्य-रचना', 'vyangya-rachna'),
    'c2-parody': ('उपहासात्मक नक़ल', 'upahasatmak naqal'),
    'c2-allegory': ('रूपक', 'roopak'),
    'c2-memoir': ('संस्मरण', 'sansmaran'),
    'c2-anthology': ('संकलन', 'sankalan'),
    'c2-manuscript': ('पांडुलिपि', 'paandulipi'),
    'c2-prose': ('गद्य', 'gadya'),
    'c2-couplet': ('युग्म पंक्ति', 'yugma pankti'),
    'c2-stanza': ('काव्य-पद', 'kavya-pad'),
    'c2-sonnet': ('सॉनेट', 'sonnet'),
    'c2-alliteration': ('अनुप्रास', 'anupras'),
    'c2-meter-poetry': ('छंद', 'chhand'),
    'c2-aesthetic': ('सौंदर्यबोध', 'saundaryabodh'),
    'c2-avant-garde': ('अग्रगामी', 'agragami'),
    'c2-baroque': ('बरोक', 'barok'),
    'c2-impressionism': ('प्रभाववाद', 'prabhavvad'),
    'c2-surrealism': ('अतियथार्थवाद', 'atiyatharthavad'),
    'c2-still-life': ('स्थिर वस्तु चित्र', 'sthir vastu chitra'),
    'c2-charcoal-drawing': ('कोयले का चित्र', 'koyle ka chitra'),
    'c2-etching': ('नक़्क़ाशी', 'naqqashi'),
    'c2-bust-sculpture': ('अर्धप्रतिमा', 'ardhapratima'),
    'c2-chisel': ('छेनी', 'chheni'),
    'c2-easel': ('चित्रफलक', 'chitraphalak'),
    'c2-palette': ('रंगपटल', 'rangpatal'),
    'c2-overture': ('पूर्वरंग', 'poorvarang'),
    'c2-aria': ('एकल गीत', 'ekal geet'),
    'c2-encore': ('पुनः प्रस्तुति', 'punah prastuti'),
    'c2-bandwidth': ('बैंडविड्थ', 'bandwidth'),
    'c2-jitter': ('समय-विचलन', 'samay-vichalan'),
    'c2-throughput': ('प्रवाह दर', 'pravah dar'),
    'c2-hashing': ('हैशिंग', 'hashing'),
    'c2-intrusion-detection': ('अनधिकृत प्रवेश पहचान', 'anadhikrit pravesh pehchan'),
    'c2-vulnerability-security': ('भेद्यता', 'bhedyata'),
    'c2-hotfix': ('त्वरित सुधार', 'tvarit sudhar'),
    'c2-backlog': ('लंबित कार्य', 'lambit karya'),
    'c2-rollout': ('क्रियान्वयन', 'kriyanvayan'),
    'c2-rollback': ('प्रत्यावर्तन', 'pratyavartan'),
    'c2-uptime': ('चालू समय', 'chaalu samay'),
    'c2-redundancy-backup': ('अतिरेक', 'atirek'),
    'c2-load-balancing': ('भार संतुलन', 'bhaar santulan'),
    'c2-legacy-system': ('विरासती प्रणाली', 'virasati pranali'),
    'c2-copyleft': ('कॉपीलेफ्ट', 'copyleft'),
    'c2-proprietary': ('स्वामित्व वाला', 'swamitva wala'),
    'c2-interoperability': ('अंतर-संक्रियता', 'antar-sankriyata'),
    'c2-passkey': ('पहुंच कुंजी', 'pahunch kunji'),
    'c2-social-engineering': ('सामाजिक अभियांत्रिकी', 'samajik abhiyantriki'),
    'c2-data-breach': ('डेटा उल्लंघन', 'data ullanghan'),
    'c2-cache': ('अस्थायी भंडार', 'asthayi bhandar'),
    'c2-query': ('प्रश्नांकन', 'prashnankan'),
    'c2-metadata': ('अनुषंगी आंकड़े', 'anushangi aankade'),
    'c2-placeholder': ('स्थानधारक', 'sthandharak'),
    'c2-workaround': ('अस्थायी समाधान', 'asthayi samadhan'),
    'c2-bottleneck': ('अड़चन', 'adchan'),
    'c2-edge-case': ('सीमांत स्थिति', 'seemant sthiti'),
    'c2-deprecated': ('अप्रचलित', 'aprachalit'),
    'c2-sandbox': ('परीक्षण वातावरण', 'parikshan vatavaran'),
    'c2-telemetry': ('दूरमिति', 'doormiti'),
    'c2-algorithmic-bias': ('कलनविधि पूर्वाग्रह', 'kalanvidhi purvagrah'),
    'c2-overfitting': ('अतिअनुकूलन', 'ati-anukulan'),
    'c2-large-language-model': ('बृहद भाषा मॉडल', 'brihad bhasha model'),
    'c2-quantum-computing': ('क्वांटम संगणन', 'quantum sanganan'),
    'c2-semiconductor': ('अर्धचालक', 'ardhachalak'),
    'c2-working-capital': ('कार्यशील पूंजी', 'karyasheel poonji'),
    'c2-solvency': ('शोधनक्षमता', 'shodhankshamata'),
    'c2-insolvency': ('दिवालियापन', 'diwaliyapan'),
    'c2-receivership': ('अधिग्रहीत प्रबंधन', 'adhigrihit prabandhan'),
    'c2-leverage-finance': ('ऋण-उत्तोलन', 'rin-uttolan'),
    'c2-hedge-finance': ('जोखिम सुरक्षा', 'jokhim suraksha'),
    'c2-yield-finance': ('प्रतिफल', 'pratiphal'),
    'c2-share-buyback': ('शेयर पुनर्खरीद', 'share punarkharid'),
    'c2-equity-ownership': ('स्वामित्व पूंजी', 'swamitva poonji'),
    'c2-treasury-bill': ('राजकोष बिल', 'rajkosh bill'),
    'c2-asset-allocation': ('परिसंपत्ति आवंटन', 'parisampatti aavantan'),
    'c2-volatility': ('अस्थिरता', 'asthirata'),
    'c2-bull-market': ('तेज़ी का बाज़ार', 'teji ka bazaar'),
    'c2-bear-market': ('मंदी का बाज़ार', 'mandi ka bazaar'),
    'c2-downturn': ('मंदी', 'mandi'),
    'c2-stagflation': ('मुद्रास्फीति सह मंदी', 'mudrasfiti sah mandi'),
    'c2-deflation': ('अपस्फीति', 'apasphiti'),
    'c2-interest-rate-hike': ('ब्याज दर वृद्धि', 'byaj dar vriddhi'),
    'c2-fiscal-policy': ('राजकोषीय नीति', 'rajkoshiya niti'),
    'c2-monetary-policy': ('मौद्रिक नीति', 'maudrik niti'),
    'c2-subsidy': ('अनुदान', 'anudan'),
    'c2-trade-quota': ('व्यापार कोटा', 'vyapar kota'),
    'c2-embargo': ('व्यापार प्रतिबंध', 'vyapar pratibandh'),
    'c2-belt-tightening': ('खर्च में कटौती', 'kharch mein katauti'),
    'c2-bailout': ('वित्तीय राहत पैकेज', 'vittiya rahat package'),
    'c2-windfall': ('अप्रत्याशित लाभ', 'apratyashit labh'),
    'c2-nest-egg': ('बचत निधि', 'bachat nidhi'),
    'c2-slush-fund': ('गुप्त कोष', 'gupt kosh'),
    'c2-kickback': ('घूस', 'ghoos'),
    'c2-money-laundering': ('काला धन सफेद करना', 'kaala dhan safed karna'),
    'c2-tax-evasion': ('कर चोरी', 'kar chori'),
    'c2-tax-loophole': ('कर की खामी', 'kar ki khaami'),
    'c2-underwriter': ('बीमाकर्ता', 'bimakarta'),
    'c2-sinking-fund': ('निक्षेप निधि', 'nikshep nidhi'),
    'c2-arbitrage': ('मध्यस्थ व्यापार', 'madhyasth vyapar'),
    'c2-freight': ('माल भाड़ा', 'maal bhada'),
    'c2-cargo-hold': ('माल कक्ष', 'maal kaksh'),
    'c2-consignment': ('खेप', 'khep'),
    'c2-customs-clearance': ('सीमा शुल्क निकासी', 'seema shulk nikasi'),
    'c2-red-eye-flight': ('रात्रि उड़ान', 'ratri udaan'),
    'c2-turbulence': ('वायु-हलचल', 'vayu-halchal'),
    'c2-taxiing': ('भू-संचालन', 'bhoo-sanchalan'),
    'c2-cockpit': ('चालक कक्ष', 'chalak kaksh'),
    'c2-overhead-compartment': ('ऊपरी सामान कक्ष', 'oopri samaan kaksh'),
    'c2-aisle-seat': ('गलियारे वाली सीट', 'galiyare wali seat'),
    'c2-boarding-pass': ('बोर्डिंग पास', 'boarding pass'),
    'c2-baggage-carousel': ('सामान पट्टी', 'samaan patti'),
    'c2-jet-bridge': ('विमान सेतु', 'vimaan setu'),
    'c2-tailgating-driving': ('पीछे से सटकर चलना', 'peeche se satkar chalna'),
    'c2-gridlock': ('पूर्ण यातायात जाम', 'poorna yatayat jaam'),
    'c2-diversion-route': ('मार्ग परिवर्तन', 'marg parivartan'),
    'c2-interchange-highway': ('राजमार्ग संगम', 'rajmarg sangam'),
    'c2-overpass': ('ऊपरी पुल', 'oopri pul'),
    'c2-underpass': ('भूमिगत मार्ग', 'bhoomigat marg'),
    'c2-toll-booth': ('टोल नाका', 'toll naka'),
    'c2-hard-shoulder': ('आपातकालीन पट्टी', 'aapatkalin patti'),
    'c2-speed-bump': ('गति अवरोधक', 'gati avrodhak'),
    'c2-blind-spot': ('अदृश्य क्षेत्र', 'adrishya kshetra'),
    'c2-hazard-lights': ('चेतावनी बत्तियां', 'chetavani battiyan'),
    'c2-windshield-wiper': ('शीशा-पोंछ', 'sheesha-ponchh'),
    'c2-clutch-car': ('क्लच', 'clutch'),
    'c2-handbrake': ('हाथ ब्रेक', 'haath brake'),
    'c2-odometer': ('दूरीमापी', 'doorimapi'),
    'c2-tow-truck': ('खींचने वाला वाहन', 'kheenchne wala vahan'),
    'c2-commute-noun': ('दैनिक यात्रा', 'dainik yatra'),
    'c2-numerator': ('अंश', 'ansh'),
    'c2-denominator': ('हर', 'har'),
    'c2-exponent': ('घात', 'ghaat'),
    'c2-square-root': ('वर्गमूल', 'vargamool'),
    'c2-decimal-point': ('दशमलव बिंदु', 'dashamlav bindu'),
    'c2-remainder': ('शेषफल', 'sheshphal'),
    'c2-prime-number': ('अभाज्य संख्या', 'abhajya sankhya'),
    'c2-integer': ('पूर्णांक', 'poornank'),
    'c2-quotient': ('भागफल', 'bhagphal'),
    'c2-percentile': ('प्रतिशतांक', 'pratishatank'),
    'c2-mean-average': ('औसत', 'ausat'),
    'c2-median': ('माध्यिका', 'madhyika'),
    'c2-outlier': ('अपवाद मान', 'apvaad maan'),
    'c2-standard-deviation': ('मानक विचलन', 'manak vichalan'),
    'c2-variance': ('प्रसरण', 'prasaran'),
    'c2-margin-of-error': ('त्रुटि मार्जिन', 'truti margin'),
    'c2-sample-size': ('प्रतिदर्श आकार', 'pratidarsh aakar'),
    'c2-exponential-growth': ('चरघातांकी वृद्धि', 'charghatanki vriddhi'),
    'c2-order-of-magnitude': ('परिमाण क्रम', 'parimaan kram'),
    'c2-rounding': ('सन्निकटन', 'sannikatan'),
    'c2-percentage-point': ('प्रतिशत बिंदु', 'pratishat bindu'),
    'c2-threefold': ('तिगुना', 'tiguna'),
    'c2-a-dozen': ('एक दर्जन', 'ek darjan'),
    'c2-round-number': ('गोल संख्या', 'gol sankhya'),
    'c2-odds-probability': ('संभावना', 'sambhavna'),
    'c2-inseam': ('भीतरी सिलाई', 'bhitri silai'),
    'c2-dart-sewing': ('चुन्नट', 'chunnat'),
    'c2-lapel': ('कोट का किनारा', 'coat ka kinara'),
    'c2-cuff': ('आस्तीन का किनारा', 'aastin ka kinara'),
    'c2-cufflinks': ('आस्तीन बटन', 'aastin button'),
    'c2-gusset': ('जोड़-पट्टी', 'jod-patti'),
    'c2-pleat': ('तह', 'tah'),
    'c2-tailored': ('दर्ज़ी-निर्मित', 'darzi-nirmit'),
    'c2-bespoke': ('माप के अनुसार बना', 'maap ke anusar bana'),
    'c2-off-the-rack': ('बना-बनाया', 'bana-banaya'),
    'c2-threadbare': ('घिसा हुआ', 'ghisa hua'),
    'c2-frayed': ('उधड़ा हुआ', 'udhda hua'),
    'c2-creased': ('सिलवटदार', 'silvatdar'),
    'c2-dapper': ('छैला', 'chhaila'),
    'c2-disheveled': ('बिखरा-बिखरा', 'bikhra-bikhra'),
    'c2-scruffy': ('मैला-कुचैला', 'maila-kuchaila'),
    'c2-garish': ('भड़कीला', 'bhadkeela'),
    'c2-understated': ('सादा', 'saada'),
    'c2-flattering-clothes': ('जंचने वाला', 'jachne wala'),
    'c2-baggy': ('ढीला-ढाला', 'dheela-dhala'),
    'c2-snug': ('चुस्त', 'chust'),
    'c2-stubble': ('हल्की दाढ़ी', 'halki daadhi'),
    'c2-freckles': ('झाइयां', 'jhaiyan'),
    'c2-dimple': ('गाल का गड्ढा', 'gaal ka gadda'),
    "c2-crow-s-feet": ("आंखों की झुर्रियां", "aankhon ki jhurriyan"),
    'c2-complexion': ('रंगत', 'rangat'),
    'c2-gaunt': ('निस्तेज व दुबला', 'nistej va dubla'),
    'c2-stocky': ('गठीला', 'gathila'),
    'c2-lanky': ('लंबा-दुबला', 'lamba-dubla'),
    'c2-poised': ('संयत', 'sanyat'),
}
