# -*- coding: utf-8 -*-
LANG = 'tr'

SENTENCES = {
    'b1-dr1': ['Araba', 'kullanmayı', 'öğreniyorum'],
    'b1-dr2': ['Genellikle', 'erken', 'uyanırım'],
    'b1-dr3': ['Dün', 'bütün', 'evi', 'temizledim'],
    'b1-dr4': ['Hiçbir', 'iş gününü', 'kaçırmadım'],
    'b1-fs1': ['Erkek kardeşim', 'spor', 'yapmıyor'],
    'b1-fs2': ['Biz', 'anne babamızı', 'aramalıyız'],
    'b1-fs3': ['Bana', 'bununla', 'yardım edebilir misiniz,', 'lütfen?'],
    'b1-fs4': ['Kız kardeşim', 'benden', 'daha konuşkan'],
    'b1-te1': ['Dün', 'yeni bir şehir', 'ziyaret ettim'],
    'b1-te2': ['Yağmur yağarsa,', 'otelde', 'kalırız'],
    'b1-te3': ['Hiç', "Japonya'ya", 'gitmedim'],
    'b1-te4': ['İyi bir otel', 'önerebilir', 'misin?'],
    'b1-op1': ['Müzik', 'çok', 'yüksek sesli'],
    'b1-op2': ['Bu şehir', 'ondan', 'daha pahalı'],
    'b1-op3': ['Bence', 'bu kitap', 'çok', 'ilginç'],
    'b1-op4': ['Bence', 'erken', 'ayrılmalıyız'],
    'c2-s01': ['Açıkçası,', 'böyle bir şeyi', 'imzalamadan önce', 'iki kere', 'düşünürdüm'],
    'c2-s02': ['Umursamıyor değilim,', 'sadece', 'verecek', 'hiçbir şeyim', 'kalmadı'],
    'c2-s03': ['Ne yaparsan yap,', 'seni', 'ikna etmesine', 'izin verme'],
    'c2-s04': ['Bu kadar', 'uzayacağını', 'bilseydim,', 'asla', 'kabul etmezdim'],
    'c2-s05': ['Önemsemedi gibi', 'davrandı,', 'ama', 'etkilendiği', 'belliydi'],
    'c2-s06': ['Onun hakkında', 'ne istersen', 'söyle,', 'ama', 'işleri hallediyor'],
    'c2-s07': ['Yapmadığım', 'bir şey için', 'özür dileyecek', 'değilim'],
    'c2-s08': ['Onlar tamir etmeye', 'vakit bulana kadar,', 'hasar', 'çoktan oluşmuştu'],
    'c2-s09': ['Aramızda kalsın,', 'bence', 'anlaşma', 'gerçekleşmeyecek'],
    'c2-s10': ['İnsan', 'şu ana kadar', 'ders aldıklarını', 'düşünür,', 'değil mi?'],
    'c2-s11': ['Daha', 'oturur oturmaz', 'yangın alarmı', 'çaldı'],
    'c2-s12': ['Senin için', 'fark etmezse,', 'bunun', 'kayıt dışı kalmasını', 'tercih ederim'],
    'c1-m01': ['Hükümet', 'enflasyonu düşürmek için', 'yeni önlemler', 'açıkladı'],
    'c1-m02': ['Rapora göre,', 'işsizlik', 'üst üste', 'üçüncü ay', 'düştü'],
    'c1-m03': ['Ayrılacağımı', 'hiç söylemedim;', 'zamana ihtiyacım', 'olduğunu söyledim'],
    'c1-m04': ['Bu gece', 'ne olursa olsun,', 'o kapıyı', 'açma'],
    'c1-m05': ['Bilim insanları', 'buzulun', 'on yıl içinde', 'kaybolabileceği konusunda', 'uyarıyor'],
    'c1-m06': ['Bana', 'gerçeği', 'söyleseydin,', 'bunların hiçbiri', 'olmazdı'],
    'c1-m07': ['Polis', 'anonim bir ihbar', 'aldıktan kısa süre sonra', 'şüpheli', 'tutuklandı'],
    'c1-m08': ['Açıkçası,', 'olanlardan', 'ikimizin de', 'sorumlu olduğunu', 'düşünüyorum'],
    'c1-m09': ['Şirket', 'iddiaları', 'reddetti ama', 'daha fazla yorum', 'yapmayı reddetti'],
    'c1-m10': ['Buraya gelmek için', 'nelerden', 'vazgeçtiğim hakkında', 'hiçbir fikrin', 'yok'],
    'c1-m11': ['Seçmenler', 'artan belirsizlik', 'ortasında', 'pazar günü', 'sandık başına gidecek'],
    'c1-m12': ['Diyelim ki', 'planladığım', 'gibi', 'gitmedi'],
}

DIALOGUES = {
    'd-a2-01': [
        'Merhaba, ben Marta. Memnun oldum.',
        'Memnun oldum, ben Alex.',
        'Hayır, teşekkürler.',
        'Sağda.',
        'Saat üç.',
    ],
    'd-a2-02': [
        'Nerelisin?',
        "Amerika'da Chicago'danım.",
        'Yirmi yaşındayım.',
        'Kahveyi severim.',
        'Bir bankada çalışıyorum.',
    ],
    'd-a2-03': [
        'Ne iş yapıyorsun?',
        'Tasarımcıyım, evden çalışıyorum.',
        'Parkın yakınında yaşıyorum.',
        'Çayı tercih ederim.',
        'Yarın yağmur yağacak.',
    ],
    'd-a2-04': [
        'Ne zamandır buradasın?',
        'İki aydır buradayım.',
        'On euroya mal oluyor.',
        'Pazarları kapalı.',
        'İki erkek kardeşim var.',
    ],
    'd-a2-05': [
        'Kardeşin var mı?',
        'Evet, büyük bir kız kardeşim var.',
        'Evet, saat sekizde.',
        'Hayır, çok pahalı.',
        'Mutfakta.',
    ],
    'd-a2-06': [
        'Geldiğin için teşekkürler, yakında görüşürüz!',
        'Sana teşekkürler, harikaydı! Yakında görüşürüz.',
        'Bir kahve istiyorum.',
        'Pardon, anlamıyorum.',
        'Tuvalet orada.',
    ],
    'd-a2-07': [
        'Bugün hava çok soğuk, değil mi?',
        'Evet, çok soğuk. Yarın kar yağacakmış.',
        'Evet, benim adım Alex.',
        'Hayır, kardeşim yok.',
        'Beş euroya mal oluyor.',
    ],
    'd-a2-08': [
        'Hafta sonu için ne planların var?',
        'Ailemi ziyaret edeceğim.',
        'Bir ofiste çalışıyorum.',
        'Solda.',
        'Kırmızıyı tercih ederim.',
    ],
    'd-a2-09': [
        'Yarın kahve içelim mi?',
        'Tabii ki! Saat on sana uyar mı?',
        "Madrid'denim.",
        'Bir köpeğim var.',
        'Çok yağmur yağıyor.',
    ],
    'd-a2-10': [
        'Film saat kaçta başlıyor?',
        'Yedi buçukta başlıyor.',
        'Çok uzakta.',
        'Çok hoşuma gidiyor.',
        'Öğrenciyim.',
    ],
    'd-a2-11': [
        'Günün nasıl geçti?',
        'Oldukça iyi, ama yorgunum.',
        'İki euro.',
        'Üçüncü katta yaşıyorum.',
        'O benim kız kardeşim.',
    ],
    'd-a2-12': [
        'Nereye gidiyorsun?',
        'Süpermarkete, akşam yemeği için hiçbir şeyim yok.',
        'Otuz yaşındayım.',
        'Hava çok sıcak.',
        'Evet, biraz konuşuyorum.',
    ],
    'd-b1-01': [
        'Ne kadar zaman oldu! Ne yapıyorsun bu aralar?',
        'Şey, iki ay önce iş değiştirdim ve çok memnunum.',
        'Tren dokuzda kalkıyor.',
        'Çayı kahveye tercih ederim.',
        'Buradan iki blok uzakta.',
    ],
    'd-b1-02': [
        'Son zamanlarda işte çok stresliyim.',
        'Çok üzüldüm. Konuşmak ister misin?',
        'Ben yeni bir bisiklet aldım.',
        'Film saat sekizde başlıyor.',
        'Kız kardeşim Roma\'da yaşıyor.',
    ],
    'd-b1-03': [
        'Peki gezi nasıldı? Anlat bana her şeyi!',
        'İnanılmazdı. Yemekler, insanlar... şimdiden geri dönmek istiyorum.',
        'Süt almam lazım.',
        'Dokuzdan beşe kadar çalışıyorum.',
        'Ocak ayında hava soğuk oluyor.',
    ],
    'd-b1-04': [
        'Lucía ile geçen hafta ayrıldık.',
        'Vay be, bilmiyordum. Nasıl idare ediyorsun?',
        'Tebrikler! Ne güzel haber.',
        'Saat kaçta buluşalım?',
        'Müze pazartesileri kapalı.',
    ],
    'd-b1-05': [
        'Hala spor salonuna gidiyor musun?',
        'Açıkçası bıraktım. Şimdi sabahları koşuyorum.',
        'Evet, ekmek çok lezzetli.',
        'Beşinci katta yaşıyorum.',
        'Yarın salı.',
    ],
    'd-b1-06': [
        'Sana önerdiğim diziyi izledin mi? Ne düşündün?',
        'İlk bölümden itibaren bağımlısı oldum, ama final biraz hayal kırıklığı yarattı.',
        'Yirmi euroya mal oluyor.',
        'İki kedim var.',
        'Tuvalet arka tarafta.',
    ],
    'd-b1-07': [
        'Cumartesi doğa yürüyüşüne gidelim mi?',
        'Cumartesi olmaz, bir düğünüm var. Pazar sana uyar mı?',
        'Evet, benim adım Alex.',
        'Trafik ışığı kırmızı.',
        'Bu şarap Şili\'den.',
    ],
    'd-b1-08': [
        'Kusura bakma, on beş dakika geç kalacağım.',
        'Sorun değil, seni köşedeki kafede beklerim.',
        'Mavi rengi severim.',
        'Bugün çok rüzgarlı.',
        'Doğum günüm mayısta.',
    ],
    'd-b1-09': [
        'Hesabı bölüşelim mi yoksa bu sefer ben mi ödeyeyim?',
        'Bölüşelim, ama bir dahakine ben ısmarlarım.',
        'Yine yağmur yağıyor.',
        'Chicago\'da doğdum.',
        'Otobüs her on dakikada bir geçiyor.',
    ],
    'd-b1-10': [
        'Perşembe günü taşınmama yardım eder misin?',
        'Tabii, bana güvenebilirsin. İşten saat altıda çıkıyorum, sana uyar mı?',
        'Peynir buzdolabında.',
        'Bir yıldır Japonca öğreniyorum.',
        'Plaj uzakta.',
    ],
    'd-b1-11': [
        'Yeni ızgara restoranında yemek yiyelim mi?',
        'Ben vejetaryenim de. Daha çok seçenek olan bir yer biliyor musun?',
        'Pazartesileri piyano dersim var.',
        'Sokak kapalı.',
        'Babam doktor.',
    ],
    'd-b1-12': [
        'Cumaya kadar bana elli euro borç verebilir misin?',
        'Evet, sorun değil. Şimdi havale ile gönderiyorum.',
        'Koridor yerine pencereyi tercih ederim.',
        'Plajda hava güneşli.',
        'Büyükannem seksen yaşında.',
    ],
    'd-b2-01': [
        'Bence uzaktan çalışmak takım çalışmasına zarar veriyor.',
        'O kadar emin değilim. Benim tecrübeme göre, iyi araçlarla takım aynı ya da daha iyi performans gösteriyor.',
        'Rapor mavi klasörde.',
        'Kahveyi şekersiz tercih ederim.',
        'Yarın tren grevi var.',
    ],
    'd-b2-02': [
        'Sosyal medya bizi daha yalnız hale getiriyor.',
        'Kısmen evet, ama aynı zamanda birçok insanın yakınında bulamadığı toplulukları bulmasına yardımcı oldu.',
        'Şifrem sekiz karakter.',
        'O restoran on birde kapanıyor.',
        'Biletleri dün aldım.',
    ],
    'd-b2-03': [
        'Şehir merkezinde arabaları yasaklamaları gerektiğini düşünüyor musun?',
        'Evet, toplu taşımayı iyileştirdikleri sürece; yoksa sorunu sadece mahallelere taşırlar.',
        'Merkez yürüyerek on dakika.',
        'Arabam kırmızı.',
        'Pazarları çalışmıyorum.',
    ],
    'd-b2-04': [
        'Aynı anda altı dil öğrenmek imkansız.',
        'Zor, evet, ama imkansız değil: roman dilleri birbirini güçlendirir, ve Japonca ile Çince birçok karakteri paylaşır.',
        'Bugün yirmi derece.',
        'Dişçi randevum var.',
        'Paket perşembe geliyor.',
    ],
    'd-b2-05': [
        'Kira gelecek ay yüzde yirmi artacak.',
        'Maliyetlerin arttığını anlıyorum, ama yüzde yirmi çok fazla. Yüzde on üzerinde anlaşıp iki yıllığına yenileyebilir miyiz?',
        'Tuvalet koridorun sonunda.',
        'Buradan manzarayı çok seviyorum.',
        'Bugün doğum günüm.',
    ],
    'd-b2-06': [
        'İnşaat iki hafta gecikecek.',
        'Nedeni tam olarak ne? Kiracıyı bilgilendirmek için kesin bir tarihe ihtiyacım var.',
        'Fayanslar gri renkte.',
        'Emlak sektöründe çalışıyorum.',
        'Köşede bir eczane var.',
    ],
    'd-b2-07': [
        'Üzgünüm, iade talebiniz reddedildi.',
        'Politikanıza göre iade için otuz günüm var ve sadece on iki gün geçti. Kararı gözden geçirmek için kiminle konuşabilirim?',
        'Dört kişilik bir masa istiyorum.',
        'Nehrin yakınında yaşıyorum.',
        'Erkek kardeşim mühendis.',
    ],
    'd-b2-08': [
        'Dün gece müzik çok yüksekti, uyuyamadım.',
        'Tamamen haklısınız, gerçekten özür dilerim. Bundan sonra saat ondan sonra sesi kısacağım.',
        'Süpermarket saat sekizde açılıyor.',
        'Köpeğini çok seviyorum.',
        'İtalyanca öğreniyorum.',
    ],
    'd-c2-01': [
        'Ne biçim park etmişsin, ehliyetini çekilişte mi kazandın?',
        'En azından benim arabam var, sen scooterla geliyorsun.',
        'Çok özür dilerim, bir daha olmayacak.',
        'Araba mavi.',
        'Bugün hava çok sıcak.',
    ],
    'd-c2-02': [
        'Neyi istersen yenerim, sen seç.',
        'Tamam: bakalım cep telefonuna bakmadan kim daha çok dayanabilecek.',
        'Haklısın, her konuda daha iyisin.',
        'Maç saat sekizde başlıyor.',
        'Kız kardeşim Sevilla\'da yaşıyor.',
    ],
    'd-c2-03': [
        'O telefon hala çalışıyor mu? Müzelik bir parça.',
        'Bak, bende olan vintage, eski değil.',
        'Evet, yarın hemen yenisini almalıyım.',
        'Müze pazartesileri kapalı.',
        'Bir şarj aletine ihtiyacım var.',
    ],
    'd-c2-04': [
        'Senin için fena değil.',
        'Suyu bile yakan birinden gelince, bunu iltifat sayıyorum.',
        'Teşekkürler, beğenmene sevindim.',
        'Tuz masanın üzerinde.',
        'Saat dokuzda akşam yemeği yedim.',
    ],
    'd-c2-05': [
        'Sosyal medya kamusal tartışmayı mahvetti, nokta.',
        'Bir suçları var, evet, ama eskiden tartışmayı üç gazete kontrol ediyordu.',
        'Tamamen katılıyorum, söylenecek başka bir şey yok.',
        'Hesabımın bin takipçisi var.',
        'Gazete sabahları geliyor.',
    ],
    'd-c2-06': [
        'Bugünün gençleri çalışmak istemiyor, işte bu kadar açık.',
        'Yoksa kirayı bile karşılamayan maaşlar için çalışmak istemiyorlar mı?',
        'Doğru, biz tembeliz.',
        'Ben bir ofiste çalışıyorum.',
        'Kira ayın birinde ödenir.',
    ],
    'd-c2-07': [
        'Şehir merkezinde arabalar, istisnasız, tamamen yasaklanmalı.',
        'İstisnasız olmaz: ya ambulanslar, teslimatlar, hareket kısıtlılığı olan insanlar?',
        'Evet, hepsini yarından itibaren yasaklayalım.',
        'Arabam kırmızı.',
        'Merkezde birçok mağaza var.',
    ],
    'd-c2-08': [
        'Dil öğrenmenin artık anlamı yok, yapay zeka her şeyi çeviriyor.',
        'Kelimeleri çeviriyor, evet; ama şakayı, tonu ve karşındakinin güvenini kimse sana çeviremez.',
        'Doğru, bugün kursu bırakıyorum.',
        'Uygulama ücretsiz.',
        'Salı günleri İspanyolca çalışıyorum.',
    ],
}
