# -*- coding: utf-8 -*-
LANG = 'vi'
WORDS = {
    'c1-broadcast': ('Sự phát sóng', None),
    'c1-coverage': ('Sự đưa tin', None),
    'c1-correspondent': ('Phóng viên thường trú', None),
    'c1-anchor-news': ('Người dẫn chương trình thời sự', None),
    'c1-editorial': ('Bài xã luận', None),
    'c1-slant-bias': ('Sự thiên lệch (thiên vị)', None),
    'c1-to-leak': ('Tiết lộ (rò rỉ thông tin)', None),
    'c1-source-journalism': ('Nguồn tin', None),
    'c1-whistleblower': ('Người tố giác', None),
    'c1-censorship': ('Sự kiểm duyệt', None),
    'c1-propaganda': ('Tuyên truyền', None),
    'c1-misinformation': ('Thông tin sai lệch', None),
    'c1-fact-check': ('Kiểm chứng thông tin', None),
    'c1-viral': ('Lan truyền (viral)', None),
    'c1-clickbait': ('Bẫy nhấp chuột (câu view)', None),
    'c1-tabloid': ('Báo lá cải', None),
    'c1-press-conference': ('Họp báo', None),
    'c1-press-release': ('Thông cáo báo chí', None),
    'c1-exclusive-story': ('Tin độc quyền', None),
    'c1-breaking-news': ('Tin nóng', None),
    'c1-viewership': ('Lượng khán giả', None),
    'c1-subscriber': ('Người đăng ký', None),
    'c1-paywall': ('Tường phí', None),
    'c1-influencer': ('Người có ảnh hưởng', None),
    'c1-to-trend': ('Trở thành xu hướng', None),
    'c1-hashtag': ('Hashtag', None),
    'c1-op-ed': ('Bài bình luận (op-ed)', None),
    'c1-byline': ('Dòng ghi tên tác giả', None),
    'c1-segment-tv': ('Phân đoạn (chương trình)', None),
    'c1-airtime': ('Thời lượng phát sóng', None),
    'c1-methodology': ('Phương pháp luận', None),
    'c1-empirical': ('Thực nghiệm', None),
    'c1-qualitative': ('Định tính', None),
    'c1-quantitative': ('Định lượng', None),
    'c1-variable': ('Biến số', None),
    'c1-correlation': ('Tương quan', None),
    'c1-causation': ('Quan hệ nhân quả', None),
    'c1-sample-study': ('Mẫu (nghiên cứu)', None),
    'c1-peer-review': ('Bình duyệt', None),
    'c1-citation': ('Trích dẫn', None),
    'c1-abstract-summary': ('Tóm tắt', None),
    'c1-dissertation': ('Luận án', None),
    'c1-scholar': ('Học giả', None),
    'c1-discipline-field': ('Chuyên ngành', None),
    'c1-paradigm': ('Hệ hình', None),
    'c1-phenomenon': ('Hiện tượng', None),
    'c1-premise': ('Tiền đề', None),
    'c1-inference': ('Sự suy luận', None),
    'c1-to-infer': ('Suy luận', None),
    'c1-to-deduce': ('Suy diễn', None),
    'c1-rigorous': ('Chặt chẽ (nghiêm ngặt)', None),
    'c1-nuanced': ('Tinh tế (có sắc thái)', None),
    'c1-to-synthesize': ('Tổng hợp', None),
    'c1-critique': ('Phê bình', None),
    'c1-discourse': ('Diễn ngôn', None),
    'c1-hierarchy': ('Hệ thống thứ bậc', None),
    'c1-paradox': ('Nghịch lý', None),
    'c1-theoretical': ('Lý thuyết', None),
    'c1-findings': ('Kết quả nghiên cứu', None),
    'c1-assumption': ('Giả định', None),
    'c1-to-back-up-support': ('Ủng hộ (hậu thuẫn)', None),
    'c1-to-bring-up-mention': ('Đề cập (nêu ra)', None),
    'c1-to-call-off': ('Hủy bỏ', None),
    'c1-to-carry-on': ('Tiếp tục', None),
    'c1-to-check-out-look-at': ('Xem thử', None),
    'c1-to-come-across': ('Bắt gặp (tình cờ)', None),
    'c1-to-cut-down-on': ('Giảm bớt', None),
    'c1-to-do-without': ('Không cần đến', None),
    'c1-to-fall-apart': ('Sụp đổ (tan vỡ)', None),
    'c1-to-fall-behind': ('Tụt lại phía sau', None),
    'c1-to-get-away-with': ('Thoát tội (trót lọt)', None),
    'c1-to-get-by': ('Xoay xở (sống qua ngày)', None),
    'c1-to-get-over': ('Vượt qua', None),
    'c1-to-give-in': ('Nhượng bộ', None),
    'c1-to-go-through-experience': ('Trải qua', None),
    'c1-to-hold-on': ('Chờ đã (giữ vững)', None),
    'c1-to-keep-up-with': ('Theo kịp', None),
    'c1-to-let-down': ('Làm thất vọng', None),
    'c1-to-look-into': ('Điều tra (xem xét)', None),
    'c1-to-look-up-to': ('Ngưỡng mộ', None),
    'c1-to-make-up-for': ('Bù đắp', None),
    'c1-to-pass-out': ('Ngất xỉu', None),
    'c1-to-point-out': ('Chỉ ra', None),
    'c1-to-put-up-with': ('Chịu đựng', None),
    'c1-to-run-into': ('Tình cờ gặp', None),
    'c1-to-set-up': ('Thiết lập', None),
    'c1-to-sort-out': ('Giải quyết', None),
    'c1-to-stand-for': ('Đại diện cho (biểu thị)', None),
    'c1-to-take-after': ('Giống (cha mẹ)', None),
    'c1-to-take-over': ('Tiếp quản', None),
    'c1-to-turn-down': ('Từ chối', None),
    'c1-to-turn-up': ('Xuất hiện (đến)', None),
    'c1-to-work-out-resolve': ('Được giải quyết (ổn thỏa)', None),
    'c1-to-wear-off': ('Phai nhạt dần (hết tác dụng)', None),
    'c1-to-wind-up-end-up': ('Kết cục là (cuối cùng thành)', None),
    'c1-to-break-off': ('Cắt đứt (quan hệ)', None),
    'c1-to-brush-up-on': ('Ôn lại', None),
    'c1-to-catch-on': ('Trở nên phổ biến', None),
    'c1-to-come-down-with': ('Mắc (bệnh)', None),
    'c1-to-crack-down-on': ('Trấn áp', None),
    'c1-to-dwell-on': ('Suy nghĩ mãi về', None),
    'c1-to-fall-through': ('Đổ bể (thất bại)', None),
    'c1-to-get-across': ('Truyền đạt (ý tưởng)', None),
    'c1-to-hold-back': ('Kìm nén', None),
    'c1-to-iron-out': ('Giải quyết ổn thỏa', None),
    'c1-to-live-up-to': ('Xứng đáng với (kỳ vọng)', None),
    'c1-to-narrow-down': ('Thu hẹp (lựa chọn)', None),
    'c1-to-opt-out': ('Từ chối tham gia', None),
    'c1-to-phase-out': ('Loại bỏ dần', None),
    'c1-to-pull-off': ('Thực hiện thành công', None),
    'c1-to-rule-out': ('Loại trừ', None),
    'c1-to-settle-for': ('Chấp nhận (thay vì tốt hơn)', None),
    'c1-to-stick-to': ('Tuân thủ (kiên trì với)', None),
    'c1-to-take-on-a-task': ('Đảm nhận', None),
    'c1-to-touch-on': ('Đề cập sơ qua', None),
    'c1-to-weigh-up': ('Cân nhắc', None),
    'c1-to-wrap-up': ('Kết thúc (tổng kết)', None),
    'c1-to-zero-in-on': ('Tập trung vào', None),
    'c1-to-fend-off': ('Chống đỡ (đẩy lùi)', None),
    'c1-to-stem-from': ('Bắt nguồn từ', None),
    'c1-awesome': ('Tuyệt vời', None),
    'c1-gross': ('Kinh tởm', None),
    'c1-lame': ('Nhạt nhẽo (dở tệ)', None),
    'c1-cheesy': ('Sến', None),
    'c1-to-chill': ('Thư giãn', None),
    'c1-dude': ('Anh bạn', None),
    'c1-to-ditch': ('Bỏ rơi (vứt bỏ)', None),
    'c1-to-bail-leave': ('Chuồn (bỏ đi)', None),
    'c1-to-crash-sleep': ('Lăn ra ngủ', None),
    'c1-to-freak-out': ('Hoảng loạn', None),
    'c1-to-nail-it': ('Làm xuất sắc', None),
    'c1-to-screw-up': ('Làm hỏng bét', None),
    'c1-a-bummer': ('Thật xui xẻo', None),
    'c1-no-biggie': ('Không có gì to tát', None),
    'c1-to-be-into': ('Mê (thích)', None),
    'c1-hooked': ('Nghiện (mê mẩn)', None),
    'c1-hype': ('Sự thổi phồng', None),
    'c1-sketchy': ('Đáng ngờ', None),
    'c1-legit': ('Chính hiệu (thật)', None),
    'c1-a-rip-off': ('Trò lừa đảo (chặt chém)', None),
    'c1-to-ghost': ('Lặn mất tăm (cắt liên lạc đột ngột)', None),
    'c1-cringe': ('Rùng mình ngượng', None),
    'c1-to-wing-it': ('Ứng biến (làm liều không chuẩn bị)', None),
    'c1-to-zone-out': ('Đờ người (mất tập trung)', None),
    'c1-to-kick-back': ('Ngả lưng thư giãn', None),
    'c1-for-real': ('Thật đấy', None),
    'c1-buddy': ('Bạn thân (chiến hữu)', None),
    'c1-to-hit-the-road': ('Lên đường', None),
    'c1-to-grab-get': ('Tóm lấy (kiếm)', None),
    'c1-sweet-great': ('Đỉnh (tuyệt)', None),
    'c1-eloquent': ('Hùng biện', None),
    'c1-poignant': ('Cảm động sâu sắc', None),
    'c1-vivid': ('Sống động', None),
    'c1-lucid': ('Minh mẫn (sáng rõ)', None),
    'c1-sublime': ('Tuyệt mỹ (cao siêu)', None),
    'c1-exquisite': ('Tinh xảo', None),
    'c1-serene': ('Thanh thản', None),
    'c1-somber': ('U ám (trầm buồn)', None),
    'c1-bleak': ('Ảm đạm', None),
    'c1-grim': ('Nghiệt ngã', None),
    'c1-austere': ('Khắc khổ', None),
    'c1-opulent': ('Xa hoa', None),
    'c1-lavish': ('Xa xỉ (hào phóng)', None),
    'c1-meager': ('Ít ỏi (nghèo nàn)', None),
    'c1-scarce': ('Khan hiếm', None),
    'c1-abundant': ('Dồi dào', None),
    'c1-pristine': ('Nguyên sơ', None),
    'c1-dilapidated': ('Đổ nát (xuống cấp)', None),
    'c1-quaint': ('Cổ kính (có nét riêng)', None),
    'c1-picturesque': ('Nên thơ', None),
    'c1-ominous': ('Đáng ngại (điềm gở)', None),
    'c1-eerie': ('Rùng rợn (kỳ quái)', None),
    'c1-uncanny': ('Kỳ lạ đến khó hiểu', None),
    'c1-whimsical': ('Kỳ khôi (bay bổng)', None),
    'c1-wistful': ('Man mác tiếc nuối', None),
    'c1-fleeting': ('Thoáng qua', None),
    'c1-enduring': ('Bền vững (lâu dài)', None),
    'c1-ubiquitous': ('Có mặt khắp nơi', None),
    'c1-elusive': ('Khó nắm bắt', None),
    'c1-tangible': ('Hữu hình', None),
    'c1-meticulous': ('Tỉ mỉ', None),
    'c1-conscientious': ('Tận tâm', None),
    'c1-diligent': ('Chăm chỉ (cần mẫn)', None),
    'c1-pragmatic': ('Thực dụng', None),
    'c1-cynical': ('Yếm thế (hoài nghi)', None),
    'c1-skeptical': ('Hoài nghi', None),
    'c1-gullible': ('Cả tin', None),
    'c1-smug': ('Tự mãn', None),
    'c1-aloof': ('Xa cách', None),
    'c1-candid': ('Thẳng thắn', None),
    'c1-tactless': ('Vụng về (thiếu tế nhị)', None),
    'c1-assertive': ('Quyết đoán', None),
    'c1-submissive': ('Phục tùng', None),
    'c1-vindictive': ('Thù dai (hay trả thù)', None),
    'c1-magnanimous': ('Cao thượng', None),
    'c1-benevolent': ('Nhân từ', None),
    'c1-malicious': ('Ác ý', None),
    'c1-frugal': ('Tiết kiệm', None),
    'c1-extravagant': ('Phung phí', None),
    'c1-impulsive': ('Bốc đồng', None),
    'c1-spontaneous': ('Tự phát (ngẫu hứng)', None),
    'c1-calculating': ('Toan tính', None),
    'c1-eccentric': ('Lập dị', None),
    'c1-unconventional': ('Khác thường (phi truyền thống)', None),
    'c1-sophisticated': ('Sành điệu', None),
    'c1-witty': ('Dí dỏm', None),
    'c1-sarcastic': ('Mỉa mai', None),
    'c1-charismatic': ('Lôi cuốn (có sức hút)', None),
    'c1-condescending': ('Kẻ cả', None),
    'c1-pretentious': ('Kiểu cách (khoe khoang)', None),
    'c1-empire': ('Đế chế', None),
    'c1-colony': ('Thuộc địa', None),
    'c1-revolution': ('Cuộc cách mạng', None),
    'c1-uprising': ('Cuộc nổi dậy', None),
    'c1-dictatorship': ('Chế độ độc tài', None),
    'c1-democracy': ('Nền dân chủ', None),
    'c1-monarchy': ('Chế độ quân chủ', None),
    'c1-republic': ('Nền cộng hòa', None),
    'c1-regime': ('Chế độ (chính quyền)', None),
    'c1-treaty': ('Hiệp ước', None),
    'c1-alliance': ('Liên minh', None),
    'c1-invasion': ('Cuộc xâm lược', None),
    'c1-occupation-military': ('Sự chiếm đóng', None),
    'c1-independence': ('Nền độc lập', None),
    'c1-sovereignty': ('Chủ quyền', None),
    'c1-civil-war': ('Nội chiến', None),
    'c1-ceasefire': ('Lệnh ngừng bắn', None),
    'c1-refugee': ('Người tị nạn', None),
    'c1-asylum': ('Sự tị nạn (quyền tị nạn)', None),
    'c1-exile': ('Sự lưu đày', None),
    'c1-dynasty': ('Triều đại', None),
    'c1-heir': ('Người thừa kế', None),
    'c1-coup': ('Cuộc đảo chính', None),
    'c1-sanctions': ('Lệnh trừng phạt', None),
    'c1-diplomacy': ('Ngoại giao', None),
    'c1-ambassador': ('Đại sứ', None),
    'c1-embassy': ('Đại sứ quán', None),
    'c1-summit-meeting': ('Hội nghị thượng đỉnh', None),
    'c1-constitution': ('Hiến pháp', None),
    'c1-amendment': ('Tu chính án', None),
    'c1-bottom-line': ('Điểm mấu chốt (kết quả cuối cùng)', None),
    'c1-ballpark-figure': ('Con số ước chừng', None),
    'c1-to-touch-base': ('Liên hệ trao đổi', None),
    'c1-to-circle-back': ('Quay lại bàn tiếp (sau)', None),
    'c1-bandwidth-capacity': ('Khả năng (thời gian) đảm nhận', None),
    'c1-to-leverage': ('Tận dụng (đòn bẩy)', None),
    'c1-synergy': ('Sự cộng hưởng', None),
    'c1-to-scale-up': ('Mở rộng quy mô', None),
    'c1-to-pivot': ('Chuyển hướng', None),
    'c1-to-onboard': ('Đào tạo hội nhập (nhân viên mới)', None),
    'c1-to-roll-out': ('Triển khai', None),
    'c1-to-ramp-up': ('Đẩy mạnh', None),
    'c1-to-wind-down': ('Giảm dần (thu hẹp)', None),
    'c1-to-cut-corners': ('Làm ẩu (bớt xén)', None),
    'c1-red-tape': ('Thủ tục hành chính rườm rà', None),
    'c1-to-go-the-extra-mile': ('Nỗ lực hết mình (vượt trên mong đợi)', None),
    'c1-on-the-same-page': ('Cùng quan điểm (đồng thuận)', None),
    'c1-to-keep-in-the-loop': ('Cập nhật thông tin cho', None),
    'c1-to-drop-the-ball': ('Sơ suất (làm hỏng việc)', None),
    'c1-to-think-outside-the-box': ('Suy nghĩ sáng tạo (khác biệt)', None),
    'c1-win-win': ('Đôi bên cùng có lợi', None),
    'c1-game-changer': ('Bước ngoặt (yếu tố thay đổi cuộc chơi)', None),
    'c1-low-hanging-fruit': ('Việc dễ làm trước (thành quả dễ đạt)', None),
    'c1-deliverable': ('Sản phẩm bàn giao', None),
    'c1-return-on-investment': ('Lợi tức đầu tư', None),
    'c1-to-sign-off-on': ('Phê duyệt', None),
    'c1-to-run-something-by-someone': ('Hỏi ý kiến ai đó trước', None),
    'c1-stakeholder-buy-in': ('Sự đồng thuận của các bên liên quan', None),
    'c1-back-to-the-drawing-board': ('Quay lại từ đầu', None),
    'c1-take-it-offline': ('Bàn riêng (sau cuộc họp)', None),
    'c1-over-the-moon': ('Vui sướng tột độ', None),
    'c1-down-in-the-dumps': ('Buồn rười rượi', None),
    'c1-on-edge': ('Căng thẳng như ngồi trên lửa', None),
    'c1-fed-up': ('Chán ngấy', None),
    'c1-at-a-loss': ('Không biết làm gì (bối rối)', None),
    'c1-in-two-minds': ('Phân vân', None),
    'c1-under-the-weather': ('Hơi mệt (khó ở)', None),
    'c1-taken-aback': ('Sững sờ', None),
    'c1-blown-away': ('Choáng ngợp (kinh ngạc)', None),
    'c1-torn-between': ('Giằng xé (giữa)', None),
    'c1-beside-oneself': ('Mất hết bình tĩnh', None),
    'c1-heartbroken': ('Đau lòng (trái tim tan vỡ)', None),
    'c1-on-the-fence': ('Chưa ngã ngũ (chưa quyết định)', None),
    'c1-laid-back': ('Thoải mái (dễ tính)', None),
    'c1-uptight': ('Căng thẳng gò bó', None),
    'c1-sick-and-tired': ('Chán ngán tận cổ', None),
    'c1-in-a-rut': ('Sa vào lối mòn', None),
    'c1-head-over-heels': ('Yêu say đắm', None),
    'c1-cold-feet': ('Chùn bước (sợ hãi vào phút chót)', None),
    'c1-second-thoughts': ('Suy nghĩ lại (do dự)', None),
    'c1-a-weight-off-my-shoulders': ('Trút được gánh nặng', None),
    'c1-butterflies-in-my-stomach': ('Bồn chồn lo lắng', None),
    'c1-a-lump-in-my-throat': ('Nghẹn ngào', None),
    'c1-goosebumps': ('Nổi da gà', None),
    'c1-speechless-with-joy': ('Sung sướng đến không nói nên lời', None),
    'c1-out-of-sorts': ('Khó ở (bực bội)', None),
    'c1-keyed-up': ('Hồi hộp căng thẳng', None),
    'c1-wound-up': ('Kích động (bực bội)', None),
    'c1-mixed-feelings': ('Cảm xúc lẫn lộn', None),
    'c1-at-peace': ('Thanh thản (yên bình)', None),
    'c1-bureaucracy': ('Bộ máy hành chính (quan liêu)', None),
    'c1-paperwork': ('Giấy tờ (thủ tục)', None),
    'c1-to-file-documents': ('Nộp (hồ sơ)', None),
    'c1-applicant': ('Người nộp đơn', None),
    'c1-eligible': ('Đủ điều kiện', None),
    'c1-to-qualify': ('Đáp ứng điều kiện', None),
    'c1-prerequisite': ('Điều kiện tiên quyết', None),
    'c1-clause': ('Điều khoản', None),
    'c1-compliance': ('Sự tuân thủ', None),
    'c1-regulation': ('Quy định', None),
    'c1-license-permit': ('Giấy phép', None),
    'c1-to-authorize': ('Cho phép (ủy quyền)', None),
    'c1-notary': ('Công chứng viên', None),
    'c1-affidavit': ('Bản khai có tuyên thệ', None),
    'c1-deed': ('Chứng thư (giấy chuyển nhượng)', None),
    'c1-title-property': ('Giấy chứng nhận quyền sở hữu', None),
    'c1-lien': ('Quyền cầm giữ tài sản', None),
    'c1-easement': ('Quyền địa dịch', None),
    'c1-appraisal': ('Sự thẩm định giá', None),
    'c1-closing-real-estate': ('Hoàn tất giao dịch (nhà đất)', None),
    'c1-escrow': ('Tài khoản ký quỹ', None),
    'c1-commission-fee': ('Hoa hồng', None),
    'c1-listing-property': ('Tin rao bán (bất động sản)', None),
    'c1-counteroffer': ('Đề nghị trả giá lại', None),
    'c1-contingency': ('Điều kiện ràng buộc', None),
    'c1-zoning-variance': ('Ngoại lệ quy hoạch', None),
    'c1-deadline-filing': ('Hạn nộp hồ sơ', None),
    'c1-certified-copy': ('Bản sao có chứng thực', None),
    'c1-jurisdiction': ('Thẩm quyền (tài phán)', None),
    'c1-liability': ('Trách nhiệm pháp lý', None),
    'c1-galaxy': ('Thiên hà', None),
    'c1-universe': ('Vũ trụ', None),
    'c1-black-hole': ('Hố đen', None),
    'c1-telescope': ('Kính thiên văn', None),
    'c1-asteroid': ('Tiểu hành tinh', None),
    'c1-eclipse': ('Nhật thực (nguyệt thực)', None),
    'c1-constellation': ('Chòm sao', None),
    'c1-particle': ('Hạt (vật chất)', None),
    'c1-radiation': ('Bức xạ', None),
    'c1-electron': ('Điện tử (electron)', None),
    'c1-isotope': ('Đồng vị', None),
    'c1-nuclear-fusion': ('Phản ứng nhiệt hạch', None),
    'c1-magnetic-field': ('Từ trường', None),
    'c1-friction': ('Ma sát', None),
    'c1-velocity': ('Vận tốc', None),
    'c1-acceleration': ('Gia tốc', None),
    'c1-momentum': ('Động lượng', None),
    'c1-inertia': ('Quán tính', None),
    'c1-density': ('Mật độ (khối lượng riêng)', None),
    'c1-pressure-physics': ('Áp suất', None),
    'c1-vacuum': ('Chân không', None),
    'c1-wavelength': ('Bước sóng', None),
    'c1-frequency-physics': ('Tần số', None),
    'c1-spectrum': ('Quang phổ', None),
    'c1-photosynthesis': ('Quang hợp', None),
    'c1-enzyme': ('Enzyme (men)', None),
    'c1-hormone': ('Hormone (nội tiết tố)', None),
    'c1-metabolism': ('Sự trao đổi chất', None),
    'c1-mutation': ('Đột biến', None),
    'c1-organism': ('Cơ thể sống (sinh vật)', None),
    'c1-to-allege': ('Cáo buộc (khẳng định chưa kiểm chứng)', None),
    'c1-to-allude': ('Ám chỉ', None),
    'c1-to-ascertain': ('Xác minh', None),
    'c1-to-bolster': ('Củng cố', None),
    'c1-to-circumvent': ('Lách (luật, quy định)', None),
    'c1-to-coerce': ('Cưỡng ép', None),
    'c1-to-condone': ('Dung túng', None),
    'c1-to-consolidate': ('Củng cố (hợp nhất)', None),
    'c1-to-curb': ('Kiềm chế', None),
    'c1-to-deter': ('Ngăn chặn (răn đe)', None),
    'c1-to-diminish': ('Suy giảm', None),
    'c1-to-disclose': ('Tiết lộ (công khai)', None),
    'c1-to-disrupt': ('Làm gián đoạn', None),
    'c1-to-divert': ('Chuyển hướng (chuyển dòng)', None),
    'c1-to-elicit': ('Gợi ra (khơi gợi)', None),
    'c1-to-endorse': ('Xác nhận ủng hộ', None),
    'c1-to-entail': ('Kéo theo (đòi hỏi)', None),
    'c1-to-eradicate': ('Xóa bỏ (tận gốc)', None),
    'c1-to-exacerbate': ('Làm trầm trọng thêm', None),
    'c1-to-exemplify': ('Minh họa (làm ví dụ điển hình)', None),
    'c1-to-foster': ('Thúc đẩy (nuôi dưỡng)', None),
    'c1-to-hinder': ('Cản trở', None),
    'c1-to-impede': ('Gây trở ngại', None),
    'c1-to-instigate': ('Xúi giục', None),
    'c1-to-mitigate': ('Giảm nhẹ', None),
    'c1-to-nurture': ('Nuôi dưỡng (vun đắp)', None),
    'c1-to-omit': ('Bỏ sót', None),
    'c1-to-precede': ('Diễn ra trước (đi trước)', None),
    'c1-to-preclude': ('Ngăn cản trước (loại trừ khả năng)', None),
    'c1-to-prompt': ('Thúc đẩy (gợi ý)', None),
    'c1-to-refrain': ('Kiềm chế (không làm)', None),
    'c1-to-relinquish': ('Từ bỏ', None),
    'c1-to-render': ('Khiến trở nên', None),
    'c1-to-scrutinize': ('Xem xét kỹ lưỡng', None),
    'c1-to-stipulate': ('Quy định (trong hợp đồng)', None),
    'c1-to-substantiate': ('Chứng minh (bằng chứng cụ thể)', None),
    'c1-to-thrive': ('Phát triển mạnh mẽ', None),
    'c1-to-undermine': ('Làm suy yếu', None),
    'c1-to-uphold': ('Duy trì (bảo vệ)', None),
    'c1-to-waive': ('Từ bỏ (quyền lợi)', None),
    'c1-to-yield': ('Sinh ra (mang lại kết quả)', None),
    'c1-to-abolish': ('Bãi bỏ', None),
    'c1-to-accommodate': ('Đáp ứng (tiếp nhận)', None),
    'c1-to-adhere': ('Tuân theo', None),
    'c1-to-attain': ('Đạt được', None),
    'c1-to-compel': ('Buộc phải', None),
    'c1-to-confine': ('Giới hạn (giam giữ)', None),
    'c1-to-contemplate': ('Cân nhắc (suy xét)', None),
    'c1-to-depict': ('Miêu tả', None),
    'c1-to-dispel': ('Xua tan', None),
    'c1-to-embody': ('Thể hiện (hiện thân của)', None),
    'c1-to-evoke': ('Gợi lên', None),
    'c1-to-forge': ('Rèn giũa (tạo dựng)', None),
    'c1-to-grasp': ('Nắm bắt (hiểu)', None),
    'c1-to-infringe': ('Vi phạm', None),
    'c1-to-overturn': ('Lật ngược (bác bỏ)', None),
    'c1-to-plead': ('Van xin (biện hộ)', None),
    'c1-to-reconcile-ideas': ('Dung hòa', None),
    'c1-to-surpass': ('Vượt qua (vượt trội)', None),
    'c1-to-unveil': ('Tiết lộ (công bố)', None),
    'c1-albeit': ('Mặc dù', None),
    'c1-notwithstanding': ('Tuy nhiên (bất kể)', None),
    'c1-insofar-as': ('Trong chừng mực mà', None),
    'c1-whereby': ('Theo đó', None),
    'c1-hereby': ('Bằng văn bản này', None),
    'c1-thereby': ('Nhờ đó (qua đó)', None),
    'c1-hence': ('Do đó', None),
    'c1-thus': ('Vì vậy', None),
    'c1-henceforth': ('Kể từ nay', None),
    'c1-likewise': ('Tương tự', None),
    'c1-conversely': ('Ngược lại', None),
    'c1-namely': ('Cụ thể là', None),
    'c1-in-lieu-of': ('Thay vì', None),
    'c1-in-light-of': ('Trong bối cảnh (xét đến)', None),
    'c1-in-view-of': ('Xét thấy', None),
    'c1-by-virtue-of': ('Theo (nhờ vào)', None),
    'c1-on-account-of': ('Vì lý do', None),
    'c1-with-a-view-to': ('Nhằm mục đích', None),
    'c1-provided-that': ('Với điều kiện là', None),
    'c1-granted': ('Đành rằng', None),
    'c1-admittedly': ('Phải thừa nhận rằng', None),
    'c1-arguably': ('Có thể nói là', None),
    'c1-presumably': ('Có lẽ (giả định là)', None),
    'c1-allegedly': ('Được cho là (theo cáo buộc)', None),
    'c1-ostensibly': ('Bề ngoài thì (có vẻ như)', None),
    'c1-undoubtedly': ('Chắc chắn (không nghi ngờ gì)', None),
    'c1-invariably': ('Luôn luôn (không thay đổi)', None),
    'c1-nevertheless-formal': ('Tuy nhiên', None),
    'c1-to-the-extent-that': ('Đến mức mà', None),
    'c1-for-all-intents-and-purposes': ('Trên thực tế (xét mọi khía cạnh)', None),
    'c1-sommelier': ('Người thử rượu (sommelier)', None),
    'c1-vintage-wine': ('Niên vụ (rượu vang)', None),
    'c1-aroma': ('Hương thơm', None),
    'c1-palate': ('Vị giác', None),
    'c1-aftertaste': ('Dư vị', None),
    'c1-full-bodied': ('Đậm đà (rượu)', None),
    'c1-dry-wine': ('Khô (rượu vang)', None),
    'c1-sparkling': ('Sủi bọt (có ga)', None),
    'c1-brew': ('Nước ủ (pha chế)', None),
    'c1-roast-coffee': ('Mức rang (cà phê)', None),
    'c1-espresso': ('Cà phê espresso', None),
    'c1-decaf': ('Đã khử caffeine', None),
    'c1-barista': ('Người pha chế cà phê (barista)', None),
    'c1-tasting-menu': ('Thực đơn nếm thử', None),
    'c1-pairing': ('Sự kết hợp (món ăn với rượu)', None),
    'c1-a-la-carte': ('Gọi món theo thực đơn (à la carte)', None),
    'c1-garnish': ('Đồ trang trí món ăn', None),
    'c1-drizzle-of-oil': ('Rưới một chút (dầu)', None),
    'c1-reduction-sauce': ('Nước sốt cô đặc', None),
    'c1-glaze': ('Lớp phủ bóng (sốt)', None),
    'c1-umami': ('Vị umami', None),
    'c1-zest': ('Vỏ bào (chanh, cam)', None),
    'c1-to-caramelize': ('Caramen hóa', None),
    'c1-to-braise': ('Om (hầm)', None),
    'c1-to-poach': ('Chần (luộc nhẹ)', None),
    'c1-al-dente': ('Vừa chín tới (al dente)', None),
    'c1-medium-rare': ('Tái chín vừa', None),
    'c1-well-done': ('Chín kỹ', None),
    'c1-signature-dish': ('Món đặc trưng', None),
    'c1-chefs-recommendation': ('Đề xuất của đầu bếp', None),
    'c1-floor-plan': ('Sơ đồ mặt bằng', None),
    'c1-open-plan': ('Không gian mở', None),
    'c1-layout': ('Bố trí (mặt bằng)', None),
    'c1-fixture': ('Thiết bị cố định', None),
    'c1-cabinetry': ('Tủ (nội thất gắn tường)', None),
    'c1-countertop': ('Mặt bàn bếp', None),
    'c1-backsplash': ('Tấm ốp chống bám bẩn (sau bếp)', None),
    'c1-grout': ('Vữa chít mạch', None),
    'c1-hardwood-floor': ('Sàn gỗ tự nhiên', None),
    'c1-laminate': ('Sàn gỗ công nghiệp (laminate)', None),
    'c1-molding-trim': ('Phào chỉ', None),
    'c1-baseboard': ('Phào chân tường', None),
    'c1-crown-molding': ('Phào trần', None),
    'c1-sconce': ('Đèn tường', None),
    'c1-pendant-light': ('Đèn thả trần', None),
    'c1-recessed-lighting': ('Đèn âm trần', None),
    'c1-dimmer': ('Bộ điều chỉnh độ sáng', None),
    'c1-vent': ('Lỗ thông gió', None),
    'c1-duct': ('Ống dẫn khí', None),
    'c1-hvac': ('Hệ thống điều hòa thông gió (HVAC)', None),
    'c1-sump-pump': ('Máy bơm hố ga', None),
    'c1-water-heater': ('Máy nước nóng', None),
    'c1-circuit-breaker': ('Cầu dao (aptomat)', None),
    'c1-load-bearing-wall': ('Tường chịu lực', None),
    'c1-joist': ('Dầm sàn (xà gồ)', None),
    'c1-stud-wall': ('Khung xương tường', None),
    'c1-subfloor': ('Lớp sàn lót', None),
    'c1-caulk': ('Keo trám', None),
    'c1-primer-paint': ('Sơn lót', None),
    'c1-punch-list': ('Danh sách hạng mục cần hoàn thiện', None),
    'c1-change-order': ('Lệnh thay đổi (thi công)', None),
    'c1-scope-of-work': ('Phạm vi công việc', None),
    'c1-rapport': ('Mối quan hệ hòa hợp', None),
    'c1-chemistry-between-people': ('Sự hợp cạ (giữa hai người)', None),
    'c1-affinity': ('Sự đồng điệu (thân thiện tự nhiên)', None),
    'c1-estranged': ('Xa cách (rạn nứt quan hệ)', None),
    'c1-reconciliation': ('Sự hòa giải', None),
    'c1-to-confide': ('Tâm sự (thổ lộ)', None),
    'c1-confidant': ('Người tâm sự cùng', None),
    'c1-to-fall-out': ('Bất hòa (cãi vã)', None),
    'c1-to-patch-things-up': ('Hàn gắn', None),
    'c1-to-drift-apart': ('Xa dần nhau', None),
    'c1-to-hit-it-off': ('Hợp nhau ngay', None),
    'c1-to-have-a-soft-spot-for': ('Có cảm tình đặc biệt với', None),
    'c1-to-hold-a-grudge': ('Để bụng (giữ mối hận)', None),
    'c1-to-bury-the-hatchet': ('Xóa bỏ hiềm khích', None),
    'c1-to-make-amends': ('Sửa sai (bù đắp lỗi lầm)', None),
    'c1-to-take-for-granted': ('Coi là hiển nhiên', None),
    'c1-to-lean-on': ('Dựa vào', None),
    'c1-to-stick-up-for': ('Bênh vực', None),
    'c1-to-look-out-for': ('Quan tâm chăm sóc', None),
    'c1-to-see-eye-to-eye': ('Đồng quan điểm', None),
    'c1-to-get-on-someones-nerves': ('Làm ai đó phát cáu', None),
    'c1-to-give-the-benefit-of-the-doubt': ('Tin tưởng dù chưa chắc chắn', None),
    'c1-to-read-between-the-lines': ('Đọc ra ẩn ý', None),
    'c1-to-beat-around-the-bush': ('Vòng vo', None),
    'c1-to-get-to-the-point': ('Đi thẳng vào vấn đề', None),
    'c1-to-keep-someone-at-arms-length': ('Giữ khoảng cách với ai đó', None),
    'c1-to-go-behind-someones-back': ('Qua mặt (sau lưng ai đó)', None),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('Bộc lộ cảm xúc thật (không giấu giếm)', None),
    'c1-tactfully': ('Khéo léo (tế nhị)', None),
    'c1-passive-aggressive': ('Thụ động hung hăng (passive-aggressive)', None),
    'c1-mediocre': ('Tầm thường', None),
    'c1-subpar': ('Dưới mức trung bình', None),
    'c1-top-notch': ('Hàng đầu (xuất sắc)', None),
    'c1-first-rate': ('Hạng nhất', None),
    'c1-second-rate': ('Hạng hai', None),
    'c1-state-of-the-art': ('Hiện đại nhất (tối tân)', None),
    'c1-cutting-edge': ('Tiên phong (đi đầu công nghệ)', None),
    'c1-run-of-the-mill': ('Tầm thường (bình thường)', None),
    'c1-exceptional': ('Xuất sắc (ngoại lệ)', None),
    'c1-flawless': ('Hoàn hảo (không tì vết)', None),
    'c1-impeccable': ('Hoàn hảo (chỉn chu)', None),
    'c1-shoddy': ('Kém chất lượng', None),
    'c1-sloppy': ('Cẩu thả', None),
    'c1-half-baked': ('Chưa chín muồi (sơ sài)', None),
    'c1-polished': ('Trau chuốt', None),
    'c1-crude': ('Thô sơ', None),
    'c1-rudimentary': ('Sơ khai', None),
    'c1-intricate': ('Phức tạp tinh vi', None),
    'c1-convoluted': ('Rối rắm', None),
    'c1-user-friendly': ('Thân thiện với người dùng', None),
    'c1-foolproof': ('Không thể sai sót', None),
    'c1-robust': ('Chắc chắn (bền vững)', None),
    'c1-seamless': ('Liền mạch (trơn tru)', None),
    'c1-glitchy': ('Hay lỗi (trục trặc)', None),
    'c1-clunky': ('Vụng về (thiếu linh hoạt)', None),
    'c1-sleek': ('Thanh mảnh (bóng bẩy)', None),
    'c1-bulky': ('Kềnh càng (cồng kềnh)', None),
    'c1-compact': ('Gọn nhẹ', None),
    'c1-flimsy': ('Mỏng manh (kém chắc chắn)', None),
    'c1-durable': ('Bền', None),
    'c1-to-mumble': ('Nói lẩm bẩm', None),
    'c1-to-mutter': ('Lầm bầm', None),
    'c1-to-stutter': ('Nói lắp', None),
    'c1-to-slur': ('Nói líu lưỡi', None),
    'c1-to-ramble': ('Nói lan man', None),
    'c1-to-rant': ('Thao thao bất tuyệt (giận dữ)', None),
    'c1-to-grumble': ('Cằn nhằn', None),
    'c1-to-whine': ('Rên rỉ (nhõng nhẽo)', None),
    'c1-to-snap-at-someone': ('Gắt gỏng (với ai đó)', None),
    'c1-hoarse': ('Khàn giọng', None),
    'c1-raspy': ('Khàn đục (giọng khàn rè)', None),
    'c1-monotone': ('Đều đều (không ngữ điệu)', None),
    'c1-shrill': ('The thé', None),
    'c1-deafening': ('Điếc tai (chói tai)', None),
    'c1-muffled': ('Nghẹt (âm thanh bị bóp nghẹt)', None),
    'c1-faint-sound': ('Yếu ớt (âm thanh nhỏ)', None),
    'c1-to-hum': ('Ngân nga', None),
    'c1-to-chant': ('Hô vang (đồng thanh)', None),
    'c1-to-murmur': ('Thì thầm', None),
    'c1-to-bellow': ('Gầm lên (quát to)', None),
    'c1-to-chuckle': ('Cười khẽ', None),
    'c1-to-giggle': ('Cười khúc khích', None),
    'c1-to-snicker': ('Cười thầm (chế giễu)', None),
    'c1-to-sob': ('Nức nở', None),
    'c1-to-wail': ('Khóc than (gào khóc)', None),
    'c1-to-howl': ('Tru (hú) lên', None),
    'c1-to-shriek': ('Thét lên', None),
    'c1-to-gasp': ('Hổn hển (thở hắt ra)', None),
    'c1-pitch-voice': ('Cao độ (giọng nói)', None),
    'c1-accent-stress': ('Trọng âm', None),
    'c1-asset': ('Tài sản', None),
    'c1-liability-finance': ('Nợ phải trả', None),
    'c1-equity': ('Vốn chủ sở hữu', None),
    'c1-portfolio': ('Danh mục đầu tư', None),
    'c1-dividend': ('Cổ tức', None),
    'c1-bond-finance': ('Trái phiếu', None),
    'c1-hedge': ('Phòng ngừa rủi ro (hedge)', None),
    'c1-liquidity': ('Tính thanh khoản', None),
    'c1-collateral': ('Tài sản thế chấp', None),
    'c1-default-loan': ('Vỡ nợ (không trả được nợ)', None),
    'c1-foreclosure': ('Tịch biên tài sản thế chấp', None),
    'c1-appreciation-value': ('Sự tăng giá trị', None),
    'c1-depreciation': ('Khấu hao (giảm giá trị)', None),
    'c1-capital-gains': ('Lãi vốn', None),
    'c1-write-off': ('Khoản xóa nợ (miễn giảm)', None),
    'c1-overhead': ('Chi phí quản lý chung', None),
    'c1-payroll': ('Bảng lương', None),
    'c1-gross-before-deductions': ('Tổng thu nhập (trước khấu trừ)', None),
    'c1-net': ('Thực nhận (sau khấu trừ)', None),
    'c1-deductible': ('Được khấu trừ', None),
    'c1-exemption': ('Sự miễn trừ', None),
    'c1-audit': ('Kiểm toán', None),
    'c1-ledger': ('Sổ cái', None),
    'c1-bookkeeping': ('Kế toán ghi sổ', None),
    'c1-break-even': ('Điểm hòa vốn', None),
    'c1-turnover': ('Doanh thu (vòng quay)', None),
    'c1-markup': ('Mức chênh lệch giá (lợi nhuận cộng thêm)', None),
    'c1-cash-reserve': ('Quỹ dự trữ tiền mặt', None),
    'c1-venture-capital': ('Vốn đầu tư mạo hiểm', None),
    'c1-fiscal-year': ('Năm tài chính', None),
    'c1-expedition': ('Cuộc thám hiểm', None),
    'c1-pilgrimage': ('Cuộc hành hương', None),
    'c1-getaway': ('Chuyến đi ngắn ngày (nghỉ dưỡng)', None),
    'c1-sabbatical': ('Kỳ nghỉ dài hạn (sabbatical)', None),
    'c1-nomad': ('Người du mục', None),
    'c1-expatriate': ('Người xa xứ (kiều dân)', None),
    'c1-immigrant': ('Người nhập cư', None),
    'c1-to-relocate': ('Chuyển đến nơi ở mới', None),
    'c1-to-settle-down': ('Ổn định cuộc sống', None),
    'c1-culture-shock': ('Sốc văn hóa', None),
    'c1-to-assimilate': ('Hòa nhập (đồng hóa)', None),
    'c1-bilingual': ('Song ngữ', None),
    'c1-multilingual': ('Đa ngôn ngữ', None),
    'c1-mother-tongue': ('Tiếng mẹ đẻ', None),
    'c1-dialect': ('Phương ngữ', None),
    'c1-slang': ('Tiếng lóng', None),
    'c1-jargon': ('Biệt ngữ (chuyên ngành)', None),
    'c1-register-language': ('Văn phong (mức độ trang trọng)', None),
    'c1-colloquial': ('Khẩu ngữ (thông tục)', None),
    'c1-fluency': ('Sự trôi chảy (ngôn ngữ)', None),
    'c1-proficiency': ('Trình độ thông thạo', None),
    'c1-to-master': ('Thông thạo (làm chủ)', None),
    'c1-immersion': ('Sự đắm mình (học ngôn ngữ)', None),
    'c1-intonation': ('Ngữ điệu', None),
    'c1-to-mispronounce': ('Phát âm sai', None),
    'c1-false-friend': ('Từ giả đồng dạng (false friend)', None),
    'c1-cognate': ('Từ đồng nguyên', None),
    'c1-loanword': ('Từ vay mượn', None),
    'c1-literacy': ('Khả năng đọc viết', None),
    'c1-interpreter': ('Phiên dịch viên', None),
    'c1-latency': ('Độ trễ', None),
    'c1-server': ('Máy chủ', None),
    'c1-cloud-computing': ('Điện toán đám mây', None),
    'c1-backup-data': ('Sao lưu (dữ liệu)', None),
    'c1-firewall': ('Tường lửa', None),
    'c1-malware': ('Phần mềm độc hại', None),
    'c1-phishing': ('Lừa đảo trực tuyến (phishing)', None),
    'c1-two-factor-authentication': ('Xác thực hai yếu tố', None),
    'c1-biometric': ('Sinh trắc học', None),
    'c1-open-source': ('Mã nguồn mở', None),
    'c1-interface': ('Giao diện', None),
    'c1-plugin': ('Tiện ích mở rộng (plugin)', None),
    'c1-patch-software': ('Bản vá (phần mềm)', None),
    'c1-to-deploy': ('Triển khai (đưa vào vận hành)', None),
    'c1-release-version': ('Phiên bản phát hành', None),
    'c1-beta': ('Bản beta (thử nghiệm)', None),
    'c1-blockchain': ('Chuỗi khối (blockchain)', None),
    'c1-cryptocurrency': ('Tiền điện tử (tiền mã hóa)', None),
    'c1-machine-learning': ('Học máy', None),
    'c1-neural-network': ('Mạng nơ-ron', None),
    'c1-dataset': ('Tập dữ liệu', None),
    'c1-drone': ('Máy bay không người lái', None),
    'c1-sensor': ('Cảm biến', None),
    'c1-augmented-reality': ('Thực tế tăng cường', None),
    'c1-wearable': ('Thiết bị đeo thông minh', None),
    'c1-smart-home': ('Nhà thông minh', None),
    'c1-bandwidth-network': ('Băng thông', None),
    'c1-outage': ('Sự cố mất dịch vụ (gián đoạn)', None),
    'c1-scalability': ('Khả năng mở rộng', None),
    'c1-encryption-key': ('Khóa mã hóa', None),
    'c1-cinematography': ('Kỹ thuật quay phim', None),
    'c1-close-up': ('Cận cảnh', None),
    'c1-wide-shot': ('Toàn cảnh', None),
    'c1-montage': ('Chuỗi cảnh dựng (montage)', None),
    'c1-flashback': ('Hồi tưởng', None),
    'c1-voice-over': ('Lời bình (giọng đọc ngoài hình)', None),
    'c1-subplot': ('Tình tiết phụ', None),
    'c1-protagonist': ('Nhân vật chính', None),
    'c1-antagonist': ('Nhân vật phản diện', None),
    'c1-cliffhanger': ('Kết thúc gây hồi hộp (cliffhanger)', None),
    'c1-plot-twist': ('Bước ngoặt cốt truyện', None),
    'c1-foreshadowing': ('Sự báo trước (dự báo tình tiết)', None),
    'c1-pacing': ('Nhịp độ (kể chuyện)', None),
    'c1-casting': ('Việc chọn diễn viên (casting)', None),
    'c1-cameo': ('Vai khách mời (cameo)', None),
    'c1-sequel': ('Phần tiếp theo', None),
    'c1-prequel': ('Phần tiền truyện', None),
    'c1-reboot': ('Làm lại (khởi động lại loạt phim)', None),
    'c1-box-office': ('Doanh thu phòng vé', None),
    'c1-blockbuster': ('Phim bom tấn', None),
    'c1-indie-film': ('Phim độc lập', None),
    'c1-cult-classic': ('Tác phẩm kinh điển được ái mộ', None),
    'c1-critically-acclaimed': ('Được giới phê bình đánh giá cao', None),
    'c1-dubbed': ('Lồng tiếng', None),
    'c1-subtitled': ('Có phụ đề', None),
    'c1-screening': ('Buổi chiếu (phim)', None),
    'c1-pilot-episode': ('Tập thí điểm (pilot)', None),
    'c1-season-finale': ('Tập cuối mùa', None),
    'c1-showrunner': ('Nhà điều hành sản xuất (showrunner)', None),
    'c1-storyboard': ('Bảng phân cảnh (storyboard)', None),
    'c1-on-the-mend': ('Đang hồi phục', None),
    'c1-run-down-exhausted': ('Kiệt sức', None),
    'c1-in-good-shape': ('Sức khỏe tốt (thể trạng tốt)', None),
    'c1-out-of-shape': ('Mất phong độ (thể trạng kém)', None),
    'c1-a-clean-bill-of-health': ('Kết quả khám sức khỏe hoàn toàn tốt', None),
    'c1-to-pull-a-muscle': ('Bị căng cơ', None),
    'c1-wear-and-tear': ('Sự hao mòn', None),
    'c1-to-nod-off': ('Ngủ gật', None),
    'c1-to-sleep-like-a-log': ('Ngủ say như chết', None),
    'c1-to-toss-and-turn': ('Trằn trọc', None),
    'c1-over-the-counter': ('Không cần kê đơn', None),
    'c1-second-opinion': ('Ý kiến tư vấn thứ hai', None),
    'c1-bedside-manner': ('Thái độ với bệnh nhân', None),
    'c1-to-be-discharged': ('Xuất viện', None),
    'c1-to-be-admitted-hospital': ('Nhập viện', None),
    'c1-outpatient': ('Bệnh nhân ngoại trú', None),
    'c1-follow-up-appointment': ('Lịch tái khám', None),
    'c1-referral': ('Giấy giới thiệu (chuyển khám chuyên khoa)', None),
    'c1-to-take-a-turn-for-the-worse': ('Trở nặng (chuyển biến xấu)', None),
    'c1-to-black-out': ('Ngất đi (mất ý thức)', None),
    'c1-under-the-knife': ('Lên bàn mổ', None),
    'c1-slipped-disc': ('Thoát vị đĩa đệm', None),
    'c1-jet-lagged': ('Bị lệch múi giờ', None),
    'c1-on-medication': ('Đang dùng thuốc điều trị', None),
    'c1-immune-to': ('Miễn dịch với', None),
    'c1-prone-to': ('Dễ mắc phải (có xu hướng)', None),
    'c1-relapse': ('Tái phát', None),
    'c1-remission': ('Sự thuyên giảm (bệnh)', None),
    'c1-a-no-brainer': ('Điều hiển nhiên (dễ như trở bàn tay)', None),
    'c1-a-long-shot': ('Khả năng mong manh', None),
    'c1-a-close-call': ('Suýt nữa thì (thoát hiểm trong gang tấc)', None),
    'c1-a-wake-up-call': ('Lời cảnh tỉnh', None),
    'c1-a-catch-hidden-problem': ('Vấn đề ẩn giấu (cái bẫy)', None),
    'c1-the-upside': ('Mặt tích cực', None),
    'c1-the-downside': ('Mặt hạn chế', None),
    'c1-a-trade-off': ('Sự đánh đổi', None),
    'c1-a-loophole': ('Kẽ hở (pháp lý)', None),
    'c1-a-setback': ('Bước lùi (trở ngại)', None),
    'c1-a-blessing-in-disguise': ('Trong cái rủi có cái may', None),
    'c1-the-tip-of-the-iceberg': ('Phần nổi của tảng băng chìm', None),
    'c1-the-last-straw': ('Giọt nước tràn ly', None),
    'c1-a-double-edged-sword': ('Con dao hai lưỡi', None),
    'c1-the-elephant-in-the-room': ('Vấn đề hiển nhiên nhưng không ai nhắc tới', None),
    'c1-a-grey-area': ('Vùng xám (không rõ ràng)', None),
    'c1-a-slippery-slope': ('Con dốc trơn trượt (nguy cơ trượt dài)', None),
    'c1-a-vicious-circle': ('Vòng luẩn quẩn', None),
    'c1-a-stepping-stone': ('Bàn đạp', None),
    'c1-a-rule-of-thumb': ('Quy tắc kinh nghiệm', None),
    'c1-a-rain-check': ('Hẹn dịp khác', None),
    'c1-a-heads-up': ('Lời báo trước', None),
    'c1-a-hunch': ('Linh cảm', None),
    'c1-a-knack': ('Sở trường (bí quyết)', None),
    'c1-a-pet-peeve': ('Điều khó chịu riêng (gai mắt cá nhân)', None),
    'c1-a-red-flag': ('Dấu hiệu cảnh báo', None),
    'c1-a-silver-lining': ('Tia hy vọng trong khó khăn', None),
    'c1-a-drop-in-the-ocean': ('Giọt nước giữa đại dương', None),
    'c1-a-piece-of-cake': ('Dễ như ăn bánh', None),
    'c1-a-far-cry-from': ('Khác xa so với', None),
    'c1-a-handful': ('Một nhúm (số ít)', None),
    'c1-a-fair-amount': ('Một lượng đáng kể', None),
    'c1-the-lions-share': ('Phần lớn nhất', None),
    'c1-a-fraction': ('Một phần nhỏ', None),
    'c1-the-vast-majority': ('Đại đa số', None),
    'c1-next-to-nothing': ('Gần như không có gì', None),
    'c1-a-great-deal': ('Rất nhiều', None),
    'c1-at-most': ('Nhiều nhất là', None),
    'c1-at-best': ('Tốt nhất thì', None),
    'c1-at-worst': ('Tệ nhất thì', None),
    'c1-in-bulk': ('Với số lượng lớn', None),
    'c1-on-average': ('Trung bình', None),
    'c1-per-capita': ('Bình quân đầu người', None),
    'c1-give-or-take': ('Xấp xỉ (chênh lệch chút ít)', None),
    'c1-a-rough-estimate': ('Ước tính sơ bộ', None),
    'c1-a-round-number': ('Con số tròn', None),
    'c1-the-odds': ('Tỷ lệ (khả năng xảy ra)', None),
    'c1-by-a-narrow-margin': ('Với chênh lệch sít sao', None),
    'c1-by-a-landslide': ('Áp đảo (thắng cách biệt lớn)', None),
    'c1-one-in-ten': ('Cứ mười thì một', None),
    'c1-twofold': ('Gấp đôi', None),
    'c1-exponentially': ('Theo cấp số nhân', None),
    'c1-marginally': ('Một chút (không đáng kể)', None),
    'c1-negligible': ('Không đáng kể', None),
    'c1-sizable': ('Đáng kể (kha khá)', None),
    'c1-umpteen': ('Vô số', None),
    'c1-in-the-region-of': ('Vào khoảng', None),
    'c1-odds-and-ends': ('Đồ linh tinh', None),
    'c1-mentor': ('Người cố vấn', None),
    'c1-protege': ('Người được dìu dắt', None),
    'c1-intern': ('Thực tập sinh', None),
    'c1-veteran-experienced': ('Người kỳ cựu', None),
    'c1-rookie': ('Người mới vào nghề', None),
    'c1-whiz': ('Bậc thầy (cao thủ)', None),
    'c1-workaholic': ('Người nghiện việc', None),
    'c1-slacker': ('Kẻ lười biếng', None),
    'c1-know-it-all': ('Kẻ tự cho là biết tuốt', None),
    'c1-yes-man': ('Người ba phải', None),
    'c1-gatekeeper': ('Người gác cổng (kiểm soát)', None),
    'c1-middleman': ('Người trung gian', None),
    'c1-liaison': ('Người liên lạc (đầu mối)', None),
    'c1-spokesperson': ('Người phát ngôn', None),
    'c1-figurehead': ('Người đứng đầu hình thức (bù nhìn)', None),
    'c1-frontrunner': ('Ứng viên dẫn đầu', None),
    'c1-underdog': ('Kẻ yếu thế', None),
    'c1-dark-horse': ('Ẩn số bất ngờ (dark horse)', None),
    'c1-wildcard': ('Nhân tố khó lường', None),
    'c1-heavyweight': ('Nhân vật nặng ký', None),
    'c1-newcomer': ('Người mới đến', None),
    'c1-insider': ('Người trong cuộc', None),
    'c1-outsider': ('Người ngoài cuộc', None),
    'c1-consultant': ('Nhà tư vấn', None),
    'c1-subcontractor': ('Nhà thầu phụ', None),
    'c1-headhunter': ('Người săn đầu người', None),
    'c1-scapegoat': ('Vật tế thần (người bị đổ lỗi)', None),
    'c1-go-getter': ('Người năng nổ tham vọng', None),
    'c1-universal-healthcare': ('Bảo hiểm y tế toàn dân', None),
    'c1-minimum-wage': ('Lương tối thiểu', None),
    'c1-affordable-housing': ('Nhà ở giá phải chăng', None),
    'c1-surveillance': ('Sự giám sát', None),
    'c1-privacy': ('Quyền riêng tư', None),
    'c1-free-speech': ('Tự do ngôn luận', None),
    'c1-polarization': ('Sự phân cực', None),
    'c1-populism': ('Chủ nghĩa dân túy', None),
    'c1-nationalism': ('Chủ nghĩa dân tộc', None),
    'c1-globalization': ('Toàn cầu hóa', None),
    'c1-austerity': ('Chính sách thắt lưng buộc bụng', None),
    'c1-welfare': ('Phúc lợi xã hội', None),
    'c1-aging-population': ('Dân số già hóa', None),
    'c1-birth-rate': ('Tỷ lệ sinh', None),
    'c1-brain-drain': ('Chảy máu chất xám', None),
    'c1-gig-economy': ('Kinh tế việc làm tự do (gig economy)', None),
    'c1-job-displacement': ('Tình trạng mất việc do tự động hóa', None),
    'c1-universal-basic-income': ('Thu nhập cơ bản toàn dân', None),
    'c1-carbon-tax': ('Thuế carbon', None),
    'c1-nuclear-energy': ('Năng lượng hạt nhân', None),
    'c1-food-security': ('An ninh lương thực', None),
    'c1-water-scarcity': ('Khan hiếm nước', None),
    'c1-urban-sprawl': ('Sự mở rộng đô thị tràn lan', None),
    'c1-rent-control': ('Kiểm soát giá thuê nhà', None),
    'c1-public-transit-funding': ('Ngân sách cho giao thông công cộng', None),
    'c1-data-protection': ('Bảo vệ dữ liệu', None),
    'c1-wealth-gap': ('Khoảng cách giàu nghèo', None),
    'c1-voter-turnout': ('Tỷ lệ cử tri đi bầu', None),
    'c1-bustling': ('Nhộn nhịp', None),
    'c1-sleepy-town': ('Yên ắng (thị trấn)', None),
    'c1-vibrant': ('Sôi động', None),
    'c1-deserted': ('Vắng vẻ (hoang vắng)', None),
    'c1-packed': ('Chật kín (đông nghịt)', None),
    'c1-cramped': ('Chật chội', None),
    'c1-airy': ('Thoáng đãng', None),
    'c1-stuffy': ('Ngột ngạt', None),
    'c1-gloomy': ('Ảm đạm (u buồn)', None),
    'c1-dingy': ('Cũ kỹ tối tăm', None),
    'c1-shabby': ('Tồi tàn', None),
    'c1-chic': ('Sang trọng (thanh lịch)', None),
    'c1-trendy': ('Thời thượng', None),
    'c1-upscale': ('Cao cấp', None),
    'c1-seedy': ('Xập xệ (tồi tàn đáng ngờ)', None),
    'c1-leafy': ('Rợp bóng cây', None),
    'c1-sprawling': ('Trải rộng (lan tỏa)', None),
    'c1-walkable': ('Thuận tiện đi bộ', None),
    'c1-secluded': ('Biệt lập', None),
    'c1-remote-place': ('Hẻo lánh', None),
    'c1-touristy': ('Đậm chất du lịch (quá tải khách du lịch)', None),
    'c1-unspoiled': ('Nguyên vẹn (chưa bị tác động)', None),
    'c1-well-kept': ('Được chăm sóc kỹ lưỡng', None),
    'c1-overgrown': ('Um tùm cây cỏ', None),
    'c1-tucked-away': ('Nằm khuất nẻo', None),
    'c1-nestled': ('Nép mình', None),
    'c1-lively': ('Tràn đầy sức sống', None),
    'c1-run-down-place': ('Xuống cấp (đổ nát)', None),
}
