# -*- coding: utf-8 -*-
LANG = 'ko'
WORDS = {
    'c2-to-abate': ("누그러지다", "nugeureojida"),
    'c2-to-abhor': ("혐오하다", "hyeomohada"),
    'c2-to-abstain': ("기권하다", "gigwonhada"),
    'c2-to-accentuate': ("강조하다", "gangjohada"),
    'c2-to-acquiesce': ("묵인하다", "muginhada"),
    'c2-to-admonish': ("훈계하다", "hungyehada"),
    'c2-to-alleviate': ("완화하다", "wanhwahada"),
    'c2-to-amass': ("축적하다", "chukjeokhada"),
    'c2-to-appease': ("무마하다", "mumahada"),
    'c2-to-ascribe': ("귀속시키다", "gwisoksikida"),
    'c2-to-augment': ("증대시키다", "jeungdaesikida"),
    'c2-to-avert': ("모면하다", "momyeonhada"),
    'c2-to-beckon': ("손짓하다", "sonjitada"),
    'c2-to-belittle': ("폄하하다", "pyeomhahada"),
    'c2-to-bequeath': ("유증하다", "yujeunghada"),
    'c2-to-beseech': ("애원하다", "aewonhada"),
    'c2-to-bewilder': ("당혹시키다", "danghoksikida"),
    'c2-to-brandish': ("휘두르다", "hwidureuda"),
    'c2-to-castigate': ("질책하다", "jilchaekhada"),
    'c2-to-coalesce': ("융합하다", "yunghaphada"),
    'c2-to-commend': ("상찬하다", "sangchanhada"),
    'c2-to-concede': ("양보하다", "yangbohada"),
    'c2-to-concoct': ("날조하다", "najohada"),
    'c2-to-confer': ("수여하다", "suyeohada"),
    'c2-to-contend': ("역설하다", "yeoseolhada"),
    'c2-to-corroborate': ("입증하다", "ipjeunghada"),
    'c2-to-aggravate': ("악화시키다", "akhwasikida"),
    'c2-to-assail': ("습격하다", "seupgyeokhada"),
    'c2-to-chastise': ("징계하다", "jinggyehada"),
    'c2-to-condescend': ("거들먹거리다", "geodeulgeogeorida"),
    'c2-to-debunk': ("논파하다", "nonpahada"),
    'c2-to-decipher': ("해독하다", "haedokhada"),
    'c2-to-decry': ("규탄하다", "gyutanhada"),
    'c2-to-deem': ("간주하다", "ganjuhada"),
    'c2-to-defer': ("연기하다", "yeongihada"),
    'c2-to-delineate': ("묘사하다", "myosahada"),
    'c2-to-denounce': ("고발하다", "gobalhada"),
    'c2-to-deplete': ("고갈시키다", "gogalsikida"),
    'c2-to-deride': ("조롱하다", "jorong-hada"),
    'c2-to-despair': ("절망하다", "jeolmanghada"),
    'c2-to-detain': ("구금하다", "gugeumhada"),
    'c2-to-deviate': ("일탈하다", "iltalhada"),
    'c2-to-disdain': ("경시하다", "gyeongsihada"),
    'c2-to-disperse': ("해산시키다", "haesansikida"),
    'c2-to-dissuade': ("만류하다", "mallyuhada"),
    'c2-to-divulge': ("누설하다", "nuseolhada"),
    'c2-to-dwindle': ("위축되다", "wichukdoeda"),
    'c2-to-elude': ("따돌리다", "ttadollida"),
    'c2-to-emanate': ("발산하다", "balsanhada"),
    'c2-to-embellish': ("윤색하다", "yunsaekhada"),
    'c2-to-encompass': ("포괄하다", "pogwalhada"),
    'c2-to-engender': ("야기하다", "yagihada"),
    'c2-to-enlighten': ("계몽하다", "gyemonghada"),
    'c2-to-enthrall': ("매료시키다", "maeryosikida"),
    'c2-to-entice': ("유인하다", "yuinhada"),
    'c2-to-envision': ("구상하다", "gusanghada"),
    'c2-to-evade': ("회피하다", "hoepihada"),
    'c2-to-exalt': ("찬양하다", "chanyanghada"),
    'c2-to-expedite': ("촉진하다", "chokjinhada"),
    'c2-to-extol': ("극찬하다", "geukchanhada"),
    'c2-to-fabricate': ("조작하다", "jojakhada"),
    'c2-to-falter': ("주춤하다", "juchumhada"),
    'c2-to-feign': ("가장하다", "gajanghada"),
    'c2-to-flourish': ("번성하다", "beonseonghada"),
    'c2-to-forfeit': ("상실하다", "sangsilhada"),
    'c2-to-forgo': ("단념하다", "dannyeomhada"),
    'c2-to-galvanize': ("고무하다", "gomuhada"),
    'c2-to-garner': ("획득하다", "hoekdeukhada"),
    'c2-to-gloat': ("고소해하다", "gosohaehada"),
    'c2-to-grapple': ("씨름하다", "ssireumhada"),
    'c2-to-harness': ("활용하다", "hwaryonghada"),
    'c2-to-heed': ("귀담아듣다", "gwidameotteutda"),
    'c2-to-hoard': ("사재기하다", "sajaegihada"),
    'c2-to-impart': ("전수하다", "jeonsuhada"),
    'c2-to-implore': ("간청하다", "gancheonghada"),
    'c2-to-incite': ("선동하다", "seondonghada"),
    'c2-to-inhibit': ("억제하다", "eokjehada"),
    'c2-to-instill': ("주입하다", "juipada"),
    'c2-to-intercede': ("중재하다", "jungjaehada"),
    'c2-to-intimidate': ("위협하다", "wihyeophada"),
    'c2-to-jeopardize': ("위태롭게 하다", "witaeropge hada"),
    'c2-to-languish': ("시들다", "sideulda"),
    'c2-to-lure': ("유혹하다", "yuhokhada"),
    'c2-to-marvel': ("경탄하다", "gyeongtanhada"),
    'c2-to-meander': ("굽이치다", "gubichida"),
    'c2-to-muster': ("끌어모으다", "kkeureomoeuda"),
    'c2-to-obliterate': ("말살하다", "malsalhada"),
    'c2-to-oscillate': ("진동하다", "jindonghada"),
    'c2-to-ostracize': ("배척하다", "baecheokhada"),
    'c2-to-perpetuate': ("영속시키다", "yeongsoksikida"),
    'c2-to-permeate': ("스며들다", "seumyeodeulda"),
    'c2-to-plummet': ("급락하다", "geumnakhada"),
    'c2-to-ponder': ("숙고하다", "sukgohada"),
    'c2-to-preach': ("설교하다", "seolgyohada"),
    'c2-to-procure': ("조달하다", "jodalhada"),
    'c2-to-proliferate': ("급증하다", "geupjeunghada"),
    'c2-to-propel': ("추진하다", "chujinhada"),
    'c2-to-quell': ("진압하다", "jinapada"),
    'c2-to-ratify': ("비준하다", "bijunhada"),
    'c2-to-rebuke': ("나무라다", "namurada"),
    'c2-to-rebut': ("반박하다", "banbakhada"),
    'c2-to-recant': ("번복하다", "beonbokhada"),
    'c2-to-redeem': ("상환하다", "sanghwanhada"),
    'c2-to-refute': ("논박하다", "nonbakhada"),
    'c2-to-relish': ("만끽하다", "mankkitada"),
    'c2-to-renounce': ("포기하다", "pogihada"),
    'c2-to-replenish': ("보충하다", "bochunghada"),
    'c2-to-reprimand': ("견책하다", "gyeonchaekhada"),
    'c2-to-repudiate': ("부인하다", "buinhada"),
    'c2-to-resonate': ("공명하다", "gongmyeonghada"),
    'c2-to-retaliate': ("보복하다", "bobokhada"),
    'c2-to-revere': ("경외하다", "gyeongoehada"),
    'c2-to-revoke': ("철회하다", "cheolhoehada"),
    'c2-to-saturate': ("포화시키다", "pohwasikida"),
    'c2-to-scorn': ("경멸하다", "gyeongmyeolhada"),
    'c2-to-squander': ("낭비하다", "nangbihada"),
    'c2-to-stagnate': ("정체되다", "jeongchedoeda"),
    'c2-to-stifle': ("억누르다", "eongnureuda"),
    'c2-to-subside': ("가라앉다", "garaantda"),
    'c2-to-succumb': ("굴복하다", "gulbokhada"),
    'c2-to-supplant': ("대체하다", "daechehada"),
    'c2-to-surmise': ("추측하다", "chucheukhada"),
    'c2-to-swindle': ("사취하다", "sachwihada"),
    'c2-to-tarnish': ("실추시키다", "silchusikida"),
    'c2-to-thwart': ("좌절시키다", "jwajeolsikida"),
    'c2-to-transcend': ("초월하다", "chowolhada"),
    'c2-to-unravel': ("밝혀내다", "balkyeonaeda"),
    'c2-to-usurp': ("찬탈하다", "chantalhada"),
    'c2-to-vanquish': ("무찌르다", "mujjireuda"),
    'c2-to-venerate': ("숭배하다", "sungbaehada"),
    'c2-to-vilify': ("비방하다", "bibanghada"),
    'c2-to-wane': ("쇠퇴하다", "soetoehada"),
    'c2-to-wield': ("행사하다", "haengsahada"),
    'c2-to-writhe': ("몸부림치다", "mombeurimchida"),
    'c2-to-yearn': ("갈망하다", "galmanghada"),
    'c2-to-beget': ("낳다", "nata"),
    'c2-to-besiege': ("포위하다", "powihada"),
    'c2-to-cajole': ("구슬리다", "guseullida"),
    'c2-to-coax': ("구워삶다", "guwosalmda"),
    'c2-to-deplore': ("개탄하다", "gaetanhada"),
    'c2-to-disparage': ("폄훼하다", "pyeonhwehada"),
    'c2-to-exhort': ("촉구하다", "chokguhada"),
    'c2-to-foment': ("조장하다", "jojanghada"),
    'c2-to-indulge': ("탐닉하다", "tamnikhada"),
    'c2-to-placate': ("달래다", "dallaeda"),
    'c2-to-preempt': ("선점하다", "seonjeomhada"),
    'c2-to-rescind': ("파기하다", "pagihada"),
    'c2-to-stymie': ("저지하다", "jeojihada"),
    'c2-to-vindicate': ("누명을 벗기다", "nummyeongeul beotgida"),
    'c2-to-evince': ("표출하다", "pyochulhada"),
    'c2-affable': ("상냥하다", "sangnyanghada"),
    'c2-churlish': ("퉁명스럽다", "tungmyeongseureopda"),
    'c2-astute': ("영민하다", "yeongminhada"),
    'c2-audacious': ("대담하다", "daedamhada"),
    'c2-belligerent': ("호전적이다", "hojeonjeogida"),
    'c2-sanguine': ("낙관적이다", "nakgwanjeogida"),
    'c2-brusque': ("무뚝뚝하다", "mudduktukhada"),
    'c2-callous': ("냉담하다", "naengdamhada"),
    'c2-truculent': ("공격적이다", "gonggyeokjeogida"),
    'c2-capricious': ("변덕스럽다", "byeondeokseureopda"),
    'c2-complacent': ("안일하다", "anilhada"),
    'c2-unflappable': ("태연자약하다", "taeyeonjayakhada"),
    'c2-cunning': ("교활하다", "gyohwalhada"),
    'c2-diffident': ("소심하다", "sosimhada"),
    'c2-officious': ("오지랖이 넓다", "ojirapi neolda"),
    'c2-docile': ("유순하다", "yusunhada"),
    'c2-erudite': ("박식하다", "baksikhada"),
    'c2-fastidious': ("까다롭다", "kkadaropda"),
    'c2-flippant': ("경박하다", "gyeongbakhada"),
    'c2-garrulous': ("수다스럽다", "sudaseureopda"),
    'c2-gregarious': ("사교적이다", "sagyojeogida"),
    'c2-haughty': ("오만하다", "omanhada"),
    'c2-impetuous': ("충동적이다", "chungdongjeogida"),
    'c2-indolent': ("나태하다", "nataehada"),
    'c2-mercurial': ("변화무쌍하다", "byeonhwamussanghada"),
    'c2-phlegmatic': ("무덤덤하다", "mudeomdeomhada"),
    'c2-obsequious': ("비굴하다", "bigulhada"),
    'c2-petulant': ("심술궂다", "simsulgutda"),
    'c2-sanctimonious': ("위선적이다", "wiseonjeogida"),
    'c2-taciturn': ("과묵하다", "gwamukhada"),
    'c2-bountiful': ("넉넉하다", "neongneokhada"),
    'c2-arduous': ("고되다", "godoeda"),
    'c2-banal': ("진부하다", "jinbuhada"),
    'c2-copious': ("풍부하다", "pungbuhada"),
    'c2-cumbersome': ("번거롭다", "beongeoropda"),
    'c2-deft': ("능란하다", "neungnanhada"),
    'c2-dire': ("처참하다", "cheochamhada"),
    'c2-ephemeral': ("덧없다", "deoseopda"),
    'c2-peerless': ("독보적이다", "dokbojeogida"),
    'c2-feeble': ("허약하다", "heoyakhada"),
    'c2-rickety': ("허술하다", "heosulhada"),
    'c2-formidable': ("만만찮다", "manmanchanta"),
    'c2-immaculate': ("결백하다", "gyeolbaekhada"),
    'c2-faultless': ("흠잡을 데 없다", "heumjabeul de eopda"),
    'c2-innocuous': ("무해하다", "muhaehada"),
    'c2-insidious': ("음흉하다", "eumhyunghada"),
    'c2-labyrinthine': ("복잡다단하다", "bokjapdadanhada"),
    'c2-profligate': ("방탕하다", "bangtanghada"),
    'c2-perspicuous': ("명료하다", "myeongnyohada"),
    'c2-sparse': ("희소하다", "huisohada"),
    'c2-infinitesimal': ("극미하다", "geungmihada"),
    'c2-sumptuous': ("호화롭다", "howaropda"),
    'c2-paltry': ("하찮다", "hachanta"),
    'c2-unblemished': ("무결하다", "mugyeolhada"),
    'c2-indomitable': ("굴하지 않다", "gulhaji anta"),
    'c2-scant': ("빈약하다", "binyakhada"),
    'c2-transcendent': ("초월적이다", "chowoljeogida"),
    'c2-tenuous': ("미약하다", "miyakhada"),
    'c2-unwieldy': ("다루기 힘들다", "daurugi himdeulda"),
    'c2-boundless': ("무한하다", "muhanhada"),
    'c2-abstruse': ("난해하다", "nanhaehada"),
    'c2-apt': ("적절하다", "jeokjeolhada"),
    'c2-cogent': ("논리정연하다", "nollijeongyeonhada"),
    'c2-contentious': ("논쟁적이다", "nonjaengjeogida"),
    'c2-deplorable': ("개탄스럽다", "gaetanseureopda"),
    'c2-dubious': ("미심쩍다", "misimjjeokda"),
    'c2-egregious': ("터무니없다", "teomunieopda"),
    'c2-exemplary': ("모범적이다", "mobeomjeogida"),
    'c2-fallacious': ("그릇되다", "geureutdoeda"),
    'c2-futile': ("헛되다", "heotdoeda"),
    'c2-gratuitous': ("부당하다", "budanghada"),
    'c2-illicit': ("불법적이다", "bulbeopjeogida"),
    'c2-impartial': ("공정하다", "gongjeonghada"),
    'c2-incongruous': ("부조화스럽다", "bujohwaseureopda"),
    'c2-ineffable': ("형언할 수 없다", "hyeongeonhal su eopda"),
    'c2-irrefutable': ("반박할 수 없다", "banbakhal su eopda"),
    'c2-laudable': ("가상하다", "gasanghada"),
    'c2-moot': ("논쟁의 여지가 있다", "nonjaengui yeojiga itda"),
    'c2-nebulous': ("애매모호하다", "aemaemohohada"),
    'c2-ostensible': ("표면적이다", "pyomyeonjeokida"),
    'c2-pernicious': ("유해하다", "yuhaehada"),
    'c2-plausible': ("그럴듯하다", "geureolteutada"),
    'c2-preposterous': ("어처구니없다", "eocheogunieopda"),
    'c2-salient': ("두드러지다", "dudeureojida"),
    'c2-spurious': ("위조되다", "wijodoeda"),
    'c2-superfluous': ("불필요하다", "bulpiryohada"),
    'c2-tenable': ("옹호할 수 있다", "onghohal su itda"),
    'c2-untenable': ("옹호할 수 없다", "onghohal su eopda"),
    'c2-viable': ("실행 가능하다", "silhaeng ganeunghada"),
    'c2-wanton': ("방자하다", "bangjahada"),
    'c2-ailing': ("병약하다", "byeongyakhada"),
    'c2-bewildered': ("어리둥절하다", "eoridungjeolhada"),
    'c2-desolate': ("황량하다", "hwangnyanghada"),
    'c2-brittle': ("부서지기 쉽다", "buseojigi swipda"),
    'c2-cohesive': ("응집력 있다", "eungjipnyeok itda"),
    'c2-defunct': ("사멸하다", "samyeolhada"),
    'c2-derelict': ("방치되다", "bangchidoeda"),
    'c2-ramshackle': ("다 쓰러져 가다", "da sseureojyeo gada"),
    'c2-dormant': ("휴면 상태다", "hyumyeon sangtaeda"),
    'c2-drowsy': ("졸리다", "jollida"),
    'c2-dwindling': ("쇠퇴해 가다", "soetoehae gada"),
    'c2-exhilarated': ("도취되다", "dochwidoeda"),
    'c2-forlorn': ("처량하다", "cheoryanghada"),
    'c2-haggard': ("초췌하다", "chochwehada"),
    'c2-imminent': ("임박하다", "imbakhada"),
    'c2-incessant': ("끊임없다", "kkeunimeopda"),
    'c2-inert': ("비활성적이다", "bihwalseongjeogida"),
    'c2-jaded': ("권태롭다", "gwontaeropda"),
    'c2-languid': ("나른하다", "nareunhada"),
    'c2-listless': ("무기력하다", "mugiryeokhada"),
    'c2-antiquated': ("구식이다", "gusikida"),
    'c2-precarious': ("불안정하다", "buranjeonghada"),
    'c2-rampant': ("만연하다", "manyeonhada"),
    'c2-fidgety': ("안절부절못하다", "anjeolbujeolmotada"),
    'c2-rife': ("무성하다", "museonghada"),
    'c2-sodden': ("흠뻑 젖다", "heumppeok jeotda"),
    'c2-stagnant': ("정체되다", "jeongchedoeda"),
    'c2-susceptible': ("취약하다", "chwiyakhada"),
    'c2-volatile': ("휘발성이다", "hwibalseongida"),
    'c2-weary': ("지치다", "jichida"),
    'c2-bombastic': ("허풍스럽다", "heopungseureopda"),
    'c2-vernacular': ("토속적이다", "tosokjeogida"),
    'c2-concise': ("간결하다", "gangyeolhada"),
    'c2-tortuous': ("꼬불꼬불하다", "kkobulkkobulhada"),
    'c2-cryptic': ("알쏭달쏭하다", "alssongdalssonghada"),
    'c2-derogatory': ("모욕적이다", "moyokjeogida"),
    'c2-didactic': ("교훈적이다", "gyohunjeogida"),
    'c2-silver-tongued': ("달변이다", "dalbyeonida"),
    'c2-emphatic': ("단호하다", "danhohada"),
    'c2-euphemistic': ("완곡하다", "wangokhada"),
    'c2-facetious': ("익살스럽다", "iksalseureopda"),
    'c2-florid': ("현란하다", "hyeollanhada"),
    'c2-glib': ("번드르르하다", "beondeureureuhada"),
    'c2-hyperbolic': ("과장되다", "gwajangdoeda"),
    'c2-incisive': ("예리하다", "yerihada"),
    'c2-laconic': ("간명하다", "ganmyeonghada"),
    'c2-long-winded': ("장황하다", "janghwanghada"),
    'c2-mordant': ("신랄하다", "sillalhada"),
    'c2-ornate': ("화려하다", "hwaryeohada"),
    'c2-pedantic': ("현학적이다", "hyeonhakjeogida"),
    'c2-pithy': ("촌철살인이다", "choncheolsarinida"),
    'c2-plaintive': ("애처롭다", "aecheoropda"),
    'c2-rhetorical': ("수사적이다", "susajeogida"),
    'c2-sardonic': ("냉소적이다", "naengsojeogida"),
    'c2-scathing': ("통렬하다", "tongnyeolhada"),
    'c2-succinct': ("요약적이다", "yoyakjeogida"),
    'c2-terse': ("쌀쌀맞다", "ssalssalmatda"),
    'c2-trite': ("케케묵다", "kekemukda"),
    'c2-verbose': ("군더더기가 많다", "gundeodeogiga manta"),
    'c2-wry': ("반어적이다", "baneojeogida"),
    'c2-acumen': ("통찰력", "tongchalnyeok"),
    'c2-alacrity': ("민첩함", "mincheopham"),
    'c2-ambivalence': ("양가감정", "yanggagamjeong"),
    'c2-apathy': ("무관심", "mugwansim"),
    'c2-aplomb': ("침착함", "chimchakham"),
    'c2-audacity': ("대담함", "daedamham"),
    'c2-candor': ("솔직함", "soljikham"),
    'c2-smugness': ("자기만족", "jagimanjok"),
    'c2-scorn': ("경멸", "gyeongmyeol"),
    'c2-deference': ("경의", "gyeongui"),
    'c2-discretion': ("신중함", "sinjungham"),
    'c2-disdain': ("멸시", "myeolsi"),
    'c2-forbearance': ("관용", "gwanyong"),
    'c2-fortitude': ("기개", "gigae"),
    'c2-hubris': ("오만", "oman"),
    'c2-meekness': ("온순함", "onsunham"),
    'c2-umbrage': ("불쾌감", "bulkwaegam"),
    'c2-ingenuity': ("독창성", "dokchangseong"),
    'c2-rectitude': ("강직함", "gangjikham"),
    'c2-malice': ("악의", "agui"),
    'c2-nostalgia': ("향수", "hyangsu"),
    'c2-perseverance': ("인내", "innae"),
    'c2-prudence': ("사려분별", "saryeobunbyeol"),
    'c2-grit': ("근성", "geunseong"),
    'c2-reticence': ("과묵함", "gwamukham"),
    'c2-equanimity': ("평정심", "pyeongjeongsim"),
    'c2-tenacity': ("끈기", "kkeungi"),
    'c2-vanity': ("허영심", "heoyeongsim"),
    'c2-vigilance': ("경계심", "gyeonggyesim"),
    'c2-zeal': ("열의", "yeorui"),
    'c2-anomaly': ("변칙", "byeonchik"),
    'c2-catalyst': ("촉매", "chokmae"),
    'c2-conundrum': ("난제", "nanje"),
    'c2-debacle': ("참패", "champae"),
    'c2-deluge': ("쇄도", "swaedo"),
    'c2-dearth': ("결핍", "gyeolpip"),
    'c2-dichotomy': ("이분법", "ibunbeop"),
    'c2-epitome': ("전형", "jeonhyeong"),
    'c2-exodus': ("대탈출", "daetalchul"),
    'c2-facade': ("허울", "heoul"),
    'c2-fallacy': ("궤변", "gwebyeon"),
    'c2-hindsight': ("후견지명", "hugyeonjimyeong"),
    'c2-impasse': ("교착 상태", "gyochak sangtae"),
    'c2-impetus': ("추진력", "chujinnyeok"),
    'c2-juncture': ("국면", "gungmyeon"),
    'c2-loophole': ("허점", "heojeom"),
    'c2-tipping-point': ("임계점", "imgyejeom"),
    'c2-onslaught': ("맹공격", "maenggonggyeok"),
    'c2-vicious-circle': ("악순환", "aksunhwan"),
    'c2-plight': ("곤경", "gongyeong"),
    'c2-precedent': ("선례", "seollye"),
    'c2-quandary': ("진퇴양난", "jintwaeyangnan"),
    'c2-ramification': ("여파", "yeopa"),
    'c2-respite': ("유예", "yuye"),
    'c2-setback': ("차질", "chajil"),
    'c2-stalemate': ("답보 상태", "dapbo sangtae"),
    'c2-surge': ("급증", "geupjeung"),
    'c2-turmoil': ("혼란", "hollan"),
    'c2-upheaval': ("격변", "gyeokbyeon"),
    'c2-watershed': ("전환점", "jeonhwanjeom"),
    'c2-accomplice': ("공범", "gongbeom"),
    'c2-adversary': ("적수", "jeoksu"),
    'c2-advocate': ("옹호자", "onghoja"),
    'c2-benefactor': ("은인", "eunin"),
    'c2-bystander': ("방관자", "banggwanja"),
    'c2-charlatan': ("협잡꾼", "hyeopjapkkun"),
    'c2-connoisseur': ("감식가", "gamsikga"),
    'c2-culprit': ("범인", "beomin"),
    'c2-demagogue': ("선동가", "seondongga"),
    'c2-dilettante': ("호사가", "hosaga"),
    'c2-envoy': ("사절", "sajeol"),
    'c2-lackey': ("하수인", "hasuin"),
    'c2-understudy': ("대역", "daeyeok"),
    'c2-hypocrite': ("위선자", "wiseonja"),
    'c2-insurgent': ("반군", "bangun"),
    'c2-layperson': ("문외한", "munoehan"),
    'c2-maverick': ("이단아", "idana"),
    'c2-sidekick': ("오른팔", "oreunpal"),
    'c2-mercenary': ("용병", "yongbyeong"),
    'c2-novice': ("초보자", "choboja"),
    'c2-pariah': ("추방자", "chubangja"),
    'c2-patron': ("후원자", "huwonja"),
    'c2-perpetrator': ("가해자", "gahaeja"),
    'c2-prodigy': ("신동", "sindong"),
    'c2-informant': ("밀고자", "milgoja"),
    'c2-recluse': ("은둔자", "eundunja"),
    'c2-sage': ("현자", "hyeonja"),
    'c2-turncoat': ("변절자", "byeonjeolja"),
    'c2-stalwart': ("충신", "chungsin"),
    'c2-tycoon': ("거물", "geomul"),
    'c2-ambiguity': ("모호함", "mohoham"),
    'c2-analogy': ("유추", "yuchu"),
    'c2-axiom': ("공리", "gongni"),
    'c2-caveat': ("단서", "danseo"),
    'c2-consensus': ("합의", "habui"),
    'c2-corollary': ("귀결", "gwigyeol"),
    'c2-yardstick': ("잣대", "jatdae"),
    'c2-narrative': ("서사", "seosa"),
    'c2-doctrine': ("교리", "gyori"),
    'c2-dogma': ("독단", "dokdan"),
    'c2-epiphany': ("깨달음", "kkaedareum"),
    'c2-ethos': ("기풍", "gipung"),
    'c2-conjecture': ("추측", "chucheuk"),
    'c2-idiosyncrasy': ("기벽", "gibyeok"),
    'c2-deduction': ("추론", "churon"),
    'c2-innuendo': ("암시", "amsi"),
    'c2-buzzword': ("유행어", "yuhaengeo"),
    'c2-simile': ("직유", "jigyu"),
    'c2-nuance': ("뉘앙스", "nwiangseu"),
    'c2-archetype': ("원형", "wonhyeong"),
    'c2-platitude': ("상투어", "sangtueo"),
    'c2-postulate': ("전제", "jeonje"),
    'c2-pretext': ("구실", "gusil"),
    'c2-rebuttal': ("반박", "banbak"),
    'c2-rhetoric': ("수사법", "susabeop"),
    'c2-semantics': ("의미론", "uimiron"),
    'c2-stigma': ("낙인", "nagin"),
    'c2-tenet': ("신조", "sinjo"),
    'c2-trope': ("관용적 표현", "gwanyongjeok pyohyeon"),
    'c2-zeitgeist': ("시대정신", "sidaejeongsin"),
    'c2-acrid': ("매캐하다", "maekaehada"),
    'c2-astringent': ("떫다", "tteolda"),
    'c2-bland-flavorless': ("밍밍하다", "mingminghada"),
    'c2-brackish': ("소금기가 있다", "sogeumgiga itda"),
    'c2-cloying': ("느끼하다", "neukkihada"),
    'c2-coarse': ("거칠다", "geochilda"),
    'c2-creamy': ("고소하다", "gosohada"),
    'c2-crunchy': ("바삭하다", "basakhada"),
    'c2-dank': ("눅눅하다", "nungnukhada"),
    'c2-earthy': ("구수하다", "gusuhada"),
    'c2-fragrant': ("향긋하다", "hyanggeutada"),
    'c2-gooey': ("끈적끈적하다", "kkeunjeokkkeunjeokhada"),
    'c2-grainy': ("까끌까끌하다", "kkakkeulkkakkeulhada"),
    'c2-unctuous': ("기름지다", "gireumjida"),
    'c2-gravelly-voice': ("걸걸하다", "geolgeolhada"),
    'c2-luscious': ("감미롭다", "gammiropda"),
    'c2-mellow': ("은은하다", "eun-eunhada"),
    'c2-hushed': ("나직하다", "najikhada"),
    'c2-musty': ("곰팡내가 나다", "gompangnaega nada"),
    'c2-piercing': ("날카롭다", "nalkaropda"),
    'c2-pungent': ("매콤하다", "maekomhada"),
    'c2-putrid': ("썩은 내가 나다", "sseogeun naega nada"),
    'c2-rancid': ("산패하다", "sanpaehada"),
    'c2-bitter-aftertaste': ("뒷맛이 쓰다", "dwinmasi sseuda"),
    'c2-grating-sound': ("귀에 거슬리다", "gwie geoseullida"),
    'c2-silky': ("매끄럽다", "maekkeureopda"),
    'c2-slimy': ("미끈거리다", "mikkeungeorida"),
    'c2-soggy': ("축축하다", "chukchukhada"),
    'c2-tangy': ("새콤하다", "saekomhada"),
    'c2-zesty': ("상큼하다", "sangkeumhada"),
    'c2-better-late-than-never': ("늦더라도 안 하는 것보다 낫다", "neutdeorado an haneun geotboda natda"),
    'c2-actions-speak-louder-than-words': ("말보다 행동이 중요하다", "malboda haengdongi jungyohada"),
    'c2-the-early-bird-catches-the-worm': ("일찍 일어나는 새가 벌레를 잡는다", "iljjik ireonaneun saega beollereul jamneunda"),
    "c2-don-t-count-your-chickens-before-they-hatch": ("김칫국부터 마시지 마라", "gimchitgukbuteo masiji mara"),
    'c2-every-cloud-has-a-silver-lining': ("비 온 뒤에 땅이 굳어진다", "bi on dwie ttangi gudeojinda"),
    'c2-practice-makes-perfect': ("연습이 완벽을 만든다", "yeonseubi wanbyeogeul mandeunda"),
    'c2-when-in-rome-do-as-the-romans-do': ("로마에 가면 로마법을 따르라", "romae gamyeon romabeobeul ttareura"),
    'c2-two-heads-are-better-than-one': ("백지장도 맞들면 낫다", "baekjijangdo matdeulmyeon natda"),
    'c2-the-grass-is-always-greener-on-the-other-side': ("남의 떡이 더 커 보인다", "namui tteogi deo keo boinda"),
    "c2-don-t-judge-a-book-by-its-cover": ("겉모습만 보고 판단하지 마라", "geotmoseupman bogo pandanhaji mara"),
    'c2-birds-of-a-feather-flock-together': ("유유상종", "yuyusangjong"),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ("손 안의 새 한 마리가 숲 속의 두 마리보다 낫다", "son anui sae han mariga sup soguui du mariboda natda"),
    "c2-where-there-s-a-will-there-s-a-way": ("뜻이 있는 곳에 길이 있다", "tteusi inneun gose giri itda"),
    "c2-rome-wasn-t-built-in-a-day": ("로마는 하루아침에 이루어지지 않았다", "romaneun haruachime irueojiji anatda"),
    'c2-too-many-cooks-spoil-the-broth': ("사공이 많으면 배가 산으로 간다", "sagongi manheumyeon baega saneuro ganda"),
    'c2-out-of-sight-out-of-mind': ("눈에서 멀어지면 마음에서도 멀어진다", "nuneseo meoreojimyeon maeumeseodo meoreojinda"),
    'c2-look-before-you-leap': ("돌다리도 두들겨 보고 건너라", "doldarido dudeulgyeo bogo geonneora"),
    'c2-necessity-is-the-mother-of-invention': ("필요는 발명의 어머니다", "piryoneun balmyeongui eomeonida"),
    "c2-you-can-t-have-your-cake-and-eat-it-too": ("두 마리 토끼를 다 잡을 수는 없다", "du mari tokkireul da jabeul suneun eopda"),
    'c2-honesty-is-the-best-policy': ("정직이 최선의 방책이다", "jeongjigi choeseonui bangchaegida"),
    'c2-still-waters-run-deep': ("고요한 물이 깊다", "goyohan muri gipda"),
    'c2-blood-is-thicker-than-water': ("피는 물보다 진하다", "pineun mulboda jinhada"),
    'c2-absence-makes-the-heart-grow-fonder': ("없으면 더 그리워진다", "eopseumyeon deo geuriwojinda"),
    'c2-every-dog-has-its-day': ("쥐구멍에도 볕 들 날 있다", "jwigumeongedo byeot deul nal itda"),
    'c2-haste-makes-waste': ("급할수록 돌아가라", "geuphalsurok doragara"),
    'c2-let-sleeping-dogs-lie': ("긁어 부스럼 만들지 마라", "geulgeo buseureom mandeulji mara"),
    'c2-strike-while-the-iron-is-hot': ("쇠뿔도 단김에 빼라", "soeppuldo dangime ppaera"),
    'c2-the-pen-is-mightier-than-the-sword': ("펜은 칼보다 강하다", "peneun kalboda ganghada"),
    'c2-curiosity-killed-the-cat': ("호기심이 고양이를 죽인다", "hogisimi goyangireul juginda"),
    "c2-beggars-can-t-be-choosers": ("찬밥 더운밥 가릴 처지가 아니다", "chanbap deounbap garil cheojiga anida"),
    'c2-to-draw-a-distinction': ("구별하다", "gubyeolhada"),
    'c2-to-reach-a-verdict': ("평결을 내리다", "pyeonggyeoreul naerida"),
    'c2-to-pose-a-threat': ("위협이 되다", "wihyeobi doeda"),
    'c2-to-bear-the-brunt': ("직격탄을 맞다", "jikgyeoktaneul matda"),
    'c2-to-lend-credence-to': ("신빙성을 더하다", "sinbingseongeul deohada"),
    'c2-to-wield-influence': ("영향력을 행사하다", "yeonghyangnyeogeul haengsahada"),
    'c2-to-incur-a-cost': ("비용을 발생시키다", "biyongeul balsaengsikida"),
    'c2-to-uphold-a-principle': ("원칙을 고수하다", "wonchigeul gosuhada"),
    'c2-to-exert-pressure': ("압력을 행사하다", "amnyeogeul haengsahada"),
    'c2-to-fulfil-an-obligation': ("의무를 이행하다", "uimureul ihaenghada"),
    'c2-to-cast-doubt-on': ("의혹을 제기하다", "uihogeul jegihada"),
    'c2-to-pay-tribute-to': ("경의를 표하다", "gyeonguireul pyohada"),
    'c2-to-take-precedence-over': ("우선하다", "useonhada"),
    'c2-to-run-the-risk-of': ("위험을 무릅쓰다", "wiheomeul mureupsseuda"),
    'c2-to-strike-a-balance': ("균형을 이루다", "gyunhyeongeul iruda"),
    'c2-to-come-to-fruition': ("결실을 맺다", "gyeolsireul maetda"),
    'c2-to-shed-light-on': ("조명하다", "jomyeonghada"),
    'c2-to-set-a-precedent': ("선례를 남기다", "seollyereul namgida"),
    'c2-to-give-rise-to': ("초래하다", "choraehada"),
    'c2-to-take-issue-with': ("이의를 제기하다", "uiireul jegihada"),
    'c2-pursuant-to': ("~에 의거하여", "e uigeohayeo"),
    'c2-heretofore': ("지금까지", "jigeumkkaji"),
    'c2-inasmuch-as': ("~인 만큼", "in mankeum"),
    'c2-in-conjunction-with': ("~와 함께", "wa hamkke"),
    'c2-hitherto': ("이제까지", "ijekkaji"),
    'c2-forthwith': ("즉시", "jeuksi"),
    'c2-whilst': ("~하는 동안", "haneun dongan"),
    'c2-wherein': ("그 안에서", "geu aneseo"),
    'c2-vis-a-vis': ("~에 대하여", "e daehayeo"),
    'c2-as-regards': ("~에 관하여", "e gwanhayeo"),
    'c2-for-the-sake-of-argument': ("논의를 위해", "nonuireul wihae"),
    'c2-be-that-as-it-may': ("그렇다 하더라도", "geureota hadeorado"),
    'c2-on-balance': ("대체로", "daechero"),
    'c2-at-the-behest-of': ("~의 요청으로", "ui yocheongeuro"),
    'c2-in-the-wake-of': ("~의 여파로", "ui yeoparo"),
    'c2-on-the-grounds-that': ("~라는 이유로", "raneun iyuro"),
    'c2-in-accordance-with': ("~에 따라", "e ttara"),
    'c2-pending': ("보류되다", "boryudoeda"),
    'c2-irrespective-of': ("~와 상관없이", "wa sanggwaneopsi"),
    'c2-hereinafter': ("이하", "iha"),
    'c2-beats-me': ("나도 몰라", "nado molla"),
    'c2-point-taken': ("일리 있네요", "illi inneyo"),
    'c2-suit-yourself': ("마음대로 해", "maeumdaero hae"),
    'c2-go-figure': ("알다가도 모르겠다", "aldagado moreugetda"),
    "c2-don-t-get-me-started": ("말도 마", "maldo ma"),
    'c2-bottom-line-is': ("결론은", "gyeollon-eun"),
    'c2-off-the-top-of-my-head': ("얼핏 생각하기에", "eolpit saenggakagie"),
    "c2-i-ll-say": ("그러게 말이야", "geureoge mariya"),
    "c2-you-ve-got-to-be-kidding-me": ("장난하는 거지", "jangnanhaneun geoji"),
    'c2-no-offense-but': ("기분 나쁘게 듣지 말고", "gibun nappeuge deutji malgo"),
    "c2-i-m-not-gonna-lie": ("솔직히 말하면", "soljikhi malhamyeon"),
    'c2-speak-of-the-devil': ("호랑이도 제 말 하면 온다", "horangido je mal hamyeon onda"),
    "c2-it-s-on-the-tip-of-my-tongue": ("혀끝에서 맴돌다", "hyeokkeuteseo maemdolda"),
    "c2-let-s-call-it-a-day": ("오늘은 여기까지 하자", "oneureun yeogikkaji haja"),
    "c2-it-s-not-rocket-science": ("그렇게 어려운 일이 아니다", "geureoke eoryeoun iri anida"),
    "c2-that-s-the-last-straw": ("인내심이 바닥났다", "innaesimi badaknatda"),
    "c2-i-couldn-t-care-less": ("전혀 신경 안 써", "jeonhyeo singyeong an sseo"),
    'c2-what-are-the-odds': ("이런 우연이", "ireon uyeoni"),
    'c2-say-no-more': ("더 말 안 해도 알아", "deo mal an haedo ara"),
    'c2-hang-in-there': ("조금만 버텨", "jogeumman beotyeo"),
    "c2-i-m-all-ears": ("귀 기울이고 있어", "gwi giulligo isseo"),
    "c2-that-s-on-me": ("내 잘못이야", "nae jalmosiya"),
    'c2-no-hard-feelings': ("악감정은 없어", "akgamjeongeun eopseo"),
    'c2-ditto': ("나도 마찬가지야", "nado machangajiya"),
    'c2-spill-the-beans': ("다 털어놔", "da teoreonwa"),
    'c2-in-one-ear-and-out-the-other': ("한 귀로 듣고 한 귀로 흘리다", "han guiro deutgo han guiro heullida"),
    'c2-cut-to-the-chase': ("본론만 말해", "bollonman malhae"),
    'c2-you-name-it': ("뭐든지", "mwodeunji"),
    'c2-not-in-a-million-years': ("절대 그럴 리 없다", "jeoldae geureol ri eopda"),
    "c2-it-is-what-it-is": ("어쩔 수 없다", "eojjeol su eopda"),
    'c2-give-me-a-break': ("좀 봐줘", "jom bwajwo"),
    'c2-hold-your-horses': ("잠깐만 기다려", "jamkkanman gidaryeo"),
    'c2-bite-the-bullet': ("이를 악물다", "ireul angmulda"),
    'c2-take-it-with-a-grain-of-salt': ("곧이곧대로 믿지 마라", "gojigotdaero mitji mara"),
    'c2-better-safe-than-sorry': ("유비무환이다", "yubimuhwanida"),
    "c2-let-s-play-it-by-ear": ("상황 봐가면서 하자", "sanghwang bwagamyeonseo haja"),
    "c2-i-ll-take-a-rain-check": ("다음 기회로 미루자", "daeum gihoero miruja"),
    "c2-for-what-it-s-worth": ("참고로 말하자면", "chamgoro malhajamyeon"),
    'c2-back-to-square-one': ("원점으로 돌아가다", "wonjeomeuro doragada"),
    'c2-touch-wood': ("나무를 두드리다", "namureul dudeurida"),
    'c2-allusion': ("언급", "eongeup"),
    'c2-anecdote': ("일화", "ilhwa"),
    'c2-antithesis': ("대극", "daegeuk"),
    'c2-aphorism': ("경구", "gyeonggu"),
    'c2-banter': ("재담", "jaedam"),
    'c2-circumlocution': ("우회적 표현", "uhoejeok pyohyeon"),
    'c2-cliche': ("진부한 표현", "jinbuhan pyohyeon"),
    'c2-connotation': ("함의", "hamui"),
    'c2-digression': ("여담", "yeodam"),
    'c2-double-entendre': ("중의적 표현", "jung-uijeok pyohyeon"),
    'c2-eloquence': ("유창함", "yuchangham"),
    'c2-euphemism': ("완곡어법", "wangogeobeop"),
    'c2-gist': ("요지", "yoji"),
    'c2-hyperbole': ("과장법", "gwajangbeop"),
    'c2-irony': ("반어법", "baneobeop"),
    'c2-juxtaposition': ("병치", "byeongchi"),
    'c2-malapropism': ("말실수", "malsilsu"),
    'c2-oxymoron': ("모순어법", "mosuneobeop"),
    'c2-paraphrase': ("환언", "hwaneon"),
    'c2-pun': ("말장난", "maljangnan"),
    'c2-quip': ("촌평", "chonpyeong"),
    'c2-sarcasm': ("비꼼", "bikkom"),
    'c2-slur-insult': ("폭언", "pogeon"),
    'c2-repartee': ("응구첩대", "eunggucheopdae"),
    'c2-auditor': ("감사관", "gamsagwan"),
    'c2-bailiff': ("집행관", "jipaenggwan"),
    'c2-blacksmith': ("대장장이", "daejangjangi"),
    'c2-cartographer': ("지도 제작자", "jido jejakja"),
    'c2-chiropractor': ("척추 지압사", "cheokchu jiapsa"),
    'c2-coroner': ("검시관", "geomsigwan"),
    'c2-curator': ("큐레이터", "kyureiteo"),
    'c2-diplomat': ("외교관", "oegyogwan"),
    'c2-dietitian': ("영양사", "yeongyangsa"),
    'c2-entomologist': ("곤충학자", "gonchunghakja"),
    'c2-forensic-scientist': ("과학 수사관", "gwahak susagwan"),
    'c2-geologist': ("지질학자", "jijilhakja"),
    'c2-glazier': ("유리공", "yuriggong"),
    'c2-interpreter-simultaneous': ("동시통역사", "dongsitongyeoksa"),
    'c2-locksmith': ("열쇠공", "yeolsoegong"),
    'c2-midwife': ("조산사", "josansa"),
    'c2-court-clerk': ("법원 서기관", "beobwon seogigwan"),
    'c2-oncologist': ("종양학자", "jongyanghakja"),
    'c2-ophthalmologist': ("안과 의사", "angwa uisa"),
    'c2-paleontologist': ("고생물학자", "gosaengmulhakja"),
    'c2-paralegal': ("법률 사무 보조원", "beomnyul samu bojowon"),
    'c2-pathologist': ("병리학자", "byeongnihakja"),
    'c2-physiotherapist': ("물리치료사", "mullichiryosa"),
    'c2-public-defender': ("국선 변호인", "gukseon byeonhoin"),
    'c2-radiologist': ("방사선과 의사", "bangsaseongwa uisa"),
    'c2-perfumer': ("조향사", "johyangsa"),
    'c2-stenographer': ("속기사", "sokgisa"),
    'c2-surveyor': ("측량사", "cheungnyangsa"),
    'c2-taxidermist': ("박제사", "bakjesa"),
    'c2-upholsterer': ("가구 덮개공", "gagu deopgaegong"),
    'c2-veterinarian-specialist': ("수의사", "suuisa"),
    'c2-welder': ("용접공", "yongjeopgong"),
    'c2-anthropology': ("인류학", "illyuhak"),
    'c2-archaeology': ("고고학", "gogohak"),
    'c2-astrophysics': ("천체물리학", "cheonchemullihak"),
    'c2-biochemistry': ("생화학", "saenghwahak"),
    'c2-botany': ("식물학", "singmulhak"),
    'c2-cartography': ("지도학", "jidohak"),
    'c2-criminology': ("범죄학", "beomjoehak"),
    'c2-demography': ("인구통계학", "ingutonggyehak"),
    'c2-econometrics': ("계량경제학", "gyeryanggyeongjehak"),
    'c2-epidemiology': ("역학", "yeokhak"),
    'c2-epistemology': ("인식론", "insingnon"),
    'c2-ethnography': ("민족지학", "minjokjihak"),
    'c2-genetics': ("유전학", "yujeonhak"),
    'c2-geopolitics': ("지정학", "jijeonghak"),
    'c2-hermeneutics': ("해석학", "haeseokhak"),
    'c2-immunology': ("면역학", "myeon-yeokhak"),
    'c2-jurisprudence': ("법학", "beophak"),
    'c2-linguistics': ("언어학", "eoneohak"),
    'c2-metaphysics': ("형이상학", "hyeong-isanghak"),
    'c2-meteorology': ("기상학", "gisanghak"),
    'c2-microbiology': ("미생물학", "misaengmulhak"),
    'c2-musicology': ("음악학", "eumakhak"),
    'c2-neuroscience': ("신경과학", "singyeonggwahak"),
    'c2-oceanography': ("해양학", "haeyanghak"),
    'c2-ornithology': ("조류학", "joryuhak"),
    'c2-pedagogy': ("교육학", "gyoyukhak"),
    'c2-pharmacology': ("약리학", "yangnihak"),
    'c2-philology': ("문헌학", "munheonhak"),
    'c2-phonetics': ("음성학", "eumseonghak"),
    'c2-seismology': ("지진학", "jijinhak"),
    'c2-semiotics': ("기호학", "gihohak"),
    'c2-sociolinguistics': ("사회언어학", "sahoieoneohak"),
    'c2-theology': ("신학", "sinhak"),
    'c2-toxicology': ("독성학", "dokseonghak"),
    'c2-zoology': ("동물학", "dongmulhak"),
    'c2-acute-sudden-severe': ("급성이다", "geupseongida"),
    'c2-latent': ("잠복하다", "jambokhada"),
    'c2-benign': ("양성이다", "yangseongida"),
    'c2-malignant': ("악성이다", "akseongida"),
    'c2-biopsy': ("생검", "saenggeom"),
    'c2-prognosis': ("예후", "yehu"),
    'c2-flare-up': ("재발", "jaebal"),
    'c2-recurrence': ("재발", "jaebal"),
    'c2-sedative': ("진정제", "jinjeongje"),
    'c2-anesthetic': ("마취제", "machwije"),
    'c2-antibody': ("항체", "hangche"),
    'c2-inflammation': ("염증", "yeomjeung"),
    'c2-airborne': ("공기로 전염되다", "gonggiro jeonyeomdoeda"),
    'c2-hereditary': ("유전적이다", "yujeonjeogida"),
    'c2-congenital': ("선천적이다", "seoncheonjeogida"),
    'c2-dosage': ("용량", "yongnyang"),
    'c2-placebo': ("위약", "wiyak"),
    'c2-contraindication': ("금기 사항", "geumgi sahang"),
    'c2-intravenous': ("정맥 주사의", "jeongmaek jusaui"),
    'c2-suture': ("봉합", "bonghap"),
    'c2-incision': ("절개", "jeolgae"),
    'c2-donor': ("기증자", "gijeungja"),
    'c2-ultrasound': ("초음파 검사", "choeumpa geomsa"),
    'c2-referral-to-a-specialist': ("진료 의뢰", "jillyo uiroe"),
    'c2-inpatient': ("입원 환자", "ibwon hwanja"),
    'c2-palliative-care': ("완화 치료", "wanhwa chiryo"),
    'c2-triage': ("중증도 분류", "jungjeungdo bunnyu"),
    'c2-convalescence': ("회복기", "hoebokgi"),
    'c2-immunity': ("면역력", "myeon-yeongnyeok"),
    'c2-pandemic': ("팬데믹", "paendemik"),
    'c2-pathogen': ("병원체", "byeongwonche"),
    'c2-electrolyte': ("전해질", "jeonhaejil"),
    'c2-cardiovascular': ("심혈관의", "simhyeolgwanui"),
    'c2-respiratory': ("호흡기의", "hoheupgiui"),
    'c2-neurological': ("신경학적이다", "singyeonghakjeogida"),
    'c2-symptomatic': ("증상이 있다", "jeungsangi itda"),
    'c2-asymptomatic': ("무증상이다", "mujeungsangida"),
    'c2-prescription-written-order': ("처방전", "cheobangjeon"),
    'c2-generic-drug': ("복제약", "bokjeyak"),
    'c2-informed-consent': ("사전 동의", "sajeon dongui"),
    'c2-acquittal': ("무죄 판결", "mujoe pangyeol"),
    'c2-conviction-guilty-verdict': ("유죄 판결", "yujoe pangyeol"),
    'c2-deposition': ("증언 진술", "jeungeon jinsul"),
    'c2-accessory-to-a-crime': ("종범", "jongbeom"),
    'c2-arson': ("방화", "banghwa"),
    'c2-remand': ("구속 수감", "gusok sugam"),
    'c2-burden-of-proof': ("입증 책임", "ipjeung chaegim"),
    'c2-custody-detention': ("구금", "gugeum"),
    'c2-defendant': ("피고인", "pigoin"),
    'c2-plaintiff': ("원고", "wongo"),
    'c2-embezzlement': ("횡령", "hoengnyeong"),
    'c2-extortion': ("갈취", "galchwi"),
    'c2-felony': ("중죄", "jungjoe"),
    'c2-misdemeanor': ("경범죄", "gyeongbeomjoe"),
    'c2-forgery': ("위조", "wijo"),
    'c2-hearsay': ("전문 증거", "jeonmun jeunggeo"),
    'c2-indictment': ("기소", "giso"),
    'c2-injunction': ("금지 명령", "geumji myeongnyeong"),
    'c2-tribunal': ("법정", "beopjeong"),
    'c2-libel': ("문서 명예훼손", "munseo myeong-yehwoeson"),
    'c2-slander': ("구두 명예훼손", "gudu myeong-yehwoeson"),
    'c2-manslaughter': ("과실치사", "gwasilchisa"),
    'c2-parole': ("가석방", "gaseokbang"),
    'c2-perjury': ("위증", "wijeung"),
    'c2-plea-bargain': ("유죄 협상", "yujoe hyeopsang"),
    'c2-probation': ("집행 유예", "jipaeng yuye"),
    'c2-racketeering': ("공갈 조직 범죄", "gonggal jojik beomjoe"),
    'c2-ransom': ("몸값", "momgap"),
    'c2-statute': ("법령", "beomnyeong"),
    'c2-statute-of-limitations': ("공소 시효", "gongso sihyo"),
    'c2-subpoena': ("소환장", "sohwanjang"),
    'c2-testimony': ("증언", "jeungeon"),
    'c2-ruling': ("판결", "pangyeol"),
    'c2-warrant': ("영장", "yeongjang"),
    'c2-witness-stand': ("증인석", "jeunginseok"),
    'c2-contempt-of-court': ("법정 모독", "beopjeong modok"),
    'c2-cross-examination': ("반대 심문", "bandae simmun"),
    'c2-mistrial': ("무효 심리", "muhyo simni"),
    'c2-sentence-punishment': ("형량", "hyeongnyang"),
    'c2-to-plead-guilty': ("유죄를 인정하다", "yujoereul injeonghada"),
    'c2-thicket': ("덤불", "deombul"),
    'c2-undergrowth': ("하층식생", "hacheungsiksaeng"),
    'c2-moss': ("이끼", "ikki"),
    'c2-lichen': ("지의류", "jiuiryu"),
    'c2-fern': ("고사리", "gosari"),
    'c2-sap': ("수액", "suaek"),
    'c2-bark-of-a-tree': ("나무껍질", "namukkeopjil"),
    'c2-sapling': ("묘목", "myomok"),
    'c2-canopy-forest': ("수관", "sugwan"),
    'c2-grove': ("작은 숲", "jageun sup"),
    'c2-meadow': ("초원", "chowon"),
    'c2-marsh': ("습지", "seupji"),
    'c2-bog': ("늪", "neup"),
    'c2-estuary': ("하구", "hagu"),
    'c2-tributary': ("지류", "jiryu"),
    'c2-ravine': ("골짜기", "goljjagi"),
    'c2-gorge': ("협곡", "hyeopgok"),
    'c2-ridge': ("능선", "neungseon"),
    'c2-summit': ("정상", "jeongsang"),
    'c2-foothills': ("산기슭", "sangiseuk"),
    'c2-escarpment': ("급경사면", "geupgyeongsamyeon"),
    'c2-salt-flat': ("소금 평원", "sogeum pyeongwon"),
    'c2-cove': ("작은 만", "jageun man"),
    'c2-atoll': ("환초", "hwancho"),
    'c2-tide-pool': ("조수 웅덩이", "josu ungdeongi"),
    'c2-driftwood': ("유목", "yumok"),
    'c2-pebble': ("조약돌", "joyakdol"),
    'c2-boulder': ("바위덩이", "bawideongi"),
    'c2-sediment': ("퇴적물", "toejeongmul"),
    'c2-erosion': ("침식", "chimsik"),
    'c2-burrow': ("굴", "gul"),
    'c2-hive': ("벌집", "beoljip"),
    'c2-cocoon': ("고치", "gochi"),
    'c2-antler': ("사슴뿔", "seuseumppul"),
    'c2-talon': ("발톱", "baltop"),
    'c2-plumage': ("깃털", "gitteol"),
    'c2-migration-animal': ("이동", "idong"),
    'c2-hibernation': ("동면", "dongmyeon"),
    'c2-pollination': ("수분", "subun"),
    'c2-germination': ("발아", "bara"),
    'c2-torrential': ("억수같다", "eoksugatda"),
    'c2-monsoon': ("계절풍", "gyejeolpung"),
    'c2-sleet': ("진눈깨비", "jinnunkkaebi"),
    'c2-flurry-snow': ("눈발", "nunbal"),
    'c2-whiteout': ("화이트아웃", "hwaiteuaut"),
    'c2-black-ice': ("노면 결빙", "nomyeon gyeolbing"),
    'c2-dew': ("이슬", "iseul"),
    'c2-haze': ("연무", "yeonmu"),
    'c2-clammy': ("눅진하다", "nukjinhada"),
    'c2-scorcher': ("폭염", "pogyeom"),
    'c2-sultry': ("후텁지근하다", "huteopjigeunhada"),
    'c2-balmy': ("온화하다", "onhwahada"),
    'c2-crisp-air': ("상쾌하다", "sangkwaehada"),
    'c2-gust': ("돌풍", "dolpung"),
    'c2-gale': ("강풍", "gangpung"),
    'c2-squall': ("스콜", "seukol"),
    'c2-thunderclap': ("벽력", "byeongnyeok"),
    'c2-lightning-bolt': ("벼락", "byeorak"),
    'c2-cloudburst': ("장대비", "jangdaebi"),
    'c2-nightfall': ("땅거미", "ttanggeomi"),
    'c2-cold-snap': ("한파", "hanpa"),
    'c2-thaw': ("해빙", "haebing"),
    'c2-humidity': ("습도", "seupdo"),
    'c2-barometer': ("기압계", "giapgye"),
    'c2-forecast-verb': ("예보하다", "yebohada"),
    'c2-daybreak': ("여명", "yeomyeong"),
    'c2-aurora': ("오로라", "orora"),
    'c2-twilight': ("황혼", "hwanghon"),
    'c2-solstice': ("지점", "jijeom"),
    'c2-equinox': ("분점", "bunjeom"),
    'c2-arch': ("아치", "achi"),
    'c2-vault-ceiling': ("궁륭", "gungnyung"),
    'c2-dome': ("돔", "dom"),
    'c2-spire': ("첨탑", "cheomtap"),
    'c2-buttress': ("부벽", "bubyeok"),
    'c2-pillar': ("기둥", "gidung"),
    'c2-column': ("원주", "wonju"),
    'c2-beam-structural': ("들보", "deulbo"),
    'c2-rafter': ("서까래", "seokkarae"),
    'c2-girder': ("대들보", "daedeulbo"),
    'c2-keystone': ("쐐기돌", "ssoegidol"),
    'c2-facade-building-front': ("정면", "jeongmyeon"),
    'c2-cornice': ("처마돌림띠", "cheomadollimtti"),
    'c2-gable': ("박공", "bakgong"),
    'c2-eaves': ("처마", "cheoma"),
    'c2-gutter-roof': ("홈통", "homtong"),
    'c2-skylight': ("천창", "cheonchang"),
    'c2-balustrade': ("난간", "nangan"),
    'c2-parapet': ("흉벽", "hyungbyeok"),
    'c2-turret': ("소탑", "sotap"),
    'c2-moat': ("해자", "haeja"),
    'c2-drawbridge': ("도개교", "dogaegyo"),
    'c2-cloister': ("회랑", "hoerang"),
    'c2-courtyard': ("안뜰", "antteul"),
    'c2-alcove': ("벽감", "byeokgam"),
    'c2-mezzanine': ("중이층", "jungicheung"),
    'c2-atrium': ("중정", "jungjeong"),
    'c2-mosaic': ("모자이크", "mojaikeu"),
    'c2-fresco': ("프레스코화", "peureseukohwa"),
    'c2-elevation-drawing': ("입면도", "ipmyeondo"),
    'c2-partition-wall': ("칸막이벽", "kanmagibyeok"),
    'c2-cladding': ("외장재", "oejangjae"),
    'c2-plumbing-system': ("배관", "baegwan"),
    'c2-ventilation-duct': ("환기 덕트", "hwangi deokteu"),
    'c2-retrofit': ("개보수", "gaebosu"),
    'c2-colander': ("거름망", "georeummang"),
    'c2-ladle': ("국자", "gukja"),
    'c2-whisk': ("거품기", "geopumgi"),
    'c2-grater': ("강판", "gangpan"),
    'c2-tongs': ("집게", "jipge"),
    'c2-spatula': ("뒤집개", "dwijipgae"),
    'c2-cutting-board': ("도마", "doma"),
    'c2-french-press': ("프렌치프레스", "peurenchipeureseu"),
    'c2-coaster': ("컵받침", "keopbatchim"),
    'c2-trivet': ("냄비받침", "naembibatchim"),
    'c2-oven-mitt': ("오븐 장갑", "obeun janggap"),
    'c2-dish-rack': ("식기 건조대", "sikgi geonjodae"),
    'c2-dustpan': ("쓰레받기", "sseureibatgi"),
    'c2-mop': ("대걸레", "daegeolle"),
    'c2-clothespin': ("빨래집게", "ppallaejipge"),
    'c2-clothesline': ("빨랫줄", "ppallaetjul"),
    'c2-shoehorn': ("구둣주걱", "gudutjugeok"),
    'c2-doormat': ("현관 매트", "hyeongwan maeteu"),
    'c2-doorknob': ("문손잡이", "munsonjabi"),
    'c2-hinge': ("경첩", "gyeongcheop"),
    'c2-latch': ("걸쇠", "geolsoe"),
    'c2-peephole': ("외시경", "oesigyeong"),
    'c2-blinds-window': ("블라인드", "beullaindeu"),
    'c2-windowsill': ("창턱", "changteok"),
    'c2-banister': ("계단 난간", "gyedan nangan"),
    'c2-landing-stairs': ("층계참", "cheunggyecham"),
    'c2-crawl-space': ("바닥 밑 공간", "badak mit gonggan"),
    'c2-cellar': ("지하 저장고", "jiha jeojanggo"),
    'c2-pantry': ("식료품 저장실", "singnyopum jeojangsil"),
    'c2-utility-room': ("다용도실", "dayongdosil"),
    'c2-fuse-box': ("두꺼비집", "dukkeobijip"),
    'c2-dimmer-switch': ("조광 스위치", "jogwang seuwichi"),
    'c2-extension-cord': ("연장 코드", "yeonjang kodeu"),
    'c2-power-strip': ("멀티탭", "meoltitaep"),
    'c2-carbon-monoxide-alarm': ("일산화탄소 경보기", "ilsanhwatanso gyeongbogi"),
    'c2-first-aid-kit': ("구급상자", "gugeupsangja"),
    'c2-sewing-kit': ("반짇고리", "banjitgori"),
    'c2-toolbox': ("공구함", "gongguham"),
    'c2-allen-key': ("육각 렌치", "yukgak renchi"),
    'c2-pliers': ("펜치", "penchi"),
    'c2-wrench': ("렌치", "renchi"),
    'c2-tape-measure': ("줄자", "julja"),
    'c2-spirit-level': ("수평계", "supyeonggye"),
    'c2-drawer-organizer': ("서랍 정리함", "seorap jeongniham"),
    'c2-bin-liner': ("쓰레기봉투", "sseuregibongtu"),
    'c2-to-seethe': ("부글부글 끓다", "bugeulbugeul kkeulta"),
    'c2-to-sulk': ("토라지다", "torajida"),
    'c2-to-fret': ("안달하다", "andalhada"),
    'c2-to-brood': ("곱씹다", "gopssipda"),
    'c2-to-wallow-in-self-pity': ("자기연민에 빠지다", "jagiyeonmine ppajida"),
    'c2-to-gloat-over-a-rival': ("고소해하다", "gosohaehada"),
    'c2-to-savor-the-moment': ("순간을 만끽하다", "sunganeul mankkitada"),
    'c2-to-revel-in': ("흠뻑 빠지다", "heumppeok ppajida"),
    'c2-to-marvel-at': ("감탄하다", "gamtanhada"),
    'c2-to-cringe': ("움찔하다", "umjjilhada"),
    'c2-to-wince': ("찡그리다", "jjinggeurida"),
    'c2-to-flinch': ("움츠러들다", "umcheureodeulda"),
    'c2-to-shudder': ("몸서리치다", "momseorichida"),
    'c2-to-quiver': ("바르르 떨다", "bareureu tteolda"),
    'c2-to-swoon': ("황홀해하다", "hwanghollhaehada"),
    'c2-to-pine-for': ("사무치게 그리워하다", "samuchige geuriwohada"),
    'c2-to-long-for': ("그리워하다", "geuriwohada"),
    'c2-to-crave': ("갈구하다", "galguhada"),
    'c2-to-abominate': ("질색하다", "jilsaekhada"),
    'c2-to-nurse-a-grievance': ("앙심을 품다", "angsimeul pumda"),
    'c2-to-begrudge': ("아까워하다", "akkawohada"),
    'c2-to-grovel': ("굽실거리다", "gupsilgeorida"),
    'c2-to-fawn-over': ("아부하다", "abuhada"),
    'c2-to-dote-on': ("애지중지하다", "aejijungjihada"),
    'c2-to-treasure': ("소중히 여기다", "sojunghi yeogida"),
    'c2-to-put-at-ease': ("안심시키다", "ansimsikida"),
    'c2-to-console': ("위로하다", "wirohada"),
    'c2-to-commiserate': ("동병상련하다", "dongbyeongsangnyeonhada"),
    'c2-to-exasperate': ("속을 뒤집다", "sogeul dwijipda"),
    'c2-to-infuriate': ("격분시키다", "gyeokbunsikida"),
    'c2-to-unnerve': ("주눅 들게 하다", "junuk deulge hada"),
    'c2-to-mortify': ("굴욕감을 주다", "guryokgameul juda"),
    'c2-to-captivate': ("사로잡다", "sarojapda"),
    'c2-to-enrapture': ("도취시키다", "dochwisikida"),
    'c2-to-disillusion': ("환멸을 느끼게 하다", "hwanmyeoreul neukkige hada"),
    'c2-to-mollify': ("누그러뜨리다", "nugeureotteurida"),
    'c2-to-embolden': ("대담하게 만들다", "daedamhage mandeulda"),
    'c2-to-dishearten': ("낙담시키다", "nakdamsikida"),
    'c2-to-rankle': ("마음에 걸리다", "maeume geollida"),
    'c2-to-smolder': ("은근히 타오르다", "eungeunhi taooruda"),
    'c2-numbness': ("무감각", "mugamgak"),
    'c2-tingling': ("저림", "jeorim"),
    'c2-cramp': ("쥐", "jwi"),
    'c2-twinge': ("욱신거림", "uksingeorim"),
    'c2-throbbing': ("지끈거리다", "jikkeungeorida"),
    'c2-dizziness': ("어지럼증", "eojireomjeung"),
    'c2-lightheaded': ("아찔하다", "ajjilhada"),
    'c2-vertigo': ("현훈", "hyeonhun"),
    'c2-queasy': ("메스껍다", "meseukkeopda"),
    'c2-lethargy': ("무기력증", "mugiryeokjeung"),
    'c2-fatigue': ("피로", "piro"),
    'c2-stamina': ("지구력", "jiguryeok"),
    'c2-reflex': ("반사 신경", "bansa singyeong"),
    'c2-flinch-noun': ("화들짝 놀람", "hwadeuljjak nollam"),
    'c2-pins-and-needles': ("저릿저릿함", "jeoritjeoritham"),
    'c2-shiver': ("오한", "ohan"),
    'c2-hot-flush': ("열감", "yeolgam"),
    'c2-blush': ("홍조", "hongjo"),
    'c2-yawn': ("하품", "hapum"),
    'c2-hiccup': ("딸꾹질", "ttalkkukjil"),
    'c2-sneeze': ("재채기", "jaechaegi"),
    'c2-itch': ("가려움", "garyeoum"),
    'c2-bruise': ("멍", "meong"),
    'c2-blister': ("물집", "muljip"),
    'c2-pulled-muscle': ("근육 좌상", "geunyuk jwasang"),
    'c2-stiffness': ("결림", "gyeollim"),
    'c2-restlessness': ("안절부절함", "anjeolbujeolham"),
    'c2-daydream': ("백일몽", "baekilmong"),
    'c2-deja-vu': ("데자뷔", "dejabwi"),
    'c2-hunch': ("예감", "yegam"),
    'c2-gut-feeling': ("직감", "jikgam"),
    'c2-brain-fog': ("멍한 상태", "meonghan sangtae"),
    'c2-second-wind': ("재충전", "jaechungjeon"),
    'c2-adrenaline-rush': ("아드레날린 분출", "adeurenallin bunchul"),
    'c2-motion-sickness': ("멀미", "meolmi"),
    'c2-camaraderie': ("동료애", "dongnyoae"),
    'c2-affinity-between-people': ("유대감", "yudaegam"),
    'c2-clique': ("파벌", "pabeol"),
    'c2-entourage': ("수행원", "suhaengwon"),
    'c2-etiquette': ("예절", "yejeol"),
    'c2-faux-pas': ("결례", "gyeollye"),
    'c2-gossip': ("험담", "heomdam"),
    'c2-grudge': ("원한", "wonhan"),
    'c2-chain-of-command': ("지휘 계통", "jihwi gyetong"),
    'c2-nepotism': ("족벌주의", "jokbeoljuui"),
    'c2-ostracism': ("따돌림", "ttadollim"),
    'c2-groupthink': ("집단 사고", "jipdan sago"),
    'c2-pecking-order': ("서열", "seoyeol"),
    'c2-rivalry': ("경쟁 관계", "gyeongjaeng gwangye"),
    'c2-solidarity': ("연대감", "yeondaegam"),
    'c2-snub': ("냉대", "naengdae"),
    'c2-taboo': ("금기", "geumgi"),
    'c2-flattery': ("아첨", "acheom"),
    'c2-backhanded-compliment': ("가시 돋친 칭찬", "gasi dotchin chingchan"),
    'c2-cold-shoulder': ("쌀쌀맞게 대하다", "ssalssalmatge daehada"),
    'c2-small-circle-inner-circle': ("측근 그룹", "cheukgeun geurup"),
    'c2-interloper': ("불청객", "bulcheonggaek"),
    'c2-old-hand': ("고참", "gocham"),
    'c2-wingman': ("들러리", "deulleori"),
    'c2-freeloader': ("빈대", "bindae"),
    'c2-busybody': ("오지랖쟁이", "ojirapjaengi"),
    'c2-killjoy': ("분위기 깨는 사람", "bunwigi kkaeneun saram"),
    'c2-show-off': ("허세꾼", "heosekkun"),
    'c2-pushover': ("만만한 사람", "manmanhan saram"),
    'c2-self-starter': ("자기주도적인 사람", "jagijudojeogin saram"),
    'c2-to-mingle': ("어울리다", "eoullida"),
    'c2-to-schmooze': ("인맥을 쌓다", "inmaegeul ssahda"),
    'c2-to-shun': ("멀리하다", "meollihada"),
    'c2-to-patronize': ("얕보다", "yatboda"),
    'c2-to-reconcile': ("화해하다", "hwahaehada"),
    'c2-to-estrange': ("소원하게 만들다", "sowonhage mandeulda"),
    'c2-to-confide-in': ("속마음을 털어놓다", "sokmaeumeul teoreonota"),
    'c2-to-hobnob': ("친하게 지내다", "chinhage jinaeda"),
    'c2-to-rub-shoulders-with': ("교류하다", "gyoryuhada"),
    'c2-to-fall-out-with': ("사이가 틀어지다", "saiga teureojida"),
    'c2-foil-character': ("대조 인물", "daejo inmul"),
    'c2-anti-hero': ("반영웅", "banyeongung"),
    'c2-narrator': ("화자", "hwaja"),
    'c2-macguffin': ("맥거핀", "maekgeopin"),
    'c2-red-herring': ("속임수 단서", "sogimsu danseo"),
    'c2-motif': ("모티프", "motipeu"),
    'c2-frame-narrative': ("액자식 구성", "aekjasik guseong"),
    'c2-denouement': ("결말", "gyeolmal"),
    'c2-satire': ("풍자", "pungja"),
    'c2-parody': ("패러디", "paereodi"),
    'c2-allegory': ("풍유", "pungyu"),
    'c2-memoir': ("회고록", "hoegorok"),
    'c2-anthology': ("선집", "seonjip"),
    'c2-manuscript': ("원고", "wongo"),
    'c2-prose': ("산문", "sanmun"),
    'c2-couplet': ("대구", "daegu"),
    'c2-stanza': ("연", "yeon"),
    'c2-sonnet': ("소네트", "soneteu"),
    'c2-alliteration': ("두운", "duun"),
    'c2-meter-poetry': ("운율", "unyul"),
    'c2-aesthetic': ("미학", "mihak"),
    'c2-avant-garde': ("아방가르드", "abanggareudeu"),
    'c2-baroque': ("바로크", "barokeu"),
    'c2-impressionism': ("인상주의", "insangjuui"),
    'c2-surrealism': ("초현실주의", "chohyeonsiljuui"),
    'c2-still-life': ("정물화", "jeongmulhwa"),
    'c2-charcoal-drawing': ("목탄화", "moktanhwa"),
    'c2-etching': ("에칭", "eching"),
    'c2-bust-sculpture': ("흉상", "hyungsang"),
    'c2-chisel': ("끌", "kkeul"),
    'c2-easel': ("이젤", "ijel"),
    'c2-palette': ("팔레트", "palleteu"),
    'c2-overture': ("서곡", "seogok"),
    'c2-aria': ("아리아", "aria"),
    'c2-encore': ("앙코르", "angkoreu"),
    'c2-bandwidth': ("대역폭", "daeyeokpok"),
    'c2-jitter': ("지터", "jiteo"),
    'c2-throughput': ("처리량", "cheorinyang"),
    'c2-hashing': ("해싱", "haesing"),
    'c2-intrusion-detection': ("침입 탐지", "chimip tamji"),
    'c2-vulnerability-security': ("취약점", "chwiyakjeom"),
    'c2-hotfix': ("긴급 수정", "gingeup sujeong"),
    'c2-backlog': ("잔무", "janmu"),
    'c2-rollout': ("배포", "baepo"),
    'c2-rollback': ("롤백", "rolbaek"),
    'c2-uptime': ("가동 시간", "gadong sigan"),
    'c2-redundancy-backup': ("이중화", "ijunghwa"),
    'c2-load-balancing': ("부하 분산", "buha bunsan"),
    'c2-legacy-system': ("레거시 시스템", "legeosi siseutem"),
    'c2-copyleft': ("카피레프트", "kapireupeuteu"),
    'c2-proprietary': ("독점적이다", "dokjeomjeogida"),
    'c2-interoperability': ("상호운용성", "sanghounyongseong"),
    'c2-passkey': ("패스키", "paeseuki"),
    'c2-social-engineering': ("사회공학", "sahoegonghak"),
    'c2-data-breach': ("데이터 유출", "deiteo yuchul"),
    'c2-cache': ("캐시", "kaesi"),
    'c2-query': ("쿼리", "kwori"),
    'c2-metadata': ("메타데이터", "metadeiteo"),
    'c2-placeholder': ("임시 표시자", "imsi pyosija"),
    'c2-workaround': ("임시방편", "imsibangpyeon"),
    'c2-bottleneck': ("병목 현상", "byeongmok hyeonsang"),
    'c2-edge-case': ("예외 상황", "yeoe sanghwang"),
    'c2-deprecated': ("사용이 중단되다", "sayongi jungdandoeda"),
    'c2-sandbox': ("샌드박스", "saendeubakseu"),
    'c2-telemetry': ("원격 측정", "wongyeok cheukjeong"),
    'c2-algorithmic-bias': ("알고리즘 편향", "algorijeum pyeonhyang"),
    'c2-overfitting': ("과적합", "gwajeokhap"),
    'c2-large-language-model': ("거대 언어 모델", "geodae eoneo model"),
    'c2-quantum-computing': ("양자 컴퓨팅", "yangja keompyuting"),
    'c2-semiconductor': ("반도체", "bandoche"),
    'c2-working-capital': ("운전자본", "unjeonjabon"),
    'c2-solvency': ("지급 능력", "jigeup neungnyeok"),
    'c2-insolvency': ("지급 불능", "jigeup bulleung"),
    'c2-receivership': ("법정관리", "beopjeonggwalli"),
    'c2-leverage-finance': ("레버리지", "rebeoriji"),
    'c2-hedge-finance': ("헤지", "heji"),
    'c2-yield-finance': ("수익률", "suikryul"),
    'c2-share-buyback': ("자사주 매입", "jasaju maeip"),
    'c2-equity-ownership': ("자기자본", "jagijabon"),
    'c2-treasury-bill': ("국고채", "gukgochae"),
    'c2-asset-allocation': ("자산 배분", "jasan baebun"),
    'c2-volatility': ("변동성", "byeondongseong"),
    'c2-bull-market': ("상승장", "sangseungjang"),
    'c2-bear-market': ("하락장", "harakjang"),
    'c2-downturn': ("경기 침체", "gyeonggi chimche"),
    'c2-stagflation': ("스태그플레이션", "seutaegeupeulleisyeon"),
    'c2-deflation': ("디플레이션", "dipeulleisyeon"),
    'c2-interest-rate-hike': ("금리 인상", "geumni insang"),
    'c2-fiscal-policy': ("재정 정책", "jaejeong jeongchaek"),
    'c2-monetary-policy': ("통화 정책", "tonghwa jeongchaek"),
    'c2-subsidy': ("보조금", "bojogeum"),
    'c2-trade-quota': ("무역 할당량", "muyeok haldangnyang"),
    'c2-embargo': ("금수 조치", "geumsu joti"),
    'c2-belt-tightening': ("허리띠 졸라매기", "heoritti jollamaegi"),
    'c2-bailout': ("구제 금융", "guje geumyung"),
    'c2-windfall': ("횡재", "hoengjae"),
    'c2-nest-egg': ("비상금", "bisanggeum"),
    'c2-slush-fund': ("비자금", "bijageum"),
    'c2-kickback': ("뒷돈", "dwitdon"),
    'c2-money-laundering': ("자금 세탁", "jageum setak"),
    'c2-tax-evasion': ("탈세", "talse"),
    'c2-tax-loophole': ("세금 허점", "segeum heojeom"),
    'c2-underwriter': ("인수인", "insuin"),
    'c2-sinking-fund': ("감채 기금", "gamchae gigeum"),
    'c2-arbitrage': ("차익 거래", "chaik georae"),
    'c2-freight': ("화물", "hwamul"),
    'c2-cargo-hold': ("화물칸", "hwamulkan"),
    'c2-consignment': ("탁송", "taksong"),
    'c2-customs-clearance': ("통관", "tonggwan"),
    'c2-red-eye-flight': ("야간 비행편", "yagan bihaengpyeon"),
    'c2-turbulence': ("난기류", "nangiryu"),
    'c2-taxiing': ("지상 활주", "jisang hwalju"),
    'c2-cockpit': ("조종석", "jojongseok"),
    'c2-overhead-compartment': ("머리 위 짐칸", "meori wi jimkan"),
    'c2-aisle-seat': ("통로석", "tongnoseok"),
    'c2-boarding-pass': ("탑승권", "tapseunggwon"),
    'c2-baggage-carousel': ("수하물 수취대", "suhamul suchwidae"),
    'c2-jet-bridge': ("탑승교", "tapseunggyo"),
    'c2-tailgating-driving': ("바짝 붙어 운전하다", "bajjak buteo unjeonhada"),
    'c2-gridlock': ("교통 마비", "gyotong mabi"),
    'c2-diversion-route': ("우회로", "uhoero"),
    'c2-interchange-highway': ("나들목", "nadeulmok"),
    'c2-overpass': ("고가도로", "gogadoro"),
    'c2-underpass': ("지하도", "jihado"),
    'c2-toll-booth': ("요금소", "yogeumso"),
    'c2-hard-shoulder': ("갓길", "gatgil"),
    'c2-speed-bump': ("과속방지턱", "gwasokbangjiteok"),
    'c2-blind-spot': ("사각지대", "sagakjidae"),
    'c2-hazard-lights': ("비상등", "bisangdeung"),
    'c2-windshield-wiper': ("와이퍼", "waipeo"),
    'c2-clutch-car': ("클러치", "keulleochi"),
    'c2-handbrake': ("사이드브레이크", "saideubeureikeu"),
    'c2-odometer': ("주행 거리계", "juhaeng georigye"),
    'c2-tow-truck': ("견인차", "gyeonincha"),
    'c2-commute-noun': ("통근", "tonggeun"),
    'c2-numerator': ("분자", "bunja"),
    'c2-denominator': ("분모", "bunmo"),
    'c2-exponent': ("지수", "jisu"),
    'c2-square-root': ("제곱근", "jegopgeun"),
    'c2-decimal-point': ("소수점", "sosujeom"),
    'c2-remainder': ("나머지", "nameoji"),
    'c2-prime-number': ("소수", "sosu"),
    'c2-integer': ("정수", "jeongsu"),
    'c2-quotient': ("몫", "mok"),
    'c2-percentile': ("백분위수", "baekbunwisu"),
    'c2-mean-average': ("평균", "pyeonggyun"),
    'c2-median': ("중앙값", "junganggap"),
    'c2-outlier': ("이상치", "isangchi"),
    'c2-standard-deviation': ("표준편차", "pyojunpyeoncha"),
    'c2-variance': ("분산", "bunsan"),
    'c2-margin-of-error': ("오차 범위", "ocha beomwi"),
    'c2-sample-size': ("표본 크기", "pyobon keugi"),
    'c2-exponential-growth': ("지수적 성장", "jisujeok seongjang"),
    'c2-order-of-magnitude': ("자릿수", "jaritsu"),
    'c2-rounding': ("반올림", "banollim"),
    'c2-percentage-point': ("퍼센트포인트", "peosenteupointeu"),
    'c2-threefold': ("세 배", "se bae"),
    'c2-a-dozen': ("한 다스", "han daseu"),
    'c2-round-number': ("어림수", "eorimsu"),
    'c2-odds-probability': ("확률", "hwangnyul"),
    'c2-inseam': ("안쪽 솔기 길이", "anjjok solgi giri"),
    'c2-dart-sewing': ("다트", "dateu"),
    'c2-lapel': ("라펠", "rapel"),
    'c2-cuff': ("소맷동", "somaetdong"),
    'c2-cufflinks': ("커프스단추", "keopeuseudanchu"),
    'c2-gusset': ("무", "mu"),
    'c2-pleat': ("주름", "jureum"),
    'c2-tailored': ("몸에 맞게 재단되다", "mome matge jaedandoeda"),
    'c2-bespoke': ("맞춤 제작되다", "matchum jejakdoeda"),
    'c2-off-the-rack': ("기성복이다", "giseongbogida"),
    'c2-threadbare': ("닳아 해지다", "dara haejida"),
    'c2-frayed': ("올이 풀리다", "ori pullida"),
    'c2-creased': ("구겨지다", "gugyeojida"),
    'c2-dapper': ("말쑥하다", "malssukhada"),
    'c2-disheveled': ("헝클어지다", "heongkeureojida"),
    'c2-scruffy': ("꾀죄죄하다", "kkoejoejoehada"),
    'c2-garish': ("요란하다", "yoranhada"),
    'c2-understated': ("수수하다", "susuhada"),
    'c2-flattering-clothes': ("잘 어울리다", "jal eoullida"),
    'c2-baggy': ("헐렁하다", "heolleonghada"),
    'c2-snug': ("딱 맞다", "ttak matda"),
    'c2-stubble': ("까칠한 수염", "kkachilhan suyeom"),
    'c2-freckles': ("주근깨", "jugeunkkae"),
    'c2-dimple': ("보조개", "bojogae"),
    "c2-crow-s-feet": ("눈가 주름", "nunga jureum"),
    'c2-complexion': ("안색", "ansaek"),
    'c2-gaunt': ("수척하다", "sucheokhada"),
    'c2-stocky': ("다부지다", "dabujida"),
    'c2-lanky': ("멀쑥하다", "meolssukhada"),
    'c2-poised': ("침착하다", "chimchakhada"),
    'c2-soliloquy': ("독백", "dokbaek"),
    'c2-subtext': ("저의", "jeoui"),
    'c2-tangent': ("곁길", "gyeotgil"),
    'c2-tirade': ("장광설", "janggwangseol"),
    'c2-understatement': ("완서법", "wanseobeop"),
    'c2-verbiage': ("군말", "gunmal"),
    'c2-to-allude-to': ("암시하다", "amsihada"),
    'c2-to-enunciate': ("또박또박 말하다", "ttobakttobak malhada"),
    'c2-to-belabor-the-point': ("지나치게 강조하다", "jinachige gangjohada"),
    'c2-to-digress': ("옆길로 새다", "yeopgillo saeda"),
    'c2-to-expound': ("부연하다", "buyeonhada"),
    'c2-to-insinuate': ("빗대다", "bitdaeda"),
    'c2-to-interject': ("끼어들다", "kkieodeulda"),
    'c2-to-hammer-home': ("못박다", "motbakda"),
    'c2-to-retort': ("맞받아치다", "matbadachida"),
    'c2-to-waffle-be-vague': ("얼버무리다", "eolbeomurida"),
    'c2-actuary': ("보험계리사", "boheomgyerisa"),
    'c2-anesthesiologist': ("마취전문의", "machwijeonmunui"),
    'c2-archivist': ("기록보관인", "girokbogwanin"),
}
