# -*- coding: utf-8 -*-
LANG = 'la'
WORDS = {
    'c1-broadcast': ('Emissio', None),
    'c1-coverage': ('Relatio', None),
    'c1-correspondent': ('Correspondens', None),
    'c1-anchor-news': ('Pronuntiator nuntiorum', None),
    'c1-editorial': ('Editoriale', None),
    'c1-slant-bias': ('Inclinatio', None),
    'c1-to-leak': ('Divulgare', None),
    'c1-source-journalism': ('Fons', None),
    'c1-whistleblower': ('Denuntiator', None),
    'c1-censorship': ('Censura', None),
    'c1-propaganda': ('Propaganda', None),
    'c1-misinformation': ('Informatio falsa', None),
    'c1-fact-check': ('Veritatis inquisitio', None),
    'c1-viral': ('Viralis', None),
    'c1-clickbait': ('Illecebra electronica', None),
    'c1-tabloid': ('Ephemeris scurrilis', None),
    'c1-press-conference': ('Congressus nuntiorum', None),
    'c1-press-release': ('Nuntiatio publica', None),
    'c1-exclusive-story': ('Relatio singularis', None),
    'c1-breaking-news': ('Nuntius recentissimus', None),
    'c1-viewership': ('Numerus spectatorum', None),
    'c1-subscriber': ('Subscriptor', None),
    'c1-paywall': ('Murus pecuniarius', None),
    'c1-influencer': ('Influxor', None),
    'c1-to-trend': ('Percrebrescere', None),
    'c1-hashtag': ('Titulus cardinalis', None),
    'c1-op-ed': ('Commentarius sententiae', None),
    'c1-byline': ('Nomen auctoris', None),
    'c1-segment-tv': ('Pars emissionis', None),
    'c1-airtime': ('Tempus emissionis', None),
    'c1-methodology': ('Methodologia', None),
    'c1-empirical': ('Empiricus', None),
    'c1-qualitative': ('Qualitativus', None),
    'c1-quantitative': ('Quantitativus', None),
    'c1-variable': ('Variabile', None),
    'c1-correlation': ('Correlatio', None),
    'c1-causation': ('Causatio', None),
    'c1-sample-study': ('Specimen', None),
    'c1-peer-review': ('Recognitio a paribus', None),
    'c1-citation': ('Citatio', None),
    'c1-abstract-summary': ('Epitome', None),
    'c1-dissertation': ('Dissertatio', None),
    'c1-scholar': ('Doctus', None),
    'c1-discipline-field': ('Disciplina', None),
    'c1-paradigm': ('Paradigma', None),
    'c1-phenomenon': ('Phaenomenon', None),
    'c1-premise': ('Propositio', None),
    'c1-inference': ('Illatio', None),
    'c1-to-infer': ('Inferre', None),
    'c1-to-deduce': ('Deducere', None),
    'c1-rigorous': ('Severus', None),
    'c1-nuanced': ('Subtilis', None),
    'c1-to-synthesize': ('Componere', None),
    'c1-critique': ('Existimatio (critica)', None),
    'c1-discourse': ('Sermo', None),
    'c1-hierarchy': ('Hierarchia', None),
    'c1-paradox': ('Paradoxon', None),
    'c1-theoretical': ('Speculativus', None),
    'c1-findings': ('Inventum', None),
    'c1-assumption': ('Suppositio', None),
    'c1-to-back-up-support': ('Sustinere', None),
    'c1-to-bring-up-mention': ('Commemorare', None),
    'c1-to-call-off': ('Rescindere', None),
    'c1-to-carry-on': ('Pergere', None),
    'c1-to-check-out-look-at': ('Inspicere', None),
    'c1-to-come-across': ('Incidere (in aliquid)', None),
    'c1-to-cut-down-on': ('Minuere', None),
    'c1-to-do-without': ('Carere', None),
    'c1-to-fall-apart': ('Dilabi', None),
    'c1-to-fall-behind': ('Deficere', None),
    'c1-to-get-away-with': ('Impune agere', None),
    'c1-to-get-by': ('Subsistere', None),
    'c1-to-get-over': ('Superare', None),
    'c1-to-give-in': ('Cedere', None),
    'c1-to-go-through-experience': ('Perpeti', None),
    'c1-to-hold-on': ('Perseverare', None),
    'c1-to-keep-up-with': ('Assequi', None),
    'c1-to-let-down': ('Fallere', None),
    'c1-to-look-into': ('Investigare', None),
    'c1-to-look-up-to': ('Suspicere', None),
    'c1-to-make-up-for': ('Compensare', None),
    'c1-to-pass-out': ('Collabi', None),
    'c1-to-point-out': ('Indicare', None),
    'c1-to-put-up-with': ('Tolerare', None),
    'c1-to-run-into': ('Offendere', None),
    'c1-to-set-up': ('Constituere', None),
    'c1-to-sort-out': ('Expedire', None),
    'c1-to-stand-for': ('Significare', None),
    'c1-to-take-after': ('Referre', None),
    'c1-to-take-over': ('Occupare', None),
    'c1-to-turn-down': ('Recusare', None),
    'c1-to-turn-up': ('Apparere', None),
    'c1-to-work-out-resolve': ('Succedere', None),
    'c1-to-wear-off': ('Evanescere', None),
    'c1-to-wind-up-end-up': ('Evadere', None),
    'c1-to-break-off': ('Abrumpere', None),
    'c1-to-brush-up-on': ('Recolere', None),
    'c1-to-catch-on': ('Increbrescere', None),
    'c1-to-come-down-with': ('Corripi (morbo)', None),
    'c1-to-crack-down-on': ('Coercere', None),
    'c1-to-dwell-on': ('Immorari', None),
    'c1-to-fall-through': ('Cadere', None),
    'c1-to-get-across': ('Declarare', None),
    'c1-to-hold-back': ('Retinere', None),
    'c1-to-iron-out': ('Dirimere', None),
    'c1-to-live-up-to': ('Respondere', None),
    'c1-to-narrow-down': ('Restringere', None),
    'c1-to-opt-out': ('Recedere', None),
    'c1-to-phase-out': ('Sensim tollere', None),
    'c1-to-pull-off': ('Perficere', None),
    'c1-to-rule-out': ('Excludere', None),
    'c1-to-settle-for': ('Acquiescere', None),
    'c1-to-stick-to': ('Adhaerere', None),
    'c1-to-take-on-a-task': ('Suscipere', None),
    'c1-to-touch-on': ('Attingere', None),
    'c1-to-weigh-up': ('Perpendere', None),
    'c1-to-wrap-up': ('Concludere', None),
    'c1-to-zero-in-on': ('Intendere', None),
    'c1-to-fend-off': ('Propulsare', None),
    'c1-to-stem-from': ('Oriri', None),
    'c1-awesome': ('Mirificus', None),
    'c1-gross': ('Spurcus', None),
    'c1-lame': ('Ineptus', None),
    'c1-cheesy': ('Insulsus', None),
    'c1-to-chill': ('Quiescere', None),
    'c1-dude': ('Sodalis', None),
    'c1-to-ditch': ('Deserere', None),
    'c1-to-bail-leave': ('Aufugere', None),
    'c1-to-crash-sleep': ('Condormiscere', None),
    'c1-to-freak-out': ('Consternari', None),
    'c1-to-nail-it': ('Excellere', None),
    'c1-to-screw-up': ('Peccare', None),
    'c1-a-bummer': ('Incommodum', None),
    'c1-no-biggie': ('Res levis', None),
    'c1-to-be-into': ('Studere', None),
    'c1-hooked': ('Addictus', None),
    'c1-hype': ('Iactatio', None),
    'c1-sketchy': ('Suspectus', None),
    'c1-legit': ('Legitimus', None),
    'c1-a-rip-off': ('Fraus', None),
    'c1-to-ghost': ('Sublabi', None),
    'c1-cringe': ('Pudendus', None),
    'c1-to-wing-it': ('Ex tempore agere', None),
    'c1-to-zone-out': ('Obstupescere', None),
    'c1-to-kick-back': ('Otiari', None),
    'c1-for-real': ('Vere', None),
    'c1-buddy': ('Contubernalis', None),
    'c1-to-hit-the-road': ('Proficisci', None),
    'c1-to-grab-get': ('Arripere', None),
    'c1-sweet-great': ('Optimus', None),
    'c1-eloquent': ('Facundus', None),
    'c1-poignant': ('Commovens', None),
    'c1-vivid': ('Vividus', None),
    'c1-lucid': ('Lucidus', None),
    'c1-sublime': ('Sublimis', None),
    'c1-exquisite': ('Exquisitus', None),
    'c1-serene': ('Serenus', None),
    'c1-somber': ('Maestus', None),
    'c1-bleak': ('Desolatus', None),
    'c1-grim': ('Trux', None),
    'c1-austere': ('Austerus', None),
    'c1-opulent': ('Opulentus', None),
    'c1-lavish': ('Sumptuosus', None),
    'c1-meager': ('Exiguus', None),
    'c1-scarce': ('Rarus', None),
    'c1-abundant': ('Abundans', None),
    'c1-pristine': ('Incorruptus', None),
    'c1-dilapidated': ('Ruinosus', None),
    'c1-quaint': ('Lepidus', None),
    'c1-picturesque': ('Amoenus', None),
    'c1-ominous': ('Ominosus', None),
    'c1-eerie': ('Horridus', None),
    'c1-uncanny': ('Mirus', None),
    'c1-whimsical': ('Iocosus', None),
    'c1-wistful': ('Desiderans', None),
    'c1-fleeting': ('Fugax', None),
    'c1-enduring': ('Perennis', None),
    'c1-ubiquitous': ('Ubiquitarius', None),
    'c1-elusive': ('Evanidus', None),
    'c1-tangible': ('Palpabilis', None),
    'c1-meticulous': ('Accuratus', None),
    'c1-conscientious': ('Religiosus', None),
    'c1-diligent': ('Diligens', None),
    'c1-pragmatic': ('Pragmaticus', None),
    'c1-cynical': ('Cynicus', None),
    'c1-skeptical': ('Scepticus', None),
    'c1-gullible': ('Credulus', None),
    'c1-smug': ('Complacens', None),
    'c1-aloof': ('Remotus', None),
    'c1-candid': ('Candidus', None),
    'c1-tactless': ('Inurbanus', None),
    'c1-assertive': ('Confidens', None),
    'c1-submissive': ('Submissus', None),
    'c1-vindictive': ('Vindex', None),
    'c1-magnanimous': ('Magnanimus', None),
    'c1-benevolent': ('Benevolus', None),
    'c1-malicious': ('Malevolus', None),
    'c1-frugal': ('Frugi', None),
    'c1-extravagant': ('Prodigus', None),
    'c1-impulsive': ('Praeceps', None),
    'c1-spontaneous': ('Spontaneus', None),
    'c1-calculating': ('Callidus', None),
    'c1-eccentric': ('Excentricus', None),
    'c1-unconventional': ('Insolitus', None),
    'c1-sophisticated': ('Urbanus', None),
    'c1-witty': ('Facetus', None),
    'c1-sarcastic': ('Mordax', None),
    'c1-charismatic': ('Gratiosus', None),
    'c1-condescending': ('Superbus', None),
    'c1-pretentious': ('Ostentosus', None),
    'c1-empire': ('Imperium', None),
    'c1-colony': ('Colonia', None),
    'c1-revolution': ('Res novae', None),
    'c1-uprising': ('Seditio', None),
    'c1-dictatorship': ('Dictatura', None),
    'c1-democracy': ('Democratia', None),
    'c1-monarchy': ('Monarchia', None),
    'c1-republic': ('Res publica', None),
    'c1-regime': ('Regimen', None),
    'c1-treaty': ('Foedus', None),
    'c1-alliance': ('Societas', None),
    'c1-invasion': ('Incursio', None),
    'c1-occupation-military': ('Occupatio', None),
    'c1-independence': ('Independentia', None),
    'c1-sovereignty': ('Maiestas', None),
    'c1-civil-war': ('Bellum civile', None),
    'c1-ceasefire': ('Indutiae', None),
    'c1-refugee': ('Profugus', None),
    'c1-asylum': ('Asylum', None),
    'c1-exile': ('Exilium', None),
    'c1-dynasty': ('Dynastia', None),
    'c1-heir': ('Heres', None),
    'c1-coup': ('Perduellio', None),
    'c1-sanctions': ('Sanctio', None),
    'c1-diplomacy': ('Diplomatia', None),
    'c1-ambassador': ('Legatus', None),
    'c1-embassy': ('Legatio', None),
    'c1-summit-meeting': ('Congressus principum', None),
    'c1-constitution': ('Constitutio', None),
    'c1-amendment': ('Emendatio', None),
    'c1-bottom-line': ('Summa summarum', None),
    'c1-ballpark-figure': ('Numerus aestimativus', None),
    'c1-to-touch-base': ('Colloqui', None),
    'c1-to-circle-back': ('Redire', None),
    'c1-bandwidth-capacity': ('Facultas', None),
    'c1-to-leverage': ('Adhibere', None),
    'c1-synergy': ('Synergia', None),
    'c1-to-scale-up': ('Augere', None),
    'c1-to-pivot': ('Vertere', None),
    'c1-to-onboard': ('Incorporare', None),
    'c1-to-roll-out': ('Proponere', None),
    'c1-to-ramp-up': ('Amplificare', None),
    'c1-to-wind-down': ('Remittere', None),
    'c1-to-cut-corners': ('Operam parcere', None),
    'c1-red-tape': ('Ambages administrativae', None),
    'c1-to-go-the-extra-mile': ('Ultra officium contendere', None),
    'c1-on-the-same-page': ('Idem sentire', None),
    'c1-to-keep-in-the-loop': ('Certiorem facere', None),
    'c1-to-drop-the-ball': ('Officio deesse', None),
    'c1-to-think-outside-the-box': ('Nova excogitare', None),
    'c1-win-win': ('Utrique utilis', None),
    'c1-game-changer': ('Rerum conversio', None),
    'c1-low-hanging-fruit': ('Fructus facilis', None),
    'c1-deliverable': ('Praestandum', None),
    'c1-return-on-investment': ('Fructus impensae', None),
    'c1-to-sign-off-on': ('Approbare', None),
    'c1-to-run-something-by-someone': ('Consulere', None),
    'c1-stakeholder-buy-in': ('Consensus partium', None),
    'c1-back-to-the-drawing-board': ('Ab integro incipere', None),
    'c1-take-it-offline': ('Seorsum tractare', None),
    'c1-over-the-moon': ('Laetissimus', None),
    'c1-down-in-the-dumps': ('Tristissimus', None),
    'c1-on-edge': ('Anxius', None),
    'c1-fed-up': ('Pertaesus', None),
    'c1-at-a-loss': ('Haesitans', None),
    'c1-in-two-minds': ('Anceps', None),
    'c1-under-the-weather': ('Aegrotus', None),
    'c1-taken-aback': ('Attonitus', None),
    'c1-blown-away': ('Obstupefactus', None),
    'c1-torn-between': ('Distractus', None),
    'c1-beside-oneself': ('Amens', None),
    'c1-heartbroken': ('Corde fractus', None),
    'c1-on-the-fence': ('Dubius', None),
    'c1-laid-back': ('Remissus', None),
    'c1-uptight': ('Rigidus', None),
    'c1-sick-and-tired': ('Prorsus pertaesus', None),
    'c1-in-a-rut': ('Torpens', None),
    'c1-head-over-heels': ('Amore perditus', None),
    'c1-cold-feet': ('Trepidatio', None),
    'c1-second-thoughts': ('Dubitatio', None),
    'c1-a-weight-off-my-shoulders': ('Onere levatus', None),
    'c1-butterflies-in-my-stomach': ('Sollicitudo praecordiorum', None),
    'c1-a-lump-in-my-throat': ('Nodus in gutture', None),
    'c1-goosebumps': ('Horripilatio', None),
    'c1-speechless-with-joy': ('Gaudio elinguis', None),
    'c1-out-of-sorts': ('Indispositus', None),
    'c1-keyed-up': ('Excitatus', None),
    'c1-wound-up': ('Commotus', None),
    'c1-mixed-feelings': ('Affectus mixti', None),
    'c1-at-peace': ('Tranquillus', None),
    'c1-bureaucracy': ('Burocratia', None),
    'c1-paperwork': ('Chartae', None),
    'c1-to-file-documents': ('Deponere', None),
    'c1-applicant': ('Petitor', None),
    'c1-eligible': ('Idoneus', None),
    'c1-to-qualify': ('Condiciones implere', None),
    'c1-prerequisite': ('Requisitum', None),
    'c1-clause': ('Clausula', None),
    'c1-compliance': ('Obtemperantia', None),
    'c1-regulation': ('Ordinatio', None),
    'c1-license-permit': ('Licentia', None),
    'c1-to-authorize': ('Auctorare', None),
    'c1-notary': ('Notarius', None),
    'c1-affidavit': ('Testimonium iuratum', None),
    'c1-deed': ('Instrumentum', None),
    'c1-title-property': ('Dominium', None),
    'c1-lien': ('Pignus', None),
    'c1-easement': ('Servitus', None),
    'c1-appraisal': ('Aestimatio', None),
    'c1-closing-real-estate': ('Emptionis confirmatio', None),
    'c1-escrow': ('Sequestrum', None),
    'c1-commission-fee': ('Merces', None),
    'c1-listing-property': ('Nuntiatio venalis', None),
    'c1-counteroffer': ('Oblatio contraria', None),
    'c1-contingency': ('Condicio', None),
    'c1-zoning-variance': ('Dispensatio', None),
    'c1-deadline-filing': ('Dies praestitutus', None),
    'c1-certified-copy': ('Exemplum authenticum', None),
    'c1-jurisdiction': ('Iurisdictio', None),
    'c1-liability': ('Obligatio', None),
    'c1-galaxy': ('Galaxia', None),
    'c1-universe': ('Universum', None),
    'c1-black-hole': ('Foramen nigrum', None),
    'c1-telescope': ('Telescopium', None),
    'c1-asteroid': ('Asteroides', None),
    'c1-eclipse': ('Eclipsis', None),
    'c1-constellation': ('Constellatio', None),
    'c1-particle': ('Particula', None),
    'c1-radiation': ('Radiatio', None),
    'c1-electron': ('Electronum', None),
    'c1-isotope': ('Isotopum', None),
    'c1-nuclear-fusion': ('Fusio nuclearis', None),
    'c1-magnetic-field': ('Campus magneticus', None),
    'c1-friction': ('Frictio', None),
    'c1-velocity': ('Velocitas', None),
    'c1-acceleration': ('Acceleratio', None),
    'c1-momentum': ('Momentum', None),
    'c1-inertia': ('Inertia', None),
    'c1-density': ('Densitas', None),
    'c1-pressure-physics': ('Pressio', None),
    'c1-vacuum': ('Vacuum', None),
    'c1-wavelength': ('Longitudo undae', None),
    'c1-frequency-physics': ('Frequentia', None),
    'c1-spectrum': ('Spectrum', None),
    'c1-photosynthesis': ('Photosynthesis', None),
    'c1-enzyme': ('Enzyma', None),
    'c1-hormone': ('Hormonum', None),
    'c1-metabolism': ('Metabolismus', None),
    'c1-mutation': ('Mutatio', None),
    'c1-organism': ('Organismus', None),
    'c1-to-allege': ('Allegare', None),
    'c1-to-allude': ('Alludere', None),
    'c1-to-ascertain': ('Comperire', None),
    'c1-to-bolster': ('Fulcire', None),
    'c1-to-circumvent': ('Circumvenire', None),
    'c1-to-coerce': ('Cogere', None),
    'c1-to-condone': ('Ignoscere', None),
    'c1-to-consolidate': ('Consolidare', None),
    'c1-to-curb': ('Frenare', None),
    'c1-to-deter': ('Deterrere', None),
    'c1-to-diminish': ('Imminuere', None),
    'c1-to-disclose': ('Patefacere', None),
    'c1-to-disrupt': ('Perturbare', None),
    'c1-to-divert': ('Avertere', None),
    'c1-to-elicit': ('Elicere', None),
    'c1-to-endorse': ('Comprobare', None),
    'c1-to-entail': ('Importare', None),
    'c1-to-eradicate': ('Eradicare', None),
    'c1-to-exacerbate': ('Exacerbare', None),
    'c1-to-exemplify': ('Illustrare', None),
    'c1-to-foster': ('Fovere', None),
    'c1-to-hinder': ('Obstare', None),
    'c1-to-impede': ('Impedire', None),
    'c1-to-instigate': ('Instigare', None),
    'c1-to-mitigate': ('Mitigare', None),
    'c1-to-nurture': ('Alere', None),
    'c1-to-omit': ('Omittere', None),
    'c1-to-precede': ('Praecedere', None),
    'c1-to-preclude': ('Praecludere', None),
    'c1-to-prompt': ('Incitare', None),
    'c1-to-refrain': ('Abstinere', None),
    'c1-to-relinquish': ('Relinquere', None),
    'c1-to-render': ('Reddere', None),
    'c1-to-scrutinize': ('Scrutari', None),
    'c1-to-stipulate': ('Stipulari', None),
    'c1-to-substantiate': ('Confirmare', None),
    'c1-to-thrive': ('Vigere', None),
    'c1-to-undermine': ('Subruere', None),
    'c1-to-uphold': ('Tueri', None),
    'c1-to-waive': ('Renuntiare', None),
    'c1-to-yield': ('Ferre', None),
    'c1-to-abolish': ('Abolere', None),
    'c1-to-accommodate': ('Accommodare', None),
    'c1-to-adhere': ('Inhaerere', None),
    'c1-to-attain': ('Adipisci', None),
    'c1-to-compel': ('Compellere', None),
    'c1-to-confine': ('Includere', None),
    'c1-to-contemplate': ('Contemplari', None),
    'c1-to-depict': ('Depingere', None),
    'c1-to-dispel': ('Dispellere', None),
    'c1-to-embody': ('Exprimere', None),
    'c1-to-evoke': ('Evocare', None),
    'c1-to-forge': ('Fabricari', None),
    'c1-to-grasp': ('Comprehendere', None),
    'c1-to-infringe': ('Violare', None),
    'c1-to-overturn': ('Evertere', None),
    'c1-to-plead': ('Causam agere', None),
    'c1-to-reconcile-ideas': ('Conciliare', None),
    'c1-to-surpass': ('Excedere', None),
    'c1-to-unveil': ('Revelare', None),
    'c1-albeit': ('Quamquam', None),
    'c1-notwithstanding': ('Nihilominus', None),
    'c1-insofar-as': ('Quatenus', None),
    'c1-whereby': ('Per quod', None),
    'c1-hereby': ('Hac ipsa re', None),
    'c1-thereby': ('Eo', None),
    'c1-hence': ('Hinc', None),
    'c1-thus': ('Ita', None),
    'c1-henceforth': ('Posthac', None),
    'c1-likewise': ('Item', None),
    'c1-conversely': ('E contrario', None),
    'c1-namely': ('Scilicet', None),
    'c1-in-lieu-of': ('Vice', None),
    'c1-in-light-of': ('Pro ratione', None),
    'c1-in-view-of': ('Habita ratione', None),
    'c1-by-virtue-of': ('Vi', None),
    'c1-on-account-of': ('Propter', None),
    'c1-with-a-view-to': ('Eo consilio ut', None),
    'c1-provided-that': ('Dummodo', None),
    'c1-granted': ('Sane', None),
    'c1-admittedly': ('Fatendum est', None),
    'c1-arguably': ('Non sine ratione', None),
    'c1-presumably': ('Ut videtur', None),
    'c1-allegedly': ('Ut aiunt', None),
    'c1-ostensibly': ('Specie', None),
    'c1-undoubtedly': ('Proculdubio', None),
    'c1-invariably': ('Constanter', None),
    'c1-nevertheless-formal': ('Attamen', None),
    'c1-to-the-extent-that': ('Eatenus ut', None),
    'c1-for-all-intents-and-purposes': ('Reapse', None),
    'c1-sommelier': ('Vinorum peritus', None),
    'c1-vintage-wine': ('Vindemia', None),
    'c1-aroma': ('Aroma', None),
    'c1-palate': ('Palatum', None),
    'c1-aftertaste': ('Sapor posterior', None),
    'c1-full-bodied': ('Corpore plenus', None),
    'c1-dry-wine': ('Siccus', None),
    'c1-sparkling': ('Spumans', None),
    'c1-brew': ('Potio', None),
    'c1-roast-coffee': ('Tostura', None),
    'c1-espresso': ('Espresso', None),
    'c1-decaf': ('Excaffeinatus', None),
    'c1-barista': ('Barista', None),
    'c1-tasting-menu': ('Index degustationis', None),
    'c1-pairing': ('Consociatio', None),
    'c1-a-la-carte': ('Singillatim', None),
    'c1-garnish': ('Ornatus', None),
    'c1-drizzle-of-oil': ('Stilla', None),
    'c1-reduction-sauce': ('Decoctio', None),
    'c1-glaze': ('Illitio', None),
    'c1-umami': ('Umami', None),
    'c1-zest': ('Ramentum', None),
    'c1-to-caramelize': ('Caramelizare', None),
    'c1-to-braise': ('Lento igne coquere', None),
    'c1-to-poach': ('Elixare', None),
    'c1-al-dente': ('Firmus sub dente', None),
    'c1-medium-rare': ('Semicoctus', None),
    'c1-well-done': ('Percoctus', None),
    'c1-signature-dish': ('Ferculum insigne', None),
    'c1-chefs-recommendation': ('Coqui commendatio', None),
    'c1-floor-plan': ('Forma aedium', None),
    'c1-open-plan': ('Spatium apertum', None),
    'c1-layout': ('Dispositio', None),
    'c1-fixture': ('Instrumentum fixum', None),
    'c1-cabinetry': ('Armaria', None),
    'c1-countertop': ('Mensa culinaria', None),
    'c1-backsplash': ('Tegumentum parietis', None),
    'c1-grout': ('Arenatum', None),
    'c1-hardwood-floor': ('Pavimentum ligneum', None),
    'c1-laminate': ('Lamina composita', None),
    'c1-molding-trim': ('Limbus', None),
    'c1-baseboard': ('Crepido', None),
    'c1-crown-molding': ('Corona', None),
    'c1-sconce': ('Lychnus parietinus', None),
    'c1-pendant-light': ('Lucerna pensilis', None),
    'c1-recessed-lighting': ('Lumina inserta', None),
    'c1-dimmer': ('Moderator luminis', None),
    'c1-vent': ('Spiramentum', None),
    'c1-duct': ('Canalis', None),
    'c1-hvac': ('Systema aeris temperandi', None),
    'c1-sump-pump': ('Antlia aquae', None),
    'c1-water-heater': ('Calefactor aquae', None),
    'c1-circuit-breaker': ('Disiunctor electricus', None),
    'c1-load-bearing-wall': ('Paries onus sustinens', None),
    'c1-joist': ('Tignum', None),
    'c1-stud-wall': ('Asser', None),
    'c1-subfloor': ('Pavimentum inferius', None),
    'c1-caulk': ('Obturamentum', None),
    'c1-primer-paint': ('Illitio prima', None),
    'c1-punch-list': ('Index emendandorum', None),
    'c1-change-order': ('Mandatum mutationis', None),
    'c1-scope-of-work': ('Ambitus operis', None),
    'c1-rapport': ('Concordia', None),
    'c1-chemistry-between-people': ('Sympathia', None),
    'c1-affinity': ('Affinitas', None),
    'c1-estranged': ('Alienatus', None),
    'c1-reconciliation': ('Reconciliatio', None),
    'c1-to-confide': ('Confidere', None),
    'c1-confidant': ('Conscius', None),
    'c1-to-fall-out': ('Dissidere', None),
    'c1-to-patch-things-up': ('Reconciliari', None),
    'c1-to-drift-apart': ('Disiungi', None),
    'c1-to-hit-it-off': ('Concordare', None),
    'c1-to-have-a-soft-spot-for': ('Peculiariter amare', None),
    'c1-to-hold-a-grudge': ('Odium fovere', None),
    'c1-to-bury-the-hatchet': ('Simultates deponere', None),
    'c1-to-make-amends': ('Satisfacere', None),
    'c1-to-take-for-granted': ('Pro certo habere', None),
    'c1-to-lean-on': ('Niti', None),
    'c1-to-stick-up-for': ('Defendere', None),
    'c1-to-look-out-for': ('Providere', None),
    'c1-to-see-eye-to-eye': ('Consentire', None),
    'c1-to-get-on-someones-nerves': ('Vexare', None),
    'c1-to-give-the-benefit-of-the-doubt': ('In meliorem partem interpretari', None),
    'c1-to-read-between-the-lines': ('Subaudire', None),
    'c1-to-beat-around-the-bush': ('Circuitione uti', None),
    'c1-to-get-to-the-point': ('Ad rem venire', None),
    'c1-to-keep-someone-at-arms-length': ('Procul habere', None),
    'c1-to-go-behind-someones-back': ('Clam agere', None),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('Animum aperte ostendere', None),
    'c1-tactfully': ('Comiter', None),
    'c1-passive-aggressive': ('Dissimulanter adversus', None),
    'c1-mediocre': ('Mediocris', None),
    'c1-subpar': ('Infra mediocritatem', None),
    'c1-top-notch': ('Praestantissimus', None),
    'c1-first-rate': ('Primae classis', None),
    'c1-second-rate': ('Secundae classis', None),
    'c1-state-of-the-art': ('Novissimus', None),
    'c1-cutting-edge': ('In acie prima', None),
    'c1-run-of-the-mill': ('Vulgaris', None),
    'c1-exceptional': ('Eximius', None),
    'c1-flawless': ('Vitio carens', None),
    'c1-impeccable': ('Impeccabilis', None),
    'c1-shoddy': ('Vilis', None),
    'c1-sloppy': ('Neglegens', None),
    'c1-half-baked': ('Imperfectus', None),
    'c1-polished': ('Politus', None),
    'c1-crude': ('Rudis', None),
    'c1-rudimentary': ('Rudimentarius', None),
    'c1-intricate': ('Perplexus', None),
    'c1-convoluted': ('Involutus', None),
    'c1-user-friendly': ('Usui facilis', None),
    'c1-foolproof': ('Ab errore tutus', None),
    'c1-robust': ('Robustus', None),
    'c1-seamless': ('Continuus', None),
    'c1-glitchy': ('Vitiosus', None),
    'c1-clunky': ('Inhabilis', None),
    'c1-sleek': ('Nitidus', None),
    'c1-bulky': ('Vastus', None),
    'c1-compact': ('Compactus', None),
    'c1-flimsy': ('Tenuis', None),
    'c1-durable': ('Durabilis', None),
    'c1-to-mumble': ('Submurmurare', None),
    'c1-to-mutter': ('Mussitare', None),
    'c1-to-stutter': ('Balbutire', None),
    'c1-to-slur': ('Confuse loqui', None),
    'c1-to-ramble': ('Digredi', None),
    'c1-to-rant': ('Vociferari', None),
    'c1-to-grumble': ('Mussare', None),
    'c1-to-whine': ('Queri', None),
    'c1-to-snap-at-someone': ('Acerbe respondere', None),
    'c1-hoarse': ('Raucus', None),
    'c1-raspy': ('Asper', None),
    'c1-monotone': ('Aequabilis', None),
    'c1-shrill': ('Acutus', None),
    'c1-deafening': ('Aures obtundens', None),
    'c1-muffled': ('Suppressus', None),
    'c1-faint-sound': ('Exilis', None),
    'c1-to-hum': ('Susurrare', None),
    'c1-to-chant': ('Canere', None),
    'c1-to-murmur': ('Murmurare', None),
    'c1-to-bellow': ('Mugire', None),
    'c1-to-chuckle': ('Subridere', None),
    'c1-to-giggle': ('Cachinnare', None),
    'c1-to-snicker': ('Furtim ridere', None),
    'c1-to-sob': ('Singultire', None),
    'c1-to-wail': ('Eiulare', None),
    'c1-to-howl': ('Ululare', None),
    'c1-to-shriek': ('Stridere', None),
    'c1-to-gasp': ('Anhelare', None),
    'c1-pitch-voice': ('Tonus', None),
    'c1-accent-stress': ('Accentus', None),
    'c1-asset': ('Bonum', None),
    'c1-liability-finance': ('Passivum', None),
    'c1-equity': ('Capitale proprium', None),
    'c1-portfolio': ('Fasciculus', None),
    'c1-dividend': ('Dividendum', None),
    'c1-bond-finance': ('Syngrapha', None),
    'c1-hedge': ('Cautio', None),
    'c1-liquidity': ('Liquiditas', None),
    'c1-collateral': ('Vadimonium', None),
    'c1-default-loan': ('Solutionis defectus', None),
    'c1-foreclosure': ('Praedii ademptio', None),
    'c1-appreciation-value': ('Pretii augmentum', None),
    'c1-depreciation': ('Deminutio pretii', None),
    'c1-capital-gains': ('Lucrum capitale', None),
    'c1-write-off': ('Abolitio debiti', None),
    'c1-overhead': ('Impensae communes', None),
    'c1-payroll': ('Ratio stipendiorum', None),
    'c1-gross-before-deductions': ('Summa integra', None),
    'c1-net': ('Purum', None),
    'c1-deductible': ('Deducibilis', None),
    'c1-exemption': ('Immunitas', None),
    'c1-audit': ('Recognitio rationum', None),
    'c1-ledger': ('Codex rationarius', None),
    'c1-bookkeeping': ('Rationum administratio', None),
    'c1-break-even': ('Punctum aequilibrii', None),
    'c1-turnover': ('Commercii volumen', None),
    'c1-markup': ('Pretii incrementum', None),
    'c1-cash-reserve': ('Reservae pecuniariae', None),
    'c1-venture-capital': ('Capitale periculosum', None),
    'c1-fiscal-year': ('Annus rationarius', None),
    'c1-expedition': ('Expeditio', None),
    'c1-pilgrimage': ('Peregrinatio', None),
    'c1-getaway': ('Excursio', None),
    'c1-sabbatical': ('Annus vacationis', None),
    'c1-nomad': ('Nomas', None),
    'c1-expatriate': ('Extorris', None),
    'c1-immigrant': ('Advena', None),
    'c1-to-relocate': ('Commigrare', None),
    'c1-to-settle-down': ('Consedere', None),
    'c1-culture-shock': ('Perturbatio culturalis', None),
    'c1-to-assimilate': ('Assimilari', None),
    'c1-bilingual': ('Bilinguis', None),
    'c1-multilingual': ('Multilinguis', None),
    'c1-mother-tongue': ('Lingua materna', None),
    'c1-dialect': ('Dialectus', None),
    'c1-slang': ('Sermo plebeius', None),
    'c1-jargon': ('Sermo technicus', None),
    'c1-register-language': ('Genus dicendi', None),
    'c1-colloquial': ('Familiaris', None),
    'c1-fluency': ('Volubilitas', None),
    'c1-proficiency': ('Peritia', None),
    'c1-to-master': ('Perdiscere', None),
    'c1-immersion': ('Immersio', None),
    'c1-intonation': ('Modulatio', None),
    'c1-to-mispronounce': ('Prave pronuntiare', None),
    'c1-false-friend': ('Amicus falsus', None),
    'c1-cognate': ('Cognatus', None),
    'c1-loanword': ('Vocabulum mutuatum', None),
    'c1-literacy': ('Litterarum peritia', None),
    'c1-interpreter': ('Interpres', None),
    'c1-latency': ('Mora', None),
    'c1-server': ('Servitor', None),
    'c1-cloud-computing': ('Computatio nebularis', None),
    'c1-backup-data': ('Exemplum reservatum', None),
    'c1-firewall': ('Murus igneus', None),
    'c1-malware': ('Programma noxium', None),
    'c1-phishing': ('Piscatio electronica', None),
    'c1-two-factor-authentication': ('Confirmatio duplex', None),
    'c1-biometric': ('Biometricus', None),
    'c1-open-source': ('Fons apertus', None),
    'c1-interface': ('Interfacies', None),
    'c1-plugin': ('Additamentum', None),
    'c1-patch-software': ('Sarcimentum', None),
    'c1-to-deploy': ('Explicare', None),
    'c1-release-version': ('Editio', None),
    'c1-beta': ('Versio experimentalis', None),
    'c1-blockchain': ('Catena frustorum', None),
    'c1-cryptocurrency': ('Pecunia cryptographica', None),
    'c1-machine-learning': ('Disciplina machinalis', None),
    'c1-neural-network': ('Rete neurale', None),
    'c1-dataset': ('Congeries datorum', None),
    'c1-drone': ('Automatum volans', None),
    'c1-sensor': ('Sensor', None),
    'c1-augmented-reality': ('Realitas aucta', None),
    'c1-wearable': ('Res gestabilis', None),
    'c1-smart-home': ('Domus sollers', None),
    'c1-bandwidth-network': ('Latitudo transmissionis', None),
    'c1-outage': ('Interruptio', None),
    'c1-scalability': ('Amplificabilitas', None),
    'c1-encryption-key': ('Clavis cryptographica', None),
    'c1-cinematography': ('Cinematographia', None),
    'c1-close-up': ('Imago propinqua', None),
    'c1-wide-shot': ('Imago lata', None),
    'c1-montage': ('Contextus imaginum', None),
    'c1-flashback': ('Reminiscentia', None),
    'c1-voice-over': ('Vox superimposita', None),
    'c1-subplot': ('Fabula secundaria', None),
    'c1-protagonist': ('Protagonistes', None),
    'c1-antagonist': ('Adversarius', None),
    'c1-cliffhanger': ('Suspensio', None),
    'c1-plot-twist': ('Conversio fabulae', None),
    'c1-foreshadowing': ('Praesagium', None),
    'c1-pacing': ('Modus procedendi', None),
    'c1-casting': ('Electio actorum', None),
    'c1-cameo': ('Apparitio brevis', None),
    'c1-sequel': ('Continuatio', None),
    'c1-prequel': ('Antecedaneum', None),
    'c1-reboot': ('Renovatio', None),
    'c1-box-office': ('Reditus theatrales', None),
    'c1-blockbuster': ('Ingens successus', None),
    'c1-indie-film': ('Cinema independens', None),
    'c1-cult-classic': ('Opus sectae carum', None),
    'c1-critically-acclaimed': ('A censoribus laudatus', None),
    'c1-dubbed': ('Alia voce redditus', None),
    'c1-subtitled': ('Subscriptus', None),
    'c1-screening': ('Exhibitio', None),
    'c1-pilot-episode': ('Pars experimentalis prima', None),
    'c1-season-finale': ('Ultima pars anni scaenici', None),
    'c1-showrunner': ('Rector fabulae', None),
    'c1-storyboard': ('Tabula fabulae', None),
    'c1-on-the-mend': ('Convalescens', None),
    'c1-run-down-exhausted': ('Defatigatus', None),
    'c1-in-good-shape': ('Bene valens', None),
    'c1-out-of-shape': ('Corpore male affectus', None),
    'c1-a-clean-bill-of-health': ('Testimonium sanitatis', None),
    'c1-to-pull-a-muscle': ('Nervum convellere', None),
    'c1-wear-and-tear': ('Usura', None),
    'c1-to-nod-off': ('Obdormiscere', None),
    'c1-to-sleep-like-a-log': ('Graviter dormire', None),
    'c1-to-toss-and-turn': ('In lecto se vertere', None),
    'c1-over-the-counter': ('Sine praescriptione', None),
    'c1-second-opinion': ('Alterum consilium', None),
    'c1-bedside-manner': ('Comitas medici', None),
    'c1-to-be-discharged': ('Dimitti', None),
    'c1-to-be-admitted-hospital': ('Recipi in valetudinarium', None),
    'c1-outpatient': ('Aeger ambulatorius', None),
    'c1-follow-up-appointment': ('Consultatio subsequens', None),
    'c1-referral': ('Delegatio ad specialem', None),
    'c1-to-take-a-turn-for-the-worse': ('In peius vergere', None),
    'c1-to-black-out': ('Animo linqui', None),
    'c1-under-the-knife': ('Sub ferro chirurgico', None),
    'c1-slipped-disc': ('Discus prolapsus', None),
    'c1-jet-lagged': ('Fessus ex volatu longo', None),
    'c1-on-medication': ('Medicamentis utens', None),
    'c1-immune-to': ('Immunis', None),
    'c1-prone-to': ('Obnoxius', None),
    'c1-relapse': ('Recidiva', None),
    'c1-remission': ('Remissio', None),
    'c1-a-no-brainer': ('Res facillima', None),
    'c1-a-long-shot': ('Spes tenuis', None),
    'c1-a-close-call': ('Angustiae vix evasae', None),
    'c1-a-wake-up-call': ('Admonitio', None),
    'c1-a-catch-hidden-problem': ('Dolus latens', None),
    'c1-the-upside': ('Commodum', None),
    'c1-the-downside': ('Detrimentum', None),
    'c1-a-trade-off': ('Permutatio', None),
    'c1-a-loophole': ('Rima iuris', None),
    'c1-a-setback': ('Repulsa', None),
    'c1-a-blessing-in-disguise': ('Bonum sub malo latens', None),
    'c1-the-tip-of-the-iceberg': ('Extrema pars molis glacialis', None),
    'c1-the-last-straw': ('Gutta quae vas superfundit', None),
    'c1-a-double-edged-sword': ('Gladius anceps', None),
    'c1-the-elephant-in-the-room': ('Elephantus in cubiculo', None),
    'c1-a-grey-area': ('Regio ambigua', None),
    'c1-a-slippery-slope': ('Clivus lubricus', None),
    'c1-a-vicious-circle': ('Circulus vitiosus', None),
    'c1-a-stepping-stone': ('Gradus ad maiora', None),
    'c1-a-rule-of-thumb': ('Regula generalis', None),
    'c1-a-rain-check': ('Dilatio', None),
    'c1-a-heads-up': ('Praemonitio', None),
    'c1-a-hunch': ('Suspicio', None),
    'c1-a-knack': ('Dexteritas', None),
    'c1-a-pet-peeve': ('Molestia peculiaris', None),
    'c1-a-red-flag': ('Signum periculi', None),
    'c1-a-silver-lining': ('Spes in adversis', None),
    'c1-a-drop-in-the-ocean': ('Gutta in mari', None),
    'c1-a-piece-of-cake': ('Ludus', None),
    'c1-a-far-cry-from': ('Longe abest ab', None),
    'c1-a-handful': ('Manipulus', None),
    'c1-a-fair-amount': ('Modus satis magnus', None),
    'c1-the-lions-share': ('Pars leonina', None),
    'c1-a-fraction': ('Fragmentum', None),
    'c1-the-vast-majority': ('Maxima pars', None),
    'c1-next-to-nothing': ('Prope nihil', None),
    'c1-a-great-deal': ('Multum', None),
    'c1-at-most': ('Ad summum', None),
    'c1-at-best': ('Quam optime', None),
    'c1-at-worst': ('Quam pessime', None),
    'c1-in-bulk': ('Universim', None),
    'c1-on-average': ('Ut plurimum', None),
    'c1-per-capita': ('Per capita', None),
    'c1-give-or-take': ('Fere', None),
    'c1-a-rough-estimate': ('Coniectura', None),
    'c1-a-round-number': ('Numerus rotundus', None),
    'c1-the-odds': ('Verisimilitudo', None),
    'c1-by-a-narrow-margin': ('Exiguo discrimine', None),
    'c1-by-a-landslide': ('Longo intervallo', None),
    'c1-one-in-ten': ('Unus e decem', None),
    'c1-twofold': ('Duplex', None),
    'c1-exponentially': ('Exponentialiter', None),
    'c1-marginally': ('Paulum', None),
    'c1-negligible': ('Neglegendus', None),
    'c1-sizable': ('Amplus', None),
    'c1-umpteen': ('Innumerabiles', None),
    'c1-in-the-region-of': ('Circiter', None),
    'c1-odds-and-ends': ('Reliquiae', None),
    'c1-mentor': ('Praeceptor', None),
    'c1-protege': ('Alumnus', None),
    'c1-intern': ('Tiro', None),
    'c1-veteran-experienced': ('Veteranus', None),
    'c1-rookie': ('Novicius', None),
    'c1-whiz': ('Artifex', None),
    'c1-workaholic': ('Laboris addictus', None),
    'c1-slacker': ('Ignavus', None),
    'c1-know-it-all': ('Omniscius', None),
    'c1-yes-man': ('Assentator', None),
    'c1-gatekeeper': ('Ianitor', None),
    'c1-middleman': ('Sequester', None),
    'c1-liaison': ('Internuntius', None),
    'c1-spokesperson': ('Praeco', None),
    'c1-figurehead': ('Simulacrum', None),
    'c1-frontrunner': ('Antecursor', None),
    'c1-underdog': ('Deterior', None),
    'c1-dark-horse': ('Latens victor', None),
    'c1-wildcard': ('Alea', None),
    'c1-heavyweight': ('Praepotens', None),
    'c1-newcomer': ('Adventicius', None),
    'c1-insider': ('Intimus', None),
    'c1-outsider': ('Alienus', None),
    'c1-consultant': ('Consiliarius', None),
    'c1-subcontractor': ('Redemptor secundarius', None),
    'c1-headhunter': ('Venator ingeniorum', None),
    'c1-scapegoat': ('Hircus emissarius', None),
    'c1-go-getter': ('Strenuus', None),
    'c1-universal-healthcare': ('Sanitas omnibus provisa', None),
    'c1-minimum-wage': ('Merces minima', None),
    'c1-affordable-housing': ('Habitatio pretio moderato', None),
    'c1-surveillance': ('Observatio', None),
    'c1-privacy': ('Secretum', None),
    'c1-free-speech': ('Libertas dicendi', None),
    'c1-polarization': ('Divisio extrema', None),
    'c1-populism': ('Popularismus', None),
    'c1-nationalism': ('Nationalismus', None),
    'c1-globalization': ('Globalizatio', None),
    'c1-austerity': ('Parsimonia', None),
    'c1-welfare': ('Subsidium sociale', None),
    'c1-aging-population': ('Populus senescens', None),
    'c1-birth-rate': ('Natalitas', None),
    'c1-brain-drain': ('Ingeniorum fuga', None),
    'c1-gig-economy': ('Oeconomia opusculorum', None),
    'c1-job-displacement': ('Officiorum amissio', None),
    'c1-universal-basic-income': ('Reditus minimus universalis', None),
    'c1-carbon-tax': ('Vectigal carbonicum', None),
    'c1-nuclear-energy': ('Energia nuclearis', None),
    'c1-food-security': ('Securitas alimentaria', None),
    'c1-water-scarcity': ('Inopia aquae', None),
    'c1-urban-sprawl': ('Urbis diffusio', None),
    'c1-rent-control': ('Moderatio pensionum', None),
    'c1-public-transit-funding': ('Subsidium vehiculorum publicorum', None),
    'c1-data-protection': ('Tutela datorum', None),
    'c1-wealth-gap': ('Discrimen divitiarum', None),
    'c1-voter-turnout': ('Frequentia suffragatorum', None),
    'c1-bustling': ('Frequens', None),
    'c1-sleepy-town': ('Sopitus', None),
    'c1-vibrant': ('Vegetus', None),
    'c1-deserted': ('Desertus', None),
    'c1-packed': ('Confertus', None),
    'c1-cramped': ('Angustus', None),
    'c1-airy': ('Perflabilis', None),
    'c1-stuffy': ('Praeclusus', None),
    'c1-gloomy': ('Tenebrosus', None),
    'c1-dingy': ('Sordidus', None),
    'c1-shabby': ('Obsoletus', None),
    'c1-chic': ('Elegans', None),
    'c1-trendy': ('Moderno more probatus', None),
    'c1-upscale': ('Splendidus', None),
    'c1-seedy': ('Turpis', None),
    'c1-leafy': ('Frondosus', None),
    'c1-sprawling': ('Diffusus', None),
    'c1-walkable': ('Ambulabilis', None),
    'c1-secluded': ('Secretus', None),
    'c1-remote-place': ('Devius', None),
    'c1-touristy': ('Peregrinatoribus frequentatus', None),
    'c1-unspoiled': ('Intactus', None),
    'c1-well-kept': ('Bene cultus', None),
    'c1-overgrown': ('Vepribus obsitus', None),
    'c1-tucked-away': ('Reconditus', None),
    'c1-nestled': ('In recessu situs', None),
    'c1-lively': ('Alacer', None),
    'c1-run-down-place': ('Neglectus', None),
}
