# -*- coding: utf-8 -*-
# Diathìris, the tongue of Diathìr: written by tools/import_rodais.py from the Diathìris dictionary.
# The reading line is the pronunciation in IPA.
LANG = 'gr'
WORDS = {
    'c1-a-blessing-in-disguise': ('Beannachd am falach', 'ˈpɛn̪ˠəxk əm ˈfal̪ˠəx'),
    'c1-a-bummer': ('Rud tàmailteach', 'ˈr̪ˠut̪ ˈt̪ʰaːmɪlʲtʃəx'),
    'c1-a-catch-hidden-problem': ('Dubhan falaichte', 'ˈt̪uvan ˈfal̪ˠɪçtʃə'),
    'c1-a-clean-bill-of-health': ('Teisteanas slàinte glan', 'ˈtʃʰeʃtʃanəs ˈsl̪ˠaːɲtʃə ˈkl̪ˠan'),
    'c1-a-close-call': ('Teicheadh caol', 'ˈtʃʰeçəɣ ˈkʰɯːl̪ˠ'),
    'c1-a-double-edged-sword': ('Claidheamh dà-fhaobharach', 'ˈkʰl̪ˠa.əv ˈt̪aːˈɯːvəɾəx'),
    'c1-a-drop-in-the-ocean': ('Boinne sa chuan', 'ˈpɔɲə sə ˈxuən'),
    'c1-a-fair-amount': ('Uiread math', 'ˈuɾʲət̪ ˈma'),
    'c1-a-far-cry-from': ('Fada bho', 'ˈfat̪ə ˈvɔ'),
    'c1-a-fraction': ('Bloigh', 'ˈpl̪ˠɤi'),
    'c1-a-great-deal': ('Fìor mhòran', 'ˈfiəɾ ˈvɔːɾan'),
    'c1-a-grey-area': ('Raon glas', 'ˈr̪ˠɯːn ˈkl̪ˠas'),
    'c1-a-handful': ('Dòrlach', 'ˈt̪ɔːɾl̪ˠəx'),
    'c1-a-heads-up': ('Rabhadh', 'ˈr̪ˠavəɣ'),
    'c1-a-hunch': ('Faireachdainn', 'ˈfaɾʲəxkɪɲ'),
    'c1-a-knack': ('Liut', 'ˈʎuʰt̪'),
    'c1-a-la-carte': ('Taghadh-mèise', 'ˈt̪ʰa.əɣˈmeːʃə'),
    'c1-a-long-shot': ('Cothrom caol', 'ˈkʰɔɾəm ˈkʰɯːl̪ˠ'),
    'c1-a-loophole': ('Beàrn laghail', 'ˈpʲaːɾn ˈl̪ˠa.ɪlʲ'),
    'c1-a-lump-in-my-throat': ('Cnap nam amhaich', 'ˈkʰn̪ˠaʰp nəm ˈavɪç'),
    'c1-a-no-brainer': ('Rud gun cheist', 'ˈr̪ˠut̪ kən̪ˠ ˈçeʃtʃ'),
    'c1-a-pet-peeve': ('Rud a chuireas dragh orm', 'ˈr̪ˠut̪ ə ˈxuɾʲəs ˈt̪ɾa ˈɔɾɔm'),
    'c1-a-piece-of-cake': ("Cho furasta 's a ghabhas", 'ˈxɔ ˈfuɾəst̪ə s ə ˈɣavəs'),
    'c1-a-rain-check': ('Uair eile', 'ˈuəɾʲ ˈelʲə'),
    'c1-a-red-flag': ('Bratach dhearg', 'ˈpɾaʰt̪əx ˈjɛɾɛk'),
    'c1-a-rip-off': ('Robaireachd', 'ˈr̪ˠɔpɪɾʲəxk'),
    'c1-a-rough-estimate': ('Tuairmse gharbh', 'ˈt̪ʰuəɾʲmʃə ˈɣaɾav'),
    'c1-a-round-number': ('Àireamh chruinn', 'ˈaːɾʲəv ˈxɾuːiɲ'),
    'c1-a-rule-of-thumb': ('Riaghailt òrdaig', 'ˈr̪ˠiə.ɪlʲtʃ ˈɔːɾt̪ɪkʲ'),
    'c1-a-setback': ('Ceum air ais', 'ˈkʲʰiəm ˈɛɾʲ ˈaʃ'),
    'c1-a-silver-lining': ('Taobh soilleir', 'ˈt̪ʰɯːv ˈsɔʎɪɾʲ'),
    'c1-a-slippery-slope': ('Leathad sleamhainn', 'ˈʎɛ.ət̪ ˈʃlʲɛvɪɲ'),
    'c1-a-stepping-stone': ('Clach-cheum', 'ˈkʰl̪ˠaxˈçiəm'),
    'c1-a-trade-off': ('Co-rèiteachadh', 'kʰɔˈr̪ˠeːʰtʃəxəɣ'),
    'c1-a-vicious-circle': ('Cearcall olc', 'ˈkʲʰɛɾkəl̪ˠ ˈɔl̪ˠk'),
    'c1-a-wake-up-call': ('Clag-dùscaidh', 'ˈkʰl̪ˠakˈt̪uːski'),
    'c1-a-weight-off-my-shoulders': ('Eallach bhàrr mo ghuailnean', 'ˈɛl̪ˠəx ˈvaːr̪ˠ mə ˈɣuəlʲnʲan'),
    'c1-abstract-summary': ('Geàrr-iomradh', 'ˈkʲaːr̪ˠˈimɾəɣ'),
    'c1-abundant': ('Pailt', 'ˈpʰalʲtʃ'),
    'c1-acceleration': ('Luathachadh', 'ˈl̪ˠuə.əxəɣ'),
    'c1-accent-stress': ('Cudrom', 'ˈkʰut̪ɾəm'),
    'c1-admittedly': ('Feumar aideachadh', 'ˈfiəməɾ ˈatʃəxəɣ'),
    'c1-affidavit': ('Teisteanas fo mhionnan', 'ˈtʃʰeʃtʃanəs fə ˈvin̪ˠan'),
    'c1-affinity': ('Dàimh', 'ˈt̪aːv'),
    'c1-affordable-housing': ('Fàrdach-shaor', 'ˈfaːɾt̪əxˈhɯːɾ'),
    'c1-aftertaste': ('Iar-bhlas', 'ˈiəɾˈvl̪ˠas'),
    'c1-aging-population': ("Sluagh a' fàs nas sine", 'ˈsl̪ˠuə ə ˈfaːs ˈn̪ˠas ˈʃinʲə'),
    'c1-airtime': ('Uain-gutha', 'ˈuənʲˈku.ə'),
    'c1-airy': ('Àileach', 'ˈaːlʲəx'),
    'c1-al-dente': ('Le-greim', 'ˈʎeˈkɾʲeim'),
    'c1-albeit': ('Ged a', 'ˈkʲetʃ ə'),
    'c1-allegedly': ('A rèir aithris', 'ə ˈr̪ˠeːɾʲ ˈaɾʲɪʃ'),
    'c1-alliance': ('Caidreachas', 'ˈkʰatʃɾʲəxəs'),
    'c1-aloof': ("Fad' às", "ˈfat̪' ˈaːs"),
    'c1-ambassador': ('Toscaire', 'ˈt̪ʰɔskɪɾʲə'),
    'c1-amendment': ('Atharrachadh', 'ˈa.ər̪ˠəxəɣ'),
    'c1-anchor-news': ('Beul-naidheachd', 'ˈpiəl̪ˠˈn̪ˠa.əxk'),
    'c1-antagonist': ('Nàmhaid-sceòil', 'ˈn̪ˠaːvɪtʃˈskʲɔːlʲ'),
    'c1-applicant': ('Tagraiche', 'ˈt̪ʰakɾɪçə'),
    'c1-appraisal': ('Luachadh', 'ˈl̪ˠuəxəɣ'),
    'c1-appreciation-value': ('Àrdachadh luach', 'ˈaːɾt̪əxəɣ ˈl̪ˠuəx'),
    'c1-arguably': ("Dh'fhaodte a ràdh", 'ˈɣɯːtʃtʃə ə ˈr̪ˠaːɣ'),
    'c1-aroma': ('Cùbhraidheachd', 'ˈkʰuːvɾɪ.əxk'),
    'c1-assertive': ('Dìorrasach', 'ˈtʃiər̪ˠəsəx'),
    'c1-asset': ('Maoin', 'ˈmɯːnʲ'),
    'c1-assumption': ('Barail', 'ˈpaɾɪlʲ'),
    'c1-asteroid': ('Clach-speura', 'ˈkʰl̪ˠaxˈspiəɾə'),
    'c1-asylum': ('Tèarmann', 'ˈtʃʰiəɾmən̪ˠ'),
    'c1-at-a-loss': ('Ann an imcheist', 'ˈaun̪ˠ ən̪ˠ ˈimçɪʃtʃ'),
    'c1-at-best': ("Aig a' char as fheàrr", 'ˈekʲ ə ˈxaɾ ˈas ˈjaːr̪ˠ'),
    'c1-at-most': ("Aig a' char as motha", 'ˈekʲ ə ˈxaɾ ˈas ˈmɔ.ə'),
    'c1-at-peace': ('Ann an sìth', 'ˈaun̪ˠ ən̪ˠ ˈʃiː'),
    'c1-at-worst': ("Aig a' char as miosa", 'ˈekʲ ə ˈxaɾ ˈas ˈmisə'),
    'c1-audit': ('Scrùdadh-cunntais', 'ˈskɾuːt̪əɣˈkʰuːn̪ˠt̪ɪʃ'),
    'c1-augmented-reality': ('Aisling-lèirsinne', 'ˈaʃlʲɪɲkʲˈʎeːɾʲʃɪɲə'),
    'c1-austere': ('Lom', 'ˈl̪ˠɔum'),
    'c1-austerity': ('Crios-teann', 'ˈkʰɾʲisˈtʃʰaun̪ˠ'),
    'c1-awesome': ('Scoinneil', 'ˈskɔɲɪlʲ'),
    'c1-back-to-the-drawing-board': ('Air ais aig an toiseach', 'ˈɛɾʲ ˈaʃ ˈekʲ ən̪ˠ ˈd̪ɔʃəx'),
    'c1-backsplash': ('Sciath-balla', 'ˈskʲiəˈpal̪ˠə'),
    'c1-backup-data': ('Cuimhne-cùil', 'ˈkʰũnʲəˈkʰuːlʲ'),
    'c1-ballpark-figure': ('Tuairmse', 'ˈt̪ʰuəɾʲmʃə'),
    'c1-bandwidth-capacity': ('Comas', 'ˈkʰɔməs'),
    'c1-bandwidth-network': ('Leud-sruthain', 'ˈʎiət̪ˈst̪ɾuhɪnʲ'),
    'c1-barista': ('Grùdaire-cofaidh', 'ˈkɾuːt̪ɪɾʲəˈkʰɔfi'),
    'c1-baseboard': ('Bòrd-sciortaidh', 'ˈpɔːɾt̪ˈskʲiɾt̪i'),
    'c1-bedside-manner': ('Dòigh leis an euslainteach', 'ˈtoːj ˈʎeʃ ən̪ˠ ˈiəsl̪ˠɪɲtʃəx'),
    'c1-benevolent': ('Deagh-rùnach', 'ˈtʃɛˈr̪ˠuːnəx'),
    'c1-beside-oneself': ('Air bhoil', 'ˈɛɾʲ ˈvɔlʲ'),
    'c1-beta': ('Tionndadh-deuchainne', 'ˈtʃʰuːn̪ˠt̪əɣˈtʃiəxɪɲə'),
    'c1-bilingual': ('Dà-chànanach', 'ˈt̪aːˈxaːnanəx'),
    'c1-biometric': ('Corp-dhearbhach', 'ˈkʰɔɾpˈjɛɾɛvəx'),
    'c1-birth-rate': ('Ìre-breith', 'ˈiːɾʲəˈpɾʲeh'),
    'c1-black-hole': ('Slugaire-solais', 'ˈsl̪ˠukɪɾʲəˈsɔl̪ˠɪʃ'),
    'c1-bleak': ('Fàsail', 'ˈfaːsɪlʲ'),
    'c1-blockbuster': ('Scàil-sluaigh', 'ˈskaːlʲˈsl̪ˠuəj'),
    'c1-blockchain': ('Slabhraidh-cunntais', 'ˈsl̪ˠavɾiˈkʰuːn̪ˠt̪ɪʃ'),
    'c1-blown-away': ('Fo iongnadh mòr', 'fə ˈjuːŋnəɣ ˈmoːɾ'),
    'c1-bond-finance': ('Bann', 'ˈpaun̪ˠ'),
    'c1-bookkeeping': ('Glèidheadh chunntasan', 'ˈkʲlʲeː.əɣ ˈxuːn̪ˠt̪əsan'),
    'c1-bottom-line': ('Bun is bàrr', 'ˈpun ɪs ˈpaːr̪ˠ'),
    'c1-box-office': ('Doras-dìolaidh', 'ˈt̪ɔɾəsˈtʃiəl̪ˠi'),
    'c1-brain-drain': ('Teicheadh-cèille', 'ˈtʃʰeçəɣˈkʲʰeːʎə'),
    'c1-break-even': ('Cothrom-meidhe', 'ˈkʰɔɾəmˈme.ə'),
    'c1-breaking-news': ('Naidheachd sa bhad', 'ˈn̪ˠa.əxk sə ˈvat̪'),
    'c1-brew': ('Grùdadh', 'ˈkɾuːt̪əɣ'),
    'c1-broadcast': ('Scaoileadh-gutha', 'ˈskɯːlʲəɣˈku.ə'),
    'c1-buddy': ('Companach', 'ˈkʰɔmpanəx'),
    'c1-bulky': ('Tomadach', 'ˈt̪ʰɔmət̪əx'),
    'c1-bureaucracy': ('Riaghladh-chlèireach', 'ˈr̪ˠiəl̪ˠəɣˈçlʲeːɾʲəx'),
    'c1-bustling': ('Trang', 'ˈt̪ʰɾauŋk'),
    'c1-butterflies-in-my-stomach': ('Dealain-dè nam stamaig', 'ˈtʃal̪ˠɪnʲˈtʃeː nəm ˈst̪amɪkʲ'),
    'c1-by-a-landslide': ('Le mòr-bhuannachd', 'lʲə ˈmoːɾˈvuən̪ˠəxk'),
    'c1-by-a-narrow-margin': ('Air èiginn', 'ˈɛɾʲ ˈeːkʲɪɲ'),
    'c1-by-virtue-of': ('Air sàilleabh', 'ˈɛɾʲ ˈsaːʎəv'),
    'c1-byline': ('Loidhne-ùghdair', 'ˈl̪ˠɤinʲəˈuːt̪ɪɾʲ'),
    'c1-cabinetry': ('Preasan', 'ˈpʰɾʲɛsan'),
    'c1-calculating': ('Carach', 'ˈkʰaɾəx'),
    'c1-cameo': ('Nochdadh goirid', 'ˈn̪ˠɔxkəɣ ˈkɔɾʲɪtʃ'),
    'c1-candid': ('Foscarra', 'ˈfɔskər̪ˠə'),
    'c1-capital-gains': ('Fàs-stòir', 'ˈfaːsˈst̪ɔːɾʲ'),
    'c1-carbon-tax': ('Cìs gualain', 'ˈkʲʰiːʃ ˈkuəl̪ˠɪnʲ'),
    'c1-cash-reserve': ('Cùl-stòras airgid', 'ˈkʰuːl̪ˠˈst̪ɔːɾəs ˈaɾʲakʲɪtʃ'),
    'c1-casting': ('Taghadh chleasaichean', 'ˈt̪ʰa.əɣ ˈçlʲɛsɪçan'),
    'c1-caulk': ('Stuth-lìonaidh', 'ˈst̪uhˈʎiəni'),
    'c1-causation': ('Adhbharachadh', 'ˈavəɾəxəɣ'),
    'c1-ceasefire': ('Fosadh-catha', 'ˈfɔsəɣˈkʰa.ə'),
    'c1-censorship': ('Caiscireachd', 'ˈkʰaʃkʲɪɾʲəxk'),
    'c1-certified-copy': ('Lethbhreac dearbhte', 'ˈʎevɾʲəʰk ˈtʃɛɾʲɛvtʃə'),
    'c1-change-order': ('Òrdugh-atharrachaidh', 'ˈɔːɾt̪əɣˈa.ər̪ˠəxi'),
    'c1-charismatic': ('Tarraingeach', 'ˈt̪ʰaːr̪ˠɪɲəx'),
    'c1-cheesy': ('Maothail', 'ˈmɯːhɪlʲ'),
    'c1-chefs-recommendation': ("Moladh a' chòcaire", 'ˈmɔl̪ˠəɣ ə ˈxɔːʰkɪɾʲə'),
    'c1-chemistry-between-people': ('Tarraing', 'ˈt̪ʰaːr̪ˠɪɲkʲ'),
    'c1-chic': ('Snasail', 'ˈsnasɪlʲ'),
    'c1-cinematography': ('Ealain-scàile', 'ˈjal̪ˠɪnʲˈskaːlʲə'),
    'c1-circuit-breaker': ('Freiceadan-dealanaich', 'ˈfɾʲeʰkʲət̪anˈtʃal̪ˠanɪç'),
    'c1-citation': ('Iomradh-tùis', 'ˈimɾəɣˈt̪ʰuːʃ'),
    'c1-civil-war': ('Cogadh catharra', 'ˈkʰɔkəɣ ˈkʰa.ər̪ˠə'),
    'c1-clause': ('Earrann-cùmhnaint', 'ˈjaːr̪ˠən̪ˠˈkʰũːnɪɲtʃ'),
    'c1-clickbait': ('Biadh-sùla', 'ˈpiəɣˈsuːl̪ˠə'),
    'c1-cliffhanger': ('Crochadh-creige', 'ˈkʰɾɔxəɣˈkʰɾʲekʲə'),
    'c1-close-up': ('Sealladh-sròine', 'ˈʃɛl̪ˠəɣˈst̪ɾɔːnʲə'),
    'c1-closing-real-estate': ('Crìochnachadh reic', 'ˈkʰɾʲiəxnəxəɣ ˈr̪ˠeʰkʲ'),
    'c1-cloud-computing': ('Cunntas-neòil', 'ˈkʰuːn̪ˠt̪əsˈɲɔːlʲ'),
    'c1-clunky': ('Cliobach', 'ˈkʲʰlʲipəx'),
    'c1-cognate': ('Facal-bràthar', 'ˈfaʰkəl̪ˠˈpɾaː.əɾ'),
    'c1-cold-feet': ("Teagamh aig a' mhionaid mu dheireadh", 'ˈtʃʰekəv ˈekʲ ə ˈvinɪtʃ mə ˈjeɾʲəɣ'),
    'c1-collateral': ('Urras', 'ˈuːr̪ˠəs'),
    'c1-colloquial': ('Labhairteach', 'ˈl̪ˠavɪɾʲtʃəx'),
    'c1-colony': ('Fearann-imrich', 'ˈfɛɾən̪ˠˈimɾʲɪç'),
    'c1-commission-fee': ('Duais-reic', 'ˈt̪uəʃˈr̪ˠeʰkʲ'),
    'c1-compact': ('Dlùth', 'ˈt̪l̪ˠuː'),
    'c1-compliance': ('Gèilleadh', 'ˈkʲeːʎəɣ'),
    'c1-condescending': ('Tàireil', 'ˈt̪ʰaːɾʲɪlʲ'),
    'c1-confidant': ('Caraid-rùin', 'ˈkʰaɾɪtʃˈr̪ˠuːnʲ'),
    'c1-conscientious': ('Cogaiseach', 'ˈkʰɔkɪʃəx'),
    'c1-constellation': ('Reul-bhad', 'ˈr̪ˠiəl̪ˠˈvat̪'),
    'c1-constitution': ('Bun-reachd', 'ˈpunˈr̪ˠɛxk'),
    'c1-consultant': ('Comhairliche', 'ˈkʰɔvɪɾʲlʲɪçə'),
    'c1-contingency': ('Cumha', 'ˈkʰuvə'),
    'c1-conversely': ("Air a' chaochladh", 'ˈɛɾʲ ə ˈxɯːxl̪ˠəɣ'),
    'c1-convoluted': ('Toinnte', 'ˈt̪ʰɔiɲtʃə'),
    'c1-correlation': ('Co-dhàimh', 'kʰɔˈɣaːv'),
    'c1-correspondent': ('Comhfhreagraiche', 'ˈkʰɔ̃ɾʲəkɾɪçə'),
    'c1-counteroffer': ('Frith-thairgse', 'ˈfɾʲihˈhaɾʲakʲʃə'),
    'c1-countertop': ('Clàr-obrach', 'ˈkʰl̪ˠaːɾˈɔpɾəx'),
    'c1-coup': ('Glacadh cumhachd', 'ˈkl̪ˠaʰkəɣ ˈkʰuvəxk'),
    'c1-coverage': ('Còmhdach', 'ˈkʰɔ̃ːt̪əx'),
    'c1-cramped': ('Cumhang', 'ˈkʰuvəŋk'),
    'c1-cringe': ('Nàire', 'ˈn̪ˠaːɾʲə'),
    'c1-critically-acclaimed': ('Air a mholadh leis an luchd-breithneachaidh', 'ˈɛɾʲ ə ˈvɔl̪ˠəɣ ˈʎeʃ ən̪ˠ ˈl̪ˠuxkˈpɾʲenʲəxi'),
    'c1-critique': ('Breithneachadh', 'ˈpɾʲenʲəxəɣ'),
    'c1-crown-molding': ('Coirnis', 'ˈkʰɔɾʲnʲɪʃ'),
    'c1-crude': ('Garbh', 'ˈkaɾav'),
    'c1-cryptocurrency': ('Airgead-dìomhair', 'ˈaɾʲakʲət̪ˈtʃiəvɪɾʲ'),
    'c1-cult-classic': ('Scàil-cràbhaidh', 'ˈskaːlʲˈkʰɾaːvi'),
    'c1-culture-shock': ('Clisceadh-coigrich', 'ˈkʲʰlʲiʃkʲəɣˈkʰɔkʲɾʲɪç'),
    'c1-cutting-edge': ('Aig an fhìor thoiseach', 'ˈekʲ ən̪ˠ ˈiəɾ ˈhɔʃəx'),
    'c1-cynical': ('Mì-earbsach', 'ˈmiːˈɛɾɛpsəx'),
    'c1-dark-horse': ('Each dubh', 'ˈɛx ˈt̪u'),
    'c1-data-protection': ('Dìon-fiosa', 'ˈtʃiənˈfisə'),
    'c1-dataset': ('Cruach-fiosa', 'ˈkʰɾuəxˈfisə'),
    'c1-deadline-filing': ('Ceann-latha', 'ˈkʲʰaun̪ˠˈl̪ˠa.ə'),
    'c1-deafening': ('Bodhrach', 'ˈpɔɾəx'),
    'c1-decaf': ('Gun-dùscadh', 'ˈkunˈt̪uːskəɣ'),
    'c1-deductible': ('A ghabhas toirt dheth', 'ə ˈɣavəs ˈt̪ʰɔɾʲtʃ ˈjeh'),
    'c1-deed': ('Còir-scrìobhte', 'ˈkʰɔːɾʲˈskɾʲiəvtʃə'),
    'c1-default-loan': ('Fàilligeadh pàighidh', 'ˈfaːʎɪkʲəɣ ˈpʰaː.i'),
    'c1-deliverable': ('Toradh ri lìbhrigeadh', 'ˈt̪ʰɔɾəɣ ɾʲə ˈʎiːvɾʲɪkʲəɣ'),
    'c1-democracy': ('Riaghladh-sluaigh', 'ˈr̪ˠiəl̪ˠəɣˈsl̪ˠuəj'),
    'c1-density': ('Dlùths', 'ˈt̪l̪ˠuːs'),
    'c1-depreciation': ('Ìsleachadh luach', 'ˈiːʃlʲəxəɣ ˈl̪ˠuəx'),
    'c1-deserted': ('Fàsail', 'ˈfaːsɪlʲ'),
    'c1-dialect': ('Dual-chainnt', 'ˈt̪uəl̪ˠˈxaiɲtʃ'),
    'c1-dictatorship': ('Deachdaireachd', 'ˈtʃɛxkɪɾʲəxk'),
    'c1-dilapidated': ('Air a dhol bhuaithe', 'ˈɛɾʲ ə ˈɣɔl̪ˠ ˈvuə.ə'),
    'c1-diligent': ('Dìcheallach', 'ˈtʃiːçəl̪ˠəx'),
    'c1-dimmer': ('Ciaraiche-lòchrain', 'ˈkʲʰiəɾɪçəˈl̪ˠɔːxɾɪnʲ'),
    'c1-dingy': ('Duaichnidh', 'ˈt̪uəçnʲi'),
    'c1-diplomacy': ('Ceàird-toscaire', 'ˈkʲʰiɾʲtʃˈt̪ʰɔskɪɾʲə'),
    'c1-discipline-field': ('Raon-eòlais', 'ˈr̪ˠɯːnˈjɔːl̪ˠɪʃ'),
    'c1-discourse': ('Conaltradh', 'ˈkʰɔnəl̪ˠt̪ɾəɣ'),
    'c1-dissertation': ('Tràchdas', 'ˈt̪ʰɾaːxkəs'),
    'c1-dividend': ('Roinn-toraidh', 'ˈr̪ˠɔiɲˈt̪ʰɔɾi'),
    'c1-down-in-the-dumps': ('Fo sprochd', 'fə ˈspɾɔxk'),
    'c1-drizzle-of-oil': ('Braon', 'ˈpɾɯːn'),
    'c1-drone': ('Speireag-iarainn', 'ˈspeɾʲakˈiəɾɪɲ'),
    'c1-dry-wine': ('Tioram', 'ˈtʃʰiɾəm'),
    'c1-dubbed': ('Guth-iasadach', 'ˈkuhˈiəsət̪əx'),
    'c1-duct': ('Pìob-adhair', 'ˈpʰiəpˈa.ɪɾʲ'),
    'c1-dude': ('Balach', 'ˈpal̪ˠəx'),
    'c1-durable': ('Buan', 'ˈpuən'),
    'c1-dynasty': ('Rìgh-shliochd', 'ˈr̪ˠiːˈhlʲixk'),
    'c1-easement': ('Còir-slighe', 'ˈkʰɔːɾʲˈʃlʲi.ə'),
    'c1-eccentric': ('Neònach', 'ˈɲɔːnəx'),
    'c1-eclipse': ('Dubhadh', 'ˈt̪uvəɣ'),
    'c1-editorial': ('Aiste-deasachaidh', 'ˈaʃtʃəˈtʃɛsəxi'),
    'c1-eerie': ('Aognaidh', 'ˈɯːkni'),
    'c1-electron': ('Mìr-dealanaich', 'ˈmiːɾʲˈtʃal̪ˠanɪç'),
    'c1-eligible': ('Airidh', 'ˈaɾʲi'),
    'c1-eloquent': ('Deas-bhriathrach', 'ˈtʃɛsˈvɾʲiəɾəx'),
    'c1-elusive': ('Doirbh a ghlacadh', 'ˈt̪ɔɾʲɔv ə ˈɣl̪ˠaʰkəɣ'),
    'c1-embassy': ('Taigh-toscaire', 'ˈt̪ʰɤjˈt̪ʰɔskɪɾʲə'),
    'c1-empire': ('Ìmpireachd', 'ˈiːmpɪɾʲəxk'),
    'c1-empirical': ('Deuchainneil', 'ˈtʃiəxɪɲɪlʲ'),
    'c1-encryption-key': ('Iuchair-rùin', 'ˈjuxɪɾʲˈr̪ˠuːnʲ'),
    'c1-enduring': ('Maireannach', 'ˈmaɾʲən̪ˠəx'),
    'c1-enzyme': ('Deascainn-cuirp', 'ˈtʃɛskɪɲˈkʰuɾʲp'),
    'c1-equity': ('Cuibhreann-seilbhe', 'ˈkʰuvɾʲən̪ˠˈʃelʲevə'),
    'c1-escrow': ('Ciste-urrais', 'ˈkʲʰiʃtʃəˈuːr̪ˠɪʃ'),
    'c1-espresso': ('Brìgh-cofaidh', 'ˈpɾʲiːˈkʰɔfi'),
    'c1-estranged': ('Coimheach', 'ˈkʰɔvəx'),
    'c1-exceptional': ('Sònraichte', 'ˈsɔːnɾɪçtʃə'),
    'c1-exclusive-story': ('Naidheachd air leth', 'ˈn̪ˠa.əxk ˈɛɾʲ ˈʎeh'),
    'c1-exemption': ('Saoradh', 'ˈsɯːɾəɣ'),
    'c1-exile': ('Fògradh', 'ˈfɔːkɾəɣ'),
    'c1-expatriate': ('Eilthireach', 'ˈelʲhɪɾʲəx'),
    'c1-expedition': ('Turas-rannsachaidh', 'ˈt̪ʰuɾəsˈr̪ˠaun̪ˠsəxi'),
    'c1-exponentially': ('Mar theine-fraoich', 'ˈmaɾ ˈhenʲəˈfɾɯːç'),
    'c1-exquisite': ('Fìor-ghrinn', 'ˈfiəɾˈɣɾʲiːɲ'),
    'c1-extravagant': ('Struidheil', 'ˈst̪ɾu.ɪlʲ'),
    'c1-fact-check': ('Dearbhadh fhìrinnean', 'ˈtʃɛɾɛvəɣ ˈiːɾʲɪɲan'),
    'c1-faint-sound': ('Fann', 'ˈfaun̪ˠ'),
    'c1-false-friend': ('Facal-brathaidh', 'ˈfaʰkəl̪ˠˈpɾahi'),
    'c1-fed-up': ('Seachd scìth', 'ˈʃɛxk ˈskʲiː'),
    'c1-figurehead': ('Ceann-suaicheantais', 'ˈkʲʰaun̪ˠˈsuəçan̪ˠt̪ɪʃ'),
    'c1-findings': ('Toraidhean rannsachaidh', 'ˈt̪ʰɔɾɪ.an ˈr̪ˠaun̪ˠsəxi'),
    'c1-firewall': ('Gàrradh-lìn', 'ˈkaːr̪ˠəɣˈʎiːnʲ'),
    'c1-first-rate': ('Den chiad scoth', 'tʃən̪ˠ ˈçiət̪ ˈskɔh'),
    'c1-fiscal-year': ('Bliadhna ionmhais', 'ˈplʲiənə ˈinivɪʃ'),
    'c1-fixture': ('Uidheam suidhichte', 'ˈu.əm ˈsu.ɪçtʃə'),
    'c1-flashback': ('Scàil-cuimhne', 'ˈskaːlʲˈkʰũnʲə'),
    'c1-flawless': ('Gun mhearachd', 'kən̪ˠ ˈvɛɾəxk'),
    'c1-fleeting': ('Diombuan', 'ˈtʃimpuən'),
    'c1-flimsy': ('Cugallach', 'ˈkʰukəl̪ˠəx'),
    'c1-floor-plan': ('Dealbh-ùrlair', 'ˈtʃal̪ˠavˈuːɾl̪ˠɪɾʲ'),
    'c1-fluency': ('Fileantachd', 'ˈfilʲan̪ˠt̪əxk'),
    'c1-follow-up-appointment': ('Coinneamh leantainneach', 'ˈkʰɔɲəv ˈʎɛn̪ˠt̪ɪɲəx'),
    'c1-food-security': ('Tèarainteachd bìdh', 'ˈtʃʰiəɾɪɲtʃəxk ˈpiː'),
    'c1-foolproof': ('Nach tèid ceàrr', 'nəx ˈtʃʰeːtʃ ˈkʲʰaːr̪ˠ'),
    'c1-for-all-intents-and-purposes': ('Anns gach seagh', 'ˈaun̪ˠs ˈkax ˈʃɛ'),
    'c1-for-real': ('Dha-rìribh', 'ˈɣaˈr̪ˠiːɾʲɪv'),
    'c1-foreclosure': ('Glacadh-seilbhe', 'ˈkl̪ˠaʰkəɣˈʃelʲevə'),
    'c1-foreshadowing': ('Roimh-shealladh', 'ˈr̪ˠɔvˈhɛl̪ˠəɣ'),
    'c1-free-speech': ('Saorsa-cainnte', 'ˈsɯːɾsəˈkʰaiɲtʃə'),
    'c1-frequency-physics': ('Tricead', 'ˈt̪ʰɾʲiʰkʲət̪'),
    'c1-friction': ('Suathadh', 'ˈsuə.əɣ'),
    'c1-frontrunner': ('Fear-toisich', 'ˈfɛɾˈt̪ʰɔʃɪç'),
    'c1-frugal': ('Caomhnach', 'ˈkʰɯ̃ːnəx'),
    'c1-full-bodied': ('Làn-bhlasta', 'ˈl̪ˠaːnˈvl̪ˠast̪ə'),
    'c1-galaxy': ('Scaoth-rionnag', 'ˈskɯːˈr̪ˠin̪ˠak'),
    'c1-game-changer': ('Puing-tionndaidh', 'ˈpʰuːiɲkʲˈtʃʰuːn̪ˠt̪i'),
    'c1-garnish': ('Sceadachadh', 'ˈskʲɛt̪əxəɣ'),
    'c1-gatekeeper': ('Dorsair', 'ˈt̪ɔɾsɪɾʲ'),
    'c1-getaway': ('Fòrladh goirid', 'ˈfɔːɾl̪ˠəɣ ˈkɔɾʲɪtʃ'),
    'c1-gig-economy': ('Cosnadh-bloighe', 'ˈkʰɔsnəɣˈpl̪ˠɔ.ə'),
    'c1-give-or-take': ('No mar sin', 'ˈn̪ˠɔ ˈmaɾ ˈʃinʲ'),
    'c1-glaze': ('Lìomh', 'ˈʎiəv'),
    'c1-glitchy': ('Làn mhearachdan', 'ˈl̪ˠaːn ˈvɛɾəxkan'),
    'c1-globalization': ('Fighe-cruinne', 'ˈfi.əˈkʰɾɯɲə'),
    'c1-gloomy': ('Gruamach', 'ˈkɾuəməx'),
    'c1-go-getter': ('Neach adhartach', 'ˈɲɛx ˈa.əɾt̪əx'),
    'c1-goosebumps': ('Grìs', 'ˈkɾʲiːʃ'),
    'c1-granted': ('Fìor gu leòr', 'ˈfiəɾ kə ˈʎɔːɾ'),
    'c1-grim': ('Mùgach', 'ˈmuːkəx'),
    'c1-gross': ('Screamhail', 'ˈskɾʲɛvɪlʲ'),
    'c1-gross-before-deductions': ('Slàn', 'ˈsl̪ˠaːn'),
    'c1-grout': ('Taois-leacan', 'ˈt̪ʰɯːʃˈʎeʰkan'),
    'c1-gullible': ('So-mhealladh', 'ˈsɔˈvɛl̪ˠəɣ'),
    'c1-half-baked': ('Leth-bhruich', 'ˈʎehˈvɾuç'),
    'c1-hardwood-floor': ('Làr fiodha cruaidh', 'ˈl̪ˠaːɾ ˈfi.ə ˈkʰɾuəj'),
    'c1-hashtag': ('Comharra-cuspair', 'ˈkʰɔvər̪ˠəˈkʰuspɪɾʲ'),
    'c1-head-over-heels': ('Gu tur ann an gaol', 'kə ˈt̪ʰuɾ ˈaun̪ˠ əŋ ˈkɯːl̪ˠ'),
    'c1-headhunter': ('Sealgair-làmhan', 'ˈʃal̪ˠakɪɾʲˈl̪ˠaːvan'),
    'c1-heartbroken': ('Le cridhe briste', 'lʲə ˈkʰɾʲi.ə ˈpɾʲiʃtʃə'),
    'c1-heavyweight': ('Trom-chuideam', 'ˈt̪ʰɾɔumˈxutʃəm'),
    'c1-hedge': ('Callaid-ionmhais', 'ˈkʰal̪ˠɪtʃˈinivɪʃ'),
    'c1-heir': ('Oighre', 'ˈɤiɾʲə'),
    'c1-hence': ('Uime sin', 'ˈumə ˈʃinʲ'),
    'c1-henceforth': ('Bho seo a-mach', 'ˈvɔ ˈʃɔ əˈmax'),
    'c1-hereby': ('Leis a seo', 'ˈʎeʃ ə ˈʃɔ'),
    'c1-hierarchy': ('Rangachd', 'ˈr̪ˠaŋəxk'),
    'c1-hoarse': ('Tùchanach', 'ˈt̪ʰuːxanəx'),
    'c1-hooked': ('An grèim', 'əŋ ˈkɾʲeːm'),
    'c1-hormone': ('Teachdaire-fala', 'ˈtʃʰɛxkɪɾʲəˈfal̪ˠə'),
    'c1-hvac': ('Anail-taighe', 'ˈanɪlʲˈt̪ʰa.ə'),
    'c1-hype': ('Othail', 'ˈɔhɪlʲ'),
    'c1-immersion': ('Bogadh', 'ˈpɔkəɣ'),
    'c1-immigrant': ('In-imriche', 'ˈinʲˈimɾʲɪçə'),
    'c1-immune-to': ('Dìonach an aghaidh', 'ˈtʃiənəx ən̪ˠ ˈa.i'),
    'c1-impeccable': ('Gun mheang', 'kən̪ˠ ˈvʲauŋk'),
    'c1-impulsive': ('Bras', 'ˈpɾas'),
    'c1-in-a-rut': ('Ann an clais', 'ˈaun̪ˠ əŋ ˈɡl̪ˠaʃ'),
    'c1-in-bulk': ('Ann am mòr-thomhas', 'ˈaun̪ˠ əm ˈmoːɾˈhɔvəs'),
    'c1-in-good-shape': ('Ann an deagh chumadh', 'ˈaun̪ˠ ən̪ˠ ˈtʃɛ ˈxuməɣ'),
    'c1-in-lieu-of': ('An àite', 'ən̪ˠ ˈaːʰtʃə'),
    'c1-in-light-of': ('A rèir', 'ə ˈr̪ˠeːɾʲ'),
    'c1-in-the-region-of': ('Mu thimcheall', 'mə ˈhimçəl̪ˠ'),
    'c1-in-two-minds': ('Eadar dà bharail', 'ˈɛt̪əɾ ˈt̪aː ˈvaɾɪlʲ'),
    'c1-in-view-of': ('A thaobh', 'ə ˈhɯːv'),
    'c1-independence': ('Neo-eisimeileachd', 'ˈɲɔˈeʃɪmɪlʲəxk'),
    'c1-indie-film': ('Scàil-aonarain', 'ˈskaːlʲˈɯːnəɾɪnʲ'),
    'c1-inertia': ('Marbhantachd', 'ˈmaɾavan̪ˠt̪əxk'),
    'c1-inference': ('Co-dhùnadh', 'kʰɔˈɣuːnəɣ'),
    'c1-influencer': ('Buachaille-sluaigh', 'ˈpuəxɪʎəˈsl̪ˠuəj'),
    'c1-insider': ('Neach a-staigh', 'ˈɲɛx əˈst̪ɤj'),
    'c1-insofar-as': ("Cho fad 's a", 'ˈxɔ ˈfat̪ s ə'),
    'c1-interface': ('Aghaidh-còmhraidh', 'ˈa.iˈkʰɔ̃ːɾi'),
    'c1-intern': ('Oileanach obrach', 'ˈɔlʲanəx ˈɔpɾəx'),
    'c1-interpreter': ('Eadar-theangair', 'ˈɛt̪əɾˈhɛŋɪɾʲ'),
    'c1-intonation': ('Fonn-labhairt', 'ˈfɔun̪ˠˈl̪ˠavɪɾʲtʃ'),
    'c1-intricate': ('Iom-fhillte', 'ˈjuːmˈiːʎtʃə'),
    'c1-invariably': ('Gun atharrachadh', 'kən̪ˠ ˈa.ər̪ˠəxəɣ'),
    'c1-invasion': ('Ionnradh', 'ˈjuːn̪ˠɾəɣ'),
    'c1-isotope': ('Càraid-dùile', 'ˈkʰaːɾɪtʃˈt̪uːlʲə'),
    'c1-jargon': ('Bèarlagair', 'ˈpiəɾl̪ˠəkɪɾʲ'),
    'c1-jet-lagged': ('Fo shuain-siubhail', 'fə ˈhuənʲˈʃuvɪlʲ'),
    'c1-job-displacement': ('Call obraichean', 'ˈkʰaul̪ˠ ˈɔpɾɪçan'),
    'c1-joist': ('Sail', 'ˈsalʲ'),
    'c1-jurisdiction': ('Ùghdarras-lagha', 'ˈuːt̪ər̪ˠəsˈl̪ˠa.ə'),
    'c1-keyed-up': ('Air ghleus', 'ˈɛɾʲ ˈjlʲiəs'),
    'c1-know-it-all': ('Uile-fhiosraiche', 'ˈulʲəˈisɾɪçə'),
    'c1-laid-back': ('Socair', 'ˈsɔʰkɪɾʲ'),
    'c1-lame': ('Lapach', 'ˈl̪ˠaʰpəx'),
    'c1-laminate': ('Fiodh-brèige', 'ˈfiɣˈpɾʲeːkʲə'),
    'c1-latency': ('Moille-fiosa', 'ˈmɔʎəˈfisə'),
    'c1-lavish': ('Sòghail', 'ˈsɔː.ɪlʲ'),
    'c1-layout': ('Cruth', 'ˈkʰɾuh'),
    'c1-leafy': ('Duilleagach', 'ˈt̪uʎəkəx'),
    'c1-ledger': ('Leabhar-cunntais', 'ˈʎɔ.əɾˈkʰuːn̪ˠt̪ɪʃ'),
    'c1-legit': ('Dligheach', 'ˈtʃlʲi.əx'),
    'c1-liability': ('Buailteachd', 'ˈpuəlʲtʃəxk'),
    'c1-liability-finance': ('Fiach', 'ˈfiəx'),
    'c1-liaison': ('Neach-ceangail', 'ˈɲɛxˈkʲʰɛŋɪlʲ'),
    'c1-license-permit': ('Cead', 'ˈkʲʰɛt̪'),
    'c1-lien': ('Tagradh air seilbh', 'ˈt̪ʰakɾəɣ ˈɛɾʲ ˈʃelʲev'),
    'c1-likewise': ('Mar an ceudna', 'ˈmaɾ əŋ ˈɡʲiət̪nə'),
    'c1-liquidity': ('Sruth-maoine', 'ˈst̪ɾuhˈmɯːnʲə'),
    'c1-listing-property': ('Sanas-seilbhe', 'ˈsanəsˈʃelʲevə'),
    'c1-literacy': ('Fios-litreach', 'ˈfisˈʎiʰtʃɾʲəx'),
    'c1-lively': ('Beòthail', 'ˈpʲɔːhɪlʲ'),
    'c1-load-bearing-wall': ('Balla-taice', 'ˈpal̪ˠəˈt̪ʰaʰkʲə'),
    'c1-loanword': ('Facal-coigrich', 'ˈfaʰkəl̪ˠˈkʰɔkʲɾʲɪç'),
    'c1-low-hanging-fruit': ('Buannachd fhurasta', 'ˈpuən̪ˠəxk ˈuɾəst̪ə'),
    'c1-lucid': ('Soilleir', 'ˈsɔʎɪɾʲ'),
    'c1-machine-learning': ('Foghlam-iarainn', 'ˈfɔl̪ˠəmˈiəɾɪɲ'),
    'c1-magnanimous': ('Mòr-inntinneach', 'ˈmoːɾˈiːɲtʃɪɲəx'),
    'c1-magnetic-field': ('Raon-iùil', 'ˈr̪ˠɯːnˈjuːlʲ'),
    'c1-malicious': ('Mì-rùnach', 'ˈmiːˈr̪ˠuːnəx'),
    'c1-malware': ('Geas-millidh', 'ˈkʲɛsˈmiʎi'),
    'c1-marginally': ('Gu ìre bhig', 'kə ˈiːɾʲə ˈvikʲ'),
    'c1-markup': ('Àrdachadh prìse', 'ˈaːɾt̪əxəɣ ˈpʰɾʲiːʃə'),
    'c1-meager': ('Crìon', 'ˈkʰɾʲiən'),
    'c1-mediocre': ('Meadhanach', 'ˈmɛ.anəx'),
    'c1-medium-rare': ('Beagan dearg', 'ˈpekan ˈtʃɛɾɛk'),
    'c1-mentor': ('Treòraiche', 'ˈt̪ʰɾʲɔːɾɪçə'),
    'c1-metabolism': ('Loscadh-bìdh', 'ˈl̪ˠɔskəɣˈpiː'),
    'c1-methodology': ('Rian-rannsachaidh', 'ˈr̪ˠiənˈr̪ˠaun̪ˠsəxi'),
    'c1-meticulous': ('Mionaideach', 'ˈminɪtʃəx'),
    'c1-middleman': ('Fear-meadhain', 'ˈfɛɾˈmɛ.ɪnʲ'),
    'c1-minimum-wage': ('Tuarastal-buinn', 'ˈt̪ʰuəɾəst̪əl̪ˠˈpuːiɲ'),
    'c1-misinformation': ('Mì-fhiosrachadh', 'ˈmiːˈisɾəxəɣ'),
    'c1-mixed-feelings': ('Faireachdainnean meascaichte', 'ˈfaɾʲəxkɪɲan ˈmɛskɪçtʃə'),
    'c1-molding-trim': ('Sceadachadh-oir', 'ˈskʲɛt̪əxəɣˈɔɾʲ'),
    'c1-momentum': ('Neart-siubhail', 'ˈɲɛɾt̪ˈʃuvɪlʲ'),
    'c1-monarchy': ('Aon-tighearnas', 'ˈɯːnˈtʃʰi.əɾnəs'),
    'c1-monotone': ('Aon-ghuthach', 'ˈɯːnˈɣu.əx'),
    'c1-montage': ('Fighe-scàile', 'ˈfi.əˈskaːlʲə'),
    'c1-mother-tongue': ('Cànan màthaireil', 'ˈkʰaːnan ˈmaːhɪɾʲɪlʲ'),
    'c1-muffled': ('Mùchte', 'ˈmuːçtʃə'),
    'c1-multilingual': ('Ioma-chànanach', 'ˈiməˈxaːnanəx'),
    'c1-mutation': ('Mùthadh', 'ˈmuː.əɣ'),
    'c1-namely': ('Is e sin', 'ɪs ˈɛ ˈʃinʲ'),
    'c1-nationalism': ('Dìlseachd-dùthcha', 'ˈtʃiːlʲʃəxkˈt̪uːxə'),
    'c1-negligible': ('Suarach', 'ˈsuəɾəx'),
    'c1-nestled': ('Na laighe gu seascair', 'nə ˈl̪ˠa.ə kə ˈʃɛskɪɾʲ'),
    'c1-net': ('Glan', 'ˈkl̪ˠan'),
    'c1-neural-network': ('Lìon-inntinne', 'ˈʎiənˈiːɲtʃɪɲə'),
    'c1-nevertheless-formal': ("A dh'aindeoin sin", 'ə ˈɣaɲtʃɪnʲ ˈʃinʲ'),
    'c1-newcomer': ('Neach ùr', 'ˈɲɛx ˈuːɾ'),
    'c1-next-to-nothing': ('Faisc air neoni', 'ˈfaʃkʲ ˈɛɾʲ ˈɲɔnʲɪ'),
    'c1-no-biggie': ('Chan eil e gu diofar', 'xan ˈelʲ ˈɛ kə ˈtʃifəɾ'),
    'c1-nomad': ('Neach-siubhail', 'ˈɲɛxˈʃuvɪlʲ'),
    'c1-notary': ('Nòtair', 'ˈn̪ˠɔːʰt̪ɪɾʲ'),
    'c1-notwithstanding': ("A dh'aindeoin", 'ə ˈɣaɲtʃɪnʲ'),
    'c1-nuanced': ('Mion-chiallach', 'ˈminˈçiəl̪ˠəx'),
    'c1-nuclear-energy': ('Neart-smùirnein', 'ˈɲɛɾt̪ˈsmuːɾʲnʲɪnʲ'),
    'c1-nuclear-fusion': ('Leaghadh-eithne', 'ˈʎɛ.əɣˈenʲə'),
    'c1-occupation-military': ('Sealbhachadh', 'ˈʃal̪ˠavəxəɣ'),
    'c1-odds-and-ends': ('Trealaich', 'ˈt̪ʰɾʲal̪ˠɪç'),
    'c1-ominous': ('Bagarrach', 'ˈpakər̪ˠəx'),
    'c1-on-account-of': ('Air scàth', 'ˈɛɾʲ ˈskaː'),
    'c1-on-average': ('Air chuibheasachd', 'ˈɛɾʲ ˈxuvəsəxk'),
    'c1-on-edge': ('Air bhioran', 'ˈɛɾʲ ˈviɾan'),
    'c1-on-medication': ('Air cungaidh', 'ˈɛɾʲ ˈkʰuŋi'),
    'c1-on-the-fence': ('Gun taobh a ghabhail', 'kən̪ˠ ˈt̪ʰɯːv ə ˈɣavɪlʲ'),
    'c1-on-the-mend': ('Am feabhas', 'əm ˈfɛvəs'),
    'c1-on-the-same-page': ('Den aon bheachd', 'tʃən̪ˠ ˈɯːn ˈvɛxk'),
    'c1-one-in-ten': ('Aon às gach deich', 'ˈɯːn ˈaːs ˈkax ˈtʃeç'),
    'c1-op-ed': ('Colbh beachd', 'ˈkʰɔl̪ˠɔv ˈpɛxk'),
    'c1-open-plan': ('Làr-foscailte', 'ˈl̪ˠaːɾˈfɔskɪlʲtʃə'),
    'c1-open-source': ('Fuaran-coitcheann', 'ˈfuəɾanˈkʰɔʰtʃçən̪ˠ'),
    'c1-opulent': ('Saidhbhir', 'ˈsajvɪɾʲ'),
    'c1-organism': ('Beò-chruth', 'ˈpʲɔːˈxɾuh'),
    'c1-ostensibly': ('Air an uachdar', 'ˈɛɾʲ ən̪ˠ ˈuəxkəɾ'),
    'c1-out-of-shape': ('Ann an droch chumadh', 'ˈaun̪ˠ ən̪ˠ ˈt̪ɾɔx ˈxuməɣ'),
    'c1-out-of-sorts': ('Às a shunnd', 'ˈaːs ə ˈhuːn̪ˠt̪'),
    'c1-outage': ('Tost-lìn', 'ˈt̪ʰɔst̪ˈʎiːnʲ'),
    'c1-outpatient': ('Euslainteach a-muigh', 'ˈiəsl̪ˠɪɲtʃəx əˈmɯj'),
    'c1-outsider': ('Coigreach', 'ˈkʰɔkʲɾʲəx'),
    'c1-over-the-counter': ('Gun òrdugh-lighiche', 'kən̪ˠ ˈɔːɾt̪əɣˈʎi.ɪçə'),
    'c1-over-the-moon': ('Air mo dhòigh', 'ˈɛɾʲ mə ˈɣɔːj'),
    'c1-overgrown': ('Fo luibhean', 'fə ˈl̪ˠuvan'),
    'c1-overhead': ('Coscais-taighe', 'ˈkʰɔskɪʃˈt̪ʰa.ə'),
    'c1-pacing': ('Astar sceòil', 'ˈast̪əɾ ˈskʲɔːlʲ'),
    'c1-packed': ('Loma-làn', 'ˈl̪ˠɔməˈl̪ˠaːn'),
    'c1-pairing': ('Càraideachadh', 'ˈkʰaːɾɪtʃəxəɣ'),
    'c1-palate': ('Càirean', 'ˈkʰaːɾʲan'),
    'c1-paperwork': ('Obair-pàipeir', 'ˈɔpɪɾʲˈpʰaːʰpɪɾʲ'),
    'c1-paradigm': ('Cumadh-smuaine', 'ˈkʰuməɣˈsmuənʲə'),
    'c1-paradox': ('Breug-fhìrinn', 'ˈpɾʲiəkˈiːɾʲɪɲ'),
    'c1-particle': ('Mìrean', 'ˈmiːɾʲan'),
    'c1-passive-aggressive': ('Balbh-nimheil', 'ˈpal̪ˠavˈɲivɪlʲ'),
    'c1-patch-software': ('Paiste', 'ˈpʰaʃtʃə'),
    'c1-payroll': ('Clàr-pàighidh', 'ˈkʰl̪ˠaːɾˈpʰaː.i'),
    'c1-paywall': ('Cachaileith-cìse', 'ˈkʰaxɪlʲɪˈkʲʰiːʃə'),
    'c1-peer-review': ('Breith-cheàrd', 'ˈpɾʲehˈçaːɾt̪'),
    'c1-pendant-light': ('Solas crochte', 'ˈsɔl̪ˠəs ˈkʰɾɔçtʃə'),
    'c1-per-capita': ('Airson gach neach', 'ˈaɾsən ˈkax ˈɲɛx'),
    'c1-phenomenon': ('Iongantas', 'ˈiŋan̪ˠt̪əs'),
    'c1-phishing': ('Dubhan-meallaidh', 'ˈt̪uvanˈmɛl̪ˠi'),
    'c1-photosynthesis': ('Beathachadh-grèine', 'ˈpɛ.əxəɣˈkɾʲeːnʲə'),
    'c1-picturesque': ('Dealbhach', 'ˈtʃal̪ˠavəx'),
    'c1-pilgrimage': ('Taistealachd', 'ˈt̪ʰaʃtʃəl̪ˠəxk'),
    'c1-pilot-episode': ('Scàil-deuchainne', 'ˈskaːlʲˈtʃiəxɪɲə'),
    'c1-pitch-voice': ('Àirde gutha', 'ˈaːɾʲtʃə ˈku.ə'),
    'c1-plot-twist': ('Car san sceul', 'ˈkʰaɾ sən̪ˠ ˈskʲiəl̪ˠ'),
    'c1-plugin': ('Ball-taice', 'ˈpaul̪ˠˈt̪ʰaʰkʲə'),
    'c1-poignant': ('Drùidhteach', 'ˈt̪ɾuːjʰtʃəx'),
    'c1-polarization': ('Scoltadh-sluaigh', 'ˈskɔl̪ˠt̪əɣˈsl̪ˠuəj'),
    'c1-polished': ('Lìomhte', 'ˈʎĩətʃə'),
    'c1-populism': ('Miodal-sluaigh', 'ˈmit̪əl̪ˠˈsl̪ˠuəj'),
    'c1-portfolio': ('Cliabh-ionmhais', 'ˈkʲʰlʲiəvˈinivɪʃ'),
    'c1-pragmatic': ('Gnìomh-chiallach', 'ˈkʲɲiəvˈçiəl̪ˠəx'),
    'c1-premise': ('Bun-smuain', 'ˈpunˈsmuənʲ'),
    'c1-prequel': ('Sceul-sinnsir', 'ˈskʲiəl̪ˠˈʃiːɲʃɪɾʲ'),
    'c1-prerequisite': ('Ro-riatanas', 'ˈr̪ˠɔˈr̪ˠiəʰt̪anəs'),
    'c1-press-conference': ('Mòd-naidheachd', 'ˈmɔːt̪ˈn̪ˠa.əxk'),
    'c1-press-release': ('Fios naidheachd', 'ˈfis ˈn̪ˠa.əxk'),
    'c1-pressure-physics': ('Bruthadh', 'ˈpɾu.əɣ'),
    'c1-presumably': ('A rèir coltais', 'ə ˈr̪ˠeːɾʲ ˈkʰɔl̪ˠt̪ɪʃ'),
    'c1-pretentious': ('Mòrchuiseach', 'ˈmɔːɾxɪʃəx'),
    'c1-primer-paint': ('Bun-pheant', 'ˈpunˈfɛn̪ˠt̪'),
    'c1-pristine': ('Fìor-ghlan', 'ˈfiəɾˈɣl̪ˠan'),
    'c1-privacy': ('Uaigneas', 'ˈuəkʲnʲəs'),
    'c1-proficiency': ('Comasachd', 'ˈkʰɔməsəxk'),
    'c1-prone-to': ('Buailteach do', 'ˈpuəlʲtʃəx t̪ə'),
    'c1-propaganda': ('Seun-sluaigh', 'ˈʃiənˈsl̪ˠuəj'),
    'c1-protagonist': ('Prìomh-charactar', 'ˈpʰɾʲiəvˈxaɾəʰkt̪əɾ'),
    'c1-protege': ('Dalta', 'ˈt̪al̪ˠt̪ə'),
    'c1-provided-that': ('Air chùmhnant gu', 'ˈɛɾʲ ˈxũːnan̪ˠt̪ kə'),
    'c1-public-transit-funding': ('Ionmhas-rathaid', 'ˈinivəsˈr̪ˠahɪtʃ'),
    'c1-punch-list': ('Cunntas-lochdan', 'ˈkʰuːn̪ˠt̪əsˈl̪ˠɔxkan'),
    'c1-quaint': ('Seann-fhasanta', 'ˈʃaun̪ˠˈasan̪ˠt̪ə'),
    'c1-qualitative': ('Càileachdail', 'ˈkʰaːlʲəxkɪlʲ'),
    'c1-quantitative': ('Cainneachdail', 'ˈkʰaɲəxkɪlʲ'),
    'c1-radiation': ('Gath-nimhe', 'ˈkahˈɲivə'),
    'c1-rapport': ('Co-chòrdadh', 'kʰɔˈxɔːɾt̪əɣ'),
    'c1-raspy': ('Piachanach', 'ˈpʰiəxanəx'),
    'c1-reboot': ('Ath-thòiseachadh', 'ˈahˈhɔːʃəxəɣ'),
    'c1-recessed-lighting': ('Solais falaichte', 'ˈsɔl̪ˠɪʃ ˈfal̪ˠɪçtʃə'),
    'c1-reconciliation': ('Rèite', 'ˈr̪ˠeːʰtʃə'),
    'c1-red-tape': ('Riaghailtean gun fheum', 'ˈr̪ˠiə.ɪlʲtʃan kən̪ˠ ˈiəm'),
    'c1-reduction-sauce': ('Sabhs lùghdaichte', 'ˈsavs ˈl̪ˠuːt̪ɪçtʃə'),
    'c1-referral': ('Tar-chur', 'ˈt̪ʰaɾˈxuɾ'),
    'c1-refugee': ('Fògarrach', 'ˈfɔːkər̪ˠəx'),
    'c1-regime': ('Rèim', 'ˈr̪ˠeːm'),
    'c1-register-language': ('Gnè-cainnte', 'ˈkʲɲeːˈkʰaiɲtʃə'),
    'c1-regulation': ('Riaghailt', 'ˈr̪ˠiə.ɪlʲtʃ'),
    'c1-relapse': ('Ath-thuiteam', 'ˈahˈhuʰtʃəm'),
    'c1-release-version': ('Foillseachadh', 'ˈfɔiʎʃəxəɣ'),
    'c1-remission': ('Faochadh', 'ˈfɯːxəɣ'),
    'c1-remote-place': ('Iomallach', 'ˈiməl̪ˠəx'),
    'c1-rent-control': ('Smachd air màl', 'ˈsmaxk ˈɛɾʲ ˈmaːl̪ˠ'),
    'c1-republic': ('Poblachd', 'ˈpʰɔpl̪ˠəxk'),
    'c1-return-on-investment': ('Toradh air tascadh', 'ˈt̪ʰɔɾəɣ ˈɛɾʲ ˈt̪ʰaskəɣ'),
    'c1-revolution': ('Tionndadh-rìoghachd', 'ˈtʃʰuːn̪ˠt̪əɣˈr̪ˠiə.əxk'),
    'c1-rigorous': ('Mionaideach', 'ˈminɪtʃəx'),
    'c1-roast-coffee': ('Ròstadh', 'ˈr̪ˠɔːst̪əɣ'),
    'c1-robust': ('Seasmhach', 'ˈʃɛsvəx'),
    'c1-rookie': ('Tòisiche', 'ˈt̪ʰɔːʃɪçə'),
    'c1-rudimentary': ('Bunasach', 'ˈpunəsəx'),
    'c1-run-down-exhausted': ('Claoidhte', 'ˈkʰl̪ˠɯːjʰtʃə'),
    'c1-run-down-place': ('Air a dhol bhuaithe', 'ˈɛɾʲ ə ˈɣɔl̪ˠ ˈvuə.ə'),
    'c1-run-of-the-mill': ('Àbhaisteach', 'ˈaːvɪʃtʃəx'),
    'c1-sabbatical': ('Fòrladh sàbaid', 'ˈfɔːɾl̪ˠəɣ ˈsaːpɪtʃ'),
    'c1-sample-study': ('Sampall', 'ˈsampəl̪ˠ'),
    'c1-sanctions': ('Bacadh-malairt', 'ˈpaʰkəɣˈmal̪ˠɪɾʲtʃ'),
    'c1-sarcastic': ('Searbhasach', 'ˈʃɛɾɛvəsəx'),
    'c1-scalability': ('Comas-fàis', 'ˈkʰɔməsˈfaːʃ'),
    'c1-scapegoat': ('Cùis-choire', 'ˈkʰuːʃˈxɔɾʲə'),
    'c1-scarce': ('Gann', 'ˈkaun̪ˠ'),
    'c1-scholar': ('Scoilear', 'ˈskɔlʲəɾ'),
    'c1-sconce': ('Solas-balla', 'ˈsɔl̪ˠəsˈpal̪ˠə'),
    'c1-scope-of-work': ('Farsaingeachd na h-obrach', 'ˈfaɾsɪɲəxk nə ˈhɔpɾəx'),
    'c1-screening': ('Taisbeanadh', 'ˈt̪ʰaʃpanəɣ'),
    'c1-seamless': ('Gun fhuaigheal', 'kən̪ˠ ˈuə.əl̪ˠ'),
    'c1-season-finale': ('Deireadh an t-sreatha', 'ˈtʃeɾʲəɣ ən̪ˠ ˈt̪ɾʲɛ.ə'),
    'c1-secluded': ('Uaigneach', 'ˈuəkʲnʲəx'),
    'c1-second-opinion': ('Dàrna beachd', 'ˈt̪aːɾnə ˈpɛxk'),
    'c1-second-rate': ('Den dàrna ìre', 'tʃən̪ˠ ˈt̪aːɾnə ˈiːɾʲə'),
    'c1-second-thoughts': ('Dàrna smaoin', 'ˈt̪aːɾnə ˈsmɯːnʲ'),
    'c1-seedy': ('Mì-chliùiteach', 'ˈmiːˈçlʲuːʰtʃəx'),
    'c1-segment-tv': ('Earrann', 'ˈjaːr̪ˠən̪ˠ'),
    'c1-sensor': ('Sùil-iarainn', 'ˈsuːlʲˈiəɾɪɲ'),
    'c1-sequel': ('Leantainn', 'ˈʎɛn̪ˠt̪ɪɲ'),
    'c1-serene': ('Ciùin', 'ˈkʲʰuːnʲ'),
    'c1-server': ('Gille-lìn', 'ˈkʲiʎəˈʎiːnʲ'),
    'c1-shabby': ('Luideach', 'ˈl̪ˠutʃəx'),
    'c1-shoddy': ('Leibideach', 'ˈʎepɪtʃəx'),
    'c1-showrunner': ('Ceann-scàile', 'ˈkʲʰaun̪ˠˈskaːlʲə'),
    'c1-shrill': ('Scalanta', 'ˈskal̪ˠan̪ˠt̪ə'),
    'c1-sick-and-tired': ('Scìth is searbh dheth', 'ˈskʲiː ɪs ˈʃɛɾɛv ˈjeh'),
    'c1-signature-dish': ('Mias shònraichte', 'ˈmiəs ˈhɔːnɾɪçtʃə'),
    'c1-sizable': ('Meadhanach mòr', 'ˈmɛ.anəx ˈmoːɾ'),
    'c1-skeptical': ('Teagmhach', 'ˈtʃʰekvəx'),
    'c1-sketchy': ('Amharasach', 'ˈavəɾəsəx'),
    'c1-slacker': ('Leiscear', 'ˈʎeʃkʲəɾ'),
    'c1-slang': ('Sràid-chainnt', 'ˈst̪ɾaːtʃˈxaiɲtʃ'),
    'c1-slant-bias': ('Claonadh', 'ˈkʰl̪ˠɯːnəɣ'),
    'c1-sleek': ('Slìom', 'ˈʃlʲiəm'),
    'c1-sleepy-town': ('Cadalach', 'ˈkʰat̪əl̪ˠəx'),
    'c1-slipped-disc': ('Sleamhnachadh-droma', 'ˈʃlʲɛ̃ũnəxəɣˈt̪ɾɔmə'),
    'c1-sloppy': ('Mì-sciobalta', 'ˈmiːˈskʲipəl̪ˠt̪ə'),
    'c1-smart-home': ('Taigh-draoidh', 'ˈt̪ʰɤjˈt̪ɾɯːj'),
    'c1-smug': ('Làn dheth fhèin', 'ˈl̪ˠaːn ˈjeh ˈheːnʲ'),
    'c1-somber': ('Dubhach', 'ˈt̪uvəx'),
    'c1-sommelier': ('Fìon-fhrithealaiche', 'ˈfiənˈɾʲi.əl̪ˠɪçə'),
    'c1-sophisticated': ('Snasail', 'ˈsnasɪlʲ'),
    'c1-source-journalism': ('Tùs', 'ˈt̪ʰuːs'),
    'c1-sovereignty': ('Uachdranas', 'ˈuəxkɾanəs'),
    'c1-sparkling': ('Builgeanach', 'ˈpulʲukʲanəx'),
    'c1-spectrum': ('Bogha-solais', 'ˈpɔ.əˈsɔl̪ˠɪʃ'),
    'c1-speechless-with-joy': ('Gun fhacal le toileachas', 'kən̪ˠ ˈaʰkəl̪ˠ lʲə ˈt̪ʰɔlʲəxəs'),
    'c1-spokesperson': ('Neach-labhairt', 'ˈɲɛxˈl̪ˠavɪɾʲtʃ'),
    'c1-spontaneous': ('Gun ullachadh', 'kən̪ˠ ˈul̪ˠəxəɣ'),
    'c1-sprawling': ('Scaoilte', 'ˈskɯːlʲtʃə'),
    'c1-stakeholder-buy-in': ('Taic luchd-ùidh', 'ˈt̪ʰaʰkʲ ˈl̪ˠuxkˈuːj'),
    'c1-state-of-the-art': ('Ùr-nodha', 'ˈuːɾˈn̪ˠɔ.ə'),
    'c1-storyboard': ('Sreath-dhealbh', 'ˈst̪ɾʲɛhˈjal̪ˠav'),
    'c1-stud-wall': ('Post-balla', 'ˈpʰɔst̪ˈpal̪ˠə'),
    'c1-stuffy': ('Plùchach', 'ˈpʰl̪ˠuːxəx'),
    'c1-subcontractor': ('Fo-cheàrd', 'ˈfɔˈçaːɾt̪'),
    'c1-subfloor': ('Fo-làr', 'ˈfɔˈl̪ˠaːɾ'),
    'c1-sublime': ('Òirdheirc', 'ˈɔːɾʲɪɾʲkʲ'),
    'c1-submissive': ('Strìochdach', 'ˈʃt̪ɾʲiəxkəx'),
    'c1-subpar': ('Fo ìre', 'fə ˈiːɾʲə'),
    'c1-subplot': ('Fo-sceul', 'ˈfɔˈskʲiəl̪ˠ'),
    'c1-subscriber': ('Fo-scrìobhadair', 'ˈfɔˈskɾʲiəvət̪ɪɾʲ'),
    'c1-subtitled': ('Bonn-scrìobhte', 'ˈpɔun̪ˠˈskɾʲiəvtʃə'),
    'c1-summit-meeting': ('Àrd-choinneamh', 'ˈaːɾt̪ˈxɔɲəv'),
    'c1-sump-pump': ('Taoscair-sloic', 'ˈt̪ʰɯːskɪɾʲˈsl̪ˠɔʰkʲ'),
    'c1-surveillance': ('Faire', 'ˈfaɾʲə'),
    'c1-sweet-great': ('Taghta', 'ˈt̪ʰat̪ə'),
    'c1-synergy': ('Co-obrachadh', 'kʰɔˈɔpɾəxəɣ'),
    'c1-tabloid': ('Duilleag-tuaileis', 'ˈt̪uʎakˈt̪ʰuəlʲɪʃ'),
    'c1-tactfully': ('Gu tuigseach', 'kə ˈt̪ʰɯkʲʃəx'),
    'c1-tactless': ('Neo-thuigseach', 'ˈɲɔˈhɯkʲʃəx'),
    'c1-take-it-offline': ('Bruidhnidh sinn air seo air leth', 'ˈpɾɯjnʲi ˈʃiːɲ ˈɛɾʲ ˈʃɔ ˈɛɾʲ ˈʎeh'),
    'c1-taken-aback': ('Air mo chlisceadh', 'ˈɛɾʲ mə ˈçlʲiʃkʲəɣ'),
    'c1-tangible': ('Faicsinneach', 'ˈfaʰkʲʃɪɲəx'),
    'c1-tasting-menu': ('Clàr-bìdh blasaid', 'ˈkʰl̪ˠaːɾˈpiː ˈpl̪ˠasɪtʃ'),
    'c1-telescope': ('Sùil-nan-reul', 'ˈsuːlʲˈn̪ˠanˈr̪ˠiəl̪ˠ'),
    'c1-the-downside': ('An taobh dona', 'ən̪ˠ ˈd̪ɯːv ˈt̪ɔnə'),
    'c1-the-elephant-in-the-room': ('An t-ailbhean san t-seòmar', 'ən̪ˠ ˈt̪ʰalʲavan sən̪ˠ ˈtʃɔːməɾ'),
    'c1-the-last-straw': ('An sop mu dheireadh', 'ən̪ˠ ˈsɔʰp mə ˈjeɾʲəɣ'),
    'c1-the-lions-share': ('Cuid an leòmhainn', 'ˈkʰutʃ ən̪ˠ ˈʎɔːvɪɲ'),
    'c1-the-odds': ('Na cothroman', 'nə ˈkʰɔɾəman'),
    'c1-the-tip-of-the-iceberg': ('Bàrr na beinne-deighe', 'ˈpaːr̪ˠ nə ˈpeɲəˈtʃe.ə'),
    'c1-the-upside': ('An taobh math', 'ən̪ˠ ˈd̪ɯːv ˈma'),
    'c1-the-vast-majority': ("A' mhòr-chuid mhòr", 'ə ˈvoːɾˈxutʃ ˈvoːɾ'),
    'c1-theoretical': ('Teòiridheach', 'ˈtʃʰɔːɾʲɪ.əx'),
    'c1-thereby': ('Le sin', 'lʲə ˈʃinʲ'),
    'c1-thus': ('Mar sin', 'ˈmaɾ ˈʃinʲ'),
    'c1-title-property': ('Còir-seilbhe', 'ˈkʰɔːɾʲˈʃelʲevə'),
    'c1-to-abolish': ('Cur às do', 'ˈkʰuɾ ˈaːs t̪ə'),
    'c1-to-accommodate': ('Toirt àite do', 'ˈt̪ʰɔɾʲtʃ ˈaːʰtʃə t̪ə'),
    'c1-to-adhere': ('Leantainn ri', 'ˈʎɛn̪ˠt̪ɪɲ ɾʲə'),
    'c1-to-allege': ('Cur às leth', 'ˈkʰuɾ ˈaːs ˈʎeh'),
    'c1-to-allude': ('Toirt sanas air', 'ˈt̪ʰɔɾʲtʃ ˈsanəs ˈɛɾʲ'),
    'c1-to-ascertain': ('Faighinn a-mach', 'ˈfa.ɪɲ əˈmax'),
    'c1-to-assimilate': ('Coimeascadh', 'ˈkʰɔməskəɣ'),
    'c1-to-attain': ('Ruigsinn', 'ˈr̪ˠɯkʲʃɪɲ'),
    'c1-to-authorize': ('Ùghdarrachadh', 'ˈuːt̪ər̪ˠəxəɣ'),
    'c1-to-back-up-support': ('Cumail taic ri', 'ˈkʰumɪlʲ ˈt̪ʰaʰkʲ ɾʲə'),
    'c1-to-bail-leave': ('Teicheadh', 'ˈtʃʰeçəɣ'),
    'c1-to-be-admitted-hospital': ('Dol a-steach don ospadal', 'ˈt̪ɔl̪ˠ əˈʃtʃɛx t̪ən̪ˠ ˈɔspət̪əl̪ˠ'),
    'c1-to-be-discharged': ('Faighinn a-mach às an ospadal', 'ˈfa.ɪɲ əˈmax ˈaːs ən̪ˠ ˈɔspət̪əl̪ˠ'),
    'c1-to-be-into': ('Bhith dèidheil air', 'ˈvih ˈtʃeː.ɪlʲ ˈɛɾʲ'),
    'c1-to-beat-around-the-bush': ("Dol mun cuairt air a' chùis", 'ˈt̪ɔl̪ˠ ˈmun ˈkʰuəɾʲtʃ ˈɛɾʲ ə ˈxuːʃ'),
    'c1-to-bellow': ('Beucail', 'ˈpiəʰkɪlʲ'),
    'c1-to-black-out': ('Dol an neul', 'ˈt̪ɔl̪ˠ ən̪ˠ ˈɲiəl̪ˠ'),
    'c1-to-bolster': ('Neartachadh', 'ˈɲɛɾt̪əxəɣ'),
    'c1-to-braise': ('Stobhadh', 'ˈst̪ɔvəɣ'),
    'c1-to-break-off': ('Briseadh dheth', 'ˈpɾʲiʃəɣ ˈjeh'),
    'c1-to-bring-up-mention': ('Togail cuspair', 'ˈt̪ʰɔkɪlʲ ˈkʰuspɪɾʲ'),
    'c1-to-brush-up-on': ('Ùrachadh', 'ˈuːɾəxəɣ'),
    'c1-to-bury-the-hatchet': ('Dèanamh rèite', 'ˈtʃiənəv ˈr̪ˠeːʰtʃə'),
    'c1-to-call-off': ('Cur dheth', 'ˈkʰuɾ ˈjeh'),
    'c1-to-caramelize': ('Ruadhadh-siùcair', 'ˈr̪ˠuə.əɣˈʃuːʰkɪɾʲ'),
    'c1-to-carry-on': ("Cumail a' dol", 'ˈkʰumɪlʲ ə ˈt̪ɔl̪ˠ'),
    'c1-to-catch-on': ('Fàs fasanta', 'ˈfaːs ˈfasan̪ˠt̪ə'),
    'c1-to-chant': ('Èigheach còmhla', 'ˈeː.əx ˈkʰɔ̃ːl̪ˠə'),
    'c1-to-check-out-look-at': ('Toirt sùil air', 'ˈt̪ʰɔɾʲtʃ ˈsuːlʲ ˈɛɾʲ'),
    'c1-to-chill': ('Leigeil anail', 'ˈʎekʲɪlʲ ˈanɪlʲ'),
    'c1-to-chuckle': ('Gàireachdainn fo anail', 'ˈkaːɾʲəxkɪɲ fə ˈanɪlʲ'),
    'c1-to-circle-back': ('Tilleadh thuige', 'ˈtʃʰiʎəɣ ˈhɯkʲə'),
    'c1-to-circumvent': ('Faighinn timcheall air', 'ˈfa.ɪɲ ˈtʃʰimçəl̪ˠ ˈɛɾʲ'),
    'c1-to-coerce': ('Co-èigneachadh', 'kʰɔˈeːkʲnʲəxəɣ'),
    'c1-to-come-across': ('Tachairt air', 'ˈt̪ʰaxɪɾʲtʃ ˈɛɾʲ'),
    'c1-to-come-down-with': ('Fàs tinn', 'ˈfaːs ˈtʃʰiːɲ'),
    'c1-to-compel': ('Toirt air', 'ˈt̪ʰɔɾʲtʃ ˈɛɾʲ'),
    'c1-to-condone': ('Leigeil seachad', 'ˈʎekʲɪlʲ ˈʃɛxət̪'),
    'c1-to-confide': ('Leigeil rùn ri', 'ˈʎekʲɪlʲ ˈr̪ˠuːn ɾʲə'),
    'c1-to-confine': ('Cuingealachadh', 'ˈkʰuɲəl̪ˠəxəɣ'),
    'c1-to-consolidate': ('Daingneachadh', 'ˈt̪aiɲnʲəxəɣ'),
    'c1-to-contemplate': ('Beachdachadh', 'ˈpɛxkəxəɣ'),
    'c1-to-crack-down-on': ('Teannachadh air', 'ˈtʃʰɛn̪ˠəxəɣ ˈɛɾʲ'),
    'c1-to-crash-sleep': ('Fuireach thairis', 'ˈfuɾʲəx ˈhaɾʲɪʃ'),
    'c1-to-curb': ('Srianadh', 'ˈst̪ɾʲiənəɣ'),
    'c1-to-cut-corners': ('Dèanamh obair leibideach', 'ˈtʃiənəv ˈɔpɪɾʲ ˈʎepɪtʃəx'),
    'c1-to-cut-down-on': ('Gearradh sìos air', 'ˈkʲaːr̪ˠəɣ ˈʃiəs ˈɛɾʲ'),
    'c1-to-deduce': ('Dèanamh a-mach', 'ˈtʃiənəv əˈmax'),
    'c1-to-depict': ('Riochdachadh', 'ˈr̪ˠixkəxəɣ'),
    'c1-to-deploy': ('Cur an gnìomh', 'ˈkʰuɾ əŋ ˈkʲɲiəv'),
    'c1-to-deter': ('Cur dheth', 'ˈkʰuɾ ˈjeh'),
    'c1-to-diminish': ('Lùghdachadh', 'ˈl̪ˠuːt̪əxəɣ'),
    'c1-to-disclose': ('Foillseachadh', 'ˈfɔiʎʃəxəɣ'),
    'c1-to-dispel': ('Scaoileadh', 'ˈskɯːlʲəɣ'),
    'c1-to-disrupt': ('Buaireadh', 'ˈpuəɾʲəɣ'),
    'c1-to-ditch': ('Trèigsinn', 'ˈt̪ʰɾʲeːkʲʃɪɲ'),
    'c1-to-divert': ('Claonadh', 'ˈkʰl̪ˠɯːnəɣ'),
    'c1-to-do-without': ('Dèanamh às aonais', 'ˈtʃiənəv ˈaːs ˈɯːnɪʃ'),
    'c1-to-drift-apart': ('Dol bho chèile', 'ˈt̪ɔl̪ˠ ˈvɔ ˈçeːlʲə'),
    'c1-to-drop-the-ball': ('Dèanamh dearmad', 'ˈtʃiənəv ˈtʃɛɾɛmət̪'),
    'c1-to-dwell-on': ('Cnuasachadh air', 'ˈkʰn̪ˠuəsəxəɣ ˈɛɾʲ'),
    'c1-to-elicit': ('Toirt a-mach', 'ˈt̪ʰɔɾʲtʃ əˈmax'),
    'c1-to-embody': ('Pearsanachadh', 'ˈpʰɛɾsanəxəɣ'),
    'c1-to-endorse': ('Cur taic ri', 'ˈkʰuɾ ˈt̪ʰaʰkʲ ɾʲə'),
    'c1-to-entail': ('Ciallachadh', 'ˈkʲʰiəl̪ˠəxəɣ'),
    'c1-to-eradicate': ('Spìonadh às a bhun', 'ˈspiənəɣ ˈaːs ə ˈvun'),
    'c1-to-evoke': ('Dùscadh', 'ˈt̪uːskəɣ'),
    'c1-to-exacerbate': ('Dèanamh nas miosa', 'ˈtʃiənəv ˈn̪ˠas ˈmisə'),
    'c1-to-exemplify': ('Sealltainn mar eisimpleir', 'ˈʃaul̪ˠt̪ɪɲ ˈmaɾ ˈeʃɪmplʲɪɾʲ'),
    'c1-to-fall-apart': ('Tuiteam às a chèile', 'ˈt̪ʰuʰtʃəm ˈaːs ə ˈçeːlʲə'),
    'c1-to-fall-behind': ('Tuiteam air dheireadh', 'ˈt̪ʰuʰtʃəm ˈɛɾʲ ˈjeɾʲəɣ'),
    'c1-to-fall-out': ('Tuiteam a-mach', 'ˈt̪ʰuʰtʃəm əˈmax'),
    'c1-to-fall-through': ('Tuiteam às a chèile', 'ˈt̪ʰuʰtʃəm ˈaːs ə ˈçeːlʲə'),
    'c1-to-fend-off': ('Cumail air falbh', 'ˈkʰumɪlʲ ˈɛɾʲ ˈfal̪ˠav'),
    'c1-to-file-documents': ('Cur a-steach', 'ˈkʰuɾ əˈʃtʃɛx'),
    'c1-to-forge': ('Cumadh', 'ˈkʰuməɣ'),
    'c1-to-foster': ('Brosnachadh', 'ˈpɾɔsnəxəɣ'),
    'c1-to-freak-out': ('Dol às a chiall', 'ˈt̪ɔl̪ˠ ˈaːs ə ˈçiəl̪ˠ'),
    'c1-to-gasp': ('Ploscadh', 'ˈpʰl̪ˠɔskəɣ'),
    'c1-to-get-across': ('Cur an cèill', 'ˈkʰuɾ əŋ ˈɡʲeːʎ'),
    'c1-to-get-away-with': ('Faighinn às le', 'ˈfa.ɪɲ ˈaːs lʲə'),
    'c1-to-get-by': ("Dèanamh a' chùis", 'ˈtʃiənəv ə ˈxuːʃ'),
    'c1-to-get-on-someones-nerves': ('Cur caothach air', 'ˈkʰuɾ ˈkʰɯː.əx ˈɛɾʲ'),
    'c1-to-get-over': ('Faighinn thairis air', 'ˈfa.ɪɲ ˈhaɾʲɪʃ ˈɛɾʲ'),
    'c1-to-get-to-the-point': ('Tighinn chun na puing', 'ˈtʃʰi.ɪɲ ˈxun nə ˈpʰuːiɲkʲ'),
    'c1-to-ghost': ('Dol à sealladh', 'ˈt̪ɔl̪ˠ ˈaː ˈʃɛl̪ˠəɣ'),
    'c1-to-giggle': ('Braoisceil', 'ˈpɾɯːʃkʲɪlʲ'),
    'c1-to-give-in': ('Gèilleadh', 'ˈkʲeːʎəɣ'),
    'c1-to-give-the-benefit-of-the-doubt': ('Toirt buannachd an teagaimh', 'ˈt̪ʰɔɾʲtʃ ˈpuən̪ˠəxk ən̪ˠ ˈdʒekɪv'),
    'c1-to-go-behind-someones-back': ('Dol air cùl', 'ˈt̪ɔl̪ˠ ˈɛɾʲ ˈkʰuːl̪ˠ'),
    'c1-to-go-the-extra-mile': ("Dèanamh barrachd na dh'fheumar", 'ˈtʃiənəv ˈpaːr̪ˠəxk nə ˈjiəməɾ'),
    'c1-to-go-through-experience': ('Dol tro', 'ˈt̪ɔl̪ˠ ˈt̪ʰɾɔ'),
    'c1-to-grab-get': ('Glacadh', 'ˈkl̪ˠaʰkəɣ'),
    'c1-to-grasp': ('Tuigsinn', 'ˈt̪ʰɯkʲʃɪɲ'),
    'c1-to-grumble': ('Gearan', 'ˈkʲɛɾan'),
    'c1-to-have-a-soft-spot-for': ('Bàidh a ghabhail ri', 'ˈpaːj ə ˈɣavɪlʲ ɾʲə'),
    'c1-to-hinder': ('Bacadh', 'ˈpaʰkəɣ'),
    'c1-to-hit-it-off': ('Còrdadh ri chèile', 'ˈkʰɔːɾt̪əɣ ɾʲə ˈçeːlʲə'),
    'c1-to-hit-the-road': ('Togail rithe', 'ˈt̪ʰɔkɪlʲ ˈr̪ˠi.ə'),
    'c1-to-hold-a-grudge': ('Cumail gamhlais', 'ˈkʰumɪlʲ ˈkãũl̪ˠɪʃ'),
    'c1-to-hold-back': ('Cumail air ais', 'ˈkʰumɪlʲ ˈɛɾʲ ˈaʃ'),
    'c1-to-hold-on': ('Cumail ort', 'ˈkʰumɪlʲ ˈɔɾt̪'),
    'c1-to-howl': ('Donnalaich', 'ˈt̪ɔn̪ˠəl̪ˠɪç'),
    'c1-to-hum': ('Crònan', 'ˈkʰɾɔːnan'),
    'c1-to-impede': ('Amladh', 'ˈaml̪ˠəɣ'),
    'c1-to-infer': ('Tuigsinn à', 'ˈt̪ʰɯkʲʃɪɲ ˈaː'),
    'c1-to-infringe': ('Briseadh', 'ˈpɾʲiʃəɣ'),
    'c1-to-instigate': ('Stuigeadh', 'ˈst̪ɯkʲəɣ'),
    'c1-to-iron-out': ('Rèiteachadh', 'ˈr̪ˠeːʰtʃəxəɣ'),
    'c1-to-keep-in-the-loop': ('Cumail fios ri', 'ˈkʰumɪlʲ ˈfis ɾʲə'),
    'c1-to-keep-someone-at-arms-length': ('Cumail aig astar', 'ˈkʰumɪlʲ ˈekʲ ˈast̪əɾ'),
    'c1-to-keep-up-with': ('Cumail suas ri', 'ˈkʰumɪlʲ ˈsuəs ɾʲə'),
    'c1-to-kick-back': ('Gabhail fois', 'ˈkavɪlʲ ˈfɔʃ'),
    'c1-to-leak': ('Leigeil a-mach', 'ˈʎekʲɪlʲ əˈmax'),
    'c1-to-lean-on': ('Cur earbsa ann', 'ˈkʰuɾ ˈɛɾɛpsə ˈaun̪ˠ'),
    'c1-to-let-down': ('Leigeil sìos', 'ˈʎekʲɪlʲ ˈʃiəs'),
    'c1-to-leverage': ('Gabhail brath air', 'ˈkavɪlʲ ˈpɾah ˈɛɾʲ'),
    'c1-to-live-up-to': ('Coileanadh dùil', 'ˈkʰɔlʲanəɣ ˈt̪uːlʲ'),
    'c1-to-look-into': ('Rannsachadh', 'ˈr̪ˠaun̪ˠsəxəɣ'),
    'c1-to-look-out-for': ('Coimhead às dèidh', 'ˈkʰɔvət̪ ˈaːs ˈtʃeːj'),
    'c1-to-look-up-to': ('Coimhead suas ri', 'ˈkʰɔvət̪ ˈsuəs ɾʲə'),
    'c1-to-make-amends': ('Dìoladh', 'ˈtʃiəl̪ˠəɣ'),
    'c1-to-make-up-for': ('Dèanamh suas airson', 'ˈtʃiənəv ˈsuəs ˈaɾsən'),
    'c1-to-master': ('Fàs ealanta air', 'ˈfaːs ˈjal̪ˠan̪ˠt̪ə ˈɛɾʲ'),
    'c1-to-mispronounce': ('Mì-fhuaimneachadh', 'ˈmiːˈuəmnʲəxəɣ'),
    'c1-to-mitigate': ('Maothachadh', 'ˈmɯː.əxəɣ'),
    'c1-to-mumble': ('Brunndail', 'ˈpɾuːn̪ˠt̪ɪlʲ'),
    'c1-to-murmur': ('Monmhar', 'ˈmɔnɔvəɾ'),
    'c1-to-mutter': ('Dranndan', 'ˈt̪ɾaun̪ˠt̪an'),
    'c1-to-nail-it': ('Bualadh na tarraig air a ceann', 'ˈpuəl̪ˠəɣ nə ˈt̪ʰaːr̪ˠɪkʲ ˈɛɾʲ ə ˈkʲʰaun̪ˠ'),
    'c1-to-narrow-down': ('Caolachadh', 'ˈkʰɯːl̪ˠəxəɣ'),
    'c1-to-nod-off': ('Tuiteam na chadal', 'ˈt̪ʰuʰtʃəm nə ˈxat̪əl̪ˠ'),
    'c1-to-nurture': ('Àrach', 'ˈaːɾəx'),
    'c1-to-omit': ('Fàgail às', 'ˈfaːkɪlʲ ˈaːs'),
    'c1-to-onboard': ('Toirt a-steach', 'ˈt̪ʰɔɾʲtʃ əˈʃtʃɛx'),
    'c1-to-opt-out': ('Tarraing a-mach', 'ˈt̪ʰaːr̪ˠɪɲkʲ əˈmax'),
    'c1-to-overturn': ('Tionndadh bun-os-cionn', 'ˈtʃʰuːn̪ˠt̪əɣ ˈpunˈɔsˈkʲʰuːn̪ˠ'),
    'c1-to-pass-out': ('Dol an neul', 'ˈt̪ɔl̪ˠ ən̪ˠ ˈɲiəl̪ˠ'),
    'c1-to-patch-things-up': ('Càradh chùisean', 'ˈkʰaːɾəɣ ˈxuːʃan'),
    'c1-to-phase-out': ('Toirt gu crìch mean air mhean', 'ˈt̪ʰɔɾʲtʃ kə ˈkʰɾʲiːç ˈmɛn ˈɛɾʲ ˈvɛn'),
    'c1-to-pivot': ('Atharrachadh cùrsa', 'ˈa.ər̪ˠəxəɣ ˈkʰuːɾsə'),
    'c1-to-plead': ('Tagradh', 'ˈt̪ʰakɾəɣ'),
    'c1-to-poach': ('Slaopadh', 'ˈsl̪ˠɯːʰpəɣ'),
    'c1-to-point-out': ('Comharrachadh', 'ˈkʰɔvər̪ˠəxəɣ'),
    'c1-to-precede': ('Dol ro', 'ˈt̪ɔl̪ˠ ɾə'),
    'c1-to-preclude': ('Dùnadh a-mach', 'ˈt̪uːnəɣ əˈmax'),
    'c1-to-prompt': ('Piobrachadh', 'ˈpʰipɾəxəɣ'),
    'c1-to-pull-a-muscle': ('Fèith a shìneadh', 'ˈfeː ə ˈhiːnʲəɣ'),
    'c1-to-pull-off': ("Dèanamh a' chùis", 'ˈtʃiənəv ə ˈxuːʃ'),
    'c1-to-put-up-with': ('Cur suas le', 'ˈkʰuɾ ˈsuəs lʲə'),
    'c1-to-qualify': ('Teisteanachadh', 'ˈtʃʰeʃtʃanəxəɣ'),
    'c1-to-ramble': ('Dol air seachran', 'ˈt̪ɔl̪ˠ ˈɛɾʲ ˈʃɛxɾan'),
    'c1-to-ramp-up': ('Àrdachadh', 'ˈaːɾt̪əxəɣ'),
    'c1-to-rant': ('Trod', 'ˈt̪ʰɾɔt̪'),
    'c1-to-read-between-the-lines': ('Leughadh eadar na loidhnichean', 'ˈʎiə.əɣ ˈɛt̪əɾ nə ˈl̪ˠɤinʲɪçan'),
    'c1-to-reconcile-ideas': ('Co-rèiteachadh', 'kʰɔˈr̪ˠeːʰtʃəxəɣ'),
    'c1-to-refrain': ('Seachnadh', 'ˈʃɛxnəɣ'),
    'c1-to-relinquish': ('Leigeil às', 'ˈʎekʲɪlʲ ˈaːs'),
    'c1-to-relocate': ('Imrich', 'ˈimɾʲɪç'),
    'c1-to-render': ('Fàgail', 'ˈfaːkɪlʲ'),
    'c1-to-roll-out': ('Cur an gnìomh', 'ˈkʰuɾ əŋ ˈkʲɲiəv'),
    'c1-to-rule-out': ("Cur às a' chunntas", 'ˈkʰuɾ ˈaːs ə ˈxuːn̪ˠt̪əs'),
    'c1-to-run-into': ('Tachairt ri', 'ˈt̪ʰaxɪɾʲtʃ ɾʲə'),
    'c1-to-run-something-by-someone': ('Faighneachd do chuideigin mu rudeigin', 'ˈfɤjnʲəxk t̪ə ˈxutʃɪkʲɪnʲ mə ˈr̪ˠutʃɪkʲɪnʲ'),
    'c1-to-scale-up': ('Leudachadh', 'ˈʎiət̪əxəɣ'),
    'c1-to-screw-up': ('Dèanamh praiseach', 'ˈtʃiənəv ˈpʰɾaʃəx'),
    'c1-to-scrutinize': ('Scrùdadh', 'ˈskɾuːt̪əɣ'),
    'c1-to-see-eye-to-eye': ('Aontachadh', 'ˈɯːn̪ˠt̪əxəɣ'),
    'c1-to-set-up': ('Stèidheachadh', 'ˈʃtʃeː.əxəɣ'),
    'c1-to-settle-down': ('Socrachadh', 'ˈsɔʰkɾəxəɣ'),
    'c1-to-settle-for': ('Dèanamh an gnothach le', 'ˈtʃiənəv əŋ ˈkn̪ˠɔ.əx lʲə'),
    'c1-to-shriek': ('Screuchail', 'ˈskɾʲiəxɪlʲ'),
    'c1-to-sign-off-on': ('Ceadachadh', 'ˈkʲʰɛt̪əxəɣ'),
    'c1-to-sleep-like-a-log': ('Cadal trom', 'ˈkʰat̪əl̪ˠ ˈt̪ʰɾɔum'),
    'c1-to-slur': ('Bruidhinn gu tiugh', 'ˈpɾu.ɪɲ kə ˈtʃʰu'),
    'c1-to-snap-at-someone': ('Freagairt gu grad', 'ˈfɾʲekɪɾʲtʃ kə ˈkɾat̪'),
    'c1-to-snicker': ('Gàireachdainn gu fanaideach', 'ˈkaːɾʲəxkɪɲ kə ˈfanɪtʃəx'),
    'c1-to-sob': ('Caoineadh gu goirt', 'ˈkʰɯːnʲəɣ kə ˈkɔɾʲtʃ'),
    'c1-to-sort-out': ('Rèiteachadh', 'ˈr̪ˠeːʰtʃəxəɣ'),
    'c1-to-stand-for': ('Seasamh airson', 'ˈʃɛsəv ˈaɾsən'),
    'c1-to-stem-from': ('Èirigh à', 'ˈeːɾʲi ˈaː'),
    'c1-to-stick-to': ('Cumail ri', 'ˈkʰumɪlʲ ɾʲə'),
    'c1-to-stick-up-for': ('Seasamh airson', 'ˈʃɛsəv ˈaɾsən'),
    'c1-to-stipulate': ('Sònrachadh', 'ˈsɔːnɾəxəɣ'),
    'c1-to-stutter': ('Bruidhinn gu gagach', 'ˈpɾu.ɪɲ kə ˈkakəx'),
    'c1-to-substantiate': ('Dearbhadh', 'ˈtʃɛɾɛvəɣ'),
    'c1-to-surpass': ('Dol thairis air', 'ˈt̪ɔl̪ˠ ˈhaɾʲɪʃ ˈɛɾʲ'),
    'c1-to-synthesize': ('Co-chur', 'kʰɔˈxuɾ'),
    'c1-to-take-a-turn-for-the-worse': ('Fàs nas miosa', 'ˈfaːs ˈn̪ˠas ˈmisə'),
    'c1-to-take-after': ('Dol ri', 'ˈt̪ɔl̪ˠ ɾʲə'),
    'c1-to-take-for-granted': ('Gabhail mar rud cinnteach', 'ˈkavɪlʲ ˈmaɾ ˈr̪ˠut̪ ˈkʲʰiːɲtʃəx'),
    'c1-to-take-on-a-task': ('Gabhail os làimh', 'ˈkavɪlʲ ˈɔs ˈl̪ˠaːv'),
    'c1-to-take-over': ('Gabhail thairis', 'ˈkavɪlʲ ˈhaɾʲɪʃ'),
    'c1-to-the-extent-that': ("Chun na h-ìre 's gun", 'ˈxun nə ˈhiːɾʲə s kən̪ˠ'),
    'c1-to-think-outside-the-box': ('Smaoineachadh gu cruthachail', 'ˈsmɯːnʲəxəɣ kə ˈkʰɾu.əxɪlʲ'),
    'c1-to-thrive': ('Soirbheachadh', 'ˈsɔɾʲɔvəxəɣ'),
    'c1-to-toss-and-turn': ("Tionndadh a-null 's a-nall", 'ˈtʃʰuːn̪ˠt̪əɣ əˈn̪ˠuːl̪ˠ s əˈn̪ˠaul̪ˠ'),
    'c1-to-touch-base': ('Cur fios', 'ˈkʰuɾ ˈfis'),
    'c1-to-touch-on': ('Beantainn ri', 'ˈpɛn̪ˠt̪ɪɲ ɾʲə'),
    'c1-to-trend': ('Èirigh-air-beul', 'ˈeːɾʲiˈɛɾʲˈpiəl̪ˠ'),
    'c1-to-turn-down': ('Diùltadh', 'ˈtʃuːl̪ˠt̪əɣ'),
    'c1-to-turn-up': ('Nochdadh', 'ˈn̪ˠɔxkəɣ'),
    'c1-to-undermine': ('Lagachadh', 'ˈl̪ˠakəxəɣ'),
    'c1-to-unveil': ('Nochdadh', 'ˈn̪ˠɔxkəɣ'),
    'c1-to-uphold': ('Cumail suas', 'ˈkʰumɪlʲ ˈsuəs'),
    'c1-to-wail': ('Caoidh', 'ˈkʰɯːj'),
    'c1-to-waive': ('Toirt seachad còir', 'ˈt̪ʰɔɾʲtʃ ˈʃɛxət̪ ˈkʰɔːɾʲ'),
    'c1-to-wear-off': ('Caitheamh air falbh', 'ˈkʰa.əv ˈɛɾʲ ˈfal̪ˠav'),
    'c1-to-wear-ones-heart-on-ones-sleeve': ('Sealltainn fhaireachdainnean gu foscailte', 'ˈʃaul̪ˠt̪ɪɲ ˈaɾʲəxkɪɲan kə ˈfɔskɪlʲtʃə'),
    'c1-to-weigh-up': ('Cothromachadh', 'ˈkʰɔɾəməxəɣ'),
    'c1-to-whine': ('Cànranaich', 'ˈkʰaːnɾanɪç'),
    'c1-to-wind-down': ('Lasachadh', 'ˈl̪ˠasəxəɣ'),
    'c1-to-wind-up-end-up': ('Ruighinn mu dheireadh', 'ˈr̪ˠu.ɪɲ mə ˈjeɾʲəɣ'),
    'c1-to-wing-it': ('Dèanamh gun ullachadh', 'ˈtʃiənəv kən̪ˠ ˈul̪ˠəxəɣ'),
    'c1-to-work-out-resolve': ('Obrachadh a-mach', 'ˈɔpɾəxəɣ əˈmax'),
    'c1-to-wrap-up': ('Crìochnachadh', 'ˈkʰɾʲiəxnəxəɣ'),
    'c1-to-yield': ('Toirt toradh', 'ˈt̪ʰɔɾʲtʃ ˈt̪ʰɔɾəɣ'),
    'c1-to-zero-in-on': ('Cuimseachadh air', 'ˈkʰumʃəxəɣ ˈɛɾʲ'),
    'c1-to-zone-out': ('Dol am bruadar', 'ˈt̪ɔl̪ˠ əm ˈpɾuət̪əɾ'),
    'c1-top-notch': ('Air leth math', 'ˈɛɾʲ ˈʎeh ˈma'),
    'c1-torn-between': ('Air mo scaradh eadar', 'ˈɛɾʲ mə ˈskaɾəɣ ˈɛt̪əɾ'),
    'c1-touristy': ('Làn luchd-turais', 'ˈl̪ˠaːn ˈl̪ˠuxkˈt̪ʰuɾɪʃ'),
    'c1-treaty': ('Cùmhnant', 'ˈkʰũːnan̪ˠt̪'),
    'c1-trendy': ('Fasanta', 'ˈfasan̪ˠt̪ə'),
    'c1-tucked-away': ('Am falach', 'əm ˈfal̪ˠəx'),
    'c1-turnover': ('Cuairt-malairte', 'ˈkʰuəɾʲtʃˈmal̪ˠɪɾʲtʃə'),
    'c1-two-factor-authentication': ('Glas-dhùbailte', 'ˈkl̪ˠasˈɣuːpɪlʲtʃə'),
    'c1-twofold': ('Dà-fhillte', 'ˈt̪aːˈiːʎtʃə'),
    'c1-ubiquitous': ('Uile-làthaireach', 'ˈulʲəˈl̪ˠaːhɪɾʲəx'),
    'c1-umami': ('Blas-eanraich', 'ˈpl̪ˠasˈɛnɾɪç'),
    'c1-umpteen': ('Iomadh', 'ˈiməɣ'),
    'c1-uncanny': ('Annasach', 'ˈan̪ˠəsəx'),
    'c1-unconventional': ('Neo-ghnàthach', 'ˈɲɔˈɣnaː.əx'),
    'c1-under-the-knife': ('Fon scian', 'ˈfɔn ˈskʲiən'),
    'c1-under-the-weather': ('Leth-tinn', 'ˈʎehˈtʃʰiːɲ'),
    'c1-underdog': ('Fear gun dùil', 'ˈfɛɾ kən̪ˠ ˈt̪uːlʲ'),
    'c1-undoubtedly': ('Gun teagamh', 'kən̪ˠ ˈtʃʰekəv'),
    'c1-universal-basic-income': ('Cuibhreann-coitcheann', 'ˈkʰuvɾʲən̪ˠˈkʰɔʰtʃçən̪ˠ'),
    'c1-universal-healthcare': ('Leigheas-coitcheann', 'ˈʎe.əsˈkʰɔʰtʃçən̪ˠ'),
    'c1-universe': ('Cruinne-cè', 'ˈkʰɾɯɲəˈkʲʰeː'),
    'c1-unspoiled': ('Gun mhilleadh', 'kən̪ˠ ˈviʎəɣ'),
    'c1-uprising': ('Ar-a-mach', 'ˈaɾˈaˈmax'),
    'c1-upscale': ('Galanta', 'ˈkal̪ˠan̪ˠt̪ə'),
    'c1-uptight': ('Teann', 'ˈtʃʰaun̪ˠ'),
    'c1-urban-sprawl': ('Scaoileadh bailteil', 'ˈskɯːlʲəɣ ˈpalʲtʃɪlʲ'),
    'c1-user-friendly': ('Furasta a chleachdadh', 'ˈfuɾəst̪ə ə ˈçlʲɛxkəɣ'),
    'c1-vacuum': ('Falamhachd', 'ˈfal̪ˠəvəxk'),
    'c1-variable': ('Sùim-chaochlaideach', 'ˈsuːmˈxɯːxl̪ˠɪtʃəx'),
    'c1-velocity': ('Astar', 'ˈast̪əɾ'),
    'c1-vent': ('Fionnaran', 'ˈfin̪ˠəɾan'),
    'c1-venture-capital': ('Ionmhas-cunnairt', 'ˈinivəsˈkʰun̪ˠɪɾʲtʃ'),
    'c1-veteran-experienced': ('Seann-làmh', 'ˈʃaun̪ˠˈl̪ˠaːv'),
    'c1-vibrant': ('Brìoghmhor', 'ˈpɾʲiəvəɾ'),
    'c1-viewership': ('Luchd-amhairc', 'ˈl̪ˠuxkˈavɪɾʲkʲ'),
    'c1-vindictive': ('Dìoghaltach', 'ˈtʃiə.əl̪ˠt̪əx'),
    'c1-vintage-wine': ('Bliadhna an fhìona', 'ˈplʲiənə ən̪ˠ ˈiənə'),
    'c1-viral': ('Scaoilteach', 'ˈskɯːlʲtʃəx'),
    'c1-vivid': ('Beòthail', 'ˈpʲɔːhɪlʲ'),
    'c1-voice-over': ('Guth-falaich', 'ˈkuhˈfal̪ˠɪç'),
    'c1-voter-turnout': ('Tional-taghaidh', 'ˈtʃʰinəl̪ˠˈt̪ʰa.i'),
    'c1-walkable': ('Freagarrach airson coiseachd', 'ˈfɾʲekər̪ˠəx ˈaɾsən ˈkʰɔʃəxk'),
    'c1-water-heater': ('Teallach-uisce', 'ˈtʃʰɛl̪ˠəxˈɯʃkʲə'),
    'c1-water-scarcity': ('Gainne uisce', 'ˈkaɲə ˈɯʃkʲə'),
    'c1-wavelength': ('Ceum-tuinne', 'ˈkʲʰiəmˈt̪ʰɯɲə'),
    'c1-wealth-gap': ('Beàrn beartais', 'ˈpʲaːɾn ˈpɛɾt̪ɪʃ'),
    'c1-wear-and-tear': ('Caitheamh is reubadh', 'ˈkʰa.əv ɪs ˈr̪ˠiəpəɣ'),
    'c1-wearable': ('Seun-làimhe', 'ˈʃiənˈl̪ˠaːvə'),
    'c1-welfare': ('Sochair', 'ˈsɔxɪɾʲ'),
    'c1-well-done': ('Làn-bhruich', 'ˈl̪ˠaːnˈvɾuç'),
    'c1-well-kept': ('Sciobalta', 'ˈskʲipəl̪ˠt̪ə'),
    'c1-whereby': ('Leis am', 'ˈʎeʃ əm'),
    'c1-whimsical': ('Luaineach', 'ˈl̪ˠuənʲəx'),
    'c1-whistleblower': ('Neach-foillseachaidh', 'ˈɲɛxˈfɔiʎʃəxi'),
    'c1-whiz': ('Sàr-làmh', 'ˈsaːɾˈl̪ˠaːv'),
    'c1-wide-shot': ('Sealladh-raoin', 'ˈʃɛl̪ˠəɣˈr̪ˠɯːnʲ'),
    'c1-wildcard': ('Cairt fhiadhaich', 'ˈkʰaɾʲtʃ ˈiə.ɪç'),
    'c1-win-win': ('Buannachd don dà thaobh', 'ˈpuən̪ˠəxk t̪ən̪ˠ ˈt̪aː ˈhɯːv'),
    'c1-wistful': ('Cianail', 'ˈkʲʰiənɪlʲ'),
    'c1-with-a-view-to': ('Leis an amas', 'ˈʎeʃ ən̪ˠ ˈaməs'),
    'c1-witty': ('Geur-chainnteach', 'ˈkʲiəɾˈxaiɲtʃəx'),
    'c1-workaholic': ('Tràill-obrach', 'ˈt̪ʰɾaːʎˈɔpɾəx'),
    'c1-wound-up': ('Air a chur thuige', 'ˈɛɾʲ ə ˈxuɾ ˈhɯkʲə'),
    'c1-write-off': ('Dubhadh-às', 'ˈt̪uvəɣˈaːs'),
    'c1-yes-man': ('Miodalaiche', 'ˈmit̪əl̪ˠɪçə'),
    'c1-zest': ('Rùsc', 'ˈr̪ˠuːsk'),
    'c1-zoning-variance': ('Saoradh-fearainn', 'ˈsɯːɾəɣˈfɛɾɪɲ'),
}
