# -*- coding: utf-8 -*-
LANG = 'sv'
WORDS = {
    'a1-hello': ('Hej', None),
    'a1-goodbye': ('Hej då', None),
    'a1-please': ('Snälla', None),
    'a1-thank-you': ('Tack', None),
    'a1-excuse-me': ('Ursäkta', None),
    'a1-sorry': ('Förlåt', None),
    'a1-yes': ('Ja', None),
    'a1-no': ('Nej', None),
    'a1-my-name-is-alex': ('Jag heter Alex', None),
    'a1-whats-your-name': ('Vad heter du?', None),
    'a1-nice-to-meet-you': ('Trevligt att träffas', None),
    'a1-how-are-you': ('Hur mår du?', None),
    'a1-mother': ('Mor', None),
    'a1-father': ('Far', None),
    'a1-sister': ('Syster', None),
    'a1-brother': ('Bror', None),
    'a1-friend': ('Vän', None),
    'a1-child': ('Barn', None),
    'a1-today': ('Idag', None),
    'a1-tomorrow': ('Imorgon', None),
    'a1-yesterday': ('Igår', None),
    'a1-now': ('Nu', None),
    'a1-morning': ('Morgon', None),
    'a1-night': ('Natt', None),
    'a1-house': ('Hus', None),
    'a1-where-is-it': ('Var är det?', None),
    'a1-left': ('Vänster', None),
    'a1-right': ('Höger', None),
    'a1-store': ('Butik', None),
    'a1-bathroom': ('Badrum', None),
    'a1-water': ('Vatten', None),
    'a1-bread': ('Bröd', None),
    'a1-coffee': ('Kaffe', None),
    'a1-tea': ('Te', None),
    'a1-delicious': ('Läcker', None),
    'a1-spicy': ('Kryddig', None),
    'a1-good-morning': ('God morgon', None),
    'a1-good-evening': ('God kväll', None),
    'a1-good-night': ('God natt', None),
    'a1-youre-welcome': ('Varsågod', None),
    'a1-see-you-soon': ('Vi ses snart', None),
    'a1-see-you-tomorrow': ('Vi ses imorgon', None),
    'a1-welcome': ('Välkommen', None),
    'a1-cheers': ('Skål!', None),
    'a1-congratulations': ('Grattis', None),
    'a1-happy-birthday': ('Grattis på födelsedagen', None),
    'a1-good-luck': ('Lycka till', None),
    'a1-have-a-nice-day': ('Ha en bra dag', None),
    'a1-take-care': ('Ta hand om dig', None),
    'a1-bless-you': ('Prosit', None),
    'a1-enjoy-your-meal': ('Smaklig måltid', None),
    'a1-nice-to-see-you': ('Roligt att se dig', None),
    'a1-long-time-no-see': ('Länge sedan sist', None),
    'a1-goodbye-for-now': ('Vi ses', None),
    'a1-i': ('Jag', None),
    'a1-you': ('Du', None),
    'a1-he': ('Han', None),
    'a1-she': ('Hon', None),
    'a1-we': ('Vi', None),
    'a1-they': ('De', None),
    'a1-man': ('Man', None),
    'a1-woman': ('Kvinna', None),
    'a1-boy': ('Pojke', None),
    'a1-girl': ('Flicka', None),
    'a1-person': ('Person', None),
    'a1-people': ('Människor', None),
    'a1-name': ('Namn', None),
    'a1-mister': ('Herr', None),
    'a1-madam': ('Fru', None),
    'a1-im-fine': ('Jag mår bra', None),
    'a1-and-you': ('Och du?', None),
    'a1-where-are-you-from': ('Var kommer du ifrån?', None),
    'a1-im-from-the-united-states': ('Jag kommer från USA', None),
    'a1-friend-female': ('Väninna', None),
    'a1-family': ('Familj', None),
    'a1-parents': ('Föräldrar', None),
    'a1-son': ('Son', None),
    'a1-daughter': ('Dotter', None),
    'a1-husband': ('Make', None),
    'a1-wife': ('Hustru', None),
    'a1-grandmother': ('Farmor', None),
    'a1-grandfather': ('Farfar', None),
    'a1-baby': ('Bebis', None),
    'a1-uncle': ('Farbror', None),
    'a1-aunt': ('Moster', None),
    'a1-cousin': ('Kusin', None),
    'a1-boyfriend': ('Pojkvän', None),
    'a1-girlfriend': ('Flickvän', None),
    'a1-neighbor': ('Granne', None),
    'a1-children': ('Barn', None),
    'a1-older-brother': ('Storebror', None),
    'a1-younger-sister': ('Lillasyster', None),
    'a1-pet': ('Husdjur', None),
    'a1-married': ('Gift', None),
    'a1-one': ('Ett', None),
    'a1-two': ('Två', None),
    'a1-three': ('Tre', None),
    'a1-four': ('Fyra', None),
    'a1-five': ('Fem', None),
    'a1-six': ('Sex', None),
    'a1-seven': ('Sju', None),
    'a1-eight': ('Åtta', None),
    'a1-nine': ('Nio', None),
    'a1-ten': ('Tio', None),
    'a1-eleven': ('Elva', None),
    'a1-twelve': ('Tolv', None),
    'a1-thirteen': ('Tretton', None),
    'a1-fourteen': ('Fjorton', None),
    'a1-fifteen': ('Femton', None),
    'a1-sixteen': ('Sexton', None),
    'a1-seventeen': ('Sjutton', None),
    'a1-eighteen': ('Arton', None),
    'a1-nineteen': ('Nitton', None),
    'a1-twenty': ('Tjugo', None),
    'a1-zero': ('Noll', None),
    'a1-thirty': ('Trettio', None),
    'a1-forty': ('Fyrtio', None),
    'a1-fifty': ('Femtio', None),
    'a1-sixty': ('Sextio', None),
    'a1-seventy': ('Sjuttio', None),
    'a1-eighty': ('Åttio', None),
    'a1-ninety': ('Nittio', None),
    'a1-one-hundred': ('Hundra', None),
    'a1-one-thousand': ('Tusen', None),
    'a1-one-million': ('En miljon', None),
    'a1-first': ('Första', None),
    'a1-second': ('Andra', None),
    'a1-third': ('Tredje', None),
    'a1-half': ('Hälft', None),
    'a1-many': ('Många', None),
    'a1-few': ('Få', None),
    'a1-all': ('Allt', None),
    'a1-some': ('Några', None),
    'a1-nothing': ('Ingenting', None),
    'a1-number': ('Siffra', None),
    'a1-more': ('Mer', None),
    'a1-less': ('Mindre', None),
    'a1-enough': ('Tillräckligt', None),
    'a1-red': ('Röd', None),
    'a1-blue': ('Blå', None),
    'a1-green': ('Grön', None),
    'a1-yellow': ('Gul', None),
    'a1-black': ('Svart', None),
    'a1-white': ('Vit', None),
    'a1-orange-color': ('Orange', None),
    'a1-pink': ('Rosa', None),
    'a1-purple': ('Lila', None),
    'a1-brown': ('Brun', None),
    'a1-gray': ('Grå', None),
    'a1-color': ('Färg', None),
    'a1-light-color': ('Ljus', None),
    'a1-dark': ('Mörk', None),
    'a1-circle': ('Cirkel', None),
    'a1-square': ('Kvadrat', None),
    'a1-triangle': ('Triangel', None),
    'a1-line': ('Linje', None),
    'a1-shape': ('Form', None),
    'a1-big': ('Stor', None),
    'a1-small': ('Liten', None),
    'a1-long': ('Lång', None),
    'a1-short-length': ('Kort', None),
    'a1-round': ('Rund', None),
    'a1-afternoon': ('Eftermiddag', None),
    'a1-evening': ('Kväll', None),
    'a1-day': ('Dag', None),
    'a1-week': ('Vecka', None),
    'a1-month': ('Månad', None),
    'a1-year': ('År', None),
    'a1-hour': ('Timme', None),
    'a1-minute': ('Minut', None),
    'a1-later': ('Senare', None),
    'a1-early': ('Tidigt', None),
    'a1-late': ('Sent', None),
    'a1-always': ('Alltid', None),
    'a1-never': ('Aldrig', None),
    'a1-sometimes': ('Ibland', None),
    'a1-often': ('Ofta', None),
    'a1-soon': ('Snart', None),
    'a1-again': ('Igen', None),
    'a1-its-late': ('Det är sent', None),
    'a1-tonight': ('Ikväll', None),
    'a1-before': ('Före', None),
    'a1-after': ('Efter', None),
    'a1-noon': ('Mitt på dagen', None),
    'a1-midnight': ('Midnatt', None),
    'a1-monday': ('Måndag', None),
    'a1-tuesday': ('Tisdag', None),
    'a1-wednesday': ('Onsdag', None),
    'a1-thursday': ('Torsdag', None),
    'a1-friday': ('Fredag', None),
    'a1-saturday': ('Lördag', None),
    'a1-sunday': ('Söndag', None),
    'a1-weekend': ('Helg', None),
    'a1-january': ('Januari', None),
    'a1-february': ('Februari', None),
    'a1-march': ('Mars', None),
    'a1-april': ('April', None),
    'a1-may': ('Maj', None),
    'a1-june': ('Juni', None),
    'a1-july': ('Juli', None),
    'a1-august': ('Augusti', None),
    'a1-september': ('September', None),
    'a1-october': ('Oktober', None),
    'a1-november': ('November', None),
    'a1-december': ('December', None),
    'a1-spring': ('Vår', None),
    'a1-summer': ('Sommar', None),
    'a1-autumn': ('Höst', None),
    'a1-winter': ('Vinter', None),
    'a1-birthday': ('Födelsedag', None),
    'a1-holiday': ('Helgdag', None),
    'a1-room': ('Rum', None),
    'a1-kitchen': ('Kök', None),
    'a1-bedroom': ('Sovrum', None),
    'a1-door': ('Dörr', None),
    'a1-window': ('Fönster', None),
    'a1-table': ('Bord', None),
    'a1-chair': ('Stol', None),
    'a1-bed': ('Säng', None),
    'a1-street': ('Gata', None),
    'a1-city': ('Stad', None),
    'a1-country': ('Land', None),
    'a1-school': ('Skola', None),
    'a1-hospital': ('Sjukhus', None),
    'a1-bank': ('Bank', None),
    'a1-restaurant': ('Restaurang', None),
    'a1-hotel': ('Hotell', None),
    'a1-market': ('Marknad', None),
    'a1-park': ('Park', None),
    'a1-church': ('Kyrka', None),
    'a1-office': ('Kontor', None),
    'a1-here': ('Här', None),
    'a1-there': ('Där', None),
    'a1-straight-ahead': ('Rakt fram', None),
    'a1-near': ('Nära', None),
    'a1-far': ('Långt bort', None),
    'a1-floor-level': ('Våning', None),
    'a1-garden': ('Trädgård', None),
    'a1-wall': ('Vägg', None),
    'a1-milk': ('Mjölk', None),
    'a1-rice': ('Ris', None),
    'a1-meat': ('Kött', None),
    'a1-fish-food': ('Fisk', None),
    'a1-chicken': ('Kyckling', None),
    'a1-egg': ('Ägg', None),
    'a1-fruit': ('Frukt', None),
    'a1-vegetables': ('Grönsaker', None),
    'a1-apple': ('Äpple', None),
    'a1-sugar': ('Socker', None),
    'a1-salt': ('Salt', None),
    'a1-beer': ('Öl', None),
    'a1-wine': ('Vin', None),
    'a1-juice': ('Juice', None),
    'a1-breakfast': ('Frukost', None),
    'a1-lunch': ('Lunch', None),
    'a1-dinner': ('Middag', None),
    'a1-im-hungry': ('Jag är hungrig', None),
    'a1-im-thirsty': ('Jag är törstig', None),
    'a1-cheese': ('Ost', None),
    'a1-soup': ('Soppa', None),
    'a1-sweet': ('Söt', None),
    'a1-food': ('Mat', None),
    'a1-drink-noun': ('Dryck', None),
    'a1-head': ('Huvud', None),
    'a1-hand': ('Hand', None),
    'a1-eye': ('Öga', None),
    'a1-foot': ('Fot', None),
    'a1-mouth': ('Mun', None),
    'a1-nose': ('Näsa', None),
    'a1-ear': ('Öra', None),
    'a1-arm': ('Arm', None),
    'a1-leg': ('Ben', None),
    'a1-heart': ('Hjärta', None),
    'a1-hair': ('Hår', None),
    'a1-face': ('Ansikte', None),
    'a1-back-body': ('Rygg', None),
    'a1-stomach': ('Mage', None),
    'a1-tooth': ('Tand', None),
    'a1-finger': ('Finger', None),
    'a1-body': ('Kropp', None),
    'a1-blood': ('Blod', None),
    'a1-neck': ('Hals', None),
    'a1-shoulder': ('Axel', None),
    'a1-knee': ('Knä', None),
    'a1-skin': ('Hud', None),
    'a1-shirt': ('Skjorta', None),
    'a1-pants': ('Byxor', None),
    'a1-shoes': ('Skor', None),
    'a1-dress': ('Klänning', None),
    'a1-hat': ('Hatt', None),
    'a1-coat': ('Kappa', None),
    'a1-jacket': ('Jacka', None),
    'a1-socks': ('Strumpor', None),
    'a1-skirt': ('Kjol', None),
    'a1-bag': ('Väska', None),
    'a1-glasses': ('Glasögon', None),
    'a1-watch-wrist': ('Armbandsur', None),
    'a1-umbrella': ('Paraply', None),
    'a1-to-wear': ('Bära', None),
    'a1-sweater': ('Tröja', None),
    'a1-t-shirt': ('T-shirt', None),
    'a1-scarf': ('Halsduk', None),
    'a1-gloves': ('Handskar', None),
    'a1-clothes': ('Kläder', None),
    'a1-size': ('Storlek', None),
    'a1-to-be': ('Vara', None),
    'a1-to-have': ('Ha', None),
    'a1-to-do': ('Göra', None),
    'a1-to-go': ('Åka', None),
    'a1-to-come': ('Komma', None),
    'a1-to-want': ('Vilja', None),
    'a1-to-be-able-to': ('Kunna', None),
    'a1-to-know': ('Veta', None),
    'a1-to-see': ('Se', None),
    'a1-to-say': ('Säga', None),
    'a1-to-eat': ('Äta', None),
    'a1-to-drink': ('Dricka', None),
    'a1-to-sleep': ('Sova', None),
    'a1-to-live': ('Bo', None),
    'a1-to-work': ('Arbeta', None),
    'a1-to-speak': ('Tala', None),
    'a1-to-understand': ('Förstå', None),
    'a1-to-like': ('Tycka om', None),
    'a1-to-need': ('Behöva', None),
    'a1-to-give': ('Ge', None),
    'a1-to-take': ('Ta', None),
    'a1-to-think': ('Tänka', None),
    'a1-to-buy': ('Köpa', None),
    'a1-to-help': ('Hjälpa', None),
    'a1-to-open': ('Öppna', None),
    'a1-to-close': ('Stänga', None),
    'a1-to-look-for': ('Leta efter', None),
    'a1-to-find': ('Hitta', None),
    'a1-to-wait': ('Vänta', None),
    'a1-to-call-phone': ('Ringa', None),
    'a1-to-read': ('Läsa', None),
    'a1-to-write': ('Skriva', None),
    'a1-to-listen': ('Lyssna', None),
    'a1-to-learn': ('Lära sig', None),
    'a1-to-play': ('Leka', None),
    'a1-to-walk': ('Gå', None),
    'a1-to-run': ('Springa', None),
    'a1-to-sit': ('Sätta sig', None),
    'a1-to-stand': ('Stå', None),
    'a1-to-arrive': ('Anlända', None),
    'a1-to-leave': ('Lämna', None),
    'a1-to-return': ('Återvända', None),
    'a1-to-put': ('Lägga', None),
    'a1-to-bring': ('Ta med', None),
    'a1-to-ask': ('Fråga', None),
    'a1-to-answer': ('Svara', None),
    'a1-to-love': ('Älska', None),
    'a1-to-pay': ('Betala', None),
    'a1-good': ('Bra', None),
    'a1-bad': ('Dålig', None),
    'a1-new': ('Ny', None),
    'a1-old-thing': ('Gammal', None),
    'a1-young': ('Ung', None),
    'a1-hot': ('Varm', None),
    'a1-cold': ('Kall', None),
    'a1-happy': ('Glad', None),
    'a1-sad': ('Ledsen', None),
    'a1-beautiful': ('Vacker', None),
    'a1-ugly': ('Ful', None),
    'a1-easy': ('Lätt', None),
    'a1-difficult': ('Svår', None),
    'a1-fast': ('Snabb', None),
    'a1-slow': ('Långsam', None),
    'a1-cheap': ('Billig', None),
    'a1-expensive': ('Dyr', None),
    'a1-full': ('Full', None),
    'a1-empty': ('Tom', None),
    'a1-clean': ('Ren', None),
    'a1-dirty': ('Smutsig', None),
    'a1-strong': ('Stark', None),
    'a1-weak': ('Svag', None),
    'a1-important': ('Viktig', None),
    'a1-what': ('Vad', None),
    'a1-who': ('Vem', None),
    'a1-where': ('Var', None),
    'a1-when': ('När', None),
    'a1-why': ('Varför', None),
    'a1-how': ('Hur', None),
    'a1-how-many': ('Hur många', None),
    'a1-which': ('Vilken', None),
    'a1-and': ('Och', None),
    'a1-or': ('Eller', None),
    'a1-but': ('Men', None),
    'a1-because': ('Eftersom', None),
    'a1-with': ('Med', None),
    'a1-without': ('Utan', None),
    'a1-for': ('För', None),
    'a1-from': ('Från', None),
    'a1-to-direction': ('Till', None),
    'a1-in': ('I', None),
    'a1-on': ('På', None),
    'a1-under': ('Under', None),
    'a1-this': ('Detta', None),
    'a1-that': ('Det där', None),
    'a1-very': ('Mycket', None),
    'a1-also': ('Också', None),
    'a1-not': ('Inte', None),
    'a1-maybe': ('Kanske', None),
    'a1-sun': ('Sol', None),
    'a1-rain': ('Regn', None),
    'a1-snow': ('Snö', None),
    'a1-wind': ('Vind', None),
    'a1-cloud': ('Moln', None),
    'a1-weather': ('Väder', None),
    'a1-sky': ('Himmel', None),
    'a1-sea': ('Hav', None),
    'a1-mountain': ('Berg', None),
    'a1-river': ('Flod', None),
    'a1-tree': ('Träd', None),
    'a1-flower': ('Blomma', None),
    'a1-dog': ('Hund', None),
    'a1-cat': ('Katt', None),
    'a1-bird': ('Fågel', None),
    'a1-fish-animal': ('Fisk', None),
    'a1-horse': ('Häst', None),
    'a1-cow': ('Ko', None),
    'a1-earth': ('Jord', None),
    'a1-moon': ('Måne', None),
    'a1-star': ('Stjärna', None),
    'a1-fire': ('Eld', None),
    'a1-its-windy': ('Det blåser', None),
    'a1-its-snowing': ('Det snöar', None),
    'a1-its-cold-today': ('Det är kallt idag', None),
    'a1-its-hot-today': ('Det är varmt idag', None),
    'a1-help': ('Hjälp!', None),
    'a1-slowly-please': ('Långsamt, tack', None),
    'a1-do-you-speak-english': ('Talar du engelska?', None),
    'a1-i-dont-know': ('Jag vet inte', None),
    'a1-where-is-the-bathroom': ('Var är badrummet?', None),
    'a1-which-way': ('Vilken väg?', None),
    'a1-one-moment-please': ('Ett ögonblick, tack', None),
    'a1-of-course': ('Självklart', None),
    'a1-no-problem': ('Inga problem', None),
    'a1-its-okay': ('Det är okej', None),
    'a1-lets-go': ('Nu går vi', None),
    'a1-come-in': ('Kom in', None),
    'a1-be-careful': ('Var försiktig', None),
    'a1-can-you-help-me': ('Kan du hjälpa mig?', None),
    'a1-what-does-that-mean': ('Vad betyder det?', None),
    'a1-can-you-repeat-that': ('Kan du upprepa det?', None),
    'a1-slower-please': ('Långsammare, tack', None),
    'a1-how-do-you-say': ('Hur säger man…?', None),
    'a1-i-would-like': ('Jag skulle vilja…', None),
    'a1-the-bill-please': ('Notan, tack', None),
    'a1-im-tired': ('Jag är trött', None),
    'a1-im-sick': ('Jag är sjuk', None),
    'a1-its-an-emergency': ('Det är ett nödläge', None),
    'a1-call-the-police': ('Ring polisen', None),
    'a1-i-speak-a-little': ('Jag talar lite', None),
    'a1-i-love-it': ('Jag älskar det', None),
    'a1-whats-this': ('Vad är det här?', None),
    'a1-i-agree': ('Jag håller med', None),
    'a1-i-dont-like-it': ('Jag gillar det inte', None),
    'a1-really': ('Verkligen?', None),
    'a1-exactly': ('Exakt', None),
    'a1-i-think-so': ('Jag tror det', None),
    'a1-dont-worry': ('Oroa dig inte', None),
    'a1-just-a-little': ('Bara lite', None),
    'a1-wait-a-moment': ('Vänta ett ögonblick', None),
    'a1-is-this-seat-free': ('Är den här platsen ledig?', None),
    'a1-money': ('Pengar', None),
    'a1-price': ('Pris', None),
    'a1-to-sell': ('Sälja', None),
    'a1-card': ('Kort', None),
    'a1-cash': ('Kontanter', None),
    'a1-receipt': ('Kvitto', None),
    'a1-open-shop': ('Öppet', None),
    'a1-closed-shop': ('Stängt', None),
    'a1-free-no-cost': ('Gratis', None),
    'a1-discount': ('Rabatt', None),
    'a1-how-much-is-it': ('Hur mycket kostar det?', None),
    'a1-too-much': ('För mycket', None),
    'a1-gift': ('Present', None),
    'a1-change-coins': ('Växel', None),
    'a1-supermarket': ('Mataffär', None),
    'a1-pharmacy': ('Apotek', None),
    'a1-bakery': ('Bageri', None),
    'a1-is-this-on-sale': ('Är det här på rea?', None),
    'a1-car': ('Bil', None),
    'a1-bus': ('Buss', None),
    'a1-train': ('Tåg', None),
    'a1-plane': ('Flygplan', None),
    'a1-bicycle': ('Cykel', None),
    'a1-taxi': ('Taxi', None),
    'a1-ticket': ('Biljett', None),
    'a1-station': ('Station', None),
    'a1-airport': ('Flygplats', None),
    'a1-road': ('Väg', None),
    'a1-to-travel': ('Resa', None),
    'a1-trip': ('Utflykt', None),
    'a1-map': ('Karta', None),
    'a1-stop-bus-stop': ('Hållplats', None),
    'a1-to-drive': ('Köra', None),
    'a1-subway': ('Tunnelbana', None),
    'a1-passport': ('Pass', None),
    'a1-suitcase': ('Resväska', None),
    'a1-exit': ('Utgång', None),
    'a1-entrance': ('Ingång', None),
    'a1-phone': ('Telefon', None),
    'a1-book': ('Bok', None),
    'a1-pen': ('Penna', None),
    'a1-paper': ('Papper', None),
    'a1-key': ('Nyckel', None),
    'a1-computer': ('Dator', None),
    'a1-clock': ('Klocka', None),
    'a1-television': ('Tv', None),
    'a1-camera': ('Kamera', None),
    'a1-box': ('Låda', None),
    'a1-glass-cup': ('Glas', None),
    'a1-bottle': ('Flaska', None),
    'a1-plate': ('Tallrik', None),
    'a1-knife': ('Kniv', None),
    'a1-fork': ('Gaffel', None),
    'a1-spoon': ('Sked', None),
    'a1-cup': ('Kopp', None),
    'a1-soap': ('Tvål', None),
    'a1-towel': ('Handduk', None),
    'a1-lamp': ('Lampa', None),
    'a1-wallet': ('Plånbok', None),
    'a1-charger': ('Laddare', None),
    'a1-thing': ('Sak', None),
    'a1-toothbrush': ('Tandborste', None),
    'a1-angry': ('Arg', None),
    'a1-scared': ('Rädd', None),
    'a1-bored': ('Uttråkad', None),
    'a1-excited': ('Exalterad', None),
    'a1-worried': ('Orolig', None),
    'a1-surprised': ('Överraskad', None),
    'a1-calm': ('Lugn', None),
    'a1-nervous': ('Nervös', None),
    'a1-proud': ('Stolt', None),
    'a1-lonely': ('Ensam', None),
    'a1-sleepy': ('Sömnig', None),
    'a1-sick-unwell': ('Krasslig', None),
    'a1-love': ('Kärlek', None),
    'a1-fear': ('Rädsla', None),
    'a1-joy': ('Glädje', None),
    'a1-funny': ('Rolig', None),
    'a2-i-work-in-an-office': ('Jag jobbar på ett kontor', None),
    'a2-i-am-a-student': ('Jag är student', None),
    'a2-i-have-a-meeting': ('Jag har ett möte', None),
    'a2-i-am-looking-for-a-job': ('Jag letar efter ett jobb', None),
    'a2-i-am-studying': ('Jag studerar', None),
    'a2-i-dont-understand': ('Jag förstår inte', None),
    'a2-how-much-is-this': ('Hur mycket kostar det här?', None),
    'a2-its-too-expensive': ('Det är för dyrt', None),
    'a2-can-i-pay-by-card': ('Kan jag betala med kort?', None),
    'a2-do-you-have-a-discount': ('Har ni någon rabatt?', None),
    'a2-im-just-looking': ('Jag bara tittar', None),
    'a2-ill-take-it': ('Jag tar den', None),
    'a2-where-is-the-train-station': ('Var ligger tågstationen?', None),
    'a2-one-ticket-please': ('En biljett, tack', None),
    'a2-how-do-i-get-to-the-airport': ('Hur kommer jag till flygplatsen?', None),
    'a2-im-lost': ('Jag har gått vilse', None),
    'a2-is-it-far': ('Är det långt?', None),
    'a2-where-is-the-restroom': ('Var är toaletten?', None),
    'a2-i-dont-feel-well': ('Jag mår inte bra', None),
    'a2-i-have-a-headache': ('Jag har ont i huvudet', None),
    'a2-where-is-the-pharmacy': ('Var ligger apoteket?', None),
    'a2-i-need-a-doctor': ('Jag behöver en läkare', None),
    'a2-im-allergic-to-peanuts': ('Jag är allergisk mot jordnötter', None),
    'a2-it-hurts-here': ('Det gör ont här', None),
    'a2-its-sunny': ('Det är soligt', None),
    'a2-its-raining': ('Det regnar', None),
    'a2-i-like-to-read': ('Jag gillar att läsa', None),
    'a2-my-favorite-is-music': ('Min favorit är musik', None),
    'a2-on-weekends-i-rest': ('På helgerna vilar jag', None),
    'a2-i-play-sports': ('Jag tränar', None),
    'a2-what-time-is-it': ('Vad är klockan?', None),
    'a2-lets-meet-tomorrow': ('Låt oss ses imorgon', None),
    'a2-can-you-call-me': ('Kan du ringa mig?', None),
    'a2-see-you-later': ('Vi ses senare', None),
    'a2-whats-your-phone-number': ('Vad är ditt telefonnummer?', None),
    'a2-im-busy-today': ('Jag är upptagen idag', None),
    'a2-job': ('Jobb', None),
    'a2-boss': ('Chef', None),
    'a2-colleague': ('Kollega', None),
    'a2-salary': ('Lön', None),
    'a2-to-earn': ('Tjäna', None),
    'a2-class': ('Klass', None),
    'a2-teacher': ('Lärare', None),
    'a2-exam': ('Prov', None),
    'a2-homework': ('Läxa', None),
    'a2-university': ('Universitet', None),
    'a2-to-teach': ('Undervisa', None),
    'a2-project': ('Projekt', None),
    'a2-deadline': ('Deadline', None),
    'a2-interview': ('Intervju', None),
    'a2-career': ('Karriär', None),
    'a2-break-pause': ('Paus', None),
    'a2-schedule': ('Schema', None),
    'a2-company': ('Företag', None),
    'a2-customer': ('Kund', None),
    'a2-unemployed': ('Arbetslös', None),
    'a2-to-try-on': ('Prova', None),
    'a2-fitting-room': ('Provrum', None),
    'a2-sale-discount-event': ('Rea', None),
    'a2-to-return-an-item': ('Returnera', None),
    'a2-refund': ('Återbetalning', None),
    'a2-brand': ('Märke', None),
    'a2-quality': ('Kvalitet', None),
    'a2-cashier': ('Kassör', None),
    'a2-shopping-cart': ('Kundvagn', None),
    'a2-online-shopping': ('Näthandel', None),
    'a2-to-order-online': ('Beställa', None),
    'a2-delivery': ('Leverans', None),
    'a2-package': ('Paket', None),
    'a2-to-choose': ('Välja', None),
    'a2-to-compare': ('Jämföra', None),
    'a2-it-fits-me': ('Den passar mig', None),
    'a2-too-big': ('För stor', None),
    'a2-do-you-have-it-in-another-color': ('Har ni den i en annan färg?', None),
    'a2-mall': ('Köpcentrum', None),
    'a2-cheaper': ('Billigare', None),
    'a2-reservation': ('Bokning', None),
    'a2-to-book': ('Boka', None),
    'a2-check-in': ('Incheckning', None),
    'a2-luggage': ('Bagage', None),
    'a2-flight': ('Flyg', None),
    'a2-delay': ('Försening', None),
    'a2-departure': ('Avresa', None),
    'a2-arrival': ('Ankomst', None),
    'a2-gate': ('Gate', None),
    'a2-seat': ('Plats', None),
    'a2-tourist': ('Turist', None),
    'a2-guide': ('Guide', None),
    'a2-sightseeing': ('Sightseeing', None),
    'a2-souvenir': ('Souvenir', None),
    'a2-beach': ('Strand', None),
    'a2-museum': ('Museum', None),
    'a2-to-visit': ('Besöka', None),
    'a2-round-trip': ('Tur och retur', None),
    'a2-one-way': ('Enkel resa', None),
    'a2-abroad': ('Utomlands', None),
    'a2-doctor': ('Läkare', None),
    'a2-nurse': ('Sjuksköterska', None),
    'a2-medicine': ('Medicin', None),
    'a2-pain': ('Smärta', None),
    'a2-fever': ('Feber', None),
    'a2-cough': ('Hosta', None),
    'a2-a-cold-illness': ('Förkylning', None),
    'a2-flu': ('Influensa', None),
    'a2-allergy': ('Allergi', None),
    'a2-appointment': ('Tidsbokning', None),
    'a2-prescription': ('Recept', None),
    'a2-stomachache': ('Ont i magen', None),
    'a2-healthy': ('Frisk', None),
    'a2-to-rest': ('Vila', None),
    'a2-insurance': ('Försäkring', None),
    'a2-emergency': ('Nödsituation', None),
    'a2-dentist': ('Tandläkare', None),
    'a2-injury': ('Skada', None),
    'a2-i-feel-better': ('Jag mår bättre', None),
    'a2-blood-pressure': ('Blodtryck', None),
    'a2-hobby': ('Hobby', None),
    'a2-music': ('Musik', None),
    'a2-movie': ('Film', None),
    'a2-sport': ('Sport', None),
    'a2-soccer': ('Fotboll', None),
    'a2-to-swim': ('Simma', None),
    'a2-to-dance': ('Dansa', None),
    'a2-to-sing': ('Sjunga', None),
    'a2-to-paint': ('Måla', None),
    'a2-game': ('Spel', None),
    'a2-team': ('Lag', None),
    'a2-to-win': ('Vinna', None),
    'a2-to-lose-a-game': ('Förlora', None),
    'a2-concert': ('Konsert', None),
    'a2-photography': ('Fotografering', None),
    'a2-to-hike': ('Vandra', None),
    'a2-gym': ('Gym', None),
    'a2-to-exercise': ('Träna', None),
    'a2-cloudy': ('Molnigt', None),
    'a2-storm': ('Storm', None),
    'a2-humid': ('Fuktig', None),
    'a2-forecast': ('Prognos', None),
    'a2-to-plan': ('Planera', None),
    'a2-to-meet-up': ('Träffas', None),
    'a2-invitation': ('Inbjudan', None),
    'a2-to-invite': ('Bjuda in', None),
    'a2-to-cancel': ('Ställa in', None),
    'a2-free-time': ('Fritid', None),
    'a2-to-postpone': ('Skjuta upp', None),
    'a2-internet': ('Internet', None),
    'a2-email': ('E-post', None),
    'a2-message': ('Meddelande', None),
    'a2-to-send': ('Skicka', None),
    'a2-to-download': ('Ladda ner', None),
    'a2-app': ('App', None),
    'a2-password': ('Lösenord', None),
    'a2-screen': ('Skärm', None),
    'a2-wi-fi': ('Wi-Fi', None),
    'a2-website': ('Webbplats', None),
    'a2-video-call': ('Videosamtal', None),
    'a2-are-you-free-on-saturday': ('Är du ledig på lördag?', None),
    'a2-sounds-good': ('Det låter bra', None),
    'a2-to-clean': ('Städa', None),
    'a2-to-wash': ('Tvätta', None),
    'a2-dishes': ('Disk', None),
    'a2-laundry': ('Tvätt', None),
    'a2-to-iron': ('Stryka', None),
    'a2-trash': ('Skräp', None),
    'a2-to-tidy-up': ('Ordna', None),
    'a2-vacuum-cleaner': ('Dammsugare', None),
    'a2-to-repair': ('Reparera', None),
    'a2-to-move-house': ('Flytta', None),
    'a2-rent': ('Hyra', None),
    'a2-landlord': ('Hyresvärd', None),
    'a2-apartment': ('Lägenhet', None),
    'a2-furniture': ('Möbler', None),
    'a2-sofa': ('Soffa', None),
    'a2-fridge': ('Kylskåp', None),
    'a2-oven': ('Ugn', None),
    'a2-stove': ('Spis', None),
    'a2-shower': ('Dusch', None),
    'a2-mirror': ('Spegel', None),
    'a2-pillow': ('Kudde', None),
    'a2-blanket': ('Filt', None),
    'a2-washing-machine': ('Tvättmaskin', None),
    'a2-roommate': ('Rumskamrat', None),
    'a2-stairs': ('Trappa', None),
    'a2-elevator': ('Hiss', None),
    'a2-to-wake-up': ('Vakna', None),
    'a2-to-get-up': ('Gå upp', None),
    'a2-to-take-a-shower': ('Duscha', None),
    'a2-to-brush-ones-teeth': ('Borsta tänderna', None),
    'a2-to-get-dressed': ('Klä på sig', None),
    'a2-to-have-breakfast': ('Äta frukost', None),
    'a2-to-commute': ('Pendla', None),
    'a2-to-go-home': ('Åka hem', None),
    'a2-to-relax': ('Koppla av', None),
    'a2-to-watch-tv': ('Titta på tv', None),
    'a2-to-go-to-bed': ('Gå och lägga sig', None),
    'a2-routine': ('Rutin', None),
    'a2-habit': ('Vana', None),
    'a2-alarm-clock': ('Väckarklocka', None),
    'a2-to-be-late': ('Komma sent', None),
    'a2-to-hurry': ('Skynda sig', None),
    'a2-on-time': ('I tid', None),
    'a2-nap': ('Tupplur', None),
    'a2-to-take-a-walk': ('Ta en promenad', None),
    'a2-to-have-lunch': ('Äta lunch', None),
    'a2-to-have-dinner': ('Äta middag', None),
    'a2-to-fall-asleep': ('Somna', None),
    'a2-every-day': ('Varje dag', None),
    'a2-usually': ('Vanligtvis', None),
    'a2-corner': ('Hörn', None),
    'a2-block': ('Kvarter', None),
    'a2-traffic-light': ('Trafikljus', None),
    'a2-bridge': ('Bro', None),
    'a2-square-plaza': ('Torg', None),
    'a2-downtown': ('Centrum', None),
    'a2-neighborhood': ('Stadsdel', None),
    'a2-building': ('Byggnad', None),
    'a2-sidewalk': ('Trottoar', None),
    'a2-to-cross': ('Korsa', None),
    'a2-to-turn': ('Svänga', None),
    'a2-address': ('Adress', None),
    'a2-post-office': ('Postkontor', None),
    'a2-library': ('Bibliotek', None),
    'a2-cinema': ('Bio', None),
    'a2-theater': ('Teater', None),
    'a2-stadium': ('Stadion', None),
    'a2-police-station': ('Polisstation', None),
    'a2-town-hall': ('Stadshus', None),
    'a2-parking-lot': ('Parkering', None),
    'a2-gas-station': ('Bensinmack', None),
    'a2-traffic': ('Trafik', None),
    'a2-opposite': ('Mittemot', None),
    'a2-next-to': ('Bredvid', None),
    'a2-between': ('Mellan', None),
    'a2-how-do-i-get-to': ('Hur kommer jag till…?', None),
    'a2-menu': ('Meny', None),
    'a2-waiter': ('Servitör', None),
    'a2-dish': ('Rätt', None),
    'a2-dessert': ('Efterrätt', None),
    'a2-starter': ('Förrätt', None),
    'a2-main-course': ('Huvudrätt', None),
    'a2-vegetarian': ('Vegetarian', None),
    'a2-tip': ('Dricks', None),
    'a2-to-cook': ('Laga mat', None),
    'a2-recipe': ('Recept', None),
    'a2-ingredient': ('Ingrediens', None),
    'a2-oil': ('Olja', None),
    'a2-butter': ('Smör', None),
    'a2-pepper': ('Peppar', None),
    'a2-onion': ('Lök', None),
    'a2-garlic': ('Vitlök', None),
    'a2-tomato': ('Tomat', None),
    'a2-potato': ('Potatis', None),
    'a2-noodles': ('Nudlar', None),
    'a2-sauce': ('Sås', None),
    'a2-to-bake': ('Baka', None),
    'a2-to-fry': ('Steka', None),
    'a2-to-boil': ('Koka', None),
    'a2-a-table-for-two': ('Ett bord för två', None),
    'a2-takeout': ('Hämtmat', None),
    'a2-snack': ('Mellanmål', None),
    'a2-salty': ('Salt', None),
    'a2-bitter': ('Bitter', None),
    'a2-tall': ('Lång', None),
    'a2-short-height': ('Kort', None),
    'a2-thin': ('Smal', None),
    'a2-overweight': ('Överviktig', None),
    'a2-blond': ('Blond', None),
    'a2-dark-haired': ('Mörkhårig', None),
    'a2-beard': ('Skägg', None),
    'a2-kind': ('Snäll', None),
    'a2-nice-person': ('Trevlig', None),
    'a2-shy': ('Blyg', None),
    'a2-talkative': ('Pratsam', None),
    'a2-smart': ('Smart', None),
    'a2-lazy': ('Lat', None),
    'a2-hardworking': ('Flitig', None),
    'a2-polite': ('Artig', None),
    'a2-rude': ('Oförskämd', None),
    'a2-patient': ('Tålmodig', None),
    'a2-honest': ('Ärlig', None),
    'a2-serious': ('Allvarlig', None),
    'a2-quiet-person': ('Tystlåten', None),
    'a2-friendly': ('Vänlig', None),
    'a2-handsome': ('Snygg', None),
    'a2-age': ('Ålder', None),
    'a2-old-person': ('Gammal', None),
    'a2-curly-hair': ('Lockigt hår', None),
    'a2-cheerful': ('Gladlynt', None),
    'a2-stubborn': ('Envis', None),
    'a2-generous': ('Generös', None),
    'a2-to-try': ('Försöka', None),
    'a2-to-start': ('Börja', None),
    'a2-to-finish': ('Avsluta', None),
    'a2-to-change': ('Ändra', None),
    'a2-to-use': ('Använda', None),
    'a2-to-receive': ('Ta emot', None),
    'a2-to-decide': ('Bestämma', None),
    'a2-to-forget': ('Glömma', None),
    'a2-to-remember': ('Komma ihåg', None),
    'a2-to-lose-an-object': ('Tappa bort', None),
    'a2-to-meet-someone-new': ('Träffa', None),
    'a2-to-prefer': ('Föredra', None),
    'a2-to-hope': ('Hoppas', None),
    'a2-to-believe': ('Tro', None),
    'a2-to-feel': ('Känna', None),
    'a2-to-seem': ('Verka', None),
    'a2-to-happen': ('Hända', None),
    'a2-to-stay': ('Stanna', None),
    'a2-to-spend-money': ('Spendera', None),
    'a2-to-show': ('Visa', None),
    'a2-to-explain': ('Förklara', None),
    'a2-to-follow': ('Följa', None),
    'a2-to-keep': ('Behålla', None),
    'a2-to-allow': ('Tillåta', None),
    'a2-to-become': ('Bli', None),
    'a2-to-continue': ('Fortsätta', None),
    'a2-to-cut': ('Skära', None),
    'a2-to-break': ('Gå sönder', None),
    'a2-to-fly': ('Flyga', None),
    'a2-to-draw': ('Rita', None),
    'a2-to-carry': ('Bära', None),
    'a2-to-push': ('Knuffa', None),
    'a2-to-pull': ('Dra', None),
    'a2-to-throw': ('Kasta', None),
    'a2-to-catch': ('Fånga', None),
    'a2-to-build': ('Bygga', None),
    'a2-to-grow': ('Växa', None),
    'a2-to-fall': ('Falla', None),
    'a2-to-climb': ('Klättra', None),
    'a2-to-jump': ('Hoppa', None),
    'a2-to-laugh': ('Skratta', None),
    'a2-to-cry': ('Gråta', None),
    'a2-to-smile': ('Le', None),
    'a2-to-shout': ('Skrika', None),
    'a2-to-whisper': ('Viska', None),
    'a2-to-hug': ('Krama', None),
    'a2-to-kiss': ('Kyssa', None),
    'a2-to-touch': ('Röra', None),
    'a2-to-smell': ('Lukta', None),
    'a2-to-taste': ('Smaka', None),
    'a2-to-wash-oneself': ('Tvätta sig', None),
    'a2-to-hide': ('Gömma', None),
    'a2-interesting': ('Intressant', None),
    'a2-boring': ('Tråkig', None),
    'a2-comfortable': ('Bekväm', None),
    'a2-dangerous': ('Farlig', None),
    'a2-safe': ('Säker', None),
    'a2-noisy': ('Högljudd', None),
    'a2-busy': ('Upptagen', None),
    'a2-heavy': ('Tung', None),
    'a2-light-weight': ('Lätt', None),
    'a2-wide': ('Bred', None),
    'a2-narrow': ('Trång', None),
    'a2-soft': ('Mjuk', None),
    'a2-hard-firm': ('Hård', None),
    'a2-wet': ('Blöt', None),
    'a2-dry': ('Torr', None),
    'a2-rich': ('Rik', None),
    'a2-poor': ('Fattig', None),
    'a2-famous': ('Berömd', None),
    'a2-popular': ('Populär', None),
    'a2-modern': ('Modern', None),
    'a2-traditional': ('Traditionell', None),
    'a2-ready': ('Redo', None),
    'a2-sure': ('Säker', None),
    'a2-wrong': ('Fel', None),
    'a2-correct': ('Korrekt', None),
    'a2-strange': ('Konstig', None),
    'a2-same': ('Samma', None),
    'a2-different': ('Annorlunda', None),
    'a2-last-week': ('Förra veckan', None),
    'a2-next-week': ('Nästa vecka', None),
    'a2-this-month': ('Den här månaden', None),
    'a2-last-year': ('Förra året', None),
    'a2-next-year': ('Nästa år', None),
    'a2-at-the-end': ('I slutet', None),
    'a2-at-the-beginning': ('I början', None),
    'a2-twice': ('Två gånger', None),
    'a2-once': ('En gång', None),
    'a2-in-a-hurry': ('I all hast', None),
    'a2-for-a-long-time': ('Under lång tid', None),
    'a2-recently': ('Nyligen', None),
    'a2-already': ('Redan', None),
    'a2-still': ('Fortfarande', None),
    'a2-not-yet': ('Inte än', None),
    'a2-until': ('Tills', None),
    'a2-since': ('Sedan', None),
    'a2-during': ('Under', None),
    'a2-ago': ('Sedan', None),
    'a2-at-least': ('Åtminstone', None),
    'a2-right-away': ('Genast', None),
    'a2-finally': ('Äntligen', None),
    'a2-suddenly': ('Plötsligt', None),
    'a2-the-day-after-tomorrow': ('I övermorgon', None),
    'a2-conversation': ('Samtal', None),
    'a2-question': ('Fråga', None),
    'a2-answer-noun': ('Svar', None),
    'a2-opinion': ('Åsikt', None),
    'a2-to-describe': ('Beskriva', None),
    'a2-to-promise': ('Lova', None),
    'a2-to-suggest': ('Föreslå', None),
    'a2-to-complain': ('Klaga', None),
    'a2-to-apologize': ('Be om ursäkt', None),
    'a2-to-thank': ('Tacka', None),
    'a2-joke': ('Skämt', None),
    'a2-story': ('Berättelse', None),
    'a2-news': ('Nyheter', None),
    'a2-to-argue': ('Bråka', None),
    'a2-to-discuss': ('Diskutera', None),
    'a2-secret': ('Hemlighet', None),
    'a2-to-mean': ('Betyda', None),
    'a2-to-pronounce': ('Uttala', None),
    'a2-to-translate': ('Översätta', None),
    'a2-word': ('Ord', None),
    'a2-sentence': ('Mening', None),
    'a2-language': ('Språk', None),
    'a2-to-spell': ('Stava', None),
    'a2-to-lie': ('Ljuga', None),
    'a2-truth': ('Sanning', None),
    'a2-to-chat': ('Chatta', None),
    'a2-accent': ('Brytning', None),
    'a2-fluent': ('Flytande', None),
    'a2-to-get-married': ('Gifta sig', None),
    'a2-wedding': ('Bröllop', None),
    'a2-couple': ('Par', None),
    'a2-childhood': ('Barndom', None),
    'a2-teenager': ('Tonåring', None),
    'a2-adult': ('Vuxen', None),
    'a2-to-grow-up': ('Växa upp', None),
    'a2-anniversary': ('Årsdag', None),
    'a2-party': ('Fest', None),
    'a2-guest': ('Gäst', None),
    'a2-to-celebrate': ('Fira', None),
    'a2-to-be-born': ('Födas', None),
    'a2-to-die': ('Dö', None),
    'a2-relatives': ('Släktingar', None),
    'a2-twins': ('Tvillingar', None),
    'a2-only-child': ('Enda barn', None),
    'a2-to-take-care-of': ('Ta hand om', None),
    'a2-nephew': ('Brorson', None),
    'a2-niece': ('Systerdotter', None),
    'a2-grandchild': ('Barnbarn', None),
    'a2-single': ('Singel', None),
    'a2-divorced': ('Skild', None),
    'a2-christmas': ('Jul', None),
    'a2-new-year': ('Nyår', None),
    'a2-cake': ('Tårta', None),
    'a2-candle': ('Ljus', None),
    'a2-lesson': ('Lektion', None),
    'a2-course': ('Kurs', None),
    'a2-to-practice': ('Öva', None),
    'a2-mistake': ('Misstag', None),
    'a2-to-correct': ('Rätta', None),
    'a2-grade-mark': ('Betyg', None),
    'a2-to-pass-an-exam': ('Klara', None),
    'a2-to-fail-an-exam': ('Bli underkänd', None),
    'a2-to-graduate': ('Ta examen', None),
    'a2-degree': ('Examen', None),
    'a2-subject': ('Ämne', None),
    'a2-math': ('Matematik', None),
    'a2-history': ('Historia', None),
    'a2-science': ('Vetenskap', None),
    'a2-art': ('Konst', None),
    'a2-dictionary': ('Ordbok', None),
    'a2-notebook': ('Anteckningsbok', None),
    'a2-to-memorize': ('Memorera', None),
    'a2-to-review': ('Repetera', None),
    'a2-classroom': ('Klassrum', None),
    'a2-semester': ('Termin', None),
    'a2-scholarship': ('Stipendium', None),
    'a2-to-register': ('Registrera sig', None),
    'a2-example': ('Exempel', None),
    'a2-level': ('Nivå', None),
    'a2-beginner': ('Nybörjare', None),
    'a2-to-save-money': ('Spara', None),
    'a2-bank-account': ('Bankkonto', None),
    'a2-to-withdraw': ('Ta ut', None),
    'a2-to-deposit': ('Sätta in', None),
    'a2-atm': ('Bankomat', None),
    'a2-loan': ('Lån', None),
    'a2-debt': ('Skuld', None),
    'a2-to-borrow': ('Låna', None),
    'a2-to-lend': ('Låna ut', None),
    'a2-to-owe': ('Vara skyldig', None),
    'a2-tax': ('Skatt', None),
    'a2-bill-utility': ('Räkning', None),
    'a2-budget': ('Budget', None),
    'a2-to-afford': ('Ha råd med', None),
    'a2-interest-bank': ('Ränta', None),
    'a2-coin': ('Mynt', None),
    'a2-to-exchange-money': ('Växla', None),
    'a2-exchange-rate': ('Växelkurs', None),
    'a2-credit-card': ('Kreditkort', None),
    'a2-to-cost': ('Kosta', None),
    'a2-salary-raise': ('Löneförhöjning', None),
    'a2-expensive-habit': ('Dyr vana', None),
    'a2-invoice': ('Faktura', None),
    'a2-payment': ('Betalning', None),
    'a2-to-miss-someone': ('Sakna', None),
    'a2-to-worry': ('Oroa sig', None),
    'a2-to-enjoy': ('Njuta av', None),
    'a2-to-hate': ('Hata', None),
    'a2-to-be-afraid-of': ('Vara rädd för', None),
    'a2-ashamed': ('Skamsen', None),
    'a2-jealous': ('Svartsjuk', None),
    'a2-embarrassed': ('Generad', None),
    'a2-disappointed': ('Besviken', None),
    'a2-grateful': ('Tacksam', None),
    'a2-relieved': ('Lättad', None),
    'a2-confused': ('Förvirrad', None),
    'a2-curious': ('Nyfiken', None),
    'a2-hopeful': ('Hoppfull', None),
    'a2-frustrated': ('Frustrerad', None),
    'a2-stressed': ('Stressad', None),
    'a2-in-a-good-mood': ('På gott humör', None),
    'a2-in-a-bad-mood': ('På dåligt humör', None),
    'a2-to-cheer-up': ('Pigga upp sig', None),
    'a2-to-calm-down': ('Lugna ner sig', None),
    'a2-to-get-angry': ('Bli arg', None),
    'a2-to-fall-in-love': ('Bli kär', None),
    'a2-mood': ('Humör', None),
    'a2-satisfied': ('Nöjd', None),
    'a2-forest': ('Skog', None),
    'a2-lake': ('Sjö', None),
    'a2-island': ('Ö', None),
    'a2-desert': ('Öken', None),
    'a2-field': ('Fält', None),
    'a2-farm': ('Bondgård', None),
    'a2-animal': ('Djur', None),
    'a2-insect': ('Insekt', None),
    'a2-mosquito': ('Mygga', None),
    'a2-bee': ('Bi', None),
    'a2-butterfly': ('Fjäril', None),
    'a2-snake': ('Orm', None),
    'a2-lion': ('Lejon', None),
    'a2-elephant': ('Elefant', None),
    'a2-monkey': ('Apa', None),
    'a2-rabbit': ('Kanin', None),
    'a2-pig': ('Gris', None),
    'a2-sheep': ('Får', None),
    'a2-plant': ('Växt', None),
    'a2-grass': ('Gräs', None),
    'a2-leaf': ('Löv', None),
    'a2-rock': ('Sten', None),
    'a2-sand': ('Sand', None),
    'a2-ocean': ('Ocean', None),
    'a2-wave': ('Våg', None),
    'a2-thunder': ('Åska', None),
    'a2-fog': ('Dimma', None),
    'a2-temperature': ('Temperatur', None),
    'a2-laptop': ('Bärbar dator', None),
    'a2-keyboard': ('Tangentbord', None),
    'a2-printer': ('Skrivare', None),
    'a2-file': ('Fil', None),
    'a2-folder': ('Mapp', None),
    'a2-to-print': ('Skriva ut', None),
    'a2-to-click': ('Klicka', None),
    'a2-to-type': ('Skriva på tangentbord', None),
    'a2-to-search-online': ('Söka på nätet', None),
    'a2-social-media': ('Sociala medier', None),
    'a2-to-post': ('Posta', None),
    'a2-to-share': ('Dela', None),
    'a2-video': ('Video', None),
    'a2-photo': ('Foto', None),
    'a2-selfie': ('Selfie', None),
    'a2-headphones': ('Hörlurar', None),
    'a2-speaker': ('Högtalare', None),
    'a2-battery': ('Batteri', None),
    'a2-to-turn-on': ('Sätta på', None),
    'a2-to-turn-off': ('Stänga av', None),
    'a2-volume': ('Volym', None),
    'a2-channel': ('Kanal', None),
    'a2-podcast': ('Podd', None),
    'a2-screenshot': ('Skärmdump', None),
    'a2-update': ('Uppdatering', None),
    'a2-notification': ('Notis', None),
    'a2-to-log-in': ('Logga in', None),
    'a2-subtitles': ('Undertexter', None),
    'a2-what-do-you-think': ('Vad tycker du?', None),
    'a2-it-depends': ('Det beror på', None),
    'a2-im-not-sure': ('Jag är inte säker', None),
    'a2-let-me-think': ('Låt mig tänka', None),
    'a2-what-a-pity': ('Så synd', None),
    'a2-never-mind': ('Glöm det', None),
    'a2-hurry-up': ('Skynda dig', None),
    'a2-watch-out': ('Se upp!', None),
    'a2-thats-a-good-idea': ('Det är en bra idé', None),
    'a2-are-you-kidding': ('Skojar du?', None),
    'a2-its-up-to-you': ('Det är upp till dig', None),
    'a2-im-on-my-way': ('Jag är på väg', None),
    'a2-same-here': ('Detsamma', None),
    'a2-me-neither': ('Inte jag heller', None),
    'a2-by-the-way': ('Förresten', None),
    'a2-in-my-opinion': ('Enligt min åsikt', None),
    'a2-to-be-honest': ('Ärligt talat', None),
    'a2-actually': ('Faktiskt', None),
    'a2-anyway': ('Hur som helst', None),
    'a2-for-example': ('Till exempel', None),
    'a2-sorry-im-late': ('Förlåt att jag är sen', None),
    'a2-no-way': ('Aldrig i livet!', None),
    'a2-that-makes-sense': ('Det låter rimligt', None),
    'a2-good-point': ('Bra poäng', None),
    'a2-banana': ('Banan', None),
    'a2-orange-fruit': ('Apelsin', None),
    'a2-grapes': ('Vindruvor', None),
    'a2-strawberry': ('Jordgubbe', None),
    'a2-lemon': ('Citron', None),
    'a2-watermelon': ('Vattenmelon', None),
    'a2-peach': ('Persika', None),
    'a2-pear': ('Päron', None),
    'a2-carrot': ('Morot', None),
    'a2-lettuce': ('Sallad', None),
    'a2-cucumber': ('Gurka', None),
    'a2-bell-pepper': ('Paprika', None),
    'a2-mushroom': ('Svamp', None),
    'a2-corn': ('Majs', None),
    'a2-beans': ('Bönor', None),
    'a2-spinach': ('Spenat', None),
    'a2-cabbage': ('Kål', None),
    'a2-pumpkin': ('Pumpa', None),
    'a2-nuts': ('Nötter', None),
    'a2-coconut': ('Kokosnöt', None),
    'a2-mango': ('Mango', None),
    'a2-pineapple': ('Ananas', None),
    'a2-cherry': ('Körsbär', None),
    'a2-avocado': ('Avokado', None),
    'a2-ripe': ('Mogen', None),
    'a2-fresh': ('Färsk', None),
    'a2-kilogram': ('Kilo', None),
    'a2-gram': ('Gram', None),
    'a2-liter': ('Liter', None),
    'a2-meter': ('Meter', None),
    'a2-kilometer': ('Kilometer', None),
    'a2-centimeter': ('Centimeter', None),
    'a2-piece': ('Bit', None),
    'a2-slice': ('Skiva', None),
    'a2-dozen': ('Dussin', None),
    'a2-pair': ('Par', None),
    'a2-percent': ('Procent', None),
    'a2-degree-temperature': ('Grad', None),
    'a2-a-bit': ('Lite', None),
    'a2-a-lot': ('Mycket', None),
    'a2-several': ('Flera', None),
    'a2-double': ('Dubbel', None),
    'a2-weight': ('Vikt', None),
    'a2-height': ('Höjd', None),
    'a2-length': ('Längd', None),
    'a2-distance': ('Avstånd', None),
    'a2-speed': ('Hastighet', None),
    'a2-total': ('Totalt', None),
    'a2-almost': ('Nästan', None),
    'a2-only': ('Bara', None),
    'a2-engineer': ('Ingenjör', None),
    'a2-lawyer': ('Advokat', None),
    'a2-chef': ('Kock', None),
    'a2-driver': ('Förare', None),
    'a2-farmer': ('Bonde', None),
    'a2-artist': ('Konstnär', None),
    'a2-musician': ('Musiker', None),
    'a2-actor': ('Skådespelare', None),
    'a2-writer': ('Författare', None),
    'a2-journalist': ('Journalist', None),
    'a2-police-officer': ('Polis', None),
    'a2-firefighter': ('Brandman', None),
    'a2-scientist': ('Forskare', None),
    'a2-programmer': ('Programmerare', None),
    'a2-designer': ('Designer', None),
    'a2-manager': ('Manager', None),
    'a2-salesperson': ('Säljare', None),
    'a2-mechanic': ('Mekaniker', None),
    'a2-electrician': ('Elektriker', None),
    'a2-plumber': ('Rörmokare', None),
    'a2-pilot': ('Pilot', None),
    'a2-accountant': ('Revisor', None),
    'a2-architect': ('Arkitekt', None),
    'a2-hairdresser': ('Frisör', None),
    'a2-soldier': ('Soldat', None),
    'a2-baker': ('Bagare', None),
    'a2-basketball': ('Basket', None),
    'a2-tennis': ('Tennis', None),
    'a2-baseball': ('Baseboll', None),
    'a2-volleyball': ('Volleyboll', None),
    'a2-running': ('Löpning', None),
    'a2-cycling': ('Cykling', None),
    'a2-skiing': ('Skidåkning', None),
    'a2-surfing': ('Surfing', None),
    'a2-yoga': ('Yoga', None),
    'a2-chess': ('Schack', None),
    'a2-cards-game': ('Kortspel', None),
    'a2-board-game': ('Brädspel', None),
    'a2-video-game': ('Tv-spel', None),
    'a2-puzzle': ('Pussel', None),
    'a2-to-go-camping': ('Campa', None),
    'a2-picnic': ('Picknick', None),
    'a2-fishing': ('Fiske', None),
    'a2-race': ('Lopp', None),
    'a2-competition': ('Tävling', None),
    'a2-referee': ('Domare', None),
    'a2-coach': ('Tränare', None),
    'a2-medal': ('Medalj', None),
    'a2-score': ('Poäng', None),
    'a2-fan-supporter': ('Supporter', None),
    'a2-to-train': ('Träna', None),
}
