# -*- coding: utf-8 -*-
LANG = 'nl'
WORDS = {
    'c2-to-abate': ('Luwen', None),
    'c2-to-abhor': ('Verafschuwen', None),
    'c2-to-abstain': ('Zich onthouden', None),
    'c2-to-accentuate': ('Accentueren', None),
    'c2-to-acquiesce': ('Berusten', None),
    'c2-to-admonish': ('Vermanen', None),
    'c2-to-alleviate': ('Verlichten', None),
    'c2-to-amass': ('Vergaren', None),
    'c2-to-appease': ('Paaien', None),
    'c2-to-ascribe': ('Toeschrijven', None),
    'c2-to-augment': ('Vermeerderen', None),
    'c2-to-avert': ('Afwenden', None),
    'c2-to-beckon': ('Wenken', None),
    'c2-to-belittle': ('Kleineren', None),
    'c2-to-bequeath': ('Legateren (nalaten)', None),
    'c2-to-beseech': ('Smeken', None),
    'c2-to-bewilder': ('Verbijsteren', None),
    'c2-to-brandish': ('Zwaaien met', None),
    'c2-to-castigate': ('Kastijden', None),
    'c2-to-coalesce': ('Samensmelten', None),
    'c2-to-commend': ('Aanbevelen (prijzen)', None),
    'c2-to-concede': ('Toegeven', None),
    'c2-to-concoct': ('Brouwen (verzinnen)', None),
    'c2-to-confer': ('Verlenen', None),
    'c2-to-contend': ('Betogen', None),
    'c2-to-corroborate': ('Staven', None),
    'c2-to-aggravate': ('Verergeren', None),
    'c2-to-assail': ('Bestormen', None),
    'c2-to-chastise': ('Tuchtigen', None),
    'c2-to-condescend': ('Zich verwaardigen', None),
    'c2-to-debunk': ('Ontkrachten', None),
    'c2-to-decipher': ('Ontcijferen', None),
    'c2-to-decry': ('Hekelen', None),
    'c2-to-deem': ('Achten', None),
    'c2-to-defer': ('Uitstellen', None),
    'c2-to-delineate': ('Omlijnen', None),
    'c2-to-denounce': ('Aanklagen', None),
    'c2-to-deplete': ('Uitputten', None),
    'c2-to-deride': ('Bespotten', None),
    'c2-to-despair': ('Wanhopen', None),
    'c2-to-detain': ('Aanhouden', None),
    'c2-to-deviate': ('Afwijken', None),
    'c2-to-disdain': ('Verachten', None),
    'c2-to-disperse': ('Verspreiden', None),
    'c2-to-dissuade': ('Ontraden', None),
    'c2-to-divulge': ('Prijsgeven', None),
    'c2-to-dwindle': ('Slinken', None),
    'c2-to-elude': ('Ontglippen', None),
    'c2-to-emanate': ('Voortkomen (uit)', None),
    'c2-to-embellish': ('Verfraaien', None),
    'c2-to-encompass': ('Omvatten', None),
    'c2-to-engender': ('Voortbrengen', None),
    'c2-to-enlighten': ('Voorlichten', None),
    'c2-to-enthrall': ('Boeien', None),
    'c2-to-entice': ('Verleiden (lokken)', None),
    'c2-to-envision': ('Voor ogen zien', None),
    'c2-to-evade': ('Ontduiken', None),
    'c2-to-exalt': ('Verheerlijken', None),
    'c2-to-expedite': ('Bespoedigen', None),
    'c2-to-extol': ('Loven', None),
    'c2-to-fabricate': ('Fabriceren (verzinnen)', None),
    'c2-to-falter': ('Haperen', None),
    'c2-to-feign': ('Veinzen', None),
    'c2-to-flourish': ('Gedijen', None),
    'c2-to-forfeit': ('Verbeuren', None),
    'c2-to-forgo': ('Afzien van', None),
    'c2-to-galvanize': ('Opzwepen', None),
    'c2-to-garner': ('Oogsten', None),
    'c2-to-gloat': ('Zich verkneukelen', None),
    'c2-to-grapple': ('Worstelen', None),
    'c2-to-harness': ('Aanwenden', None),
    'c2-to-heed': ('Acht slaan op', None),
    'c2-to-hoard': ('Hamsteren', None),
    'c2-to-impart': ('Overdragen', None),
    'c2-to-implore': ('Bezweren', None),
    'c2-to-incite': ('Ophitsen', None),
    'c2-to-inhibit': ('Belemmeren', None),
    'c2-to-instill': ('Inprenten', None),
    'c2-to-intercede': ('Tussenbeide komen', None),
    'c2-to-intimidate': ('Intimideren', None),
    'c2-to-jeopardize': ('In gevaar brengen', None),
    'c2-to-languish': ('Kwijnen', None),
    'c2-to-lure': ('Lokken (aas uitgooien)', None),
    'c2-to-marvel': ('Zich verwonderen', None),
    'c2-to-meander': ('Meanderen', None),
    'c2-to-muster': ('Verzamelen (moed)', None),
    'c2-to-obliterate': ('Uitwissen', None),
    'c2-to-oscillate': ('Oscilleren', None),
    'c2-to-ostracize': ('Buitensluiten', None),
    'c2-to-perpetuate': ('Bestendigen', None),
    'c2-to-permeate': ('Doordringen', None),
    'c2-to-plummet': ('Kelderen', None),
    'c2-to-ponder': ('Overpeinzen', None),
    'c2-to-preach': ('Preken', None),
    'c2-to-procure': ('Verwerven', None),
    'c2-to-proliferate': ('Woekeren', None),
    'c2-to-propel': ('Voortstuwen', None),
    'c2-to-quell': ('Bedwingen', None),
    'c2-to-ratify': ('Bekrachtigen', None),
    'c2-to-rebuke': ('Berispen', None),
    'c2-to-rebut': ('Weerleggen', None),
    'c2-to-recant': ('Herroepen', None),
    'c2-to-redeem': ('Verlossen (inwisselen)', None),
    'c2-to-refute': ('Ontzenuwen', None),
    'c2-to-relish': ('Smullen van', None),
    'c2-to-renounce': ('Afzweren', None),
    'c2-to-replenish': ('Aanvullen', None),
    'c2-to-reprimand': ('Terechtwijzen', None),
    'c2-to-repudiate': ('Verwerpen', None),
    'c2-to-resonate': ('Weerklinken', None),
    'c2-to-retaliate': ('Vergelden', None),
    'c2-to-revere': ('Vereren', None),
    'c2-to-revoke': ('Intrekken', None),
    'c2-to-saturate': ('Verzadigen', None),
    'c2-to-scorn': ('Minachten', None),
    'c2-to-squander': ('Verkwisten', None),
    'c2-to-stagnate': ('Stagneren', None),
    'c2-to-stifle': ('Smoren', None),
    'c2-to-subside': ('Wegebben', None),
    'c2-to-succumb': ('Bezwijken', None),
    'c2-to-supplant': ('Verdringen', None),
    'c2-to-surmise': ('Vermoeden', None),
    'c2-to-swindle': ('Oplichten', None),
    'c2-to-tarnish': ('Bezoedelen', None),
    'c2-to-thwart': ('Verijdelen', None),
    'c2-to-transcend': ('Overstijgen', None),
    'c2-to-unravel': ('Ontrafelen', None),
    'c2-to-usurp': ('Usurperen', None),
    'c2-to-vanquish': ('Overwinnen', None),
    'c2-to-venerate': ('Aanbidden (vereren)', None),
    'c2-to-vilify': ('Belasteren', None),
    'c2-to-wane': ('Tanen', None),
    'c2-to-wield': ('Hanteren', None),
    'c2-to-writhe': ('Kronkelen', None),
    'c2-to-yearn': ('Hunkeren', None),
    'c2-to-beget': ('Verwekken', None),
    'c2-to-besiege': ('Belegeren', None),
    'c2-to-cajole': ('Overhalen (vleien)', None),
    'c2-to-coax': ('Ompraten', None),
    'c2-to-deplore': ('Betreuren', None),
    'c2-to-disparage': ('Denigreren', None),
    'c2-to-exhort': ('Aansporen', None),
    'c2-to-foment': ('Aanwakkeren', None),
    'c2-to-indulge': ('Zich overgeven aan', None),
    'c2-to-placate': ('Sussen', None),
    'c2-to-preempt': ('Vóór zijn', None),
    'c2-to-rescind': ('Tenietdoen', None),
    'c2-to-stymie': ('Dwarsbomen', None),
    'c2-to-vindicate': ('In het gelijk stellen', None),
    'c2-to-evince': ('Aan de dag leggen', None),
    'c2-affable': ('Beminnelijk', None),
    'c2-churlish': ('Lomp', None),
    'c2-astute': ('Scherpzinnig', None),
    'c2-audacious': ('Vermetel', None),
    'c2-belligerent': ('Strijdlustig', None),
    'c2-sanguine': ('Hoopvol', None),
    'c2-brusque': ('Bruusk', None),
    'c2-callous': ('Hardvochtig', None),
    'c2-truculent': ('Twistziek', None),
    'c2-capricious': ('Grillig', None),
    'c2-complacent': ('Zelfgenoegzaam', None),
    'c2-unflappable': ('Onverstoorbaar', None),
    'c2-cunning': ('Listig', None),
    'c2-diffident': ('Schuchter', None),
    'c2-officious': ('Bemoeizuchtig', None),
    'c2-docile': ('Volgzaam', None),
    'c2-erudite': ('Erudiet', None),
    'c2-fastidious': ('Kieskeurig', None),
    'c2-flippant': ('Laatdunkend', None),
    'c2-garrulous': ('Praatziek', None),
    'c2-gregarious': ('Sociabel', None),
    'c2-haughty': ('Hooghartig', None),
    'c2-impetuous': ('Onstuimig', None),
    'c2-indolent': ('Indolent', None),
    'c2-mercurial': ('Wispelturig', None),
    'c2-phlegmatic': ('Flegmatiek', None),
    'c2-obsequious': ('Kruiperig', None),
    'c2-petulant': ('Kribbig', None),
    'c2-sanctimonious': ('Schijnheilig', None),
    'c2-taciturn': ('Zwijgzaam', None),
    'c2-bountiful': ('Overvloedig', None),
    'c2-arduous': ('Moeizaam', None),
    'c2-banal': ('Banaal', None),
    'c2-copious': ('Rijkelijk', None),
    'c2-cumbersome': ('Omslachtig', None),
    'c2-deft': ('Behendig', None),
    'c2-dire': ('Nijpend', None),
    'c2-ephemeral': ('Vergankelijk', None),
    'c2-peerless': ('Weergaloos', None),
    'c2-feeble': ('Krachteloos', None),
    'c2-rickety': ('Gammel', None),
    'c2-formidable': ('Geducht', None),
    'c2-immaculate': ('Onberispelijk', None),
    'c2-faultless': ('Feilloos', None),
    'c2-innocuous': ('Onschadelijk', None),
    'c2-insidious': ('Verraderlijk', None),
    'c2-labyrinthine': ('Doolhofachtig', None),
    'c2-profligate': ('Verkwistend', None),
    'c2-perspicuous': ('Glashelder', None),
    'c2-sparse': ('Schaars', None),
    'c2-infinitesimal': ('Oneindig klein', None),
    'c2-sumptuous': ('Weelderig', None),
    'c2-paltry': ('Armzalig', None),
    'c2-unblemished': ('Vlekkeloos', None),
    'c2-indomitable': ('Ontembaar', None),
    'c2-scant': ('Karig', None),
    'c2-transcendent': ('Transcendent', None),
    'c2-tenuous': ('Broos', None),
    'c2-unwieldy': ('Log', None),
    'c2-boundless': ('Grenzeloos', None),
    'c2-abstruse': ('Ondoorgrondelijk', None),
    'c2-apt': ('Passend', None),
    'c2-cogent': ('Overtuigend', None),
    'c2-contentious': ('Omstreden', None),
    'c2-deplorable': ('Betreurenswaardig', None),
    'c2-dubious': ('Twijfelachtig', None),
    'c2-egregious': ('Flagrant', None),
    'c2-exemplary': ('Voorbeeldig', None),
    'c2-fallacious': ('Drogredenerend', None),
    'c2-futile': ('Vergeefs', None),
    'c2-gratuitous': ('Nodeloos', None),
    'c2-illicit': ('Ongeoorloofd', None),
    'c2-impartial': ('Onpartijdig', None),
    'c2-incongruous': ('Ongerijmd', None),
    'c2-ineffable': ('Onuitsprekelijk', None),
    'c2-irrefutable': ('Onweerlegbaar', None),
    'c2-laudable': ('Loffelijk', None),
    'c2-moot': ('Irrelevant (academisch)', None),
    'c2-nebulous': ('Nevelig', None),
    'c2-ostensible': ('Ogenschijnlijk', None),
    'c2-pernicious': ('Verderfelijk', None),
    'c2-plausible': ('Aannemelijk', None),
    'c2-preposterous': ('Bespottelijk', None),
    'c2-salient': ('Opvallend', None),
    'c2-spurious': ('Vals', None),
    'c2-superfluous': ('Overbodig', None),
    'c2-tenable': ('Houdbaar', None),
    'c2-untenable': ('Onhoudbaar', None),
    'c2-viable': ('Levensvatbaar', None),
    'c2-wanton': ('Moedwillig', None),
    'c2-ailing': ('Sukkelend', None),
    'c2-bewildered': ('Verbijsterd', None),
    'c2-desolate': ('Troosteloos', None),
    'c2-brittle': ('Bros', None),
    'c2-cohesive': ('Samenhangend', None),
    'c2-defunct': ('Ter ziele', None),
    'c2-derelict': ('Vervallen', None),
    'c2-ramshackle': ('Bouwvallig', None),
    'c2-dormant': ('Sluimerend', None),
    'c2-drowsy': ('Slaperig', None),
    'c2-dwindling': ('Slinkend', None),
    'c2-exhilarated': ('Opgetogen', None),
    'c2-forlorn': ('Hopeloos verlaten', None),
    'c2-haggard': ('Verwilderd', None),
    'c2-imminent': ('Dreigend', None),
    'c2-incessant': ('Onophoudelijk', None),
    'c2-inert': ('Inert', None),
    'c2-jaded': ('Afgestompt', None),
    'c2-languid': ('Loom', None),
    'c2-listless': ('Lusteloos', None),
    'c2-antiquated': ('Verouderd', None),
    'c2-precarious': ('Precair', None),
    'c2-rampant': ('Welig tierend', None),
    'c2-fidgety': ('Onrustig', None),
    'c2-rife': ('Wijdverbreid', None),
    'c2-sodden': ('Doorweekt', None),
    'c2-stagnant': ('Stilstaand', None),
    'c2-susceptible': ('Vatbaar', None),
    'c2-volatile': ('Vluchtig', None),
    'c2-weary': ('Afgemat', None),
    'c2-bombastic': ('Bombastisch', None),
    'c2-vernacular': ('Volkstalig', None),
    'c2-concise': ('Beknopt', None),
    'c2-tortuous': ('Kronkelend', None),
    'c2-cryptic': ('Cryptisch', None),
    'c2-derogatory': ('Denigrerend', None),
    'c2-didactic': ('Didactisch', None),
    'c2-silver-tongued': ('Welbespraakt', None),
    'c2-emphatic': ('Nadrukkelijk', None),
    'c2-euphemistic': ('Eufemistisch', None),
    'c2-facetious': ('Schertsend', None),
    'c2-florid': ('Bloemrijk', None),
    'c2-glib': ('Rad van tong', None),
    'c2-hyperbolic': ('Hyperbolisch', None),
    'c2-incisive': ('Raak (scherp)', None),
    'c2-laconic': ('Laconiek', None),
    'c2-long-winded': ('Langdradig', None),
    'c2-mordant': ('Bijtend', None),
    'c2-ornate': ('Overladen (sierlijk)', None),
    'c2-pedantic': ('Pedant', None),
    'c2-pithy': ('Kernachtig', None),
    'c2-plaintive': ('Klaaglijk', None),
    'c2-rhetorical': ('Retorisch', None),
    'c2-sardonic': ('Sardonisch', None),
    'c2-scathing': ('Vernietigend', None),
    'c2-succinct': ('Bondig', None),
    'c2-terse': ('Kortaf', None),
    'c2-trite': ('Afgezaagd', None),
    'c2-verbose': ('Woordenrijk', None),
    'c2-wry': ('Wrang', None),
    'c2-acumen': ('Schranderheid', None),
    'c2-alacrity': ('Voortvarendheid', None),
    'c2-ambivalence': ('Ambivalentie', None),
    'c2-apathy': ('Apathie', None),
    'c2-aplomb': ('Aplomb', None),
    'c2-audacity': ('Vermetelheid', None),
    'c2-candor': ('Openhartigheid', None),
    'c2-smugness': ('Zelfvoldaanheid', None),
    'c2-scorn': ('Minachting', None),
    'c2-deference': ('Eerbied', None),
    'c2-discretion': ('Discretie', None),
    'c2-disdain': ('Verachting', None),
    'c2-forbearance': ('Verdraagzaamheid', None),
    'c2-fortitude': ('Standvastigheid', None),
    'c2-hubris': ('Hoogmoed', None),
    'c2-meekness': ('Zachtmoedigheid', None),
    'c2-umbrage': ('Aanstoot', None),
    'c2-ingenuity': ('Vindingrijkheid', None),
    'c2-rectitude': ('Rechtschapenheid', None),
    'c2-malice': ('Boosaardigheid', None),
    'c2-nostalgia': ('Nostalgie', None),
    'c2-perseverance': ('Volharding', None),
    'c2-prudence': ('Voorzichtigheid', None),
    'c2-grit': ('Doorzettingsvermogen', None),
    'c2-reticence': ('Terughoudendheid', None),
    'c2-equanimity': ('Gemoedsrust', None),
    'c2-tenacity': ('Vasthoudendheid', None),
    'c2-vanity': ('IJdelheid', None),
    'c2-vigilance': ('Waakzaamheid', None),
    'c2-zeal': ('IJver', None),
    'c2-anomaly': ('Anomalie', None),
    'c2-catalyst': ('Katalysator', None),
    'c2-conundrum': ('Raadsel', None),
    'c2-debacle': ('Debacle', None),
    'c2-deluge': ('Stortvloed', None),
    'c2-dearth': ('Schaarste', None),
    'c2-dichotomy': ('Tweedeling', None),
    'c2-epitome': ('Belichaming', None),
    'c2-exodus': ('Exodus', None),
    'c2-facade': ('Façade', None),
    'c2-fallacy': ('Drogreden', None),
    'c2-hindsight': ('Wijsheid achteraf', None),
    'c2-impasse': ('Impasse', None),
    'c2-impetus': ('Stuwkracht', None),
    'c2-juncture': ('Kritiek tijdstip', None),
    'c2-loophole': ('Maas in de wet', None),
    'c2-tipping-point': ('Kantelpunt', None),
    'c2-onslaught': ('Stormloop', None),
    'c2-vicious-circle': ('Vicieuze cirkel', None),
    'c2-plight': ('Benarde toestand', None),
    'c2-precedent': ('Precedent', None),
    'c2-quandary': ('Dilemma', None),
    'c2-ramification': ('Vertakking', None),
    'c2-respite': ('Respijt', None),
    'c2-setback': ('Tegenslag', None),
    'c2-stalemate': ('Patstelling', None),
    'c2-surge': ('Golf (van toename)', None),
    'c2-turmoil': ('Beroering', None),
    'c2-upheaval': ('Omwenteling', None),
    'c2-watershed': ('Keerpunt', None),
    'c2-accomplice': ('Medeplichtige', None),
    'c2-adversary': ('Tegenstander', None),
    'c2-advocate': ('Pleitbezorger', None),
    'c2-benefactor': ('Weldoener', None),
    'c2-bystander': ('Omstander', None),
    'c2-charlatan': ('Kwakzalver', None),
    'c2-connoisseur': ('Fijnproever', None),
    'c2-culprit': ('Schuldige', None),
    'c2-demagogue': ('Demagoog', None),
    'c2-dilettante': ('Dilettant', None),
    'c2-envoy': ('Gezant', None),
    'c2-lackey': ('Lakei', None),
    'c2-understudy': ('Doublure', None),
    'c2-hypocrite': ('Huichelaar', None),
    'c2-insurgent': ('Opstandeling', None),
    'c2-layperson': ('Leek', None),
    'c2-maverick': ('Non-conformist', None),
    'c2-sidekick': ('Kompaan', None),
    'c2-mercenary': ('Huurling', None),
    'c2-novice': ('Beginneling', None),
    'c2-pariah': ('Paria', None),
    'c2-patron': ('Mecenas', None),
    'c2-perpetrator': ('Dader', None),
    'c2-prodigy': ('Wonderkind', None),
    'c2-informant': ('Informant', None),
    'c2-recluse': ('Kluizenaar', None),
    'c2-sage': ('Wijze', None),
    'c2-turncoat': ('Overloper', None),
    'c2-stalwart': ('Steunpilaar', None),
    'c2-tycoon': ('Magnaat', None),
    'c2-ambiguity': ('Dubbelzinnigheid', None),
    'c2-analogy': ('Analogie', None),
    'c2-axiom': ('Axioma', None),
    'c2-caveat': ('Voorbehoud', None),
    'c2-consensus': ('Consensus', None),
    'c2-corollary': ('Uitvloeisel', None),
    'c2-yardstick': ('Maatstaf', None),
    'c2-narrative': ('Verhaallijn', None),
    'c2-doctrine': ('Doctrine', None),
    'c2-dogma': ('Dogma', None),
    'c2-epiphany': ('Openbaring', None),
    'c2-ethos': ('Ethos', None),
    'c2-conjecture': ('Gissing', None),
    'c2-idiosyncrasy': ('Eigenaardigheid', None),
    'c2-deduction': ('Deductie', None),
    'c2-innuendo': ('Insinuatie', None),
    'c2-buzzword': ('Modewoord', None),
    'c2-simile': ('Vergelijking (beeldspraak)', None),
    'c2-nuance': ('Nuance', None),
    'c2-archetype': ('Archetype', None),
    'c2-platitude': ('Gemeenplaats', None),
    'c2-postulate': ('Postulaat', None),
    'c2-pretext': ('Voorwendsel', None),
    'c2-rebuttal': ('Weerlegging', None),
    'c2-rhetoric': ('Retoriek', None),
    'c2-semantics': ('Semantiek', None),
    'c2-stigma': ('Stigma', None),
    'c2-tenet': ('Grondbeginsel', None),
    'c2-trope': ('Stijlfiguur (cliché)', None),
    'c2-zeitgeist': ('Tijdgeest', None),
    'c2-acrid': ('Prikkelend', None),
    'c2-astringent': ('Samentrekkend', None),
    'c2-bland-flavorless': ('Smaakloos', None),
    'c2-brackish': ('Brak', None),
    'c2-cloying': ('Zoetig', None),
    'c2-coarse': ('Ruw', None),
    'c2-creamy': ('Romig', None),
    'c2-crunchy': ('Knapperig', None),
    'c2-dank': ('Klam', None),
    'c2-earthy': ('Aards', None),
    'c2-fragrant': ('Geurig', None),
    'c2-gooey': ('Kleverig', None),
    'c2-grainy': ('Korrelig', None),
    'c2-unctuous': ('Zalvend', None),
    'c2-gravelly-voice': ('Schor', None),
    'c2-luscious': ('Sappig', None),
    'c2-mellow': ('Mild', None),
    'c2-hushed': ('Gedempt', None),
    'c2-musty': ('Muf', None),
    'c2-piercing': ('Doordringend', None),
    'c2-pungent': ('Scherp', None),
    'c2-putrid': ('Verrot', None),
    'c2-rancid': ('Ranzig', None),
    'c2-bitter-aftertaste': ('Bittere nasmaak', None),
    'c2-grating-sound': ('Krassend', None),
    'c2-silky': ('Zijdeachtig', None),
    'c2-slimy': ('Slijmerig', None),
    'c2-soggy': ('Papperig', None),
    'c2-tangy': ('Pittig', None),
    'c2-zesty': ('Kruidig', None),
    'c2-better-late-than-never': ('Beter laat dan nooit', None),
    'c2-actions-speak-louder-than-words': ('Daden zeggen meer dan woorden', None),
    'c2-the-early-bird-catches-the-worm': ('De vroege vogel vangt de worm', None),
    "c2-don-t-count-your-chickens-before-they-hatch": ('Men moet de huid niet verkopen voordat de beer geschoten is', None),
    'c2-every-cloud-has-a-silver-lining': ('Achter de wolken schijnt de zon', None),
    'c2-practice-makes-perfect': ('Oefening baart kunst', None),
    'c2-when-in-rome-do-as-the-romans-do': ('Zo het klokje thuis tikt, tikt het nergens', None),
    'c2-two-heads-are-better-than-one': ('Twee weten meer dan één', None),
    'c2-the-grass-is-always-greener-on-the-other-side': ('Het gras is altijd groener aan de overkant', None),
    "c2-don-t-judge-a-book-by-its-cover": ('Schijn bedriegt', None),
    'c2-birds-of-a-feather-flock-together': ('Soort zoekt soort', None),
    'c2-a-bird-in-the-hand-is-worth-two-in-the-bush': ('Beter één vogel in de hand dan tien in de lucht', None),
    "c2-where-there-s-a-will-there-s-a-way": ('Waar een wil is, is een weg', None),
    "c2-rome-wasn-t-built-in-a-day": ('Rome is niet in één dag gebouwd', None),
    'c2-too-many-cooks-spoil-the-broth': ('Te veel koks bederven de brij', None),
    'c2-out-of-sight-out-of-mind': ('Uit het oog, uit het hart', None),
    'c2-look-before-you-leap': ('Bezint eer ge begint', None),
    'c2-necessity-is-the-mother-of-invention': ('Noodzaak is de moeder van de uitvinding', None),
    "c2-you-can-t-have-your-cake-and-eat-it-too": ('Je kunt niet blazen en het meel in de mond houden', None),
    'c2-honesty-is-the-best-policy': ('Eerlijkheid duurt het langst', None),
    'c2-still-waters-run-deep': ('Stille wateren hebben diepe gronden', None),
    'c2-blood-is-thicker-than-water': ('Bloed kruipt waar het niet gaan kan', None),
    'c2-absence-makes-the-heart-grow-fonder': ('Afwezigheid versterkt de liefde', None),
    'c2-every-dog-has-its-day': ('Iedereen komt een keer aan de beurt', None),
    'c2-haste-makes-waste': ('Haastige spoed is zelden goed', None),
    'c2-let-sleeping-dogs-lie': ('Wek geen slapende honden', None),
    'c2-strike-while-the-iron-is-hot': ('Men moet het ijzer smeden als het heet is', None),
    'c2-the-pen-is-mightier-than-the-sword': ('De pen is machtiger dan het zwaard', None),
    'c2-curiosity-killed-the-cat': ('Nieuwsgierigheid is de kat de das om', None),
    "c2-beggars-can-t-be-choosers": ('Een gegeven paard mag men niet in de bek kijken', None),
    'c2-to-draw-a-distinction': ('Een onderscheid maken', None),
    'c2-to-reach-a-verdict': ('Tot een uitspraak komen', None),
    'c2-to-pose-a-threat': ('Een bedreiging vormen', None),
    'c2-to-bear-the-brunt': ('De klappen opvangen', None),
    'c2-to-lend-credence-to': ('Geloofwaardigheid verlenen aan', None),
    'c2-to-wield-influence': ('Invloed uitoefenen', None),
    'c2-to-incur-a-cost': ('Kosten oplopen', None),
    'c2-to-uphold-a-principle': ('Een principe hooghouden', None),
    'c2-to-exert-pressure': ('Druk uitoefenen', None),
    'c2-to-fulfil-an-obligation': ('Een verplichting nakomen', None),
    'c2-to-cast-doubt-on': ('Twijfel zaaien over', None),
    'c2-to-pay-tribute-to': ('Hulde brengen aan', None),
    'c2-to-take-precedence-over': ('Voorrang hebben op', None),
    'c2-to-run-the-risk-of': ('Het risico lopen', None),
    'c2-to-strike-a-balance': ('Een evenwicht vinden', None),
    'c2-to-come-to-fruition': ('Zijn beslag krijgen', None),
    'c2-to-shed-light-on': ('Licht werpen op', None),
    'c2-to-set-a-precedent': ('Een precedent scheppen', None),
    'c2-to-give-rise-to': ('Aanleiding geven tot', None),
    'c2-to-take-issue-with': ('Bezwaar maken tegen', None),
    'c2-pursuant-to': ('Overeenkomstig', None),
    'c2-heretofore': ('Tot dusver', None),
    'c2-inasmuch-as': ('Voor zover', None),
    'c2-in-conjunction-with': ('In samenhang met', None),
    'c2-hitherto': ('Tot nu toe', None),
    'c2-forthwith': ('Onverwijld', None),
    'c2-whilst': ('Terwijl', None),
    'c2-wherein': ('Waarin', None),
    'c2-vis-a-vis': ('Ten opzichte van', None),
    'c2-as-regards': ('Wat betreft', None),
    'c2-for-the-sake-of-argument': ('Bij wijze van spreken', None),
    'c2-be-that-as-it-may': ('Hoe dan ook', None),
    'c2-on-balance': ('Alles afwegend', None),
    'c2-at-the-behest-of': ('Op aandringen van', None),
    'c2-in-the-wake-of': ('In de nasleep van', None),
    'c2-on-the-grounds-that': ('Op grond dat', None),
    'c2-in-accordance-with': ('In overeenstemming met', None),
    'c2-pending': ('In afwachting van', None),
    'c2-irrespective-of': ('Ongeacht', None),
    'c2-hereinafter': ('Hierna', None),
    'c2-beats-me': ('Geen idee', None),
    'c2-point-taken': ('Punt genomen', None),
    'c2-suit-yourself': ('Zoals je wilt', None),
    'c2-go-figure': ('Wie zou het zeggen', None),
    "c2-don-t-get-me-started": ('Begin er niet over', None),
    'c2-bottom-line-is': ('Kortom', None),
    'c2-off-the-top-of-my-head': ('Zo uit mijn hoofd', None),
    "c2-i-ll-say": ('Zeg dat wel', None),
    "c2-you-ve-got-to-be-kidding-me": ('Dat meen je niet', None),
    'c2-no-offense-but': ('Niet kwaad bedoeld, maar', None),
    "c2-i-m-not-gonna-lie": ('Ik zal je niet voorliegen', None),
    'c2-speak-of-the-devil': ('Als je het over de duivel hebt', None),
    "c2-it-s-on-the-tip-of-my-tongue": ('Het ligt op het puntje van mijn tong', None),
    "c2-let-s-call-it-a-day": ('Laten we ermee stoppen voor vandaag', None),
    "c2-it-s-not-rocket-science": ('Het is geen hogere wiskunde', None),
    "c2-that-s-the-last-straw": ('Dat is de druppel die de emmer doet overlopen', None),
    "c2-i-couldn-t-care-less": ('Het kan me niets schelen', None),
    'c2-what-are-the-odds': ('Wat is de kans', None),
    'c2-say-no-more': ('Zeg maar niets meer', None),
    'c2-hang-in-there': ('Hou vol', None),
    "c2-i-m-all-ears": ('Ik ben een en al oor', None),
    "c2-that-s-on-me": ('Dat is mijn schuld', None),
    'c2-no-hard-feelings': ('Niets persoonlijks', None),
    'c2-ditto': ('Idem', None),
    'c2-spill-the-beans': ('Uit de school klappen', None),
    'c2-in-one-ear-and-out-the-other': ('Het ene oor in, het andere uit', None),
    'c2-cut-to-the-chase': ('Kom ter zake', None),
    'c2-you-name-it': ('Noem het maar', None),
    'c2-not-in-a-million-years': ('Nog in geen duizend jaar', None),
    'c2-it-is-what-it-is': ('Het is zoals het is', None),
    'c2-give-me-a-break': ('Doe me een lol', None),
    'c2-hold-your-horses': ('Rustig aan', None),
    'c2-bite-the-bullet': ('Door de zure appel heen bijten', None),
    'c2-take-it-with-a-grain-of-salt': ('Neem het met een korrel zout', None),
    'c2-better-safe-than-sorry': ('Beter het zekere voor het onzekere nemen', None),
    "c2-let-s-play-it-by-ear": ('We zien wel hoe het loopt', None),
    "c2-i-ll-take-a-rain-check": ('Ik hou tegoed', None),
    "c2-for-what-it-s-worth": ('Voor wat het waard is', None),
    'c2-back-to-square-one': ('Terug bij af', None),
    'c2-touch-wood': ('Afkloppen (op hout)', None),
    'c2-allusion': ('Toespeling', None),
    'c2-anecdote': ('Anekdote', None),
    'c2-antithesis': ('Antithese', None),
    'c2-aphorism': ('Aforisme', None),
    'c2-banter': ('Plagerij', None),
    'c2-circumlocution': ('Omhaal van woorden', None),
    'c2-cliche': ('Cliché', None),
    'c2-connotation': ('Connotatie', None),
    'c2-digression': ('Uitweiding', None),
    'c2-double-entendre': ('Dubbelzinnige uitdrukking', None),
    'c2-eloquence': ('Welsprekendheid', None),
    'c2-euphemism': ('Eufemisme', None),
    'c2-gist': ('Kern', None),
    'c2-hyperbole': ('Hyperbool', None),
    'c2-irony': ('Ironie', None),
    'c2-juxtaposition': ('Juxtapositie', None),
    'c2-malapropism': ('Verhaspeling', None),
    'c2-oxymoron': ('Oxymoron', None),
    'c2-paraphrase': ('Parafrase', None),
    'c2-pun': ('Woordspeling', None),
    'c2-quip': ('Kwinkslag', None),
    'c2-sarcasm': ('Sarcasme', None),
    'c2-slur-insult': ('Smaad', None),
    'c2-repartee': ('Gevat weerwoord', None),
    'c2-soliloquy': ('Alleenspraak', None),
    'c2-subtext': ('Subtekst', None),
    'c2-tangent': ('Zijspoor', None),
    'c2-tirade': ('Tirade', None),
    'c2-understatement': ('Understatement', None),
    'c2-verbiage': ('Woordenbrij', None),
    'c2-to-allude-to': ('Zinspelen op', None),
    'c2-to-enunciate': ('Articuleren', None),
    'c2-to-belabor-the-point': ('Doordrammen op een punt', None),
    'c2-to-digress': ('Afdwalen', None),
    'c2-to-expound': ('Uiteenzetten', None),
    'c2-to-insinuate': ('Insinueren', None),
    'c2-to-interject': ('Ertussen werpen', None),
    'c2-to-hammer-home': ('Erin hameren', None),
    'c2-to-retort': ('Van repliek dienen', None),
    'c2-to-waffle-be-vague': ('Wollig praten', None),
    'c2-actuary': ('Actuaris', None),
    'c2-anesthesiologist': ('Anesthesioloog', None),
    'c2-archivist': ('Archivaris', None),
    'c2-auditor': ('Auditor', None),
    'c2-bailiff': ('Deurwaarder', None),
    'c2-blacksmith': ('Smid', None),
    'c2-cartographer': ('Cartograaf', None),
    'c2-chiropractor': ('Chiropractor', None),
    'c2-coroner': ('Lijkschouwer', None),
    'c2-curator': ('Conservator', None),
    'c2-diplomat': ('Diplomaat', None),
    'c2-dietitian': ('Diëtist', None),
    'c2-entomologist': ('Entomoloog', None),
    'c2-forensic-scientist': ('Forensisch onderzoeker', None),
    'c2-geologist': ('Geoloog', None),
    'c2-glazier': ('Glazenmaker', None),
    'c2-interpreter-simultaneous': ('Simultaantolk', None),
    'c2-locksmith': ('Slotenmaker', None),
    'c2-midwife': ('Vroedvrouw', None),
    'c2-court-clerk': ('Griffier', None),
    'c2-oncologist': ('Oncoloog', None),
    'c2-ophthalmologist': ('Oogarts', None),
    'c2-paleontologist': ('Paleontoloog', None),
    'c2-paralegal': ('Juridisch medewerker', None),
    'c2-pathologist': ('Patholoog', None),
    'c2-physiotherapist': ('Fysiotherapeut', None),
    'c2-public-defender': ('Pro-deo-advocaat', None),
    'c2-radiologist': ('Radioloog', None),
    'c2-perfumer': ('Parfumeur', None),
    'c2-stenographer': ('Stenograaf', None),
    'c2-surveyor': ('Landmeter', None),
    'c2-taxidermist': ('Taxidermist', None),
    'c2-upholsterer': ('Stoffeerder', None),
    'c2-veterinarian-specialist': ('Dierenarts', None),
    'c2-welder': ('Lasser', None),
    'c2-anthropology': ('Antropologie', None),
    'c2-archaeology': ('Archeologie', None),
    'c2-astrophysics': ('Astrofysica', None),
    'c2-biochemistry': ('Biochemie', None),
    'c2-botany': ('Plantkunde', None),
    'c2-cartography': ('Cartografie', None),
    'c2-criminology': ('Criminologie', None),
    'c2-demography': ('Demografie', None),
    'c2-econometrics': ('Econometrie', None),
    'c2-epidemiology': ('Epidemiologie', None),
    'c2-epistemology': ('Kennisleer', None),
    'c2-ethnography': ('Etnografie', None),
    'c2-genetics': ('Genetica', None),
    'c2-geopolitics': ('Geopolitiek', None),
    'c2-hermeneutics': ('Hermeneutiek', None),
    'c2-immunology': ('Immunologie', None),
    'c2-jurisprudence': ('Rechtstheorie', None),
    'c2-linguistics': ('Taalkunde', None),
    'c2-metaphysics': ('Metafysica', None),
    'c2-meteorology': ('Meteorologie', None),
    'c2-microbiology': ('Microbiologie', None),
    'c2-musicology': ('Musicologie', None),
    'c2-neuroscience': ('Neurowetenschap', None),
    'c2-oceanography': ('Oceanografie', None),
    'c2-ornithology': ('Vogelkunde', None),
    'c2-pedagogy': ('Pedagogiek', None),
    'c2-pharmacology': ('Farmacologie', None),
    'c2-philology': ('Filologie', None),
    'c2-phonetics': ('Fonetiek', None),
    'c2-seismology': ('Seismologie', None),
    'c2-semiotics': ('Semiotiek', None),
    'c2-sociolinguistics': ('Sociolinguïstiek', None),
    'c2-theology': ('Theologie', None),
    'c2-toxicology': ('Toxicologie', None),
    'c2-zoology': ('Dierkunde', None),
    'c2-acute-sudden-severe': ('Acuut', None),
    'c2-latent': ('Latent', None),
    'c2-benign': ('Goedaardig', None),
    'c2-malignant': ('Kwaadaardig', None),
    'c2-biopsy': ('Biopsie', None),
    'c2-prognosis': ('Prognose', None),
    'c2-flare-up': ('Opflakkering', None),
    'c2-recurrence': ('Recidief', None),
    'c2-sedative': ('Sedativum', None),
    'c2-anesthetic': ('Anestheticum', None),
    'c2-antibody': ('Antilichaam', None),
    'c2-inflammation': ('Ontsteking', None),
    'c2-airborne': ('Door de lucht overgedragen', None),
    'c2-hereditary': ('Erfelijk', None),
    'c2-congenital': ('Aangeboren', None),
    'c2-dosage': ('Dosering', None),
    'c2-placebo': ('Placebo', None),
    'c2-contraindication': ('Contra-indicatie', None),
    'c2-intravenous': ('Intraveneus', None),
    'c2-suture': ('Hechting', None),
    'c2-incision': ('Incisie', None),
    'c2-donor': ('Donor', None),
    'c2-ultrasound': ('Echografie', None),
    'c2-referral-to-a-specialist': ('Verwijzing', None),
    'c2-inpatient': ('Opgenomen patiënt', None),
    'c2-palliative-care': ('Palliatieve zorg', None),
    'c2-triage': ('Triage', None),
    'c2-convalescence': ('Reconvalescentie', None),
    'c2-immunity': ('Immuniteit', None),
    'c2-pandemic': ('Pandemie', None),
    'c2-pathogen': ('Ziekteverwekker', None),
    'c2-electrolyte': ('Elektrolyt', None),
    'c2-cardiovascular': ('Cardiovasculair', None),
    'c2-respiratory': ('Respiratoir', None),
    'c2-neurological': ('Neurologisch', None),
    'c2-symptomatic': ('Symptomatisch', None),
    'c2-asymptomatic': ('Asymptomatisch', None),
    'c2-prescription-written-order': ('Recept', None),
    'c2-generic-drug': ('Generiek geneesmiddel', None),
    'c2-informed-consent': ('Geïnformeerde toestemming', None),
    'c2-acquittal': ('Vrijspraak', None),
    'c2-conviction-guilty-verdict': ('Veroordeling', None),
    'c2-deposition': ('Beëdigde verklaring', None),
    'c2-accessory-to-a-crime': ('Handlanger', None),
    'c2-arson': ('Brandstichting', None),
    'c2-remand': ('Voorlopige hechtenis', None),
    'c2-burden-of-proof': ('Bewijslast', None),
    'c2-custody-detention': ('Voorarrest', None),
    'c2-defendant': ('Beklaagde', None),
    'c2-plaintiff': ('Eiser', None),
    'c2-embezzlement': ('Verduistering', None),
    'c2-extortion': ('Afpersing', None),
    'c2-felony': ('Zwaar misdrijf', None),
    'c2-misdemeanor': ('Overtreding', None),
    'c2-forgery': ('Vervalsing', None),
    'c2-hearsay': ('Horen-zeggen', None),
    'c2-indictment': ('Tenlastelegging', None),
    'c2-injunction': ('Rechterlijk bevel', None),
    'c2-tribunal': ('Tribunaal', None),
    'c2-libel': ('Smaadschrift', None),
    'c2-slander': ('Laster', None),
    'c2-manslaughter': ('Doodslag', None),
    'c2-parole': ('Voorwaardelijke invrijheidstelling', None),
    'c2-perjury': ('Meineed', None),
    'c2-plea-bargain': ('Schikking (strafvermindering)', None),
    'c2-probation': ('Proeftijd', None),
    'c2-racketeering': ('Afpersingspraktijken', None),
    'c2-ransom': ('Losgeld', None),
    'c2-statute': ('Wet', None),
    'c2-statute-of-limitations': ('Verjaring', None),
    'c2-subpoena': ('Dagvaarding', None),
    'c2-testimony': ('Getuigenis', None),
    'c2-ruling': ('Uitspraak', None),
    'c2-warrant': ('Arrestatiebevel', None),
    'c2-witness-stand': ('Getuigenbank', None),
    'c2-contempt-of-court': ('Minachting van de rechtbank', None),
    'c2-cross-examination': ('Kruisverhoor', None),
    'c2-mistrial': ('Nietig geding', None),
    'c2-sentence-punishment': ('Vonnis', None),
    'c2-to-plead-guilty': ('Schuld bekennen', None),
    'c2-thicket': ('Kreupelhout', None),
    'c2-undergrowth': ('Ondergroei', None),
    'c2-moss': ('Mos', None),
    'c2-lichen': ('Korstmos', None),
    'c2-fern': ('Varen', None),
    'c2-sap': ('Sap', None),
    'c2-bark-of-a-tree': ('Schors', None),
    'c2-sapling': ('Jonge boom', None),
    'c2-canopy-forest': ('Bladerdak', None),
    'c2-grove': ('Bosje', None),
    'c2-meadow': ('Weiland', None),
    'c2-marsh': ('Moeras', None),
    'c2-bog': ('Veen', None),
    'c2-estuary': ('Riviermonding', None),
    'c2-tributary': ('Zijrivier', None),
    'c2-ravine': ('Ravijn', None),
    'c2-gorge': ('Kloof', None),
    'c2-ridge': ('Bergkam', None),
    'c2-summit': ('Bergtop', None),
    'c2-foothills': ('Uitlopers', None),
    'c2-escarpment': ('Steilrand', None),
    'c2-salt-flat': ('Zoutvlakte', None),
    'c2-cove': ('Inham', None),
    'c2-atoll': ('Atol', None),
    'c2-tide-pool': ('Getijdenpoel', None),
    'c2-driftwood': ('Drijfhout', None),
    'c2-pebble': ('Kiezelsteen', None),
    'c2-boulder': ('Zwerfkei', None),
    'c2-sediment': ('Sediment', None),
    'c2-erosion': ('Erosie', None),
    'c2-burrow': ('Hol', None),
    'c2-hive': ('Bijenkorf', None),
    'c2-cocoon': ('Cocon', None),
    'c2-antler': ('Gewei', None),
    'c2-talon': ('Klauw', None),
    'c2-plumage': ('Verenkleed', None),
    'c2-migration-animal': ('Dierentrek', None),
    'c2-hibernation': ('Winterslaap', None),
    'c2-pollination': ('Bestuiving', None),
    'c2-germination': ('Kieming', None),
    'c2-torrential': ('Hevig (van regen)', None),
    'c2-monsoon': ('Moesson', None),
    'c2-sleet': ('Natte sneeuw', None),
    'c2-flurry-snow': ('Sneeuwbui', None),
    'c2-whiteout': ('Sneeuwblindheid', None),
    'c2-black-ice': ('IJzel', None),
    'c2-dew': ('Dauw', None),
    'c2-haze': ('Waas', None),
    'c2-clammy': ('Klef', None),
    'c2-scorcher': ('Snikhete dag', None),
    'c2-sultry': ('Zwoel', None),
    'c2-balmy': ('Zacht (weer)', None),
    'c2-crisp-air': ('Fris', None),
    'c2-gust': ('Windvlaag', None),
    'c2-gale': ('Storm', None),
    'c2-squall': ('Regenbui met wind', None),
    'c2-thunderclap': ('Donderslag', None),
    'c2-lightning-bolt': ('Bliksemschicht', None),
    'c2-cloudburst': ('Wolkbreuk', None),
    'c2-nightfall': ('Invallen van de nacht', None),
    'c2-cold-snap': ('Koudegolf', None),
    'c2-thaw': ('Dooi', None),
    'c2-humidity': ('Vochtigheid', None),
    'c2-barometer': ('Barometer', None),
    'c2-forecast-verb': ('Voorspellen', None),
    'c2-daybreak': ('Dageraad', None),
    'c2-aurora': ('Poollicht', None),
    'c2-twilight': ('Schemering', None),
    'c2-solstice': ('Zonnewende', None),
    'c2-equinox': ('Dag-en-nachtevening', None),
    'c2-arch': ('Boog', None),
    'c2-vault-ceiling': ('Gewelf', None),
    'c2-dome': ('Koepel', None),
    'c2-spire': ('Torenspits', None),
    'c2-buttress': ('Steunbeer', None),
    'c2-pillar': ('Pijler', None),
    'c2-column': ('Zuil', None),
    'c2-beam-structural': ('Balk', None),
    'c2-rafter': ('Dakspant', None),
    'c2-girder': ('Draagbalk', None),
    'c2-keystone': ('Sluitsteen', None),
    'c2-facade-building-front': ('Gevel', None),
    'c2-cornice': ('Kroonlijst', None),
    'c2-gable': ('Puntgevel', None),
    'c2-eaves': ('Dakrand', None),
    'c2-gutter-roof': ('Dakgoot', None),
    'c2-skylight': ('Lichtkoepel', None),
    'c2-balustrade': ('Balustrade', None),
    'c2-parapet': ('Borstwering', None),
    'c2-turret': ('Torentje', None),
    'c2-moat': ('Slotgracht', None),
    'c2-drawbridge': ('Ophaalbrug', None),
    'c2-cloister': ('Kloostergang', None),
    'c2-courtyard': ('Binnenplaats', None),
    'c2-alcove': ('Nis', None),
    'c2-mezzanine': ('Tussenverdieping', None),
    'c2-atrium': ('Atrium', None),
    'c2-mosaic': ('Mozaïek', None),
    'c2-fresco': ('Fresco', None),
    'c2-elevation-drawing': ('Gevelaanzicht', None),
    'c2-partition-wall': ('Scheidingswand', None),
    'c2-cladding': ('Gevelbekleding', None),
    'c2-plumbing-system': ('Sanitair (leidingwerk)', None),
    'c2-ventilation-duct': ('Ventilatiekanaal', None),
    'c2-retrofit': ('Renovatie', None),
    'c2-colander': ('Vergiet', None),
    'c2-ladle': ('Soeplepel', None),
    'c2-whisk': ('Garde', None),
    'c2-grater': ('Rasp', None),
    'c2-tongs': ('Keukentang', None),
    'c2-spatula': ('Spatel', None),
    'c2-cutting-board': ('Snijplank', None),
    'c2-french-press': ('Stempelkan', None),
    'c2-coaster': ('Onderzetter', None),
    'c2-trivet': ('Pannenonderzetter', None),
    'c2-oven-mitt': ('Ovenwant', None),
    'c2-dish-rack': ('Afdruiprek', None),
    'c2-dustpan': ('Stofblik', None),
    'c2-mop': ('Dweil', None),
    'c2-clothespin': ('Wasknijper', None),
    'c2-clothesline': ('Waslijn', None),
    'c2-shoehorn': ('Schoenlepel', None),
    'c2-doormat': ('Deurmat', None),
    'c2-doorknob': ('Deurknop', None),
    'c2-hinge': ('Scharnier', None),
    'c2-latch': ('Klink', None),
    'c2-peephole': ('Kijkgaatje', None),
    'c2-blinds-window': ('Jaloezieën', None),
    'c2-windowsill': ('Vensterbank', None),
    'c2-banister': ('Trapleuning', None),
    'c2-landing-stairs': ('Overloop', None),
    'c2-crawl-space': ('Kruipruimte', None),
    'c2-cellar': ('Kelder', None),
    'c2-pantry': ('Provisiekast', None),
    'c2-utility-room': ('Bijkeuken', None),
    'c2-fuse-box': ('Zekeringkast', None),
    'c2-dimmer-switch': ('Dimmer', None),
    'c2-extension-cord': ('Verlengsnoer', None),
    'c2-power-strip': ('Stekkerdoos', None),
    'c2-carbon-monoxide-alarm': ('Koolmonoxidemelder', None),
    'c2-first-aid-kit': ('EHBO-kit', None),
    'c2-sewing-kit': ('Naaidoos', None),
    'c2-toolbox': ('Gereedschapskist', None),
    'c2-allen-key': ('Inbussleutel', None),
    'c2-pliers': ('Tang', None),
    'c2-wrench': ('Moersleutel', None),
    'c2-tape-measure': ('Rolmaat', None),
    'c2-spirit-level': ('Waterpas', None),
    'c2-drawer-organizer': ('Ladeverdeler', None),
    'c2-bin-liner': ('Vuilniszak', None),
    'c2-to-seethe': ('Koken van woede', None),
    'c2-to-sulk': ('Mokken', None),
    'c2-to-fret': ('Tobben', None),
    'c2-to-brood': ('Piekeren', None),
    'c2-to-wallow-in-self-pity': ('Zwelgen in zelfmedelijden', None),
    'c2-to-gloat-over-a-rival': ('Zich verkneukelen over een rivaal', None),
    'c2-to-savor-the-moment': ('Genieten van het moment', None),
    'c2-to-revel-in': ('Zich vermeien in', None),
    'c2-to-marvel-at': ('Zich verwonderen over', None),
    'c2-to-cringe': ('Ineenkrimpen', None),
    'c2-to-wince': ('Het gezicht vertrekken', None),
    'c2-to-flinch': ('Terugdeinzen', None),
    'c2-to-shudder': ('Huiveren', None),
    'c2-to-quiver': ('Trillen', None),
    'c2-to-swoon': ('Bezwijmen', None),
    'c2-to-pine-for': ('Smachten naar', None),
    'c2-to-long-for': ('Verlangen naar', None),
    'c2-to-crave': ('Snakken naar', None),
    'c2-to-abominate': ('Walgen van', None),
    'c2-to-nurse-a-grievance': ('Een wrok koesteren', None),
    'c2-to-begrudge': ('Misgunnen', None),
    'c2-to-grovel': ('Kruipen', None),
    'c2-to-fawn-over': ('Vleien', None),
    'c2-to-dote-on': ('Vertroetelen', None),
    'c2-to-treasure': ('Koesteren', None),
    'c2-to-put-at-ease': ('Op zijn gemak stellen', None),
    'c2-to-console': ('Troosten', None),
    'c2-to-commiserate': ('Medeleven betuigen', None),
    'c2-to-exasperate': ('Tot wanhoop drijven', None),
    'c2-to-infuriate': ('Woedend maken', None),
    'c2-to-unnerve': ('Van zijn stuk brengen', None),
    'c2-to-mortify': ('Diep vernederen', None),
    'c2-to-captivate': ('Betoveren', None),
    'c2-to-enrapture': ('In vervoering brengen', None),
    'c2-to-disillusion': ('Ontgoochelen', None),
    'c2-to-mollify': ('Kalmeren', None),
    'c2-to-embolden': ('Moed geven', None),
    'c2-to-dishearten': ('Ontmoedigen', None),
    'c2-to-rankle': ('Blijven knagen', None),
    'c2-to-smolder': ('Smeulen', None),
    'c2-numbness': ('Gevoelloosheid', None),
    'c2-tingling': ('Tinteling', None),
    'c2-cramp': ('Kramp', None),
    'c2-twinge': ('Pijnsteek', None),
    'c2-throbbing': ('Bonzend', None),
    'c2-dizziness': ('Duizeligheid', None),
    'c2-lightheaded': ('Licht in het hoofd', None),
    'c2-vertigo': ('Vertigo', None),
    'c2-queasy': ('Misselijk', None),
    'c2-lethargy': ('Lethargie', None),
    'c2-fatigue': ('Vermoeidheid', None),
    'c2-stamina': ('Uithoudingsvermogen', None),
    'c2-reflex': ('Reflex', None),
    'c2-flinch-noun': ('Schrikreactie', None),
    'c2-pins-and-needles': ('Slapend gevoel', None),
    'c2-shiver': ('Rilling', None),
    'c2-hot-flush': ('Opvlieger', None),
    'c2-blush': ('Blos', None),
    'c2-yawn': ('Geeuw', None),
    'c2-hiccup': ('Hik', None),
    'c2-sneeze': ('Nies', None),
    'c2-itch': ('Jeuk', None),
    'c2-bruise': ('Blauwe plek', None),
    'c2-blister': ('Blaar', None),
    'c2-pulled-muscle': ('Spierverrekking', None),
    'c2-stiffness': ('Stijfheid', None),
    'c2-restlessness': ('Rusteloosheid', None),
    'c2-daydream': ('Dagdroom', None),
    'c2-deja-vu': ('Déjà vu', None),
    'c2-hunch': ('Voorgevoel', None),
    'c2-gut-feeling': ('Onderbuikgevoel', None),
    'c2-brain-fog': ('Mentale mist', None),
    'c2-second-wind': ('Tweede adem', None),
    'c2-adrenaline-rush': ('Adrenalinestoot', None),
    'c2-motion-sickness': ('Reisziekte', None),
    'c2-camaraderie': ('Kameraadschap', None),
    'c2-affinity-between-people': ('Affiniteit', None),
    'c2-clique': ('Kliek', None),
    'c2-entourage': ('Gevolg', None),
    'c2-etiquette': ('Etiquette', None),
    'c2-faux-pas': ('Misstap', None),
    'c2-gossip': ('Roddel', None),
    'c2-grudge': ('Wrok', None),
    'c2-chain-of-command': ('Bevelstructuur', None),
    'c2-nepotism': ('Vriendjespolitiek', None),
    'c2-ostracism': ('Sociale uitsluiting', None),
    'c2-groupthink': ('Groepsdenken', None),
    'c2-pecking-order': ('Pikorde', None),
    'c2-rivalry': ('Rivaliteit', None),
    'c2-solidarity': ('Solidariteit', None),
    'c2-snub': ('Bruuske afwijzing', None),
    'c2-taboo': ('Taboe', None),
    'c2-flattery': ('Vleierij', None),
    'c2-backhanded-compliment': ('Vergiftigd compliment', None),
    'c2-cold-shoulder': ('Koude schouder', None),
    'c2-small-circle-inner-circle': ('Naaste kring', None),
    'c2-interloper': ('Indringer', None),
    'c2-old-hand': ('Ervaren rot', None),
    'c2-wingman': ('Secondant', None),
    'c2-freeloader': ('Klaploper', None),
    'c2-busybody': ('Bemoeial', None),
    'c2-killjoy': ('Spelbreker', None),
    'c2-show-off': ('Opschepper', None),
    'c2-pushover': ('Doetje', None),
    'c2-self-starter': ('Initiatiefnemer', None),
    'c2-to-mingle': ('Zich mengen onder de mensen', None),
    'c2-to-schmooze': ('Slijmen (netwerken)', None),
    'c2-to-shun': ('Mijden', None),
    'c2-to-patronize': ('Neerbuigend behandelen', None),
    'c2-to-reconcile': ('Zich verzoenen', None),
    'c2-to-estrange': ('Vervreemden', None),
    'c2-to-confide-in': ('Zich toevertrouwen aan', None),
    'c2-to-hobnob': ('Verkeren met voorname kringen', None),
    'c2-to-rub-shoulders-with': ('Omgaan met', None),
    'c2-to-fall-out-with': ('Ruzie krijgen met', None),
    'c2-foil-character': ('Contrastfiguur', None),
    'c2-anti-hero': ('Antiheld', None),
    'c2-narrator': ('Verteller', None),
    'c2-macguffin': ('MacGuffin', None),
    'c2-red-herring': ('Afleidingsmanoeuvre', None),
    'c2-motif': ('Motief', None),
    'c2-frame-narrative': ('Raamvertelling', None),
    'c2-denouement': ('Ontknoping', None),
    'c2-satire': ('Satire', None),
    'c2-parody': ('Parodie', None),
    'c2-allegory': ('Allegorie', None),
    'c2-memoir': ('Memoires', None),
    'c2-anthology': ('Bloemlezing', None),
    'c2-manuscript': ('Manuscript', None),
    'c2-prose': ('Proza', None),
    'c2-couplet': ('Rijmpaar', None),
    'c2-stanza': ('Strofe', None),
    'c2-sonnet': ('Sonnet', None),
    'c2-alliteration': ('Alliteratie', None),
    'c2-meter-poetry': ('Versmaat', None),
    'c2-aesthetic': ('Esthetiek', None),
    'c2-avant-garde': ('Avant-garde', None),
    'c2-baroque': ('Barok', None),
    'c2-impressionism': ('Impressionisme', None),
    'c2-surrealism': ('Surrealisme', None),
    'c2-still-life': ('Stilleven', None),
    'c2-charcoal-drawing': ('Houtskooltekening', None),
    'c2-etching': ('Ets', None),
    'c2-bust-sculpture': ('Buste', None),
    'c2-chisel': ('Beitel', None),
    'c2-easel': ('Schildersezel', None),
    'c2-palette': ('Palet', None),
    'c2-overture': ('Ouverture', None),
    'c2-aria': ('Aria', None),
    'c2-encore': ('Toegift', None),
    'c2-bandwidth': ('Bandbreedte', None),
    'c2-jitter': ('Jitter', None),
    'c2-throughput': ('Doorvoercapaciteit', None),
    'c2-hashing': ('Hashing', None),
    'c2-intrusion-detection': ('Inbraakdetectie', None),
    'c2-vulnerability-security': ('Kwetsbaarheid', None),
    'c2-hotfix': ('Noodpatch', None),
    'c2-backlog': ('Achterstand', None),
    'c2-rollout': ('Uitrol', None),
    'c2-rollback': ('Terugdraaien', None),
    'c2-uptime': ('Bedrijfstijd', None),
    'c2-redundancy-backup': ('Redundantie', None),
    'c2-load-balancing': ('Belastingverdeling', None),
    'c2-legacy-system': ('Verouderd systeem', None),
    'c2-copyleft': ('Copyleft', None),
    'c2-proprietary': ('Propriëtair', None),
    'c2-interoperability': ('Interoperabiliteit', None),
    'c2-passkey': ('Toegangssleutel', None),
    'c2-social-engineering': ('Sociale manipulatie', None),
    'c2-data-breach': ('Datalek', None),
    'c2-cache': ('Cache', None),
    'c2-query': ('Zoekopdracht', None),
    'c2-metadata': ('Metadata', None),
    'c2-placeholder': ('Plaatshouder', None),
    'c2-workaround': ('Noodoplossing', None),
    'c2-bottleneck': ('Knelpunt', None),
    'c2-edge-case': ('Randgeval', None),
    'c2-deprecated': ('Afgeraden (verouderd)', None),
    'c2-sandbox': ('Testomgeving', None),
    'c2-telemetry': ('Telemetrie', None),
    'c2-algorithmic-bias': ('Algoritmische vertekening', None),
    'c2-overfitting': ('Overfitting', None),
    'c2-large-language-model': ('Groot taalmodel', None),
    'c2-quantum-computing': ('Kwantumcomputing', None),
    'c2-semiconductor': ('Halfgeleider', None),
    'c2-working-capital': ('Werkkapitaal', None),
    'c2-solvency': ('Solvabiliteit', None),
    'c2-insolvency': ('Insolventie', None),
    'c2-receivership': ('Curatele', None),
    'c2-leverage-finance': ('Hefboomwerking', None),
    'c2-hedge-finance': ('Afdekking', None),
    'c2-yield-finance': ('Rendement', None),
    'c2-share-buyback': ('Aandeleninkoop', None),
    'c2-equity-ownership': ('Eigen vermogen', None),
    'c2-treasury-bill': ('Schatkistpapier', None),
    'c2-asset-allocation': ('Vermogensspreiding', None),
    'c2-volatility': ('Volatiliteit', None),
    'c2-bull-market': ('Stierenmarkt', None),
    'c2-bear-market': ('Berenmarkt', None),
    'c2-downturn': ('Neergang', None),
    'c2-stagflation': ('Stagflatie', None),
    'c2-deflation': ('Deflatie', None),
    'c2-interest-rate-hike': ('Renteverhoging', None),
    'c2-fiscal-policy': ('Begrotingsbeleid', None),
    'c2-monetary-policy': ('Monetair beleid', None),
    'c2-subsidy': ('Subsidie', None),
    'c2-trade-quota': ('Handelsquotum', None),
    'c2-embargo': ('Embargo', None),
    'c2-belt-tightening': ('De broekriem aanhalen', None),
    'c2-bailout': ('Reddingsoperatie', None),
    'c2-windfall': ('Meevaller', None),
    'c2-nest-egg': ('Appeltje voor de dorst', None),
    'c2-slush-fund': ('Geheime kas', None),
    'c2-kickback': ('Steekpenning', None),
    'c2-money-laundering': ('Geldwitwassen', None),
    'c2-tax-evasion': ('Belastingontduiking', None),
    'c2-tax-loophole': ('Belastingmaas', None),
    'c2-underwriter': ('Garantsteller', None),
    'c2-sinking-fund': ('Aflossingsfonds', None),
    'c2-arbitrage': ('Arbitrage', None),
    'c2-freight': ('Vracht', None),
    'c2-cargo-hold': ('Laadruim', None),
    'c2-consignment': ('Zending', None),
    'c2-customs-clearance': ('Douaneafhandeling', None),
    'c2-red-eye-flight': ('Nachtvlucht', None),
    'c2-turbulence': ('Turbulentie', None),
    'c2-taxiing': ('Taxiën', None),
    'c2-cockpit': ('Cockpit', None),
    'c2-overhead-compartment': ('Bagagerek', None),
    'c2-aisle-seat': ('Gangpadstoel', None),
    'c2-boarding-pass': ('Instapkaart', None),
    'c2-baggage-carousel': ('Bagageband', None),
    'c2-jet-bridge': ('Slurf', None),
    'c2-tailgating-driving': ('Bumperkleven', None),
    'c2-gridlock': ('Verkeersinfarct', None),
    'c2-diversion-route': ('Omleiding', None),
    'c2-interchange-highway': ('Knooppunt', None),
    'c2-overpass': ('Viaduct', None),
    'c2-underpass': ('Onderdoorgang', None),
    'c2-toll-booth': ('Tolhuisje', None),
    'c2-hard-shoulder': ('Vluchtstrook', None),
    'c2-speed-bump': ('Verkeersdrempel', None),
    'c2-blind-spot': ('Dode hoek', None),
    'c2-hazard-lights': ('Alarmlichten', None),
    'c2-windshield-wiper': ('Ruitenwisser', None),
    'c2-clutch-car': ('Koppeling', None),
    'c2-handbrake': ('Handrem', None),
    'c2-odometer': ('Kilometerteller', None),
    'c2-tow-truck': ('Sleepwagen', None),
    'c2-commute-noun': ('Woon-werkverkeer', None),
    'c2-numerator': ('Teller', None),
    'c2-denominator': ('Noemer', None),
    'c2-exponent': ('Exponent', None),
    'c2-square-root': ('Vierkantswortel', None),
    'c2-decimal-point': ('Komma (decimaalteken)', None),
    'c2-remainder': ('Rest', None),
    'c2-prime-number': ('Priemgetal', None),
    'c2-integer': ('Geheel getal', None),
    'c2-quotient': ('Quotiënt', None),
    'c2-percentile': ('Percentiel', None),
    'c2-mean-average': ('Gemiddelde', None),
    'c2-median': ('Mediaan', None),
    'c2-outlier': ('Uitschieter', None),
    'c2-standard-deviation': ('Standaardafwijking', None),
    'c2-variance': ('Variantie', None),
    'c2-margin-of-error': ('Foutmarge', None),
    'c2-sample-size': ('Steekproefomvang', None),
    'c2-exponential-growth': ('Exponentiële groei', None),
    'c2-order-of-magnitude': ('Orde van grootte', None),
    'c2-rounding': ('Afronding', None),
    'c2-percentage-point': ('Procentpunt', None),
    'c2-threefold': ('Drievoudig', None),
    'c2-a-dozen': ('Een dozijn', None),
    'c2-round-number': ('Rond getal', None),
    'c2-odds-probability': ('Kansverhouding', None),
    'c2-inseam': ('Binnenbeenlengte', None),
    'c2-dart-sewing': ('Figuurnaad', None),
    'c2-lapel': ('Revers', None),
    'c2-cuff': ('Manchet', None),
    'c2-cufflinks': ('Manchetknopen', None),
    'c2-gusset': ('Geer', None),
    'c2-pleat': ('Plooi', None),
    'c2-tailored': ('Op maat gemaakt', None),
    'c2-bespoke': ('Op maat gesneden (naar wens)', None),
    'c2-off-the-rack': ('Confectie', None),
    'c2-threadbare': ('Kaal versleten', None),
    'c2-frayed': ('Uitgerafeld', None),
    'c2-creased': ('Gekreukt', None),
    'c2-dapper': ('Piekfijn', None),
    'c2-disheveled': ('Verfomfaaid', None),
    'c2-scruffy': ('Sjofel', None),
    'c2-garish': ('Opzichtig', None),
    'c2-understated': ('Ingetogen', None),
    'c2-flattering-clothes': ('Flatterend', None),
    'c2-baggy': ('Zakkerig', None),
    'c2-snug': ('Nauwsluitend', None),
    'c2-stubble': ('Stoppelbaard', None),
    'c2-freckles': ('Sproeten', None),
    'c2-dimple': ('Kuiltje', None),
    "c2-crow-s-feet": ('Kraaienpootjes', None),
    'c2-complexion': ('Teint', None),
    'c2-gaunt': ('Uitgemergeld', None),
    'c2-stocky': ('Gedrongen', None),
    'c2-lanky': ('Slungelig', None),
    'c2-poised': ('Beheerst', None),
}
